.circleci/config.yml
The DISPLAY environment variable needs to set to ':99.0' before xvfb starts because xvfb uses that variable
=> Fix testing fork prs

spec/api-native-image-spec.js, spec/package.json
=> Add Chai library for tests

docs-translations/README.md
A followup to #11039 
project, not projects.
=> fix link to crowdin

docs/tutorial/updates.md
@MarshallOfSound did a thing and is just sending around DMs, but I think this deserves to be in the official docs 🏷
=> docs: Document Nucleus

README.md
Small changes to standardize formatting.
=> Standardize README.md headers

spec/api-app-spec.js, spec/api-auto-updater-spec.js, spec/api-browser-window-spec.js, spec/api-clipboard-spec.js, spec/api-crash-reporter-spec.js, spec/api-desktop-capturer-spec.js, spec/api-global-shortcut-spec.js, spec/api-native-image-spec.js, spec/api-process-spec.js, spec/api-protocol-spec.js, spec/api-screen-spec.js, spec/api-session-spec.js, spec/api-shell-spec.js, spec/api-system-preferences-spec.js, spec/asar-spec.js, spec/chromium-spec.js, spec/modules-spec.js, spec/node-spec.js, spec/webview-spec.js
I guess marking them as passed of ignoring them at all is not the best idea =)
/cc @codebytere
=> Explicitly skip tests that should be skipped

docs/development/source-code-directory-structure.md
Just copying some wisdom from @deepak1556 and putting it into the docs. :)
=> document chromium_src directory

docs/development/upgrading-chrome.md
This guide proposes an update to the current set of steps for updating Chromium within Electron. 
Please feel free to leave feedback and propose more changes!
/cc @cifratila @alexeykuzmin @ckerr @alespergl
=> Proposed update to Chromium checklist

CODE_OF_CONDUCT.md, docs-translations/README.md
=> fix word docs-translation/README.md, CODE_OF_CONDUCT.md

brightray/browser/inspectable_web_contents_impl.cc, brightray/browser/url_request_context_getter.cc, brightray/browser/url_request_context_getter.h
Progress on fixing compilation errors when building against the brightray target.
/cc @ckerr @alexeykuzmin @gavignus
=> Fix brightray target compilation errors

docs/api/download-item.md
=> fix doc in download-item

docs/development/upgrading-chromium.md, docs/development/upgrading-crashpad.md, docs/development/upgrading-node.md
Cherry-pick over from @ckerr's branch https://github.com/electron/electron/pull/11228 that i may or may not have accidentally rebased 🙈.
=> Upgrading docs

atom/app/atom_login_helper.mm, atom/app/resources/mac/loginhelper-Info.plist, atom/browser/browser_mac.mm, atom/common/platform_util.h, atom/common/platform_util_mac.mm, docs/api/app.md, docs/tutorial/mac-app-store-submission-guide.md, electron.gyp, filenames.gypi, spec/api-app-spec.js
Land #10856 again (which was reverted in #11140)
Changes are cherry-picked from original PR to master with test fix commit https://github.com/electron/electron/commit/d9481430dfa07c1028285d5aee56f55ed6f8dabf.
=> Re-land MAS login helper (w/ regression fix)

atom/common/api/atom_api_native_image.cc, spec/api-native-image-spec.js
Fixes #11245.
_Tests are simply enabled, they still have to be fixed._
=> Enable nativeImage module addRepresentation() tests

docs/api/structures/upload-file-system.md, docs/api/structures/upload-file.md
Reported by a translator in Crowdin: https://crowdin.com/translate/electron/150/en-uk#11450
=> fix typos in structures

atom/browser/api/event_subscriber.cc, atom/browser/atom_browser_client.cc, atom/browser/native_window_views.cc, atom/browser/ui/win/taskbar_host.cc, atom/browser/web_view_guest_delegate.cc, atom/browser/web_view_guest_delegate.h, brightray/browser/media/media_capture_devices_dispatcher.cc
This pulls and tests https://github.com/electron/libchromiumcontent/pull/403
Refs https://github.com/electron/libchromiumcontent/issues/359
/cc @alexeykuzmin @alespergl @zcbenz @ckerr
=> Build with dchecks disabled on subset of targets

Jenkinsfile
Added timeout to Jenkins CI builds to abort if they take longer than 1 hour.
=> Add 1 hour timeout to Jenkins CI

docs/tutorial/versioning.md
The bump of docs linter module is breaking our CI
=> Fix docs linting error

atom/browser/api/atom_api_app.cc, atom/browser/api/atom_api_app.h, atom/browser/atom_browser_client.cc, brightray/browser/browser_main_parts.cc, brightray/browser/media/media_capture_devices_dispatcher.cc
Fixes https://github.com/electron/electron/issues/11319 , https://github.com/electron/electron/issues/11318
=> Fix: Re-enable some dchecks

README.md
Available here: electronpl.github.io
=> Added Polish Electron Community

atom/browser/api/atom_api_system_preferences.cc, atom/browser/api/atom_api_system_preferences.h, atom/browser/api/atom_api_system_preferences_mac.mm, docs/api/system-preferences.md, spec/api-system-preferences-spec.js
Reverts electron/electron#11395
cc @codebytere, @ckerr
=> Revert "Add systemPreferences.registerDefaults()"

lib/browser/api/menu.js, spec/api-menu-spec.js
Reverts electron/electron#11385
cc @felixrieseberg, @ckerr
=> Revert "fix: Fix `menu.popup()` bugs"

lib/browser/api/menu.js, spec/api-menu-spec.js
This is exactly the same as #11385, but rebased on top of master. It didn't hang for me, so I'm reopening this PR to see how CI behaves now.
=> fix: Menu bugs (take two)

atom/browser/api/atom_api_system_preferences.cc, atom/browser/api/atom_api_system_preferences.h, atom/browser/api/atom_api_system_preferences_mac.mm, docs/api/system-preferences.md, spec/api-system-preferences-spec.js
Fixed hanging issues in previous PR.
/cc @ckerr @alexeykuzmin
=> [WIP] add back systemPreferences.registerDefaults()

.circleci/config.yml, script/bump-version.py, script/ci-release-build.js, script/merge-release.js, script/prepare-release.js, script/release.js, script/upload-to-github.js, script/upload.py
1. Update libcc to latest from electron-1-7-x
2. Add release scripts to 1-7-x branch.
=> Preparation for 1.7.10 release

docs/development/releasing.md
=> Update release process for API invoked release builds

docs/api/auto-updater.md
Missing documentation on the issue https://github.com/electron/electron/issues/10903
=> Updated auto-updater.md

docs/development/upgrading-node.md
Add a few sentences to the beginning of the node upgrade doc to make more clear how the initial branch is made. 
/cc @alexeykuzmin
=> Update branching steps in upgrading-node.md

atom/browser/node_debugger.cc
After figuring this out I found out this code change is already in master so this just needs to go to the 1-8-x branch 👍 
Fixes #11430
=> Fix inspect-brk in 1.8.x

spec/node-spec.js
This ports https://github.com/electron/electron/pull/11526 to master branch.
Note that the patch on Node is slightly different, I also patched the code in `src/node_http2.cc`.
=> master: Fix crash when using crypto module

docs/tutorial/keyboard-shortcuts.md
Issue related [electronjs.org/issues/983](https://github.com/electron/electronjs.org/issues/983)
=> Doc update: New path for web-contents.md

CONTRIBUTING.md
=> Update CONTRIBUTING.md with link to development docs

atom/browser/native_window_views.cc
Fixes #10678, see the discussion at the issue comments
=> Remove WS_EX_COMPOSITED style from window (master)

.circleci/config.yml, .gitignore, atom/common/native_mate_converters/net_converter.cc, brightray/brightray.gyp, brightray/brightray.gypi, docs/tutorial/supported-platforms.md, electron.gyp, script/create-dist.py, script/lib/config.py, toolchain.gypi
This PR enables mips64el build for the 1.8.x, the build is ready but we have crashes when running.
=> Enable mips64el CI job

script/prepare-release.js, script/release.js, script/upload.py
This PR allows us to run multiple releases at the same time if needed.
=> Parallel releases for 1-7-x

script/prepare-release.js, script/release.js, script/upload.py
This PR allows us to run multiple releases at the same time if needed.
=> Parallel releases 1-8-x

script/prepare-release.js, script/release.js, script/upload.py
This PR allows us to run multiple releases at the same time if needed.
=> Allow multiple releases to run at once

package.json, script/ci-release-build.js, script/merge-release.js, script/prepare-release.js, script/release.js, script/upload.py
This PR allows us to run multiple releases at the same time if needed.
=> Allow multiple releases to run at once for 1-6-x

atom/browser/browser.cc, atom/browser/browser.h, atom/browser/browser_win.cc, brightray/browser/win/windows_toast_notification.cc, brightray/common/application_info.cc, brightray/common/application_info.h, brightray/common/application_info_win.cc, brightray/filenames.gypi
=> Fix implicit setting of appUserModelId

script/ci-release-build.js, script/prepare-release.js, script/publish-to-npm.js, script/release.js
=> Backport release updates to 1-8-x

CONTRIBUTING.md, docs/development/coding-style.md, docs/development/issues.md, docs/development/pull-requests.md
This PR adds more information around contributing to Electron ✨ 
Related: https://github.com/electron/electron/pull/11888
=> enhance documentation around contributing to electron

atom/browser/api/atom_api_web_contents.cc, atom/browser/api/atom_api_web_contents.h, atom/browser/osr/osr_output_device.cc, atom/browser/osr/osr_output_device.h, atom/browser/osr/osr_render_widget_host_view.cc, atom/browser/osr/osr_render_widget_host_view.h, atom/browser/osr/osr_web_contents_view.cc, atom/browser/osr/osr_web_contents_view.h
This backports #11728 to 1.7.x
=> Improve OSR API (1-7-x)

docs/api/dialog.md
=> Mark securityScopedBookmarks as optional and a boolean

docs/api/app.md, docs/api/sandbox-option.md, docs/api/session.md, docs/api/web-contents.md, docs/api/web-frame.md, docs/development/upgrading-crashpad.md, docs/development/upgrading-node.md, docs/tutorial/installation.md, docs/tutorial/security.md
=> Propose fix some typos

atom/renderer/api/atom_api_web_frame.cc, atom/renderer/api/atom_api_web_frame.h, docs/api/web-frame.md, spec/api-web-frame-spec.js
This reverts commit 181169b74313e280d1cd649f1e2054bfd7029e9c per discussion
/cc @MarshallOfSound @deepak1556
=> Revert "Merge pull request #11737 from kwonoj/feat-cache-capacity"

atom/browser/native_window_views.cc
Fixes #11849
Master seems to be unaffected as far as I can tell from my testing.
=> Re-add WS_EX_COMPOSITED when GPU acceleration is enabled (1-8-x)

spec/api-session-spec.js
Adds a test to https://github.com/electron/electron/pull/11804 as requested
=> Add 'download from custom protocol' test

Dockerfile.arm64, Dockerfile.armv7, atom/browser/ui/file_dialog_gtk.cc, atom/browser/ui/message_box_gtk.cc, atom/browser/ui/views/menu_bar.cc, brightray/filename_rules.gypi, docs/development/build-instructions-linux.md, docs/tutorial/snapcraft.md, script/cibuild
=> Fix GTK+ 3 deprecations

atom/browser/api/atom_api_menu.cc, atom/browser/api/atom_api_menu.h, atom/browser/api/event_emitter.h, lib/browser/api/menu.js, spec/api-menu-spec.js
This PR fixes the memory leak when using menus, closes https://github.com/electron/electron/issues/9823.
=> Fix the cyclic reference in menu delegate

script/release.js
During the 2.0.0-beta.1 release I found a couple issues with the release script.
This provides the following fixes:
1. Remove logic to delete release branch because that branch is no longer used.
2. Fix `--validateRelease` to not  verify shasums when release is in draft mode since the shasums don't exist at that point.
=> Fixes from running 2.0.0-beta.1 release

script/release.js
Backport of #12013 for 2-0-x
This provides the following fixes:
1. Remove logic to delete release branch because that branch is no longer used.
2. Fix --validateRelease to not verifyShasums when release is in draft mode.
(cherry picked from commit fa6510a90c800703e43224b8fc01e0006b2c0114)
=> Backport fixes from running 2.0.0-beta.1 release to 2-0-x

docs/tutorial/security.md
=> Quick typo

docs/api/shell.md, docs/tutorial/desktop-environment-integration.md
Related https://github.com/electron/electronjs.org/issues/1161
=> [Docs] Fix url to unity-launcher

atom/browser/api/atom_api_protocol.h, atom/browser/net/atom_url_request.cc, atom/browser/net/atom_url_request_job_factory.cc, atom/browser/net/atom_url_request_job_factory.h, spec/api-session-spec.js
=> Fix protocol filtering of net.request for 1.8.

docs/tutorial/application-packaging.md
=> Fix typo found during the Spanish translation

README.md, docs-translations/README.md, docs/styleguide.md
See https://github.com/electron/i18n/issues/255
=> update references to renamed i18n repo

docs/tutorial/planned-breaking-changes.md
This PR outlines the breaking changes for 3.0, cleaning up the changes that have already been removed in 2.0 and adding the new ones.
/cc @ckerr
=> Outline planned breaking changes for 3.0

spec/api-app-spec.js, spec/fixtures/api/singleton/main.js
Backports https://github.com/electron/electron/pull/12139 to `2-0-x`
/cc @alexeykuzmin @ckerr
=> Backport flake fixes (2-0-x)

atom/browser/ui/cocoa/atom_menu_controller.mm
Fix context menu click callback
(cherry picked from commit cc608a3fb0cc6eb5f4d575ab2fdae4ddb888f41f)
Fixes #11818.
/cc @codebytere
=> [2.0.x] Merge pull request #12043 from kaylieEB/fix-menu-item

atom/browser/api/atom_api_menu_views.cc
Backport of https://github.com/electron/electron/pull/12180
=> Fix popup menu position (2.0)

Jenkinsfile.arm64, spec/static/index.html
This PR updates 2-0-x to the latest libchromiumcontent for 2-0-x
=> Update to latest libchromiumcontent for 2-0-x

atom/browser/atom_browser_client.cc, atom/browser/atom_browser_client.h, atom/common/api/atom_bindings.cc, common.gypi, electron.gyp
Updating to Node `v9.7.0`.
Todo:
/cc @alexeykuzmin
=> Update to node v9.7.0

atom/browser/api/atom_api_menu_views.cc
Backport of https://github.com/electron/electron/pull/12180
=> Fix popup menu position (1.8)

package.json
Brings up changes from:
- electron/libchromiumcontent#456
- electron/libchromiumcontent#475
/cc @ckerr
=> Update to the latest libcc from electron-1-7-x

.github/config.yml
what it says on the tin
/cc @MarshallOfSound
=> Add config for trop (backporting bot)

spec/chromium-spec.js
Fixes https://github.com/electron/electron/issues/12173
=> spec: isolate sw file scheme spec storage with temp partition

atom/browser/api/atom_api_web_contents.cc, atom/browser/api/atom_api_web_contents.h, atom/browser/api/event.cc, atom/browser/api/event.h, atom/browser/api/event_emitter.cc, atom/browser/api/event_emitter.h, atom/common/api/api_messages.h, atom/common/api/remote_callback_freer.cc, atom/common/api/remote_object_freer.cc, atom/renderer/api/atom_api_renderer_ipc.cc, atom/renderer/api/atom_api_web_frame.cc, atom/renderer/atom_render_frame_observer.cc, atom/renderer/atom_render_frame_observer.h, atom/renderer/atom_render_view_observer.cc, atom/renderer/atom_render_view_observer.h, atom/renderer/atom_renderer_client.cc, atom/renderer/atom_sandboxed_renderer_client.cc, atom/renderer/renderer_client_base.cc
Backports https://github.com/electron/electron/pull/12190
/cc @MarshallOfSound
=> browser: fix preload loading twice in 2.x

spec/api-crash-reporter-spec.js
=> add missing report.length > 1 assertion

spec/node-spec.js
=> fix remote setInterval flake

spec/node-spec.js
=> fix remote setInterval flake (1.8.x)

spec/node-spec.js
=> fix remote setInterval flake (2.0.x)

atom/browser/api/atom_api_web_contents.cc, atom/browser/api/atom_api_web_contents.h, atom/browser/web_contents_preferences.cc, atom/browser/web_contents_preferences.h, lib/browser/guest-view-manager.js, lib/browser/guest-window-manager.js, lib/renderer/security-warnings.js, spec/api-browser-window-spec.js, spec/chromium-spec.js, spec/fixtures/pages/window-opener-no-web-view-tag.html, spec/fixtures/pages/window-opener-web-view.html
Ensure that the webview `options` object has appropriate default values.
Details at https://www.electronjs.org/blog/webview-fix
=> Set appropriate defaults for webview options

atom/browser/api/atom_api_web_contents.cc, atom/browser/api/atom_api_web_contents.h, atom/browser/web_contents_preferences.cc, atom/browser/web_contents_preferences.h, lib/browser/guest-view-manager.js, lib/browser/guest-window-manager.js, spec/api-browser-window-spec.js, spec/chromium-spec.js, spec/fixtures/pages/window-opener-no-web-view-tag.html, spec/fixtures/pages/window-opener-web-view.html
=> Backport (1-7-x) - Set appropriate defaults for webview options

lib/browser/api/navigation-controller.js
Reverts electron/electron#12193
Some things broke after this PR, different fix will come soon 👍
=> Revert "Fixes electron/electron#12147"

docs/tutorial/first-app.md
path and url needed to be require'd
=> Update example code

.circleci/config.yml, Dockerfile, Dockerfile.arm64v8, Dockerfile.circleci, Jenkinsfile.arm64
Backports https://github.com/electron/electron/pull/12351 to `1-8-x`
/cc @jkleinsc
=> Update CI to use Node 8

.github/CODEOWNERS
=> now we call ourselves electrocats

docs/api/browser-window.md
=> Fix documentation tyop

.gitignore, docs/api/environment-variables.md, npm/index.js, npm/install.js
For instance from `~/projects/electron/out/D`
Fixes #12413
=> Provide an easy way to use a local build of Electron

docs/api/browser-window.md
The linter was unable to get `paused` as a possible value for `mode`.
Fixes #10775
=> update doc for setProgressBar

lib/browser/api/menu.js
=> Backport (1-8-x) - Fix disabling accelerators

atom/browser/ui/file_dialog_mac.mm
=> Backport #12404 to 1-8-x

atom/browser/api/atom_api_web_contents.cc, atom/common/api/atom_api_native_image.cc
Update libcc submodule reference to pick up the new electron-2-0-x changes, e.g. the 2D canvas patch
Haven't PRed one of these before, so here are the steps I used:
```sh
git checkout 2-0-x
git pull
cd vendor/libchromiumcontent
git fetch
git checkout electron-2-0-x
cd ../..
git add vendor
git commit
```
=> update libcc submodule reference to electron-2-0-x

docs/glossary.md
From today's weekly meeting discussion.
=> add IDL and Mojo to glossary

script/prepare-release.js
This fixes an error that was occuring on the autorelease when pushing the new release.
=> Fix pushRelease for autorelease

atom/browser/api/atom_api_browser_window.cc
=> Focus webview directly in offscreen mode

.circleci/config.yml
=> Use CircleCI for Mac builds for 1-8-x

filenames.gypi, lib/renderer/init.js, lib/renderer/web-frame-init.js, lib/sandboxed_renderer/init.js, spec/api-web-contents-spec.js
=> Enable WebFrame method forwarding in sandboxed renderers

docs/api/app.md, docs/api/frameless-window.md, docs/api/in-app-purchase.md, docs/api/synopsis.md, docs/api/touch-bar-button.md, docs/api/touch-bar-color-picker.md, docs/api/touch-bar-group.md, docs/api/touch-bar-label.md, docs/api/touch-bar-popover.md, docs/api/touch-bar-scrubber.md, docs/api/touch-bar-segmented-control.md, docs/api/touch-bar-slider.md, docs/api/touch-bar-spacer.md, docs/api/touch-bar.md, docs/development/README.md
=> [Docs] Fix dead urls

docs/api/browser-window.md, docs/api/webview-tag.md
Fix broken url for 'blink-feature-string'
=> [doc] Fix broken url

.github/ISSUE_TEMPLATE.md
=> Add last known working electron version

docs/development/coding-style.md
Corrected CamelCase to PascalCase and 
mixedCase to camelCase
=> Corrected the name of Capitalization Styles

package.json
=> Add missing chai-as-promised dep

docs/api/web-contents.md
=> Docs: Add missing webContents events

spec/api-browser-window-spec.js, spec/webview-spec.js
- Rewrite BrowserWindow.addDevToolsExtension tests
- Slightly rewrite one of the \<webview\> tests
=> Update some tests

atom/common/crash_reporter/crash_reporter_linux.cc, atom/common/crash_reporter/linux/crash_dump_handler.cc, atom/common/crash_reporter/linux/crash_dump_handler.h
=> refactor: breakpad #includes to work with GN and GYP

atom/common/native_mate_converters/string16_converter.h
Prepare for https://github.com/electron/native-mate/pull/34
=> Don't use native_mate/compat.h macros

atom/browser/native_window.cc
=> Only expand maximum size constraint if there was a constraint originally

atom/browser/api/atom_api_view.h, atom/browser/api/atom_api_web_contents_view.cc, atom/browser/api/atom_api_web_contents_view.h, atom/browser/atom_browser_main_parts.cc, spec/api-view-spec.js, spec/api-web-contents-view-spec.js
Fix a few crashes when using `WebContentsView`, and add some tests.
=> Fix crashes and add tests for View API

package-lock.json, package.json, spec/package.json
Fix vulnerable packages exposed with `npm audit` both in the top-level `package.json` and in the `spec`-level `package.json`.
/cc @zeke @ckerr
=> Fix vulnerabilities both top-level and in spec

script/upload-symbols.py, script/upload.py
This PR resolves #10105.
The symbol upload script which worked only for windows previously, now uploads other platform symbols also.
=> Update upload symbols script for posix

docs/api/remote.md
=> docs: fix a typo in remote.md

DEPS
Needed for the build instructions in #13005 to work
=> Roll libchromiumcontent

script/tls.py
Yeah so I saw this twice today and it bugged me 😆
=> chore: add space in TLS version check log

atom/browser/api/atom_api_web_contents.cc, atom/browser/common_web_contents_delegate.h, atom/browser/common_web_contents_delegate_views.cc, atom/browser/ui/autofill_popup.cc, atom/browser/ui/autofill_popup.h
This PR fixes the positioning issues and the OSR crash mentioned in #12528
=> fix: autofill popups spawned from webviews

spec/events-helpers.js, spec/webview-spec.js
Light refactoring of the `<webview>` tag tests.
=> spec: slightly rewrite webview tests

atom/browser/net/asar/url_request_asar_job.cc, atom/browser/net/asar/url_request_asar_job.h
Chromium-style was failing on this file. Now it isn't.
=> refactor: fix chromium-style in url_request_asar_job

docs/api/crash-reporter.md
=> Add Sentry.io to 3rd party hosted solution list for crash reports

atom/browser/browser_mac.mm, atom/browser/mac/atom_application.h, atom/browser/mac/atom_application.mm, atom/browser/mac/atom_application_delegate.mm, atom/browser/native_window_mac.h, atom/browser/native_window_mac.mm, atom/browser/ui/cocoa/atom_ns_window.h, atom/browser/ui/cocoa/atom_ns_window.mm, atom/browser/ui/cocoa/atom_ns_window_delegate.mm, brightray/browser/mac/cocoa_notification.h, brightray/browser/mac/cocoa_notification.mm, brightray/browser/mac/notification_center_delegate.mm, docs/api/frameless-window.md, docs/tutorial/development-environment.md, docs/tutorial/support.md
It's not supported anymore by Chromium 66
Fixes #13125
=> fix: Drop support for OS X Mavericks (version 10.9)

atom/browser/browser_mac.mm, atom/browser/mac/atom_application.h, atom/browser/mac/atom_application.mm, atom/browser/mac/atom_application_delegate.mm, atom/browser/native_window_mac.h, atom/browser/native_window_mac.mm, atom/browser/ui/cocoa/atom_ns_window.h, atom/browser/ui/cocoa/atom_ns_window.mm, atom/browser/ui/cocoa/atom_ns_window_delegate.mm, brightray/browser/mac/cocoa_notification.h, brightray/browser/mac/cocoa_notification.mm, brightray/browser/mac/notification_center_delegate.mm, docs/api/frameless-window.md, docs/tutorial/development-environment.md, docs/tutorial/support.md
Reverts electron/electron#13296
As discussed in that PR with @miniak
=> Revert "fix: Drop support for OS X Mavericks (version 10.9)"

docs/tutorial/code-signing.md
=> Fix broken link of electron-builder

spec/chromium-spec.js
=> spec: enable a disabled test

spec/window-helpers.js
=> spec: refactor helper closeWindow() function

BUILD.gn, DEPS, build/node/BUILD.gn, build/node/node_override.gypi
Fixes the GN build for changes that were introduced between chrome 63 and
chrome 66.
=> chore: update GN build for chrome 66

atom/browser/api/atom_api_top_level_window.cc, atom/browser/api/atom_api_web_contents.cc, atom/browser/browser.h, atom/browser/browser_win.cc, atom/browser/native_window_views_win.cc, atom/browser/ui/certificate_trust_win.cc, atom/browser/ui/file_dialog.h, atom/browser/ui/file_dialog_win.cc, atom/browser/ui/message_box_win.cc, atom/browser/ui/views/menu_bar.cc, atom/browser/ui/views/win_frame_view.cc, atom/browser/ui/views/win_frame_view.h, atom/browser/ui/win/jump_list.cc, atom/browser/ui/win/jump_list.h, atom/browser/ui/win/notify_icon.h, atom/browser/ui/win/taskbar_host.cc, atom/browser/ui/win/taskbar_host.h, atom/common/api/atom_api_native_image.cc, atom/common/crash_reporter/crash_reporter_win.h, atom/common/crash_reporter/win/crash_service.cc, atom/common/node_bindings_win.h, atom/common/platform_util_win.cc, chromium_src/chrome/browser/extensions/global_shortcut_listener_win.h, chromium_src/chrome/utility/printing_handler_win.h
These errors weren't previously picked up because the GN build wasn't running on Windows.
=> chore: fix various chromium-style errors in windows

spec/webview-spec.js
=> spec: rewrite and enable a webview's disableguestresize attr test

BUILD.gn, build/node/BUILD.gn
Grab basket of changes needed to get the `electron_lib` target building on Windows with GN.
=> chore: [gn] changes to BUILD.gn for windows

docs/development/source-code-directory-structure.md
Update the structure doc for the changes in #13450
=> docs: add native_mate to source code directory structure doc

atom/common/native_mate_converters/net_converter.cc, atom/common/native_mate_converters/network_converter.cc, atom/common/native_mate_converters/v8_value_converter.cc
Address inline vector allocation comments left in associated PR [here](https://github.com/electron/electron/pull/13436/files#r198324911).
/cc @deepak1556
=> fix: inline vector allocation

atom/app/atom_main.cc, atom/browser/net/url_request_async_asar_job.cc, atom/common/promise_util.cc, atom/common/promise_util.h, chromium_src/chrome/browser/ui/views/color_chooser_dialog.h, chromium_src/chrome/browser/ui/views/color_chooser_win.cc
Finding more chromium-style linting errors as I build more of the windows code :)
=> chore: fix more chromium-style errors in windows code

BUILD.gn
This allows building electron.exe on windows 🎉
=> chore: [gn] add electron_app target for windows

spec/chromium-spec.js, spec/fixtures/pages/jquery.html
Backports https://github.com/electron/electron/pull/13475 to 3-0-x.
=> Fix the crash when loading site with jquery (3-0-x)

BUILD.gn, DEPS, native_mate/native_mate/dictionary.cc, native_mate/native_mate/dictionary.h, native_mate/native_mate/persistent_dictionary.cc, native_mate/native_mate/persistent_dictionary.h, native_mate/native_mate/wrappable.h
The native_mate repository was merged into e/e as of #13379, but the GN build was still building the old repo.
As a bonus, find & fix some chromium-style issues.
=> chore: [gn] use the merged-in native_mate

atom/renderer/atom_sandboxed_renderer_client.cc, lib/browser/guest-view-manager.js, lib/sandboxed_renderer/init.js, spec/api-browser-window-spec.js
webview tag doesn't work in sandbox renderer. This PR enables it.
=> Enable webview in sandbox renderer

brightray/browser/devtools_embedder_message_dispatcher.cc, brightray/browser/devtools_embedder_message_dispatcher.h, brightray/browser/inspectable_web_contents_impl.cc, brightray/browser/inspectable_web_contents_impl.h, spec/api-browser-window-spec.js
Close https://github.com/electron/electron/issues/13408, Refs https://github.com/electron/electron/issues/13344.
There are still one devtools test disabled, but it is caused by something else and I will fix it in another PR.
=> Fix devtools not functioning well

spec/api-browser-window-spec.js
This PR updates Node to include https://github.com/electron/node/commit/a782199c99b5716582791fe8145756fd5bcfde27. Close https://github.com/electron/electron/issues/13344.
=> Fix failed devtools tests due to fs.statSyncNoException not working 

BUILD.gn, brightray/BUILD.gn, build/node/BUILD.gn, build/node/node_override.gypi
Grab bag of fixes that get the GN linux build working again.
=> chore: [gn] fix linux build

atom/common/api/atom_api_v8_util.cc, atom/common/api/remote_callback_freer.cc, atom/common/api/remote_callback_freer.h, atom/common/api/remote_object_freer.cc, atom/common/api/remote_object_freer.h, brightray/browser/browser_context.cc, lib/browser/objects-registry.js, lib/browser/rpc-server.js, lib/renderer/api/remote.js
Backports https://github.com/electron/electron/pull/13603 to `2-0-x` branch.
=> fix: guard against double-freeing remote references (2-0-x)

docs/development/releasing.md, script/ci-release-build.js
Backport of #13632 for 2-0-x
* Fixed Appveyor URL
* Updated docs to reflect current process
* Also added troubleshooting steps.
(cherry picked from commit 6b5ccec0c6e574b6f810dde1566c98e03daa2c46)
=> chore: Updates for release process (2-0-x)

docs/api/app.md
=> docs: update second-instance event docs

tools/js2asar.py
Fixes the current windows CI issues on master
=> build: handle win32 path separator in js2asar

.github/PULL_REQUEST_TEMPLATE.md, .github/config.yml, docs/development/pull-requests.md, docs/tutorial/electron-versioning.md
If #13359 gets merged we'll need to update our semantic guidelines to enforce semantic titles for PR's
=> doc: update docs on semantic requirements for #13359

lib/browser/guest-view-manager.js, lib/renderer/web-view/guest-view-internal.js, lib/renderer/web-view/web-view-attributes.js, lib/renderer/web-view/web-view.js, spec/webview-spec.js
Backports https://github.com/electron/electron/pull/13713 to `2-0-x`.
=> fix: create WebContents for webview on request (2-0-x)

docs/api/app.md, docs/api/menu-item.md, docs/api/sandbox-option.md, docs/api/structures/certificate-principal.md, docs/api/structures/gpu-feature-status.md, docs/api/structures/mime-typed-buffer.md, docs/api/structures/rectangle.md, docs/api/structures/scrubber-item.md, docs/api/structures/segmented-control-segment.md, docs/api/structures/stream-protocol-response.md, docs/api/web-contents.md, docs/api/web-frame.md, docs/development/build-instructions-gn.md, docs/development/coding-style.md, docs/development/debugging-instructions-macos-xcode.md, docs/tutorial/application-distribution.md, docs/tutorial/electron-versioning.md, docs/tutorial/using-selenium-and-webdriver.md
- Correct formatting in documents.
- Replace:
electron ~> Electron
node.js ~> Node.js
chromium ~> Chromium
atom-shell ~> electron (folder name)
=> docs: Improved documentation

.circleci/config.yml
I'm not sure if there's any way to mark this specifically as an FYI bot in GitHub, but this is working just about well enough to be useful!
=> build: [ci] add GN linux CI build

spec/api-browser-window-spec.js
- manually close the existing window before creating a new one.
We have to do it because the `afterEach` hook doesn't get called
if a test fails.
- add some async/await goodies
=> chore: [tests] update some BrowserWindow tests

BUILD.gn, brightray/BUILD.gn, brightray/common/main_delegate.cc, electron_paks.gni
This fixes "pak not found" log messages that were showing up on boot.
=> build: [gn] simplify resource pak build

BUILD.gn
This was causing an error at link time.
=> build: [gn win] link dwmapi in component build

BUILD.gn, DEPS
Also, roll libcc to include
https://github.com/electron/libchromiumcontent/commit/9b66eb4f048a91b85260edb622ea497b6b97c481
=> build: [gn] win and linux depend on :packed_resources

brightray/browser/inspectable_web_contents_impl.cc
Fix a crash when loading https://httpbin.org/ with devtools opened.
Code is synced with https://cs.chromium.org/chromium/src/content/shell/browser/shell_devtools_bindings.cc?type=cs&sq=package:chromium&g=0&l=102-119.
Refs #13618.
=> fix: check string encoding before creating value

docs/tutorial/application-architecture.md
=> docs: grammar fix in application-architecture.md

BUILD.gn
=> build: [gn] fix resource path conflict on mac

package-lock.json
These changes happen on every bootstrap and are **super** annoying 😄 
This was generated by running `npm run clean` and `python script/bootstrap.py -v --dev` then committing the changes to the lock file.  My npm version is the latest `6.2.0` so this is the most up to date the lock file can be 👍 
cc @nornagon
=> build: commit changes to the package-lock.json file

BUILD.gn, build/node/BUILD.gn
This is a canonical formatting.
=> chore: [gn] run 'gn format' over BUILD.gn files

.circleci/config.yml
Adds a release build of GN to the CI matrix.
=> ci: gn linux release builds

docs/development/upgrading-node.md
Update the `upgrading-node.md` doc for latest paths and script commands.
/cc @alexeykuzmin
=> docs: update node upgrade doc

.circleci/config.yml
=> ci: [gn] add builders for 32-bit linux debug + release

docs/development/build-instructions-gn.md
=> docs: [gn] update build instructions

DEPS
should fix the last failing test on GN build
=> chore: roll libcc and node DEPS

docs/development/build-instructions-windows.md
=> docs: min windows server version for building is 2012

vsts-gn.yml
I'm not sure how to configure VSTS to run this against PRs yet.
=> ci: [gn] add Mac support to VSTS build

atom/browser/api/atom_api_menu_mac.mm
Backport of https://github.com/electron/electron/pull/12809
See above PR for details.
=> fix: Prevent menu update while it's open (backport: 2-0-x)

DEPS
Brings in electron/libchromiumcontent#633.
=> chore: roll libcc

docs/tutorial/security.md
Fixes the typos mentioned in #13943
=> docs: fix typos in security.md

atom/browser/api/atom_api_web_contents.cc, atom/browser/api/atom_api_web_contents.h, atom/common/options_switches.cc, atom/common/options_switches.h, lib/browser/guest-window-manager.js
=> refactor: make methods const + small cleanup

appveyor-gn.yml
x86 builds are important to us and we should test them :)
=> ci: build x86 builds on GN in appveyor

spec/fixtures/api/mixed-sandbox-app/main.js
Windows apparently has issues running opening two windows at once which is causing flakiness on the mixed sandbox tests.  This PR changes those tests to open the windows sequentially to avoid this issue.
=> fix: Fix flaky sandbox tests

lib/browser/objects-registry.js
=> chore: add FIXME for remote deref

.circleci/config.yml
This PR adds arm and arm64 debug GN builds to our CI.
=> ci: Add arm/arm64 debug gn builds

script/prepare-release.js
=> build: use targetRepo in prepare-release

script/prepare-release.js
=> build: nightly is nightly, beta is beta

script/bump-version.py
=> build: replace nightly and dev versions in the release script

script/release.js
=> chore: add flag to skip version check

DEPS
=> chore: update node revision

script/publish-to-npm.js
=> chore: support otp

script/publish-to-npm.js
=> chore: fix npm nightly dist-tag

.env.example, script/lib/util.py, script/prepare-release.js
=> chore: fix beta bumping in 3.0

.gitignore, script/lib/util.py
=> chore: make beta bumps work on master

script/bump-version.py
=> chore: correctly get pre version in bumper

BUILD.gn
Add `group` targets to build some of the Chromium tests.
Compilation works on my Mac with this change https://github.com/electron/libchromiumcontent/pull/655.
/cc @jkleinsc
=> build: add Chromium tests targets

script/upload-index-json.py
=> chore: remove v from script :sigh:

script/publish-to-npm.js
=> chore: dont check version when publishing

script/bump-version.py, script/publish-to-npm.js, script/upload-index-json.py
=> chore: add sw patches from master

script/publish-to-npm.js
=> fix: add dist tags for release branches

script/publish-to-npm.js
=> fix: add dist tags for release branches (backport 3-0-x)

script/prepare-release.js
=> chore: Fix nightlies on 2-0-x

script/upload.py
=> chore: fix upload script for nightly support

script/prepare-release.js
=> chore: match the bump commit exactly, reverts should not count

script/upload-index-json.py
Backport of 59d6c1e063c3fd0acd564b8130d4eb729d5c357b
=> chore: add metadumper to 2 0 x

script/prepare-release.js
Allow autorelease of all types `[beta | stable | nightly]`.
=> chore: remove autorelease check logic

BUILD.gn, build/args/testing.gn, vsts-gn.yml
This is required for the non-component build where ffmpeg is built as a dynamic library.
=> build: [gn mac] copy ffmpeg lib to framework bundle

atom/browser/atom_browser_context.cc, atom/browser/atom_browser_context.h, atom/browser/special_storage_policy.cc, atom/browser/special_storage_policy.h, brightray/browser/browser_context.cc, brightray/browser/browser_context.h, brightray/filenames.gypi, filenames.gypi
=> refactor: move SpecialStoragePolicy from brightray to atom

.circleci/config.yml, BUILD.gn, appveyor-gn.yml, build/args/release.gn, build/write_version.py, build/zip.py, vsts-gn.yml
=> build: [gn] add distributable zip target

script/ci-release-build.js
=> ci: add better logging around request failures for releasing

script/upload-index-json.py
=> chore: retry for the meta dumper a few times

.circleci/config.yml, appveyor-gn.yml, build/args/ffmpeg.gn, build/args/native_mksnapshot.gn, build/args/testing.gn, script/verify-ffmpeg.py, vsts.yml
This PR adds ffmpeg and native_mksnapshot targets so that we can build those assets for release builds.
=> build: build ffmpeg and native_mksnapshot for GN release builds

docs/tutorial/using-native-node-modules.md
Credit for actually finding this easy method goes to @nornagon.
Notes: Added developer instructions for building native node addons
=> docs: Developer instructions for native Node addons

docs/api/web-frame.md
Fixes #14288
Notes: Improve documentation of "worldId" in the web frame docs
=> docs: explain "worldId" in the web frame docs

BUILD.gn, DEPS
Is supposed to fix debug build Windows with GN.
=> build: windows gn linker fix

spec/api-app-spec.js
It constantly fails on GN builds with Ch66, but looks good with Ch67.
Should be enabled after Ch67 is merged into master.
=> test: disable "app moduele > app.exit(exitCode) > closes all windows"

BUILD.gn, components/pepper_flash/BUILD.gn, electron.gyp
Fixes #14339.
Depends on https://github.com/electron/libchromiumcontent/pull/664
=> build: add enable_pepper_flash flag to GN build

atom/browser/web_contents_preferences.cc, atom/browser/web_contents_preferences.h, default_app/default_app.js, default_app/index.html, default_app/renderer.js, docs/api/breaking-changes.md, lib/browser/api/web-contents.js, lib/common/api/deprecate.js, lib/renderer/security-warnings.js
Reverts electron/electron#14284
Weird native crashes
=> chore: Revert "sec: deprecate some webPreference defaults to be secure-by-default"

spec/api-browser-window-spec.js, spec/fixtures/api/isolated-fetch-preload.js, spec/fixtures/api/isolated-preload.js, spec/fixtures/api/isolated.html, spec/webview-spec.js
Fixes https://github.com/electron/electron/issues/14346
=> chore: refactor context isolation spec

atom/browser/api/atom_api_debugger.cc, atom/browser/render_process_preferences.cc
Fixes https://github.com/electron/electron/issues/12771
=> refactor: replace base::Value::DeepCopy and CreateDeepCopy with Clone

.circleci/config.yml, appveyor-gn.yml, script/lib/gn.py, script/verify-ffmpeg.py
=> refactor: do not use electron.gyp to verify ffmpeg

script/release-artifact-cleanup.js
Backport of https://github.com/electron/electron/pull/14250.
=> chore: add release-artifact-cleanup script (3-0-x)

script/release-artifact-cleanup.js
Backport of https://github.com/electron/electron/pull/14250.
=> chore: add release-artifact-cleanup script (2-0-x)

script/release-artifact-cleanup.js
Backport of https://github.com/electron/electron/pull/14250.
=> chore: add release-artifact-cleanup script (1-8-x)

docs/tutorial/first-app.md
Notes: Update first-app.md with at least a pointer to more info on npm
=> docs: Update first-app.md with pointer to more npm info

atom/browser/api/atom_api_debugger.cc, atom/browser/api/atom_api_debugger.h, atom/common/native_mate_converters/value_converter.cc, atom/common/native_mate_converters/value_converter.h, spec/api-debugger-spec.js
Backport https://github.com/electron/electron/pull/14475 to `3-0-x`
=> backport debugger fix

spec/asar-spec.js
=> test: refactor the "util.promisify" test

BUILD.gn, build/args/release.gn
=> docs: expand on TODOs in BUILD.gn

atom/app/atom_content_client.cc, atom/renderer/renderer_client_base.cc, atom/renderer/renderer_client_base.h, chromium_src/chrome/common/chrome_paths.cc, chromium_src/chrome/renderer/media/chrome_key_systems.cc, chromium_src/chrome/renderer/media/chrome_key_systems_provider.cc, chromium_src/chrome/renderer/media/chrome_key_systems_provider.h, electron.gyp, filenames.gypi
Backport of https://github.com/electron/electron/pull/14423.
/cc @deepak1556 
=> build: [gn] widevine cdm support behind flag (3-0-x)

spec/api-power-monitor-spec.js
Reverts electron/electron#14458
=> revert: "fix: re-enable power monitor test"

spec/api-power-monitor-spec.js
Reverts electron/electron#14496
notes: no notes
=> revert: "fix: re-enable power monitor test (3-0-x)"

script/bump-version.py, script/verify-ffmpeg.py
There was a number of errors, which caused automated checks to fail on CI machines.
Related to #14536.
=> chore: fix pylint errors

appveyor-gn.yml
The artifact wasn't showing up in appveyor.
=> ci: fix path to dist.zip on appveyor

patches/common/chromium/.patches.yaml, patches/common/chromium/exclude-a-few-test-files-from-build.patch
=> test: fix compilation of blink_unittests

script/patch.py
=> chore: copy script/patch.py from the libcc repo

.circleci/config.yml
=> ci: add a FYI job to build Chromium test binaries

electron.gyp
Resolves https://github.com/electron/electron/issues/14653.
Defines `ENABLE_PEPPER_FLASH` in `electron.gyp`
/cc @deepak1556 
=> fix: define ENABLE_PEPPER_FLASH

script/release-artifact-cleanup.js
=> chore: fix await in cleanup script

.circleci/config.yml
To clean up the config and make test restarts easier.
Builds with `verify-ffmpeg` step enabled
https://circleci.com/workflow-run/c3f5d025-efa3-43a2-85e4-53de78e1bb61
Builds with `verify-ffmpeg` step disabled
https://circleci.com/workflow-run/9efe8146-798b-4780-92d2-9ccec95756dd
=> ci: refactor Mac builds on CircleCI

docs/development/upgrading-node.md
Remove some references to libcc and add some notes about the GN build files we now maintain.
I think there's more to do here, and I'll continue to add to & update this documentation as I go through the process of upgrading node in the context of the GN build.
=> docs: update "upgrading node" guide

script/lint.js
This fixes linting locally when you have the `spec` node modules installed.  It was removed in https://github.com/electron/electron/pull/14622/files#diff-1b0fd5322de42e11c8786543f74c7c41 and passes on CI because linting is run without `spec/node_modules` being installed.
=> chore: ignore spec/node_modules from linting

.circleci/config.yml
- it is an independent task and should be done separately
- we can use smaller machines for that
An example workflow https://circleci.com/workflow-run/379ca922-fcea-42bc-b370-803a916fd4b6
=> ci: build ffmpeg and verify it in a separate jobs

lib/browser/api/app.js
Fixes #14713.
Notes: Added end-of-support warning message
=> feat: add 1.7.x end-of-support warning

script/spec-runner.js
to get some output other than "it didn't work" when it doesn't work.
=> test: inherit stdio when 'npm install'ing spec deps

.circleci/config.yml
Test run of the new builds: https://circleci.com/workflow-run/a8fd392a-77f7-433d-b51a-4ddb2cabb1bd
=> ci: build mksnapshot in a separate job

docs/api/app.md
Fix the event handler signature in the 'second-instance' event handler example.
Notes: Fixed `second-instance` API documentation error.
=> docs: fix `second-instance` handler signature example

.circleci/config.yml, script/native-tests.py, script/tests.yml
Example https://circleci.com/gh/electron/electron/64511
Let's run them only nightly for now, since the job takes a lot of time. It can probably be parallelised though.
=> ci: run native tests on CircleCI

docs/development/build-instructions-gn.md, docs/development/releasing.md, script/upload.py
Update releasing info to reflect new 2FA requirements and user for `npm`.
Todo: 
/cc @jkleinsc 
=> docs: update releasing info

script/native-tests.py
It is optional now:
```
-v {all,errors,silent}, --verbosity {all,errors,silent}
set verbosity level
-q, --quiet           suppress stdout from test binaries
-qq, --quiet-quiet    suppress stdout and stderr from test binaries
```
=> ci: do not suppress stdout from Google Test binaries

.circleci/config.yml, BUILD.gn, appveyor.yml, patches/common/v8/.patches.yaml, patches/common/v8/expose_mksnapshot.patch, script/upload.py, vsts.yml
Update `upload.py` to be compatible with our build process now that we've switched to GN.
**To-Do:**
/cc @jkleinsc 
=> chore: update mksnapshot and ffmpeg for GN

.circleci/config.yml, vsts.yml
Since we now build not only from master.
=> ci: add a branch name to Slack notifications

package-lock.json
This one `s` was causing branch switching to fail 😢 Checking it in to stop annoying me 😄 
=> chore: check in the changes to package-lock.json

BUILD.gn, atom/browser/osr/osr_render_widget_host_view.cc, atom/browser/osr/osr_render_widget_host_view.h, atom/browser/osr/osr_render_widget_host_view_mac.mm
It's enabled for GYP builds, so it should be enabled for GN builds.
=> build: turn on OSR for GN builds

atom/browser/common_web_contents_delegate_mac.mm, atom/browser/common_web_contents_delegate_views.cc, spec/api-web-contents-spec.js, spec/package-lock.json, spec/package.json, tools/run-if-exists.js
DevTools webContents do not have webPreferences
_reccomend viewing the diff with `?w=1`_
Fixes #14685
Notes: fix basic shortcuts (copy, paste, etc.) not working in devtools
=> fix: handle shortcuts by default if no WebPreference object exists

spec/api-app-spec.js
=> test: disable getGPUInfo() tests on Linux

.circleci/config.yml
=> ci: fail a tests job is there are no test results

atom/browser/api/atom_api_app.cc, spec/api-app-spec.js, spec/fixtures/api/gpu-info.js
Those tests timeout quite often, e.g. only today's builds from the `master`
https://circleci.com/gh/electron/electron/68451
https://circleci.com/gh/electron/electron/68402
https://circleci.com/gh/electron/electron/68387
https://circleci.com/gh/electron/electron/68335
=> test: slightly rewrite getGPUInfo() tests

script/spec-runner.js
=> chore: some async await stuff for the spec runner

build/zip.py
=> chore: remove duplicate and un-needed files from dist zips

spec/configs/unittests.yml
Fails after the Chromium 68 upgrade.
=> test: disable one test in base_unittests

.circleci/config.yml
- do not build ffmpeg for every PR on CircleCI
- build and run unittests in a separate workflow on CircleCI
- build chromedriver in a separate job
An updated workflow for all PRs: https://circleci.com/workflow-run/e00a158c-95b6-493d-b8ba-4211a34d5d73
An updated nightly run: https://circleci.com/workflow-run/13cca510-8c66-4f8d-a9bc-646f76101d05
=> ci: rearrange builds on CircleCI

atom/browser/relauncher_linux.cc, spec/api-app-spec.js
=> fix relaunch on linux

vsts.yml
=> ci: temporary do not run "verify-ffmpeg.py" on Mac CI

.circleci/config.yml
This PR saves the build artifacts for debug builds so that they are available for testing/developer use.
=> ci: Save build artifacts for debug builds

atom/browser/api/atom_api_web_contents.cc, atom/browser/osr/osr_render_widget_host_view.cc, atom/browser/osr/osr_render_widget_host_view.h, atom/browser/osr/osr_render_widget_host_view_mac.mm, build/args/all.gn
What it says on the tin.
/cc @brenca 
Notes: Re-enable osr
=> fix: re-enable osr following m68 upgrade

atom/browser/api/stream_subscriber.cc, atom/browser/net/asar/asar_protocol_handler.cc, atom/browser/net/js_asker.cc, atom/browser/net/js_asker.h, atom/browser/net/url_request_async_asar_job.cc, atom/browser/net/url_request_async_asar_job.h, atom/browser/net/url_request_buffer_job.cc, atom/browser/net/url_request_buffer_job.h, atom/browser/net/url_request_fetch_job.cc, atom/browser/net/url_request_fetch_job.h, atom/browser/net/url_request_stream_job.cc, atom/browser/net/url_request_stream_job.h, atom/browser/net/url_request_string_job.cc, atom/browser/net/url_request_string_job.h, patches/common/chromium/.patches.yaml, patches/common/chromium/dcheck.patch, spec/configs/unittests.yml
we are depending on weak ptrs quite a bit and ignoring this dcheck will cause problems moving forward.
=> refactor: enable weak ptr unwrap sequence dcheck

DEPS, script/update-external-binaries.py
1. Make downloading of external binaries optional and parameterized.
2. Reformat DEPS to make it look more like Chromium's //DEPS:
- use name-pattern-condition-action order for hooks
- add trailing commas
- remove some line breaks
Also remove redundant entry from "recursedeps".
=> build: make external binaries download action more flexible

.circleci/config.yml
- do not report success from Electron build jobs
- report failures from more jobs
- add separate summary jobs to report success
https://circleci.com/workflow-run/5d3b90ed-6f4e-43a1-9341-6058f8ff9f1e
=> ci: better Slack notifications for nightly jobs

.circleci/config.yml, appveyor.yml, vsts.yml
- ci: don't send Slack notifications for the "linux-ia32-testing-tests" job
- ci: fix symbols collection job on VSTS
- ci: run tests on Windows for both "testing" and "release" builds
**nightly-release-osx-x64**
https://github.visualstudio.com/electron/_build/results?buildId=13940&view=logs
**electron-nightly-release-test-x64**
https://windows-ci.electronjs.org/project/AppVeyor/electron-hernh/build/1.0.106
=> ci: various fixes

lib/renderer/init.js
Replace `'true'` / `'false'` strings with boolean variables.
(https://github.com/electron/electron/blob/master/docs/development/testing.md)
=> refactor: use boolean for nodeIntegration / webviewTag

script/dump-symbols.py, script/lib/util.py, script/upload.py, tools/win/generate_breakpad_symbols.py, vsts.yml
Nightly builds have been failing lately because the `upload.py` script couldn't find Electron's binary.
https://github.visualstudio.com/electron/_build/results?buildId=13965&view=logs
A build after the fix https://github.visualstudio.com/electron/_build/results?buildId=14070&view=logs
/cc @jkleinsc 
=> ci: fix the upload distribution step on VSTS

docs/development/build-instructions-gn.md
This PR documents how maintainers currently pull/push. This is likely not the best way to actually achieve our goal, but I'd love visitors and "outsiders" to know how _we're_ doing it.
Notes: Added documentation on how to pull/push with `gclient`
=> docs: Add instructions on how to pull/push

build/zip.py
This reverts commit f7dee77f2bf6b1df96e4546d0a86a5bfe438df5f.
=> revert: "fixme: allow huge Electron archives"

vsts.yml
Because we can't afford waiting too much for hanging builds.
=> ci: set timeouts for all steps on VSTS

patches/common/chromium/.patches.yaml, patches/common/chromium/dump_syms.patch
=> chore: patch dump_syms to not hard fail on dylib resolve error

DEPS
=> fix: update node for patch that allows native modules built on < node 10

patches/common/chromium/notification_provenance.patch
Fix compilation of `unittests` after the Ch69 merge.
Compilation succeeds, but some tests fail: https://circleci.com/gh/electron/electron/81097
=> test: update notification_provenance.patch to fix unittests compilation

DEPS
To be able to build clean Chromium from sources.
=> build: add "apply_patches" flag to gclient

atom/browser/api/atom_api_web_contents.cc, atom/browser/api/atom_api_web_contents.h, atom/browser/api/atom_api_web_contents_osr.cc, atom/browser/common_web_contents_delegate.cc, atom/browser/common_web_contents_delegate.h, atom/browser/osr/osr_render_widget_host_view.cc, atom/browser/osr/osr_render_widget_host_view.h, atom/browser/osr/osr_render_widget_host_view_mac.mm, atom/browser/osr/osr_web_contents_view.cc, atom/browser/osr/osr_web_contents_view.h, buildflags/buildflags.gni
Upgrade osr code to re-enable it for compatibility with M69; cherry picked from old PR to avoid a rebase hellscape.
h/t @brenca ✨ 
=> fix: update and enable osr

atom/renderer/renderer_client_base.cc
Fixes #14976.
Notes: fix: backgroundColor is preserved through reload
=> fix: preserve background color through reload

atom/renderer/renderer_client_base.cc
Backport of https://github.com/electron/electron/pull/15105
Notes: fix: backgroundColor is preserved through reload
=> fix: preserve background color through reload (backport: 3-0-x)

vsts.yml
It appears that VSTS doesn't get rid of untracked git files, so this PR makes sure we start off with a clean git dir.
=> ci: make sure git directories don't have unneeded files in them

patches/common/chromium/.patches.yaml, patches/common/chromium/blink_file_path.patch
[ci skip]
Per discussion with @zcbenz.
=> chore: add documentation for blink_file_path.patch

DEPS
brings in electron/node#76 and electron/node#77 and https://github.com/electron/node/pull/75
Notes: fix an issue where N-API and zlib symbols weren't correctly exported on windows, and also enable support for the NODE_OPTIONS environment variable
=> chore: roll node

script/upload-symbols.py
Symbol server wasn't able to fetch files as they are case sensitive. Upload after converting to lowercase.
=> fix: Convert to lower case in upload symbols script

atom/common/node_bindings.cc
=> fix: convert wstring to string on windows in node_bindings

spec/api-browser-window-spec.js, spec/fixtures/api/sandbox.html, spec/fixtures/module/preload-sandbox.js
Make it more readable.
/cc @ppontes 
=> test: asyncawaitify one of sandbox related tests

spec/api-browser-window-spec.js, spec/fixtures/api/sandbox.html, spec/fixtures/module/preload-sandbox.js
=> test: asyncawaitify one of sandbox related tests (backport: 3-0-x)

docs/development/build-instructions-gn.md, docs/development/build-instructions-windows.md
Fix dead links (to macOS build instructions) and improve instructions for building on Windows 10.
/cc @nornagon @codebytere @jkleinsc
=> docs: fix dead links and update Windows build instructions

docs/tutorial/security.md
=> docs: Fix CSP header setting of sample code

DEPS
To allow in-house builds to checkout those manually.
Notes:  no notes
=> build: add conditions to check out Chromium and Node.js

.circleci/config.yml, script/lib/native_tests.py, script/native-tests.py, spec/configs/unittests.yml
https://circleci.com/workflow-run/5abe1628-7296-4872-b923-f79fbaf2d536
=> ci: run more Chromium unit tests

README.md
This PR adds an Azure Pipelines build status to our README.
=> docs: add Azure Pipelines status

docs/tutorial/electron-versioning.md
=> chore: update versioning doc for nightlies

spec/asar-spec.js
This spec is passing locally on MacOS once more.
=> chore: re-enable execFileSync binary exec spec

spec/api-net-log-spec.js
Passing locally, let's see what happens on CI 🤔 
=> chore: re-enable failing netlog spec

spec/api-session-spec.js
It passes locally on all platforms once more.
/cc @jkleinsc 
=> chore: re-enable protocol partition request spec

docs/api/system-preferences.md
Notes: fixed return type information for `systemPreferences.subscribeNotification`
=> docs: add return type for subscribeNotification

docs/api/breaking-changes.md
The 'second-instance' handler receives `event` as its first argument.
https://github.com/electron/electron/blob/3-0-x/docs/api/app.md#event-second-instance
Notes: docs: fix the "second-instance" event handler signature in the docs
=> docs: fix the "second-instance" event handler signature in the docs

.circleci/config.yml, DEPS
=> build: make pyyaml an optional dependency (backport: 4-0-x)

patches/common/chromium/dcheck.patch
Restore a commented-out DCHECK in viz
=> chore: restore viz dcheck

.circleci/config.yml, appveyor.yml, script/verify-mksnapshot.py, spec/fixtures/snapshot-items-available.js, spec/fixtures/testsnap.js, vsts.yml
This PR adds testing of mksnapshot to our CI.
=> ci: add testing for mksnapshot

vsts.yml
root cause to be investigated separately
=> ci: temporarily disable verify ffmpeg & mksnapshot tests on vsts

docs/development/build-instructions-gn.md
Make the error googleable hopefully.
=> docs: add troubleshooting section for win toolchain prompt

docs/development/build-instructions-windows.md
Changed German link with English one for "Windows SDK and emulator archive"
=> docs: changed German link with English one for Windows SDK Archive

docs/development/build-instructions-windows.md
On my machine, I had to go through extra steps to get the SDK Debugging Tools installed.
=> docs: update Windows build instructions to include debugging tools

atom/app/atom_main_delegate.cc, atom/app/atom_main_delegate.h, atom/browser/atom_browser_main_parts.cc, patches/common/chromium/.patches, patches/common/chromium/content_allow_embedder_to_prevent_locking_scheme_registry.patch, patches/common/chromium/dcheck.patch
=> chore: restore //url dchecks

atom/renderer/atom_sandboxed_renderer_client.cc, lib/browser/guest-view-manager.js, lib/sandboxed_renderer/init.js, spec/api-browser-window-spec.js
Notes: Enable webview in sandbox renderer
Security: Inherit embedder prefs onto webview
=> fix: enable webview in sandbox renderer (#13435)

vsts.yml
This PR makes sure that the git directories don't contain any extra files.  This is a backport of #15248 to 3-1-x
=> ci: clean git before building

spec/api-browser-window-spec.js, spec/api-web-contents-spec.js
=> test: fix a bunch of flaky tests related to emittedOnce (backport: 4-0-x)

atom/browser/net/url_request_context_getter.cc, patches/common/chromium/.patches, patches/common/chromium/ensure_cookie_store.patch, spec/api-session-spec.js, spec/fixtures/api/cookie-app/main.js, spec/fixtures/api/cookie-app/package.json
Backport of #15836 
Notes: Fixed a bug that made all cookies non persistent.
=> fix: backport patch that ensures that cookie store is always created (backport: 4-0-x)

patches/common/chromium/dcheck.patch
Hoping that it no longer fires 🤞 
=> chore: restore ppapi_host DCHECK

electron_paks.gni
=> chore: add webui_resources to pak

atom/browser/api/atom_api_top_level_window.cc, atom/browser/native_window.h, atom/browser/native_window_mac.h, atom/browser/native_window_mac.mm, atom/browser/native_window_views.cc, atom/browser/native_window_views.h, spec/api-browser-window-spec.js, spec/package-lock.json, spec/package.json
Close https://github.com/electron/electron/issues/15911.
I have written a module to validate that the result of `BrowserWindow.getNativeWindowHandle` is a valid window: https://github.com/electron/node-is-valid-window.
Notes: Fix `BrowserWindow.getNativeWindowHandle()` returning invalid handle.
=> fix: return pointer instead of pointer's content

patches/common/chromium/.patches, patches/common/chromium/disable_color_correct_rendering.patch
Backport of #15898
Notes: Add `--disable-color-correct-rendering` switch
=> fix: restore ability to disable color correct rendering (backport: 4-0-x)

filenames.gni, lib/browser/rpc-server.js, lib/renderer/api/remote.js, lib/renderer/init.js, lib/renderer/override.js
- remove unused arguments of `exceptionToMeta`
- remove unnecessary `override.js`, use `window-setup` directly
- format `getCurrentWebContents` consistently with other `remote` methods
=> chore: misc cleanup

.github/config.yml
What is says on the tin.
/cc @BinaryMuse
=> chore: add BinaryMuse to troppers

spec/chromium-spec.js
Backports #15857 to reduce flakiness
=> test: fix remote-debugging-port test calling done twice (#15857)

script/release-artifact-cleanup.js
=> chore: correctly capitalize releaseID (backport: 3-1-x)

script/release-artifact-cleanup.js
=> chore: correctly capitalize releaseID (backport: 3-0-x)

patches/common/chromium/chrome_process_finder.patch
Follow up to https://github.com/electron/electron/pull/15424.
=> chore: fix chrome_process_finder.patch description

script/upload-to-github.js
The release upload script is not properly deleting assets that failed to upload; this PR adds some additional error handling to determine the root cause of this.
=> chore: add additional logging for release upload failures

script/prepare-release.js
GitHub's docs do not quite make this clear 🙃 
/cc @BinaryMuse 
=> chore: release.id => release.data.id

spec/api-browser-window-affinity-spec.js, spec/api-browser-window-spec.js, spec/api-session-spec.js, spec/api-web-contents-spec.js, spec/api-web-frame-spec.js, spec/chromium-spec.js
Some of these are taking advantage of the new `loadURL` promise return, others just asyncifying things for a more natural flow.
=> test: promisify a bunch of tests

spec/chromium-spec.js
Fix the failing CI on master branch.
Notes: no-notes.
=> fix: add missing require in chromium-spec

npm/package.json
Resolves https://github.com/electron/electron/issues/16173.
Updates `@types/node` from `v8.0.24` => `v10.12.18`.
=> chore: update @types/node dep

script/publish-to-npm.js
=> chore: publish nightlies to electron-nightly

script/upload-to-github.js
"Manual backport" of https://github.com/electron/electron/pull/16127
This was never merged to master; it's already been backported to 2-0-x, 3-0-x, and 3-1-x.
=> chore: add additional logging during asset upload

script/publish-to-npm.js
We already have [electron-nightly](https://www.npmjs.com/package/electron-nightly) so this allows for fewer changes to get nightlies going again.
/cc @BinaryMuse 
Notes: none
=> chore: @electron/nightly => electron-nightly

.circleci/config.yml
Revert https://github.com/electron/electron/pull/15665. It's causing broken builds on master.
cc @alexeykuzmin @MarshallOfSound 
Notes: none
=> chore: revert "ci: use config version 2.1 on CircleCI"

DEPS, script/external-binaries.json, script/update-external-binaries.py
I think it's better to have an explicit list of all "external binaries" we download.
/cc @jkleinsc 
=> build: extract external binaries config

script/bump-version.js, script/lib/version-utils.js, spec/version-bump-spec.js
Add specs for https://github.com/electron/electron/pull/16311.
Notes: none
=> test: add specs to version bump utils

script/release.js
`electron-bot` [reverted this](https://github.com/electron/electron/commit/2ee59cc82c18607e9bc366accee58ec7f4ae532d) somehow 
cc @BinaryMuse @ckerr 
Notes: none
=> chore: redo size -> length

script/release-artifact-cleanup.js
=> chore: always try to nuke tags

lib/renderer/init.js
=> fix: dont run window-setup on chrome:// protocol, introduced in b965e54

docs/tutorial/electron-timelines.md
Living document for Electron release schedules. We're kicking off with v5.0.0. 
Notes: Added doc for Electron timelines
=> docs: add Electron timelines document

atom/browser/ui/views/menu_bar.cc
Fix the following crash when running tests on CI:
https://windows-ci.electronjs.org/project/AppVeyor/electron-67iac/build/1.0.5048
```
[7368:0128/165957.622:FATAL:focus_controller.cc(238)] Check failed: rules_->CanFocusWindow(window, nullptr). 
19594Backtrace:
19595	logging::LogMessage::~LogMessage [0x02BFEBE7+103]
19596	wm::FocusController::SetFocusedWindow [0x02BE8BE2+124]
19597	wm::FocusController::ResetFocusWithinActiveWindow [0x02BE8B4D+109]
19598	views::DesktopNativeWidgetAura::ClearNativeFocus [0x05025712+50]
19599	views::View::OnFocus [0x03E18EC9+25]
19600	views::Button::OnFocus [0x0501E49B+11]
19601	views::LabelButton::OnFocus [0x0500565B+11]
19602	views::View::Focus [0x03E18EF9+33]
19603	views::FocusManager::SetFocusedViewWithReason [0x03E0B72D+343]
19604 …
```
=> fix: CI failure on Windows

docs/api/app.md
=> docs: Fixed a little typo

script/upload-to-github.js
Fix `github.repos.updateAsset` => `github.repos.editAsset`
Notes: none
=> chore: fix asset fail workaround

docs/api/dialog.md
=> docs: Recommend use of callback with dialog.showSaveDialog

docs/tutorial/first-app.md
Added a missing let that was missing.
=> docs: Add missing let

atom/browser/api/atom_api_top_level_window.cc
Follow-up to [this comment](https://github.com/electron/electron/pull/16657#discussion_r253535488). Remove unused variable.
cc @deepak1556 
Notes: none
=> chore: remove unused variable in removeWindow

lib/browser/guest-view-manager.js, lib/common/web-view-methods.js, lib/renderer/web-view/web-view.js
Backport of https://github.com/electron/electron/pull/16433.
Notes: Fixed an issue with promise methods not resolving correctly over ipc in the renderer process.
=> fix: correctly handle IPC for promise-based methods

.github/ISSUE_TEMPLATE/Bug_report.md
Hopefully this will make it easier to read issues that come in, & make it less likely that people leave the template text in.
=> chore: update issue template, comment out instructions

script/upload-index-json.py
I managed to recover the damage from yesterday but this will ensure that we never push bad JSON again 👍 
=> build: ensure index.json is actually valid JSON before uploading

package.json, script/run-gn-format.py
Adds `gn format` as a precommit hook
=> chore: auto-format GN and python files in our precommit

docs/api/app.md
=> docs: improve `app.commandLine` documentation

docs/tutorial/using-native-node-modules.md
Recently went through this journey (again) and wanted to save others some pain.
=> docs: add some troubleshooting info related to win_delay_load_hook

docs/api/web-contents.md
=> docs: added webContents.getType() method

docs/tutorial/security.md
The security doc now provides a solid check, as in point 11 and 12.
Notes: fixes issue #16774
=> fix: security doc now provides solid url check

script/upload-to-github.js
This reverts commit ab503c7e4349315f600ac3c49b43bab6f88b6f54.
Notes: none
=> chore: revert hack around GitHub upload API failure / flake

lib/browser/init.ts
🔗 https://github.com/electron/electron/pull/16441/files/15affe3eb9716d3b463231eb3537c693ac2c77c6#r254632887
=> fix: restore accidentally removed chrome-extension require

lib/browser/chrome-devtools.js
As discussed in https://github.com/electron/electron/pull/16607.
/cc @nornagon
=> chore: add menu-will-close comment explaining setTimeout

atom/common/keyboard_util.cc, docs/api/accelerator.md
Resolves https://github.com/electron/electron/issues/16160.
Add accelerator support for Scroll Lock.
cc @brenca 
Notes: Added support for Scroll Lock accelerator.
=> feat: add support for scroll lock accelerator

docs/api/webview-tag.md
=> docs: remove removed autosize attribute

.circleci/config.yml
Fixes https://github.com/electron/electron/pull/16494#issuecomment-462218838
=> ci: fix binaries for chromedriver build on macOS

docs/api/protocol.md
Fix lint errors in master from https://github.com/electron/electron/pull/16762 
=> chore: fix lint errors

build/npm-run.py
=> chore: suppress output of npm_action unless it fails

atom/browser/ui/file_dialog_gtk.cc
This PR adds a file preview for the GTK file picker.  Resolves #15792.
Notes: 
Added file preview for file picker in Linux
=> feat: add file preview for GTK file picker

spec/webview-spec.js
=> fix: potential flake/race in webview specs

docs/tutorial/electron-timelines.md
Update the timelines doc per the result of #16876.
- ~~`npm test` passes~~ (not applicable)
- ~~tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)~~ (not applicable)
=> docs: update chromium version in 5.0.0 release schedule

atom/browser/api/atom_api_app.cc, atom/browser/api/atom_api_content_tracing.cc, atom/browser/api/atom_api_cookies.cc, atom/browser/api/atom_api_debugger.cc, atom/browser/api/atom_api_debugger.h, atom/browser/api/atom_api_protocol.cc, atom/browser/api/atom_api_system_preferences_mac.mm, atom/browser/api/atom_api_web_contents.cc, atom/browser/api/gpuinfo_manager.cc, atom/browser/api/gpuinfo_manager.h, atom/browser/browser.cc, atom/browser/browser.h, atom/common/api/atom_api_shell.cc, atom/common/api/atom_bindings.cc, atom/common/api/atom_bindings.h, atom/common/platform_util.h, atom/common/platform_util_linux.cc, atom/common/platform_util_mac.mm, atom/common/platform_util_win.cc, atom/common/promise_util.cc, atom/common/promise_util.h, native_mate/native_mate/arguments.h
Backport https://github.com/electron/electron/pull/17071 to `5-0-x` branch.
=> chore: make util::Promise a move-only type (5-0-x)

atom/browser/api/atom_api_web_contents_impl.cc
Replaces the usage of testing api added in https://github.com/electron/electron/pull/16334/commits/03d499bf34d664866f30b280f55b72290b538653
=> fix: use frame tree api to remove <webview> frame

lib/browser/chrome-extension.js
Load the JSON file with messages asynchronously without blocking the main thread.
=> refactor: make CHROME_GET_MESSAGES handler async

spec/api-browser-window-spec.js, spec/fixtures/module/preload-sandbox.js
Add missing checks to "validates process APIs access in sandboxed renderer"
=> test: add missing checks to "validates process APIs access in sandboxed renderer"

DEPS, patches/common/chromium/.patches, patches/common/chromium/browser_compositor_mac.patch, patches/common/chromium/can_create_window.patch, patches/common/chromium/command-ismediakey.patch, patches/common/chromium/disable_color_correct_rendering.patch, patches/common/chromium/fix_backup_includes_for_ptrace_get_thread_area_on_arm_arm64.patch, patches/common/chromium/mas-cfisobjc.patch, patches/common/chromium/mas_blink_no_private_api.patch, patches/common/chromium/mas_no_private_api.patch, patches/common/chromium/render_widget_host_view_mac.patch, patches/common/chromium/scroll_bounce_flag.patch, patches/common/chromium/webview_cross_drag.patch
Updating Chromium to 73.0.3683.61.
Also backport https://chromium-review.googlesource.com/c/chromium/src/+/1496448 which fixes the build on ARM/ARM64.
See [all changes in 73.0.3683.58..73.0.3683.61](https://chromium.googlesource.com/chromium/src/+/73.0.3683.58..73.0.3683.61)
Notes: Updated Chromium to 73.0.3683.61.
=> chore: bump chromium to 73.0.3683.61 (master)

DEPS, patches/common/chromium/.patches, patches/common/chromium/browser_compositor_mac.patch, patches/common/chromium/can_create_window.patch, patches/common/chromium/command-ismediakey.patch, patches/common/chromium/disable_color_correct_rendering.patch, patches/common/chromium/fix_backup_includes_for_ptrace_get_thread_area_on_arm_arm64.patch, patches/common/chromium/mas-cfisobjc.patch, patches/common/chromium/mas_blink_no_private_api.patch, patches/common/chromium/mas_no_private_api.patch, patches/common/chromium/render_widget_host_view_mac.patch, patches/common/chromium/scroll_bounce_flag.patch, patches/common/chromium/webview_cross_drag.patch
Updating Chromium to 73.0.3683.61.
Also backport https://chromium-review.googlesource.com/c/chromium/src/+/1496448 which fixes the build on ARM/ARM64.
See [all changes in 73.0.3683.54..73.0.3683.61](https://chromium.googlesource.com/chromium/src/+/73.0.3683.54..73.0.3683.61)
Notes: Updated Chromium to 73.0.3683.61.
=> chore: bump chromium to 73.0.3683.61 (5-0-x)

package-lock.json, spec/package-lock.json
```
electron master$ git pull
electron master$ npx npm@latest install --package-lock-only
electron master$ git commit -am "fix those damn package-lock diffs"
```
=> chore: update package-lock.json with npm@latest

lib/renderer/web-view/web-view-attributes.ts, lib/renderer/web-view/web-view-element.ts
* remove unused _args var
* handle type/variable shadowing
=> build: fix new TS linting errors

docs/development/build-instructions-gn.md
It took me some time to figure out how to get a distributable zip file from the build.
I think it's worth adding this to the build documentation.
Notes: `no-notes`
=> docs: Add information on packaging a build

spec/api-web-contents-spec.js
Hoping this will reduce flake. e.g. https://circleci.com/gh/electron/electron/149558
=> test: robustify sendInputEvent beforeEach hook

patches/common/chromium/accelerator.patch
Adds a description to accelerator.patch based on @zcbenz's description in slack.
=> chore: add description to accelerator.patch

default_app/renderer.ts, docs/api/app.md
clarified what requestSingleInstanceLock() does in the app docs based on #17188 
=> docs: clarification of requestSingleInstanceLock() docs

docs/api/webview-tag.md
Fixed a small spelling mistake.
/cc @zeke @electron/wg-docs-tools
=> docs: fix typo

docs/api/structures/ipc-main-event.md
Corrected 'frane' to 'frame' in ipc-main-event.md
=> docs: correction to ipc-main-event.md 'frane' to 'frame'

docs/tutorial/windows-taskbar.md
The PR removes the following broken URL: 
- <http://i.msdn.microsoft.com/dynimg/IC420539.png>
used for the **"Tasks of Internet Explorer"** image, on the `docs/tutorial/windows-taskbar.md` file, 
and replaces it with the correct one: 
- <https://i-msdn.sec.s-msft.com/dynimg/IC420539.png>
As a sanity check, the new image URL uses the same domain name, **`https://i-msdn.sec.s-msft`**, as the other 2 in the file:
- <https://i-msdn.sec.s-msft.com/dynimg/IC420540.png>
- <https://i-msdn.sec.s-msft.com/dynimg/IC420441.png>
Fixes #17387.
Old URL | New URL
--- | ---
Notes:  Use correct image URL on `docs/tutorial/windows-taskbar.md`
=> docs: Use correct image URL on `docs/tutorial/windows-taskbar.md`

DEPS
No changes made to node canary, just rebased with fixups.
This change updates to the new commit of `electron-node-canary`.
=> chore: Update node commit sha

.github/ISSUE_TEMPLATE/Feature_request.md
=> chore: fix typos in feature request template instructions

atom/browser/api/atom_api_web_contents.cc, atom/renderer/atom_render_frame_observer.cc, lib/browser/chrome-extension.js
Backport of #17614
Notes: DevTools Extensions now load correctly
=> fix: make devtools extensions load correctly

docs/tutorial/code-signing.md
Updated documentation to add fee hint.
Notes: none
=> docs: added fee hint

atom/browser/javascript_environment.cc
Fix a possible crash on exit, see https://github.com/electron/electron/pull/17877 for more details
Notes: Fix a possible crash on exit
=> fix: drain tasks before shutting down isolate (master)

docs/tutorial/electron-timelines.md
6.0.0 Timeline ⚡️ 
cc @electron/wg-releases @electron/wg-upgrades 
Notes: Added 6.0.0 Release Timeline
=> docs: add timeline document for Electron v6.0.0

docs/tutorial/electron-timelines.md
cc @electron/wg-releases 
Notes: no-notes.
=> docs: edit Release Timelines doc format and add title

package-lock.json, package.json
This fixes some new Promise type definitions
=> build: update ts generator

atom/browser/api/atom_api_session.cc
Ref https://github.com/electron/electron/issues/15791
=> refactor: session.clearHostResolverCache with network service

atom/browser/api/atom_api_app.cc, atom/browser/api/atom_api_app.h, atom/browser/api/event_emitter.h, atom/common/api/event_emitter_caller.h
Update `base::Bind` to `base::BindRepeating` and `base::BindOnce` where applicable.
cc @deepak1556 @MarshallOfSound 
Notes: none
=> chore: update base::Bind in app module

.github/main.workflow
Adds workflow file for GitHub Actions.
Notes: none
=> chore: add base workflow file

DEPS, atom/browser/api/atom_api_app.cc, atom/browser/browser_win.cc, atom/browser/notifications/win/notification_presenter_win.cc, atom/browser/ui/views/autofill_popup_view.cc, atom/browser/ui/views/menu_delegate.cc, atom/browser/ui/views/root_view.cc, atom/common/platform_util_win.cc, patches/common/chromium/.patches, patches/common/chromium/disable_custom_libcxx_on_windows.patch
As per @electron/wg-upgrades 
Notes: Upgraded Chromium to 76
=> chore: upgrade chromium to 76

.github/main.workflow
Stem the release check tide of doom.
Notes: none
=> chore: disable release notes GH Action

atom/browser/api/atom_api_session.cc, atom/browser/api/atom_api_session.h
Refactors session.{clearCache,getCacheSize} to use the network service
=> refactor: session.{clearCache,getCacheSize} nws13n

atom/browser/api/atom_api_url_request.cc, atom/browser/api/atom_api_web_contents.cc, atom/browser/atom_browser_client.cc, atom/browser/atom_browser_main_parts.cc, atom/browser/mac/in_app_purchase_observer.mm, atom/browser/net/atom_cert_verifier.cc, atom/browser/net/js_asker.cc, atom/browser/net/js_asker.h, atom/browser/net/url_request_async_asar_job.cc, atom/browser/net/url_request_buffer_job.cc, atom/browser/net/url_request_fetch_job.cc, atom/browser/net/url_request_stream_job.cc, atom/browser/net/url_request_string_job.cc, atom/browser/notifications/platform_notification_service.cc, atom/browser/notifications/win/windows_toast_notification.cc, atom/browser/osr/osr_video_consumer.h, atom/browser/ui/inspectable_web_contents_impl.cc, atom/browser/ui/views/menu_delegate.cc, atom/browser/ui/win/notify_icon.cc, atom/browser/zoom_level_delegate.cc, atom/common/api/atom_api_command_line.cc, atom/common/api/constructor.h, atom/renderer/api/atom_api_spell_check_client.cc, chromium_src/chrome/browser/certificate_manager_model.cc
Continuation of `base::Bind` conversion efforts.
Notes: none
=> chore: convert more files away from base::Bind

docs/tutorial/support.md
Also, use semver terminology instead of "release series".
=> docs: explicitly list supported versions

docs/api/native-image.md
Address https://github.com/electron/electron/issues/18311
=> docs: link to better list of icons for nativeImage.createFromNamedImage()

script/download-circleci-artifacts.js
This PR addresses issue with downloading arm/arm64 assets from CircleCI in Azure Pipelines.
The changes made are:
1. Make sure we pass along token to download from CircleCI
2. Added back off period for retries on downloads.
=> ci: fix issues downloading from CircleCI

lib/browser/api/app.ts
Makes parsing of the commandline line option more robust by using 
- `app.commandLine.hasSwitch()`
- `app.commandLine.getSwitchValue()`
=> refactor: use app.commandLine.getSwitchValue() for parsing --user-data-dir

atom/browser/api/atom_api_in_app_purchase.cc, atom/browser/mac/in_app_purchase_product.h, atom/browser/mac/in_app_purchase_product.mm, docs/api/structures/product.md
Backport of #18720
Notes: none
=> fix: correct isDownloadable docs to match impl

atom/browser/api/atom_api_web_contents.cc, atom/browser/api/atom_api_web_contents.h, atom/browser/common_web_contents_delegate.cc, atom/browser/common_web_contents_delegate.h
Backport of #18736
Notes: fix exiting html fullscreen mode for embedded contents
=> fix: HTML fullscreen request for sub frames (#18736)

script/lib/utils.js, script/prepare-release.js, script/publish-to-npm.js, script/release-artifact-cleanup.js
Backport of https://github.com/electron/electron/pull/18810 and https://github.com/electron/electron/pull/15921.
See those PRs for more details.
Notes: none
=> chore: improve current branch fetching

lib/renderer/init.ts
Just fixing a typo.
Notes: none
=> fix: typo in comment

BUILD.gn
Backport of #18870. See that PR for details.
Notes: Fixed crash when starting with `--disable-gpu`.
=> fix: bundle swiftshader and ANGLE libraries on mac

package.json, script/bump-version.js, yarn.lock
Follow up to https://github.com/electron/electron/pull/18849. Remove unneeded require now that we autogenerate the plist.
Notes: none
=> chore: remove unneeded require

atom/browser/net/url_request_async_asar_job.cc, spec/api-protocol-spec.js
Backport of #18854.
Notes: none
=> fix: sanitize invalid custom protocol headers

spec/api-subframe-spec.js
=> fix: remove unused variables in specs

script/release/uploaders/upload-index-json.py, script/release/uploaders/upload-node-checksums.py, script/release/uploaders/upload-node-headers.py, script/release/uploaders/upload-symbols.py, script/release/uploaders/upload.py
This fixes the currently failing nightly releases
=> build: fix include paths so that __file__ is absolute not relative

docs/api/power-monitor.md
Backport of #19015 see that PR for details
=> docs: fix heading level for power-monitor docs

lib/common/api/deprecate.ts, spec/api-deprecations-spec.js, typings/internal-electron.d.ts
Backport of #19012
Notes: none
=> refactor: improve function deprecation module

spec-main/api-ipc-main-spec.ts
Moves the ipcMain specs to the main process
Notes: none
=> test: move ipcMain spec

docs/tutorial/testing-on-headless-ci.md
Just stumbled across this and wanted to change it.
=> docs: Update incorrect author name

docs/development/build-instructions-gn.md
Just a small improvement to build documentation.
=> docs: Add command to quickly fix the SMBv2 cache

BUILD.gn
Following https://chromium.googlesource.com/chromium/src/+/69.0.3497.128/ui/gl/BUILD.gn#14
Notes: none
=> fix: don't try to generate swiftshader symbols on arm

shell/browser/browser_mac.mm
Refactors RemoveFromLoginItems to not iterate the SharedFileList twice. I have a feeling this fixes #19160 but not 100% sure as i couldn't reproduce the crash locally.
=> refactor: simplify RemoveFromLoginItems

.github/ISSUE_TEMPLATE/Bug_report.md
Add mention of Electron Fiddle in the bug report template.
=> docs: mention fiddle in bug report template

spec-main/index.js
We do this in the remote runner. This hides a bunch of spam.
Notes: none
=> test: disable security warnings in main runner

spec-main/api-browser-window-spec.ts, spec/fixtures/api/sandbox.html
seems like this should have been this way the whole time
Notes: none
=> test: actually test sandbox events in the test that says 'test sandbox events'

spec-main/api-browser-window-spec.ts
this was lost due to a tragic merge incident in #19182
Notes: none
=> test: re-add accidentally deleted test

docs/development/testing.md
CC @jkleinsc 
Adds a note to `testing.md` describing how to install Meiryo on Windows 10 systems. Fixes #19201.
=> docs: describe how to install Meiryo font on Windows 10

script/release/notes/notes.js
Removes all but the most recent Chromium update from release notes. 
Addresses this issue found when generating the `6.0.0` release notes:
```
* Updated Chromium to 72.0.3626.102.
* Updated Chromium to 72.0.3626.107.
* Updated Chromium to 72.0.3626.108.
* Updated Chromium to 72.0.3626.110.
* Updated Chromium to 72.0.3626.90.
* Updated Chromium to 72.0.3626.94.
* Updated Chromium to 72.0.3626.99.
* Updated Chromium to 73.0.3683.41.
* Updated Chromium to 73.0.3683.45.
* Updated Chromium to 73.0.3683.47.
* Updated Chromium to 73.0.3683.48.
* Updated Chromium to 73.0.3683.49.
* Updated Chromium to 73.0.3683.58.
* Updated Chromium to 73.0.3683.61.
* Updated Chromium to 73.0.3683.65.
* Updated Chromium to 73.0.3683.68.
* Updated Chromium to 74.0.3729.27.
* Updated Chromium to 74.0.3729.38.
* …
```
=> chore: omit superceded Chromium updates from notes

spec/webview-spec.js
=> test: disable flaky webview.clearHistory test

build/args/all.gn
Refs: https://github.com/nodejs/node/pull/28774
This is in preparation for branching Electron 7
=> build: update NMV for Electron 7

docs/api/browser-window.md, yarn.lock
=> docs: make setBounds take a Partial<Rectangle>

shell/app/atom_main.cc
Building with `dchecks_always_on=true` in release configuration seems to introduce a crash when content processes exit because the TLS is double-freed, which shows up in the Windows on Arm unit tests as an incorrect exit code. Removing the TLS destruction code (which is only needed in component builds) resolves the flakiness.
This issue affects master, but also affects 6-0-x.
CC: @jkleinsc @MarshallOfSound 
=> fix: remove TLS destruction

docs/api/ipc-main.md
Fixes a link. Enforced by https://github.com/electron/i18n/pull/759. 
Story of this LoC: Worked. Broken. Fixed. Broken again. Worked. Broken. _Today._
cc @HashimotoYT
Notes: none
=> docs: fix broken link in ipcMain docs

docs/api/notification.md, spec-main/api-notification-spec.ts
=> test: move Notification spec to main process

docs/api/browser-window.md, docs/api/touch-bar-button.md, docs/api/touch-bar-scrubber.md, docs/api/touch-bar-segmented-control.md, docs/api/touch-bar.md, spec-main/api-touch-bar-spec.ts
=> test: move the TouchBar specs to the main process

spec-main/api-menu-spec.ts
all aboard the spec-main train 🚅 
Notes: none
=> test: move menu spec to main process

shell/browser/extensions/atom_extension_system.cc, shell/browser/extensions/atom_extension_system.h
https://chromium-review.googlesource.com/c/chromium/src/+/1699223
broke in recent chromium roll.
Notes: none
=> fix: [extensions] remove InitForIncognitoProfile

docs/tutorial/support.md
6.0.x release preparation (https://github.com/electron/electron/projects/20#card-24035642).
cc @sofianguy 
Notes: none
=> docs: update supported versions section

shell/browser/api/atom_api_web_contents.cc
=> build: fix with ENABLE_OSR disabled

spec/api-session-spec.js
Backport of #18751
Notes: none
=> test: add test for invalid cookie url

docs/api/menu-item.md, lib/browser/api/menu-item-roles.js, spec/api-menu-item-spec.js, spec/ts-smoke/electron/main.ts
Backport of https://github.com/electron/electron/pull/19329.
Notes: none
=> doc: add missing MenuItem roles

DEPS, patches/chromium/blink_initialization_order.patch, patches/chromium/blink_local_frame.patch, patches/chromium/blink_world_context.patch, patches/chromium/build_win_disable_zc_twophase.patch, patches/chromium/can_create_window.patch, patches/chromium/cross_site_document_resource_handler.patch, patches/chromium/disable_color_correct_rendering.patch, patches/chromium/disable_user_gesture_requirement_for_beforeunload_dialogs.patch, patches/chromium/exclude-a-few-test-files-from-build.patch, patches/chromium/feat_offscreen_rendering_with_viz_compositor.patch, patches/chromium/frame_host_manager.patch, patches/chromium/gritsettings_resource_ids.patch, patches/chromium/mas_blink_no_private_api.patch, patches/chromium/resource_file_conflict.patch, patches/chromium/scroll_bounce_flag.patch, patches/chromium/ssl_security_state_tab_helper.patch, patches/chromium/worker_context_will_destroy.patch, shell/browser/api/atom_api_session.cc, shell/browser/net/system_network_context_manager.cc, shell/common/api/BUILD.gn, shell/common/api/api.mojom, shell/utility/atom_content_utility_client.cc, shell/utility/atom_content_utility_client.h
So that roller rolls correctly 👍 
=> build: lock chromium major to 78 on 7-0-x

spec-main/api-callbacks-registry-spec.ts
Last test in spec-main, now all are ts!
Notes: none
=> test: tsify callbacks-registry spec

spec-main/api-net-log-spec.ts
incredibly, no doc bugs this time!
Notes: none
=> test: tsify netlog spec

docs/api/ipc-main.md
Update broken link.
Notes: none
=> docs: update link to webContents.send

docs/api/protocol.md
Backport of https://github.com/electron/electron/pull/17759.
Notes: none
=> docs: explanation on using protocols with partitions

docs/api/browser-window.md, spec/api-browser-window-spec.js
Backport of https://github.com/electron/electron/pull/19675.
Notes: none
=> docs: update hasShadow for win and linux

docs/development/build-instructions-windows.md
Stumbled across this "feature" while troubleshooting our Windows env 😏 
ref https://stackoverflow.com/questions/30418886/how-and-why-does-quickedit-mode-in-command-prompt-freeze-applications
cc @erickzhao @MarshallOfSound @nornagon 
Notes: none
=> docs: mention QuickEdit in Windows troubleshooting

shell/browser/api/atom_api_web_request_ns.cc, shell/common/api/atom_api_native_theme.cc
Fix compilation failures due to PRs merged after the Chromium upgrade.
=> fix: compilation failure after chromium upgrade

spec/api-web-contents-view-spec.js, spec/fixtures/api/leak-exit-webcontentsview.js, vsts-arm32v7.yml, vsts-arm64v8.yml
Resolves the issue of the test `WebContentsView new WebContentsView() does not crash on exit` flaking on arm on 5-0-x/
=> ci: fix flaky test on arm (5-0-x)

docs/api/screen.md, docs/fiddles/screen/fit-screen/main.js
Backport of #19759
Notes: none
=> docs: add exemplary fiddle for `launch in fiddle` feat

.github/CODEOWNERS
The DEPS file falls squarely within purview of the Upgrades WG, so they should be requested for review when it changes either by a maintainer's hand or by the roller bot's.
cc @electron/wg-upgrades 
Notes: none
=> ci: upgrades-wg owns DEPS

.circleci/config.yml, BUILD.gn
As we now have resources to do so, we should enable debug builds for macOS.  This PR enables those builds.
=> ci: add macOS debug builds

script/lib/utils.js
If I have to trim one more string....
=> build: trim branch name before comparing to master

docs/api/dock.md
Refs https://github.com/electron/electron/issues/19890.
Clarifies circumstances necessary for `app.dock.bounce` to take effect.
Notes: none
=> docs: clarify dock.bounce usage

spec-main/api-session-spec.ts
This fixes the clearAuthCache test to not depend on the `'login'` event, which is currently broken. Ref https://github.com/electron/electron/issues/19602.
Notes: none
=> test: fix clearAuthCache test

script/lib/utils.js, script/release/prepare-release.js, script/release/release-artifact-cleanup.js, script/release/release.js, script/spec-runner.js
Follow-up to https://github.com/electron/electron/pull/19994#discussion_r318779539.
Simplify unicode characters for readability.
Notes: none
=> build: simplify unicode console output

shell/browser/api/atom_api_url_request_ns.cc, shell/browser/atom_browser_context.cc, shell/browser/atom_browser_context.h, shell/browser/net/atom_url_loader_factory.cc
Backport of https://github.com/electron/electron/pull/19998.
=> chore: cache URLLoaderFactory per-session (7-0-x)

docs/tutorial/boilerplates-and-clis.md
updated boilerplates-and-clis.md in order to more accuratly represent the current availability of templates in electron forge
Notes: Updated list of templates available in electron-forge
=> docs: update boilerplates-and-clis.md

spec-main/api-desktop-capturer-spec.ts
Another remote-using spec down.
Notes: none
=> test: move desktopCapturer spec to main runner

appveyor.yml, azure-pipelines-woa.yml, script/spec-runner.js, script/verify-ffmpeg.py, spec-main/api-app-spec.ts, spec-main/api-web-contents-spec.ts, spec-main/index.js, spec/api-crash-reporter-spec.js, spec/static/index.html
This PR add WOA testing to our CI by running our tests on Windows on Arm hardware
=> ci: run tests on WOA hardware

spec-main/api-desktop-capturer-spec.ts, spec/static/main.js
Don't know if this ever worked...
Notes: none
=> test: fix test for desktopCapturer preventDefault

appveyor.yml, azure-pipelines-woa.yml, script/spec-runner.js, script/verify-ffmpeg.py, spec-main/index.js, spec/api-crash-reporter-spec.js, spec/api-shell-spec.js, spec/api-web-contents-spec.js, spec/static/index.html
Backport of #20031 for 7-0-x.
* ci: run tests on WOA hardware
* Temporarily disable test until #20008 is resolved
* deterministically run tests in sorted order
(cherry picked from commit bedc5f7da9c6785a507bbf7668cfe1d8c23e0141)
Resolves #20097 
=> ci: run tests on WOA hardware (7-0-x)

appveyor.yml, azure-pipelines-woa.yml, script/spec-runner.js, script/verify-ffmpeg.py, spec-main/api-app-spec.ts, spec-main/index.js, spec/api-browser-window-spec.js, spec/api-shell-spec.js, spec/api-web-contents-spec.js, spec/fixtures/api/gpu-info.js, spec/static/index.html
=> ci: test on woa hardware (6-0-x)

shell/common/promise_util.h
Use `base::StringPiece` to specify explicit move in native Promise rejection.
cc @MarshallOfSound @ckerr 
Notes: none
=> refactor: use StringPiece in native Promise rejection

script/release/uploaders/upload-to-github.js
yeah we totally have more than 30....
=> build: get all the release assets when looking for one to delete 

patches/common/chromium/.patches, patches/common/chromium/fix_add_more_checks_in_mojocdmservice.patch
Backport of #20217 
Applies https://chromium.googlesource.com/chromium/src.git/+/b7b305f3389017cc42e2cfac6e7a319f42d5bde3%5E%21/
=> fix: Add more checks in MojoCdmService.

azure-pipelines-woa.yml
=> ci: actually kill leftover processes on WOA testing

shell/browser/api/atom_api_web_contents.cc
=> refactor: move GetCursorBlinkInterval() to a helper function

script/strip-binaries.py
This .so file moved in a recent chromium roll, but I forgot to update this file.
Notes: none
=> chore: update strip-binaries for moved swiftshader.so

shell/browser/ui/cocoa/atom_menu_controller.mm
Fixes https://github.com/electron/electron/issues/20364.
In the past when we constructed our menu through `MainMenu.xib`, we got Chromium's submenu construction defaults for free, which is why prior to `v6.0.0-beta.1` the `recentDocuments` role worked as we intended. The `recentDocuments` NSMenuItem would never have a `nil` submenu, since barring any actual recent documents it had a default `Clear Menu` item (see `.xib` file in linked CL). When they removed their dependence on MainMenu.xib via  [this CL](https://chromium-review.googlesource.com/c/chromium/src/+/1627242) it had the unfortunate side-effect that [this call](https://github.com/electron/electron/blob/eb2d2264d02abd7f34df36809d44752aaf93da93/shell/browser/ui/cocoa/atom_menu_controller.mm#L196-L197) would always return a null …
=> fix: recentDocuments menu role on macOS

script/release/ci-release-build.js
This PR resolves an issue we were seeing with sudowoodo where CircleCI urls were incorrectly being returned as: `https://circleci.com/gh/electron/electron/NaN`.  Basically we were not waiting long enough to get a job number and not validating that a number was returned.
=> ci: verify CircleCI job number before returning job url

docs/tutorial/support.md, docs/tutorial/windows-arm.md
Quick description of how to cross-compile and debug Electron apps for Windows on Arm.
=> docs: add WoA cross-compilation instructions

spec-main/api-net-spec.ts
I'm reviving this because these tests are still flaking out on Windows, so it's not related to #19368. cc @deepak1556 
Ref #19389
Notes: none
=> test: ensure cleanup of net requests in tests

spec/fixtures/module/answer.js, spec/fixtures/pages/resize.html
These files aren't referenced anywhere.
Notes: none
=> test: remove more unused files

spec-main/asar-spec.ts, spec/asar-spec.js
Just moves the relevant tests to the main process.
Notes: none
=> test: remove remote usage from asar spec

docs/api/debugger.md, spec-main/api-debugger-spec.ts
Also fix a minor docs bug.
Notes: none
=> test: move debugger spec to main process

spec-main/api-app-spec.ts, spec-main/api-web-contents-spec.ts
Backport of #20566
Note: use "Hide whitespace changes" when reviewing.
=> test: skip desktopCapturer tests when the feature is disabled

lib/renderer/window-setup.ts
`Map` has better semantics than plain object. Follow up to #20565
=> refactor: use Map for windowProxies in window-setup.ts

docs/api/context-bridge.md
This commit didn't make it to the original PR, quick addition here
=> docs: mark contextBridge as experimental

docs/fiddles/native-ui/drag-and-drop/index.html, docs/fiddles/native-ui/drag-and-drop/main.js, docs/fiddles/native-ui/drag-and-drop/renderer.js
Refs #20442
Adds the Drag and Drop files example from `electron-api-demos` into a runnable Fiddle example.
notes: Added the Drag and Drop files example from `electron-api-demos` into a runnable Fiddle example.
=> docs: Added Drag and drop files Fiddle example

atom/renderer/api/atom_api_renderer_ipc.cc
If the receiver end of the `ElectronBrowser` mojo interface disconnects, we should signal the WaitableEvent to continue execution. 
We are hitting this in the very specific case of a `event.preventDefault()`-ed `nativeWindowOpen` child window with a preload script that sends a synchronous IPC. Because the nativeWindowOpen API is kinda janky, the WebContents is already created by the time we get the preventDefault from the consumer, so we do the only thing we can do: [destroy the WebContents](https://github.com/electron/electron/blob/9bd63864e487532e0adb7d36473fb72d7f83c09a/atom/browser/api/atom_api_web_contents.cc#L578). But the preload script has already started running, interestingly, first _in the opener renderer_, because site isolation may not have forced the new window into its own …
=> fix: don't hang on SendSync if ElectronBrowser receiver is destroyed (6-0-x)

docs/tutorial/support.md
Please do not merge until Oct 22, when 7.0.0 is released
Notes: `no-notes`
=> docs: update currently supported versions for 7.0.0 release

atom/renderer/api/atom_api_renderer_ipc.cc
Missed cleaning up a member variable in when addressing review feedback in #20547
=> chore: remove unused member variable in renderer IPC

DEPS, patches/chromium/add_realloc.patch, patches/chromium/blink_local_frame.patch, patches/chromium/build_fix_when_building_with_enable_plugins_false.patch, patches/chromium/build_gn.patch, patches/chromium/can_create_window.patch, patches/chromium/dcheck.patch, patches/chromium/disable-redraw-lock.patch, patches/chromium/disable_color_correct_rendering.patch, patches/chromium/disable_hidden.patch, patches/chromium/disable_user_gesture_requirement_for_beforeunload_dialogs.patch, patches/chromium/exclude-a-few-test-files-from-build.patch, patches/chromium/expose_setuseragent_on_networkcontext.patch, patches/chromium/frame_host_manager.patch, patches/chromium/mas_no_private_api.patch, patches/chromium/network_service_allow_remote_certificate_verification_logic.patch, patches/chromium/printing.patch, patches/chromium/scroll_bounce_flag.patch, patches/chromium/support_mixed_sandbox_with_zygote.patch, patches/chromium/web_contents.patch, patches/chromium/webview_cross_drag.patch, patches/chromium/worker_context_will_destroy.patch, shell/browser/api/atom_api_url_request_ns.cc
Updating Chromium to 78.0.3904.68.
See [all changes in 78.0.3905.1..78.0.3904.68](https://chromium.googlesource.com/chromium/src/+log/78.0.3905.1..78.0.3904.68?n=10000&pretty=fuller)
Notes: Updated Chromium to 78.0.3904.68.
=> chore: bump chromium to 78.0.3904.68 (7-0-x)

script/lib/utils.js
As in title, some regex updates
=> build: handle -x-y format for getCurrentBranch

docs/README.md
Add the performance checklist from #20230 to the documentation table of contents.
=> docs: add the performance doc to the table of contents

script/check-trailing-whitespace.py, script/lib/patches.py
=> chore: fix formatting of a few Python files

.circleci/config.yml, docs/development/build-instructions-gn.md
=> docs: Update the sccache name

docs/tutorial/performance.md
I noticed some formatting issues while looking over the [performance checklist on the website](https://electronjs.org/docs/tutorial/performance) that I missed during the initial review.
* fix list formatting
* remove unused link ref
=> docs: clean up performance checklist formatting

script/release/ci-release-build.js
This PR lengthens the amount of time the release script waits and the amount of retries when trying to get the build URL for CircleCI release builds.  Also, there is additional logging if the script cannot get the build URL after retrying 10 times.
=> build: lengthen wait times and retries for CircleCI releases

docs/fiddles/system/system-app-user-information/app-information/index.html, docs/fiddles/system/system-app-user-information/app-information/main.js, docs/fiddles/system/system-app-user-information/app-information/renderer.js
=> docs: add app information example

script/release/ci-release-build.js
=> build: allow CircleCI timeout and retry to be set via env variables (7-0-x)

.circleci/config.yml, script/release/ci-release-build.js
This reverts #20893, #20864, #20863, #20852 for 7-0-x as these changes are preventing the 7.0.1 release from going out.
=> ci: Revert CircleCI changes

docs/fiddles/communication/two-processes/synchronous-messages/index.html, docs/fiddles/communication/two-processes/synchronous-messages/main.js, docs/fiddles/communication/two-processes/synchronous-messages/renderer.js
=> docs: add Synchronous Messages Fiddle example

docs/development/coding-style.md
This PR documents an informal standard in our JS around constants.
=> docs: document JS constant naming

script/lint.js
We have a policy that all patches need to come with justification for their existence. This will help us enforce that policy.
Notes: none
=> chore: lint patch descriptions

appveyor.yml
Similar to what was done in #17827, this PR caches the source directory based on the DEPS file and saves it to a file store that is attached to our Windows VMS.  
=> build: speed up windows source retrieval 

docs/api/protocol.md, docs/api/structures/protocol-response-upload-data.md, package.json, spec-main/api-protocol-spec.ts, yarn.lock
=> chore: upgrade ts generator for better type safety

docs/api/touch-bar-button.md, lib/browser/api/touch-bar.js, shell/browser/ui/cocoa/atom_touch_bar.mm
Closes #20903
Notes: Adds ability to disable / enable a `TouchBarButton`
=> feat: allow TouchBarButton instances to be disabled

.circleci/config.yml, spec-main/api-app-spec.ts, spec-main/api-browser-view-spec.ts, spec-main/api-browser-window-spec.ts, spec-main/api-ipc-spec.ts, spec-main/api-web-contents-spec.ts, spec-main/chromium-spec.ts, spec-main/index.js, spec/api-native-image-spec.js, spec/api-remote-spec.js, spec/api-shell-spec.js, spec/api-web-frame-spec.js, spec/asar-spec.js, spec/chromium-spec.js, spec/node-spec.js, spec/static/index.html, spec/static/main.js, spec/webview-spec.js
Let's split our tests into a few nice slices, courtesy of CircleCI.
Speeding up the build is hard, slicing the tests is easy 🤷‍♂ 
=> build: speedy tests on circle by splitting the test files into multiple jobs

docs/tutorial/performance.md
=> docs: correct the syntax to caniuse.com link

docs/tutorial/installation.md
Closes https://github.com/electron/electron/issues/20841
=> docs: use new China's mirror address

shell/common/gin_converters/content_converter.cc
=> refactor: simplify Converter<content::PermissionType>::ToV8

spec/webview-spec.js
Fixes CI issue introduced by #20825
=> test: skip flaky <webview>.capturePage() test on Windows

docs/api/structures/ipc-main-event.md
=> docs: document the channel param for `event.reply`

.circleci/config.yml
This resolves the issue where we are running out of space on MacOS for release builds, eg https://circleci.com/gh/electron/electron/401721
=> build: delete unneeded files when running a release

native_mate/native_mate/function_template.h, shell/browser/api/atom_api_menu.cc, shell/browser/api/atom_api_menu.h, shell/browser/api/atom_api_menu_mac.h, shell/browser/api/atom_api_menu_mac.mm, shell/browser/api/atom_api_menu_views.cc, shell/browser/api/atom_api_menu_views.h, shell/browser/ui/cocoa/atom_menu_controller.h, shell/browser/ui/cocoa/atom_menu_controller.mm, spec-main/api-menu-spec.ts
Backport of #21169.
Notes: Fix context menu disappearing when showing.
=> fix: menu should not be garbage-collected when popuping (7-1-x)

.circleci/config.yml, DEPS, appveyor.yml
Resolves the issue of our download external binaries script failing with a newer depot tools.
=> ci: use system python to download external binaries

.circleci/config.yml, script/add-debug-link.py, script/copy-debug-symbols.py, script/lib/config.py, script/lib/util.py, script/release/release.js, script/release/uploaders/upload.py, script/strip-binaries.py, script/zip-symbols.py
Backport of #18676, see that PR for details.
Notes: Generate debug symbols on Linux.
=> ci: generate debug symbols on Linux

docs/api/menu-item.md
=> docs: fix duplicate "close"

docs/tutorial/installation.md
=> docs: Update installation.md

patches/common/chromium/.patches, patches/common/chromium/mas_disable_custom_window_frame.patch, patches/common/chromium/mas_disable_remote_accessibility.patch, patches/common/chromium/mas_disable_remote_layer.patch, patches/common/chromium/mas_disable_spi_file_type_mappings.patch
Backport of #20965.
Notes: Fix Electron apps getting rejected to Mac App Store.
=> fix: disable more private macOS APIs in MAS build (5-0-x)

patches/common/chromium/.patches, patches/common/chromium/mas_disable_custom_window_frame.patch, patches/common/chromium/mas_disable_remote_accessibility.patch, patches/common/chromium/mas_disable_remote_layer.patch, patches/common/chromium/mas_disable_spi_file_type_mappings.patch
Backport of #20965.
Notes: Fix Electron apps getting rejected to Mac App Store.
=> fix: disable more private macOS APIs in MAS build (6-1-x)

lib/browser/guest-window-manager.js
=> fix: enforce parent-child relationship in custom postMessage() handler

lib/browser/api/web-contents.js, lib/browser/guest-window-manager.js
=> refactor: export internalWindowOpen from guest-window-manager

docs/api/web-contents.md
References: https://github.com/electron/electron/pull/16795 https://github.com/electron/electron/pull/17907
=> docs: update webContents.printToPDF() example for promisified API

appveyor.yml
attempting to fix e.g. https://ci.appveyor.com/project/electron-bot/electron-ljo26/builds/29608768
Notes: none
=> ci: retry uploading pdb files on appveyor

script/lib/utils.js
Make pattern more robust to avoid edge cases like the ones we're seeing on 8.
Notes: none
=> chore: make release branch pattern more robust

docs/api/shell.md
Closes https://github.com/electron/electron/issues/21623.
Refs https://github.com/electron/governance/blob/master/wg-api/spec-documents/shell-openitem.md.
Corrects documentation to align with spec and actual behavior.
Notes: none
=> docs: fix shell.openPath documentation

LICENSE
This PR is an update of the license to include the current year.
=> fix: update license year

docs/tutorial/devtools-extension.md
Update react devtool version in document, this way people can just copy paste the code snippet without spending time debugging which one is the correct version number.
=> docs: Update react devtool version in document

build/args/goma.gn, docs/development/goma.md, script/external-binaries.json, script/update-external-binaries.py
Initial work at documenting Goma usage, please note that it doesn't actually work yet 😆We're working on it.
=> build: document goma usage and add the external binaries

spec-main/api-web-contents-spec.ts, spec-main/visibility-state-spec.ts
Add retries for a few flaky tests.
=> test: retry for a few flaky tests

docs/fiddles/windows/manage-windows/frameless-window/index.html, docs/fiddles/windows/manage-windows/frameless-window/main.js, docs/fiddles/windows/manage-windows/frameless-window/renderer.js, docs/fiddles/windows/manage-windows/manage-window-state/index.html, docs/fiddles/windows/manage-windows/manage-window-state/main.js, docs/fiddles/windows/manage-windows/manage-window-state/renderer.js, docs/fiddles/windows/manage-windows/window-events/index.html, docs/fiddles/windows/manage-windows/window-events/main.js, docs/fiddles/windows/manage-windows/window-events/renderer.js
Refs #20442
Adds Window Management 👇🏼
✅ Frameless window
✅ Manage window state
✅ Window events
Fiddle example.
Notes: Adds Window Management (frameless window, manage window state, and window events) Fiddle example.
=> docs: Adds Window Management (frameless window, manage window state, and window events) Fiddle example

.circleci/config.yml, appveyor.yml, script/external-binaries.json, script/start-goma.ps1
This PR updates our Windows and Linux CI to use goma to speed up compilation.
=> ci: use goma for windows and linux builds

script/verify-mksnapshot.py
Fixes failing mksnapshot tests, eg: https://circleci.com/gh/electron/electron/443219
=> test: specify target arch on mksnapshot

docs/development/testing.md
=> docs: details to run unit tests on Windows

docs/api/browser-window.md
=> docs: sandbox is not experimental 

docs/tutorial/offscreen-rendering.md
=> docs: offscreen-rendering - missing word "is"

docs/development/debugging-instructions-macos.md
Update docs to add a critical step for source mapping in lldb on macOS.
=> docs: add .lldbinit to macOS debugging docs

docs/api/native-theme.md, lib/browser/navigation-controller.js, shell/browser/api/atom_api_web_contents.cc, shell/browser/native_window_mac.mm, spec-main/chromium-spec.ts
=> fix: spelling errors

script/lint.js, shell/browser/mac/atom_application_delegate.mm, shell/browser/native_window_mac.mm, shell/browser/ui/cocoa/atom_bundle_mover.mm, shell/browser/ui/cocoa/atom_menu_controller.mm, shell/browser/ui/cocoa/atom_touch_bar.mm
=> chore: fix linter errors in .mm files

.circleci/config.yml, appveyor.yml, script/verify-chromedriver.py
Closes #21968
Adds a script that tries to execute the Electron ChromeDriver executable and checks if its output is correct.
For the CI bits, I kind of kept adding steps to jobs until it turned green, so when reviewing, please watch out for unnecessary steps in the CI 🙇.
=> ci: verify chromedriver

docs/tutorial/support.md
Please do not merge until Feb 4, when 8.0.0 stable gets released.
Notes: `no-notes`
=> docs: update currently supported versions for 8.0.0 release

.circleci/config.yml
Backport of #21994.
Notes: none
=> ci: fix ELECTRON_OUT_DIR

shell/common/gin_helper/wrappable.cc
Recently CI fails frequently due to crashes caused by JS code running inside weak callback, this PR fixes the crash by delaying deletion of native object to next tick.
This only affects native object's lifetime during garbage collection, and I'm confident that it would not cause side effects.
```
#
#
#
#
#FailureMessage Object: 0xffaf6ec0Received signal 4 ILL_ILLOPN 00005da9eeff
#0 0x00005bfaf11f base::debug::CollectStackTrace()
#1 0x00005beda052 base::debug::StackTrace::StackTrace()
#2 0x00005bfaed3f base::debug::(anonymous namespace)::StackDumpSignalHandler()
#3 0x0000f7f040a0 ([vdso]+0x109f)
#4 0x00005da9eeff v8::base::OS::Abort()
#5 0x00005da98bcb V8_Fatal()
#6 0x00005da987a6 v8::base::(anonymous namespace)::*******DcheckHandler()
#7 0x00005da98bf3 V8_Dcheck()
#8 0x000059c613fa …
```
=> fix: delay deletion of Wrappable objects

shell/browser/printing/print_preview_message_handler.cc
Backport of https://github.com/electron/electron/pull/22013.
Notes: none.
=> chore: wrap cb with default invocation

.circleci/config.yml, appveyor.yml, script/start-goma.ps1
This PR adds goma to our macOS CI and also enables cache only Goma for PRs coming from forks.
=> ci:  enable goma for all testing builds

script/spec-runner.js
This PR enables native unit tests once again.  It turns out that they work properly on Windows with our latest VM without requiring any code changes to the tests.
=> test: get native unit tests running

.circleci/config.yml, script/strip-binaries.py
Followup to #22070:  That PR didn't copy the file to the right location.  This PR fixes that.  Release builds were triggered to verify that this fixes the release issue.
=> build: copy chromedriver to correct location

lib/renderer/api/remote.js
This was accidentally left in and should be removed.
Notes: none
=> chore: remove debugging log

atom/browser/api/atom_api_menu.cc
Backport of https://github.com/electron/electron/pull/19427.
Notes: Fix a potential issue with active Menu garbage collection.
=> fix: keep references to active menus created by api Menu

.circleci/config.yml, script/release/ci-release-build.js
This PR speeds up our release process by using CircleCI workflows to separate our source checkout and building steps.  This allows us to use a faster linux machine on mac checkouts and also makes reruns faster as we don't have to checkout the code again.
=> ci: Speed up release

shell/browser/native_window_mac.mm
Backport of https://github.com/electron/electron/pull/22121.
Notes: none.
=> refactor: use NSVisualEffectMaterial* constants directly

build/args/all.gn
=> chore: update NMV for Electron 10

build/args/all.gn
Was following the process and realized my commit to do this got lost at some point during me making the branch
=> chore: update NMV for Electron 9

.circleci/config.yml, appveyor.yml, script/start-goma.ps1
Backport of #21992.
(cherry picked from commit e7982623ecef502cb98b795cb3e15a52644cc70b)
=> ci: enable goma for all testing builds

script/release/notes/notes.js
Release lines that use libcc are long since EOL, so we should no longer take that potential into account.
cc @ckerr @MarshallOfSound 
Notes: none
=> chore: remove libcc from release note generator

.circleci/config.yml, script/release/ci-release-build.js
CircleCI is deprecating the v1.1 API we use for releases in March: https://circleci.com/blog/a-deprecation-notice-on-job-triggering-with-api-v1-1/.  This PR updates our older branches to use the new v2 API so that releases will still work on older branches once the 1.1 API is no longer available.
=> ci: update to CircleCI v2 config and APIs

spec-main/fixtures/chromium/spellchecker.html, spec-main/spellchecker-spec.ts
Let's make sure we don't break this again, just some simple E2E spellchecker tests
=> chore: add tests for the spellchecker

DEPS, patches/chromium/can_create_window.patch, patches/chromium/chore_use_electron_resources_not_chrome_for_spellchecker.patch, patches/chromium/command-ismediakey.patch, patches/chromium/disable_color_correct_rendering.patch, patches/chromium/disable_hidden.patch, patches/chromium/expose_setuseragent_on_networkcontext.patch, patches/chromium/feat_add_support_for_overriding_the_base_spellchecker_download_url.patch, patches/chromium/feat_allow_disbaling_blink_scheduler_throttling_per_renderview.patch, patches/chromium/fix_add_executable_to_chromedriver_s_rpath_for_electron_8.patch, patches/chromium/fix_route_mouse_event_navigations_through_the_web_contents_delegate.patch, patches/chromium/mas_disable_remote_layer.patch, patches/chromium/mas_no_private_api.patch, patches/chromium/network_service_allow_remote_certificate_verification_logic.patch, patches/chromium/web_contents.patch
Notes: Updated Chromium to 80.0.3987.128.
=> chore: bump chromium to 80.0.3987.128

shell/app/node_main.cc
In ongoing efforts to match `ELECTRON_RUN_AS_NODE` as closely as possible to Node.js main instance execution, we should ensure that that scopes we have in place are correct.
cc @MarshallOfSound @zcbenz @nornagon 
Notes: none
=> chore: ensure correct scopes are in place

shell/browser/net/proxying_url_loader_factory.cc, shell/browser/net/proxying_url_loader_factory.h, spec-main/api-web-request-spec.ts
Close https://github.com/electron/electron/issues/22242.
Recent Chromium upgrade has changed how CORS requests are handled, this PR updates our webRequest implementation to correctly handle CORS preflight requests.
Notes: Fix `webRequest` not working for CORS requests.
=> fix: make webRequest work for CORS preflight requests

spec-main/spellchecker-spec.ts
The spellchecker tests are flaky on arm CI.
=> test: give arm machines more time to load spellchecker

docs/api/browser-window.md, shell/browser/api/electron_api_top_level_window.cc, shell/browser/api/electron_api_top_level_window.h, shell/browser/native_window.h, shell/browser/native_window_mac.h, shell/browser/native_window_mac.mm, spec-main/api-browser-window-spec.ts
Backport of #22533.
Notes: Added ability to set and get title bar traffic light position on the fly (macOS).
=> feat: programmatically modify traffic light positioning

docs/api/browser-window.md, shell/browser/api/electron_api_top_level_window.cc, shell/browser/api/electron_api_top_level_window.h, shell/browser/native_window.h, shell/browser/native_window_mac.h, shell/browser/native_window_mac.mm, spec-main/api-browser-window-spec.ts
Backport of #22533
Notes: Added ability to set and get title bar traffic light position on the fly (macOS).
=> feat: programmatically modify traffic light positioning (#22533)

appveyor.yml
This PR is a followup to #22538.  Unfortunately that PR didn't fix the underlying issue, but this one does.
=> ci: fix windows source cache

script/lib/utils.js
One day these scripts will be flawless, today is not that day
=> build: update release scripts to handle a remote master

.circleci/config.yml, appveyor.yml, script/start-goma.ps1
This PR adds Goma to our older releases.  This is needed so that we can use smaller machines for building on Windows.
=> ci: Add goma to older branches

package.json, yarn.lock
Upgrade to new version of asar, testing with the Electron testsuite per https://github.com/electron/asar/pull/191#issuecomment-590115339
CC: @MarshallOfSound 
=> build: upgrade asar to a version that requires Node 10

lib/browser/api/view.js, lib/browser/api/views/image-view.js, lib/browser/api/web-contents-view.js
Some code are no longer needed.
Notes: none
=> chore: remove unused code in View's JS file

docs/api/app.md
Explain what the method actually does.
Notes: none
=> docs: clarify app.enableSandbox documentation

.gitattributes
Hopefully this will reduce patch conflicts in .patches files. Not sure if github understands it but it's worth a shot!
Notes: none
=> build: set merge=union for .patches

docs/api/shell.md
=> docs: note that shell can't be used in sandboxed renderers

script/release/uploaders/upload.py
When zip contains files larger than 4GB, 4bytes length headers are
not sufficient anymore. Zip64 defines an extra header 0x0001 which
may contain 8byte lengthed (16 exabytes) lengths [uncompressed and compressed].
Read this value when performing extra data cleaning and override the
bogus value if the header is available.
Read https://blog.yaakov.online/zip64-go-big-or-go-home/ for more
information on Zip64 extra header.
This is the first known implementation of zip64 stripping.
This change was needed since electron CI explicitly enable zip64
and some files inside these zips may exceed the maximum zip file size (4GB).
This is particularly true on Linux when debuggings symbols are enabled.
Cc: @nornagon @ikkisoft @jkleinsc 
=> build: implement zip64 stripping

docs/api/system-preferences.md
As in title, check the TS diff if you want to see the change
=> docs: fix type definition for setUserDefault

spec-main/api-system-preferences-spec.ts
Regression from https://github.com/electron/electron/pull/23002
https://circleci.com/gh/electron/electron/517401#tests/containers/1
Notes: none
=> chore: fix type check in systemPreferences module specs

shell/browser/api/electron_api_web_contents.cc, shell/browser/api/electron_api_web_contents.h, spec-main/api-web-contents-spec.ts
Backport of #21497
Notes: Added workaround for nativeWindowOpen hang.
=> fix: workaround for hang when preventDefault-ing nativeWindowOpen

script/lib/patches.py
Backport of #23070. See that change for details.
Notes: none
=> build: improve patch filename remembering

spec-main/api-web-contents-spec.ts
Backport of #23187
Notes: none
=> test: fix type errors in devToolsWebContents

lib/browser/guest-window-manager.js
=> fix: do not double-declare webPreferences

lib/renderer/api/ipc-renderer.ts, lib/renderer/ipc-renderer-internal.ts
=> fix: do not mutate ipc instances across contexts

script/doc-only-change.js
This PR updates our check for doc only changes to handle the use case where the GitHub API reports no files for a PR.  It shouldn't happen but if it does we should assume that the change is more than doc changes just to be safe.
Notes: none
=> ci: robustify doc only change check

spec-main/api-crash-reporter-spec.ts
Broken in #23178 but I ignored the warnings 😞
Notes: none
=> test: fix crashReporter test on woa

docs/api/app.md
more descriptions on second-instance event.
Notes: none
=> docs: update description on second-instance event.

shell/app/electron_content_client.cc, shell/app/uv_task_runner.h, shell/browser/javascript_environment.h, shell/common/api/electron_bindings.h, shell/common/electron_command_line.cc, shell/common/node_bindings.h, shell/renderer/renderer_client_base.h
=> style: use build/include_directory for NOLINT (#23266)

filenames.auto.gni, lib/browser/api/web-contents.js, lib/isolated_renderer/init.js, lib/renderer/api/context-bridge.ts, lib/renderer/window-setup.ts, shell/renderer/api/electron_api_context_bridge.cc, shell/renderer/api/electron_api_context_bridge.h, shell/renderer/electron_renderer_client.cc, shell/renderer/electron_sandboxed_renderer_client.cc, spec-main/api-context-bridge-spec.ts, spec/chromium-spec.js, spec/fixtures/pages/window-open-postMessage.html
Backport of #23194
Backport of #23235
See those PRs for details.
=> refactor: port window-setup to use ctx bridge instead of being run in the main world

lib/renderer/window-setup.ts
=> fix: do not add 104 to the history length

lib/browser/rpc-server.js, lib/sandboxed_renderer/init.js
Follow-up to #23340
Notes: none
=> chore: remove unused ELECTRON_GET_CONTENT_SCRIPTS ipc handler

docs/tutorial/performance.md
Fix markdown list item formatting error
Notes: none
=> docs: fix markdown list item formatting error

spec-main/crash-spec.ts, spec-main/fixtures/crash-cases/early-in-memory-session-create/index.js
=> chore: fix linting

shell/browser/api/electron_api_system_preferences_mac.mm
Refactor as suggested in #22193
cc @zcbenz
Notes: none
=> refactor: SystemPreferences::SetUserDefault

spec-main/api-browser-window-spec.ts, spec-main/node-spec.ts, spec/webview-spec.js
Fix conditions for a few tests.
Notes: none
=> test: fix conditions for some tests

spec-main/api-browser-window-spec.ts, spec/webview-spec.js
Backport of #23489
Notes: none
=> test: fix conditions for some tests  (#23489)

shell/common/api/electron_api_v8_util.cc
=> fix: expose v8util.createIDWeakMap() regardless of enable_remote_module

filenames.gni, shell/browser/ui/file_dialog_win.cc, shell/browser/ui/message_box_win.cc, shell/browser/ui/win/dialog_thread.cc, shell/browser/ui/win/dialog_thread.h
Backport of #23495
Notes: none
=> fix: do not destroy thread in UI thread

docs/api/browser-window.md, filenames.auto.gni, lib/browser/guest-view-manager.js, lib/browser/guest-window-manager.js, shell/browser/web_contents_preferences.cc, shell/common/options_switches.cc, shell/common/options_switches.h, shell/renderer/content_settings_observer.cc, spec-main/chromium-spec.ts, spec/fixtures/pages/storage/web_sql.html
Backport of #23311
Notes: enableWebSQL is a new webpreference option to enable/disable websql api
=> feat: add enableWebSQL webpreference

spec-main/api-web-contents-spec.ts
This test has been flaky for ages. I don't know how to fix it. This will at least save me retrying CI endlessly.
Notes: none
=> test: retry beforeunload test

filenames.auto.gni, lib/browser/api/net.ts, spec-main/api-net-spec.ts, typings/internal-ambient.d.ts
look all i'm saying is,,, it compiles
Notes: none
=> refactor: tsify net module

spec-main/api-browser-window-spec.ts
Trying to fight the flake.
Notes: none
=> test: add retries to another beforeunload test

docs/tutorial/support.md
~~Please do not merge until **May 19th**, when 9.0.0 stable is released.~~ We can merge this as soon as today if we want to
Notes: 'none'
=> docs: update currently supported versions for 9.0.0 release

spec-main/webview-spec.ts
To make it more pleasant to run these tests locally.
Notes: none
=> test: hide child windows in webview spec

script/release/notes/index.js
=> fix: support 10-x-y in the release notes generator

docs/api/service-workers.md, docs/api/web-contents.md, docs/api/webview-tag.md
Added explanations for parameters of the `console-message` event.
Notes: none
=> docs: Explain console-message parameters

lib/renderer/init.ts, lib/sandboxed_renderer/init.js
Quick clean up of this unused global
Notes: none
=> chore: remove unused isolated-world-args

spec-main/api-app-spec.ts, spec-main/api-browser-window-spec.ts, spec-main/api-ipc-spec.ts
Backport of #23675 
Notes: none
=> test: call "expect()" on a correct call stack

spec-main/node-spec.ts, spec/fixtures/module/delay-exit.js
Add more logging in node inspector test, it is still flaky.
Notes: none
=> test: more logging in node inspector test

spec-main/node-spec.ts
An attempt to make the node inspector test less flaky.
Notes: none
=> test: return after inspector connection is closed

shell/browser/mac/electron_application_delegate.mm
When application is activated thru macOS app switcher (cmd+tab) the App's activate event is note emitted. [Here](https://gist.github.com/isnotgood/5ad90ba50f45ad26be052de8646fdb1b) is Electron Fiddle with steps to repro (tested on macOS 10.15.4). 
The reason is that `applicationShouldHandleReopen:hasVisibleWindows:` is sent only when app
is activated via Dock not the other ways like app switcher. Using `applicationDidBecomeActive:` is handling all the cases properly. Also to maintain backward compatibility I added logic to avoid firing 'activate' event after the application launch.
Notes: none
=> fix: trigger activate event when app is activated via app switcher

spec-main/index.js, spec/static/get-files.js, spec/static/index.html
Backport of #23774
Notes: none
=> test: refactor how spec files are collected

lib/browser/remote/server.ts, lib/common/type-utils.ts, lib/renderer/api/remote.js, spec-main/api-remote-spec.ts
Backport of https://github.com/electron/electron/pull/23693.
Backport of https://github.com/electron/electron/pull/23759.
See those PRs for more info.
Notes: Ensured proper nativeImage serialization between renderer and browser processes via remote.
=> fix: ensure nativeImage serialization main->renderer

filenames.auto.gni, lib/sandboxed_renderer/init.ts, script/gen-filenames.js, typings/internal-ambient.d.ts
Does what it says on the tin, converts the sandboxed renderer init script to TS
Notes: none
=> chore: tsify sandboxed init

build/webpack/webpack.config.base.js, package.json, spec-main/api-desktop-capturer-spec.ts, yarn.lock
Backport of #23864
Notes: none
=> build: fix for "enable_desktop_capturer = false"

lib/sandboxed_renderer/init.ts
Low hanging fruit, a whole millisecond 😆 These modules can be lazily loaded instead of paying the cost on page load
Notes: none
=> perf: lazily load some modules in sandbox mode

.github/PULL_REQUEST_TEMPLATE.md
Just to help us all remember :)
Notes: none
=> chore: note quiet period in PR template

docs/api/app.md
=> docs: default of allowRendererProcessReuse is true

patches/chromium/disable_unnecessary_ischromefirstrun_check.patch
=> chore: update tracking bug for disable_unnecessary_ischromefirstrun_check.patch

shell/renderer/api/electron_api_ipc_renderer.cc, spec-main/api-ipc-renderer-spec.ts
... instead of crashing.
This fixes a possible segfault that was introduced [here](https://github.com/electron/electron/pull/23321/files#diff-c330abcb8a74593f6eced7f04ff261fcR67). This crash could happen if the `ipcRenderer` module was used after the context was released.
This change makes this pattern throw a JS error instead of crashing.
I'm not convinced that this is the right behavior, ultimately. The initial fix in #23321 works around a memory leak that can happen if the main process leaks an `invoke` promise without resolving it. I think that #23321 is potentially preventing legitimate uses that retain the context after blink has released it, though I don't have any concrete examples. We should consider reverting #23321 and leaving it up to apps to resolve their own memory leaks …
=> fix: throw when using ipcRenderer after context released

spec-main/api-ipc-renderer-spec.ts
I'm not sure what event to hook here, so poll instead.
Notes: none
=> test: reduce flakiness of post-context-release ipc test

docs/api/structures/trace-config.md, script/lint.js, shell/browser/plugins/plugin_utils.cc, shell/renderer/electron_renderer_pepper_host_factory.cc
=> chore: use more inclusive language in a few places

docs/api/app.md, docs/api/modernization/property-updates.md, lib/browser/api/app.ts, shell/browser/api/electron_api_app.cc, spec-main/api-app-spec.ts
Backport of https://github.com/electron/electron/pull/22713.
Notes: none.
=> chore: update app module property support

docs/api/download-item.md, docs/api/native-image.md, docs/api/system-preferences.md, lib/browser/api/system-preferences.ts, lib/common/api/native-image.js, shell/browser/api/electron_api_system_preferences.cc, shell/common/api/electron_api_native_image.cc, spec-main/api-system-preferences-spec.ts, spec/api-native-image-spec.js
Backport of #22688
Notes: none
=> chore: more modules to dual prop/fn support

spec-main/api-remote-spec.ts
This adds a test for a GC race which can occur in `remote`, that is worked
around by refcounting on the server side.
Notes: none
=> test: add test for gc race in remote

shell/common/api/electron_api_v8_util.cc, spec-main/api-browser-window-spec.ts, spec-main/api-menu-spec.ts, typings/internal-ambient.d.ts
WeakRef is better :)
Notes: none
=> chore: remove test usages of createIDWeakMap

script/update-external-binaries.py
A nightly failed due to a network blip, we can be nicer here and rety
=> build: retry external binary downloads a few times

default_app/main.ts
Mostly uplifted from how node does it
=> chore: expose electrons built in modules in the REPL along with nodes

filenames.auto.gni, lib/browser/remote/server.ts, lib/browser/rpc-server.ts, spec-main/api-browser-window-spec.ts, spec-main/chromium-spec.ts, typings/internal-electron.d.ts
Just tsifying more stuff.
Notes: none
=> chore: convert rpc-server to ts

filenames.auto.gni, lib/browser/chrome-extension-shim.ts, lib/common/api/deprecate.ts, typings/internal-electron.d.ts
=> chore: tsify extensions shim

spec-main/api-app-spec.ts, spec-main/api-auto-updater-spec.ts, spec-main/api-browser-view-spec.ts, spec-main/api-browser-window-spec.ts, spec-main/api-content-tracing-spec.ts, spec-main/api-crash-reporter-spec.ts, spec-main/api-debugger-spec.ts, spec-main/api-menu-item-spec.ts, spec-main/api-power-monitor-spec.ts, spec-main/api-protocol-spec.ts, spec-main/api-remote-spec.ts, spec-main/api-session-spec.ts, spec-main/api-web-contents-spec.ts, spec-main/asar-spec.ts, spec-main/chromium-spec.ts, spec-main/modules-spec.ts, spec-main/node-spec.ts, spec-main/spec-helpers.ts, spec-main/spellchecker-spec.ts, spec/api-web-frame-spec.js, spec/asar-spec.js, spec/chromium-spec.js, spec/node-spec.js, spec/spec-helpers.js, spec/webview-spec.js
=> test: make sure tests fail properly instead of timing out

docs/api/app.md
=> chore: add missing _Deprecated_ to 'renderer-process-crashed' on app

patches/chromium/.patches, patches/chromium/backport_1019161.patch, patches/chromium/backport_1063177.patch
Backports following to M80:
- [1063177](https://bugs.chromium.org/p/chromium/issues/detail?id=1063177) ([CL](https://chromium-review.googlesource.com/c/chromium/src/+/2111393/))
- [1019161](https://bugs.chromium.org/p/chromium/issues/detail?id=1019161) ([CL](https://chromium-review.googlesource.com/c/chromium/src/+/2125690))
Notes: backported fixes for UAF in extensions (CVE-2020-6454 and NOCVE)
=> chore: backport Chromium fixes

DEPS
=> build: use python3 for electron hooks

package.json, yarn.lock
=> build: update ts defs generator

.circleci/config.yml
=> build: fix bad 'when' clause

package.json, spec-main/video-helpers.js, yarn.lock
=> build: update webpack / TS build deps

default_app/index.html, filenames.gni, package.json, yarn.lock
Next in line for dependency updates is octicons, some icons were renamed / redesigned so I found the new equivs.
=> build: update octicons

filenames.auto.gni, lib/worker/init.ts
=> build: tsify worker/init

build/webpack/get-outputs.js, build/webpack/run-compiler.js, build/webpack/webpack.config.base.js, build/webpack/webpack.config.browser.js, build/webpack/webpack.config.isolated_renderer.js, build/webpack/webpack.config.renderer.js, build/webpack/webpack.config.sandboxed_renderer.js, build/webpack/webpack.config.worker.js, script/lint.js
Noticed this folder wasn't being linted 🤷  now it is 😄 
=> build: run the JS linter on the build folder

.circleci/config.yml
=> build: free up more space on the mac VM

patches/v8/.patches, patches/v8/backport_1084820.patch
[1084820] [High] [CVE-2020-6512]: DCHECK failure in value.IsHeapObject() in objectsdebug.cc
Backport https://chromium.googlesource.com/v8/v8.git/+/c16f62d6e943756d8b4170a36f61e666ced82e6d
Notes: fix: DCHECK failure in value.IsHeapObject() in objectsdebug.cc. (Chromium security issue 1084820)
=> chore: cherry-pick fix from chromium issue 1084820

patches/config.json, patches/skia/.patches, patches/skia/backport_1080481.patch
[[1080481](https://crbug.com/1080481)] [**Medium**] [CVE-2020-6523]: Security: Skia: Integer Overflow in GrTextBlob::Make
Backport https://skia.googlesource.com/skia.git/+/8d2ebfffaf6ece9a7e9839dca2d7907f241c3460
Notes: fix: integer overflow in GrTextBlob::Make. (Chromium security issue 1080481)
=> chore: cherry-pick fix from chromium issue 1080481

docs/api/auto-updater.md, spec-main/api-auto-updater-spec.ts, spec-main/api-autoupdater-darwin-spec.ts, spec-main/fixtures/auto-update/check-with-headers/index.js, spec-main/fixtures/auto-update/check-with-headers/package.json, spec-main/fixtures/auto-update/update-json/index.js, spec-main/fixtures/auto-update/update-json/package.json
Adds more test coverage of squirrel.mac / the macOS auto updater.  Will increase confidence in future changes.
=> test: add more auto updater tests for squirrel.mac

docs/api/session.md
Fixes #23609 . Descriptions of various types of permissions are intended included in the documentation via this PR.
@erickzhao Please review.
Notes: none
=> docs: add descriptions for types of permissions

docs/api/menu.md
Fix typos in role values for some menu items. They must have changed since the docs were originally made.
Notes: none
=> doc: Fix typos in MenuItem role values

script/release/uploaders/upload.py
Edge condition for the new arm64 darwin builds
=> build: upload x-compiled arm mksnapshot only on linux

docs/tutorial/recent-documents.md
docs: Solving issue #22018, adapting the additions made by PR #11166, i.e. adding documentation for adding menu-item for opening recent files.
Notes: none.
=> docs: Adding Documentation for Open Recent Menu-item

docs/tutorial/recent-documents.md
=> build: fix linting issue in docs

shell/app/resources/mac/loginhelper-Info.plist, shell/browser/resources/mac/Info.plist, shell/common/resources/mac/Info.plist, shell/renderer/resources/mac/Info.plist
Electron crashes under rosetta, we should prevent execution under rosetta.
Refs: #24319  
=> fix: disable rosetta as Electron does not run under rosetta

.circleci/config.yml
=> build: only move folder if it exists when freeing space

lib/browser/api/system-preferences.ts, shell/browser/api/electron_api_system_preferences.cc, shell/browser/api/electron_api_system_preferences.h, shell/browser/api/electron_api_system_preferences_mac.mm, shell/browser/api/electron_api_system_preferences_win.cc, spec-main/api-system-preferences-spec.ts
=> refactor: ginify SystemPreferences

lib/browser/api/auto-updater/auto-updater-native.ts, shell/browser/api/electron_api_auto_updater.cc, shell/browser/api/electron_api_auto_updater.h, shell/browser/auto_updater.cc, shell/browser/auto_updater.h, shell/browser/auto_updater_mac.mm
=> refactor: ginify autoUpdater

lib/browser/api/app.ts, shell/browser/api/electron_api_app.cc, shell/browser/api/electron_api_app.h, shell/browser/api/electron_api_app_mas.mm, shell/browser/browser.cc, shell/browser/browser.h, shell/browser/browser_linux.cc, shell/browser/browser_mac.mm, shell/browser/browser_win.cc
=> refactor: ginify app

spec-main/index.js
Stops infinitely hung builds
E.g. https://ci.appveyor.com/project/electron-bot/electron-ljo26/builds/34349651
=> spec: fail tests if the spec runner promise rejects

shell/common/api/electron_api_asar.cc
Straightforward refactor.
Notes: none
=> refactor: ginify Archive

script/release/uploaders/upload-symbols.py
=> build: only do the lower case symbol copy on case sensitive file systems

script/release/release.js, script/release/uploaders/upload-to-github.js
Fixes the nightly release upload
=> build: upload the file stream not a JSON blob for the read stream

patches/chromium/command-ismediakey.patch, patches/chromium/crash_allow_setting_more_options.patch, patches/chromium/disable_compositor_recycling.patch, patches/chromium/fix_provide_axtextchangevaluestartmarker_a11y_value_change.patch, patches/chromium/fix_use_the_new_mediaplaypause_key_listener_for_internal_chrome.patch, patches/chromium/mas-cfisobjc.patch, patches/chromium/mas_blink_no_private_api.patch, patches/chromium/mas_disable_custom_window_frame.patch, patches/chromium/mas_disable_remote_accessibility.patch, patches/chromium/mas_disable_remote_layer.patch, patches/chromium/mas_no_private_api.patch, patches/chromium/render_widget_host_view_mac.patch, patches/chromium/webview_cross_drag.patch, patches/squirrel.mac/fix_ensure_that_self_is_retained_until_the_racsignal_is_complete.patch
Fixes current master
Notes: none
=> chore: update patches

script/release/uploaders/upload-symbols.py
Broken two years ago here --> https://github.com/electron/electron/pull/13058/files
=> build: upload windows breakpad symbols

docs/tutorial/support.md
To be merged when we're ready to kick off 10.0.0 release next week
Notes: none
=> docs: update currently supported versions for 10.0.0 release

azure-pipelines-woa.yml, spec-main/crash-spec.ts, spec-main/fixtures/crash-cases/early-in-memory-session-create/index.js
Manual backport of #25018
Resolves #24942 for 10-x-y
Notes: none
=> ci: fix WOA failing tests (10-x-y)

shell/browser/api/electron_api_web_contents.cc, shell/browser/electron_navigation_throttle.cc, shell/browser/electron_navigation_throttle.h, spec-main/api-browser-window-spec.ts
=> refactor: wire will-navigate up to a navigation throttle instead of OpenURL

npm/install.js
=> chore: update import for use new ECMA features

script/release/prepare-release.js
Was pointed out that this string is inaccurate
Notes: none
=> chore: we do not use the nightly tag on npm

docs/api/power-monitor.md
Backport of #25149
Notes: none
=> docs: fix supported platforms of powerMonitor

azure-pipelines-woa.yml, spec-main/api-crash-reporter-spec.ts, spec-main/fixtures/api/ipc-main-listeners/package.json, spec-main/fixtures/api/net-log/package.json, spec-main/fixtures/apps/crash/package.json, spec-main/fixtures/apps/remote-control/package.json, spec-main/fixtures/auto-update/check-with-headers/package.json, spec-main/fixtures/auto-update/check/package.json, spec-main/fixtures/auto-update/initial/package.json, spec/fixtures/api/app-path/package.json, spec/fixtures/api/command-line/package.json, spec/fixtures/api/default-menu/package.json, spec/fixtures/api/locale-check/package.json, spec/fixtures/api/site-instance-overrides/package.json, spec/fixtures/api/window-all-closed/package.json, spec/fixtures/snapshot-items-available/package.json
This PR cleans up directories on WOA that tests create so that the WOA runners are in a clean state for subsequent test runs. 
Notes: none
=> ci: cleanup up test app directories

docs/breaking-changes.md
These changes should have been part of #25114.
Notes: none
=> docs: breaking changes for moveItemToTrash

docs/development/README.md
Ref https://github.com/electron/electronjs.org/issues/1022#issuecomment-672277691
Attempts to change links to MD files.
Notes: none
=> docs: full links to MD files in development README

.github/CODEOWNERS
Changes to this file are likely to be security-relevant.
Notes: none
=> chore: add wg-security as required reviewer for rpc-server changes

build/webpack/run-compiler.js, build/webpack/webpack.config.base.js, build/webpack/webpack.config.isolated_renderer.js, build/webpack/webpack.config.renderer.js, build/webpack/webpack.config.sandboxed_renderer.js, build/webpack/webpack.config.worker.js, shell/common/node_bindings.cc, shell/common/node_util.cc
=> fix: handle electron script errors better

package.json, spec/package.json, spec/yarn.lock, yarn.lock
Audit warnings were annoying me
=> chore: update dependencies

electron_paks.gni, shell/browser/extensions/electron_extensions_api_client.cc
=> build: fix build with enable_pdf_viewer=false

.github/CODEOWNERS
I want to be aware of changes that happen in these files to make sure they are mirrored at https://github.com/electron/remote.
Notes: none
=> chore: add @nornagon as codeowner of remote

script/nan-spec-runner.js
Found while debugging nan issues on the last roll that it is super hard to run a single nan test in a quick way, this does two things.
1. `--only` now works with the nan spec runner
2. We set `-j max` on the `node-gyp` rebuild command to build all the native modules used for testing in seconds instead of minutes
=> build: add --only support to the nan test runner

.circleci/config.yml, script/doc-only-change.js
Circle wants to delete an image we're using, testing out the updated image.
=> build: use newer xCode image

docs/api/structures/stream-protocol-response.md, docs/api/structures/string-protocol-response.md, filenames.auto.gni
=> docs: remove unused StreamProtocolResponse / StringProtocolResponse

docs/api/download-item.md
add more info about downloadItem.setSavePath api
Notes: none.
=> docs: add more info about downloadItem.setSavePath api

lib/browser/guest-view-manager.js, script/doc-only-change.js, script/release/notes/notes.js, script/release/prepare-release.js, spec-main/fixtures/api/sandbox.html, spec-main/video-helpers.js, spec/static/main.js
Fix a few small warts & warnings in the code, e.g. unused requires, dead assignments, and passing more variables than a function takes. As with 7f885bd266b525053b8708786e56023bab4e7b9d, these are all from [lgtm](https://lgtm.com/projects/g/electron/electron/?mode=list&id=py%2Funused-import). Most of the warnings there are false negatives for code written in an intentional way for a test, rather than production code. This PR fixes some of the things that don't look intentional.
Marked as 'refactor' rather than 'fix' as none of these warnings affect production, aside from a small amount of unused code in the release
No particular stakeholder; any reviewer welcomed
Notes: none
=> chore: fix minor script warnings

docs/api/message-channel-main.md
=> docs: clarify example in message-channel-main

patches/chromium/printing.patch
backport of #25679
Notes: fix: gdi printing in silent printing mode
=> fix: gdi printing in silent printing mode

build/args/all.gn
=> chore: fix nmv for Electron v11

build/args/all.gn
=> chore: fix nmv for Electron v12

script/release/release.js
=> build: fix mergeShasums

script/check-relative-doc-links.py, script/check-trailing-whitespace.py
Just fixing a recurring typo I noticed in some scripts.
cc @zcbenz 
Notes: none
=> build: fix typos in script messages

docs/api/protocol.md
Adds hyperlinks for the `ProtocolRequest` doc throughtout the protocol docs
Notes: none
=> docs: link ProtocolRequest doc

shell/browser/net/electron_url_loader_factory.cc, shell/browser/net/electron_url_loader_factory.h, shell/browser/net/proxying_url_loader_factory.cc, shell/browser/net/proxying_url_loader_factory.h
Fixed intermittent access violation during redirects (intercepted requests)
Notes: Fixed intermittent access violation during redirects (intercepted requests)
=> fix: access violation during redirects (intercepted requests)

shell/common/api/electron_api_native_image.cc
Fixes #25753.
This holds a reference to the underlying pixel data for as long as the buffer
returned by getBitmap() is referenced.
Notes: Fixed an issue where the buffer returned by NativeImage.getBitmap() could point to freed memory.
=> fix: prevent UAF in NativeImage.getBitmap

script/release/uploaders/upload.py
=> build: print upload script output

lib/asar/fs-wrapper.ts, lib/browser/api/base-window.ts, lib/browser/api/browser-window.ts, lib/browser/api/screen.ts, lib/browser/devtools.ts, lib/browser/guest-window-manager.ts, lib/browser/ipc-main-impl.ts, lib/browser/ipc-main-internal-utils.ts, lib/browser/navigation-controller.ts, lib/browser/remote/server.ts, lib/browser/rpc-server.ts, lib/common/api/deprecate.ts, lib/common/type-utils.ts, lib/renderer/inspector.ts, lib/renderer/web-view/web-view-impl.ts, lib/renderer/window-setup.ts, spec-main/api-deprecate-spec.ts, typings/internal-ambient.d.ts, typings/internal-electron.d.ts
=> refactor: replace a few any-s with proper types

docs/api/modernization/overview.md, docs/api/modernization/property-updates.md, docs/api/session.md, docs/api/web-contents.md, docs/development/azure-vm-setup.md, docs/development/source-code-directory-structure.md, docs/tutorial/electron-timelines.md
Some typos in the docs.
cc @nornagon @jkleinsc
Notes: none
=> docs: fix typos

spec-main/api-session-spec.ts
=> test: improve app 'session-created' event spec
