electron/electron

- lib/browser/api/menu-item-roles.ts
- patches/node/chore_expose_v8_initialization_isolate_callbacks.patch
> refactor: wrap Object.prototype.hasOwnProperty.call

- docs/api/session.md
> docs: fix protocol.registerFileProtocol() usage in session.md

- appveyor.yml
- azure-pipelines-woa.yml
Cherry-pick from master roll
CrBug: https://bugs.chromium.org/p/chromium/issues/detail?id=1139022
Notes: none
> chore: fix visibility tests on windows 

- patches/chromium/chore_expose_v8_initialization_isolate_callbacks.patch
Update the patch to fix CI failure on master branch.
Notes: none
> chore: update chore_expose_v8_initialization_isolate_callbacks.patch

- azure-pipelines-woa.yml
Missed in the last master roll
Notes: none
> chore: fix visibility tests for woa

- script/lib/patches.py
- script/release/uploaders/upload-symbols.py
- script/release/uploaders/upload.py
- script/strip-binaries.py
- script/update-external-binaries.py
- script/verify-chromedriver.py
Fixing a few linter errors. Python linting is currently silently failing in `master`, trying to fix up the linting errors before fixing that. They're mostly just line length issues.
Notes: none
> chore: fix linter errors

- shell/browser/electron_browser_client.cc
> chore: make RenderProcessHostPrivilege enum class

- shell/browser/extensions/electron_extensions_api_client.cc
- shell/renderer/printing/print_render_frame_helper_delegate.cc
- shell/renderer/renderer_client_base.cc
- shell/renderer/renderer_client_base.h
Backport of #25959
Notes: Fixed an issue where `Save as PDF` from PDF Viewer Print dialog failed and sometimes crashed.
> fix: Save As PDF from PDF Preview

- script/lint.js
This one probably needs a more thorough review and discussion, I don't love it.
First part of the fix is simple, use `shell: true` so that the command runs correctly on Windows, this is what was stopping it before.
However, once that was fixed it immediately runs into "The command line is too long." The full command with the list of hundreds of files maxes out Window's max length for a command line invocation. Looking at the [eslint command line options](https://eslint.org/docs/user-guide/command-line-interface) I don't see any other way to give it the list of files. There's `--stdin` where you could dump all the contents, but then you lose filenames, so that's not going to work.
~~So this PR runs the files one at a time through `eslint`. I don't know if there's much of a performance …
> build: fix running eslint on Windows

- shell/browser/notifications/mac/notification_center_delegate.mm
- shell/browser/notifications/notification.cc
- shell/browser/notifications/notification.h
- shell/browser/notifications/win/windows_toast_notification.cc
> revert: reply notifs sometimes destroyed too early

- docs/tutorial/web-embeds.md
Revised the web embeds feature page
Notes: Revised the web embeds feature page
> docs: revised the web embeds feature page

- shell/browser/api/electron_api_base_window.cc
- shell/browser/api/electron_api_web_contents.cc
- shell/browser/browser_win.cc
- shell/browser/electron_browser_context.cc
- shell/browser/electron_download_manager_delegate.cc
- shell/browser/native_window_views_win.cc
- shell/browser/osr/osr_render_widget_host_view.cc
- shell/browser/ui/autofill_popup.cc
- shell/browser/ui/message_box_win.cc
- shell/common/gin_converters/guid_converter.h
- shell/renderer/api/electron_api_context_bridge.cc
Came out as a suggestion from a `clang-tidy` check, seems like a good thing to tidy up.
Notes: none
> chore: prefer empty() check for readability

- package.json
- yarn.lock
Picks up a couple of fixes.
Notes: none
> chore: bump @electron/docs-parser version

- docs/development/build-instructions-windows.md
Debated adding this to troubleshooting instead, but AFAIK you *will* hit it if you don't do this step, so it seems more like a "must-do" than a troubleshooting step.
Notes: none
> docs: Windows Security modifies Chromium checkout

- docs/tutorial/linux-desktop-actions.md
Revised linux desktop actions page
Notes: revised linux desktop actions page
> docs: revised linux desktop actions page

- docs/tutorial/windows-taskbar.md
Revised windows taskbar page
Notes: Revised windows taskbar page, unified structure of the sections
> docs: revised windows taskbar page

- chromium_src/chrome/browser/process_singleton_posix.cc
- chromium_src/chrome/browser/ui/views/frame/global_menu_bar_registrar_x11.cc
- shell/browser/api/electron_api_app.cc
- shell/common/api/electron_api_v8_util.cc
- shell/common/api/electron_bindings.cc
Another little modernizing the codebase change.
Notes: none
> chore: change some for loops to range-based

- spec-main/api-session-spec.ts
Example flake: https://app.circleci.com/pipelines/github/electron/electron/31724/workflows/ad370a6d-7c65-44dc-bf8b-e3978e263fe5/jobs/699105
Ref #26166
Notes: none
> test: deflake ses.setProxy test

- shell/browser/api/electron_api_debugger.cc
- shell/browser/api/electron_api_download_item.cc
- shell/browser/api/electron_api_power_monitor_win.cc
- shell/browser/api/electron_api_session.cc
- shell/browser/api/electron_api_system_preferences_win.cc
- shell/browser/api/electron_api_web_contents.cc
- shell/browser/api/process_metric.cc
- shell/browser/electron_browser_client.cc
- shell/browser/electron_download_manager_delegate.cc
- shell/browser/native_window_views.cc
- shell/browser/native_window_views_win.cc
- shell/browser/notifications/platform_notification_service.cc
- shell/browser/osr/osr_render_widget_host_view.cc
- shell/browser/osr/osr_web_contents_view.cc
- shell/browser/ui/views/autofill_popup_view.cc
- shell/browser/ui/views/inspectable_web_contents_view_views.cc
- shell/browser/ui/views/menu_bar.cc
- shell/browser/ui/views/menu_delegate.cc
- shell/browser/ui/win/notify_icon_host.cc
- shell/common/api/electron_bindings.cc
- shell/common/gin_helper/callback.cc
- shell/common/gin_helper/wrappable.cc
- shell/common/node_bindings.cc
- shell/common/skia_util.cc
> chore: use auto to avoid repeating type

- patches/v8/.patches
- patches/v8/perf_improve_heap_snapshot_performance.patch
Fixes #24509.
cherry-pick 2e2dc98 from v8
Notes: improved performance of `takeHeapSnapshot()`.
> perf: improve heap snapshot performance

- .circleci/config.yml
- package.json
- patches/chromium/rename_the_v8_context_snapshot_on_arm64_macos_builds.patch
- script/push-patch.js
- tsconfig.script.json
- yarn.lock
Small bit of code to auto push three way merge patch file changes from CI.  Abuses a GH app to do it similar to how trop works
> build: auto-push patch file changes

- .eslintrc.json
Fixes some indentation and makes consistent use of the named rule values rather than the less friendly number version.
Notes: none
> chore: tidy up .eslintrc.json

- script/export_all_patches.py
- script/lib/config.py
- script/lib/git.py
- script/release/uploaders/upload.py
* Fixes line endings when exporting patches on Windows
* Python3 compatibility fixes
Notes: none
> build: Python3 compat and Win line-endings fixes

- build/npm-run.py
- build/profile_toolchain.py
- build/strip_framework.py
- build/zip.py
- script/check-relative-doc-links.py
Just file length violations and a couple unused variables and shadowing builtin names.
Notes: none
> chore: cleanup pylint violations

- docs/api/structures/protocol-response.md
> docs: link ProtocolResponseUploadData

- docs/development/build-instructions-gn.md
- docs/tutorial/performance.md
- docs/tutorial/windows-arm.md
> chore: fix markdown in docs

- docs/api/session.md
- shell/common/gin_converters/content_converter.cc
- spec-main/chromium-spec.ts
Backport of #26172
Notes: updated setPermissionRequestHandler to correctly recognize permissions being requested.
> feat: correctly identify permissions when using setPermissionRequestHandler

- .circleci/config.yml
- appveyor.yml
- script/release/uploaders/upload-to-github.js
- script/release/uploaders/upload.py
The release no work, now it work
> build: fix usage of octokit/rest and make uploading better

- script/lib/util.py
- script/release/uploaders/upload-to-github.ts
- script/release/uploaders/upload.py
> chore: move upload-to-github to TS

- script/release/uploaders/upload.py
> build: verbose is flag, no value

- .circleci/config.yml
- package.json
- script/push-patch.js
- tsconfig.script.json
- yarn.lock
> build: auto-push patch file changes (#26235)

- patches/chromium/export_gin_v8platform_pageallocator_for_usage_outside_of_the_gin.patch
Missed a comment asking for a patch description for this one
> chore: add patch description to gin allocator patch

- docs/development/issues.md
The issue template shown in the docs was outdated.
Notes: none
> docs: update issue template

- shell/renderer/api/electron_api_web_frame.cc
Fixes regression introduced in #25060.
> build: fix build with enable_builtin_spellchecker=false

- lib/renderer/api/remote.ts
- lib/renderer/ipc-renderer-internal-utils.ts
- lib/renderer/ipc-renderer-internal.ts
- lib/renderer/web-view/guest-view-internal.ts
- lib/renderer/window-setup.ts
- typings/internal-electron.d.ts
> fix: ensure that internal messages are sent from the main process

- docs/tutorial/support.md
To be merged when we're ready to kick off 11 stable release
Notes: none
> docs: update currently supported versions for 11.0.0 release

- docs/api/power-monitor.md
- lib/browser/api/power-monitor.ts
- shell/browser/api/electron_api_power_monitor.cc
- spec-main/api-power-monitor-spec.ts
Fixes #26457.
Notes: Added `powerMonitor.onBatteryPower`.
> feat: add powerMonitor.onBatteryPower

- docs/api/ipc-renderer.md
Clarify some particulars about Structured Clone in relation to IPC to the main process. Ref #26510.
Notes: none
> docs: note about structured clone and DOM types

- lib/browser/api/web-contents.ts
- shell/browser/api/electron_api_browser_view.cc
- shell/browser/api/electron_api_web_contents.cc
- shell/browser/api/electron_api_web_contents.h
- shell/browser/api/electron_api_web_contents_view.cc
Two functions, one purpose.
Notes: none
> refactor: consolidate WebContents::{Create,New}

- lib/renderer/web-view/guest-view-internal.ts
Fixes #26561
Notes: Fixed `<webview>` `render-process-gone` event dispatch.
> fix: <webview> render-process-gone event dispatch

- shell/browser/api/electron_api_printing.cc
Fix regression introduced by #26518
> build: fix build with enable_printing=false

- build/args/all.gn
Refs https://github.com/nodejs/node/pull/36101.
Notes: none.
> chore: update nmv for Electron v13

- lib/browser/guest-view-manager.ts
- lib/browser/rpc-server.ts
- lib/renderer/api/module-list.ts
- lib/renderer/init.ts
- lib/sandboxed_renderer/api/module-list.ts
- lib/sandboxed_renderer/init.ts
- shell/renderer/renderer_client_base.cc
> refactor: use getWebPreference() for all options

- script/codesign/generate-identity.sh
- script/lib/npx.py
- script/nan-spec-runner.js
- script/release/uploaders/upload-symbols.py
- script/spec-runner.js
- script/yarn.js
`npx@7` requires a `Yes` prompt, this env var emulates `--yes` and also supports `npx@6`
> build: update npx.py to support npx@7

- lib/browser/remote/objects-registry.ts
- lib/browser/remote/server.ts
- lib/renderer/api/remote.ts
- lib/renderer/remote/callbacks-registry.ts
Avoids conflicts with https://github.com/electron/remote
> refactor: replace V8 hidden values with WeakMap / WeakSet

- .circleci/config.yml
- appveyor.yml
> build: use one-for-all goma

- .circleci/config.yml
- appveyor.yml
This reverts commit 6761814f14003aee84885485aa6081aaa0d4d7d0.
Notes: none
> Revert "build: use one-for-all goma (#26679)"

- patches/ReactiveObjC/build_conditionally_import_ext_headers_from_framework_or_from.patch
- patches/chromium/feat_allow_embedders_to_add_observers_on_created_hunspell.patch
- patches/node/fix_expose_tracing_agent_and_use_tracing_tracingcontroller_instead.patch
Some patches are missing descriptions. Refs https://github.com/electron/electron/pull/26595.
Notes: none
> chore: add descriptions for patches

- script/lint.js
I'm not sure this linter was actually running. It was looking for `config.json` in individual patch directories, which doesn't seem to be the case with the current layout.
Unfortunately all of the linters seem to suffer from silently failing. They all follow a pattern of "no news is good news", but sometimes "no news" means the linter didn't actually run, or do meaningful work. I've tried to somewhat curtail that in this PR by requiring files be worked on for `allOk` to be true.
This PR also changes up how descriptions are checked for on patches, to better handle multi-line subjects. This was brought up with a recent patch where it wasn't detected, see https://github.com/electron/electron/pull/26331#discussion_r520152954.
~There are currently three patches in the repo which don't have a …
> chore: fixup patches linting

- .circleci/config.yml
- appveyor.yml
Reland with more files on macOS
> build: use all-for-one goma

- spec-main/api-web-contents-spec.ts
It was also flaking on ASan.
cc @CezaryKulakowski. I hope this maintains the original intention of the test.
Notes: none
> test: deflake current-render-view-deleted test

- shell/browser/api/electron_api_app.cc
There are a few old TODOs on `SetHidden` that can be removed.
Notes: none
> chore: remove TODO on SetHidden calls

- shell/browser/api/electron_api_screen.cc
Added in https://github.com/electron/electron/pull/1016, hasn't been used in a long time.
Notes: none
> chore: remove unused FindByID helper

- docs/breaking-changes.md
Lets changes in #26792 run cleanly.
Notes: none
> chore: blank lines before lists in markdown

- .github/config.yml
Letting me be able to run trop backports manually.
@codebytere @jkleinsc 
Notes: None
> chore: add @mlaurencin to manual backport config

- spec-main/chromium-spec.ts
Not sure what the underlying issue is but it's more important currently to have
CI functioning.
Notes: none
> test: disable flaky reporting API test

- .circleci/config.yml
- .gitmodules
- DEPS
- appveyor.yml
The python script that imported the `requests` module (`script/lib/github.py`) has been removed in July 2018:  https://github.com/electron/electron/pull/13597
Therefore the `requests` module is no longer needed and can be removed from git submodule
Ref
https://github.com/electron/electron/pull/2111
https://github.com/electron/electron/pull/14970
https://github.com/electron/electron/pull/22126
Notes: none
> build: remove requests from git submodule

- shell/browser/native_window_mac.mm
Close https://github.com/electron/electron/issues/10424.
The `customButtonsOnHover` option relied on the `NSWindowStyleMaskFullSizeContentView` style to hide window title and buttons, which is actually a weird code path and unnecessary.
This PR makes it use the normal window styles like the other `titleBarStyle` options, which fixes the problem that the window has no rounded corner.
Notes: Fix window with `customButtonsOnHover` option not having rounded corner on macOS.
> fix: window with customButtonsOnHover should have rounded corner

- docs/tutorial/quick-start.md
The quick start guide code got updated for the fiddle integration, but the comment describing the code was not.
Notes: none
> docs: update quick start description after fiddle integration

- docs/tutorial/quick-start.md
`author` and `description` field is required
Notes: none
> docs: include author and description in package.json in quick-start.md

- docs/api/global-shortcut.md
- shell/browser/api/electron_api_global_shortcut.cc
Backport of #27002.
Notes: none
> fix: throw when using globalShortcut before ready

- docs/api/web-contents.md
- docs/tutorial/offscreen-rendering.md
Backport of #26805.
Notes: none
> docs: update OSR max FPS number

- lib/browser/remote/server.ts
Port https://github.com/electron/remote/pull/24
> fix: handle _sendToFrameInternal() throwing an exception in remote/server.ts

- docs/tutorial/snapcraft.md
docs: fix two "add" mistake in snapcraft.md
Notes: none.
> docs: fix two "add" mistake in snapcraft.md

- shell/browser/api/electron_api_browser_view.cc
- shell/browser/api/electron_api_web_contents.cc
- shell/browser/api/electron_api_web_contents.h
- shell/browser/api/electron_api_web_contents_view.cc
- spec-main/api-browser-view-spec.ts
Backport of #26802
Notes: none
> feat: add support for webContents option in BrowserView

- docs/api/extensions.md
- script/gen-filenames.ts
- shell/browser/electron_browser_client.cc
- shell/browser/extensions/electron_extension_loader.cc
- shell/common/extensions/electron_extensions_client.cc
- spec-main/extensions-spec.ts
- spec-main/fixtures/extensions/chrome-webRequest-wss/background.js
- spec-main/fixtures/extensions/chrome-webRequest-wss/manifest.json
- spec-main/fixtures/extensions/chrome-webRequest/background.js
- spec-main/fixtures/extensions/chrome-webRequest/manifest.json
- spec/ts-smoke/electron/renderer.ts
Backport of #22655 
Notes: Fixed `chrome.webRequest` extensions API not intercepting any requests.
> fix(extensions): implement missing web_request hooks

- docs/api/web-frame-main.md
- spec-main/api-web-frame-main-spec.ts
Also add missing test for this and refactor the existing one to use the `emittedNTimes` helper
> docs: webFrameMain.fromId() can return undefined

- shell/browser/api/electron_api_base_window.cc
- shell/browser/api/electron_api_base_window.h
- shell/browser/api/electron_api_tray.cc
- shell/browser/api/electron_api_tray.h
- shell/browser/api/electron_api_web_contents.cc
- shell/browser/browser.h
- shell/browser/browser_mac.mm
- shell/common/api/electron_api_native_image.cc
- shell/common/api/electron_api_native_image.h
- shell/common/gin_converters/image_converter.cc
- spec-main/api-app-spec.ts
- spec-main/api-tray-spec.ts
- spec-main/api-web-contents-spec.ts
Backport of #26546.
Notes: none
> refactor: remove path from nativeImage converter

- spec-main/api-web-contents-spec.ts
> test: skip PictureInPicture video when media not supported

- .github/ISSUE_TEMPLATE/feature_request.yml
Fixup incorrect [template formatting](https://gh-community.github.io/issue-template-feedback/structured/).
cc @jkleinsc @MarshallOfSound 
Notes: none.
> build: fixup feature request template

- .circleci/config.yml
Manual backport for 10-x-y of #27224
Notes: none
> ci: fix broken homebrew cache

- docs/tutorial/devtools-extension.md
> docs: update devtools extension tutorial

- lib/browser/api/web-contents.ts
- lib/browser/ipc-main-internal-utils.ts
- lib/renderer/api/ipc-renderer.ts
- lib/renderer/ipc-renderer-internal.ts
- shell/browser/api/electron_api_web_contents.cc
- shell/browser/api/electron_api_web_contents.h
- shell/browser/electron_browser_handler_impl.cc
- shell/browser/electron_browser_handler_impl.h
- shell/common/api/api.mojom
- shell/renderer/api/electron_api_ipc_renderer.cc
- shell/renderer/electron_api_service_impl.cc
- shell/renderer/electron_api_service_impl.h
- typings/internal-ambient.d.ts
- typings/internal-electron.d.ts
Backport of #26771. Backporting #26807 depends on this refactoring.
> chore: remove unused sendToAll + related APIs

- lib/browser/remote/objects-registry.ts
- lib/renderer/remote/callbacks-registry.ts
> refactor: store WeakMaps in CallbacksRegistry / ObjectsRegistry

- docs/api/web-frame-main.md
- lib/browser/api/web-contents.ts
- lib/browser/api/web-frame-main.ts
- lib/browser/init.ts
- shell/browser/api/electron_api_web_contents.cc
- shell/browser/api/electron_api_web_contents.h
- shell/browser/api/electron_api_web_frame_main.cc
- shell/browser/api/electron_api_web_frame_main.h
- shell/common/api/electron_api_native_image.h
- spec-main/api-ipc-spec.ts
- spec-main/api-subframe-spec.ts
- spec-main/api-web-frame-main-spec.ts
- typings/internal-ambient.d.ts
- typings/internal-electron.d.ts
Backport of #26807
Notes: Added `webFrameMain.send()` / `webFrameMain.postMessage()`.
> feat: add webFrameMain.send() / webFrameMain.postMessage()

- patches/chromium/.patches
- patches/chromium/mojo_fix_uaf_on_nodechannel.patch
Mojo: Fix UAF on NodeChannel
TBR=rockot@google.com
(cherry picked from commit 9c8a98b3983dd1c7828ceae2fc8a5a2e9bad1f68)
(cherry picked from commit 06fe641d21bda1b5869a46e59b13873762ce1324)
Fixed: 1162198
Change-Id: Ief850903a7e6ba3d7c5c0129704d1f80aa3467ce
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2612085
Reviewed-by: Ken Rockot <rockot@google.com>
Cr-Original-Original-Commit-Position: refs/heads/master@{#840942}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2621996
Cr-Original-Commit-Position: refs/branch-heads/4324@{#1637}
Cr-Original-Branched-From: c73b5a651d37a6c4d0b8e3262cc4015a5579c6c8-refs/heads/master@{#827102}
Reviewed-on: …
> chore: cherry pick 06fe641d21bd from chromium

- docs/tutorial/security.md
`Map` should accept an array of iterable object whose elements are key-value pairs
> docs: fix code sample in security.md

- docs/tutorial/web-embeds.md
> docs: update web-embeds

- shell/browser/api/electron_api_web_frame_main.cc
- shell/browser/api/electron_api_web_frame_main.h
- spec-main/api-web-frame-main-spec.ts
- Remove unused `v8::Isolate* isolate` arguments
- Check property types in tests
> refactor: cleanup WebFrameMain + improve tests

- patches/chromium/.patches
- patches/chromium/cherry-pick-9ec949913373.patch
Mojo: Fix UAF on NodeChannel
TBR=rockot@google.com
(cherry picked from commit 9c8a98b3983dd1c7828ceae2fc8a5a2e9bad1f68)
(cherry picked from commit 06fe641d21bda1b5869a46e59b13873762ce1324)
Fixed: 1162198
Change-Id: Ief850903a7e6ba3d7c5c0129704d1f80aa3467ce
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2612085
Reviewed-by: Ken Rockot <rockot@google.com>
Cr-Original-Original-Commit-Position: refs/heads/master@{#840942}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2621996
Cr-Original-Commit-Position: refs/branch-heads/4324@{#1637}
Cr-Original-Branched-From: c73b5a651d37a6c4d0b8e3262cc4015a5579c6c8-refs/heads/master@{#827102}
Reviewed-on: …
> chore: cherry-pick 9ec949913373 from chromium

- docs/tutorial/support.md
Add documentation about :apple: Apple Silicon. This may need to be backported to the 11.0.0 release notes. (Implemented in https://github.com/electron/electron/pull/24545) @MarshallOfSound 
Notes:  Update documentation about Apple Silicon.
> docs: Add Note About Apple Silicon

- chromium_src/BUILD.gn
- shell/browser/api/electron_api_web_contents.cc
- shell/browser/api/electron_api_web_contents.h
Backport of #27275
Notes: None
> fix: add eyedropper tool functionality to browser view

- docs/api/ipc-renderer.md
- docs/api/web-contents.md
Backport of #27483
Notes: none
> docs: update verb tenses for structured clone notes

- docs/tutorial/devtools-extension.md
Refs https://github.com/electron/electron/pull/25198
Notes: None
> chore: fix lint

- lib/browser/rpc-server.ts
Might improve performance slightly
> refactor: load preload script directly as a string

- shell/browser/native_browser_view_mac.mm
Backport of #27585.
Notes: Fixed an occasional white flicker present when rendering BrowserViews in close succession.
> fix: BrowserView rendering flicker

- shell/browser/ui/inspectable_web_contents_impl.cc
Backport of #26474.
Notes: Fixed an Uncaught TypeError when opening DevTools.
> fix: Cannot read property 'setDockSide' of undefined

- azure-pipelines-woa.yml
Windows on ARM testing has been consistently failing due to issues cleaning up after testing.  This should resolve that issue.
Notes: none
> ci: ignore errors deleting user app directories on WOA testing

- shell/browser/api/electron_api_web_contents_mac.mm
A past refactor of what is now `ElectronNSWindow` removed `EventDispatchingWindow` from its inheritance chain, without also adding `ElectronNSWindow` where `EventDispatchingWindow` was previously used. This small change restores that functionality to `ElectronNSWindow`.
Fixes #27268 which is a modern duplicate of #6016 which was fixed in #6068 but then became unfixed in #12696 and has been (presumably) broken ever since.
cc @MarshallOfSound
Notes: Fixed OS-level shortcuts on macOS (e.g. Ctrl + F2, ⌘ + ~).
> fix: restore window event redispatching on mac

- docs/api/app.md
Makes the TOC look weird
Notes: none
> docs: fix header level of some events in app.md

- filenames.gni
- shell/browser/api/electron_api_web_contents.cc
- shell/browser/bluetooth/electron_bluetooth_delegate.cc
- shell/browser/bluetooth/electron_bluetooth_delegate.h
- shell/browser/electron_browser_client.cc
- shell/browser/electron_browser_client.h
- shell/browser/lib/bluetooth_chooser.cc
- shell/browser/lib/bluetooth_chooser.h
- spec-main/chromium-spec.ts
Backport of #27902
Notes: Fixed navigator.bluetooth.requestDevice.
> fix: navigator.bluetooth.requestDevice

- lib/browser/api/net.ts
Backport of #27898. (cc @khwaaj)
Notes: Fixed race condition in electron.net implementation.
> fix: prevent race-condition in electron.net

- shell/browser/lib/bluetooth_chooser.cc
- shell/browser/lib/bluetooth_chooser.h
- spec-main/chromium-spec.ts
Backport of #27902
Notes: Fixed navigator.bluetooth.requestDevice crash
> fix: navigator.bluetooth.requestDevice crash

- docs/tutorial/support.md
> docs: update currently supported versions for 12.0.0 release

- spec-main/api-app-spec.ts
- spec-main/extensions-spec.ts
Add more logging for a few frequently failing tests.
Notes: none
> test: add more logging for a few tests.

- shell/browser/native_browser_view_mac.mm
Closes https://github.com/electron/electron/issues/27884.
We need to offset `BrowserView`s by the browserview bounds to prevent drag regions from mismatching the bounds of the `BrowserView` itself.
Tested with https://gist.github.com/08f3e56e0a4dc443621bd769e18c7cd6
Notes: Fixed an issue where `BrowserView`s could have mismatched draggable regions to their bounds.
> fix: offset browserview drag regions on macOS

- docs/fiddles/quick-start/main.js
Fixes #27957
There are probably a bunch of other fiddles that need updating too :/
Notes: none
> docs: update fiddles/quick-start to set contextIsolation: false

- spec-main/api-app-spec.ts
- spec-main/extensions-spec.ts
- spec/fixtures/api/relaunch/main.js
Make the `app.relaunch` test more stable, also add more information to the loggings added by https://github.com/electron/electron/pull/27956.
Notes: none
> test: exit after app.relaunch is called

- spec-main/chromium-spec.ts
The locale test fails frequently, print more information in it.
Notes: none
> test: print more information in locale test

- .github/ISSUE_TEMPLATE/bug_report.yml
I hope this is the right syntax.
Notes: none
> docs: add bug label to bug reports

- docs/api/window-open.md
FYI, I'm not adding much info because I simply added three characters to a markdown document.
Notes: none
> docs: fixed typo in api/window-open.md

- shell/common/api/electron_api_v8_util.cc
- spec-main/spellchecker-spec.ts
- typings/internal-ambient.d.ts
Backport of https://github.com/electron/electron/pull/28118.
Notes: none
> test: reliably wait for spellchecker to load

- spec-main/spellchecker-spec.ts
The spellchecker may take several minutes to load under ASan, give it 10 minutes to load.
Notes: none
> test: spellchecker may take several minutes to load under ASan

- docs/tutorial/quick-start.md
fix: Fix main.js source code, missing large bracket
Notes: none
> docs: fix main.js source code example

- .circleci/config.yml
This PR adds cleanup to our macOS arm64 tests so that the runners are in the proper state for future test runs.
Notes: none
> ci: cleanup directories on arm64 machines after running tests

- docs/tutorial/message-ports.md
Backport of #27678
Notes: none
> docs: MessagePorts guide (#27678)

- spec-main/spellchecker-spec.ts
Use a minimal dictionary when testing spellchecker, which should be able to make the test run much faster under ASan.
This will solve the hang in CI: `Too long with no output (exceeded 10m0s): context deadline exceeded`.
Notes: none
> test: load minimal dict for spellchecker

- lib/browser/api/touch-bar.ts
- shell/browser/ui/cocoa/electron_touch_bar.mm
Backport of #27901 
Notes: Fixed bug where TouchBarPopover and TouchBarGroup were no longer rendering
> fix: make TouchBarPopover and TouchBarGroup work (#27901)

- lib/browser/api/touch-bar.ts
- shell/browser/ui/cocoa/electron_touch_bar.mm
Backport of #27901
Notes: Fixed bug where TouchBarPopover and TouchBarGroup were no longer rendering
> fix: make TouchBarPopover and TouchBarGroup work

- lib/browser/default-menu.ts
Closes #28359
Notes: Updated community discussions link in default Electron menu.
> chore: update Community link in default menu

- script/lib/git.py
As per the nit in #28454 we don't need this variable anymore, quick clean up 😄 
cc @ckerr 
> refactor: remove unneeded patch_count variable

- lib/renderer/api/web-frame.ts
- typings/internal-ambient.d.ts
> chore: add types for electron_renderer_web_frame binding

- docs/tutorial/support.md
- shell/browser/resources/mac/Info.plist
> docs: the minimum supported version of macOS is now 10.11

- shell/browser/ui/file_dialog_gtk.cc
Closes https://github.com/electron/electron/issues/27837.
Tested with https://gist.github.com/mkaesberger/107ca937bdf4cc94ac01a1f4605e7985.
Notes: none.
> fix: dialog DCHECK on Linux

- .circleci/config.yml
- appveyor.yml
For some reason fork PRS are occasionally failing with Goma errors, eg:
https://app.circleci.com/pipelines/github/electron/electron/37607/workflows/cbf7910b-6ffa-45c5-964f-7a960a2b0730/jobs/829907.  This PR adds and environment variable to compilation to continue even if Goma is having issues.
Notes: none
> ci: Add goma fallback flag

- build/webpack/webpack.config.base.js
- build/webpack/webpack.gni
Let's not be trying to debug minimized js.
No release notes and semver/none because this does not affect released artifacts.
Notes: none
> chore: don't minimize js in development

- script/release/ci-release-build.js
Mild improvement in release build error handling.
Notes: none
> build: better error handling for release builds

- .gitignore
- spec-main/chromium-spec.ts
Small PR that does makes a test more readable and adds a generated file to the gitignore
Notes: none
> chore: clean up some spec things

- script/doc-only-change.js
Noticed this issue while writing #28712
Notes: none
> build: fix docs only change script to pull all files not just 30

- patches/chromium/.patches
- patches/chromium/cherry-pick-6a6361c9f31c.patch
WebContents bug fix: Device capture only if web contents is valid
(cherry picked from commit a462be0883486431086c5f07cdafbd3607005a59)
(cherry picked from commit e6f11cafde08981e47ba77e71abf99a271f7a042)
Bug: 1181228
Change-Id: I0a4c9718a3c0ccb52cefa4565b9787e6912554c9
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2752235
Commit-Queue: Palak Agarwal <agpalak@chromium.org>
Cr-Original-Original-Commit-Position: refs/heads/master@{#863828}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2782122
Auto-Submit: Guido Urdaneta <guidou@chromium.org> …
> chore: cherry-pick 6a6361c9f31c from chromium

- patches/v8/.patches
- patches/v8/merged_squashed_multiple_commits.patch
Merged: Squashed multiple commits.
Merged: [const-tracking] Mark const field as mutable when reconfiguring
Revision: 7535b91f7cb22274de734d5da7d0324d8653d626
Merged: [const-tracking] Fix incorrect DCHECK in MapUpdater
Revision: f95db8916a731e6e5ccc0282616bc907ce06012f
BUG=chromium:1161847,chromium:1185463,v8:9233
NOTRY=true
R=​ishell@chromium.org
(cherry picked from commit 56518020bff4d0e8b82cff843c9f618c90084e42)
Change-Id: I7f46a701646e1dd67a049b2aa4ac32d05b6885f3
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/2748079
Cr-Original-Commit-Position: refs/branch-heads/8.9@{#43}
Cr-Original-Branched-From: …
> chore: cherry-pick ffde6ee0e4 from v8

- patches/chromium/.patches
- patches/chromium/cherry-pick-fe85e04a1797.patch
Don't use BigBuffer for IPC::Message transport
* ipc/ipc_message_pipe_reader.cc
Fixed extra include.
(cherry picked from commit 85bd7c88523545ab0e497d5e7b3e929793813358)
(cherry picked from commit fad3b9ffe7c7ff82909d911c573bd185aa3b3b50)
Fixed: 1184399
Change-Id: Iddd91ae8d7ae63022b61c96239f5e39261dfb735
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2737012
Cr-Original-Original-Commit-Position: refs/heads/master@{#860010}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2779918
Reviewed-by: Adrian Taylor <adetaylor@chromium.org>
Reviewed-by: Alex Gough <ajgo@chromium.org> …
> chore: cherry-pick fe85e04a1797 from chromium

- appveyor.yml
- patches/chromium/.patches
- patches/chromium/revert_roll_clang_llvmorg-13-init-7051-gdad5caa5-2.patch
Refs https://github.com/electron/electron/issues/28876
> build: enable woa testing

- docs/tutorial/installation.md
This is a pattern that we actively want to discourage.
Notes: none
> docs: remove reference to global Electron install

- patches/chromium/.patches
- patches/chromium/cherry-pick-5d3a047a15e0.patch
conditionally import strip_binary.gni in chromedriver tests
Backported from https://chromium-review.googlesource.com/c/chromium/src/+/2869218
> chore: cherry-pick 5d3a047a15e0 from chromium

- .circleci/config.yml
> build: Use goma for all releases

- lib/browser/guest-view-manager.ts
- lib/renderer/web-view/web-view-constants.ts
- lib/renderer/web-view/web-view-element.ts
- typings/internal-electron.d.ts
Simpifies `<webview>` implementation for upcoming refactoring to use `contextBridge` when `contextIsolation` is enabled.
> chore: cleanup dead <webview> related code

- .github/CODEOWNERS
Follow-up to #25415. All these files have IPC main handlers in them and could be security sensitive.
> chore: add wg-security as required reviewer for other files with IPC handlers

- README.md
Updating list of available docs list at readme.md file.
Notes: No release notes 
As per [image](https://i.imgur.com/pcCmce8.png) there are 8 language variants of docs not 16 as in current docs language "list".
> docs: Updating "list" of docs languages in readme.md file

- patches/chromium/desktop_media_list.patch
Thanks to @deepak1556 for providing additional context.
Notes: none
> docs: expand description of desktop_media_list.patch

- patches/chromium/isolate_holder.patch
> docs: expand description of isolate_holder.patch

- shell/browser/api/electron_api_system_preferences_mac.mm
- shell/browser/api/electron_api_web_contents.cc
- shell/common/api/electron_api_native_image.cc
- shell/common/api/electron_api_native_image.h
- shell/renderer/api/electron_api_context_bridge.cc
- shell/renderer/api/electron_api_web_frame.cc
- shell/renderer/electron_sandboxed_renderer_client.cc
- shell/renderer/electron_sandboxed_renderer_client.h
- shell/renderer/renderer_client_base.cc
- shell/renderer/renderer_client_base.h
I've experimented a bit with http://www.harukizaemon.com/simian
> refactor: eliminate duplicate code

- docs/tutorial/support.md
To be merged when we're ready to kick off 11 stable release
Notes:  None
> docs: update currently supported versions for 13.0.0 release

- docs/fiddles/features/notifications/main/index.html
- docs/fiddles/features/notifications/main/main.js
- docs/tutorial/notifications.md
Removed `nodeIntegration`
Linted code using `standard`.
Notes: none
> docs: Update notifications (main) docs

- docs/tutorial/quick-start.md
Modify the usage of attaching a preload script. The old version cannot run on windows in version 13.0.0.
> docs: Modify the usage of attaching a preload script in quick-start.md

- shell/browser/net/electron_url_loader_factory.cc
- shell/browser/net/node_stream_loader.cc
- shell/common/gin_helper/wrappable_base.h
Just a few typos I caught.
Notes: none
> chore: fix typos in comments

- shell/common/gin_helper/wrappable.cc
Popped out of `clang-tidy` as a suggestion. It's a no-op to `delete` a `null` pointer, so the check isn't necessary.
Notes: none
> chore: simplify WrappableBase::SecondWeakCallback

- script/lib/utils.js
One step along the way to changing the default branch name of e/e.
Notes: none
> refactor: getCurrentBranch respects main

- script/release/version-utils.js
Update version-utils to handle 'main' branch.
Notes: none
> refactor: version-utils respects main

- docs/development/coding-style.md
Current link works, but hits a landing page saying it's moved, and provides a link to the new location. This PR updates the link to the new location.
Notes: none
> docs: update link to Chromium's coding style guide

- shell/browser/api/electron_api_protocol.cc
Looks like this line got duplicated by accident, this PR just trims the duplicate.
Notes: none
> chore: remove duplicate option get for CustomScheme

- shell/common/node_bindings.cc
- spec-main/node-spec.ts
- spec/fixtures/module/fail.js
> test: add spec for --require filtering in NODE_OPTIONS

- docs/api/client-request.md
Just making the mention of `IncomingMessage` a link.
Notes: none
> docs: link to IncomingMessage

- lib/asar/fs-wrapper.ts
- lib/browser/api/menu.ts
- lib/browser/default-menu.ts
- lib/sandboxed_renderer/init.ts
- typings/internal-electron.d.ts
Use `WeakMap` / `WeakSet` instead.
> refactor: replace a few usages of V8 hidden properties

- shell/browser/api/electron_api_cookies.cc
Return after rejecting the promise otherwise code execution will continue on.
cc: @nornagon 
Notes: none
> chore: return early on promise rejection in cookies.set

- patches/chromium/accelerator.patch
- shell/browser/api/electron_api_menu.cc
- shell/browser/api/electron_api_menu.h
- shell/browser/api/electron_api_menu_mac.h
- shell/browser/api/electron_api_menu_mac.mm
- shell/browser/ui/accelerator_util.cc
- shell/browser/ui/cocoa/electron_menu_controller.mm
- shell/common/gin_converters/blink_converter.cc
- shell/common/keyboard_util.cc
- shell/common/keyboard_util.h
- spec-main/api-menu-item-spec.ts
Backport of #29202
Notes: Fix shifted character getting changed in menu accelerator.
> fix: keep shifted character in menu accelerator

- docs/tutorial/performance.md
Fixes https://github.com/electron/electron/issues/29580
Notes: none
> docs: fix image links in `performance.md`

- docs/tutorial/process-model.md
> docs: fix typo in process-model.md

- .circleci/config.yml
Fixes poor @erickzhao 's CI runs
Notes: none
> build: restore workspace on osx builds to get docs-only-change file

- chromium_src/chrome/browser/certificate_manager_model.cc
- shell/browser/api/electron_api_web_contents.cc
- shell/browser/electron_browser_context.cc
- shell/browser/extensions/electron_extension_system.cc
- shell/renderer/electron_api_service_impl.cc
> refactor: use std::make_unique/base::MakeRefCounted when possible

- docs/api/web-frame.md
Backport of #28860
See that pr for more details.
Notes: no notes.
> docs: Add clarification for Visual Zoom behavior

- .circleci/config.yml
I realized when backporting #29714 that we need to cleanup the directories created by our test suite after running the tests so that the container is properly cleaned up to run the next set of tests.
Notes: none
> ci: cleanup electron dirs after running tests on arm

- shell/browser/api/electron_api_content_tracing.cc
Pulled a simple one out of #29739, seemed like a good candidate for `base::SplitOnceCallback`.
cc @ckerr 
Notes: none
> refactor: migrate AdaptCallbackForRepeating to SplitOnceCallback in content_tracing

- .circleci/config.yml
- spec-main/version-bump-spec.ts
Backport of #29714
Notes: none
> ci: run linux arm tests on CircleCI

- .circleci/config.yml
#29767 was merged with the cross arm mksnapshot tests failing on linux on arm.  This PR fixes those failures.
Notes: none
> ci: fixup cross arch mksnapshot testing

- script/release/ci-release-build.js
> build: add support for spawning builds for a specific commit on appveyor

- shell/browser/notifications/mac/cocoa_notification.mm
Fix the build failure introduced by #29990, sorry!
Notes: none
> fix: build error caused by extra ]

- docs/tutorial/dark-mode.md
Fix the unmatched css file name
Notes: none
> docs: match css filename in dark-mode.md

- docs/api/ipc-main.md
> docs: mention contextIsolation in ipc-main example

- spec-main/api-browser-window-spec.ts
Fix flaky test introduced by https://github.com/electron/electron/pull/29857
Notes: none
> chore: fix flaky fullscreen inheritance test

- script/node-disabled-tests.json
These started failing recently for unknown reasons.
Notes: none
> test: disable failing node tests

- docs/tutorial/electron-timelines.md
* Note about new 8-week cadence
* E15 alpha
* Change months to month abbreviations
Notes: none
> docs: Update timeline for E15 alpha announcement

- shell/browser/login_handler.cc
Backport of #30068.
Notes: Fixed a crash when calling the `webContents.on('login')` callback synchronously.
> fix: crash when invoking login callback synchronously

- docs/api/webview-tag.md
- spec-main/webview-spec.ts
Fix #10042. Document an existing event
https://github.com/electron/electron/blob/21319926a0be74a6c0ce4f9b52f904a9f1f731b0/lib/common/web-view-events.ts#L3
Notes: none
> docs: add <webview> 'did-attach' event documentation

- docs/tutorial/quick-start.md
Change app-quit link definition, so both window-all-closed and app-quit redirects to appropriate sites.
Notes:  none
> docs: update quick-start.md

- spec-main/api-browser-window-spec.ts
Refs https://github.com/electron/electron/pull/30096#issuecomment-878679843
Notes: none
> test: disable flaky fullscreen test

- docs/tutorial/support.md
- script/release/version-bumper.js
- spec-main/fixtures/version-bumper/fixture_support.md
To be merged when we're ready to kick off 14 stable release
Notes: None
> docs: update supported versions to match new release cadence

- shell/browser/api/electron_api_web_contents.cc
- spec-main/api-web-contents-spec.ts
- typings/internal-electron.d.ts
The method is undocumented & unused.
Notes: none
> chore: remove unused getWebPreferences method

- docs/tutorial/security.md
> docs: mention sandboxing in security docs

- docs/tutorial/launch-app-from-url-in-another-app.md
Updating the title of one of the guides so it doesn't look like this:
This should be backported to previous branches where applicable.
cc @erickzhao although I believe is on vacation already
Notes: none
> docs: update title of guide

- script/release/publish-to-npm.js
This ensures that we don't get hit with a rate limit while trying to publish a release.
Notes: none
> chore: update publish to npm to use GitHub token

- lib/browser/guest-view-manager.ts
Simplifies further fixes and refactoring.
Notes: none
> refactor: move related code to makeWebPreferences in guest-view-manager.ts

- spec-main/api-crash-reporter-spec.ts
- spec-main/spec-helpers.ts
Hopefully makes the test a bit more robust. It's been flaking a lot recently.
Notes: none
> test: deflake crashReporter.getLastCrashReport test

- .circleci/config.yml
- vsts-arm32v7.yml
- vsts-arm64v8.yml
Pulls in https://github.com/electron/build-images/pull/11
Notes: none
> build: update build images to update npm and node

- script/generate-deps-hash.js
Looks like we have a bad cache 🤔 
Notes: none
> build: bust the deps cache on windows

- build/npm.gni
- build/webpack/webpack.gni
This aligns the code with the GN Style Guide: https://gn.googlesource.com/gn/+/refs/heads/main/docs/style_guide.md#deps
Notes: none
> build: use fully qualified path names for deps

- shell/common/crash_keys.cc
Adds more detection to the gin::Wrappable crash keys.
cc @vertedinde
Notes: none
> chore: more crash-keys for gin::Wrappable debugging

- shell/common/gin_converters/guid_converter.h
Manual backport of #30442
Notes: none
> fix: explicitly define REFGUID from ::GUID&, not base::GUID (#30442)

- script/node-disabled-tests.json
Backport of #30096
Notes: none
> test: disable failing node tests (#30098)

- build/npm-run.py
Backport of #30093
Notes: none
> build: decode error output as utf8 (#30093)

- shell/browser/api/electron_api_menu.cc
- shell/browser/api/electron_api_menu.h
- shell/browser/api/electron_api_menu_mac.h
- shell/browser/api/electron_api_menu_mac.mm
- shell/common/api/electron_api_v8_util.cc
- shell/renderer/api/electron_api_context_bridge.cc
Backport of #29620
Notes: none
> fix: check DCHECK_IS_ON() instead of #ifdef DCHECK_IS_ON (#29674)

- .circleci/config.yml
Manual backport of #30526
Notes: none
> ci: update git on CI machines (#30526)

- docs/tutorial/updates.md
ref https://github.com/electron/i18n/pull/1993
Notes: none
> docs: update Hazel information

- docs/api/webview-tag.md
- lib/common/web-view-events.ts
- spec/webview-spec.js
Fixes #30378
Notes: Added `<webview>` `'did-redirect-navigation'` event.
> feat: add <webview> 'did-redirect-navigation' event

- spec-main/api-session-spec.ts
Fixes some tests that broke with #30576.
Notes: none
> ci: fix setCertificateVerifyProc tests

- docs/tutorial/process-model.md
Backport of #30690
notes: none
> docs: fix code example in process-model.md (#30690)

- patches/breakpad/.patches
- patches/breakpad/revert_add_inline_and_inline_origin_records_to_symbol_file.patch
- patches/breakpad/revert_remove_warning_about_unknown_abstract_origin.patch
- patches/config.json
> build: temporarily revert broken dump_syms changes in breakpad

- docs/api/auto-updater.md
Squirrel.Mac can be served from a static host as well.
Notes: none
> docs: Update windows info for auto-updater

- shell/common/crash_keys.cc
This change emits a warning when the passed crash key name is longer than the maximum allowed length of 39 bytes.
Notes: Emit a warning when setting a crash key name longer than the maximum allowed length.
> feat: warn when crash key name is longer than 39 bytes

- docs/tutorial/launch-app-from-url-in-another-app.md
Partial Backport of #30194
Backport of #30566
Backport of #30832
See those PRs for details.
Notes: none
> docs(protocols): simplify packaging section & cleanup

- docs/glossary.md
We have a handy glossary that we haven't updated in a while!
New entries: code signing, context isolation, MSI, notarization, preload script, sandbox
Removed entries: libchromiumcontent
Modified entries: ASAR, DMG, NSIS, process
Notes: none
> docs: update glossary

- shell/browser/ui/views/win_frame_view.cc
Backport of #30938.
Notes: None
> fix: add casing for WCO edge

- script/lib/git.py
- script/lib/native_tests.py
- script/lint.js
- script/patches-mtime-cache.py
- script/release/uploaders/upload.py
- script/verify-ffmpeg.py
Backport of #31138
Notes: none
> chore: fix pylint

- docs/api/app.md
> fix: fix typo in description of secureDnsMode

- patches/node/chore_add_context_to_context_aware_module_prevention.patch
Backport of #31579
Notes: none
> chore: update chore_add_context_to_context_aware_module_prevention.patch

- docs/tutorial/electron-timelines.md
> docs: Update E17 release dates

- patches/chromium/chore_provide_iswebcontentscreationoverridden_with_full_params.patch
Backport of #31573.
Notes: none.
> chore: fix malformed mojom::CreateNewWindowParams patch

- docs/tutorial/application-distribution.md
Just a small typo fix
`Instead of from shipping` -> `Instead of shipping`
Notes: none
> docs: Fix typo in distribution docs

- docs/api/web-contents.md
- lib/browser/api/web-contents.ts
> fix: ensure bluetooth devices are not returned by default

- docs/development/testing.md
This pull request fixes a small wording issue on the testing documentation page.
Notes: none
> docs: fix wording on testing documentation

- docs/api/browser-view.md
The previous example was not beginner-friendly
Notes: none
> docs: improve BrowserView example

- patches/chromium/notification_provenance.patch
Cleans up a couple of things missed in ee8b69d0671b0b76c2fe4a2b143eb0448a5bf7b9 and extends the patch to cover another `content::PlatformNotificationService` implementation.
cc @nornagon 
Notes: none
> chore: update notification provenance patch

- package.json
- yarn.lock
Backport of #32420
Notes: none
> build: pin colors to v1.4.0 in package.json

- docs/tutorial/testing-on-headless-ci.md
Hello! I am a Web Producer at CircleCI and noticed a broken link within your docs. I removed the broken link and I also updated the company name so that it is accurate. Thanks a lot.
Notes: none
> docs: Remove broken link and update CircleCI's name

- spec-main/webview-spec.ts
> test: disable flaky test on WOA

- docs/tutorial/support.md
Fixes an error in how supported versions are displayed (this is already fixed in 17-x-y & 18-x-y).
Notes: none
> docs: fix supported versions

- docs/api/browser-window.md
- docs/api/environment-variables.md
Backport of #32478.
Notes: none
> docs: fix anchors for broken relative links

- docs/api/app.md
Closes https://github.com/electron/electron/issues/32582.
Fixes documentation and therefore TS definitions.
Notes: none
> docs: correct requestSingleInstanceLock parameter

- docs/development/build-instructions-gn.md
In continuation of my efforts to improve doc for building electron, these are some improvements that I did which I feel improves the doc readability for someone who is new to building electron. 
**Release Notes**
Notes: none
> docs: Update the build docs for electron to improve doc readability

- docs/api/browser-window.md
> docs: fix typo in BrowserWindow description

- docs/api/web-contents.md
Hopefully this cleans up some confusion. Ref #32748.
Notes: none
> docs: clarify meaning of cssOrigin

- docs/tutorial/performance.md
- docs/tutorial/security.md
The security and performance checklists are great resources for developers, but need some cleanup for 2022.
1. Updates guides with `contextIsolation` changes and `remote` module removal.
2. Changes heading hierarchy to be more readable (e.g. "Checklist" is 1 level above all checklist items now).
3. Uses Docusaurus frontmatter to hide all H4s (all the Why? and How? sections) from the website to avoid cluttering the table of contents.
4. Leverages some Docusaurus markup features we didn't use before (`title` meta for code blocks, admonitions, etc.)
5. A little arbitrary, but I changed `1)` for `1.` in the headings.
Notes: none
> docs: update checklists

- shell/common/node_bindings.cc
This PR improves error handling during Node.js Environment creation. Previously, it was very hard to diagnose Environment creation failures owing to the fact that we only surfaced errors when creation failed in the renderer process, and even then only logged an error amounting to "this failed". This makes it much harder during upgrades, for example, to more effectively identify and fix bootstrapping problems with descriptive errors.
Before: 
```
[72201:0210/194105.829906:FATAL:node_bindings.cc(485)] Check failed: env.
```
After:
```
[75744:0210/194903.608995:ERROR:node_bindings.cc(500)] Failed to initialize node environment in process: browser with error: Missing internal module 'internal/process/promises'
[75744:0210/194903.609014:FATAL:node_bindings.cc(503)] Check failed: env.
``` …
> chore: improve error catching in NodeBindings

- patches/devtools_frontend/fix_expose_globals_to_allow_patching_devtools_dock.patch
Fix CI failure on main due to out-of-date patch.
Notes: none
> chore: update patch to fix CI

- lib/browser/api/net.ts
- shell/browser/api/electron_api_power_monitor_win.cc
- shell/browser/api/electron_api_url_loader.cc
- shell/browser/auto_updater_mac.mm
- shell/browser/browser_mac.mm
- shell/browser/native_window_mac.mm
- shell/browser/native_window_views_win.cc
- shell/browser/ui/message_box_win.cc
- shell/browser/ui/win/electron_desktop_window_tree_host_win.cc
- shell/common/gin_helper/function_template.h
- shell/common/platform_util_linux.cc
- shell/renderer/electron_render_frame_observer.cc
- shell/renderer/electron_renderer_client.cc
- spec-main/index.js
Just fixing some typos, they're all in comments and one log message.
Notes: none
> chore: fix typos

- patches/chromium/.patches
- patches/chromium/cleanup_pausablecriptexecutor_usage.patch
Cleanup PausablecriptExecutor usage.
Improve performance of API so we don't have to go from
WTF::String->WebString->WTF::String for execution.
Ensure the Executor is traced via the PausableScriptExecutor.
BUG=[1289384](https://bugs.chromium.org/p/chromium/issues/detail?id=1289384)
(cherry picked from [commit c8231f9a89460fd8336e6c0d8e10347f52f540ec](https://chromium-review.googlesource.com/q/commit:c8231f9a89460fd8336e6c0d8e10347f52f540ec))
Change-Id: [If9badab91222c49c08a983c60132ce71b183e951](https://chromium-review.googlesource.com/q/If9badab91222c49c08a983c60132ce71b183e951)
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3407654
Reviewed-by: Michael Lippautz <[mlippautz@chromium.org](mailto:mlippautz@chromium.org)>
Reviewed-by: Daniel Cheng …
> chore: cherry-pick 11505c3867 from chromium

- patches/chromium/.patches
- patches/chromium/build_disable_thin_lto_on_mac.patch
- shell/app/electron_main_delegate.cc
This PR manually backports two PRs needed to fix the release
Manual backport of #32854
Manual backport of #33115 
Notes: none
> chore: fixup 18-x-y release

- docs/api/browser-window.md
Fixed a typo in the API documentation of `BrowserWindow` (changed "make app feel more native" to "make the app feel more native").
Notes: Fixed a typo in the API documentation for BrowserWindow.
> docs: Fixed a typo

- spec-main/fixtures/native-addon/uv-dlopen/foo.cpp
- spec-main/fixtures/native-addon/uv-dlopen/main.cpp
Formatted C++ Files According to the clang-format file.
notes: none
> test: Formatted C++ Files According to the clang-format file.

- docs/tutorial/process-model.md
"The main process' primary purpose" -> "The primary purpose of the main process"
As suggested in comments, reworded the [sentence](https://www.electronjs.org/docs/latest/tutorial/process-model#window-management) for a better understanding.
Notes: none
> docs: reword sentence for better understanding

- docs/api/app.md
- docs/api/client-request.md
- docs/api/command-line-switches.md
- docs/api/content-tracing.md
- docs/api/session.md
- docs/api/structures/protocol-response.md
- docs/api/structures/trace-config.md
- docs/api/web-contents.md
- docs/development/build-instructions-gn.md
- docs/development/build-instructions-windows.md
- docs/glossary.md
- docs/tutorial/sandbox.md
Mostly updates `master` -> `main` in the Chromium source links. I also confirmed all of the links I touched are still valid as of this PR, with one change for a broken link for a renamed file.
Notes: none
> docs: update links to Chromium source

- script/lib/util.py
- script/release/uploaders/upload.py
Removed imported objects which were being unused.
Notes: none
> fix: removed unused import

- docs/tutorial/ipc.md
The `counter` channel should be `update-counter` channel
Just some possible typos
Notes: none
> docs: possible change in tutorial/ipc

- shell/common/node_bindings.cc
- shell/common/node_bindings.h
- shell/common/node_bindings_linux.cc
- shell/common/node_bindings_linux.h
- shell/common/node_bindings_mac.cc
- shell/common/node_bindings_mac.h
- shell/common/node_bindings_win.cc
- shell/common/node_bindings_win.h
- shell/renderer/electron_renderer_client.cc
Backport of https://github.com/electron/electron/pull/33207
Notes: fix broken event loop in renderer process when process reuse is enabled on windows platform
> fix: iocp integration when process is reused

- .github/ISSUE_TEMPLATE/bug_report.yml
Gentle reminder to only report issues for supported versions, and also bumps the versions in placeholder text since those are unsupported versions now.
Notes: none
> docs: add note about supported versions to issue template

- spec-main/api-debugger-spec.ts
This test was disabled a [long time ago](https://github.com/electron/electron/issues/21470), and never followed up on.
It seems like enabling the network capture _after_ the load rather than before
is necessary. I think this is because before the load, no renderer process
exists, so the attach / `Network.enable` maybe get queued? And then delivered
too late to catch the navigation load. Enabling the network synchronously
immediately after the load seems to be fast enough to catch the response.
Fixes #21470.
Notes: none
> test: fix and re-enable Network.getResponseBody test

- README.md
These are now being built on 20.04, and 18.04 is going EOL in April.
Notes: none
> docs: update Ubuntu version used for Linux prebuilt binaries

- spec/webview-spec.js
Reverts electron/electron#33220
This was merged with failing CI.  
Notes: none
> test: Revert "test: re-enable webview resize events test"

- README.md
Source: https://zhuanlan.zhihu.com/p/465424728
Notes: none
> docs: update china npmmirror

- shell/browser/api/electron_api_web_contents.cc
- spec-main/api-browser-view-spec.ts
- spec-main/api-browser-window-spec.ts
Manual backport of #32973
Notes: Fix the IncrementCapturerCount regression introduced by 13.0.0-beta.21
> fix: IncrementCapturerCount doesn't increase the capturer count

- docs/breaking-changes.md
Remove some confusing text from the breaking-changes document.
Notes: none
> docs: simplify skipTaskbar breaking changes text

- shell/browser/electron_browser_handler_impl.h
> fix: building with printing disabled

- shell/browser/native_window.cc
- shell/browser/native_window.h
- shell/browser/ui/cocoa/electron_ns_window_delegate.mm
Just a typo I spotted while reading this code.
Notes: none
> chore: fix typo in NotifyWindowRequestPreferredWidth method name

- build/args/all.gn
Per: https://electronhq.slack.com/archives/C5VT8SQ8K/p1649804939676079?thread_ts=1649804900.892869&cid=C5VT8SQ8K
> build: add comment for enable_cet_shadow_stack

- docs/fiddles/ipc/pattern-1/index.html
- docs/fiddles/ipc/pattern-1/main.js
- docs/fiddles/ipc/pattern-1/preload.js
- docs/fiddles/ipc/pattern-1/renderer.js
- docs/fiddles/ipc/pattern-2/index.html
- docs/fiddles/ipc/pattern-2/main.js
- docs/fiddles/ipc/pattern-2/preload.js
- docs/fiddles/ipc/pattern-2/renderer.js
- docs/fiddles/ipc/pattern-3/index.html
- docs/fiddles/ipc/pattern-3/main.js
- docs/fiddles/ipc/pattern-3/preload.js
- docs/fiddles/ipc/pattern-3/renderer.js
Backport of https://github.com/electron/electron/pull/32059
Following #33746 
notes: none
> docs: add ipc fiddle samples

- build/args/all.gn
Expand docs for why we set is_cfi = false
Notes: none
> docs: note reason for is_cfi = false

- package.json
- script/lib/azput.js
- script/lib/util.py
- script/release/release.js
- script/release/uploaders/upload-index-json.py
- script/release/uploaders/upload-node-checksums.py
- script/release/uploaders/upload-node-headers.py
- script/release/uploaders/upload-symbols.py
- script/release/uploaders/upload.py
- yarn.lock
> build: upload to AZ as well as S3

- .circleci/config/base.yml
- BUILD.gn
- script/node-disabled-tests.json
> build: improve CI speeds and reduce CI costs (#33904)

- shell/browser/net/system_network_context_manager.cc
Manual backport of #33971
Notes: Fixed the initialization of First Party Sets
> fix: fix FirstPartySetsHandler initialization

- spec/fixtures/pages/native-module.html
Follow-up to #33822
Notes: none
> test: fix require('echo') -> require('@electron-ci/echo')

- spec-main/api-browser-window-spec.ts
- spec-main/api-web-frame-main-spec.ts
Fixes a few race condition to make these tests more reliable
> test: unflake some focus tests

- spec-main/chromium-spec.ts
This is flaking in the 16-x-y branch too
> test: also disable flaky WOA test on v16

- docs/api/app.md
Adds a missing parameter to the code sample for `app.requestSingleInstanceLock`.
Notes: none
> docs: add missing ackCallback parameter

- docs/tutorial/quick-start.md
According to Jetbrains LanguageTool, "Consider using All the. "
> docs: fix typo in quick-start.md

- .circleci/config/base.yml
- BUILD.gn
- script/node-disabled-tests.json
> build: improve CI speeds and reduce CI costs

- spec-main/api-browser-window-spec.ts
- spec-main/fixtures/apps/background-color-transparent/main.js
Pretty sure this fixes the flake, if it doesn't I also added a log that should make it more debuggable
> test: fix background transparency flake

- build/args/all.gn
Add missing explanation for
https://github.com/electron/electron/blob/8b5613efcbd322ea19407f8655b4691b09c3b2b4/build/args/all.gn#L24-L25
Notes: none
> docs: add missing explanation for [angle|dawn]_enable_vulkan_validation_layers = false

- patches/config.json
- patches/icu/.patches
- patches/icu/m100_cp_pr_2070_fix_int32_overflow.patch
[m100] CP PR 2070 fix int32 overflow
https://github.com/unicode-org/icu/pull/2070
https://unicode-org.atlassian.net/browse/ICU-22005
Bug: chromium:1316946
Change-Id: I6cd7d687a55b6cc157b1afa52365908be2992fa6
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/deps/icu/+/3614280
Reviewed-by: Jungshik Shin <jshin@chromium.org>
(cherry picked from commit 85814e1af52482199a13d284545623ffbc9eef83)
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/deps/icu/+/3632709
Notes: Backported fix for CVE-2022-1638.
> chore: cherry-pick 14e51893e5 from icu

- docs/api/safe-storage.md
- shell/browser/api/electron_api_safe_storage.cc
- shell/browser/electron_browser_main_parts.cc
- shell/browser/net/system_network_context_manager.cc
- spec-main/api-safe-storage-spec.ts
- spec-main/fixtures/crash-cases/safe-storage/index.js
Backport of https://github.com/electron/electron/pull/33913.
Notes: none.
> fix: crash in `safeStorage` on Linux

- appveyor.yml
Manual backport of #33510
Notes: none
> ci: save Windows artifacts at end of job in case they fail

- shell/browser/api/electron_api_system_preferences_mac.mm
- shell/browser/api/electron_api_web_contents.cc
- shell/browser/mac/electron_application_delegate.mm
- shell/browser/mac/in_app_purchase_product.mm
- shell/browser/native_window_mac.mm
- shell/browser/ui/cocoa/electron_menu_controller.mm
- shell/browser/ui/cocoa/electron_ns_window.mm
- shell/browser/ui/cocoa/electron_ns_window_delegate.mm
- shell/browser/ui/cocoa/electron_touch_bar.h
- shell/browser/ui/cocoa/electron_touch_bar.mm
Remove redundant `@available` checks now that the minimum version is `10.13.0`
Notes: none
> chore: remove redundant @available checks

- script/run-clang-tidy.ts
I fixed `--use-color` on Windows [upstream in LLVM](https://reviews.llvm.org/D90109) a while back and forgot to come back and make use of it here instead of manually recoloring.
Notes: none
> build: switch to --use-color flag for clang-tidy

- patches/config.json
- patches/ffmpeg/cherry-pick-e481fc655a62.patch
ref https://github.com/electron/electron/pull/34559
Notes: none
> chore: add ffmpeg patch dir to config.json

- shell/browser/ui/drag_util_mac.mm
Backport of #34615.
Notes: none
> refactor: remove deprecated drag-and-drop code

- shell/browser/api/electron_api_web_request.cc
Modernize usage of base::Value in WebRequest
Notes: none
> chore: modernize base::Value usage in WebRequest

- shell/browser/api/electron_api_session.cc
- shell/browser/electron_browser_context.cc
Modernize ListValue code in Session.
ListValue is deprecated.
Notes: none
> chore: modernize ListValue code in session

- shell/renderer/printing/print_render_frame_helper_delegate.cc
> chore: modernize base::Value usage in shell/renderer/printing

- spec-main/api-browser-window-spec.ts
This is likely a holdover from when maximize wasn't firing like it should.
Notes: none
> test: use maximize event instead of resize event

- shell/browser/api/electron_api_browser_window.cc
- shell/browser/api/electron_api_url_loader.cc
- shell/browser/electron_autofill_driver.cc
- shell/browser/extensions/api/runtime/electron_runtime_api_delegate.cc
Cleaning up a few spurious trailing namespace comments.
Notes: none
> chore: remove spurious trailing namespace comments

- shell/browser/ui/webui/accessibility_ui.cc
Modernize usage of base::Value in accessibility_ui.cc
Notes: none
> chore: modernize base::Value usage in accessibility_ui

- script/release/ci-release-build.js
We recently updated `got` in both electron/electron and in build-tools. This PR slightly modifies which parameters are passed into makeRequest -> got as top level auth parameters. Fixes nightly.
Notes: none
> build: update makeRequest parameters

- .github/workflows/release_dependency_versions.yml
Makes GitHub's workflow editor happy about the release_dependency_versions github workflow.
Notes: none
> build: fix release_dependency_versions workflow

- shell/browser/api/electron_api_web_contents.cc
- shell/browser/ui/inspectable_web_contents.cc
- shell/browser/ui/inspectable_web_contents.h
ListValue is deprecated, switch to Value::List
Notes: none
> chore: modernize some devtools code using deprecated ListValue

- shell/common/asar/archive.cc
- shell/common/asar/archive.h
base::DictionaryValue is deprecated.
Notes: none
> chore: modernize base::Value useage in asar/archive

- .circleci/config/base.yml
Backport of #34850
Notes: none
> build: run CI tests on Xcode 13.3.0

- patches/chromium/short-circuit_permissions_checks_in_mediastreamdevicescontroller.patch
Fixes a patch update in `main`
Notes: none
> build: update mediastreamdevicescontroller.patch

- shell/browser/ui/views/menu_bar.cc
- shell/browser/ui/views/menu_delegate.cc
> refactor: use Get/SetID from views:View in Button

- spec-main/api-clipboard-spec.ts
> test: migrate clipboard spec to spec-main

- docs/api/native-image.md
- spec-main/api-native-image-spec.ts
Also, simplify the tests somewhat.
I don't believe we need to test this in both main and renderer as the
underlying code is not different.
Notes: none
> test: migrate nativeImage specs to main

- spec-main/api-global-shortcut-spec.ts
- spec-main/api-web-contents-spec.ts
- spec/package.json
robotjs isn't present in any of our package.json files, so these tests are
never run, and as such are likely broken.
Notes: none
> test: remove references to robotjs

- spec-main/chromium-spec.ts
- spec/chromium-spec.js
- spec/fixtures/pages/shared_worker.html
- spec/fixtures/pages/worker.html
> test: migrate more chromium specs to main

- patches/node/build_ensure_v8_pointer_compression_sandbox_is_enabled_on_64bit.patch
Manual backport of #34914
Notes: Fixes native module compilation issues on arm
> fix: ensure that v8 sandbox isnt enabled for arm

- shell/browser/native_window_views.cc
Follow-up to https://github.com/electron/electron/pull/35123
Notes: none
> chore: remove unsupported skiptaskbar linux impl

- docs/tutorial/introduction.md
The introduction documentation page describes each of the categories available in the sidebar, but some of the category titles didn't match.
Notes: none
> docs: update categories to match sidebar

- docs/tutorial/tutorial-4-adding-features.md
Relands https://github.com/electron/electronjs.org-new/pull/240 upstream.
Notes: none
> docs: fix link in tutorial

- spec-main/webview-spec.ts
- spec/static/main.js
- spec/webview-spec.js
Following on from #35076.
Notes: none
> test: migrate <webview> tag event specs to main runner

- README.md
> docs: remove reference to electron/i18n in README

- shell/browser/mac/electron_application_delegate.mm
- spec-main/api-browser-window-spec.ts
There are flaky crashes on mas arm64, eg : https://app.circleci.com/pipelines/github/electron/electron/56374/workflows/f36ca7bb-9b6e-4a76-89af-c09c37a0aa83/jobs/1284377.  This PR disables those tests temporarily until we can fix the underlying issue.
Notes: none
> test: temporarily disable tests on mas arm64 that are causing a crash

- lib/asar/fs-wrapper.ts
- lib/browser/api/auto-updater/squirrel-update-win.ts
- lib/browser/api/desktop-capturer.ts
- lib/browser/api/touch-bar.ts
- lib/browser/guest-view-manager.ts
> refactor: use optional chaining / nullish coalescing operator

- docs/api/session.md
> docs: fix getStoragePath return type

- shell/browser/browser_mac.mm
As of https://chromium-review.googlesource.com/c/chromium/src/+/2522876 - our previous implementation of `RemoveFromLoginItems()` is functionally identical to that in `base::mac`. Simplify by calling into that implementation instead, given we already call into `base::mac::AddToLoginItems`.
Notes: none
> refactor: simplify `Browser::SetLoginItemSettings`

- docs/tutorial/introduction.md
Updates "What is in the docs?" to match titles in sidebar
Notes: none
> docs: update docs description to match sidebar

- docs/tutorial/tutorial-3-preload.md
Close https://github.com/electron/electron/issues/35157.
This change adds the required lines to the sample code so that it can be used directly via copy/paste without any hassle.
Notes: none
> docs: fix missing includes in code example

- docs/tutorial/security.md
Pr #33369 added a new security guideline leaving the [checklist](https://github.com/electron/electron/blob/main/docs/tutorial/security.md#checklist-security-recommendations) section unmodified.
This pr essentially adds its corresponding link to checklist :)
Notes: none
> docs: add IPC validation guideline link in checklist

- docs/tutorial/tutorial-2-first-app.md
Minor grammar fixes in part two of tutorial documentation.
Notes: none.
> docs: minor grammar fixes in tutorial

- .github/semantic.yml
I believe this went stale as a result of #33857 since this file is a config for the previous implementation which is no longer used.
Notes: none
> build: remove unused GitHub app config file

- .github/workflows/release_dependency_versions.yml
Fixes errors as seen [here](https://github.com/electron/electron/actions/workflows/release_dependency_versions.yml).
Notes: none
> build: fix major dependencies update workflow file

- script/lint.js
Shores up patch file linting logic to make the output cleaner and not include stack traces.
Before:
```
Error: Expected all the patch files listed in the .patches file at "/Users/codebytere/Developer/electron-gn/src/electron/patches/v8/.patches" to exist but some did not:
[
"revert_runtime_dhceck_terminating_exception_in_microtasks.patch",
"chore_disable_is_execution_terminating_dcheck.patch"
]
at Object.run (/Users/codebytere/Developer/electron-gn/src/electron/script/lint.js:218:15)
at main (/Users/codebytere/Developer/electron-gn/src/electron/script/lint.js:338:20)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
After:
```
Expected all the patch files listed in the .patches file at …
```
> build: clean up patch linting errors

- lib/common/reset-search-paths.ts
- spec/modules-spec.ts
https://github.com/electron/electron/pull/35915 landed without any tests, so this change adds some. This also documents why these variations exist. I admit, it isn't the best place for documenting such a thing because it's not very accessible but I don't know what the best place is either, so suggestions welcome!
Notes: none 
cc @MarshallOfSound
> test: add tests for valid electron module names

- docs/api/session.md
- shell/browser/api/electron_api_web_contents.cc
- shell/browser/electron_browser_client.cc
- shell/browser/web_contents_permission_helper.cc
- shell/browser/web_contents_permission_helper.h
> fix: pass rfh instances through to the permission helper

- docs/breaking-changes.md
> docs: fix erroneous removal warning for decrementCapturerCount

- appveyor.yml
Manual backport of #35377
Notes: none
> ci: use AppVeyor workflows

- appveyor.yml
This should for sure fix the nightly release, maybe, I hope.  Honestly there's a chance...
> build: use python3 for appveyor commands

- docs/tutorial/process-model.md
Follow-up to https://github.com/electron/electron/pull/34980#discussion_r988155989
> docs: add utility process info to tutorial docs

- BUILD.gn
- filenames.gni
Backport of #36193
Notes: none
> build: fix building with enable_plugins = false

- docs/api/app.md
There is no `driverId` (AFAIK).
Notes: none
> docs: fix driverId -> deviceId typo

- script/sysroots.json
- #35628 reintroduced the issue resolved in #34491.  This fixes the issue with a better fix.
- Resolves #35877
Notes: none
> fix: arm linux glibc dependency

- .github/workflows/release_dependency_versions.yml
> ci: pin version of actions/checkout

- .github/workflows/semantic.yml
> ci: pin amannn/action-semantic-pull-request

- README.md
Minor tweak, just tweaking three characters to reflect the actual handle on Twitter. Banding! @electron/wg-outreach 
> docs: update README.md to use correct twitter handle

- .github/PULL_REQUEST_TEMPLATE.md
add a check for broken guides/templates to the pr template to aid in keeping our documentation up to date
Notes:  none
> docs: change pull request template to include mentions of templates and examples

- .github/workflows/update_appveyor_image.yml
- appveyor-bake.yml
- appveyor.yml
- build/profile_toolchain.py
- script/lib/utils.js
- script/prepare-appveyor.js
- script/release/ci-release-build.js
- script/setup-win-for-dev.bat
- spec/api-browser-view-spec.ts
- spec/api-browser-window-spec.ts
Manual backport of #35396
Notes: none
> ci: bake appveyor images automatically, run sync on depshash change

- shell/browser/ui/tray_icon_gtk.cc
- shell/browser/ui/tray_icon_gtk.h
Follow-up to #36333
Notes: none
> refactor: make StatusIconType an enum class

- appveyor-bake.yml
- appveyor.yml
- script/prepare-appveyor.js
Our Windows image used by Appveyor needed Windows updates applied to it.  This PR updates the image and also changes our bake process to use the latest image which should make bakes run faster.
Notes: <!-- Please add a one-line description for app developers to read in the release notes, or 'none' if no notes relevant to app developers. Examples and help on special cases: https://github.com/electron/clerk/blob/master/README.md#examples - ->none
> chore: update AppVeyor image to include latest Windows updates

- docs/tutorial/tutorial-3-preload.md
The line in the main.js file change was displayed incorrectly, so it was corrected.
Notes: none
> docs: main.js file change was displayed incorrectly

- docs/tutorial/tutorial-3-preload.md
The highlighted lines in the code snippets were unaligned, which could cause a newcomer unneeded confusion on what lines need to be changed.
notes: none
> docs: update code highlights in tutorial

- .github/PULL_REQUEST_TEMPLATE.md
Just tidying up more links after `master` -> `main` switch overs.
Notes: none
> chore: update electron/clerk links in PR template

- docs/README.md
- docs/api/auto-updater.md
- docs/api/utility-process.md
- docs/tutorial/boilerplates-and-clis.md
- docs/tutorial/forge-overview.md
- docs/tutorial/notifications.md
- docs/tutorial/performance.md
- docs/tutorial/snapcraft.md
- docs/tutorial/tutorial-4-adding-features.md
- docs/tutorial/tutorial-6-publishing-updating.md
Updates various links, including link text (`electron-forge` -> Electron Forge) and also one header since I was cleaning up other Electron Forge stuff.
Notes: none
> docs: update links

- docs/api/app.md
See https://github.com/electron/electron/issues/20322
Notes: none
> docs: Add note about argv getting modified

- docs/breaking-changes.md
Backticks around the link were breaking the rendering of it.
Notes: none
> docs: fix link in breaking-changes.md

- .github/workflows/stale.yml
Closes https://github.com/electron/electron/issues/36842.
Notes: none.
> build: fix broken stale issues workflow

- .github/workflows/release_dependency_versions.yml
Update mksnapshot for every release, not just major.
Notes: none.
> build: update release deps workflow

- .github/workflows/semantic.yml
Updates action version to clear the deprecation warning about Node v12.
Notes: none
> ci: update amannn/action-semantic-pull-request version

- spec/chromium-spec.ts
Fixes an issue in one of the USB devices tests. Might only repro locally since the test behavior changes based on USB devices found.
Notes: none
> test: fix test for USB device.forget()

- docs/api/clipboard.md
- docs/fiddles/system/clipboard/copy/index.html
- docs/fiddles/system/clipboard/copy/main.js
- docs/fiddles/system/clipboard/copy/preload.js
- docs/fiddles/system/clipboard/copy/renderer.js
- docs/fiddles/system/clipboard/paste/index.html
- docs/fiddles/system/clipboard/paste/main.js
- docs/fiddles/system/clipboard/paste/preload.js
- docs/fiddles/system/clipboard/paste/renderer.js
> docs: update clipboard fiddles

- patches/chromium/.patches
- patches/chromium/axselectedtextmarkerrange_should_not_be_backwards.patch
Refs https://github.com/microsoft/vscode/issues/144791
Backports https://bugs.chromium.org/p/chromium/issues/detail?id=1172956
Notes: fix voiceover repeating selected text when expanding selection in a textarea
> chore: cherry-pick 5e04f643 from chromium

- package.json
- script/spec-runner.js
- yarn.lock
Backport of https://github.com/electron/electron/pull/36944
Notes: none
> test: support running tests against Electron releases

- lib/renderer/web-view/web-view-attributes.ts
- lib/renderer/web-view/web-view-constants.ts
- lib/renderer/web-view/web-view-element.ts
- lib/renderer/web-view/web-view-impl.ts
Decrease the entropy a bit :)
Notes: none
> refactor: separate WEB_VIEW_ATTRIBUTES / WEB_VIEW_ERROR_MESSAGES

- docs/fiddles/system/protocol-handler/launch-app-from-URL-in-another-app/main.js
- docs/tutorial/launch-app-from-url-in-another-app.md
Notes: In deep link docs the windows specific code also contains macOS/Linux code which is confusing.
> docs: updated deep link docs

- shell/browser/ui/views/autofill_popup_view.cc
> fix: ensure autofill popup view is > 1x1 in size

- .circleci/config/base.yml
#37069 fixed regular builds but Linux release builds were still failing.  This PR fixes that issue.
Notes: none
> ci: fixup ninja for release

- docs/README.md
Has gotten a bit out-of-date, so updating it to be more accurate.
Notes: none
> docs: update modules list in docs/README.md

- docs/api/browser-window.md
Closes https://github.com/electron/electron/issues/37040.
Notes: none
> docs: note how to clear an aspect ratio

- lib/sandboxed_renderer/init.ts
- shell/renderer/electron_sandboxed_renderer_client.cc
- shell/renderer/electron_sandboxed_renderer_client.h
This makes the code more robust and eliminates duplication
Notes: none
> refactor: process event emitting for sandboxed renderers

- .github/workflows/stale.yml
- .github/workflows/update_appveyor_image.yml
For easier testing/debugging, allow manual triggering of some GitHub Actions.
Notes: none
> build: allow workflow_dispatch on scheduled Actions

- docs/api/context-bridge.md
`ipcRenderer` is used but not required.
Notes: none
> docs: add missing ipcRenderer require to example code

- .github/workflows/release_dependency_versions.yml
Backport of https://github.com/electron/electron/pull/37036
Notes: none
> build: fixup release_dependency_versions action

- script/lib/config.py
The TODO is from 2016, seems like it's time.
Notes: none
> chore: remove old script code for ATOM_SHELL_

- spec/index.js
> build: only retry tests on CI

- docs/development/creating-api.md
- shell/common/node_bindings.cc
- spec-main/internal-spec.ts
Backport of #35949
Notes: none
> fix: expose native bindings by process type

- docs/api/session.md
- spec/chromium-spec.ts
> docs: add missing clipboard-sanitized-write permission value to setPermissionRequestHandler()

- appveyor-woa.yml
- appveyor.yml
- build/args/all.gn
- shell/browser/api/message_port.h
- shell/browser/electron_browser_main_parts.cc
- shell/browser/native_window_mac.mm
- shell/browser/ui/gtk_util.cc
- spec/ts-smoke/electron/main.ts
- spec/ts-smoke/electron/renderer.ts
No functional changes, just updating links in comments. Mostly `master` -> `main`, but also fixes a handful of broken links.
Notes: none
> chore: update links in comments

- package.json
- script/release/release.js
- yarn.lock
Ensure the right versions are tagged as `Latest` on GitHub according to semver instead of by recency.
> build: set make_latest correctly on published releases

- script/release/uploaders/upload.py
Adds verbose logging to help debug json/release errors
Notes: none
> chore: add logging for debugging release json

- script/release/uploaders/upload.py
Refs https://github.com/electron/electron/pull/37270
Notes: none
> build: add missing `is_verbose_mode` import

- script/lint.js
- spec/ts-smoke/electron/main.ts
- spec/ts-smoke/electron/renderer.ts
- spec/ts-smoke/runner.js
There is no reason for these files to be excluded from linting
Notes: none
> test: enable linting of ts-smoke and fix all issues

- spec/api-browser-window-spec.ts
- spec/api-ipc-spec.ts
- spec/api-protocol-spec.ts
- spec/api-service-workers-spec.ts
- spec/api-web-contents-spec.ts
- spec/api-web-request-spec.ts
- spec/chromium-spec.ts
Just use plain variable declarations
Notes: none
> test: cleanup let xyz = null as unknown as T;

- spec/api-menu-item-spec.ts
Improves type-safety
Notes: none
> test: type-safe import of menu-item-roles in api-menu-item-spec.ts

- spec/api-app-spec.ts
- spec/api-browser-window-spec.ts
- spec/api-context-bridge-spec.ts
- spec/api-crash-reporter-spec.ts
- spec/api-debugger-spec.ts
- spec/api-ipc-spec.ts
- spec/api-media-handler-spec.ts
- spec/api-net-log-spec.ts
- spec/api-net-spec.ts
- spec/api-protocol-spec.ts
- spec/api-service-workers-spec.ts
- spec/api-session-spec.ts
- spec/api-shell-spec.ts
- spec/api-subframe-spec.ts
- spec/api-web-contents-spec.ts
- spec/api-web-frame-main-spec.ts
- spec/api-web-request-spec.ts
- spec/chromium-spec.ts
- spec/extensions-spec.ts
- spec/guest-window-manager-spec.ts
- spec/lib/spec-helpers.ts
- spec/security-warnings-spec.ts
- spec/spellchecker-spec.ts
- spec/webview-spec.ts
Also adds an async `listen` helper to eliminate duplicate code.
Notes: none
> test: convert functions to async & eliminate duplicates

- docs/breaking-changes.md
This'll probably hit a fair few apps, so note it in breaking changes.
Notes: none
> docs: document change in draggable region behavior on macOS

- .github/config.yml
Refs https://github.com/electron/trop/pull/247.
Notes: none
> chore: remove dead config code for trop

- .github/CODEOWNERS
To ensure better visibility for Releases WG on changes to `/docs/breaking-changes.md`.
Notes: none
> chore: set wg-releases as owner of /docs/breaking-changes.md

- .circleci/config.yml
> build: set base rev 24-x-y

- .circleci/config.yml
> build: set base rev 23-x-y

- lib/browser/api/web-contents.ts
> refactor: use _loadURL(url, options ?? {});

- docs/api/clipboard.md
Updates the clipboard API doc, demo code uses wrong variable.
Notes:  none
> docs(clipboard): fix an issue of demo code

- docs/fiddles/features/web-usb/main.js
- docs/fiddles/features/web-usb/renderer.js
- While working on #37441, I realized that the fiddle for WebUSB had some errors.  This PR fixes those errors.
Notes: none
> docs: fixup WebUSB fiddle

- docs/api/app.md
- docs/api/notification.md
- docs/api/push-notifications.md
- docs/development/creating-api.md
- docs/development/debugging-on-windows.md
- docs/tutorial/code-signing.md
- docs/tutorial/tutorial-6-publishing-updating.md
Fixing broken links - the low hanging fruit from `yarn run lint:docs-relative-links --fetch-external-links`.
Notes: none
> docs: update broken links

- shell/browser/api/electron_api_debugger.cc
- shell/browser/api/electron_api_web_request.cc
- shell/browser/ui/inspectable_web_contents.cc
- shell/browser/ui/webui/accessibility_ui.cc
- shell/common/gin_converters/net_converter.cc
Small cleanup and follow-up to #37570
Notes: none
> chore: remove unnecessary casting to base::Value

- docs/api/app.md
- docs/api/auto-updater.md
- docs/api/browser-window.md
- docs/api/native-image.md
- docs/api/system-preferences.md
- docs/faq.md
- docs/fiddles/menus/customize-menus/index.html
- docs/tutorial/recent-documents.md
- docs/tutorial/using-native-node-modules.md
Backport of #37603
Notes: none
> docs: change MSDN links to new Microsoft docs

- docs/api/structures/ipc-main-event.md
- docs/api/structures/ipc-main-invoke-event.md
- docs/api/structures/ipc-renderer-event.md
> docs: add links to IPC event structures

- appveyor-woa.yml
- appveyor.yml
- spec/package.json
- spec/yarn.lock
Request has an unresolved audit issue, this switches us to a fork of the only dependency that uses it so we can clean up our audit report
> build: remove request dependency

- shell/app/electron_main_mac.cc
Ref https://chromium-review.googlesource.com/c/chromium/src/+/2015364
Notes: none
> fix: record helper error messages in electron_main_mac

- .markdownlint.json
- CONTRIBUTING.md
- docs/api/app.md
- docs/api/browser-window.md
- docs/api/menu-item.md
- docs/api/menu.md
- docs/api/native-image.md
- docs/api/session.md
- docs/api/tray.md
- docs/api/web-contents.md
- docs/api/webview-tag.md
- docs/development/azure-vm-setup.md
- docs/development/goma.md
- docs/development/issues.md
- docs/development/pull-requests.md
- docs/tutorial/boilerplates-and-clis.md
- docs/tutorial/electron-timelines.md
- docs/tutorial/electron-versioning.md
- docs/tutorial/macos-dock.md
- docs/tutorial/offscreen-rendering.md
- docs/tutorial/performance.md
- docs/tutorial/recent-documents.md
- docs/tutorial/security.md
Backport of #37787.
Notes: none
> chore: enforce consistent Markdown style for strong and emphasis

- shell/renderer/api/electron_api_context_bridge.cc
- spec/api-context-bridge-spec.ts
Similar to #37895, fixes an additional crash case + an infinite hang case in the promise resolution code path.
> fix: exceptions during function/promise result conversions live in calling world

- docs/api/auto-updater.md
- docs/api/crash-reporter.md
- docs/development/coding-style.md
- docs/tutorial/boilerplates-and-clis.md
- docs/tutorial/mac-app-store-submission-guide.md
- docs/tutorial/security.md
- docs/tutorial/snapcraft.md
- docs/tutorial/updates.md
- docs/tutorial/windows-store-guide.md
Continuing cleanup of links in the doc which redirect.
Notes: none
> docs: update github.com links

- docs/tutorial/tutorial-2-first-app.md
Fix code line highlighted in this page/section : https://www.electronjs.org/docs/latest/tutorial/tutorial-first-app#running-an-electron-app
> docs: fix start highlight tutorial-2-first-app.md

- docs/api/web-contents.md
- spec/api-web-contents-spec.ts
- spec/chromium-spec.ts
Manual backport of https://github.com/electron/electron/pull/38026
Notes: none
> fix: webContents return type incorrect

- shell/browser/hid/electron_hid_delegate.h
- shell/browser/serial/electron_serial_delegate.h
[See it on godbolt](https://godbolt.org/z/5q4s411bq)
Notes: none
> chore: correct extra qualification causing build error with GCC

- patches/chromium/.patches
- #38067 renamed a patch and didn't delete the old name from the .patches file. 
Notes: none
> build: fixup patches

- spec/extensions-spec.ts
Address TODO by refactoring test to serve the content over http.
Notes: none
> test: re-enable extensions test with http server

- shell/app/electron_main_delegate.cc
- shell/common/api/electron_bindings.cc
- shell/common/gin_helper/callback.cc
- shell/common/gin_helper/locker.cc
- shell/common/gin_helper/locker.h
- shell/common/gin_helper/microtasks_scope.cc
- shell/common/gin_helper/promise.cc
- shell/common/gin_helper/promise.h
- shell/common/gin_helper/trackable_object.cc
- shell/common/node_bindings.cc
- shell/common/process_util.cc
- shell/common/process_util.h
- spec/api-utility-process-spec.ts
- spec/fixtures/api/utility-process/eval.js
Backport of #38014
Notes: Fix crash when executing eval in the utility process.
> fix: crash in utilityProcess when generating code from strings

- lib/browser/api/web-contents.ts
- shell/browser/web_contents_preferences.cc
- spec/api-browser-window-spec.ts
- spec/guest-window-manager-spec.ts
- spec/lib/screen-helpers.ts
Backport of #36914.
Notes: Fixed an issue where default background color for windows might be incorrect
> fix: falsy transparent shouldn't affect webContents background

- spec/api-web-contents-view-spec.ts
- spec/extensions-spec.ts
Backport of #38166.
Notes: none
> test: use `await` to call "closeWindow"

- docs/api/session.md
- docs/tutorial/devices.md
Backport of https://github.com/electron/electron/pull/38188
Notes: none
> docs: fix typing of `session.setDevicePermissionHandler`

- shell/browser/api/electron_api_web_contents.cc
- shell/browser/native_window.cc
- shell/browser/native_window.h
- shell/browser/native_window_mac.mm
- shell/browser/ui/cocoa/electron_ns_window_delegate.mm
> refactor: use standard naming for enum class values

- docs/api/session.md
- docs/tutorial/devices.md
Backport of #38188.
Notes: none
> docs: fix typing of session.setDevicePermissionHandler

- script/spec-runner.js
- spec/package.json
Backport of #38287.
Notes: none
> test: prewarm Node headers cache if specifying Electron version

- .circleci/config/base.yml
Should fix the tar issues we're seeing with python and goma.
Notes: none
> build: bump brew cache to v6

- spec/ts-smoke/electron/main.ts
Follow up to #38231. Smoke tests could use some expanding and general TLC, for future tasks.
Notes: none
> chore: add smoke test for `devtools-open-url`

- docs/api/session.md
> docs: update example to use app.whenReady()

- docs/api/dialog.md
- spec/api-dialog-spec.ts
- spec/ts-smoke/electron/main.ts
Backport of #38336.
Notes: none
> docs: fix typing of message box type value

- shell/browser/api/electron_api_session.cc
- shell/browser/bluetooth/electron_bluetooth_delegate.cc
- shell/browser/hid/hid_chooser_controller.cc
- shell/browser/serial/serial_chooser_controller.cc
- shell/browser/usb/usb_chooser_controller.cc
> chore: eliminate a few uses of base::AdaptCallbackForRepeating()

- docs/tutorial/electron-timelines.md
This PR updates the timelines for Electron 26 and continues support for Electron 22.
Notes: none
> docs: update timelines for E26

- buildflags/BUILD.gn
- buildflags/buildflags.gni
- shell/common/api/features.cc
- spec/chromium-spec.ts
- typings/internal-ambient.d.ts
> build: remove unused enable_tts build flag

- .github/workflows/branch-created.yml
Follow-up to #38181, this was missed in that original PR.
Notes: none
> ci: set description for release labels

- docs/tutorial/performance.md
Fixes broken link to "Analyze runtime performance" article.
Adds missing item to a list in the beginning.
Notes: none
> docs: fix performance tutorial

- .circleci/config/base.yml
- script/verify-chromedriver.py
> build: drop python2 from CI (#38303)

- .circleci/config/base.yml
- script/verify-chromedriver.py
> build: drop python2 from CI

- docs/api/structures/serial-port.md
The majority of the properties are optional and should be reflected as such in the typing.
Notes: none
> docs: fix SerialPort typing

- shell/app/electron_content_client.cc
- shell/app/electron_main_delegate.cc
- shell/browser/api/electron_api_crash_reporter.cc
- shell/common/node_bindings.cc
- shell/common/process_util.cc
- shell/common/process_util.h
Follow-up to #35949
Notes: none
> refactor: use `process_util.h` helpers

- package.json
- yarn.lock
Backport of #38435.
Backport of #38645.
See those PRs for details.
Notes: none
> build: upgrade @electron/github-app-auth to 2.0.0

- .github/workflows/update_appveyor_image.yml
Label is https://github.com/electron/electron/labels/semver%2Fnone.
Notes: none
> build: fix semver/none label on appveyor update PR

- script/release/release.js
Try to minimize the window in which a release can fail but still be listed in https://releases.electronjs.org/releases.json
Notes: none
> build: move uploadIndexJson to just before publishRelease

- .circleci/config/base.yml
Didn't push this commit up with the M1 PR 🙃 
Notes: none
> build: actually use m1.large for publish job

- script/lint.js
- script/nan-spec-runner.js
- script/node-spec-runner.js
- script/push-patch.js
- script/release/notes/index.js
- script/release/version-bumper.js
> chore: change remaining usages of `process.mainModule`

- package.json
- spec/api-web-contents-spec.ts
- yarn.lock
Fixes some formatting issues in the ts-generator
Notes: none
> build: update typescript-generator and docs-parser

- default_app/.eslintrc.json
- default_app/default_app.ts
- default_app/main.ts
Follow-up to #38487
Notes: none
> refactor: use node scheme imports in default_app

- shell/browser/api/electron_api_web_contents.cc
- shell/browser/api/electron_api_web_contents.h
Backport of #38695.
Notes: none
> refactor: api web contents ownership

- docs/api/structures/browser-window-options.md
Closes #34499
Made changes in docs regarding the type property of the BrowserWindow that lacked explanation. Therefore added the required explanation and maintained consistency.
Notes: none
> docs: Improved the Documentation on BrowserWindow type attribute

- docs/fiddles/native-ui/notifications/basic-notification/index.html
- docs/fiddles/windows/manage-windows/create-frameless-window/index.html
> docs: updated the markup tag i with the em

- shell/browser/native_window_mac.mm
Closes https://github.com/electron/electron/issues/39033.
Fixes an issue where `BrowserWindow.moveAbove()` and `BrowserWindow.moveTop()` did not work for child windows. This was happening owing to an AppKit issue where  `-[NSWindow orderWindow]` doesn't handle reordering for children windows. Their order is fixed to the attachment order, where the last attached window is on the top.
Fix this by re-parenting in the correct order when necessary.
Notes: Fixes an issue where `BrowserWindow.moveAbove()` and `BrowserWindow.moveTop()` did not work for child windows on macOS.
> fix: `BrowserWindow.moveAbove()` not working for child windows

- shell/browser/browser_process_impl.cc
- shell/browser/browser_process_impl.h
- shell/browser/electron_browser_main_parts.cc
- spec/chromium-spec.ts
Backport of #38491.
Notes: Fixed an issue where `navigator.connection` returned incorrect data.
> fix: `navigator.connection` not working as intended

- shell/browser/ui/file_dialog_mac.mm
Backport of #38557.
Notes: Fixed an issue where files could in some circumstances be selection when `openFile` was not passed as a dialog property.
> fix: file selection when disallowed on macOS

- .devcontainer/devcontainer.json
As in title.
<details><summary>Issue Screenshot</summary>
<p>
</p>
</details> 
Notes: none
> build: correct codespaces devcontainer extensions settings

- docs/api/safe-storage.md
- shell/browser/api/electron_api_safe_storage.cc
- shell/browser/browser_process_impl.cc
- shell/browser/browser_process_impl.h
- shell/browser/electron_browser_main_parts.cc
- shell/browser/net/system_network_context_manager.cc
- spec/api-safe-storage-spec.ts
- spec/fixtures/api/safe-storage/decrypt-app/main.js
- spec/fixtures/api/safe-storage/encrypt-app/main.js
Refs https://github.com/electron/electron/pull/39107#issuecomment-1637386936
Notes: none
> chore: revert 459fe0e from 26-x-y

- .github/workflows/branch-created.yml
After [the latest project templates update](https://github.blog/changelog/2023-07-20-github-issues-projects-july-20th-update/#%F0%9F%8E%A8-project-template-updates) this is no longer necessary.
Notes: none
> ci: don't set column for draft issues on new project board

- docs/development/creating-api.md
Updating to match the current code:
https://github.com/electron/electron/blob/3a5e2dd90c099b10679364642a0f7fa398dce875/typings/internal-ambient.d.ts#L202
Notes: none
> docs: update binding linking example in creating API doc

- docs/tutorial/electron-timelines.md
> docs: fill in Node.js version for v25 release

- docs/tutorial/asar-integrity.md
- docs/tutorial/fuses.md
Ensures the code examples work out of the box and pulls them closer to the usage example on [`electron/fuses`](https://github.com/electron/fuses).
Notes: none
> docs: update @electron/fuses code examples

- docs/api/window-open.md
Backport of https://github.com/electron/electron/pull/39162
Notes: None
> docs: update window-open.md to include target

- spec/api-app-spec.ts
- spec/api-auto-updater-spec.ts
- spec/api-crash-reporter-spec.ts
- spec/api-debugger-spec.ts
- spec/api-net-log-spec.ts
- spec/api-process-spec.ts
- spec/api-protocol-spec.ts
- spec/api-web-contents-spec.ts
- spec/fixtures/api/default-menu/main.js
- spec/fixtures/module/echo-renamed.js
- spec/webview-spec.ts
Identified by https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-optional-catch-binding.md
Notes: none
> refactor: use optional catch binding

- docs/api/desktop-capturer.md
- docs/api/native-image.md
- docs/api/session.md
- docs/api/web-contents.md
- docs/api/webview-tag.md
- spec/api-session-spec.ts
- spec/ts-smoke/electron/main.ts
> docs: fix some string union type

- lib/browser/api/web-contents.ts
- lib/common/deprecate.ts
- spec/api-app-spec.ts
Identified by https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-useless-promise-resolve-reject.md
Notes: none
> refactor: throw errors directly in async functions

- lib/browser/init.ts
- lib/browser/parse-features-string.ts
- script/nan-spec-runner.js
Identified by https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-set-has.md
Notes: none
> refactor: use Set instead of Array when appropriate

- docs/api/web-contents.md
- docs/api/webview-tag.md
Correcting a small typo in the description here. Thank you @albu77 for pointing it out in https://github.com/electron/website/issues/304. 🙇 
Notes: none
> docs: fix description of pageRanges

- lib/browser/api/dialog.ts
- spec/api-desktop-capturer-spec.ts
- spec/api-subframe-spec.ts
- spec/lib/video-helpers.js
- spec/ts-smoke/electron/renderer.ts
Identified by https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-for-loop.md
Notes: none
> refactor: use `for-of` instead of `for` simple array iteration

- appveyor-woa.yml
- appveyor.yml
Backport of #39362
Notes: none
> ci: fix hang when validating AppVeyor artifacts (#39362)

- appveyor-woa.yml
- appveyor.yml
Backport of #39362
Notes: none
> ci: fix hang when validating AppVeyor artifacts

- lib/renderer/api/ipc-renderer.ts
Follow-up to #39091. `warnOnce` creates a function which then needs to be called.
Notes: none
> chore: fix ipcRenderer.sendTo deprecation warning

- docs/fiddles/media/screenshot/take-screenshot/main.js
- docs/fiddles/media/screenshot/take-screenshot/renderer.js
It has been broken since #30720
Notes: none
> docs: fix take-screenshot fiddle to use desktopCapturer in main.js

- docs/fiddles/system/system-app-user-information/app-information/main.js
- docs/fiddles/system/system-app-user-information/app-information/renderer.js
- docs/fiddles/windows/manage-windows/new-window/index.html
- docs/fiddles/windows/manage-windows/new-window/main.js
- docs/fiddles/windows/manage-windows/new-window/renderer.js
Follow-up to #39379. Also fix completely broken `docs/fiddles/system/system-app-user-information/app-information`
Notes: none
> docs: handle opening links in the default browser in main.js (part #2)

- spec/api-session-spec.ts
- spec/api-system-preferences-spec.ts
- spec/api-web-contents-spec.ts
Swapping these out for usages of `as const` ensures the values are strongly typed.
Notes: none
> test: use as const to remove some usages of as any

- .github/workflows/branch-created.yml
- .github/workflows/issue-labeled.yml
- .github/workflows/issue-unlabeled.yml
- .github/workflows/pull-request-labeled.yml
Fixing a mistake here in the CLI usage which causes an error: https://github.com/electron/electron/actions/runs/5869553380/job/15914768741
Notes: none
> ci: fix @electron/github-app-auth CLI usage

- .github/workflows/branch-created.yml
There's a few spots where this would be useful to have.
Notes: none
> ci: add prev-major variable to release board templating

- appveyor-woa.yml
- appveyor.yml
- script/start-goma.ps1
Backport of #39650
Notes: none
> ci: explicitly use python3 to start goma

- .github/workflows/pull-request-labeled.yml
There's an upstream issue which prevents this action from working with pull requests, so I forked and fixed. [Upstreaming PR here](https://github.com/github/update-project-action/pull/135). Switching to my fork for now as the upstream project hasn't had a release in over a year, so not sure it'll land and be released any time soon.
Notes: none
> ci: fix deprecation review automation for PRs

- .github/workflows/stale.yml
Let's strike a balance here and not annoy reporters by making them constantly bump an issue.
Notes: none
> ci: don't mark status/confirmed labeled issues as stale

- spec/chromium-spec.ts
> refactor: generate 'chrome:// pages' specs to remove duplicate code

- spec/api-browser-view-spec.ts
- spec/api-browser-window-spec.ts
- spec/api-menu-spec.ts
- spec/api-protocol-spec.ts
- spec/api-tray-spec.ts
- spec/api-web-contents-spec.ts
- spec/api-web-request-spec.ts
- spec/chromium-spec.ts
- spec/guest-window-manager-spec.ts
- spec/lib/spec-helpers.ts
Also use the `listen` helper everywhere, which now supports `http2.Http2SecureServer`
Notes: none
> test: convert a few more specs to async/await

- spec/api-browser-window-spec.ts
- spec/api-debugger-spec.ts
- spec/api-ipc-spec.ts
- spec/api-web-contents-spec.ts
- spec/chromium-spec.ts
- typings/internal-ambient.d.ts
- typings/internal-electron.d.ts
> test: remove a few casts to any

- .circleci/config/base.yml
Backport of #39742
Notes: none.
> build: fix depot_tools patch application

- spec/api-content-tracing-spec.ts
Backport of #39682
Notes: none
> test: fix flaky content tracing test

- shell/common/gin_helper/locker.h
Regressed in #39803
Notes: none
> fix: prevent `gin_helper::Locker` heap allocation

- .github/workflows/issue-commented.yml
This slipped through accidentally and is causing workflow failures.
Fixes #39882.
Notes: none
> ci: fix issue-commented workflow sytnax

- docs/api/ipc-renderer.md
- spec/ts-smoke/electron/main.ts
- spec/ts-smoke/electron/renderer.ts
- yarn.lock
Use https://github.com/electron/typescript-definitions/pull/241
Notes: none
> docs: add missing `ipcRenderer.off()` / `ipcRenderer.addListener()` aliases

- .circleci/config/base.yml
https://chromium-review.googlesource.com/c/chromium/tools/depot_tools/+/4869108 fixed our use of autoninja, but it introduced an error verifying goma, so this PR will fix that issue.
- Main will get this change via #39774
- 26-x-y will get this change via #39887
Notes: none
> build: fixup autoninja

- docs/api/cookies.md
> docs: add a more detailed explanation to cookies.flushStore()

- patches/node/test_formally_mark_some_tests_as_flaky.patch
> chore: fixup node flakes

- .circleci/config/base.yml
#39881 indavertenly broke Linux builds for forks; this PR should fix them.
Notes: none
> ci: fix linux builds of forks

- spec/api-browser-window-spec.ts
- spec/is-valid-window/.gitignore
- spec/is-valid-window/README.md
- spec/is-valid-window/binding.gyp
- spec/is-valid-window/lib/is-valid-window.js
- spec/is-valid-window/package.json
- spec/is-valid-window/src/impl.h
- spec/is-valid-window/src/impl_darwin.mm
- spec/is-valid-window/src/impl_posix.cc
- spec/is-valid-window/src/impl_win.cc
- spec/is-valid-window/src/main.cc
- spec/package.json
- spec/yarn.lock
Vendors the code from [`electron/node-is-valid-window`](https://github.com/electron/node-is-valid-window) so that we can better maintain it going forward and that repo can be archived. That repo hasn't had a commit in coming up on 5 years, and there's no CI or defined release process. Since the package is only used by the core repo tests (AFAICT), it seems cleanest to pull it in here.
Open to suggestions on a better spot to drop it in to.
Notes: none
> test: vendor node-is-valid-window

- script/release/uploaders/upload-to-github.ts
Release builds are timing out uploading to GitHub, so this PR adds logging to try to isolate the problem.
Notes: none
> build: log uploads to GitHub

- shell/browser/electron_browser_context.h
> chore: add missing include for std::variant

- docs/api/system-preferences.md
- shell/browser/api/electron_api_system_preferences.cc
- shell/browser/api/electron_api_system_preferences.h
- shell/browser/api/electron_api_system_preferences_mac.mm
backport of #39631 
See that pr for details.
Notes: none
> feat: expose app accessibility transparency settings api

- spec/ts-smoke/electron/main.ts
This was removed in #39631 where it caused a transient failure of the lint job.
Notes: none
> test: add back smoke test for removed API

- docs/api/session.md
Handful of typo fixes.
(https://github.com/electron/clerk/blob/main/README.md#examples).
Notes: none
> docs: fix typo in session docs

- shell/browser/api/electron_api_base_window.cc
- shell/browser/api/electron_api_browser_view.cc
- shell/browser/api/electron_api_content_tracing.cc
- shell/browser/api/electron_api_session.cc
- shell/browser/api/electron_api_web_contents.cc
- shell/browser/bluetooth/electron_bluetooth_delegate.cc
- shell/browser/hid/hid_chooser_context.cc
- shell/browser/native_window.cc
- shell/browser/native_window_views.cc
- shell/browser/serial/serial_chooser_context.cc
- shell/browser/ui/file_dialog_gtk.cc
- shell/browser/ui/file_dialog_mac.mm
- shell/browser/ui/file_dialog_win.cc
- shell/browser/usb/usb_chooser_context.cc
- shell/common/api/electron_api_clipboard.cc
- shell/common/api/electron_api_shell.cc
- shell/renderer/api/electron_api_context_bridge.cc
Addressing a few left-overs from the original PR #39547
Notes: none
> refactor: use gin_helper::Dictionary::CreateEmpty() helper

- docs/api/app.md
- docs/api/web-contents.md
- docs/api/web-frame.md
- spec/ts-smoke/electron/main.ts
Backport of #40180.
Notes: none
> docs: fix some string union typings

- docs/fiddles/features/represented-file/main.js
Fixes #38406 
Also tweaks it to match our latest best practices.
Notes: none
> docs: fix represented file fiddle

- lib/browser/api/web-contents.ts
- shell/browser/api/electron_api_web_contents.cc
- spec/ts-smoke/electron/main.ts
> refactor: options parsing in WebContents.prototype.printToPDF()

- spec/api-utility-process-spec.ts
Follow-up to #40281
Notes: none
> test: add spec for `app.getAppMetrics()` for utility process

- .circleci/config/base.yml
> build: upload slow, more time good

- BUILD.gn
- chromium_src/BUILD.gn
> build: fix ":electron_lib_arc" / "chromium_src:chrome_lib_arc" dependencies

- docs/api/utility-process.md
> docs: add reference to `app.getAppMetrics()` in `serviceName` for `utilityProcess`

- script/release/uploaders/upload.py
> build: actually show github upload output if verbose is true.

- docs/tutorial/electron-timelines.md
As in title. Follow-up from summit.
Notes: none
> docs: document our Node.js versioning policy

- docs/api/app.md
- docs/fiddles/system/protocol-handler/launch-app-from-URL-in-another-app/index.html
- docs/tutorial/asar-integrity.md
- docs/tutorial/boilerplates-and-clis.md
- docs/tutorial/code-signing.md
- docs/tutorial/dark-mode.md
- docs/tutorial/launch-app-from-url-in-another-app.md
- docs/tutorial/snapcraft.md
- docs/tutorial/tutorial-5-packaging.md
- docs/tutorial/using-native-node-modules.md
- docs/tutorial/windows-store-guide.md
The package and repo have been renamed so update these references.
Notes: none
> docs: update references to Electron Packager

- docs/api/structures/user-default-types.md
- lib/browser/api/browser-window.ts
- shell/browser/api/electron_api_app.cc
- shell/browser/api/electron_api_desktop_capturer.cc
- shell/browser/browser_observer.h
- shell/browser/electron_download_manager_delegate.cc
- shell/browser/microtasks_runner.cc
- shell/browser/net/system_network_context_manager.cc
- shell/browser/ui/win/notify_icon_host.cc
- shell/browser/usb/usb_chooser_controller.cc
- shell/browser/zoom_level_delegate.cc
- shell/common/api/BUILD.gn
- shell/common/gin_helper/event_emitter.h
- shell/common/node_bindings.cc
- shell/renderer/api/electron_api_context_bridge.cc
- shell/services/node/node_service.cc
Fixing typos - they're all in comments or docs so there is no functional impact from this change.
Notes: none
> chore: fix some typos

- tsconfig.json
Upstreaming of https://github.com/discord/electron/commit/bf63336f6065e6654f4c315cab2b3c7921145173
> build: specify explicit typeroots for ts builds

- script/lint.js
Backport of #40571
Notes: none
> chore: allow passing more roots to lint.js

- patches/chromium/revert_same_party_cookie_attribute_removal.patch
Fix FTBFS when applying patches in 28-x-y.
CC @electron/wg-upgrades 
Notes: none
> fix: 28-x-y patches

- .github/workflows/pull-request-labeled.yml
Tweak needed so it works with forks. This is safe because the content from the fork is not used (perms updated to ensure this).
Notes: none
> ci: use pull_request_target for PR labeled workflows

- spec/node-spec.ts
Follow-up to https://github.com/electron/electron/pull/40650#issuecomment-1835987539
> chore: cleanup global reject handler leaking into tests

- docs/tutorial/electron-timelines.md
@georgexu99 @dsanders11 @VerteDinde 
Notes: none
> docs: fix year typos in electron-timelines.md

- .github/workflows/branch-created.yml
Forgot these so this part of the automation didn't work (no biggie).
Notes: none
> ci: fix missing inputs for release project board automation

- .circleci/config/base.yml
Doesn't speed up things, but it does make it slow in the worst case.  So remove it
Notes: none
> build: remove CI cache of git cache

- patches/reclient-configs/fix_add_python_remote_wrapper.patch
python wrapper needs the x bit too
Notes: none
> build: fix windows remote exec of python actions

- spec/api-crash-reporter-spec.ts
- spec/api-utility-process-spec.ts
> chore: cleanup tests creating crashpad handler in the test runner process

- .github/ISSUE_TEMPLATE/config.yml
Let's add some links to [the issue template chooser](https://github.com/electron/electron/issues/new/choose) like other open source projects do to help direct folks to other useful links.
cc @electron/wg-outreach 
Notes: none
> chore: add extra links to issue template chooser

- lib/node/init.ts
Follow-up to #41080 and #41118
Notes: none
> refactor: type-safe imports in lib/node/init.ts

- shell/browser/api/electron_api_notification.cc
- shell/browser/api/electron_api_notification.h
- shell/browser/electron_browser_context.cc
- shell/browser/electron_browser_context.h
- shell/browser/extensions/api/tabs/tabs_api.cc
- shell/browser/native_window_views.cc
- shell/browser/net/network_context_service.cc
- shell/browser/osr/osr_render_widget_host_view.cc
- shell/browser/osr/osr_render_widget_host_view.h
- shell/browser/osr/osr_video_consumer.cc
- shell/browser/osr/osr_view_proxy.cc
- shell/browser/osr/osr_view_proxy.h
- shell/browser/osr/osr_web_contents_view.cc
- shell/browser/ui/views/root_view.cc
- shell/browser/ui/views/root_view.h
- shell/browser/web_contents_zoom_controller.cc
- shell/browser/web_contents_zoom_controller.h
Manually backport #41125. See that PR for details.
Notes: none.
> refactor: inline simple getters

- docs/tutorial/security.md
This adds a new item to the security checklist to review the fuses values. IT also adds item number 18 to the ToC up top.
Notes: none
> docs: add note about fuses to our security documentation

- lib/browser/init.ts
- lib/common/init.ts
- lib/node/asar-fs-wrapper.ts
- lib/sandboxed_renderer/init.ts
> refactor: type-safe module imports / requires

- shell/browser/api/electron_api_app.cc
- shell/browser/api/electron_api_safe_storage.cc
- shell/browser/api/electron_api_web_contents.cc
- shell/browser/api/electron_api_web_contents.h
- shell/browser/api/electron_api_web_contents_mac.mm
- shell/browser/browser.cc
- shell/browser/browser.h
- shell/browser/browser_process_impl.cc
- shell/browser/browser_process_impl.h
- shell/browser/native_window.cc
- shell/browser/native_window.h
- shell/browser/native_window_mac.mm
- shell/browser/ui/autofill_popup.cc
- shell/browser/ui/autofill_popup.h
- shell/browser/ui/cocoa/electron_inspectable_web_contents_view.mm
- shell/browser/ui/cocoa/electron_menu_controller.mm
- shell/browser/ui/cocoa/electron_ns_window_delegate.mm
- shell/browser/ui/electron_menu_model.cc
- shell/browser/ui/electron_menu_model.h
- shell/browser/ui/inspectable_web_contents.cc
- shell/browser/ui/inspectable_web_contents.h
- shell/browser/ui/views/autofill_popup_view.cc
- shell/browser/ui/views/inspectable_web_contents_view_views.cc
Manually backport #41254 to 29-x-y.
Notes: none
> refactor: inline simple getters, pt . 2 (#41254)

- docs/tutorial/electron-timelines.md
Updates our Release Schedule for the future Electron 30 release.
I also took the opportunity to update the Node.js version of Electron 29, which we are releasing soon.
Notes: none
> docs: update release schedule for E30

- shell/renderer/electron_render_frame_observer.cc
- spec/api-browser-window-spec.ts
- spec/lib/screen-helpers.ts
- spec/package.json
- spec/yarn.lock
Manual backport of #41377
Notes: Fixed an issue where the -webkit-app-region: drag property was not respected on some windows.
> fix: check for draggable regions outside of main frame

- shell/browser/api/electron_api_app.cc
- shell/browser/api/electron_api_safe_storage.cc
- shell/browser/api/electron_api_web_contents.cc
- shell/browser/api/electron_api_web_contents.h
- shell/browser/api/electron_api_web_contents_mac.mm
- shell/browser/browser.cc
- shell/browser/browser.h
- shell/browser/browser_process_impl.cc
- shell/browser/browser_process_impl.h
- shell/browser/native_window.cc
- shell/browser/native_window.h
- shell/browser/native_window_mac.mm
- shell/browser/ui/autofill_popup.cc
- shell/browser/ui/autofill_popup.h
- shell/browser/ui/cocoa/electron_inspectable_web_contents_view.mm
- shell/browser/ui/cocoa/electron_menu_controller.mm
- shell/browser/ui/cocoa/electron_ns_window_delegate.mm
- shell/browser/ui/electron_menu_model.cc
- shell/browser/ui/electron_menu_model.h
- shell/browser/ui/inspectable_web_contents.cc
- shell/browser/ui/inspectable_web_contents.h
- shell/browser/ui/views/autofill_popup_view.cc
- shell/browser/ui/views/inspectable_web_contents_view_views.cc
Manually backport #41254 to 27-x-y.
Notes: none
> refactor: inline simple getters, pt . 2 

- patches/node/src_preload_function_for_environment.patch
- shell/app/node_main.cc
- shell/common/node_bindings.cc
Backport of https://github.com/electron/electron/pull/41500
Notes: none
> chore: update src_preload_function_for_environment.patch

- .devcontainer/devcontainer.json
> chore: remove 8088 from codespaces port forwarding

- yarn.lock
Picks up a fix for false positives when checking for broken external links.
Notes: none
> build: update @electron/lint-roller to 1.11.1

- shell/browser/api/electron_api_app.cc
- spec/api-app-spec.ts
Adds some basic JumpList-related specs as I noticed none existed.
Notes: none
> test: add test for `setJumpList` arguments

- .circleci/config/base.yml
- spec/api-media-handler-spec.ts
- spec/api-web-contents-spec.ts
Backport of #41649
Notes: none
> ci: use CircleCI hosted macOS arm64 runners for testing

- docs/api/app.md
- docs/api/auto-updater.md
- docs/api/browser-window.md
- docs/api/client-request.md
- docs/api/crash-reporter.md
- docs/api/ipc-main.md
- docs/api/protocol.md
- docs/api/push-notifications.md
- docs/api/session.md
- docs/api/structures/file-path-with-headers.md
- docs/api/structures/notification-response.md
- docs/api/structures/protocol-request.md
- docs/api/structures/protocol-response.md
- docs/api/structures/trace-config.md
- docs/api/system-preferences.md
- docs/api/web-contents.md
- docs/api/web-request.md
- docs/api/webview-tag.md
- docs/breaking-changes.md
Backport of #41575
notes: none
> docs: backslash escape parametrized TypeScript types

- .github/workflows/issue-opened.yml
> build: fix potential source of errors in issue workflow

- .markdownlint.json
- docs/api/base-window.md
- docs/api/client-request.md
- docs/tutorial/tutorial-2-first-app.md
- package.json
- yarn.lock
Backport of #41753.
Notes: none
> build: add Markdown lint check for unescaped angle brackets

- docs/api/session.md
- spec/chromium-spec.ts
Backport of #41698.
Notes: none
> test: add tests for Storage Access API

- docs/development/build-instructions-gn.md
update the build docs, support the Windows command line and PowerShell
Notes: Updated windows build docs
> docs: update build docs,support Powershell on Windows

- yarn.lock
> build: update typescript-definitions to 8.15.6

- shell/app/electron_content_client.cc
- shell/browser/electron_browser_client.cc
- shell/renderer/renderer_client_base.cc
Backport of #41990
Notes: none
> chore: fixup gn check when enable_pdf_viewer is false

- patches/chromium/.patches
- patches/chromium/bindings_refactor_domdatastore.patch
- patches/chromium/merge_fix_domarraybuffer_isdetached_and_comment_out_a_check.patch
* 1b454576028b from chromium
* 0d9350b71fd0 from chromium
Notes:
* Security: backported fix for CVE-2024-3914.
> chore: cherry-pick 1 changes from 0-M124

- docs/api/base-window.md
- docs/api/browser-window.md
- docs/api/net.md
- docs/api/session.md
- docs/api/web-contents.md
- docs/development/debugging-with-symbol-server.md
- docs/tutorial/esm.md
- docs/tutorial/tutorial-1-prerequisites.md
- docs/tutorial/tutorial-2-first-app.md
Backport of https://github.com/electron/electron/pull/42052
Notes: none
> docs: update formatting for mdx3 compatibility

- docs/api/protocol.md
Closes #42102.
The current example at the top of the file doesn't handle the edge case where a filename has a `#`, update it to match the pattern used in later examples. The second modified example was using `path.join` which wouldn't work well with absolute paths so update that as well.
Notes: none
> docs: improve protocol.handle file examples

- shell/common/asar/archive.cc
- spec/api-autoupdater-darwin-spec.ts
- spec/asar-integrity-spec.ts
- spec/fixtures/apps/hello/hello.js
- spec/lib/codesign-helpers.ts
- spec/lib/fs-helpers.ts
- spec/node-spec.ts
- spec/package.json
- spec/yarn.lock
> test: add tests for electron fuses

- docs/development/build-instructions-gn.md
Resolves (in part) <https://github.com/electron/build-tools/issues/587>. Provides troubleshooting advice for RBE auth returning a 'token not valid' error. I kept running into this issue on my Windows 11 install and it turned out I had to manually resync my system time even though it automatically resynced 4 days before (thanks @dsanders11 for the advice).
Notes: Added troubleshooting advice for rbe auth 'token not valid' error to docs.
> docs: troubleshooting advice for rbe auth 'token not valid' error

- .circleci/config/base.yml
- .github/workflows/config/gclient.diff
Refs https://chromium-review.googlesource.com/c/chromium/tools/depot_tools/+/5598577
Notes: none
> build: fix `depot_tools` patch

- .github/workflows/macos-build.yml
- .github/workflows/macos-pipeline.yml
- script/actions/move-artifacts.sh
- Make tar less verbose
- Clean up `CHECK_DIST_MANIFEST` logic
- Remove non-macOS bash logic
Notes: none
> build: cleanup to macos pipeline

- .github/workflows/linux-pipeline.yml
- .github/workflows/linux-publish.yml
- script/release/ci-release-build.js
This PR adds the needed steps to complete Linux's publish job.
Notes: none
> build: add needed steps/tweaks to Linux publish job

- script/generate-deps-hash.js
This was noisy, probably spare debugging from me
Notes: none
> build: generate deps hash quietly

- .github/workflows/linux-pipeline.yml
- script/actions/move-artifacts.sh
- script/actions/restore-artifacts.sh
> build: add Linux GHA test step

- .github/workflows/linux-pipeline.yml
- .github/workflows/macos-pipeline.yml
- script/actions/move-artifacts.sh
- script/actions/restore-artifacts.sh
- script/nan-spec-runner.js
- script/node-disabled-tests.json
This PR:
- Adds chromedriver verification
- Adds mksnapshot verifications
- Adds Node.js tests
- Adds Nan tests
- Fixes xarch snapshot logic
Notes: none
> build: add several missing test steps for GHA

- .github/actions/build-electron/action.yml
- .github/workflows/pipeline-segment-electron-test.yml
- .github/workflows/pipeline-segment-node-nan-test.yml
- script/actions/move-artifacts.sh
- script/actions/restore-artifacts.sh
Split out src dir artifacts from generated artifacts.
Notes: none
> build: upload separate artifact for src files

- .github/workflows/build.yml
- .github/workflows/linux-publish.yml
- .github/workflows/macos-publish.yml
- .github/workflows/pipeline-segment-node-nan-test.yml
> build: pin and dedupe build image sha

- script/release/ci-release-build.js
- script/release/prepare-release.js
This is safer and more correct
Notes: none
> build: run gha on tag not branch

- .github/actions/build-electron/action.yml
Correctly escape the " characters
Notes: none
> build: fix v8 toolchain for macOS x64

- .github/workflows/pipeline-segment-electron-build.yml
> build: only load SDK for mac builds

- .github/workflows/build.yml
- .github/workflows/pipeline-electron-lint.yml
> build: add lint GHA job

- .github/workflows/build.yml
- .github/workflows/pipeline-electron-build-and-test-and-nan.yml
- .github/workflows/pipeline-electron-build-and-test.yml
- .github/workflows/pipeline-segment-electron-build.yml
- .github/workflows/pipeline-segment-electron-test.yml
- .github/workflows/pipeline-segment-node-nan-test.yml
- script/actions/run-tests.sh
- script/node-disabled-tests.json
- script/split-tests.js
* Use `--privileged` for test runner so sandbox works
* Enable arm / arm64 tests (#42493)
* Use `runuser` so we aren't running the tests as root
* Fix the mac_sdk_path issue on linux
Notes: none
> build: fix linux tests

- .github/workflows/pipeline-segment-electron-test.yml
> build: fix dubious ownership error in version bumper spec

- .github/workflows/build.yml
- .github/workflows/pipeline-electron-build-and-test.yml
- .github/workflows/pipeline-segment-electron-build.yml
- .github/workflows/pipeline-segment-electron-gn-check.yml
- .github/workflows/pipeline-segment-node-nan-test.yml
- script/generate-deps-hash.js
Adds gn check step.
https://github.com/electron/electron/actions/runs/9521745927
Notes: none
> build: add GN check step

- .github/actions/install-build-tools/action.yml
- .github/workflows/pipeline-segment-electron-build.yml
- .github/workflows/pipeline-segment-electron-gn-check.yml
- .github/workflows/pipeline-segment-node-nan-test.yml
Having this SHA everywhere was annoying, let's dedupe
Notes: none
> build: de-dupe load build tools into composite action

- .github/workflows/pipeline-electron-build-and-test-and-nan.yml
- .github/workflows/pipeline-electron-build-and-test.yml
- .github/workflows/pipeline-segment-electron-gn-check.yml
Runs GN Check tests everywhere.
Notes: none
> build: run GN Check everywhere

- .github/workflows/pipeline-segment-node-nan-test.yml
> build: fix nan/node tests on GHA

- .github/workflows/linux-publish.yml
This PR modifies the GCLIENT_EXTRA_ARGS in linux-publish to be correct, so the cache is consistent between checkout and build.
Notes: none
> build: correct GCLIENT_EXTRA_ARGS in linux-publish

- patches/DirectXShaderCompiler/.patches
- patches/DirectXShaderCompiler/cherry-pick-33051b084850.patch
- patches/DirectXShaderCompiler/cherry-pick-b845fed99111.patch
- patches/config.json
- patches/dawn/.patches
- patches/dawn/dawn_dxc_disable_dxc_pass_structurize-loop-exits-for-unroll.patch
* 33051b084850 from DirectXShaderCompiler
* b845fed99111 from DirectXShaderCompiler
* 9c6534f82db3 from dawn
Notes:
* Security: backported fix for CVE-2024-5831.
* Security: backported fix for CVE-2024-5832.
> chore: [30-x-y] cherry-pick 3 changes from 0-M126

- .github/actions/restore-cache-azcopy/action.yml
- .github/workflows/build.yml
It's Time. This PR turns on GitHub Actions, by default, for all branches and pull requests.
Notes: none
> build: turn on GitHub Actions by default for all branches and pull requests

- .github/actions/build-electron/action.yml
- .github/workflows/pipeline-segment-electron-build.yml
- script/lib/azput.js
- script/release/ci-release-build.js
- script/release/find-github-release.js
- script/release/prepare-release.js
- script/release/publish-to-npm.js
- script/release/release.js
- script/release/uploaders/upload-to-github.ts
This PR removes CircleCI from the release pipeline, and alters the release scripts to remove the test repo (test-releases) where we were sending test release assets
Notes: none
> build: remove CircleCI from release pipeline

- script/release/uploaders/upload-index-json.py
Cleans up error logging and handling a little bit so it's easier to see in logs.
<p>
```
electron on git:main ❯ python3 script/release/uploaders/upload-index-json.py v33.0.0-nightly.20240625
Traceback (most recent call last):
File "/Users/codebytere/Developer/electron-gn/src/electron/script/release/uploaders/upload-index-json.py", line 35, in get_content
with urlopen(request) as resp:
File "/Users/codebytere/.electron_build_tools/third_party/Xcode/Xcode-15.0.0.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 214, in urlopen
return opener.open(url, data, timeout)
File "/Users/codebytere/.electron_build_tools/third_party/Xcode/Xcode-15.0.0.app/Contents/Developer/Library/Frameworks/Python3.framew …
```
> build: clean up upload-index-json error handling

- .circleci/config/jobs/lint.yml
- script/lib/util.py
- script/run-clang-format.py
- script/run-gn-format.py
Manual backport of #42715
Notes: none
> build: fix clang format/lint

- .github/actions/build-electron/action.yml
- .github/actions/checkout/action.yml
- .github/actions/fix-sync-macos/action.yml
- .github/actions/free-space-macos/action.yml
- .github/actions/install-build-tools/action.yml
- .github/actions/restore-cache-aks/action.yml
- .github/actions/restore-cache-azcopy/action.yml
- .github/workflows/build.yml
- .github/workflows/config/gclient.diff
- .github/workflows/linux-publish.yml
- .github/workflows/macos-publish.yml
- .github/workflows/pipeline-electron-build-and-test-and-nan.yml
- .github/workflows/pipeline-electron-build-and-test.yml
- .github/workflows/pipeline-electron-docs-only.yml
- .github/workflows/pipeline-electron-lint.yml
- .github/workflows/pipeline-segment-electron-build.yml
- .github/workflows/pipeline-segment-electron-gn-check.yml
- .github/workflows/pipeline-segment-electron-test.yml
- .github/workflows/pipeline-segment-node-nan-test.yml
- script/actions/move-artifacts.sh
- script/actions/restore-artifacts.sh
- script/actions/run-tests.sh
- script/release/ci-release-build.js
- script/split-tests.js
- spec/api-app-spec.ts
- spec/api-protocol-spec.ts
This PR migrates 32-x-y to use GitHub Actions, backporting existing changes in main
Notes: none
> build: migrate to GitHub Actions

- .circleci/config/base.yml
Manual backport of #42718
Notes: none
> build: remove MacOS x64 from CircleCI

- docs/api/net.md
Changes heading level for net.resolveHost() entry to H3
Notes: just updating the documentation, thanks!
> docs - Update net.md

- docs/tutorial/updates.md
Ref https://github.com/electron/electron/issues/29943
notes: none
> docs(autoUpdater): document static storage strategy

- .circleci/config.yml
- .circleci/config/base.yml
Follow-up to #42763 - currently CircleCI workflows aren't running as a result of that change.
Notes: none
> ci: fix CircleCI config

- script/release/prepare-release.js
Fixes publish by passing in a new, needed variable to the ci-release-build script
Notes: none
> build: fix release, add newVersion for tagging

- .circleci/config.yml
- .circleci/config/base.yml
Backport of #42763.
Notes: none
> build: remove all publish & build on macOS

- script/nan-spec-runner.js
Backport of #42863.
Notes: none
> ci: fix Nan test failure on Linux

- .github/actions/install-build-tools/action.yml
This pulls in https://github.com/electron/build-tools/pull/618, which is needed for the GHA migration
Notes: none
> build: update build-tools for GHA

- .github/workflows/build.yml
- .github/workflows/linux-publish.yml
- .github/workflows/macos-publish.yml
- .github/workflows/pipeline-electron-docs-only.yml
- .github/workflows/pipeline-electron-lint.yml
- .github/workflows/pipeline-segment-node-nan-test.yml
Use new runners with dind sidecar and better naming
Notes: none
> build: use new arc runner names

- .github/actions/install-build-tools/action.yml
- .github/actions/restore-cache-azcopy/action.yml
- .github/workflows/pipeline-segment-electron-build.yml
- .github/workflows/pipeline-segment-electron-gn-check.yml
- Fixes using reclient credential helper from fork PRS on GitHub Actions
- Fixes source cache restore from fork PRS on GitHub Actions
Notes: none
> build: fixup GHA running on fork PRs

- shell/browser/file_system_access/file_system_access_permission_context.cc
- shell/browser/file_system_access/file_system_access_permission_context.h
Closes https://github.com/electron/electron/issues/42352.
Enables File System Access API to remember last picked directory for the duration of a given session. Upstream uses a `HostContentSettingsMap` to do this, which is a `ProfileKeyedService` bringing with it a fair amount of complexity I don't believe we need. I therefore took a simpler approach of storing relevant data in a `std::map`, while maintaining the general eviction and memory logic upstream does.
Notes: Fixed an issue where the File System Access API did not remember the user's last picked directory as expected.
> fix: File System Access API should remember last picked directory

- shell/browser/hid/hid_chooser_context.cc
Refs https://chromium-review.googlesource.com/c/chromium/src/+/4966528
1. `it` was erased inside the cycle that was iterating over `devices`.
Since `devices` is equal to `it->second`, the condition of the for cycle
was addressing the destroyed memory, which is a potential security
issue.
2. Since `if (device_it == devices_.end())` clause didn't increase
`guid` iterator, it would cause an infinite loop if it was ever hit.
Notes: none
> fix: iteration issues in hid `RevokeEphemeralDevicePermission`

- .github/workflows/issue-opened.yml
Automatically detect that the issue was opened for an unsupported major (when the "Electron Version" value is well-formed) and comment with a request they try a newer version. Also labels the issue appropriately with https://github.com/electron/electron/labels/blocked%2Fneed-info%20%E2%9D%8C so we can come back to it when it's unblocked.
Notes: none
> ci: auto comment on new issues for unsupported majors

- shell/browser/web_contents_permission_helper.cc
Closes https://github.com/electron/electron/issues/42714
Closes https://github.com/electron/electron/issues/29861
Fixes an issue where `navigator.mediaDevices.getUserMedia` and `navigator.getUserMedia` should reject with a `NotAllowedError` if microphone or camera permissions have been denied at the system level. Prior to this, it would appear to work but fail to actually capture sound or play a stream as macOS permissions took precedence.
Notes: Fixes an issue where `navigator.mediaDevices.getUserMedia` and `navigator.getUserMedia` should reject with a `NotAllowedError` if microphone or camera permissions have been denied at the system level on macOS.
> fix: `getUserMedia` needs macOS system permissions check

- package.json
- yarn.lock
Bumping to the latest version of `@electron/lint-roller` which includes initial support for linting API history in the docs. Prep work for future PRs which will start adding the API history.
Notes: none
> build: update @electron/lint-roller to 2.3.0

- docs/api/desktop-capturer.md
Closes https://github.com/electron/electron/issues/42605.
Updates desktopCapturer example to reflect our current recommendations - this wasn't updated after we added support for `navigator.mediaDevices.requestDisplayMedia` via https://github.com/electron/electron/issues/30702
Notes: none
> docs: improve desktop capture example

- patches/DirectXShaderCompiler/.patches
- patches/DirectXShaderCompiler/cherry-pick-9463ce9cd8d9.patch
- patches/chromium/.patches
- patches/chromium/cherry-pick-44b7fbf35b10.patch
- patches/dawn/.patches
- patches/dawn/reland_deps_update_dxc_to_patched_branch.patch
* 44b7fbf35b10 from chromium
* c9815acd5a88 from dawn
* 9463ce9cd8d9 from DirectXShaderCompiler
Notes:
* Security: backported fix for CVE-2024-6989.
* Security: backported fix for CVE-2024-6991.
> chore: cherry-pick 3 changes from 0-M127

- .github/workflows/issue-opened.yml
What it says on the tin.
Notes: none
> ci: auto label bug issues with platform

- patches/chromium/fix_potential_draggable_region_crash_when_no_mainframeimpl.patch
Updates a patch that is in conflict
Notes: none.
> build: fixup patches in main

- .github/dependabot.yml
Save us a tiny bit of work with needing to label these PRs.
Notes: none
> ci: set labels on Dependabot PRs for GitHub Actions deps

- docs/tutorial/fuses.md
These are rendering all on one line currently which is visually confusing. Additional newline gets it rendering as separate lines which seems to be the original intent.
Notes: none
> docs: fix formatting in fuses tutorial

- shell/common/platform_util_mac.mm
Closes https://github.com/electron/electron/issues/43126.
Do not merge until https://github.com/electron/electron/pull/43087 has merged!
Migrates deprecated macOS APIs after Chromium upgrade to macOS 11*
Notes: none
> refactor: migrate deprecated `platform_util_mac` calls

- .github/workflows/build.yml
- .github/workflows/pipeline-electron-build-and-test-and-nan.yml
- .github/workflows/pipeline-electron-build-and-test.yml
Backport of #43187.
Notes: none
> build: use smaller instances for gn-check

- shell/browser/api/electron_api_auto_updater.cc
- shell/common/api/electron_bindings.cc
- shell/common/gin_helper/callback.h
- shell/common/gin_helper/event_emitter_caller.cc
- shell/common/gin_helper/function_template.h
- shell/common/gin_helper/microtasks_scope.h
- shell/common/gin_helper/promise.cc
- shell/common/gin_helper/promise.h
- shell/common/node_bindings.cc
- shell/common/v8_value_serializer.cc
- shell/renderer/api/electron_api_spell_check_client.cc
- shell/renderer/electron_sandboxed_renderer_client.cc
Backport of https://github.com/electron/electron/pull/43185
Notes: none
> fix: `gin_helper::MicrotasksScope` instantiation

- patches/v8/.patches
- patches/v8/spill_all_loop_inputs_before_entering_loop.patch
Refs https://chromium-review.googlesource.com/c/v8/v8/+/5797073
Notes: none
> chore: cherry-pick 9797576 from v8

- docs/tutorial/window-customization.md
This PR slightly updates the window customization tutorial, now that Windows Control Overlay is supported on Linux.
Notes: none
> docs: update window customization tutorial

- .github/CODEOWNERS
Ensures the WG gets automatically tagged for review on these files.
Notes: none
> chore: set wg-infra as CODEOWNER for GHA build configs

- script/sysroots.json
As in title. Update following https://github.com/electron/debian-sysroot-image-creator/pull/33
Notes: none
> build: roll sysroots

- .github/config.yml
We've recently enable commit signature verification on this repo, so let's remind first-time contributors to sign their commits.
Notes: none
> chore: mention signed commit requirement

- shell/browser/api/electron_api_debugger.cc
- shell/browser/electron_download_manager_delegate.cc
- shell/browser/net/asar/asar_url_loader.cc
- shell/browser/net/url_pipe_loader.h
- shell/browser/serial/serial_chooser_context.cc
- shell/browser/ui/inspectable_web_contents.cc
- shell/browser/usb/usb_chooser_context.cc
- shell/common/api/electron_api_url_loader.h
- shell/common/gin_helper/arguments.cc
- shell/common/process_util.cc
These got a little out of whack in #43012, so getting them back in proper order.
Notes: none
> chore: cleanup include groupings

- .github/workflows/pipeline-segment-electron-build.yml
- .github/workflows/pipeline-segment-electron-gn-check.yml
Backport of #43533
Notes: none
> build: free up macos disk space as soon as possible

- .github/workflows/issue-commented.yml
Improves an oversight where issues labeled https://github.com/electron/electron/labels/blocked%2Fneed-info%20%E2%9D%8C aren't being updated on user comment.
Notes: none
> ci: remove blocked/need-info label on user comment

- BUILD.gn
- shell/browser/api/electron_api_web_contents.cc
- shell/browser/api/electron_api_web_contents.h
- shell/browser/electron_pdf_document_helper_client.cc
- shell/browser/electron_pdf_document_helper_client.h
Backport of #43436.
Notes: none
> test: add -pdf-ready-to-print event to WebContents for testing

- shell/browser/javascript_environment.cc
Backport of #43356.
Notes: none.
> chore: remove unused ConvertableToTraceFormatWrapper

- .github/actions/checkout/action.yml
- .github/workflows/build.yml
Backport of #43139.
Notes: none
> build: fix patchup logic only running on one platform

- docs/api/view.md
Document the edge case where `View.removeChildView()` is called with a view that is not a child.
[:link: Link to the relevant code](https://github.com/electron/electron/blob/0cc60500ed949e1082909328daa10b71a681a58f/shell/browser/api/electron_api_view.cc#L256)
Notes: none
> docs: document View.removeChildView edge case

- .github/actions/generate-types/action.yml
- .github/workflows/archaeologist-dig.yml
- docs/api/structures/base-window-options.md
- This PR in conjunction with https://github.com/electron/archaeologist/pull/44 will allow us to migrate from Archaeologist from CircleCI to GitHub Actions.  Additionally, this will allow us to support re-runs of Archaeologist by re-running the new Archaeologist Dig action which also provides the artifacts diff, eg see: https://github.com/electron/electron/actions/runs/10888035620?pr=43701
Successful archaeologist run here: https://github.com/electron/electron/pull/43701/checks?check_run_id=30211644858
Notes: none
> ci: move Archaeologist to GHA

- BUILD.gn
- build/config/BUILD.gn
- patches/chromium/build_do_not_depend_on_packed_resource_integrity.patch
- patches/chromium/disable_compositor_recycling.patch
- patches/chromium/feat_add_support_for_missing_dialog_features_to_shell_dialogs.patch
- patches/chromium/feat_enable_offscreen_rendering_with_viz_compositor.patch
- patches/chromium/feat_ensure_mas_builds_of_the_same_application_can_use_safestorage.patch
- patches/chromium/mas_avoid_private_macos_api_usage.patch.patch
- patches/chromium/osr_shared_texture_remove_keyed_mutex_on_win_dxgi.patch
- patches/chromium/printing.patch
- script/generate-mas-config.py
- shell/app/electron_main_delegate.cc
- shell/app/electron_main_mac.cc
- shell/app/node_main.cc
- shell/browser/api/electron_api_app.cc
- shell/browser/api/electron_api_app.h
- shell/browser/api/electron_api_crash_reporter.cc
- shell/browser/api/electron_api_web_contents.cc
- shell/browser/api/process_metric.cc
- shell/browser/auto_updater.cc
- shell/browser/browser_mac.mm
- shell/browser/notifications/mac/notification_center_delegate.mm
- shell/browser/ui/cocoa/electron_ns_window.mm
- shell/browser/ui/file_dialog_mac.mm
- shell/common/api/electron_bindings.cc
- shell/common/node_bindings.cc
- shell/common/platform_util_mac.mm
- shell/renderer/api/electron_api_crash_reporter_renderer.cc
This makes the MAS build way faster, and should make it work for release builds too 🥳 
Notes: none
> build: make is_mas_build a generated header instead of config

- shell/browser/api/electron_api_debugger.cc
- shell/browser/api/electron_api_download_item.cc
- shell/browser/api/electron_api_net_log.cc
- shell/browser/api/electron_api_protocol.cc
- shell/browser/api/electron_api_service_worker_context.cc
- shell/browser/api/electron_api_session.cc
- shell/browser/api/electron_api_web_contents.cc
- shell/browser/hid/hid_chooser_controller.cc
- shell/browser/native_window_mac.mm
- shell/browser/usb/usb_chooser_context.cc
- shell/browser/usb/usb_chooser_controller.cc
- shell/common/crash_keys.cc
- shell/common/node_bindings_mac.cc
- shell/common/node_util.cc
- shell/common/node_util.h
- shell/common/process_util.cc
- shell/common/process_util.h
- shell/common/skia_util.cc
Manual backport of https://github.com/electron/electron/pull/43722. to 33-x-y. See that PR for details.
Notes: none.
> refactor: add `EmitWarning(v8::Isolate*)` helper

- script/release/get-asset.js
- script/release/get-url-hash.js
- script/release/release.js
Logs... We need logs...
Notes: none
> build: improve logging on http errors during release process

- script/release/get-asset.js
- script/release/release.js
> build: improve logging on http errors during release process (again)

- script/release/get-asset.js
- script/release/get-url-hash.js
- script/release/release.js
Backport of three separate PRs (first two were kinda dodge)
Notes: none
> build: improve logging on http errors during release process 

- .github/workflows/pipeline-segment-electron-build.yml
Fixes the macOS release
---
Notes: none
> build: let darwin/mas run concurrently

- .github/dependabot.yml
> build: update-check-skip on dependabot backport PRs

- docs/api/auto-updater.md
- docs/tutorial/updates.md
Closes #43181
@electron/docs 
Notes: none
> docs: add advanced specification for Squirrel updater

- appveyor-woa.yml
- appveyor.yml
- script/setup-win-for-dev.bat
Manually backport #43897 to 33-x-y. See that PR for details.
Not sure why trop couldn't do this one; cherry-pick wfm without any manual changes :man_shrugging: 
Notes: none
> build: use Node 20 in Appveyor images (33-x-y)

- script/release/bin/README.md
- script/release/bin/cleanup-release.ts
- script/release/bin/prepare-for-release.ts
- script/release/bin/print-next-version.ts
- script/release/bin/publish-to-github.ts
- script/release/bin/publish-to-npm.ts
- script/release/bin/run-release-builds.ts
- script/release/bin/validate-before-publish.ts
- script/release/get-asset.ts
- script/release/notes/index.ts
- script/release/notes/notes.ts
- script/release/prepare-release.ts
- script/release/release-artifact-cleanup.ts
- script/release/release.ts
- script/release/run-release-ci-jobs.ts
- script/release/types.ts
- script/release/uploaders/upload-to-github.ts
Backport of #44058.
Notes: none
> build: cleanup release scripts, separate cli entrypoints from logic

- script/release/bin/publish-to-npm.ts
> build: fix relative file read during npm publish

- .github/workflows/pipeline-segment-electron-test.yml
- appveyor-woa.yml
- appveyor.yml
This PR adds Datadog logging for our tests so that we can track flaky tests.
Notes: none
> ci: add datadog test logging

- build/args/all.gn
Node PR: https://github.com/nodejs/node/pull/55306
Do not merge before attached Node PR is merged. This PR updates our NMV to 132 for Electron 34
Please merge this PR before branching 34-x-y
Notes: none
> build: update NMV to 132

- script/release/prepare-release.ts
We haven't used bump commits since Oct 2022 so `changesToRelease` always returns `true`. Sudowoodo will check if there's anything to release.
Notes: none
> build: remove dead code in prepare release script

- patches/chromium/printing.patch
This PR updates the printing patch after the latest Chrome roll
Notes: none
> build: fix main printing patch conflict

- .github/actions/install-build-tools/action.yml
- .github/workflows/pipeline-segment-electron-build.yml
- .github/workflows/pipeline-segment-electron-gn-check.yml
- appveyor-woa.yml
- appveyor.yml
Backport of #44280
Notes: none
> chore: fixup reclient read only access on forks

- docs/api/utility-process.md
Refs https://github.com/electron/electron/issues/44338.
Clarifies `child.pid` value of `utilityProcess`.
Notes: none
> docs: clarify utilityProcess child.pid value

- spec/api-session-spec.ts
- #44380 accidentally got merged with failing tests - this PR fixes those tests.
Notes: none
> test: fixup broken tests in 32-x-y

- .github/workflows/build.yml
- .github/workflows/linux-publish.yml
- .github/workflows/macos-publish.yml
This pulls in the latest from https://github.com/electron/build-images/pull/39
Notes: none
> build: update linux container

- docs/api/base-window.md
Closes https://github.com/electron/electron/issues/44410.
Notes: none.
> docs: fix `win.getContentView(`) return type

- package.json
- yarn.lock
I doubt this package has been in use in a long time, so let's go ahead and jettison it, especially since it's confusingly named with our lint scripts.
Notes: none
> build: remove unused lint package

- .github/workflows/build.yml
Backport of #44432
Notes: none
> build: add new status to verify if all the required gha jobs have run

- spec/api-session-spec.ts
- #44389 fixed some flaky tests in 32-x-y, mainly by migrating away from synchronous mocha functions to async ones.  It turns out that those flakes are present in newer versions as well, eg https://github.com/electron/electron/actions/runs/11645084310/job/32437831508?pr=44534, so we should apply the same fixes to newer versions.
- 
Notes: none
> test: fixup flaky session tests

- docs/api/session.md
Relevant code: https://github.com/electron/electron/blob/48801be8e9e3b898635e55abb0b596c83bb9c17a/shell/browser/electron_browser_context.cc#L332-L335
Notes: none
> docs: clarify that sessions use cache by default

- lib/browser/api/browser-window.ts
- lib/browser/api/web-contents.ts
- patches/chromium/.patches
- patches/chromium/refactor_unfilter_unresponsive_events.patch
- shell/browser/api/electron_api_browser_window.cc
- shell/browser/api/electron_api_browser_window.h
- shell/browser/api/electron_api_web_contents.cc
Manual backport of #44629
Notes: none
> refactor: unfilter unresponsive events

- shell/common/extensions/api/_api_features.json
- shell/common/extensions/api/_manifest_features.json
- shell/common/extensions/api/_permission_features.json
Copied all non-private and non-chromeOS manifest and permission features from
- https://source.chromium.org/chromium/chromium/src/+/main:chrome/common/extensions/api/_permission_features.json;drc=5691b7c58c31b1dd4e50056b2456050e6f92be86
- https://source.chromium.org/chromium/chromium/src/+/main:chrome/common/extensions/api/_manifest_features.json;drc=5691b7c58c31b1dd4e50056b2456050e6f92be86
This will satisfy a [DCHECK when loading extensions](https://source.chromium.org/chromium/chromium/src/+/main:extensions/common/manifest_handlers/permissions_parser.cc;l=244-246;drc=c835ee197ea7448a3648187c8cd576bee9657d27) without a known permission. This also suppresses warnings when loading extensions.
Notes: none
> chore: update extensions features

- spec/api-debugger-spec.ts
Breaking out a potential flaky test fix from https://github.com/electron/electron/pull/44665
Notes: none
> test: run script to help target discovery and reduce flakes

- docs/tutorial/electron-timelines.md
> docs: correct stable release dates for v34.0.0

- docs/api/session.md
Relevant code section: https://github.com/electron/electron/blob/9f1e23c405847c2773231347b7604731741b0034/shell/browser/api/electron_api_session.cc#L169-L170
Notes: none
> docs: clarify what session.clearData() with data type 'cache' deletes

- docs/api/app.md
Fix grammar in `app.relaunch` docs
Notes: none
> docs: fix grammar in `app.relaunch` docs

- docs/fiddles/features/web-bluetooth/index.html
fix:remove extra "
Notes: none
> docs: remove extra "

- .github/actions/checkout/action.yml
- .github/actions/install-dependencies/action.yml
- .github/actions/restore-cache-azcopy/action.yml
Small QOL update - bumps actions/cache up to remove deprecation warnings
Notes: none
> build: bump actions/cache past deprecated version

- docs/why-electron.md
As discussed in wg-outreach and wg-ecosystem, this document summarizes the points I make when companies approach me to discuss whether or not they should use Electron. We're open source, nobody here makes any money when another app is built with Electron, _but_ we decided that it's important for us to communicate the "Why?" behind some of our core choices.
> docs: Why Electron?

- docs/why-electron.md
Backport of https://github.com/electron/electron/pull/45191
notes: none
> docs: Why Electron? (#45191)

- shell/browser/file_system_access/file_system_access_permission_context.cc
When consuming a callback that lives in `callback_map_`, remove it from the map to prevent dangling references. Fixes a 0e5fe3f issue.
Notes: none
> fix: consume the file permission callback when used

- patches/chromium/add_didinstallconditionalfeatures.patch
- patches/chromium/build_do_not_depend_on_packed_resource_integrity.patch
- patches/chromium/can_create_window.patch
- patches/chromium/cherry-pick-1282289030ab.patch
- patches/chromium/cherry-pick-3dc17c461b12.patch
- patches/chromium/chore_partial_revert_of.patch
- patches/chromium/chore_provide_iswebcontentscreationoverridden_with_full_params.patch
- patches/chromium/disable_unload_metrics.patch
- patches/chromium/expose_setuseragent_on_networkcontext.patch
- patches/chromium/fix_on-screen-keyboard_hides_on_input_blur_in_webview.patch
- patches/chromium/fix_software_compositing_infinite_loop.patch
- patches/chromium/network_service_allow_remote_certificate_verification_logic.patch
- patches/chromium/notification_provenance.patch
- patches/chromium/partially_revert_is_newly_created_to_allow_for_browser_initiated.patch
- patches/chromium/printing.patch
- patches/chromium/refactor_expose_cursor_changes_to_the_webcontentsobserver.patch
- patches/chromium/refactor_unfilter_unresponsive_events.patch
- patches/chromium/support_mixed_sandbox_with_zygote.patch
- patches/chromium/web_contents.patch
- patches/chromium/webview_fullscreen.patch
Backport of #45218.
Notes: Fixed an issue where print scaling could be too small during silent print.
> fix: page scaling in silent mode printing

- docs/tutorial/native-file-drag-drop.md
Fixes #45326
Copies the working code from the example fiddle into the docs.
Notes: none
> docs: fix broken code in drag and drop example

- .github/workflows/windows-publish.yml
Follow up to #45137, mild clean up on the Windows actions workflow names & images
Notes: none
> build: use windows builders for win-publish

- patches/chromium/.patches
- patches/chromium/cherry-pick-35f86d6a0a03.patch
- patches/chromium/feat_add_signals_when_embedder_cleanup_callbacks_run_for.patch
- patches/chromium/ignore_parse_errors_for_pkey_appusermodel_toastactivatorclsid.patch
- patches/skia/ganesh_avoid_overflow_when_combining_aahairlineops.patch
- patches/v8/cherry-pick-3c2d220ad025.patch
- shell/browser/api/electron_api_notification.cc
- shell/browser/api/electron_api_notification.h
- shell/browser/api/electron_api_session.cc
- shell/browser/api/electron_api_session.h
- shell/browser/api/electron_api_tray.cc
- shell/browser/api/electron_api_tray.h
- shell/browser/api/electron_api_web_contents.cc
- shell/browser/api/electron_api_web_contents.h
- shell/browser/api/message_port.cc
- shell/browser/api/message_port.h
- shell/browser/javascript_environment.cc
- shell/common/api/electron_api_url_loader.cc
- shell/common/api/electron_api_url_loader.h
- shell/common/gin_helper/cleaned_up_at_exit.cc
- shell/common/gin_helper/cleaned_up_at_exit.h
- shell/common/gin_helper/wrappable.cc
Manual backport of #45368
Notes: Fixed crash in gin::wrappable::secondweakcallback
> fix: crash in gin::wrappable::secondweakcallback

- shell/common/extensions/api/pdf_viewer_private.idl
Refs https://chromium-review.googlesource.com/c/chromium/src/+/6160067.
Notes: none
> chore: update `pdf_viewer_private.idl`

- shell/browser/extensions/api/scripting/scripting_api.cc
- shell/browser/extensions/api/scripting/scripting_api.h
Refs:
- https://chromium-review.googlesource.com/c/chromium/src/+/6123601
- https://chromium-review.googlesource.com/c/chromium/src/+/6142377
- https://chromium-review.googlesource.com/c/chromium/src/+/6173554
Notes: none
> chore: update `chrome.scripting.execute` logic

- .github/actions/build-electron/action.yml
- script/lib/config.py
This PR handles the building and uploading of the Windows toolchain for release builds
Notes: none
> build: add win toolchain for release builds

- docs/why-electron.md
> fix: fix typo in docs why-electron.md

- docs/api/structures/base-window-options.md
- docs/api/structures/display.md
Added missing space and fixed code field
I accidentally deleted the repo (#45432)
Notes: none
> docs: style fixes

- docs/tutorial/security.md
Use the correct headings level in tutorial/security.md.
Notes: none
> docs: use correct headings in tutorial/security.md

- shell/browser/native_window_mac.mm
- shell/browser/ui/cocoa/electron_ns_window.h
- shell/browser/ui/cocoa/electron_ns_window.mm
Manual backport of #45427
Notes: none
> fix: Update widget visibility in `NativeWindowMac::ShowInactive`

- DEPS
- patches/chromium/blink_local_frame.patch
- patches/chromium/build_do_not_depend_on_packed_resource_integrity.patch
- patches/chromium/can_create_window.patch
- patches/chromium/cherry-pick-dd8e2822e507.patch
- patches/chromium/chore_partial_revert_of.patch
- patches/chromium/chore_provide_iswebcontentscreationoverridden_with_full_params.patch
- patches/chromium/desktop_media_list.patch
- patches/chromium/disable_hidden.patch
- patches/chromium/feat_separate_content_settings_callback_for_sync_and_async_clipboard.patch
- patches/chromium/fix_on-screen-keyboard_hides_on_input_blur_in_webview.patch
- patches/chromium/fix_restore_original_resize_performance_on_macos.patch
- patches/chromium/fix_return_v8_value_from_localframe_requestexecutescript.patch
- patches/chromium/gritsettings_resource_ids.patch
- patches/chromium/mas_avoid_private_macos_api_usage.patch.patch
- patches/chromium/notification_provenance.patch
- patches/chromium/partially_revert_is_newly_created_to_allow_for_browser_initiated.patch
- patches/chromium/refactor_expose_cursor_changes_to_the_webcontentsobserver.patch
- patches/chromium/refactor_unfilter_unresponsive_events.patch
- patches/chromium/support_mixed_sandbox_with_zygote.patch
- patches/chromium/web_contents.patch
- patches/chromium/webview_fullscreen.patch
Updating Chromium to 135.0.6989.0.
See [all changes in 134.0.6988.0..135.0.6989.0](https://chromium.googlesource.com/chromium/src/+log/134.0.6988.0..135.0.6989.0?n=10000&pretty=fuller)
Notes: Updated Chromium to 135.0.6989.0.
> chore: bump chromium 134.0.6989.0

- DEPS
- patches/chromium/add_electron_deps_to_license_credits_file.patch
- patches/chromium/build_do_not_depend_on_packed_resource_integrity.patch
- patches/chromium/can_create_window.patch
- patches/chromium/cherry-pick-dd8e2822e507.patch
- patches/chromium/chore_introduce_blocking_api_for_electron.patch
- patches/chromium/chore_partial_revert_of.patch
- patches/chromium/chore_provide_iswebcontentscreationoverridden_with_full_params.patch
- patches/chromium/disable_hidden.patch
- patches/chromium/feat_add_support_for_missing_dialog_features_to_shell_dialogs.patch
- patches/chromium/fix_crash_loading_non-standard_schemes_in_iframes.patch
- patches/chromium/fix_on-screen-keyboard_hides_on_input_blur_in_webview.patch
- patches/chromium/fix_restore_original_resize_performance_on_macos.patch
- patches/chromium/frame_host_manager.patch
- patches/chromium/gritsettings_resource_ids.patch
- patches/chromium/mas_avoid_private_macos_api_usage.patch.patch
- patches/chromium/partially_revert_is_newly_created_to_allow_for_browser_initiated.patch
- patches/chromium/printing.patch
- patches/chromium/refactor_expose_cursor_changes_to_the_webcontentsobserver.patch
- patches/chromium/refactor_unfilter_unresponsive_events.patch
- patches/chromium/resource_file_conflict.patch
- patches/chromium/web_contents.patch
- patches/chromium/webview_fullscreen.patch
Updating Chromium to 134.0.6990.0.
See [all changes in 134.0.6989.0..134.0.6990.0](https://chromium.googlesource.com/chromium/src/+log/134.0.6989.0..134.0.6990.0?n=10000&pretty=fuller)
Notes: Updated Chromium to 134.0.6990.0.
> chore: bump chromium 134.0.6990.0

- docs/tutorial/tutorial-3-preload.md
Fixed grammar in the preload tutorial summary.
Notes: none
> docs: fix grammar in preload tutorial summary

- DEPS
- patches/chromium/mas_avoid_private_macos_api_usage.patch.patch
- shell/browser/api/electron_api_cookies.cc
- shell/browser/browser_process_impl.h
- shell/browser/electron_pdf_document_helper_client.h
- shell/browser/extensions/electron_extension_loader.cc
- shell/browser/native_window_views.cc
- shell/browser/native_window_views.h
- shell/browser/osr/osr_video_consumer.cc
- shell/browser/ui/message_box_win.cc
- shell/browser/ui/win/notify_icon.cc
- shell/browser/ui/win/notify_icon.h
- shell/browser/ui/win/taskbar_host.cc
- shell/common/api/electron_api_native_image.cc
- shell/common/api/electron_api_native_image.h
- shell/common/api/electron_api_native_image_win.cc
- spec/api-content-tracing-spec.ts
Updating Chromium to 134.0.6998.10.
See [all changes in 134.0.6990.0..134.0.6998.10](https://chromium.googlesource.com/chromium/src/+log/134.0.6990.0..134.0.6998.10?n=10000&pretty=fuller)
NB: This is the last 134 release.
Notes: Updated Chromium to 134.0.6998.10.
> chore: bump chromium to 134.0.6998.10 (main)

- shell/browser/api/electron_api_menu.cc
- shell/browser/api/electron_api_utility_process.cc
- shell/browser/api/electron_api_web_frame_main.cc
- shell/browser/extensions/electron_extension_system.cc
- shell/browser/printing/printing_utils.cc
- shell/common/gin_converters/blink_converter.cc
- shell/common/platform_util.cc
- shell/common/skia_util.cc
- shell/renderer/api/electron_api_context_bridge.cc
Manual backport of #44843. See that PR for details.
Notes: none.
> fix: misc-use-internal-linkage warnings (32-x-y)

- CONTRIBUTING.md
Added a missing period in a specific part of the text to maintain consistency across the document. This ensures a uniform writing style, improves readability, and aligns with the formatting used throughout the content.
Notes: none
> docs: added missing period for consistency and readability

- shell/browser/api/electron_api_web_contents.cc
- shell/browser/api/electron_api_web_frame_main.cc
- shell/browser/api/electron_api_web_frame_main.h
- shell/common/gin_converters/std_converter.h
- spec/api-web-frame-main-spec.ts
- typings/internal-electron.d.ts
Backport of #45609
Notes: Fixed WebFrameMain crash related to accessing speculative frames that have been destroyed.
> fix: dangling speculative frames

- shell/common/heap_snapshot.cc
Third and last `base::span` PR of the evening.
This is another small cleanup to use the `base::span` helpers instead of using `reinterpret_cast` or `static_cast`.
This time, we're converting the `char*, int  size` provided by v8 into a `base::span<uint8_t>` needed for passing to `WriteAtCurrentPosAndCheck()`.
Notes: none.
> refactor: use `base::as_bytes()` in `WriteAsciiChunk()`

- shell/browser/api/electron_api_base_window.cc
- shell/browser/api/electron_api_global_shortcut.cc
- shell/browser/api/electron_api_power_save_blocker.cc
- shell/browser/api/electron_api_protocol.cc
- shell/browser/api/electron_api_session.cc
- shell/browser/api/electron_api_web_contents.cc
- shell/browser/api/electron_api_web_frame_main.cc
- shell/browser/api/electron_api_web_request.cc
- shell/browser/api/message_port.cc
- shell/browser/electron_autofill_driver_factory.cc
- shell/browser/electron_browser_client.cc
- shell/browser/extensions/api/scripting/scripting_api.cc
- shell/browser/extensions/api/tabs/tabs_api.cc
- shell/browser/extensions/electron_component_extension_resource_manager.cc
- shell/browser/hid/electron_hid_delegate.cc
- shell/browser/hid/hid_chooser_context.cc
- shell/browser/plugins/plugin_utils.cc
- shell/browser/serial/serial_chooser_context.cc
- shell/browser/ui/cocoa/electron_touch_bar.mm
- shell/browser/ui/message_box_gtk.cc
- shell/browser/ui/message_box_mac.mm
- shell/browser/ui/message_box_win.cc
- shell/browser/usb/electron_usb_delegate.cc
- shell/browser/usb/usb_chooser_context.cc
- shell/common/api/electron_api_clipboard.cc
- shell/renderer/api/electron_api_context_bridge.cc
- shell/renderer/api/electron_api_spell_check_client.cc
- shell/renderer/electron_renderer_client.cc
- shell/renderer/electron_sandboxed_renderer_client.cc
Manually backport #45742 to 35-x-y. See that PR for details.
Notes: none.
> refactor: use C++20's contains() method (35-x-y)

- shell/browser/api/electron_api_base_window.cc
- shell/browser/api/electron_api_global_shortcut.cc
- shell/browser/api/electron_api_power_save_blocker.cc
- shell/browser/api/electron_api_protocol.cc
- shell/browser/api/electron_api_session.cc
- shell/browser/api/electron_api_web_contents.cc
- shell/browser/api/electron_api_web_frame_main.cc
- shell/browser/api/electron_api_web_request.cc
- shell/browser/api/message_port.cc
- shell/browser/electron_autofill_driver_factory.cc
- shell/browser/electron_browser_client.cc
- shell/browser/extensions/api/scripting/scripting_api.cc
- shell/browser/extensions/api/tabs/tabs_api.cc
- shell/browser/extensions/electron_component_extension_resource_manager.cc
- shell/browser/hid/electron_hid_delegate.cc
- shell/browser/hid/hid_chooser_context.cc
- shell/browser/plugins/plugin_utils.cc
- shell/browser/serial/serial_chooser_context.cc
- shell/browser/ui/cocoa/electron_touch_bar.mm
- shell/browser/ui/message_box_gtk.cc
- shell/browser/ui/message_box_mac.mm
- shell/browser/ui/message_box_win.cc
- shell/browser/usb/electron_usb_delegate.cc
- shell/browser/usb/usb_chooser_context.cc
- shell/common/api/electron_api_clipboard.cc
- shell/renderer/api/electron_api_context_bridge.cc
- shell/renderer/api/electron_api_spell_check_client.cc
- shell/renderer/electron_renderer_client.cc
- shell/renderer/electron_sandboxed_renderer_client.cc
Manual backport of #45742 to 34-x-y. See that PR for details.
Notes: none.
> refactor: use C++20's contains() method

- shell/browser/api/electron_api_power_monitor.h
- shell/browser/api/electron_api_web_contents.h
- shell/browser/native_window_views.h
- shell/browser/ui/devtools_ui_theme_data_source.cc
- shell/browser/ui/views/submenu_button.cc
- shell/browser/ui/win/electron_desktop_window_tree_host_win.cc
- shell/common/gin_converters/frame_converter.cc
> docs: fix spelling errors in code comments

- build/args/all.gn
Corresponding Node PR: https://github.com/nodejs/node/pull/57151
_NOTE: Needs to be merged before 36-x-y branch is cut_
Notes: none
> build: bump NMV to 135

- DEPS
> chore: bump Chromium 136.0.7058.1

- .github/actions/checkout/action.yml
https://github.com/electron/electron/actions/runs/13865507398/job/38803643930
Notes: none
> build: fix compound bash conditional in patchup

- docs/breaking-changes.md
Use the [proper process event](https://nodejs.org/api/process.html#event-unhandledrejection) in code example.
Notes: none
> docs: fix code example in breaking-changes.md

- shell/browser/api/electron_api_base_window.cc
- shell/browser/api/electron_api_global_shortcut.cc
- shell/browser/api/electron_api_power_save_blocker.cc
- shell/browser/api/electron_api_protocol.cc
- shell/browser/api/electron_api_session.cc
- shell/browser/api/electron_api_web_contents.cc
- shell/browser/api/electron_api_web_frame_main.cc
- shell/browser/api/electron_api_web_request.cc
- shell/browser/api/message_port.cc
- shell/browser/electron_autofill_driver_factory.cc
- shell/browser/electron_browser_client.cc
- shell/browser/extensions/api/scripting/scripting_api.cc
- shell/browser/extensions/api/tabs/tabs_api.cc
- shell/browser/extensions/electron_component_extension_resource_manager.cc
- shell/browser/hid/electron_hid_delegate.cc
- shell/browser/hid/hid_chooser_context.cc
- shell/browser/plugins/plugin_utils.cc
- shell/browser/serial/serial_chooser_context.cc
- shell/browser/ui/cocoa/electron_touch_bar.mm
- shell/browser/ui/message_box_gtk.cc
- shell/browser/ui/message_box_mac.mm
- shell/browser/ui/message_box_win.cc
- shell/browser/usb/electron_usb_delegate.cc
- shell/browser/usb/usb_chooser_context.cc
- shell/common/api/electron_api_clipboard.cc
- shell/renderer/api/electron_api_context_bridge.cc
- shell/renderer/api/electron_api_spell_check_client.cc
- shell/renderer/electron_renderer_client.cc
- shell/renderer/electron_sandboxed_renderer_client.cc
Manually backport #45742 to 33-x-y. See that PR for details.
Notes: none.
> refactor: use C++20's contains() method (33-x-y)

- .github/actions/build-electron/action.yml
- .github/workflows/macos-publish.yml
- .github/workflows/windows-publish.yml
Followup to #45881.  There were a couple changes missed in that PR that are necessary for release builds.
Notes: none
> build: fixup release builds

- .devcontainer/docker-compose.yml
- .github/workflows/build.yml
- .github/workflows/linux-publish.yml
- .github/workflows/macos-publish.yml
- .github/workflows/windows-publish.yml
Refs:
- https://github.com/electron/build-images/pkgs/container/devcontainer/382350682?tag=latest
- https://github.com/electron/build-images/pkgs/container/test/382354921?tag=arm32v7-9f11982e806f439d0a0a8ebbbf566cd5e0d9e952
- https://github.com/electron/build-images/pkgs/container/test/382353733?tag=arm64v8-latest
- https://github.com/electron/build-images/pkgs/container/build/382348549?tag=latest
Notes: none
> build: roll build-images SHAs

- .github/actions/set-chromium-cookie/action.yml
Validate that the Chromium cookie is set as expected. Tested locally.
Notes: none
> build: validate Chromium cookie authentication

- .github/actions/set-chromium-cookie/action.yml
- .github/workflows/linux-publish.yml
- .github/workflows/macos-publish.yml
- .github/workflows/windows-publish.yml
Make it clearer when cookie authentication scripts run and fix missing cookie in publish jobs.
Notes: none
> build: make it clearer when cookie auth runs

- docs/api/tray.md
> docs: updated tray doc with tooltip removing

- .devcontainer/docker-compose.yml
- .github/workflows/build.yml
- .github/workflows/linux-publish.yml
- .github/workflows/macos-publish.yml
- .github/workflows/windows-publish.yml
Refs https://github.com/electron/build-images/pull/47.
Notes: none
> build: roll build-images

- .github/actions/install-build-tools/action.yml
- .github/workflows/pipeline-segment-electron-test.yml
This PR updates build-tools to the latest version, particularly to get https://github.com/electron/build-tools/pull/696 which should resolve issues like https://github.com/electron/electron/actions/runs/14493394971/job/40655348383.
Notes: none
> build: update build tools

- docs/api/app.md
Fixes a hierarchy issue with `app.resolveProxy(url)`.
Notes: none
> docs: use correct heading level for API function

- spec/api-global-shortcut-spec.ts
- spec/api-menu-spec.ts
- spec/lib/accelerator-helpers.ts
Follow-up to https://github.com/electron/electron/pull/44488
Refs https://github.com/electron/electron/pull/44341
Test Menu rendering accelerator combinations.
Notes: none
> test: test menu rendering accelerators

- shell/common/node_util.cc
Changes the DCHECK condition in `ExplicitMicrotasksScope` (added in #46973) to exclude the browser/utility processes from the scoped microtask check and replace it with a check for the assumption that they are always using the explicit microtask policy.
Fixes #47019
Notes: none
> fix: explicit microtask scope DCHECK condition

- shell/common/gin_converters/osr_converter.cc
> fix: prevent gc monitor 2nd pass crash

- .github/actions/checkout/action.yml
- .github/problem-matchers/patch-conflict.json
Adds [a GitHub actions problem matcher](https://github.com/actions/toolkit/blob/main/docs/problem-matchers.md) to add error annotations for patch conflicts to the workflow runs so they're more discoverable.
Notes: none
> ci: add problem matcher for patch conflict output

- .github/actions/install-build-tools/action.yml
Backport of #47194
Notes: none
> build: fix depot tool pathing on Windows (#47194)

- shell/browser/ui/file_dialog_mac.mm
Fixes https://github.com/electron/electron/issues/47248
Regressed with https://github.com/electron/electron/pull/47077
Notes: fix regression with directory selection in macOS dialogs
> fix: regression with directory selection in macOS dialogs

- patches/v8/.patches
- patches/v8/debug_fix_crash_when_pausing_in_for-of_loop_header.patch
- patches/v8/parser_set_start_end_on_materialized_scopes.patch
Backports https://issues.chromium.org/issues/399002824
Refs https://github.com/microsoft/vscode/issues/249927
Notes: Fixed crash when pausing in loops due to missing context when desugared.
> fix: crash due to incorrect debug scope information

- docs/development/pull-requests.md
The electron/electron repository requires signed commits, so we should mention that in our docs.
Notes: none
> docs: document commit signing requirement

- patches/v8/cherry-pick-7bc0a67ebfbf.patch
> chore: run `e patches all`

- build/siso/backend.star
Pairs with https://github.com/electron/build-tools/pull/731
Notes: none
> build: add siso backend.star

- shell/browser/browser_mac.mm
Address outstanding TODO.
Notes: none
> refactor: use non-deprecated macOS API in `RemoveAsDefaultProtocolClient`

- .github/workflows/audit-branch-ci.yml
Fixes #47547 
Only send the Slack message if there's a new failure, not a stale one.
Notes: none
> ci: fix audit workflow alerting on stale results

- docs/development/build-instructions-linux.md
- docs/development/build-instructions-macos.md
- docs/development/build-instructions-windows.md
As in title. See also https://github.com/electron/build-tools/pull/739
Notes: none
> docs: update build prerequisites

- yarn.lock
> build: deep update brace-expansion to resolve an audit alert

- .github/actions/checkout/action.yml
- .github/actions/restore-cache-azcopy/action.yml
This fixes the issue we are seeing on Windows builds: `Dangerous symbolic link path was ignored`
Notes: none
> build: cleanup symlinks in cache

- spec/chromium-spec.ts
Deflake the following failure:
https://github.com/electron/electron/actions/runs/16273281729/job/45949205666?pr=47744
Notes: none
> test: deflake clipboard read/write specs

- spec/ts-smoke/electron/utility.ts
- spec/ts-smoke/tsconfig.json
We were missing any TS smoke test coverage for `electron/utility` so add some.
Notes: none
> test: add TS smoke test for electron/utility

- .github/actions/free-space-macos/action.yml
- .github/workflows/pipeline-segment-electron-test.yml
- spec/chromium-spec.ts
Backport of #47982
Notes: none
> ci: fixup mac runner hang

- build/webpack/webpack.config.base.js
- lib/browser/init.ts
- lib/node/asar-fs-wrapper.ts
- lib/renderer/init.ts
- lib/utility/init.ts
- lib/worker/init.ts
- package.json
- tsconfig.json
- typings/internal-ambient.d.ts
- yarn.lock
Backport of #47798.
Notes: none
> build: drop @types/webpack-env in favor of webpack/module types

- .github/actions/ssh-debug/action.yml
- .github/actions/ssh-debug/setup-ssh.sh
- .github/actions/ssh-debug/ssh-session.sh
- .github/actions/ssh-debug/sshd_config.template
- .github/workflows/build.yml
- .github/workflows/pipeline-electron-build-and-test.yml
- .github/workflows/pipeline-segment-electron-build.yml
- .github/workflows/pipeline-segment-electron-test.yml
Fix an issue where username incorrectly matched to authorized users and also move to dynamic local tunnels.
Notes: none
> build: use quick tunnels for ssh debugging

- shell/browser/osr/osr_render_widget_host_view.cc
Address outstanding TODO now that CL:6250383 has landed.
Notes: none.
> chore: remove upstream OSR temp fix

- build/args/all.gn
Corresponding Node PR: https://github.com/nodejs/node/pull/59627
NOTE: Needs to be merged before 39-x-y branch is cut
Notes: none
> build: bump NMV to 140

- .github/actions/build-electron/action.yml
- .github/actions/cipd-install/action.yml
- .github/actions/fix-sync/action.yml
- .github/actions/install-build-tools/action.yml
- .github/workflows/pipeline-segment-electron-build.yml
- .github/workflows/pipeline-segment-electron-test.yml
- build/siso/backend.star
- build/siso/main.star
- script/actions/move-artifacts.sh
- script/node/generate_original_fs.py
Backport of #47534
Notes: none
> build: use siso instead of reclient (37-x-y)

- spec/yarn.lock
`cookies` & `serialize-javascript`, spec only deps
Notes: none
> build: update spec deps for clean audit

- patches/v8/.patches
- patches/v8/cherry-pick-ec6c18478382.patch
Manual backport of https://github.com/electron/electron/pull/48335
Notes: none
> chore: cherry-pick ec6c18478382 from v8

- .github/actions/build-electron/action.yml
- .github/actions/install-build-tools/action.yml
Backport of #48345
Notes: none
> build: update build tools to get siso for forks fix (#48345)

- .github/workflows/pipeline-segment-electron-test.yml
- package.json
- script/actions/screencapture-nag-remover.sh
- script/spec-runner.js
- spec/lib/screen-helpers.ts
- spec/webview-spec.ts
- yarn.lock
Backport of #48205
Notes: none
> test: rerun failed tests individually

- docs/api/web-utils.md
Resolves https://github.com/electron/electron/issues/45666
Just replaced the example with one in Breaking Changes document as suggested in the issue.
Notes: none
> docs: mention that webUtils should be used via preload script
