electron/electron

- docs/api/web-contents.md
The end is near, this is the (hopefully) last of my PRs for tidying up the markdown in the docs, along with #26665. After these two are merged I hope to make a PR adding `markdownlint` to the linters to keep the docs tidier going forward.
Notes: none
> chore: tidy up docs markdown

- shell/browser/electron_browser_main_parts.cc
This fixes a use-after-free bug which could happen when using OTR sessions (i.e. partitions whose name does not begin with `persist:`). Detected by [asan](https://github.com/electron/electron/pull/23570).
The bug here is that OTR sessions use the default session as their "parent" session:
https://github.com/electron/electron/blob/0be6c92aa91475bdff38c67afedc0ea0a976c8e5/shell/browser/extensions/electron_extensions_browser_client.cc#L112-L120
The child session expects the parent session to still be alive during destruction. This PR ensures that.
Probably unrelatedly to this PR, there is some weird disagreement about what the "parent" session is here: https://github.com/electron/electron/blob/0be6c92aa91475bdff38c67afedc0ea0a976c8e5/shell/browser/extensions/electron_extension_system_factory. …
> fix: use-after-free in ElectronBrowserContext during shutdown

- shell/browser/api/electron_api_web_contents.cc
Fixes #26475.
Introduced in 10a209ecba.
Notes: Fixed a use-after-free error that could occur when destroying a WebContents during the `did-stop-loading` event.
> fix: uaf in WebContents::DidStopLoading

- docs/api/process.md
- shell/renderer/electron_sandboxed_renderer_client.cc
- spec-main/api-browser-window-spec.ts
- spec-main/fixtures/module/preload-sandbox.js
Add [`process.uptime()`](https://nodejs.org/api/process.html#process_process_uptime) to sandboxed renderers.
Notes: Added `process.uptime()` to sandboxed renderers.
> feat: add process.uptime() to sandboxed renderers

- docs/api/shell.md
- lib/common/api/shell.ts
- shell/common/api/electron_api_shell.cc
- shell/common/platform_util.h
- shell/common/platform_util_mac.mm
- shell/common/platform_util_win.cc
- spec-main/api-shell-spec.ts
- spec/ts-smoke/electron/main.ts
[This is already documented as removed in Electron 13](https://github.com/electron/electron/blob/master/docs/breaking-changes.md#removed-shellmoveitemtotrash)
Notes: Removed deprecated `shell.moveItemToTrash()`.
> chore: remove deprecated shell.moveItemToTrash()

- docs/tutorial/offscreen-rendering.md
docs: revised offscreen rendering page
Notes: docs: revised offscreen rendering page
> docs: revised offscreen rendering page

- script/lint.js
This is a better fix for #26014, and has some other benefits.
Count successes instead of expecting error output. Seems that the most common reason the linters get broken is that they aren't actually running what is expected, something silently fails, and silence is considered success. Invert that logic, and start with a fail state, so if nothing runs, it's a failure by default.
When in verbose mode, output names of files linted even if they ran clean. This again makes it easier to tell if a linter is running as intended, or silently failing.
Notes: none
> chore: use ESLint API for linting

- shell/browser/api/electron_api_app.cc
- shell/browser/api/electron_api_app.h
- shell/browser/electron_browser_client.cc
- shell/browser/electron_browser_client.h
There is no need to map the child process ID to PID
> refactor: simplify child process tracking for app.getAppMetrics()

- shell/browser/api/electron_api_browser_window.cc
- shell/browser/api/electron_api_browser_window_mac.mm
- shell/browser/native_browser_view.h
- shell/browser/native_browser_view_mac.h
- shell/browser/native_browser_view_mac.mm
Closes https://github.com/electron/electron/issues/26588.
Fixes a regression introduced in https://github.com/electron/electron/pull/26145. As a part of that PR, I reworked the parameters to `UpdateDraggableRegions` in `NativeBrowserView` such that they took  `const std::vector<mojom::DraggableRegionPtr>& regions` instead of `const std::vector<gfx::Rect>& drag_exclude_rects`. This was necessary in order to enable draggable regions worked on BrowserViews standalone, but introduced a new issue.
This was that `drag_exclude_rects` were then calculated from the passed regions, they would be calculated with the `webViewWidth` and `webViewHeight` _relative to the containing WebContents_. This caused https://github.com/electron/electron/issues/26588. To fix this, we need to ensure that the …
> fix: draggable regions calculation in BrowserWindow/BrowserView

- shell/browser/resources/mac/Info.plist
We've received several reports of our app crashing when loading pages that require Bluetooth on Big Sur. As described in the [corresponding Chrome issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1126246):
> For apps compiled against the macOS 11.0 SDK, TCC will crash
> if the NSBluetoothAlwaysUsageDescription string isn't available
> and Bluetooth APIs are called.
This PR makes the same change as Chrome to Electron's info.plist (following #19871).
I'm not sure if it's actually necessary to include `NSBluetoothPeripheralUsageDescription`; Apple's [documentation](https://developer.apple.com/documentation/bundleresources/information_property_list/nsbluetoothperipheralusagedescription) describes it as being used only on old versions of iOS. However, since Chrome includes it, I …
> fix: Add default Bluetooth permission strings

- shell/browser/native_browser_view_views.cc
- shell/browser/native_browser_view_views.h
- shell/browser/native_window_views.cc
- shell/browser/ui/views/frameless_view.cc
Closes https://github.com/electron/electron/issues/26562.
Prior to this PR draggable views did not work with BrowserViews except on macOS, which was fixed in https://github.com/electron/electron/pull/26145. This fixes that same functionality on Windows.
Tested with https://gist.github.com/7278c8c62ec976110afb47ef2d861a7a.
Notes:  Fixed an issue where draggable regions did not work exclusively on BrowserViews on Windows.
> fix: draggable views on BrowserViews on Windows

- docs/api/environment-variables.md
Adds information about two environment variables that can be enabled for more effective debugging.
cc @MarshallOfSound @zcbenz @jkleinsc 
Notes: none.
> docs: add debugging vars to env var doc

- docs/api/content-tracing.md
According to the API docs, the property is called included_categories, not include_categories.
Notes: none
> docs: fix contentTracing code sample

- shell/browser/native_window_views.cc
- shell/browser/native_window_views_win.cc
- spec-main/api-browser-window-spec.ts
Backport of #26586
Notes: Fixed an issue where IsMaximized would incorrectly return false for some windows on Windows.
> fix: add check in IsMaximized for non-WS_THICKFRAME windows

- lib/asar/fs-wrapper.ts
- spec/asar-spec.js
Backport of #26749.
Notes: Fixed import of unpacked node modules.
> fix: internalModuleReadJSON for unpacked JSON

- docs/breaking-changes.md
> docs: BrowserWindow extension APIs are deprecated in Electron 9

- shell/common/node_bindings.cc
Addresses an outstanding TODO of mine. We should be properly emitting the after() `async_hooks` when an exception has been handled in the renderer process. This is done in Node.js [here](https://github.com/nodejs/node/blob/ddff2b2b22c5b7691c100ad4eea07ca926bcea05/lib/internal/process/execution.js#L182-L187).
cc @zcbenz @nornagon @jkleinsc 
Notes: Fixed an issue where some `async_hooks` were not properly emitted after an error in the renderer process.
> fix: properly emit after hooks after exception

- lib/browser/api/web-contents.ts
- lib/browser/ipc-main-internal-utils.ts
- lib/renderer/api/ipc-renderer.ts
- lib/renderer/ipc-renderer-internal.ts
- shell/browser/api/electron_api_web_contents.cc
- shell/browser/api/electron_api_web_contents.h
- shell/common/api/api.mojom
- shell/renderer/api/electron_api_ipc_renderer.cc
- shell/renderer/electron_api_service_impl.cc
- shell/renderer/electron_api_service_impl.h
- typings/internal-ambient.d.ts
- typings/internal-electron.d.ts
No longer needed after the native Chrome extensions support has landed.
> chore: remove unused sendToAll + related APIs

- npm/index.js
If you --ignore-scripts when installing electron currently, it'll fail to write the path.txt file and thus fail to use the override dist path. Open to other solutions - just hoping to be able to use a prebuilt electron binary with the default package without having to muck around with it installing an unused version.
Default to `electron` if the `ELECTRON_OVERRIDE_DIST_PATH` environment variable is present.
Notes: none
> feat: allow path override with --ignore-scripts

- lib/browser/remote/server.ts
`IPC_MESSAGES.RENDERER_RELEASE_CALLBACK` is an internal IPC message and needs to be sent via `_sendToFrameInternal()`.
This regression was introduced in #24115.
Notes: Fixed callbacks passed via the `remote` module not being released after all references are dropped.
> fix: send IPC_MESSAGES.RENDERER_RELEASE_CALLBACK as internal message

- docs/api/context-bridge.md
- lib/renderer/api/context-bridge.ts
- shell/renderer/api/electron_api_context_bridge.cc
- spec-main/api-context-bridge-spec.ts
This PR allows exposing non-object APIs via contextBridge `exposeInMainWorld`.
```ts
contextBridge.exposeInMainWorld('nonObjectString', 'some-text')
contextBridge.exposeInMainWorld('nonObjectFunction', () => console.log('nonObjectFunction console log'))
contextBridge.exposeInMainWorld('nonObjectArray', [1, 2, 3, 4])
contextBridge.exposeInMainWorld('nonObjectPromise', Promise.resolve('resolved-value'))
contextBridge.exposeInMainWorld('nonObjectPromiseReject', Promise.reject(new Error('i-rejected-non-object')))
contextBridge.exposeInMainWorld('nonObjectError', new Error('error-value'))
contextBridge.exposeInMainWorld('nonObjectSymbol', Symbol('unique'))
contextBridge.exposeInMainWorld('nonObjectUnit8Arr', new Uint8Array(100))
contextBridge.exposeInMainWorld('nonObjectComplex',
(second) => …
```
> feat: exposeInMainWorld allow to expose non-object APIs

- patches/chromium/.patches
- patches/chromium/ui_check_that_unpremultiply_is_passed_a_32bpp_image.patch
ui: CHECK that UnPremultiply is passed a 32bpp image
To do otherwise results in accessing random data.
BUG=1147430
TEST=none
(cherry picked from commit 1f673896837ab8c687d93fec604c96c78c7f679b)
Change-Id: Icedacbaac64cad3fc903e6423c6f9aad8c1e8cb5
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2531118
Commit-Queue: danakj <danakj@chromium.org>
Reviewed-by: danakj <danakj@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#826300}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2538047
Reviewed-by: Scott Violet <sky@chromium.org>
Commit-Queue: Scott Violet <sky@chromium.org>
Cr-Commit-Position: refs/branch-heads/4240@{#1452}
Cr-Branched-From: f297677702651916bbf65e59c0d4bbd4ce57d1ee-refs/heads/master@{#800218}
Notes: backported the …
> chore: cherry-pick 8c346e3cd9 from chromium.

- patches/chromium/.patches
- patches/chromium/cherry-pick-eec5025668f8.patch
Merged: [wasm][code cache] Match response to cached raw resource
- Verifies that the retrieved resource has the same response time, and
that the source matches (i.e. both are from service worker, or both
are not).
Bug: chromium:1146673
(cherry picked from commit a8b46244ecaa1647ee2d70304878c0365ee04087)
Change-Id: I6243ec9017b2405687056aa6ea199c67b1c16063
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2526802
Reviewed-by: Andreas Haas <ahaas@chromium.org>
Commit-Queue: Bill Budge <bbudge@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#826277}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2537531
Commit-Queue: Andreas Haas …
> chore: cherry-pick eec5025668f8 from chromium

- lib/browser/api/web-contents.ts
- typings/internal-electron.d.ts
This method is not called.
Notes: none
> chore: remove unused _replyInternal method

- lib/browser/api/screen.ts
- spec-main/api-screen-spec.ts
Let's make it possible to stub `screen` methods for testing.
Notes:  Fixed "screen" methods to be reassignable again.
> fix: add a "set" trap to the "screen" module proxy

- lib/renderer/security-warnings.ts
Fixes #26829
Notes: Fixes uncaught promise rejection when creating `webContents` with javascript disabled
> fix: handle security warnings promise when JS is disabled

- docs/api/session.md
- docs/breaking-changes.md
- shell/browser/electron_permission_manager.cc
Bringing back #14544
Fixes #14544
Notes: Additional permission checks are now routed through `session.setPermissionCheckHandler`.  These include `Notification.permission`, and `permission.query`.  Please note that the `webContents` parameter to the check handler can now be null.
> feat: route frame based permission checks through our permission check handler

- docs/tutorial/quick-start.md
Unhandled exception error is received if description is not defined while running "npm run make."  Defining a description solves this issue.
Notes: none
> docs: add description to package.json of quick-start

- docs/tutorial/using-native-node-modules.md
Attempt to make the native modules documentation clearer, and mention Electron Forge where appropriate.
> docs: clean up the native modules documentation

- shell/browser/api/electron_api_system_preferences.h
- shell/browser/api/electron_api_system_preferences_mac.mm
- shell/browser/api/electron_api_web_request.cc
- shell/browser/api/electron_api_web_request.h
> refactor: convert more C++ enums to C++11 enum classes

- docs/api/web-contents.md
- docs/tutorial/offscreen-rendering.md
The max FPS for offscreen rendering was changed from 60 to 240 in #11728, but the docs were never update. Oops!
Notes: none
> docs: update OSR max FPS number

- lib/browser/api/screen.ts
Follow-up to https://github.com/electron/electron/pull/26620.
Closes https://github.com/electron/electron/issues/26713.
Fixes an issue whereby `remote.screen` EventEmitter methods are undefined in the renderer. This is fixed by implementing `getPrototypeOf` as a Proxy trap.
cc @nornagon @MarshallOfSound 
Notes: Fixed an issue whereby `remote.screen` `EventEmitter` methods are undefined in the renderer.
> fix: screen EventEmitter methods with remote

- lib/browser/api/system-preferences.ts
This seems like a copy-paste error. It should return `systemPreferences.getEffectiveAppearance()`.
Notes: Fix `systemPreferences.effectiveAppearance` returning `systemPreferences.getAppLevelAppearance()`.
> fix: systemPreferences.effectiveAppearance returning systemPreferences.getAppLevelAppearance()

- lib/browser/navigation-controller.ts
- lib/browser/rpc-server.ts
Only keep the `NavigationController` class in `lib/browser/navigation-controller.ts`.
> refactor: move IPC handlers from navigation-controller to rpc-server

- patches/chromium/.patches
- patches/chromium/cherry-pick-5ffbb7ed173a.patch
Pepper: Ensure weak pointer is still valid before use (M86).
TBR=bbudge@chromium.org
(cherry picked from commit f24c213293752250db05e11c5e4b77adce002d38)
Bug: 1146675
Change-Id: I382dcb5c0b09a26e3c397ebef46947f626e2aef9
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2527065
Reviewed-by: Bill Budge <bbudge@chromium.org>
Commit-Queue: Darwin Huang <huangdarwin@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#825558}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2536757
Reviewed-by: Darwin Huang <huangdarwin@chromium.org>
Cr-Commit-Position: refs/branch-heads/4240@{#1448}
Cr-Branched-From: f297677702651916bbf65e59c0d4bbd4ce57d1ee-refs/heads/master@{#800218}
Notes: Security: backported the fix to CVE-2020-16014: Use after free in …
> chore: cherry-pick 5ffbb7ed173a from chromium

- .gitmodules
`boto` is replaced by `aws-sdk-js`, but it has not been removed from git submodule
See also https://github.com/electron/electron/pull/24863
Notes: none
> build: remove boto from git submodule

- patches/chromium/.patches
- patches/chromium/cherry-pick-ecdec1fb0f42.patch
Fix text eliding for single-codepoint text with BiDi
This CL is fixing a corner case where RenderText::Elide(...) may
produce a text with more codepoints than the original one. This is
an issue since the breaklists are not resized and the overflow
will lead the render_text code to perfoarm an out-of-bound memory
access by deferencing breaks_.end() while rendering the text. This
is causing chrome to crash.
See crbug/1142020 for details.
The bug was happening when:
1) The text to elide was a single codepoint
2) The width of the glyph of the codepoint is larger than the width
of the ellipsis glyph
3) Eliding is set to ELIDING_TAIL
4) The display_rect width will trigger eliding
(smaller than codepoint width, but larger than ellipsis width)
5) The render text is set to RTL
A possible solution …
> chore: cherry-pick ecdec1fb0f42 from chromium

- shell/browser/ui/message_box_gtk.cc
Tests: https://github.com/stevenjoezhang/electron-quick-start
Issue resolved: https://github.com/electron/electron/issues/26482
See also https://github.com/electron/electron/pull/2145
Ref https://developer.gnome.org/gtk3/stable/GtkMessageDialog.html#gtk-message-dialog-new
Notes: Fixed an issue that a message box in GTK contains no buttons.
> fix: message box missing an "OK" button in GTK

- docs/api/structures/ipc-main-event.md
- docs/api/structures/ipc-main-invoke-event.md
- docs/api/web-frame-main.md
- lib/browser/api/web-contents.ts
- shell/common/gin_converters/frame_converter.cc
- shell/common/gin_converters/frame_converter.h
- spec-main/api-subframe-spec.ts
Also add missing `event.processId`, which needs to be passed to `webFrameMain.fromId()`.
Notes: Added `event.senderFrame` property returning the originating `webFrameMain` of the IPC message.
> feat: add event.senderFrame property returning the webFrameMain

- patches/chromium/.patches
- patches/chromium/cherry-pick-bbc6ab5bb49c.patch
Add ports 5060 and 5061 to the restricted list
Some NAT devices examine traffic on port 5060 to look for a valid SIP
message. If they find one, they will forward a port back to the origin
host. A carefully crafted HTTP request can trick these NAT devices into
forwarding an arbitrary port. See https://samy.pl/slipstream for more
details on the attack and sample code.
Block port 5060 for HTTP. Out of an abundance of caution, and to match
the Fetch standard (https://github.com/whatwg/fetch/pull/1109), also
block port 5061 (SIP over TLS).
Also reduce the whitespace before protocol description comments. This
was insisted on by clang-format and is not worth fighting.
BUG=1145680
(cherry picked from commit 90d1302aec437166b383eabc08af741bf24f7ea8)
(cherry picked from commit …
> chore: cherry-pick bbc6ab5bb49c from chromium

- .circleci/config.yml
Occasionally CircleCI builds fail while printing the ninja summary of the build.  Since this report is informational only, this PR changes that step so that any failures are ignored.
Here's an example of a failed build: https://app.circleci.com/pipelines/github/electron/electron/33723/workflows/138db88d-eacb-4421-8ea9-3b1a6c5cef81/jobs/741116
Notes: none
> ci: ignore failures on Ninja summary

- patches/chromium/.patches
- patches/chromium/merge_m86_ensure_that_buffers_used_by_imagedecoder_haven_t_been.patch
"Ensure that buffers used by ImageDecoder haven't been neutered."
Since JavaScript may detach the underlying buffers, we need to check
to ensure they're still valid before using them for decoding.
TBR=sandersd
(cherry picked from commit fa93fba6a28d384b0a0cddd63e85eb10cb97bb53)
Test: Updated unittests. Manual test case breaks.
Change-Id: Iefe5f8adf619cd6afdfedcb08a13c2996bfe0d32
Fixed: 1146761
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2527542
Commit-Queue: Dale Curtis <dalecurtis@chromium.org>
Auto-Submit: Dale Curtis <dalecurtis@chromium.org>
Reviewed-by: Dan Sanders <sandersd@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#825615}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2537781
Reviewed-by: Dale Curtis …
> chore: cherry-pick 381c4b5679 from chromium.

- .gitignore
- script/lint.js
* Ensure --fix output is actually written to disk
* Cache bust on lint.js file changes
* Ensure CI does not use the linting cache
> build: fix JS linting

- docs/api/context-bridge.md
- shell/renderer/api/electron_api_context_bridge.cc
- spec-main/api-context-bridge-spec.ts
As in title and as in notes, uses blink APIs to safely transfer a WebElement reference from one context to another
Notes: Added support for passing DOM elements over the context bridge
> feat: add support for DOM elements going over the context bridge

- patches/chromium/.patches
- patches/chromium/cherry-pick-d8d64b7cd244.patch
Ensure change type for OverflowControlsClip is returned
This at least ensures that we will update the paint properites for the
composited overflow control layers in pre-CompositeAfterPaint to avoid
stale properties on the layers.
The test doesn't actually reproduce the bug because any test simpler
than the bug case couldn't reproduce the bug as the update would be
triggered in other code paths (any style change, layout change, etc.).
Anyway this CL does fix the bug case.
TBR=wangxianzhu@chromium.org
(cherry picked from commit c20bb9897ef6d26a46391a4dc1658c5d33e0c100)
(cherry picked from commit cfb81e677a508871f56d8bec958d0b585298ae0c)
Bug: 1137603
Change-Id: I5cca970bcf8cda6085527f79a97f269c4e3e9986
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2500264 …
> chore: cherry-pick d8d64b7cd244 from chromium

- patches/v8/.patches
- patches/v8/cherry-pick-290fe9c6e245.patch
Merged: [compiler] Fix a bug in SimplifiedLowering
Revision: ba1b2cc09ab98b51ca3828d29d19ae3b0a7c3a92
BUG=chromium:1150649
NOTRY=true
TBR=tebbi@chromium.org
Change-Id: I3600d25ebc255b0e58a7db1ca8d025424f6ad3f5
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/2557983
Reviewed-by: Georg Neis <neis@chromium.org>
Cr-Commit-Position: refs/branch-heads/8.7@{#55}
Cr-Branched-From: 0d81cd72688512abcbe1601015baee390c484a6a-refs/heads/8.7.220@{#1}
Cr-Branched-From: 942c2ef85caef00fcf02517d049f05e9a3d4b440-refs/heads/master@{#70196}
Notes: Security: backport fix for 1150649.
> chore: cherry-pick 290fe9c6e245 from v8

- docs/breaking-changes.md
This should have been done in #19656.
> docs: add missing deprecated systemPreferences APIs to breaking-changes

- patches/chromium/.patches
- patches/chromium/cherry-pick-3abc372c9c00.patch
Apply markup sanitizer in CompositeEditCommand::MoveParagraphs()
CompositeEditCommand::MoveParagraphs() serailizes part of the DOM and
then re-parse it and insert it at some other place of the document. This
is essentially a copy-and-paste, and can be exploited in the same way
how copy-and-paste is exploited. So we should also sanitize markup in
the function.
(cherry picked from commit c529cbcc1bb0f72af944c30f03c2b3b435317bc7)
Bug: 1141350
Change-Id: I25c1dfc61c20b9134b23e057c5a3a0f56c190b5c
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2500633
Commit-Queue: Yoshifumi Inoue <yosin@chromium.org>
Reviewed-by: Yoshifumi Inoue <yosin@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#821098}
Reviewed-on: …
> chore: cherry-pick 3abc372c9c00 from chromium

- script/release/uploaders/upload-symbols.py
Fixes #26961.
Notes: Add Electron DLLs like libGLESv2.dll to symbol server
> fix: Upload all *.dll.pdb to symbol server

- docs/api/structures/ipc-main-event.md
- docs/api/structures/ipc-main-invoke-event.md
- docs/api/web-contents.md
- lib/browser/api/web-contents.ts
- lib/browser/remote/server.ts
- shell/browser/api/electron_api_web_contents.cc
- shell/browser/api/electron_api_web_contents.h
- shell/common/gin_helper/event_emitter.cc
- spec-main/api-ipc-main-spec.ts
- spec-main/fixtures/snapshots/proxy-window-open.snapshot.txt
- spec-main/guest-window-manager-spec.ts
- typings/internal-electron.d.ts
Backport of #26875. See that change for details.
Notes: Fixed an issue where `event.reply` could sometimes not deliver a reply to an IPC message when cross-site iframes were present.
> fix: restrict sendToFrame to same-process frames by default

- docs/api/structures/ipc-main-event.md
- docs/api/structures/ipc-main-invoke-event.md
- docs/api/web-contents.md
- lib/browser/api/web-contents.ts
- lib/browser/remote/server.ts
- shell/browser/api/electron_api_web_contents.cc
- shell/browser/api/electron_api_web_contents.h
- shell/common/gin_helper/event_emitter.cc
- spec-main/api-ipc-main-spec.ts
- spec-main/fixtures/snapshots/proxy-window-open.snapshot.txt
- spec-main/guest-window-manager-spec.ts
- typings/internal-electron.d.ts
Backport of #26875. See that change for details.
Notes: Fixed an issue where `event.reply` could sometimes not deliver a reply to an IPC message when cross-site iframes were present.
> fix: restrict sendToFrame to same-process frames by default (#26875)

- patches/skia/.patches
- patches/skia/cherry-pick-6763a713f957.patch
Limit morphology radius to 100 pixels
This limit is arbitrary, but hopefully prevents pathological (or
malicious) SVG content from consuming huge amounts of CPU/GPU time,
without impacting any legitimate uses of feMorphology. (Typical usage
has a much smaller radius).
Bug: chromium:1123035
Change-Id: I4405bc595128e9a6287eb5efa1be14621baa3a00
Reviewed-on: https://skia-review.googlesource.com/c/skia/+/315219
Reviewed-by: Mike Reed <reed@google.com>
Commit-Queue: Brian Osman <brianosman@google.com>
Notes: Security: backported fix for chromium:1123035.
> chore: cherry-pick 6763a713f957 from skia

- lib/asar/fs-wrapper.ts
- spec/asar-spec.js
when using `readdir`/`readdirSync` (w/ withFileTypes) on a deep directory within the archive, the code fails to get the stats of child paths.
Notes: Fixed `readdir`/`readdirSync` (w/ `withFileTypes`) failing on a deep directory within archive.
> fix: readdir/readdirSync (w/ withFileTypes) failing on a deep directory within asar archive

- docs/api/global-shortcut.md
- shell/browser/api/electron_api_global_shortcut.cc
Fixes #26986.
We should throw in JS instead of CHECK()ing.
No release notes because this module was already not usable before
app.on('ready'), it just changes a CHECK to an exception.
Notes: none
> fix: throw when using globalShortcut before ready

- shell/common/gin_converters/content_converter.cc
When mapping content::PermissionType enum values from C++ to javascript, the content::PermissionType::CAMERA_PAN_TILT_ZOOM case statement fell through to the next case, which was FONT_ACCESS. This meant that if the CAMERA_PAN_TILT_ZOOM permission were requested, the JS permission request handler would get called with the string 'font-access' as the permission.
This change changes that mapping so that CAMERA_PAN_TILT_ZOOM corresponds to the string 'media'. Having CAMERA_PAN_TILT_ZOOM be the same string as VIDEO_CAPTURE matches https://source.chromium.org/chromium/chromium/src/+/master:content/browser/devtools/protocol/browser_handler.cc;l=150?q=CAMERA_PAN_TILT_ZOOM%20-f:%5Eout%20lang:cc&start=11.
Notes: Apps requesting the CAMERA_PAN_TILT_ZOOM permission will have the permission request …
> fix: incorrect case in content::PermissionType mapping

- shell/browser/electron_browser_main_parts.h
- shell/browser/microtasks_runner.cc
- shell/common/api/electron_bindings.cc
We should be using the publicly exposed `CallbackScope` where possible, since `InternalCallbackScope` is not public and ideally we should be working to get rid of our patch exposing it. We can't fully get rid of it yet, since our integration with `async_hooks` is broken and we need to specifically skip them when we're adding a callback scope to load the `Environment` in `ELECTRON_RUN_AS_NODE`, but i'll be doing that as a follow up.
Notes: none
> refactor: use public node::CallbackScope where possible

- docs/breaking-changes.md
- lib/browser/api/system-preferences.ts
- shell/browser/api/electron_api_system_preferences.cc
- shell/browser/api/electron_api_system_preferences.h
- shell/browser/api/electron_api_system_preferences_mac.mm
- spec-main/api-system-preferences-spec.ts
Deprecated documentation added in #26848.
Notes: Remove deprecated `systemPreferences` methods.
> chore: remove deprecated systemPreferences methods

- shell/browser/api/electron_api_browser_view.cc
- shell/browser/api/electron_api_web_contents.cc
- shell/browser/api/electron_api_web_contents.h
- shell/browser/api/electron_api_web_contents_view.cc
- spec-main/api-browser-view-spec.ts
This PR adds support for `webContents` option in BrowserView, which works similarly as in BrowserWindow. Since the new `webContents.setWindowOpenHandler` doesn't support BrowserViews, we can at least listen to the internal `-add-new-contents` event and create a BrowserView with provided `webContents`. This PR will also help in adding support for BrowserView in `setWindowOpenHandler` in the future.
Closes #24833
Could this be backported to 12-x-y?
Since it's a hidden API, I think it's not worth mentioning this change in the release notes.
> feat: add support for webContents option in BrowserView

- docs/api/browser-window.md
- shell/browser/api/electron_api_base_window.cc
- shell/browser/native_window.h
- shell/browser/native_window_mac.h
- shell/browser/native_window_mac.mm
- spec-main/api-browser-window-spec.ts
This PR makes `trafficLightPosition` and its set/get APIs work for windows with `customButtonOnHover` titleBarStyle, close https://github.com/electron/electron/issues/10243.
Notes: Make `trafficLightPosition` option work for `customButtonOnHover` window.
> feat: make trafficLightPosition work for customButtonOnHover

- docs/api/web-contents.md
- shell/common/gin_converters/blink_converter.cc
- shell/common/gin_converters/content_converter.cc
This PR fills in a nontrivial amount of data missing from the object emitted by the 'context-menu' event. It'd been a significant amount of time since this was last updated, so a number of fields have been added to the object which may be useful to users handling the event and which we should therefore expose.
cc @zcbenz @jkleinsc @MarshallOfSound 
Notes: Added missing fields to the parameters emitted as part of the `context-menu` event.
> feat: add missing 'context-menu' values

- lib/browser/api/protocol.ts
- spec-main/api-remote-spec.ts
Close https://github.com/electron/electron/issues/26900.
Notes: Fixed `protocol` methods not being accessible via `remote.protocol`.
> fix: make protocol wrapper remote-friendly again

- docs/api/session.md
This PR fixes the code example for the new `select-serial-port` events:
- The event returns four parameters, including webContents.
- vendorId and productId are strings
- there is no result1
/cc @jkleinsc 
Notes: none
> docs: update select-serial-port example

- lib/browser/desktop-capturer.ts
Fixes #21555.
The event listener was never being removed.
Notes: Fixed a memory leak in desktopCapturer.getSources.
> fix: memory leak in desktopCapturer.getSources

- lib/browser/api/web-contents.ts
Fixes #26567.
This makes `WebContents.id` work even after the underlying `WebContents` C++
object is destroyed, allowing `remote` to clean up its object registry safely.
Notes: Fixed a crash that could occur on app quit when using the remote module.
> fix: make webContents.id work even after destroy

- shell/browser/native_window.h
- shell/browser/native_window_mac.h
- shell/browser/native_window_mac.mm
The `NativeWindowMac` class has become a bit hard to work on, because its overrides do not match the base class's order, and its method definitions do not match the declarations' order. So I'm putting them in order in this PR.
This will make certain backports harder, but I think it worths the efforts otherwise the class will only become more messy, and I already find it very difficult to add new methods to this class.
There is no actual change to the code except for simple moves.
> chore: put NativeWindowMac's methods in order

- shell/browser/native_window_mac.mm
`setTitlebarAppearsTransparent` has already been called above for frameless window, and `title_bar_style_ != TitleBarStyle::kNormal` forces the window to be a frameless window.
Notes: none
> chore: remove extra setTitlebarAppearsTransparent

- shell/browser/native_browser_view_views.cc
Closes https://github.com/electron/electron/issues/27131.
Closes https://github.com/electron/electron/issues/27149.
Fixes an issue where some BrowserViews might exhibit unclickable button behavior when loading some websites. What was happening was that #26738 made the mistaken assumption that snapped areas should be draggable, which meant that when users set `-webkit-app-region: no-drag` the areas would become draggable (and thus not clickable).
Tested with https://gist.github.com/f1426205af6799b5d208d1cd54136457 and confirmed not to regress initial fix made in https://github.com/electron/electron/pull/26738 with https://gist.github.com/7278c8c62ec976110afb47ef2d861a7a.
Notes: Fixed an issue where some draggable regions were not clickable when loaded into BrowserViews on Windows.
> fix: unclickable regions in some draggable BrowserViews

- script/lib/git.py
Before:
```sh
electron on git:roller/chromium/master ❯ e patches all                  10:05AM
Exporting 11 patches since ef6c61213b14d3cf31e97bbd314e1dda24794a0d
Exporting 1 patches since 78d3966b3c331292ea29ec38661b25df0a245948
Exporting 1 patches since 3b39cefc6195f782b655e2c73ac2a73313c28879
Exporting 32 patches since a2f9a70900a7cde073b1426d71fd211bbd25c342
Exporting 2 patches since cdc0729c8bf8576bfef18629186e1e9ecf1b0d9f
Exporting 1 patches since 74ab5baccc6f7202c8ac69a8d1e152c29dc1ea76
Exporting 108 patches since 232a0643cdd7b98a844b43c6c5e3fa33a2c60f78
Exporting 2 patches since ca058c06474c4492f0fbd517679793234dde6165
Exporting 1 patches since 2c4ee8a32a299eada3cd6e468bbd0a473bfea96d
```
After:
```sh
electron on git:roller/chromium/master ❯ e patches all                  10:07AM …
```
> build: show more info about exported patches

- docs/api/webview-tag.md
It seems like the WebView spec URL went down sometime this past month ([link to archive](http://web.archive.org/web/*/https://developer.chrome.com/apps/tags/webview)).
Notes: none
> docs: update broken Chrome webview URL

- shell/browser/api/electron_api_base_window.cc
- shell/browser/api/electron_api_base_window.h
- shell/browser/api/electron_api_tray.cc
- shell/browser/api/electron_api_tray.h
- shell/browser/api/electron_api_web_contents.cc
- shell/browser/browser.h
- shell/browser/browser_mac.mm
- shell/common/api/electron_api_native_image.cc
- shell/common/api/electron_api_native_image.h
- shell/common/gin_converters/image_converter.cc
- spec-main/api-app-spec.ts
- spec-main/api-tray-spec.ts
- spec-main/api-web-contents-spec.ts
This refactor pulls the `base::FilePath` converter option out of the `NativeImage` converter.  Our converter contract is that converters return false when they fail -  they shouldn't touch the exception state.
Placed which previously leveraged the `NativeImage` converter to allow either a path or an image object are now changed to take `v8::Local<v8::Value>`s in their arguments instead of `gin::Handle<NativeImage>`, and detect the type passed and invoke the appropriate method for acquiring the image depending on whether the user passed a bespoke `NativeImage` or a string.
This also allows for better error handling by allowing the callers to decide whether to throw errors into JavaScript.
cc @nornagon @jkleinsc @zcbenz 
Notes: none
> refactor: remove path from nativeImage converter

- shell/browser/native_browser_view_mac.mm
- shell/browser/ui/drag_util.cc
Closes https://github.com/electron/electron/issues/27112.
Fixes an issue where non-draggable regions on `BrowserView`s would have an incorrectly assumed `(x,y)` origin of `(0,0)` which is an assumption that can be made for `BrowserWindow`s but _not_ for `BrowserView`s. In the latter case, we should calculate and pass the origin point of the BrowserView and pass it instead.
Notes: Fixes an issue where non-draggable regions on BrowserViews could have incorrectly calculated bounds.
> fix: default offset when no BrowserView drag regions

- shell/browser/api/electron_api_base_window.cc
- spec-main/api-browser-view-spec.ts
Closes https://github.com/electron/electron/issues/26975.
Fixes an issue where a `BrowserView` couldn't be reparented properly (moved from one `BrowserWindow` to another) because it wasn't properly detached from the first `BrowserWindow`.
A `BrowserWindow` has a one-to-many relationship with `BrowserViews`, but a `BrowserView` can only have a single owner window. As such, if a `BrowserView` is added to a `BrowserWindow` which has an owner window which is  both not null and _not_ the current window in question, then it needs to be properly detached from the previous owner window.
Tested with https://gist.github.com/a786242649a5d2e462c3328c905f0c9f.
Notes: Fixes an issue where BrowserViews couldn't be effectively reparented.
> fix: handle BrowserView reparenting

- docs/api/web-contents.md
Ref #27066.
Backport because https://github.com/electron/electron/pull/26875 was backported
too.
Notes: none
> docs: document frameId meaning

- docs/api/extensions.md
- shell/browser/electron_browser_client.cc
- shell/browser/extensions/electron_extension_loader.cc
- shell/common/extensions/electron_extensions_client.cc
- spec-main/extensions-spec.ts
- spec-main/fixtures/extensions/chrome-webRequest-wss/background.js
- spec-main/fixtures/extensions/chrome-webRequest-wss/manifest.json
- spec-main/fixtures/extensions/chrome-webRequest/background.js
- spec-main/fixtures/extensions/chrome-webRequest/manifest.json
Backport of #22655
Notes: Fixed `chrome.webRequest` extensions API not intercepting any requests.
> fix(extensions): implement missing web_request hooks

- docs/api/browser-window.md
- patches/chromium/.patches
- patches/chromium/enable_reset_aspect_ratio.patch
- shell/browser/native_window_views.cc
- shell/browser/ui/views/frameless_view.cc
- shell/browser/ui/views/native_frame_view.cc
Close https://github.com/electron/electron/issues/8036.
This PR makes `win.setAspectRatio` work on Windows. It didn't work previously because the Windows implementation requires a non-zero maximum size, while we provided (0, 0) when maximum size is not set.
There is also a patch added to allow setting aspect ratio to 0 on Windows.
I'm unable to write a test for this because the aspect ratio is not respected when window is resized programmingly with APIs like `win.setSize`, it is also why we did not have a test for it at the first place.
Notes: Make `win.setAspectRatio()` work on Windows.
> feat: make win.setAspectRatio() work on Windows

- docs/api/web-frame-main.md
- shell/browser/api/electron_api_web_frame_main.cc
- shell/browser/api/electron_api_web_frame_main.h
- spec-main/api-web-frame-main-spec.ts
Add this missing API for consistency with `webFrame` and `webContents`.
Notes: Added missing `webFrameMain.executeJavaScriptInIsolatedWorld()`.
> feat: add missing webFrameMain.executeJavaScriptInIsolatedWorld()

- docs/api/browser-window.md
When using a depreciated vibrancy style in your app, the following message is printed to console. This PR updates so it matches the docs.
`(node:33818) electron: NSVisualEffectMaterialDark has been deprecated and removed as of macOS 10.15.`
Notes: none
> docs: NSVisualEffectMaterialDark has been deprecated and removed as of macOS 10.15

- docs/development/build-instructions-linux.md
Add the libraries required to build on Arch Linux / Manjaro
Notes: none.
Related to: https://github.com/electron/electron/pull/27108
> docs: add libraries for arch and manjaro linux

- docs/api/structures/display.md
These properties are in DIP points (rather than screen points). We can use `screen.dipToScreen*` to convert to screen points.
Notes: none.
> docs: coordinate system of Display.bounds and Display.workArea

- spec-main/api-protocol-spec.ts
This test fails when using a custom ffmpeg build without the appropriate codecs.
> test: skip protocol.registerSchemesAsPrivileged stream test when media not supported

- .circleci/config.yml
This resolves the issue of mac builds failing trying to restore the home brew cache, as seen here:
https://app.circleci.com/pipelines/github/electron/electron/34454/workflows/03af8a9e-1356-41cd-b74d-1541a4a4d84d
and here:
https://app.circleci.com/pipelines/github/electron/electron/34452/workflows/f6f88137-9be6-4475-bc72-ea42e57b57eb
Notes: none
> ci: fix broken homebrew cache

- spec-main/api-web-contents-spec.ts
This test fails when using a custom ffmpeg build without the appropriate codecs.
> test: skip PictureInPicture video when media not supported

- spec/webview-spec.js
This test fails when using a custom ffmpeg build without the appropriate codecs.
> test: skip media-started-playing media-paused events test when media not supported

- electron_paks.gni
Fixes broken PDF viewer introduced in https://github.com/electron/electron/pull/25995. 
Refs https://chromium-review.googlesource.com/c/chromium/src/+/2489921.
Verifiable by adding
```js
mainWindow.loadURL('http://www.africau.edu/images/default/sample.pdf')
```
to any fiddle.
Notes: Fixes PDFs not loading in the PDF viewer.
> fix: broken PDF viewer

- spec-main/chromium-spec.ts
We are getting this error when running Electron tests on our internal builds:
```
not ok 1620 chrome extensions emits extension lifecycle events
AssertionError: expected 'mhjfbmdgcfjbbpaeojofohoefgiehjai' to equal 'eljodghdfipnjkfegmopjgggbaniogag'
at Context.<anonymous> (electron/spec-main/extensions-spec.ts:135:34)
```
Handle the case when multiple extensions are loaded.
> test: use emittedUntil in PDF Viewer tests

- shell/browser/extensions/api/resources_private/resources_private_api.cc
Fixes the following error seen when loading PDFs:
```
[74831:0107/104235.588122:INFO:CONSOLE(222)] "Unexpected condition on chrome-extension://mhjfbmdgcfjbbpaeojofohoefgiehjai/index.html: Could not find value for presentationModeEnabled", source: chrome://resources/js/load_time_data.m.js (222)
[74831:0107/104235.588212:INFO:CONSOLE(222)] "Unexpected condition on chrome-extension://mhjfbmdgcfjbbpaeojofohoefgiehjai/index.html: [undefined] (presentationModeEnabled) is not a boolean", source: chrome://resources/js/load_time_data.m.js (222)
```
cc @MarshallOfSound @jkleinsc 
Notes: Fix missing presentation mode option in PDF viewer.
> fix: set presentationModeEnabled value for PDF viewer

- script/codesign/codesign.cnf
Make it work with a bit different OpenSSL version.
> build: fix installing of code-signing identity on macOS

- docs/api/screen.md
[Electron inherits this confusing name from Chromium](https://github.com/chromium/chromium/blob/99314be8152e688bafbbf9a615536bdbb289ea87/ui/display/win/screen_win.cc#L677-L681). We can also see there that the return value is a DIPPoint, due to `ScreenToDIPPoint` call:
gfx::Point ScreenWin::GetCursorScreenPoint() {
POINT pt;
::GetCursorPos(&pt);
return gfx::ToFlooredPoint(ScreenToDIPPoint(gfx::PointF(gfx::Point(pt))));
}
I lost over a day due to debugging this. I don't think we can change the method name due to backwards compatibility, but we can at least make amends in the documentation.
Notes: none
> docs: coordinate system of badly named method getCursorScreenPoint

- docs/api/structures/desktop-capturer-source.md
Corrected the meaning of the id string to match observed behavior (verified on Windows 10 and Ubuntu)
Corrected the meaning of the id string to match observed behavior (verified on Windows 10 and Ubuntu)
Notes: none
> docs: correct meaning of DesktopCapturerSource.id 

- docs/tutorial/code-signing.md
The certificate authority mentioned "Comodo" has recently been renamed "Sectigo". This updates the name of the certificate authority, and the link to get the code signing certificates for Sectigo/Comodo.
Notes: none.
> docs: renames Comodo to Sectigo

- docs/api/web-request.md
- shell/browser/api/electron_api_web_request.cc
- spec-main/api-web-request-spec.ts
This adds a `frame` property to the `details` object passed to `webRequest`
handlers, so that the main process can discriminate based on the origin frame.
It also adds a `webContents` property for more convenient access to the
containing `WebContents`--this was already indirectly available as
`webContentsId`, but there's no reason not to expose the object directly.
Notes: Added `frame` and `webContents` properties to the details object in webRequest handlers.
> feat: add frame and webContents to webRequest details

- docs/api/structures/ipc-main-event.md
- docs/api/structures/ipc-main-invoke-event.md
- docs/api/web-frame-main.md
- lib/browser/api/web-contents.ts
- shell/common/gin_converters/frame_converter.cc
- shell/common/gin_converters/frame_converter.h
- spec-main/api-subframe-spec.ts
Backport of #26764
Notes: Added `event.senderFrame` property returning the originating `webFrameMain` of the IPC message.
> feat: add event.senderFrame property returning the originating webFrameMain

- .github/semantic.yml
It is not necessary requiring commit messages to be semantic, since we always do "squash and merge" so as long as the PR title is semantic the final commit message will be too.
This would make it easier to merge PRs from beginners since lots of them do not understand why the "
Semantic Pull Requests" check keeps failing. 
Notes: none
> chore: only do semantic check on PR titles

- shell/browser/api/electron_api_web_contents.cc
Surface failed load error messages a little more readily so that new folks aren't left as confused. 
e.g. https://github.com/electron/electron/issues/5107#issuecomment-281200144
> chore: surface webcontents load error more readily

- shell/browser/api/electron_api_web_contents.cc
- shell/browser/api/electron_api_web_contents.h
We should be using the upstream TaskRunner logic that Chromium does, as seen [here](https://source.chromium.org/chromium/chromium/src/+/master:chrome/browser/ui/webui/print_preview/local_printer_handler_default.cc;l=36-57;bpv=1;bpt=1). This fixes that. 
cc @deepak1556 @zcbenz @MarshallOfSound 
Notes: none
> refactor: use platform-specific TaskRunner to print

- shell/browser/browser.cc
- shell/browser/browser_linux.cc
- shell/browser/browser_win.cc
Reuse the general `Browser::Focus` implementation on Windows, and remove the ancient low-level code.
Notes: none
> chore: remove ancient Browser::Focus implementation on Windows

- spec-main/chromium-spec.ts
Reverts #27248, it wasn't fixing the correct test.
> revert: test use emittedUntil in PDF Viewer tests

- patches/chromium/disable_color_correct_rendering.patch
- patches/chromium/fix_disable_usage_of_setapplicationisdaemon_and.patch
- patches/chromium/fix_patch_out_profile_refs_in_accessibility_ui.patch
- patches/chromium/fix_properly_honor_printing_page_ranges.patch
- patches/chromium/gpu_notify_when_dxdiag_request_fails.patch
- patches/chromium/mas_no_private_api.patch
- patches/node/allow_preventing_preparestacktracecallback.patch
- patches/node/fix_allow_preventing_setpromiserejectcallback.patch
- patches/node/n-api_src_provide_asynchronous_cleanup_hooks.patch
Fixes the patch warnings that had accumulated in the 11-x-y branch e.g. trailing whitespaces. No functional changes.
No single stakeholder; random reviewers welcomed
Notes: none
> chore: fix patch warnings in 11-x-y

- patches/node/chore_prevent_warn_non_context-aware_native_modules_being_loaded.patch
Closes https://github.com/electron/electron/issues/27252. 
We need to return `false` when a user attempts to load a non-context-aware native module in the renderer process with `app.allowRendererProcessReuse` enabled. This became an issue in Electron v12 and on because the default of `app.allowRendererProcessReuse` switched to `true`.
Verified by adding `require('node-pty').spawn('/bin/sh')` to an arbitrary renderer process and observing the correct error:
```
"Uncaught Error: Loading non-context-aware native module in renderer: '/private/var/folders/w4/6ckkx75165l174lkz07vgx_m0000gn/T/tmp-64859-HboWDaDRZg4c/node_modules/node-pty/build/Release/pty.node',
```
in console.
cc @deepak1556 @zcbenz 
Notes: Fixed a crash in renderer process when loading non-context-aware modules with …
> fix: crash in renderer process with non-context-aware modules

- docs/api/web-frame-main.md
- lib/browser/api/web-contents.ts
- lib/browser/api/web-frame-main.ts
- lib/browser/init.ts
- shell/browser/api/electron_api_web_contents.cc
- shell/browser/api/electron_api_web_contents.h
- shell/browser/api/electron_api_web_frame_main.cc
- shell/browser/api/electron_api_web_frame_main.h
- shell/common/api/electron_api_native_image.h
- spec-main/api-ipc-spec.ts
- spec-main/api-subframe-spec.ts
- spec-main/api-web-frame-main-spec.ts
- typings/internal-ambient.d.ts
- typings/internal-electron.d.ts
Add `webFrameMain.send()` / `webFrameMain.postMessage()`.
Notes: Added `webFrameMain.send()` / `webFrameMain.postMessage()`.
> feat: add webFrameMain.send() / webFrameMain.postMessage()

- shell/common/api/BUILD.gn
When enabling the component build it fails (at least on windows where I tested) due the fact that many mojom interfaces are included both by linking against `blink_common.dll` and by having `//third_party/blink/public/mojom:mojom_core` (source_set) as a dependency of `shell/common/api:mojo`. 
This change mirrors what happens in `//content/public/common/BUILD.gn`, which overrides the dependency on the source set with one on the blink_common dll, thus fixing the duplicate problem.
The override happens only if the component build is enabled so it shouldn't cause any issues for the builds already working.
Note that this change does not make it so that you can build with is_component_build=true right after cloning, for that to happen there are a few more problems that I encountered and that …
> chore: duplicate symbols for mojom interfaces in component build

- shell/browser/native_window_views.cc
- shell/browser/native_window_views.h
- spec-main/api-browser-window-spec.ts
Versions affected:
- 10.2.0
- 11.2.0
- 12.0.0-beta.14
Activating a key to close a window will cause a silent crash. Handling the keyboard event will lead to a nullptr dereferenced in Chromium code if the window widget has already been destroyed.
I've only been able to reproduce this on Windows. I've tested macOS as well.
Callstack when the segfault occurs:
Crash occurs in [ui/views/focus/focus_manager.cc](https://source.chromium.org/chromium/chromium/src/+/master:ui/views/focus/focus_manager.cc;l=614-615;drc=7ccffaf0933ccc647c744bf66971bcf5f33a676a)
```c++
bool FocusManager::RedirectAcceleratorToBubbleAnchorWidget(
const ui::Accelerator& accelerator) {
views::BubbleDialogDelegate* widget_delegate =
widget_->widget_delegate()->AsBubbleDialogDelegate();
```
Here's a fiddle gist to reproduce …
> fix: prevent crash when keyboard event immediately precedes calling BrowserWindow.close()

- shell/browser/net/electron_url_loader_factory.cc
- spec-main/api-protocol-spec.ts
Refs code in [`content/common/service_worker/service_worker_loader_helpers.cc`](https://source.chromium.org/chromium/chromium/src/+/5da0ed1e65305ab2c6d9de2bb4ce62f159520ba8:content/common/service_worker/service_worker_loader_helpers.cc;l=127-151).
Close #25894. It may fix it, but no reproduce case has been provided, so I can't definitively say that this fixes it.
I tried to add test coverage, but the test times out for some reason. I can see that it reaches the expected `callback(text)` after redirecting, but the promise from `executeJavaScript` never resolves. I've tried both `ajax` and `fetch` to no avail. The test was manually tested using that intercept code and acted as expected - `POST`s receiving a 302 or 303 redirects will be request the new location using `GET` rather than the …
> fix: improve redirect behavior in protocol module

- docs/api/browser-window.md
- shell/browser/api/electron_api_base_window.cc
- shell/browser/api/electron_api_base_window.h
- shell/browser/native_window.cc
- shell/browser/native_window.h
- shell/browser/native_window_mac.h
- shell/browser/native_window_mac.mm
- spec-main/api-browser-window-spec.ts
- typings/internal-electron.d.ts
I have been cleaning up `titleBarStyle`'s implementations and this is part of the refactoring. No one requested for this but it would be a good thing to fix an edge case in our APIs.
I have also added some tests for the `setWindowButtonVisibility` API.
Notes: Make `BrowserWindow.setWindowButtonVisibility` work for window with `customButtonsOnHover` titlebar style.
> fix: make setWindowButtonVisibility work for customButtonsOnHover

- BUILD.gn
Refs https://github.com/microsoft/vscode/issues/112172
Upstream issue https://bugs.chromium.org/p/chromium/issues/detail?id=1164201
Fix is based on https://bugs.chromium.org/p/chromium/issues/detail?id=1164201#c6
Notes: Increase stack size on windows x64 to 8MB
> fix: increase stack size on windows

- patches/chromium/.patches
- patches/chromium/cherry-pick-19aeffd4d93f.patch
Fix UAF in ~MultiThreadedCertVerifier
MultiThreadedCertVerifier keeps a list of
MultiThreadedCertVerifier::InternalRequests in order to eagerly reset
callbacks passed to Verify() if the MultiThreadedCertVerifier is
itself deleted (CertVerifier contract guarantees this eager reset
behavior).
In ~MultiThreadedCertVerifier we loop through this list and reset the
callbacks, but then delete the InternalRequest from the list. However,
the callbacks are allowed to own the InternalRequest, so this leads
to a UaF.
We don't need to remove the InternalRequest from the list in
~MultiThreadedCertVerifier, because we are not in charge of the
lifetime of the InternalRequest. InternalRequest can remove itself
from the list during ~InternalRequest, or MultiThreadedCertVerifier
can remove it from the list …
> chore: cherry-pick 19aeffd4d93f from chromium

- docs/tutorial/native-file-drag-drop.md
Corrects minor typo in the documentation of Native file drag and drop.
Notes: `docs: correct typo in native file drag and drop`
I am a bit intimidated by the amount of guidelines for such a big project; I'm happy to update if I missed something!
> docs: correct typo in native file drag and drop

- shell/browser/electron_browser_main_parts.cc
The call stack for one of our top crashes looks like this:
```
node::Abort (node_errors.cc:241)
node::Assert (node_errors.cc:256)
node::MakeCallback (callback.cc:226)
gin_helper::internal::CallMethodWithArgs (event_emitter_caller.cc:23)
gin_helper::EmitEvent<T> (event_emitter_caller.h:51)
gin_helper::EventEmitterMixin<T>::Emit<T> (event_emitter_mixin.h:81)
electron::api::DownloadItem::OnDownloadUpdated (electron_api_download_item.cc:115)
download::DownloadItemImpl::UpdateObservers (download_item_impl.cc:482)
content::DownloadManagerImpl::Shutdown (download_manager_impl.cc:508)
content::BrowserContext::~BrowserContext (browser_context.cc:476)
```
Full stack here: https://sentry.io/share/issue/9b030a0601b547188181b543c16ecda2/
During browser shutdown, the `DownloadManager` was being cleaned …
> fix: Shutdown crash in DownloadItem callback

- patches/chromium/.patches
- patches/chromium/cherry-pick-d866af575997.patch
Clear handlers when the base context goes away.
Previously, in BaseAudioContext::Clear() we called
GetDeferredTaskHandler().ClearHandlersToBeDeleted().  But this was
also called in DeferredTaskHandler::ContextWillBeDestroyed(), which is
called in BaseAudioContext::~BaseAudioContext().
There's no need to call this twice while handling the audio context
going away.
Manually verified that the tests from issue 1125635 and 1153658 work,
and the deadlock in issue 1136571 is gone.
Bug: 1150065, 1153658
Change-Id: Iee15c31dc637bf82d66bfd79d5238b1f80813153
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2575418
Commit-Queue: Raymond Toy <rtoy@chromium.org>
Reviewed-by: Hongchan Choi <hongchan@chromium.org>
Cr-Commit-Position: refs/heads/master@{#834265}
Notes: Security: …
> chore: cherry-pick d866af575997 from chromium

- patches/v8/.patches
- patches/v8/cherry-pick-63166010061d.patch
[liftoff][arm] Release temp registers after use
The {ParallelRegisterMove} at the end of {AtomicLoad} might need a
temporary scratch register for spilling values to the stack. Make sure
that one is available by giving up the scratch register used for the
address of the atomic access.
R=ahaas@chromium.org
Bug: chromium:1153442
Change-Id: I267c43e2193662c420f96f6683ebd4bbb0e1bca3
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/2566759
Reviewed-by: Andreas Haas <ahaas@chromium.org>
Cr-Commit-Position: refs/heads/master@{#71564}
Notes: Security: backported fix for chromium:1153442.
> chore: cherry-pick 63166010061d from v8

- patches/config.json
- patches/icu/.patches
- patches/icu/fix_apply_tzdata2020f_to_icu.patch
We got reports of wrong times displaying for customers in Yukon, Canada.
Update the timezone database in ICU to the latest version to fix this.
Notes: Updated the ICU time zone database to the latest 2020f version.
> fix: apply tzdata2020f to ICU

- docs/breaking-changes.md
- docs/tutorial/electron-versioning.md
lt may be more suitable to use SemVer than semver. For "SemVer" is the Abbreviation of "Semantic Versioning Specification"
reference: https://semver.org/
> docs: change semver to SemVer

- patches/v8/.patches
- patches/v8/cherry-pick-ffd6ff5a61b9.patch
Merged: [wasm-simd] Fix loading fp pair registers
We were incorrectly clearing the high reg from the list of regs to load.
The intention was to prevent double (and incorrect) loading - loading
128 bits from the low fp and the loading 128 bits from the high fp.
But this violates the assumption that the two regs in a pair would be
set or unset at the same time.
The fix here is to introduce a new enum for register loads, a nop, which
does nothing. The high fp of the fp pair will be tied to this nop, so as
we iterate down the reglist, we load 128 bits using the low fp, then
don't load anything for the high fp.
Bug: chromium:1161654
(cherry picked from commit 8c698702ced0de085aa91370d8cb44deab3fcf54)
Change-Id: Ib8134574b24f74f24ca9efd34b3444173296d8f1
No-Try: true …
> chore: cherry-pick ffd6ff5a61b9 from v8

- patches/chromium/.patches
- patches/chromium/cherry-pick-861253f1de98.patch
Update the restricted port list
Add ports 69, 137, 161, 554, 1719, 1720, 1723, 6566 to the restricted
ports list to match Firefox. See
https://hg.mozilla.org/mozilla-central/file/tip/netwerk/base/nsIOService.cpp.
Leave out port 10080 for now as it seems likely to cause compatibility
problems.
BUG=1148309
Change-Id: I16f9a61068dbe35334fd5ca2bf55b3ab0287df74
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2562905
Reviewed-by: David Schinazi <dschinazi@chromium.org>
Commit-Queue: Adam Rice <ricea@chromium.org>
Cr-Commit-Position: refs/heads/master@{#832169}
(cherry picked from commit c36c5078c41bd1a9e2455d747d69ac1703d977d3)
TBR=ricea@chromium.org
Change-Id: I9cc989e46ac63b3c656eb2eaed825add9b8346f8
Reviewed-on: …
> chore: cherry-pick 861253f1de98 from chromium

- patches/v8/.patches
- patches/v8/merged_compiler_mark_jsstoreinarrayliteral_as_needing_a_frame.patch
- patches/v8/merged_deoptimizer_stricter_checks_during_deoptimization.patch
[deoptimizer] Stricter checks during deoptimization
Revision: 506e893b812e03dbebe34b11d8aa9d4eb6869d89
BUG=chromium:1161357
NOTRY=true
R=mythria@chromium.org
Change-Id: I97b69ae11d85bc0acd4a0c7bd28e1b692433de80
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/2616219
Reviewed-by: Mythri Alle <mythria@chromium.org>
Cr-Commit-Position: refs/branch-heads/8.8@{#23}
Cr-Branched-From: 2dbcdc105b963ee2501c82139eef7e0603977ff0-refs/heads/8.8.278@{#1}
Cr-Branched-From: 366d30c99049b3f1c673f8a93deb9f879d0fa9f0-refs/heads/master@{#71094}
[compiler] Mark JSStoreInArrayLiteral as needing a frame state
Revision: b837e0338963611c08344cbb6f655a0abd9238c1
BUG=chromium:1161357
NOTRY=true …
> chore: cherry-pick 44d052c and 0919d75 from v8.

- shell/browser/api/electron_api_debugger.cc
Refs https://source.chromium.org/chromium/chromium/src/+/master:chrome/browser/extensions/api/debugger/debugger_api.cc;l=322-326;drc=7f6312f028d758cd23cd0d6d8df5ffaf4a5d23a7;bpv=0;bpt=1
cc @deepak1556 @zcbenz @MarshallOfSound 
Notes: none
> fix: actually clear pending requests in DevToolsAgentHost

- lib/browser/api/web-contents.ts
- lib/browser/devtools.ts
- lib/renderer/api/remote.ts
- package.json
- script/gen-filenames.ts
- spec-main/api-autoupdater-darwin-spec.ts
- spec-main/api-browser-window-spec.ts
- spec-main/api-context-bridge-spec.ts
- spec-main/api-crash-reporter-spec.ts
- spec-main/api-ipc-spec.ts
- spec-main/api-menu-spec.ts
- spec-main/api-net-log-spec.ts
- spec-main/api-protocol-spec.ts
- spec-main/api-service-workers-spec.ts
- spec-main/api-session-spec.ts
- spec-main/api-shell-spec.ts
- spec-main/api-web-contents-spec.ts
- spec-main/api-web-request-spec.ts
- spec-main/chromium-spec.ts
- spec-main/crash-spec.ts
- spec-main/extensions-spec.ts
- spec-main/modules-spec.ts
- spec-main/visibility-state-spec.ts
- spec-main/webview-spec.ts
- tsconfig.json
- typings/internal-ambient.d.ts
- yarn.lock
Allows removing copied `WeakRef` / `FinalizationRegistry` declarations.
Addresses [resolve’s Parameters Are No Longer Optional in Promises](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-1.html#resolves-parameters-are-no-longer-optional-in-promises)
> chore: update to latest TypeScript, which has built-in WeakRef declarations

- patches/chromium/.patches
- patches/chromium/cherry-pick-79440c3a0675.patch
Fail gracefully if |parameter| object has an invalid array topology
AudioWorkletProcessor::CopyParamValueMapToObject() assumed the array
topology is always valid (DCHECK), but if the user code actively mangles
the parameter descriptor getter the array to return invalid content
this assumption becomes invalid.
The fix is to fail gracefully when the object type or the array content
is not correct.
Bug: 1151069
Test: The repro case does not reproduce any more after 1 hour run.
Change-Id: I3f8decd3721e9b00ba201e2f76751e4bc941e05d
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2569788
Reviewed-by: Raymond Toy <rtoy@chromium.org>
Commit-Queue: Hongchan Choi <hongchan@chromium.org>
Cr-Commit-Position: refs/heads/master@{#834503}
Notes: Security: backported fix for …
> chore: cherry-pick 79440c3a0675 from chromium

- patches/chromium/.patches
- patches/chromium/cherry-pick-da9b5ec032ad.patch
viz: Destroy |gpu_memory_buffer_factory_| on IOThread
|gpu_memory_buffer_factory_| weak pointers are checked on the
IOThread.
Weak pointers should be invalidated on the same thread that
checks them.
This CL moves the destruction of |gpu_memory_buffer_factory_|
on the IOThread to avoid possible use after free issues.
Bug: 1152645
Change-Id: I0d42814f0e435a3746728515da1f32d08a1252cf
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2563077
Commit-Queue: Daniele Castagna <dcastagna@chromium.org>
Reviewed-by: Andres Calderon Jaramillo <andrescj@chromium.org>
Cr-Commit-Position: refs/heads/master@{#836827}
Notes: Security: backported fix for 1152645.
> chore: cherry-pick da9b5ec032ad from chromium

- patches/config.json
- patches/sqlite/.patches
- patches/sqlite/fix_a_problem_handling_sub-queries_with_both_a_correlated_where.patch
Backport https://sqlite.org/src/info/f62f983b56623f0e.
User & Date: dan on 2020-12-22 16:23:29
Fix a problem handling sub-queries with both a correlated WHERE clause and a "HAVING 0" clause where the parent query is itself an aggregate.
Notes: backported the fix to CVE-2021-21120 from sqlite.
> chore: cherry-pick f62f983b56623f0e from sqlite.

- spec-main/api-service-workers-spec.ts
Refs https://github.com/electron/electron/issues/26043.
By using a new uuid for each test we should be able to reduce the flakes in ServiceWorker tests.
Notes: none
> test: use new uuid for each ServiceWorker test

- shell/browser/native_window_mac.mm
Closes https://github.com/electron/electron/issues/27283.
Refs https://github.com/electron/electron/pull/26901.
Previous we early-exited subsequent logic [here](https://github.com/electron/electron/pull/26901/files#diff-148ef9a1a6f049d9fef8c6272a4871d89315f8fc6cd80dc2d41a28b21b29184cL1714-L1715) for non-normal `titleBarStyle`s, but this change made it such that `SetMaximizable(false);` would be called for `hidden` and `hiddenInset` which would cause those styles to lose their zoom buttons. Fix this by moving that line into other associated logic exclusive to `normal` and `customButtonsOnHover` styles.
cc @jkleinsc @zcbenz  
Notes: Fixed an issue where the zoom button was missing for windows with `titleBarStyle: hiddenInset` on macOS.
> fix: hiddenInset missing maximize button

- shell/browser/api/electron_api_base_window.cc
- shell/browser/api/electron_api_base_window.h
- shell/common/api/electron_api_native_image.cc
- shell/common/api/electron_api_native_image.h
- spec-main/api-browser-window-spec.ts
Fixes #27303.
Don't throw exceptions in the BrowserWindow constructor when fed an invalid image.
This change adds a new parameter to TryConvert that specifies what to do on error -- to throw or to warn. The default is to throw.
This change also adds a new protected method SetIconImpl() that is basically the old SetIcon() + that new parameter. This was added instead of appending a switch to SetIcon() because the latter is directly callable as public API and it doesn't make sense to expose this switch. SetIcon() is now a one-liner that calls SetIconImpl() with 'throw' behavior. The BrowserWindow constructor calls SetIconImpl() with 'warn' behavior.
CC @codebytere 
Notes: fix regression that crashed Electron when processing an invalid icon.
> fix: don't throw on bad icons in BrowserWindow constructor

- shell/browser/api/electron_api_screen.cc
- shell/browser/api/message_port.cc
- shell/browser/extensions/electron_extension_system.cc
- shell/browser/net/url_pipe_loader.cc
- shell/browser/ui/gtk/app_indicator_icon.cc
- shell/common/api/electron_api_clipboard.cc
- shell/common/gin_converters/callback_converter.h
- shell/common/gin_helper/callback.h
- shell/common/gin_helper/wrappable.h
- shell/renderer/electron_autofill_agent.cc
Replace deprecated `base::Bind()` with explicit `base::BindOnce()` / `base::BindRepeating()`.
> refactor: replace base::Bind() with base::BindOnce() / base::BindRepeating()

- lib/renderer/web-view/web-view-impl.ts
- spec-main/webview-spec.ts
- spec/fixtures/pages/webview-trusted-types.html
Fixes #27211
Before:
After:
Notes: Fixed `<webview>` not working with Trusted Types.
> fix: <webview> not working with Trusted Types

- lib/renderer/security-warnings.ts
- spec-main/security-warnings-spec.ts
- typings/internal-ambient.d.ts
Fixes #27211
Need to use `eval('')` instead of `new Function('')` due to a bug in [Trusted Types for function constructor](https://github.com/w3c/webappsec-trusted-types/wiki/Trusted-Types-for-function-constructor).
Before:
After:
Notes: Fixed CSP with `unsafe-eval` detection with Trusted Types.
> fix: CSP with unsafe-eval detection with Trusted Types

- patches/chromium/.patches
- patches/chromium/cherry-pick-3ca3d70c7af5.patch
Minor UI logic changes to prevent a UAF bug when starting tab capture.
See discussion in crbug 1155426 for details. Changes:
MediaStreamCaptureIndicator::UIDelegate: Ignore multiple calls to
OnStarted().
TabSharingUIViews: Unconditionally execute clean-up tasks in destructor.
Bug: 1155426
Change-Id: I392fba38118ce51744ba36b4dec19ebfe39f1fbe
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2581028
Reviewed-by: Marina Ciocea <marinaciocea@chromium.org>
Commit-Queue: Yuri Wiitala <miu@chromium.org>
Cr-Commit-Position: refs/heads/master@{#835736}
Notes: Security: backported fix for 1155426.
> chore: cherry-pick 3ca3d70c7af5 from chromium

- patches/chromium/.patches
- patches/chromium/cherry-pick-4794770cf175.patch
Correctly handle detach during (de)compression
Sometimes CompressionStream and DecompressionStream enqueue multiple
output chunks for a single input chunk. When this happens, JavaScript
code can detach the input ArrayBuffer while the stream is processing it.
This will cause an error when zlib tries to read the buffer again
afterwards.
To prevent this, buffer output chunks until the entire input chunk has
been processed, and then enqueue them all at once.
Bug: 1151298
Change-Id: I03fca26fc641d54b09067e3994b76ee8efca6839
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2567539
Commit-Queue: Adam Rice <ricea@chromium.org>
Cr-Commit-Position: refs/heads/master@{#833659}
Notes: Security: backported fix for 1151298.
> chore: cherry-pick 4794770cf175 from chromium

- default_app/index.html
- default_app/preload.ts
> chore: enable Trusted Types in default app

- shell/browser/api/electron_api_web_contents.cc
- shell/browser/api/electron_api_web_contents.h
Fix regression introduced by #27225
> build: fix build with enable_printing=false

- lib/renderer/security-warnings.ts
- spec-main/security-warnings-spec.ts
- typings/internal-ambient.d.ts
Backport of #27446
Notes: Fixed CSP with `unsafe-eval` detection with Trusted Types.
> fix: CSP with `unsafe-eval` detection with Trusted Types

- patches/chromium/.patches
- patches/chromium/cherry-pick-d74ba931c4b7.patch
content-visibility: Don't adjust position of a locked hittest result node.
This patch ensures that if we have a hittest result that has a locked
node, we don't try to recurse into its subtree. This can happen when we
do a PositionWithAffinity check.
R=chrishtr@chromium.org
(cherry picked from commit 8483cf6944e38203c3b247163c54cfa105e89c56)
(cherry picked from commit 3f7b67374a1121b6756ccfd2e4e414987f167489)
Bug: 1162131
Change-Id: I357bd7032c6c2b6c9405bf26c49a36bda22d6a0d
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2611453
Reviewed-by: Chris Harrelson <chrishtr@chromium.org>
Commit-Queue: vmpstr <vmpstr@chromium.org>
Cr-Original-Original-Commit-Position: refs/heads/master@{#840727}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2618603 …
> chore: cherry-pick d74ba931c4b7 from chromium

- patches/chromium/.patches
- patches/chromium/ots_backport_maxp_sanitization.patch
- patches/chromium/ots_backport_of_glyf_guard_access_to_maxp_version_1_field.patch
====
[OTS] Backport maxp sanitization
Backport [1] to perform additional sanitization on maxp values.
[1] https://github.com/khaledhosny/ots/pull/227
(cherry picked from commit 6d0e7d799a46336c6bc297d4075a27dd0e7c235d)
Bug: 1153329
Change-Id: I4bc2288574802559f6c9c67a52b6dfcd8cc7467a
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2588339
Auto-Submit: Dominik Röttsches <drott@chromium.org>
Commit-Queue: Kenichi Ishibashi <bashi@chromium.org>
Reviewed-by: Koji Ishii <kojii@chromium.org>
Reviewed-by: Kenichi Ishibashi <bashi@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#836679}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2620800
Commit-Queue: Dominik Röttsches <drott@chromium.org>
Commit-Queue: Anders Hartvoll Ruud …
> chore: cherry-pick 4af9de9806 and 115eccc0c6 from chromium.

- docs/api/ipc-renderer.md
- docs/api/web-contents.md
As per feedback on Appzi, this removes the copy that specifies the version number where passing DOM objects over IPC is deprecated, since the feature was removed back in Electron 9.
Notes: none
> docs: update verb tenses for structured clone notes

- docs/breaking-changes.md
- shell/browser/web_contents_preferences.cc
- shell/renderer/api/electron_api_context_bridge.cc
- shell/renderer/api/electron_api_context_bridge.h
- shell/renderer/api/electron_api_web_frame.cc
- spec-main/api-context-bridge-spec.ts
Fixes #25806
As per the original deprecation message, enabling `worldSafeExecuteJavaScript` by default in Electron 12.  Also plans its removal for Electron 14.
In order to remain backwards-compatible (in regards to promise support and exception handling) I moved the copy-value logic to use the ctx bridge to support non-clonable types and also updated the ctx bridge logic to better handle exception messages
Notes: Changed the default value of `worldSafeExecuteJavaScript` to be `true`.
> feat: enable world safe JS by default

- docs/README.md
The docs README is manually generated, and doesn't include the `contextBridge` API. 🙃 
This PR fixes the problem!
> docs: add missing contextBridge API to README

- lib/common/asar.js
- spec/asar-spec.js
Backport of #26865
Notes: Fixed `readdir`/`readdirSync` (w/ `withFileTypes`) failing on a deep directory within archive.
> fix(asar): readdir(withFileTypes) fails on deep directory

- BUILD.gn
- electron_paks.gni
- shell/browser/extensions/api/resources_private/resources_private_api.cc
- shell/browser/extensions/electron_component_extension_resource_manager.cc
- spec-main/chromium-spec.ts
Refs https://chromium-review.googlesource.com/c/chromium/src/+/2614504.
Died in https://github.com/electron/electron/commit/adf0a7354369a1d0387b66ed547b59cfbee185d8.
Tested by adding `mainWindow.loadURL('http://www.africau.edu/images/default/sample.pdf')` to an arbitrary Fiddle gist.
After:
Notes: Fixed PDF viewer failing to load resources.
> fix: pdf viewer missing resources

- docs/development/build-instructions-macos.md
We are now using Xcode 12.2 / macOS SDK 11.0
https://github.com/electron/electron/blob/f24348485a1a938f7e3173e0a94bee6e29b18104/.circleci/config.yml#L86-L98
> docs: update Xcode / macOS SDK version in build-instructions-macos.md

- patches/chromium/.patches
- patches/chromium/layoutng_fix_an_incorrect_cache-hit_for_line_boxes.patch
LayoutNG: Fix an incorrect cache-hit for line boxes
If an IFC contains an item for an orthogonal writing-mode root,
NGFragmentItems::DirtyLinesFromNeedsLayout() failed to mark it as dirty
because NeedsLayout flag for the item was already cleared in the
ComputeMinMaxSizes() step.
This CL avoids this issue by assuming orthogonal writing-mode roots
dirty regardless of NeedsLayout flag.
(cherry picked from commit 21976a78429ccd8325acb00b41b4120271580bfb)
Bug: 1125870, 1147357
Change-Id: I603bdd76f9015fbcde46da8e09fb6757b4b0222b
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2544326
Reviewed-by: Koji Ishii <kojii@chromium.org>
Commit-Queue: Kent Tamura <tkent@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#828237}
Reviewed-on: …
> chore: cherry-pick 442703fe44 from chromium.

- spec-main/extensions-spec.ts
Fixes failures on 
```
chrome extensions chrome.webRequest onBeforeRequest can cancel http requests - can cancel http requests
```
introduced by https://github.com/electron/electron/commit/db08f08b88c7dca7b03a6d6ebe1e33be1cb473c9.
see https://github.com/electron/electron/pull/27513
Notes: none
> spec: fix failing http spec

- README.md
We're still telling people what to do when you're installing Electron < 2. Maybe we shouldn't!
Notes: none
> docs: Update Readme, don't mention Electron < 2

- patches/chromium/.patches
- patches/chromium/cherry-pick-0d2bf89e15cc.patch
Observe ProcessManager shutdowns from KeepAliveImpl.
ExtensionRegistry uses the underlying BrowserContext for incognito
contexts. Thus, for incognito uses, the ProcessManager can be destroyed
without the KeepAliveImpl being notified. Observe ProcessManager
shutdowns directly to ensure KeepAliveImpls are cleaned up when a
ProcessManager is shut down.
[Substituted ScopedObserver for base::ScopedObservation since the latter
was introduced in 88]
(cherry picked from commit 5a55fe16e633dd02e3c40e513acabf4324bb6318)
(cherry picked from commit c2bf2463fbeff3959ea1998a4f3ae82dd648b56c)
Bug: 1149177
Change-Id: I39a0cf54bcf8cf0d58e36560935b8d2f79399cd2
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2548585
Auto-Submit: Sam McNally <sammc@chromium.org>
Commit-Queue: Ben Wells …
> chore: cherry-pick 0d2bf89e15cc from chromium

- patches/v8/.patches
- patches/v8/merged_wasm_liftoff_fix_register_usage_for_i64_addi.patch
Merged: [wasm][liftoff] Fix register usage for i64_addi
The arm implementation made the assumption that the {lhs} and {dst}
registers are either the same, or there is no overlap. This assumption
does not hold.
ia32 on the other hand has a lot of complicated logic (and unnecessary
code generation) for different cases of overlap.
This CL fixes the arm issue *and* simplifies the ia32 logic by making
the arm assumption hold, and using it to eliminate special handling on
ia32.
R=​thibaudm@chromium.org
(cherry picked from commit 89ca48c907e25ef94a135255092c4e150654c4fc)
Bug: chromium:1146861
Change-Id: I96c4985fb8ff710b98e009e457444fc8804bce58
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/2584242
Reviewed-by: Thibaud Michaud …
> chore: cherry-pick eddb823309 from v8.

- shell/renderer/api/electron_api_context_bridge.cc
Refs https://chromium-review.googlesource.com/c/v8/v8/+/2574699.
Ensure that the `contextBridge` doesn't try to serialize `WasmMemoryObject`s as plain objects.
Notes: Fixed an issue where `contextBridge` might incorrectly try to serialize some WebAssembly objects.
> fix: dont try to serialize WasmModuleObjects

- lib/browser/guest-window-manager.ts
- spec-main/fixtures/snapshots/native-window-open.snapshot.txt
- spec-main/fixtures/snapshots/proxy-window-open.snapshot.txt
- spec-main/guest-window-manager-spec.ts
Closes #27036
This PR restores the behavior where the native window.open() parameter _windowName_, as named in the [native window.open() documentation](https://developer.mozilla.org/en-US/docs/Web/API/Window/open#parameters) or _frameName_ in the [Electron documentation](https://www.electronjs.org/docs/api/window-open#windowopenurl-framename-features), is not used by default to set the window title. Previously, the title defaulted to use this parameter, caused by a regression occurring in https://github.com/electron/electron/pull/19703. Now the _windowName_ parameter is no longer used by default.
Notes: Fixed native window.open() to not use _windowName/frameName_ as title by default
> fix: replace default frameName title with null check

- lib/asar/fs-wrapper.ts
- lib/browser/api/menu.ts
- lib/browser/api/touch-bar.ts
- lib/browser/api/web-contents.ts
- lib/browser/guest-view-manager.ts
- lib/browser/guest-window-manager.ts
- lib/browser/guest-window-proxy.ts
- lib/browser/remote/server.ts
- lib/renderer/api/context-bridge.ts
- lib/renderer/init.ts
- lib/renderer/security-warnings.ts
- lib/renderer/web-view/web-view-attributes.ts
- lib/renderer/web-view/web-view-element.ts
- spec-main/api-context-bridge-spec.ts
- typings/internal-ambient.d.ts
- typings/internal-electron.d.ts
Improves type safety. `any` was used 377 times in lib, lowered to 333 times.
> chore: remove bunch of usages of any

- shell/browser/ui/views/menu_bar.cc
- shell/browser/ui/views/menu_bar.h
- shell/browser/ui/views/submenu_button.cc
- shell/browser/ui/views/submenu_button.h
Fix https://github.com/electron/electron/issues/26717.
Some recent changes in Chromium made `views::Button::SetCallback` stop working in `views::MenuButton`, pass the callback in constructor to make the callback work again. Also this is a better tested code path in Chromium and we will have much less chance running into problems with it.
Notes: Fix menubar not clickable on Windows and Linux.
> fix: pass button callback in constructor

- docs/api/browser-window.md
- filenames.gni
- shell/browser/native_window.h
- shell/browser/native_window_mac.h
- shell/browser/native_window_mac.mm
- shell/browser/ui/cocoa/electron_ns_window_delegate.mm
- shell/browser/ui/cocoa/window_buttons_view.h
- shell/browser/ui/cocoa/window_buttons_view.mm
This PR cleans up the implementations of titleBarStyle, by making them share the same core implementation that uses a custom buttons view.
With this PR:
1. 3 unique code paths of titleBarStyle are merged to one, with lots of hacks removed.
2. The weird behaviors of `hiddenInset` titleBarStyle are gone (will be explained bellow).
3. It becomes possible to toggle the rounded corners of frameless window.
4. It becomes possible to precisely control the traffic lights.
5. It becomes possible to dynamically change between different titleBarStyles.
As you can see in the screenshots bellow, with current implementation of `hiddenInset`, the titlebar under fullscreen has to be either a tall titlebar with aligned traffic lights and no title, or a tall titlebar that has traffic lights and title …
> fix: clean up implementations of titleBarStyle

- shell/renderer/api/electron_api_web_frame.cc
- shell/renderer/electron_render_frame_observer.cc
- shell/renderer/electron_renderer_client.cc
- shell/renderer/electron_renderer_client.h
- shell/renderer/electron_sandboxed_renderer_client.cc
- shell/renderer/electron_sandboxed_renderer_client.h
- shell/renderer/renderer_client_base.h
This code was leftover from the old JS extensions implementation which was removed in #23340
Notes: none
> refactor: remove unused extension content script code

- shell/browser/extensions/electron_extension_loader.cc
- spec-main/extensions-spec.ts
- spec-main/fixtures/extensions/load-error/manifest.json
A segfault occurs when an extension fails to load.
I forgot to check for a nullptr before writing an extension pref in #22655
Notes: Fixed crash when extension fails to load.
> fix: crash when loadExtension fails

- docs/api/ipc-main.md
Include information in ipcMain documentation about ipcMain.handle() error handling and workaround provided by @nornagon included in issue #24427.
Notes: none
> docs: Update ipcMain.handle() docs in ipc-main.md for error-handling details

- docs/api/browser-window.md
- shell/browser/api/electron_api_base_window.cc
- shell/browser/native_window.h
- shell/browser/native_window_mac.h
- shell/browser/native_window_mac.mm
- shell/browser/native_window_views.cc
- shell/browser/native_window_views.h
Allows calls to win.SetVisibleOnAllWorkspaces to skip transforming the process type. This allows us to use the same behavior found in Electron versions 9.2.1 and under, which is useful for "pinning" an app to a workspace/desktop, without causing other issues related to process transformation. 
This PR adds optional backwards-compatibility with 9.2.1 and under, while maintaining the same default behavior.
Fixes: (#27101)
Process transformation introduced in this PR: [PR #24956](https://github.com/electron/electron/pull/24956)
Stakeholders:
@codebytere 
@zcbenz 
@MarshallOfSound 
Notes: Allowed skipping process type transformation in win.SetVisibleOnAllWorkspaces on macOS.
> feat: add option to not transform processes on win.SetVisibleOnAllWorkspaces

- shell/browser/ui/x/window_state_watcher.cc
- shell/browser/ui/x/window_state_watcher.h
A minor cleanup to the X11 window state watcher: We're already precaching _NET_WM_STATE but now use other atoms too, so let's precache them. Atoms are X11 versions of the same idea as interned strings & Symbols -- they never change their values, and so precaching & holding forever is safe. This avoids unnecessary string lookups when processing X11 events.
The code branches that use these atoms are not reached as often as the ones using _NET_WM_STATE, so this is a smaller win than  83d5833 [was](https://github.com/electron/electron/pull/22706#issuecomment-600364289).
No particular stakeholder; any reviewer welcomed
Notes: none
> refactor: precache atoms in window-state-watcher

- .circleci/config.yml
- BUILD.gn
This fixes the buildflags.h generation issue that happened in the roll here:  #27111.
That roll updated GN which included this change:
https://gn.googlesource.com/gn/+/0ae75f90df148d19083055b29c4c940b136904b4
In order to resolve the issue we needed to include 
"//base" and "//electron/buildflags" in the deps for electron_app because otherwise gn thinks that there are just data dependencies and won't properly generate buildflags.h
Thanks to @codebytere and @nornagon for helping out on this.
Notes: none
> build: fix buildflags.h generation on macos

- docs/tutorial/dark-mode.md
> docs: fix `source` typo

- patches/chromium/.patches
- patches/chromium/cherry-pick-5c7ad5393f74.patch
Mac a11y: Use the keyboard focusable element for
NSAccessibilityTextChangeElement
When setting the NSAccessibilityTextChangeElement property for
NSAccessibilitySelectedTextChangedNotifications, use the keyboard
focusable element instead of the element that has the focus side of the
text selection. Using the latter, when the element is an empty group,
VoiceOver will focus the containing Web View (when using the VO
cursor follows keyboard focus setting). This makes it impossible to use
the down keyboard key to move past these empty nodes.
VoiceOver cursor" setting in contenteditable nodes.
AX-Relnotes: Fix a bug with the "Synchronize keyboard focus and
Bug: 952922
Change-Id: I3627936726f89b01132c32bd5d83758fc7c3dac4
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/26426 …
> fix: cherry-pick 5c7ad5393f74 from chromium

- patches/chromium/.patches
- patches/chromium/cherry-pick-5902d1aa722a.patch
Use the native combobox a11y role more often on MacOS
Instead of mapping the ARIA combobox role to other roles on MacOS,
always use it unless it is applied to a multiline edit field. This
matches the specified behavior and other browsers.
These were originally mapped to other roles because of VoiceOver
failures that have been fixed with other changes.
Bug: 1125165
Change-Id: I26b8ccb006c15d6329da1c29193640f529fab781
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2611093
Reviewed-by: Dominic Mazzoni <dmazzoni@chromium.org>
Commit-Queue: Martin Robinson <mrobinson@igalia.com>
Cr-Commit-Position: refs/heads/master@{#844021}
Notes: Backported fix for https://crbug.com/1125165.
> fix: cherry-pick 5902d1aa722a from chromium

- shell/browser/native_window_mac.mm
The buttonsView should be restored before leaving fullscreen instead of after leaving fullscreen, otherwise the traffic light buttons would flicker. This is a regression introduced by https://github.com/electron/electron/pull/27489.
> fix: avoid flicker when leaving fullscreen in frameless window

- patches/v8/.patches
- patches/v8/cherry-pick-36abafa0a316.patch
[Merged ][wasm] PostMessage of Memory.buffer should throw
PostMessage of an ArrayBuffer that is not detachable should result
in a DataCloneError.
TBR=gdeepti@chromium.org
(cherry picked from commit dfcf1e86fac0a7b067caf8fdfc13eaf3e3f445e4)
Bug: chromium:1170176, chromium:961059
No-Try: true
Change-Id: Ife852df032841b7001375acd5e101d614c4b0771
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/2674169
Reviewed-by: Zhi An Ng <zhin@chromium.org>
Commit-Queue: Zhi An Ng <zhin@chromium.org>
Cr-Commit-Position: refs/branch-heads/8.8@{#30}
Cr-Branched-From: 2dbcdc105b963ee2501c82139eef7e0603977ff0-refs/heads/8.8.278@{#1}
Cr-Branched-From: 366d30c99049b3f1c673f8a93deb9f879d0fa9f0-refs/heads/master@{#71094}
Notes: Security: backported fix for …
> chore: cherry-pick 36abafa0a316 from v8

- shell/browser/native_window_views_win.cc
Electron currently has a Windows-specific workaround, to help a minimized window correctly restore itself to the closest display (rather than the default left-most display). We hijack and reset the position of the window during the restore operation.
However, this workaround was incorrectly catching windows that were not just minimized, but closed; because the closed window also reported it's `last_normal_placement_bounds` as empty, similar to a minimized window. When this closed window is "restored", it is unresponsive and the affected app has to be hard quit.
This PR adds a check to make sure the window is minimized, not just hidden, before performing the restore position operation.
Fixes #26899 
Notes: Fixes native window freeze on Windows when Electron app is sent to tray and external …
> fix: do not run display check on "closed" windows in tray

- shell/renderer/api/context_bridge/object_cache.cc
base::LinkedList does not delete its members on destruction. We need to manually ensure the linkedlist is empty when the ObjectCache is destroyed.
Fixes #27039
Notes: Fixed memory leak when sending non-primitives over the context bridge
> fix: clean up base::LinkedList in context_bridge::ObjectCache

- shell/browser/electron_browser_main_parts.cc
- shell/browser/electron_browser_main_parts.h
- shell/common/gin_helper/trackable_object.cc
- shell/common/gin_helper/trackable_object.h
This fixes a memory leak in TrackableObject (of which BaseWindow and
BrowserWindow are the only subclasses). It was registering an exit-time
destructor for every TrackableObject, and never removing them. This is replaced
by the gin_helper::CleanedUpAtExit helper class, which removes the destructor
from the list when the object is destroyed.
Ref #21586.
Notes: Fixed a memory leak when creating BrowserWindows.
> fix: memory leak in TrackableObject

- shell/browser/api/electron_api_base_window.cc
fixed typo.
```
reseting -> resetting
```
notes: none
> chore: fix typo in electron_api_base_window.cc

- patches/chromium/.patches
- patches/chromium/fix_svg_filter_data_invalidation_for_empty_containers.patch
This is a backport of an upstream fix that is already in Electron v12.0.0-beta.16 and newer.
Downstream issue:
https://github.com/microsoft/vscode/issues/112693
In a VS Code, an SVG produced by a notebook wasn't rendering on time.
Diff to backport from Chromium:
https://chromium.googlesource.com/chromium/src/+/15a8dbe6efe865eaaae63b48b6a3bacd3420a89b%5E%21/
There was an SVG rendering glitch in Chromium where invalidate wasn't getting called in some cases.
Notes: Fix svg with filter content not being rendered
> fix: Backport SVG filter invalidation fix from Chromium

- patches/node/.patches
- patches/node/darwin_libuv_use_posix_spawn.patch
Spawning child processes in an Electron application with a hardened runtime has become slow in macOS Big Sur.
This patch is a squashed version of https://github.com/libuv/libuv/pull/3064, and should be removed when the libuv PR is merged.
Fixes: https://github.com/libuv/libuv/issues/3050
Fixes: https://github.com/electron/electron/issues/26143
PR-URL: https://github.com/libuv/libuv/pull/3064
@jpcanepa: authoring the libuv patch
@davidzech @marcello3d @srubin: identifying the underlying Electron issue
@marcello3d: creating the [Electron repro](https://github.com/descriptinc/electron-spawn-perf-bug)
@bnoordhuis: assistance with libuv
@deepak1556: thanks for the [libuv repro](https://github.com/deepak1556/libuv-spawn)
@erickzhao: thanks for the support in the Electron Discord & assisting …
> perf: patch libuv to use posix_spawn on macOS

- package.json
- shell/browser/native_browser_view_mac.mm
Closes https://github.com/electron/electron/issues/27378.
In an `NSView`, `drawRect` draws the view’s image within the specified rectangle. It's invoked _very_ frequently and as such performance is paramount. As calls to `drawRect` need to traverse the whole responder chain, we were adding a costly [`getenv`](https://pubs.opengroup.org/onlinepubs/009695399/functions/getenv.html) call to every invocation, which created a rendering flicker. This was debug-only, so we should not override it at all, but keep it commented out.
See https://developer.apple.com/documentation/appkit/nsview/1483686-drawrect for more details.
Notes: Fixed an occasional white flicker present when rendering BrowserViews in close succession.
> fix: BrowserView rendering flicker

- shell/browser/api/electron_api_web_frame_main.cc
- shell/browser/api/electron_api_web_frame_main.h
fixes #26824
Changes `WebFrameMain` to inherit from `gin_helper::Pinnable` so we can keep it in-memory while multiple gin handles to it exist.
This fixes the issue seen in #26824 in which `webContents.mainFrame` would sometimes return `undefined` (and all the flaky tests with it). However, I'm pretty new to the behaviors of v8's garbage collection and I only half-understand why this works. Here's what I think is going on:
1. We request a gin handle to a new `WebFrameMain` instance.
2. We request another gin handle to the existing `WebFrameMain` instance.
3. The first `WebFrameMain` instance gets garbage collected and the memory is freed.
4. We attempt to access the second handle to the now garbage collected `WebFrameMain` instance.
5. We get `undefined` as the value.
So we need to keep …
> fix: early GC of WebFrameMain instances

- BUILD.gn
Recently macos release builds started failing with `fatal error: 'electron/fuses.h' file not found`:
https://app.circleci.com/pipelines/github/electron/electron/35682/workflows/2c29722d-5388-481c-aef8-3e8697374bdd/jobs/782479
https://app.circleci.com/pipelines/github/electron/electron/35679/workflows/e16ac8a7-6ec8-4417-aa8d-00106befd854/jobs/782308
I believe this may be related to #27579 so I applied the same fix we did there. 
Notes: none.
> build: make sure fuses.h gets generated for macos builds

- docs/api/app.md
- docs/api/web-contents.md
- shell/browser/api/electron_api_web_contents.cc
This adds extra information that could be helpful in debugging renderer process
exits.
Notes: Added `exitCode` to `render-process-gone` details.
> feat: add exit code to render-process-gone details

- docs/api/browser-window.md
- shell/browser/native_window_mac.mm
- shell/common/options_switches.cc
- shell/common/options_switches.h
Add an option to remove rounded corners of frameless windows on macOS, close https://github.com/electron/electron/issues/414.
Notes: Add `roundedCorners` option for `BrowserWindow`.
> feat: add roundedCorners option for BrowserWindow

- lib/renderer/api/remote.ts
- lib/renderer/init.ts
- lib/renderer/ipc-renderer-internal-utils.ts
- lib/renderer/ipc-renderer-internal.ts
- lib/renderer/web-view/guest-view-internal.ts
- lib/renderer/window-setup.ts
- lib/sandboxed_renderer/init.ts
- typings/internal-electron.d.ts
This is a behavioral no-op since all existing listeners were using
the "onMessageFromMain" API. This refactor just makes it harder to accidentally
add a new usage of the insecure version that didn't check for "from main".
cc @miniak
Notes: none
> refactor: only allow internal messages from the main process

- shell/browser/api/electron_api_web_contents.cc
Move it from LoadURL to RenderViewCreated which is present
in all window creation cases and is called early enough to be
relevant from UX perspective but after RenderWidgetHostView
is already present.
Notes: Fixed background color not being applied for child windows created by native window.open path.
> fix: set WebContents background color ubiquitously

- patches/node/fix_comment_out_incompatible_crypto_modules.patch
- spec/node-spec.js
Closes https://github.com/electron/electron/issues/27673.
We disabled the contents of one of the Diffie-Hellman constructors owing to BoringSSL compatibilities, but I've determined that the functionality itself is compatible; it's just the error throwers that aren't. As such, we can specifically remove those and restore `crypto.createDiffieHellman()` functionality. 
Tested with https://gist.github.com/SchoofsKelvin/90f78f8aeffa04e344bf8dbd3ade4961.
Notes: Fixed a crash when calling `crypto.createDiffieHellman()` with certain parameters.
> fix: crash in crypto.createDiffieHellman

- docs/tutorial/message-ports.md
This adds a guide page explaining some details about how MessagePorts work in
Electron and some example use-cases.
Another example I'd like to add is that of "ports as capabilities", i.e. as a
security feature--if you have the MessagePort, you're allowed to use the
feature. That might be a bit abstract though, and I'm not aware of any apps
using that strategy in the wild.
Notes: none
> docs: MessagePorts guide

- docs/api/service-workers.md
- shell/app/electron_content_client.cc
- shell/browser/api/electron_api_service_worker_context.cc
- shell/browser/api/electron_api_service_worker_context.h
- shell/renderer/extensions/electron_extensions_renderer_client.cc
- shell/renderer/renderer_client_base.cc
- shell/renderer/renderer_client_base.h
- spec-main/extensions-spec.ts
- spec-main/fixtures/extensions/mv3-service-worker/background.js
- spec-main/fixtures/extensions/mv3-service-worker/manifest.json
Manifest V3 (MV3) has become [generally available in M88 Beta.](https://blog.chromium.org/2020/12/manifest-v3-now-available-on-m88-beta.html)
This adds the bare minimum in order to run MV3's new service workers meant to replace MV2's background processes.
A new `registration-completed` event is added to `Session.serviceWorkers` for testing whether extension service workers register properly.
cc @electron/wg-api 
Notes:
* Added support for registering Manifest V3 extension service workers.
* Added 'registration-completed' event to `ServiceWorkers`.
> feat: support registering MV3 extension service workers

- patches/config.json
- patches/skia/.patches
- patches/skia/cherry-pick-b0d3d3e85fa6.patch
Fix DrawEdgeAAQuad degenerate issue where 3D points don't correctly project to 2D points.
Bug: chromium:1162942
Change-Id: Idc1dcb725ff9eae651b84de2fe792b188dcd1c1b
Reviewed-on: https://skia-review.googlesource.com/c/skia/+/354671
Commit-Queue: Brian Salomon <bsalomon@google.com>
Reviewed-by: Michael Ludwig <michaelludwig@google.com>
(cherry picked from commit 7656c4b7e89b4ff00480a6d7a8a19e3fd0e5c86e)
Reviewed-on: https://skia-review.googlesource.com/c/skia/+/360376
Reviewed-by: Brian Salomon <bsalomon@google.com>
Notes: Security: backported fix for chromium:1162942.
> chore: cherry-pick b0d3d3e85fa6 from skia

- patches/chromium/.patches
- patches/chromium/cherry-pick-9afec1792cfc.patch
[LTS-M86 Merge] Move FontPreloadManager to Oilpan
Currently, TimerBase cannot correctly track the lifetime of objects
embedded in GC-ed objects, like FontPreloadManager which is embedded in
Document. This causes some memory safety issues.
This patch moves FontPreloadManager to Oilpan to avoid the issue.
(cherry picked from commit d31bbf2910ee44e4a206d926ddae6827d16a2754)
(cherry picked from commit cdab130053839ffae4a02d00812c1c3a0ecf01bd)
Bug: 1154965
Change-Id: I490b416abc6a997034baaa7994cd3a50bca7e055
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2611755
Reviewed-by: Kentaro Hara <haraken@chromium.org>
Commit-Queue: Xiaocheng Hu <xiaochengh@chromium.org>
Cr-Original-Original-Commit-Position: refs/heads/master@{#841039}
Reviewed-on: …
> chore: cherry-pick 9afec1792cfc from chromium

- patches/chromium/.patches
- patches/chromium/cherry-pick-df438f22f7d2.patch
[navigation] Fix navigation request reset logic
Do not delete navigation request which has started upon receiving
notification about beforeunload dialog being cancelled, as a) this
navigation request is not waiting for beforeunload and b) it might have
been this navigation request which canceled this beforeunload dialog.
* content/browser/frame_host/*
In ToT files the affected under frame_host directory are moved to
renderer_host dir. Applied patch to frame_host, no further conflicts.
R=​alexmos@chromium.org
BUG=1161705
(cherry picked from commit 23c110b5b81dc401ded5d4dcecfab65d5d88fdfa)
(cherry picked from commit 87550e04d9fed4bbedff4546f4161e3c02415d7e)
Change-Id: I7d385d4326fac6f67d17a003679471806b5ad3b2
Reviewed-on: …
> chore: cherry-pick df438f22f7d2 from chromium

- LICENSE
Per discussions with the Foundation, we are making an update to all copyright headers to follow the Linux Foundation guidance on copyright notices. In particular, we are broadening them to cover all contributors, and eliminating the year to avoid the need to keep them up to date.
> chore: update copyright headers

- docs/api/frameless-window.md
Read that on some external website. I think this should be added to the official docs.
Updated docs: Clarifying that window will not be transparent when dev tools are openend .
Notes: none
> docs: transparent window opaque while dev tools opened

- patches/chromium/.patches
- patches/chromium/disable_unload_metrics.patch
- spec-main/fixtures/apps/crash/main.js
Chromium introduced metrics to measure unload performance in:
https://chromium-review.googlesource.com/c/chromium/src/+/2314877
Which would cause some DCHECKs to assert in Electron in some cases: https://github.com/electron/electron/issues/27717.
And it would result in failing tests, because it caused the main process to crash:
```
crashReporter module should send minidump when sandboxed renderer crashes api-crash-reporter-spec.ts 643 ms
Error message:
ptype: expected 'browser' to equal 'renderer'
Error stack trace:
AssertionError: ptype: expected 'browser' to equal 'renderer'
at checkCrash (electron\spec-main\api-crash-reporter-spec.ts:39:35)
at Context.<anonymous> (electron\spec-main\api-crash-reporter-spec.ts:154:7)
at runMicrotasks (<anonymous>)
at processTicksAndRejections …
```
> fix: disable unload metrics to fix CI failure

- docs/api/session.md
Closes https://github.com/electron/electron/issues/27576.
Chromium introduced a new permission option, display-capture, for sessions. `display-capture` requests access to capture the screen. 
This API is currently in master and was introduced in the 12-x-y line, but as it is a minor change, it is undocumented. This PR documents this change  and commits it as a semver minor.
Notes: Added display-capture API for session.setPermissionRequestHandler
> feat: add session display-capture api option

- spec-main/api-web-contents-spec.ts
- spec-main/webview-spec.ts
- spec/webview-spec.js
Close https://github.com/electron/electron/issues/26045.
The `did-change-theme-color` event is only emitted when the page has been painted, so for webview the event is usually only emitted when the parent BrowserWindow is visible.
This PR moves the webview `did-change-theme-color` test to main process and makes sure its parent window is visible, to fix the flaky test.
Notes: none
> test: fix flaky did-change-theme-color test

- docs/api/browser-window.md
- docs/api/extensions.md
- docs/api/session.md
- docs/tutorial/devtools-extension.md
- shell/browser/api/electron_api_session.cc
- shell/browser/api/electron_api_session.h
- shell/browser/extensions/electron_extension_loader.cc
- shell/browser/extensions/electron_extension_loader.h
- shell/browser/extensions/electron_extension_system.cc
- shell/browser/extensions/electron_extension_system.h
Backport of #25198.
Notes: Added `allowFileAccess` option to `loadExtension()` API.
> feat: implement allowFileAccess loadExtension option

- shell/common/node_bindings.cc
- shell/common/node_bindings.h
- shell/renderer/electron_renderer_client.cc
Closes https://github.com/electron/electron/issues/27457.
Refs https://github.com/electron/electron/commit/13f319eddfe2207558862aa5556da22fea983bd6
If we're loading Node.js into a subframe and we've already initialized the Node.js integration, that means we're in `DidCreateScriptContext` because a new subframe was created, not because we've reloaded the page. If that's the case, that means the last call to `node_bindings_->PrepareMessageLoop()` may still be active and calling it twice in a row can hang the page. In that case, don't re-prepare the message loop.
cc @deepak1556 @zcbenz @MarshallOfSound @ckerr 
Notes: Fixed an issue where libuv might hang with multiple subframes when `nodeIntegrationInSubframes` is enabled.
> fix: libuv hang when nodeIntegrationInSubframes enabled

- shell/browser/api/electron_api_web_contents.cc
- spec-main/api-web-contents-spec.ts
Fix a crash that caused by `render-process-gone` event accessing WebContents after user has destroyed it in the `crashed` event.
Notes: Fix crash when destroying WebContents in the `crashed` event.
> fix: check WebContents before emitting render-process-gone event

- patches/chromium/.patches
- patches/chromium/cherry-pick-76cb1cc32baa.patch
Use a copy for transferring non detachable buffers
Currently, |DOMArrayBuffer::Transfer()| makes a copy, but still uses
the original buffer for transferring, thus making it possible to share a
regular ArrayBuffer (not SAB) with multiple threads.
(cherry picked from commit 0d289da12075592372940a366ad565b9a13d57ce)
Bug: 1177341
Change-Id: Idb48deb1698fe555f32531bc04b55dd3e1fb0a06
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2690630
Reviewed-by: Bill Budge <bbudge@chromium.org>
Reviewed-by: Andreas Haas <ahaas@chromium.org>
Commit-Queue: Sergei Glazunov <glazunov@google.com>
Commit-Queue: Daniel Cheng <dcheng@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#853272}
Reviewed-on: …
> chore: cherry-pick 76cb1cc32baa from chromium

- shell/browser/api/electron_api_web_contents.cc
I am still working on improving this PR, so any additional insights into better ways to accomplish this (or other general review) would be appreciated.
Closes https://github.com/electron/electron/issues/27188
This PR restores the functionality where the title of a browser window is properly updated when navigating through its session history. Before, when you tried to navigate to a previously loaded page in the window history (such as with commands like `window.history.back()`) the title of the page would not be updated to reflect this navigation. Now the window's title will be properly updated.
cc @MarshallOfSound , @nornagon , @zcbenz  
**Further Notes (for more context):**
The code path that these navigation commands were initially following was changed with [this …
> fix: add support for title change with window history navigation

- docs/api/browser-window.md
- shell/browser/api/electron_api_base_window.cc
- shell/browser/api/electron_api_base_window.h
- shell/browser/api/electron_api_browser_window.cc
- shell/browser/api/electron_api_browser_window.h
- shell/browser/native_window.h
- shell/browser/native_window_mac.h
- shell/browser/native_window_mac.mm
- shell/browser/native_window_views.cc
- shell/browser/native_window_views.h
- spec-main/api-browser-view-spec.ts
Backport of #27007 
Notes: Added `win.setTopBrowserView()` so that BrowserViews can be raised.
> feat: add `win.setTopBrowserView()` so that BrowserViews can be raised

- patches/chromium/.patches
- patches/chromium/disable_gpu_acceleration_on_all_mesa_software_rasterizers.patch
Disable GPU acceleration on all Mesa software rasterizers
The previous entry only disabled acceleration on swrast, but softpipe
and llvmpipe shouldn't be used for "GPU" acceleration either.
This should apply to Linux but not ChromeOS, AFAICT.
This only improves an existing software rendering list entry, but here
is the rationale: We prefer to rely on our own (domain specific, so more
efficient) software paths, at least for everything other than WebGL. And
for WebGL, SwiftShader avoids unknown factors like
llvmpipe/softpipe/swrast.
If you are running a Mesa GL driver (not e.g. NVIDIA) then you can force
these configurations with:
- LIBGL_ALWAYS_SOFTWARE=1
https://docs.mesa3d.org/envvars.html#libgl-environment-variables:~:text=LIBGL_ALWAYS_SOFTWARE
- GALLIUM_DRIVER=llvmpipe, softpipe, or …
> chore: cherry-pick 62bda83979 from chromium

- lib/renderer/security-warnings.ts
Closes https://github.com/electron/electron/issues/23163.
The security warnings logic was checking:
```js
webPreferences.enableBlinkFeatures && webPreferences.enableBlinkFeatures.length === 0
```
as a way to rule out whether or not to show `enableBlinkFeatures` security warning. This presented an issue because the `&&` operator actually returns the value of one of the specified operands and so if this operator is used with non-Boolean values, it will return a non-Boolean value. In this case `webPreferences.enableBlinkFeatures` is `string | undefined`, and so if the first operand in the expression is falsy, as it would be for empty string, it would simply return `''` and show the warning where none should be shown.
This can be verified in the Node.js repl:
```console
Welcome to Node.js …
```
> fix: enableBlinkFeatures warning in webviews

- patches/chromium/.patches
- patches/chromium/stop_using_raw_webcontents_ptr_in_dragdownloadfile.patch
Stop using raw WebContents ptr in DragDownloadFile
BUG=1172192
(cherry picked from commit 99dc876a13df19f3512bcfb97e794ab5d1b28905)
Change-Id: Ie029713553ff88c1e271db1c84396e1ddda19286
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2666189
Reviewed-by: Xing Liu <xingliu@chromium.org>
Commit-Queue: Min Qin <qinmin@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#849692}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2692927
Reviewed-by: Shakti Sahu <shaktisahu@chromium.org>
Cr-Commit-Position: refs/branch-heads/4324@{#2200}
Cr-Branched-From: c73b5a651d37a6c4d0b8e3262cc4015a5579c6c8-refs/heads/master@{#827102}
Notes: Security: backported fix for 1172192.
> chore: cherry-pick 3a6f6fbfd8 from chromium

- patches/v8/.patches
- patches/v8/merged_interpreter_store_accumulator_to_callee_after_optional.patch
Merged: [interpreter] Store accumulator to callee after optional chain checks
Revision: df98901c19ce17ca995ee6750379b0f004210d68
BUG=chromium:1171954
NOTRY=true
R=rmcilroy@chromium.org
Change-Id: Ib62b5cecb1f0c5a31856a26d97464e1ca941bc39
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/2689191
Reviewed-by: Ross McIlroy <rmcilroy@chromium.org>
Cr-Commit-Position: refs/branch-heads/8.8@{#34}
Cr-Branched-From: 2dbcdc105b963ee2501c82139eef7e0603977ff0-refs/heads/8.8.278@{#1}
Cr-Branched-From: 366d30c99049b3f1c673f8a93deb9f879d0fa9f0-refs/heads/master@{#71094}
Notes: Security: backported fix for 1171954.
> chore: cherry-pick 84853ff62a from v8

- patches/chromium/.patches
- patches/chromium/websocket_don_t_clear_event_queue_on_destruction.patch
WebSocket: Don't clear event queue on destruction
It's unnecessary to clear the event queue as it will be garbage
collected anyway. Stop doing it.
Also add a unit test for GC with pending events. This can only happen if
the execution context changes while the events are pending.
BUG=1170657
(cherry picked from commit 2dae20b0b3890af23852345a69158c99b47746aa)
(cherry picked from commit 171d6ee562c3cac850d9705e18745bb1214e5d83)
Change-Id: I01e5a687587f7471e88640c43f0dfe83e5c01bd1
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2655089
Commit-Queue: Adam Rice <ricea@chromium.org>
Cr-Original-Original-Commit-Position: refs/heads/master@{#848065}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/266095 …
> chore: cherry-pick b712f9fd66 from chromium

- patches/chromium/.patches
- patches/chromium/fix_heap_overflow_in_videoframeyuvconverter.patch
Fix heap overflow in VideoFrameYUVConverter
Currently with some texture sizes GLES2Util::ComputeImageDataSizesES3
will attempt to add row padding when calculating the size of a
VideoFrame plane. This is because it's currently assumed that each row
aligns on a 4 byte boundary based on GL_UNPACK_ALIGNMENT but
VideoFrames make no such guarantee as they may be densely packed.
This CL removes the GL_UNPACK_ALIGNMENT assumption so that we only use
the VideoFrame's stride when calculating padding.
(cherry picked from commit 7de5d0ecb5a4f73aeffe15d825bf694d0d8e2a08)
Bug: 1166504, 1161131
Change-Id: I2484f5dfd2ad85b088fee57758776a5c9bd01d95
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2642765
Reviewed-by: Vasiliy Telezhnikov <vasilyt@chromium.org>
Commit-Queue: Nathan …
> chore: cherry-pick 59f3ca2780 from chromium

- shell/browser/electron_download_manager_delegate.cc
- shell/browser/electron_download_manager_delegate.h
Closes https://github.com/electron/electron/issues/27601.
It shouldn't be the case that we create the last saved download directory if it doesn't exist. Only do this if it's the global default.
Notes: Fixed an issue where deleted download directories would be sometimes recreated by the operating system.
> fix: don't create last saved path if none exists

- shell/browser/common_web_contents_delegate_mac.mm
Backport of #27701
Notes: Fixed OS-level shortcuts on macOS (e.g. Ctrl + F2, ⌘ + ~).
> fix: restore window event redispatching on mac

- patches/chromium/.patches
- patches/chromium/websocket_don_t_clear_event_queue_on_destruction.patch
WebSocket: Don't clear event queue on destruction
It's unnecessary to clear the event queue as it will be garbage
collected anyway. Stop doing it.
Also add a unit test for GC with pending events. This can only happen if
the execution context changes while the events are pending.
BUG=1170657
(cherry picked from commit 2dae20b0b3890af23852345a69158c99b47746aa)
(cherry picked from commit 171d6ee562c3cac850d9705e18745bb1214e5d83)
Change-Id: I01e5a687587f7471e88640c43f0dfe83e5c01bd1
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2655089
Commit-Queue: Adam Rice <ricea@chromium.org>
Cr-Original-Original-Commit-Position: refs/heads/master@{#848065}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/266095 …
> chore: cherry-pick b712f9fd6 from chromium

- docs/api/menu.md
Closes https://github.com/electron/electron/issues/25028
Previously it was not documented on Electron that an '&' was needed to escape an '&' for a menu item name. 
Gist: https://gist.github.com/mlaurencin/b9f5968c70c3e8628150e11fa88e81cb
Notes:  None
> docs: update menu item '&' escaping

- shell/browser/electron_browser_client.cc
Adds some crash keys for path data when the child process exe path is found to
be different from the parent's path on win/linux.
We're seeing this CHECK fire in production, and this will hopefully help us
narrow down the cause!
Notes: none
> fix: gather crash data for unexpected helper path

- patches/chromium/feat_enable_offscreen_rendering_with_viz_compositor.patch
- shell/browser/osr/osr_host_display_client.cc
- shell/browser/osr/osr_host_display_client.h
- shell/browser/osr/osr_render_widget_host_view.cc
- shell/browser/osr/osr_render_widget_host_view.h
Close https://github.com/electron/electron/issues/23640.
The offscreen patch was sending a sync IPC message to call `IsOffScreen`, which caused memory corruptions since the related classes might be destroyed while waiting for the message to reply.
This PR refactors the offscreen patch to pass `IsOffScreen` via async parameter to avoid doing the sync IPC call.
Notes: none
> fix: pass IsOffscreen via parameter instead of sync IPC method

- shell/common/gin_converters/blink_converter.cc
This fixes two bugs with `sendInputEvent`, detected by ASan.
1. The call to `memset` was not clearing the full buffer, as the size of each
element of the array is 2 bytes, not 1.
2. This buffer is at some later point passed to string() as a raw char16
pointer, which causes the length of the string to be computed by seeking for
a null terminator. However, this results in an out-of-bounds access as we
often fill all 4 characters of both `text` and `unmodified_text` with
non-null values.
It looks like this code was inspired by
[BuildCharEvent](https://source.chromium.org/chromium/chromium/src/+/master:content/renderer/pepper/event_conversion.cc;l=442-458;drc=e1f0247fb2114a48a94b60c887b447a939efd64c)
in content/renderer/pepper/event_conversion.cc, so I've updated this to be a
little closer to …
> fix: cap sendInputEvent text length at n-1

- .github/ISSUE_TEMPLATE/feature_request.yml
This will fix the Feature Request template. More details: https://gh-community.github.io/issue-template-feedback/changes
This PR updates the feature request config in accordance with the new YAML structure.
If you want, you could also modify the Preflight Checklist section to use checkboxes rather than textarea now:
```
- type: checkboxes
attributes:
label: Preflight Checklist
description: Please ensure you've completed the following steps by replacing [ ] with [x]
options:
- label: I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
required: true
- label: I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
required: true
- …
```
> build: update feature_request.yml

- lib/browser/api/base-window.ts
`TypeError: this.isFullscreen is not a function`
I believe this should fix `isDocumentEdited()` api
Notes: none
> fix: isFullScreen typo

- package.json
Noticed while scanning the package.json for other stuff, these aren't prod deps.  This package.json shouldn't have any prod deps 🤔 
> chore: move stray prod deps to dev deps

- shell/renderer/api/electron_api_context_bridge.cc
- spec-main/api-context-bridge-spec.ts
Found this issue while doing #26890 
Notes: Fixed issue where `window.open()` would not return an object with a `location.href` setter when `contextIsolation` is enabled and `nativeWindowOpen` is disabled.
> fix: values return from the ctx bridge with dynamic property support should themselves support dynamic properties

- lib/browser/api/net.ts
Fixes a race-condition in electron.net reported in issue https://github.com/electron/electron/issues/27805.
The race exists in the implementation of [IncomingMessage](https://github.com/electron/electron/blob/master/lib/browser/api/net.ts#L38) in the [_pushInternalData](https://github.com/electron/electron/blob/master/lib/browser/api/net.ts#L122) function. Under some circumstances, e.g. when a pipe throttles the response data, the callback stored in `this._resume` can be updated by [_storeInternalData](https://github.com/electron/electron/blob/master/lib/browser/api/net.ts#L109), triggered by the callback itself, before it is [reset to `null`](https://github.com/electron/electron/blob/master/lib/browser/api/net.ts#L125). This results in it being overwritten with `null`, effectively …
> fix: prevent race-condition in electron.net

- .circleci/config.yml
- vsts-arm32v7.yml
- vsts-arm64v8.yml
Pulls in https://github.com/electron/build-images/pull/5 which updates our CI to use node 14
Notes: none
> build: update docker images to node 14

- script/spec-runner.js
We don't need to use a fancy version of `node-gyp` for `arm64` anymore, my changes have made their way upstream 👍 
Notes: none
> build: remove node-gyp arm64 tricks

- docs/api/web-frame-main.md
- shell/browser/api/electron_api_web_frame_main.cc
- shell/browser/api/electron_api_web_frame_main.h
- spec-main/api-web-frame-main-spec.ts
Addresses #27862.
The upcoming `WebFrameMain` API implements `executeJavaScriptInIsolatedWorld` with an interface that doesn't match that of `WebContents`. Because we need to reconcile these two APIs, this PR temporarily reverts the API before the Electron 12 stable release. We'll then restore the refactored API both in master and in a 12-x-y minor release.
_Note: I targeted master and a 12-x-y backport to keep master and 12 in sync, but since this is being specifically reverted for 12, happy to change this and only target 12._
Notes: Reverted `WebFrameMain.executeJavaScriptInIsolatedWorld()`
> chore: revert webFrameMain.executeJavaScriptInIsolatedWorld method

- shell/browser/api/electron_api_base_window.cc
Ensure that the `owner_window` is valid before potentially calling any methods on it. 
In the initial PR we checked it in [`AddBrowserView`](https://github.com/electron/electron/pull/27000/files#diff-9e3935b7f7b31cb73a8e976e9725bab5c20c499dc5d1e33c7c7f62e3f90b72c9R765) but not in [`ResetBrowserViews`](https://github.com/electron/electron/pull/27000/files#diff-9e3935b7f7b31cb73a8e976e9725bab5c20c499dc5d1e33c7c7f62e3f90b72c9R1086) and we should check both.
Notes: Fixed a potential crash when resetting `BrowserView`s.
> fix: ensure owner window is valid in ResetBrowserViews

- shell/browser/api/electron_api_web_contents.cc
Backport of #27593.
Notes: Fixed background color not being applied for child windows created by native window.open path.
> fix: set WebContents background color ubiquitously 

- shell/browser/api/electron_api_web_contents.cc
- spec-main/api-web-contents-spec.ts
- spec-main/fixtures/apps/quit/main.js
When Electron is quitting, it may happen that the `content::WebContents` is destroyed while `electron::api::WebContents` is still alive.  This was causing a few CI flakes.
Notes: none
> fix: check web_contents() for destroyed WebContents

- lib/renderer/api/web-frame.ts
Command-line switches are no longer used to pass `webPreferences` to the renderer, replace with `getWebPreference`.
Notes: Fixed warning when `worldSafeExecuteJavaScript` is disabled.
> fix: warning when worldSafeExecuteJavaScript is disabled

- patches/boringssl/.patches
- patches/boringssl/expose_des-ede3.patch
Fixes #27277.
Notes: Added support for the des-ede3 cipher in node crypto.
> feat: expose des-ede3 cipher

- spec-main/fixtures/apps/quit/main.js
The https://github.com/electron/electron/pull/27815 relies on `contextIsolation` being false by default and fails after the default value is flipped.
Notes: none
> test: fix contextIsolation value for later added test

- patches/chromium/.patches
- patches/chromium/word_break_between_space_and_alphanumeric.patch
Backports https://chromium-review.googlesource.com/c/chromium/src/+/2666008
Refs https://github.com/microsoft/vscode/issues/90578
Notes: [a11y] Fixes broken word navigation for certain alphanumeric characters
> chore: cherry-pick 67fe5a41bff from chromium

- docs/api/power-monitor.md
Closes #27761. 
Updates accordingly PowerMonitor documentation for `suspend` and `resume`, which were added on Linux by #25149.
Notes: None
> docs: suspend and resume are available on Linux

- shell/browser/badging/badge_manager.cc
- shell/browser/badging/badge_manager.h
- shell/browser/electron_browser_client.cc
- shell/browser/electron_browser_client.h
- spec-main/chromium-spec.ts
- spec/fixtures/pages/service-worker/badge-index.html
- spec/fixtures/pages/service-worker/service-worker-badge.js
This is a followup to #27067.  As described here: https://web.dev/badging-api/#use, the badging API can be called from a service worker.  This PR fixes that API so that it works in a service worker.
Notes:  Fixed using navigator.setAppBadge and navigator.clearAppBadge from a service worker in Electron.
> fix: navigator.setAppBadge/clearAppBadge from a service worker

- lib/browser/api/crash-reporter.ts
When developer set  submitURL to '' crash reports will be saved  at `...\AppData\Roaming\...\Crashpad\reports`, will not be uploaded to the server.
So  at this time `deprecate.log('Sending uncompressed crash reports....')`  is  unnecessary.
Notes: none.
> chore: Add a condition to crashReporter deprecate log

- shell/browser/api/electron_api_base_window.cc
- shell/browser/api/electron_api_base_window.h
- shell/browser/api/electron_api_browser_view.cc
- shell/browser/api/electron_api_browser_window.cc
- shell/browser/api/electron_api_browser_window.h
- shell/browser/api/electron_api_web_contents.cc
- shell/browser/api/electron_api_web_contents.h
- shell/browser/api/electron_api_web_contents_view.cc
- shell/browser/ui/cocoa/electron_inspectable_web_contents_view.h
- shell/browser/ui/cocoa/electron_inspectable_web_contents_view.mm
- shell/browser/ui/inspectable_web_contents.cc
- shell/browser/ui/inspectable_web_contents_view_mac.mm
This PR cleans up the shutdown routine of WebContents, so:
1. The `content::WebContents` is always destroyed synchronously in the destructor of `api::WebContents`.
2. The only way to destroy `api::WebContents` is to call `api::WebContents::Destroy`, both in C++ and JavaScript.
With this change, it becomes much clearer how WebContents is destroyed, and the WebContents will have a deterministic destruction order.
Note that this PR might introduce new crashes, we should not backport it to old branches.
Notes: none
> refactor: cleanup how WebContents is destroyed

- docs/api/window-open.md
https://github.com/electron/electron/pull/24517 caused the doco here to change, however the doco incorrectly shows using boolean returns instead of object returns as stated in the API.
Notes: none
> docs: `setWindowOpenHandler` should show object return

- docs/api/browser-window.md
Updates the values for `contextIsolation` and `worldSafeExecuteJavaScript` for Electron 12.
Notes: none
> docs: update WebPreferences default values for Electron 12

- docs/api/auto-updater.md
Checking for updates every minute will cause the autoUpdater to fail if the internet connection is slow. This happens because the autoUpdater will download the update automatically which causes the previous download to be overridden.
This is my attempt to document it a little bit better so other people are not running into this situation. We fixed it by tracking if an update is already downloading and not calling `autoUpdate.checkForUpdates()` in this case.
Currently, the auto-update guide shows a one-minute check for update interval which should probably be improved as well.
https://www.electronjs.org/docs/tutorial/updates#implementing-updates-in-your-app
Notes: None
> docs: auto update downloading multiple times

- spec-main/extensions-spec.ts
The `extension-ready` event may also be emitted by the "Chromium PDF Viewer".
Notes: none
> test: ignore the ready event from PDF Viewer

- .circleci/config.yml
electron/build-tools#262 broke our CI because we were calling `node -e "require('./src/utils/goma.js').ensure()"` to start the goma proxy.  This PR changes our CI to instead call `goma_ctl.py ensure_start` directly.
Notes: none
> build: call goma_ctl.py ensure_start directly

- spec-main/extensions-spec.ts
- spec-main/index.js
- spec/static/index.html
Show full object diff when test fails, instead of unhelpful message like `expected { Object (openAtLogin, openAsHidden, ...) } to deeply equal { Object (openAtLogin, openAsHidden, ...) }`
Notes: none
> test: show full object diff

- docs/api/browser-window.md
- shell/browser/api/electron_api_web_contents.cc
- spec-main/api-browser-window-spec.ts
Closes https://github.com/electron/electron/issues/6015.
Closes https://github.com/electron/electron/issues/27891.
If the renderer is suspended or otherwise occluded, there's no guarantee that `view->CopyFromSurface` will ever be called and thus the promise ever resolved (see [here](https://source.chromium.org/chromium/chromium/src/+/master:content/public/browser/render_widget_host_view.h;l=218-219?q=CopyFromSurface&ss=chromium)). Handle this by checking for the current page visibility and returning an empty image if this is the case.
cc @ckerr @zcbenz @MarshallOfSound @deepak1556 
Notes: Fixed an issue where `win.capturePage()` never called back after calling `hide()` for a hidden window on some platforms.
> fix: capturePage not resolving with hidden windows

- patches/chromium/.patches
- patches/chromium/cherry-pick-6ed1c0c425e0.patch
[Merge to M89] Fix GetP2PSocketManager ownership
Let it return a mojo::SharedRemote<> instead of a raw pointer - this is
a decoration around a shared_refptr.
(cherry picked from commit 82cdc0781ceb4c22ef5903cf3115bea518a5523b)
Bug: chromium:1172054
Change-Id: I49bd22a0dc949bf869744d2ad25c1afcaea7fdbc
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2692532
Cr-Original-Commit-Position: refs/heads/master@{#854050}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2709590
Reviewed-by: Harald Alvestrand <hta@chromium.org>
Cr-Commit-Position: refs/branch-heads/4389@{#1280}
Cr-Branched-From: 9251c5db2b6d5a59fe4eac7aafa5fed37c139bb7-refs/heads/master@{#84 …
> chore: cherry-pick 6ed1c0c425e0 from chromium

- spec-main/chromium-spec.ts
The test no longer fails persistently.
Notes: none
> test: enable locale test for asan build

- patches/chromium/.patches
- patches/chromium/cherry-pick-aeb6bc551b60.patch
Prevent accessing shared buffers from audio rendering thread
The shared buffer in ScriptProcessorNode can be accessed by the
audio rendering thread when it is held by the main thread.
The solution suggested here is simply to expand the scope of
the mutex to minimize the code change. This is a deprecated
feature in Web Audio, so making significant changes is not
sensible. By locking the entire scope of Process() call, this
area would be immune to the similar problems in the future.
(cherry picked from commit 60987aa224f369fc0ea38c56e498389440921356)
Bug: 1174582
Test: The repro case doesn't crash on ASAN.
Change-Id: I2b292f94be65e6ec26c6eb0e0ed32b3fb2d88466
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2681193
Commit-Queue: Hongchan Choi <hongchan@chromium.org> …
> chore: cherry-pick aeb6bc551b60 from chromium

- patches/node/.patches
- patches/node/src_inline_asynccleanuphookhandle_in_headers.patch
Fixes https://github.com/electron/electron/issues/28043
Backports https://github.com/nodejs/node/pull/37000
Notes: fix native module compilation with AsyncCleanupHooks on windows
> chore: cherry-pick 1fe571a from node

- docs/api/cookies.md
The docs were wrong, now they right.  Simple enuf
> docs: fix cookies event documentation for type generation

- shell/browser/api/electron_api_browser_window.cc
Chromium in Electron 11 renamed `OS_MACOSX` to `OS_MAC`.
> fix: change #if defined(OS_MACOSX) to #if defined(OS_MAC)

- shell/common/api/electron_api_v8_util.cc
- spec-main/spellchecker-spec.ts
- typings/internal-ambient.d.ts
Make the spellchecker tests more reliable by using a busy loop to check spellchecker's state instead of waiting for fixed time.
Notes: none
> test: reliably wait for spellchecker to load

- patches/chromium/.patches
- patches/chromium/mediarecorder_tolerate_non-gmb_nv12_frames_for_h264.patch
MediaRecorder: tolerate non-GMB NV12 frames for H264.
The VPX video track recorders were updated to tolerate non-GMB NV12
input in crrev/c/2425748, but the H264 encoder was left neglected,
which hurts Mac users that have disabled hardware acceleration. This
change adds that support to it.
[TBR landing because mcasas@chromium.org is OOO]
TBR=mcasas@chromium.org
(cherry picked from commit de865890bf6a12c74ae9943ede6132d25c7a33dd)
Bug: 1177593
Change-Id: I608c76b1de8261dcc44463fe896e3b63d5fd329e
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2694407
Reviewed-by: ccameron <ccameron@chromium.org>
Reviewed-by: Evan Shrubsole <eshr@google.com>
Reviewed-by: Miguel Casas <mcasas@chromium.org>
Commit-Queue: Markus Handell <handellm@google.com> …
> chore: cherry-pick 38781b86f0 from chromium

- docs/tutorial/quick-start.md
With npm 7, just running `npx @electron-forge/cli import` results in:
```
npm ERR! could not determine executable to run
```
I tested this very quickly on Linux with Node 15.11.0 / npm 7.6.0, and the [associated Electron Forge docs](https://www.electronforge.io/import-existing-project) have also been updated.
Notes: none
> docs(quick-start): make import command npm 7-compatible

- docs/breaking-changes.md
In the Discord server, we're getting a lot of questions about using `require()` in the renderer with Electron 12 now that `contextIsolation` defaults to `false`, despite them having `nodeIntegration` set to `true`. This is probably the first step in socializing that.
Some discussion will be needed somewhere as to where else to add this sort of information (FAQ? Context Isolation doc?).
CC: @electron/wg-ecosystem
Notes: none
> docs(breaking-changes): contextIsolation disables require in renderer 

- patches/chromium/.patches
- patches/chromium/cherry-pick-eb0c0353bf24.patch
Convert AudioParam NaN values to the default value
If any output value of an AudioParam (including the intrinsic values
and any inputs to the AudioParam), should be NaN, replace the NaN
value with the associated defaultValue.
This causes some slowdowns so SIMD/NEON code was added to mitigate the
degradation.  There is still some slowdown, but the worst case is now
about 7% slower on x86 and 10% on arm. Generally, the slowdown is less
than 2% and 5%, respectively.  (Perversely, some results got faster,
and the differences are statistically significant.)
Full details can be found at
https://docs.google.com/spreadsheets/d/1EhbLHm-9cUoEO5aj1vYemVBLQ3Dh4dCJPPLTfZPrZt4/edit?usp=sharing
Manually tested the test case from the bug and the issue no longer
occurs.
(cherry picked from commit …
> chore: cherry-pick eb0c0353bf24 from chromium

- patches/chromium/.patches
- patches/chromium/cherry-pick-a4faa754a9ef.patch
[Merge to M86-LTS] Fix GetP2PSocketManager ownership
Let it return a mojo::SharedRemote<> instead of a raw pointer - this is
a decoration around a shared_refptr.
(cherry picked from commit 82cdc0781ceb4c22ef5903cf3115bea518a5523b)
(cherry picked from commit 6ed1c0c425e03172c77ba0f1465fe3ade79f2b2a)
Bug: chromium:1172054
Change-Id: I49bd22a0dc949bf869744d2ad25c1afcaea7fdbc
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2692532
Cr-Original-Original-Commit-Position: refs/heads/master@{#854050}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2709590
Reviewed-by: Harald Alvestrand <hta@chromium.org> …
> chore: cherry-pick a4faa754a9ef from chromium

- .github/ISSUE_TEMPLATE/feature_request.yml
I hope this is the right syntax? the existing one doesn't seem to be working.
Notes: none
> docs: use :syntax: for emoji in feature request template

- .github/ISSUE_TEMPLATE/bug_report.yml
looks like the top-level `about` is deprecated?
Notes: none
> docs: about->description in issue template

- patches/config.json
- patches/pdfium/.patches
- patches/pdfium/m89_upgrade_openjpeg_to_2_4_0.patch
M89: Upgrade OpenJPEG to 2.4.0
Upgrade OpenJPEG by copying the files from 2.4.0 and then applying
patches. Patch files that are no longer relevant are deleted.
Some parts of patch 3 are no longer applicable.
The bug from patch 36 was fixed by upstream commit
024b8407392cb0b82b04b58ed256094ed5799e04.
Add a new patch 39 to remove the unused opj_mqc_renorme() function.
Fixed: pdfium:1634
Change-Id: Iaf5e208ea1f32a84aedb09744e0df084621f73dd
Bug: pdfium:1634, chromium:1177875
Reviewed-on: https://pdfium-review.googlesource.com/c/pdfium/+/78050
Reviewed-by: Tom Sepez <tsepez@chromium.org>
Commit-Queue: Daniel Hosseinian <dhoss@chromium.org>
(cherry picked from commit a81ff7286463b41d1055353a1e5ed6a2501a8b63)
Reviewed-on: https://pdfium-review.googlesource.com/c/pdfium/+/78170
Auto-Submit: …
> chore: cherry-pick 157601b9b9 from pdfium

- .github/ISSUE_TEMPLATE/bug_report.yml
The template includes a comment section at the end anyway:
Notes: none
> docs: remove "Additional information" section from issue template

- patches/chromium/.patches
- patches/chromium/cherry-pick-3910c9f5cde6.patch
Convert AudioParam NaN values to the default value
If any output value of an AudioParam (including the intrinsic values
and any inputs to the AudioParam), should be NaN, replace the NaN
value with the associated defaultValue.
This causes some slowdowns so SIMD/NEON code was added to mitigate the
degradation.  There is still some slowdown, but the worst case is now
about 7% slower on x86 and 10% on arm. Generally, the slowdown is less
than 2% and 5%, respectively.  (Perversely, some results got faster,
and the differences are statistically significant.)
Full details can be found at
https://docs.google.com/spreadsheets/d/1EhbLHm-9cUoEO5aj1vYemVBLQ3Dh4dCJPPLTfZPrZt4/edit?usp=sharing
Manually tested the test case from the bug and the issue no longer
occurs.
(cherry picked from commit …
> chore: cherry-pick 3910c9f5cde6 from chromium

- patches/chromium/.patches
- patches/chromium/cherry-pick-18d3f86206e8.patch
[Autofill] Limit preview and filling only for non-state fields.
The number of times a value is filled into different fields is limited.
The exception are state fields because websites sometimes have one
state select box for each country and display the relevant select
box once the respective country has been selected.
This CL simplifies this mechanism and makes it more explicit by
encoding the type-dependent limits in TypeValueFormFillingLimit().
As a side effect, the limits apply not just to filled fields but also
unfilled fields of the same type.
Bug: 1075734, 1084903
Change-Id: Icc5e8e082850ed44d9c7fbbc911d03a95033d81f
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2557977
Commit-Queue: Matthias Körber <koerber@google.com>
Reviewed-by: Matthias Körber …
> chore: cherry-pick 18d3f86206e8 from chromium

- shell/browser/ui/win/notify_icon.h
- shell/browser/ui/win/notify_icon_host.cc
Backport of #26668.
cc @nornagon 
Notes: Fixed a rare crash on Windows that could occur when emitting certain Tray events.
> fix: delay emitting NotifyIcon events on Windows

- shell/browser/api/electron_api_system_preferences_mac.mm
- shell/common/color_util.cc
- shell/common/color_util.h
Fixes #27048
There's a helpful `skia` util for doing this so it's not too bad in the end.  Diving down the rabbit hole that is our color related APIs at the moment.  I'll be raising the transparency (missing alpha channel) issue with the API WG soon for discussion 👍 
Notes: Colors returned from `systemPreferences.getAccentColor()`, `getSystemColor` and `getColor` are now correctly converted into the devices color space.  Previously the color would have been subtly incorrect.
> fix: convert system colors to device color space in systemPreferences

- shell/browser/native_window_mac.mm
- shell/browser/native_window_views.cc
- spec-main/fixtures/crash-cases/transparent-window-get-background-color/index.js
Fixes #28104
`[CALayer backgroundColor]` is `nil` by default.  When we are transparent and don't assign a background color this would crash inside the skia helper
Notes: Fixed crash when calling `getBackgroundColor` on a transparent window with no assigned background color.
> fix: handle a nil backgroundColor in win.getBackgroundColor()

- lib/browser/api/top-level-window.js
Manual backport of #27823
Notes: Fixed BrowserWindow.documentEdited property on top level window.
> fix: documentEdited property on BrowserWindow

- patches/chromium/.patches
- patches/chromium/cherry-pick-b772b48067c4.patch
[Autofill] Limit preview and filling only for non-state fields.
The number of times a value is filled into different fields is limited.
The exception are state fields because websites sometimes have one
state select box for each country and display the relevant select
box once the respective country has been selected.
This CL simplifies this mechanism and makes it more explicit by
encoding the type-dependent limits in TypeValueFormFillingLimit().
As a side effect, the limits apply not just to filled fields but also
unfilled fields of the same type.
(cherry picked from commit 18d3f86206e88156e2eb20c1f691b3b40a779150)
Bug: 1075734, 1084903
Change-Id: Icc5e8e082850ed44d9c7fbbc911d03a95033d81f
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2557977
Commit-Queue: …
> chore: cherry-pick b772b48067c4 from chromium

- .github/ISSUE_TEMPLATE/bug_report.yml
Gives a bit more guidance about how to find the OS version and what info specifically we're looking for.
Notes: none
> docs: expand OS version prompt in issue template

- docs/api/session.md
The Web Serial API was released in Chromium v89, so it's not considered an experimental feature anymore and does not require `enableBlinkFeatures`.
/cc @jkleinsc
Notes: none
> docs: remove unnecessary enableBlinkFeatures

- patches/chromium/.patches
- patches/chromium/cherry-pick-6e8856624cbb.patch
Mark additional RootInlineBox dirty when culled inline box is removed
When a |LayoutInline| is removed, |LineBoxList::
DirtyLinesFromChangedChild| tries to mark affected
|RootInlineBox| dirty.
When the |LayoutInline| to be removed is culled, it tries to
find the |RootInlineBox| from its previous siblings, then look
for its previous and next |RootInlineBox|es.
Occasionally, the next next line of the previous sibling is
wrapped at the |LayoutInline|, and that its |LineBreakObj()|
holds the reference to the |LayoutInline|. This patch marks
such |RootInlineBox| dirty.
(cherry picked from commit 2dbdabb28d647c8ee20cbe36e3c957e74aff663b)
Bug: 1186287
Change-Id: I8ca73ebb4f5e4f13e997662fffd803d6a74ef49a
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2748756
Auto-Submit: …
> chore: cherry-pick 6e8856624cbb from chromium

- patches/chromium/.patches
- patches/chromium/cherry-pick-b3dc4c4b349d.patch
Introduce AudioBuffers for user access in ScriptProcessorNode
This CL adds new AudioBuffers for the access from the user code.
(cherry picked from commit b9e60ddc7606689e508f295077656389380288ba)
(cherry picked from commit c281886ca9ff22f6e75c8c1967dab9bf18b9942d)
(cherry picked from commit 33861dcf6d15415b6abf2152440906fafb74a27a)
Bug: 1177465
Test: The local ASAN build doesn't reproduce on given POCs.
Change-Id: Id9a3505ddb9ab61b4442385d0b830ef56f65f797
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2718543
Auto-Submit: Hongchan Choi <hongchan@chromium.org>
Reviewed-by: Raymond Toy <rtoy@chromium.org>
Commit-Queue: Hongchan Choi <hongchan@chromium.org>
Cr-Original-Original-Original-Commit-Position: refs/heads/master@{#857817}
Reviewed-on: …
> chore: cherry-pick b3dc4c4b349d from chromium

- lib/asar/fs-wrapper.ts
- shell/common/api/electron_api_asar.cc
- shell/common/asar/archive.cc
- shell/common/asar/archive.h
- shell/common/asar/scoped_temporary_file.cc
- shell/common/asar/scoped_temporary_file.h
- typings/internal-ambient.d.ts
This reverts commit 01a2e23194f86df1d0dcc4a3ccb3ea37e8f8c98b.
Fixes #27982.
Fixes https://github.com/electron/electron/issues/28195.
We should figure out a way to get the mmap code working, but in the mean time
this should solve the issue.
Notes: Fixed intensive I/O from asar files causing ERR_FILE_NOT_FOUND after a while.
> fix: revert "refactor: mmap asar files (#24470)"

- patches/chromium/.patches
- patches/chromium/cherry-pick-5651fb858b75.patch
[Merge to M89] Iterate more carefully over DTLS transports at close
Ensure that even if the set of DTLS transports is modified during
callbacks called from close, the process will be well-defined.
(cherry picked from commit 4f62c7bb28b0ce77b773a611c6ba02b361db1c85)
Bug: chromium:1167357
Change-Id: I712280e7382a647027912178156127831b437f75
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2639893
Reviewed-by: Henrik Boström <hbos@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#845122}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2752880
Reviewed-by: Adrian Taylor <adetaylor@chromium.org>
Cr-Commit-Position: refs/branch-heads/4389@{#1521} …
> chore: cherry-pick 5651fb858b75 from chromium

- docs/api/browser-window.md
Fixes #28178
Notes: Fixed type definition for `BrowserWindow.hookWindowMessage`
> docs: document the parameter structure of hookWindowMessage

- shell/browser/native_window.h
- shell/browser/native_window_mac.h
- shell/browser/native_window_mac.mm
Closes https://github.com/electron/electron/issues/15494.
Overrides `OnDisplayMetricsChanged` in `NativeWindowMac` so that when display metrics change and the `BrowserWindow` is in `simpleFullscreen` mode, the frame is recalibrated for the new bounds.
Tested with https://gist.github.com/bpasero/e4013ea83033a8c231f58f94c0df57c3.
cc @bpasero 
Notes: Fixed an issue where windows in `simpleFullscreen` mode were not properly resizing when display metrics changed.
> fix: recalibrate simpleFullscreen when display metrics change

- docs/development/issues.md
Since we have moved to the new issue forms we no longer have templates that we link to.
Notes: none
> docs: remove no longer relevant link

- docs/api/process.md
- lib/renderer/init.ts
- lib/sandboxed_renderer/init.ts
- spec-main/api-browser-window-spec.ts
- spec-main/fixtures/module/preload-sandbox.js
- spec/api-process-spec.js
The built-in remote module is usable in sandboxed renderers. However the standalone https://github.com/electron/remote version is not due to `process._linkedBinding` not being available to the preload script. Expose public API for that.
Notes: Added `process.contextId` used by `@electron/remote`.
> feat: add process.contextId used by @electron/remote

- docs/api/process.md
- shell/renderer/electron_renderer_client.cc
- shell/renderer/electron_sandboxed_renderer_client.cc
- shell/renderer/electron_sandboxed_renderer_client.h
- shell/renderer/renderer_client_base.cc
- shell/renderer/renderer_client_base.h
- spec-main/api-browser-window-spec.ts
- spec-main/fixtures/module/preload-sandbox.js
- spec/fixtures/api/isolated-process.js
It is currently not possible to determine whether `contextIsolation` is enabled in the renderer process without passing a flag from the main process. Add a property for that.
Notes: Added `process.contextIsolation` property that indicates whether the current renderer context has `contextIsolation` enabled.
> feat: add process.contextIsolation property

- docs/fiddles/quick-start/index.html
- docs/fiddles/quick-start/main.js
- docs/fiddles/quick-start/preload.js
- docs/tutorial/quick-start.md
Manual backport of #28223
With `contextIsolation` enabled by default in Electron 12, the Getting Started Guide no longer works as it is written. In order for the basic example to display values from `process.versions`, this change adds a `preload.js` to the example.
Adding a preload script does increase the complexity of the "hello world" example, but setting `contextIsolation: false` in the example code seemed like a less ideal solution since it encourages insecure practices
> docs: Update Quick Start Guide for Electron 12

- docs/fiddles/quick-start/index.html
- docs/fiddles/quick-start/main.js
- docs/fiddles/quick-start/preload.js
- docs/tutorial/quick-start.md
Manual backport of #28223 to 13-x-y
With `contextIsolation` enabled by default in Electron 12, the Getting Started Guide no longer works as it is written. In order for the basic example to display values from `process.versions`, this change adds a `preload.js` to the example.
Adding a preload script does increase the complexity of the "hello world" example, but setting `contextIsolation: false` in the example code seemed like a less ideal solution since it encourages insecure practices
> docs: Update Quick Start Guide to work with contextIsolation

- patches/chromium/.patches
- patches/chromium/cherry-pick-e1505713dc31.patch
css: Make fetches from inline CSS use the document's URL as referrer
Right now, fetches from inline CSS use the inline CSS's base URL
instead of the URL from the context that embeds the inline CSS: for
instance, loading a source-site.com page with the following code
<base href="https://other-site.com">
<style type=text/css> @import('best-sheet.com') </style>
should lead to the best-sheet.com sheet getting fetched with a
source-site.com referrer, but it will currently provide an
other-site.com referrer. However, if the imported sheet from
best-sheet.com makes more nested fetches, those nested requests should
use best-sheet.com as the basis for their referrers (as they do
currently).
This CL updates CSSParserContext's referrer setting logic to roughly do
the following:
- inline CSS: use the …
> chore: cherry-pick e1505713dc31 from chromium

- patches/v8/.patches
- patches/v8/regexp_throw_when_length_of_text_nodes_in_alternatives_is_too.patch
- patches/v8/reland_regexp_hard-crash_on_invalid_offsets_in.patch
Reland "[regexp] Hard-crash on invalid offsets in AdvanceCurrentPosition"
This is a reland of 164cf80bbb0a6e091300bfc4cbbe70a6e6bd3e49
The reland fixes UB (left-shift of negative integer type) with a
static_cast<uint32_t>.
> [regexp] Hard-crash on invalid offsets in AdvanceCurrentPosition
>
> Drive-by: Range checks in `Emit(byte, twenty_four_bits)` to ensure the
> given packed bits actually fit into 24 bits.
>
> Bug: chromium:1166138
> Change-Id: I2e711e6466bb48d7b9897f68dfe621d12bd92508
> Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/2625877
> Commit-Queue: Jakob Gruber <jgruber@chromium.org>
> Commit-Queue: Leszek Swirski <leszeks@chromium.org>
> Auto-Submit: Jakob Gruber <jgruber@chromium.org>
> Reviewed-by: Leszek Swirski …
> chore: cherry-pick 53c4d05797 and 6e8f04c980 from v8

- patches/chromium/.patches
- patches/chromium/cherry-pick-37210e5ab006.patch
Strip url to origin in X-Frame-Options violation messages
X-Frame-Options violations are logged via a console message in the
parent frame. To avoid leaking sensitive data to the parent frame,
let's report as "blocked url" just the origin of the blocked frame's
url, as we are already doing for the frame-ancestors CSP directive.
[M86 Merge]: ancestor_throttle.cc was moved.
(cherry picked from commit 93ce5606cd9a9597993ba70670b4092ab6722281)
Bug: 1146651
Change-Id: If5e5ac62f7e44e714b109e6adc389f11999e0f8b
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2534851
Commit-Queue: Antonio Sartori <antoniosartori@chromium.org>
Reviewed-by: Charlie Reis <creis@chromium.org>
Reviewed-by: Arthur Sonzogni <arthursonzogni@chromium.org> …
> chore: cherry-pick 37210e5ab006 from chromium

- docs/tutorial/quick-start.md
Embarrassingly, #28223 merged with a typo in `quick-start.md`. I had tested the code from the Fiddle code sample, but not from the markdown file, so I missed the typo. This change fixes the typo.
I've now tested both the Fiddle example *and* the example code from `quick-start.md` in Fiddle, and they both run successfully.
> docs: add missing curly brace to quick start example code

- docs/tutorial/using-selenium-and-webdriver.md
See #28197 . The existing snippet works with selenium-webdriver <= 3.6.0, but any more recent version seems to require using 'goog:chromeOptions' and forBrowser('chrome').
Notes: none
> docs: updated example to work with latest versions of selenium-webdriver

- shell/browser/api/electron_api_menu_mac.mm
Fixes #13279.
This looks like it was a typo. When `positioning_item` isn't specified, it's
`-1`, which evaluates to `true`, so this block wouldn't be invoked.
I've tested manually and it seems to fix the behavior described in the bug.
Notes: Fixed context menus not being positioned correctly when near the edge of the screen.
> fix: bad menu position when no positioning item specified

- shell/browser/api/electron_api_desktop_capturer.cc
- shell/browser/api/electron_api_desktop_capturer.h
`desktopCapturer.getSources()` returns a promise which should resolve
when capturing finishes. Internally it creates an instance of
DesktopCapturer which is responsible for resolving or rejecting
the promise.
Between the time DesktopCapturer starts capturing frames and when
it finishes, it's possible for its handle to be GC'd leading to
it never resolving.
These changes pin the instance of DesktopCapturer until it either
finishes or errors.
fixes #25595
------
To verify the fix, I ran this Fiddle gist which normally fails after 10-30 seconds without the fix
https://gist.github.com/90f43a52e7c48a531a57bec77428e11a
Notes: Fixed `desktopCapturer.getSources()` promise result sometimes never resolving.
> fix: DesktopCapturer gc'd prior to capture completion

- docs/api/process.md
- shell/renderer/renderer_client_base.cc
- spec-main/api-browser-window-spec.ts
- spec-main/fixtures/module/preload-sandbox.js
- spec/fixtures/api/isolated-process.js
Discussed in api-wg --> https://electronhq.slack.com/archives/CNL6E1GJD/p1616022446002700
I've updated the notes of the original PR (#28030) and will cherry pick this commit onto the backport shortly
> chore: rename process.contextIsolation to process.contextIsolated

- docs/api/crash-reporter.md
- lib/browser/api/crash-reporter.ts
- spec-main/api-crash-reporter-spec.ts
If there's no uploading, no submit URL is needed.
Notes: The `submitURL` option for `crashReporter.start` is no longer a required argument when `uploadToServer` is false.
> feat: allow omitting submitURL when uploadToServer is false

- patches/chromium/.patches
- patches/chromium/cherry-pick-c6d6f7aee733.patch
M86-LTS: Destroy `url_loader_factories_` before other NetworkContext fields
[M86 Merge]: Fixed conflict in network_context.h.
(cherry picked from commit f2b091f02593c67fd67db936452f363102b8d035)
(cherry picked from commit ffeb0731f83f8c4fa72776b658df45f0e6da041c)
Bug: 1174943
Change-Id: I7488c7779f51a3f0d82ecad3d65446032c065b26
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2679230
Commit-Queue: Łukasz Anforowicz <lukasza@chromium.org>
Reviewed-by: Matt Menke <mmenke@chromium.org>
Cr-Original-Original-Commit-Position: refs/heads/master@{#852311}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2692489
Reviewed-by: Łukasz Anforowicz <lukasza@chromium.org> …
> chore: cherry-pick c6d6f7aee733 from chromium

- shell/browser/api/electron_api_base_window.cc
Discovered when triaging https://github.com/electron/electron/issues/28228.
Reproducible with https://gist.github.com/c138020abbb7d949608c3c11b1cad253, when hitting `Stop` in Fiddle. Only shows up in `master`, so I assume gin changed something [here](https://github.com/electron/electron/commit/eb0e55c514866e67b2fd93eb7f94d2151b38a784) recently 🤔 
Notes: none.
> fix: missing HandleScope in ResetBrowserViews

- shell/browser/native_browser_view_mac.mm
Closes https://github.com/electron/electron/issues/28228.
Our y-axis offset calculation was slightly off - this corrects that.
Tested with https://gist.github.com/c138020abbb7d949608c3c11b1cad253 and also with https://gist.github.com/08f3e56e0a4dc443621bd769e18c7cd6 to ensure no regressions.
Notes: Fixed an issue where the drag regions in BrowserViews on macOS could be off in their y-axis.
> fix: drag region offsets in BrowserViews

- shell/browser/api/electron_api_web_contents.cc
- shell/browser/ui/inspectable_web_contents.h
The `DevToolsEmbedderMessageDispatcher` and `DevToolsFrontendHost` instances should be destroyed before destroying the WebContents, otherwise there might be race conditions when handling messages from the WebContents. This matches the destruction order in Chromium's `chrome/browser/devtools/devtools_ui_bindings.h`.
This should be able to fix the crash when testing devtools in CI:
```
0   Electron Framework                  0x0000000110427549 base::debug::CollectStackTrace(void**, unsigned long) + 9
1   Electron Framework                  0x0000000110343a43 base::debug::StackTrace::StackTrace() + 19
2   Electron Framework                  0x0000000110427471 base::debug::(anonymous namespace)::StackDumpSignalHandler(int, __siginfo*, void*) + 2385
3   libsystem_platform.dylib …
```
> fix: destroy MessageDispatcher before WebContents

- docs/api/browser-window.md
- docs/api/context-bridge.md
- docs/api/process.md
This is another piece of example code that no longer works with `contextIsolation: false`. Since you can't expose values through `global` anymore, it no longer made sense to have the example live in the `process` `'loaded'` event docs. I moved it to the `contextBridge` docs since that's what you'd now use to expose Node APIs.
> docs: update Node global symbols example to use contextBridge

- shell/common/node_bindings.cc
Addresses a longstanding TODO  to use the more well-maintained and embedder-focused `node::InitializeNodeWithArgs` instead of `node::Init`. See [here](https://github.com/nodejs/node/commit/d7f11077f15f52a2db191d3a5bcc41581cb7361f).
Notes: none
> refactor: prefer embedder-focused InitializeNodeWithArgs

- patches/chromium/.patches
- patches/chromium/cherry-pick-a66dbdcf6493.patch
Reland "Reland "[FSA] Add IsSafePathComponent checks to GetFile/GetDirectoryHandle.""
This is a reland of 2d41c3952d2851948a09ddcf3e97bae6c419b024
The added test was modified to no longer assert that all unsafe files
were written to disk successfully. This should make the test pass (albeit
with less stringent checks) on file systems/platforms that don't allow
all unsafe file names.
> Reland "[FSA] Add IsSafePathComponent checks to GetFile/GetDirectoryHandle."
>
> This is a reland of 004377929febd7cf7392932b01df7f4a0a362679
>
> The main difference is to make sure iterating over a directory doesn't
> return files we don't want to expose either (and not CHECK failing if
> such files are found when iterating).
>
> Original change's description:
> > [FSA] Add …
> chore: cherry-pick a66dbdcf6493 from chromium

- shell/renderer/api/electron_api_context_bridge.cc
- spec-main/api-context-bridge-spec.ts
- spec-main/fixtures/api/context-bridge/context-bridge-mutability/index.html
- spec-main/fixtures/api/context-bridge/context-bridge-mutability/main.js
- spec-main/fixtures/api/context-bridge/context-bridge-mutability/package.json
- spec-main/fixtures/api/context-bridge/context-bridge-mutability/preload.js
This PR adds a new `base::Feature` - `ContextBridgeMutability`. When the feature is enabled values that are exposed via context bridge are not freezed and are not made readonly.
**ContextBridgeMutability off**
**ContextBridgeMutability on**
As discussed with @MarshallOfSound no need to document it.
Notes: Adding `ContextBridgeMutability` feature that skips context bridge `DeepFreeze` and `SetReadOnlyNonConfigurable` when exposing a value.
> feat: add ContextBridgeMutability feature

- spec-main/api-web-contents-spec.ts
- spec-main/api-web-frame-main-spec.ts
- spec-main/fixtures/sub-frames/frame-with-frames.html
Adds tests to @deepak1556's `findInFrame/stopFindInFrame` API. Also adds some tests to `findInPage` for `webContents`.
Notes: none
> chore: add unit tests for findInPage/findInFrame

- shell/common/node_bindings.cc
- shell/common/node_bindings.h
- spec-main/fixtures/apps/libuv-hang/index.html
- spec-main/fixtures/apps/libuv-hang/main.js
- spec-main/fixtures/apps/libuv-hang/preload.js
- spec-main/fixtures/apps/libuv-hang/renderer.js
- spec-main/node-spec.ts
Closes https://github.com/electron/electron/issues/28154.
https://github.com/electron/electron/pull/25869 used `uv_loop_->iocp` to decide whether to re-prep the message loop, and it turns out not to be the case that it works and updates the same way that `uv_backend_fd` does, so what resulted was that when `allowRendererProcessReuse` was true the loop would not re-prep on reload and libuv would hang.
This fixes that by only handling this case on non-Windows systems.
Tested with https://gist.github.com/codebytere/2face1c26d09e38c06f49111c3fca13f.
Notes: Fixed an issue where some Node.js modules would hang on page reload on Windows.
> fix: libuv hang on Windows

- shell/common/platform_util_win.cc
This aligns our `openExternal` behavior with upstream where the URL should be escaped before being sent to the external handler.  Most applications expect a spec-compliant URI, this ensures they receive one.
Notes: URLS passed to `shell.openExternal` on windows are now correctly URI encoded.  This was already occurring on macOS and Linux.
> fix: escape URL passed to shell.openExternal on windows

- lib/browser/api/web-contents.ts
- shell/renderer/printing/print_render_frame_helper_delegate.cc
Fixes an issue where `window.print()` did not work properly when printing a pdf from the pdf plugin. Pulled from Chromium's [corresponding impl](https://source.chromium.org/chromium/chromium/src/+/master:chrome/renderer/printing/chrome_print_render_frame_helper_delegate.cc;l=64-81;drc=ce83ee3f482ef49409bf97c28dd28cd8da8072c7;bpv=1;bpt=1). 
Tested with https://gist.github.com/293b0a64d8564da954fc222b9aba9ce1.
Notes: Fixed an issue where `window.print()` did not work properly when printing a pdf from the pdf plugin.
> fix: window.print() in pdf plugin

- shell/app/electron_content_client.cc
- shell/browser/api/electron_api_protocol.cc
- shell/browser/electron_browser_client.cc
- spec-main/api-protocol-spec.ts
- spec-main/index.js
Fix https://github.com/electron/electron/issues/20248.
The bug was caused by 2 reasons:
1. ServiceWorker loader does not have WebContents associated, so it did not get custom protocols registered.
2. `registerSchemesAsPrivileged` is called after service worker schemes get registered, so the custom scheme could not be recognized as service worker scheme.
Notes: Fix service worker not working with custom protocol.
> fix: make sure service worker scheme is registered with allowServiceWorkers

- shell/renderer/renderer_client_base.cc
[A recent change in Chromium](https://source.chromium.org/chromium/chromium/src/+/37893bf803b256be100b1bd1805abcd069c33140) started isolating (basically) all Pepper plugins. It seems like the smart thing for us to do is to follow suit and mimic their new behavior in our own `IsOriginIsolatedPepperPlugin` method.
Fixes #28200. See [this deep dive comment](https://github.com/electron/electron/issues/28200#issuecomment-801496222) for more context.
CC @nornagon 
Notes: Pepper plugins are now isolated from origins.
> fix: isolate Pepper plugins

- shell/renderer/api/electron_api_context_bridge.cc
- spec-main/api-context-bridge-spec.ts
Previously a function sent over the bridge would result in a proxy function existing in the other context, sending it back would create a proxy-of-a-proxy and so on.  With each successive pass over the bridge it would add another layer of proxy'ing which would get slower and slower.  This change ensures that when a method is cleanly passed back over the bridge to it's origin we use the stored "original function" as the return value thus ensuring a max proxy depth of 1.
This is safe to do for function because the lifetime of the proxy function is _already_ tied to the lifetime of the original function.  We can't do this for others objects / types without some smarts and last time we tried to implement those smarts it caused massive issues.
Notes: Improved performance characteristics of …
> perf: do not double-proxy methods being return over the contextBridge

- docs/api/browser-window.md
- docs/api/context-bridge.md
- docs/api/process.md
> docs: update Node API renderer example to use contextBridge

- script/lib/git.py
- script/lint.js
When a patch targets a file using CRLF line endings, they need to be retained in the exported patch file. Otherwise the patch will fail to apply. `git am` searches for surrounding lines of the initial file before patching, and without matching line endings it will fail to find them.
```
git am ../../electron/patches/webrtc/example.patch --reject
Checking patch modules/desktop_capture/win/wgc_capture_session.cc...
error: while searching for:
...
```
This came about due to the file referenced above containing CRLF line endings. This was probably a mistake upstream, but regardless should ideally still be supported by Electron scripts anyway.
Reasons why this wasn't supported before was
- [`str.splitlines()`](https://docs.python.org/3/library/stdtypes.html#str.splitlines) does not keep line …
> fix: export patches not retaining CRLF line endings

- shell/browser/native_window_views.cc
- shell/browser/ui/win/taskbar_host.cc
- shell/browser/ui/win/taskbar_host.h
Fixes https://github.com/electron/electron/issues/28319.
When the window is removed from the taskbar via `win.hide()`, the thumbnail buttons need to be set up again. Ensure that when the window is hidden, the taskbar host is notified that it should re-add them.
Tested with https://gist.github.com/883fa102da7c81e47bb866aa20089292.
Notes: Fixed an issue where the thumbar disappeared after `win.hide()` on Windows.
> fix: disappearing thumbar after win.hide()

- docs/api/web-contents.md
The text block is rendered as part of the `features` property, not the `handler` where it belongs to
Notes: none
> docs: add missing line in web-contents.md

- docs/api/command-line-switches.md
- shell/browser/electron_browser_main_parts.cc
- shell/browser/feature_list.cc
- shell/browser/feature_list.h
Fixes: #27877
Refs: #27877
Initializes field trials so Electron applications can opt-in to trialing specific in-development features. This is quite used in the WebRTC part for instance. Once such field trial is Opus audio redundancy. This PR facilitates testing that.
Notes: Added ability to enable field trials.
> feat: initialize field trials from command line arguments

- spec-main/spellchecker-spec.ts
Even with https://github.com/electron/electron/pull/28386 the spellchecker may still take more than a minute to load under ASan, so increate the timeout of spellchecker to 3 minutes for ASan.
This is my last try to make spellchecker test work under ASan, if it is still flaky, I think we should just disable it for ASan.
Notes: none
> test: increase timeout for spellchecker under ASan

- shell/browser/api/electron_api_crash_reporter.cc
- shell/browser/api/electron_api_download_item.cc
- shell/browser/api/electron_api_download_item.h
- shell/browser/api/electron_api_menu.cc
- shell/browser/api/electron_api_session.cc
- shell/browser/api/electron_api_session.h
- shell/browser/api/electron_api_url_loader.cc
- shell/browser/native_window_mac.mm
- shell/renderer/api/electron_api_web_frame.cc
`v8::Isolate::GetCurrent()` is deprecated, and we should be using our helper method where possible.
Notes: none
> refactor: remove more uses of `v8::Isolate::GetCurrent()`

- patches/chromium/expose_setuseragent_on_networkcontext.patch
- patches/chromium/network_service_allow_remote_certificate_verification_logic.patch
This fixes #28313.
Before this change, the RemoteCertVerifier would receive several concurrent
requests to verify the same domain, and the 2nd one to return would cause a
crash. I'm not totally sure what the exact cause of the crash was, but putting
the RemoteCertVerifier upstream from the coalescing and caching layers means
that only one verification request gets sent to the main process, and by doing
so fixes the crash.
Notes: Fixed a network process crash that could happen when using `setCertificateVerifyProc` with many concurrent verification requests.
> fix: put RemoteCertVerifier upstream from the caching and coalescing layers

- shell/renderer/api/electron_api_context_bridge.cc
- spec-main/api-context-bridge-spec.ts
Closes https://github.com/electron/electron/issues/28327.
Fixes an issue where errors thrown in functions passed over the `contextBridge` would be prefixed with `Uncaught Error` so that the error message then incorrectly displayed as `Error: Uncaught Error: test`. This is owed to the fact that errors aren't serializable as-is, so we should be pulling the message off the exception and re-constructing and throwing it in the destination context
Tested with https://gist.github.com/f11c77f9bc2cbf98d42a9fcaf477c80a.
Notes: Fixed an issue where errors thrown in functions passed over the `contextBridge` could be displayed incorrectly.
> fix: errors thrown in functions over the `contextBridge`

- docs/README.md
- docs/breaking-changes.md
- docs/development/issues.md
- docs/tutorial/quick-start.md
- docs/tutorial/security.md
- docs/tutorial/using-selenium-and-webdriver.md
This brings all the documentation changes to the guides that are missing in the `13-x-y` release in preparation to start using the documentation from the right branch.
While there were less commits than for [v12-x-y](https://github.com/electron/electron/pull/28396), I decided to use the same approach of copy pasting the `tutorials` folder and verified that the contents are relevant to v13.
I guess that @erickzhao would be the right stakeholder but there might be others as well.
Notes: none
> docs: backport current tutorials to 13-x-y

- shell/browser/extensions/electron_extension_system.cc
This aligns our component extension loading logic with https://source.chromium.org/chromium/chromium/src/+/master:chrome/browser/extensions/component_loader.cc;l=215-216;drc=062c315a858a87f834e16a144c2c8e9591af2beb
Notes: Fixes rare crash when initializing the internal PDF extension
> fix: handle an unparsable pdf manifest

- script/lib/git.py
This caused some patches to fail incorrectly as the patch file included non-ascii characters, we have to manually convert using the utf8 charset.
Appears to have been broken by #28360
> build: fix unicode patch file comparison in git.py

- patches/chromium/expose_setuseragent_on_networkcontext.patch
- patches/chromium/network_service_allow_remote_certificate_verification_logic.patch
Backport of #28358.
Notes: Fixed a network process crash that could happen when using `setCertificateVerifyProc` with many concurrent verification requests.
> fix: put RemoteCertVerifier upstream from the caching and coalescing layers (#28358)

- docs/api/window-open.md
There was no update to the `window.open` documentation when https://github.com/electron/electron/pull/27481 was merged. This PR adds a note for how `frameName` is related to `windowName` in the [native documentation](https://developer.mozilla.org/en-US/docs/Web/API/Window/open#parameters).
Notes:  None
> docs: add frameName note for window.open

- shell/browser/javascript_environment.cc
This seems to just have been missing here, leaking memory
(and breaking the API contract for Node.js embedding).
Notes: none
> fix: free IsolateData in ~NodeEnvironment

- docs/api/frameless-window.md
- shell/browser/native_window_views.cc
- shell/browser/native_window_views_win.cc
Closes https://github.com/electron/electron/issues/27838
Closes https://github.com/electron/electron/issues/27264
Previously windows without a frame (including transparent windows) used a workaround in order to maximize properly (See these two PRs: https://github.com/electron/electron/pull/6417 & https://github.com/electron/electron/pull/26586). With the latest change however, windows without frames could no longer be properly maximized using the Windows system menu (accessible through `alt + space`).
With this PR, the ability to maximize and unmaximize using the Windows system menu and double clicking the title bar, has been disabled for transparent windows. These windows will only be maximizable through Electron's API. Non-transparent frameless windows no longer use the workaround and …
> fix: enable system maximization for frameless windows except if transparent

- docs/tutorial/code-signing.md
Closes #28493. GoDaddy no longer offers this service.
Notes: none
> docs: Remove GoDaddy from Windows code signing options

- .circleci/config.yml
Followup to #26914 to further mute these errors as they still appear to be happening
> build: ignore ninja summary print failures

- lib/browser/api/web-contents.ts
- lib/browser/guest-window-manager.ts
- spec-main/guest-window-manager-spec.ts
Fixes #27967.
The window open handler was not invoked in situations where `-new-window` was
called without calling `-will-add-new-contents` / `-add-new-contents`, in
particular, when `target=_blank` or when holding a modifier key when clicking
on a link.
Notes: Fixed the handler set with `setWindowOpenHandler` not being invoked when a link was middle-clicked or shift-clicked.
> fix: invoke the window open handler for _blank links

- spec-main/node-spec.ts
Same with https://github.com/electron/electron/pull/28156, disable this test since spawning child Electron apps may receive SIGKILL because of out of memory.
Notes: none
> test: disable "fs in renderer process" test under ASan

- docs/api/structures/upload-file.md
- docs/api/structures/upload-raw-data.md
- lib/browser/guest-window-manager.ts
- lib/common/parse-features-string.ts
- spec-main/api-browser-window-spec.ts
This adds the missing `postData` parameter to `new-window`, which was previously omitted. This is the only call site of `emitDeprecatedNewWindowEvent`, so I can only assume its omission was accidental.
Notes: Fixed `postData` parameter missing from `new-window` event.
> fix: pass postData to new-window event

- shell/app/node_main.cc
- shell/browser/javascript_environment.cc
`JavascriptEnvironment` is the class that calls `RegisterIsolate()`
so it should be the one to call `UnregisterIsolate`, and this can happen
right before disposing the aforementioned `isolate`.
See: https://github.com/electron/electron/pull/28468
cc @deepak1556 
> fix: call `UnregisterIsolate` consistently

- shell/browser/electron_browser_client.cc
- shell/browser/protocol_registry.cc
- shell/browser/protocol_registry.h
- spec-main/chromium-spec.ts
- spec/webview-spec.js
Subresource `file://` requests should be explicitly allowed when web security is disabled, closes https://github.com/electron/electron/issues/23757.
This PR also rewrites webview web security tests, since they were passing even though `file://` requests were actually failing.
Notes: Fix failing to request file:// resources when web security is disabled.
> fix: allow accessing file:// when web security is disabled

- docs/api/web-contents.md
- shell/browser/api/electron_api_browser_window.cc
- shell/browser/api/electron_api_web_contents.cc
- spec-main/api-web-contents-spec.ts
Closes https://github.com/electron/electron/issues/20746.
Closes https://github.com/electron/electron/issues/27722.
Fixes an issue where `beforeunload` and `unload` weren't firing at all in `BrowserView`s. This was happening because we were only checking the BrowserWindow's `webContents` to see whether or not the events needed to be fired, and we also needed to check the `BrowserView`s WebContents.
However, this change makes it such that the event will be emitted for `BrowserViews` but will _not_ be respected - I've chosen not to tie the `BrowserView` lifecycle to its owning BrowserWindow should one exist per the [specification](https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event). Either way this is undefined behavior, and the alternative would be to wait until …
> fix: beforeunload and unload firing in BrowserViews

- docs/api/dialog.md
Undocument the `checkboxLabel` and `checkboxChecked` within `dialog.showMessageBoxSync` to avoid confusion as the result is not accessible with that API
View #28394
Notes: none
> docs: remove checkbox options in dialog.showMessageBoxSync

- docs/breaking-changes.md
> docs: fix typo in breaking-changes.md

- BUILD.gn
As of #28480 we now dynamically determine the `LSMinimumSystemVersion` value as part of the build process.  To avoid this changing and no one realizing we now have this assert which will trip during a Chromium upgrade if they bump the minimum supported macOS version so we can update our documentation appropriately.
> build: add safety net for mac_deployment_target

- patches/chromium/.patches
- patches/chromium/blink_wasm_eval_csp.patch
- spec-main/chromium-spec.ts
Backport of #28535
Notes: Support `wasm-eval` csp behind `WebAssemblyCSP` flag.
> fix: support wasm-eval csp behind WebAssemblyCSP flag

- docs/breaking-changes.md
I think this was technically marked deprecated in 12, but it wasn't added to breaking-changes, so doing that now.
Notes: none
> docs: note that new-window event is deprecated

- docs/api/browser-window.md
- lib/renderer/api/web-frame.ts
- lib/renderer/security-warnings.ts
- lib/renderer/web-frame-init.ts
- patches/chromium/allow_in_process_windows_to_have_different_web_prefs.patch
- shell/browser/web_contents_preferences.cc
- shell/common/options_switches.cc
- shell/common/options_switches.h
- shell/renderer/api/electron_api_web_frame.cc
- spec-main/api-web-frame-spec.ts
- typings/internal-ambient.d.ts
- typings/internal-electron.d.ts
Remove deprecated `worldSafeExecuteJavaScript` option from `webPreferences`.
This is already documented in Electron 14 breaking changes: 
https://github.com/electron/electron/blob/master/docs/breaking-changes.md#removed-worldsafeexecutejavascript
Notes: Deprecated `worldSafeExecuteJavaScript` option was removed from `webPreferences`.
> chore: remove deprecated `worldSafeExecuteJavaScript` option

- .circleci/config.yml
- spec-main/api-app-spec.ts
- spec-main/api-protocol-spec.ts
- spec-main/chromium-spec.ts
- spec-main/crash-spec.ts
- spec-main/node-spec.ts
- spec-main/webview-spec.ts
Reverts #28156 and #28509 in favor of just giving the ASAN tests a bigger box with more memory, previously they had a 4GB box.  They now get a 16GB box (with potential for us to go all the way to 40GB if we wanted to, but we really shouldn't need to.
> build: give ASAN tests more memory to avoid SIGKILL or disabling tests

- lib/renderer/web-view/web-view-attributes.ts
Tiny change i noticed as I was doing some tangential spelunking - we can use the URL API here.
Notes: none
> refactor: use URL API in resolveURL

- docs/tutorial/quick-start.md
Very small addition - the name of the preload script (`preload.js`) in the [Quick Start Guide] as it's not stated under what name it should be saved.
[Quick Start Guide]: https://www.electronjs.org/docs/tutorial/quick-start#define-a-preload-script
Notes: none
> docs: define the name of the preload script

- docs/api/system-preferences.md
Added missing return type to the docs for `systemPreferences.subscribeWorkspaceNotification`
https://github.com/electron/electron/blob/f73d09374eb8399541070796a2ac1a0de63e95f9/shell/browser/api/electron_api_system_preferences_mac.mm#L184-L189
Not sure whether to go with semver patch or none for this change. I went with patch since technically a project using TypeScript might not be expecting a return type after this change.
Notes: none
> docs: systemPreferences.subscribeWorkspaceNotification return type

- filenames.gni
- shell/browser/net/asar/asar_url_loader_factory.cc
- shell/browser/net/asar/asar_url_loader_factory.h
- shell/browser/protocol_registry.cc
- shell/browser/protocol_registry.h
- shell/browser/ui/inspectable_web_contents.cc
Fixes https://github.com/electron/electron/issues/21699
Notes: Allow loading source maps from custom protocols and asar bundles
> fix: load source maps from custom protocols and asar bundles

- patches/chromium/.patches
- patches/chromium/cherry-pick-162efe98330e.patch
Reland "Use a timer instead of a sleep loop."
This is a reland of ec21b4b42aa7ccebe79bfbee7db87c9cba20979a
> Use a timer instead of a sleep loop.
>
> This paves the way for implementing timer slack on the kqueue
> message pump.
>
> Bug: 1181297
> Change-Id: I74fdb63e85cf726000ee94b5851f84b06de314ae
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2713848
> Auto-Submit: Sigurður Ásgeirsson <siggi@chromium.org>
> Reviewed-by: Mark Mentovai <mark@chromium.org>
> Reviewed-by: Etienne Pierre-Doray <etiennep@chromium.org>
> Reviewed-by: Robert Sesek <rsesek@chromium.org>
> Commit-Queue: Sigurður Ásgeirsson <siggi@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#857894}
Bug: 1181297
Change-Id: I63287f8d53f0aee9833d090ef6d32aa94698c692 …
> chore: cherry-pick 162efe98330e from chromium

- shell/browser/serial/serial_chooser_controller.cc
- spec-main/chromium-spec.ts
Closes https://github.com/electron/electron/issues/28500.
Fixes an issue where `select-serial-port` callback crashes when called with an invalid serial port ID.
Tested with https://gist.github.com/ntamas/36ce5ef35c2427180b157d2903263846
Notes: Fixed an issue where `select-serial-port` callback crashes when called with an invalid serial port ID.
> fix: crash on invalid select-serial-port callback

- docs/api/browser-window.md
- docs/api/window-open.md
- docs/breaking-changes.md
- shell/browser/web_contents_preferences.cc
- spec-main/api-browser-window-spec.ts
- spec-main/chromium-spec.ts
- spec-main/fixtures/snapshots/proxy-window-open.snapshot.txt
- spec/static/main.js
- spec/webview-spec.js
Make `nativeWindowOpen: true` the default.
This option has been better than the alternative for some time (fewer bugs,
faster new windows, and more flexible). Let's make it the default.
Closes #28511.
Notes: `nativeWindowOpen: true` is now the default.
> feat: enable nativeWindowOpen by default

- script/lint.js
Bit of an annoyance when this lint failed and it just points you at a 300 line patch file 😆  Giving line numbers is easy enough here.
> build: provide line numbers of bad patch lines when linting

- shell/browser/native_window_mac.mm
Fix #27061 Fix #27080 
Notes: Fixed corner radius for vibrancy view in macOS 11
> fix: increase corner radius for vibrancy view on big sur

- shell/browser/native_window_mac.mm
Closes https://github.com/electron/electron/issues/28658.
If a sheet is attached to the window when we call `[window_ orderOut:nil]` in `window.hide()` on macOS, the sheet won't be able to show again on the same window. We therefore should be closing the attached sheet before calling `[window_ orderOut:nil]` on the `NSWindow` being hidden.
Tested with https://github.com/tsminh/electron-dialog-missing-after-hide
Notes:  Fixed an issue where some dialogs would stop working on macOS if `window.hide()` was called while they were open.
> fix: end attached sheet when calling window.hide()

- lib/browser/api/net.ts
This fixes a flake on linux CI which started recently where the "write" promise is being rejected after the request has been aborted / cancelled.  In this case we should drop the error to the floor but instead we pass it down the stack where it eventually emits a now unhandled error event.
Example failure: https://app.circleci.com/pipelines/github/electron/electron/38072/workflows/c1faf19b-aa41-4f99-a564-165729222859/jobs/838813
Verified fix by running the test that caused it 10000 times before fix and 10000 times after.  ~50 failures before, 0 after.
Putting no-notes because I don't think this was ever a released issue and I'm not sure what folks would see in their apps anyway.  It seems like a recent CI flake, I'll send it to all supported versions anyway though.
> fix: do not handle write errors after request is aborted

- patches/chromium/.patches
- patches/chromium/cherry-pick-3c80bb2a594f.patch
Forbid script execution while updating the paint lifecycle.
(cherry picked from commit 5425d3b100fab533ea9ddc2ed8fbfc4870db0587)
Bug: 1196781
Change-Id: Idc8d24792d5c413691977b09ca821de4e13887ad
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2812000
Commit-Queue: Adrian Taylor <adetaylor@chromium.org>
Commit-Queue: Robert Flack <flackr@chromium.org>
Reviewed-by: Xianzhu Wang <wangxianzhu@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#870275}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2821879
Reviewed-by: Robert Flack <flackr@chromium.org>
Commit-Queue: Jana Grill <janagrill@chromium.org> …
> chore: cherry-pick 3c80bb2a594f from chromium

- docs/development/build-instructions-gn.md
- docs/development/build-instructions-linux.md
- docs/development/build-instructions-macos.md
- docs/development/build-instructions-windows.md
We've gotten a surprising number of folks in the Discord server trying to use the Build Instructions to bundle/distribute their Electron apps. This pull request clarifies on each of the build instructions pages that the pages are for building itself, and points to a different docs page for building apps.
Notes: none
> docs(build-instructions): clarify that these are for building Electron itself

- .circleci/config.yml
These are functionally equivalent, let's not make this confusing
> build: unify machine-mac-large-arm and machine-mac-large

- docs/api/structures/user-default-types.md
- docs/api/system-preferences.md
- filenames.auto.gni
- package.json
- spec/ts-smoke/electron/main.ts
- yarn.lock
Couple of upstream fixes for description comment formatting and a couple of places where it was missing.
This also introduces generic types to our markdown parser such that we can type `getUserDefault`'s return type based on the provided param.
Closes https://github.com/electron/typescript-definitions/issues/58
> chore: update ts parser for description comment fixes and generic types

- patches/chromium/.patches
- patches/chromium/cherry-pick-162efe98330e.patch
Backport https://chromium.googlesource.com/chromium/src/+/162efe98330e8d243d472889db81dd78b691156f to fix crash on m1 mac.
This change is already in 12 and 13 after Chromium upgrades, we need to manually backport it for 11.
Close https://github.com/electron/electron/issues/28577.
Notes: Fix crash on m1 mac.
> fix: backport patch to fix crash on m1 mac

- patches/skia/.patches
- patches/skia/skscalercontext_getimage_less_brittle.patch
SkScalerContext::getImage less brittle.
Properly handle edge cases like
* the temporary glyph being a different size than expected
* filters which reduce in size
* filters which return false to indicate no filtering has been done
Bug: chromium:1190525
Change-Id: Ibc53eb1d7014210019e96cd6bae3e256d967be54
Reviewed-on: https://skia-review.googlesource.com/c/skia/+/392156
Commit-Queue: Ben Wagner <bungeman@google.com>
Reviewed-by: Herb Derby <herb@google.com>
(cherry picked from commit 348ee387a96d7d94733d46ad9e82b19cb890dd16)
Reviewed-on: https://skia-review.googlesource.com/c/skia/+/392437
Notes: Security: Backported fix to chromium:1190525.
> chore: cherry-pick 872b8c13d7 from skia

- patches/chromium/.patches
- patches/chromium/cherry-pick-012e9baf46c9.patch
Mojo: Remove some inappropriate DCHECKs
There are a few places where we DCHECK conditions that cannot be
reliably asserted since they depend on untrusted inputs. These are
replaced with logic to conditionally terminate the connection to the
offending peer process.
(cherry picked from commit a32b061fc92cc3864d036ffb8c22c12b05202589)
Fixed: 1195333
Change-Id: I0c6873bf55d6b0b1d0cbb3c2e5b256e1a57ff696
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2808893
Cr-Original-Commit-Position: refs/heads/master@{#870007}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2821958
Reviewed-by: Victor-Gabriel Savu …
> chore: cherry-pick 012e9baf46c9 from chromium

- shell/browser/native_window_views.cc
When creating a widget on linux the bounds are restricted to the screen size, when calling SetSize / SetBounds they are not.  This fixes this initialization issue by calling SetBounds after widget creation.
Noticed this issue while running linux tests on xvfb with a screen size smaller than the default electron window size (resulted in a failed test).
> fix: ensure widget size is set correctly on linux on small screens

- docs/api/browser-window.md
- lib/browser/api/base-window.ts
- shell/browser/api/electron_api_base_window.cc
- shell/browser/api/electron_api_base_window.h
- shell/browser/native_window.cc
- shell/browser/native_window.h
- shell/browser/native_window_mac.h
- shell/browser/native_window_mac.mm
- shell/browser/native_window_views.cc
- shell/browser/native_window_views.h
- spec-main/api-browser-window-spec.ts
Closes https://github.com/electron/electron/issues/28623.
Adds the corresponding `isFocusable` method to existing `BrowserWindow.setFocusable()`. As noted in the issue, there are myriad use cases where one would want to know the value of a   window's focusability without needing to manually keep track of various calls to `setFocusable`.
Notes: Added `BrowserWindow.isFocusable()` to determine whether a window is focusable.
> feat: add BrowserWindow.isFocusable()

- shell/browser/native_window.cc
- shell/browser/native_window_mac.h
- shell/browser/native_window_mac.mm
- shell/browser/ui/cocoa/electron_ns_window.mm
- shell/browser/ui/cocoa/electron_ns_window_delegate.mm
- spec-main/api-browser-window-spec.ts
- spec-main/chromium-spec.ts
Closes https://github.com/electron/electron/issues/25426.
Closes https://github.com/electron/electron/issues/25427.
`[NSWindow -toggleFullScreen]` is an asynchronous operation, which means that it's possible to call it while a fullscreen transition is currently in process. As such, this can create weird behavior (incl. phantom windows and missing traffic lights) and so we want to queue up transitions until the previous ones have completed. We do this by tracking when fullscreen transitions begin and end, and scheduling those transitions to execute in order after any current transitions complete.
cc @MarshallOfSound @nornagon @zcbenz 
Notes: Fixed an issue where multiple calls to `window.setFullScreen` could cause problems.
> fix: handle async nature of [NSWindow -toggleFullScreen]

- patches/chromium/.patches
- patches/chromium/cherry-pick-8c3eb9d1c409.patch
[M86-LTS merge] x11/ozone: fix two edge cases
WindowTreeHost::OnHostMovedInPixels() may trigger a nested message
loop (tab dragging), which when the stack unravels means this may
be deleted. This adds an early out if this happens.
X11WholeScreenMoveLoop has a similar issue, in so far as notifying
the delegate may delete this.
BUG=1185482
TEST=WindowTreeHostPlatform.DeleteHostFromOnHostMovedInPixels
(cherry picked from commit 5e3a738b1204941aab9f15c0eb3d06e20fefd96e)
(cherry picked from commit 8ad84a8e7882275fb32f938fd0adc04d1a2a5773)
Change-Id: Ieca1c90b3e4358da50b332abe2941fdbb50c5c25
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2743555
Reviewed-by: Thomas Anderson <thomasanderson@chromium.org>
Commit-Queue: Scott Violet <sky@chromium.org> …
> chore: cherry-pick 8c3eb9d1c409 from chromium

- patches/chromium/.patches
- patches/chromium/cherry-pick-6a6361c9f31c.patch
WebContents bug fix: Device capture only if web contents is valid
(cherry picked from commit a462be0883486431086c5f07cdafbd3607005a59)
(cherry picked from commit e6f11cafde08981e47ba77e71abf99a271f7a042)
Bug: 1181228
Change-Id: I0a4c9718a3c0ccb52cefa4565b9787e6912554c9
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2752235
Commit-Queue: Palak Agarwal <agpalak@chromium.org>
Cr-Original-Original-Commit-Position: refs/heads/master@{#863828}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2782122
Auto-Submit: Guido Urdaneta <guidou@chromium.org> …
> chore: cherry-pick 6a6361c9f31c from chromium

- build/args/all.gn
- script/zip_manifests/dist_zip.linux.arm.manifest
- script/zip_manifests/dist_zip.linux.arm64.manifest
- script/zip_manifests/dist_zip.linux.x64.manifest
- script/zip_manifests/dist_zip.linux.x86.manifest
- script/zip_manifests/dist_zip.mac.arm64.manifest
- script/zip_manifests/dist_zip.mac.x64.manifest
- script/zip_manifests/dist_zip.mac_mas.arm64.manifest
- script/zip_manifests/dist_zip.mac_mas.x64.manifest
- script/zip_manifests/dist_zip.win.arm64.manifest
- script/zip_manifests/dist_zip.win.ia32.manifest
- script/zip_manifests/dist_zip.win.x64.manifest
Remove pseudocode locales from Electron, which were added in https://chromium-review.googlesource.com/c/chromium/src/+/2774898 and rolled in https://github.com/electron/electron/pull/28462. We don't use these.  
See https://electronhq.slack.com/archives/CC8J5QC00/p1618961550011900?thread_ts=1618932845.005500&cid=CC8J5QC00.
Notes: none
> build: disable pseudolocales in Electron

- patches/chromium/.patches
- patches/chromium/use_idtype_for_permission_change_subscriptions.patch
- shell/browser/electron_permission_manager.cc
- shell/browser/electron_permission_manager.h
Use IDType for permission change subscriptions.
(cherry picked from commit ad1489b7c3ed705fc623cdffdc292324be9fcbfa)
Bug: 1025683
Change-Id: I3b44ba7833138e8a657a4192e1a36c978695db32
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2791431
Reviewed-by: Richard Coles <torne@chromium.org>
Reviewed-by: Yuchen Liu <yucliu@chromium.org>
Reviewed-by: Nasko Oskov <nasko@chromium.org>
Reviewed-by: Andrey Kosyakov <caseq@chromium.org>
Reviewed-by: Fabrice de Gans-Riberi <fdegans@chromium.org>
Reviewed-by: Arthur Sonzogni <arthursonzogni@chromium.org>
Reviewed-by: Illia Klimov <elklm@google.com>
Auto-Submit: Balazs Engedy <engedy@chromium.org>
Notes: Security: Backported fix to CVE-2021-21201.
> chore: cherry-pick 74c9ad9a53 from chromium

- docs/api/web-frame-main.md
- shell/browser/api/electron_api_web_frame_main.cc
- shell/browser/api/electron_api_web_frame_main.h
- spec-main/api-web-frame-main-spec.ts
- spec-main/spec-helpers.ts
Adds `WebFrameMain.visibilityState` instance property which aligns with `document.visibilityState` in the renderer.
This can be useful for telling whether a frame is visible without needing to execute any JS in the renderer.
Notes: Added `WebFrameMain.visibilityState` instance property.
> feat: add WebFrameMain.visibilityState

- docs/api/browser-window.md
This was showing up as 🔢  in https://www.electronjs.org/docs/api/browser-window#wingetmediasourceid.
Notes: none
> docs: fix unintentional emoji in win.getMediaSourceId description

- .github/ISSUE_TEMPLATE/bug_report.yml
I removed this in #28136 but the GitHub UI changed since then to remove the extra comment section, so let's add this back.
Notes: none
> chore: restore "Additional Information" section in bug report template

- shell/common/platform_util.cc
- spec-main/api-shell-spec.ts
Fixes #28029. This has been broken in the renderer since it was introduced (by me 😳 ) in #25114.
Notes: Fixed a crash when calling `shell.trashItem()` from the renderer process.
> fix: shell.trashItem crash when called in renderer

- shell/browser/api/electron_api_app.cc
- shell/browser/extensions/electron_extension_host_delegate.cc
- shell/browser/extensions/electron_extensions_api_client.cc
- shell/browser/extensions/electron_extensions_api_client.h
- shell/browser/ui/inspectable_web_contents.cc
- spec-main/chromium-spec.ts
- spec-main/extensions-spec.ts
This removes one usage of `GetWebContentsFromProcessID`, which is important as there can potentially be several `WebContents` relating to a given process ID.
Previously, we were using `RenderProcessReady` to be a "backstop" for catching certain unusual paths for creation of WebContents instances. In particular, the WebContents that are created for devtools, and those that are created for guest views (specifically, mime viewer guest views, i.e. for the pdfium pdf viewer).
This PR shifts the creation of the `api::WebContents` wrapper for devtools to be explicitly created at the same time as the devtools `content::WebContents`, and similarly for extension background pages and mime view handlers (i.e. pdf viewer guest views).
Notes: none
> refactor: be more precise when creating api::WebContents

- patches/chromium/.patches
- patches/chromium/cherry-pick-6b84dc72351b.patch
M86-LTS: Ensure that BrowserContext is not used after it has been freed
Previously, it was possible for the BrowserContext to be destroyed
before ReportAnchorElementMetricsOnClick attempted to access it.
The fix uses the fact that NavigationPredictor extends
WebContentsObserver and checks that web_contents is still alive
before dereferencing BrowserContext. WebContents will always
outlive BrowserContext.
R=​lukasza@chromium.org, ryansturm@chromium.org
(cherry picked from commit 7313a810ae0b1361cbe8453bc5496654dee24c76)
Bug: 1197904
Change-Id: Iee4f126e92670a84d57c7a4ec7d6f702fb975c7e
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2821639
Reviewed-by: Ryan Sturm <ryansturm@chromium.org>
Reviewed-by: Łukasz Anforowicz <lukasza@chromium.org>
Commit-Queue: Łukasz …
> chore: cherry-pick 6b84dc72351b from chromium

- patches/v8/.patches
- patches/v8/merged_squashed_multiple_commits.patch
Merged: Squashed multiple commits.
Merged: [builtins] Fix Array.prototype.concat with @@species
Revision: 7989e04979c3195e60a6814e8263063eb91f7b47
Merged: [builtins] Harden Array.prototype.concat.
Revision: 8284359ed0607e452a4dda2ce89811fb019b4aaa
BUG=chromium:1195977
NOTRY=true
Change-Id: Ic65e4ee3c5a91dc8f55edfb07cee664a6a1d6fff
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/2826126
Cr-Commit-Position: refs/branch-heads/9.0@{#36}
Cr-Branched-From: bd0108b4c88e0d6f2350cb79b5f363fbd02f3eb7-refs/heads/9.0.257@{#1}
Cr-Branched-From: 349bcc6a075411f1a7ce2d866c3dfeefc2efa39d-refs/heads/master@{#73001}
Notes: Security: backported fix to CVE-2021-21225.
> chore: cherry-pick c87b3c1157 from v8

- patches/v8/.patches
- patches/v8/lts-m86_builtins_fix_array_prototype_concat_with_species.patch
- patches/v8/lts-m86_builtins_harden_array_prototype_concat.patch
[LTS-M86][builtins] Fix Array.prototype.concat with @@species
(cherry picked from commit 7989e04979c3195e60a6814e8263063eb91f7b47)
No-Try: true
Bug: chromium:1195977
Change-Id: I16843bce2e9f776abca0f2b943b898ab5e597e42
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/2810787
Reviewed-by: Camillo Bruni <cbruni@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#73842}
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/2823829
Commit-Queue: Jana Grill <janagrill@chromium.org>
Cr-Commit-Position: refs/branch-heads/8.6@{#77} …
> chore: cherry-pick 8ebd894186 and 1e35f64725 from v8

- patches/config.json
- patches/webrtc/.patches
- patches/webrtc/merge_m86_-_fix_race_with_sctptransport_destruction_and_usrsctp.patch
- patches/webrtc/merge_m86_-_reland_fix_race_between_destroying_sctptransport_and.patch
[Merge M86] - Fix race with SctpTransport destruction and usrsctp timer thread.
The race occurs if the transport is being destroyed at the same time as
a callback occurs on the usrsctp timer thread (for example, for a
retransmission). Fixed by slightly extending the scope of mutex
acquisition to include posting a task to the network thread, where it's
safe to do further work.
Bug: chromium:1162424
Change-Id: Ia25c96fa51cd4ba2d8690ba03de8af9e9f1605ea
Reviewed-on: https://webrtc-review.googlesource.com/c/src/+/202560
Reviewed-by: Harald Alvestrand <hta@webrtc.org>
Commit-Queue: Taylor <deadbeef@webrtc.org>
Cr-Original-Commit-Position: refs/heads/master@{#33048}
No-Try: True
No-Presubmit: True
Reviewed-on: https://webrtc-review.googlesource.com/c/src/+/215101
Reviewed-by: Mirko Bonadei …
> chore: cherry-pick d5d222b6ca and 1627015c84 from webrtc

- shell/browser/electron_permission_manager.cc
This refactors ElectronPermissionManager to avoid calling
GetWebContentsFromProcessID and instead reference the RenderFrameHost by its
ID.
Notes: none
> refactor: use rfh instead of process id in permission manager

- default_app/default_app.ts
We should not set the backgroundColor when opening a custom file / URL in the default-app. Otherwise this happens:
Regression from #22675
Notes: No longer set backgroundColor in default-app when opening custom files / URLs.
> fix: only set backgroundColor in default-app for default index.html

- patches/v8/.patches
- patches/v8/merged_squashed_multiple_commits.patch
Merged: Squashed multiple commits.
Merged: [const-tracking] Mark const field as mutable when reconfiguring
Revision: 7535b91f7cb22274de734d5da7d0324d8653d626
Merged: [const-tracking] Fix incorrect DCHECK in MapUpdater
Revision: f95db8916a731e6e5ccc0282616bc907ce06012f
BUG=chromium:1161847,chromium:1185463,v8:9233
NOTRY=true
R=​ishell@chromium.org
(cherry picked from commit 56518020bff4d0e8b82cff843c9f618c90084e42)
Change-Id: I7f46a701646e1dd67a049b2aa4ac32d05b6885f3
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/2748079
Cr-Original-Commit-Position: refs/branch-heads/8.9@{#43}
Cr-Original-Branched-From: …
> chore: cherry-pick ffde6ee0e4 from v8

- patches/chromium/.patches
- patches/chromium/cherry-pick-e4abe032f3ad.patch
Ensure that BrowserContext is not used after it has been freed
Previously, it was possible for the BrowserContext to be destroyed
before ReportAnchorElementMetricsOnClick attempted to access it.
The fix uses the fact that NavigationPredictor extends
WebContentsObserver and checks that web_contents is still alive
before dereferencing BrowserContext. WebContents will always
outlive BrowserContext.
R=​​lukasza@chromium.org, ryansturm@chromium.org
(cherry picked from commit 7313a810ae0b1361cbe8453bc5496654dee24c76)
(cherry picked from commit f782a440339fa19a44422ca5e7165cddd1cffcc9)
Bug: 1197904
Change-Id: Iee4f126e92670a84d57c7a4ec7d6f702fb975c7e
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2821639
Reviewed-by: Ryan Sturm <ryansturm@chromium.org>
Reviewed-by: Łukasz …
> chore: cherry-pick e4abe032f3ad from chromium

- patches/chromium/.patches
- patches/chromium/cherry-pick-fe20b05a0e5e.patch
M86-LTS: DevTools: expect PageHandler may be destroyed during Page.navigate
(cherry picked from commit ff5e70191ec701cce4f84aaa25cd676376253a8a)
Bug: 1188889
Change-Id: I5c2fcca84834d66c46d77a70683212c2330177a5
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2787756
Commit-Queue: Andrey Kosyakov <caseq@chromium.org>
Reviewed-by: Dmitry Gozman <dgozman@chromium.org>
Reviewed-by: Karan Bhatia <karandeepb@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#867507}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2821536
Commit-Queue: Achuith Bhandarkar <achuith@chromium.org>
Owners-Override: Achuith Bhandarkar …
> chore: cherry-pick fe20b05a0e5e from chromium

- patches/chromium/.patches
- patches/chromium/cherry-pick-fe85e04a1797.patch
Don't use BigBuffer for IPC::Message transport
* ipc/ipc_message_pipe_reader.cc
Fixed extra include.
(cherry picked from commit 85bd7c88523545ab0e497d5e7b3e929793813358)
(cherry picked from commit fad3b9ffe7c7ff82909d911c573bd185aa3b3b50)
Fixed: 1184399
Change-Id: Iddd91ae8d7ae63022b61c96239f5e39261dfb735
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2737012
Cr-Original-Original-Commit-Position: refs/heads/master@{#860010}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2779918
Reviewed-by: Adrian Taylor <adetaylor@chromium.org>
Reviewed-by: Alex Gough <ajgo@chromium.org> …
> chore: cherry-pick fe85e04a1797 from chromium

- patches/chromium/.patches
- patches/chromium/cherry-pick-1536a564d959.patch
Mojo: Properly validate broadcast events
This corrects broadcast event deserialization by adding a missing
validation step when decoding the outer message header.
(cherry picked from commit 6740adb28374ddeee13febfd5e5d20cb8a365979)
Fixed: 1195308
Change-Id: Ia67a20e48614e7ef00b1b32f7f4e5f20235be310
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2808678
Cr-Original-Commit-Position: refs/heads/master@{#870238}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2827760 …
> chore: cherry-pick 1536a564d959 from chromium

- patches/chromium/.patches
- patches/chromium/cherry-pick-7dd3b1c86795.patch
[views] Handle window deletion during HandleDisplayChange.
In principle there is no reason why the HWNDMessageHandler shouldn't be
deleted by a HandleDisplayChange() call out to the delegate, e.g. if the
change results in a change in window layout.
(cherry picked from commit 299155e5e37a77670b7969771e09e9a16b1f5612)
Bug: 1192552
Change-Id: I9fca35ff32e7037c6492f4cee7069e272059b920
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2804382
Auto-Submit: Wez <wez@chromium.org>
Commit-Queue: Scott Violet <sky@chromium.org>
Reviewed-by: Scott Violet <sky@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#869603}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2826321
Cr-Commit-Position: refs/branch-heads/4430@{#1291} …
> chore: cherry-pick 7dd3b1c86795 from chromium

- patches/chromium/.patches
- patches/chromium/m86-lts_add_null_pointer_check_in_renderwidgethostinputeventrouter.patch
- patches/chromium/m86-lts_add_weak_pointer_to_rwhier_framesinkidownermap_and.patch
M86-LTS: Add null pointer check in RenderWidgetHostInputEventRouter
We have some crashes in RenderWidgetHostInputEventRouter class, we are
adding some null pointer check in this class to avoid the crash.
(cherry picked from commit 5f47666b79ac7ded20e1c7657037498561bd3352)
Bug: 1155297
Change-Id: I3b63d5748523ae2ce8ab469832adfc75d586e411
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2818680
Reviewed-by: Charlie Reis <creis@chromium.org>
Commit-Queue: Lan Wei <lanwei@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#871108}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2838329
Reviewed-by: Lan Wei <lanwei@chromium.org>
Commit-Queue: Achuith Bhandarkar <achuith@chromium.org>
Owners-Override: Achuith Bhandarkar …
> chore: cherry-pick 8f054c5df2 and de1dbdb608 from chromium

- script/release/publish-to-npm.js
Sometimes the publish succeeds and the tagging fails, on reruns the publish then fails because you can't publish over an already published release.
This change checks if the npm version is already published before trying to publish it again which will allow reruns of this step in sudowoodo to work correctly.
> build: fix releases that failed halfway through npm publish actions

- patches/chromium/.patches
- patches/chromium/cherry-pick-406ae3e8a9a8.patch
M86-LTS: Mojo: Properly validate broadcast events
This corrects broadcast event deserialization by adding a missing
validation step when decoding the outer message header.
(cherry picked from commit 6740adb28374ddeee13febfd5e5d20cb8a365979)
Fixed: 1195308
Change-Id: Ia67a20e48614e7ef00b1b32f7f4e5f20235be310
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2808678
Cr-Original-Commit-Position: refs/heads/master@{#870238}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2837712
Auto-Submit: Achuith Bhandarkar <achuith@chromium.org>
Reviewed-by: Artem Sumaneev <asumaneev@google.com>
Commit-Queue: …
> chore: cherry-pick 406ae3e8a9a8 from chromium

- patches/chromium/.patches
- patches/chromium/m90_devtools_expect_pagehandler_may_be_destroyed_during.patch
[m90] DevTools: expect PageHandler may be destroyed during Page.navigate
(cherry picked from commit ff5e70191ec701cce4f84aaa25cd676376253a8a)
Bug: 1188889
Change-Id: I5c2fcca84834d66c46d77a70683212c2330177a5
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2787756
Commit-Queue: Andrey Kosyakov <caseq@chromium.org>
Reviewed-by: Dmitry Gozman <dgozman@chromium.org>
Reviewed-by: Karan Bhatia <karandeepb@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#867507}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2798538
Cr-Commit-Position: refs/branch-heads/4430@{#968}
Cr-Branched-From: e5ce7dc4f7518237b3d9bb93cccca35d25216cbe-refs/heads/master@{#857950}
Notes: Security: Backported fix to CVE-2021-21202.
> chore: cherry-pick f79751ee25 from chromium

- patches/chromium/.patches
- patches/chromium/cherry-pick-66b9ad64f4a4.patch
[merge][90][GeneratedCodeCache] Copy large data before hashing and writing
- Makes a copy before hashing and writing large code entries.
(cherry picked from commit cea0cb8eee9900308d9b43661e9faca449086940)
Bug: chromium:1194046
Change-Id: Id5a6e6d3a04c83cfed2f18db53587d654d642fc0
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2807255
Reviewed-by: Nasko Oskov <nasko@chromium.org>
Reviewed-by: Mythri Alle <mythria@chromium.org>
Commit-Queue: Bill Budge <bbudge@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#870064}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2827763
Commit-Queue: Nasko Oskov <nasko@chromium.org>
Reviewed-by: Bill Budge …
> chore: cherry-pick 66b9ad64f4a4 from chromium

- patches/chromium/.patches
- patches/chromium/cherry-pick-1028ffc9bd83.patch
M86-LTS: [GeneratedCodeCache] Copy large data before hashing and writing
- Makes a copy before hashing and writing large code entries.
(cherry picked from commit cea0cb8eee9900308d9b43661e9faca449086940)
Bug: chromium:1194046
Change-Id: Id5a6e6d3a04c83cfed2f18db53587d654d642fc0
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2807255
Reviewed-by: Nasko Oskov <nasko@chromium.org>
Reviewed-by: Mythri Alle <mythria@chromium.org>
Commit-Queue: Bill Budge <bbudge@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#870064}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2838077
Reviewed-by: Bill Budge <bbudge@chromium.org>
Commit-Queue: Achuith Bhandarkar <achuith@chromium.org> …
> chore: cherry-pick 1028ffc9bd83 from chromium

- patches/v8/.patches
- patches/v8/merged_compiler_fix_a_bug_in_visitspeculativeintegeradditiveop.patch
Merged: [compiler] Fix a bug in VisitSpeculativeIntegerAdditiveOp
Revision: 9313c4ce3f32ad81df1c65becccec7e129181ce3
BUG=chromium:1199345
NOTRY=true
R=nicohartmann@chromium.org
Change-Id: I0ee9f13815b1a7d248d4caa506c6930697e1866c
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/2839559
Cr-Commit-Position: refs/branch-heads/9.0@{#41}
Cr-Branched-From: bd0108b4c88e0d6f2350cb79b5f363fbd02f3eb7-refs/heads/9.0.257@{#1}
Cr-Branched-From: 349bcc6a075411f1a7ce2d866c3dfeefc2efa39d-refs/heads/master@{#73001}
Notes: Security: backported fix to CVE-2021-21227.
> chore: cherry-pick aa2154a9c1 from v8

- docs/api/session.md
- shell/browser/api/electron_api_session.cc
- shell/browser/api/electron_api_session.h
- spec-main/api-session-spec.ts
For apps that have multiple sessions that have their own settings / config storage it is sometimes a requirement to store those settings / config options per-session.  Currently the paths to these sessions are predictable but not guaranteed, this use case is made way safer by just exposing this path.
Notes: Added new `session.storagePath` API to get the path on disk for session-specific data
> feat: add session.storagePath to get path on disk for session data

- spec-main/api-shell-spec.ts
This test is timing out consistently on windows / ia32 for unknown reasons. Ref #28748.
Notes: none
> test: disable shell.trashItem in renderer test on win-ia32

- patches/angle/.patches
- patches/angle/d3d11_skip_blits_if_there_is_no_intersection_of_dest_areas.patch
- patches/config.json
D3D11: Skip blits if there is no intersection of dest areas
Blit11 would clip the destination rectangle with the destination size
but ignore the result. gl::ClipRectangle returns false when the
rectangles do not intersect at all, indicating the blit can be skipped.
This could lead to an out-of-bounds write to the GPU memory for the
destination texture.
Mark ClipRectangle as nodiscard to prevent future issues.
Bug: chromium:1199402
Change-Id: I260e82d0917b8aa7e7887f2c9f7ed4b1a03ba785
Reviewed-on: https://chromium-review.googlesource.com/c/angle/angle/+/2836786
(cherry picked from commit b574643ef28c92fcea5122dd7a72acb42a514eed)
Reviewed-on: …
> chore: cherry-pick ed5f62c36d from angle.

- .gitignore
- docs/development/source-code-directory-structure.md
This functionality was removed in
https://github.com/electron/electron/pull/26701.
Notes: none
> docs: Remove mentions of the old external_binaries directory

- patches/chromium/.patches
- patches/chromium/privacy_budget_remove_unnecessary_kcanvasreadback_metrics.patch
[privacy_budget] Remove unnecessary kCanvasReadback metrics.
The identifiability metrics recorded under kCanvasReadback surface type
used two conflicting sources as inputs: the CanvasRenderingContext
type, and the paint-op digest.
There are known collisions between resulting IdentifiableSurface values
from the two sources, which makes it impossible to losslessly separate
the two during analysis.
While the fact that a canvas readback happened is interesting, it
doesn't help determine the observed diversity of clients. Hence this
change removes one of those sources: the CanvasRenderingContext type.
* third_party/blink/renderer/core/offscreencanvas/offscreen_canvas.cc
M86 does not have the code removed in original CL.
* …
> chore: cherry-pick 809231f0c9 from chromium.

- patches/chromium/.patches
- patches/chromium/cherry-pick-5745eaf16077.patch
[privacy_budget] Remove unnecessary kCanvasReadback metrics.
The identifiability metrics recorded under kCanvasReadback surface type
used two conflicting sources as inputs: the CanvasRenderingContext
type, and the paint-op digest.
There are known collisions between resulting IdentifiableSurface values
from the two sources, which makes it impossible to losslessly separate
the two during analysis.
While the fact that a canvas readback happened is interesting, it
doesn't help determine the observed diversity of clients. Hence this
change removes one of those sources: the CanvasRenderingContext type.
* third_party/blink/renderer/core/offscreencanvas/offscreen_canvas.cc
M86 does not have the code removed in original CL.
* …
> chore: cherry-pick 5745eaf16077 from chromium

- docs/development/source-code-directory-structure.md
Follow up to #28859 the `tools` directory does not exist anymore either.  We migrated everything to `build/` or `scripts/`
> docs: the tools folder does not exist anymore

- script/lib/util.py
This is like 6 year old tech debt that I just stumbled upon, this might blow up the nightly tomorrow but I honestly wouldn't be able to explain why if it does.  Anyway, SSL is a good thing lol.
Notes: none
> build: actually use SSL when downloading things via python

- patches/chromium/.patches
- patches/chromium/add_crashkeys_to_identify_where_target_is_assigned_to_a_stale_value.patch
- patches/chromium/add_null_pointer_check_in_renderwidgethostinputeventrouter.patch
- patches/chromium/add_weak_pointer_to_rwhier_framesinkidownermap_and_rwhier_targetmap.patch
Add crashkeys to identify where |target| is assigned to a stale value
In RenderWidgetHostInputEventRouter::DispatchTouchscreenGestureEvent, the
|target|'s address is changed and assigned to a stale value.
(cherry picked from commit b7758233216445264174dd249e7565ab4849daa6)
Bug: 1155297
Change-Id: Id87175059b6d74eeac165abe0ccfd5f6c25d659a
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2764892
Commit-Queue: Lan Wei <lanwei@chromium.org>
Reviewed-by: Alex Moshchuk <alexmos@chromium.org>
Reviewed-by: James MacLean <wjmaclean@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#867419}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2828850
Auto-Submit: Lan Wei <lanwei@chromium.org>
Reviewed-by: Adrian Taylor <adetaylor@google.com> …
> chore: cherry-pick c768895b3f, 58393127e7 and c2f6803bdd from chromium

- shell/browser/native_window.cc
- spec-main/api-app-spec.ts
Fixes #28774. This moves the trigger for emitting the window-all-closed event until after the BrowserWindow has been marked destroyed.
Notes: Fixed the window-all-closed event being emitted while the last BrowserWindow was still in the process of being closed.
> fix: emit window-all-closed after closing the window

- build/dump_syms.py
This PR fixes the python 3 error found when generating breakpad symbols on our release builds:
https://app.circleci.com/pipelines/github/electron/electron/38729/workflows/85a2e978-9b30-4540-ad18-74dc974f0f61/jobs/854168
Notes: none
> build: fix dump_syms.py to work with python 3

- appveyor.yml
The chromium roll introduced in #28676 broke WOA testing to the point that it consistently times out after 60 minutes.  This PR temporarily disables WOA test on master until the issue is resolved so that we don't overwhelm WOA CI.
Notes: none
> build: temporarily disable WOA testing

- lib/browser/api/app.ts
Refs: https://github.com/electron/electron/pull/28909#issuecomment-828739482
Notes: Restored cross-platform noop implementation of `app.setAppUserModelId`
> fix: provide no-op implementation of app.setUserModelId

- patches/chromium/.patches
- patches/chromium/cherry-pick-668cf831e912.patch
Never fail in ReceiverSet::Add
Because of how UniqueReceiverSet is implemented and used, it is
dangerous to allow Add() to fail: callers reasonably assume that added
objects are still alive immediately after the Add() call.
This changes ReceiverId to a uint64 and simply CHECK-fails on
insert collision.
This fundamentally increases binary size of 32-bit builds, because
a widely used 32-bit data type is expanding to 64 bits for the sake
of security and stability. It is effectively unavoidable for now, and
also just barely above the tolerable threshold.
A follow-up (but less backwards-mergeable) change should be able to
reduce binary size beyond this increase by consolidating shared
code among ReceiverSet template instantiations.
Fixed: 1185732
Change-Id: …
> chore: cherry-pick 668cf831e912 from chromium

- build/npm-run.py
Fix error seen when building latest master:
<details>
<summary>Build Failure</summary>
```
electron on git:master ❯ e build                                                       2:07PM
Running "e load-xcode --quiet"
Running "ninja -j 200 electron" in /Users/codebytere/Developer/electron-gn/src/out/Testing
[103/4101] ACTION //electron:npm_pre_flight_b..._definitions(//build/toolchain/mac:clang_x64)
FAILED: gen/electron/npm_pre_stamps/npm_pre_flight_build_electron_definitions.stamp
python3 ../../electron/build/npm-run.py --silent pre-flight -- --stamp /Users/codebytere/Developer/electron-gn/src/out/Testing/gen/electron/npm_pre_stamps/npm_pre_flight_build_electron_definitions.stamp
Traceback (most recent call last):
File "/Users/codebytere/Developer/electron-gn/src/out/Testing/../../electron/ …
```
> build: fix npm-run python bytes error

- patches/chromium/.patches
- patches/chromium/cherry-pick-02f5ef8c88d7.patch
Fix removal of observers in NetworkStateNotifier
The NetworkStateNotifier has a per-thread list of observer pointers. If
one is deleted mid-iteration, what we do is replace the pointer in the
list with a 0, and add the index to the zeroed list of observers to
remove after iteration completes. Well, the removal step was broken
for cases where there were multiple elements to remove. It didn't adjust
for the fact that the indexes shifted after each removal.
(cherry picked from commit 5d34987de6cffb8d747c5ed16e82614e9146cc0a)
Bug: 1170148
Change-Id: I446acaae5f8a805a58142848634a0ee8c5f90882
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2727306
Reviewed-by: Kentaro Hara <haraken@chromium.org>
Commit-Queue: Josh Karlin <jkarlin@chromium.org> …
> chore: cherry-pick 02f5ef8c88d7 from chromium

- patches/chromium/disable_color_correct_rendering.patch
- patches/chromium/notification_provenance.patch
- patches/chromium/support_mixed_sandbox_with_zygote.patch
- shell/browser/electron_browser_client.cc
- shell/browser/electron_browser_client.h
- shell/browser/notifications/platform_notification_service.cc
- shell/browser/notifications/platform_notification_service.h
This removes another usage of GetWebContentsFromProcessID, by plumbing the
RenderFrameHost instead of the RenderProcessHost through to
DisplayNotification. Depends on
https://chromium-review.googlesource.com/c/chromium/src/+/2781233 so this is
based on the Chromium roll for now. Will re-target once the roll lands.
Notes: none
> refactor: plumb RFH instead of RPH for notifications

- .circleci/config.yml
Adds the variable `context: release-env` to the `publish-macos` build step in CircleCI. This matches publish-linux and is required for uploading releases. 
Notes: none
> build: add release-env context to publish-macos

- patches/chromium/.patches
- patches/chromium/cherry-pick-f37149c4434f.patch
[Autofill] Don't show autofill dropdown for element outside the viewport
Details are in the linked bug.
Also cherry pick crrev/c/2682341 and a part of crrev/c/2628287 to fix
failing tests and compile errors.
(cherry picked from commit 53a4f38ee5d44bd935d176cc89e3e59fd0a3970e)
Bug: 1172533,1173297
Change-Id: Iee429cac167ccdb0cd74acf57fc5f7c3821883b1
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2675932
Commit-Queue: Mohamed Amir Yosef <mamir@chromium.org>
Reviewed-by: Vasilii Sukhanov <vasilii@chromium.org>
Reviewed-by: Evan Stade <estade@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#851718}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2822155
Commit-Queue: Jana Grill <janagrill@google.com>
Reviewed-by: Achuith Bhandarkar …
> chore: cherry-pick f37149c4434f from chromium

- shell/browser/browser.h
- shell/browser/browser_linux.cc
- shell/browser/browser_mac.mm
After #28127 this is Windows only https://github.com/electron/electron/blob/56c3103e73ac71bd6845a31a2e37f5ffd0810be7/shell/browser/api/electron_api_app.cc#L1538-L1541
> chore: Browser::SetAppUserModelID is Windows only

- docs/api/browser-window.md
For loading a local file the loadFile API is a better way to load any html file in the Renderer process.
Have changed it in the example.
Have edited a example in BrowserWindow section of electron docs, to load local files using loadFile() api instead of loadURL() api. 
Notes: none.
> docs: Added loadFile instead of loadURL in BrowserWindow documentation example

- shell/common/node_bindings.cc
When `uv_run()` resulted in invocation of JS functions the microtask
queue checkpoint in Node's CallbackScope was a no-op because the
expected microtask queue policy was `kExplicit` and Electron ran under
`kScoped` policy. This change switches policy to `kExplicit` right
before `uv_run()` and reverts it back to original value after `uv_run()`
completes to provide better compatibility with Node.
cc @codebytere since you touched this code.
Notes: Allow Node.js to manage microtasks queue by using explicit microtasks policy before calling `uv_run()`
> fix: allow Node.js to manage microtasks queue

- docs/README.md
- docs/tutorial/repl.md
Looks like this guide has been outdated for a while. A few changes:
* Removed global install commands
* Adds link to why REPL doesn't work on Windows
* Removes reference to ancient `electron-prebuilt` module
* Adds this doc under "Debugging and Testing"
Notes: none
> docs: update REPL guide

- shell/browser/native_window_mac.mm
- spec-main/api-browser-window-spec.ts
Closes https://github.com/electron/electron/issues/28927.
If a sheet is attached to the window when we call `[window_ performClose:nil]`, the window won't close properly
even after the user has ended the sheet. Ensure it's closed before calling `[window_ performClose:nil]`. Also fix an issue where `endSheet` may have been called with a `nil` sheet, triggering the following:
```sh
2021-05-03 11:39:00.871 Electron[30923:22268077] endSheet:returnCode: requires a non-nil sheet
```
Notes: Fixed an issue where the window couldn't be closed if a user tried to quit with a message box showing.
> fix: close attached sheet on window close

- lib/browser/guest-view-manager.ts
- shell/browser/api/electron_api_web_view_manager.cc
- shell/browser/web_view_manager.cc
- shell/browser/web_view_manager.h
- typings/internal-ambient.d.ts
`element_instance_id_to_guest_map_` was used by `GetGuestByInstanceID`, which was removed from `BrowserPluginGuestManager` by
https://chromium-review.googlesource.com/c/chromium/src/+/2401031
> chore: remove unused element_instance_id_to_guest_map_ from WebViewManager

- build/dump_syms.py
Reverts #28910 for 13-x-y to fix error when generating breakpad symbols on our release builds:
https://app.circleci.com/pipelines/github/electron/electron/39027/workflows/31bac545-4bf8-43fb-97cc-eb4c33f34e61/jobs/861006
Notes: none
> revert: fix dump_syms.py to work with python 3

- lib/browser/api/dialog.ts
- lib/browser/api/web-contents.ts
- lib/common/web-view-events.ts
- lib/renderer/web-view/guest-view-internal.ts
> refactor: use "as const" for constant mappings

- lib/browser/api/dialog.ts
Just call `setupOpenDialogProperties` / `setupSaveDialogProperties` directly
> refactor: remove unnecessary setupDialogProperties

- docs/api/webview-tag.md
Make it easier to jump to the docs page on BrowserView. ✨ 
Notes: none.
> docs: link to `BrowserView` from `webview` page

- .circleci/config.yml
These have been failing due to out of disk space for months now, they provide no signal (we don't even get alerts for them in #bot-nightly-ci) and they consume our valuable and limited macOS resources early in the morning when they could be going to actual nightly/beta/stable release jobs.
This is also part of a wider plan I have to greatly simplify our CI config with the eventual goal of using CircleCI setup workflows which will allow us to do substantially cooler and cleverer things with regards to how we run CI.
It's also worth noting that the `chromium-upgrade-branches` pattern hasn't matched chromium upgrades for a long time, it's been `roller/chromium/*` since we brought roller bot to life
> build: remove macOS nightly release tests

- shell/browser/native_browser_view_mac.mm
Closes https://github.com/electron/electron/issues/28405. This was originally added in https://github.com/electron/electron/pull/27147, but it turns out that solution masked a different root problem, which was what I later solved in https://github.com/electron/electron/pull/28268. However, this meant that the previous PR was relying on incorrect assumptions, and would thus offset the bounds _too far_. This correct it so that all offsetting is handled in a single place for BrowserViews and we can once more safely assume that defaulting to `0, 0` for `x, y` in the case of no drag regions will produce the desired drag configuration. 
Tested with:
- https://gist.github.com/b9c5a45bf59f6ba748041d000414e571
- https://gist.github.com/9dd56c8dae033bcb77cd107259591121
- …
> fix: drag region BrowserView calculations on macOS

- patches/chromium/allow_in_process_windows_to_have_different_web_prefs.patch
Follow up to #28983, we can remove these prefs from our webprefs patch too
> chore: remove unused patched webprefs

- lib/renderer/web-view/web-view-impl.ts
- spec-main/webview-spec.ts
https://github.com/electron/electron/blob/961b74b2ac335abf99dcf50ce512f58cb250be80/lib/renderer/web-view/web-view-impl.ts#L165 is not equal when `contextIsolation` is enabled
Notes: Fixed `<webview>` `focus` / `blur` events not working with `contextIsolation` enabled.
> fix: <webview> focus / blur events don't work with contextIsolation enabled

- lib/browser/guest-view-manager.ts
- lib/common/web-view-events.ts
- lib/renderer/web-view/guest-view-internal.ts
- lib/renderer/web-view/web-view-init.ts
The `guestInstanceId` is not used in the `focus-change` handler. It is also the same as webContents ID that we already know.
> refactor: 'focus-change' does not need guestInstanceId

- spec-main/api-native-theme-spec.ts
I've seen this flake several times, I assume it's a race condition between the value updating in the main process and the propagation to the renderer vs our executeJS IPC message.
Notes: none
> test: attempt to fix flaky nativeTheme spec

- lib/browser/desktop-capturer.ts
- lib/browser/init.ts
- lib/browser/rpc-server.ts
- lib/common/api/clipboard.ts
- lib/isolated_renderer/init.ts
- lib/renderer/init.ts
- lib/renderer/security-warnings.ts
- lib/renderer/web-view/guest-view-internal.ts
- lib/renderer/web-view/web-view-element.ts
- lib/renderer/web-view/web-view-impl.ts
- lib/renderer/web-view/web-view-init.ts
- lib/renderer/window-setup.ts
- lib/sandboxed_renderer/init.ts
`require` returns `any`, which is dangerous. Let's use `as typeof` with `import type` trick to solve this.
> chore: make raw requires type-safe

- docs/tutorial/recent-documents.md
When an application menu is added before 'whenReady' all items seem to work except 'recent documents'
This causes the issue listed here: https://github.com/electron/electron/issues/17388
Notes: none
> docs: menu must be added on whenReady

- patches/node/.patches
- patches/node/node-api_faster_threadsafe_function.patch
Backports: https://github.com/nodejs/node/pull/38506
See: https://github.com/electron/electron/pull/28957 for discussion
In few words, `napi_threadsafe_function` was significantly slower in Electron due to scheduling each call on the next uv tick. We've patched electron in #28957 to let microtasks queue execute from within `uv_run()` and now this backports a patch that makes `napi_threadsafe_function` calls scheduled while one was running happen on the same tick. Fixing the performance issue.
cc @codebytere @deepak1556 @zcbenz 
Notes: Improved performance of `napi_threadsafe_function`
> chore: cherry-pick 7abc7e45b2 from node

- lib/renderer/web-view/web-view-attributes.ts
Simpifies `<webview>` implementation for upcoming refactoring to use `contextBridge` when `contextIsolation` is enabled.
> refactor: invoke loadURL in SrcAttribute instead of sending IPC directly

- lib/renderer/web-view/web-view-attributes.ts
- lib/renderer/web-view/web-view-element.ts
- lib/renderer/web-view/web-view-impl.ts
Simpifies `<webview>` implementation for upcoming refactoring to use `contextBridge` when `contextIsolation` is enabled.
> refactor: remove setupWebViewAttributes gymnastics

- patches/chromium/.patches
Revert "Experiment on Canary: Enable BackupRefPtr (15th round, Win & Android)"
This reverts commit 0f25421a49f714ee2553e6b249924ed874cefc9e.
Reason for revert: build triggered, keep the branch clean
> Experiment on Canary: Enable BackupRefPtr (15th round, Win & Android)
>
> PS1: CheckedPtr rewrite generated by rewrite-multiple-platforms.sh
> on beece242e447f48499bbf0fcc0b71fb21e0c7aba then rebased on top of
> branch-heads/4500 (no conflicts)
> PS2: Enable and configure BRP + clang.gni workaround
> PS3: Apply a build break workaround (crrev.com/c/2879256)
>
> More details here:
> https://docs.google.com/document/d/1zKoTPWl_lEBmQcSSpKtXSjWXMs-1oWRwZp8dCu3KRyA/edit?resourcekey=0-3tbMv2PBZnCHFvHcSPS7NQ#heading=h.c0uts5ftkk58
>
> Bug: 1073933
> Change-Id: …
> chore: cherry-pick 82434206f306 from chromium

- lib/isolated_renderer/init.ts
- lib/renderer/web-view/web-view-constants.ts
- lib/renderer/web-view/web-view-element.ts
- lib/renderer/web-view/web-view-impl.ts
- lib/renderer/web-view/web-view-init.ts
Simpifies `<webview>` implementation for upcoming refactoring to use `contextBridge` when `contextIsolation` is enabled.
> refactor: use WeakMap instead of hidden V8 properties to store WebViewImpl

- .circleci/config.yml
Precursor to setup workflows, having better usage of built-in circle features instead of YAML templating everything
> build: use executors instead of YAML templating

- shell/renderer/api/electron_api_web_frame.cc
- shell/renderer/electron_renderer_client.cc
- shell/renderer/electron_renderer_client.h
- shell/renderer/renderer_client_base.cc
- shell/renderer/renderer_client_base.h
- spec-main/spellchecker-spec.ts
- spec/fixtures/module/preload-electron.js
Backport of #29053
Notes: Fixed `webFrame` spell checker APIs crashing when called in sandboxed renderer.
> fix: webFrame spell checker APIs crashing in sandboxed renderers

- shell/browser/native_window_mac.h
- shell/browser/native_window_mac.mm
Closes https://github.com/electron/electron/issues/29061.
We set the radius on a frameless BrowserWindow with vibrancy and then didn't previously update it when fullscreen transitions happened, which had the potential to create weird side-effects and also to work incorrectly when the window was itself in fullscreen mode.
Before in non-fullscreen:
Before in fullscreen (must click, hard to see otherwise that there's a little weird white bit):
Notes: Fixed the possibility for incorrect visual artifacts when using vibrancy and making frameless windows fullscreen on macOS.
> fix: update NSView radii on fullscreen transition

- package.json
- script/release/get-url-hash.js
- script/release/prepare-release.js
- script/release/release.js
- yarn.lock
During the sudowoodo release phase we download all the release assets and manually verify their hashes.  Previously this happened via the `sumchecker` module and downloading every asset in parallel onto the local heroku node.
This was terribly slow, although our assets only sum to around ~10GB the "validate assets" step took almost 20 minutes this morning.  It's slow for a few reasons but mostly (a) we're severely bandwidth limited, the download speed on heroku isn't that fast and (b) we're disk / CPU limited, heroku's I/O performance isn't great either.
I spun up a quick lambda function in our AWS account that takes a URL and a hashing algorithm and _very_ quickly returns the hash.  I managed to validate the checksums of every release asset in the beta 32 release (that went out this …
> build: offload hash checking logic to lambda worker during release

- shell/common/api/electron_api_v8_util.cc
- shell/common/gin_converters/net_converter.cc
- shell/common/gin_converters/std_converter.h
- shell/common/gin_helper/callback.cc
- shell/common/gin_helper/event_emitter.cc
- shell/common/gin_helper/persistent_dictionary.h
- shell/common/gin_helper/promise.h
- shell/common/gin_helper/wrappable.cc
- shell/common/v8_value_converter.cc
- shell/renderer/api/context_bridge/object_cache.cc
- shell/renderer/api/electron_api_context_bridge.cc
- shell/renderer/api/electron_api_web_frame.cc
- shell/renderer/electron_sandboxed_renderer_client.cc
A bit more readable perhaps. Also use this style of casting consistently.
Also make `GetWebFrameId` take a `v8::Object` handle to match https://github.com/electron/electron/blob/2b84d79b185a550684d60b3902a2cb02a90e61dc/shell/renderer/api/electron_api_context_bridge.cc#L59-L67
cc @nornagon 
> refactor: replace v8::Local<T>::Cast() with As<T>()

- script/release/release.js
The node.js SHASUM file is subtly different to SHASUM256 for Electron
Notes: none
> build: merge double space in SHASUM validation logic

- .circleci/config.yml
Auto Ninja prints build stats for us, and handles exit codes nicely and such 😄 
> build: use autoninja to print stats

- patches/chromium/.patches
- patches/chromium/make_include_of_stack_trace_h_unconditional.patch
I'll post a longer explanation in Slack as this is very specific to our goma infra but the TLDR is remove these two lines makes the build 33% faster with no negatives afaik 🤷 Will land just to master initially to see how it goes
> build: unconditionally include stack_trace.h

- .circleci/config.yml
Currently tests are split into a 10minute test run and a 5 minute test run, in theory we could do 7:30 and 7:30 😄 
> build: split tests by timing to make it more even

- lib/browser/api/menu.ts
Closes #29088.
Fixed an issue where the void function `Menu.setApplicationMenu` would return a value on some platforms.
Notes: Fixed an issue where the void function `Menu.setApplicationMenu` would return a value on some platforms.
> fix: do not return value from `Menu.setApplicationMenu`

- shell/browser/feature_list.cc
This feature no longer has any effect.
Notes: none
> chore: remove no-op EnableWebComponentsV0 feature

- .circleci/config.yml
We don't need to declare the same job 4 times, we can declare it once and give it a new name each time we require it.
> build: dedupe release summary jobs

- .circleci/config.yml
`checkout-fast` was slower and `checkout-and-save-cache` sometimes didn't save a cache...
Basically this unifies our checkout-and-save-cache steps under the existing electron-build command so less steps are duplicated and renames checkout-fast and checkout-and-save-cache to be more aligned with what they actually do.
* `checkout-fast` --> `checkout-for-workspace`: Checks out a fully synced directory and then persists to a workspace layer
* `checkout-and-save-cache` --> `make-src-cache`: Ensures that there is a valid and accurate src cache for this commit.  It doesn't always check it out, sometimes it early outs via the src-cache-marker
> build: rename and unify checkout-fast and checkout-and-save-cache

- .circleci/config.yml
This removes all our duplicated store_artifact commands and stores all artifacts in a single command which should be dramatically faster and is also easier to read.
> build: store artifacts in simpler way

- docs/tutorial/mac-app-store-submission-guide.md
Close https://github.com/electron/electron/issues/28428.
The Mac App Store Submission Guide has been quite outdated that, it is impossible to make a signed app that can actually run by following it.
I have revised the guide to add latest information about provisioning profile and different kinds of certificates, and the instructions are now using `electron-osx-sign` instead of a custom script that does not run.
Notes: none
> docs: revise Mac App Store Submission Guide

- docs/api/web-contents.md
- docs/api/webview-tag.md
The existing documentation for the `findNext` option of `findInPage` reads as if `findNext: false` is for a first request, and `findNext: true` is for a follow up request. However, it's actually the opposite - `findNext: true` maps to Chromium's `new_session` option ([code](https://github.com/electron/electron/blob/0a1b26b1d5d99f22c2b837176c28b66d7b050227/shell/browser/api/electron_api_web_contents.cc#L2647)), which should only be used for first requests. I've tried to make the description more specific so it's clear which value to use.
Notes: none
> docs: Improve description of findInPage options

- .circleci/config.yml
Moves the logic that saves the `.ninja_log` to our unified artifacts store step so that we persist the ninja log in release builds too.  This will be helpful for debugging release build performance issues.
> build: save the ninja log for release builds too

- .circleci/config.yml
As in title.  Trying to reduce dependencies on electron bot.
> build: make patch auto fixes come from PatchUp rather than Electron Bot

- lib/renderer/security-warnings.ts
- spec-main/security-warnings-spec.ts
Closes #29020.
Notes: Fixed an incorrect warning about enableRemoteModule being issued when the option was undefined (and thus defaulting to false).
> fix: don't warn about enableRemoteModule when it's undefined

- lib/renderer/web-view/guest-view-internal.ts
- lib/renderer/web-view/web-view-element.ts
- lib/renderer/web-view/web-view-impl.ts
- spec-main/webview-spec.ts
- typings/internal-electron.d.ts
Backport of #26289
Notes: Fixed an issue where events on webview elements were missing properties if contextIsolation was enabled.
> fix: [webview] fix missing properties on events when contextIsolation: true

- docs/api/browser-window.md
- shell/browser/native_window_mac.h
- shell/browser/native_window_mac.mm
For Electron <= 12, using vibrancy with titleBarStyle together requires a small hack added by https://github.com/electron/electron/pull/11886 and https://github.com/electron/electron/pull/12157, because titleBarStyle was implemented by force showing original titlebar buttons.
But after https://github.com/electron/electron/pull/27489, the implementation of titleBarStyle no longer uses original titlebar buttons, and the old hack can be removed, which will fix https://github.com/electron/electron/issues/28782.
Notes: Fix using vibrancy with titleBarStyle together resulting in weird window shadow on macOS.
> fix: remove background color hack in vibrancy

- shell/renderer/electron_render_frame_observer.cc
- shell/renderer/electron_renderer_client.cc
- shell/renderer/electron_sandboxed_renderer_client.cc
- spec-main/fixtures/crash-cases/js-execute-iframe/index.html
- spec-main/fixtures/crash-cases/js-execute-iframe/index.js
- spec-main/fixtures/crash-cases/js-execute-iframe/page2.html
Closes https://github.com/electron/electron/issues/27995.
Fixes an issue where `illegal access error` would be thrown by the V8 isolate in some circumstances where an iframe was loaded and its source set later when Node.js integration is enabled in subframes. This was happening because if an iframe is created and a source is not set, the iframe loads about:blank and creates a script context for the same. We don't want to create a Node.js environment here because if the src is later set, the JS necessary to do that triggers illegal access errors when the initial about:blank Node.js environment is [cleaned up](https://github.com/nodejs/node/blob/73ef3f2f050a874712d1770ddd4e02930a638eda/src/env.cc#L558-L559). 
See this comment: https://source.chromium.org/chromium/chromium/src/+/main:content/ …
> fix: illegal access errors with nodeIntegrationInSubFrames

- shell/browser/electron_browser_client.cc
Refs https://github.com/electron/electron/pull/24984.
Fixes an issue where  extensions without a background page can't xhr file URLs even if they have the necessary permissions. This regressed inin https://crrev.com/564596 - [crbug](https://bugs.chromium.org/p/chromium/issues/detail?id=1179732)
Fixed in https://chromium-review.googlesource.com/c/chromium/src/+/2744160.
Notes: Fixed an issue where extensions without a background page might not have file access.
> fix: ensure extensions w/o a background page have file access

- docs/api/command-line-switches.md
On the [Supported Command Line Switches page](https://www.electronjs.org/docs/api/command-line-switches), all the other argument headers were H3 (`###`) but `--force-fieldtrials` was H2 (`##`) for some reason. 
I changed it to H3 to make it consistent with the others.
(https://github.com/electron/clerk/blob/master/README.md#examples).
Notes: none
> docs: --force-fieldtrials was h2 rather than h3

- patches/chromium/dcheck.patch
We now use the built-in navigation controller so these DCHECKs should no longer
fire.
Notes: none
> chore: uncomment some DCHECKs

- docs/api/accelerator.md
`Meta` is a valid alternative for `Super` and should be listed as an available modifier in the documentation.
See this source line showing that Electron can process `Meta`: https://github.com/electron/electron/blob/da8c35e3b256b4f9ad0c16edfbc2b56748b3a740/shell/common/keyboard_util.cc#L24
Notes: none
> docs: mention Meta key in Accelerator

- docs/fiddles/features/drag-and-drop/index.html
- docs/fiddles/features/drag-and-drop/main.js
- docs/fiddles/features/drag-and-drop/preload.js
- docs/fiddles/features/drag-and-drop/renderer.js
- docs/tutorial/native-file-drag-drop.md
Update the "Native Files Drag and Drop" tutorial to no longer require nodeIntegration and properly use the preload script to inject IPC methods.
Notes: none
cc: @erickzhao
> docs: update drag and drop tutorial

- docs/fiddles/features/macos-dock-menu/index.html
- docs/fiddles/features/macos-dock-menu/main.js
- docs/fiddles/features/macos-dock-menu/preload.js
- docs/tutorial/macos-dock.md
Updates the `fiddle` example for macOs Dock files to work correctly with 12.0.7.
Notes: none
cc @erickzhao
> docs: Update the macos Dock Instructions

- shell/common/api/electron_api_native_image.cc
The amount of memory used needs to be subtracted in the `NativeImage` destructor.
This regressed in #27111
Originally added by https://github.com/electron/electron/commit/1fcf6ea73f5a0412774197e405fa47ad8d5d6143
Discovered randomly when working on #29174
> fix: AdjustAmountOfExternalAllocatedMemory regression in NativeImage destructor

- shell/browser/native_window_views.cc
- shell/browser/native_window_views.h
- shell/browser/native_window_views_win.cc
fixed #25811
possibly related to #25420 #21777
On Windows, the `will-resize` and `will-move` events emit the pending bounds of the window. However, they're reported in screen coordinates which aren't scaled according to the display scale factor.
Here's a clip of a window being moved between a 4k and 1080p monitor which causes its scale factor to change. The width/height of `newBounds` remains the same with this fix.
(as an aside, there seems to be an unrelated rounding bug with the width/height of `currentBounds` you can also see)
https://user-images.githubusercontent.com/1656324/118202321-a9c64680-b427-11eb-82d0-8574ee10eb58.mp4
No tests are included as I'm not sure whether we have a way to test display scale changes.
Notes: Fixed `will-resize` and `will-move` events not scaling the …
> fix: window bounds not scaled from screen coordinates

- docs/api/dialog.md
> docs: option title for showSaveDialog is not supported for some platforms

- lib/browser/api/browser-window.ts
- shell/browser/api/electron_api_browser_window.cc
- shell/browser/api/electron_api_web_contents.cc
- shell/browser/api/electron_api_web_contents.h
- shell/browser/native_window.h
- shell/browser/native_window_mac.h
- shell/browser/native_window_mac.mm
- spec-main/api-web-contents-spec.ts
- spec-main/chromium-spec.ts
- typings/internal-electron.d.ts
Fixes https://github.com/electron/electron/issues/28897
Also verified to not regress https://github.com/electron/electron/issues/25287
Notes: fix incorrect value of `document.focus` when opening multiple windows on macOS
> fix: adjust initial webContents focus calculation

- shell/browser/api/electron_api_session.cc
- shell/browser/extensions/electron_extension_system.cc
Fixes #29191.  The chromium roll #28462 included a change to [shell/browser/extensions/electron_extension_system.cc](https://github.com/electron/electron/pull/28462/files#diff-8e14b16934c07d35e6a4cf41d9a071c63d6f018e10dd09e190ba1cc46bf673deR122) to address https://chromium-review.googlesource.com/c/chromium/src/+/2771320, but the wrong `extensions::mojom::ManifestLocation` was used which caused a permissioning error which prevented the PDF viewer from displaying.  This PR updates shell/browser/extensions/electron_extension_system.cc to use the proper `extensions::mojom::ManifestLocation`.
Notes: Fixed permissions issue that was preventing the PDF viewer from displaying.
> fix: pdf viewer permissions

- BUILD.gn
- patches/chromium/build_libc_as_static_library.patch
Follow up to #29281, the build generation step in BUILD.gn needs to be updated to `libcxx_objects_zip`
Notes: none
> fix: correct libcxx_objects build action name

- docs/fiddles/features/keyboard-shortcuts/global/index.html
- docs/fiddles/features/keyboard-shortcuts/global/main.js
- docs/fiddles/features/keyboard-shortcuts/interception-from-main/index.html
- docs/fiddles/features/keyboard-shortcuts/interception-from-main/main.js
- docs/fiddles/features/keyboard-shortcuts/local/index.html
- docs/fiddles/features/keyboard-shortcuts/local/main.js
- docs/fiddles/features/keyboard-shortcuts/web-apis/index.html
- docs/fiddles/features/keyboard-shortcuts/web-apis/main.js
- docs/fiddles/features/keyboard-shortcuts/web-apis/renderer.js
- docs/tutorial/keyboard-shortcuts.md
Updates the fiddles for Keyboard shortcuts. (local, global, and main-intercept).
The fiddles work as is so this PR:
* removes `nodeIntegration: true` from the `BrowserWindow`
* removes the version display from the home page.
Notes: none
cc @erickzhao
> docs: Update docs for keyboard shortcuts

- lib/renderer/init.ts
- lib/sandboxed_renderer/init.ts
- shell/renderer/electron_renderer_client.cc
- shell/renderer/electron_sandboxed_renderer_client.cc
- shell/renderer/renderer_client_base.cc
- shell/renderer/renderer_client_base.h
@electron/remote is now using `process.contextId` (https://github.com/electron/remote/pull/44)
> refactor: expose process.contextId directly

- .circleci/config.yml
This job is declared but not used by any workflows 🤷 
> build: remove unused build job

- shell/browser/api/electron_api_web_frame_main.cc
This change fixes the test case where a concurrent search in two iframes cannot occur.
Notes:
> fix: get subframes directly rather than from main frame

- shell/browser/extensions/electron_extension_loader.cc
Just a code hygiene change, suggested by `clang-tidy`. Access the static method directly through the class instead of creating an instance. Makes this usage consistent with the rest of the code base.
Notes: none
> chore: use base::Time::Now() directly

- .circleci/config.yml
Fixes #29337.
mksnapshot.zip for macOS arm64 (Apple Silicon) was missing two needed files:
`mksnapshot_args` and `clang_x64_v8_arm64/gen/v8/embedded.S`.  This PR adds those files to mksnapshot.zip for macOS arm64 
Notes: Fixed using custom v8 snapshots on Apple Silicon.
> build: ensure that mksnapshot for Apple Silicon has all of the needed files for snapshot generation

- docs/api/context-bridge.md
- shell/renderer/api/electron_api_context_bridge.cc
- spec-main/api-context-bridge-spec.ts
Based on https://github.com/electron/electron/pull/26776 and fixes https://github.com/electron/electron/issues/27364
Notes: Added support for sending Blobs over the context bridge.
> feat: add support for Blob's going over the ctx bridge

- docs/development/build-instructions-windows.md
Opening VS installer gives the option to "Modify" (and launch/open more options) rather than "Change" Visual Studio. Reflected this in the docs as as result.
- [x ] PR description included and stakeholders cc'd
Notes: changed wording in the Visual Studio Installer step.
> docs: update Windows build instructions

- .circleci/config.yml
Backport of #29338
Notes: Fixed using custom v8 snapshots on Apple Silicon.
> build: ensure that mksnapshot for Apple Silicon has all of the needed files for snapshot generation 

- shell/browser/ui/views/menu_bar.cc
Fix a regression caused by https://github.com/electron/electron/pull/29262 that, the autoHide menu bar is not automatically closed when focus is moved away.
I'm not adding any release notes since the change has not been released yet.
Notes: none
> fix: close autoHide menu bar when focus is lost

- docs/tutorial/quick-start.md
Fixes the Fiddle meta link for `docs/fiddle/quick-start`.
Notes: none
> docs: fix link to `docs/fiddle/quick-start`

- docs/development/clang-tidy.md
Just a simple typo which snuck into the original version of the doc.
Notes: none
> docs: fix typos in clang-tidy examples

- shell/browser/api/message_port.cc
- shell/browser/extensions/electron_extension_loader.cc
- shell/browser/file_select_helper.cc
- shell/common/asar/archive.cc
Another PR like #26109. Prefer using `empty()` for checks instead of `size()` or comparison to an empty string.
Notes: none
> chore: prefer empty() check for readability

- docs/tutorial/support.md
Freenode has been [taken over by a malicious actor](https://gist.github.com/joepie91/df80d8d36cd9d1bde46ba018af497409). Further, that channel was only very lightly used. Let's not recommend it any more.
Notes: none
> docs: remove freenode channel from support list

- script/release/publish-to-npm.js
make publish-to-npm accept 'main'.
Notes: none
> refactor: publish-to-npm respects main

- script/release/notes/index.js
Switch to use `main` in the release-notes script.
Notes: none
> refactor: use main in release-notes

- script/release/notes/index.js
Use the default branch instead of hard-coding 'main' in release notes.
cc @ckerr @marshallofsound
Notes: none
> fix: use default_branch in release-notes

- docs/tutorial/introduction.md
The reference links on this page weren't working because of wrong md syntax. This PR fixes that
Notes: The issue was introduced (or may be reproduced) in this [PR](https://github.com/electron/electron/pull/29062)
> docs: fixes issue with reference links

- .circleci/config.yml
I had a lot of changes I needed to stash, this one can be a solo PR.  Just trying to simplify our damm YAML file still
> build: merge chromedriver gen and build

- shell/browser/api/electron_api_web_request.cc
- shell/browser/ui/accelerator_util.h
- shell/common/gin_helper/callback.h
- shell/common/gin_helper/function_template.h
Back with another installment.
Notes: none
> chore: fix typos in comments

- shell/browser/api/electron_api_protocol.cc
- shell/browser/api/electron_api_protocol.h
- shell/renderer/renderer_client_base.cc
- spec-main/chromium-spec.ts
- spec/fixtures/pages/service-worker/custom-scheme-index.html
Closes #28528. 
Notes: Fixed missing 'fetch' event in service workers for requests using a registered protocol
> fix: add service worker schemes from command line in renderer

- shell/browser/net/electron_url_loader_factory.cc
- shell/browser/net/proxying_url_loader_factory.cc
- shell/browser/ui/inspectable_web_contents.cc
Code hygiene change, favor using the status code constants from `net/http/http_status_code.h` over hardcoding them.
Notes: none
> chore: use HTTP status code constants

- shell/browser/ui/views/menu_bar.cc
- shell/browser/ui/views/root_view.cc
Fix pressing keys like `Alt+Shift` wrongly getting captured for menu shortcuts, close https://github.com/electron/electron/issues/28088.
Notes: Fix pressing `Alt+Shift` and `Alt+Ctrl` toggling menu bar on KDE.
> fix: correctly handle Alt+Key shortcuts

- shell/common/gin_helper/error_thrower.cc
- shell/common/gin_helper/error_thrower.h
- shell/common/gin_helper/object_template_builder.cc
- shell/common/gin_helper/object_template_builder.h
Another `clang-tidy` suggestion: `class 'ErrorThrower' can be made trivially destructible by defaulting the destructor on its first declaration [performance-trivially-destructible]`
Moving the default destructors to the header allows these two classes to be trivially destructible, which is nice.
Notes: none
> chore: move destructors to header so they can be trivially destructible

- shell/browser/native_window_views.cc
- shell/browser/native_window_views.h
Holding <kbd>Alt</kbd> + mouse click should __not__ result in the menu bar getting toggled, close https://github.com/electron/electron/issues/26154.
Notes: Fix pressing Alt with mouse click results in toggling menu bar.
> fix: Alt+Click should not toggle menu bar

- shell/browser/api/electron_api_protocol.cc
- shell/browser/api/electron_api_protocol.h
- shell/renderer/renderer_client_base.cc
- spec-main/chromium-spec.ts
- spec/fixtures/pages/service-worker/custom-scheme-index.html
Backport of #29425.
Notes: Fixed missing 'fetch' event in service workers for requests using a registered protocol
> fix: add service worker schemes from command line in renderer (#29425)

- docs/api/browser-window.md
- shell/browser/api/electron_api_base_window.cc
- shell/browser/api/electron_api_base_window.h
- shell/browser/native_window.cc
- shell/browser/native_window.h
- shell/browser/native_window_observer.h
- shell/browser/native_window_views_win.cc
- shell/browser/ui/cocoa/electron_ns_window_delegate.h
- shell/browser/ui/cocoa/electron_ns_window_delegate.mm
- shell/common/gin_converters/gfx_converter.cc
- shell/common/gin_converters/gfx_converter.h
```diff
interface BrowserWindow {
on(event: 'will-resize', listener: (event: Event,
newBounds: Rectangle,
+                                     details: { edge: string }
) => void): this;
}
```
When resizing a window, it can be helpful to know which edge of the window is being dragged to resize it. Knowing the resize edge can allow an application to change behavior depending on which is being used. For example, respecting an aspect ratio only when the window is resized vertically.
On Windows, we're able to know exactly which edge/corner is used for resizing.
On macOS, we know whether the window was initially dragged horizontally or vertically.
On Linux, we don't support the `will-resize` event yet. 🤷‍♂️
In lieu of tests (unable to simulate resize), here are previews for both supported …
> feat: include resize edge with will-resize event

- docs/fiddles/features/progress-bar/index.html
- docs/fiddles/features/progress-bar/main.js
- docs/tutorial/progress-bar.md
Updated the `progress-bar` fiddle feature. Improved the sample by adding a little bit of logic to progress the bar through 100% to show not only the behavior of the bar set to an intermediate state, but also set to `-1` to reset.
Updated the tutorial page too to reflect the changes to the fiddle  and improved some of the language.
Notes: none
> docs: Updated "progress bar" fiddle feature in docs

- lib/browser/devtools.ts
- typings/internal-electron.d.ts
Fixes an issue where right-clicking on the inspector throws an error:
```
[84035:0601/000704.374553:ERROR:CONSOLE(57)] "Uncaught (in promise) Error: Error invoking remote method 'INSPECTOR_CONTEXT_MENU': TypeError: e._getURL is not a function", source: electron/js2c/sandbox_bundle.js (57)
Error occurred in handler for 'INSPECTOR_CONTEXT_MENU': TypeError: e._getURL is not a function
at assertChromeDevTools (electron/js2c/browser_init.js:177:881)
at electron/js2c/browser_init.js:177:1127
at new Promise (<anonymous>)
at electron/js2c/browser_init.js:177:1117
at electron/js2c/browser_init.js:197:579
at Object.<anonymous> (electron/js2c/browser_init.js:161:10150)
at Object.emit (events.js:376:20)
```
Tested by running a stock Fiddle and right-clicking in the devtools console.
Notes: Fixes an …
> fix: inspector context menu throwing an error

- docs/api/app.md
- shell/browser/api/electron_api_app.cc
- shell/browser/api/electron_api_app.h
- shell/browser/api/electron_api_app_mac.mm
- spec-main/api-app-spec.ts
This PR adds a new generic property `runningUnderARM64Translation` to `app` that is supposed to supersede `runningUnderRosettaTranslation`, adding support to the same kind of check on Windows: whether or not the app is an x64 build running emulated on a Windows ARM device using [WOW](https://en.wikipedia.org/wiki/Windows_on_Windows). This while keeping the behavior of `runningUnderRosettaTranslation` for macOS.
Notes: Added new `app.runningUnderARM64Translation` property to detect when running under Rosetta on Apple Silicon, or WOW on Windows for ARM.
> feat: add new runningUnderARM64Translation property to detect x64 translated apps running on Windows ARM

- typings/internal-electron.d.ts
Refs https://github.com/electron/electron/pull/28839.
Removes methods no longer used/needed.
Notes: none.
> chore: remove unused WebContents method types

- script/lib/config.py
Electron already seems to support `cygwin`, so `msys` is a natural
addition. This is the only required change as far as I can see on my
local development environment, as otherwise the build scripts don't
realize that msys = windows.
Notes: none
> build: Support building Electron on msys2

- shell/browser/native_window_mac.mm
`clang-tidy` flagged this as a use after move. I don't think this was necessarily causing any issues, but I think this PR is logically correct.
cc @zcbenz
Notes: none
> chore: don't use after move

- shell/common/node_bindings.cc
Working toward a clean run of `clang-tidy` using the inherited config from Chromium, it pointed out this change.
Notes: none
> chore: use static_cast rather than C-style cast

- patches/chromium/accelerator.patch
- shell/browser/api/electron_api_menu.cc
- shell/browser/api/electron_api_menu.h
- shell/browser/api/electron_api_menu_mac.h
- shell/browser/api/electron_api_menu_mac.mm
- shell/browser/ui/accelerator_util.cc
- shell/browser/ui/cocoa/electron_menu_controller.mm
- shell/common/gin_converters/blink_converter.cc
- shell/common/keyboard_util.cc
- shell/common/keyboard_util.h
- spec-main/api-menu-item-spec.ts
When a shifted character is used in accelerator, for example `Ctrl+Plus` and `Ctrl+?`, it should be kept as it is. And when Shift key and unshifted character are used, for example `Ctrl+Shift+=` and `Ctrl+Shift+/`, it should not be converted to shifted character.
Close https://github.com/electron/electron/issues/21790.
```js
const template = [
{
label: 'Test',
submenu: [
{ label: 'Alt+Shift+3',
accelerator: 'Alt+Shift+3' }
},
{ label: 'Alt+#',
accelerator: 'Alt+#' }
},
{ label: 'Ctrl+Plus',
accelerator: 'Ctrl+Plus' }
},
{ label: 'Ctrl+Shift+=',
accelerator: 'Ctrl+Shift+=' }
},
{ label: 'Ctrl+?',
accelerator: 'Ctrl+?' }
},
{ label: 'Ctrl+Shift+/',
accelerator: 'Ctrl+Shift+/' }
}
]
},
]
```
Also as a side effect of this change, the `accelerator.patch` removes the hack hat uses …
> fix: keep shifted character in menu accelerator

- shell/browser/api/electron_api_app_mac.mm
Looks like merging #29168 broke the macOS build due to some missing `#include`s.
cc @zcbenz @deepak1556 
Notes: none
> build: fix macOS build

- lib/browser/api/app.ts
- shell/browser/api/electron_api_app.cc
- shell/browser/api/electron_api_app.h
- shell/common/node_bindings.cc
There are two implementations, one in JavaScript and one in C++. Let's use the C++ one and expose it to JavaScript.
> refactor: eliminate duplicate C++ / JavaScript implementation of app.isPackaged

- script/release/prepare-release.js
This switches `prepare-release` to key off `main` instead of `master`.
Notes: none
> refactor: point prepare-release at main

- script/release/version-bumper.js
- spec-main/fixtures/version-bumper/fixture_support.md
- spec-main/version-bump-spec.ts
Following up on a great suggestion by @MarshallOfSound in #29377, this PR adds a function to our version bump script that changes the `support.md` file on two conditions:
1. When we promote a new major nightly version (i.e. 14.0.0-nightly.xx -> 15.0.0-nightly.xx)
2. When we promote a new major stable version (e.g. 14.x.x -> 15.0.0)
Ideally, we could simplify this to _only_ bump when a new nightly is created. The website bases it's public information off of the latest stable branch, so the currently supported versions will appear correctly as each nightly goes through the nightly -> stable cycle and eventually becomes stable.
However, I left in the new major stable bump for 1) backwards compatibility, so we don't need to manually update current nightly and beta, and 2) having an additional …
> build: update support.md on stable version bumps

- shell/browser/api/electron_api_web_contents.cc
Backport of #29404.
Notes: Added support for debug URLs such as `chrome://gpucrash`.
> feat: support loading debug urls with loadURL()

- patches/chromium/.patches
- patches/chromium/cherry-pick-3299d70b7d0f.patch
Make PushPullFIFO adapt to irregular audio callbacks from the browser process
For background and rationale:
go/webaudio-worklet-glitch-aaudio (Googler only)
The current implementation of PushPullFIFO doesn’t dynamically increase
or decrease the amount frames to keep in the FIFO. So it is vulnerable
to callback bursts from the device thread and it does not recover from
subsequent callbacks when underrun happens.
The proposed solution is to implement the “earmark” counter in
PushPullFIFO, so it can dynamically adapt when the buffer
underrun happens by increasing the frame amount to keep. This design is
inspired by the buffer optimization technique [1] from the AAudio
reference.
[1] https://developer.android.com/ndk/guides/audio/aaudio/aaudio#optimizing-performance
Tested on: …
> chore: cherry-pick 3299d70b7d0f from chromium

- shell/common/node_bindings.cc
- spec-main/node-spec.ts
- spec/fixtures/module/fail.js
> test: add spec for --require filtering in NODE_OPTIONS

- patches/squirrel.mac/build_add_gn_config.patch
Right now, if executing `xcrun` fails, then the error message prints the
second argument to the `xcrun.py` script, which is the first argument to
the tool that `xcrun` is executing, making the whole error message quite
confusing.
Consider the following error:
```
python ../../third_party/squirrel.mac/build/xcrun.py dtrace -h -s /private/tmp/20210531211008-def376dc/src/third_party/squirrel.mac/vendor/ReactiveObjC/ReactiveObjC/RACSignalProvider.d -o /private/tmp/20210531211008-def376dc/src/out/release/gen/third_party/squirrel.mac/dtrace/RACSignalProvider.h
xcrun script '-h' failed with code '71':
xcrun: error: can't exec '/tmp/20210531211008-def376dc/dtrace' (errno=Permission denied)
```
The command that `xcrun` is executing is `dtrace`, but the error just
mentions the `-h` flag.
Notes: …
> build: Improve squirrel.mac BUILD.gn xcrun_action error

- README.md
I don't think this is useful. Our devDependencies are out of date, apparently, but I don't think that's an important enough fact to have it be on our front page.
Also the image is sometimes broken.
Notes: none
> docs: remove devDependencies badge from README

- shell/app/electron_crash_reporter_client.cc
- shell/browser/api/electron_api_app.cc
- shell/browser/browser_linux.cc
- shell/browser/electron_browser_client.cc
- shell/browser/electron_browser_main_parts.cc
- shell/browser/linux/unity_service.cc
- shell/browser/ui/gtk/app_indicator_icon.cc
- shell/browser/ui/views/electron_views_delegate.cc
- shell/browser/ui/x/x_window_utils.cc
- shell/common/node_bindings.cc
- shell/common/platform_util_linux.cc
Some code is using `auto env = base::Environment::Create(); ` while other code is using `std::unique_ptr<base::Environment> env(base::Environment::Create());`. Let's unify on the shorter version.
> refactor: use auto env = base::Environment::Create(); everywhere

- shell/browser/electron_browser_main_parts.cc
- shell/common/asar/archive.cc
- shell/common/asar/archive.h
- shell/common/asar/asar_util.cc
- shell/common/asar/asar_util.h
- shell/renderer/electron_renderer_client.cc
- shell/renderer/web_worker_observer.cc
Close #29292.
This PR changes the ASAR archive cache in `shell/common/asar/asar_util.cc` to be process-wide instead of in thread-locals to prevent the `asar::Archive` from being leaked on worker thread exit. See issue #29292 for the technical details about the bug.
Changing the cache to being process-wide means that thread-safety had to be added to `asar::Archive` and `asar::GetOrCreateAsarArchive`. This is (unfortunately?) accomplished with locks, as `asar::GetOrCreateAsarArchive` is used in both async (`AsarURLLoader`) and sync (`NativeImage`) contexts. I know in Chromium locks are frowned upon, but using them here allows the code to continue to be used where it is currently in synchronous code.
Other changes include making `asar::IsDirectoryCached` thread-safe, where it wasn't before, …
> fix: change ASAR archive cache to per-process to fix leak

- shell/browser/net/proxying_url_loader_factory.cc
- shell/browser/net/proxying_url_loader_factory.h
This PR pulls `electron::ProxyingURLLoaderFactory` closer to upstream `extensions::WebRequestProxyingURLLoaderFactory` so that diffs between the two are cleaner, and it's easier to see how they differ, and land changes from upstream. Creating this PR highlighted a few future PRs in this class (will make those PRs after this is merged to avoid conflicts) and some changes for upstream (will make those).
There should be no functional changes in this PR, the closest to a functional change is adding `const` to one of the member variables to match upstream. Otherwise this PR:
* Adds/removes headers to more closely match upstream
* Changes a couple of comments to match upstream
* Changes order of methods and a member variable to match upstream 
This results in a more clear diff when comparing to …
> chore: pull ProxyingURLLoaderFactory closer to upstream class it mirrors

- build/args/all.gn
For info ping me in Slack, I'll fill out this PR body later.
Notes: Fixed crashes on latest gen Intel and Ryzen processors
> fix: disable CET as v8 deoptimization is incompatible with it

- shell/browser/electron_browser_client.cc
- shell/browser/net/electron_url_loader_factory.cc
The comments went stale in 69f1731bbbaa5211aefe64f3d155b11ab7bcb327, when `NonNetworkURLLoaderFactoryBase` was removed from upstream.
Notes: none
> chore: update base class name in comment

- shell/browser/electron_browser_main_parts.cc
- shell/common/asar/archive.cc
- shell/common/asar/archive.h
- shell/common/asar/asar_util.cc
- shell/common/asar/asar_util.h
- shell/renderer/electron_renderer_client.cc
- shell/renderer/web_worker_observer.cc
Backport of #29293.
Notes: Fixed memory leak when requesting files in ASAR archive from renderer
> fix: change ASAR archive cache to per-process to fix leak (#29293)

- docs/fiddles/features/notifications/renderer/index.html
- docs/fiddles/features/notifications/renderer/main.js
- docs/fiddles/features/notifications/renderer/renderer.js
- docs/tutorial/notifications.md
Removed `nodeIntegration` and update the logic a little bit for showing how to trigger a notification from the `renderer.js` file and how to handle a click on that notification.
Linted code using `standard`.
Notes: none
> docs: Update notifications (renderer) docs

- shell/browser/api/electron_api_app.cc
Fixes #28553.
cc @zcbenz @deepak1556 
No test added because I wasn't sure there's a viable way to make one (no current tests for this functionality) since it pulls client certificates from the system store. See #21980.
Manually reproduced and tested the fix. The fix is straight forward, but if anyone else really feels like confirming it themselves, these are the steps I used on macOS, it was a bit of a pain:
1. In `Keychain Access`, use `Keychain Access -> Certificate Assistant` to create a certificate chain, using 'SSL Client' for the type for all certificates. Create:
1. A self-signed root CA.
2. An intermediate CA.
3. A leaf certificate.
2. Apply the Chromium patch provided below, which ensures Chromium will include intermediates on macOS, otherwise they are only included when the …
> fix: make intermediates work with 'select-client-certificate'

- .circleci/config.yml
- script/release/ci-release-build.js
Continuing circle simplification, this removes our "single job" publish workflows for linux and macOS and replaces them with the primary publish workflow but ensures that the other jobs have no steps if they aren't the selected arch.  This doesn't impact the normal sudowoodo flow, just ad-hoc release builds triggered by `ci-release-builds.js`
> build: remove individual release build workflows

- docs/api/browser-window.md
- docs/api/web-contents.md
- shell/browser/api/electron_api_web_contents.cc
- shell/browser/api/electron_api_web_contents.h
- shell/browser/web_contents_preferences.cc
- shell/common/options_switches.cc
- shell/common/options_switches.h
As in title, adds a new webpref to map to the Chromium webpref.  Also adds a webContents setter so that this can be set at runtime without having to reload / recreate the webContents.
This is helpful for apps that need to enable / disable animations for accessibility or performance reasons.
Notes: Added new `imageAnimationPolicy` web preference to control how images are animated
> feat: add new imageAnimationPolicy webpref and webContents setter

- .circleci/config.yml
#29133 accidentally removed dist.zip from the artifacts saved on macOS.  This PR puts back that artifact.
Notes: none
> ci: save artifacts before cleaning up big things on macOS

- shell/browser/electron_browser_main_parts.cc
- shell/browser/electron_browser_main_parts.h
- shell/common/platform_util_linux.cc
- spec-main/chromium-spec.ts
Closes https://github.com/electron/electron/issues/28436.
`GDK_BACKEND` is set by Chromium as of [this CL](https://chromium-review.googlesource.com/c/chromium/src/+/2586184) and can detrimentally affect external app behaviors, so we want to unset it and replace with the user's setting if one exists.
Notes: Fixed an issue where `GDK_BACKEND` was being propagated to subprocesses on Linux.
> fix: don't propagate GDK_BACKEND to subprocs

- shell/browser/lib/bluetooth_chooser.cc
- shell/browser/lib/bluetooth_chooser.h
#27902 included logic to handle the use case on macOS where BluetoothChooser::ShowDiscoveryState fires twice with a state of `DiscoveryState::DISCOVERING` because there is a [rescan event](https://source.chromium.org/chromium/chromium/src/+/main:content/browser/bluetooth/bluetooth_device_chooser_controller.cc;l=476) that fires on macOS.  This is usually not a problem but if a developer immediately handles the `select-bluetooth-device` event before the second `BluetoothChooser::ShowDiscoveryState` fires, a crash occurs because the BluetoothChooser is destroyed once a bluetooth device is selected.
Unfortunately this logic caused an issue on Windows where the rescan event does not fire.  I was able to fix this issue by adding a flag to only fire the rescan logic when a rescan is triggered. …
> fix: select-bluetooth-device on Windows

- shell/browser/electron_browser_main_parts.cc
- shell/browser/electron_browser_main_parts.h
- shell/common/platform_util_linux.cc
- spec-main/chromium-spec.ts
Reverts electron/electron#28898
It broke main, see sudowoodo channel for details.  TLDR: uses the wrong optional and tests fail when using the right kind
Notes: none
> fix: Revert "fix: don't propagate GDK_BACKEND to subprocs"

- build/fuses/build.py
python2 and python3 have subtley different behavior when getting `keys()` from a JSON parsed dictionary.  Forcing the dictionary to be an `OrderedDict` ensures the behavior is consistent (and what we have documented).
Notes: Electron Fuses are now in a consistent order across platforms
> fix: ensure fuse order is read in a stable way

- shell/browser/native_window_mac.h
- shell/browser/native_window_mac.mm
Closes https://github.com/electron/electron/issues/29541.
Fixes an issue that surfaced as a result of https://github.com/electron/electron/commit/8bf66f8974c6dc0aecdc22e4ddce2881e1836840, where custom traffic lights could show underneath a BrowserView (e.g. wouldn't always be floated to the top of the view hierarchy). This fixes that.
Notes: Fixed an issue where custom traffic lights could be covered by BrowserViews on macOS.
> fix: ensure custom traffic lights float to top

- shell/browser/net/url_pipe_loader.cc
Fixes #27426.
From the comment for `SimpleURLLoaderStreamConsumer::OnDataReceived`, which `URLPipeLoader::OnDataReceived` overrides:
```
// |string_piece| will only be valid for the duration of the OnDataReceived()
// call, but does remain valid during that call even if the SimpleURLLoader
// is destroyed. |string_piece| will never be of length 0.
```
cc @zcbenz 
Notes: Fixed potential corruption of piped response data when using interceptHttpProtocol/registerHttpProtocol
> fix: copy received data in URLPipeLoader to prevent corruption

- shell/browser/net/electron_url_loader_factory.cc
- shell/renderer/electron_renderer_client.cc
Code hygiene change, make use of the HTTP method constants from `net/http/http_request_headers.h`.
Notes: none
> chore: use HTTP method constants

- shell/browser/api/electron_api_web_request.cc
- spec-main/api-web-request-spec.ts
The spelling of 'attachment' was incorrect when being set in the 'Content-Disposition' header via `webRequest`.
cc @zcbenz 
Notes: Fixed the spelling of 'attachment' in 'Content-Disposition' header when using the webRequest module
> fix: use correct spelling of attachment with Content-Disposition header

- shell/browser/api/electron_api_menu.cc
- shell/browser/api/electron_api_menu.h
- shell/browser/api/electron_api_menu_mac.h
- shell/browser/api/electron_api_menu_mac.mm
- shell/common/api/electron_api_v8_util.cc
- shell/renderer/api/electron_api_context_bridge.cc
`DCHECK_IS_ON` is always defined, so this was always evaluating to true.
Notes: none
> fix: check DCHECK_IS_ON() instead of #ifdef DCHECK_IS_ON

- shell/app/command_line_args.cc
This change refactors the code to use `isalpha()` and
`isspace()` so that the code is more readable.
Notes: none
> refactor: use `locale` functions in `command_line_args.cc`

- shell/browser/net/proxying_url_loader_factory.cc
- shell/browser/net/proxying_url_loader_factory.h
Makes the request ID type for `ProxyingURLLoaderFactory::InProgressRequest::InProgressRequest` consistent with the rest of the file, where it is `uint64_t`.
Notes: none
> chore: use consistent integer type for request ID

- docs/api/app.md
- docs/api/menu.md
- docs/breaking-changes.md
- docs/tutorial/debugging-vscode.md
- docs/tutorial/using-selenium-and-webdriver.md
Use relative links within the docs, which ensures the relative link linting keeps them from going stale. Also makes sure links stay on the same docs site, instead of linking from the new beta docs site back to the current docs site.
Notes: none
> docs: use relative links within docs

- default_app/main.ts
- lib/browser/api/app.ts
- lib/browser/init.ts
- shell/app/electron_crash_reporter_client.cc
- shell/app/electron_main_delegate.cc
- shell/browser/api/electron_api_app.cc
- shell/browser/api/electron_api_crash_reporter.cc
- shell/browser/browser.cc
- shell/browser/browser_process_impl.cc
- shell/browser/electron_browser_client.cc
- shell/browser/electron_browser_context.cc
- shell/browser/electron_browser_main_parts.cc
- shell/browser/net/system_network_context_manager.cc
- shell/browser/ui/devtools_manager_delegate.cc
- shell/common/electron_paths.h
- typings/internal-electron.d.ts
This extracts just the PathProvider refactor from #25089, for separate review.
Also fixes #29340.
Notes: Fixed `app.getPath('logs')` returning the wrong path on Linux and Windows.
> refactor: use PathProvider for user-data-dir and others

- spec-main/api-browser-window-spec.ts
- spec-main/api-protocol-spec.ts
- spec/fixtures/pages/cache-storage.html
These tests were marked as skip, but pass on `main` on macOS. I think they may have just never been re-enabled. One test in a `describe` still failed so I marked it as `it.skip`.
Notes: none
> test: re-enable some skipped tests

- lib/renderer/security-warnings.ts
- spec-main/security-warnings-spec.ts
The `remote` module is disabled by default since Electron 10.
Also skip the warning logic when `enable_remote_module` is disabled in build options.
Notes: Fixed `warnAboutRemoteModuleWithRemoteContent` for the new default value of `enableRemoteModule`.
> fix: warnAboutRemoteModuleWithRemoteContent

- lib/renderer/security-warnings.ts
- spec-main/security-warnings-spec.ts
> fix: don't warn about enableRemoteModule when it's disabled at build time

- shell/browser/native_window_mac.mm
- spec-main/api-browser-window-spec.ts
Closes https://github.com/electron/electron/issues/29653.
Fixes a potential crash when a value is passed in for the vibrancy type which is not valid either owing to operating system version or the string itself. This will now simply no-op.
Notes: Fixes a potential crash when setting vibrancy on macOS.
> fix: potential crash when setting vibrancy

- docs/api/window-open.md
The "Native `Window` example" in `docs/api/window-open.md` calls `webContents.setWindowOpenHandler` incorrectly. This PR fixes the call, in line with previous fixes to other calls in this document.
Notes: Fixed invocation of `webContents.setWindowOpenHandler` in `window.open` example.
> docs: fix setWindowOpenHandler invocation in window.open example

- shell/browser/api/electron_api_browser_window.cc
- shell/browser/api/electron_api_browser_window.h
- shell/browser/api/electron_api_browser_window_mac.mm
- shell/browser/api/electron_api_browser_window_views.cc
- shell/browser/ui/views/inspectable_web_contents_view_views.cc
Closes https://github.com/electron/electron/issues/29159.
We addressed a similar problem in https://github.com/electron/electron/pull/26361 but draggable regions are implemented differently enough across platforms that one solution rarely addresses all of them. Windows and Linux work such that we check the current cursor position and then check to see if that falls inside draggable region bounds. On `BrowserView`s, we considered that the `BrowserView` bounds may not begin at (0,0) and accounted for that by offsetting the bounds when performing that calculation, but failed to take into account that this may also be the case for draggable regions inside the primary `BrowserWindow`'s `WebContents.` When a DevTools instance is open, for example, this would mean the draggable region would be …
> fix: draggable regions with devtools open

- shell/browser/native_window_mac.mm
- shell/browser/ui/cocoa/electron_ns_window.h
Remove the c-style type conversions when using and setting `[window vibrantView]`.
Notes: none
> chore: remove c-style conversion for vibrantView

- shell/browser/ui/cocoa/electron_inspectable_web_contents_view.mm
We have logic [here](https://github.com/electron/electron/blob/main/shell/browser/ui/cocoa/electron_inspectable_web_contents_view.mm#L121) that ensures that the devtools window is draggable when docked so draggable regions work correctly.  However a docked devtools window can be toggled into detached mode and after that the entire devtools window becomes draggable.
This fixes that by ensuring the "draggable" status is tied to `is_docked`
> fix: ensure detached devtools are not always draggable

- docs/tutorial/installation.md
> docs: clarify use of ELECTRON_SKIP_BINARY_DOWNLOAD

- chromium_src/BUILD.gn
- shell/browser/api/electron_api_web_contents.cc
- shell/browser/api/electron_api_web_contents.h
- shell/browser/ui/inspectable_web_contents.cc
- shell/browser/ui/inspectable_web_contents_delegate.h
Closes https://github.com/electron/electron/issues/25352. 
Fixes the eyedropper not working from DevTools. Tested by adding 
```js
color: 'blueviolet'
```
to the default css of the default Fiddle's index.html css and triggering the eyedropper.
Notes: Fixes the color select eyedropper not working within DevTools.
> fix: color select eyedropper not working within DevTools

- lib/renderer/api/ipc-renderer.ts
- lib/renderer/ipc-renderer-internal.ts
- shell/browser/api/electron_api_web_contents.cc
- shell/browser/api/electron_api_web_contents.h
- shell/browser/electron_browser_handler_impl.cc
- shell/browser/electron_browser_handler_impl.h
- shell/common/api/api.mojom
- shell/renderer/api/electron_api_ipc_renderer.cc
- typings/internal-ambient.d.ts
- typings/internal-electron.d.ts
It no longer works after #27676
> chore: remove unused and broken ipcRendererInternal.sendTo()

- patches/chromium/extend_apply_webpreferences.patch
Closes https://github.com/electron/electron/issues/29665.
Refs https://github.com/electron/electron/pull/28938 - previously the call to `blink::WebView::SetUseExternalPopupMenu` was guarded by `USE_EXTERNAL_POPUP_MENU` - the refactor removed this for the moved call to the selfsame function but that flag is [only defined](https://source.chromium.org/chromium/chromium/src/+/main:content/common/features.gni?q=USE_EXTERNAL_POPUP_MENU&ss=chromium&start=11) on macOS and Android. This caused the element dropdown to stop working on Windows. We don't have access to `USE_EXTERNAL_POPUP_MENU` within Blink so just fix this by moving inside a macOS-only guard.
Notes: Fixed the `<select>` element dropdown not appearing on Windows or Linux.
> fix: select element not working on Windows

- shell/browser/ui/views/frameless_view.cc
Fix bug : when BrowserWindow is not resizable, the hover state of DOM element may not be cleared.
https://github.com/electron/electron/issues/611
Notes: fix hover state not clear bug when BrowserWindow is not resizable
> fix: hover state bug when BrowserWindow is not resizable

- spec-main/extensions-spec.ts
An extension background page test was expecting a certain value for the URL before the URL was guaranteed to be committed and accessible.
```
not ok 1671 chrome extensions background pages has session in background page
AssertionError: expected '' to match /^chrome-extension:\/\/.+\/_generated_background_page.html$/
at Context.<anonymous> (electron\spec-main\extensions-spec.ts:440:42)
```
https://ci.appveyor.com/project/electron-bot/electron-x64-testing-pr/builds/39634739#L46419
Notes: none
> fix: flaky extension bg page test

- docs/tutorial/tray.md
Fixing a little mishap with the formatting slipped through the previous PR. Without this whitespace fix, Markdown parsers won't correctly detect the frontmatter.
Notes: none
> docs: fix frontmatter for Tray tutorial

- shell/browser/api/electron_api_net_log.cc
- shell/browser/api/electron_api_net_log.h
Apologies for the nondescript title, couldn't think of a proper name since it's a bag of a couple of changes. Main one is land [45d3c7fe83f4c11c556734093236ab47efce01c5](https://source.chromium.org/chromium/chromium/src/+/45d3c7fe83f4c11c556734093236ab47efce01c5) from upstream, to use newer Mojo types, then there's an added comment to document which upstream class it's referencing code from, and adding some headers in an attempt to get some better IWYU going on.
Notes: none
> refactor: tune-up electron::api::NetLog

- DEPS
- patches/squirrel.mac/build_add_gn_config.patch
- patches/squirrel.mac/fix_ensure_that_self_is_retained_until_the_racsignal_is_complete.patch
Refs: https://github.com/Squirrel/Squirrel.Mac/pull/259
Closes: #29119
Notes: Fixed issue where the update permission prompt would cause 100% CPU spin while the prompt was open
> fix: update Squirel.Mac to fix CPU spin during update

- spec-main/api-app-spec.ts
If the app is run with `LC_ALL=C` on Linux, the test would fail as
`app.getLocaleCountryCode()` would return `""`.
Notes: none
> fix: relax app.getLocaleCountryCode() test

- patches/angle/.patches
- patches/angle/cherry-pick-3d4f87ab5b9b.patch
D3D11: Fix respecifying 3D textures.
The missing check for the "Depth" dimension could lead to a bug
where we would not recreate a texture when the dimension changed.
Bug: chromium:1210414
Change-Id: Id59097ad14ae77ff80d27081f61786dad17a77ea
Reviewed-on: https://chromium-review.googlesource.com/c/angle/angle/+/2911032
Reviewed-by: Geoff Lang <geofflang@chromium.org>
(cherry picked from commit 2697358464cf20576701987f60300b6c4086c11e)
Reviewed-on: https://chromium-review.googlesource.com/c/angle/angle/+/2937026
Notes: Security: backported fix for CVE-2021-30547.
> chore: cherry-pick 3d4f87ab5b9b from angle

- patches/v8/.patches
- patches/v8/cherry-pick-b9ad6a864c79.patch
[M90-LTS] Reland "Merged: [compiler] Always record constness dependency for FastDataConstant"
This is a reland of 638d1b238d510a349bdd38648add8d5c85bc5f7d after a
one-character change. A local variable still has a non-optional type
in this version of V8.
> Merged: [compiler] Always record constness dependency for FastDataConstant
>
> Revision: 1bfa5139966fe0c9e8036fe6362b61c483675775
>
> BUG=chromium:1209558
> NOTRY=true
> NOPRESUBMIT=true
> NOTREECHECKS=true
>
> Change-Id: If4f7243647bcc12ed482796c1353f0717630f6b9
> Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/2919823
> Commit-Queue: Georg Neis <neis@chromium.org>
> Reviewed-by: Igor Sheludko <ishell@chromium.org>
> Cr-Commit-Position: refs/branch-heads/9.1@{#59}
> Cr-Branched-From: …
> chore: cherry-pick b9ad6a864c79 from v8

- patches/v8/.patches
- patches/v8/cherry-pick-fd8cbdf7b888.patch
[M86-LTS] Reland "Merged: [compiler] Always record constness dependency for FastDataConstant"
This is a reland of 638d1b238d510a349bdd38648add8d5c85bc5f7d after a
one-character change. A local variable still has a non-optional type
in this version of V8.
> Merged: [compiler] Always record constness dependency for FastDataConstant
>
> Revision: 1bfa5139966fe0c9e8036fe6362b61c483675775
>
> BUG=chromium:1209558
> NOTRY=true
> NOPRESUBMIT=true
> NOTREECHECKS=true
>
> Change-Id: If4f7243647bcc12ed482796c1353f0717630f6b9
> Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/2919823
> Commit-Queue: Georg Neis <neis@chromium.org>
> Reviewed-by: Igor Sheludko <ishell@chromium.org>
> Cr-Commit-Position: refs/branch-heads/9.1@{#59}
> Cr-Branched-From: …
> chore: cherry-pick fd8cbdf7b888 from v8

- shell/browser/api/electron_api_web_request.cc
- spec-main/api-web-request-spec.ts
Fixes #20751.
Notes: Fixed an issue where request headers were cleared if the optional "requestHeaders" parameter was not included in the webRequest.onBeforeSendHeaders callback response object
> fix: properly handle optional requestHeaders with onBeforeSendHeaders

- patches/chromium/.patches
- patches/chromium/cherry-pick-d9556a80a790.patch
A few fixes to the D3D11H264Accelerator
- Adds a AsD3D11H264Picture method to H264Pictures because sometimes
there can be just normal H264Pictures in the DPB and this could cause
some invalid variable access as we were statically casting the
pointer before.
- Adds a bounds check just in case there are more than 16 items in the
DPB.
(cherry picked from commit 5a3cf91d0f2352e697017e13f4754989f46f2f3e)
Bug: 1194689
Change-Id: Ief2e1d00b451fbc0585dd0b22b5aff7a6918fa11
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2923118
Commit-Queue: Ted Meyer <tmathmeyer@chromium.org>
Reviewed-by: Frank Liberato <liberato@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#888267}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2944579
Auto-Submit: …
> chore: cherry-pick d9556a80a790 from chromium

- docs/api/dialog.md
This is causing the docs to show incorrect types, as `String[] (optional)` is parsed as the text `String` followed by a link to "optional" with empty text. See e.g. https://www.electronjs.org/docs/api/dialog#dialogshowsavedialogbrowserwindow-options
Notes: none
> docs: fix broken markdown in dialog.md

- patches/chromium/.patches
- patches/chromium/cherry-pick-910e9e40d376.patch
[M90-LTS] Fix URLLoader cleanup on CorsURLLoaderFactory destruction.
Destroying one URLLoader can result in other URLLoaders getting errors,
due to to cache interconnectedness. CorsURLLoaderFactory's destructor
was not taking that into account.
Also fix a bonus bug:  HttpCache::Transaction::response_ wasn't being
cleared in HttpCache::Transaction::DoHeadersPhaseCannotProceed(), which
could result in DCHECKs when calling GetResponseInfo() when a
transaction that was waiting on a cached response from another
transaction ended up failing.
[M90]: Fixed trivial conflict
(cherry picked from commit 2f49a3c69a2184c95f43a395e4f33a3959cb8dbc)
(cherry picked from commit baf23e3c5b1394982cff718a0e055d4f239245ad)
Bug: 1209769
Change-Id: I2c18caa488767a29011aca1e1b0bace24c1ba8fc
Reviewed-on: …
> chore: cherry-pick 910e9e40d376 from chromium

- patches/v8/.patches
- patches/v8/cherry-pick-50de6a8ddad9.patch
M90-LTS: [debugger] Return ServerError if debugger agent is disabled
This returns a server error on setting breakpoints if the
agent is disabled.
(cherry picked from commit 5aa2de8128f885c44df79d38fb4aa5c6a5d94306)
Also-by: bmeurer@chromium.org
Fixed: chromium:1202534
No-Try: true
Change-Id: I87c80a4bd785fa5c59a8dd0d5ac5f4b31b015ed8
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/2874662
Commit-Queue: Kim-Anh Tran <kimanh@chromium.org>
Commit-Queue: Benedikt Meurer <bmeurer@chromium.org>
Auto-Submit: Kim-Anh Tran <kimanh@chromium.org>
Reviewed-by: Benedikt Meurer <bmeurer@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#74399}
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/2940883
Reviewed-by: Achuith …
> chore: cherry-pick 50de6a8ddad9 from v8

- patches/v8/.patches
- patches/v8/cherry-pick-fd9ce58ecd13.patch
M86-LTS: [debugger] Return ServerError if debugger agent is disabled
This returns a server error on setting breakpoints if the
agent is disabled.
(cherry picked from commit 5aa2de8128f885c44df79d38fb4aa5c6a5d94306)
Also-by: bmeurer@chromium.org
Fixed: chromium:1202534
No-Try: true
Change-Id: I87c80a4bd785fa5c59a8dd0d5ac5f4b31b015ed8
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/2874662
Commit-Queue: Kim-Anh Tran <kimanh@chromium.org>
Commit-Queue: Benedikt Meurer <bmeurer@chromium.org>
Auto-Submit: Kim-Anh Tran <kimanh@chromium.org>
Reviewed-by: Benedikt Meurer <bmeurer@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#74399}
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/2940882
Reviewed-by: Achuith …
> chore: cherry-pick fd9ce58ecd13 from v8

- shell/browser/api/electron_api_base_window.cc
- shell/browser/api/electron_api_base_window.h
- shell/browser/native_window.h
- shell/browser/native_window_mac.h
- shell/browser/native_window_mac.mm
- shell/browser/native_window_views.h
- spec-main/api-browser-window-spec.ts
Fixes an issue found while debugging https://github.com/electron/electron/issues/29732 - when a child window is attached to a parent `NSWindow`, the child window's level will be reset. E.g if one calls `childWindow.setAlwaysOnTop(true, 'screen-saver')`, this will not be honored. This fixes that by preserving the window level before it's attached to the parent and then restoring it.
Tested with https://gist.github.com/f2a3a5e8d9130223f18b8ddade390f20.
A test can't be added here because `isAlwaysOnTop` is true for all child windows, and while `setAlwaysOnTop` differentiates between different window levels the getter does not, and so it's not possible at present to tell whether or not a window level is for ex. `screen-saver` or `pop-up-menu` since `isAlwaysOnTop` would be true for both. …
> fix: child window alwaysOnTop level persistence

- shell/browser/native_window_mac.mm
Follow-up on #29677, which fixed the crash on invalid values, but an invalid value still changes the window. This just moves a block into the check for the vibrancy type so it only executes for a valid vibrancy. It needs to be after `vibrancy_type_` is set since `UpdateVibrancyRadii` reads that value.
cc @codebytere
Notes: none
> fix: ensure set vibrancy with invalid value is a no-op

- default_app/main.ts
- lib/browser/api/app.ts
- lib/browser/init.ts
- shell/app/electron_crash_reporter_client.cc
- shell/app/electron_main_delegate.cc
- shell/browser/api/electron_api_app.cc
- shell/browser/api/electron_api_crash_reporter.cc
- shell/browser/browser.cc
- shell/browser/browser_process_impl.cc
- shell/browser/electron_browser_client.cc
- shell/browser/electron_browser_context.cc
- shell/browser/electron_browser_main_parts.cc
- shell/browser/net/system_network_context_manager.cc
- shell/browser/ui/devtools_manager_delegate.cc
- shell/common/electron_paths.h
- typings/internal-electron.d.ts
Backport of #29649.
Notes: Fixed `app.getPath('logs')` returning the wrong path on Linux and Windows.
> refactor: use PathProvider for user-data-dir and others (#29649)

- lib/browser/guest-window-proxy.ts
- spec-main/guest-window-manager-spec.ts
Fixes a never-ending `sendSync` when calling `window.open` with
nativeWindowOpen: false and the new window is denied.
Fixes #29509.
Notes: Fixed a hang when denying a `window.open` using `setWindowOpenHandler` when `nativeWindowOpen: false`.
> fix: stop window.open from hanging when prevented

- lib/renderer/inspector.ts
Closes https://github.com/electron/electron/issues/29543.
Introduced with the default change from `contextIsolation: false` to `contextIsolation: true`.  When `contextIsolation` is enabled, `window.InspectorFrontendHost`, `window.Persistence`, and `window.UI` are all undefined in the isolated world. We therefore need to set them with the `contextBridge` so that we can override them correctly.
Notes: Fixed an issue where dropdown menus did not work in DevTools when `contextIsolation` was enabled.
> fix: Inspector method overrides when contextIsolation enabled

- shell/browser/native_window_mac.mm
Closes https://github.com/electron/electron/issues/29820.
Properly orders out child windows when `window.hide()` is called on a parent window. This should not change any end user behavior, but Chromium specifically DCHECKs for it so we should handle it properly.
Notes: none.
> fix: properly order out child windows on `window.hide()`

- shell/browser/api/electron_api_browser_window.cc
- shell/browser/api/electron_api_cookies.cc
- shell/browser/api/electron_api_menu_mac.mm
- shell/browser/api/electron_api_session.cc
- shell/browser/electron_browser_main_parts_posix.cc
- shell/common/extensions/electron_extensions_api_provider.cc
- shell/renderer/extensions/electron_extensions_dispatcher_delegate.cc
Trims some unused namespace and using declarations, as suggested by `clang-tidy`'s `misc-unused-using-decls` and `misc-unused-alias-decls` checks.
Notes: none
> chore: remove unused using and namespace declarations

- docs/api/browser-window.md
- docs/api/window-open.md
- docs/breaking-changes.md
- shell/browser/web_contents_preferences.cc
- spec-main/api-browser-window-spec.ts
- spec-main/chromium-spec.ts
- spec-main/fixtures/snapshots/proxy-window-open.snapshot.txt
- spec/static/main.js
- spec/webview-spec.js
This reverts #28552, instead warning of the upcoming default change. The
default change will occur instead in 15.x.
Notes: Undo the `nativeWindowOpen` default change; delayed until 15.x.
> feat: undo nativeWindowOpen default change, warn instead

- docs/api/web-request.md
Closes #28287.
Per discussion with @zcbenz, since it doesn't look like this has ever worked (the original bug goes back to 8.2.2 and I tested back to 6 as well), just update the documentation to reflect this reality. This is also consistent with `chrome.webRequest.onHeadersReceived` which does not provide `requestHeaders`.
Notes: none
> docs: remove requestHeaders in webRequest.onHeadersReceived

- shell/browser/electron_browser_client.cc
- shell/browser/electron_browser_client.h
- shell/browser/electron_browser_main_parts.cc
- shell/browser/electron_browser_main_parts.h
- shell/browser/electron_browser_main_parts_mac.mm
Geolocation was crashing in Release builds with a backtrace that seemed to implicate WASM SIMD.
```
$ lldb --debug ./Electron.app/Contents/MacOS/Electron 
(lldb) target create "./Electron.app/Contents/MacOS/Electron"
Current executable set to '/Users/omar/Downloads/electron-v13/Electron.app/Contents/MacOS/Electron' (x86_64).
(lldb) r https://www.google.com/
Process 67072 launched: '/Users/omar/Downloads/electron-v13/Electron.app/Contents/MacOS/Electron' (x86_64)
2021-06-27 10:10:30.780668-0700 Electron[67072:11102508] +[MTLIOAccelDevice registerDevices]: Zero Metal services found
Process 67072 stopped
* thread #39, name = 'Geolocation', stop reason = EXC_BAD_ACCESS (code=1, address=0x8)
frame #0: 0x0000000106a8e3e4 Electron Framework`___lldb_unnamed_symbol4$$Electron Framework + 53326868 …
```
> fix: geolocation crashes electron on macOS

- patches/chromium/.patches
- patches/chromium/cherry-pick-ee6aee64e24c.patch
[M90-LTS] Add AudioHandler to orphan handlers when context is suspended.
If the context is suspended, pulling of the audio graph is stopped.
But we still need to add the handler in this case so that when the
context is resumed, the handler is still alive until it can be safely
removed.  Hence, we must still add the handler if the context is
suspended.
Test cases from issue 1176218 manually tested with no failures.  Also
this doesn't cause any regressions in issue 1003807 and issue 1017961.
(Manually tested the test cases from those issues.)
(cherry picked from commit 4a38ea3f1f78e0a0ffc1464e227cee6c1f2fd90b)
Bug: 1176218
Change-Id: Icd927c488505dfee9ff716866f98286e286d546a
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2874771
Reviewed-by: Hongchan Choi …
> chore: cherry-pick ee6aee64e24c from chromium

- patches/chromium/.patches
- patches/chromium/cherry-pick-ff0d013f60fa.patch
[86-LTS] Add AudioHandler to orphan handlers when context is suspended.
If the context is suspended, pulling of the audio graph is stopped.
But we still need to add the handler in this case so that when the
context is resumed, the handler is still alive until it can be safely
removed.  Hence, we must still add the handler if the context is
suspended.
Test cases from issue 1176218 manually tested with no failures.  Also
this doesn't cause any regressions in issue 1003807 and issue 1017961.
(Manually tested the test cases from those issues.)
(cherry picked from commit 4a38ea3f1f78e0a0ffc1464e227cee6c1f2fd90b)
Bug: 1176218
Change-Id: Icd927c488505dfee9ff716866f98286e286d546a
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2874771
Commit-Queue: Raymond Toy …
> chore: cherry-pick ff0d013f60fa from chromium

- .circleci/config.yml
- script/spec-runner.js
- vsts-arm32v7.yml
- vsts-arm64v8.yml
The new installs of python module, python-dbusmock, is broken for python2. The tests still run fine on linux machine in Electron's pipeline setup on CircleCI, because the docker image used has the non-broken version of python-dbusmock for python2 installed. But running electron tests on any other linux machine would fail if they don't have this non-broken version of python-dbusmock for python2 installed, already, which is the case for most of the machines.
Moreover, Python2 is deprecated now. So it would be better if we change the python interpreter in script/spec-runner.js file to python3, for which all the python modules are updated and working.
Notes: none
> chore: set python interpreter to python3 in script/spec-runner.js

- docs/api/menu-item.md
- lib/browser/api/menu-item.ts
- shell/browser/api/electron_api_menu.cc
- shell/browser/api/electron_api_menu.h
- shell/browser/api/electron_api_menu_mac.mm
- shell/browser/ui/cocoa/electron_menu_controller.h
- shell/browser/ui/cocoa/electron_menu_controller.mm
This allows folks to read the user-assigned accelerator that macOS users can provide in system preferences. Useful for showing in-app shortcut help dialogs, you need to know if the accelerator you provided is not being used in favor of a user assigned one.
Notes: Added new `MenuItem.userAccelerator` property to read user-assigned macOS accelerator overrides
> feat: add MenuItem.userAccelerator property

- shell/browser/web_view_guest_delegate.cc
- spec-main/webview-spec.ts
- spec/fixtures/api/native-window-open-noopener.html
Fixes https://github.com/electron/electron/issues/28348
When running the test case in debug build, it will be seen that `RWHV::SetActive` call fails because it tries to access an interface [blink::FrameWidget](https://source.chromium.org/chromium/chromium/src/+/main:content/browser/renderer_host/render_widget_host_impl.cc;l=1301) that is not bound.
The interface usually gets bound when `RenderView` gets created during navigation
```
RenderWidgetHostImpl::BindAndGenerateCreateFrameWidgetParams
RenderViewHostImpl::CreateRenderView
WebContentsImpl::CreateRenderViewForRenderManager
RenderFrameHostManager::InitRenderView
```
When starting with window.opener suppressed, `WebViewGuestDelegate::CreateNewGuestWindow` created NSView for page which is going to be navigated …
> fix: crash when clicking links with target=_blank from webview

- shell/browser/api/electron_api_web_contents.cc
- spec-main/api-web-contents-spec.ts
Fixes #29942.
Sometimes pages don't have any navigation entries associated with them, e.g.
when calling `window.open('')`. This allows the page title update to be
propagated even in that instance.
I suspect this method could be even further simplified, but this is the minimal
change to fix the linked bug.
Notes: Fixed page title not being updated on child windows without navigation entries under nativeWindowOpen.
> fix: correctly propagate title updates for window with no navigation entries

- shell/browser/native_window_mac.mm
Closes https://github.com/electron/electron/issues/29260.
Fixes an issue where Electron could crash after calling `app.quit()` on macOS. This can happen as a result of `[NSEvent removeMonitor:]`(https://developer.apple.com/documentation/appkit/nsevent/1533709-removemonitor?language=objc) being called twice; from the documentation discussion:
> You must ensure that eventMonitor is removed only once. Removing the same eventMonitor instance multiple times results in an over-release condition, even in a Garbage Collected environment
This fixes any potential issues by ensuring that we only call `[NSEvent removeMonitor:]` on a non-nil `id`. Chromium uses a similar approach [here](https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/ui/views/eye_dropper/eye_dropper_view_mac.mm; …
> fix: potential crash on macOS app exit

- shell/browser/electron_browser_client.cc
Closes https://github.com/electron/electron/issues/29909.
Makes it such that `ElectronBrowserClient::GetDefaultDownloadDirectory()` honors user-defined Downloads directories by calling out to platform-specific download logic defined [in Chromium](https://source.chromium.org/chromium/chromium/src/+/main:chrome/common/chrome_paths_internal.h;drc=c14f6f4b9c44fe479a8d004576b42723b2a5feb6;bpv=1;bpt=1;l=54)
Notes: Fixes an issue where Electron would sometimes not honor the user-defined Downloads directory.
> fix: honor user-defined Downloads directory

- script/release/ci-release-build.js
To support accurate after-the-fact reruns of release builds appveyor needs to take in a commit SHA.  Circle we can just use the "rerun" API, we can't do that for apveyor because it loses environment variables between runs.
> build: add support for spawning builds for a specific commit on appveyor

- docs/api/browser-window.md
- docs/api/frameless-window.md
- shell/browser/api/electron_api_browser_window.cc
- shell/browser/api/electron_api_browser_window.h
- shell/browser/api/electron_api_web_contents.cc
- shell/browser/native_window.cc
- shell/browser/native_window.h
- shell/browser/native_window_mac.h
- shell/browser/native_window_mac.mm
- shell/browser/native_window_observer.h
- shell/browser/ui/cocoa/window_buttons_view.h
- shell/browser/ui/cocoa/window_buttons_view.mm
- shell/common/options_switches.cc
- shell/common/options_switches.h
- spec-main/api-browser-window-spec.ts
- spec-main/fixtures/pages/overlay.html
This PR adds a new property `titleBarOverlay` to `BrowserWindow` on macOS to support [Window Controls Overlay](https://github.com/WICG/window-controls-overlay/blob/main/explainer.md).   On macOS, when using a frameless window in conjunction with `win.setWindowButtonVisibility(true)` or using a `titleBarStyle` so that the traffic lights are visible, this property enables the Window Controls Overlay [JavaScript APIs ](https://github.com/WICG/window-controls-overlay/blob/main/explainer.md#javascript-apis) and [CSS Environment Variables](https://github.com/WICG/window-controls-overlay/blob/main/explainer.md#css-environment-variables) will be available for developers to use to better style custom titlebars.
There will be another PR forthcoming that will enable this capability on Windows. …
> feat: enable window controls overlay on macOS

- shell/app/electron_main.cc
- shell/app/electron_main_delegate.cc
- shell/browser/api/electron_api_protocol.cc
- shell/browser/api/electron_api_web_request.cc
- shell/browser/api/gpu_info_enumerator.h
- shell/common/gin_helper/trackable_object.cc
- shell/renderer/api/electron_api_context_bridge.cc
- shell/renderer/api/electron_api_web_frame.cc
Most of the time you just `const char*` is not what you want, for constant strings. More discussion [can be found here](https://groups.google.com/a/chromium.org/g/chromium-dev/c/iyjW0-fXT9A/m/20v1n0eWtFMJ).
For consistency, favor `const char ...[]` over `const char* const` for defining a string constant. The constants in `GPUInfoEnumerator` are an exception I've made here, as they're member variables and wouldn't otherwise compile as `const char ...[]`. They should probably be made static or moved outside of the class, but I decided that was outside the scope of this PR.
Notes: none
> chore: cleanup usages of const char*

- patches/config.json
- patches/usrsctp/.patches
- patches/usrsctp/improve_restart_handling.patch
Backport https://github.com/sctplab/usrsctp/commit/0f8d58300b1fdcd943b4a9dd3fbd830825390d4d as per https://chromium-review.googlesource.com/c/chromium/src/+/2945772.
Improve restart handling.
This fixes in particular a possible use after free bug reported
Anatoly Korniltsev and Taylor Brandstetter for the userland stack.
Notes: Security: backported fix for CVE-2021-30523.
> chore: cherry-pick 0f8d58300b from usrsctp

- patches/chromium/.patches
- patches/chromium/webview_fullscreen.patch
- shell/browser/api/electron_api_web_contents.cc
- shell/browser/api/electron_api_web_contents.h
- shell/browser/web_view_manager.h
- spec-main/fixtures/webview/fullscreen/frame.html
- spec-main/fixtures/webview/fullscreen/main.html
- spec-main/webview-spec.ts
Close https://github.com/electron/electron/issues/27719.
When entering fullscreen with Element.requestFullscreen in child frames, the parent frame should also enter fullscreen mode too. Chromium handles this for iframes, but not for webviews, as the latter are essentially main frames instead of child frames.
This PR makes sure webviews propagate the fullscreen state to embedder.
Note that the patch itself in this PR is not enough to fix the issue, to fix it we have to make the fullscreen state sync between the webview and its embedder frame, and in Electron we are just manually synchronizing the states. A decent patch should change callers or callees of `IsFullscreenForTabOrPending` to be aware of outer frames (webviews), but it would require much more refactoring. I think it does not …
> fix: webview should maximize on requestFullscreen

- shell/browser/api/electron_api_web_contents.cc
- shell/browser/api/electron_api_web_contents.h
There is no more code using `WebContents. _grantOriginAccess`.
Notes: none
> chore: remove unused _grantOriginAccess method

- docs/tutorial/notifications.md
Electron's Notification API now has the `hasReply` feature, there is no more need to mention the third party module.
Notes: none
> docs: remove mention of node-mac-notifier

- shell/browser/notifications/mac/cocoa_notification.mm
Fix a leak when using `NSUUID` in `Notification`.
Notes: Fix memory leak when creating notification on macOS.
> fix: do not leak NSUUID

- patches/chromium/.patches
- patches/chromium/cherry-pick-cc20b36a5845.patch
Use a 100ms timer in MacScrollbarAnimatorImpl::StartScrollbarPaintTimer
MacScrollbarAnimatorImpl::StartScrollbarPaintTimer has a timer that
runs while ShouldSuspendScrollAnimations is true. The timer was changed
from 100ms to 1ms in https://crrev.com/376453. This was later changed to
0ms in https://crrev.com/434428 which caused a performance regression
(https://crbug.com/713669). The timer was then changed back to 1ms in
https://crrev.com/470823 with a comment about giving other tasks time to
cancel the timer. This patch restores the 100ms timer. The comment has
been removed because this timer is more of a polling mechanism.
Bug: 1090000
Change-Id: I4041d9ba5869abbe4ff7d55d56d921c7d90a72ad
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2903830
Reviewed-by: Hiroki …
> chore: cherry-pick cc20b36a5845 from chromium

- docs/api/context-bridge.md
The API has been around for about 3 years. It should no longer be considered experimental.
/cc @MarshallOfSound 
Notes: none
> docs: remove `Experimental` from `contextBridge.exposeInMainWorld`

- lib/worker/init.ts
- spec-main/chromium-spec.ts
- spec-main/fixtures/apps/self-module-paths/index.html
- spec-main/fixtures/apps/self-module-paths/main.js
- spec-main/fixtures/apps/self-module-paths/package.json
- spec-main/fixtures/apps/self-module-paths/renderer.js
- spec-main/fixtures/apps/self-module-paths/worker.js
Closes https://github.com/electron/electron/issues/24735.
Fixes an issue where `self.module.paths` didn't work in a web worker context. Fixed with the same logic as is present in `renderer/init.ts`.
Notes: Fixed an issue where `self.module.paths` wouldn't work in Workers.
> fix: self.module.paths not working in web workers

- shell/browser/browser.cc
- shell/browser/browser.h
Just a typo in the member variable and getter names.
Notes: none
> chore: correct spelling of is_quitting in electron::Browser

- patches/node/.patches
- patches/node/src_add_missing_context_scopes.patch
Closes https://github.com/electron/electron/issues/29920.
This was occurring because Node.js wasn't properly entering the `v8::Context` before resolving the Promise. This was fixed in https://github.com/nodejs/node/pull/36413 which is present in v14.17.0 and beyond, and so needs to be backported only to v12 and v13.
Notes: Fixed a possible renderer crash when using `fsPromises.readFile`.
> fix: fsPromises.readFile renderer crash

- npm/install.js
Refs #29627
Notes: Installing the `electron` package on an M1 macbook while using an x64 version of node will now automatically download the arm64 version of Electron instead of the x64 version
> fix: download the arm64 version of Electron when running node under rosetta

- shell/browser/api/electron_api_web_contents.cc
Follow-up to #20354. Caused by https://source.chromium.org/chromium/chromium/src/+/9bec86a5335c6f8bfbf002ef3c023c8d7e38c143
```
In file included from ../../electron/shell/browser/api/electron_api_web_contents.cc:49:
../../content/public/browser/plugin_service.h:17:2: error: "Plugins should be enabled"
#error "Plugins should be enabled"
^
1 error generated.
```
Notes: none
> build: fix building with enable_plugins = false

- docs/api/web-request.md
- shell/browser/api/electron_api_web_request.cc
Making it match [enum class WebRequestResourceType](https://source.chromium.org/chromium/chromium/src/+/main:extensions/browser/api/web_request/web_request_resource_type.h;l=18-33;drc=1fa0d9e0b955e66dcced5c70bf8098515759b915;bpv=1;bpt=1) in Chromium. Also add strong typing for the enum values in TypeScript.
Note: I am not sure if this is considered a semver/patch as values previously returned as `other` are now converted to the appropriate value name.
Notes: Added missing `resourceType` conversions for `webRequest` listener details: `font`, `ping`, `cspReport`, `media`, `webSocket`.
> feat: add missing resourceType conversions for webRequest listener details

- docs/api/structures/web-request-filter.md
- docs/api/web-request.md
- filenames.auto.gni
In case `types` filter gets added (#10867), it will be done in a single place.
Notes: none
> docs: move webRequest filters definition to structures/web-request-filter.md

- docs/fiddles/system/protocol-handler/launch-app-from-URL-in-another-app/index.html
- docs/fiddles/system/protocol-handler/launch-app-from-URL-in-another-app/main.js
- docs/fiddles/system/protocol-handler/launch-app-from-URL-in-another-app/preload.js
- docs/fiddles/system/protocol-handler/launch-app-from-URL-in-another-app/renderer.js
- docs/tutorial/launch-app-from-url-in-another-app.md
Changed docs to use `protocol.registerFileProtocol` rather than `app.setAsDefaultProtocol` and removed legacy code from the index.html file.
Notes: update protocol-handler docs to use `protocol.registerFileProtocol`
> docs: modernize protocol-handler docs

- shell/browser/native_window_mac.mm
- spec-main/api-browser-window-spec.ts
Fixes https://github.com/electron/electron/issues/29758
The call to `NativeWidgetMac::Activate` added in https://github.com/electron/electron/pull/29204 tries to set the visibility state of the window via `NativeWidgetNSWindowBridge` with state [kShowAndActivateWindow](https://source.chromium.org/chromium/chromium/src/+/main:components/remote_cocoa/common/native_widget_ns_window.mojom;l=50-51) which eventually calls `[NSWindow makeKeyAndOrderFront:]`
This is all fine for normal cases, but under the following situations it triggers a series of `windowDidBecomeKey:` notifications that messes with window ordering.
1) When opening panels the main window takes key status and captures the input events
2) When in fullscreen opening a second window does not inherit the fullscreen behavior
3) …
> fix: window ordering on mac

- shell/browser/api/electron_api_web_contents.cc
- shell/browser/browser_win.cc
- shell/browser/notifications/win/win32_desktop_notifications/common.h
- shell/browser/notifications/win/win32_desktop_notifications/desktop_notification_controller.cc
- shell/browser/notifications/win/win32_desktop_notifications/desktop_notification_controller.h
- shell/browser/notifications/win/win32_desktop_notifications/toast.cc
- shell/browser/notifications/win/win32_desktop_notifications/toast_uia.cc
- shell/browser/notifications/win/win32_desktop_notifications/toast_uia.h
- shell/browser/notifications/win/win32_notification.cc
- shell/browser/notifications/win/windows_toast_notification.cc
- shell/browser/notifications/win/windows_toast_notification.h
- shell/browser/ui/message_box_win.cc
- shell/browser/ui/win/notify_icon.cc
`base::as_wcstr` is cost free but `base::UTF16ToWide` will do a string copy. So we should use `std::u16string` to store strings when possible, instead of converting them to `std::wstring`s.
Notes: none
> chore: remove unneeded conversions between wstring and u16string

- spec-main/api-browser-window-spec.ts
https://github.com/electron/electron/pull/30081 attempted to reduce the flakiness of the test but it still fails in CI https://github.com/electron/electron/runs/3043847085, I am unable to repro the failure locally hence disabling it.
Notes: none
> chore: disable fullscreen test on mac arm

- shell/browser/api/electron_api_system_preferences_mac.mm
Fixes #26628.
The docs already state that this returns #RRGGBBAA, so this change brings the
function in line with the docs.
Notes: Fixed systemPreferences.getSystemColor returning colors missing alpha values.
> fix: return RGBA values from getSystemColor

- shell/browser/login_handler.cc
Closes #30065.
This is because somehow the LoginHandler is deleted while calling Emit(), so
accessing the `auth_required_callback_` member variable after that is a
segmentation fault.
It looks like calling `cb()` from JS ultimately ends up deleting the
LoginHandler:
https://source.chromium.org/chromium/chromium/src/+/main:content/browser/storage_partition_impl.cc;l=523;drc=ded7717f5252a0c9d9de56bc22483b195d1801e0.
So this crashes: https://github.com/electron/electron/blob/ccfde6c9d44e64621e2c3a92e5113c1d26e61d67/shell/browser/login_handler.cc#L73 because `this` has been deleted.
We can work around that by taking a weak ptr before the `Emit` call and checking it afterwards, to guard against deletion. In that situation, `auth_required_callback_` would have been null anyway, so there …
> fix: crash when invoking login callback synchronously

- build/npm-run.py
The results that come back from `npm run` tools are not necessarily encoded as
ascii.
Notes: none
> build: decode error output as utf8

- spec-main/logging-spec.ts
When running tests with the release build of Electron we are getting this error:
```
An error occurred while running the spec-main spec runner
Error: No such module was linked: electron_common_testing
at process._linkedBinding (internal/bootstrap/loaders.js:127:34)
at Object.<anonymous> (C:\agent\_work\283\b\src\electron\spec-main\logging-spec.ts:11:20)
at Module._compile (internal/modules/cjs/loader.js:1125:30)
at Module.m._compile (C:\agent\_work\283\b\src\electron\node_modules\ts-node\src\index.ts:435:23)
at Module._extensions..js (internal/modules/cjs/loader.js:1155:10)
at Object.require.extensions.<computed> [as .ts] (C:\agent\_work\283\b\src\electron\node_modules\ts-node\src\index.ts:438:12)
at Module.load (internal/modules/cjs/loader.js:982:32)
at Module._load …
```
> test: fix check for electron_common_testing binding in logging-spec.ts

- docs/api/app.md
- shell/browser/api/electron_api_app.cc
- shell/browser/api/electron_api_app.h
- shell/browser/browser.h
- shell/browser/browser_mac.mm
- shell/browser/browser_observer.h
- shell/browser/mac/electron_application_delegate.mm
This PR aims to extend the existing `continue-activity` event params to resolve issue https://github.com/electron/electron/issues/29926.
Primarily a new `details` object is added as a parameter to the event, and `webpageURL` is added inside that details object if the userActivity contains `webpageURL`. 
Notes:  Extended `continue-activity` event API to support `webpageURL` property from `NSUserActivity`.
> feat: continue-activity event is extended to support webpageURL property

- CONTRIBUTING.md
- docs/tutorial/support.md
Merge after 8 week release cadence blog: https://github.com/electron/electronjs.org/pull/5463
Updates our release cadence from 12 weeks to 8 weeks in CONTRIBUTING.md.
Notes: none
> chore: update releases to 8 weeks in CONTRIBUTING

- shell/browser/api/electron_api_web_contents.cc
- spec-main/webview-spec.ts
Refs https://github.com/electron/electron/issues/27719.
There is a small problem with the issue's fix https://github.com/electron/electron/pull/29952 that, after entering fullscreen from webview, pressing ESC does not exit fullscreen for the window.
This is caused by native window fullscreen state not synchronized with html fullscreen state, it was intended because I thought there was no need to do so.
Notes: Fix pressing ESC not exiting fullscreen from `webview`.
> fix: pressing ESC should exit fullscreen from webview

- shell/app/electron_main_delegate.cc
- shell/browser/browser.cc
- shell/browser/electron_browser_context.cc
- shell/common/application_info.cc
- shell/common/application_info.h
- shell/common/application_info_linux.cc
- spec-main/api-app-spec.ts
Fixes #30112.
Notes: Fixed an issue where the user-data directory was incorrect in unpackaged apps.
> fix: use correct userData path when unbundled

- docs/tutorial/launch-app-from-url-in-another-app.md
This is breaking the build in `electron/electronjs.org-new` and will
most likely not work when clicking the "Fiddle" button.
Rel: https://github.com/electron/electronjs.org-new/pull/65
cc @erickzhao 
Notes: none
> docs: fix fiddle path

- docs/api/extensions.md
According to the extensions support docs, https://www.electronjs.org/docs/api/extensions , chrome.runtime.reload in not available/supported in electron apps. Mentioning this as a possible cause for `extension-loaded` event getting fired seems incorrect if the API can't be triggered inside electron app.
**Edit**: As @nornagon pointed out, it seems like runtime.reload is available but only for background scripts. It makes sense to mention this as a cause for `extension-loaded` event in session docs. And it should also be specified as supported extension API accordingly here https://www.electronjs.org/docs/api/extensions
Notes: none
> docs: add runtime.reload as supported extension api

- shell/browser/native_window_mac.mm
Closes https://github.com/electron/electron/issues/30026.
Fixes an issue where the traffic lights would get double-drawn when exiting fullscreen and adding a `BrowserView` on macOS. In https://github.com/electron/electron/commit/8bf66f8974c6dc0aecdc22e4ddce2881e1836840 the original code did not redraw traffic lights when the window was fullscreened, but this logic did not perisist and then when I merged https://github.com/electron/electron/pull/29595 this created the issue.
We fix this by not reordering the buttons in the view hierarchy when we're in fullscreen mode.
Tested with https://gist.github.com/45f0a58d69bec2834535e57768363572 and confirmed not to regress https://github.com/electron/electron/issues/29541.
Notes: Fixes an issue where the traffic lights would get double-drawn when …
> fix: double traffic lights on exit fullscreen

- shell/browser/net/electron_url_loader_factory.cc
- shell/browser/net/electron_url_loader_factory.h
- spec-main/api-protocol-spec.ts
- spec-main/api-web-request-spec.ts
Fixes #29656.
Makes use of `URLLoader::FollowRedirect` to more properly handle redirects for custom protocols. Currently cross-protocol redirects work without this fix because Chromium disconnects the `URLLoader` and creates a new one for the new protocol, since `URLLoaderFactory` is registered per-scheme, so a different factory is used for the redirected request.
This change also ensures that redirects within custom protocols play nice with `webRequest`, since using `FollowRedirect` lets headers modified by `webRequest.onBeforeSendHeaders` for the redirected request be properly applied.
~Putting this PR as a draft for now, because it needs [an upstream change](https://chromiumdash.appspot.com/commits?commit=28770d1c88e71756a98ab9645d8f6db92ed393b2&platform=Mac) which landed in …
> fix: handle redirects within registered protocols

- shell/browser/api/electron_api_web_contents.cc
Closes https://github.com/electron/electron/issues/30082.
Fixes an issue where BrowserWindows would not properly honor `transparency: true` or a `backgroundColor` being set in their constructor options. This happened as a result of [this CL](https://chromium-review.googlesource.com/c/chromium/src/+/2695928) rolled into Electron via https://github.com/electron/electron/pull/29751. The new method `SetPageBaseBackgroundColor` set the default content background color - i.e, the color that would appear behind the content unless the content overrode it. What then happened was that when we changed our logic to call this method, it was eventually [overridden by Blink](https://source.chromium.org/chromium/chromium/src/+/main:content/browser/renderer_host/render_widget_host_view_base.cc;drc=3bfd3ba3 …
> fix: BrowserWindow transparency not working

- shell/browser/ui/tray_icon_cocoa.mm
Fixes #29287.
Notes: Fixed tray.setTitle not respecting ANSI colors if a font type was specified.
> fix: allow colored tray titles when font type is specified

- patches/v8/.patches
- patches/v8/cherry-pick-e76178b896f2.patch
Merged: [JSON] Fix GC issue in BuildJsonObject
We must ensure that the sweeper is not running or has already swept
mutable_double_buffer. Otherwise the GC can add it to the free list.
Change-Id: If0fc7617acdb6690f0567215b78f8728e1643ec0
No-Try: true
Bug: v8:11837, chromium:1214842
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/2993033
Reviewed-by: Michael Lippautz <mlippautz@chromium.org>
Commit-Queue: Victor Gomes <victorgomes@chromium.org>
Cr-Commit-Position: refs/branch-heads/9.1@{#75}
Cr-Branched-From: 0e4ac64a8cf298b14034a22f9fe7b085d2cb238d-refs/heads/9.1.269@{#1}
Cr-Branched-From: f565e72d5ba88daae35a59d0f978643e2343e912-refs/heads/master@{#73847}
Notes: Security: backported …
> chore: cherry-pick e76178b896f2 from v8

- docs/tutorial/sandbox.md
Fixes broken context isolation link in the [sandbox](https://www.electronjs.org/docs/tutorial/sandbox#preload-scripts) documentation.
The link is named `context-isolation` at the end of the file but `contextIsolation` is being used instead.
Notes: none
> docs: fix broken context isolation link in sandbox docs

- docs/tutorial/code-signing.md
- docs/tutorial/dark-mode.md
Electron Packager updated its default branch to `main` (much like `electron/electron`), and so did the API docs links. As a result, there are a couple of guides which need their links updated.
Notes: none
> docs: update default branch for Electron Packager API links

- script/release/notes/index.js
- script/release/prepare-release.js
- script/release/publish-to-npm.js
- script/release/version-bumper.js
- script/release/version-utils.js
- spec-main/version-bump-spec.ts
Updates the version-bumper script and supporting utils to support an alpha build for Electron 15.
This PR also adds a mock to support new version-bumper tests for alpha tags. Because we don't currently have alpha tags and were previously using Electron's actual git tags from 2.x.x, a mock was required to test for alphas. These tests are currently separated from the rest to make them easier to delete, but they can easily be integrated with the main tests if we decide we want to keep the alpha channel.
Notes: none
> build: update version-bumper to support alpha

- script/release/release.js
This caused a silent failure in our beta release today
> build: handle release failure by exiting with code 1

- patches/chromium/.patches
- patches/chromium/cherry-pick-e60cc80ff744.patch
[M92] Fix multidraw validation drawcount + offset out of bounds
(cherry picked from commit 7d0a12ce19fed024d56b95a692d888fe3ef14e2f)
Bug: 1219886
Change-Id: I8a84664150758370d9a77ee22ac5549bead0e37e
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2977850
Commit-Queue: Kenneth Russell <kbr@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#895423}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2988885
Reviewed-by: Shrek Shao <shrekshao@google.com>
Reviewed-by: Austin Eng <enga@chromium.org>
Cr-Commit-Position: refs/branch-heads/4515@{#1101}
Cr-Branched-From: 488fc70865ddaa05324ac00a54a6eb783b4bc41c-refs/heads/master@{#885287}
Notes: Security: backported fix for CVE-2021-30568.
> chore: cherry-pick e60cc80ff744 from chromium

- patches/chromium/.patches
- patches/chromium/cherry-pick-3feda0244490.patch
serial: Fix parent class tracing for SerialPort
When SerialPort was updated to be ActiveScriptWrappable and an
EventTarget the Trace method was not updated to call the parent class
trace methods.
(cherry picked from commit 4059ecc3a5352601a4d79196f90c8ca19262afe1)
Bug: 1220078
Change-Id: If6967a913268bce86d4488359a9418a814530f84
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2965255
Auto-Submit: Reilly Grant <reillyg@chromium.org>
Reviewed-by: Tom Sepez <tsepez@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#893039}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2992740
Commit-Queue: Reilly Grant …
> chore: cherry-pick 3feda0244490 from chromium
