electron/electron

- patches/chromium/.patches
- patches/chromium/cherry-pick-5487040a284a.patch
Closes https://github.com/electron/electron/issues/30173.
Don't TexImage via GPU when OOP raster is disabled on Windows.
For some reason it's much slower than the the non-GPU based path. The
test page https://koush.github.io/webcodecs/ goes from ~270fps decoding
and ~5fps rendering to ~300fps decoding and >> 60fps rendering when
running with --disable-oop-rasterization.
R=kbr
Bug: 1227921
Change-Id: I1abbcfd5c4a515540753c8c5e681949f6f236c9c
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3018801
Commit-Queue: Dale Curtis <dalecurtis@chromium.org>
Cr-Commit-Position: refs/heads/master@{#900587}
Closes #30173.
Notes: Backported fix for https://crbug.com/1227921.
> chore: cherry-pick 5487040a284a from chromium

- shell/app/electron_main.cc
- spec-main/crash-spec.ts
- spec-main/fixtures/crash-cases/quit-on-crashed-event/index.js
Increase main thread stack size to 4MiB on Windows x86, to fix V8 stack overflow (#28487 ).
@deepak1556 increased stack size on Windows x64 to 8MiB, but only 0.5MiB on Windows x86 (#27376 ). It's not enough for V8.
Fixes https://github.com/electron/electron/issues/28487
Fixes https://github.com/electron/electron/issues/29177
callstack while stack overflow.
```
0:000:x86> kbL
00 000ce034 0223dee3 000ce040 03a05afc 95de35b8 electron!v8::internal::Isolate::StackOverflow
01 000ce050 01f77440 00495bd8 0add5360 03a05afc electron!v8::internal::PendingCompilationErrorHandler::ReportErrors+0x33
02 000ce074 01f74ce5 000ce1a8 000ce150 000ce288 electron!v8::internal::`anonymous namespace'::FailWithPreparedPendingException+0x40
03 (Inline) -------- -------- -------- -------- …
```
> fix: increase stack size on windows x86

- patches/chromium/.patches
- patches/chromium/cherry-pick-cd98d7c0dae9.patch
Fix UAF problem in SharedImageInterfaceInProcess
(cherry picked from commit 38b4905f8d877b27bc2d4ccd4cfc0f82b636deea)
Bug: 1216822
Change-Id: I8ae1f7c406e1899e500ee7ddeaaf18230b1cbcb2
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2971144
Commit-Queue: Peng Huang <penghuang@chromium.org>
Commit-Queue: Vasiliy Telezhnikov <vasilyt@chromium.org>
Auto-Submit: Peng Huang <penghuang@chromium.org>
Reviewed-by: Vasiliy Telezhnikov <vasilyt@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#893931}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3011895
Auto-Submit: Mason Freed <masonf@chromium.org>
Reviewed-by: Peng Huang <penghuang@chromium.org>
Cr-Commit-Position: refs/branch-heads/4515@{#1369} …
> chore: cherry-pick cd98d7c0dae9 from chromium

- shell/browser/api/electron_api_browser_window.cc
- shell/browser/api/electron_api_web_contents.cc
- shell/browser/api/electron_api_web_contents_mac.mm
- shell/browser/api/electron_api_web_view_manager.cc
- shell/browser/electron_browser_client.cc
- shell/browser/electron_download_manager_delegate.cc
- shell/browser/electron_javascript_dialog_manager.cc
- shell/browser/web_contents_preferences.cc
- shell/browser/web_contents_preferences.h
- spec-main/api-browser-window-spec.ts
This refactors WebContentsPreferences to store its values directly, rather than
keyed by string in a base::DictionaryValue. It also centralizes logic for
default values; callers no longer have to provide a default value. And finally,
it centralizes all parsing logic in web\_contents\_preferences.cc, instead of
having logic for fetching keys by string scattered around the codebase.
I think this is not yet the best form of WebContentsPreferences. In particular,
the `Merge` method makes me uneasy, but I don't yet fully understand why it is
architected that way currently. It has to do with webviews.
This refactor is motivated by a desire to change the default for `sandbox`
under complex circumstances. The straightforward approach to that (shown …
> refactor: remove base::Value from WebContentsPreferences

- shell/browser/native_window_mac.mm
- shell/browser/ui/cocoa/window_buttons_view.h
- shell/browser/ui/cocoa/window_buttons_view.mm
Close https://github.com/electron/electron/issues/30230.
Since macOS 11 the default position of traffic lights has changed, but #27489 did not take account of it. This PR updates the position of traffic lights for `titleBarStyle: 'hidden'`, so the behavior matches Electron <= 12.
Notes: Fix frameless window having wrong traffic lights position on macOS 11.
> fix: update traffic lights position for macOS 11

- shell/browser/electron_browser_context.cc
- shell/browser/electron_browser_context.h
- shell/browser/serial/electron_serial_delegate.cc
- shell/browser/serial/serial_chooser_context.cc
- shell/browser/serial/serial_chooser_context.h
- shell/browser/serial/serial_chooser_context_factory.cc
- shell/browser/serial/serial_chooser_controller.cc
- shell/browser/serial/serial_chooser_controller.h
When I implemented web serial in #25237, I did not add logic to persist serial ports that permission has been granted due to complexity in getting [ObjectPermissionContextBase](https://chromium.googlesource.com/chromium/src/+/main/components/permissions/object_permission_context_base.h) working in Electron.  This PR fixes that issue by adding functions to ElectronBrowserContext to persist and retrieve saved devices to/from the BrowserContext.  These methods will also be used by the forthcoming WebHID implementation.
Fixes #29366
Notes: Fixed navigator.serial.getPorts() to return previously selected ports.
> fix: persist permission granted to serial ports

- patches/v8/.patches
- patches/v8/cherry-pick-e76178b896f2.patch
Fix use-after-free with XSLT strip-space
Fixed: 1219209
Change-Id: I3baab9d1b419407d964a80f10c6ca05e0294554f
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2965632
Commit-Queue: Joey Arhar <jarhar@chromium.org>
Reviewed-by: Stephen Chenney <schenney@chromium.org>
Cr-Commit-Position: refs/heads/master@{#892861}
Notes: Security: backported fix for CVE-2021-30560.
> chore: cherry-pick 79fc7bcbc9 from chromium.

- lib/browser/devtools.ts
- lib/browser/guest-view-manager.ts
- lib/browser/guest-window-manager.ts
- lib/browser/guest-window-proxy.ts
- spec-main/ambient.d.ts
- typings/internal-electron.d.ts
The following APIs can return `null`:
https://github.com/electron/electron/blob/b8261f15916eb94428d5672716f85c56720b1501/shell/browser/api/electron_api_web_contents.cc#L3043-L3065
Notes: none
> fix: type internal APIs that can return null properly

- docs/api/menu-item.md
`shareMenu` (#25629) and `toggleSpellChecker` (#26276) were missing from the `menuItem.role` documentation. I think this also affects the [generated TypeScript declarations](https://unpkg.com/browse/electron@13.1.7/electron.d.ts#L5316).
Cc @zcbenz
Notes: none
> fix: Add missing items to menuItem.role documentation

- patches/chromium/.patches
- patches/chromium/cherry-pick-ac9dc1235e28.patch
Add locks and empty string checks to FakeV4L2Impl
FakeV4L2Impl is crashed by fuzzer with some weird ASAN errors, which
turned out to be a threading issue.
Bug: 1205059,1196302
Change-Id: Ieb3a917c9a4549b655862e69214774e183a70bc3
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2883613
Reviewed-by: Ricky Liang <jcliang@chromium.org>
Commit-Queue: Ilya Nikolaevskiy <ilnik@chromium.org>
Cr-Commit-Position: refs/heads/master@{#883390}
Notes: Security: backported fix for 1205059,1196302.
> chore: cherry-pick ac9dc1235e28 from chromium

- patches/v8/.patches
- patches/v8/cherry-pick-e38d55313ad9.patch
Merged: [liftoff] Fix merges with moves of cache registers
On v9.2 we did not have a chached memory start yet, so the patch needed
major adjustments.
This is the original CL description:
We did not handle conflicts between regular register moves and the
cached instance / cached memory start correctly. This could lead to us
overwriting a regular register when restoring the cached instance, which
results in either crashes or miscalculations afterwards.
R=ahaas@chromium.org
(cherry picked from commit cb6218cab029d7ab08bc6d24200a9a966db826ae)
Bug: chromium:1217064
No-Try: true
Change-Id: Iea849950ed1209efdb965ec49e921a0a26513fef
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/3024151 …
> chore: cherry-pick e38d55313ad9 from v8

- .circleci/config.yml
Should dramatically improve our forked CI flakes
Notes: none
> build: set the export goma auth fallback flag for the control process

- lib/browser/guest-view-manager.ts
- lib/renderer/init.ts
- lib/renderer/web-view/web-view-init.ts
- lib/renderer/window-setup.ts
- lib/sandboxed_renderer/init.ts
- patches/chromium/allow_in-process_windows_to_have_different_web_prefs.patch
- shell/browser/web_contents_preferences.cc
- shell/browser/web_contents_preferences.h
- shell/browser/web_view_manager.cc
- shell/browser/web_view_manager.h
- shell/common/options_switches.cc
- shell/common/options_switches.h
- shell/renderer/api/electron_api_web_frame.cc
- typings/internal-ambient.d.ts
- typings/internal-electron.d.ts
This is going to allow creating the webContents for webview with all webPreferences right away, removing the need for `WebContentsPreferences::Merge`. Enables #30311.
Notes: none
> refactor: remove guestInstanceId from WebPreferences

- patches/v8/.patches
- patches/v8/merged_compiler_fix_a_bug_in.patch
Merged: [compiler] Fix a bug in CodeGenerator::AddTranslationForOperand
(cherry picked from commit 374354bfe4a30740b96936b33e522d6fcd1cda67)
Bug: chromium:1228407
No-Try: true
Change-Id: I358d8736b7b5f87300496cbb39a7689d8207d85f
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/3027260
Cr-Commit-Position: refs/branch-heads/9.1@{#77}
Cr-Branched-From: 0e4ac64a8cf298b14034a22f9fe7b085d2cb238d-refs/heads/9.1.269@{#1}
Cr-Branched-From: f565e72d5ba88daae35a59d0f978643e2343e912-refs/heads/master@{#73847}
Notes: Security: backported fix for CVE-2021-30563.
> chore: cherry-pick 0e7f91956cec from v8

- shell/browser/api/electron_api_browser_window_views.cc
Closes https://github.com/electron/electron/issues/30287.
Fixes a potential crash that would occur if there was no `NativeView` - e.g. if a window had just been closed.
Notes: Fixes a potential crash that would occur with draggable regions on Windows.
> fix: guard against missing native view

- shell/browser/native_window_mac.mm
Closes https://github.com/electron/electron/issues/30277.
Fixes an issue where the aspect ratio would (incorrectly) take the height of the title bar into account when maximizing the window.
This fixes the issue by instead using a more specific `setContentAspectRatio` method such that macOS considers only the content view and not the whole NSWindow when calculating width.
Notes: Fixes an issue where a specified aspect ratio could become incorrect when maximizing a window on macOS.
> fix: use `contentAspectRatio` in `setAspectRatio()` on macOS

- docs/api/session.md
- shell/browser/serial/electron_serial_delegate.cc
- spec-main/chromium-spec.ts
- spec-main/index.js
Web Serial API [shipped as enabled by default in Chromium 89](https://www.chromestatus.com/feature/6577673212002304), so we should no longer mark this feature as experimental in Electron.
Notes: Web Serial API is no longer experimental.
> chore: remove experimental from navigator.serial implementation

- patches/chromium/.patches
- patches/chromium/replace_first_of_two_waitableevents_in_creditcardaccessmanager.patch
Replace first of two WaitableEvents in CreditCardAccessManager
(cherry picked from commit 48cf01e4039fecbe119d8223d1f6072aaf44f258)
Bug: 1214234
Change-Id: I38171be7b38982f25abfbb3dff7a41f19a167764
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3001123
Reviewed-by: Jared Saul <jsaul@google.com>
Commit-Queue: Dominic Battré <battre@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#898237}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3011066
Reviewed-by: Dominic Battré <battre@chromium.org>
Reviewed-by: Prudhvi Kumar Bommana <pbommana@google.com>
Owners-Override: Prudhvi Kumar Bommana <pbommana@google.com>
Cr-Commit-Position: refs/branch-heads/4515@{#1366} …
> chore: cherry-pick 24293de155 from chromium

- shell/browser/native_browser_view_views.cc
- shell/browser/native_browser_view_views.h
- shell/browser/ui/views/inspectable_web_contents_view_views.h
Closes https://github.com/electron/electron/issues/29859.
Fixes an issue where `BrowserView`s would appear not to load their `webContents`. Further investigation showed that it was in fact not that the `webContents` weren't being loaded, but that they weren't being _painted_ properly. If I tried to open `devTools` on the webContents or called `setBounds` _after_ the initial URL load it would work - this tracked back to `Layout` in `inspectable_web_contents_view_views.h` and to a hierarchy change in https://chromium-review.googlesource.com/c/chromium/src/+/2780032. Essentially, the change meant that `Layout` was no longer called by Chromium in some of the places it was before.
To fix this, I added an override for `RenderViewReady` and called into `Layout()` so that paints would happen …
> fix: BrowserViews not painting their WebContents

- patches/sqlite/.patches
- patches/sqlite/utf-8_q_when_20constructing_20the_20synthensized_20select_20sta.patch
When constructing the synthensized SELECT statement that is used to choose
the rows in an UPDATE FROM, make sure the first table is really the table
being updated, and not some common-table expression that happens to have the
same name.  [forum:/forumpost/a274248080|forum post a274248080].  More
changes associated with CTE name resolution are pending.
FossilOrigin-Name: 0f0959c6f95046e8e7887716e0a7de95da18d1e926ab1f919527083a56541db5
(cherry picked from commit 1168f810929ede4d8d323a6acf721ff9cd89de90)
Bug: 1218707
Change-Id: Idfec0bff8422f3ec34b142e5782f7104502d38f8
Notes: Security: backported fix for CVE-2021-30569.
> chore: cherry-pick 1168f81092 from sqlite

- shell/browser/ui/inspectable_web_contents.cc
- shell/browser/ui/inspectable_web_contents.h
The LogJsConsoleMessages feature is supposed to control whether `CONSOLE`
messages are printed to logs.
RFH::DidAddMessageToConsole respects this: https://source.chromium.org/chromium/chromium/src/+/main:content/browser/renderer_host/render_frame_host_impl.cc;l=3275;drc=e99bf3c8e0f35f1f82a12338cd1f9f064b5408c5
but InspectableWebContents::DidAddMessageToConsole didn't.
Notes: Fixed some console messages still being printed to logs when the LogJsConsoleMessages feature was disabled.
> fix: respect LogJsConsoleMessages feature in InspectableWebContents::DidAddMessageToConsole

- docs/tutorial/accessibility.md
- docs/tutorial/automated-testing-with-a-custom-driver.md
- docs/tutorial/dark-mode.md
- docs/tutorial/in-app-purchases.md
- docs/tutorial/keyboard-shortcuts.md
- docs/tutorial/launch-app-from-url-in-another-app.md
- docs/tutorial/macos-dock.md
- docs/tutorial/message-ports.md
- docs/tutorial/notifications.md
- docs/tutorial/online-offline-events.md
- docs/tutorial/process-model.md
- docs/tutorial/progress-bar.md
- docs/tutorial/quick-start.md
- docs/tutorial/recent-documents.md
- docs/tutorial/represented-file.md
- docs/tutorial/security.md
Updating the tutorial docs so that the code examples use the new Javascript arrow function syntax rather than the old `function () {...}` syntax to be in line with Electron coding style guide.
Notes:  none
> docs: Update to the use of arrow functions in line with the style guide

- lib/browser/api/menu-item-roles.ts
Fixes #28770.
`webContents.getOwnerBrowserWindow()` when called on a devtools webcontents
seems to return the BrowserWindow containing the webContents to which the
devtools is attached.
This probably doesn't work great for windows with BrowserViews in them, but
then, the previous implementation of this also didn't work correctly for that
case, so it's probably fine?
Notes: Fixed detached DevTools window not closing when a menu item with the toggleDevTools role was triggered.
> fix: toggleDevTools menu role closes devtools window

- docs/api/crash-reporter.md
- docs/breaking-changes.md
- patches/config.json
- patches/webrtc/.patches
- patches/webrtc/add_thread_local_to_x_error_trap_cc.patch
- shell/app/electron_main.cc
- spec-main/api-crash-reporter-spec.ts
This enables crashpad by default on Linux, matching Chrome.
Closes #27859.
Notes: The `crashReporter` API is now powered by Crashpad on Linux.
> feat: switch to crashpad on linux

- shell/common/crash_keys.cc
Regressed by #30161
```
ld.lld: error: undefined symbol: electron::api::DesktopCapturer::kWrapperInfo
>>> referenced by crash_keys.cc:189 (../../electron/shell/common/crash_keys.cc:189)
>>>               obj/electron/electron_lib/crash_keys.o:(electron::crash_keys::SetCrashKeyForGinWrappable(gin::WrapperInfo*))
```
Notes: none
> build: fix building with enable_desktop_capturer = false

- docs/breaking-changes.md
I got confused about which release this was landing in.
Notes: none
> docs: crashpad on linux lands in 16, not 15

- patches/sqlite/.patches
- patches/sqlite/sqlite_fix_an_undefined-integer-overflow_problem_in_fts3_c.patch
This backports
https://chromium.googlesource.com/chromium/deps/sqlite.git/+/774cfcb0903686282a85d2367a83b512d2e17603
from sqlite.
Notes: Security: backported fix for https://crbug.com/1204814.
> fix: backport 774cfcb from sqlite

- script/release/release-artifact-cleanup.js
Ensures that we rebase to the current upstream before trying to push a revert commit, handles a race condition between a release failing and a new commit landing on the upstream that would have prevented the revert being pushed.
Pairs up with https://github.com/electron/sudowoodo/pull/214
> build: rebase release branch before reverting bump

- shell/common/crash_keys.cc
Changed here: #30404  When trying to build on Windows, the tray_icon.h include within crash_keys.cc causes build errors. This PR fixes the build on master by gating the import to non-Windows OS'es.
(Marking as no backport because the backport PRs for the original PR have not been merged yet, so we can add the fix to them directly 🙂)
Notes: none
> fix: build SetCrashKeyGW without tray on Windows

- patches/chromium/.patches
- patches/chromium/cherry-pick-e2123a8e0943.patch
Manually post task to bind FileUtilitiesHost.
The FileUtilitiesHost binder is posted to a separate sequence, and the
ServiceWorkerHost may be destroyed by the time the it runs, causing a
UAF.
This CL changes it so that, when we try to bind a new receiver, the
host's worker_process_id() is obtained first (on the service worker's
core thread) and then a task is posted to do the actual binding on a
USER_VISIBLE task runner.
Credit: This issue was first reported (with analysis) by
soulchen8650@gmail.com.
Bug: 1229298
Change-Id: I6d5c05a830ba30f6cb98bf2df70a3df3333f3dd9
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3041006
Reviewed-by: Kinuko Yasuda <kinuko@chromium.org>
Reviewed-by: Kouhei Ueno <kouhei@chromium.org>
Commit-Queue: Tal Pressman <talp@google.com> …
> chore: cherry-pick e2123a8e0943 from chromium

- shell/browser/web_contents_preferences.cc
This was broken by the refactor in #30193.
Notes: Fixed imageAnimationPolicy not being respected.
> fix: respect image animation policy pref

- shell/browser/native_window_views.cc
Fixes #30402. This the issue that @electron/wg-releases marked as a stable blocker last week.
This bug is from the "CanResize has been de-virtualized" refactor in https://github.com/electron/electron/pull/29256
One-sentence summary: In order for [CanResize()](https://source.chromium.org/chromium/chromium/src/+/main:ui/views/widget/widget_delegate.cc;l=97?q=SetCanResize&ss=chromium%2Fchromium%2Fsrc) to return the right value [here](https://github.com/electron/electron/pull/29721/files#diff-5e25c7662c97f9f68ed2d91bac1c44f260b62c541617e4f115236cc7f4a73ab9R39), we need to call [SetCanResize()](https://source.chromium.org/chromium/chromium/src/+/main:ui/views/widget/widget_delegate.cc;l=321?q=SetCanResize&ss=chromium%2Fchromium%2Fsrc) first.
Notes: Fix beta-only bug that caused mouse clicks to …
> fix: mouse doesn't work on frameless browserwindows

- docs/api/menu.md
hideothers -> hideOthers (the TS compiler caught this)
The TypeScript compiler also did not like the pattern used to
switch between platforms for submenus was loosing the type information
of the literal constants and generalized them as strings which
conflicts with the type definition of MenuItemConstructorOptions.
This pull request is about
1) fixing an identifier in the menu template example documentation where the type definition demands camel-case but the example lacked said camel-case in "hideOthers".
2) when tying to use the template example in a TypeScript project the example did not compile as the type definition for MenuItemConstructorOptions used literal constants. The TS compile however can not interfere the correct type in the construct used in the example and generalized the …
> docs: fix camelcase in menu example

- docs/api/webview-tag.md
We are missing the documentation and generated types for these `<webview>` events:
https://github.com/electron/electron/blob/66c458a3530ed857955eb285700156b00bfc0271/lib/common/web-view-events.ts#L17
https://github.com/electron/electron/blob/66c458a3530ed857955eb285700156b00bfc0271/lib/common/web-view-events.ts#L19
Notes: none
> docs: add missing <webview> event documentation

- .circleci/config.yml
#30020 added tests that on macOS end up writing to the keychain.  Due to the setup of our macOS arm64 test machines, we need to clean up the keychain when running tests in order to make sure there isn't a OS UI asking for keychain access which ends up timing out the tests, eg: https://app.circleci.com/pipelines/github/electron/electron/43162/workflows/b60a0c49-aca0-476f-9cb6-48e2a0cf3493/jobs/966531.
Notes: none
> ci: cleanup keychain after tests on arm64 mac

- shell/common/crash_keys.cc
- shell/common/gin_converters/guid_converter.h
Workaround before this CL merges: https://chromium-review.googlesource.com/c/chromium/src/+/3076480
Currently if you `#include "base/guid.h"` before `#include "base/win/win_util.h"`, clang will throw an error. It turns out `REFGUID `is defined as `#define REFGUID const GUID&`. By the rules of C++ unqualified name lookup, this will first check `base::win::GUID`, then `base::GUID`, followed by `GUID` (aka `::GUID`) if none of the previous ones exist. Thus, our value's type was being set as `base::GUID`.
This PR undefines and redefines `REFGUID`, in case it was incorrectly defined with `base::GUID` in a previous file. We can remove this once the above CL lands/is backported.
Notes: none
> fix: explicitly define REFGUID from ::GUID&, not base::GUID

- script/release/ci-release-build.js
This broke in #30492, we weren't handled 20X status codes and weren't authing to appveyor correctly.
> build: fix release CI jobs start script

- shell/browser/feature_list.cc
- spec-main/api-desktop-capturer-spec.ts
Fixes #29458
When trying to screen capture an Electron application's own window, the screen will show as blank. This is because when `kWindowCaptureMacV2` is enabled, the latter portion of the DesktopMediaID is incorrectly replaced. For example: the DesktopMediaID is changed from `window:626:0` (correct) to `window:626:626` (incorrect). Passing the incorrect id into the desktop capture API results in the window not being found, and a blank or default-colored screen.
`kWindowCaptureMacV2` is already disabled by default in upstream Chromium (see here: https://chromium-review.googlesource.com/c/chromium/src/+/3069272). This PR also disables the feature by default until the upstream fix is in main. It also adds a new desktop capture test to keep the issue from happening again.
Notes: Fixed an …
> fix: disable kWindowCaptureMacV2 for desktop capturer

- .circleci/config.yml
This broke in https://github.com/electron/electron/pull/30492
Notes: none
> build: manually pull 64bit dugite for 32bit tests

- .circleci/config.yml
This depot_tools change broke CI because we were running an older verison of Git in our docker images:
https://chromium-review.googlesource.com/c/chromium/tools/depot_tools/+/3083251
This PR updates our docker image to a newer container that has a newer (2.32.0) version of git.
Notes: none
> ci: update git on CI machines

- shell/browser/ui/views/inspectable_web_contents_view_views.cc
Closes https://github.com/electron/electron/issues/29778.
Fixes an issue where background color would not be correctly applied to `BrowserViews` on Windows when either the `x` or `y` coordinate is negative (off-screen).
This was happening because `view::Views` was trying to paint the whole content bounds instead of the visible bounds, which caused issues because when part of the bounds are offscreen the compositor overrides and paints them white. This fixes that by painting the visible bounds.
Before:
After:
Tested with https://gist.github.com/712a2fde2757736c9dbf6c3e7e0aa18b.
Notes: Fixed an issue where background color would not be correctly applied to `BrowserViews` on Windows when either the `x` or `y` coordinate is negative (off-screen).
> fix: persist BrowserView background color when bounds offscreen

- docs/tutorial/in-app-purchases.md
- docs/tutorial/installation.md
- docs/tutorial/linux-desktop-actions.md
- docs/tutorial/macos-dock.md
- docs/tutorial/notifications.md
- docs/tutorial/progress-bar.md
- docs/tutorial/represented-file.md
- docs/tutorial/snapcraft.md
- docs/tutorial/using-native-node-modules.md
- docs/tutorial/using-pepper-flash-plugin.md
- docs/tutorial/using-selenium-and-webdriver.md
- docs/tutorial/web-embeds.md
- docs/tutorial/windows-arm.md
- docs/tutorial/windows-taskbar.md
Tidies up the doc names within the `/tutorial/` folder.
* Title case enforced for titles (as per style guide)
* Made some titles more concise (e.g. `Using Native Node Modules` becomes `Native Node Modules`)
* Made platform-specific titles consistent
Notes: none
> docs: uniformize tutorial titles

- docs/api/browser-window.md
The initial implementation of `acceptFirstMouse` was macOS-only (see #215), but the docs never specified this. Current code search for the `kAcceptFirstMouse` switch shows it only being used on macOS as well.
To verify, open https://gist.github.com/erickzhao/4b08e1978146265170938cdc45fe3394 on Windows and click the inactive fiddle window. The click-through will always work.
Notes: none
> docs: clarify platform-specific usage of the `acceptFirstMouse` option

- shell/browser/api/electron_api_browser_window_views.cc
Follow up to https://github.com/electron/electron/pull/30304 the issue was not that the NativeView was missing (it's stack allocated anyway, so truthy checking it didn't do anything).  The crash shows a failure in the pointer indirection of the `unique_ptr` for the `view`.  i.e. the `view` was nullptr.
Notes: Fixed rare crash in UpdateDraggableRegions
> fix: handle nullish WebContentsView in UpdateDraggableRegions

- shell/browser/api/electron_api_web_contents.cc
- spec-main/webview-spec.ts
- spec/fixtures/pages/a.html
Closes https://github.com/electron/electron/issues/30509.
Fixes an issue present in `webView` where the `leave-html-full-screen` event is not emitted if the user exits fullscreen with `esc` instead of by clicking into the webView.
This was happening because when the user exits by clicking into the webview, we call into `ExitFullScreenModeFromTab` on the webcontents of the webview - meaning the event is emitted correctly to the webview. When we do so from esc, however, this happens from the wrong `webContents` and so then go and loop through each child webview to ensure they all exit properly with `api_web_contents->SetHtmlApiFullscreen(false);`. Since the emit happens in `ExitFullScreenModeFromTab` though, `leave-html-full-screen` is not emitted again.
This fixes the issue by centralizing …
> fix: {exit|enter}-html-fullscreen emitted after esc in webview

- patches/chromium/.patches
- patches/chromium/fix_media_key_usage_with_globalshortcuts.patch
- spec-main/api-global-shortcut-spec.ts
Closes https://github.com/electron/electron/issues/30543.
Refs https://github.com/electron/electron/pull/27475.
[This CL](https://chromium-review.googlesource.com/c/chromium/src/+/2606785/1) moved around the location for media key listener logic in Chromium, and as a result [this patch](https://github.com/electron/electron/pull/27475/files#diff-715074556fc5163e2e7faeaba16111a69fa68add0ff58cd934188c38f8167ea7) was fully removed instead of being updated (regressing https://github.com/electron/electron/pull/21959).
This fixes the issue by reinvigorating the patch in accordance with latest upstream logic.
Notes: Fixed media key `globalShortcut`s on macOS.
> fix: media key globalShortcuts on macOS

- shell/browser/api/electron_api_browser_window_views.cc
Notes: Fixed potential crash when programatically closing a draggable frameless child window
> fix: ensure web_contents() is alive before grabbing view

- shell/browser/electron_browser_client.cc
- spec-main/api-web-contents-spec.ts
Closes https://github.com/electron/electron/issues/30514.
Fixed an issue where loading a url, calling `forcefullyCrashRenderer()`, then reloading the page would cause an Observer DCHECK. This is happening because we previously added an observer in  [`RenderProcessWillLaunch`](https://github.com/electron/electron/commit/d9321f4df751fa32813fab1b6387bbd61bd681d0) and then ensured its removal in [`RenderProcessHostDestroyed`](https://github.com/electron/electron/commit/d9321f4df751fa32813fab1b6387bbd61bd681d0). However, the codepath taken in `forcefullyCrashRenderer()` is a bit of a misonomer, in that it results in a clean exit and so [`RenderProcessExited`](https://github.com/electron/electron/commit/d9321f4df751fa32813fab1b6387bbd61bd681d0) is called instead of …
> fix: DCHECK on reload when forcefullyCrashRenderer() is called

- shell/browser/api/electron_api_web_contents.cc
- shell/browser/api/electron_api_web_contents.h
- shell/browser/api/electron_api_web_frame_main.cc
- shell/browser/api/electron_api_web_frame_main.h
- spec-main/api-web-frame-main-spec.ts
Recommended reading to better understand RenderFrameHosts and swapping of them during cross-origin navigation:
https://www.chromium.org/developers/design-documents/oop-iframes
This PR is to address one of the issues brought up in https://github.com/electron/electron/pull/29290#issuecomment-876875670.
`WebFrameMain` (WFM) currently abstracts `content::RenderFrameHost` and aligns closely with its lifespan. Under the OOPIF architecture and Site Isolation, cross-origin navigation leads to a RFH getting swapped for a new RFH in a separate process. WFM doesn't handle this case which will lead to cached references being marked as disposed if held through cross-origin navigation.
To address this, I've modified lookup of a WFM instance to use a `FrameTreeNode` (FTN) ID. This is a globally unique …
> fix: cross-origin navigation disposing WebFrameMain instances

- appveyor.yml
From CI:
```
if "%RUN_GCLIENT_SYNC%"=="true" ( gclient sync --with_branch_heads --with_tags --ignore_locks)
Warning: ignore_locks is no longer used. Please remove its usage.
```
Notes: none.
> build: remove redundant --ignore_locks from appveyor

- shell/browser/native_window_mac.mm
Closes https://github.com/electron/electron/issues/30564.
Fixes an issue where toggling `documentEdited` status on macOS with `titlebarStyle: 'hiddenInset'` inadvertently moves the traffic light location. Fix this by ensuring the traffic lights are redrawn according to the current `titleBarStyle` when `documentEdited` status is changed.
Tested with https://gist.github.com/166ffcd98c950e6e97fec05ae4f2683b.
Notes: Fixed an issue where toggling `documentEdited` status on macOS with `titlebarStyle: 'hiddenInset'` inadvertently moves the traffic light location.
> fix: documentEdited with non-default titlebarStyle

- patches/chromium/add_gin_wrappable_crash_key.patch
- shell/common/crash_keys.cc
- shell/common/crash_keys.h
Changes the added crash key to gin::Wrappable from a set crash key to a scoped crash key. The current crash key will be added to any crash that occurs after SecondWeakCallback runs once. This scoped crash key will keep the crash key from appearing if the crash does not occur in SecondWeakCallback, even if the code path was used prior to the crash.
Notes: none
> fix: change gin::Wrappable crash key type to ScopedCrashKey

- patches/chromium/.patches
- patches/chromium/cherry-pick-1227933.patch
Merge 4577: Fix nested inline box fragmentation
This patch fixes when nested inline boxes are fragmented in a
line due to bidi reordering.
Before this change, the fragmented boxes are appended to the
end of |box_data_list_|. Then when |NGInlineLayoutStateStack::
CreateBoxFragments| creates inline boxes in the ascending
order of |box_data_list_|, it failed to add the fragmented
boxes into their parent inline boxes.
This is critical for out-of-flow positioned objects whose
containing block is an inline box, because they expect to be
propagated through all ancestor inline boxes.
|UpdateBoxDataFragmentRange| is a little tricky by appending
to a vector it is iterating. Changing it to insert to the
correct position makes the function even trickier. This patch
changes it to add fragmented boxes …
> chore: cherry-pick fix for 1227933 from chromium

- patches/v8/.patches
- patches/v8/cherry-pick-1231950.patch
[liftoff][arm64] Zero-extend offsets also for SIMD
This extends https://crrev.com/c/2917612 also for SIMD, which
(sometimes) uses the special {GetMemOpWithImmOffsetZero} method.
As part of this CL, that method is renamed to {GetEffectiveAddress}
which IMO is a better name. Also, it just returns a register to make the
semantic of that function obvious in the signature.
Drive-by: When sign extending to 32 bit, only write to the W portion of
the register. This is a bit cleaner, and I first thought that
this would be the bug.
R=jkummerow@chromium.org
CC=​thibaudm@chromium.org
Bug: chromium:1231950, v8:12018
Change-Id: Ifaefe1f18e3a00534a30c99e3c37ed09d9508f6e
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/3049073
Reviewed-by: Zhi An Ng <zhin@chromium.org>
Commit-Queue: …
> chore: cherry-pick fix for 1231950 from v8

- patches/angle/.patches
- patches/angle/cherry-pick-1fb846c.patch
- patches/angle/cherry-pick-d8cb996.patch
- patches/config.json
2 fixes picked:
https://chromium.googlesource.com/angle/angle.git/+/d8cb996768a3d1536efe6d4edb1f92b0e6e86240
https://chromium.googlesource.com/angle/angle.git/+/1fb846cbed194e990c76bd475987665c37009c1a
Notes: Security: Backported fix for 1234829.
> chore: cherry-pick fix for 1234829 from angle

- docs/tutorial/launch-app-from-url-in-another-app.md
Code snippet for the info.plist example had html formatting. Removed.
Notes: none
> docs:  typo in launch-app-from-url-in-another-app.md

- shell/browser/api/electron_api_web_frame_main.cc
Follow up to #30076 which introduced a bug failing a test. See https://github.com/electron/electron/pull/30076#issuecomment-901583229
I propose we merge the previous backport PRs from #30076, then merge this and backport it to each target version.
Unfortunately I wasn't able to find a way to test this with a consistent failure case. I tried triggering cross-origin navigation and calling `webContents.executeJavaScript()` before and after, but the mojo pipe never disconnected.
cc @zcbenz @nornagon 
Notes: none
> fix: WebFrameMain mojo pipe not reset

- .gitignore
- docs/tutorial/installation.md
- npm/install.js
- npm/package.json
- script/release/publish-to-npm.js
In theory this isn't user facing.
Currently we download `SHASUMS256.txt` and the target Electron binary from GH releases and then use one to validate the other.  In terms of "did the download get the right thing" it's a valid check, from a security perspective it's a little bit too close to self-validation than I'd like.  The only thing protecting the `SHASUMS256.txt` file is GH write access and SSL during the download.
This change embeds the `SHASUMS256.txt` content in our `electron` npm package at publish time.  This means the checksums are now (a) stored separately to the actual Electron binary and (b) protected by the integrity SHA in your `yarn.lock` / `package-lock.json` lockfile.
Tested locally, and we can test this on tomorrows nightly.
> build: embed binary checksums in the npm package

- shell/browser/electron_browser_client.cc
- spec-main/api-web-contents-spec.ts
Reverts electron/electron#30544
Test failures caused by original PR https://electronhq.slack.com/archives/C6JSJ9FS5/p1629325475019900
Notes: none
> fix: Revert "fix: DCHECK on reload when forcefullyCrashRenderer() is called"

- README.md
The linked repo has examples that haven't been updated in years.
Notes: none
> docs: remove link to outdated examples from README

- docs/api/touch-bar-scrubber.md
- shell/browser/ui/cocoa/electron_touch_bar.mm
Closes https://github.com/electron/electron/issues/30658.
Fixes an issue where the TouchBarScrubber crashes if `items` is an empty array.
Notes: Fixed an issue where the TouchBarScrubber crashes when `showArrowButtons` is enabled if `items` is an empty array.
> fix: crash when using TouchBarScrubber arrow button

- docs/api/session.md
> docs: explain the null webContents case in permission checks

- docs/api/webview-tag.md
- lib/browser/guest-view-manager.ts
- lib/common/web-view-methods.ts
- spec/webview-spec.js
This allows replying to an IPC sent by a frame (when `nodeIntegrationInSubFrames` is enabled) inside of the `<webview>`:
```js
webview.addEventListener('ipc-message', event => {
webview.sendToFrame(event.frameId, event.channel, ...event.args);
});
```
Fixes #30207.
Notes: Added `<webview>.sendToFrame()` / `frameId` to `'ipc-message'` event.
> feat: add <webview>.sendToFrame() / frameId to 'ipc-message' event

- lib/browser/rpc-server.ts
- lib/renderer/api/native-image.ts
- shell/common/api/electron_api_native_image_win.cc
Backport of #30728.
Notes: none
> fix: remove ipc wrapper for nativeImage.createThumbnailFromPath

- patches/chromium/.patches
- patches/chromium/cherry-pick-1234009.patch
Defer looking up the WebContents for the directory confirmation dialog.
Look up the WebContents to use for the sensitive directory confirmation
dialog immediately before it's used instead of before performing some
blocking file access to determine whether it's necessary.
Bug: 1234009
Change-Id: I5e00c7fa199b3da522e1fdb73242891d7f5f7423
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3063743
Reviewed-by: Alex Danilo <adanilo@chromium.org>
Reviewed-by: Ben Wells <benwells@chromium.org>
Commit-Queue: Sam McNally <sammc@chromium.org>
[modify] https://crrev.com/18236a0db8341302120c60781ae3129e94fbaf1c/extensions/browser/api/file_system/file_system_api.cc
[modify] https://crrev.com/18236a0db8341302120c60781ae3129e94fbaf1c/extensions/browser/api/file_system/file_system_api. …
> chore: cherry-pick fix for 1234009 from chromium

- docs/breaking-changes.md
Adds the remote module removal to Breaking Changes in E14
Notes: none
> docs: add remote removal to E14 breaking changes

- docs/tutorial/code-signing.md
This PR improves the macOS code signing documentation to take into account the changes made to how memory allocation is done in Electron 12. With the changes, Electron applications no longer need the unsafe memory entitlement. 
Notes: none
> docs: improve documentation about macOS entitlement usage security

- shell/common/platform_util_linux.cc
Refs https://chromium-review.googlesource.com/c/chromium/src/+/3009959.
Adds OpenURI portal support for `shell.showItemInFolder()`.
> The OpenURI portal is a more universal standard for being able to open
various items on the host, including directories. More critically, it
has special handling for containerized runtimes that will remap special
paths to point to the proper host locations.
> Use the OpenURI portal as a fallback for
if the FileManager1 API is not available. When running in a
containerized runtime, D-Bus access is generally sandboxed, so Chromium
will notice that FileManager1 is not accessible and use the portal.
Notes: none
> fix(linux): OpenURI portal support for `shell.showItemInFolder()`

- docs/tutorial/process-model.md
the demo have two error: 
- at macos, close all window, the app will not quite, unless press `cmd` + `q`
- attach preload.js, use preload prop that is member of `webPreferences` property of `BrowserWindow` controller argument
Notes: none
> docs: fix code example in process-model.md

- azure-pipelines-woa.yml
Recently in 1de8f746b5c304d45002731283552ef2bf6ba0f9 I added a step to our WOA tests to download the PDB files so that we get better stack traces on WOA testing.  Unfortunately sometimes this step fails (possibly because of how large the file is) and ends up marking the whole test run as a failure, eg:
https://github.visualstudio.com/electron/_build/results?buildId=115579&view=logs&j=6b902995-b73d-5f5c-66fd-a7f66c857d2c&t=de3312e4-438d-59aa-78f3-46bf3faba2ab&s=b15d9194-8f26-5328-b47f-5968c76b37e7
Since these pdb files are not needed for testing (but are useful if there), I've changed the WOA job to ignore failures downloading the pdb files.  I did some testing here to verify that a download error doesn't mark the job as failed:
https://github.visualstudio.com/electron/_build/results?buildI …
> ci: ignore pdb download failure on WOA

- docs/api/web-contents.md
- docs/api/web-frame-main.md
- shell/browser/api/electron_api_web_contents.cc
- shell/browser/api/electron_api_web_frame_main.cc
- shell/browser/api/electron_api_web_frame_main.h
- shell/common/gin_converters/frame_converter.cc
- shell/common/gin_converters/frame_converter.h
- shell/common/gin_helper/accessor.h
- shell/common/gin_helper/dictionary.h
- spec-main/api-web-frame-main-spec.ts
- spec-main/fixtures/sub-frames/frame-container.html
- spec-main/fixtures/sub-frames/frame-with-frame.html
resolves #27344
~~WebContents now emits a 'frame-dom-ready' event when either the top-level frame or a sub frame's document is ready.~~
WebFrameMain now emits a 'dom-ready' event when the frame's document is ready.
Notes:
* Added 'dom-ready' event to `WebFrameMain` which emits when the frame's document is ready.
* Added 'frame-created' event to `WebContents` which emits when a frame is created in the page.
> feat: add 'dom-ready' event to WebFrameMain

- shell/browser/extensions/electron_extension_loader.cc
Remove meaningless warnings when loadExtension extension
Fixes:
https://github.com/electron/electron/issues/23662
https://github.com/MarshallOfSound/electron-devtools-installer/pull/177
https://github.com/MarshallOfSound/electron-devtools-installer/issues/182
----
`"Unrecognized manifest key '*'."` and `Cannot load extension with file or directory name _metadata.` warnings is there is no point. And they are very annoying...
This change should not be fixed on `chromium`, but downstream of it: `electron`. see: https://bugs.chromium.org/p/chromium/issues/detail?id=377278
Notes: none
> fix: remove extension warning that do not have any impact

- shell/browser/api/electron_api_browser_window.cc
- shell/browser/api/electron_api_web_contents.cc
fixes #30759
The renderer in Blink now sets its own background color which is determined from the logic in [`WebViewImpl::BaseBackgroundColor()`](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/exported/web_view_impl.cc;l=3049-3058;drc=98898daa2e8f46ff098cea1f2e218f8a8266c838).
To set this background color for the main frame, we must use `WebContents::SetPageBaseBackgroundColor(SkColor)`.
In #30136, we had reverted using this API because it ended up breaking BrowserWindow transparency. To get this to work, we can see from `WebViewImpl::BaseBackgroundColor()` that there's a property to enable transparency, `override_base_background_color_to_transparent_`.
To override the base background color to be transparent, we must call …
> fix: BrowserWindow backgroundColor

- docs/breaking-changes.md
- lib/renderer/api/desktop-capturer.ts
Deprecates desktopCapturer.getSources in the renderer. See #30720 for more
details.
Notes: Usage of the `desktopCapturer.getSources` API from the renderer process has been deprecated and will be removed.
> feat: deprecate desktopCapturer.getSources in the renderer

- shell/browser/api/electron_api_web_contents.cc
fixes #30807
Backport a fix from #29290 which has already made it into `main` and `15-x-y` branches.
The check below will get thrown sometimes when the `old_host` is a nullptr which I hadn't expected initially. The code works fine with this check removed.
https://github.com/electron/electron/blob/c0da647170fa03b79de33e67f42e3acf5ce36ca2/shell/browser/api/electron_api_web_contents.cc#L1426-L1429
Notes: Fixed crash that occasionally happens when closing or opening BrowserWindows.
> fix: remove CHECK_EQ for swapped RFH

- patches/v8/.patches
- patches/v8/cherry-pick-fbfd2557c2ab.patch
Return early when initializing feedback cell for AsmWasm functions
AsmWasmFunctions don't allocate / use feedback vectors.
Bug: chromium:1206289
Change-Id: I970d5eaba6603809a844c2fc5753efba411cd719
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/2909854
Commit-Queue: Mythri Alle <mythria@chromium.org>
Reviewed-by: Ross McIlroy <rmcilroy@chromium.org>
Cr-Commit-Position: refs/heads/master@{#74708}
Notes: Backported fix for chromium:1206289.
> chore: cherry-pick fbfd2557c2ab from v8

- patches/chromium/.patches
- patches/chromium/cherry-pick-d727013bb543.patch
[macOS Capture] Fix UAF in VideoCaptureDeviceAVFoundation's dealloc.
Despite dealloc performing stopCapture prior to clearing variables like
_sampleBufferTransformer, it appears possible for callbacks that are
already running concurrently to be using these variables, resulting in
rare use-after-free races. By grabbing the _lock, we avoid this issue.
We also have to introduce a new lock, _destructionLock, to ensure |this|
is not destroyed while -captureOutput is still running.
Bug: chromium:1227228
Change-Id: I8c2c4d9834ee995d3f4154fae13e262398e6f2e2
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3013796
Reviewed-by: Evan Shrubsole <eshr@google.com>
Reviewed-by: Ilya Nikolaevskiy <ilnik@chromium.org>
Commit-Queue: Henrik Boström <hbos@chromium.org> …
> chore: cherry-pick d727013bb543 from chromium

- patches/chromium/.patches
- patches/chromium/merge_m92_speculative_fix_for_crash_in.patch
[Merge M92] Speculative fix for crash in URLLoader::OnBeforeSendHeadersComplete
I wasn't able to reproduce the crash, but this should prevent crashing
when accessing an invalid pointer for the HttpRequestHeaders. Instead of
passing a raw pointer, OnBeforeStartTransaction will now take optional
headers in the callback to modify the extra headers. If the job has been
destroyed, the callback will not be run since it was bound with a
WeakPtr to the job.
(cherry picked from commit c06b3928469bfd0e0a9fa6045b95a7be70ef393f)
Bug: 1221047
Change-Id: I93d5838b778e7283f7043fd2c841844941f52a85
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3042975
Commit-Queue: Clark DuVall <cduvall@chromium.org>
Reviewed-by: Matt Mueller <mattm@chromium.org> …
> chore: cherry-pick d1eade9d39 from chromium

- shell/browser/ui/views/inspectable_web_contents_view_views.cc
Closes https://github.com/electron/electron/issues/30803.
Refs https://chromium-review.googlesource.com/c/chromium/src/+/2228988.
Fixes an issue where undocked devtools was not resizable on Windows. This was because Chromium de-virtualized `CanResize`, and the default is false. In the above CL, Chromium introduced a convenience method to handle all three of `CanMaximize`, `CanMinimize`, and `CanResize`, so remove our other two overrides here as well.
Notes: Fixed an issue where undocked devtools was not resizable on Windows.
> fix: undocked devtools not resizable on Windows

- docs/api/webview-tag.md
This PR is a documentation update in response to https://github.com/electron/electron/issues/30656 opened by @Oliver-Fish. It changes the webview tag preload documentation to more accurately reflect the current behavior when referencing asar archives to get the script. 
Notes: docs: updated webview tag documentation to accurately reflect preload behavior with asar archives
> docs: updated webview tag docs to reflect preload behavior with .asar

- shell/browser/api/electron_api_web_request.cc
Refactors the `webRequest` module to use a getter for lazily serializing WebFrameMain instances.
Notes: none
> refactor: use getter for frame in webrequest details

- shell/browser/native_window_views.cc
- spec-main/api-browser-window-spec.ts
fixes #30798
Transparent frameless windows do not support being maximized.
We approximate the maximized state by checking if the window takes up the nearest screen's bounds: https://github.com/electron/electron/blob/49e62f1261d289500e5e85973fb4962fea3f7cab/shell/browser/native_window_views.cc#L597-L610
If that's the case, `browserWindow.show()` attempts to restore the window to a maximized state which will break its transparency and bounds. See https://github.com/electron/electron/issues/30798#issuecomment-910834940 for more details.
Notes: Fixed transparent frameless windows having an opaque background when opened in a maximized state.
> fix: show maximized frameless window

- docs/tutorial/process-model.md
The docs for the process model mention that `preload` should be a property of `webPreferences`, but the code example showed something else.
notes: none
> docs: fix wrong code example for preload property

- docs/tutorial/launch-app-from-url-in-another-app.md
Does two things in the protocol guide:
* Clean up grammar/formatting
* Replace the packaging section, which references `--extend-info` (and looks like it came from `electron-api-demos`) with a more modern set of instructions, as Electron Packager / Electron Forge has a specific parameter or two for macOS protocol support, and Linux support was not addressed.
Notes: none
> docs(protocols): simplify packaging section & cleanup 

- shell/browser/api/gpuinfo_manager.cc
Refs CL:1208362
CL:1087582 made it such that the GL context is created early on macOS, and as such it won't be the case that this will ever be true by the time it's called.
Notes: none
> refactor: remove dead code in NeedsCompleteGpuInfoCollection

- shell/browser/api/electron_api_web_contents.cc
- spec-main/fixtures/crash-cases/api-web-frame-main-connect/index.html
- spec-main/fixtures/crash-cases/api-web-frame-main-connect/index.js
Regressed with https://github.com/electron/electron/pull/30598
Refs https://github.com/microsoft/vscode/issues/132238
This is only needed for 13-x-y branch were process reuse can be disabled.
<details>
<summary>
Stack Trace
</summary>
```
:FATAL:render_frame_host_impl.cc(1921)] Check failed: IsRenderFrameCreated().
Backtrace:
base::debug::CollectStackTrace [0x00007FF725426128+32] (o:\base\debug\stack_trace_win.cc:303)
base::debug::StackTrace::StackTrace [0x00007FF7253919A4+24] (o:\base\debug\stack_trace.cc:195)
logging::LogMessage::~LogMessage [0x00007FF7253A5874+184] (o:\base\logging.cc:566)
logging::LogMessage::~LogMessage [0x00007FF7253A66B8+24] (o:\base\logging.cc:559)
content::RenderFrameHostImpl::GetRemoteInterfaces [0x00007FF72498D7EC+92] …
```
> fix: crash when navigating with render process reuse disabled

- docs/tutorial/launch-app-from-url-in-another-app.md
Backport of #30832
Notes: none
> docs(protocols): simplify packaging section & cleanup

- patches/chromium/.patches
- patches/chromium/pa_make_getusablesize_handle_nullptr_gracefully.patch
Refs https://bugs.chromium.org/p/chromium/issues/detail?id=1221442
Backports https://chromium-review.googlesource.com/c/chromium/src/+/3060345
Fix is already available in chromium > 92
Notes: fix crash when launching app with systemd v249
> fix: crash when launching app with systemd v249

- shell/browser/net/asar/asar_file_validator.cc
- shell/browser/net/asar/asar_file_validator.h
- shell/browser/net/asar/asar_url_loader.cc
- shell/common/asar/archive.cc
- shell/common/asar/archive.h
The 15-x-y backport of #30667 had some compile failures and a potential use-after-move, this just takes the commit in that backport and lands it to `main` as well 👍 
> chore: upstream changes from 15-x-y ASAR validation PR

- shell/browser/file_select_helper.cc
Fixes #30858 
There seems to be a race condition with two functions, `OnFilesSelected` and `OnOpenDialogDone`, when opening or attaching a file from the file dialog. On Windows and Linux, the execution goes something like this:
1. Open dialog is triggered, user selects a file and clicks "Ok"
2. `OnFilesSelected` runs. `render_frame_host_` is set to `nullptr` and `this` is deleted
3. `OnOpenDialogDone` runs. `render_frame_host_` still exists when the function begins, and the `nullptr` checks don't trigger. However, the `render_frame_host_` and `this` are then deleted in `OnFilesSelected`. When we then try to access `render_frame_host_->GetProcess()` at the end of the function, the program hard crashes.
It seems as though the` render_frame_host_` deletion in `OnFilesSelected` was being done …
> fix: only delete render_frame_host_ after OnDialogDone completes

- shell/browser/file_select_helper.cc
Follow up to #30916, which fixed the file picker crash for Windows and Linux, but regressed and caused the crash to start occurring on Mac.
`RunFileChooserEnd` does not need to run on Mac after selecting files and opening the dialog, because 1) on Mac only, we bind the `ProcessSelectedFilesMac` function to run and block the thread, and 2) `RunFileChooserEnd` is already run in `ProcessSelectedFilesMac` within `file_select_helper_mac.mm` at the appropriate time.
This PR gates the function to only run on non-Mac OSes.
Notes: Notes: Fixed a crash when selecting and opening files in a native file dialog on Mac.
> fix: remove conflicting RunFileChooserEnd for Mac

- chromium_src/BUILD.gn
If the [`enable_pdf_viewer`](https://github.com/deermichel/electron/blob/06b3b49214d086e8aa747b354509f479036bf261/buildflags/buildflags.gni#L15) build flag is set to false, linking will fail:
```
ld64.lld: error: undefined symbol: PepperFlashFontFileHost::PepperFlashFontFileHost(content::RendererPpapiHost*, int, int, ppapi::proxy::SerializedFontDescription const&, PP_PrivateFontCharset)
>>> referenced by obj/electron/chromium_src/plugins/chrome_renderer_pepper_host_factory.o
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
Traceback (most recent call last):
File "../../build/toolchain/apple/linker_driver.py", line 305, in <module>
Main(sys.argv)
File "../../build/toolchain/apple/linker_driver.py", line 98, in Main …
```
> fix: PepperFlashFontFileHost not included when disabling pdf viewer

- shell/common/platform_util_mac.mm
I added some methods from https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/platform_util_mac.mm so that Electron builds when building with `is_debug = true` on macOS.
Notes: none
> fix: Building on macOS with is_debug true

- docs/api/browser-window.md
Reverts some of the changes in #19196 where two headings were moved up a level by accident.
Notes: none
> chore: correct hierarchy of BrowserWindow headings

- docs/tutorial/context-isolation.md
Updates the Context Isolation tutorial.
Changes:
* Removes language around context isolation being enabled in the future
* Adds a bit more detail to the Migration section
* Adds a section about augmenting the global `window` object with TypeScript
I usually don't add release notes, but I figure the TypeScript stuff is worth pointing out.
cc @MarshallOfSound @malept
Notes: adds documentation on using TypeScript with the `contextBridge` API
> docs: update context isolation doc

- patches/v8/.patches
- patches/v8/cherry-pick-034c2003be31.patch
Merged: [compiler] Fix a bug in global property access reduction
Bug: chromium:1247763
(cherry picked from commit 6391d7a58d0c58cd5d096d22453b954b3ecc6fec)
Change-Id: Ifa775224ed30a2d680c6e3653063483c733de831
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/3151960
Commit-Queue: Nico Hartmann <nicohartmann@chromium.org>
Reviewed-by: Michael Hablich <hablich@chromium.org>
Cr-Commit-Position: refs/branch-heads/9.3@{#37}
Cr-Branched-From: 7744dce208a555494e4a33e24fadc71ea20b3895-refs/heads/9.3.345@{#1}
Cr-Branched-From: 4b6b4cabf3b6a20cdfda72b369df49f3311c4344-refs/heads/master@{#75728}
Notes: Backported fix for CVE-2021-30632.
> chore: cherry-pick 034c2003be31 from v8

- docs/tutorial/fuses.md
Adds a link to the fuses documentation where we suggest people read the README without actually linking it. I assume @MarshallOfSound would be a good person to ping for this since I see his name as the last committer for fuses :)
Notes: none
> docs: add link to @electron/fuses

- build/args/all.gn
Updates Electron 16 to use the correct NMV number.
Ref (do not merge until this PR has merged): https://github.com/nodejs/node/pull/39950
Notes: none
> chore: update E16 node module version

- build/args/all.gn
Updates Electron 14 to use the correct NMV number.
Ref (do not merge until this PR has merged): https://github.com/nodejs/node/pull/39950
Notes: none
> chore: update E14 node module version

- build/args/all.gn
Updates Electron 15 to use the correct NMV number.
Ref (do not merge until this PR has merged): https://github.com/nodejs/node/pull/39950
Notes: none
> chore: update E15 node module version

- shell/browser/ui/views/win_frame_view.cc
Closes #30828
Previously, an extra 1 pixel edge existed between the border of the screen and the WCO when maximized. Though this pixel is needed for manual resizing, as explained in the code, it is not needed in the maximized state.
This PR adds a check that only adds the pixel edge when the window is not maximized.
Notes:  None
> fix: add casing for WCO edge

- patches/chromium/.patches
- patches/chromium/cherry-pick-8623d711677d.patch
[layout] Remove limit from LayoutInline::SplitInlines.
After 200 elements the code "gave up" causing the layout tree to be
"strange".
This caused a To<LayoutInline> to fail in the OOF code. Relaxing this
To<> to a DynamicTo<> caused additional CHECKs / DCHECKs all over the
place (not just in NG but in Legacy as well).
This patch removes the limit at which we "give up". This may cause
additional render hangs.
However we currently have a project "block-in-inline" which will (for
most cases) stop inline-splitting for occuring (except in legacy
fallback).
(cherry picked from commit bbd315efb49a4ae257509dd0f0d85c6b5906e0e4)
(cherry picked from commit d760d2ae1d51c0b4fda87a0a3af4e7ed30d2ff4c)
Bug: 1245786
Change-Id: I5f1c4d6a4b81a8345974de40c0c50a27a839b7b4
Reviewed-on: …
> chore: cherry-pick 8623d711677d from chromium

- patches/chromium/.patches
- patches/chromium/content-visibility_force_range_base_extent_when_computing_visual.patch
content-visibility: Force range base/extent when computing visual selection.
Some of the code that does visual selection ends up updating style and
layout for node. This means that it will temporarily unlock c-v nodes
and may cause a state rewind from layout clean to visual update pending.
That's not an operation we support, verified by DCHECKs. So, instead
we should unlock any c-v nodes prior to getting to layout clean.
R=​chrishtr@chromium.org, yosin@chromium.org
(cherry picked from commit 484bc1abffcdee33648695244c86daca15ab6539)
Bug: 1237533
Change-Id: Ib30036c4536bea3da2ae4fa54c19ad5684829597
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3114230
Commit-Queue: Yoshifumi Inoue <yosin@chromium.org>
Reviewed-by: Chris Harrelson <chrishtr@chromium.org> …
> chore: cherry pick 9723e3c13c from chromium

- docs/tutorial/performance.md
- docs/tutorial/progress-bar.md
Images that used the inline link format do not show up on Docusaurus or
the old website infrastructure. There are only 2 guides using it so it
is faster to change the format rather than figuring out why the parsin
logic does not work.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Ref: https://github.com/electron/electronjs.org-new/issues/84
Fixes #30996
CC @erickzhao  @ckerr 
Notes: none
> fix: links to images

- typings/internal-electron.d.ts
Chrome now use developer.chrome.com/docs/extensions/* instead of developer.chrome.com/extensions/* to host their documentation of chrome extensions.
The old links may deprecate in the future.
Notes: none
> chore: update links of documentation of chromes in comments

- shell/browser/native_window_mac.h
- shell/browser/native_window_mac.mm
- spec-main/api-browser-window-spec.ts
Refs CL:2485774
Refs https://github.com/electron/electron/pull/29256/commits/a5628cac3e1290a08f3ef75a5fc6356e5a0720a6
Fixes an issue wherein when `mainWindow.setResizable(false)` is called and immediately followed by `mainWindow.setResizable(true)` on macOS, the zoom button remains disabled.
When `SetCanResize` was de-virtualized we started calling it in `SetResizable` - this eventually alters the titlebar controls on macOS when it falls down to [`SetSizeConstraints`](https://source.chromium.org/chromium/chromium/src/+/main:components/remote_cocoa/app_shim/native_widget_ns_window_bridge.mm;l=1037-1054?q=SetSizeConstraints%20nswindow&ss=chromium%2Fchromium%2Fsrc). Fullscreen controls are enabled depending on whether both maximizable and resizable are true. Since we didn't override …
> fix: disabling and enabling resizability on macOS

- shell/browser/api/electron_api_web_contents.cc
- shell/browser/api/electron_api_web_contents.h
- shell/browser/ui/inspectable_web_contents.cc
- shell/browser/ui/inspectable_web_contents.h
Refactor to make `InitWithWebContents` and `InspectableWebContents` take a `unique_ptr`.
cc @zcbenz 
Notes: none
> refactor: make `InitWithWebContents` and `InspectableWebContents` take a `unique_ptr`

- patches/chromium/.patches
- patches/chromium/m93_indexeddb_add_browser-side_checks_for_committing_transactions.patch
- patches/chromium/m93_indexeddb_don_t_reportbadmessage_for_commit_calls.patch
M93: [IndexedDB] Add browser-side checks for committing transactions.
No new IPCs should come in for a transaction after it starts committing.
This CL adds browser-side checks in addition to the existing
renderer-side checks for this.
(cherry picked from commit ec3ddd67bae4c491ec1faba7be7cc988c425506c)
Bug: 1247766
Change-Id: If9d69d5a0320bfd3b615446710358dd439074795
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3149409
Reviewed-by: Joshua Bell <jsbell@chromium.org>
Cr-Original-Commit-Position: refs/heads/main@{#919898}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3154684
Auto-Submit: Victor Costan <pwnall@chromium.org>
Commit-Queue: Rubber Stamper …
> chore: cherry-pick 7699615c0d and 2f5740f50f from chromium

- patches/angle/.patches
- patches/angle/webgl_make_unsuccessful_links_fail_subsequent_draw_calls.patch
- patches/chromium/.patches
- patches/chromium/skip_webgl_conformance_programs_program-test_html_on_all_platforms.patch
Skip WebGL conformance/programs/program-test.html on all platforms
To unblock ANGLE CL http://crrev.com/c/3140496, which modifies behaviour
to make it an error to draw after the current program fails to re-link.
(cherry picked from commit 8ef1e4544ed5214608039d969940347d8f98e543)
Bug: 1241123
Bug: angleproject:6358
Change-Id: I40a1f4843f902533745cc9527379def9d777a578
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3140226
Auto-Submit: Yuly Novikov <ynovikov@chromium.org>
Cr-Original-Commit-Position: refs/heads/main@{#918281}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3150594
Auto-Submit: Jamie …
> chore: cherry-pick 13842c96c2 from chromium and 018f85dea1 from angle

- .github/CODEOWNERS
> chore: add wg-security as required reviewer for security-warnings.ts

- shell/browser/api/electron_api_browser_window.cc
- shell/browser/api/electron_api_web_contents.cc
This fixes a couple of issues with transparent windows that were introduced
with #30778.
1. Sometimes, transparent windows would be white until a repaint (e.g. resize)
happened. This seems to be an issue with the `SetPageBaseBackgroundColor`
API, possibly will eventually be resolved with
https://chromium-review.googlesource.com/c/chromium/src/+/2958369 or
similar.
2. Child windows don't have their WebPreferences set immediately, so the
background color was nullopt at the time that HandleNewRenderFrame was
called. We fix this by updating the background color when the WebContents
wrapper is created in `WebContents::CreateFromWebPreferences`.
Notes: Fixed an issue where some transparent windows would show with a white background.
> fix: transparency on child windows being lost

- patches/chromium/.patches
- patches/chromium/cherry-pick-ddc4cf156505.patch
[M93 merge] webui: make WebUIAllowlist and WebUIAllowlistProvider thread-safe
This CL adds synchronization lock to WebUIAllowlist, and expose it as
scoped_refptr, so it provides thread-safety when used in
WebUIAllowlistProvider (per requirements of HostContentSettingsMap).
(cherry picked from commit 56489e04b7c39e7b6d2b3fb33549d2657dad23a9)
(cherry picked from commit 58eda7adb82e7fcc8001482334bfa6f9482aee78)
Fixed: 1238178
Change-Id: I4d8112f7792a7113b412af2eb67cbcef0bdcec1d
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3102499
Commit-Queue: Jiewei Qian  <qjw@chromium.org>
Reviewed-by: Christian Dullweber <dullweber@chromium.org>
Reviewed-by: calamity <calamity@chromium.org>
Reviewed-by: Victor Costan <pwnall@chromium.org>
Cr-Original-Original-Commit-Position: …
> chore: cherry-pick ddc4cf156505 from chromium

- docs/api/app.md
- docs/api/web-contents.md
- shell/browser/api/electron_api_app.cc
Fixes #30662
Notes: Added `isMainFrame` argument to `'certificate-error'` event.
> feat: add isMainFrame argument to 'certificate-error' event

- docs/api/browser-window.md
- shell/browser/native_window_mac.h
- shell/browser/native_window_mac.mm
- shell/browser/ui/cocoa/electron_ns_window_delegate.mm
- spec-main/api-browser-window-spec.ts
Partially addresses https://github.com/electron/electron/issues/30979.
Fixes an issue where non-resizable non-fullscreenable windows with aspect ratios set could return incorrect results for `isMaximized()`. macOS calls `windowWillUseStandardFrame:defaultFrame` with what it refers to as the "best fit" frame for a
given zoom (see [Discussion Section](https://developer.apple.com/documentation/appkit/nswindowdelegate/1419684-windowwillusestandardframe?language=objc)). This means that even if an aspect ratio is set, macOS might adjust it to better fit the screen. Thus, we can't just calculate the maximized aspect ratio'd sizing from the current visible screen and compare that to the current window's frame to determine whether a window is maximized in `isMaximized`.
Notes: Fixes an issue where …
> fix: maximized state calculation for non-resizable windows

- lib/browser/api/web-contents.ts
In #24517 and #28518, as part of adding the new `setWindowOpenHandler` API, we refactored the `_callWindowOpenHandler` method to pass in additional details and make it more compatible with the new API standard, `setWindowOpenHandler`. However, this also broke how feature details were passed into new child/guest windows, specifically ones still using `window.open` - if a window was not opened with an existing windowHandler, all child window constructor options would automatically return null, [hitting this check](https://github.com/electron/electron/pull/24517/files#diff-f6ca6a11b1d9a20b2f71e91a51c06f4956adb0eec9f07ac0705190f77c257211R448).
In Electron 14 and 15, two things changed: 1) [child windows no longer inherit their transparency settings from parent …
> fix: propagate window.open settings to child window

- docs/api/web-contents.md
- shell/browser/api/electron_api_web_contents.cc
- shell/common/gin_converters/content_converter.cc
- shell/common/gin_converters/content_converter.h
- spec-main/api-web-contents-spec.ts
Adds `frame` property to the context-menu event params.
Notes: Added `frame` property to the `params` object of the 'context-menu' event.
> feat: add frame to context-menu event params

- shell/browser/ui/file_dialog_gtk.cc
- shell/browser/ui/gtk_util.cc
- shell/browser/ui/gtk_util.h
- shell/browser/ui/message_box_gtk.cc
Closes https://github.com/electron/electron/issues/30247.
When passing `nullptr` for the text fields in `GtkFileChooserNative`, GTK+ will provide default, localized buttons.
GTK+ 4.0 also removes the stock items for dialog buttons, with the idea that devs would instead use `_("_Cancel")` `_("_Open")`, etc directly (using `gettext` to pull the appropriate translated strings from the translations that ship with GTK+).
This updates our logic accordingly.
Tested with https://gist.github.com/Kilian/3de5f404d90d9b12ccaec817fdc4d6da.
Notes: Fixed an issue where button labels in file choosers were improperly localized on Linux.
> fix: proper localization when using GtkFileChooserNative

- lib/browser/api/web-contents.ts
Small PR, follow up to #31031 - the comment above the fix marked `window.open` as being deprecated, when actually it's the `new-window` event that is now deprecated. To avoid adding confusion, this PR fixes that comment, changing `window.open` to `new-window.`
Notes: none
> chore: clarify new-window fix comment

- shell/browser/native_window_views.cc
To enable/disable window resizing we set/unset WS_THICKFRAME style
flag on the window. Window's frame styles are cached so we need to
call SetWindowPos with the SWP_FRAMECHANGED flag set to update
cache properly.
Issue: https://github.com/electron/electron/issues/31020
Notes: fixed black border around the page after resizing is disabled
> fix: update Windows' cache after changing window's style

- docs/api/web-contents.md
Fixed: https://github.com/electron/electron/issues/30992
Notes: none
> fix: startDrag params type incorrect

- docs/api/dialog.md
- lib/browser/api/dialog.ts
- shell/browser/ui/message_box.h
- shell/browser/ui/message_box_mac.mm
- shell/common/gin_converters/message_box_converter.cc
This allows working around the overly narrow `NSAlert` dialogs on macOS Big Sur. Default:
textWidth = 420:
Notes: Added `textWidth` option to `dialog.showMessageBox()` / `dialog.showMessageBoxSync()`.
> feat: add textWidth option to dialog.showMessageBox()

- patches/chromium/.patches
- patches/chromium/linux_sandbox_return_enosys_for_clone3.patch
- patches/chromium/linux_sandbox_update_syscall_numbers_for_all_platforms.patch
Refs https://bugs.launchpad.net/ubuntu/+source/glibc/+bug/1944468
Refs https://bugs.chromium.org/p/chromium/issues/detail?id=1244383
Refs https://bugs.chromium.org/p/chromium/issues/detail?id=1213452
The fix is available in Electron >= 14
Notes: fix crash in seccomp sandbox with glibc 2.34
> fix: crash in seccomp sandbox with glibc 2.34

- shell/browser/native_browser_view_mac.mm
Partially addresses https://github.com/electron/electron/issues/31058.
Fixes an issue where the `DragRegionView` did not accept the first mouse click, meaning that the first click would only activate the window and not trigger drag behavior immediately as would occur with a BrowserWindow. This fixes the error by ensuring that `acceptsFirstMouse` returns `YES` for  `DragRegionView`.
Tested with https://gist.github.com/0a371fe58ff8c8b72287629ab6d76d34.
Notes: Fixes an issue where out-of-focus BrowserViews could not be immediately dragged.
> fix: first mouse not dragging BrowserView

- patches/node/fix_handle_boringssl_and_openssl_incompatibilities.patch
Made obsolete in https://boringssl-review.googlesource.com/c/boringssl/+/40484 and can now be removed.
Notes: none
> chore: remove obsolete chunk of BoringSSL patch

- shell/browser/api/electron_api_web_contents.cc
- shell/browser/api/electron_api_web_contents.h
Fix a race condition when destroying WebContents that, if the `FirstWeakCallback` of `gin::Wrapper` has been called but the `SecondWeakCallback` has not, the `api::WebContents::Destroy` will still call `delete this` while unable to prevent `SecondWeakCallback` from calling `delete this`, which will result in double free.
Notes: Fix crash caused by double free when destroying WebContents.
> fix: avoid double free when destroying WebContents

- shell/browser/api/electron_api_menu.cc
- shell/browser/api/electron_api_menu.h
- shell/browser/api/electron_api_menu_mac.h
- shell/browser/api/electron_api_menu_mac.mm
- shell/common/api/electron_api_v8_util.cc
- spec-main/api-menu-item-spec.ts
- typings/internal-electron.d.ts
Several tests are failing with a release build as they are calling APIs only available when `DCHECK` is on:
```
not ok 783 MenuItems MenuItem accelerators should display modifiers correctly for simple keys
TypeError: menu.getAcceleratorTextAt is not a function
at Context.<anonymous> (electron/spec-main/api-menu-item-spec.ts:465:19)
at processImmediate (node:internal/timers:464:21)
not ok 784 MenuItems MenuItem accelerators should display modifiers correctly for special keys
TypeError: menu.getAcceleratorTextAt is not a function
at Context.<anonymous> (electron/spec-main/api-menu-item-spec.ts:477:19)
at processImmediate (node:internal/timers:464:21)
not ok 785 MenuItems MenuItem accelerators should not display modifiers twice
TypeError: menu.getAcceleratorTextAt is not a function
at …
```
> fix: running tests with release build

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/ISSUE_TEMPLATE/mac_app_store_private_api_rejection.yml
- .github/PULL_REQUEST_TEMPLATE.md
- .github/config.yml
- CONTRIBUTING.md
- README.md
- SECURITY.md
- docs/breaking-changes.md
- docs/development/README.md
- docs/development/azure-vm-setup.md
- docs/development/build-instructions-gn.md
- docs/development/electron-vs-nwjs.md
- docs/development/pull-requests.md
- docs/tutorial/fuses.md
- docs/tutorial/security.md
- docs/tutorial/support.md
Update references to `master` in the documentation to `main` for `electron/electron` and `electron/governance`.
Notes: none
> docs: Update Branch Name

- docs/development/debugging-instructions-macos.md
.lldbinit config stale (unavailable)
see: https://chromium.googlesource.com/chromium/src/+/refs/heads/main/docs/lldbinit.md
the previous document has no effect
Notes: none
cc: @felixrieseberg @kevinsawicki
> fix: .lldbinit config stale (unavailable)

- shell/common/api/electron_api_v8_util.cc
- spec-main/api-context-bridge-spec.ts
- typings/internal-ambient.d.ts
Follow-up to #31092. It also fixes the release builds, which the previous PR broke.
Notes: none
> refactor: use native WeakRef instead of v8util.weaklyTrackValue()

- shell/browser/native_browser_view_mac.mm
This PR fixes issue #31058, inconsistent window dragging behavior between `BrowserWindow`s and `BrowserView`s. The root cause was a malformed selector, which no `view.window` instances could respond to.
https://www.loom.com/share/3ab47d45a0be4223af88b3377a800cd9
[Guidance appreciated for the Checklist and Release Notes sections. This change should help Electron better implement its current documentation; no new docs or userland education is expected. `npm test` is failing for me on node-gyp rebuilds, so hoping CI can confirm this is safe.]
Notes: Fixes an issue where BrowserView dragging behavior was inconsistent with MacOS window dragging.
> fix: BrowserView drag now delegates to the OS when possible

- script/lint.js
In order to validate that header guards match the corresponding file
names, `cpplint.py` determines the root of the project based on the
presence of a `.git` directory.
For space reasons, our Electron.js fork running on CircleCI deletes the
`.git` directories as upstream Electron.js does here:
https://github.com/electron/electron/blob/cd09a5436544ca0610542bc5b14adf992a9d9df2/.circleci/config.yml#L426
If the C++ linter is ran *after* deleting git directories, `cpplint.py`
gets the root wrong and throws errors for every single header guard in
the project.
Making sure we run the C++ linter *before* deleting git directories
fixes the issue. In any case, this commit always manually passes
`--project_root` to `cpplint.py` so that the implicit default is
explicitly declared and saves some …
> build: Explicitly pass the project root to cpplint.py

- shell/browser/api/electron_api_browser_window_mac.mm
Closes https://github.com/electron/electron/issues/31068
Closes https://github.com/electron/electron/issues/31052.
After https://github.com/electron/electron/pull/26145, it was possible to make draggable regions on BrowserViews independent from those of BrowserWindows. As such, if a BrowserView with different draggable regions than the BrowserWindow it belongs to is superimposed on top of that window, the draggable regions of the BrowserView take precedence over those of the BrowserWindow. This is fixed by having each BrowseView update its own draggable regions in `BrowserWindow::UpdateDraggableRegions` instead of inheriting those coming in from `BrowserWindow::UpdateDraggableRegions`.
Tested with https://gist.github.com/0a53108546ef22e4d03e1b6dea55a79a and …
> fix: draggable regions in `BrowserView`s are independent

- shell/browser/mac/electron_application.mm
- shell/browser/native_window_mac.mm
- shell/browser/ui/tray_icon_cocoa.mm
The minimum supported deploy target is 10.11, so these are no longer necessary.
Notes: none
> chore: remove redundant 10.11 @available checks

- patches/chromium/.patches
- patches/chromium/cherry-pick-f8a74d72f328.patch
content-visibility: Add a clipper fix for content-visibility.
This patch adds a few checks in the svg painting code which may access
a content-visibility locked element via an svg reference.
R=​fs@opera.com,jarhar@chromium.org
(cherry picked from commit e0d8a4f20bf98bbda2dc58199fca5caf0add1b00)
Bug: 1247196
Change-Id: I4dcb4ef298fb8d51aa0ec1a3b3bc130cfb560791
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3149811
Reviewed-by: Fredrik Söderquist <fs@opera.com>
Reviewed-by: Joey Arhar <jarhar@chromium.org>
Commit-Queue: vmpstr <vmpstr@chromium.org>
Cr-Original-Commit-Position: refs/heads/main@{#920209}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3158958
Commit-Queue: Joey Arhar <jarhar@chromium.org>
Commit-Queue: Mason Freed …
> chore: cherry-pick f8a74d72f328 from chromium

- patches/boringssl/.patches
- patches/boringssl/enable_x509_v_flag_trusted_first_flag.patch
This flag is set by default on OpenSSL.
Fixes: https://github.com/electron/electron/issues/31212
Notes: Fix Let's Encrypt DST Root CA X3 certificate expiration.
> fix: Enable X509_V_FLAG_TRUSTED_FIRST flag in BoringSSL

- docs/fiddles/system/protocol-handler/launch-app-from-URL-in-another-app/main.js
Corrects the following error in Electron Fiddle:
```
Uncaught Exception:
ReferenceError: dialog is not defined
...
```
Notes: none
> docs: dialog is not defined

- patches/v8/.patches
- patches/v8/cherry-pick-5c4acf2ae64a.patch
Merged: [heap] Improve ephemeron processing
Revision: 1054ee7f349d6be22e9518cf9b794b206d0e5818
Bug: chromium:1252918
Change-Id: I0764cb78d4a0d4b5859c0edf383c2827321db398
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/3195062
Reviewed-by: Shu-yu Guo <syg@chromium.org>
Cr-Commit-Position: refs/branch-heads/9.4@{#37}
Cr-Branched-From: 3b51863bc25492549a8bf96ff67ce481b1a3337b-refs/heads/9.4.146@{#1}
Cr-Branched-From: 2890419fc8fb9bdb507fdd801d76fa7dd9f022b5-refs/heads/master@{#76233}
Notes: Security: backported fix for CVE-2021-37975.
> chore: cherry-pick 5c4acf2ae64a from v8

- patches/angle/.patches
- patches/angle/fix_integer_overflow_in_blocklayoutencoder.patch
- patches/config.json
Fix integer overflow in BlockLayoutEncoder
BlockLayoutEncoder::mCurrentOffset's computation had the
possibility of causing integer overflows in multiple places,
so this CL adds CheckedNumeric variables in a number of
these occurrences in order to prevent integer overflows and
causing issues.
The issue in this case was an integer overflow causing the
code in ValidateTypeSizeLimitations.cpp to use an invalid
result from "layoutEncoder.getCurrentOffset()", which ended
up compiling a shader which would later cause an OOM error.
Bug: chromium:1248665
Change-Id: I688d669f21c6dc2957e43bdf91f8f8f08180a6f7
Reviewed-on: https://chromium-review.googlesource.com/c/angle/angle/+/3163356
Reviewed-by: Geoff …
> chore: cherry-pick e8cb0e7aa32 from angle

- patches/chromium/.patches
- patches/chromium/cherry-pick-4e528a5a8d83.patch
FSA: Fix race condition in manager
(cherry picked from commit 951339b41022b08a67ad94ba5960b05c84bf4cf2)
Bug: 1248030
Change-Id: I1ea819d1d6ac63ec8f400a45c893da49596235ef
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3154425
Auto-Submit: Austin Sullivan <asully@chromium.org>
Cr-Original-Commit-Position: refs/heads/main@{#920376}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3160301
Commit-Queue: Austin Sullivan <asully@chromium.org>
Cr-Commit-Position: refs/branch-heads/4606@{#1077}
Cr-Branched-From: 35b0d5a9dc8362adfd44e2614f0d5b7402ef63d0-refs/heads/master@{#911515}
Notes: Security: backported fix for CVE-2021-37970.
> chore: cherry-pick 4e528a5a8d83 from chromium

- shell/browser/api/electron_api_printing.cc
- shell/browser/api/electron_api_web_contents.cc
- shell/browser/api/electron_api_web_contents.h
Refs:
- https://chromium-review.googlesource.com/c/chromium/src/+/2796126
- https://chromium-review.googlesource.com/c/chromium/src/+/2932396
Chromium recently added the ability to  distinguish between no printer(s) and a query failure. I don't think a failure to enumerate printers should result in a user-facing error, but we should at least log this nuance instead of dropping it on the ground.
Notes: none
> chore: add logging for print_backend failures

- spec/webview-spec.js
Follow-up to #31259
Notes: none
> test: add missing context-menu event spec for <webview>

- docs/api/webview-tag.md
The `'context-menu'` event is forwarded to the `<webview>`, but it's not documented there.
https://github.com/electron/electron/blob/3b2c46dfd6ceb7dfdbfd93ea8a91e5f9b0b5a7ea/lib/common/web-view-events.ts#L11
Notes: none
> docs: add missing 'context-menu' event to webview-tag.md

- docs/api/session.md
- docs/tutorial/devices.md
- shell/browser/electron_browser_context.cc
- shell/browser/electron_browser_context.h
- shell/browser/electron_permission_manager.cc
- shell/browser/serial/electron_serial_delegate.cc
- shell/browser/serial/serial_chooser_context.cc
- shell/browser/serial/serial_chooser_context.h
- shell/browser/serial/serial_chooser_context_factory.cc
- shell/browser/serial/serial_chooser_controller.cc
- shell/browser/serial/serial_chooser_controller.h
- shell/browser/web_contents_permission_helper.cc
- shell/browser/web_contents_permission_helper.h
This is a refactor of #30209 to use the same permissioning that was implemented for [WebHID](#21311).
Notes: Changed Web Serial to use `ses.setDevicePermissionHandler` to allow developers more control over Web Serial permissioning.
> chore: refactor persisting permission granted to serial ports

- shell/browser/api/electron_api_browser_window.cc
- spec-main/api-browser-window-spec.ts
Closes https://github.com/electron/electron/issues/31337.
Fixes a crash when a `BrowserWindow` is closed subsequent to its `webContents` being destroyed.
We were checking for `web_contents()` being nullptr but not `api_web_contents_`, which would be the case if the `webContents` is destroyed prior to the window.
Notes: Fixed a crash when a `BrowserWindow` is closed subsequent to its `webContents` being destroyed.
> fix: crash on close window when webContents destroyed

- shell/browser/hid/electron_hid_delegate.cc
This PR changes WebHID to use the `disable-hid-blocklist` flag to enable access to FIDO devices.  The original WebHID implementation disallowed access to all FIDO devices for security reasons, but using the `disable-hid-blocklist` flag (which is by default false) allow developers to opt-in to FIDO device access while maintaining the default of disabling access to FIDO devices via WebHID. 
Closes #31595
Notes: changed WebHID to use `disable-hid-blocklist` flag to enable FIDO devices.
> fix: use disable-hid-blocklist to allow FIDO devices

- docs/api/clipboard.md
- shell/common/api/electron_api_clipboard.cc
- spec/api-clipboard-spec.js
#31566 incorrectly assumed that `clipboard.read` and `clipboard.readBuffer` should operate differently, but after testing earlier versions of Electron, the only difference between these two functions is that `clipboard.read` returns a String and `clipboard.readBuffer` returns a Buffer.
- fixes #31130
Notes: fixed clipboard.read to once again work like clipboard.readBuffer.
> fix: clipboard.read() to work consistently with clipboard.readBuffer()

- patches/chromium/printing.patch
Backport of #31489.
Notes: Fixed an issue which caused print settings to not work properly when printing silently.
> fix: silent print settings

- patches/node/chore_add_context_to_context_aware_module_prevention.patch
Backport of #31579
Notes: none
> chore: update chore_add_context_to_context_aware_module_prevention.patch

- patches/node/.patches
- patches/node/test_fix_test-datetime-change-notify_after_daylight_change.patch
The node test `parallel/test-datetime-change-notify` started failing recently due to a daylight savings change.  This PR backports https://github.com/nodejs/node/commit/747ef34fb0c9c1f2924ab1b79ea000c87e67a8eb to fix that issue.
Notes: none
> test: fix test-datetime-change-notify after daylight change

- script/lint.js
- shell/browser/ui/file_dialog_mac.mm
- shell/browser/ui/message_box_mac.mm
- shell/common/gin_helper/promise.h
Close https://github.com/electron/electron/issues/26884.
The completion handler of macOS dialogs runs inside a transaction commit, and calling `runModal` in it would cause an assertion in internal macOS. This results in crash when showing a synchronous dialog immediately after showing an asynchronous dialog, and it can be fixed by delaying the callback of async dialog APIs to the next tick of message loop.
I'm unable to write a test for this, since the crash involves showing an synchronous dialog, which currently can not be controlled programmingly.
Notes: Fix crash when using sync dialog APIs immediately after async dialog APIs.
> fix: do not run dialog callback inside transaction commit

- patches/v8/.patches
- patches/v8/cherry-pick-feef10137b16.patch
Merged: [runtime] Check if we have a pending exception before returning it
Revision: be55c16e50e714475034b00ed2682f0813794d15
BUG=chromium:1263462
NOTRY=true
R=cbruni@chromium.org
Change-Id: Ib7de676fe614403674fcd2745c574f7e91ded23f
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/3247033
Reviewed-by: Camillo Bruni <cbruni@chromium.org>
Cr-Commit-Position: refs/branch-heads/9.4@{#52}
Cr-Branched-From: 3b51863bc25492549a8bf96ff67ce481b1a3337b-refs/heads/9.4.146@{#1}
Cr-Branched-From: 2890419fc8fb9bdb507fdd801d76fa7dd9f022b5-refs/heads/master@{#76233}
Notes: Backported fix for CVE-2021-38003.
> chore: cherry-pick feef10137b16 from v8

- patches/chromium/.patches
- patches/chromium/cherry-pick-45f9dcf5021d.patch
Disable QuicTransport explicitly in the Network Service
(cherry picked from commit b1997bdadcda9738a19773f82605f65832acedac)
Bug: 1260940
Change-Id: I6689fbce8115eda19e68414d7c03691704749b17
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3242207
Auto-Submit: Victor Vasiliev <vasilvv@chromium.org>
Commit-Queue: Yutaka Hirano <yhirano@chromium.org>
Cr-Commit-Position: refs/branch-heads/4606@{#1411}
Cr-Branched-From: 35b0d5a9dc8362adfd44e2614f0d5b7402ef63d0-refs/heads/master@{#911515}
Notes: Backported fix for CVE-2021-38002.
> chore: cherry-pick 45f9dcf5021d from chromium

- patches/v8/.patches
- patches/v8/cherry-pick-014e1f857c33.patch
Merged: [super ic] Fix receiver vs lookup start object confusion related to module exports
Revision: e4dba97006ca20337deafb85ac00524a94a62fe
BUG=chromium:1260577
NOTRY=true
R=ishell@chromium.org
Change-Id: Ia85235fecdb37a5da6a28f7a0092a754a8620552
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/3240826
Commit-Queue: Marja Hölttä <marja@chromium.org>
Cr-Commit-Position: refs/branch-heads/9.4@{#48}
Cr-Branched-From: 3b51863bc25492549a8bf96ff67ce481b1a3337b-refs/heads/9.4.146@{#1}
Cr-Branched-From: 2890419fc8fb9bdb507fdd801d76fa7dd9f022b5-refs/heads/master@{#76233}
Notes: Backported fix for CVE-2021-38001.
> chore: cherry-pick 014e1f857c33 from v8

- shell/browser/api/electron_api_web_request.cc
- spec-main/api-web-request-spec.ts
Closes https://github.com/electron/electron/issues/31662.
Refs https://github.com/electron/electron/pull/25961.
Fixes an issue where `Content-Disposition` filenames would be incorrectly truncated at the first comma for filename attachments which contained one. This was happening becuase the filename in the parse `net::HttpContentDisposition` header was not being correctly wrapped in double quotes, thereby breaking serialization.
Tested with the repro provided in the above linked issue:
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
Notes: Fixes an issue where `Content-Disposition` filenames would be incorrectly truncated at the first comma for a filename attachment which contained one.
> fix: incorrect Content-Disposition serialization

- patches/v8/.patches
- patches/v8/merged_cppgc_fix_marking_of_ephemerons_with_keys_in_construction.patch
Merged: cppgc: Fix marking of ephemerons with keys in construction
Revision: 32a09a6bce6cc75806dee5ec748bb1d081048fd0
BUG=chromium:1259587
NOTRY=true
R=dinfuehr@chromium.org
Change-Id: Ief330b4b71705c16bc61a3aca6d3aa1db172cdf3
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/3234200
Reviewed-by: Dominik Inführ <dinfuehr@chromium.org>
Cr-Commit-Position: refs/branch-heads/9.4@{#46}
Cr-Branched-From: 3b51863bc25492549a8bf96ff67ce481b1a3337b-refs/heads/9.4.146@{#1}
Cr-Branched-From: 2890419fc8fb9bdb507fdd801d76fa7dd9f022b5-refs/heads/master@{#76233}
Notes: Backported fix for CVE-2021-37998.
> chore: cherry-pick 656c2769c5 from v8

- shell/browser/electron_autofill_driver.cc
- shell/browser/electron_autofill_driver.h
- shell/browser/electron_autofill_driver_factory.cc
- shell/browser/electron_autofill_driver_factory.h
- shell/browser/electron_browser_client.cc
Update our AutofillDriver and AutofillDriverFactory code to match upstream.
This was prompted by an upstream change that removes API that we were using. Specifically, https://github.com/electron/electron/pull/31555 includes https://chromium-review.googlesource.com/c/chromium/src/+/3241451 removes the getAllFrames() API that our AutofillDriverFactory uses.
Our code appears to be derived from [components/autofill/content/browser/content_autfill_driver*[cc,h]](components/autofill/content/browser/content_autofill_driver), whose identical use of getAllFrames()  removed in 2019 by https://chromium-review.googlesource.com/c/chromium/src/+/1826885. In that change, the upstream factory was changed to create and bind the autofill drivers on command. This PR tries to follow that approach in our …
> refactor: use upstream AutofillDriverFactory diffs

- patches/chromium/.patches
- patches/chromium/cherry-pick-91dd4f79ab5b.patch
[mojo] Validate INTRODUCE source node
INTRODUCE NodeChannel messages should only be acknowledged when coming
from the broker process.
(cherry picked from commit 6e74f7b5cb2f48b17403f0431f3e4f3a2e716265)
Fixed: 1252858
Change-Id: I2dff6d5cab102ce744ad2ad66a9f24b4202cbea8
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3193798
Reviewed-by: Alex Gough <ajgo@chromium.org>
Cr-Original-Commit-Position: refs/heads/main@{#926430}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3229034
Reviewed-by: Oksana Zhuravlova <oksamyt@chromium.org>
Commit-Queue: Oksana Zhuravlova <oksamyt@chromium.org>
Cr-Commit-Position: refs/branch-heads/4638@{#964} …
> chore: cherry-pick 91dd4f79ab5b from chromium

- shell/browser/api/electron_api_web_contents.cc
- shell/browser/web_contents_preferences.cc
- shell/browser/web_contents_preferences.h
In #30193, we refactored WebContentsPreferences to store its values directly and centralize logic for default values. As part of that refactor, the `transparency` setting was removed, and any transparent values were instead stored in the `background_color_` property (e.g., `background_color_ = SK_ColorTRANSPARENT`. 
We handle for cases like this explicitly for browser windows here:
https://github.com/electron/electron/blob/a2d993c9b48809128ca0d8a6c61f4c5ff7c8e385/shell/browser/api/electron_api_browser_window.cc#L40-L50
However, this transparency handling only applies to browser windows, and does not take into account events where the WebContents or WebContentsPreferences are created independently from the browser window, such as "-will-add-new-contents" events.
This PR adds a transparency …
> fix: apply transparency settings to WebContentsPreferences

- patches/chromium/feat_add_data_parameter_to_processsingleton.patch
- spec-main/api-app-spec.ts
- spec/fixtures/api/singleton-data/main.js
- spec/fixtures/api/singleton/main.js
This PR adds more tests to the `app.requestSingleInstanceLock` second instance -> first instance data flow, since it'll be helpful to have tests running more for that flow before part ii (https://github.com/electron/electron/pull/31460) gets merged in.
Notes: Fixed behaviour on posix when passing lists into `app.requestSingleInstanceLock(additionalData)` API.
> fix: second-instance additionalData parameter

- shell/app/electron_main_delegate.cc
- shell/browser/electron_browser_client.cc
Closes https://github.com/electron/electron/issues/31643.
Closes https://github.com/electron/electron/issues/31565
Refs https://github.com/electron/electron/pull/30278 - now that Electron has switched to Crashpad by default on Linux `DIR_CRASH_DUMPS` should be the same across supported platforms.
Notes:  Fixed an issue where `app.getPath('crashDumps')` returned an incorrect path for Linux.
> fix: crash dump location on Linux

- spec-main/fixtures/devtools-extensions/foo/panel.js
The test `<webview> tag loads devtools extensions registered on the parent window Link Column Header Test` has been more[ flaky recently on WOA](https://github.visualstudio.com/electron/_test/analytics?definitionId=48&contextType=build) and this PR should make that test less flaky.  I ran it three times on WOA and got green builds:
https://github.visualstudio.com/electron/_build/results?buildId=118722
https://github.visualstudio.com/electron/_build/results?buildId=118715
https://github.visualstudio.com/electron/_build/results?buildId=118729
Notes: none
> test: deflake <webview> tag loads devtools extensions on WOA

- shell/browser/api/electron_api_web_contents.cc
Fixes #31686 regressed by #30777
Notes: Fixed `<webview>` background transparency regression.
> fix: <webview> background transparency

- BUILD.gn
- filenames.gni
- package.json
- shell/browser/api/electron_api_app.h
- shell/browser/certificate_manager_model.cc
- shell/browser/certificate_manager_model.h
These are the last source files in chromium_src, just move them to shell. Follow-up to #30837
Notes: none
> refactor: move certificate_manager_model to shell

- spec-main/api-crash-reporter-spec.ts
Follow-up to #30278. We are now using Crashpad everywhere.
Notes: none
> chore: remove Breakpad tests for crashReporter on Linux

- lib/renderer/api/context-bridge.ts
- lib/renderer/init.ts
- lib/renderer/web-view/web-view-init.ts
- lib/sandboxed_renderer/init.ts
- shell/renderer/api/electron_api_web_frame.cc
- spec/fixtures/api/window-open-preload.js
- typings/internal-ambient.d.ts
We can use `process.contextIsolated` instead.
Notes: none
> refactor: remove duplicate contextIsolation from getWebPreference()

- spec-main/api-browser-window-spec.ts
This fixes a crash that was happening in CI.  Its possible this was originally caused/exposed by:
- #27920
The underlying issue is that the test `BrowserWindow module window states (excluding Linux) fullscreen state should not cause a crash if called when exiting fullscreen` calls close on the window, but it doesn't wait for the window to be closed before finishing the test.  When the test finishes, `closeAllWindows` is invoked which ends up [destroying the window](https://github.com/electron/electron/blob/main/spec-main/window-helpers.ts#L20) before the close can complete, thus causing the crash.
- Fixes #28361
Notes: none
> test: fix crash in electron::NativeWindowMac::Close()

- patches/node/.patches
- patches/node/test_add_fixture_trim_option.patch
- script/node-disabled-tests.json
Fixes a spec failure originating with a strict requirement in BoringSSL
that base64 strings be evenly divisible by 4 in their implementation of
`NETSCAPE_SPKI_b64_decode`.
Fixes that issue by trimming the newlines out of the file.
Upstreamed at https://github.com/nodejs/node/pull/40757.
Notes: none.
> fix: failing Node.js certificate spec

- shell/browser/api/electron_api_browser_view.cc
- shell/browser/api/electron_api_web_contents.cc
Closes https://github.com/electron/electron/issues/31742.
Applies fix from https://github.com/electron/electron/pull/30777 to `BrowserView`s. Also updates https://github.com/electron/electron/pull/31722 to include `BrowserView`s.
Tested with https://gist.github.com/kevinlinv/2de60478ffec6a2f18f1ec0fc6f5add9
Notes: Fix `BrowserView.setBackgroundColor()` not working correctly.
> fix: BrowserView setBackgroundColor()

- script/release/notes/notes.js
Previously the release notes generator produced notes such as:
`Fixed &lt;webview&gt; background transparency regression.`
This fix produces the correct note as follows:
`Fixed <webview> background transparency regression.`
@miniak 
Notes:  None
> fix: generate angle brackets in release notes

- patches/node/.patches
- patches/node/fix_crash_caused_by_gethostnamew_on_windows_7.patch
Close https://github.com/electron/electron/issues/31795.
Apply the patch https://github.com/libuv/libuv/pull/3285 to fix crash caused by GetHostNameW on Windows 7.
The original PR has not been merged to upstream yet but has already got some eyes on it, and I think the code is safe.
It seems that upstream libuv is not going to merge the PR anytime soon, and we should not break Windows 7 support yet, so applying the fix in Electron seems the best solution.
Notes: Fix crash caused by `GetHostNameW` on Windows 7.
> fix: crash caused by GetHostNameW on Windows 7

- shell/browser/ui/file_dialog_gtk.cc
Fixes #31630.
Adds a size check to the image file before previewing it. I've set the cutoff at 100 MB since "100 MB ought to be enough for anybody" but if there's a strong use case for previewing 100 MB image files we could increase it.
CC @codebytere 
Notes: Fixed crash in GTK open dialog when trying to preview huge image files.
> fix: in GTK open dialog, do not preview huge files

- shell/browser/ui/gtk_util.cc
- shell/browser/ui/gtk_util.h
Fixes https://github.com/electron/electron/issues/31797. Default text labels in GTK dialogs broke as a side-effect of switching to GtkNativeDialogs.
CC @codebytere, this is the other issue I was talking about looking at when I came across 31630 :smile_cat: 
Notes: Fixed default label text in GTK dialogs.
> fix: correct default text for button labels in gtk dialogs

- shell/browser/api/electron_api_web_contents.cc
- spec-main/api-browser-view-spec.ts
Fixes an issue where `BrowserView`s crashed if `view.webContents.destroy()` is called after loading a URL. This happened because when the webContents closed synchronously, the `InspectableWebContents` was forced to close before all observers had been notified, causing a CHECK [here](https://source.chromium.org/chromium/chromium/src/+/main:content/browser/web_contents/web_contents_impl.cc;l=988?q=is_notifying_observers&ss=chromium).
To fix this, I chose to remove the `BrowserView` type from the synchronous conditions, though if there is a preferred approach I'm happy to modify this.
Notes: Fixes an issue where `BrowserView`s crashed if `view.webContents.destroy()` is called after loading a URL.
> fix: crash on browserView.webContents.destroy()

- patches/chromium/fix_media_key_usage_with_globalshortcuts.patch
Playing media shouldn't open Accessibility permissions dialog on macOS.
However, we still need to watch for media events, just not globally and
`media_keys_listener_` is an API over global capture of the media keys.
The fix is to let chromium call `UpdateWhichKeysAreListenedFor` which
will call `UpdateSystemMediaControlsEnabledControls` and watch for
events on `system_media_controls_` without triggering permissions popup.
Fix: #31558
Notes: Fixed an issue where playing media would open Accessibility permissions dialog on macOS.
> fix: media shouldn't open permissions dialog

- docs/api/cookies.md
- shell/browser/api/electron_api_cookies.cc
- spec-main/api-net-spec.ts
Resolves #31553
Chrome recently [changed the same site default setting for cookies](https://www.chromium.org/updates/same-site) from `NO_RESTRICTION` to `LAX_MODE`.
This PR updates our cookie API to reflect that change, which will allow users to set insecure cookies again. However, cookies with `lax` or `strict` settings would not persist over redirects, which would break an expected default behavior for users.
Notes: Fixed default setting used when setting an insecure cookie on a secure site.
> fix: change cookie default from NO_RESTRICTION to LAX_MODE

- chromium_src/BUILD.gn
- shell/browser/net/network_context_service.cc
- shell/browser/net/system_network_context_manager.cc
- shell/browser/net/system_network_context_manager.h
Manual backport of #31777
Notes: `~/.config/{App Name}` will no longer be incorrectly deleted if it is a symlink on unix systems
> fix: provide paths for all NetworkContextFilePaths keys 

- chromium_src/BUILD.gn
- shell/browser/net/network_context_service.cc
- shell/browser/net/system_network_context_manager.cc
- shell/browser/net/system_network_context_manager.h
Chromium is currently migrating file paths for the network service to a different path, as such a bunch of path calculations were moved into a config struct that we weren't fully populating.
This populates the struct identically to `//chrome`.
Refs: https://source.chromium.org/chromium/chromium/src/+/main:services/network/public/mojom/network_context.mojom;l=219;drc=b6e40f8ab247ea209bcecff994386a70a4169e9d
Refs: https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/net/profile_network_context_service.cc;l=712;drc=b6e40f8ab247ea209bcecff994386a70a4169e9d;bpv=1;bpt=1
Notes: `~/.config/{App Name}` will no longer be incorrectly deleted if it is a symlink on unix systems
> fix: provide paths for all NetworkContextFilePaths keys

- shell/common/gin_converters/std_converter.h
- shell/renderer/api/electron_api_context_bridge.cc
The variable `input` is accepted by a universal reference, so it doesn't
make sense to cast a potential lvalue reference into an rvalue
reference. In case `input` is an lvalue reference, we should rather
forward the value as is to `ToV8()`.
Notes: none
> chore: use `std::forward()` in `ConvertToV8()`

- build/args/all.gn
This PR updates our NMV to 103 for Electron 18
Please do not merge until 17-alpha branch is created and this PR has been closed: https://github.com/nodejs/node/pull/40768
Notes: none
> chore: update nmv to 103 for Electron 18

- script/generate-config-gypi.py
enabling `--openssl-no-asm` for all platforms
Related PR: https://github.com/electron/electron/pull/31404
cc: @zcbenz 
Notes: none
> fix: ninja build failed on some system

- shell/browser/api/electron_api_browser_view.cc
I determined in testing that https://github.com/electron/electron/pull/31746 regressed https://github.com/electron/electron/issues/29778. 
It remains the case that we want to call `SetPageBaseBackgroundColor` on the `BrowserView`'s webContents, but we don't want to do this at the expense of calling `SetBackgroundColor` on the `RenderWidgetHostView`. We need to do both calls - similar to what's done here: https://github.com/electron/electron/blob/7e328c4b87399e36b6d7173eac5332a5255ee3cc/shell/browser/api/electron_api_web_contents.cc#L1462-L1463
Tested with
- https://gist.github.com/kevinlinv/2de60478ffec6a2f18f1ec0fc6f5add9 to ensure default transparency
- https://gist.github.com/712a2fde2757736c9dbf6c3e7e0aa18b
Notes: Fixed a potential issue when setting backgroundColor on `BrowserView`s.
> fix: BrowserView setBackgroundColor needs two calls

- patches/chromium/.patches
- patches/chromium/fix_aspect_ratio_with_max_size.patch
- spec-main/api-browser-window-spec.ts
Add the native frame border size to the minimum and maximum size if
the view reports its size as the client size. It allows to enlarge
window to proper values when aspect ratio and max width/height are
set. It also fixes DCHECK which was triggered when user tried to
enlarge window above dimensions set during creation of the
BrowserWindow.
Fixes https://github.com/electron/electron/issues/29100
Notes: fixed respecting aspect ratio when maximum size is set on BrowserWindow
> fix: aspect ratio when max width/height is set

- patches/chromium/.patches
- patches/chromium/cherry-pick-a5f54612590d.patch
M96: Storage Foundation: Avoid cross-thread access of DOMArrayBufferView.
blink::NativeIOFile::{read, write}() (in the Storage Foundation API
implementation) pass DOMArrayBufferView instances to
blink::NativeIOFile::Do{Read,Write}() via CrossThreadPersistent.
blink::NativeIOFile::Do{Read,Write}() accesses these instances.
CrossThreadPersistent can be used across threads to keep a garbage
collected object alive. However, accessing the object on a different
thread is not safe. cppgc::subtle::CrossThreadPersistent
(blink::CrossThreadPersistent is an alias to that) has comments
explaining that the garbage collected heap can go away while the
CrossThreadPersistent instance exists.
This CL bypasses the problem by having Do{Read,Write}() receive a
ArrayBufferContents that has the …
> chore: cherry-pick a5f54612590d from chromium

- patches/v8/.patches
- patches/v8/cherry-pick-5d2b5e7c006c.patch
Merged: [TurboFan] Do not use NumberConstant as immediate in x86
Bug: chromium:1254189
(cherry picked from commit bdf31d5883607db4377b519d7308fb1e639a0448)
Change-Id: I1d4426fee8392c7a680ad67af4bf2745d04b2e52
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/3268905
Commit-Queue: Nico Hartmann <nicohartmann@chromium.org>
Reviewed-by: Maya Lekova <mslekova@chromium.org>
Cr-Commit-Position: refs/branch-heads/9.6@{#22}
Cr-Branched-From: 41a5a247d9430b953e38631e88d17790306f7a4c-refs/heads/main@{#77244}
Notes: Backported fix for CVE-2021-38007.
> chore: cherry-pick 5d2b5e7c006c from v8

- patches/chromium/.patches
- patches/chromium/cachestorage_store_partial_opaque_responses.patch
CacheStorage: Store partial opaque responses.
(cherry picked from commit 802faa035409ac7cbb58ad1a385bb8507fe99077)
Fixed: 1260649
Change-Id: If83156096e6aecec55490330d03c56c0c26120bc
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3251749
Commit-Queue: Ben Kelly <wanderview@chromium.org>
Cr-Original-Commit-Position: refs/heads/main@{#937400}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3264366
Cr-Commit-Position: refs/branch-heads/4664@{#774}
Cr-Branched-From: 24dc4ee75e01a29d390d43c9c264372a169273a7-refs/heads/main@{#929512}
Notes: Backported fix for CVE-2021-38009.
> chore: cherry-pick 1fcfb942bd from chromium

- shell/app/node_main.cc
When adopting [16.8.0](https://github.com/electron/electron/pull/30714) our global console window patch was replaced to adopt https://github.com/nodejs/node/pull/39712 but it was not adopted for `ELECTRON_RUN_AS_NODE` instances leading to the creation of console windows when spawning console applications from a forked process.
Refs https://github.com/microsoft/vscode/issues/137481
Gist example: https://gist.github.com/deepak1556/eefed2d47fada30c15ab9077d1532d0b
Notes: fix console windows from ELECTRON_RUN_AS_NODE instances
> fix: console windows from ELECTRON_RUN_AS_NODE instances

- docs/tutorial/automated-testing.md
Adds documentation on Playwright's experimental Electron support as part of our Spectron deprecation initiative.
See https://electronjsorg-new-pr-152.herokuapp.com/docs/latest/tutorial/automated-testing/#using-playwright for website preview
cc @VerteDinde 
Notes: none
> docs: add playwright e2e testing docs

- script/release/ci-release-build.js
Fast-follow to #31741. In our release build script, we currently hard-check for one workflow job during publish. However, dynamic config and path-filtering add a mandatory additional setup job. This PR adds logic to check and account for that setup job, and return the correct API response.
_Note: These CI changes were merged into main. While the changes were also backported to other branches, they were not merged until a new nightly was successfully kicked off. This commit will be added to the existing backport PRs, hence the "no backport" label._
Notes: none
> build: account for path-filtering workflow in release-build script

- patches/chromium/desktop_media_list.patch
Fixes https://sentry.io/share/issue/23956e3126894e84a9ab73a87b22c09d/
No repro so no test case but basically there is a scenario on aura platforms where we can end up calling `OnRefreshComplete` twice as a result of our patch.  We should ensure we are only calling it once.
Notes: Fixed potential crash on Windows and Linux when using `desktopCapturer.getSources`
> fix: avoid double call in OnRefreshComplete on aura platforms

- shell/browser/ui/file_dialog_gtk.cc
In the synchronous code path, gtk_native_dialog_run() will call
gtk_native_dialog_show(). Previously this was causing an assertion to be
hit at run time.
https://gitlab.gnome.org/GNOME/gtk/-/blob/3.24.30/gtk/gtknativedialog.c#L584
fixes #31997 
Notes: Assertion failure happening in the `showSaveDialogSync()` code path has been fixed. (Fixes #31997)
> fix: gtk_native_dialog_run() calls show() internally

- patches/chromium/desktop_media_list.patch
Manual backport of #32052
Notes: Fixed potential crash on Windows and Linux when using `desktopCapturer.getSources`
> fix: avoid double call in OnRefreshComplete on aura platforms (#32052)

- README.md
- docs/tutorial/installation.md
Taobao npm mirror domain has been changed to npmmirror.com.
Ref: https://segmentfault.com/a/1190000040936469
> docs: change China mirror domain to npmmirror.com

- default_app/default_app.ts
- default_app/main.ts
- default_app/preload.ts
Let's lead by example
Notes: none
> refactor: use process type specific electron imports in default_app

- docs/api/window-open.md
- lib/browser/api/web-contents.ts
- lib/browser/guest-window-manager.ts
- shell/renderer/api/electron_api_web_frame.cc
- shell/renderer/electron_render_frame_observer.cc
- shell/renderer/electron_render_frame_observer.h
- shell/renderer/electron_renderer_client.cc
- shell/renderer/web_worker_observer.cc
- spec-main/chromium-spec.ts
- spec-main/fixtures/crash-cases/setimmediate-window-open-crash/index.html
- spec/chromium-spec.js
- spec/static/main.js
This PR fixes an issue that, child window opened with `window.open` can not override its web preferences inherited from the parent window, close https://github.com/electron/electron/issues/31949, close https://github.com/electron/electron/issues/31959.
Please check the comments in `electron_render_frame_observer.cc` for the background of the problem.
Fix PR also fixes an issue introduced by https://github.com/electron/electron/pull/31031 that, the feature string in `window.open` was treated as `windowOpenOverriddenOptions` which would override the `securityWebPreferences`. This problem was hidden by the above bug 31949 because the web preferences could not be overridden, but with the bug fixed 31031 would then allow features string to override security options.
There are also changes to …
> fix: window.open not overriding parent's webPreferences

- docs/tutorial/installation.md
The names of environment variables are case-sensitive on Linux and Mac.
Notes: none
> docs: Fix environment variable name

- docs/tutorial/introduction.md
The discord url in [the introduction page](https://www.electronjs.org/docs/latest#getting-help) ([github](https://github.com/electron/electron/blob/main/docs/tutorial/introduction.md)) is discord.gg/electron, which doesn't refer to the electron project. This commit changes the URL to discord.gg/electronjs to ensure people reading this documentation are directed to the correct discord server
Notes: none
> docs: update discord server URL in tutorial/introduction.md

- patches/chromium/fix_media_key_usage_with_globalshortcuts.patch
Closes https://github.com/electron/electron/issues/31762.
Regression caused by https://github.com/electron/electron/pull/31492. On Windows 7 & 8 / macOS 10.11/10.12, `system_media_controls_` is `nullptr` and calling methods on it crashes the process. This PR wraps problematic statements in an if-clause like upstream Chromium does.
I manually checked that MediaMetadata still works on Windows 10 and above.
cc @codebytere @lyswhut @miniak 
Notes: Fixed crash when playing media files on Windows 7/8 or macOS 10.11/10.12.
> fix: older systems crash when playing media files

- lib/browser/api/web-contents.ts
Fast follow for #32178 - ensures bluetooth devices are not returned by default, checks for a single default listener instead of none.
Notes: No Notes
> fix: check for single bluetooth listener

- patches/v8/.patches
- patches/v8/cherry-pick-418c276ef228.patch
Merged: [compiler] Don't elide ChangeTaggedToInt32->ChangeInt31ToTaggedSigned
(cherry picked from commit 4fae8b16802a416fe3aab0e7792fabe96cf1ecd8)
(cherry picked from commit f4f11c23ae2eaf9bb4525d0fac7ab842de9b0fe2)
Bug: chromium:1278387
No-Try: true
Change-Id: I9b89834c094510e064988aa534ec230309996034
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/3329665
Cr-Original-Commit-Position: refs/branch-heads/9.6@{#40}
Cr-Original-Branched-From: 0b7bda016178bf438f09b3c93da572ae3663a1f7-refs/heads/9.6.180@{#1}
Cr-Original-Branched-From: 41a5a247d9430b953e38631e88d17790306f7a4c-refs/heads/main@{#77244}
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/3335759
Commit-Queue: …
> chore: cherry-pick 418c276ef228 from v8

- docs/tutorial/quick-start.md
This pull request fixes a minor grammar issue in the quick-start guide documentation.
Notes: none
> docs: fix typo in quick-start.md

- .github/ISSUE_TEMPLATE/bug_report.yml
I noticed a mistake in the bug report template that made me do a double take and fixed it.
Changed the text of the last checkbox from "feature request" to "bug report".
Notes: none
> docs: fix typo in bug report issue template

- patches/v8/.patches
- patches/v8/merged_allow_compiled_module_invalidation_at_wasmstreaming_finish.patch
Merged: Allow compiled module invalidation at WasmStreaming::Finish()
This CL adds `can_use_compiled_module` parameter to
WasmStreaming::Finish() that is used by Chromium
https://chromium-review.googlesource.com/c/chromium/src/+/3282643
to invalidate compiled module bytes after SetCompiledModuleBytes().
(cherry picked from commit b0c6dd86bd563672dba6256f482dc5e145f094ae)
Bug: chromium:1260939
Change-Id: I28554ed79ed56349fa38517ed03785e0c8146b4d
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/3306788
Commit-Queue: Hiroshige Hayashizaki <hiroshige@chromium.org>
Reviewed-by: Andreas Haas <ahaas@chromium.org>
Cr-Commit-Position: refs/branch-heads/9.6@{#36} …
> chore: cherry-pick 04a58fedd5 from v8

- BUILD.gn
WebRTC has changed how they integrate into Chromium, they don't expose their dependencies externally anymore.
Instead, one must now go through webrtc_overrides:
https://chromium.googlesource.com/chromium/src.git/+/cbc90fd093956
We're already including webrtc_overrides as a dependency which includes the modules, so this extra deps isn't needed anymore. It didn't apply to regular builds anyway, but it caused an error when attempting component builds.
Notes: none
CC: @jkleinsc
> build: remove stale dependency for webrtc desktop capture module

- patches/chromium/.patches
- patches/chromium/cherry-pick-f781748dcb3c.patch
Show the origin of the last redirecting server in external protocol handler dialogs
External protocol handlers always show the initiating url's origin. This can be misleading if there are server side redirects.
Now we will show the origin of the last redirecting server (falling back to the request_initiator if there were no redirects / if the request goes straight to an external protocol).
Bug: 1197889
Change-Id: I3cf7ccf3a8bd79d161364680a1871d1c88bec813
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3113931
Commit-Queue: Ravjit Singh Uppal <ravjit@chromium.org>
Reviewed-by: Arthur Sonzogni <arthursonzogni@chromium.org>
Reviewed-by: Collin Baker <collinbaker@chromium.org>
Reviewed-by: Takashi Toyoshima <toyoshim@chromium.org>
Reviewed-by: Łukasz Anforowicz …
> chore: cherry-pick f781748dcb3c from chromium

- docs/tutorial/quick-start.md
there is a issue with rendering on the bottom of page https://www.electronjs.org/docs/v14-x-y/tutorial/quick-start
which looks like this
all id did is remove the spacing and it should fix the issue. sometimes having spaces before a "```" will cause issues
hope this helps!
> docs: Docs rendering issue with rendering on electronjs quick-start

- docs/api/crash-reporter.md
Adds Bugsnag to the list of 3rd party crash servers in the `crashReporter` docs ([announcement blog](https://www.bugsnag.com/blog/error-monitoring-stability-electron)).
Notes: none
> docs: add Bugsnag as a 3rd party crash server

- patches/webrtc/.patches
- patches/webrtc/merge_to_m96_sdp_reject_large_number_of_channels.patch
[merge to M96] sdp: reject large number of channels
the maximum used in practice is multiopus with
6 or 8 channels. 24 is the maximum number of channels
supported in the audio decoder.
BUG=chromium:1265806
(cherry picked from commit d58ac5adf887a2bc96d75b1c0fb6fef17889ac80)
No-Try: True
Change-Id: Iba8e3185a1f235b846fed9c154e66fb3983664ed
Reviewed-on: https://webrtc-review.googlesource.com/c/src/+/238980
Reviewed-by: Harald Alvestrand <hta@webrtc.org>
Commit-Queue: Philipp Hancke <phancke@nvidia.com>
Cr-Original-Commit-Position: refs/heads/main@{#35440}
Reviewed-on: https://webrtc-review.googlesource.com/c/src/+/239740
Commit-Queue: Mirko Bonadei <mbonadei@webrtc.org>
Reviewed-by: Taylor Brandstetter <deadbeef@webrtc.org>
Cr-Commit-Position: refs/branch-heads/4664@{#3} …
> chore: cherry-pick 809830f1b3 from webrtc

- patches/chromium/.patches
- patches/chromium/cherry-pick-6bb320d134b1.patch
M96: Storage Foundation: Share FileState ownership with I/O threads.
blink::NativeIOFile methods implementing the Storage Foundation
JavaScript API pass raw pointers to NativeIOFile::FileState instances to
their corresponding blink::NativeIOFile::Do*() methods, which rely on
that CrossThreadPersistent<NativeIOFile> arguments to keep the
underlying NativeIOFile::FileState instances alive.
CrossThreadPersistent can be used across threads to keep a garbage
collected object alive, together with any non-garbage-collected objects
that it owns. However, relying on CrossThreadPersistent existence to
access the owned objects on a different thread is not safe.
cppgc::subtle::CrossThreadPersistent (blink::CrossThreadPersistent is an
alias to that) has comments explaining that the garbage collected …
> chore: cherry-pick 6bb320d134b1 from chromium

- shell/browser/api/electron_api_app.cc
CFLocaleGetValue() returned null and crashed the process when
app.getLocaleCountryCode() was run on a CircleCI metal resource class
macOS instance with Xcode 12.5.1. This change fixes that logic and adds
further checks to make the code future-proof.
Here too people are complaining that the returned country code migth be
null: https://stackoverflow.com/questions/15202454/nslocalecountrycode-returns-nil
Notes: Fixed a crash caused by app.getLocaleCountryCode().
> fix: crash caused by `app.getLocaleCountryCode()`

- patches/chromium/.patches
- patches/chromium/m96_fileapi_move_origin_checks_in_bloburlstore_sooner.patch
M96: [FileAPI] Move origin checks in BlobURLStore sooner.
Rather than waiting to verify if a valid origin was passed in until
register/revoke time, check if the origin is valid at the time the
mojo interface is requested. This avoids the need to pass the
delegate on to BlobURLStoreImpl, further decoupling this from
BlobRegistryImpl.
(cherry picked from commit 15cfa2bed3ce9dcdd0a06d3cd3b8330e3591acdc)
Bug: 1262183
Change-Id: I4889685d03501158abfe4f87c647dc468d005f78
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3264353
Reviewed-by: Alex Moshchuk <alexmos@chromium.org>
Cr-Original-Commit-Position: refs/heads/main@{#940015}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3285385
Bot-Commit: …
> chore: cherry-pick 2b978fb482 from chromium

- docs/api/web-frame.md
The current description incorrectly states that the webFrame export represents the top frame but it actually represents the current frame.
Notes: none
> docs: correct webFrame description

- shell/browser/browser_win.cc
Closes #32141
Added quotes in command registry so that `bat` complier think it as a single argument. 
Notes: Bug fixed for registering protocol in windows which used to set invalid command if the execution path included space.
> fix: register wrong command for setAsDefaultProtocolClient

- patches/v8/.patches
- patches/v8/version_9_6_180_13_cherry-pick.patch
Version 9.6.180.13 (cherry-pick)
Merged 85ab0ad7789a7188b4c0b2be3cd3d758134c7de6
Reland "[runtime] Reset clobbered argument in DefineClass"
R=ishell@chromium.org
Change-Id: I892729eafe841e57b853f0d0a885e05847efe547
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/3289176
Cr-Commit-Position: refs/branch-heads/9.6@{#24}
Cr-Branched-From: 41a5a247d9430b953e38631e88d17790306f7a4c-refs/heads/main@{#77244}
Notes: Backported fix for CVE-2021-4078.
> chore: cherry-pick 05ccacee14 from v8. 

- patches/chromium/.patches
- patches/chromium/cherry-pick-109fde1088be.patch
MediaStreamSource: Retain observers till callbacks have been executed
(cherry picked from commit d1055cb23b15e42381bc815eeabb207ce18394d9)
Bug: chromium:1263620
Change-Id: I0655474bd3c5f4f927db1834e95b2724a20ba4e9
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3247159
Commit-Queue: Michael Lippautz <mlippautz@chromium.org>
Reviewed-by: Elad Alon <eladalon@chromium.org>
Cr-Original-Commit-Position: refs/heads/main@{#935842}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3257492
Auto-Submit: Elad Alon <eladalon@chromium.org>
Reviewed-by: Michael Lippautz <mlippautz@chromium.org>
Commit-Queue: Guido Urdaneta <guidou@chromium.org>
Cr-Commit-Position: refs/branch-heads/4638@{#1004} …
> chore: cherry-pick 109fde1088be from chromium

- patches/angle/.patches
- patches/angle/cherry-pick-2b98abd8cb6c.patch
- patches/config.json
M96: Vulkan: Fix image respecify's usage tracking
When respecifying an image due to mip level count changes, the previous
image is staged as an update to the new image.  The resource usage info
was not being transferred to the image being staged as an update,
causing it to be prematurely deleted.
Test based on one authored by sugoi@google.com.
Bug: chromium:1270658
Bug: angleproject:4835
Change-Id: I9810f8940e0107bc8a04fa3fb9c26a045c0d689c
Reviewed-on: https://chromium-review.googlesource.com/c/angle/angle/+/3318257
Reviewed-by: Lingfeng Yang <lfy@google.com>
Notes: Backported fix for CVE-2021-4099.
> chore: cherry-pick 2b98abd8cb6c from angle

- docs/breaking-changes.md
- lib/browser/api/web-contents.ts
Prepare for #29405
Notes: none
> chore: deprecate nativeWindowOpen in Electron 17

- lib/browser/api/web-contents.ts
Fixes a type error in main related to the removal of nativeWindowOpen.
Notes: none
> fix: drop nativeWindowOpen deprecation warning

- patches/node/.patches
- patches/node/fix_don_t_create_console_window_when_creating_process.patch
Since the `windowsHide` parameters still default to `false`, we need to keep the patch that disables console windows from showing up. Otherwise, for `execSync` calls, or `spawnSync` calls with `shell: true`, console windows still show up for Windows users.
This issue has been occurring since Electron 16.
Downstream issue: https://github.com/microsoft/vscode/issues/138792
Notes: Fix regression where console windows would open for execSync and some spawnSync calls for Windows users.
> fix: Don't create console window when creating process

- shell/browser/api/electron_api_web_contents.h
- spec-main/ambient.d.ts
- spec-main/api-protocol-spec.ts
- spec-main/api-web-contents-spec.ts
- spec-main/chromium-spec.ts
Small cleanup to improve type safety. Also removes a few `(global as any)` in the tests.
Notes: none
> chore: cleanup spec-main/ambient.d.ts

- npm/install.js
Closes https://github.com/electron/electron/issues/32147.
If the `npm_config_arch` environment variable is set on Mac, then use the specified architecture rather than overriding it to x64.
Currently, `npm/install.js` overrides the architecture specified in `npm_config_arch` to be `arm64` when running on Mac Rosetta. However, this can break workflows that rely on specific architectures for compatibility with native addons. Some native addons do not yet provide prebuilds for Mac arm64, requiring the use of Electron x64. By installing native addons in a Rosetta environment, the correct x64 prebuilds will be used for native addons, but `npm/install.js` as written will force an install of arm64 Electron, which is incompatible with the x64 addons.
Additionally, it's quite confusing that …
> fix: Allow x64 arch on Mac Rosetta

- docs/api/web-contents.md
Add missing `left` mode to `contents.openDevTools()` options.
Notes: none
> docs: left is a valid mode in contents.openDevTools() options

- shell/browser/api/electron_api_base_window.cc
Fix incorrect `skipTransformProcessType` option parsing added in #27200.
Notes: Fixed incorrect `skipTransformProcessType` option parsing in `win.setVisibleOnAllWorkspaces()`.
> fix: incorrect `skipTransformProcessType` option parsing in `win.setVisibleOnAllWorkspaces()`

- docs/api/browser-window.md
Updating this note to be accurate. I manually confirmed that the `will-move` event doesn't fire for `setPosition`/`setBounds`/`center` on Windows and macOS.
cc @samuelmaddock @deermichel 
Notes: none
> docs: fix note for `will-move` event

- patches/v8/.patches
- patches/v8/version_9_6_180_13_cherry-pick.patch
Version 9.6.180.13 (cherry-pick)
Merged 85ab0ad7789a7188b4c0b2be3cd3d758134c7de6
Reland "[runtime] Reset clobbered argument in DefineClass"
R=ishell@chromium.org
Change-Id: I892729eafe841e57b853f0d0a885e05847efe547
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/3289176
Cr-Commit-Position: refs/branch-heads/9.6@{#24}
Cr-Branched-From: 41a5a247d9430b953e38631e88d17790306f7a4c-refs/heads/main@{#77244}
Notes: Backported fix for CVE-2021-4078.
> chore: cherry-pick 05ccacee14 from v8.

- docs/api/session.md
You must either (1) have a case-insensitive file server (2) upload files in both casings. See <https://github.com/electron/electron/issues/22482#issuecomment-593617375>. This improves the docs to clarify that.
Notes: none
> docs: clarify case insensitive dictionary hosting

- script/git-export-patches
- script/git-import-patches
- script/lib/git.py
The scripts `git-import-patches` and `git-export-patches` work *almost* out of the box with Python3,
the only issue is that the `unicode` type was renamed to `str` there. For this reason, the interpreter version was hardcoded in #25335.
But the error with Python3 can easily be fixed by aliasing `unicode` to `str`. With that issue fixed, we can switch the shebang line back to the unversioned python command.
This saves one from having to install Python2 just for these scripts when Python3 is already installed on the system.
Notes: none
> fix: Support running git-[im,ex]port-patches with Python3 too

- patches/node/.patches
- patches/node/test_fix_test-fs-utimes_on_non-y2k38_file_systems.patch
CI is running into https://github.com/nodejs/node/issues/36591 on 13-x-y, so this PR backports the fix for that issue to 13-x-y.
Notes: none
> fix: node test failure

- patches/angle/.patches
- patches/angle/cherry-pick-891020ed64d4.patch
[M96] Ignore the pixel unpack state for compressed textures.
From OpenGL ES 3 spec: All pixel storage modes are ignored when decoding
a compressed texture image
This was causing a bad access when calling compressedTexImage3D
with GL_UNPACK_IMAGE_HEIGHT greater than the image height.
Bug: chromium:1267496
Change-Id: I9b1f4c645548af64f2695fd23262225a1ad07cd7
Reviewed-on: https://chromium-review.googlesource.com/c/angle/angle/+/3296622
Commit-Queue: Jonah Ryan-Davis <jonahr@google.com>
Reviewed-by: Geoff Lang <geofflang@chromium.org>
(cherry picked from commit 870f458f507ff7ba0f67b28a30a27955ce79dd3e)
Reviewed-on: https://chromium-review.googlesource.com/c/angle/angle/+/3309097
Reviewed-by: Jonah Ryan-Davis <jonahr@google.com> …
> chore: cherry-pick 891020ed64d4 from angle

- package.json
- yarn.lock
Fixes #32416 by pinning Electron's `colors` dependency to 1.4.0.
This isn't user-facing so there's (probably) no action needed by @electron/wg-security action needed, but CC'ing as an FYI to keep them in the loop.
Background from https://snyk.io/blog/open-source-npm-packages-colors-faker/ 
> On January 8, 2022, the open source maintainer of the wildly popular npm package colors, published colors@1.4.1 and colors@1.4.44-liberty-2 in which they intentionally introduced an offending commit that adds an infinite loop to the source code. The infinite loop is triggered and executed immediately upon initialization of the package’s source code, and would result in a Denial of Service (DoS) to any Node.js server using it.
Notes: none
> build: pin colors to v1.4.0 in package.json

- patches/chromium/chore_provide_iswebcontentscreationoverridden_with_full_params.patch
Fixes a mistake in this patch. That code path doesn't appear to be used by Electron, so it wasn't affecting things, but I was trying (mostly out of curiosity) to build a different target out of the Electron source tree and ran across a compilation error here.
Notes: none
> chore: fix incorrect usage of reference

- patches/chromium/desktop_media_list.patch
Two things:
* Make consistent usage of `refresh_thumbnails` parameter name, was `fetch_thumbnails` in one of the headers
* Add parameter to `FakeDesktopMediaList::Update` as well, so that code still compiles if you try to build a different GN target (I'm playing with building the `interactive_ui_tests` target)
cc @deepak1556 
Notes: none
> chore: update DesktopMediaList patch

- lib/browser/guest-view-manager.ts
- lib/renderer/web-view/web-view-impl.ts
- spec/static/main.js
- spec/webview-spec.js
- typings/internal-electron.d.ts
Don't break when internal undocumented `params.instanceId` is modified by application code.
Keep passing it to `will-attach-webview` in case an app reads the value.
Also remove unused `userAgentOverride` param.
Notes: The `<webview>` implementation was made more robust, it no longer breaks when `will-attach-webview` handler modifies the internal `params.instanceId`.
> fix: `will-attach-webview` handler modifying `params.instanceId` does not break `<webview>`

- patches/chromium/chore_provide_iswebcontentscreationoverridden_with_full_params.patch
Two changes:
* Add missing namespace for parameter in `headless/lib/browser/headless_web_contents_impl.cc`
* Update parameters in `chrome/browser/ui/views/hats/hats_next_web_dialog.cc`
Notes: none
> chore: update IsWebContentsCreationOverridden patch

- docs/api/dialog.md
Fixes #32390. See #19782 for context.
CC @VerteDinde (as a stakeholder via traige), @codebytere (as a stakeholder via NativeImage and Dialog work), and @electron/wg-releases 
Notes: Fixed allowed types in MessageBoxOpitons.icon documentation.
> docs: explicitly allow string for MessageBoxOptions.icon

- shell/browser/api/electron_api_web_frame_main.cc
- shell/renderer/api/electron_api_ipc_renderer.cc
- spec-main/api-ipc-spec.ts
Closes https://github.com/electron/electron/issues/32427.
Fixes an issue where attempts to use `ipcRenderer.postMessage` without the ostensibly optional `transfer` argument would throw `TypeError: Invalid value for transfer`. This was happening because `absl::optional` value checks consider `undefined` a value, so we were incorrectly trying to [convert `undefined` into an array of transferrable objects](https://github.com/electron/electron/blob/b4f2bdaaefcdea4e62d0f0c3f6cfdea517a70936/shell/renderer/api/electron_api_ipc_renderer.cc#L150-L153). This is fixed by checking explicitly for `transfer` being `undefined`.
Notes: Fixed an issue where `ipcRenderer.postMessage` would throw errors when the `transfer` argument was not passed.
> fix: optional postMessage transfer arg

- docs/api/browser-window.md
- docs/api/environment-variables.md
Fixes a handful of relative links in the docs which are broken. Appears there's some edge cases the linter for broken relative links isn't catching. For example, the setting background color link broke in 54b44584fa9a1f5a142e8eb6b446084e962cec75 and the linter doesn't catch it.
My VS Code extension flagged them as broken, so at some point I can look at the difference there and try to update the linter to catch these cases.
cc @erickzhao 
Notes: none
> docs: fix anchors for broken relative links

- shell/browser/ui/x/window_state_watcher.cc
- shell/browser/ui/x/window_state_watcher.h
Closes https://github.com/electron/electron/issues/28699.
Fixes an issue where the 'maximize' and 'unmaximize' events didn't fire properly on linux.
This was happening as a result of changes made in https://github.com/electron/electron/pull/27280 to address CL:2577887 and CL:2585750. In the resultant change, we assigned `was_maximized_` at the top of `WindowStateWatcher::OnEvent` - given that this was being called in the function after the event had taken place, the previous value would match the current value using this logic and thus it would _never_ be the case that `is_minimized != was_minimized_` or `is_maximized != was_maximized_` and thus the events would never fire.
Fix this by assigning `was_minimized_` and `was_maximized_` in places that properly allow the change to be …
> fix: maximize/unmaximize firing on linux

- shell/browser/native_window_views.cc
- spec-main/api-browser-window-spec.ts
Fixes #32350.
Test is currently disabled on Linux until #28699 is fixed.
cc @ckerr 
Notes: Fixed minimized BrowserWindow being restored by BrowserWindow.unmaximize()
> fix: check for maximized window before unmaximizing

- docs/api/web-contents.md
Fixed some odd language in `web-contents.md`. The line was introduced in [the original "add will-redirect" PR](https://github.com/electron/electron/pull/13866/files#diff-18ed6a5b5a9084c976509502962b7f05989a8bd13a2ba3dc02868056938c03b6R194).
Notes: none
> docs: Clarify `will-redirect` event

- shell/browser/api/electron_api_browser_window.cc
Closes https://github.com/electron/electron/issues/32007.
Fixes an issue where if `backgroundColor` was set to `undefined`, vibrancy failed to work and the `backgroundColor` would show up as white. This was happening because we were converting the background color from an arbitrary `v8::Value`, when we only accept strings. As a result, `undefined` would return `true` from the conversion instead of false as it should. Fix this by expecting the more specific type.
Notes: Fixed an issue where if `backgroundColor` was set to `undefined`, vibrancy failed to work and the `backgroundColor` would show up as white.
> fix: undefined backgroundColor

- script/lib/config.py
\#29719 introduced the crashpad\_handler binary, but did not add it to the
stripped binary list, so it was being shipped with full symbols, to the tune of
15MB. Whoops.
Notes: Strip symbols from crashpad_handler binary on Linux, reducing bundle size.
> fix: strip crashpad_handler binary

- patches/angle/.patches
- patches/angle/cherry-pick-cc44ae61f37b.patch
M96: D3D11: Fix OOB access in vertex conversion code.
This could happen when using certain combinations of stride and
offset. Fix the issue by using checked math.
Bug: chromium:1274499
Change-Id: I3e286a30fe128ab4684ee5e172dc9e3345e3b2f4
Reviewed-on: https://chromium-review.googlesource.com/c/angle/angle/+/3365657
Notes: Backported fix for CVE-2021-4066.
> chore: cherry-pick cc44ae61f37b from angle

- .circleci/build_config.yml
https://chromium-review.googlesource.com/c/chromium/tools/depot_tools/+/3400398 broke our linux builds because it requires python 3.7 or higher and our docker images have python 3.6.  I've tried updating our docker images to use python 3.7, but using Ubuntu 18.04 with python 3.7 is problematic since 3.6 is already installed. Updating our docker images to Ubuntu 20.04 causes a docker build issue with snapcraft.  In the long term, I'm sure we can update our docker images, but until we do that, this will get linux building again.
Also, the gist of this change is to change the [autoninja ](https://source.chromium.org/chromium/chromium/tools/depot_tools/+/main:autoninja?q=autoninja&ss=chromium)shell script to not invoke ninjalog_uploader_wrapper.py, which if we call it ends up being a noop, so …
> ci: call autoninja without ninjalog_uploader_wrapper.py

- electron_paks.gni
Add strings that were missing in resource pak bundles, resulting in crashes
when starting VoiceOver on macOS (and probably other problems, too).
These were split out in
https://chromium-review.googlesource.com/c/chromium/src/+/3323855, but we
didn't notice straight away.
Notes: Fixed a crash when starting VoiceOver on macOS.
> fix: bundle a11y strings in resources

- docs/api/incoming-message.md
- lib/browser/api/net.ts
- shell/browser/api/electron_api_url_loader.cc
- spec-main/api-net-spec.ts
The goal of this change is to add a `rawHeaders` to `IncomingMessage`, similar to how Node's `http.IncomingMessage` [has](https://nodejs.org/api/http.html#messagerawheaders) a `rawHeaders`. Related to #31531. (Note: link to Node docs may not scroll to the right spot)
I am initially opening this PR as a draft in order to get review and approval.
cc @electron/wg-api 
Notes: Added rawHeaders to IncomingMessage.
> feat: add rawHeaders to IncomingMessage

- patches/chromium/.patches
- patches/chromium/cherry-pick-c5571653d932.patch
Quota: Use Threadsafe Pressure Callback.
Fixes UAF by removing use of raw ptr to StorageNotificationService.
Instead, the service's interface exposes a method to create a
thread-safe callback to pass to the quota manager instead.
This change also changes the parameter type for the call chain from
url::Origin to blink::StorageKey to match the type Quota is keyed on.
Bug:1275020
(cherry picked from commit e304c0373f9cc4a65d39d7094e4897627e83390e)
Change-Id: Icc696d22fa41324e7a6c056599db635bb5de6291
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3347939
Reviewed-by: Joshua Bell <jsbell@chromium.org>
Reviewed-by: Nasko Oskov <nasko@chromium.org>
Commit-Queue: Jarryd Goodman <jarrydg@chromium.org>
Cr-Original-Commit-Position: refs/heads/main@{#953375}
Reviewed-on: …
> chore: cherry-pick c5571653d932 from chromium

- shell/browser/native_window_mac.mm
- shell/browser/ui/cocoa/electron_ns_window.mm
- spec-main/api-browser-window-spec.ts
Close https://github.com/electron/electron/issues/28686.
By default "Close Window" is always disabled when window has no title, this PR makes it possible to close such windows. This fixes the problem that windows with `roundedCorners: false` was not closable, because the option is implemented by removing window's title.
Also note that this PR removes the use of `NSWindowStyleMaskFullSizeContentView` style, it is actually no-op if the window has no title and we don't really need it to implement `roundedCorners: false`.
Notes: Fix windows with `roundedCorners: false` unable to be closed.
> fix: make windows without rounded corners closable

- shell/browser/web_view_guest_delegate.cc
- #20314 included cadf148cea5c78c7f44fe62db2c74f072252b55f, which incorrectly migrated `content::ZoomLevelToZoomFactor` to `blink::PageZoomFactorToZoomLevel` in `shell/browser/web_view_guest_delegate.cc` instead of migrating to the correct `blink::PageZoomLevelToZoomFactor`.  This caused the crash detailed in #30028.
- Fixes #30028
Notes: Fixed crash when calling `webContents.setZoomFactor(1.0)`.
> fix: webContents.setZoomFactor crash

- .circleci/build_config.yml
Docs only PRs were timing out (eg see https://app.circleci.com/pipelines/github/electron/electron/48723/workflows/500d13bc-6323-46bf-9b2f-442635beed07/jobs/1108175) because they were not using the proper source cache.  This PR updates the ts-compile-doc-change job to properly use the cached source.
Notes: none
> ci: update ts-compile-doc-change to properly use src cache

- docs/development/build-instructions-linux.md
Closes #27704 
[Chromium script](https://chromium.googlesource.com/chromium/src/+/main/build/install-build-deps.sh#527) to install build dependencies seems to suggest that `libgnome-keyring-dev` isn't needed on Ubuntu 20.
And the tests run fine with `python3-dbusmock`
cc: @ckerr @dsanders11 @codebytere 
Notes: none
> docs: separate the dependency list for ubuntu

- docs/api/web-request.md
There are a property  **uploadData[]** in the listener of [webRequest.onBeforeRequest([filter, ]listener)](https://www.electronjs.org/docs/latest/api/web-request#webrequestonbeforerequestfilter-listener).  In addition, the listener is also in [webRequest.onBeforeSendHeaders([filter, ]listener)](https://www.electronjs.org/docs/latest/api/web-request#webrequestonbeforesendheadersfilter-listener), they are also the same Function (except for requestHeaders, which is not in onBeforeRequest's listener).
After testing, I found the **uploadData** is in the listener of [webRequest.onBeforeSendHeaders([filter, ]listener)](https://www.electronjs.org/docs/latest/api/web-request#webrequestonbeforesendheadersfilter-listener) if it's provided in request. So I add it into the document.
Notes: none
> fix: uploadData is in webRequest.onBeforeSendHeaders but not shown in api document

- shell/browser/native_window.cc
Fixes #32608.
https://github.com/electron/electron/pull/31982 changed this condition from `|`
to `||`, which broke because `||` short-circuits but `|` does not.
Notes: Fixed `maxWidth` not working in BrowserWindow constructor options.
> fix: maxWidth not being respected

- docs/api/context-bridge.md
From my testing it doesn't remove Promises in nested objects,
also according to the test suite it does not:
https://github.com/electron/electron/blob/80577a4f08824c031ad020b8f4e3c5975ff8081a/spec-main/api-context-bridge-spec.ts#L693
Also improve Error description.
Notes: Updated context bridge docs about Promises and Errors.
> docs: update context bridge docs about Promises and Errors

- shell/browser/api/electron_api_browser_window.cc
- shell/browser/api/electron_api_web_contents.cc
- shell/browser/api/electron_api_web_contents.h
- spec-main/api-browser-window-spec.ts
- spec-main/fixtures/apps/background-color-transparent/index.html
- spec-main/fixtures/apps/background-color-transparent/main.js
- spec-main/fixtures/apps/background-color-transparent/package.json
- spec-main/fixtures/apps/background-color-transparent/renderer.js
- spec-main/package.json
- spec-main/yarn.lock
Closes https://github.com/electron/electron/issues/31862.
Background colors are a [bit of a mess](https://docs.google.com/document/d/13uQA6G06dCaSd1FvdJ2amzPKF3wKZOVZL6wdAooHFow) right now in Chromium. They're working on cleaning things up, but in the process have made it harder to determine background color precedence as well as how we can override certain defaults. If we in Electron set `const mainWindow = new BrowserWindow({ frame: false, transparent: true, vibrancy:'under-window' })` and then set the CSS `background` to `green` the initial [content background color](https://source.chromium.org/chromium/chromium/src/+/main:content/browser/web_contents/web_contents_impl.cc;l=5766-5771?q=SetContentBackgroundColor&ss=chromium) gets set to `green` and at no point after that can be set back …
> fix: css transparent background being lost

- .circleci/build_config.yml
This reverts commit 8803e7f02026fac62985eaf9745fd9ae0760cd18.
This PR temporarily reverts the update to Ubuntu 20 for our docker images because there are issues with the gclient cache that are blocking PRs.  There will be a followup PR to re-enable Ubuntu 20 once all the caching issues can be resolved. 
Notes: none
> ci: revert update to Ubuntu 20.04 docker image

- patches/chromium/.patches
- patches/chromium/cherry-pick-f5101995acd2.patch
fix draggable regions not updating without layout
This fixes draggable regions not being updated when styles change, but there is
no layout as a result of the style change. Some changes to styles can cause a
change in draggable regions without causing a layout (e.g. applying the
`-webkit-app-region: drag` style to an element without changing its size).
Bug: 1051562
Change-Id: Ifdf835be9e6c762131529b4309c6579366b80d6d
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3416279
Reviewed-by: Stefan Zager <szager@chromium.org>
Commit-Queue: Jeremy Apthorp <jeremya@chromium.org>
Cr-Commit-Position: refs/heads/main@{#963777}
Notes: Fixed draggable regions not updating unless a relayout occurs.
> chore: cherry-pick f5101995acd2 from chromium

- docs/api/dock.md
- docs/api/menu-item.md
- docs/development/build-instructions-gn.md
For the people who only know English, it's very difficult to understand the Latin phrase "Nota Bene". Just to call the reader's attention to a particularly important piece of information, I think we can use "Note" which does the same job for us. It really helps in not distracting the readers flow from the document :)  
**Release Notes**
Notes: none
> docs: Remove the latin phrase "Nota Bene"  from docs

- script/lib/config.py
* Fix missing comma
I believe this is a minimal change
Notes: none.
> fix: Missing comma in config.py

- default_app/main.ts
- lib/browser/api/auto-updater/squirrel-update-win.ts
- lib/browser/ipc-main-impl.ts
- package.json
- spec-main/api-context-bridge-spec.ts
- spec-main/api-ipc-spec.ts
- spec-main/api-web-contents-spec.ts
- spec-main/node-spec.ts
- tsconfig.spec.json
- typings/internal-ambient.d.ts
- yarn.lock
It should be slightly faster due to https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-5.html#faster-load-time-with-realpathsyncnative. `ResizeObserver` is now declared in lib.dom.d.ts
Notes: none
> chore: update to latest TypeScript

- patches/chromium/.patches
- patches/chromium/fix_wayland_bugs_related_to_bad_versioning.patch
Chromium tries to bind to the newest version of some wayland interfaces. This causes issues when it doesn't actually support the version.
This patch ensures that only supported versions are bound to.
Fixes #32487
Backport of #32603
Notes: none.
> fix: ensure that chromium binds to wayland interface versions it supports

- shell/browser/serial/serial_chooser_context.cc
- shell/browser/serial/serial_chooser_context.h
Due to logic copied from upstream chromium, not all serial devices are passed along to the handler specified via `session.setDevicePermissionHandler`.  Given that we are giving control to the developer as to which ports are being exposed, we can probably skip this check.
- Resolves #32505
Notes: fixed issue where not all serial devices were exposed to the handler specified by `session.setDevicePermissionHandler`
> fix: expose all serial devices to setDevicePermissionHandler

- shell/browser/native_window_views.cc
- shell/browser/native_window_views_win.cc
- spec-main/api-browser-window-spec.ts
Closes https://github.com/electron/electron/issues/32633.
This PR fixes an issue with transparent windows failing to fire the `maximize` and `unmaximize` events on Windows.
We've made a few fixes to transparent window size events on Windows of late, including https://github.com/electron/electron/pull/28207 and https://github.com/electron/electron/pull/26586. As of now, we set transparent window to maximized by calling [`SetBounds`](https://github.com/electron/electron/blob/a2d993c9b48809128ca0d8a6c61f4c5ff7c8e385/shell/browser/native_window_views_win.cc#L189), which means that `NativeWindowViews::HandleSizeEvent` is not triggered with `SIZE_MAXIMIZED` as it should be. This also presents an issue with unmaximization for similar reasons, and caused the `maximize` and `unmaximize` events not …
> fix: transparent window max/unmax event firing

- docs/api/clipboard.md
Looks like just a typo, missing the final `>` of the HTML tag in the example.
cc @codebytere (examples originally added in #20224)
Notes: none
> docs: fix missing tag end in clipboard example

- docs/api/web-contents.md
- shell/browser/api/electron_api_web_contents.cc
- shell/browser/api/electron_api_web_contents.h
- spec-main/api-web-contents-spec.ts
Adds 'focus' and 'blur' events to `WebContents`.
resolves #22201
cc @electron/wg-api 
Notes: Added 'focus' and 'blur' events to `WebContents`
> feat: add focus and blur events for WebContents

- .circleci/build_config.yml
- #32656 was needed because the gclient cache was not being properly keyed which meant the cache was never restored.  Since the cache was not restored, there was a step called "Fix Sync" that was failing with the following error:
```
cd src/third_party/angle
git remote set-url origin https://chromium.googlesource.com/angle/angle.git
git fetch
error: object directory /home/builduser/.gclient-cache/chromium.googlesource.com-angle-angle/objects does not exist; check .git/objects/info/alternates
remote: Finding sources: 100% (193770/193770)           ects: 1           
error: object directory /home/builduser/.gclient-cache/chromium.googlesource.com-angle-angle/objects does not exist; check .git/objects/info/alternates
remote: Total 193770 (delta 129285), reused 193125 (delta 129285) …
```
> ci: fixup gclient cache on ubuntu 20

- patches/chromium/printing.patch
Closes https://github.com/electron/electron/issues/32684.
This PR fixes a crash that occurred when a user attempted to print a document either with `window.print()`, the print button in the PDF viewer, or with `BrowserWindow.webContents()` and clicked cancel in the resulting print dialog. This was introduced in https://github.com/electron/electron/pull/32030/commits/e693ad9f50ff9228fa3b5c228851fb01b3f5ff5a as a result of an attempt to handle upstream changed in CL:3305095. This added a new function `OnUserInitCancelled` to the `PrintJob` `Observer` with the intent that when a job was cancelled it would broadcast to an observed function `OnUserInitCancelled()` in `PrintViewManagerBase`. However, there is one critical problem with that - that `print_job_` does not exist that that point and …
> fix: crash on printer dialog cancellation

- shell/browser/native_window_views.cc
Closes https://github.com/electron/electron/issues/30760.
Fixes an issue where frameless windows would show chrome during the loading process when they shouldn't. Cleans up the logic for `SetWindowLong` `GWL_STYLE` application to ensure that `WS_CAPTION` is removed when the window is frameless and not just when `thickFrame` is false.
Notes: Fixes an issue where frameless windows on Windows would incorrectly show a small frame during the loading process.
> fix: some frameless windows showing a frame on Windows

- shell/browser/ui/win/electron_desktop_window_tree_host_win.cc
- shell/browser/ui/win/electron_desktop_window_tree_host_win.h
This adds a patch to Chromium that marks [non-client](https://docs.microsoft.com/en-us/windows/win32/gdi/nonclient-area) mouse hover events as handled so they don't get redispatched to the default OS event handler (which is currently immediately "stealing" the mouse every time it moves).
Currently, on Windows with WCO-enabled windows, Win API mouse messages first find their way to `LegacyRenderWidgetHostHWND::OnMouseRange` which, for non-client mouse moved events, will both handle the event normally (through `HWNDMessageHandler::HandleMouseMessage` which eventually bubbles down to `Widget::OnMouseEvent`) as well as redispatch the original message back to the OS default window procedure (via the Win API `DefWndProc`) on the real window handle, depending on some conditions.
Calling …
> fix: WCO window hover on window controls on Windows

- BUILD.gn
- shell/common/api/electron_api_native_image_mac.mm
Closes https://github.com/electron/electron/issues/32455.
Updates code inside `NativeImage::CreateThumbnailFromPath` to conform to new `QuickLookThumbnailing` framework approach outlined by apple [here](https://developer.apple.com/documentation/quicklookthumbnailing?language=objc).
Notes: none
> refactor: use QuickLookThumbnailing where applicable

- DEPS
- patches/chromium/can_create_window.patch
- patches/chromium/disable_hidden.patch
- patches/chromium/printing.patch
- patches/chromium/revert_do_not_display_grammar_error_if_there_it_overlaps_with_spell.patch
- patches/chromium/webview_fullscreen.patch
- patches/v8/fix_disable_implies_dcheck_for_node_stream_array_buffers.patch
Updating Chromium to 96.0.4664.174.
See [all changes in 96.0.4664.110..96.0.4664.174](https://chromium.googlesource.com/chromium/src/+log/96.0.4664.110..96.0.4664.174?n=10000&pretty=fuller)
Notes: Updated Chromium to 96.0.4664.174.
> chore: bump chromium to 96.0.4664.174 (16-x-y)

- build/args/all.gn
This PR adds a new node version number for Electron 19.
_NOTE: Please hold until the 18 branch has been cut and the node PR merged: https://github.com/nodejs/node/pull/41814_
Notes: none
> chore: bump NMV for Electron 19

- script/lib/util.py
Running a build on Cygwin or MSYS2 otherwise fails.
Notes: None
> build: Support cygwin in script/lib/util.py

- spec-main/api-browser-window-spec.ts
While triaging https://github.com/electron/electron/issues/32696 this morning i discovered that we don't explicitly test all `saveType` options in our `webContents.savePage` tests. This corrects that.
Notes: none.
> test: improve `webContents.savePage()` specs

- docs/api/web-contents.md
- shell/browser/api/electron_api_web_contents.cc
- spec-main/api-browser-window-spec.ts
Closes https://github.com/electron/electron/issues/32696.
Fixes an issue where `webContents.savePage` failed consistently on Windows and Linux and sporadically on macOS when passing a relative path instead of an absolute one. Our version of `savePage` plumbs down to [`content/browser/web_contents/web_contents_impl.cc`](https://source.chromium.org/chromium/chromium/src/+/main:content/browser/web_contents/web_contents_impl.cc;l=4863-4865;drc=cba00174ca338153b9c4f0c31ddbabaac7dd38c7;bpv=1;bpt=1?q=savepage%20webcontents%20-f:out%20&ss=chromium%2Fchromium%2Fsrc), which, per comment:
> Used in automated testing to bypass prompting the user for file names. Instead, the names and paths are hard coded rather than running them through file name sanitation and extension / mime checking.
As a result, …
> fix: savePage throw on relative paths

- patches/chromium/.patches
- patches/chromium/cherry-pick-1284367.patch
Subject: Use RFH global id to ensure the RFH is valid.
Observing via RenderFrameDeleted and RenderFrameHostChanged is not
sufficient for validating the RFH is still valid, because the frames
can belong to inner WebContents. As suggested in
https://crrev.com/c/2449389, storing a GlobalFrameRoutingId is the
preferred method of keeping a reference to a RFH.
Bug: 1284367
Notes: Security: backported fix for chromium:1284367.
> chore: cherry-pick fix for 1284367 from chromium

- patches/v8/.patches
- patches/v8/cherry-pick-27bc67f761e6.patch
Merged: [maps] Lock map_updater_access in CompleteInobjectSlackTracking
CompleteInobjectSlackTracking potentially shrinks multiple maps, and
the relation between these maps should be preserved in a concurrent
environment. Thus it is not enough to make each modification
atomically, but all related map modifications must be within a
critical section.
We do this by locking the map_updater_access mutex
CompleteInobjectSlackTracking, and hence moving the function to the
MapUpdater class.
(cherry picked from commit 4b8d04897cba70cac45eea33d78fa2354dfe2bd7)
No-Try: true
No-Treechecks: true
Bug: chromium:1274445,v8:7990
Change-Id: If99bb8b55e03180128ee397d845fa4c269c4241e
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/3379819
Reviewed-by: Igor Sheludko …
> chore: cherry-pick 27bc67f761e6 from v8

- BUILD.gn
The `dist.zip` generated by the `electron_dist_zip` action was not getting
updated when changes were being made to the dependencies, like the
source files. It turns out, we were using `data_deps` for the dependencies
instead of `deps`. Here is the difference:
`data_deps`: things needed to ultimately run the thing built by a target
`deps`: things needed to build the target
So the difference in treatment of both sets of dependencies is actually
intentional.
cc @nornagon @dsanders11 
Notes: none
> build: rebuild the `dist_zip`s when the deps get modified

- patches/chromium/.patches
- patches/chromium/merge_m-97_serial_check_for_detached_buffers_when_writing.patch
Subject: serial: Check for detached buffers when writing
This change adds check in SerialPortUnderlyingSink::WriteData() to
ensure that the V8BufferSource being written to the Mojo data pipe has
not been detached since it was passed to the WritableStream.
(cherry picked from commit 7ce1516b49e86430c9216d0df8e23a325104a8c5)
Bug: 1267627
Change-Id: I63d48584eb0be1c1d87c27115900aa5c17931fcf
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3269348
Commit-Queue: Reilly Grant <reillyg@chromium.org>
Auto-Submit: Reilly Grant <reillyg@chromium.org>
Reviewed-by: Hongchan Choi <hongchan@chromium.org>
Cr-Original-Commit-Position: refs/heads/main@{#940631}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3279207
Bot-Commit: Rubber Stamper …
> chore: cherry-pick 55f6cb37 from chromium 

- patches/angle/.patches
- patches/angle/m96_validate_samplerformat.patch
Subject: M96: Validate SamplerFormat
We weren't validating sampler formats in ProgramExecutable validation.
Bug: chromium:1273661
Change-Id: Ida0c67c0c7169ea3f47ceb2d433bee17012a7e5e
Reviewed-on: https://chromium-review.googlesource.com/c/angle/angle/+/3312717
Reviewed-by: Charlie Lao <cclao@google.com>
Commit-Queue: Lingfeng Yang <lfy@google.com>
(cherry picked from commit 6d3435fddd7abd67699c3f020d6b4fa21445d9b3)
Reviewed-on: https://chromium-review.googlesource.com/c/angle/angle/+/3335173
Notes: Security: backported fix for chromium:1273661
> chore: cherry-pick ce8b70863 from angle

- patches/chromium/.patches
- patches/chromium/fire_iframe_onload_for_cross-origin-initiated_same-document.patch
Subject: Fire iframe onload for cross-origin-initiated same-document navigations
A cross-origin initiator can check whether or not onload fired to
guess the url of a target frame. Always firing onload makes it
appear to be a cross-document navigation, even when it wasn't.
Bug: 1248444
Change-Id: I79249cb441f61ac6cab65ab9e5dd4a44b291bc4a
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3193885
Commit-Queue: Nate Chapin <japhet@chromium.org>
Reviewed-by: Rakina Zata Amni <rakina@chromium.org>
Cr-Commit-Position: refs/heads/main@{#931681}
Notes: Security: backported fix for chromium:1248444
> chore: cherry-pick 5f8ddef5a6 from chromium

- shell/browser/api/electron_api_web_contents.cc
- shell/browser/api/electron_api_web_contents.h
- shell/browser/web_contents_permission_helper.cc
- shell/browser/web_contents_permission_helper.h
Fixes an issue where the [Pointer Lock API](https://developer.mozilla.org/en-US/docs/Web/API/Pointer_Lock_API) could be properly engaged but not disengaged. We were not properly routing requests through the `ExclusiveAccessManager` nor handling special override keys for exclusive access in `WebContents::PreHandleKeyboardEvent`. As of this change, [this demo](https://mdn.github.io/dom-examples/pointer-lock/) works identically to Chrome.
cc @nornagon @jkleinsc 
Notes: Fixed an issue where Pointer Lock behavior could not be properly exited.
> fix: pointer lock escape handling

- spec/chromium-spec.js
Disable a test added in https://github.com/electron/electron/pull/32057 that, is very likely responsible for causing hanging on exit sometimes when running tests on Windows.
Notes: none
> test: disable the test that makes spec runner hang on exit

- patches/chromium/.patches
- patches/chromium/cherry-pick-9db9911e1242.patch
Keep a set of previously dropped peers
Test that a given node name hasn't been seen before.
A side effect of this fix is that re-invitation will not work anymore.
BUG=chromium:1274113
Change-Id: Ibdc50291efa1f6298614b163b544ad980615a981
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3341553
Reviewed-by: Ken Rockot <rockot@google.com>
Commit-Queue: Stephen Röttger <sroettger@google.com>
Cr-Commit-Position: refs/heads/main@{#956441}
Notes: Security: backported fix for chromium:1274113
> chore: cherry-pick 9db9911e1242 from chromium

- patches/chromium/.patches
- patches/chromium/handle_potentiallydanglingmarkup_for_cssimagevalue.patch
Subject: Handle PotentiallyDanglingMarkup() for CSSImageValue
The flag was lost in the KURL -> String -> KURL conversions. Store the
flag on CSSImageValue and always re-resolve from the original relative
url before fetching when that flag is set. The blocking happens in
BaseFetchContext::CanRequestInternal().
Bug: 1039885
Change-Id: Ia5777739a0ee0bee591163873926d19e0ea014bf
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3226142
Reviewed-by: Anders Hartvoll Ruud <andruud@chromium.org>
Reviewed-by: Mike West <mkwst@chromium.org>
Commit-Queue: Rune Lillesveen <futhark@chromium.org>
Cr-Commit-Position: refs/heads/main@{#932004}
Notes: Security: backported fix for chromium:1039885
> chore: cherry-pick 349a35b19 from chromium

- patches/angle/.patches
- patches/angle/vangle_change_the_default_vulkan_device_choose_logic.patch
- patches/chromium/.patches
- patches/chromium/do_not_select_vulkan_device_based_on_the_passed_in_gpu_info_on_linux.patch
Subject: Do not select vulkan device based on the passed in gpu_info on Linux
On linux dual GPU setup, we cannot detect the active GPU correctly.
It causes problems for GL and Vulkan interop. So we would to use
ANGLE vulkan backend when vulkan is enabled. So we can choose the same
GPU for both vulkan and GL. So for this CL, we will not create vulkan
device based on passed in gpu_info anymore, instead GPU device will be
selected by the order of
(discrete GPU > integrated GPU > virtual GPU > CPU simulated GPU).
And we will use the same logic in ANGLE vulkan backend as well.
Bug: 1260869
Change-Id: I6fb79a4e6ce1710e4809cd63a0f7738955a8e2d2
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3242785
Commit-Queue: Peng Huang <penghuang@chromium.org>
Commit-Queue: Vasiliy …
> chore: cherry-pick efdfe711dc5 from chromium

- patches/chromium/.patches
- patches/chromium/cherry-pick-1283371.patch
Subject: Fix lifetime bug in PrefetchURLLoader
PrefetchURLLoader is now owned by PrefetchURLLoaderService, which is no
longer refcounted. This makes the lifetime much easier to reason about.
Bug: 1283371
Notes: Security: backported fix for chromium:1283371.
> chore: cherry-pick fix for 1283371 from chromium

- patches/v8/.patches
- patches/v8/regexp_fix_uaf_in_regexpmacroassembler.patch
[regexp] Fix UAF in RegExpMacroAssembler
.. by turning `masm_` into a unique_ptr s.t. it's freed after the
NoRootArrayScope which references it.
Fixed: [chromium:1252620](https://bugs.chromium.org/p/chromium/issues/detail?id=1252620)
Change-Id: [I24580c5a96d76a973b2b083e7a76b95f93bb6068](https://chromium-review.googlesource.com/q/I24580c5a96d76a973b2b083e7a76b95f93bb6068)
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/3185459
Commit-Queue: Jakob Gruber <[jgruber@chromium.org](mailto:jgruber@chromium.org)>
Commit-Queue: Patrick Thier <[pthier@chromium.org](mailto:pthier@chromium.org)>
Auto-Submit: Jakob Gruber <[jgruber@chromium.org](mailto:jgruber@chromium.org)>
Reviewed-by: Patrick Thier <[pthier@chromium.org](mailto:pthier@chromium.org)> …
> chore: cherry-pick c1700c5 from v8

- .circleci/build_config.yml
- build/args/all.gn
- shell/app/electron_main_delegate.cc
Fixes an issue with publish jobs on main - the debug header for stack_trace.h seems to be included in the test build, but not the release build. Likely, this header was originally included via another header, and removed during Chromium upstream header #include cleanup.
This PR explicitly adds the header to the file.
Notes: none
> build: add stack_trace.h to main delegate

- patches/config.json
- patches/devtools_frontend/.patches
- patches/devtools_frontend/revert_include_group_children_if_group_parent_header_is_filtered.patch
Backport of https://chromium.googlesource.com/devtools/devtools-frontend/+/5841c2bf19dac6a6b764d8a4dff3db3e3bd084fb
Upstream Chromium bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1263070
Downstream VS Code bug: https://github.com/microsoft/vscode/issues/142611
Notes: Backport fix from https://crbug.com/1263070 for filtering in devtools console .
> chore: cherry-pick 5841c2bf1 from devtools-frontend

- lib/browser/guest-view-manager.ts
- lib/renderer/web-view/web-view-impl.ts
- spec/static/main.js
- spec/webview-spec.js
- typings/internal-electron.d.ts
Backport of #32386
Notes: The `<webview>` implementation was made more robust, it no longer breaks when `will-attach-webview` handler modifies the internal `params.instanceId`.
> fix: will-attach-webview handler modifying params.instanceId does not break <webview>

- patches/chromium/.patches
- patches/chromium/cherry-pick-1283375.patch
Subject: Ensure valid print render host before proceeding to print.
Bug: 1283375
Notes: Security: backported fix for chromium:1283375
> chore: cherry-pick fix for 1283375 from chromium

- docs/development/pull-requests.md
This relative link outside the `/docs` directory is broken on the website. This fixes it to use the GitHub URL directly.
Notes: none
> docs: fix relative link in developer documentation

- patches/chromium/.patches
- patches/chromium/cherry-pick-1283198.patch
Subject: CHECK page on thumbnail requests
Elevate DCHECK to CHECK.
Fixed: 1283198
Notes: Security: backported fix for chromium:1283198.
> chore: cherry-pick fix for 1283198 from chromium

- patches/config.json
- patches/devtools_frontend/.patches
- patches/devtools_frontend/fix_expose_globals_to_allow_patching_devtools_dock.patch
Closes https://github.com/electron/electron/issues/32702.
Electron calls into `UI.DockController.instance().setDockSide(side)` in order to allow users to set the devtools dock position via `webContents.openDevTools({ mode })`. In [this DevTools CL](https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/3310870) the globals which we used to enable this were removed, and so we need to re-expose them to fix this broken functionality. We should look to upstream a more durable approach to allowing us to do this.
Tested by adding `mainWindow.webContents.openDevTools({ mode: 'left' })` to the default stock Fiddle and observing that it no longer errors and the devtools docks appropriately to the left-hand side.
Notes: Fixed an issue where `webContents.openDevTools({ mode })` did …
> fix: `webContents.openDevTools({mode})` not working

- patches/chromium/.patches
- patches/chromium/cherry-pick-0081bb347e67.patch
gamepad: Return an invalid handle after ReportBadMessage
Bug: 1285449
Change-Id: I746c539577f7bdf69cbe4212ac380e0c92a5c771
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3373944
Auto-Submit: Matt Reynolds <mattreynolds@chromium.org>
Reviewed-by: Reilly Grant <reillyg@chromium.org>
Commit-Queue: Reilly Grant <reillyg@chromium.org>
Cr-Commit-Position: refs/heads/main@{#961125}
Notes: Backported fix for CVE-2022-0610.
> chore: cherry-pick 0081bb347e67 from chromium

- patches/angle/.patches
- patches/angle/m98_vulkan_fix_vkcmdresolveimage_extents.patch
- patches/angle/m98_vulkan_fix_vkcmdresolveimage_offsets.patch
M98: Vulkan: Fix vkCmdResolveImage offsets
glBlitFramebuffer takes identical regions for src and dst when
resolving.  vkCmdResolveImage should use the clipped area instead of
using the actual offsets passed to this function.
Bug: [chromium:1292537](https://bugs.chromium.org/p/chromium/issues/detail?id=1292537)
Change-Id: [If283a8acbca3249b771facbc30bd9f8080a03656](https://chromium-review.googlesource.com/q/If283a8acbca3249b771facbc30bd9f8080a03656)
Reviewed-on: https://chromium-review.googlesource.com/c/angle/angle/+/3457023
Reviewed-by: Tim Van Patten <[timvp@google.com](mailto:timvp@google.com)>
====================
M98: Vulkan: Fix vkCmdResolveImage extents
The source framebuffer's extents were accidentally used instead of the
blit area extents.
Bug: …
> chore: cherry-pick b790affce3 and 9c1efd3def from angle

- patches/chromium/.patches
- patches/chromium/cherry-pick-ebc188ad769e.patch
[M96-LTS] Fix potential handle reuse in Mojo
(cherry picked from commit 76eca90d0e9c09bfbb8c3e8999f36e6da6842a39)
(cherry picked from commit e1432faf5e101b3a516037a26818c03c759d2fdd)
Fixed: 1270333
Change-Id: Ife188d519092e4e634355fd53d97c85009771b76
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3414063
Commit-Queue: Daniel Cheng <dcheng@chromium.org>
Cr-Original-Original-Commit-Position: refs/heads/main@{#962946}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3421488 …
> chore: cherry-pick ebc188ad769e from chromium

- .circleci/build_config.yml
This should speed up the run-tests portion of our macOS CI
> build: use gen2 macOS resources for tests

- shell/browser/electron_browser_main_parts.cc
Closes #32884.
In the mentioned [Chromium roll](https://github.com/electron/electron/pull/28660/files) I observed the following:
- [`patches/chromium/content_browser_main_loop.patch`](https://github.com/electron/electron/blob/7816fd240fdc552ea29b1d41c3c352d6a5272dad/patches/chromium/content_browser_main_loop.patch) which replaced `QuitClosure()` with `QuitWhenIdleClosure()` got removed
-  this appears again in the modified [`shell/browser/electron_browser_main_parts.cc`](https://github.com/electron/electron/pull/28660/files#diff-aaa10535b05dec71603ff4ab2971c77ec6798e2e25b080742831249f0359c960), but now with `QuitClosure()`
If I replace `QuitClosure()` with `QuitWhenIdleClosure()`, all processes terminate properly as it was the case before the Chromium roll. Since this is Electron code, it …
> fix: stale renderer process on quit

- docs/tutorial/notifications.md
This fixes a broken link to the GNOME Desktop Notifications Specification ([old link](https://developer.gnome.org/notification-spec/) to [new link](https://developer-old.gnome.org/notification-spec/)).
- [-] `npm test` passes
- [-] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)
- [-] relevant documentation is changed or added
- [-] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).
Notes: none
> docs: fix broken link to GNOME notifications spec

- .github/CODEOWNERS
Previously, @electron/wg-upgrades was the sole CODEOWNER of patches/. However, @electron/wg-security regularly merges patches and should have review power also.
It is left to the reviewer's judgement whether a patch should be reviewed by security or upgrades WG.
Notes: none
> chore: add @electron/wg-security to patches/ CODEOWNERS

- shell/browser/browser_win.cc
Enclose all arguments in quotation marks so that application can respect the individual arguments.
*Before:*
```ps
"C:\example\node_modules\electron\dist\electron.exe" "c:\example --arg" "%1"
```
*After:*
```ps
"C:\example\node_modules\electron\dist\electron.exe" "c:\example" "--arg" "%1"
```
Refs https://github.com/microsoft/vscode/issues/142685
Fixes #32463 
Notes: fix command string registered via setAsDefaultProtocolClient on windows
> fix: command string for windows protocol handler

- patches/chromium/.patches
- patches/chromium/cherry-pick-be50c60b4225.patch
Viz: Fix UAF on context loss
(cherry picked from commit 98d246cabe677e1d8287e4d42ce02825417be9e2)
Fixed: 1250655
Change-Id: I2898316635d370fa36b94e0ae2564ed357745b2c
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3413372
Reviewed-by: Kyle Charbonneau <kylechar@chromium.org>
Commit-Queue: Kyle Charbonneau <kylechar@chromium.org>
Cr-Original-Commit-Position: refs/heads/main@{#963012}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3430523
Cr-Commit-Position: refs/branch-heads/4758@{#1050}
Cr-Branched-From: 4a2cf4baf90326df19c3ee70ff987960d59a386e-refs/heads/main@{#950365}
Notes: …
> chore: cherry-pick be50c60b4225 from chromium

- patches/chromium/.patches
- patches/chromium/m98_fs_fix_fileutil_lifetime_issue.patch
M98: FS: Fix FileUtil lifetime issue
Keeps FileSystemContext alive while while resolving a URL on an open
file system, removing the possibility of the file system being
destroyed while a URL is being resolved on it.
(cherry picked from [commit 3fdf2adf11b3c716c9015597d30b59bffc7ac91b](https://chromium-review.googlesource.com/q/commit:3fdf2adf11b3c716c9015597d30b59bffc7ac91b))
Bug: [1275622](https://bugs.chromium.org/p/chromium/issues/detail?id=1275622), [1289394](https://bugs.chromium.org/p/chromium/issues/detail?id=1289394)
Change-Id: [Ic1b97552f9d41a61163d72ff8c605699f673f55f](https://chromium-review.googlesource.com/q/Ic1b97552f9d41a61163d72ff8c605699f673f55f)
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3373583
Reviewed-by: Marijn Kruisselbrink …
> chore: cherry-pick 05e714a87c from chromium

- patches/chromium/fix_don_t_restore_maximized_windows_when_calling_showinactive.patch
Fixes a malformed patch causing our patch-fixer to push to unrelated PRs (see https://github.com/electron/electron/pull/33025)
Notes: none.
> chore: fix out-of-date chromium patch

- patches/chromium/.patches
- patches/chromium/cherry-pick-1277917.patch
Subject: Avoid UAF on StreamingSearchPrefetchURLLoader.
StreamingSearchPrefetchURLLoader::OnDataAvailable used to "delete this",
which results in deleting the DataPipeDrainer, which will then be used
once OnDataAvailable returns. Instead, we post a task to delete the
URL loader later on.
Bug: 1277917
Notes: Security: backported fix for chromium:1277917.
> chore: cherry-pick fix for 1277917 from chromium

- docs/api/browser-window.md
- shell/browser/native_window.cc
- shell/browser/native_window.h
- shell/browser/native_window_mac.mm
- shell/browser/native_window_views.cc
- shell/browser/ui/cocoa/window_buttons_proxy.h
- shell/browser/ui/cocoa/window_buttons_proxy.mm
- shell/browser/ui/views/win_caption_button.cc
- shell/browser/ui/views/win_caption_button.h
- shell/browser/ui/views/win_caption_button_container.cc
- shell/browser/ui/views/win_caption_button_container.h
- shell/browser/ui/views/win_frame_view.cc
- shell/browser/ui/views/win_frame_view.h
- shell/common/options_switches.cc
- shell/common/options_switches.h
- spec-main/api-browser-window-spec.ts
Backport of #31222
Notes: Added `height` option for Windows Control Overlay
> feat: add WCO height option

- docs/api/window-open.md
- lib/browser/api/web-contents.ts
- lib/browser/guest-window-manager.ts
- typings/internal-electron.d.ts
Fixes: https://github.com/electron/electron/issues/11128
Currently electron automatically closes child windows when the opener window closes.
This behavior is a left over from the Atom text editor and does not conform with standard browser behavior.
The PR adds the ability to control this behavior, since it is not possible to deactivate this without hacks.
Note: This is not a breaking change since the flag is not required and the default stays the same as it used to be.
Notes: Added ability to configure if window should close when opener closes
> feat: Added ability to configure if window should close when opener closes

- shell/browser/api/electron_api_web_contents.cc
Closes https://github.com/electron/electron/issues/32846.
Traced back to https://github.com/electron/electron/pull/30778 - we no longer have a transparent option in `webPreferences`, and so https://github.com/electron/electron/blob/28ada6ea8bd2abeca8812e6d284c1f5f3974286b/shell/browser/api/electron_api_web_contents.cc#L771 would _always_ return false. As of the above PR, we handle transparency in `webPreferences` by propagating it to `webPreferences` in the `BrowserWindow` ctor: https://github.com/electron/electron/blob/28ada6ea8bd2abeca8812e6d284c1f5f3974286b/shell/browser/api/electron_api_browser_window.cc#L56-L57 Therefore, in order to properly instantiate a transparent offscreen window, we need to check for the `backgroundColor` being set to the hex equivalent of `SK_ColorTRANSPARENT` …
> fix: broken OSR transparent option

- shell/browser/window_list.cc
Closes https://github.com/electron/electron/issues/33034.
Fixes a potential DCKECK resultant of trying to close an already-closed window.
Notes: none
> fix: DCHECK when calling app.exit()

- script/release/release.js
This PR is a debug PR specific to 18-x-y, to help debug an error when validating a release. This PR should be reverted once the issue has been resolved.
Notes: none
> build: add logging validate release

- shell/browser/api/electron_api_tray.cc
- shell/browser/api/electron_api_tray.h
Closes https://github.com/electron/electron/issues/31564.
Fixes an issue where the Tray could get garbage collected incorrectly under some circumstances.
I bisected this to https://github.com/electron/electron/compare/v10.0.0-nightly.20200310...v10.0.0-nightly.20200311 - which was the diff that removed the [catch-all `HandleScope`](https://github.com/electron/electron/commit/19314d3cafc5ec1c4b1f1316b3f5d9744f8e9604). For some trays, this wasn't an issue - if they had a menu, for example, those are prevented from being GC'd which also prevented Tray GC. We fix this by pinning the Tray, in similar fashion to what's done with, for example, `BrowserView`.
Notes: Fixed an issue where the Tray could get garbage collected incorrectly under some circumstances.
> fix: incorrect tray garbage collection

- docs/fiddles/ipc/pattern-2/main.js
Fiddle ipc pattern 2 update 
updated main.js such that now it requires dialog otherwise it would have thrown "Error occurred in handler for 'dialog:openFile': ReferenceError: dialog is not defined"
Notes: none
> docs: fiddle ipc pattern 2 example update 

- shell/browser/ui/tray_icon_cocoa.mm
Closes https://github.com/electron/electron/issues/33008.
Fixes an issue where `alternateImage`s did not work properly on macOS. To fix this, we need to change the button type when setting an alternate image because the default button type for `NSStatusItem`, `NSStatusBarButton`, does not display alternate content when clicked. [`NSButtonTypeMomentaryChange`](https://developer.apple.com/documentation/appkit/nsbuttontype/nsbuttontypemomentarychange?language=objc) displays its alternate content when clicked and returns to its normal content when the user releases it, which is the behavior users would expect when clicking a button with an alternate image set. After this fix, the tray icon displays the same behavior as it did prior to this breaking. Also tested with context menus etc to …
> fix: macOS tray icon alternate images

- spec-main/api-browser-window-spec.ts
- spec-main/fixtures/pages/half-background-color.html
- spec-main/screen-helpers.ts
Adds tests for ensuring `backgroundColor` and `transparent` options work for `BrowserWindow`.
Note:
- No tests for `BrowserView` or WebContents Off-Screen Renderer
- `NativeImage` pixel is sometimes a slightly different color depending on underlying `desktopCapturer` implementation or maybe image compression 🤔 
- `desktopCapturer` tests currently don't support Linux so it's also skipped here for capturing the screen pixel
cc @nornagon @VerteDinde 
Notes: none
> test: BrowserWindow backgroundColor and transparency

- shell/browser/native_window.cc
Closes https://github.com/electron/electron/issues/32995.
Fixes an issue where setting window `maxHeight` or `maxWidth` made it so the width and height could no longer be resized.
https://github.com/electron/electron/pull/32628 fixed an issue with `maxWidth` not being respected at all, but also changed defaults such that `max_width` and `max_height` conformed to `size_constraints.GetMaximumSize()`. By default, `size_constraints.GetMaximumSize()` returns `(0, 0)` unless it's been previously set, so this accidentally made it such that the `maxHeight` couldn't be changed if the `maxWidth` was set, and vice versa. This fixes that issue.
Notes: Fixed an issue where setting window `maxHeight` or `maxWidth` made it so the width and height could no longer be resized.
> fix: max window size defaults to 0

- .circleci/build_config.yml
- build/args/all.gn
- patches/chromium/.patches
- patches/chromium/build_disable_thin_lto_on_mac.patch
We recently disabled thin LTO for all builds in order to save disk space on Mac CircleCI jobs. However, this had the unintended side effect of breaking the publish job for Windows ia32.
This PR patches Chromium to disable thin LTO on Mac only.
I had tested using the new CircleCI executors on Mac, but we were still unfortunately running out of disk space. This should unblock our nightlies from failing, pending one other fix. Mac ARM publish jobs are still occasionally failing on a libswiftshader issue that is unrelated to this changes (was introduced in the last Chrome roll)
Notes: none
> ci: disable use-thin-lto on Mac only

- docs/tutorial/in-app-purchases.md
- docs/tutorial/launch-app-from-url-in-another-app.md
- docs/tutorial/linux-desktop-actions.md
- docs/tutorial/macos-dock.md
- docs/tutorial/progress-bar.md
- docs/tutorial/recent-documents.md
- docs/tutorial/represented-file.md
- docs/tutorial/windows-taskbar.md
This is a companion PR to https://github.com/electron/electronjs.org-new/pull/177.
I'm removing the clunky `(Mac and Windows)` parts of the documentation titles and instead storing that metadata within the sidebars on the website.
The end goal is to have the docs look like this to end users:
cc @electron/wg-ecosystem 
Notes: none
> docs: remove platform notices from tutorial titles

- docs/tutorial/quick-start.md
The steps on the section to Package and Distribute an Application using Electron Forge had incorrect numbering
Notes: none
> docs: Updated list numbering

- .circleci/build_config.yml
Doc only changes coming from forks were failing on gclient sync.  Forks do not get access to the source/git caches that branches use, so gclient sync is much slower.  Using a larger machine alleviates this problem.
#33140 shows a fork PR successfully running a docs only change at https://app.circleci.com/pipelines/github/electron/electron/50155/workflows/3a2f415d-cd20-4dcf-9d2a-565fbb33204e/jobs/1144884
Notes: none
> ci: use larger machine for docs only check

- spec-main/chromium-spec.ts
Disables flaky
> 'disables JavaScript when it is disabled on the parent window'
test on `17-x-y`. This has previously been disabled on 18 and main.
Notes: none.
> test: disable consistently flaky WOA JS test

- spec-main/api-browser-window-spec.ts
#31017 added new tests but because it was a fork those tests did not run on WOA.  Once it was merged it broke CI because these tests do not work on WOA.
Notes: none
> test: disable newly added tests on WOA

- patches/chromium/.patches
- patches/chromium/cherry-pick-6b2643846ae3.patch
[M96-LTS] Guard BatchingMediaLog::event_handlers_ with lock
It seems that despite MediaLog::OnWebMediaPlayerDestroyed and
MediaLog::AddLogRecord both grabbing a lock,
BatchingMediaLog::AddLogRecordLocked can escape the lock handle by
posting BatchingMediaLog::SendQueuedMediaEvents, causing a race.
When the addition of an event is interrupted by the deletion of a player
due to player culling in MediaInspectorContextImpl, a UAF can occur.
R=​dalecurtis
(cherry picked from commit 34526c3d0a857a22618e4d77c7f63b5ca6f8d3d2)
Bug: 1295786
Change-Id: I77df94988f806e4d98924669d27860e50455299d
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3451494
Commit-Queue: Ted (Chromium) Meyer <tmathmeyer@chromium.org>
Cr-Original-Commit-Position: refs/heads/main@{#970815}
Reviewed-on: …
> chore: cherry-pick 6b2643846ae3 from chromium

- docs/fiddles/ipc/pattern-2/main.js
- docs/fiddles/ipc/pattern-3/main.js
There is a another bug in `docs/fiddles/ipc/pattern-3/renderer.js` : `event.reply` is `undefined` .
```js
const counter = document.getElementById('counter')
window.electronAPI.handleCounter((event, value) => {
const oldValue = Number(counter.innerText)
const newValue = oldValue + value
counter.innerText = newValue
event.reply('counter-value', newValue)  // `event.reply` is undefined, `event.sender.send` is available.
})
```
Notes: none
> docs: fix missing dependencies in ipc patterns

- shell/browser/api/electron_api_app.cc
Ref #33045.
This is already documented, but this makes the landing softer when the API is misused.
Notes: none
> fix: gracefully fail if app.configureHostResolver is called before ready

- .git-blame-ignore-revs
Utilizes a new flagged GH feature which exposes the `--ignore-revs-file` option to the git blame UI. This allows us to ignore massive refactor commits from the git blame UI to make tracking down issues easier.  You can still view the blame including these commits locally and on GH if you view the blame from a commit prior to this file being added.
As an example:
* With JS semicolon in blame: https://github.com/electron/electron/blame/main/lib/browser/ipc-main-impl.ts
* Without JS semicolon in blame: https://github.com/electron/electron/blame/ignore-revs/lib/browser/ipc-main-impl.ts
> chore: add ignore revs file for GH blame UI

- patches/angle/.patches
- patches/angle/cherry-pick-49e8ff16f1fe.patch
M99: Vulkan: Fix texture array level redefinition
When a level of a texture is redefined, all staged updates to that level
should be removed, not the ones specific to the new layers.  The bug
fixed was that if the texture was redefined to have its number of layers
changed, the staged higher-layer-count update to the image was not
removed.
Bug: chromium:1289383
Change-Id: Iab79c38d846d1abbdd92e11b1b60a3adf0fbde4c
Reviewed-on: https://chromium-review.googlesource.com/c/angle/angle/+/3441309
Reviewed-by: Lingfeng Yang <lfy@google.com>
Notes: Security: backported fix for chromium:1289383.
> chore: cherry-pick 49e8ff16f1fe from angle

- patches/chromium/.patches
- patches/chromium/cherry-pick-62142d222a80.patch
[M96-LTS][mojo-bindings]: Validate message headers sooner
- multiplex_router.h: conflict in removed lines because of
differences in comments above header_validator_
- connector.h: conflicting includes
Message header validation has been tied to interface message dispatch,
but not all mojo::Message consumers are interface bindings.
mojo::Connector is a more general-purpose entry point through which
incoming messages are received and transformed into mojo::Message
objects. Blink's MessagePort implementation uses Connector directly to
transmit and receive raw serialized object data.
This change moves MessageHeaderValidator ownership into Connector and
always applies its validation immediately after reading a message from
the pipe, thereby ensuring that all mojo::Message …
> chore: cherry-pick 62142d222a80 from chromium

- docs/api/web-contents.md
Fixes a small documentation issue -- `webContents.getFocusedWebContents()` can return `null`, so that value should be part of the return type signature. Thanks to @erickzhao for the assist and pointers.
See also: https://github.com/electron/typescript-definitions/issues/202
Notes: Fixed the documented return value declared by `webContents.getFocusedWebContents()` to include `null`, matching the documented usage of the function.
> docs: fix documented return value for getFocusedWebContents

- patches/chromium/.patches
- patches/chromium/cherry-pick-1887414c016d.patch
[M96-LTS] Replace WidgetObserver::OnWidgetClosing() with OnWidgetDestroying()
In some cases, OnWidgetClosing() is not called when the widget is
closed, resulting an invalid pointer |widget_| stored in
WebContentsDisplayObserverView.
This CL replaces OnWidgetClosing() with OnWidgetDestroying(), which
is recommended in crbug.com/1240365
(cherry picked from commit 4535fe2334d0713535adb52b641a8cb34e11333c)
Bug: 1291728
Change-Id: I64fef8b30930f60220008809ee00f4385d6c3520
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3425473
Auto-Submit: Muyao Xu <muyaoxu@google.com>
Commit-Queue: Takumi Fujimoto <takumif@chromium.org>
Cr-Original-Commit-Position: refs/heads/main@{#965431}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3435985
Reviewed-by: …
> chore: cherry-pick 1887414c016d from chromium

- patches/chromium/feat_add_data_transfer_to_requestsingleinstancelock.patch
- patches/chromium/feat_enable_offscreen_rendering_with_viz_compositor.patch
- patches/chromium/fix_media_key_usage_with_globalshortcuts.patch
- patches/chromium/process_singleton.patch
`#if defined(OS_WIN)` needs to be replaced with `#if BUILDFLAG(IS_WIN)`
`#if defined(OS_MAC)` needs to be replaced with `#if BUILDFLAG(IS_MAC)`
Notes: none
> fix: patches to use BUILDFLAG(IS_WIN) / BUILDFLAG(IS_MAC) checks

- shell/browser/ui/inspectable_web_contents.cc
Closes https://github.com/electron/electron/issues/33023.
Fixes an issue where clicking "Open in Containing Folder" in the Sources tab in Devtools caused a crash. 
We were incorrectly [passing an empty callback](https://github.com/electron/electron/blob/28ada6ea8bd2abeca8812e6d284c1f5f3974286b/shell/browser/ui/inspectable_web_contents.cc#L742) instead of a callback which [calls `ShowItemInFolder`](https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/devtools/devtools_file_helper.cc;l=457-460). Chromium's call also opens the directory containing the file in their call to `platform_util::OpenItem`, so we correct that on our end (since we don't pass an option to differentiate) by passing the file's parent directory to `OpenPath`
Notes: Fixed an issue where clicking "Open …
> fix: crash when showing item in folder on DevTools

- patches/chromium/.patches
- patches/chromium/fix_non-client_mouse_tracking_and_message_bubbling_on_windows.patch
- shell/browser/ui/win/electron_desktop_window_tree_host_win.cc
- shell/browser/ui/win/electron_desktop_window_tree_host_win.h
My change in #32672 caused a regression where WCO-enabled windows (on Windows) could no longer be dragged. This is because in `HWNDMessageHandler::HandleMouseEventInternal`, `HandleMouseEvent` (which is what I patched in the previous PR) is called before `HandleMouseInputForCaption` (which is where the dragging happens I think, from testing). Instead of trying to patch in something to move the marking of the event as handled further down, I opted instead to try and fix the issue with `LegacyRenderWidgetHostHWND`.
This PR introduces a patch that does two things, particularly only for WCO-enabled windows right now:
1. Correctly track non-client mouse events, not just regular mouse events. This is mostly just some boilerplate to include those messages.
2. Instead of falling through to …
> fix: non-client mouse events on WCO-enabled windows

- docs/breaking-changes.md
- lib/browser/api/web-contents.ts
Per https://github.com/electron/electron/issues/28466#issuecomment-887009418,
though a little delayed.
Notes: Added warning that preload scripts will be sandboxed by default beginning in Electron 20.
> feat: warn that preloads will be sandboxed by default in v20

- shell/browser/ui/inspectable_web_contents.cc
- shell/browser/ui/inspectable_web_contents.h
Closes https://github.com/electron/electron/issues/33102.
Closes https://github.com/electron/electron/issues/31864.
In https://github.com/electron/electron/issues/31317 we adapted to changes in [this crbug](https://bugs.chromium.org/p/chromium/issues/detail?id=1245541), which inadvertently caused issues since we don't support synced settings in Electron. Synced settings are settings which persist across Chrome profiles, which is a concept we don't have in Electron. This removes code related to the synced settings, which caused devtools settings not to persist between loads.
Notes: Fixed an issue where Chrom DevTools settings didn't persist between loads.
> fix: settings not persisting across devtools loads

- shell/browser/electron_browser_client.cc
Fixes #15448. Modeled after Chrome: https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/chrome_content_browser_client.cc;l=1156;drc=e2cba64c183ae17816143ee344e6f7c81451555a
Notes: Added support for the `--unsafely-treat-insecure-origin-as-secure` command-line flag.
> fix: propagate unsafely-treat-insecure-origin-as-secure to renderer children

- shell/browser/native_window_views.cc
- shell/browser/native_window_views_win.cc
- spec-main/api-browser-window-spec.ts
Fixes #32976.
This doesn't fix macOS (see #32947), only Windows and Linux, but the test will ensure that it works on macOS as well once that issue is closed.
This is somewhat of a half measure to address this particular case, instead of a holistic sweep to ensure 'show' is fired any time a BrowserWindow transitions from unshown to shown. I think that would be a good thing to do, but I don't have the bandwidth to do that at the moment (this is like, the 3rd issue in a chain of blocking issues), so this will serve as an incremental step in that direction which also adds test coverage.
Notes: Fire 'show' event when a BrowserWindow is shown via maximize()
> fix: fire show event when BrowserWindow shown via maximize()

- patches/chromium/expose_setuseragent_on_networkcontext.patch
- patches/chromium/network_service_allow_remote_certificate_verification_logic.patch
This fixes a bug with the RemoteCertVerifier patch that drives the
`ses.setCertificateVerifyProc` API. When an in-flight request was cancelled
after the procedure was invoked but before the result was received, a
use-after-free could occur.
Fixes #31675.
Notes: Fixed a network service crash that could occur when using setCertificateVerifyProc.
> fix: prevent UAF crash in setCertificateVerifyProc

- shell/app/electron_main_mac.cc
- shell/app/electron_main_win.cc
Fix https://chromium-review.googlesource.com/c/chromium/src/+/3404768 properly
It was incorrectly handled by #33093, which removed the fix from #15711
Notes: none
> fix: add missing [[maybe_unused]] to IsEnvSet

- shell/browser/ui/cocoa/electron_inspectable_web_contents_view.mm
Not 100% sure if this fixes it but I believe this is the race condition.
Notes: Theoretical fix for a crash we're seeing when closing multiple child windows at the same time on macOS
> fix: race condition where webContents can be nullptr during re-focus and a multi-window close sequence

- docs/api/session.md
- shell/browser/api/electron_api_session.cc
- shell/browser/api/electron_api_session.h
- spec-main/api-session-spec.ts
Add `ses.setCodeCachePath()` API for setting code cache directory.
When transitioning to a node-free renderer environment apps which previously relied on creating v8 cached data via the [vm](https://nodejs.org/dist/latest-v14.x/docs/api/vm.html) module would store the data at version based locations of the format like `<user-data-dir>/<commit-sha-or-version>` so that the cache can be invalidated on updates. When relying on blink to now handle the cache creation and invalidation, this api is useful to serve as a hard reset when the cache goes into a non-recoverable state.
Notes: Added `ses.setCodeCachePath()` API for setting code cache directory.
> feat: allow setting code cache directory

- docs/api/process.md
The key was [removed back in Electron 7](https://github.com/electron/electron/blob/main/docs/breaking-changes.md#removed-marked-property-on-getblinkmemoryinfo).
Notes: none
> docs: remove "marked" from process.getBlinkMemoryInfo()

- patches/chromium/.patches
- patches/chromium/fix_imagebitmaprenderingcontext_interaction_with_software_compositor.patch
Fix ImageBitmapRenderingContext interaction with software compositor.
Before this CL, there was an early exit condition that prevented
texture-backed resources from being presented to the software compositor
even when the texture backing is swiftshader. This meant that in some
cases, ImageBitmaps that were created by webGL contexts would fail to
render.  Once the early exit removed, there were other bugs due to the
fact that bitmaps were not being converted to N32 format before being
dispatched to the software compositor.  This could cause several types
of rendering artifacts, including leaking bitmap data between contexts.
BUG=1283434
Change-Id: I6f353bc6301b79d7a4124445c85956125135f539
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3387268
Reviewed-by: Juanmi …
> chore: cherry-pick eb967bf211 from chromium

- docs/fiddles/ipc/pattern-3/renderer.js
- docs/tutorial/ipc.md
Closes #32867 
Fixed docs and fiddle code and tested with the fiddle.
- Added missing requirement `ipcMain` in docs code.
- Modified `event.reply` to `event.sender.send` as reply is not a function anymore in process event.
Notes: none
> fix: fiddle ipc code pattern 3

- shell/common/api/electron_api_native_image.cc
- shell/common/api/electron_api_native_image.h
This change is modeled after [how it is done for `ImageBitmap` in Chromium](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/imagebitmap/image_bitmap.cc;l=832-850;drc=d6530d58164c28dfba8e6a8c0f2c17f25afdc016;bpv=0;bpt=0).
The current code has the potential to make unbalanced adjustments, decrementing more memory than it has incremented, which messes with the overall tracking. Currently adding a representation to an empty `nativeImage` doesn't increase the external memory count, but the destructor decrements it, leading to a net negative. If you run that in a loop, you'll eventually turn the total external allocated memory count negative.
I think there are improvements to be made on the general tracking here, especially with multiple representations, …
> fix: ensure external memory adjustments are balanced

- shell/renderer/electron_renderer_client.cc
- shell/renderer/web_worker_observer.cc
- spec-main/fixtures/crash-cases/fs-promises-renderer-crash/index.html
- spec-main/fixtures/crash-cases/fs-promises-renderer-crash/index.js
Fixes https://github.com/electron/electron/issues/33164
Notes: fix crash in the render process on reload with pending node fs.promises
> fix: crash when destroying node env with pending promises

- shell/common/gin_helper/trackable_object.h
- spec-main/api-browser-window-spec.ts
Fixes #21608. The object was being added to the weak map only _after_ the
`_init` function was called, meaning that the TrackableObject::FromWrappedClass
method would not work during the `_init` function.
Notes: Fixed a bug where `BrowserWindow.fromWebContents` would return `undefined` during the `browser-window-created` event.
> fix: BrowserWindow.fromWebContents should work in browser-window-created

- docs/api/web-contents.md
- docs/api/webview-tag.md
- docs/tutorial/security.md
- lib/browser/guest-view-manager.ts
- shell/browser/api/electron_api_net.cc
- shell/browser/web_contents_preferences.cc
- shell/common/options_switches.cc
- shell/common/options_switches.h
- spec/static/main.js
- typings/internal-ambient.d.ts
- typings/internal-electron.d.ts
Ref #21553.
Instead of having a separate semi-documented `preloadURL` WebPreference that
only is ever used for webviews and provides no actual different functionality
from the existing `preload` (it only allows `file://` URLs), resolve the URL to
a file path when we get it from the webview before passing it to
WebPreferences.
Notes: Removed the semi-documented `preloadURL` property from WebPreferences.
> chore: remove awkward semi-documented preloadURL WebPreference

- lib/browser/api/web-contents.ts
Build got broken by a collision of #32868 and #33228.
Notes: none
> build: fix build by removing usage of removed preloadUrl

- patches/chromium/desktop_media_list.patch
Backport of #32435.
Notes: Fixed an issue where calling screen capture on macOS does not properly release underlying OS capture mechanisms.
> fix: desktop screen capture on macOS not releasing

- shell/browser/net/system_network_context_manager.cc
A [recent change in Chromium (CL: #3449280)](https://chromium-review.googlesource.com/c/chromium/src/+/3449280) now requires First Party Sets (FPS) to be fully initialized before queries can be received and responded to. This initialization happened in two parts: receiving the sets from the command line, and parsing the sets file.
This PR passes an empty file to `SetFirstPartySets`, to allow both checks to pass.
Notes: Fixed an issue where First Party Sets were not correctly loaded on app launch.
> fix: initialize FPS file in network service

- patches/chromium/.patches
- patches/chromium/enable_forcesynchronoushtmlparsing_by_default.patch
Enable ForceSynchronousHTMLParsing by default
This feature is enabled at 100% (with 1% stable holdback) on all
channels since M96. No unresolved problems have been reported,
and overall metrics are improved [1]. This CL enables the
ForceSynchronousHTMLParsing feature by default, and removes the
LoaderDataPipeTuning feature entirely, replacing it with newly-
hard-coded values from the launched experiment.
[1] https://docs.google.com/document/d/13GewLNZ50nqs0OI7-rzofOXtjuAlD0R4PMLTUsr73dg/edit#heading=h.ctbltu75kgzp
This part is cool:
Fixed: [901056](https://bugs.chromium.org/p/chromium/issues/detail?id=901056)
Fixed: [461877](https://bugs.chromium.org/p/chromium/issues/detail?id=461877)
Fixed: [761992](https://bugs.chromium.org/p/chromium/issues/detail?id=761992)
Fixed: …
> chore: cherry-pick c11809b8c0 from chromium

- patches/chromium/.patches
- patches/chromium/cherry-pick-246c10dede97.patch
[CherryPick to 99] Switch to new RequestPermissionsFromCurrentDocument API method for Media Stream Devices
Switch away from the deprecated RequestPermissions() API, as a part of removing a bug where the previously provided request.security_origin param might get destroyed during the method execution.
(cherry picked from commit cb6778fb965e2b010922f157c68480de863c252e)
Bug: 1283402
Change-Id: I512ce910146ec60d4d35fa1a86a71a3b0983a5d1
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3417436
Reviewed-by: Florent Castelli <orphis@chromium.org>
Commit-Queue: Tony Herre <toprice@chromium.org>
Cr-Original-Commit-Position: refs/heads/main@{#964535}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3473365
Cr-Commit-Position: refs/branch-heads/4844@{#655} …
> chore: cherry-pick 246c10dede97 from chromium

- script/add-debug-link.py
- script/check-relative-doc-links.py
- script/copy-debug-symbols.py
- script/generate-config-gypi.py
- script/generate-zip-manifest.py
- script/lib/config.py
- script/lib/git.py
- script/lib/native_tests.py
- script/lib/util.py
- script/native-tests.py
- script/release/uploaders/upload.py
- script/run-clang-format.py
- script/zip_manifests/check-zip-manifest.py
Prerequisite for landing #33232, see that PR for the lint failures this PR fixes.
Most are pretty straight forward, a few I ignored because `pylint-2.7` was suggesting changes which are Python 3 only (`super()` and `raise ... from ...`), and we need to maintain Python 2 compatibility for now. EDIT: I backed out the ignore comments because it created a chicken and egg problem where older `pylint` didn't recognize the codes. I'm attempting to keep updating to `pylint-2.7` separate from this PR just for cleaner separation and it can be reverted separately if need be.
Notes: none
> chore: fix pylint-2.7 errors

- shell/common/node_bindings.cc
- shell/common/node_bindings.h
- shell/common/node_bindings_linux.cc
- shell/common/node_bindings_linux.h
- shell/common/node_bindings_mac.cc
- shell/common/node_bindings_mac.h
- shell/common/node_bindings_win.cc
- shell/common/node_bindings_win.h
- shell/renderer/electron_renderer_client.cc
Fixes https://github.com/electron/electron/issues/1968
Fixes https://github.com/electron/electron/issues/30153
Refs https://github.com/microsoft/vscode/issues/142786#issuecomment-1061673400
Notes: fix broken event loop in renderer process when process reuse is enabled on windows platform
> fix: iocp integration when process is reused

- patches/chromium/.patches
- patches/chromium/cherry-pick-905302eb3a2b.patch
[M96-LTS] Roll libxml from dea91c97 to eab86522
2022-01-31 wellnhofer@aevum.de Make xmllint return an error if arguments
are missing
2022-01-28 wellnhofer@aevum.de Avoid potential integer overflow in
xmlstring.c
2021-07-07 ddkilzer@apple.com xmlAddChild() and xmlAddNextSibling() may
not attach their second argument
2022-01-25 wellnhofer@aevum.de Run CI tests with UBSan
implicit-conversion checks
2022-01-25 wellnhofer@aevum.de Fix casting of line numbers in SAX2.c
2022-01-25 wellnhofer@aevum.de Fix integer conversion warnings in hash.c
2022-01-25 wellnhofer@aevum.de Add explicit casts in runtest.c
2022-01-25 wellnhofer@aevum.de Fix integer conversion warning in
xmlIconvWrapper
2022-01-25 wellnhofer@aevum.de Add suffix to unsigned constant in
xmlmemory.c
2022-01-25 wellnhofer@aevum.de Add …
> chore: cherry-pick 905302eb3a2b from chromium

- docs/api/native-theme.md
- shell/browser/api/electron_api_native_theme.cc
- shell/browser/api/electron_api_native_theme.h
- spec-main/api-native-theme-spec.ts
https://blogs.windows.com/msedgedev/2020/09/17/styling-for-windows-high-contrast-with-new-standards-for-forced-colors/
Notes: Added `nativeTheme.inForcedColorsMode` API to allow detecting forced color mode.
> feat: add nativeTheme.inForcedColorsMode

- docs/api/browser-view.md
- docs/api/browser-window.md
- shell/browser/api/electron_api_base_window.cc
- shell/browser/api/electron_api_base_window.h
- shell/browser/api/electron_api_browser_view.cc
- shell/browser/api/electron_api_browser_window.cc
- shell/browser/api/electron_api_web_contents.cc
- shell/browser/native_window.cc
- shell/browser/ui/cocoa/electron_touch_bar.mm
- shell/browser/web_contents_preferences.cc
- shell/common/color_util.cc
- shell/common/color_util.h
- spec-main/api-browser-window-spec.ts
Refs https://github.com/electron/electron/issues/31019. 
In https://github.com/electron/electron/pull/30193, we unintentionally refactored `WebPreferences` such that `backgroundColor` no longer accepted CSS color values like `red`. However, that only worked for some types of `backgroundColor` methods, since others did enforce that the passed value be hex.
This PR thus adds more official support for the following formats:
- CSS Color Names
- HSL Colors
- RGB Colors
- Hex Color Values
And as a bonus removes some duplicate code from our `color_util` file.
Notes: Added support for more color formats in `setBackgroundColor`.
> feat: support more color formats for `backgroundColor`

- shell/browser/ui/views/win_frame_view.cc
Closes https://github.com/electron/electron/issues/32681.
Fixes a DCHECK encountered when trying to resize frameless windows on Windows.
<details> <summary>Stacktrace</summary>
```
[17168:0131/153326.410:FATAL:native_view_host.cc(248)] Check failed: false. This view is not expected to receive events directly. Event targeting should find the native view as target window instead of the view hierarchy. This is likely due to an overlapping View that receives but is not handling this event. See crbug.com/1263413 and Widget::ShouldDescendIntoChildForEventHandling() for some more leads. If the overlapping view was not intended to receive events, call SetCanProcessEventsWithinSubtree(false) on the overlapping View that paints to a layer. If it's intended to receive some, but not this event, event …
```
> fix: NOTREACHED when resizing windows frameless bounds

- shell/browser/api/electron_api_web_contents.cc
- spec-main/api-browser-view-spec.ts
- spec-main/api-browser-window-spec.ts
This regression was introduced by commit 22a70eb8. The change done by WebContentsImpl::IncrementCapturerCount() is reverted just before returning in WebContents::IncrementCapturerCount(), so the isBeingCaptured() always returns false. Fixed the issue by not running the close closure returned by web_contents::IncrementCapturerCount().
Please double-check that this change is fine since I'm not familiar with this code.
cc @ckerr @codebytere  @deepak1556 @MarshallOfSound 
Related #30666 
Affected branches: 13-x-y to the current stable branch, please consider backporting this fix to them.
```c++
base::ScopedClosureRunner WebContentsImpl::IncrementCapturerCount(
const gfx::Size& capture_size,
bool stay_hidden,
bool stay_awake) {`
....
return base::ScopedClosureRunner( …
```
> fix: IncrementCapturerCount doesn't increase the capturer count

- spec/webview-spec.js
This is an experimental PR to check in on an old test that we disabled during a Chromium roll awhile back. I came across it this morning and enough time has passed that it seemed like a good step would be to try re-enabling to see if it's still broken, or if anything else has changed in the interim.
Notes: none
> test: re-enable webview resize events test

- shell/browser/native_window_views.cc
- shell/browser/native_window_views.h
- shell/browser/native_window_views_win.cc
Closes https://github.com/electron/electron/issues/33279.
Refs CRBUG:251813
It's the case at present that `widget()->SetBounds(bounds)` does not take effect if the window is currently being moved or resized. This is an open issue on Chromium since 2013, with no real solution implemented upstream but several options suggested, including:
> Drag completes ignoring the bounds update but the bounds update is queued and then executed after drag completes.
In a Chromium context, this might not be ideal, but in an Electron context I believe this is the most expected behavior from a development standpoint. As a result of this PR, the bounds update correctly once the user completes the resize or the drag movements to reflect the new bounds set programmatically. Now, we take the last call to …
> fix: pend bounds change when moving BrowserWindows

- patches/angle/.patches
- patches/angle/m98_protect_against_deleting_a_current_xfb_buffer.patch
[M98] Protect against deleting a current XFB buffer.
Bug: [chromium:1295411](https://bugs.chromium.org/p/chromium/issues/detail?id=1295411)
Change-Id: [I097f272c38e444e0af71aa55c0dc508a07aa0bd3](https://chromium-review.googlesource.com/q/I097f272c38e444e0af71aa55c0dc508a07aa0bd3)
Reviewed-on: https://chromium-review.googlesource.com/c/angle/angle/+/3498262
Reviewed-by: Amirali Abdolrashidi <[abdolrashidi@google.com](mailto:abdolrashidi@google.com)>
Reviewed-by: Geoff Lang <[geofflang@chromium.org](mailto:geofflang@chromium.org)>
Commit-Queue: Jamie Madill <[jmadill@chromium.org](mailto:jmadill@chromium.org)>
(cherry picked from [commit d9002eef2a5f27fc5d6b65d01d02afcfb9a35db1](https://chromium-review.googlesource.com/q/commit:d9002eef2a5f27fc5d6b65d01d02afcfb9a35db1))
Reviewed-on: …
> chore: cherry-pick 161f0866e8 from angle

- docs/api/browser-window.md
- docs/breaking-changes.md
- shell/browser/native_window_views.cc
BREAKING CHANGE
Closes #33124.
`skipTaskbar` has no effect on Wayland. Currently Electron uses `_NET_WM_STATE_SKIP_TASKBAR` to tell the WM to hide an app from the taskbar, and this works fine on X11 but there's no equivalent mechanism in Wayland. There _are_ some workarounds available on different systems, e.g. GNOME and KWin, but they some unacceptable tradeoffs, e.g. `Window.is_skip_taskbar` requires unsafe mode.
tl;dr I don't see a way to support this feature on Linux anymore.
This PR updates the documentation to reflect that it's only supported on macOS / Windows and makes an announcement in "breaking changes" (it's broken already, but better to document it here for visibility).
Notes: Marked `.skipTaskbar` as unsupported on Linux.
> docs: mark skipTaskbar as unsupported on Linux

- patches/squirrel.mac/.patches
- patches/squirrel.mac/fix_use_kseccschecknestedcode_kseccsstrictvalidate_in_the_sec.patch
- spec-main/api-autoupdater-darwin-spec.ts
Validate _more_ things during the update process
> fix: use stricter options in SecStaticCodeCheckValidity

- patches/chromium/feat_add_data_transfer_to_requestsingleinstancelock.patch
- shell/browser/api/electron_api_app.cc
- shell/browser/api/electron_api_app.h
This came out of looking into some X11/Wayland stuff. It looks like Arch Linux [patches Electron to make these changes](https://github.com/archlinux/svntogit-community/blob/1f0c64e/electron/trunk/std-vector-non-const.patch). As far as I can tell that patch hasn't been submitted to Electron as a PR before.
That further led me to a review from a couple of weeks ago for libc++ [where they are removing support for `std::vector<const`](https://reviews.llvm.org/D120996):
> This extension is a portability trap for users, since no other standard library supports it. Furthermore, the Standard explicitly allows implementations to reject std::allocator<cv T>, so allowing it is really going against the current.
Since it's coming down the pipeline eventually, might as well do it now, and then Arch …
> chore: change usages of std::vector with const elements

- docs/tutorial/quick-start.md
remove extra $ from npm install command
remove extra $ from npm install command. The $ causes the command to fail when pasted in the terminal to be run.
minor doc change
Notes: none
> docs: remove extra $ from npm install command

- spec-main/screen-helpers.ts
Ran into this causing a test crash on an M1 MBP. The root crash is in a converter, but this works around the test crash now.
@codebytere 
Notes: none
> test: fix crash on image.crop

- script/lint.js
- script/release/uploaders/upload.py
- script/run-clang-format.py
Currently `yarn lint:py` won't run on Apple silicon since it would use Python 2, and Chromium infra doesn't provide a Python 2.7 package:
```
dsanders@Davids-MacBook-Pro electron % yarn lint:py  
yarn run v1.22.17
$ node ./script/lint.js --py
[E2022-03-10T17:14:02.282736-08:00 98290 0 annotate.go:273] original error: no such package: infra/python/wheels/wrapt/mac-arm64_cp27_cp27m
goroutine 100:
#0 go.chromium.org/luci/cipd/client/cipd/client.go:1934 - cipd.(*clientImpl).humanErr()
#1 go.chromium.org/luci/cipd/client/cipd/client.go:929 - cipd.(*clientImpl).ResolveVersion()
#2 go.chromium.org/luci/cipd/client/cipd/resolver.go:176 - cipd.(*Resolver).resolveVersion.func1()
#3 go.chromium.org/luci/common/sync/promise/promise.go:84 - promise.(*Promise).runGen()
#4 runtime/asm_arm64.s:1130 - …
```
> chore: use pylint-2.7

- docs/tutorial/security.md
Realized that we talk about this a lot but it isn't in the docs anywhere, this adds IPC validation to our security reccomendations
> docs: add new IPC validation section to the security tutorial

- shell/browser/ui/views/inspectable_web_contents_view_views.cc
Closes: https://github.com/electron/electron/issues/31513
This PR reverts the change introduced in PR: https://github.com/electron/electron/pull/30510, to persist the content bounds of a BrowserView when it goes outside it's parent window. For background reference to see why this change was done, see: https://github.com/electron/electron/issues/29778.
The reason for this PR and why we think it's a reasonable change to do is the following:
- We want to have an option to shift a BrowserView to go outside of it's parent window without having the framework limiting it's bounds, which we had before.
- If the color issue can be solved by making sure a BrowserView is inside it's parent window, we would prefer to let the application developer solve this and still allow to have a choice to move a …
> fix: persist BrowserView content bounds when calculating layout

- patches/angle/.patches
- patches/angle/m96-lts_vulkan_fix_issue_with_redefining_a_layered_attachment.patch
[M96-LTS] Vulkan: Fix issue with redefining a layered attachment.
The fix ensures we complete level redefinition before we get the
layer render target in TextureVk::getAttachmentRenderTarget.
Bug: chromium:1296866
Change-Id: Id7fa8e9fed5e766c30580b09336713c675c4e4f0
Reviewed-on: https://chromium-review.googlesource.com/c/angle/angle/+/3498283
(cherry picked from commit 348ece42552a99cff88f79c80652b9dd3155ab22)
Reviewed-on: https://chromium-review.googlesource.com/c/angle/angle/+/3513754
Notes: Backported fix for CVE-2022-0976.
> chore: cherry-pick 2b75a29bf2 from angle

- .circleci/build_config.yml
- appveyor.yml
Recently we ran into an issue where CI was taking forever because the Goma auth token had expired.  This PR adds logic to CI to abort jobs if the Goma auth token is no longer valid so that we don't waste compute time.  This also should make it more noticeable when the token expires.
I did some testing to verify short cutting of jobs which can be seen here:
https://app.circleci.com/pipelines/github/electron/electron/50963/workflows/7c408b57-9835-4c88-91ae-b88a82f31e71/jobs/1164588
and here:
https://ci.appveyor.com/project/electron-bot/electron-ia32-testing/builds/42993932
Notes: none
> ci: abort CI if goma authentication is invalid

- docs/development/build-instructions-windows.md
Closes #33229.
Now that `pywin32` isn't used anymore in Electron, this isn't necessary.
Notes: none
> docs: remove pywin32 from Windows build instructions

- spec/webview-spec.js
This test is already disabled on 18-x-y and later, but it is also very flaky on older branches.
Notes: none
> test: disable webview.capturePage test

- docs/api/web-frame-main.md
These markdown links were broken.
Notes: none
> docs: fix SCA and postMessage links in web-frame-main.md

- patches/v8/.patches
- patches/v8/cherry-pick-c46fb3a15ec2.patch
[M96-LTS][liftoff][x64] Fix bug in i32.atomic.sub32
{AtomicSub} on x64 first negates the {value} register, then does an
atomic addition. For that reason, {value} should be a unique register.
So far, we only checked that it's not used in the value stack, but we
should also check for overlap with the destination address or the offset
register.
Drive-by: Remove unneeded handling of non-unique register index on arm,
as that cannot happen (LiftoffCompiler ensures that the result register
is unique).
R=​thibaudm@chromium.org
(cherry picked from commit b5003a3c631328bfbe3357dfea7aaebf46316c09)
Bug: chromium:1296876
Change-Id: Ie6b97eec8e8dea07b0bcc644d261f47467cc5b8e
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/3487987 …
> chore: cherry-pick c46fb3a15ec2 from v8

- patches/angle/.patches
- patches/angle/cherry-pick-2b75a29bf241.patch
[M96-LTS] Vulkan: Fix issue with redefining a layered attachment.
The fix ensures we complete level redefinition before we get the
layer render target in TextureVk::getAttachmentRenderTarget.
Bug: chromium:1296866
Change-Id: Id7fa8e9fed5e766c30580b09336713c675c4e4f0
Reviewed-on: https://chromium-review.googlesource.com/c/angle/angle/+/3498283
(cherry picked from commit 348ece42552a99cff88f79c80652b9dd3155ab22)
Reviewed-on: https://chromium-review.googlesource.com/c/angle/angle/+/3513754
Notes: Backported fix for CVE-2022-0976.
> chore: cherry-pick 2b75a29bf241 from angle

- patches/chromium/.patches
- patches/chromium/cherry-pick-eb967bf21108.patch
Fix ImageBitmapRenderingContext interaction with software compositor.
Before this CL, there was an early exit condition that prevented
texture-backed resources from being presented to the software compositor
even when the texture backing is swiftshader. This meant that in some
cases, ImageBitmaps that were created by webGL contexts would fail to
render.  Once the early exit removed, there were other bugs due to the
fact that bitmaps were not being converted to N32 format before being
dispatched to the software compositor.  This could cause several types
of rendering artifacts, including leaking bitmap data between contexts.
BUG=1283434
Change-Id: I6f353bc6301b79d7a4124445c85956125135f539
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3387268
Reviewed-by: Juanmi …
> chore: cherry-pick eb967bf21108 from chromium

- docs/api/browser-window.md
- shell/browser/api/electron_api_browser_window.cc
- shell/browser/api/electron_api_browser_window.h
- shell/browser/native_window.h
- shell/browser/native_window_views.h
- shell/browser/ui/views/win_caption_button.cc
- shell/browser/ui/views/win_frame_view.cc
- shell/browser/ui/views/win_frame_view.h
This PR adds a new API to `BrowserWindow` to change the style of the window controls on a WCO-enabled window (only on Windows):
* `BrowserWindow#setTitleBarOverlay(options: TitleBarOverlay): void`
The `options` parameter mimics the options object in the `BrowserWindow` constructor. That said, the `BrowserWindow` constructor also accepts a `boolean` value, which this method does not! At least not right now, that is. Being able to toggle the titlebar overlay on and off on an already-constructed window might require a substantial refactor to recreate/adjust the entire window view hierarchy and modify the native window. Instead, I'm forgoing the toggle so I can just implement what is necessary to adjust the style of the titlebar overlay. This method is can be augmented in the future to add …
> feat: add WCO title bar style setters

- shell/browser/api/electron_api_web_contents.cc
Building with following additional args:
```gn
enable_basic_printing=false
enable_pdf=false
enable_print_preview=false
enable_pdf_viewer=false
```
Results in:
```sh
ERROR at //electron/shell/browser/api/electron_api_web_contents.cc:170:11: Can't include this header from here.
#include "printing/mojom/print.mojom.h"
^---------------------------
The target:
//electron:electron_lib
is including a file from the target:
//printing/mojom:mojom__generator
It's usually best to depend directly on the destination target.
In some cases, the destination target is considered a subcomponent
of an intermediate target. In this case, the intermediate target
should depend publicly on the destination to forward the ability
to include headers.
Dependency chain (there may also be others): …
```
> fix: gn check when //printing component is disabled

- patches/chromium/fix_non-client_mouse_tracking_and_message_bubbling_on_windows.patch
🥲 #32871 broke the double-click-to-maximize behavior on frameless and WCO windows. As they say, third time's a charm!
To expound a bit more, this patch has been modified to follow the old code path 99% of the time, and the only time it deviates from chrome is on non-client mouse move messages. This is specifically because mouse movements are tracked on the legacy window, not the actual web content (parent) window that you see.
I manually tested all the possible window controls and title bar interactions I could, from drags and double clicks and hovers and system commands (the move and size actions in the window's system menu that you control with your keyboard). Web content below seems to be functioning right as well. Everything I can think of seems to work. Hopefully that means this …
> fix: non-client windows messages on legacy widget host (again)

- shell/browser/api/electron_api_browser_view.cc
- shell/browser/api/electron_api_web_contents.cc
- spec-main/api-browser-view-spec.ts
Closes https://github.com/electron/electron/issues/33374.
Fixes an issue where backgroundColor would not be applied correctly to a BrowserView on Windows. This was happening because the color was being set on the `RenderWidgetHostView` in webContents, but the color was missing from `webPreferences` and so was transparent every time. We need to ensure the color is set properly on the window as well as the contents every time `setBackgroundColor` is called, as is done on `BrowserWindow`.
Notes: Fixed an issue with background colors being improperly applied to `BrowserView`s on Windows.
> fix: BrowserView background color in webContents

- .circleci/build_config.yml
Will be useful for debugging failures in the `post_build_ninja_summary` script
> build: store last ninja log in artifacts

- docs/tutorial/security.md
Rule 13 recommends using Node's URL parser for handling url inputs. At
the moment, this is not being followed in the code example for rule 5,
which falls back on checking that the url ends with a '/'. If this was
forgotten when a user copies this code it could introduce security
vulnerabilities if an attacker uses an URL in the following way:
"https://example.com.attacker.com"
Using Node's URL parser fixes this potential missuse and enables the
'/' to be omited from the code example.
Addresses #33192
Notes: none
> docs: Use Node's URL parser in the 5th security recommendation example

- patches/v8/.patches
- patches/v8/cherry-pick-26b7ad6967b1.patch
[M96-LTS][runtime] Fix handling of interceptors
(cherry picked from commit 0981e91a4f8692af337e2588562ad1504f4bffdc)
Bug: chromium:1309225
Change-Id: Ifd62639a2aa18b633e7cf36632677ee16c977afd
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/3548458
Cr-Original-Commit-Position: refs/heads/main@{#79613}
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/3550263
Reviewed-by: Lutz Vahl <vahl@chromium.org>
Commit-Queue: Lutz Vahl <vahl@chromium.org>
Cr-Commit-Position: refs/branch-heads/9.6@{#54}
Cr-Branched-From: 41a5a247d9430b953e38631e88d17790306f7a4c-refs/heads/main@{#772 …
> chore: cherry-pick 26b7ad6967b1 from v8

- lib/common/webpack-provider.ts
- npm/package.json
- package.json
- spec-main/api-web-request-spec.ts
- typings/internal-ambient.d.ts
- yarn.lock
Update the version of `@types/node` in both the repo `package.json` (mostly for the sake of tests, rather than scripts) as well as the published npm `package.json`. This doesn't match the version in `DEPS` because `@types/node` doesn't *always* release with Node (found this out the hard way). Fixes #33089
Notes: Updated node types version.
> chore: update node types version

- docs/breaking-changes.md
Manually backport #33479 to 18-x-y. See that PR for details.
Notes: none
> docs: docs: simplify skipTaskbar breaking changes text

- DEPS
- patches/chromium/build_do_not_depend_on_packed_resource_integrity.patch
- patches/chromium/chore_use_electron_resources_not_chrome_for_spellchecker.patch
- patches/chromium/resource_file_conflict.patch
Updating Chromium to 98.0.4758.141.
See [all changes in 98.0.4758.109..98.0.4758.141](https://chromium.googlesource.com/chromium/src/+log/98.0.4758.109..98.0.4758.141?n=10000&pretty=fuller)
Notes: Updated Chromium to 98.0.4758.141.
> chore: bump chromium in DEPS to 98.0.4758.141

- shell/browser/native_window_mac.mm
This PR resets the `WindowButtonsProxy` in `NativeWindowMac` when deleting the underlying `NSWindow`. This is needed, because `WindowButtonsProxy` has a reference to `NSWindow`, which is not cleared when `NSWindow` is. This can cause a crash when `WindowButtonsProxy` calls something on the `NSWindow` when that is already cleared.
We ran into this crash at Around only when we were updating our electron app and wanted to quit the application and restart a new one. So it's hard to formulate a repro for this.
Notes: Fix crash when WindowButtonsProxy references cleared NSWindow
> fix: crash when WindowButtonsProxy references cleared NSWindow

- .circleci/build_config.yml
https://chromium-review.googlesource.com/c/chromium/tools/depot_tools/+/3556588 changed depot_tools to echo out a message when updating depot_tools.  Unfortunately this broke our logic to update esbuild on our macOS builds, eg: 
https://app.circleci.com/pipelines/github/electron/electron/51193/workflows/a804e7b5-844e-4a76-824c-cf3b8c90aded/jobs/1170674
Notes: none
> ci: fixup esbuild on macos

- docs/api/web-frame.md
Made the heading of `webFrame.insertCSS` an h3 instead of h4 by removing a '#' from the markdown.
Fixes #33451.
> docs: update heading level of webFrame.insertCSS

- spec-main/api-desktop-capturer-spec.ts
Refs https://github.com/electron/electron/pull/20649/commits/2cfcbd4e33e834c221f9977667c4a92ce816f1fc.
Refs https://github.com/electron/electron/issues/20771.
Rewrite and re-enable a failing desktopCapturer spec. This spec was failing owing to a few issues: chiefly: `forEach` is not promise-aware. `orderWindow:relativeTo` can also behave a bit weirdly on macOS when the window is unfocused, so ensure proper behavior by calling `focus` before calling `moveAbove`.
Notes: none.
> chore: fix moveAbove desktopCapturer spec

- spec-main/api-desktop-capturer-spec.ts
Closes https://github.com/electron/electron/issues/20771.
These appear to work now - I'm fairly certain that the original culprit for these failures was resolved by https://github.com/electron/electron/pull/32435, but at the time we never attempted to re-enable them so we didn't know.
Notes: none
> test: re-enable `desktopCapturer` specs

- docs/api/system-preferences.md
This was incorrectly typed as always being a `string`, this is now accurate
> docs: fix type of 'value' param in setUserDefaults

- build/args/all.gn
This PR adds a new node version number for Electron 20.
Merged Node PR here: https://github.com/nodejs/node/pull/41814
_NOTE: Please hold until the 19 branch has been cut_
Notes: none
> chore: bump NMV for Electron 20

- shell/browser/native_window_mac.mm
- spec-main/api-browser-window-spec.ts
Fixes #32947.
Notes: Fixed behavior of BrowserWindow.maximize on macOS for not shown windows
> fix: on macOS show BrowserWindow on maximize if not currently shown

- docs/api/app.md
- shell/browser/api/electron_api_app.cc
- shell/browser/browser.h
- shell/browser/browser_mac.mm
- spec-main/api-app-spec.ts
Refs #30485.
Added an API to check if the app is hidden on macOS. This is a distinct state from the app _windows_ being hidden, and can be used to implement unique behaviour on activation. It is also useful in conjunction with `NSWindow.canHide`, which I will introduce in a follow-up MR if there are no objections.
Notes: Added `app.isHidden()` to check if the app is hidden (e.g. with Command-H) on macOS.
> feat: add app.isHidden API for macOS

- shell/browser/electron_browser_main_parts.cc
- shell/common/node_bindings.cc
- shell/common/node_bindings.h
- shell/common/node_bindings_linux.cc
- shell/common/node_bindings_linux.h
- shell/common/node_bindings_mac.cc
- shell/common/node_bindings_mac.h
- shell/common/node_bindings_win.cc
- shell/common/node_bindings_win.h
- shell/renderer/electron_renderer_client.cc
- shell/renderer/web_worker_observer.cc
In the node integration code, on Linux and macOS we have code checking whether the backend fd is changed to prevent duplicate initializations. But since the backend fd of default uv loop is never changed, the code is essentially just preventing double initialization, which is identical to the Windows code.
This PR removes redundant check of backend fd and changes the code to use same routine on all platforms.
The code was introduced in https://github.com/electron/electron/pull/25869 and #27582, and I can verify the original issues are not regressed.
Notes: none
> chore: remove redundant code in node integration

- .circleci/build_config.yml
- patches/node/build_add_gn_build_files.patch
- script/node-disabled-tests.json
Re-enable disabled `parallel/test-child-process-stdio-overlapped` spec. This was previously disabled owing to the fact that it relied on a small test executable being build in `node.gyp`, which we didn't build. Fixed this by building the executable as a component of the node tests in CI.
Notes: none
> test: re-enable `test-child-process-stdio-overlapped`

- appveyor.yml
Sometimes Appveyor has trouble uploading artifacts and this causes a build to be marked as failing when really the only thing that failed was saving artifacts to Azure storage.  Since these artifacts are not necessary to determine whether a build was successful or not, this PR moves the uploads of the artifacts AFTER the tests instead of before the tests.  This means that now the tests will run first and will not be blocked by artifact uploads failing.
Notes: none
> ci: save Windows artifacts at end of job in case they fail

- BUILD.gn
- chromium_src/BUILD.gn
- shell/app/electron_content_client.cc
- shell/browser/electron_api_ipc_handler_impl.h
- shell/browser/electron_browser_client.cc
- shell/browser/electron_web_contents_utility_handler_impl.h
- shell/common/electron_constants.cc
- shell/common/electron_constants.h
- shell/renderer/renderer_client_base.cc
Cleanup from https://github.com/electron/electron/pull/33091 and also uses reuses constants from upstream where possible.
> fix: build when pdf component is disabled

- shell/browser/native_window_mac.h
- shell/browser/native_window_mac.mm
- spec-main/api-browser-window-spec.ts
Closes https://github.com/electron/electron/issues/33329.
Fixes an issue where a BrowserWindow would inexplicably become tiny if `BrowserWindow.unmaximize()` was called when the last set bounds were the size of the screen.
Per [docs](https://developer.apple.com/documentation/appkit/nswindow/1419513-zoom?language=objc) during `zoom:`:
> If there’s no saved user state because there has been no previous
> zoom,the size and location of the window don’t change.
However, in classic Apple fashion, this is not the case in practice, and the frame inexplicably becomes very tiny. We should prevent zoom from being called if the window is being unmaximized and its unmaximized window bounds are themselves functionally maximized.
Notes: Fixed an issue where the the window bounds would incorrectly change …
> fix: don't unmaximize on macOS if user set max bounds

- patches/v8/.patches
- patches/v8/cherry-pick-a1427aad7cef.patch
Assert that we never copy properties from an object itself
When copying properties, it should never happen that source == target.
Add a CHECK to assert this assumption.
Bug: chromium:1260129
Change-Id: Ia5248e4363d85e13052db726fb7143897cea9c87
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/3226779
Commit-Queue: Patrick Thier <pthier@chromium.org>
Cr-Commit-Position: refs/heads/main@{#77418}
Notes: Security: backported fix for chromium:1260129.
> chore: cherry-pick a1427aad7cef from v8

- docs/api/app.md
It was accidentally added to public docs in https://github.com/electron/electron/pull/19480 and there is no description of it there. If we really want to expose this path, we should give it a more detailed name as it is hard to tell whether this path points to `/tmp` or `~/.cache`.
Note that `cache` and `userCache` paths were added in Electron a long time ago and there are already some apps using them, so we can not remove them in code. They were not added to public docs because Electron does not support changing path of browser cache so exposing the paths would cause confusions.
Notes: none
> docs: remove "cache" from app.getPath

- shell/browser/api/electron_api_app.cc
- spec-main/api-app-spec.ts
- spec/fixtures/api/singleton-userdata/main.js
- spec/fixtures/api/singleton-userdata/package.json
- spec/fixtures/api/singleton/main.js
Closes #33547.
Regression introduced by https://github.com/electron/electron/pull/30594. The patch removed the behavior of [creating the `userData` folder](https://github.com/electron/electron/blob/5554de0237cd029a38806405ca771c57db529fa1/chromium_src/chrome/browser/process_singleton_posix.cc#L720) if needed. Without it, the single instance lock cannot be aquired and `app.requestSingleInstanceLock()` incorrectly returns false on first start of the app.
This PR restores the behavior from Electron 15 and below (= before the refactor landed). Test to prevent future regressions added as well ☺️ .
cc @magom001 @miniak @rzhao271
Notes: Fixed incorrect return value of `app.requestSingleInstanceLock()` when setting non-existent user data folder.
> fix: create `userData` on requestSingleInstanceLock() if needed

- docs/api/browser-window.md
Cleaning up spots where `BrowserWindow` platform-specific functionality wasn't being marked with the italics notation.
Notes: none
> docs: mark platform-specific functionality for BrowserWindow

- package.json
- script/lib/azput.js
- script/lib/util.py
- script/release/release.js
- script/release/uploaders/upload-index-json.py
- script/release/uploaders/upload-node-checksums.py
- script/release/uploaders/upload-node-headers.py
- script/release/uploaders/upload-symbols.py
- script/release/uploaders/upload.py
- yarn.lock
This duplicates our upload logic so that all files are uploaded to both S3 and our new AZ storage containers.  This patch also switches our checksum generation logic to use the AZ storage container exclusively.
> build: upload to AZ as well as S3

- shell/browser/native_window_views.cc
Reverts electron/electron#32692
I agree with [this](https://github.com/electron/electron/issues/32981#issuecomment-1083938180), the original bug is solvable by following best practices.  The new bugs are worse and not solvable by end users.
Notes: Fixes issues with frameless window animations and styling
> fix: revert "fix: some frameless windows showing a frame on Windows"

- electron_strings.grdp
Fixes https://sentry.io/share/issue/be7de46ea41d4628ac692dadc5a8248d/
Notes: Fixed potential crash while generating accessibility trees for certain images
> fix: add missing translation string for ax tree

- spec-main/api-browser-window-spec.ts
- #33523 was merged without Windows CI running.  It appears that #33523 introduced a test that fails on Windows in 15-x-y.  This PR disables that test.  cc @dsanders11.
Notes: none
> test: disable newly added/failing test on Windows

- patches/v8/.patches
- patches/v8/cherry-pick-f599381978f2.patch
[M96-LTS][runtime] Fix handling of interceptors, pt.3
... in JSObject::DefineOwnPropertyIgnoreAttributes().
Don't execute interceptor again if it declined to handle the operation.
(cherry picked from commit c4e66b89b4ecd0e90b31e9e4ed08d38085a84c49)
Bug: chromium:1311641
No-Try: true
Change-Id: Ie9aef5a98959403f6a26e6bef7f4a77d312bd62a
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/3568921
Reviewed-by: Lutz Vahl <vahl@chromium.org>
Cr-Commit-Position: refs/branch-heads/9.6@{#56} …
> chore: cherry-pick f599381978f2 from v8

- docs/api/browser-window.md
Close https://github.com/electron/electron/issues/33581.
As noticed by https://github.com/electron/electron/issues/33581, the document is both recommending and not recommending to set the `event.returnValue` directly.
Notes: none
> docs: recommend setting e.returnValue

- patches/chromium/.patches
- patches/chromium/use_numpy_1_2x_supported_1_for_vpython.patch
Backport https://chromium-review.googlesource.com/c/chromium/src/+/3459767
Fixes the following issue preventing building on Apple Silicon Macs:
```
#0 go.chromium.org/luci/cipd/client/cipd/ensure/file.go:255 - ensure.(*File).Resolve.func1.1()
reason: failed to resolve infra/python/wheels/numpy/mac-arm64_cp38_cp38@version:1.20.3 (line 0)
```
Notes: none
> build: fix numpy package install on mac arm64

- shell/common/platform_util_win.cc
Report more detailed errors in `shell.openExternal()` on Windows.
Before:
> Error: Failed to open
After:
> Error: Failed to open: The system cannot find the file specified. (0x2)
Notes: `shell.openExternal()` now reports more detailed errors on Windows.
> fix: report more detailed errors in shell.openExternal() on Windows

- appveyor.yml
- script/release/release.js
- script/release/uploaders/upload.py
- As documented in #33652, symbol generation is failing on 32-bit Windows release builds.  This PR temporarily disables symbol generation on 32-bit Windows so that we can get nightlies and 19 alphas published.  We will need to resolve this issue before 19 goes stable, but this will at least allow us to publish releases in the meantime.
Notes: Temporarily disabled symbol generation on 32-bit Windows due to issues with symbol generation on that platform.
> build: temporarily disable 32-bit Windows symbol generation

- patches/config.json
- patches/skia/.patches
- patches/skia/fix_when_a_glyph_has_a_path.patch
https://newpulselabs.com/emoji-black-white-chrome/
> If you have an emoji inside of a bold text element, the emoji will show up monochrome/black & white instead of its normal colour.
Fixes: https://bugs.chromium.org/p/chromium/issues/detail?id=1266022
Backport: https://skia-review.googlesource.com/c/skia/+/482076
To repro, just add this to the document:
```html
<p style="font-weight: bold;">😀 😃 😄 😁 😆 😅 😂 🤣 🥲 ☺️ 😊 😇 🙂 🙃 😉 😌 😍 🥰 😘 😗 😙 😚 😋 😛 😝 😜 🤪 🤨 🧐 🤓 😎 🥸 🤩 🥳 😏 😒 😞 😔 😟 😕 🙁 ☹️ 😣 😖 😫 😩 🥺 😢 😭 😤 😠 😡 🤬 🤯 😳 🥵 🥶 😱 😨 😰 😥 😓 🤗 🤔 🤭 🤫 🤥 😶 😐 😑 😬 🙄 😯 😦 😧 😮 😲 🥱 😴 🤤 😪 😵 🤐 🥴 🤢 🤮 🤧 😷 🤒 🤕 🤑 🤠 😈 👿 👹 👺 🤡 💩 👻 💀 ☠️ 👽 👾 🤖 🎃 😺 😸 😹 😻 😼 😽 🙀 😿 😾</p>
```
Before:
After:
Notes: Fixed emojis appearing black and white in Chromium 96.
> fix: emojis appearing black and white in Chromium 96

- appveyor.yml
- script/release/release.js
- script/release/uploaders/upload.py
Follows #33653 - this PR modifies the assets in the validation check to not include the ia32 pdb.zip (dependent on symbols.zip). It also fixes a logical error that led to other assets [not being properly uploaded](https://my.papertrailapp.com/events?focus=1449117079501893636&q=program%3Aapp%2Fweb.1&selected=1449117079501893637).
Notes: none
> chore: modify uploaded assets for win-ia32

- appveyor.yml
- script/release/release.js
- script/release/uploaders/upload.py
Manual backport of #33653
Notes: Temporarily disabled symbol generation on 32-bit Windows due to issues with symbol generation on that platform.
> build: temporarily disable 32-bit Windows symbol generation (#33653)

- docs/api/extensions.md
- shell/browser/extensions/api/tabs/tabs_api.cc
- shell/browser/extensions/api/tabs/tabs_api.h
- shell/common/extensions/api/tabs.json
Closes https://github.com/electron/electron/issues/33519.
Addresses a failure introduced by CL:3501416, whereby if a PDF failed to load:
and a user then clicked the `Reload` button, the following error would be seen in console:
> [86492:0331/154624.774205:INFO:CONSOLE(2251)] "Uncaught TypeError: chrome.tabs.reload is not a function", source: chrome-extension://mhjfbmdgcfjbbpaeojofohoefgiehjai/pdf_viewer_wrapper.js (2251)
This is fixed by implementing `chrome.tabs.reload`. Given it's `semver-minor` as a change, I think we should likely document it as we would if we were implementing it standalone.
Note: needs tests.
Notes: Fixed an issue where the PDF Viewer would fail if a user attempted to reload.
> feat: implement chrome.tabs.reload to fix PDF Viewer error

- docs/development/build-instructions-linux.md
- docs/development/build-instructions-macos.md
- docs/development/coding-style.md
- package.json
- script/check-relative-doc-links.py
`python` no longer exists on macOS Monterey.
Notes: none
> build: use python3 to lint

- patches/webrtc/.patches
- patches/webrtc/cherry-pick-a18fddcb53e6.patch
Filter out Mac StatusIndicator window from desktop capture list
Since 12.2, the orange/red indicator at the top right of the screen shows up as a window in the Chrome getDisplayMedia() picker, as it's not filtered out by the existing filters. Screenshots in the bug.
Bug: chromium:1297731, b/218211225
Change-Id: I0f87e8d2af42a5a2e3d84f69fe73596e9cf35622
Reviewed-on: https://webrtc-review.googlesource.com/c/src/+/251841
Reviewed-by: Alexander Cooper <alcooper@chromium.org>
Commit-Queue: Tony Herre <herre@google.com>
Cr-Commit-Position: refs/heads/main@{#36350}
Notes: Backported fix for chromium:1297731, b/218211225.
> chore: cherry-pick a18fddcb53e6 from webrtc

- patches/chromium/.patches
- patches/chromium/cherry-pick-4d26949260aa.patch
Don't interpret informational response body as HTTP/0.9 response
An informational (1xx) response with body can be interpreted as an
informational response followed by an HTTP/0.9 response. It is confusing
so let's stop doing that.
Bug: 1291482
Change-Id: Ic3823838614330d761f11360a783859e5baa260e
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3428433
Reviewed-by: Matt Menke <mmenke@chromium.org>
Reviewed-by: Kenichi Ishibashi <bashi@chromium.org>
Reviewed-by: Mike West <mkwst@chromium.org>
Commit-Queue: Yutaka Hirano <yhirano@chromium.org>
Cr-Commit-Position: refs/heads/main@{#967169}
Notes: Backported fix for chromium:1291482.
> chore: cherry-pick 4d26949260aa from chromium

- patches/chromium/.patches
- patches/chromium/fix_--without-valid_build.patch
- patches/chromium/use-after-free_of_id_and_idref_attributes.patch
Commit 652dd12a  authored 1 month ago by [Nick Wellnhofer](https://gitlab.gnome.org/nwellnhof)'s avatar Nick Wellnhofer
[CVE-2022-23308] Use-after-free of ID and IDREF attributes
If a document is parsed with XML_PARSE_DTDVALID and without
XML_PARSE_NOENT, the value of ID attributes has to be normalized after
potentially expanding entities in xmlRemoveID. Otherwise, later calls
to xmlGetID can return a pointer to previously freed memory.
ID attributes which are empty or contain only whitespace after
entity expansion are affected in a similar way. This is fixed by
not storing such attributes in the ID table.
The test to detect streaming mode when validating against a DTD was
broken. In connection with the defects above, this could result in a
use-after-free when using the xmlReader …
> chore: cherry-pick 652dd12a and d05317ce from libxml

- patches/config.json
- patches/pdfium/.patches
- patches/pdfium/cherry-pick-a48de319c521.patch
Use safe arithmetic in CJBig2_Context::ParseSymbolDict()
These should be mitigated by size checks higher up, but it wouldn't
hurt to be sure.
Bug: chromium:1280743
Change-Id: I03c46e3d11316a9f9634256bd0e2394548d2681e
Reviewed-on: https://pdfium-review.googlesource.com/c/pdfium/+/88290
Notes: Security: backported fix for chromium:1280743.
> chore: cherry-pick a48de319c521 from pdfium

- spec-main/api-web-contents-spec.ts
- spec-main/chromium-spec.ts
Re-enable specs disabled in https://github.com/electron/electron/issues/31555 - Chromium has addressed this issue and these tests now pass locally.
Notes: none.
> test: re-enable disabled ScriptOrModule specs

- docs/api/safe-storage.md
Closes https://github.com/electron/electron/issues/33640.
Notes: none.
> docs: note `safeStorage.isEncryptionAvailable()` needs ready event

- script/release/uploaders/upload-index-json.py
Follow up to #33720, which changed scripts to explicitly run with Python 3. The [urllib2](https://docs.python.org/2/library/urllib2.html#module-urllib2) module has been split across several modules in Python 3 named urllib.request and urllib.error. This PR migrates those imports to the Python 3 modules.
Notes: none
> build: migrate urllib to python3

- docs/tutorial/ipc.md
Backport of #32059
This is stupid, but I messed up the backporting for https://github.com/electron/electron/pull/32059 because the PR was open for too long and I missed a more recent branch.
The doc already exists on 17-x-y, 19-x-y, and main, but not 18-x-y. I just copied the raw file from `main` and pasted it here.
notes: none
> docs: manually backport ipc doc

- shell/common/color_util.cc
Fixes an issue where `#ARGB` ->`#RGBA` and `#AARRGGBB` ->`#RRGGBBAA` were converted improperly when setting background color.
Notes: Fixed an issue where `#ARGB` ->`#RGBA` and `#AARRGGBB` ->`#RRGGBBAA` were converted improperly when setting background color.
> fix: #ARGB to #RGBA conversion

- script/release/uploaders/upload.py
Follow up to #33699 - fixes an `or` in symbol logic that was mistakenly changed on the wrong line during backporting.
Notes: none
> build: filter symbols/json correctly per arch

- patches/chromium/.patches
- patches/chromium/cherry-pick-1665a1d16d46.patch
Reland "Make web cursor size limits match on browser and renderer"
This reverts commit 38a8343085e53889eba48fcff78a6c2295927333.
Reason for revert: Fix without regressing https://crbug.com/1292426
(Increased WebCursor limit 128->150px to support DevToolsEyeDropper)
> Revert "Make web cursor size limits match on browser and renderer"
>
> This reverts commit 868b44dd8b4a1a3b9698f561ca17f75e4ec78dd2.
>
> Reason for revert: https://crbug.com/1292426
>
> Original change's description:
> > Make web cursor size limits match on browser and renderer
> >
> > Use NSCursor arrowCursor on Mac for ui::mojom::CursorType::kNull.
> > (i.e. when WebCursor is constructed with an overly large custom cursor)
> >
> > Bug: 1246188
> > Test: Automated unit tests and WPTs
> > …
> chore: cherry-pick 1665a1d16d46 from chromium

- docs/api/system-preferences.md
- shell/browser/api/electron_api_system_preferences.h
- shell/browser/api/electron_api_system_preferences_mac.mm
- spec-main/api-system-preferences-spec.ts
Closes https://github.com/electron/electron/issues/33632.
Allows for `systemPreferences.subscribe{Local|Workspace}Notification` methods to take `null` for their event parameters.
Per [documentation](https://developer.apple.com/documentation/foundation/nsdistributednotificationcenter/1414136-addobserver):
> When nil, the notification center doesn’t use a notification’s name to decide whether to deliver it to the observer.
cc @knev 
Notes: Enabled `systemPreferences.subscribe{Local|Workspace}Notification` to take a `null` value for the `event` parameter.
> feat: allow `null` when subscribing notification

- script/release/uploaders/upload-index-json.py
Follow up to Python 3 changes, we need to explicitly pass in "binary" as an open option in order to read the file.
Notes: none
> chore: interpret bytes and string args on python3 open

- lib/browser/api/web-contents.ts
- spec-main/api-ipc-spec.ts
Fixes https://github.com/electron/electron/issues/33722
Missed in https://github.com/electron/electron/pull/26764
Notes: apply senderFrame details to ipcMain port event
> fix: apply senderFrame details to ipcMain port event

- patches/v8/.patches
- patches/v8/cherry-pick-f546ac11eec7.patch
[M96-LTS][super IC] Turn off super ICs
Conflicts in the bytecode test expectations
They make assumptions which don't hold for API handlers.
(cherry picked from commit c6b68cbfbd49a24bd9d343d718132125370da729)
Bug: v8:9237,chromium:1308360
No-Try: true
Change-Id: I9f122c4e75a24d83ef3653cbf7a223ed522e4d13
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/3548899
Commit-Queue: Marja Hölttä <marja@chromium.org>
Cr-Original-Commit-Position: refs/heads/main@{#79614}
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/3553109
Cr-Commit-Position: refs/branch-heads/9.6@{#60} …
> chore: cherry-pick f546ac11eec7 from v8

- .circleci/build_config.yml
On April 13, CircleCI updated their MacOS executor image to use xcode 13.3.1, which [does not include Python2 by default](https://circle-macos-docs.s3.amazonaws.com/image-manifest/cci-macos-production-2718/index.html). This PR temporarily builds python2 using a custom homebrew tap until we can migrate build scripts entirely to python3.
Notes: none
> ci: manually install python2

- patches/chromium/.patches
- patches/chromium/cherry-pick-a1dc371d6680.patch
usb: Fix OOB access with non-sequential interfaces
When accessing a usb device with non-sequential interface number or
alternative setting value, it might end up using index out of the
internal array allocated size. It is caused by using incorrect
parameters (i.e interface_number and alternate_setting) into the
callback which expects taking interface_index and alternate_index. Fix
it by passing the correct parameters which are already available in the
function to the callback.
Bug: 1286816
Change-Id: I6b3533f944f94e94e63959b99718858e089449da
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3384715
Reviewed-by: Reilly Grant <reillyg@chromium.org>
Commit-Queue: Jack Hsieh <chengweih@chromium.org>
Cr-Commit-Position: refs/heads/main@{#961679}
Notes: Backported fix for …
> chore: cherry-pick a1dc371d6680 from chromium

- shell/browser/api/electron_api_web_contents.cc
Closes https://github.com/electron/electron/issues/33721.
Fixes an issue where `Escape` keyboard events would not be properly propagated to the parent window after entering fullscreen and then exiting it again on Windows.
This was happening as a result of calling `SetHtmlApiFullscreen(false)` _prior_ to calling `exclusive_access_manager_->fullscreen_controller()->ExitFullscreenModeForTab(source)`. This created a race condition, wherein some platforms like macOS would work correctly becuase by the time [`!exclusive_access_context->IsFullscreen()`](https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/ui/exclusive_access/fullscreen_controller.cc;l=237) was called, it wouldn't yet be true on macOS, and [`NotifyTabExclusiveAccessLost`](https://source.chromium.org/chromium/chr …
> fix: event propagation after exiting fullscreen on Windows

- .circleci/build_config.yml
Improves on our previous change to add python2 back into CircleCI images - this PR now builds python2 from source rather than via homebrew, per CircleCI's [updated recommendations](https://discuss.circleci.com/t/xcode-13-3-1-released/43675).
_Note: The publish-mac job is currently failing - this is a known issue with CircleCI's new 13.3.1 image and disk space, and will be fixed on their end._
Notes: none
> ci: build python2 from source

- patches/chromium/.patches
- patches/chromium/fix_--without-valid_build.patch
- patches/chromium/use-after-free_of_id_and_idref_attributes.patch
Commit 652dd12a  authored 1 month ago by [Nick Wellnhofer](https://gitlab.gnome.org/nwellnhof)'s avatar Nick Wellnhofer
[CVE-2022-23308] Use-after-free of ID and IDREF attributes
If a document is parsed with XML_PARSE_DTDVALID and without
XML_PARSE_NOENT, the value of ID attributes has to be normalized after
potentially expanding entities in xmlRemoveID. Otherwise, later calls
to xmlGetID can return a pointer to previously freed memory.
ID attributes which are empty or contain only whitespace after
entity expansion are affected in a similar way. This is fixed by
not storing such attributes in the ID table.
The test to detect streaming mode when validating against a DTD was
broken. In connection with the defects above, this could result in a
use-after-free when using the xmlReader …
> chore: cherry-pick 652dd12a and d05317ce from libxml 

- BUILD.gn
- patches/chromium/make_gtk_getlibgtk_public.patch
Fix ci regression caused by 37b7e347fce555836d694f36f6ee5e2ea67db049
> chore: fix patch conflicts from 37b7e347

- docs/api/context-bridge.md
- docs/breaking-changes.md
- docs/tutorial/security.md
These docs don't align with our recommendations, context isolation should be enabled for all content not just specifically remote content.
Closes #33806
> docs: update security guide regarding ctx isolation

- docs/api/browser-view.md
- docs/api/browser-window.md
We already document such info for other APIs, like the `'screen'` API in
https://github.com/electron/electron/blob/f711fe6b5701196e5d803c04aab44bc62b392f8e/docs/api/screen.md?plain=1#L7-L8. So we should do the same thing for these ones too.
Notes: none
> docs: document when `BrowserWindow` and `BrowserView` can be used

- electron_paks.gni
Backport of #33840
Notes: Fixed crash when img without `alt` is shown with accessibility features enabled
> fix: include accessibility blink strings

- .github/workflows/semantic.yml
The semantic commit checker is
[down](https://github.com/zeke/semantic-pull-requests/issues/183), and not for
the first time. Let's switch to using GitHub Actions.
Notes: none
> chore: use semantic-commit-action

- shell/browser/electron_api_ipc_handler_impl.h
- shell/browser/electron_web_contents_utility_handler_impl.h
Related to #33602 and #33664
Notes: none
> fix: building with printing disabled

- patches/v8/.patches
- patches/v8/cherry-pick-b2d3ef69ef99.patch
[M96-LTS][compiler] mark receiver and function as escaping
(cherry picked from commit 8081a5ffa7ebdb0e5b35cf63aa0490ad3578b940)
Bug: chromium:1315901
No-Try: true
Change-Id: Ic44bfcae32aba202ba25c5f59fe579214a444584
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/3584117
Cr-Original-Commit-Position: refs/heads/main@{#79968}
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/3584531
Reviewed-by: Tobias Tebbi <tebbi@chromium.org>
Cr-Commit-Position: refs/branch-heads/9.6@{#62} …
> chore: cherry-pick b2d3ef69ef99 from v8

- BUILD.gn
- shell/app/electron_main_mac.cc
Refs
https://chromium-review.googlesource.com/c/chromium/src/+/3298858
https://chromium-review.googlesource.com/c/chromium/src/+/3314829
Found when looking into https://bugs.chromium.org/p/chromium/issues/detail?id=1255223
Might address the sqlite crash from https://github.com/electron/electron/issues/32406
Notes: fix initialization race when registering partition allocator on macOS
> fix: adopt partition alloc early initialization for macOS

- patches/chromium/.patches
- patches/chromium/m100_change_ownership_of_blobbytesprovider.patch
M100: Change ownership of BlobBytesProvider.
Rather than immediately passing ownership to a cross-thread
SelfOwnedReceiver while retaining a raw pointer, instead maintain
ownership in a unique_ptr as long as it is needed, only transferring
ownership to a SelfOwnedReceiver when BlobData is done with the
BlobBytesProvider.
Also clean-up/tighten down sequence checks for BlobBytesProvider a bit.
(cherry picked from commit 7222e9825fc02acc962e005c59885ee2f26df185)
Bug: 1285234
Change-Id: I7273e886a0bab2ae489b680d786991c9e4ff1dbb
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3553304
Cr-Original-Commit-Position: refs/heads/main@{#986111}
Reviewed-on: …
> chore: cherry-pick 5cb934a23d from chromium

- patches/chromium/.patches
- patches/chromium/cherry-pick-5cb934a23ddf.patch
M100: Change ownership of BlobBytesProvider.
Rather than immediately passing ownership to a cross-thread
SelfOwnedReceiver while retaining a raw pointer, instead maintain
ownership in a unique_ptr as long as it is needed, only transferring
ownership to a SelfOwnedReceiver when BlobData is done with the
BlobBytesProvider.
Also clean-up/tighten down sequence checks for BlobBytesProvider a bit.
(cherry picked from commit 7222e9825fc02acc962e005c59885ee2f26df185)
Bug: 1285234
Change-Id: I7273e886a0bab2ae489b680d786991c9e4ff1dbb
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3553304
Cr-Original-Commit-Position: refs/heads/main@{#986111}
Reviewed-on: …
> chore: cherry-pick 5cb934a23ddf from chromium

- patches/chromium/feat_add_data_transfer_to_requestsingleinstancelock.patch
Backport of https://github.com/electron/electron/pull/33777
Fixes #33736
CC @nornagon @deepak1556 
Notes: Fixed an issue with the `app.requestSingleInstanceLock()` API where it would sometimes hang.
> fix: requestSingleInstanceLock API sometimes hangs

- BUILD.gn
- shell/app/electron_main_mac.cc
This is fixing random build failures that we ran into in our internal Electron builds.
Notes: none
> build: fix intermittent compilation failures on macOS

- patches/chromium/.patches
- patches/chromium/cherry-pick-1a31e2110440.patch
[css-typed-om] Disallow CSS-wide keywords for StylePropertyMap.set
We don't support this properly, and the spec does not handle CSS-keywords
either. Disallow it until we can add proper support for this.
(cherry picked from commit 02e4b18febb37de8baea718bc2f62cfb5fe56e23)
Fixed: 1292905
Bug: 1310761
Change-Id: Ieb3d20edfea72c2ccb0928536fdfd86d10aad1a9
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3551609
Reviewed-by: Rune Lillesveen <futhark@chromium.org>
Commit-Queue: Anders Hartvoll Ruud <andruud@chromium.org>
Cr-Original-Commit-Position: refs/heads/main@{#986411}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3572186
Commit-Queue: Srinivas Sista <srinivassista@chromium.org>
Auto-Submit: Srinivas Sista <srinivassista@chromium.org> …
> chore: cherry-pick 1a31e2110440 from chromium

- patches/v8/.patches
- patches/v8/cherry-pick-2004594a46c8.patch
[M96-LTS][turbofan] Fix NumberConstant used with Word32 rep in ISel
Bug: chromium:1304658
(cherry picked from commit bbea5909c797dec7c620b9fee43d80a1420c2e08)
No-Try: true
Change-Id: I6a82603a7c5de5ae8f5a895990c1a904bbdd39b2
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/3532263
Auto-Submit: Nico Hartmann <nicohartmann@chromium.org>
Cr-Original-Commit-Position: refs/heads/main@{#79526}
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/3541919
Cr-Commit-Position: refs/branch-heads/9.6@{#58} …
> chore: cherry-pick 2004594a46c8 from v8

- BUILD.gn
- #33731 broke macOS release GN generation due to a typo.  This PR fixes that issue.
Notes: none
> build: fix macos release GN gen

- patches/chromium/sysroot.patch
Use the new az storage account for our sysroots, the sysroot image creator has been updated to upload to this account.  As a bonus this is behind a CDN so downloads of the sysroot should be quicker 👍 
> build: use dev-cdn instead of sysroots s3 bucket

- .circleci/config/base.yml
- BUILD.gn
- script/node-disabled-tests.json
* Rely on src cache instead of workspace
* Run some tasks in the background and "thread join" later
* Merge some ninja build commands to reduce overhead
This drops average CI execution of the `build` jobs on linux from ~14 minutes to ~10 minutes and drops the unhappy build cost by almost 80%.  Explanation below:
We used to checkout code in two different ways in testing CI "make-src-cache" which populates the `src-cache` bucket and `checkout-for-workspace` which _might_ use the src cache but eventually ends up populating a workspace layer with the checkout.  For historical reasons we used `src-cache` for builds and `workspace` for GN checks, this no longer makes any sense.  The build graph for both platforms now looks like this
```
/ -- build-arch-2
make-src-cache ----- | -- build-arch-1
\ …
```
> build: improve CI speeds and reduce CI costs

- script/release/release.js
No idea why the linter didn't warn about the unused variable
> build: actually verify az urls too

- .circleci/config/base.yml
There's an edge case where this marker file doesn't exist and therefore the git cache push doesn't work because the cachekey can't be calculated
> build: ensure sync-done file exists during git cache save

- docs/api/app.md
Before:
```ts
setJumpList(categories: (JumpListCategory[]) | (null)): void;
```
After:
```ts
setJumpList(categories: (JumpListCategory[]) | (null)): ('ok' | 'error' | 'invalidSeparatorError' | 'fileTypeRegistrationError' | 'customCategoryAccessDeniedError');
```
Fixes: https://github.com/electron/electron/issues/33909
Notes: none
> docs: fix return type of setJumpList() in electron.d.ts

- .circleci/config/base.yml
As noted in #33904 with Goma and other CI improvements we really don't need to be burning a 20 core machine.  Some super basic testing shows that dropping from the 20 core machine to an 8 core machine _increases_ CI time by ~30-90 seconds, I don't think that is going to be the end of the world for anyone especially when the above mentioned PR speeds CI up by over double that 🤷 
This should drop our linux credit usage by almost ~50% ✨ 🥳 
Changes:
* Testing builds now use 8 core instead of 20 core
* Unused release jobs deleted
* Publish builds now use 16 core instead of 20 core
> build: use smaller resource_class because goma

- patches/webrtc/.patches
- patches/webrtc/adding_fuzzer_for_pcm16b_decoder_and_fixing_a_fuzzer_problem.patch
Adding fuzzer for PCM16b decoder and fixing a fuzzer problem
Bug: [chromium:1280852](https://bugs.chromium.org/p/chromium/issues/detail?id=1280852)
Change-Id: [I7f6c5de86ceee01156743c0389c59f875e53bb5f](https://webrtc-review.googlesource.com/q/I7f6c5de86ceee01156743c0389c59f875e53bb5f)
Reviewed-on: https://webrtc-review.googlesource.com/c/src/+/251580
Reviewed-by: Minyue Li <[minyue@webrtc.org](mailto:minyue@webrtc.org)>
Commit-Queue: Henrik Lundin <[henrik.lundin@webrtc.org](mailto:henrik.lundin@webrtc.org)>
Cr-Commit-Position: refs/heads/main@{#36005}
Notes: Security: backported fix for chromium:1280852.
> chore: cherry-pick ac341df436 from webrtc

- shell/browser/resources/mac/Info.plist
- shell/common/resources/mac/Info.plist
- shell/renderer/resources/mac/Info.plist
Upstream change: https://chromium-review.googlesource.com/c/chromium/src/+/1137131/
Not disabling nano malloc zone not only causes the issues listed in https://bugs.chromium.org/p/chromium/issues/detail?id=861939, but also breaks Partition Alloc.
This change should fix #32718 making it possible to get rid of #33114.
Notes: [Mac] Fixed Partition Alloc related crash in pre-BigSur (macos <= 10.15).
> fix: [Mac] Disable MallocNanoZone

- patches/chromium/.patches
- patches/chromium/cherry-pick-38ab9c5b06a4.patch
[M96-LTS] Use IsErrorDocument() to prevent BFCacheing of interstitials and errors.
Tests not present on M96:
- back_forward_cache_basics_browsertest.cc
- back_forward_cache_browsertest.h
- back_forward_cache_internal_browsertest.cc
chrome_track_event.proto:
- changed code (tracing) doesn't exist on M96, discarded
all changes
back_forward_cache_browsertest.cc:
- conflicting includes
- removed NavigateAndBlock, which would be called on
on back_forward_cache_browsertest.cc (not present in M96)
page_handler.cc:
- conflicting case statements on NotRestoredReasonToProtocol
back_forward_cache_can_store_document_result.cc:
- NotRestoredReasonToTraceEnum not present on M96
- conflicting case statements on NotRestoredReasonToString
back_forward_cache_metrics.h:
- conflicting …
> chore: cherry-pick 38ab9c5b06a4 from chromium

- shell/browser/ui/views/frameless_view.cc
- shell/browser/ui/views/frameless_view.h
- shell/browser/ui/views/win_frame_view.cc
- shell/browser/ui/views/win_frame_view.h
Follow-up to https://github.com/electron/electron/pull/33029.
A more robust way of addressing https://github.com/electron/electron/issues/32681 - instead of blocking the client view's event handling logic we should instead more effectively target and redirect events as they come in.
Tested with https://gist.github.com/4256f388d41ef0d974645a11ab72b1fe
Notes: none
> refactor: better solution for resizable frameless DCHECK

- shell/browser/net/system_network_context_manager.cc
Initialization for FirstPartySets was [removed in a recent Chromium roll](https://github.com/electron/electron/pull/33454/commits/00465d5d62e06e15f84ec42218dbc2c8cbcca691). 
This PR re-adds the FPS initialization, and updates it based on the Chromium updates from that CL.
Notes: Fixed the initialization of First Party Sets
> fix: fix FirstPartySetsHandler initialization

- script/release/uploaders/upload-index-json.py
After changing our scripts to run on python3 (#33720), we needed to apply a fast follow to urllib to get it working with the new version of python (#33737). However, the python3 migration was only backported through 16-x-y. The urllib fix was backported through 15-x-y. 
This PR reverts the fix (commit a29136950e87a64e69c1e2e8965f7d45acc1a2dc), since 15-x-y is still running python 2 and it does not apply.
> build: revert migrate urllib to python3

- spec/static/main.js
Some ports are considered to be "unsafe" by Chromium, but Windows on Microsoft-hosted agents sometimes assigns one of them to a Node.js server. Chromium refuses to establish a connection and the whole app crashes with the "Error: net::ERR_UNSAFE_PORT" error.
Let's allow connections to those ports to avoid test failures.
Use a comma-separated list of ports as a flag value, e.g. "666,667,668".
https://source.chromium.org/chromium/chromium/src/+/main:net/base/port_util.cc
Notes: none
> test: allow connections to port 2049

- shell/browser/electron_browser_main_parts.cc
- shell/browser/net/system_network_context_manager.cc
In this CL, First Party Sets initialization was moved to the [content layer](https://source.chromium.org/chromium/chromium/src/+/main:content/browser/browser_main_loop.cc;l=987-997): https://chromium-review.googlesource.com/c/chromium/src/+/3448551 . We still need to initialize an empty sets file within Electron's equivalent PreMainMessageLoopRun method. However, our First Party Set initialization is currently in the wrong place.
This PR moves Electron's First Party Sets initialization to the PreMainMessageLoopRun method.
Notes: Fixed the initialization of first party sets in the browser process.
> fix: move FirstPartySets initialization into the browser process

- shell/browser/ui/file_dialog_gtk.cc
Closes https://github.com/electron/electron/issues/33844.
Notes: Fixed an issue where mixed-case extension filters in file dialogs were ignored on Linux.
> fix: support mixed-case extensions in Linux file dialogs

- patches/chromium/.patches
- patches/chromium/cherry-pick-5361d836aeb1.patch
[M96-LTS] Add bounds check to WebGPUDecoderImpl::DoRequestDevice
(cherry picked from commit bee4701c99cbbbb25c0bd6c5c79a40f63f1b1e47)
Fixed: chromium:1314754
Change-Id: Id23af9cc3df08cca3ce7d627e3761c9a65a2c802
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3580555
Commit-Queue: Austin Eng <enga@chromium.org>
Cr-Original-Commit-Position: refs/heads/main@{#991510}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3589810
Cr-Commit-Position: refs/branch-heads/4664@{#1603}
Cr-Branched-From: 24dc4ee75e01a29d390d43c9c264372a169273a7-refs/heads/main@{#929512}
Notes: …
> chore: cherry-pick 5361d836aeb1 from chromium

- spec-main/fixtures/api/native-window-open-native-addon.html
- spec-main/fixtures/module/echo-renamed.js
- spec-main/fixtures/module/echo.js
- spec-main/fixtures/module/uv-dlopen.js
- spec-main/fixtures/native-addon/echo/package.json
- spec-main/fixtures/native-addon/uv-dlopen/package.json
- spec-main/modules-spec.ts
- spec-main/package.json
- spec-main/yarn.lock
This PR scopes the internal test fixtures `echo` and `uv-dlopen` under the `@electron` scope.
I understand that these packages are not published and are only fixtures for the test suite. However, it is always a good practice to use scopes that you own to avoid substitution attacks[^1]. This attack was already attempted with `uv-dlopen` and npmjs.com has a security hold on that package name as a result[^2].
I wish to do the same change for other `package.json` files under `spec/fixtures` as well, but thought I'd start small first.
Notes: none
[^1]: https://github.blog/2021-02-12-avoiding-npm-substitution-attacks/
[^2]: https://www.npmjs.com/package/uv-dlopen
> test: scope internal test fixtures under `@electron-ci`

- spec-main/crash-spec.ts
- Due to #34020, for now disable a flaky test on 32-bit Windows.
Notes: none
> test: skip flaky test on 32-bit Windows

- .circleci/config/base.yml
These are all unused config blocks, renamed the `-skip-checkout` because other jobs that also skip checkout don't have that suffix
> build: remove dead circle config bits

- patches/angle/.patches
- patches/angle/cherry-pick-d27d9d059b51.patch
[M96-LTS] Vulkan: Update mCurrentElementArrayBuffersync based on dirty bit
ContextVk.cpp:
ContextVk::setupIndexedDraw: vertexArrayVk/getVertexArray() isn't present in M96
ContextVk::syncState: M96 uses mVertexArray instead of vertexArrayVk
VertexArrayVk.cpp:
VertexArrayVk::updateCurrentElementArrayBuffer doesn't exist in M9
Created it and kept M96 logic for retrieving buffer/offset
The previous fix crrev.com/c/3513553 has run into corner case that
requires more follow up change crrev.com/c/3522565. But with that, there
is report that now we are hitting assertion in
handleDirtyGraphicsIndexBuffer(). This becomes a bit fragile This new
fix relies on the DIRTY_BIT_INDEX_BUFFER dirty bit and should be more
reliable as long as the dirty bit is set properly (if not, then we …
> chore: cherry-pick d27d9d059b51 from angle

- patches/chromium/.patches
- patches/chromium/cherry-pick-12ba78f3fa7a.patch
[M96-LTS] Sanitize DragData markup before inserting it into document
(cherry picked from commit 5164a0fe3391283663e1196cf4576ec233985e89)
Fixed: 1315040
Change-Id: I8a0ddfb983d12c185f7e943d3d5277788199b011
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3579670
Quick-Run: Xiaocheng Hu <xiaochengh@chromium.org>
Auto-Submit: Xiaocheng Hu <xiaochengh@chromium.org>
Commit-Queue: Kent Tamura <tkent@chromium.org>
Cr-Original-Commit-Position: refs/heads/main@{#991324}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3589799
Cr-Commit-Position: refs/branch-heads/4664@{#1602} …
> chore: cherry-pick 12ba78f3fa7a from chromium

- patches/angle/.patches
- patches/angle/m100_fix_crash_when_pausing_xfb_then_deleting_a_buffer.patch
- patches/config.json
[M100] Fix crash when pausing XFB then deleting a buffer.
Fix is to validate XFB buffer bindings even if we're paused.
This is undefined behaviour so we can use any non-crashing solution.
Bug: [chromium:1305190](https://bugs.chromium.org/p/chromium/issues/detail?id=1305190)
Change-Id: [Ib95404cdb13adbde7f34d6cc77473a8b3cbf1de7](https://chromium-review.googlesource.com/q/Ib95404cdb13adbde7f34d6cc77473a8b3cbf1de7)
Reviewed-on: https://chromium-review.googlesource.com/c/angle/angle/+/3522283
Reviewed-by: Geoff Lang <[geofflang@chromium.org](mailto:geofflang@chromium.org)>
Commit-Queue: Jamie Madill <[jmadill@chromium.org](mailto:jmadill@chromium.org)>
(cherry picked from [commit 708ce9cfd63bc8eab7c48987612a2dedce78c69a](https://chromium-review.googlesource.com/q/commit:708ce9cfd63bc8eab7c4898 …
> chore: cherry-pick d24570fb65 from angle

- patches/chromium/.patches
- patches/chromium/cherry-pick-e2b8856012e0.patch
[M101] Sanitize DragData markup before inserting it into document
(cherry picked from commit 5164a0fe3391283663e1196cf4576ec233985e89)
Fixed: 1315040
Change-Id: I8a0ddfb983d12c185f7e943d3d5277788199b011
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3579670
Quick-Run: Xiaocheng Hu <xiaochengh@chromium.org>
Auto-Submit: Xiaocheng Hu <xiaochengh@chromium.org>
Reviewed-by: Kent Tamura <tkent@chromium.org>
Commit-Queue: Kent Tamura <tkent@chromium.org>
Cr-Original-Commit-Position: refs/heads/main@{#991324}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3588887
Cr-Commit-Position: refs/branch-heads/4951@{#831} …
> chore: cherry-pick e2b8856012e0 from chromium

- patches/chromium/.patches
- patches/chromium/cherry-pick-5be8e065f43e.patch
[M96-LTS] Check for error when calling ComputeImageSizeInBytes
(cherry picked from commit f3244fe50ba6c64ab6a75f1370d8dd983927fae6)
Bug: chromium:1304987
Change-Id: I8311231156fca3200ce74d79db59d910a1a0e33a
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3556686
Commit-Queue: Gregg Tavares <gman@chromium.org>
Cr-Original-Commit-Position: refs/heads/main@{#986304}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3597078
Owners-Override: Victor-Gabriel Savu <vsavu@google.com>
Cr-Commit-Position: refs/branch-heads/4664@{#1609}
Cr-Branched-From: 24dc4ee75e01a29d390d43c9c264372a169273a7-refs/heads/main@{#929512}
Notes: Backported fix …
> chore: cherry-pick 5be8e065f43e from chromium

- spec/webview-spec.js
The logic was flipped
https://github.com/electron/electron/blob/7dee5179cb0f4a79056204a243aa3317fbe711a6/spec/webview-spec.js#L10
It needs to be
https://github.com/electron/electron/blob/7dee5179cb0f4a79056204a243aa3317fbe711a6/spec-main/modules-spec.ts#L13
https://github.com/electron/electron/blob/7dee5179cb0f4a79056204a243aa3317fbe711a6/spec/static/main.js#L90
Depends on #34026
Notes: none
> test: fix nativeModulesEnabled in spec/webview-spec.js

- patches/chromium/.patches
- patches/chromium/cherry-pick-5ff02e4d7368.patch
[M96-LTS] NavigatorManagedData: Prevent iterator invalidation during Promise resolution
(cherry picked from commit 6083135252280d9b43e26169eb35154a9ac861ea)
Bug: 1307223
Change-Id: Iead6cf8c6236a95dbdfe7877c912f6ba86b370ac
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3532439
Commit-Queue: Anqing Zhao <anqing@chromium.org>
Cr-Original-Commit-Position: refs/heads/main@{#984230}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3577263
Reviewed-by: Artem Sumaneev <asumaneev@google.com>
Owners-Override: Artem Sumaneev <asumaneev@google.com>
Cr-Commit-Position: refs/branch-heads/4664@{#1591}
Cr-Branched-From: 24dc4ee75e01a29d390d43c9c264372a169273a7-refs/heads/main@{#929512}
Notes: …
> chore: cherry-pick 5ff02e4d7368 from chromium

- patches/chromium/.patches
- patches/chromium/reland_fix_noopener_case_for_user_activation_consumption.patch
Reland "Fix noopener case for user activation consumption"
This is a reland of e9828a82b5c182dc9a7fb0ae7226c35ba1726e7d
The MSAN error is from checking status before err in
content/renderer/render_view_impl.cc .
https://ci.chromium.org/ui/p/chromium/builders/ci/Linux%20ChromiumOS%20MSan%20Tests/b8821495655905086193/overview
The fix is to split the check for err and kIgnore into two checks,
and put the err check before kBlocked.
It is probably possible for the browser to consume user activation
but then eventually mojo returns an error and the renderer doesn't
consume activation, but that seems pretty marginal.
> Fix noopener case for user activation consumption
>
>
> The flow for user activation consumption in window.open was as follows:
>
> Renderer: ask …
> chore: cherry-pick 6b66a45021 from chromium

- script/run-clang-format.py
run-clang-format was excluding all files?
Notes: none
> build: fix run-clang-format extension matching

- patches/chromium/.patches
- patches/chromium/cherry-pick-6b66a45021a0.patch
Reland "Fix noopener case for user activation consumption"
This is a reland of e9828a82b5c182dc9a7fb0ae7226c35ba1726e7d
The MSAN error is from checking status before err in
content/renderer/render_view_impl.cc .
https://ci.chromium.org/ui/p/chromium/builders/ci/Linux%20ChromiumOS%20MSan%20Tests/b8821495655905086193/overview
The fix is to split the check for err and kIgnore into two checks,
and put the err check before kBlocked.
It is probably possible for the browser to consume user activation
but then eventually mojo returns an error and the renderer doesn't
consume activation, but that seems pretty marginal.
> Fix noopener case for user activation consumption
>
>
> The flow for user activation consumption in window.open was as follows:
>
> Renderer: ask …
> chore: cherry-pick 6b66a45021a0 from chromium

- shell/browser/osr/osr_render_widget_host_view.cc
- shell/browser/osr/osr_render_widget_host_view.h
- shell/browser/osr/osr_video_consumer.cc
- shell/browser/osr/osr_video_consumer.h
Closes https://github.com/electron/electron/issues/34047.
Fixes the following crash:
```
FATAL:frame_sink_video_capturer_impl.cc(304)] Invalid resolutions constraints: 36x0 must not be greater than 36x0; and also within media::limits.
```
This was happening because we were calling `SizeChanged` on the video consumer for popup widgets, which would have invalid `gfx::Size` values for their positions. To fix this, I refactored this to more closely mimic CEF's approach and callpaths, found [here](https://bitbucket.org/chromiumembedded/cef/src/7702d96b3329c59394e89227955dae33d8aae037/libcef/browser/osr/video_consumer_osr.cc#lines-58).
Tested with https://gist.github.com/gtalusan/c0ad56685aeb3b2c1108fbccf6b451b4.
Notes: Fixed an OSR crash happening when input select items were rendered.
> fix: offscreen rendering crash on input select

- spec-main/api-net-spec.ts
- spec-main/webview-spec.ts
* Fulllscreen is unobservably async on macOS and linux, waiting a second after each tests seems to make it pass reliably
* The net test fails with numbers like 21 and 23 constantly, allowing up to 25 seems reasonable and ensures the test remains green
> test: unflake some more tests

- shell/browser/api/electron_api_app.cc
- shell/browser/api/electron_api_auto_updater.cc
- shell/browser/api/electron_api_base_window.cc
- shell/browser/api/electron_api_browser_window.cc
- shell/browser/api/electron_api_data_pipe_holder.cc
- shell/browser/api/electron_api_debugger.cc
- shell/browser/api/electron_api_desktop_capturer.cc
- shell/browser/api/electron_api_menu.cc
- shell/browser/api/electron_api_session.cc
- shell/browser/api/electron_api_tray.cc
- shell/browser/api/electron_api_web_contents.cc
- shell/browser/api/electron_api_web_frame_main.cc
- shell/browser/event_emitter_mixin.h
- shell/browser/javascript_environment.cc
- shell/browser/net/node_stream_loader.cc
- shell/browser/printing/print_preview_message_handler.cc
- shell/browser/ui/file_dialog_mac.mm
- shell/browser/ui/file_dialog_win.cc
- shell/common/api/electron_bindings.cc
- shell/common/gin_helper/event_emitter.h
- shell/common/gin_helper/pinnable.h
- shell/common/gin_helper/promise.cc
- shell/common/node_bindings.cc
v8::Locker is supposed to coordinate usage of a single v8::Isolate from
multiple threads. However, we don't actually access the isolate from multiple
threads in Electron. To wit, there is a [persistent locker][] in
`JavascriptEnvironment`, that is initialized at boot time and held until
shutdown, meaning that any method that were to attempt to access the Isolate in
another thread would hang forever. That this doesn't happen is evidence that we
do not access the isolate from non-main threads.
[persistent locker]: https://github.com/electron/electron/blob/5b648854d59180cc9d72c6def8849ec59489bba6/shell/browser/javascript_environment.h#L50
As a followup, we should remove the `IsBrowserProcess` method from
`gin_helper::Locker`, where it never really belonged in the first place.
Notes: none
> chore: stop using v8::Locker everywhere

- patches/chromium/.patches
- patches/chromium/fsa_pass_file_ownership_to_worker_for_async_fsarfd_file_operations.patch
FSA: Pass File ownership to worker for async FSARFD file operations
We cannot access the backing file as a member of the
FileSystemAccessRegularFileDelegate since WrapCrossThreadPersistent
does NOT cancel the task posted to the worker pool if delegate is
destroyed. Passing ownership to the worker task ensures the file must
be alive when used. After the operation, ownership of the file is
passed back to the delegate.
This pattern was already used for the SetLength operation on old Macs.
Bug: 1299743
Change-Id: Ie00c09e8f77dc353f280af726a68ed6c572b750b
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3498864
Commit-Queue: Austin Sullivan <asully@chromium.org>
Cr-Commit-Position: refs/heads/main@{#980167}
Notes: …
> chore: cherry-pick cf64617c1cc5 from chromium

- .circleci/config/base.yml
We recently switched to using the macos.x86.medium.gen2 in CI for MacOS publish jobs. This works well on branches that have a default xcode version of 12.7.0+, as CircleCI can bump all images that use 12.7.0 or higher to ~150 GB. However, for branches that are still using 12.4.0 for publish (like 17-x-y) and only have access to ~80 GB images, this is causing us to run out of diskspace before the publish run can be completed.
This PR bumps us up to the large executor for macos publish jobs only.
> build: use large executors for macos publish on 12.4.0

- shell/browser/browser_mac.mm
Update `SetLoginItemSettings` to include CL:964074. From the CL:
> If a user has a network volumes listed in login items, calling
LSSharedFileListItemCopyResolvedURL() will cause an attempt to mount
those volumes. This is confusing behavior because it is not relevant to
the user's action (which is likely installing PWA or Chrome extension
with a background page). Also the name "GetLoginFileList" doesn't
indicate there is any such side-effect expected. Using kLSSharedFileListDoNotMountVolumes flag will prevent this
behavior.
Notes: Fixed an issue where calling `SetLoginItemSettings()` could potentially cause network volumes to be incorrectly mounted.
> fix: prevent `SetLoginItemSettings()` from mounting volumes

- patches/angle/.patches
- patches/angle/cherry-pick-d49484c21e3c.patch
[M100] Add error check on resuming XFB with deleted buffer.
Bug: chromium:1313905
Change-Id: I22c6f6400b05ca32c922fba9a3b9d4b5841ca8b8
Reviewed-on: https://chromium-review.googlesource.com/c/angle/angle/+/3578378
Auto-Submit: Jamie Madill <jmadill@chromium.org>
Reviewed-by: Geoff Lang <geofflang@chromium.org>
(cherry picked from commit 5c85fd4e11a3835a0719223a7cedb978d309da21)
Reviewed-on: https://chromium-review.googlesource.com/c/angle/angle/+/3594103
Notes: Backported fix for CVE-2022-1477.
> chore: cherry-pick d49484c21e3c from angle

- script/release/get-url-hash.js
This is the last trace of AWS / S3.  Should be fully migrated once this lands
> build: use azure function to hash assets instead of lambda

- script/release/uploaders/upload-index-json.py
Follow up to #34104, corrects the path for headers/dist artifacts in upload-index-json.py ([specific error here](https://github.com/electron/electron/pull/34104/files#diff-9b264d89ea713efb8d1742959114a0364ae01fec94bdda761f2a699aa90b3024R62))
> build: remove ending slash upload-index-json

- docs/api/safe-storage.md
- shell/browser/api/electron_api_safe_storage.cc
- spec-main/api-safe-storage-spec.ts
- spec-main/fixtures/crash-cases/safe-storage/index.js
On Linux, `isEncryptionAvailable()` was crashing instead of returning a
boolean before the 'ready' event was emitted by the app. The reason of
the crash is that [`CreateKeyStorage()`](https://source.chromium.org/chromium/chromium/src/+/main:components/os_crypt/os_crypt_linux.cc;l=74;drc=35be6215ec8f09e50176f36753c68f26c63d1885;bpv=1;bpt=0)
expects the config to be set but the function responsible for setting the
config, [`SetConfig()`](https://source.chromium.org/chromium/chromium/src/+/main:components/os_crypt/os_crypt_linux.cc;l=237;drc=35be6215ec8f09e50176f36753c68f26c63d1885;bpv=1;bpt=0),
is called only after the app is ready inside [`PostCreateMainMessageLoop()`](https://github.com/electron/electron/blob/main/shell/browser/electron_browser_main_parts.cc#L499).
So this changes …
> fix: fix a crash in `safeStorage` on Linux

- shell/browser/ui/electron_gtk.sigs
Fixes https://github.com/electron/electron/issues/34118
Check for availability of `gtk_native_dialog_get_type` which is only available with `>= 3.20` symbol used by the `gtk_native_dialog_*` code path
Notes: fix crash on startup due to missing gtk symbol on older distros
> fix: crash on startup due to missing gtk symbol on older distros

- patches/chromium/feat_add_data_transfer_to_requestsingleinstancelock.patch
While investigating #33975, we realized that the problem is not limited to just running the same version of one app in two user sessions, but any two Electron apps using 18 or higher in two user sessions. For example: If a user runs an app using Electron 18+ in one Windows user session, and then run a simple Fiddle that calls `app.requestSingleInstanceLock()` in another Windows user session, the Fiddle crashes.
The problem is that named pipes are not session-specific, and thus all Electron apps are trying to access the same named pipe.
This PR adjusts the pipe name, so that it is more unique per executable and per user.
Notes: Fixed a crash on Windows when opening apps in multiple, separate user sessions.
> fix: create singleton pipename from user & executable

- script/node-spec-runner.js
node-spec-runner.js was using `python` instead of `python3` to execute tests,
causing failures on macOS Monterey which has no `python` binary.
Notes: none
> test: run node specs with py3

- patches/node/.patches
- patches/node/build_disable_v8_pointer_compression_on_32bit_archs.patch
Backports https://github.com/nodejs/node/commit/a536de469564eea56129385c321c42c75f310b05
Fixes 32-bit native module builds with node-gyp@9.0.0 that uses `config.gypi` from bundled custom headers. Also removes redundant patch `enable_31_bit_smis_on_64bit_arch_and_ptr_compression.patch` since we always ship a single copy of `config.gypi` with pointer compression enabled since https://github.com/electron/electron/commit/d1e0b6324a0b380912f3d0dc5fc799ed2447ab1e
Notes: Fix 32-bit native module builds with node-gyp >= 9.0.0
> chore: backport a536de469 from node

- spec-main/api-browser-window-spec.ts
As seen here:  https://github.visualstudio.com/electron/_build/results?buildId=125690&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=5caf77c8-9b10-50ef-b5c7-ca89c63e1c86, the following test sometimes errors out:
```
BrowserWindow module beginFrameSubscription method does not crash when callback returns nothing
done() called multiple times
```
This PR adds logic to make sure that doesn't happen.
Notes: none
> test: fixup done being called multiple times

- lib/browser/guest-window-manager.ts
- spec-main/api-browser-window-spec.ts
- spec-main/fixtures/apps/open-new-window-from-link/index.html
- spec-main/fixtures/apps/open-new-window-from-link/main.js
- spec-main/fixtures/apps/open-new-window-from-link/new-window-page.html
- spec-main/fixtures/apps/open-new-window-from-link/package.json
- spec-main/fixtures/apps/open-new-window-from-link/preload.js
Closes https://github.com/electron/electron/issues/34152.
Fixes an issue where windows opened from new links wouldn't properly load URLs. This happened as a result of cleanup in https://github.com/electron/electron/commit/d44a187d0b226800fe0cb4f7a0d2b36c871b27cd - a section of code was removed which loaded the url for non-guest windows in `openGuestWindow`. It's actually the case that this code is necessary when we're opening new windows from links as well. When we open a new window from a link via `Shift+LeftClick`, this routes through `OpenUrlFromTab`, at which point the browser process is responsible for initiating navigation in the new window. This PR restores that code and updates the comment accordingly.
Notes: Fixes an issue where some `BrowserWindow`s opened from new links …
> fix: call loadUrl when opening new windows from links

- patches/node/.patches
- patches/node/feat_add_knostartdebugsignalhandler_to_environment_to_prevent.patch
- shell/common/node_bindings.cc
Backport of #33188.
Notes: SIGUSR1 is no longer handled when the `node_cli_inspect` fuse is disabled
> fix: disable SIGUSR1 when --inspect is disabled

- docs/api/session.md
- docs/fiddles/features/web-hid/main.js
- docs/fiddles/features/web-serial/main.js
- docs/tutorial/devices.md
This PR clarifies how the `hid-device-added`, `hid-device-removed`, `serial-port-added`, and `serial-port-removed` events work.  This should help clarify issues like #34103.
Notes: none
> docs: clarify added/removed events on device APIs

- appveyor.yml
- script/release/release.js
- script/release/uploaders/upload.py
Manual backport of https://github.com/electron/electron/pull/34162
_Note: Please don't merge unless the electron-ia32-release job is green_
Notes: Re-enabled symbol generation on 32-bit Windows.
> build: re-enable 32-bit Windows symbol generation

- npm/install.js
- npm/package.json
`extract-zip@^1.0.3` indirectly depends on `minimist@0.0.8` which is affected by [CVE-2021-44906](https://nvd.nist.gov/vuln/detail/CVE-2021-44906).
By upgrading this package, it requires updating our minimum version of Node required by the Electron npm installer.
Followup: does CI run tests against the npm package scripts?
Notes: Minimum required node version to install the `electron` npm package is now >10
> chore: upgrade extract-zip for installer

- shell/browser/ui/tray_icon_cocoa.mm
Closes https://github.com/electron/electron/issues/32111.
Ensures that the menu controller not only exists, but has a non-zero number of items before choosing to pass the click item to the superclass. 
Regressed in https://github.com/electron/electron/commit/47a38daee20ef77cc98bc13bb7a7c1d690fd635c.
Notes: Fixed an issue where tray items wouldn't highlight in some scenarios on macOS.
> fix: tray icon not highlighting on empty menu

- patches/angle/.patches
- patches/angle/cherry-pick-a602a068e022.patch
[M100] Fix validate state cache after XFB buffer deleted.
Bug: chromium:1317650
Change-Id: Iec9f1167c3b2957091dd0f4ef3efcfcd7c4bf3c0
Reviewed-on: https://chromium-review.googlesource.com/c/angle/angle/+/3594250
Auto-Submit: Jamie Madill <jmadill@chromium.org>
(cherry picked from commit 4efc4ee6830a8a53a0daf9daa3c7aa835db4220f)
Reviewed-on: https://chromium-review.googlesource.com/c/angle/angle/+/3621779
Reviewed-by: Amirali Abdolrashidi <abdolrashidi@google.com>
Notes: Backported fix for CVE-2022-1639.
> chore: cherry-pick a602a068e022 from angle

- shell/renderer/printing/print_render_frame_helper_delegate.cc
Refs CL:3214635.
Updates `PrintRenderFrameHelperDelegate::GetPdfElement` to find the PDF object element in the
unseasoned PDF frame.
Notes: none
> fix: fetching PDF element from `WebLocalFrame`

- patches/chromium/.patches
- patches/chromium/cherry-pick-ec0cce63f47d.patch
[M96-LTS][profiler] Cleanup profiler group detached profilers
ProfilerGroup keeps track of detached profilers to be able to gracefully
stop leaked profilers when the corresponding ExecutionContext is
destroyed.
(cherry picked from commit 9f9d5fd2f3085414fc8776bf556fb5c4fa2dac2c)
Change-Id: I4fdbbc3a5208819397d742c9ecbff117f839691c
Bug: chromium:1297283
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3594570
Commit-Queue: Corentin Pescheloche <cpescheloche@fb.com>
Cr-Original-Commit-Position: refs/heads/main@{#994316}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3620956
Reviewed-by: Oleh Lamzin <lamzin@google.com>
Owners-Override: Oleh Lamzin <lamzin@google.com>
Auto-Submit: …
> chore: cherry-pick ec0cce63f47d from chromium

- patches/angle/.patches
- patches/angle/cherry-pick-a4f71e40e571.patch
Fix CheckedNumeric using the wrong type.
Validation for glBufferSubData checks that the buffer is large enough
for size+offset but verifies they fit in a size_t which is a different
type than the deduced type for size+offset on 32-bit systems.
Use decltype to ensure that we always verify there is no overflow on the
correct type.
Bug: chromium:1298867
Change-Id: I82f534b2d227d3273a763e626ebeae068dc918dc
Reviewed-on: https://chromium-review.googlesource.com/c/angle/angle/+/3563515
Reviewed-by: Jonah Ryan-Davis <jonahr@google.com>
(cherry picked from commit c458b5add432c3da98ef370680518d0af7e4d4e3)
Reviewed-on: https://chromium-review.googlesource.com/c/angle/angle/+/3630020
Notes: Backported …
> chore: cherry-pick a4f71e40e571 from angle

- spec-main/api-browser-window-spec.ts
Follow-up to https://github.com/electron/electron/pull/34140
Also edits a previously-added test to address some JS issues.
Notes: none
> test: add `setTitlebarOverlay` spec

- patches/angle/.patches
- patches/angle/fix_checkednumeric_using_the_wrong_type.patch
Fix CheckedNumeric using the wrong type.
Validation for glBufferSubData checks that the buffer is large enough
for size+offset but verifies they fit in a size_t which is a different
type than the deduced type for size+offset on 32-bit systems.
Use decltype to ensure that we always verify there is no overflow on the
correct type.
Bug: chromium:1298867
Change-Id: I82f534b2d227d3273a763e626ebeae068dc918dc
Reviewed-on: https://chromium-review.googlesource.com/c/angle/angle/+/3563515
Reviewed-by: Jonah Ryan-Davis <jonahr@google.com>
(cherry picked from commit c458b5add432c3da98ef370680518d0af7e4d4e3)
Reviewed-on: https://chromium-review.googlesource.com/c/angle/angle/+/3630020
Notes: Backported …
> chore: cherry-pick a4f71e40e5 from angle

- patches/v8/.patches
- patches/v8/cherry-pick-723ed8a9cfff.patch
Merged: [wasm] Fix Int64Lowering for tagged stack-passed parameters
When lowering signatures, we must preserve the separation of parameters
into tagged and untagged sections.
Fixed: chromium:1320614
(cherry picked from commit 8062598f26127d833c237acb3da154c91c1ec7e7)
Change-Id: I2f84535f785ce5c96e9c892994416986965eaa40
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/3632515
Commit-Queue: Jakob Kummerow <jkummerow@chromium.org>
Reviewed-by: Shu-yu Guo <syg@chromium.org>
Cr-Commit-Position: refs/branch-heads/10.1@{#28}
Cr-Branched-From: b003970395b7efcc309eb30b4ca06dd8385acd55-refs/heads/10.1.124@{#1}
Cr-Branched-From: e62f556862624103ea1da5b9dcef9b216832033b-refs/heads/main@{#79503}
Notes: Backported fix for chromium:1320614.
> chore: cherry-pick 723ed8a9cfff from v8

- patches/config.json
- patches/icu/.patches
- patches/icu/m100_cp_pr_2070_fix_int32_overflow.patch
[m100] CP PR 2070 fix int32 overflow
https://github.com/unicode-org/icu/pull/2070
https://unicode-org.atlassian.net/browse/ICU-22005
Bug: chromium:1316946
Change-Id: I6cd7d687a55b6cc157b1afa52365908be2992fa6
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/deps/icu/+/3614280
Reviewed-by: Jungshik Shin <jshin@chromium.org>
(cherry picked from commit 85814e1af52482199a13d284545623ffbc9eef83)
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/deps/icu/+/3632709
Notes: Backported fix for CVE-2022-1638.
> chore: cherry-pick 14e51893e5 from icu

- patches/config.json
- patches/icu/.patches
- patches/icu/cherry-pick-14e51893e5b5.patch
[m100] CP PR 2070 fix int32 overflow
https://github.com/unicode-org/icu/pull/2070
https://unicode-org.atlassian.net/browse/ICU-22005
Bug: chromium:1316946
Change-Id: I6cd7d687a55b6cc157b1afa52365908be2992fa6
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/deps/icu/+/3614280
Reviewed-by: Jungshik Shin <jshin@chromium.org>
(cherry picked from commit 85814e1af52482199a13d284545623ffbc9eef83)
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/deps/icu/+/3632709
Notes: Backported fix for CVE-2022-1638.
> chore: cherry-pick 14e51893e5b5 from icu

- shell/browser/ui/views/win_frame_view.cc
- spec-main/api-browser-window-spec.ts
Closes https://github.com/electron/electron/issues/34137.
Fixes an issue where calling `setTitlebarOverlay` with an initially invalid `titleBarStyle` on Windows would result in a crash. Ideally, we'd throw in the constructor, but that causes a whole host of issues, so we instead no-op if we attempt to call `setTitleBarStyle` and the overlay was never correctly initialized.
Notes: Fixes an issue where calling `setTitlebarOverlay` with an initially invalid `titleBarStyle` on Windows would result in a crash.
> fix: WCO crash on bad `titlebarStyle`

- docs/api/webview-tag.md
> docs: added units to <webview>.print() pageSize option

- patches/chromium/.patches
- patches/chromium/merge_to_m100_don_t_use_getoriginalopener_to_get_opener_s_origin_on.patch
[Merge to M100] Don't use GetOriginalOpener to get opener's origin on FrameTree initialization
When setting the origin of the new main RFH on FrameTree initialization,
we base it on the opener's origin if it exists. GetOriginalOpener()
was used to get the opener, but that function will actually return the
main frame of the opener. This means when the FrameTree is opened by a
non-main frame, we might inherit the wrong origin.
This CL fixes the bug by getting the actual opener using GetOpener()
instead, and adds a regression test and warning note to
GetOriginalOpener().
(cherry picked from [commit 4eb716ef5cdbca4db3a9377ee6390964d0d4025f](https://chromium-review.googlesource.com/q/commit:4eb716ef5cdbca4db3a9377ee6390964d0d4025f))
Bug: …
> chore: cherry-pick 2941a90229 from chromium

- patches/chromium/.patches
- patches/chromium/cherry-pick-99c3f3bfd507.patch
Only destroy successfully created compression session in VT encoder
This is a defensive change, since we don't have a repro on hand.
My guess is that VTCompressionSessionCreate() might fail to create a
compression session, but still write a value to compressionSessionOut.
It makes VTCompressionSessionInvalidate() access uninitialized memory.
That's why this CL makes sure that we only destroy a compression session
if VTCompressionSessionCreate() reports success.
Bug: 1312563
Change-Id: I468ce0e10bad251ca0b62b568607dbc5c32ba8bc
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3575680
Reviewed-by: Dale Curtis <dalecurtis@chromium.org>
Commit-Queue: Eugene Zemtsov <eugene@chromium.org>
Cr-Commit-Position: refs/heads/main@{#990654}
Notes: Backported fix for …
> chore: cherry-pick 99c3f3bfd507 from chromium

- docs/api/safe-storage.md
- shell/browser/api/electron_api_safe_storage.cc
- shell/browser/electron_browser_main_parts.cc
- shell/browser/net/system_network_context_manager.cc
- spec-main/api-safe-storage-spec.ts
- spec-main/fixtures/crash-cases/safe-storage/index.js
Backport of https://github.com/electron/electron/pull/33913.
Notes: none.
> fix: crash in `safeStorage` on Linux

- patches/chromium/printing.patch
- shell/browser/api/electron_api_web_contents.cc
- shell/browser/api/electron_api_web_contents.h
Closes https://github.com/electron/electron/issues/34270.
Refs CL:3579297
Fixes a DCHECK when calling `webContents.print()`.
Tested with https://gist.github.com/0f0e776b138452d6815ef4efc16aa0d1
Notes: Fixed a potential crash when calling `webContents.print()`
> fix: DCHECK on `webContents.print()`

- shell/browser/api/electron_api_web_contents.cc
- shell/browser/api/electron_api_web_frame_main.cc
- shell/browser/api/electron_api_web_frame_main.h
fixes #33880
Speculative render frames are created with pending cross-origin navigation requests. Their RenderFrameHost is not fully active until the navigation is later committed.
There seems to be a crash with our code to handle new RFHs. I've added a check to make sure the RFH has been notified of the RenderFrame being created prior to connecting the WebFrameMain's Mojo interface.
I wasn't able to reproduce the crash in a test.
Notes: Fixed potential crash with WebFrameMain when navigating between cross-origin websites.
> fix: crash when creating interface for speculative frame

- .github/workflows/semantic.yml
GitHub asks developers to define workflow permissions, see https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/ and https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token for securing GitHub workflows against supply-chain attacks.
The Open Source Security Foundation (OpenSSF) [Scorecards](https://github.com/ossf/scorecard) also treats not setting token permissions as a high-risk issue. 
This PR adds minimum token permissions for the GITHUB_TOKEN using https://github.com/step-security/secure-workflows. 
This project is part of the top 100 critical projects as per OpenSSF (https://github.com/ossf/wg-securing-critical-projects), so fixing the token permissions to improve …
> ci: Add GitHub token permissions for workflows

- script/release/uploaders/upload-index-json.py
All branches except 15-x-y were migrated to Python 3. However, the last release of 15-x-y failed due to tooling expecting a Python 3 library. This PR adds compatibility for both Python 2 and Python 3 to that file prior to the final 15-x-y release.
Notes: none
> build: fix index upload error on 15-x-y

- patches/chromium/.patches
- patches/chromium/custom_protocols_plzserviceworker.patch
- shell/browser/electron_browser_client.cc
- spec-main/api-protocol-spec.ts
Backport of https://github.com/electron/electron/pull/34290
Notes: fix service worker registration with custom protocols
> fix: service worker registration with custom protocols

- docs/tutorial/quick-start.md
reference: Note: It is known that having both Content-Security-Policy
and X-Content-Security-Policy or X-Webkit-CSP causes unexpected
behaviours on certain versions of browsers. Please avoid using deprecated
X-* headers. https://content-security-policy.com/
also:
https://github.com/electron/electron-quick-start/commit/1ad18486ed9be39612fdfe7b8fe265e602846ab3
> docs: remove X-Content-Security-Policy header in quick-start.md

- shell/browser/electron_permission_manager.cc
- spec-main/api-browser-window-spec.ts
- spec-main/chromium-spec.ts
While working on implementing [SerialPort.forget()](https://chromium-review.googlesource.com/c/chromium/src/+/3560622), I found a crash caused by #32651.
- Fixes #33889 
Notes: fixed crash when calling navigator.serial.getPorts()
> fix: crash on navigator.serial.getPorts()

- spec-main/api-web-contents-spec.ts
The `new-window` event is [deprecated](https://github.com/electron/electron/blob/main/docs/breaking-changes.md#deprecated-webcontents-new-window-event).
Notes: none
> test: use webContents.setWindowOpenHandler() in specs

- shell/browser/api/electron_api_crash_reporter.cc
Initializing the crashReporter takes around 620 milliseconds on Intel
macOS. I have sent a CL to crashpad to partially fix the performance
issue in https://chromium-review.googlesource.com/c/crashpad/crashpad/+/3641386.
It would be beneficial to log the performance impact of this function in
the traces in case this slows down in the future.
Notes: Added a TRACE call named `crash_reporter::Start` under the `electron` category for `crash_reporter::Start()`.
> chore: add a TRACE call for `crash_reporter::Start()`

- lib/browser/guest-window-manager.ts
There is no point in returning an object with a single property.
Notes: none
> refactor: return options directly in makeBrowserWindowOptions() helper

- default_app/default_app.ts
The `new-window` event is [deprecated](https://github.com/electron/electron/blob/main/docs/breaking-changes.md#deprecated-webcontents-new-window-event).
Notes: none
> chore: use webContents.setWindowOpenHandler() in default-app

- patches/chromium/.patches
- patches/chromium/cherry-pick-b321ac924772.patch
[M98] Do not expose inner WebContents on scripting/getAllFrames.
Inner WebContents shouldn't be exposed for executeScript or getAllFrames
APIs. This is consistent with the API before crrev.com/f894f106
and crrev.com/c8de3b0a.
BUG=1301320,1261261
(cherry picked from commit 5c4e043324b3afd1be673ae2c0a5c00845bb0e86)
Change-Id: I86a5b09aa44c48319b7dd0a10e5442b8c803d4e5
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3497565
Reviewed-by: Devlin Cronin <rdevlin.cronin@chromium.org>
Reviewed-by: Kevin McNee <mcnee@chromium.org>
Commit-Queue: Dave Tapuska <dtapuska@chromium.org>
Cr-Original-Commit-Position: refs/heads/main@{#977769}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3514993
Cr-Commit-Position: refs/branch-heads/4758@{#1244} …
> chore: cherry-pick b321ac924772 from chromium

- .circleci/config/base.yml
- yarn.lock
As in title, no point checking out all of Chromium just to run webpack / tsc for a few seconds.
This should make third-party docs changes way quicker on CI.
> build: do not checkout chromium for ts docs check

- .github/workflows/release_dependency_versions.yml
Refs https://github.com/electron/chromedriver/pull/98
Refs https://github.com/electron/mksnapshot/pull/61
This GitHub Action adds automated release for chromedriver and mksnapshot whenever there are new major releases of Electron. 
✅ mksnapshot [test run](https://github.com/electron/mksnapshot/actions/runs/2383109099)
✅ chromedriver [test run](https://github.com/electron/chromedriver/runs/6588071750?check_suite_focus=true)
Notes: none
> build: trigger mksnapshot/chromedriver releases automatically

- appveyor.yml
`CalculateNativeWinOcclusion` was originally disabled for Windows CI due to https://bugs.chromium.org/p/chromium/issues/detail?id=1139022 . However, that issue has since been marked as fixed. Running the Windows tests both locally and in CI shows that the failures seem to be resolved. This PR re-enables `CalculateNativeWinOcclusion` in AppVeyor.
Notes: none
> ci: re-enable CalculateNativeWinOcclusion

- electron_strings.grdp
- patches/chromium/printing.patch
Closes https://github.com/electron/electron/issues/34358.
Adds missing resource string resultant of [CL:3470185](https://chromium-review.googlesource.com/c/chromium/src/+/3470185)
Notes: Fix printing crash when using `webContents.print()`.
> fix: missing resource printing DCHECK

- patches/chromium/.patches
- patches/chromium/pa_support_16kb_pagesize_on_linux_arm64.patch
Refs https://chromium-review.googlesource.com/c/chromium/src/+/3545665
Refs https://github.com/electron/electron/issues/25387
Notes: Enable 16k page sizes support for linux arm64
> chore: backport a704c3a from chromium

- shell/browser/api/electron_api_web_frame_main.cc
Follow up to #33919. A code path involving speculative RenderFrameHosts being created is resulting in a crash when initially setting up the Mojo connection.
More investigation is still needed to determine what leads to this state where `render_frame_` is a nullptr.
Notes: Fixed potential crash in WebFrameMain when performing a cross-origin navigation.
> fix: crash in WebFrameMain mojo connection when RenderFrameHost is nullptr

- .circleci/config/base.yml
Beginning in main/20-x-y, the linking step on Mac is taking over a half hour.
While we figure out why this linking time has increased, this PR increases the output timeout from 30m to 60m so we can keep nightly and alpha releases moving.
Notes: none
> chore: increase timeout for electron-build step

- shell/browser/native_window_mac.h
- shell/browser/native_window_mac.mm
- shell/browser/ui/cocoa/electron_ns_window_delegate.mm
- spec-main/api-browser-window-spec.ts
On macOS, BrowserWindows cannot be resized when in a fullscreen transition or when actively in fullscreen.
Notes: Fixed an issue where BrowserWindows on macOS were incorrectly marked as resizable.
> fix: fullscreen windows aren't resizable on macOS

- spec-main/api-web-frame-main-spec.ts
Recently added tests (#34428) seem to flake on Linux
https://app.circleci.com/pipelines/github/electron/electron/54242/workflows/168eb782-e823-4fb5-8448-dd0e0df0e8b1/jobs/1239573
https://app.circleci.com/pipelines/github/electron/electron/54205/workflows/aba3671a-ebc8-40bc-b7da-df3d4149f8d5/jobs/1239757
This fix is currently untested. Going to see how it performs in CI for now.
Notes: none
> test: fix for flaky renderer crash test

- script/nan-spec-runner.js
In https://github.com/electron/electron/pull/29281, we modified the nan spec runner to build with `libc++`/`libc++abi`, since Linux uses `libstdc++` by default and there was a mismatch between the two that was causing test failures. However, this change inadvertently caused it to begin failing on macOS since that's not tested as part of the suite.
It transpires that macOS uses `libc++` by default, and so forcing it to use the `libc++` found in `src/buildtools/third_party/libc++` instead of what's found in XCode causes issues. We only need to pass `-std=c++17` as part of `CFLAGS` on macOS, and then the test suite works fully.
We might also consider running the nan tests on macOS as part of our test suite to help catch issues like this in the future 🤔  
Notes: none
> chore: fix nan spec runner on macOS

- script/lint.js
Currently when `cpplint` runs on Windows it is complaining a lot about incorrect header guards due to not knowing the correct root, which the `--project_root` flag is supposed tell it. It looks like `--root` and `--project_root` aim to do the same thing, AFAICT, but it doesn't seem like `--project_root` is working as intended. [cpplint/cpplint](https://github.com/cpplint/cpplint) (which is actually a fork and has diverged from 'depot_tools' `cpplint`, eek) has improved handling of `--root` (and doesn't have `--project_root` at all) which I [upstreamed to depot_tools](
https://chromium-review.googlesource.com/c/chromium/tools/depot_tools/+/3648533), so let's use that.
Notes: none
> chore: use --root instead of --project_root for cpplint

- shell/browser/native_window_mac.h
- shell/browser/native_window_mac.mm
- shell/browser/ui/cocoa/electron_ns_window_delegate.mm
- spec-main/api-browser-window-spec.ts
Closes https://github.com/electron/electron/issues/34401.
Fixes an issue where normal bounds would not be appropriately updated if the user minimized via clicking on the minimize button as opposed to calling `BrowserWindow.minimize()` on macOS. This fixes that by updating the normal bounds value prior to window miniaturization in the NSWindow delegate.
Notes: Fixed an issue where normal bounds would not be appropriately updated if the user minimized with the minimize button.
> fix: update normal bounds prior to minimizing

- docs/tutorial/window-customization.md
This PR modifies the documentation for the WCO height option added by https://github.com/electron/electron/pull/34278 to include macOS functionality.
Notes: None
> docs: add macOS height option info

- script/sysroots.json
When we updated our sysroots in #33557 as part of the Chromium roll to 102.0.4989.0, it introduced a new dependency in linux arm64 builds to use glibc 2.29 or greater.  Since there are supported versions of linux distros (eg Ubuntu 18.04) that do not have access to this version of glibc, Electron no longer works in those versions.
This PR reverts the sysroot for linux arm64 only to the older sysroot as this issue only affects linux arm64 (linux x64 and armv7 are unaffected).
- Fixes #34399
Notes: Fixed linux arm64 builds to not require glibc 2.29+
> fix: don't require glibc 2.29+ on linux arm64 builds

- spec/webview-spec.js
We are only testing the deprecated `page-title-set` event for webview.
Notes: none
> test: add missing page-title-updated event spec for webview

- lib/browser/api/web-contents.ts
- spec-main/guest-window-manager-spec.ts
Closes https://github.com/electron/electron/issues/34508.
Fixes an error where `setWindowOpenHandler()` would crash if the callback threw an error. Fix this issue by wrapping the call in a try/catch and handling appropriately if an error is thrown.
Notes: Fixed an error where `setWindowOpenHandler()` would crash if the callback threw an error
> fix: crash when `setWindowOpenHandler` callback throws

- BUILD.gn
- build/fuses/fuses.json5
- buildflags/BUILD.gn
- buildflags/buildflags.gni
- filenames.gni
- shell/browser/ui/win/electron_desktop_window_tree_host_win.cc
- shell/browser/ui/win/electron_desktop_window_tree_host_win.h
- shell/browser/win/dark_mode.cc
- shell/browser/win/dark_mode.h
- shell/common/api/features.cc
- typings/internal-ambient.d.ts
Closes #32913, closes #18119.
A refactored implementation of dark mode for Windows, using official API for Windows 11 and undocumented flag on Win 10 >= 20H1. It allows Electron apps to set a dark title bar based on the system preference.
cc @dsanders11 @deermichel @ckerr 
Notes: Added immersive dark mode on Windows.
> feat: add immersive dark mode on windows

- patches/angle/.patches
- patches/angle/cherry-pick-9768648fffc9.patch
- patches/config.json
[M102] Fix to invalidate cache when binding Transform Feedback.
Bug: chromium:1330379
Change-Id: I091116286ac511c50f9abcffa4d3cf350be920b4
Reviewed-on: https://chromium-review.googlesource.com/c/angle/angle/+/3677115
(cherry picked from commit d96cee6685099f6bcc392a4d20d28c8ec484673a)
Reviewed-on: https://chromium-review.googlesource.com/c/angle/angle/+/3691799
Notes: Backported fix for CVE-2022-2011.
> chore: cherry-pick 9768648fffc9 from angle

- patches/chromium/.patches
- patches/chromium/cherry-pick-21139756239b.patch
{M102 PICK} [IndexedDB] Use-After-Free Fix
We can't guarantee order in the task the constructor dispatches the same
way we could before due to all the async changes. Let's be sure all the
objects exist before using them now. Long term, we need to address
ownership of the idb context.
Bug: 1324864, 1218100
Change-Id: Id5753297a4c966432028a1e7e063c5f1bed6f619
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3646994
Reviewed-by: Ayu Ishii <ayui@chromium.org>
Commit-Queue: Srinivas Sista <srinivassista@chromium.org>
Cr-Commit-Position: refs/branch-heads/5005@{#812}
Cr-Branched-From: 5b4d9450fee01f821b6400e947b3839727643a71-refs/heads/main@{#992738}
Notes: Security: backported fix for 1324864, 1218100.
> chore: cherry-pick 21139756239b from chromium

- patches/chromium/.patches
- patches/chromium/cherry-pick-f1504440487f.patch
PaintOpReader: Harden PaintImage deserialization
This fix prevents the deserialization of PaintImage pixel data from
reading data out of bounds when the block of serialized pixel data isn't
large enough to cover the expected amount of data, given the size and
format of the image.
(cherry picked from commit e89ea1489429a9a9e49e70d5d4e8d018fbafb6ac)
Bug: 1325298
Change-Id: Icbeb405d2031d7d8ce4537836d7996ce7885f6d1
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3669596
Commit-Queue: Justin Novosad <junov@chromium.org>
Reviewed-by: Jonathan Ross <jonross@chromium.org>
Cr-Original-Commit-Position: refs/heads/main@{#1007804}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3687975
Bot-Commit: Rubber Stamper …
> chore: cherry-pick f1504440487f from chromium

- patches/chromium/.patches
- patches/chromium/cherry-pick-f1dd785e021e.patch
M102: FSA: Sanitize .scf files
.scf files can be used to execute code without opening the file.
Sanitize these files the same way we sanitize .lnk files.
Also updates filename sanitization logic to be consistent in blocking
.lnk and .local extensions on all OSes.
(cherry picked from commit 988164c6c4a563c3d4c0dedba295d09472dfc15f)
Bug: 1227995
Change-Id: I4b018f1ba524c783547e18630db9addc9fb126e6
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3089422
Cr-Original-Commit-Position: refs/heads/main@{#1002147}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3648322
Auto-Submit: Austin Sullivan <asully@chromium.org>
Commit-Queue: Austin …
> chore: cherry-pick f1dd785e021e from chromium

- patches/angle/.patches
- patches/angle/cherry-pick-03aa5ae75c29.patch
M102: Ignore eglBind/ReleaseTexImage calls for lost contexts.
eglBindTexImage and eglReleaseTexImage no-op when no context is
current. Extend this to lost contexts to match the behaviour of making
a GL call on a lost context.
This avoids potential unexpected bad accesses in the backends.
Bug: chromium:1316578
Change-Id: I7b309c297e0c803019720733dee2950abb4c4b5f
Reviewed-on: https://chromium-review.googlesource.com/c/angle/angle/+/3683869
Reviewed-by: Alexis Hétu <sugoi@google.com>
Reviewed-by: Alexis Hétu <sugoi@chromium.org>
(cherry picked from commit bfab7e60a15dc6f72e34406d3f2a3996cd8d0be2)
Reviewed-on: https://chromium-review.googlesource.com/c/angle/angle/+/3691180
Ref …
> chore: cherry-pick 03aa5ae75c29 from angle

- patches/ffmpeg/.patches
- patches/ffmpeg/cherry-pick-e481fc655a62.patch
Do not parse late SEI messages during decoding.
Bug: 1306751
Change-Id: I2088b9ff89bd8eee8ab82675258af302d9bfccf9
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/third_party/ffmpeg/+/3625832
Reviewed-by: Dale Curtis <dalecurtis@chromium.org>
Ref electron/security#166
Notes: Security: backported fix for 1306751.
> chore: cherry-pick e481fc655a62 from ffmpeg

- shell/browser/native_browser_view_views.cc
Closes https://github.com/electron/electron/issues/34552.
Fixes an issue where draggable regions were not recalculated when BrowserView bounds changed. This was happening because we didn't issue a call to `UpdateDraggableRegions` after bounds changed on Windows, as we do on macOS: https://github.com/electron/electron/blob/abf6f1cf78fa4e88131fe2a77caf350cb3b9fdcb/shell/browser/native_browser_view_mac.mm#L270 
Notes: Fixed an issue where draggable regions were not recalculated when BrowserView bounds changed on Windows.
> fix: draggable regions updating on bounds change

- shell/renderer/api/electron_api_web_frame.cc
`webFrame.getWebPreference()` is an internal API and we have removed unused keys before. We only need to keep these:
https://github.com/electron/electron/blob/bad8d5e08af159371b0dc2875eb6c2281bff59a5/typings/internal-ambient.d.ts#L106-L111
Notes: none
> chore: cleanup undocumented keys from webFrame.getWebPreference()

- shell/browser/ui/drag_util_mac.mm
Closes https://github.com/electron/electron/issues/34603.
Refs CL:1191742
Modernizes macOS APIs behind drag-and-drop functionality to remove deprecation warning.
Notes: none
> refactor: remove deprecated drag-and-drop code

- script/node-spec-runner.js
Take into account tests that Node.js has themselves marked as flaky, so that we can better parse out which failures are a result of our changes vs known flakes we haven't been aware of. For example: ['sequential/test-cpu-prof-dir-worker'](https://github.com/nodejs/node/issues/32168) is marked as flaky in Node.js on all platforms
Notes: none.
> build: mark existing Node.js flakes as dontcare

- .circleci/config/base.yml
- script/release/release.js
- script/release/uploaders/upload.py
This reverts commit 2bbbc66eb83b42041d768ea64f5ada9ed1ffd301 to fix the June 21 nightly build
Notes: none
> chore: Revert "build: build & release libcxx objects on darwin (#34586)"

- shell/common/gin_converters/net_converter.cc
Modernize ListValue usage in net_converter.
This also fixes a 3-year-old bug introduced by
https://github.com/electron/electron/pull/20719, in which the `length` property
in resource bodies was ignored.
Notes: Fixed the 'length' property in UploadFile objects being ignored.
> fix: modernize ListValue in net converters

- patches/v8/.patches
- patches/v8/cherry-pick-44c4e56fea2c.patch
Merged: [weakrefs] Set unregister_token to undefined when unregistering
(cherry picked from commit dd3289d7945dac855d1287cf4ea248883e908d54)
Bug: chromium:1321078
Change-Id: Ic7537cc5101b35018911c27a81e9b0e0a7da154b
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/3695262
Reviewed-by: Dominik Inführ <dinfuehr@chromium.org>
Commit-Queue: Michael Lippautz <mlippautz@chromium.org>
Cr-Commit-Position: refs/branch-heads/10.2@{#16}
Cr-Branched-From: 374091f382e88095694c1283cbdc2acddc1b1417-refs/heads/10.2.154@{#1}
Cr-Branched-From: f0c353f6315eeb2212ba52478983a3b3af07b5b1-refs/heads/main@{#79976}
Ref electron/security#176
Notes: Security: backported fix for 1321078.
> chore: cherry-pick 44c4e56fea2c from v8

- shell/browser/native_window_views.cc
- shell/browser/ui/views/win_caption_button_container.cc
- shell/browser/ui/views/win_caption_button_container.h
- shell/browser/ui/views/win_frame_view.h
Closes https://github.com/electron/electron/issues/32285.
Adapts WCO window button container to adapt to and update based on the maximizable, minimizable, and closable states of a given BrowserWindow. It is slightly different UI-wise than native, in that it does not fully grey out when disabled, but it behaves the same.
Notes: Fixed an issue where Windows Control Overlay buttons did not respect  maximizable/minimizable/closable states of a BrowserWindow.
> fix: WCO respects maximizable/closable/minimizable

- patches/chromium/.patches
- patches/chromium/cherry-pick-22c61cfae5d1.patch
FSA: Sanitize .url files
Bug: 1307930
Change-Id: I7ed3cca5942a5334ba761d269bdd8961fa9d13fe
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3638698
Auto-Submit: Austin Sullivan <asully@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1002495}
Notes: Security: backported fix for CVE-2022-2162.
> chore: cherry-pick 22c61cfae5d1 from chromium

- lib/renderer/security-warnings.ts
Fixes this error (the previous `import` statement leads to delay loading of `webFrame` due to how the TypeScript code is translated to JavaScript)
when bindings are removed in the preload script for security reasons (after all the imports)
> delete process.binding;
delete process._linkedBinding;
Notes: none
> refactor: load webFrame via process._linkedBinding in security-warnings.ts

- patches/chromium/printing.patch
Build tests are currently failing in `main` across the board on gclient sync - see a recent example here: https://app.circleci.com/pipelines/github/electron/electron/55166/workflows/7299e7fc-2b57-4f92-8438-3548563c256e
This PR updates the printing patch, and should get it up and running again.
Notes: none
> chore: update printing patch for main gclient sync

- shell/browser/ui/views/autofill_popup_view.cc
Closes https://github.com/electron/electron/issues/34750.
Refs CL:3560843
Fixes an issue where DataList bounds had part of the item text cut off vertically. This happened in https://github.com/electron/electron/pull/33556 when we switched from the mult-parameter form of `gfx::Insets`, since the horizontal and vertical parameters switched and we didn't catch it.
Tested with https://gist.github.com/1525a4d39d33bc46eb033af6ebcf51c1.
Notes: Fixed an issue where DataList bounds had part of the item text cut off vertically.
> fix: `<datalist>` bounds vertical cutoff

- appveyor.yml
Remove defunct webhook notification from Appveyor config.
See [example failure](https://ci.appveyor.com/project/electron-bot/electron-ia32-testing/builds/44003410):
> Error sending Webhook notification: Error calling webhook https://electron-mission-control.herokuapp.com/rest/appveyor-hook: Response status code does not indicate success: 404 (Not Found).
Notes: none
> build: remove appveyor hook to defunct service

- docs/breaking-changes.md
Chromium had dropped support for IA32 Linux, so the Chromium
102.0.4999.0 upgrade PR, https://github.com/electron/electron/pull/33731, had introduced the commit,
https://github.com/electron/electron/pull/33731/commits/389ef0731efca802db2089486ad6d9a91cc02ba8, to drop support for IA32 Linux but the change landed
without an addition to the documentation for the breaking changes,
so this PR adds that.
Closes: https://github.com/electron/electron/issues/34783
Refs: https://bugs.chromium.org/p/chromium/issues/detail?id=1194538
Notes: none
> docs: document the removal of IA32 Linux support

- patches/chromium/.patches
- patches/chromium/cherry-pick-f427936d32db.patch
- patches/chromium/m102_ensure_raw_ptr_t_and_t_are_treated_identically_in_base.patch
[M102] Ensure raw_ptr<T> and T* are treated identically in //base callback.
There are safety checks associated with raw pointers (e.g. ensuring
receiver pointers are not raw pointers). Make sure these checks are
applied whether the input type is T* or raw_ptr<T>.
- Implement base::IsPointer<T> and base::RemovePointer<T>, which are
similar to std::is_pointer<T> and std::remove_pointer<T>, except they
also consider raw_ptr<T> a raw pointer type.
- Fix failures from the strengthened asserts: WebAppInstallFinalizer
does not need a callback at all, while the privacy sandbox dialog
tests can safely use base::Unretained().
- Add test cases to cover this in the //base callback nocompile test
suite.
- Fix the existing nocompile tests, which did not escape `||` and
inadvertently matched any error …
> chore: cherry-pick f427936d32db from chromium

- patches/v8/.patches
- patches/v8/cherry-pick-d0882b3dff76.patch
- patches/v8/version_10_2_154_10_cherry-pick.patch
Version 10.2.154.10 (cherry-pick)
Merged 85b4b5d719c50ecc8f376ca853c9001d5ac0ed9a
[compiler] only enable MidTierRegisterAllocator for Wasm
Bug: chromium:1335054
Change-Id: I61ab97d4fbfcbb81319e611a64a6454e050a1d65
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/3705397
Owners-Override: Tobias Tebbi <tebbi@chromium.org>
Cr-Commit-Position: refs/branch-heads/10.2@{#18}
Cr-Branched-From: 374091f382e88095694c1283cbdc2acddc1b1417-refs/heads/10.2.154@{#1}
Cr-Branched-From: f0c353f6315eeb2212ba52478983a3b3af07b5b1-refs/heads/main@{#79976}
Ref electron/security#173
Notes: Security: backported fix for 1335054.
> chore: cherry-pick d0882b3dff76 from v8

- README.md
- docs/tutorial/examples.md
- docs/tutorial/introduction.md
- docs/tutorial/tutorial-4-adding-features.md
- docs/tutorial/tutorial-6-publishing-updating.md
- lib/browser/default-menu.ts
We continue to be plagued by the wrong Discord links, one slipped in via #34604.
This PR fixes that link, and updates all links to be `https://discord.gg/electronjs` for consistency.
Notes: none
> chore: update Discord invite links

- shell/browser/native_window_views_win.cc
- shell/browser/ui/views/win_caption_button_container.h
Closes https://github.com/electron/electron/issues/34763.
When a window with WCO is restored after the minimize button is clicked, the button was left in the `STATE_HOVERED` state. This meant that when the user restored (unminimized) the window, the button was incorrectly left painted as though the user was still hovered over it, and could only fix this by once again hovering over the button and then moving off of it. This issue is fixed by ensuring that windows controls are reset when the window is restored, since the buttons could neither be pressed or hovered over as that is occurring by the nature of the event taking place.
Tested by adding:
```js
titleBarStyle: 'hidden',
titleBarOverlay: {
color: '#2f3241',
symbolColor: '#74b1be',
height: 60
}
```
to the BrowserWindow ctor options of …
> fix: WCO pressed background state updates

- spec-main/chromium-spec.ts
- spec/fixtures/api/first-party-sets/base/main.js
- spec/fixtures/api/first-party-sets/base/package.json
- spec/fixtures/api/first-party-sets/command-line/main.js
- spec/fixtures/api/first-party-sets/command-line/package.json
First party sets are now being used by Electron app developers. Although Electron itself does not contain API code for first party sets, it would be helpful to have a few small tests to protect against any upstream changes or breaks (for example, when upgrading a Chromium role).
This PR adds two small tests to test loading FPS within an app and from the command line.
Notes: none
> test: add first-party-set chromium tests

- shell/browser/native_window_mac.mm
Closes https://github.com/electron/electron/issues/34822.
Fixes an issue where calling `BrowserWindow.setRepresentedFilename` on macOS with `titlebarStyle: 'hiddenInset'`  or `titlebarStyle: 'hidden'` inadvertently moves the traffic light location. Fix this by ensuring the traffic lights are redrawn according to the current `titleBarStyle` when `representedFilename` value is changed.
Tested with https://gist.github.com/9ad043673ca425c92bbb4e1f951c455c
Notes: Fixed an issue where calling `BrowserWindow.setRepresentedFilename` on macOS with `titlebarStyle: 'hiddenInset'`  or `titlebarStyle: 'hidden'` inadvertently moves the traffic light location.
> fix: `setRepresentedFilename` with non-default `titlebarStyle`

- shell/browser/native_window_views.cc
- spec-main/api-browser-window-spec.ts
Refs https://github.com/electron/electron/pull/34677.
Fixes a potential crash when changing window settings after initializing WCO with an invalid `titleBarStyle`. We need both to ensure that the overlay has been set and _also_ that the `titleBarStyle` is valid for the platform.
Notes: Fixed a potential crash when changing window settings after initializing WCO with an invalid `titleBarStyle`.
> fix: safer check for WCO button updates

- script/lint.js
Some folks (especially build_tools users) do not have a version of depot_tools on their path.  Just a convenience thing for us build-tools users who touch python files 😆 
> build: use third_party DEPOT_TOOLS when running lint scripts

- script/run-clang-tidy.ts
Currently tries to run `clang-tidy` even when there are no filenames to run it on if you set more jobs.
Notes: none
> chore: improve run-clang-tidy.ts behavior when filenames < jobs

- shell/browser/native_window_views.cc
- shell/browser/notifications/linux/libnotify_notification.cc
- shell/common/platform_util.h
- shell/common/platform_util_linux.cc
Electron versions prior to 18.0.0 (`<18.0.0`) were setting the [Wayland application ID](https://wayland.app/protocols/xdg-shell#xdg_toplevel:request:set_app_id) to the same value as the X11 `WM_CLASS` property. But in recent versions of Electron the Wayland's application ID property is empty (#33578).
Most likely this was caused by [this upstream Chromium change](https://chromium-review.googlesource.com/c/chromium/src/+/3347575) which introduced the [`wayland_app_id`](https://source.chromium.org/chromium/chromium/src/+/main:ui/platform_window/platform_window_init_properties.h;l=132-134;drc=f28f4f8f90c4494c9bc9f34a28f5dcc215caa077) property.
This pull-request makes use of the `wayland_app_id` property by setting its value to the *basename of the application's `.desktop` file*.
Fixes #33578 …
> fix: set Wayland application ID

- patches/webrtc/.patches
- patches/webrtc/cherry-pick-763d847f1e5a.patch
[M102] Do not allow simulcast to be turned off using SDP munging
This is an error that puts the PC into an inconsistent state, so
causing a crash is the right thing to do.
(cherry picked from commit 3fe8b0d9a980642ee5ebb1f9e429378b063c1f07)
TBR=hta@webrtc.org
Bug: chromium:1341043
Change-Id: Ie1eb89400ad87f0c83634b7073236b07e92ec7ab
Reviewed-on: https://webrtc-review.googlesource.com/c/src/+/267281
Reviewed-by: Mirko Bonadei <mbonadei@webrtc.org>
Reviewed-by: Henrik Boström <hbos@webrtc.org>
Commit-Queue: Harald Alvestrand <hta@webrtc.org>
Cr-Original-Commit-Position: refs/heads/main@{#37391}
Reviewed-on: https://webrtc-review.googlesource.com/c/src/+/267427
Commit-Queue: Taylor Brandstetter <deadbeef@webrtc.org>
Reviewed-by: Guido Urdaneta <guidou@webrtc.org> …
> chore: cherry-pick 763d847f1e5a from webrtc

- patches/v8/.patches
- patches/v8/cherry-pick-13ffdf63a471.patch
Merged: [compiler] make CanCover() transitive
In addition to checking that a node is owned, CanCover() also needs to
check if there are any side-effects in between the current node and
the merged node. When merging inputs of inputs, this check was done
with the wrong side-effect level of the in-between node.
We partially fixed this before with `CanCoverTransitively`.
This CL addresses the issue by always comparing to the side-effect
level of the node from which we started, making `CanCoverTransitively`
superfluous.
Bug: chromium:1336869
(cherry picked from commit 6048f754931e0971cab58fb0de785482d175175b)
Change-Id: I63cf6bfdd40c2c55921db4a2ac737612bb7da4e4
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/3722095 …
> chore: cherry-pick 13ffdf63a471 from v8

- filenames.gni
- shell/browser/ui/views/win_caption_button.cc
- shell/browser/ui/views/win_caption_button.h
- shell/browser/ui/views/win_icon_painter.cc
- shell/browser/ui/views/win_icon_painter.h
Refs CL:3674580
This PR updates WCO restore and maximize buttons to match Windows 11 design. It also refactors out the functionality into its own file, as the above CL does, to make it more maintainable an extensible
Notes: Updated Windows Control Overlay buttons to look and feel more native on Windows 11.
> fix: update Windows caption buttons to match Win11 style

- shell/app/electron_content_client.cc
- shell/renderer/renderer_client_base.cc
When widevine was disabled at the build level we never dealt with the callback passed into GetSupportedKeySystems.  This was ok until requests became marked pending in https://chromium-review.googlesource.com/c/chromium/src/+/3430502 until the callback was called.  This resulted in a promise never resolving / rejecting and certain media websites (E.g. spotify) hanging on load waiting for a signal that would never arrive.
Notes: Ensures that `requestMediaKeySystemAccess` eventually resolves / rejects
> fix: ensure that requestMediaKeySystemAccess resolves

- shell/browser/api/electron_api_push_notifications.h
- shell/browser/api/electron_api_push_notifications_mac.mm
- shell/browser/mac/electron_application_delegate.mm
Refs https://github.com/electron/electron/pull/33574.
Hotfixes incorrect `base::DictionaryValue` usage.
Notes: none.
> fix: `base::DictionaryValue` usage in APNS notifs

- shell/browser/native_window_views.cc
Fixes #32889
On X11 when alwaysOnTop was set as a browser window preference, it got applied to the window before showing it. While that set the z-index of the window in X11, it didn't take effect, it just behaved as a window without alwaysOnTop.
This was working correctly prior to Electron 16, but not ever since. No idea why it broke, didn't find any trace for it.
Notes: Fix alwaysOnTop BrowserWindow option for X11 Linux
> fix: alwaysOnTop browser window option for X11 Linux

- patches/chromium/.patches
- patches/chromium/remove_default_window_title.patch
Backport of https://chromium-review.googlesource.com/c/chromium/src/+/3722478.
The change landed on main recently in the latest chromium 105.0.5173.0
upgrade - https://github.com/electron/electron/pull/34770, so it would
not be backported automatically to the currently supported stable
branches, so I thought it would make sense to manually backport it.
Fixes: https://github.com/electron/electron/issues/34467
Notes: Prevent brief display of "Ozone X11" in window title on Linux.
> fix: prevent brief display of "Ozone X11" in window title on Linux

- .circleci/config/base.yml
CircleCI has been timing out frequently on our macOS release jobs, eg:
https://app.circleci.com/pipelines/github/electron/electron/55680/workflows/dca75325-3a54-4600-a06e-0d34ee650ec0.
This PR updates the timeout waiting for goma to 5 minutes.  This should be enough time to accommodate hiccups without waiting too long.
Notes: none
> ci: wait longer for goma to be ready

- patches/chromium/printing.patch
Fixes a potential printing hang. Before this fix, if the `printing_context_` failed to resolve the default settings, `GetSettingsDone` would never be called. This corrects the issue.
Notes: Fixed a potential printing hang.
> fix: potential hang on print settings failure

- script/node-disabled-tests.json
- script/node-spec-runner.js
Adds the ability to check that all tests currently disabled via `node-disabled-tests.json` still exist. This is especially helpful during Node.js upgrade rolls, to ensure that our skip test file is still up to date.
Notes: none.
> test: optionally validate disabled Node.js specs

- shell/browser/native_window_mac.mm
- spec-main/api-browser-window-spec.ts
Fixes https://github.com/electron/electron/issues/34707.
Fixes an issue where calling `BrowserWindow.setEnabled(false)` would crash. This was happening because we were attempting to create a sheet modal on the window with itself. Fix this by instead creating a dummy sheet window to disable interaction with the main window.
Notes: Fixed a crash when calling `BrowserWindow.setEnabled()`.
> fix: crash on `BrowserWindow.setEnabled()`

- shell/browser/printing/print_view_manager_electron.cc
Closes https://github.com/electron/electron/issues/34813.
Fixes an issue where invalid `pageSize` values would cause a silent hang and eventual crash. This was happening because our `PrintVieeManager` was incorrectly delegating failures back to `PrintViewManagerBase` for non-headless job failures. Correct this issue by delegating when the job is a regular printer job and not a headless PDF job.
Notes: Fixes an issue where invalid `pageSize` values would cause a silent hang and eventual crash.
> fix: delegate to `PrintViewManagerBase` on failed print

- shell/app/electron_crash_reporter_client.cc
ElectronCrashReporterClient::GetProcessSimpleAnnotations() merges
annotations provided as argument with global_annotations_,
preserving useful information.
Notes: more crash annotations preserved
> fix: merge crash annotations instead of overwriting

- patches/v8/.patches
- patches/v8/cherry-pick-8ea66a7833e2.patch
Merged: [compiler] fix FrameState revisit bug in escape analysis
(cherry picked from commit 17da9e70833014e0a2646db5c11588f0aee02de7)
Bug: chromium:1340335, chromium:1315901
Change-Id: I81cdc6bc3d6c7441ebc333d33801329c05fbd5d4
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/3755103
Reviewed-by: Thibaud Michaud <thibaudm@chromium.org>
Commit-Queue: Samuel Groß <saelo@chromium.org>
Cr-Commit-Position: refs/branch-heads/10.2@{#25}
Cr-Branched-From: 374091f382e88095694c1283cbdc2acddc1b1417-refs/heads/10.2.154@{#1}
Cr-Branched-From: f0c353f6315eeb2212ba52478983a3b3af07b5b1-refs/heads/main@{#79976}
Ref electron/security#183
Notes: Security: backported fix for 1340335.
> chore: cherry-pick 8ea66a7833e2 from v8

- patches/chromium/.patches
- patches/chromium/cherry-pick-3cbd5973d704.patch
Keep refptr to ServiceWorkerVersion in MaybeTimeoutRequest
The callback in ServiceWorkerVersion::MaybeTimeoutRequest may reduce the
reference to the version object, which can be the last reference to it.
In thet case, the object can be destroyed and the `inflight_requests_`
field access after the callback become invalid.
This CL keeps this to avoid the object destruction.
(cherry picked from commit 5926fa916d9ad53c77e31ee757e1979275d7466c)
Bug: 1339844
Change-Id: I6564627bad0527dea007ca73261c5636dab56755
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3739330
Commit-Queue: Yoshisato Yanagisawa <yyanagisawa@chromium.org>
Reviewed-by: Hiroki Nakagawa <nhiroki@chromium.org>
Reviewed-by: Sergei Glazunov <glazunov@google.com> …
> chore: cherry-pick 3cbd5973d704 from chromium

- filenames.gni
- shell/browser/electron_browser_main_parts.cc
- shell/browser/electron_browser_main_parts.h
- shell/browser/electron_browser_main_parts_linux.cc
Add support for the `--ozone-platform-hint` flag in order to make it easier for users to switch between the X11 and Wayland platforms (e.g.: by using `--ozone-platform-hint=auto`).
~This was implemented by reusing the [same logic from upstream](https://chromium-review.googlesource.com/c/chromium/src/+/3188974), but it required implementing [`chrome::SessionEnding()`](https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/lifetime/application_lifetime.h;l=84-85;drc=627a149e7e191267a05b354a2bb697394bf4e1ae) which is a bit hacky. This was necessary due to [this call](https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/chrome_browser_main_extra_parts_ozone.cc;l=23;drc=627a149e7e191267a05b354a2bb697394bf4e1ae) from ` …
> fix: add support for --ozone-platform-hint flag on Linux

- patches/chromium/printing.patch
Refs https://github.com/electron/electron/issues/34813.
Fixes an issue where invalid print job settings would correctly call back `Invalid print settings` as the failure reason, but would then not terminate the print job, leading to an eventual crash on exit. As a side effect of this, the job success status variables have been streamlined and converted into an enum.
Notes: Fixed an issue where invalid print job settings would correctly call back `Invalid print settings` as the failure reason, but would then not terminate the print job, leading to an eventual crash on exit.
> fix: clean up callback handling in `webContents.print()`

- lib/browser/api/web-contents.ts
- typings/internal-electron.d.ts
This method was once used for the remote module, and is no longer used.
Notes: none
> chore: remove unused WebContents._sendToFrameInternal

- patches/chromium/.patches
- patches/chromium/cherry-pick-d7a5d6b38ea8.patch
Fix dawn write handle data update OOB check
(cherry picked from commit 0ba6ae3d447de7bc599a191f6792a4e6676f10a3)
Bug: chromium:1340654
Change-Id: I9d87cb868eccc380f707ab6c3c6bdc26c386fbfc
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3738662
Commit-Queue: Shrek Shao <shrekshao@google.com>
Reviewed-by: Corentin Wallez <cwallez@chromium.org>
Cr-Original-Commit-Position: refs/heads/main@{#1021911}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3758974
Reviewed-by: Austin Eng <enga@chromium.org>
Commit-Queue: Austin Eng <enga@chromium.org>
Auto-Submit: Shrek Shao <shrekshao@google.com>
Cr-Commit-Position: refs/branch-heads/5005@{#1246} …
> chore: cherry-pick d7a5d6b38ea8 from chromium

- patches/chromium/.patches
- patches/chromium/cherry-pick-22abbad430b6.patch
[M102-LTS] WebGPU: Mark the context lost on GPU context lost
M102 merge issues:
- dawn_control_client_holder.h/cc:
GetWGPUInstance() not present in M102
Fixes a bug where completely destructing the context instead of
marking it lost when receiving a context lost notification freed
memory still accessible by the page.
Fixed: 1336014
Change-Id: I662e531102af91362b4f62700bfbee507fc44d1f
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3708646
Commit-Queue: Austin Eng <enga@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1017003}
(cherry picked from commit 6c7f327b7a15aabd3fc5d57e9c05b95d02f1cd36)
Ref electron/security#186
Notes: Security: backported fix for 1336014.
> chore: cherry-pick 22abbad430b6 from chromium

- docs/development/build-instructions-linux.md
This PR slightly updates the required packages needed to build Electron on Fedora, based on a recent debugging session. Two packages are no longer available and have been removed, and one package was needed that wasn't listed (see `.build/install-build-deps.sh` in Chromium src for more information) 
Notes: none
> docs: update build dependencies for Fedora
