docs/tutorial/introduction.md
The introduction page in the official docs has a missing link to the tutorial page
Add missing link to tutorial page from `introduction.md`
Notes: none
=> docs: Add missing link to tutorial page

shell/browser/serial/electron_serial_delegate.cc, shell/browser/serial/electron_serial_delegate.h, shell/browser/serial/serial_chooser_context.cc, shell/browser/serial/serial_chooser_context.h, shell/browser/serial/serial_chooser_controller.cc, shell/browser/serial/serial_chooser_controller.h
Closes https://github.com/electron/electron/issues/34887.
Notes: fixed `serial-port-added` and `serial-port-removed` events not firing.
=> fix: properly fire serial-port-added and serial-port-removed events

patches/chromium/.patches, patches/chromium/keep_handling_scroll_update_if_you_can.patch
Fixes #35049
Backport: https://chromium-review.googlesource.com/c/chromium/src/+/3681882
Notes: Fixed inertial scroll is broken when the scrollable element has an overlay with pointer-events: none.
=> fix: inertial scroll is broken when the scrollable element has an overlay with pointer-events: none

patches/chromium/disable_color_correct_rendering.patch
In Chromium 100, [this change](https://chromium-review.googlesource.com/c/chromium/src/+/3448774) made it so that color space was read from `ColorTargetParams` versus being passed into functions directly. This made the flag stop working in CSS and IMG. With this PR, color space will be added to `ColorTargetParams` before returning.
In Chromium 103 (or earlier), [this change](https://chromium-review.googlesource.com/c/chromium/src/+/3449754) integrated `TargetColorParams` in a few more places. There's no preset for "Unmanaged", so the flag stopped working in GL canvases. With this PR, we'll detect if the flag is enabled, and if so, return `gfx::ColorSpace()` to use an unmanaged color space. 
Notes: none
=> fix: Make disable_color_correct_rendering patch work again

spec/chromium-spec.js
Windows CI has been hanging while running `spec/chromium-spec.js`, eg: https://ci.appveyor.com/project/electron-bot/electron-x64-testing/builds/44279018
Investigating this, I found that removing the test `chromium feature window.open accepts "nodeIntegration" as feature` resolves the hang as seen by this test run that runs through that test file 100 times:
https://ci.appveyor.com/project/electron-bot/electron-x64-testing/builds/44276581.
Researching further, we basically have a duplicate test in spec-main: https://github.com/electron/electron/blob/main/spec-main/chromium-spec.ts#L842, so this test is not necessary in `spec/chromium-spec.js` anymore. so I removed it completely.
Notes: none
=> test: remove duplicate test that is causing hang in Windows

shell/browser/native_window_views.h, shell/browser/native_window_views_win.cc
Refs https://github.com/electron/electron/issues/34763#issuecomment-1195342899 - augments previous solution in https://github.com/electron/electron/pull/34771 to handle the case where a window is unminimized directly back into a maximized state without being restored. The previous solution incorrectly assumed that a window would be restored after being maximized.
Notes: Fixed a Windows Control Overlay issue where a window taken directly from minimized to maximized state could have incorrect hover state.
=> fix: handle WCO pressed state when going maximized -> minimized

shell/browser/native_window_views.cc
Closes #34599
Refs #33288
Refs #33279
The prior work in #33279 to allow calling SetBounds during a resize or move (defined as time period between receiving a WM_MOVING or WM_SIZING--respectively--and WM_EXITSIZEMOVE WNDPROC message) prevented the ability to call preventDefault() within 'will-resize' or 'will-move' and then call SetBounds to change the size and position of the window immediately.  After the PR, the window does not change bounds until the user ends the resize or move by releasing the mouse button, e.g. This PR simply removes the early-return statement to forward the SetBounds call to the widget, allowing for the bounds to change immediately if the movement or resizing has been cancelled through 'preventDefault' or after it has ended otherwise.
Tested with …
=> fix: allow setsize to be called within a move or resize for preventDefault

appveyor.yml, build/extract_symbols.gni, script/release/release.js, script/release/uploaders/upload.py
Addresses #34413
We're currently experiencing build failures on main, 20-x-y and 18-x-y because the ia32 symbol generation is running out of virtual memory space. This PR uses the win_clang_x64 binary to extract/generate electron symbols for Windows x86.
_Note: This issue isn't currently affecting 19-x-y, but it was introduced into 18-x-y by a backported Chromium roll. Adding this change to 19-x-y will protect us against a potential future breakage in that branch._
Notes: Fixed symbol generation on 32-bit Windows release builds.
=> fix: use win_clang_x64 binary for x86 extract symbols

shell/browser/electron_browser_main_parts.cc
Fixes #34996.
This is a regression introduced in 20.0.0-beta.9 caused by `ElectronBrowserMainParts::PreCreateThreads()` creating the main window before loading the locale resource bundle, but `ui::BuildDisplaysFromXRandRInfo()` needed that locale info to be loaded.
CC @electron/wg-releases 
Notes: Fix 20.0.0-beta.8 X11 crash regression.
=> fix: crash on startup in X11

docs/api/app.md
Add warning about late registration of the `open-url` event, similar to that of `open-file`.
Notes: none
=> docs: don't wait for ready event to register open-url listener

script/lint.js
https://chromium-review.googlesource.com/c/chromium/tools/depot_tools/+/3780302 broke lint because we were using `pylint` instead of a specific version.  This PR fixes our linting to explicitly use `pylint-1.5` since that is what the `pylint` alias was pointing to.
Notes: none
=> ci: explicitly use pylint-1.5 for pylint

build/extract_symbols.gni
Manual backport of #35078 
Notes: Fixed symbol generation on 32-bit Windows release builds
=> fix: use win_clang_x64 binary for x86 extract symbols (#35078)

patches/chromium/.patches, patches/chromium/cherry-pick-664e0d8b4cfb.patch
[M96-LTS] Fix incorrect text itemization for \r codepoint
render_text_unittest.cc
Tests Clusterfuzz_Issue_1298286/1299054 aren't present
in M96 and caused a merge conflict.
The "\r" codepoint should be split to be rendered in a single
harfbuzz run (same as "\n").
We do recognize these sequences as newline:
\r
\n
\r\n
Previously, the itemization will leave the "\r" with the previous
run. This is leading to incorrect multiline lines splitting.
(cherry picked from commit eee0c5ca752ad50df9986c551cb98226ce078893)
Bug: 1287804
Change-Id: Idfc00a3cf147eb53258d5da9ea105e2d6dc25f05
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3708936
Commit-Queue: Etienne Bergeron <etienneb@chromium.org>
Cr-Original-Commit-Position: refs/heads/main@{#1014955} …
=> chore: cherry-pick 664e0d8b4cfb from chromium

patches/chromium/.patches, patches/chromium/cherry-pick-2a2d7536227b.patch
[M96-LTS] WebGPU: Mark the context lost on GPU context lost
- gpu.h:
BoxedMappableWGPUBufferHandles not present in M96
- dawn_control_client_holder.h/cc:
GetWGPUInstance() not present in M96
- Copied part of the DEPS rules from https://crrev.com/c/3456506 to
fix a presubmit issue:
** Presubmit ERRORS **
You added one or more #includes that violate checkdeps rules.
third_party/blink/renderer/modules/webgpu/gpu_context_lost_test.cc
Illegal include: "base/run_loop.h"
Because of "-base" from third_party's include_rules.
Fixes a bug where completely destructing the context instead of
marking it lost when receiving a context lost notification freed
memory still accessible by the page.
(cherry picked from commit 6c7f327b7a15aabd3fc5d57e9c05b95d02f1cd36)
Fixed: 1336014 …
=> chore: cherry-pick 2a2d7536227b from chromium

patches/pdfium/.patches, patches/pdfium/cherry-pick-3466cc056b05.patch
M102: Retain nodes when manipulating their dictionaries in CPDF_NameTree.
-- Pass retain ptrs consistently in a few other places.
Bug: chromium:1335861
Change-Id: If23cf6b6ec39ef02384beaa6745e1c7256160cba
Reviewed-on: https://pdfium-review.googlesource.com/c/pdfium/+/94430
(cherry picked from commit ebebb757c1f210ccc16e0cb2b425860a141a4e9f)
Reviewed-on: https://pdfium-review.googlesource.com/c/pdfium/+/95271
Reviewed-by: Nigi <nigi@chromium.org>
Notes: Security: backported fix for CVE-2022-2478.
=> chore: cherry-pick 3466cc056b05 from pdfium

patches/chromium/.patches, patches/chromium/cherry-pick-902f0d144a5b.patch
Mitigate bad cast in OffscreenCanvas::GetFontSelector
This change will cause the browser to crash if the execution context
is not a Window or WorkerGlobalScope.  This is a temporary solution
to handle the case where the execution context is an
AudioWorkletGlobalScope.  The longer term solution, which will be
implemented in a follow-up CL, is to block OffscreenCanvas objects from
being transferred to AudioWorklets, as required by the postMessage spec.
BUG=1334864
(cherry picked from commit 028c11e59fd41bc22eff06dbec10fe9b0e82bd04)
Change-Id: Ief5e37eca6dff14098b12cdbe6fc362c3dd87d1d
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3722117
Auto-Submit: Justin Novosad <junov@chromium.org>
Reviewed-by: Juanmi Huertas <juanmihd@chromium.org>
Commit-Queue: Juanmi Huertas …
=> chore: cherry-pick 902f0d144a5b from chromium

shell/browser/api/electron_api_web_contents.cc, shell/browser/electron_browser_context.cc, shell/browser/electron_browser_context.h, spec-main/api-web-contents-spec.ts
Closes https://github.com/electron/electron/issues/35046.
Refs https://github.com/electron/electron/pull/34481 - this change made it such that we were [no longer initializing the user agent](https://github.com/electron/electron/pull/34481/files#diff-fa823350727ad86e0ac08c18d6f17e24a62d653b43a08242e4608f5a8ee8e5b9L110) and so it would always be empty when calling `webContents.getUserAgent()` unless it had been previously set by `webContents.setUserAgent(agent)`. This fixes that, and incidentally removes the need to have a separate `GetUserAgentOverride`.
Confirmed not to regress https://github.com/electron/electron/issues/30201
Notes: Fixed `webContents.getUserAgent()` incorrectly returning an empty string unless previously set.
=> fix: empty result of `webContents.getUserAgent()`

docs/tutorial/message-ports.md
Added a code example describing how to set up a `messageChannel` between two renderers from inside of main. 
Notes: none
=> docs: new main -> renderers messageChannel example

shell/browser/web_contents_preferences.cc, spec-main/fixtures/apps/libuv-hang/main.js, spec/webview-spec.js
Manual backport of #32869 
Notes: Notes: Renderers are now sandboxed by default unless `nodeIntegration: true` or `sandbox: false` is specified.
=> feat: sandbox preloads by default

docs/api/browser-window.md, shell/browser/native_window_views.cc
This doesn't work in Wayland and won't be fixed. The feature couldn't be removed in e19 due to the policy of not removing features that aren't advertised in advance in Breaking Changes, so it was listed in e19 and is being removed now for e20.
See #33226 for more information.
CC @electron/wg-releases 
Notes: Removed the skip-taskbar feature on Linux.
=> fix: remove skip-taskbar feature on Linux.

.circleci/config/base.yml
#34983 updated the version of macOS used to build Electron because CircleCI removed support for that version of macOS.  Unfortunately the new version of macOS has less disk space and caused publish jobs to run out of disk space, eg: https://app.circleci.com/pipelines/github/electron/electron/56260/workflows/3bc90396-6f1a-4436-920e-17400f1a93db/jobs/1281741
This PR changes the mac publish jobs to use `macos.x86.medium.gen2` machines which have a large disk.
Notes: none
=> build: use macos.x86.medium.gen2 for macos publish jobs

shell/browser/api/electron_api_web_contents.cc, shell/browser/native_window.cc, shell/browser/native_window.h, shell/browser/ui/cocoa/electron_ns_window_delegate.mm, spec-main/api-browser-window-spec.ts
Fixes a DCHECK introduced by https://github.com/electron/electron/pull/32905. This was happening because I adapted `WebContents::IsFullscreenForTabOrPending` to also return true if the window was in a fullscreen transition state, but this only applies in the context of the problem is the window is entering fullscreen _from html_. e.g. with `document.enterFullscreen()`. This change makes it so that html fullscreen and native fullscreen both receive appropriate values.
```
88442:0728/112318.332158:FATAL:web_contents_impl.cc(5858)] Check failed: !IsFullscreen(). 
0   Electron Framework                  0x000000012a8a7ec2 base::debug::CollectStackTrace(void**, unsigned long) + 18
1   Electron Framework                  0x000000012a7c5223 …
```
=> fix: DCHECK entering fullscreen while loading url

.github/workflows/electron_woa_testing.yml
This PR turns off the newly added test result comments on WOA jobs eg: https://github.com/electron/electron/pull/35137#issuecomment-1199944379 because those comments generate unnecessary notifications.
Notes: none
=> ci: turn off windows on arm test result comments

shell/browser/electron_download_manager_delegate.cc, shell/browser/electron_download_manager_delegate.h
Closes #34450
Previously when saving a file on Windows, the file type would not be defined based on the extension of the file. (The linked issue also mentions that the file name should include the extension, but I could not replicate this on non-Electron applications). The file dialog will now properly display the file type and the saved file will include the extension.
Notes: None
=> fix: modify file extension generation on Windows

patches/chromium/.patches, patches/chromium/chore_allow_chromium_to_handle_synthetic_mouse_events_for_touch.patch, shell/browser/ui/win/electron_desktop_window_tree_host_win.cc, shell/browser/ui/win/electron_desktop_window_tree_host_win.h
Backport of https://github.com/electron/electron/pull/35117
Notes: fix WCO not responding to touch events on windows.
=> fix: touch events not recognized by WCO on windows (#35117)

shell/common/logging.cc
Some apps use logging in production to collect data in the wild. However,
there's no way for such apps to recover from a situation in which logging fails
(e.g. if the log file location is not accessible).
Instead of crashing, log (?) an error and continue.
Notes: Do not exit when logging initialization fails.
=> fix: fail non-fatally when InitLogging fails

build/args/all.gn
This PR adds a new node module version number for Electron 21.
Node PR here: https://github.com/nodejs/node/pull/44034
_NOTE: ~Please hold until the node PR has been merged~ Node PR is merged_
Notes: none
=> chore: update NMV for Electron 21

shell/browser/api/electron_api_menu_mac.mm
Use `visibleFrame` instead of `frame` when computing edge of screen, the former excludes the dock and menubar from the frame.
Close https://github.com/electron/electron/issues/14261.
Notes: Fix context menu not showing all items on macOS when dock is not hidden.
=> fix: consider dock space when showing menu

docs/tutorial/tutorial-6-publishing-updating.md
The dot at the end of the URL will depend on the site that cannot open. Because it will open `https://update.electronjs.org./` which does not exist.
Notes: none
=> docs: Fix the URL bugs at tutorial-6-publishing-updating.md

patches/chromium/.patches, patches/chromium/do_not_reduce_page_size_from_64k_to_4k_on_linux_arm64.patch
https://github.com/electron/electron/pull/34385 only addressed allocator side of changes to support 16k page sizes on Linux arm64, turns out there was also a compile time restriction. The fix is already present in Chromium >= 102.
Backports https://chromium-review.googlesource.com/c/chromium/src/+/3542265
Notes: Fix page size always being restricted to 4k on Linux arm64
=> chore: cherry-pick 97193a64b431 from chromium

docs/api/tray.md
Updates tray documentation to make creating tray icons on macos a bit clearer.
Notes: none
=> docs: update tray docs with info for mac menubar icons

package.json, yarn.lock
Fixes https://app.circleci.com/pipelines/github/electron/electron/56459/workflows/8871d616-7680-4a32-a486-530221587750/jobs/1285883 by pulling in https://github.com/levp/wrapper-webpack-plugin/commit/ab85c307150e9f289b22b6c7b8bca446b25ce67f.
Notes: none
=> build: fix webpack prod failure

patches/webrtc/.patches, patches/webrtc/cherry-pick-06aea31d10f8.patch
[Merge-104] Disallow invalid arguments in RestoreEncodingLayers.
Changing DCHECK into CHECK for good measure.
(cherry picked from commit 2b1f509f3a05035a17917061a71b16114e8c72dc)
No-Try: True
Bug: chromium:1343889
Change-Id: I2cede85dc2d2a4238739f73afe25275047f4aa50
Reviewed-on: https://webrtc-review.googlesource.com/c/src/+/268460
Reviewed-by: Ilya Nikolaevskiy <ilnik@webrtc.org>
Commit-Queue: Henrik Boström <hbos@webrtc.org>
Cr-Original-Commit-Position: refs/heads/main@{#37511}
Reviewed-on: https://webrtc-review.googlesource.com/c/src/+/269242
Cr-Commit-Position: refs/branch-heads/5112@{#8}
Cr-Branched-From: a976a871159f85f975fbd6f170d0a8f00a4aee49-refs/heads/main@{#37168}
Notes: Security: backported fix for chromium:1343889.
=> chore: cherry-pick 06aea31d10f8 from webrtc

.circleci/config/base.yml
Fixes the following error: https://app.circleci.com/pipelines/github/electron/electron/56517/workflows/ea0f6548-e0ac-40c6-bacb-e24610cd6670/jobs/1287168?invite=true#step-103-29
```sh
$ webpack --config build/webpack/webpack.config.asar.js --output-filename=asar.js --output-path=./.tmp --env.mode=development
[webpack-cli] Error: Unknown option '--env.mode=development'
[webpack-cli] Run 'webpack --help' to see available commands and options
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
This probably started happening because of the recent webpack upgrade in https://github.com/electron/electron/pull/34990.
Notes: none
=> build: fix error in the `ts-compile-doc-change` step

patches/chromium/.patches, patches/chromium/cherry-pick-c643d18a078d.patch
[BackgroundFetch] Don't expose URL chain in case of CO redirect
Bug: 1278255
Change-Id: If853327b853e29792e5c8d1dfaeecf21d6fec004
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3693143
Reviewed-by: Susanne Westphal <swestphal@google.com>
Commit-Queue: Rayan Kanso <rayankans@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1011409}
Notes: Security: backported fix for CVE-2022-2610.
=> chore: cherry-pick c643d18a078d from chromium

patches/chromium/.patches, patches/chromium/cherry-pick-bd9724c9fe63.patch
[M104][Background fetch] passing update_first_party_url_on_redirect=false for fetch
Background fetch doesn't work like regular download as it is not
considered a top frame navigation. This CL let background fetch to
pass update_first_party_url_on_redirect=false to DownloadURLParameters,
and handle it properly w.r.t samesite cookies.
BUG=1268580
(cherry picked from commit bf1e93c6af21dad12088b615feda07a90a85c158)
Change-Id: I3a1cc33be8578d5d8c796dbbb21fa35a47bdda36
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3712307
Reviewed-by: Rayan Kanso <rayankans@chromium.org>
Commit-Queue: Min Qin <qinmin@chromium.org>
Cr-Original-Commit-Position: refs/heads/main@{#1016316}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3727786 …
=> chore: cherry-pick bd9724c9fe63 from chromium

docs/tutorial/tutorial-2-first-app.md
I just fixed a small typo in the section on debugging with VSCode
> If you want to debug your application using VS Code, you **have need** attach VS Code to both the main and renderer processes.
to
> If you want to debug your application using VS Code, you **need to** attach VS Code to both the main and renderer processes.
notes: Fixed a typo in the section on debugging with VSCode
Notes: 
notes: Fixed a typo in the section on debugging with VSCode
=> fix(docs): fix a typo in section on debugging with VSCode

docs/api/web-contents.md, shell/browser/api/electron_api_web_contents.cc
Closes https://github.com/electron/electron/issues/34129.
This change matches Chromium behavior for WCO by opening DevTools in detached mode if WCO is enabled.
This prevents the DevTools from being occluded and becoming semi-unusable.
</details>
</details>
Notes: Fixed an issue where WCO could occlude DevTools opened in any non-detached mode.
=> fix: WCO occlusion of DevTools

npm/package.json
Aligns our npm package with the newest version of @electron/get, and the new minimum version of Node that is required (see @electron/get PR here: https://github.com/electron/get/pull/225 )
Notes: Bumps the minimum required version of Node.js needed to install Electron to 12.20.55
=> build: bump @electron/get to 2.0.0, node to >= 12+

patches/chromium/.patches, patches/chromium/cherry-pick-54a7927b19f9.patch
Merge 104: Speculative fix for IsValidCodePointInIndex() range crash
(cherry picked from commit b4d1ce62d7783a9b31a0a2bec1b886a9a6519a40)
Bug: 1333970
Change-Id: I5a4c78e708357074fdec1f7a18fa928e39f9c51a
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3757922
Auto-Submit: Aaron Leventhal <aleventhal@chromium.org>
Reviewed-by: Nektarios Paisios <nektar@chromium.org>
Commit-Queue: Aaron Leventhal <aleventhal@chromium.org>
Cr-Original-Commit-Position: refs/heads/main@{#1025405}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3788215
Cr-Commit-Position: refs/branch-heads/5112@{#1206}
Cr-Branched-From: b13d3fe7b3c47a56354ef54b221008afa754412e-refs/heads/main@{#1012729}
Notes: …
=> chore: cherry-pick 54a7927b19f9 from chromium

docs/fiddles/features/drag-and-drop/preload.js, docs/tutorial/native-file-drag-drop.md
notes: Removes unused import which causes issue in preload script of drag and drop tutorial
It fails to run with the error.
```
VM4 sandbox_bundle:93 Error: module not found: path
at preloadRequire (VM4 sandbox_bundle:93:1386)
at <anonymous>:3:14
at runPreloadScript (VM4 sandbox_bundle:93:2213)
at Object.<anonymous> (VM4 sandbox_bundle:93:2480)
at ./lib/sandboxed_renderer/init.ts (VM4 sandbox_bundle:93:2636)
at __webpack_require__ (VM4 sandbox_bundle:1:170)
at VM4 sandbox_bundle:1:1242
at ___electron_webpack_init__ (VM4 sandbox_bundle:1:1320)
at VM4 sandbox_bundle:160:455
```
Notes: Removes unused import which causes issue in preload script of drag and drop tutorial
=> docs: removes unused import in preload script

shell/common/node_bindings.cc
stop_and_close_uv_loop add call uv_loop_close.
In the destructor of NodeBindings, stop_and_close_uv_loop is called, but stop_and_close_uv_loop does not call uv_loop_close. After NodeBindings are destructed, libuv still holds the member objects of NodeBindings. When power resume, libuv enumerates all loops, and will accesses a pointer that has been released.
as issue https://github.com/electron/electron/issues/32926
About npm test in checklist.  Before I modified the code, 15 cases could not pass on my computer. After I modified, the failed  cases did not increase, so there should be no problem with npm test.
Resolves #32926
Notes: Fixed crash in renderer when resuming system from sleep
=> fix: add uv_loop_close when object release to fix crash

filenames.gni, shell/browser/ui/views/win_caption_button.cc, shell/browser/ui/views/win_caption_button.h, shell/browser/ui/views/win_icon_painter.cc, shell/browser/ui/views/win_icon_painter.h
Fixes https://github.com/electron/electron/issues/35038
Backport of #34790. However, the fix also incorporates https://chromium.googlesource.com/chromium/src/+/30a32e6d6909e8e6e267b48bb7294e739b210c51 which is part of https://bugs.chromium.org/p/chromium/issues/detail?id=1316028.
The screenshot below has the cursor hovering over the restore button.
Notes: Fixed the alignment of the WCO restore button.
=> fix: WCO restore button is off-center

shell/browser/serial/electron_serial_delegate.cc, shell/browser/serial/serial_chooser_context.cc, shell/browser/serial/serial_chooser_context.h
Closes https://github.com/electron/electron/issues/35282.
Fixes an issue where `serialPort.open()` failed with `NetworkError: Failed to open serial port.`.
This was happening because we returned `nullptr` from `ElectronSerialDelegate::GetPortInfo`: https://github.com/electron/electron/blob/648c9934c01c12ea082a18fdf690c37e3112ce12/shell/browser/serial/electron_serial_delegate.cc#L91-L96
and `SerialService::OpenPort` expects that `delegate->GetInfo` [returns non-null](https://source.chromium.org/chromium/chromium/src/+/main:content/browser/serial/serial_service.cc;l=128;drc=06106fa71f3ed1044028f77ccf4d5b9de7028b8b;bpv=1;bpt=1) in order to succeed.
Tested with https://gist.github.com/17afc65be515f3a1aec6256cb69f069d and an Arduino Uno.
Notes: Fixed an issue where `serialPort.open()` failed …
=> fix: `serialPort.open()` failing

lib/browser/api/web-contents.ts
Follow-up to #34959.
The order in this case does not match the documentation: https://github.com/electron/electron/blob/main/docs/api/web-frame-main.md#frameipc-readonly
Notes: none
=> fix: IPC emit order in -ipc-ports handler

patches/chromium/disable_color_correct_rendering.patch
This PR updates `disable_color_correct_rendering.patch` to make it work with images in WebGL canvases. Without this change, attempting to render an image inside of a WebGL canvas, with the `disable_color_correct_rendering` flag enabled, will cause a crash in the renderer. This was introduced in https://github.com/electron/electron/pull/35050.
The crash is caused because `unpack_color_space` is null. So this PR adds a check to see that it's not null before sending it to `ConvertToColorSpace`. The reason that it is null in the first place is that `gfx::ColorSpace()` is not a "valid" color space according to Skia. So when we call `gfx::ColorSpace().ToSkColorSpace()` we get null back.
This crash only occurs in Electron 19. The code in Chromium in Electron 20 is rewritten, and does not have …
=> fix: Make the disable_color_correct_rendering flag work with textured images

shell/browser/api/electron_api_web_frame_main.cc, spec/api-web-frame-main-spec.ts
Closes https://github.com/electron/electron/issues/32756.
Closes https://github.com/electron/electron/issues/32164.
PR changes the backend for `WebFrameMain::ExecuteJavaScript` to use the version that allows resolving promises before returning the result. Not sure why the previous version which does not support promises https://source.chromium.org/chromium/chromium/src/+/main:content/browser/renderer_host/render_frame_host_impl.cc;l=2667-2670 was adopted in https://github.com/electron/electron/commit/704d69a8f96d904afc725f121432d23b7f44bd33 but this aligns the behavior with `WebFrame::ExecuteJavaScript`.
Was identified when writing tests for https://github.com/electron/electron/pull/35281
Notes: fix enable promise support with webFrameMain.executeJavaScript
=> fix: promise support with webFrameMain.executeJavaScript

docs/development/build-instructions-gn.md, docs/development/build-instructions-macos.md
added some troubleshooting solutions to the section in `docs/development/build-instructions-gn.md`, and created the troubleshooting section for macOS. 
Also added a dependency specifically for M1 MacOS:
Not having Rosetta 2 installed on arm64-architecture MacOS laptops can cause vpython to fail during e sync.
This bug is documented [here](https://bugs.chromium.org/p/chromium/issues/detail?id=1103275). It was fixed earlier this year, but I ran into this problem regardless, so it may be worth it to add Rosetta 2 into dependencies to tick all the boxes.
Notes: none
=> docs: add dependencies and troubleshooting section to build-instructions

shell/browser/electron_browser_client.cc
Remove unneeded bypass of redirect checks when creating URL loader factories.
Notes: none
=> fix: don't bypass redirect checks

appveyor.yml
This PR splits up our Windows CI into two jobs: build and test.  This means that we can re-run just the tests if needed which is much quicker than re-running the whole build and test.
Notes: none
=> ci: use AppVeyor workflows

patches/chromium/feat_add_data_parameter_to_processsingleton.patch, patches/chromium/process_singleton.patch, shell/browser/api/electron_api_app.cc, shell/browser/api/electron_api_app.h
Refs https://github.com/electron/electron/pull/34993#discussion_r947188904
Reuse the change from https://chromium-review.googlesource.com/c/chromium/src/+/3781028 to delay socket watcher.
Notes: none
=> chore: update process singleton patch

shell/browser/electron_permission_manager.cc, spec/api-session-spec.ts
With https://github.com/electron/electron/commit/7e59d784a0b5c922564cbc8c55f95f0e7daf6997, https://chromium-review.googlesource.com/c/chromium/src/+/3495142 deprecates `GetPermissionStatusForFrame` in favor of `GetPermissionStatusForCurrentDocument` and the latter always called into `GetPermissionStatus` which does not have a frame context leading to empty `RenderFrameHost` causing the above issue. 
Depends on https://github.com/electron/electron/pull/35292
Notes: fix undefined details.requestingUrl from session.setPermissionCheckHandler
=> fix: undefined details.requestingUrl from session.setPermissionCheckHandler

shell/browser/ui/views/win_caption_button.cc, shell/browser/ui/views/win_icon_painter.cc
Applies [Chromium commit 30a32e6](https://source.chromium.org/chromium/chromium/src/+/30a32e6d6909e8e6e267b48bb7294e739b210c51) to align Electron's WCO a bit more with Chromium's.
Upstream Chromium bug (see comment 14): https://bugs.chromium.org/p/chromium/issues/detail?id=1316028.
This PR does not fix the WCO spacer colour issue.
Notes: Modified the WCO maximized button style to match Windows 11 more closely.
=> chore: apply chromium commit 30a32e6

shell/browser/native_window_views_win.cc
Closes #35223 #28570
Previously when a window was maximized, minimized, and then restored, the window is not sent a restore notification upon the restoration, only a maximize one. This fix adds in an additional restore notification as well.
Notes: None
=> fix: add restore event for minimized maximization

patches/chromium/.patches, patches/chromium/cherry-pick-96306321286a.patch
[M102-LTS] Don't re-lock DisplayLocks during forced unlock
When a DisplayLock is unlocked via ForceUnlockIfNeeded, subsequent
updates to the DisplayLock can cause it to become locked again which is
problematic.
This patch prevents the DisplayLock from being locked again until the
next frame.
(cherry picked from commit ab55fe05c2c37693afe5021aa637fb2d7491eb6d)
Fixed: 1338135
Change-Id: I07790658e25ea9fe2f4e8de154e3a58e7e08892b
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3751710
Commit-Queue: Joey Arhar <jarhar@chromium.org>
Cr-Original-Commit-Position: refs/heads/main@{#1028405}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3817524
Owners-Override: Michael Ershov …
=> chore: cherry-pick 96306321286a from chromium

script/lib/git.py
#34993 added a patch (f82c240acb13b0a4605306930f28ab2f5d41415a) that only applies to source code that only exists on Linux.  That broke exporting patches on OSes other than Linux.  This PR fixes that issue.
Notes: none
=> build: fix export patches to work when source directory does not exist

appveyor.yml
The docs only check on Windows was not working properly due to how we were reading the exit code from the check.  This change will allow that check to operate properly.
Notes: none
=> ci: fixup doc-only-change on Windows

appveyor.yml
Seeing several appveyor failures on PRs with unrelated changed (e.g. https://ci.appveyor.com/project/electron-bot/electron-x64-testing/builds/44541167/job/t510wg0a0mprn94c#L3197).
In the latest Chrome roll, we saw similar failures when the `v8\tools\builtins-pgo` folder wasn't persisted for tests. The recent split in "Build" and "Test" workflows resulted in this folder being empty during tests, which likely causes this failure. This PR zips `v8\tools\builtins-pgo` to upload, then re-download for use during the test workflow.
Notes: none
=> ci: fix appveyor x64 tests

patches/angle/.patches, patches/angle/m104_vulkan_fix_xfb_buffer_redefine_to_smaller_size.patch, patches/config.json
M104: Vulkan: Fix xfb buffer redefine to smaller size
In 89e11878b275b15735eaf273ababfa6fd43a2e3d, a use-after-free bug was
fixed where glBufferData redefined a buffer, leading to a change in
storage.  This was only tested for the case where the new buffer was
larger than the old buffer.
When the new buffer is smaller however, another issue remains where the
buffer size as cached by the transform feedback object used the old
object's size.  This is worked around in this change, with a fix for the
real issue (that the buffer state is updated after calling into the
backend instead of before) coming up.
Bug: chromium:1345042
Change-Id: I7bafd51b6203a419e5ef123da26b9e1eaf079bf1
Reviewed-on: https://chromium-review.googlesource.com/c/angle/angle/+/3812556
Reviewed-by: Ian Elliott …
=> chore: cherry-pick 1121a459f094 from angle

docs/api/browser-window.md, shell/browser/native_window_mac.mm, spec/api-browser-window-spec.ts
Closes https://github.com/electron/electron/issues/35403.
Refs CL:1125099.
Fixes an issue where frameless windows with `roundedCorners: false` cannot enter fullscreen without crashing. This is happening because Chromium uses a custom `NativeWidgetMacNSWindowBorderlessFrame` when the NSWindow has a `NSWindowStyleMaskBorderless` style mask, which is itself a subclass of `NSNextStepFrame`. `NSNextStepFrame` does not implement any of the public or private methods required for fullscreen, and so it would crash with errors like:
```
-[NativeWidgetMacNSWindowBorderlessFrame _surrenderToolbarViewForFullScreenWindow:]: unrecognized selector sent to instance
```
The cleanest solution for this would be to document this case in the `roundedCorners` option, and prevent the window from going …
=> fix: fullscreen crashing with `roundedCorners: false`

.circleci/config/base.yml, .gitignore
Missed these in the rename.
Notes: none
=> test: fix some broken globs for spec-main

script/export_all_patches.py
Fixes an error on macOS where editing an existing patch and re-exporting it would cause a Not Found error. This error was happening when editing and re-exporting patches only, as opposed to when applying patches, since `apply_all_patches.py` specifically [ensures the dir exists](https://github.com/electron/electron/blob/97b353a30a0e92a169fb0557ddff641fa0332d7c/script/apply_all_patches.py#L14). The same should be true in `export_all_patches.py` - this PR fixes that.
This came up as of https://github.com/electron/electron/pull/34993 since `third_party/lss`doesn't exist on macOS.
Notes: none
=> build: fix missing patch config dir error

patches/chromium/.patches, patches/chromium/cherry-pick-2f19801aeb77.patch
[M102-LTS] Don't allow cookies with hidden cookie prefixes
M102 merge issues:
Build failures in the unit tests because the interface of
CreateUnsafeCookieForTesting changed
Prevent the creation of any cookies that have an empty name field and
whose value impersonates a cookie name prefix.
This will also delete any previously stored cookies that meet the
conditions by causing them to fail their IsCanonical() check.
(cherry picked from commit f9580905b45edb8dfe7da6cd5f26421ab2b5c285)
(cherry picked from commit e118b7e282002908b0135a2107fec25cedc4436e)
Bug: 1345193
Change-Id: I7e1adef3391bb7caee183204bb609cd63bcdaea7
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3782906
Commit-Queue: Steven Bingler <bingler@chromium.org> …
=> chore: cherry-pick 2f19801aeb77 from chromium

docs/api/session.md, shell/browser/api/electron_api_web_contents.cc, shell/browser/electron_browser_client.cc, shell/browser/web_contents_permission_helper.cc, shell/browser/web_contents_permission_helper.h
Some permission helper methods weren't passing the render frame host through all the way, this fixes it so they do.
=> fix: pass rfh instances through to the permission helper

patches/node/build_add_gn_build_files.patch
Refs https://github.com/nodejs/node/pull/27283/files.
More closely aligns with nghttp2.gyp.
Notes: none.
=> chore: use nghttp2's config.h on all platforms

patches/node/feat_add_uv_loop_interrupt_on_io_change_option_to_uv_loop_configure.patch, shell/common/node_bindings.cc
Closes https://github.com/electron/electron/issues/35384.
Closes https://github.com/electron/electron/issues/35442.
Fixes a potential crash on WebWorker destruction. This was happening as a result of our custom `UV_LOOP_INTERRUPT_ON_IO_CHANGE` code added to libuv, as `uv_loop_close` results in a call to `uv__io_stop`, which then calls `uv__loop_interrupt`. `uv__loop_interrupt` didn't account for the case where the loop was no longer alive, and so would crash. This fixes that.
This PR also switches over from a direct call to `uv_loop_close` to Node's wrapper `CheckedUvLoopClose`, which calls `uv_loop_close` as expected but also aids in future debugging by logging all open handles should they exist. 
Notes: Fixed a potential crash on WebWorker destruction.
=> fix: crash on WebWorker destruction

shell/browser/native_browser_view_mac.mm, spec/api-browser-view-spec.ts
Closes https://github.com/electron/electron/issues/32880.
Fixes an issue where part of the BrowserView could be cut off when calling `setBounds` on some windows. This was happening because we were not taking the titlebar height into account when calling `setBounds` on a framed window, which meant that the y-value for the bounds would end up negative. For example, the following snippet:
<details><summary>main.js</summary>
```js
const {app, BrowserView, BrowserWindow} = require('electron')
const path = require('path')
function createWindow () {
const mainWindow = new BrowserWindow({
width: 1200,
height: 900,
webPreferences: {
preload: path.join(__dirname, 'preload.js')
}
})
mainWindow.removeMenu();
const view = new BrowserView()
mainWindow.setBrowserView(view) …
```
=> fix: compensate for title bar height when setting bounds on `BrowserView`

shell/browser/api/electron_api_web_contents.cc
No need for the extra check, base::Bind already does the weakptr check.
Notes: none
=> refactor: simplify WebContents::Destroy

shell/browser/api/electron_api_menu_mac.mm, shell/browser/api/electron_api_menu_views.cc
This no longer seems to be necessary since #20114 moved the menu popup loop off
the UI thread.
Notes: none
=> chore: drop unresponsive suppressor for menus

shell/browser/api/electron_api_base_window.cc, shell/browser/api/electron_api_base_window.h, shell/browser/api/electron_api_browser_view.cc, shell/browser/api/electron_api_browser_view.h, shell/browser/api/electron_api_browser_window.cc, shell/browser/api/electron_api_browser_window.h, spec/api-browser-view-spec.ts
This changes the owner\_window of a BrowserView from NativeWindow to
BaseWindow, and makes `getBrowserViews()` always in sync with the browser views
in a window, even if they are reparented.
Notes: Fixed `win.getBrowserViews()` not being updated when a BrowserView was moved to a different window.
=> refactor: BrowserView is owned by a BaseWindow

docs/api/web-frame-main.md, shell/browser/api/electron_api_web_frame_main.cc, shell/browser/api/electron_api_web_frame_main.h, spec/api-web-frame-main-spec.ts
This adds `webFrameMain.origin`, which is useful for verifying the provenance
of `about:blank` child windows.
Notes: Added `webFrameMain.origin`.
=> feat: webFrameMain.origin

patches/config.json, patches/sqlite/.patches, patches/sqlite/utf-8_q_simplify_20the_20logic_20that_20converts_20the_20_1_20.patch
commit fd34e75b0a8994b2b96900c3237bc536127447d4
Author: drh <>
Date: Wed Jul 20 17:01:18 2022 +0000
Simplify the logic that converts the "1" expression in "ORDER BY 1" into a
copy of the expression that defines the first output column.
FossilOrigin-Name: 449935914c3f64e37bbfb9842e868927222fa3d5315c123a32818e67fcfbbf60
Notes: Security: backported fix for CVE-2022-3041.
=> chore: cherry-pick fd34e75b0a from sqlite

shell/browser/api/electron_api_screen.cc, shell/browser/api/electron_api_screen.h
Closes https://github.com/electron/electron/issues/35471.
Fixes an issue where `screen.getCursorScreenPoint()` crashed on Wayland when it was called before a `BrowserWindow` had been created. This happened becuase the Wayland implementation [requires it](https://source.chromium.org/chromium/chromium/src/+/main:ui/ozone/platform/wayland/host/wayland_screen.cc;l=325-327;drc=7267e612666ee78e5809dcc48253af2857989a47;bpv=1;bpt=1?q=wayland_scr&ss=chromium%2Fchromium%2Fsrc). To fix this, we throw an error if a user attempts to call it before creating a `BrowserWindow`.
Notes: Fixed an issue where `screen.getCursorScreenPoint()` crashed on Wayland when it was called before a `BrowserWindow` had been created.
=> fix: `screen.getCursorScreenPoint()` crash on Wayland

patches/chromium/.patches, patches/chromium/cherry-pick-9b5207569882.patch
Mojo: Validate response message type
Ensures that a response message is actually the type expected by the
original request.
Fixed: 1358134
Change-Id: I8f8f58168764477fbf7a6d2e8aeb040f07793d45
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3864274
Cr-Commit-Position: refs/heads/main@{#1041553}
Notes: Security: backported fix for CVE-2022-3075.
=> chore: cherry-pick 9b5207569882 from chromium

patches/chromium/.patches, patches/chromium/cherry-pick-079105b7ebba.patch
bindings: Add argument type checks to ObservableArray<T>
Performs type checks for arguments of trap functions and throws
a TypeError if a type is wrong.
(cherry picked from commit 4d67bb1dbf55e2eddf513f29ac33e38e8e1d2fab)
Bug: 1352549
Change-Id: I66df3a9eeae5e4f44bdf714666a2c6304ebec0f5
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3835494
Auto-Submit: Yuki Shiino <yukishiino@chromium.org>
Reviewed-by: Kentaro Hara <haraken@chromium.org>
Commit-Queue: Kentaro Hara <haraken@chromium.org>
Cr-Original-Commit-Position: refs/heads/main@{#1036005}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3849901
Cr-Commit-Position: refs/branch-heads/5112@{#1514}
Cr-Branched-From: b13d3fe7b3c47a56354ef54b221008afa754412e-refs/heads/main@{#1012729}
Notes: …
=> chore: cherry-pick 079105b7ebba from chromium

patches/chromium/.patches, patches/chromium/cherry-pick-2083e894852c.patch
Fix heap-overflow in blink::TableLayoutAlgorithmAuto::InsertSpanCell
The CL fixes size confusion between Member<> and raw pointers.
The bug was found (and the fix was proposed) by m.cooolie@gmail.com.
Bug: 1341539
Change-Id: I99d524fd65c2d6305693d09ad274c23178271269
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3751138
Reviewed-by: Kentaro Hara <haraken@chromium.org>
Commit-Queue: Anton Bikineev <bikineev@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1022529}
Ref electron/security#208
Notes: Security: backported fix for CVE-2022-3040.
=> chore: cherry-pick 2083e894852c from chromium

patches/chromium/.patches, patches/chromium/cherry-pick-51daffbf5cd8.patch
Fix UAF on network::URLLoader
network::URLLoader::SetUpUpload calls NotifyCompleted asynchronously,
as it can be called in the constructor and we don't want to run
NotifyCompleted in the constructor.
The problem is that it attaches a raw pointer to the method, which leads to a use-after-free problem if the URLLoader is destructed before
NotifyCompleted is called.
Use weak pointers instead of raw pointers to avoid the problem.
Bug: 1340253
Change-Id: Iacb1e772bf7a8e3de4a7bb9de342fea9ba0f3f3c
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3740150
Reviewed-by: Kenichi Ishibashi <bashi@chromium.org>
Commit-Queue: Yutaka Hirano <yhirano@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1020539}
Ref electron/security#203
Notes: Security: backported fix for …
=> chore: cherry-pick 51daffbf5cd8 from chromium

shell/app/electron_main_win.cc, shell/browser/electron_browser_main_parts.cc
Follow up to a recent Chrome roll (#34993), this PR moves Windows dark mode activation from electron_browser_main_parts.cc to electron_main_win.cc, to more closely match Chromium.
Notes: none
=> chore: move dark mode activation to main_win.cc

appveyor.yml
- #35377 inadvertently broke fork PR CI testing on Windows because it no longer was saving artifacts for fork PRs. This PR fixes the saving of artifacts so that fork PRs can properly run tests.
Notes: none
=> ci: make sure artifacts are saved for fork PRs

docs/api/protocol.md
Using `url.fileURLToPath` will handle correctly handle cases where the custom URI includes `%20` unlike `path.normalize`
Notes: none
=> docs: improve registerFileProtocol example

shell/browser/ui/views/win_caption_button_container.cc, shell/browser/ui/views/win_frame_view.cc
Fixes https://github.com/electron/electron/issues/35312
Ref https://github.com/electron/electron/issues/35312#issuecomment-1235944004
Chromium was setting a background colour for the windows control overlay container, whereas we weren't. This PR copies the line so that we are also setting a background colour for the WCO container, which should avoid rendering glitches.
I'm currently on an RTL system language to work on another issue, so the WCO in the demo below is mirrored, but it shows that the gaps have been filled in with the overlay button colour.
Notes: Added a background to the WCO container to avoid rendering glitches.
=> fix: Set background for WCO container

docs/tutorial/fuses.md
Fixes misspelling in new Fuses docs (`.asasr` -> `.asar`).
Notes: none
=> docs: fix misspelling in fuses

shell/browser/api/electron_api_web_contents.cc, shell/browser/api/electron_api_web_contents.h, spec/chromium-spec.ts
This fixes https://github.com/electron/electron/issues/35391
When a sandboxed iframe calls `history.go()`, the renderer calls into the browser at [RenderFrameHostImpl::GoToEntryAtOffset](https://chromium.googlesource.com/chromium/src.git/+/refs/tags/106.0.5216.0/content/browser/renderer_host/render_frame_host_impl.cc#6153):
```c++
if (delegate_->IsAllowedToGoToEntryAtOffset(offset)) {
if (IsSandboxed(network::mojom::WebSandboxFlags::kTopNavigation)) {
// Keep track of whether this is a session history from a sandboxed iframe
// with top level navigation disallowed.
frame_tree_->controller().GoToOffsetInSandboxedFrame(
offset, GetFrameTreeNodeId());
} else {
frame_tree_->controller().GoToOffsetFromRenderer(offset);
}
}
```
The call to `delegate_->IsAllowedToGoToEntryAtOffset(offset)` goes …
=> fix: ensure history navigations are sandboxed-iframe-aware

lib/browser/api/browser-window.ts
We cannot access the `webContents` property before checking for `!isDestroyed()`
Notes: none
=> fix: potential "Object has been destroyed" error in BrowserWindow.getFocusedWindow

docs/tutorial/performance.md
Fixes https://github.com/electron/electron/issues/35512
Notes: docs: add performance advice to disable default menu creation
=> docs: add performance advice to disable default menu creation

docs/faq.md
Relative Markdown links are rendered relative to the host domain, which works fine when viewing it on Github, but since you also use the same generated HTML in your doc site, the link is broken. See here: https://www.electronjs.org/docs/latest/faq#the-font-looks-blurry-what-is-this-and-what-can-i-do
Using an absolute URL here should fix the issue on the main site.
Notes: Fixed broken image link in `docs/latest/faq`.
=> docs: Use inline image link in faq.md

docs/fiddles/features/web-serial/main.js
Fixed a typescript warning / error in the example code
- [ x ] relevant documentation is changed or added
Notes: None
=> docs: fix typescript error in code samples

shell/browser/electron_download_manager_delegate.cc
Closes https://github.com/electron/electron/issues/35594 https://github.com/electron/electron/issues/35429
Removes an extra period from the extension portion of the dialog filter on Windows. This is not expected in Electron's implementation of filters, but was in place for Chromium's. Updates https://github.com/electron/electron/pull/34723
Notes:  Added support for Windows drop-down dialog extensions
=> fix: remove extra dot in extension

shell/browser/ui/views/win_caption_button_container.cc
This change backports [CL 3753528](https://chromium-review.googlesource.com/c/chromium/src/+/3753528) to keep Electron's WCO behaviour for `WinCaptionButtonContainer::UpdateButtons` in sync with Chromium.
Downstream issue: https://github.com/microsoft/vscode/issues/159851
Notes: Enable WCO maximize button when window enters tablet mode and is not already maximized.
=> fix: allow maximizing when window enters tablet mode with WCO

script/check-symlinks.js
Right now the `check-symlinks.js` assumes that the branding product name
is "Electron". If users change `BRANDING.json` on custom builds, the
script will fail.
Notes: none
=> build: make check-symlinks.js aware of BRANDING.json changes

patches/sqlite/.patches, patches/sqlite/utf-8_q_when_20applying_20the_20omit-order-by_20optimization.patch
Author: Ayu Ishii <ayui@chromium.org>
Date:   Fri Jul 15 13:20:47 2022 +0000
When applying the omit-ORDER-BY optimization, defer deleting the AST of
the deleted ORDER BY clause until after code generation ends.
FossilOrigin-Name: b88d6c4b814ec4166ec50f32a2f10d7857df05414c0048c1234ab290a273e50c
(cherry picked from commit 9dde91f61386e4fc53eb95b6cbd26bf30521225f)
Bug: 1343348
Change-Id: Id677f72166c00a05f95c25438230f4b1d40f4d4d
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/deps/sqlite/+/3764026
Commit-Queue: Ayu Ishii <ayui@chromium.org>
Reviewed-by: Joshua Bell <jsbell@chromium.org>
Notes: Security: backported fix for CVE-2022-3039.
=> chore: cherry-pick 88f6139ead from sqlite

docs/api/session.md, shell/browser/api/electron_api_session.cc, spec/spellchecker-spec.ts
Closes https://github.com/electron/electron/issues/35508.
Formally make `session.setSpellCheckerLanguages()` and `session.setSpellCheckerDictionaryDownloadURL()` no-ops on macOS. macOS uses system spellchecking functionality so those functions would not have their intended effect, but could still throw errors if called with an unsupported language.
Notes: Fixed an issue where some spellcheck functionality would incorrectly throw errors on macOS.
=> chore: make macOS spellchecker fns formal no-ops

patches/v8/.patches, patches/v8/cherry-pick-c0a5a7d5006d.patch
[M102-LTS][rab/gsab] Fix flag mismatch in serialized data
(cherry picked from commit 3483b970eb1c35f96b2b605cfaf6ca25dc9b6ab9)
Bug: v8:11111,chromium:1339648
No-Try: true
Change-Id: I3b472f74f37a4e1514ce20635b16970e95a36e15
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/3735162
Reviewed-by: Shu-yu Guo <syg@chromium.org>
Commit-Queue: Marja Hölttä <marja@chromium.org>
Cr-Original-Commit-Position: refs/heads/main@{#81598}
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/3859324
Reviewed-by: Simon Zünd <szuend@chromium.org>
Cr-Commit-Position: refs/branch-heads/10.2@{#29} …
=> chore: cherry-pick c0a5a7d5006d from v8

shell/browser/api/electron_api_web_contents.cc
Regressed in #35209, cc @codebytere
```
../../electron/shell/browser/api/electron_api_web_contents.cc(2484,27): error: unknown type name 'NativeWindowViews'
auto* win = static_cast<NativeWindowViews*>(owner_window());
^
../../electron/shell/browser/api/electron_api_web_contents.cc(2487,19): error: no member named 'IsWindowControlsOverlayEnabled' in 'electron::NativeWindow'
if (win && win->IsWindowControlsOverlayEnabled())
~~~  ^
```
Notes: none
=> build: fix building with enable_basic_printing false

.github/stale.yml
=> build: add stale configuration

patches/node/fix_crash_caused_by_gethostnamew_on_windows_7.patch, patches/node/fix_suppress_clang_-wdeprecated-declarations_in_libuv.patch
Fixes #35219. Regressed in https://github.com/electron/electron/pull/32833/commits/a2e5d1946711299d69d275e4a69f5f75a18304de
Notes: Fixed `uv_os_gethostname` failing on Windows 7
=> fix: uv_os_gethostname failing on Windows 7 (libuv patch regression)

shell/browser/serial/electron_serial_delegate.cc, shell/browser/serial/electron_serial_delegate.h
When compiling electron 20.1.4 on linux with gcc, the compiler cannot determine what `Observer` refers to. I needed to apply this patch to get it to compile.
Notes: none
=> chore: fix ambiguous reference gcc compile error

lib/common/.eslintrc.json, lib/common/api/clipboard.ts, lib/isolated_renderer/.eslintrc.json, lib/renderer/.eslintrc.json, lib/renderer/common-init.ts, lib/renderer/inspector.ts, lib/renderer/web-frame-init.ts, lib/sandboxed_renderer/.eslintrc.json, lib/worker/.eslintrc.json
We only had this `.eslintrc.json` in `lib/browser` limiting the imports to `electron/main`.
Do the same for the renderers and common.
Follow-up to #24512
Notes: none
=> chore: add missing .eslintrc.json files to limit imports properly

patches/chromium/.patches, patches/chromium/cherry-pick-eb4d31309df7.patch
Fix for reference to invalid iterator
Evidently, LocalFrameView::layout_subtree_root_list_ can be modified
during LayoutFromRootObject, leaving the loop variable in an invalid
state. I don't know the exact sequence, but the test case crashes for
me without this patch, and doesn't crash with the patch.
(cherry picked from commit 815aa5ca03ab4ecc619b2d2ad7650531bd3892a8)
Bug: 1355237
Change-Id: Ib17b1fac5b2ec060eda39be76305db18075802fa
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3864877
Reviewed-by: Ian Kilpatrick <ikilpatrick@chromium.org>
Commit-Queue: Stefan Zager <szager@chromium.org>
Cr-Original-Commit-Position: refs/heads/main@{#1041903}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3884238
Owners-Override: Srinivas Sista …
=> chore: cherry-pick eb4d31309df7 from chromium

docs/tutorial/security.md
Removed the claim that HTTPS authenticates the remote server. This is not a feature of HTTPS. This would require certificate pinning. It has been in the security docs since https://github.com/electron/electron/commit/2db125890cf901f939ab60b550dee54a091d57a4
Related
https://github.com/electron/electron/issues/3330
https://www.npmjs.com/package/electron-ssl-pinning
https://cheatsheetseries.owasp.org/cheatsheets/Pinning_Cheat_Sheet.html
Notes: none
=> docs: remove claim that HTTPS authenticates the remote server

shell/browser/api/electron_api_web_contents.cc
Close https://github.com/electron/electron/issues/35715.
Refactor https://github.com/electron/electron/pull/35209 to _default_ the devtools position to `detach` rather than forcing it unilaterally.
Notes: Fixed an issue where DevTools could not be docked with Windows Control Overlay enabled.
=> fix: allow docking DevTools with WCO

docs/tutorial/tutorial-1-prerequisites.md
Updated the link for `Introduction to NodeJs`  that was https://nodejs.dev/learn but the new one is https://nodejs.dev/en/learn/ . 
This change was needed because the NodeJs organisation has updated their routes and if you go to that old link then you will get 404 " PAGE NOT FOUND" error.
I changed the file `electron/docs/tutorial/tutorial-prerequisites.md`. Only one link was found and was changed.
Notes: none
=> docs: update the link for Introduction to Node.js

.github/CODEOWNERS
This ensures that we don't need **both** security and upgrades to sign off on a patch PR, instead a single rep from either team can approve
=> build: make patches owned by patch-owners (formed by upgrades + security)

docs/tutorial/message-ports.md
changed event.data to data under the message.port in docs.
Notes:  none
=> docs: changed event.data to data under the message.port in docs

patches/pdfium/.patches, patches/pdfium/cherry-pick-497f077a1d46.patch
[M104] Return retained const objects from SearchNameNodeByNameInternal()
Cherry-pick of d51720c9bb55d1163ab4fdcdc6981e753aa2354d + manual
conflict resolution.
Bug: chromium:1358075
Change-Id: Ibb20a6feaf79f7b351f22c607c306da40026d53e
Reviewed-on: https://pdfium-review.googlesource.com/c/pdfium/+/97739
Auto-Submit: Tom Sepez <tsepez@chromium.org>
Commit-Queue: Lei Zhang <thestig@chromium.org>
Notes: Security: backported fix for CVE-2022-3197.
=> chore: cherry-pick 497f077a1d46 from pdfium

build/args/all.gn
This PR adds a new node module version number for Electron 22.
Node PR here: https://github.com/nodejs/node/pull/44748
NOTE: Please hold until the node PR has been merged
Notes: none
=> chore: update NMV for Electron 22

docs/api/app.md, filenames.auto.gni, shell/browser/api/electron_api_app.cc, shell/browser/api/electron_api_app.h, shell/browser/browser_process_impl.cc, shell/browser/browser_process_impl.h, shell/browser/electron_browser_main_parts.cc, shell/browser/electron_browser_main_parts.h, shell/browser/electron_browser_main_parts_mac.mm, spec/api-app-spec.ts, spec/chromium-spec.ts, spec/fixtures/api/locale-check/main.js
This PR adds a method to fetch the OS locale from Chromium. That way, even when the application is in a certain locale, the program can still know the system locale and make recommendations based off of that.
Downstream: https://github.com/microsoft/vscode/issues/159813 and PR https://github.com/microsoft/vscode/pull/159958.
Notes: Added `app.getSystemLocale()` method.
=> feat: add app.getSystemLocale() method

.circleci/config/base.yml, shell/browser/electron_browser_main_parts.cc, shell/browser/net/system_network_context_manager.cc, spec/api-safe-storage-spec.ts
Fixes #34614
Notes: Usage of `safeStorage` now consistently uses the correct service name on macOS regardless of timing with browser window construction
=> fix: set macOS crypto keychain name earlier

patches/config.json, patches/ffmpeg/.patches, patches/ffmpeg/cherry-pick-c2c8cac2131b.patch
[M102-LTS] avformat/mov: Check count sums in build_open_gop_key_points()
Fixes: ffmpeg.md
Fixes: Out of array access
Fixes: CVE-2022-2566
Bug: 1348283
Found-by: Andy Nguyen <theflow@google.com>
Found-by: 3pvd <3pvd@google.com>
Change-Id: I6821c87acce5a62cd9a5b829c17f56ae6418116a
Signed-off-by: Michael Niedermayer <michael@niedermayer.cc>
(cherry picked from commit 64d7d8d0e5035087ebe24a65845b36f78e7fad92)
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/third_party/ffmpeg/+/3890391
Reviewed-by: Matthew Wolenetz <wolenetz@chromium.org>
Notes: Security: backported fix for 1348283.
=> chore: cherry-pick c2c8cac2131b from ffmpeg

patches/v8/.patches, patches/v8/cherry-pick-3704cf78f471.patch
Merged: [heap] Fix aborting compaction with map space compaction
Revision: 3ec02e314cfca04e7457a60363af98b9c9957b16
BUG=chromium:1359294,v8:12578
NOTRY=true
R=mlippautz@chromium.org
Change-Id: I04093833a1bfef4269eb578fa5a002872015199e
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/3882977
Reviewed-by: Michael Lippautz <mlippautz@chromium.org>
Cr-Commit-Position: refs/branch-heads/10.4@{#43}
Cr-Branched-From: b1413ed7c71ababe05d590de4b5c4ed97b68693e-refs/heads/10.4.132@{#1}
Cr-Branched-From: 9d0a09368569234a1d1094975e2e92591922cd08-refs/heads/main@{#80972}
Notes: Security: backported fix for chromium:1359294,v8:12578.
=> chore: cherry-pick 3704cf78f471 from v8

patches/pdfium/.patches, patches/pdfium/cherry-pick-7f0bb5197ed1.patch
[M104] Avoid de-referencing end() in GetNextAvailContentHeight().
Add the same HasCurrentViewRecord() check as in other methods.
Bug: chromium:1355682
Change-Id: I466f386f037801daa82ead30239f34e025748748
Reviewed-on: https://pdfium-review.googlesource.com/c/pdfium/+/96910
Auto-Submit: Tom Sepez <tsepez@chromium.org>
Commit-Queue: Lei Zhang <thestig@chromium.org>
(cherry picked from commit 0d76a139d7ffbbdfb0ef5f5e714597a25f9767c4)
Reviewed-on: https://pdfium-review.googlesource.com/c/pdfium/+/97738
Notes: Security: backported fix for CVE-2022-3198.
=> chore: cherry-pick 7f0bb5197ed1 from pdfium

lib/browser/api/web-contents.ts, typings/internal-ambient.d.ts
> TypeError: Error processing argument at index 1, conversion failure from undefined
happens here in the generated `out/release/gen/electron/js2c/browser_init.js`
```ts
this.on("-ipc-message",(function(e,r,n,s){if(addSenderFrameToEvent(e),r)c.ipcMainInternal.emit(n,e,...s);else{addReplyToEvent(e),this.emit("ipc-message",e,n,...s);const r=p.fromIdOrNull(e.processId,e.frameId);r&&r.ipc.emit(n,e,...s),t.emit(n,e,...s),o.ipcMain.emit(n,e,...s)}}))
```
which maps to https://github.com/electron/electron/blob/ad33a5f364c5a630c148fe4866d38c735f905bfe/lib/browser/api/web-contents.ts#L577
Related to #35231
Notes: none
=> fix: potential exception when calling webFrameMainBinding.fromIdOrNull()

docs/api/session.md, docs/fiddles/features/web-bluetooth/main.js, docs/fiddles/features/web-bluetooth/preload.js, docs/fiddles/features/web-bluetooth/renderer.js, docs/tutorial/devices.md, filenames.auto.gni, shell/browser/api/electron_api_session.cc, shell/browser/api/electron_api_session.h, shell/browser/bluetooth/electron_bluetooth_delegate.cc, shell/browser/bluetooth/electron_bluetooth_delegate.h, shell/browser/electron_permission_manager.cc, shell/browser/electron_permission_manager.h
https://chromium-review.googlesource.com/c/chromium/src/+/2841104 added support for providing a pin for bluetooth devices on Windows and Linux when required but we simply stubbed out this functionality on the chromium roll (#31317).  This PR adds a new event `bluetooth-pair-prompt` to Session to allow developers to handle the request for a pin when pairing a bluetooth device.
Resolves #33111
Notes: Added support for Web Bluetooth pin pairing on Linux and Windows
=> feat: add support for Web Bluetooth pin pairing

patches/config.json, patches/libaom/.patches, patches/libaom/use_non_normative_scaler_for_non_optimized_ratio.patch
Use non normative scaler for non optimized ratio
There are only optimized scalers for 1/4, 1/2 and 3/4 scaling ratio.
SSSE3 also has 2x upscaling optimization.
Use non normative scalers for all other scaling ratios.
Bug: chromium:1346938
Bug: chromium:1338114
Change-Id: [I2a01717b56c53c42906440d5a3f95ca2c00dc571](https://aomedia-review.googlesource.com/#/q/I2a01717b56c53c42906440d5a3f95ca2c00dc571)
(cherry picked from commit ff7b753a63a536423a91b64a066bd385c52ceacc)
Notes: Security: backported fix chromium:1346938.
=> chore: cherry-pick 3eca8ad6b0b5 from libaom

.github/workflows/release_dependency_versions.yml
Previous error:
```
Run if [[  =~ ^refs/tags/v[0-9]+\.0\.0$ ]]; then
if [[  =~ ^refs/tags/v[0-9]+\.0\.0$ ]]; then
echo ::set-output name=should_release::true
fi
shell: /usr/bin/bash -e {0}
env:
GITHUB_TOKEN: ***
/home/runner/work/_temp/e[1](https://github.com/electron/electron/actions/runs/3131226499/jobs/5082347062#step:3:1)9d80f[2](https://github.com/electron/electron/actions/runs/3131226499/jobs/5082347062#step:3:2)-96d2-479[3](https://github.com/electron/electron/actions/runs/3131226499/jobs/5082347062#step:3:3)-8029-207b2b7[5](https://github.com/electron/electron/actions/runs/3131226499/jobs/5082347062#step:3:5)b8[6](https://github.com/electron/electron/actions/runs/3131226499/jobs/5082347062#step:3:6)d.sh: line 1: conditional binary operator expected
Error: Process completed with …
```
=> build: fix deps workflow tag comparison

shell/common/node_bindings.cc
Fixes a scoping issue with `TryCatch` in node_bindings which may have obscured errors farther below where we intended.
Notes: none
=> fix: `TryCatch` scope in node_bindings

patches/v8/.patches, patches/v8/cherry-pick-2f6a2939514f.patch
Merged: [compiler] fix typing of [[DateValue]]
Bug: chromium:1356308
(cherry picked from commit ae329407989f1e4689baba7a7827863057d688a9)
Change-Id: I1e132e96325296d180488774ef183daa36dc22c7
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/3915224
Reviewed-by: Darius Mercadier <dmercadier@chromium.org>
Cr-Commit-Position: refs/branch-heads/10.6@{#25}
Ref electron/security#227
Notes: Security: backported fix for 1356308.
=> chore: cherry-pick 2f6a2939514f from v8

patches/chromium/.patches, patches/chromium/cherry-pick-9bebe8549a36.patch
[M106] Ensure iterator validity in CustomElementRegistry::DefineInternal()
Currently, this function first resolves a promise, and then erases an
iterator from a hash map, but the promise resolving may run synchronous
JavaScript that invalidates the iterator.
This patch switches the ordering so that we always use the iterator when
it's valid.
(cherry picked from commit ed87ab54b29898a96a87e8fd497425db32539350)
(cherry picked from commit b0bfc4334369bd1d44bc6507dfefc012afb7e12d)
Fixed: 1366813
Change-Id: Iaa6631db5f3ad47049f46ddf909f18a49e5880c0
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3915346
Commit-Queue: Xiaocheng Hu <xiaochengh@chromium.org>
Reviewed-by: Joey Arhar <jarhar@chromium.org>
Cr-Original-Original-Commit-Position: refs/heads/main@{#1050816} …
=> chore: cherry-pick 9bebe8549a36 from chromium

patches/chromium/.patches, patches/chromium/cherry-pick-1eb1e18ad41d.patch
Add CSSTokenizer-created strings to CSSVariableData's backing strings
When computing the value of a registered custom property, we create
a CSSVariableData object equivalent to the computed CSSValue by
serializing that CSSValue to a String, then tokenizing that value.
The problem is that CSSTokenizer can create *new* string objects
during the tokenization process (see calls to CSSTokenizer::
RegisterString), without communicating that fact to the call-site.
Therefore, this CL adds a way to access those strings so they can
be added to the backing strings of the CSSVariableData.
Also added a DCHECK to verify that we don't have any tokens with
non-backed string pointers.
Fixed: 1358907
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3892782
Reviewed-by: Steinar H …
=> chore: cherry-pick 1eb1e18ad41d from chromium

patches/v8/.patches, patches/v8/cherry-pick-8b040cb69e96.patch
[wasm][liftoff] Fix a register reuse corner case
Fixed: chromium:1366399
(cherry picked from commit 6c214db445827707d65be08d177c9a4257a03a7b)
Change-Id: I72cf30cbd31a21acb44b524a194acfb89d8fecbc
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/3925795
Reviewed-by: Matthias Liedtke <mliedtke@chromium.org>
Cr-Commit-Position: refs/branch-heads/10.6@{#29}
Ref electron/security#225
Notes: Security: backported fix for CVE-2022-3373.
=> chore: cherry-pick 8b040cb69e96 from v8

docs/fiddles/features/web-bluetooth/preload.js
Fix the spelling of the event name in the bluetooth example fiddle `preload.js` file so that the correct event get triggered. 
(https://github.com/electron/clerk/blob/master/README.md#examples).
Notes: Fixed spelling in bluetooth example documentation
=> docs: update bluetooth fiddle example event name to trigger correct event

README.md
Bumps the latest support Mac version to 10.13, in accordance with the[ updated Chromium min system version](https://source.chromium.org/chromium/chromium/src/+/main:build/config/mac/mac_sdk.gni;l=23-28;drc=73a09d1a67a9bab66eba08b51372f431ab709b2d).
Notes: none
=> docs: update supported Mac versions

docs/api/browser-window.md, docs/api/web-contents.md, docs/breaking-changes.md, shell/browser/api/electron_api_web_contents.cc, spec/api-browser-window-spec.ts
Refactors `webContents.{increment|decrement}CapturerCount` to remove usage of private `WebContents::DecrementCapturerCount` exposed via patch. We now store the handle received from calls to `IncrementCapturerCount` and `api::WebContents::DecrementCaptureCount` now calls `RunAndReset` on the stored capture handle. 
Functionality previously exposed through `webContents.{increment|decrement}CapturerCount` has now been folded into `webContents.capturePage`.
Notes: none.
=> refactor: eliminate `DecrementCapturerCount` patch

patches/chromium/.patches, patches/chromium/cherry-pick-c83640db21b5.patch
build: set DTSDKBuild correctly when generating plist files
Currently we set DTSDKBuild to the version of the SDK used to build
Chromium.  This value is supposed to be the build version (this is
what xcode sets it to for instance).  We read this value out of the
SDK directly and use it instead.
Change-Id: Ieb7990f13095683ad8c026f027b2605ae39523a4
Notes: none
=> chore: cherry-pick c83640db21b5 from chromium

docs/development/build-instructions-windows.md
`pywin32` was removed from the build instructions in #33402 but this reference in the troubleshooting section was missed.
Notes: none
=> docs: remove pywin32 mention in Windows build instructions

patches/node/.patches, patches/node/fix_expose_the_built-in_electron_module_via_the_esm_loader.patch, spec/modules-spec.ts
This specifically enables the following two patterns:
```js
// foo.mjs
import { app } from 'electron';
```
```js
// foo.js or foo.mjs
async function main() {
const { app } = await import('electron');
}
```
This is not "ESM support for Electron".  I classify that as supporting an ESM entrypoint for an Electron app. Currently for reasons well outlined in the requisite issue #21457 an Electron app **must** have a CJS entrypoint.  It can then immediately farm out to an ESModule but it's important apps understand the limitations / issues with that approach, hence we do not allow an `mjs` file to be directly used as an entrypoint.
Weirdly, this is like the 4th time I've tried this.  And this time I found a relatively lightweight patch to make it work, basically we trick the ESM module resolver …
=> fix: expose the built-in electron module via the ESM loader

shell/app/electron_main_delegate.cc, shell/app/electron_main_delegate.h
Closes https://github.com/electron/electron/issues/35916.
Overrides `content::ContentMainDelegate::CreateContentClient()` to prevent duplicate creation. The previous code was added in Electron's infancy, and the override did not become available until 2019, which is why this hasn't yet been changed.
Notes: Fixed a potential memory leak.
=> fix: override `content::ContentMainDelegate::CreateContentClient()`

shell/browser/ui/views/win_caption_button.cc, shell/browser/ui/views/win_icon_painter.cc
Fixes #35938
Backport of #35370.
CC @deepak1556
Notes: Modified the Windows 11 WCO to match the native look more closely.
=> chore: cherry-pick 30a32e6 from chromium (#35370)

lib/browser/api/web-contents.ts, shell/browser/api/electron_api_web_contents.cc
Closes https://github.com/electron/electron/issues/35971.
Fixes some incorrect options plumbing in `webContents.printToPDF()`
Tested with https://gist.github.com/lesleyandreza/7699603b20f2459d1fcf3b9480fb22e1
Notes: Fixed an issue where some options were incorrectly ignored when using `webContents.printToPDF()`.
=> fix: `webContents.printToPDF` option plumbing

.circleci/config/base.yml, appveyor.yml, docs/development/build-instructions-gn.md, shell/renderer/api/electron_api_spell_check_client.cc, shell/renderer/api/electron_api_spell_check_client.h, spec/node-spec.ts
Also `third_party/WebKit/LayoutTests` no longer exists
Notes: none
=> chore: remove WebKit leftovers after it was renamed to Blink

BUILD.gn, chromium_src/BUILD.gn
Related to https://chromium-review.googlesource.com/c/chromium/src/+/3750107
Without this change we are getting
```
ERROR at //ppapi/proxy/BUILD.gn:9:1: Assertion failed.
assert(enable_ppapi)
^-----
See //electron/chromium_src/BUILD.gn:377:5: which caused the file to be included.
"//ppapi/proxy",
^--------------
```
Notes: none
=> build: fix building with enable_ppapi = false

docs/tutorial/message-ports.md
Follow-up to #34959
Notes: none
=> docs: use webContents.mainFrame.on() in MessagePort tutorial

spec/api-power-monitor-spec.ts
This PR re-enables the power monitor tests on Linux arm64.
- Resolves #20781 
Notes: none
=> test: re-enable power monitor tests on arm64

spec/webview-spec.ts
This PR re-enables the <webview> tag DOM events emits resize event test.
- Resolves #19086
Notes: none
=> test: re-enable <webview> tag DOM events emits resize event

default_app/main.ts
Fixes #35967 (and maybe #34801).
Override app's desktop name and v8 flags when launching local app from default-app.
Notes: Fixed v8 flags and desktop name in package.json does not hornored when running local app using electron cli.
=> fix: override app's desktop name and v8 flags in default-app

docs/tutorial/tutorial-2-first-app.md
Usage of `pwa-` prefixes on the debugger types are deprecated, VS Code now tells you to drop the prefix.
Notes: none
=> docs: update VS Code debugger types to remove "pwa-" prefix

shell/browser/printing/print_view_manager_electron.cc
Fixes headless job tracking for `contents.printToPDF()`, which was incorrectly/unintentionally removed in [a recent Chromium roll](https://github.com/electron/electron/pull/34993/files#diff-2b43b0cabaeb72a224a224d5e7611592bf1c5e02d890c7fe8d132e41bd39d6e5L132-L134).
Notes: Fixed a potential issue when calling `webContents.printToPDF()`.
=> fix: headless job tracking in printToPDF

package.json, script/gn-asar-hash.js, script/gn-asar.js, spec/fixtures/test.asar/repack.js, yarn.lock
This is a cosmetic change, and future updates to the `asar` package will only be published to `@electron/asar`.
=> refactor: migrate from asar to @electron/asar

patches/chromium/.patches, patches/chromium/cherry-pick-cb9dff93f3d4.patch
[Merge to M106] Use HeapMojoReceiver rather than mojo::Receiver for PeerConnectionTracker
HeapMojoReceiver is recommended for garbage collected objects, avoiding
problems with conflicting lifetimes.
(cherry picked from commit e3437317c4cd8401f0f0d599b61751bbe0e1ec70)
Bug: chromium:1369882
Change-Id: Ic38e761cf4275e6d7b30a6d7e2daa5d1596e67a4
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3936144
Reviewed-by: Henrik Boström <hbos@chromium.org>
Cr-Original-Commit-Position: refs/heads/main@{#1055630}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3934344
Commit-Queue: Henrik Boström <hbos@chromium.org>
Auto-Submit: Harald Alvestrand <hta@chromium.org> …
=> chore: cherry-pick cb9dff93f3d4 from chromium

chromium_src/BUILD.gn, shell/browser/api/electron_api_web_contents.cc, shell/browser/api/electron_api_web_contents.h, shell/browser/printing/print_view_manager_electron.cc, shell/browser/printing/print_view_manager_electron.h
Refs CL:3780384 and CL:3805932
Refactor `PrintViewManagerElectron` to take advantage of changes made in CL:3780384 and CL:3805932. Specifically - offload PDF print jobs to a newly added `components/printing/browser/print_to_pdf/pdf_print_job.{h|cc}` class. This also enables PDF composition support to allow OOPIF printing to PDF.
Tested with:
- https://gist.github.com/codebytere/0f0e776b138452d6815ef4efc16aa0d1
- https://gist.github.com/lesleyandreza/7699603b20f2459d1fcf3b9480fb22e1
Notes: Enabled out-of-process iframe printing to PDF with `webContents.printToPDF().`.
=> refactor: enable OOPIF printing to PDF

patches/sqlite/.patches, patches/sqlite/utf-8_q_m102-lts_20enhance_20defensive_20mode_20so_20that_20i.patch
[M102-LTS] Enhance defensive mode so that it disallows CREATE TRIGGER statements if
the statements within the trigger attempt to write on a shadow table.  Also
make the legacy FTS3 code more robust against integer overflow during
memory allocation.
Bug: [1368076](https://bugs.chromium.org/p/chromium/issues/detail?id=1368076)
FossilOrigin-Name: c41f25e6f3591e575452c4c68f8072a0163cc00d80af31f90d407c7deca79622
(cherry picked from [commit 3ec786ab9cfa213525ecc18b326aeb18ab842f7d](https://chromium-review.googlesource.com/q/commit:3ec786ab9cfa213525ecc18b326aeb18ab842f7d))
Change-Id: [I3b2cbf7c04f1873a6001d577feefaa8abd9f2a7d](https://chromium-review.googlesource.com/q/I3b2cbf7c04f1873a6001d577feefaa8abd9f2a7d)
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/deps/sqlite/+/393355 …
=> chore: cherry-pick d7feae867b83 from sqlite

script/node-spec-runner.js
Exit properly if `node script/node-spec-runner --validateDisabled` finds no missing tests.
Notes: none
=> test: exit properly when `node-spec-runner` validates specs

package.json, script/gn-asar-hash.js, script/gn-asar.js, spec/fixtures/test.asar/repack.js, yarn.lock
Backport of #36070 
* refactor: migrate from asar to @electron/asar
* fix: update asar require calls
=> refactor: migrate from asar to @electron/asar (#36070)

script/lib/get-version.js
This might fix the nightly release, shot in the dark
=> build: ensure get-version runs in the electron git checkout

docs/api/ipc-renderer.md
Closes #24427.
I don't think we want to change the serialization behavior of `Error` here, but enough people have tripped over this that it deserves a mention in the docs.
Notes: none
=> docs: document that when `invoke` rejects, it gives a different Error

lib/browser/api/web-contents.ts, spec/api-web-contents-spec.ts
Fixes #28208.
Notes: Fixed spurious promise rejection in `webContents.loadURL` when navigating to a hash.
=> fix: resolve loadURL properly for in-page navigations

patches/config.json, patches/skia/.patches, patches/skia/cherry-pick-07a2ce61e31a.patch
[Cherry-pick] Fix GrDirectContext::fClinetMappedBuffer access in abandoned callbacks.
Bug: chromium:1364604
Change-Id: I1ca44cab1c762e7f94ac94be94991ec94a7497be
Reviewed-on: https://skia-review.googlesource.com/c/skia/+/583963
Commit-Queue: Greg Daniel <egdaniel@google.com>
Reviewed-by: Brian Salomon <bsalomon@google.com>
Reviewed-on: https://skia-review.googlesource.com/c/skia/+/587879
Auto-Submit: Greg Daniel <egdaniel@google.com>
Commit-Queue: Brian Salomon <bsalomon@google.com>
Notes: Security: backported fix for 1364604.
=> chore: cherry-pick 07a2ce61e31a from skia

patches/chromium/.patches, patches/chromium/cherry-pick-65f0ef609c00.patch
Fix UAF issue around permission status observer list
(cherry picked from commit 4df595127d95d4b0bf115be1ab4604d95b75273c)
(cherry picked from commit 1dc5dda6112bdd811c923520cc728a474583409e)
Bug: 1363040
Change-Id: I1f64a901b83aa834ae652c8041456e9b7d253c1f
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3907744
Reviewed-by: Kamila Hasanbega <hkamila@chromium.org>
Commit-Queue: Andy Paicu <andypaicu@chromium.org>
Cr-Original-Original-Commit-Position: refs/heads/main@{#1049058}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3929034
Reviewed-by: Illia Klimov <elklm@chromium.org>
Cr-Original-Commit-Position: refs/branch-heads/5304@{#483}
Cr-Original-Branched-From: 5d7b1fc9cb7103d9c82eed647cf4be38cf09738b-refs/heads/main@{#1047731}
Reviewed-on: …
=> chore: cherry-pick 65f0ef609c00 from chromium

lib/renderer/web-view/web-view-attributes.ts
`loadURL` throws uncaught promise error such as `Uncaught (in promise) Error: Error invoking remote method 'GUEST_VIEW_MANAGER_CALL': Error: ERR_FAILED (-2) loading 'http://xxx.com/'
at t.ipcRendererInternal.invoke` very often.
Issues: #28208, #35240
Actually I do nothing. But I think it's better than uncaught error.
Notes: none
=> refactor: handle uncaught promise error

spec/chromium-spec.ts
Something changed on our arm CI hardware where HID devices are no longer available, so this PR updates the afffected test.  This change will land in main under the roller PR.
Notes: none
=> test: fixup HID test for ARM CI

script/release/uploaders/upload.py
In a previous PR, we removed the "v" prefix from Electron version, as there were several areas in the code that weren't expecting it. However, the upload script still expects a prefix. This PR re-adds the prefix to the upload script.
Notes: none
=> build: prefix version in uploader script

script/release/publish-to-npm.js
Fixes the beta release - use npm@7 explicitly when publishing
Notes: none
=> build: use npm@7 for npm view command

docs/tutorial/mac-app-store-submission-guide.md
- replaced mention of Application Loader with Apple Transporter, its replacement
- replaced mention of iTunes Connect with App Store Connect
- updated link for creating a record
Fixes https://github.com/electron/electron/issues/35115
Notes: none
=> docs: Fixed outdated documentation (uploading to App Store)

patches/v8/.patches, patches/v8/cherry-pick-194bcc127f21.patch
Merged: [turbofan] validate more concurrent reads
Bug: chromium:1369871
(cherry picked from commit ebe5675360e4735589a92a8836303822da79a8f4)
Change-Id: I49243d2c604cb4635d0d49a572245f7469eabffa
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/3952937
Cr-Commit-Position: refs/branch-heads/10.6@{#41}
Ref electron/security#235
Notes: Security: backported fix for CVE-2022-3652.
=> chore: cherry-pick 194bcc127f21 from v8

patches/chromium/.patches, patches/chromium/cherry-pick-67c9cbc784d6.patch
Validate `source_context` in ExtensionHostMsg_OpenChannelToNativeApp.
After this CL, the Browser process will verify `source_context` in the
IPC payload of the ExtensionHostMsg_OpenChannelToNativeApp message and
avoid processing malformed or spoofed IPCs.
Change-Id: I9466dc076c4d07dbb4bec38973000dc0418565f6
Bug: 1356234
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3854987
Commit-Queue: Łukasz Anforowicz <lukasza@chromium.org>
Reviewed-by: Devlin Cronin <rdevlin.cronin@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1041118}
Notes: Security: backported fix for 1356234.
=> chore: cherry-pick 67c9cbc784d6 from chromium

patches/chromium/.patches, patches/chromium/cherry-pick-d5ffb4dd4112.patch
[M106 Merge] WebGPU: use CHECK instead of DCHECK to crash out of bounds write in SerializeDataUpdate
A comprised renderer could have a shared memory size not large enough
to fit the GPU buffer contents. Instead of DCHECK, do a CHECK here to
crash the release build. The crash is fine since it is not reachable
from normal behavior. WebGPU post-V1 will have a refactored API.
(cherry picked from commit 9bcbce75d5feaa1ba48a5d0d8036b5c77500bb67)
Fixed: 1373314
Change-Id: I8d8e1a469c2b10ff16e7363f9b6f7b63587cb007
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3946246
Reviewed-by: Austin Eng <enga@chromium.org>
Commit-Queue: Shrek Shao <shrekshao@google.com>
Cr-Original-Commit-Position: refs/heads/main@{#1058233}
Reviewed-on: …
=> chore: cherry-pick d5ffb4dd4112 from chromium

patches/angle/.patches, patches/angle/cherry-pick-b8636b57b8f2.patch
[M106] Vulkan: Ensure we sync the draw FB before beingQuery.
Bug: chromium:1354271
(cherry picked from commit 4ebdac790c76b65abf5703bcef9482c638076195)
Change-Id: I7b715a9c28badfe58a0ae1a478d2b4e8bbd23c47
Reviewed-on: https://chromium-review.googlesource.com/c/angle/angle/+/3956939
Ref electron/security#239
Notes: Security: backported fix for CVE-2022-3653.
=> chore: cherry-pick b8636b57b8f2 from angle

patches/webrtc/.patches, patches/webrtc/cherry-pick-eef098d1c7d5.patch
[Merge-107] [Stats] Avoid DCHECK crashing if SSRCs are not unique.
To properly handle SSRC collisions in non-BUNDLE we need to change how
RTP stats IDs are generated, but that is a riskier change to be dealt
with in a separate CL.
For now, we just make sure that crashing is not a possibility during
SSRC collisions as a mitigation for https://crbug.com/1361612. This is
achieved by adding a TryAddStats() method to RTCStatsReport returning
whether successful.
(cherry picked from commit da6297dc53cb2eaae7b1c5381652de9d707a7d48)
Bug: chromium:1361612
Change-Id: I8577ae4c84a7c1eb3c7527e9efd8d1b0254269a3
Reviewed-on: https://webrtc-review.googlesource.com/c/src/+/275766
Reviewed-by: Harald Alvestrand <hta@webrtc.org>
Commit-Queue: Henrik Boström <hbos@webrtc.org> …
=> chore: cherry-pick eef098d1c7d5 from webrtc

patches/chromium/.patches, patches/chromium/cherry-pick-06c87f9f42ff.patch
Avoid layout roots in subtrees skipped for style recalc
Layout roots are laid out from inner to outer in LocalFrameView. DOM
mutations may have added layout roots inside size container subtrees
before style recalc. If we decide to postpone style recalc until layout
of the size container, it means we may try to layout a root inside a
subtree skipped for style recalc. That causes a DCHECK and possibly
other issues.
This also fixes the use-after-poison issue 1365330.
(cherry picked from commit 0f0f1e99201fadb3c68518350e1cd6af1b665346)
Bug: 1371820, 1365330
Change-Id: Ia48890c08aacfe7b9a3e660817702abce0570564
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3934847
Reviewed-by: Ian Kilpatrick <ikilpatrick@chromium.org>
Commit-Queue: Rune Lillesveen <futhark@chromium.org> …
=> chore: cherry-pick 06c87f9f42ff from chromium

patches/chromium/.patches, patches/chromium/cherry-pick-933cc81c6bad.patch
Remove symlinks from FileChooserImpl folder upload result
FileChooserImpl is the browser-side implementation of
<input type=file>. When uploading a whole folder, it
currently uses DirectoryLister to list all the files in a
directory. The result also includes resolved symbolic links
(which may even hide deep in some subfolder), which is not a
desired behavior.
Therefore, this patch removes all symbolic links from the
result by checking each file against `base::IsLink()`. Since
the function needs blocking calls to access file data, the
job is sent to a worker pool thread.
Fixed: 1345275
Change-Id: I8ab58214c87944408c64b177e915247a7485925b
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3866767
Commit-Queue: Xiaocheng …
=> chore: cherry-pick 933cc81c6bad from chromium

patches/v8/.patches, patches/v8/cherry-pick-ec236fef54b8.patch
Merged: [turbofan] do not optimize any stores for field type None
Fixed: chromium:1378239
(cherry picked from commit db83e72034c0d431ff2f73e3c4ae3130c0f3e4e1)
Change-Id: I061d5dfe6e4ee24e6d0e7df56e15fbe37752d51e
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/3982254
Reviewed-by: Tobias Tebbi <tebbi@chromium.org>
Cr-Commit-Position: refs/branch-heads/10.6@{#45}
Ref electron/security#240
Notes: Security: backported fix for CVE-2022-3723.
=> chore: cherry-pick ec236fef54b8 from v8

patches/chromium/.patches, patches/chromium/refresh_cached_attributes_before_name_computation_traversal.patch, patches/chromium/review_add_clear_children_checks_during_accname_traversal.patch
Backport:
- https://chromium-review.googlesource.com/c/chromium/src/+/3633568
- https://chromium-review.googlesource.com/c/chromium/src/+/3657488
```
Teams.exe!blink::AXObject::AOMPropertyOrARIAAttributeIsTrue(blink::AOMBooleanProperty property) Line 1100    C++
Teams.exe!blink::AXNodeObject::TextFromDescendants(blink::HeapHashSet<cppgc::internal::BasicMember<const blink::AXObject,cppgc::internal::StrongMemberTag,cppgc::internal::DijkstraWriteBarrierPolicy,cppgc::internal::DisabledCheckingPolicy>,WTF::MemberHash<const blink::AXObject>,WTF::HashTraits<cppgc::internal::BasicMember<const blink::AXObject,cppgc::internal::StrongMemberTag,cppgc::internal::DijkstraWriteBarrierPolicy,cppgc::internal::DisabledCheckingPolicy>>> & visited, const blink::AXObject * aria_label_or_description_root, bool …
```
=> fix: crash in AXNodeObject::TextFromDescendants()

patches/chromium/.patches, patches/chromium/cherry-pick-ac4785387fff.patch
[m106] Fix PauseOrFreezeOnWorkerThread with nested Worklets.
Worklets can use the same backing thread which means we can have
nested WorkerThreads paused. If a parent WorkerThread gets deallocated
make sure we don't access anything after it is deallocated once the
nested event queue is released.
BUG=1372695
(cherry picked from commit ff5696ba4bc0f8782e3de40e04685507d9f17fd2)
Change-Id: I176b8f750da5a41d19d1b3a623944d9a2ed4a441
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3953152
Commit-Queue: Dave Tapuska <dtapuska@chromium.org>
Cr-Original-Commit-Position: refs/heads/main@{#1059485}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4004562
Cr-Commit-Position: refs/branch-heads/5249@{#906} …
=> chore: cherry-pick ac4785387fff from chromium

patches/v8/.patches, patches/v8/cherry-pick-80ed4b917477.patch
Merged: [compiler] Fix mutable heap number object reference leak
(cherry picked from commit 64112122374c00a86771b4612d20ca5d88ad5bfb)
Bug: chromium:1380063
No-Try: true
Change-Id: Ifa1737af7fbc7e14d69a5080cbe0aabf7ef466fa
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/4009978
Commit-Queue: Maya Lekova <mslekova@chromium.org>
Cr-Commit-Position: refs/branch-heads/10.6@{#51}
Ref electron/security#246
Notes: Security: backported fix for CVE-2022-3889.
=> chore: cherry-pick 80ed4b917477 from v8

patches/v8/.patches, patches/v8/cherry-pick-2ac0620a5bbb.patch
Merged: [wasm] Reload cached instance fields in catch handler
Bug: chromium:1377816
(cherry picked from commit f517e518af26b7eac23c9e328b463eb1e8ee3499)
Change-Id: I993bcff0389a1ba134e89e8ac5299d742ddd150c
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/3999134
Commit-Queue: Thibaud Michaud <thibaudm@chromium.org>
Reviewed-by: Jakob Kummerow <jkummerow@chromium.org>
Cr-Commit-Position: refs/branch-heads/10.6@{#47}
Ref electron/security#241
Notes: Security: backported fix for CVE-2022-3885.
=> chore: cherry-pick 2ac0620a5bbb from v8

patches/chromium/.patches, patches/chromium/cherry-pick-a1cbf05b4163.patch
[M106] webcodecs: Fix race in VE.isConfigSupported() promise resolution
If the context is destroyed before VideoEncoder calls `done_callback`, bad
things can happen. That's why we extract a callback runner before doing
anything asynchronous. Since we hold a ref-counted pointer to the
runner it should be safe now.
(cherry picked from commit 2acf28478008315f302fd52b571623e784be707b)
Bug: 1375059
Change-Id: I984ab27e03e50bd5ae4bf0eb13431834b14f89b7
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3965544
Commit-Queue: Eugene Zemtsov <eugene@chromium.org>
Reviewed-by: Dale Curtis <dalecurtis@chromium.org>
Cr-Original-Commit-Position: refs/heads/main@{#1061737}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4005574
Reviewed-by: Matthew Wolenetz …
=> chore: cherry-pick a1cbf05b4163 from chromium

patches/chromium/.patches, patches/chromium/cherry-pick-1894458e04a2.patch
Validate number of bytes read
Original commit:
https://chromium-review.googlesource.com/c/crashpad/crashpad/+/3994208
(cherry picked from commit 7585111a6c1dfa502f3ca1e3d27aed066e479fd9)
Bug: chromium:1380083
Change-Id: If9708ccdbf6957ef169b35f8f89e2b0744d066d7
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4000305
Reviewed-by: Mark Mentovai <mark@chromium.org>
Commit-Queue: Joshua Peraza <jperaza@chromium.org>
Cr-Original-Commit-Position: refs/branch-heads/5359@{#529}
Cr-Original-Branched-From: 27d3765d341b09369006d030f83f582a29eb57ae-refs/heads/main@{#1058933}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4004067
Cr-Commit-Position: refs/branch-heads/5249@{#905} …
=> chore: cherry-pick 1894458e04a2 from chromium

patches/chromium/.patches, patches/chromium/cherry-pick-81cb17c24788.patch
[Autofill] Handle misaligned FormData, FormStructure.
This CL handles the case where the fields of the cached FormStructure
and the FormData are misaligned in
BrowserAutofillManager::WillFillCreditCardNumber.
(cherry picked from commit 1ad751f7dfa30a12a85824c291394b73c5c47eff)
Bug: 1376637, 1376639
Change-Id: Id7c3357a274b4d6624009ecf52b95a24cf3bfa1d
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3965141
Commit-Queue: Christoph Schwering <schwering@google.com>
Quick-Run: Christoph Schwering <schwering@google.com>
Reviewed-by: Dominic Battré <battre@chromium.org>
Auto-Submit: Christoph Schwering <schwering@google.com>
Cr-Original-Commit-Position: refs/heads/main@{#1061790}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4003032
Commit-Queue: …
=> chore: cherry-pick 81cb17c24788 from chromium

patches/chromium/.patches, patches/chromium/fix_crash-on-close_for_mac_udp_sockets.patch
Backport: https://chromium-review.googlesource.com/c/chromium/src/+/3682001
Notes: none
=> fix: crash-on-close for Mac UDP sockets

patches/v8/.patches, patches/v8/cherry-pick-177e8bcd3584.patch
Merged: [compiler] fix bug in inlining of Array.At
The inlined version of Array.At was only checking the kind of the
maps, rather than the maps themselves. When the feedback was
containing an array map that "supports_fast_array_iteration", then its
kind was added to the list of supported kinds. If this Array.at was
later called with a non-array map with the same kind, then the object
would be wrongly treated as an array.
This is now fixed: inlining Array.at checks the maps directly rather
than only their kinds.
Bug: chromium:1377775
(cherry picked from commit 0ce27310674150b46605c1e226b8f1a2503bac8c)
Change-Id: I2398f2f7a1ea37808962ba5eb3d1fe00a54fd614
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/3990747
Commit-Queue: Darius Mercadier <dmercadier@chromium.org> …
=> chore: cherry-pick 177e8bcd3584 from v8

filenames.auto.gni
This change happens on clean branches, not sure how it got out of sync
=> build: fix filenames.auto

BUILD.gn, build/config/BUILD.gn, patches/chromium/.patches, patches/chromium/build_only_use_the_mas_build_config_in_the_required_components.patch, patches/chromium/disable_compositor_recycling.patch, patches/chromium/feat_ensure_mas_builds_of_the_same_application_can_use_safestorage.patch, patches/chromium/mas-cgdisplayusesforcetogray.patch, patches/chromium/mas_avoid_usage_of_private_macos_apis.patch, patches/chromium/mas_blink_no_private_api.patch, patches/chromium/mas_disable_custom_window_frame.patch, patches/chromium/mas_disable_remote_accessibility.patch, patches/chromium/mas_disable_remote_layer.patch, patches/chromium/mas_no_private_api.patch, patches/chromium/mas_use_public_apis_to_determine_if_a_font_is_a_system_font.patch, patches/chromium/render_widget_host_view_mac.patch, shell/app/electron_main_delegate.cc, shell/app/electron_main_mac.cc, shell/app/node_main.cc, shell/browser/api/electron_api_app.cc, shell/browser/api/electron_api_app.h, shell/browser/api/electron_api_crash_reporter.cc, shell/browser/api/electron_api_web_contents.cc, shell/browser/api/process_metric.cc, shell/browser/auto_updater.cc, shell/browser/browser_mac.mm, shell/browser/notifications/mac/notification_center_delegate.mm, shell/browser/ui/file_dialog_mac.mm, shell/common/api/electron_bindings.cc, shell/common/node_bindings.cc, shell/renderer/api/electron_api_crash_reporter_renderer.cc
This is missing-definition safe and thus allows us to move the definition of this macro away from "all compilation targets" to "just the compilation targets that depend on this macro".
In turn this makes the rebuild time changing from mas <-> darwin only 80 seconds on my machine, instead of the 12-15 minutes it used to take.  This will also allow us in the future to build both MAS and darwin on the same CI machine.  Costing us ~2 minutes on one machine but saving us anywhere from 30 minutes to an hour of CI time on other parts of the matrix.
I think before this lands I want to clean up the new patch file a bit (potentially merge those changes into the other MAS patch files) but I'll consider that tomorrow.
=> refactor: change defined(MAS_BUILD) to IS_MAS_BUILD()

.circleci/config/base.yml
This makes the src cache a bit smaller
=> build: make src cache smaller

.circleci/config/base.yml
I believe changes in ninja have made this logic not work and although we might want to make it work again in the future, right now we're burning network transit, storage costs and CI time doing something that has no positive impact on build time.
=> build: remove out cache

SECURITY.md
We have this new "Report a vulnerability" feature now, we should be directing people to that instead of asking them to email us.
=> docs: update SECURITY.md with new GHSA reporting feature

.circleci/config/base.yml
This is a CI build time optimization.  Basically we are willing to burn a few minutes in the `osx` build job in order to completely remove the need for a separate `mas` job.  In the worst case this takes an additional 10 minutes in the `osx` job (though on average it should be ~5-6 minutes).  But it saves us a full 40-60 minutes in a separate job thus lowering our macOS machine usage considerably.
As all this config is re-usable there's potentially a world where we can do this for the `no-run-as-node` build as well but not sure how much value we'd get out of that in comparison.
=> build: build mas and darwin simultaneously

patches/node/.patches, patches/node/chore_enable_c_17_for_native_modules.patch
With Electron 20, V8 uses C++17 features. We updated userland build tools to provide the required compile time flag https://github.com/electron/rebuild/pull/1022. But instead the headers we ship should reflect this change by default similar to Nodejs, refs https://github.com/nodejs/node/pull/38807.
`main` branch already has this change since we updated to Nodejs v18
Notes: Update `common.gypi` for native modules to support C++17 features in V8
=> chore: compile addons with --gnu++17

npm/install.js
Fix an unresolved promise introduced in #33979, where the `resolve` is never called.
This problem was not observable because there's no variable holding reference to the promise, so V8 will correctly GC it. But the code logic still has problem.
=> chore: fix dangling promise in npm install

.circleci/config/base.yml
As in title, this was caused by https://chromium-review.googlesource.com/c/chromium/tools/depot_tools/+/4034942 (Credit @VerteDinde for tracking down that change)
Notes: none
=> build: force ninja binary to the right arch after src cache restore

.github/workflows/update_appveyor_image.yml, appveyor-bake.yml, appveyor.yml, build/profile_toolchain.py, script/lib/utils.js, script/prepare-appveyor.js, script/release/ci-release-build.js, script/setup-win-for-dev.bat, spec/api-browser-view-spec.ts, spec/api-browser-window-spec.ts
This PR improves our current Windows automation in two ways:
1. Automatically bakes AppVeyor images when the version of Chromium is updated in the base branch (main, 21-x-y, etc).
2. Determines whether or not the depshash of the PR in testing is different than the latest baked image - if it is the same, we run `gclient runhooks` rather than a full `gclient sync`, saving time.
In order to accomplish #1 and keep each branch relatively up to date with the latest baked image, this PR also adds a daily cron job/GitHub Action that checks whether or not the Chromium version in main has changed, kicks off a new image bake and automatically opens a PR updating `appveyor.yml` to the newest bake image.
Merge Blockers:
Potential Future Improvement:
Notes: none
=> ci: bake appveyor images automatically, run sync on depshash change

.devcontainer/README.md, .devcontainer/devcontainer.json, .devcontainer/docker-compose.yml, .devcontainer/on-create-command.sh, .devcontainer/update-content-command.sh
With codespaces prebuild's and some other new codespaces features this is now super usable.
It takes ~12-15 minutes to go from nothing to a fully built linux checkout.  (Down from 1-2 hours)
=> build: update devcontainer and use latest codespaces features

appveyor.yml, script/setup-win-for-dev.bat
Windows release builds failed because `symstore` was not in the PATH of the appveyor baked images.  This PR updates the bake to set the path properly.
Notes: none
=> build: fixup appveyor image for release

docs/api/utility-process.md
=> docs: add missing event-emitter link to utility-process docs

patches/chromium/.patches, patches/chromium/cherry-pick-6b4af5d82083.patch
[M107] Fix potential OOB problem with validating command decoder
Bug: [1392715](https://bugs.chromium.org/p/chromium/issues/detail?id=1392715)
Change-Id: [If51b10cc08e5b3ca4b6012b97261347a5e4c134e](https://chromium-review.googlesource.com/q/If51b10cc08e5b3ca4b6012b97261347a5e4c134e)
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4048203
Auto-Submit: Peng Huang <[penghuang@chromium.org](mailto:penghuang@chromium.org)>
Commit-Queue: Peng Huang <[penghuang@chromium.org](mailto:penghuang@chromium.org)>
Reviewed-by: Geoff Lang <[geofflang@chromium.org](mailto:geofflang@chromium.org)>
Cr-Commit-Position: refs/heads/main@{#1074966}
Notes: Security: backported fix for CVE-2022-4135.
=> chore: cherry-pick 6b4af5d82083 from chromium

patches/chromium/.patches, patches/chromium/cherry-pick-7196a42b42ce.patch
Reconfigure stream on window resize when using ScreenCaptureKit
Bug: chromium:1352405
Change-Id: I315104eb4ee985a2d04ea90f01341129c6307501
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4027202
Reviewed-by: ccameron chromium <ccameron@chromium.org>
Commit-Queue: Johannes Kron <kron@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1072984}
Notes: Backported fix for chromium:1352405.
=> chore: cherry-pick 7196a42b42ce from chromium

filenames.gni, patches/node/.patches, patches/node/enable_crashpad_linux_node_processes.patch, shell/app/node_main.cc, shell/common/api/crashpad_support.cc, shell/common/node_bindings.cc, spec/api-crash-reporter-spec.ts, spec/fixtures/apps/crash/fork.js, spec/fixtures/apps/crash/main.js, spec/fixtures/apps/crash/node-extra-args.js
Manual backport of #36460
Notes: Enable crashpad for ELECTRON_RUN_AS_NODE processes on linux.
=> fix: enable crashpad for ELECTRON_RUN_AS_NODE processes

build/args/all.gn
This PR adds a new node module version number for Electron 23. This needs to be merged before the first 23 alpha is cut.
Node PR here: https://github.com/nodejs/node/pull/45661
NOTE: Please hold until the node PR has been merged
Notes: none
=> chore: update NMV for Electron 23

shell/browser/notifications/platform_notification_service.cc
This makes it so that HTML5 Notifications with the `requireInteraction` flag will not timeout/disappear automatically, taking advantage of the work done in https://github.com/electron/electron/pull/20153 for Linux/Windows. cc @codebytere @MarshallOfSound 
Notes: Changed HTML5 Notifications created with the `requireInteraction` option to not timeout on Linux and Windows.
=> fix: handle Notification requireInteraction option

docs/api/web-contents.md
This was added in https://github.com/electron/electron/pull/31314 but wasn't
documented in setWindowOpenHandler's docs, only in the window.open docs.
Notes: none
=> docs: document outlivesOpener option in window open handler

build/args/all.gn
This PR adds a new node module version number for Electron 24.
Node PR here: nodejs/node#45661
⚠️ NOTE: Please hold until the node PR has been merged and the 23-x-y branch has been cut. ⚠️ 
Notes: none
=> chore: update NMV for Electron 24

.circleci/config/base.yml
- Fixup of #36378 for Linux.  Unfortunately that PR did not remove the unneeded args for the Linux mksnapshot zips. 
Notes:  Removed unneeded --turbo-profiling-input argument from mksnapshot_args for Linux mksnapshot zips.
=> build: fixup mksnapshot args on linux

patches/chromium/.patches, patches/chromium/cherry-pick-3235c1d1955b.patch
Set visible_rect for streams captured with ScreenCaptureKit
This is needed to make the window capturing code on macOS
using the new ScreenCaptureKit API work, because the IOSurface
may be larger than the actual content resulting in garbage
unless the frame is cropped to |visible_rect|.
Bug: chromium:1352405
Change-Id: I1ce3c13947b9b4f9b75a071800a84a27a7c2ee4a
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4046582
Reviewed-by: Mark Foltz <mfoltz@chromium.org>
Commit-Queue: Johannes Kron <kron@chromium.org>
Reviewed-by: ccameron chromium <ccameron@chromium.org>
Reviewed-by: Ilya Nikolaevskiy <ilnik@chromium.org>
Reviewed-by: Will Cassella <cassew@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1077752}
Notes: Backported fix for chromium:1352405.
=> chore: cherry-pick 3235c1d1955b from chromium

docs/api/net.md
Closes #36548
This should be linked 👍 
=> docs: link net.request options to ClientRequestConstructorOptions

.github/workflows/issue-labeled.yml, .github/workflows/stale.yml
The bot that responds to blocked/need-repro says that the issue will be closed
in 10 days with no response, so this makes that true.
Notes: none
=> ci(not-really): autoclose issues with blocked/need-repro and no response

patches/chromium/.patches, patches/chromium/cherry-pick-f98adc846aad.patch
FSA: Block .url files in getFileHandle and getEntries
Fixed: 1354518
Change-Id: I663d4481ccc2047c49d7466bbfe9751e8c140edf
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3945587
Auto-Submit: Austin Sullivan <asully@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1057675}
Notes: Security: backported fix for CVE-2022-4193.
=> chore: cherry-pick f98adc846aad from chromium

docs/api/structures/web-request-filter.md
When I was using the Electron docs I wanted to know how to use [webRequest.onBeforeSendHeaders](https://www.electronjs.org/docs/latest/api/web-request#webrequestonbeforesendheadersfilter-listener) but I was unable to correctly guess the correct format for the `WebRequestFilter` URL strings, and there was no explanation in the Electron docs. Eventually I googled it and found the MDN article which helped me.
- [x ] PR description included and stakeholders cc'd
- [x ] relevant documentation, tutorials, templates and examples are changed or added
Notes: none
=> docs: add mdn link to web-request-filter.md

patches/v8/.patches, patches/v8/cherry-pick-c79148742421.patch
Merged: Reland "[Promise.any] Fix errors allocation"
Bug: chromium:1379054
(cherry picked from commit 8b35091b2d244c975975e1c78e4cd09cb479b5dc)
Change-Id: Iec8f8bb51f4434d6ae86887cf742f2883a9b7bef
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/4004804
Cr-Commit-Position: refs/branch-heads/10.8@{#34}
Cr-Branched-From: f1bc03fd6b4c201abd9f0fd9d51fb989150f97b9-refs/heads/10.8.168@{#1}
Cr-Branched-From: 237de893e1c0a0628a57d0f5797483d3add7f005-refs/heads/main@{#83672}
Ref electron/security#252
Notes: Security: backported fix for CVE-2022-4174.
=> chore: cherry-pick c79148742421 from v8

patches/chromium/.patches, patches/chromium/cherry-pick-2ef09109c0ec.patch
Unify security check for Javascript URL navigation
This change unifies CSP and Trusted Types check for Javascript URL
navigations.
Bug: 1365082
Change-Id: I46aea31a918c6397ea71fd5ab345bc9dc19d91c2
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3905476
Auto-Submit: Jun Kokatsu <jkokatsu@google.com>
Commit-Queue: Jun Kokatsu <jkokatsu@google.com>
Reviewed-by: Nate Chapin <japhet@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1050416}
Notes: Security: backported fix for 1365082.
=> chore: cherry-pick 2ef09109c0ec from chromium

patches/chromium/.patches, patches/chromium/cherry-pick-42e15c2055c4.patch
Avoid use-after-free in ValidationMessageOverlayDelegate
When ValidationMessageOverlayDelegate calls
ForceSynchronousDocumentInstall, it can somehow cause another validation
overlay to be created and delete the ValidationMessageOverlayDelegate.
This patch avoids additional code from being run inside the deleted
ValidationMessageOverlayDelegate.
(cherry picked from commit a37b66ded21af7ff1442bddd2ec3a0845535b3d6)
Fixed: 1382581
Change-Id: I044f91ecb55c77c4a5c40030b6856fc9a8ac7f6f
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4019655
Reviewed-by: David Baron <dbaron@chromium.org>
Commit-Queue: Joey Arhar <jarhar@chromium.org>
Cr-Original-Commit-Position: refs/heads/main@{#1071652}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4043489 …
=> chore: cherry-pick 42e15c2055c4 from chromium

patches/chromium/.patches, patches/chromium/cherry-pick-f46db6aac3e9.patch
Do not traverse directory symlinks when uploading folder
Previous patch crrev.com/c/3866767 removed symlink files when uploading
a folder. However, while the remaining files are themselves not
symlinks, they may be included as the result of traversing directory
symlink.
This patch further excludes such files by checking if any parent
directory is a symlink, all the way until the base directory (which is
the directory chosen for upload).
(cherry picked from commit 4fa830d8af6b2fb293219edeb39eebccfd322305)
Fixed: 1378997
Change-Id: I75a92df4cd50f9aba7824955a3de792583bc6154
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3997720
Reviewed-by: Mason Freed <masonf@chromium.org>
Reviewed-by: Alex Moshchuk …
=> chore: cherry-pick f46db6aac3e9 from chromium

patches/node/.patches, patches/node/cherry-pick-09ae62b.patch
node-api: handle no support for external buffers
Refs: https://github.com/electron/electron/issues/35801
Refs: https://github.com/nodejs/abi-stable-node/issues/441
Electron recently dropped support for external
buffers. Provide a way for addon authors to:
- hide the methods to create external buffers so they can
avoid using them if they want the broadest compatibility.
- call the methods that create external buffers at runtime
to check if external buffers are supported and either
use them or not based on the return code.
Signed-off-by: Michael Dawson <mdawson@devrus.com>
PR-URL: https://github.com/nodejs/node/pull/45181
Reviewed-By: Chengzhong Wu <legendecas@gmail.com>
Reviewed-By: Minwoo Jung <nodecorelab@gmail.com>
Notes: Added node-api: handle no support for external buffers.
=> chore: cherry-pick 09ae62b from node

patches/chromium/.patches, patches/chromium/cherry-pick-176c526846cb.patch
Fix a data race leading to use-after-free in mojo::ChannelMac ShutDown
(cherry picked from commit bd8a1e43aa93d5bb7674cb5a431e7375f7e2f192)
Bug: 1378564
Change-Id: I67041b1e2ef08dd0ee1ccbf6d534249c539b74db
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4027242
Commit-Queue: Robert Sesek <rsesek@chromium.org>
Reviewed-by: Ken Rockot <rockot@google.com>
Cr-Original-Commit-Position: refs/heads/main@{#1071700}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4035114
Auto-Submit: Robert Sesek <rsesek@chromium.org>
Cr-Commit-Position: refs/branch-heads/5359@{#881} …
=> chore: cherry-pick 176c526846cb from chromium

script/add-debug-link.py, script/copy-debug-symbols.py, script/lib/config.py, script/lib/util.py, script/strip-binaries.py
When creating branded release builds and using scripts/strip-binaries.py
on Linux, the final artifacts end up unstripped due to the static set of
binaries considered for stripping.
With this patch the name of the electron binary is taken from the
BRANDING.json `project_name` key.
Notes: Fix binary stripping for branded release builds on Linux
=> fix: strip branded binaries

patches/chromium/.patches, patches/chromium/cherry-pick-65ad70274d4b.patch
Fix UAF in VideoCaptureDeviceWin::FrameReceived
(cherry picked from commit d08a3822658cb4ca4261659f1487069a14b51bd9)
Bug: 1381401
Change-Id: Ib742ec7b86d3c419f37f12694bf9cd5f3f03305c
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4013158
Reviewed-by: Markus Handell <handellm@google.com>
Commit-Queue: Ilya Nikolaevskiy <ilnik@chromium.org>
Cr-Original-Commit-Position: refs/heads/main@{#1069054}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4023295
Cr-Commit-Position: refs/branch-heads/5359@{#809}
Cr-Branched-From: 27d3765d341b09369006d030f83f582a29eb57ae-refs/heads/main@{#1058933}
Ref electron/security#250
Notes: Security: backported fix for CVE-2022-4175.
=> chore: cherry-pick 65ad70274d4b from chromium

appveyor.yml
- This PR updates Windows CI to use the e-108.0.5359.125 for 22-x-y, to correspond with the latest chromium roll on that branch: #36661
Notes: none
=> ci: update Windows image to e-108.0.5359.125

patches/webrtc/.patches, patches/webrtc/cherry-pick-136ef25acbf7.patch
Fix crash when appending empty array to AudioMultiVector.
Bug: webrtc:14442,chromium:1367993
Change-Id: I9453e300a6d3d78571d08cc65770787e13d43885
Reviewed-on: https://webrtc-review.googlesource.com/c/src/+/276620
Commit-Queue: Jakob Ivarsson‎ <jakobi@webrtc.org>
Reviewed-by: Henrik Lundin <henrik.lundin@webrtc.org>
Cr-Commit-Position: refs/heads/main@{#38208}
Notes: Security: backported fix for 1367993.
=> chore: cherry-pick 136ef25acbf7 from webrtc

patches/chromium/.patches, patches/chromium/cherry-pick-d1d654d73222.patch
[M108] Mojo: Fix potential UAF in IPC Channel
(cherry picked from commit 120b4b05ac7eaa9024f677394aa663c2702174ce)
Fixed: 1394692
Change-Id: I1753b79eb6e9230ebb663eca47295d81dd859068
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4066994
Cr-Original-Commit-Position: refs/heads/main@{#1077742}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4085806
Cr-Commit-Position: refs/branch-heads/5359@{#1115} …
=> chore: cherry-pick d1d654d73222 from chromium

patches/config.json, patches/libaom/.patches, patches/libaom/rtc_avoid_scene_detection_on_resize.patch
rtc: Avoid scene detection on resize
Don't enter scene detection under external resize.
Add rc->prev_coded_width/height to track the
previous encoded frame eweight/height.
The rc is part of layer context so this will be
per spatial layer for SVC.
This fixes the buffer overflow issue below.
Bug: chromium:1393384
Change-Id: [I4b11818a27c439c2d2c42036dff7b8777f70a86e](https://aomedia-review.googlesource.com/#/q/I4b11818a27c439c2d2c42036dff7b8777f70a86e)
(cherry picked from commit bee1caded272127a6d6b70ac79479083d183d5d0)
Notes: Security: backported fix for chromium:1393384.
=> chore: cherry-pick fcf671adc2f3 from libaom

patches/chromium/.patches, patches/chromium/cherry-pick-eed5a4de2c40.patch
Fix UaF in ui::DropTargetEvent::DropTargetEvent.
There is an async operation in WebContentsViewAura that uses a ui::DropTargetEvent. DropTargetEvent has a pointer to OSExchangeData which gets destroyed before the async operation is called. This triggers the UaF because the operation attempts to reference a freed object (OSExchangeData).
Fix is for WebContentsViewAura::DragUpdatedCallback to use a DropMetadata struct instead of a ui::DropTargetEvent. This is the same pattern used by other callbacks in WebContentsViewAura.
(cherry picked from commit 9f4b5761c546a118b7187c0c7ddcb9ee5756f32c)
Bug: 1392661
Change-Id: I3c62a7473ef9b6cdd223f75fbda50671f539f9eb
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4070787
Reviewed-by: Avi Drissman <avi@chromium.org>
Commit-Queue: …
=> chore: cherry-pick eed5a4de2c40 from chromium

patches/chromium/.patches, patches/chromium/cherry-pick-9b3d0e2f1aab.patch
Keep a reference to the transfer buffer in Dawn read/write handles.
Previously the Dawn read/write handles in the GPU process only contained
a pointer to the inside of a shmem region owned by a gpu::Buffer that
had a different lifetime. This could allow a renderer process to
deallocate the memory from underneath the handle which is bad.
Fix this by keepind a scoped_refptr to the gpu::Buffer inside the
read/write handles to extend the lifetime of the shmem to be at least as
big as the handle's.
Fixed: chromium:1393177
Change-Id: I9d9c18d5155a46e0e3a01d385d221a6370bd2bea
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4056276
Reviewed-by: Austin Eng <enga@chromium.org>
Commit-Queue: Corentin Wallez <cwallez@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1076828} …
=> chore: cherry-pick 9b3d0e2f1aab from chromium

patches/chromium/.patches, patches/chromium/cherry-pick-65d46507a0c9.patch
[Merge to M108] Replace raw pointer to LocalMuter with weak ptr
This CL replaces a raw pointer to LocalMuter with a weak ptr. Additional
info about this bug here: http://crbug/1377783
(cherry picked from commit 9989b93eb12c93b9351d5bf2872c1069ef5f7d01)
Bug: 1377783
Change-Id: Id821ea800ba12f1cfae4677fc591c12dec112852
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3997421
Reviewed-by: Paul Semel <paulsemel@chromium.org>
Reviewed-by: Olga Sharonova <olka@chromium.org>
Commit-Queue: Evan Liu <evliu@google.com>
Cr-Original-Commit-Position: refs/heads/main@{#1068776}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4024547
Auto-Submit: Evan Liu <evliu@google.com>
Owners-Override: Srinivas Sista <srinivassista@chromium.org>
Bot-Commit: Rubber …
=> chore: cherry-pick 65d46507a0c9 from chromium

docs/tutorial/tutorial-3-preload.md
At the moment, the "Communicating between processes" `main.js` snippet highlights the line containing `})` when the relevant line for this part of the tutorial is `ipcMain.handle('ping', () => 'pong')`, this change just updates the highlighted line.
Notes: none
=> docs: Fix incorrect highlight in an example snippet

patches/chromium/.patches, patches/chromium/cherry-pick-819d876e1bb8.patch
Fix UAF caused by vector operations during iteration
MediaInspectorContextImpl::CullPlayers iterates through dead_players_
to remove their events, but this can cause a GC event which can
end up adding more players to the |dead_players_| vector, causing
it to get re-allocated and it's iterators invalidated.
We can fix this simply by not using an iterator, and removing elements
from the vector before we trigger any GC operations that might cause
other changes to the vector.
Bug: 1383991
Change-Id: I59f5824c156ff58cf6b55ac9b942c8efdb1ed65a
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4064295
Reviewed-by: Andrey Kosyakov <caseq@chromium.org>
Commit-Queue: Ted (Chromium) Meyer <tmathmeyer@chromium.org>
Reviewed-by: Thomas Guilbert <tguilbert@chromium.org> …
=> chore: cherry-pick 819d876e1bb8 from chromium

patches/chromium/.patches, patches/chromium/mojo_disable_sync_call_interrupts_in_the_browser.patch, patches/chromium/mojo_validate_that_a_message_is_allowed_to_use_the_sync_flag.patch
Mojo: Disable sync call interrupts in the browser
This changes the default Mojo sync call behavior in the browser process
to prevent any blocking sync calls from being interrupted by other
incoming sync IPC dispatches.
(cherry picked from [commit b6f921260e0e763db7a72de9c7a3f0f78a99f21f](https://chromium-review.googlesource.com/q/commit:b6f921260e0e763db7a72de9c7a3f0f78a99f21f))
Bug: [1376099](https://bugs.chromium.org/p/chromium/issues/detail?id=1376099)
Change-Id: [I53681ef379fdd3c2bfc37d7e16b3de17acad5d20](https://chromium-review.googlesource.com/q/I53681ef379fdd3c2bfc37d7e16b3de17acad5d20)
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3989408
Commit-Queue: Ken Rockot <[rockot@google.com](mailto:rockot@google.com)>
Reviewed-by: Daniel Cheng …
=> chore: cherry-pick 0d4862e31aca and c4e7fe2f2e1b from chromium

patches/chromium/.patches, patches/chromium/cherry-pick-77208afba04d.patch
Make WidgetBase::BeginMainFrame resilient to disposed 'this'
This patch makes sure that WidgetBase::BeginMainFrame can finish
execution even if processing the RAF-throttled handlers
(DispatchRafAlignedInput) destroys 'this' instance.
(cherry picked from commit af6e22c14bec7ad64115b24ece6d423f144214ca)
Bug: chromium:1381871
Change-Id: I81aa4ba697f80f8666bb2a3b5542cac210b1efa9
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4030809
Reviewed-by: Dave Tapuska <dtapuska@chromium.org>
Commit-Queue: Jaroslav Sevcik <jarin@chromium.org>
Cr-Original-Commit-Position: refs/heads/main@{#1072864}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4068023
Auto-Submit: Jaroslav Sevcik <jarin@chromium.org>
Commit-Queue: Dave Tapuska <dtapuska@chromium.org> …
=> chore: cherry-pick 77208afba04d from chromium

lib/browser/api/net.ts, shell/browser/api/electron_api_url_loader.cc, spec/api-net-spec.ts, typings/internal-ambient.d.ts
Chrome's parsed headers contain everything except the cookies ([ref](https://source.chromium.org/chromium/chromium/src/+/main:services/network/public/cpp/net_ipc_param_traits.cc;l=190;drc=098756533733ea50b2dcb1c40d9a9e18d49febbe)), so use those and add in the set-cookie header at the end.
Closes #27895.
Notes: Fixed net.request response headers missing `Content-Type`.
=> fix: use chrome headers in net.request for everything except cookie

docs/development/build-instructions-windows.md
=> docs: update visual studio min version

docs/api/session.md
A couple of rogue backticks snuck into `docs/api/session.md`. Interestingly wasn't affecting rendering due to where they were located. Cleaned them up and made more consistent use of inline code for function names in those sections.
Note to future self, would be nice if these could be caught by a `markdownlint` rule.
Notes: none
=> docs: cleanup some rogue backticks

patches/angle/.patches, patches/angle/fix_rename_webswapcgllayer_to_webswapcgllayerchromium.patch, patches/config.json
Fixes #33685
This was being fixed in ANGLE https://chromium-review.googlesource.com/c/angle/angle/+/3062212
But now again both WebKit and Chromium have the duplicate symbol as they both use ANGLE
Notes: Fixed warning about duplicate `WebSwapCGLLayer` symbols when Electron starts on macOS.
=> fix: rename WebSwapCGLLayer to WebSwapCGLLayerChromium

shell/browser/ui/message_box_mac.mm
Closes https://github.com/electron/electron/issues/36721.
We shouldn't manually highlight the default button unless there's a cancel button with respective `cancelId`. macOS automatically infers default button highlighting and changing that affects focus ring behavior and appearance.
</details>
</details>
Tested with https://gist.github.com/d9bd650ffc1efcf61016cbc81ea35652.
There's also another issue here with key equivalent accessibility, but i'm going to look into that as a follow-up.
Notes: Fixed an issue with incorrect focus ring highlighting when using `dialog.showMessageBox()`.
=> fix: focus rings with multiple buttons in `showMessageBox`

patches/chromium/feat_expose_raw_response_headers_from_urlloader.patch, shell/browser/api/electron_api_url_loader.cc
This moves the report_raw_headers parameter to the TrustedParams struct inside
URLRequest.
Notes: none
=> fix: move report_raw_headers to TrustedParams

shell/browser/ui/drag_util_mac.mm, shell/browser/ui/drag_util_views.cc
Refs CL:4116595. Minor updates to `drag_util` logic to better match upstream.
Notes: none.
=> chore: cleanup `drag_util`

lib/asar/fs-wrapper.ts, spec/asar-spec.ts
Fixes https://github.com/isaacs/node-graceful-fs/issues/223 in Electron. I also have a PR on that repo to improve their behavior (which would also fix the issue), so I'm fixing it from all angles.
This moves `fs.readdir` slightly closer to the typings from Node, but there's still other issues (`options` could be a string). I plan on doing a more general improvement PR to fix up behavior in `lib/asar/fs-wrapper.ts`.
Notes: Fixed an error when fs.readdir gets null for options
=> fix: handle null/undefined options for fs.readdir

shell/browser/browser.h, shell/browser/browser_mac.mm, shell/browser/electron_browser_main_parts.cc
Closes https://github.com/electron/electron/issues/36539.
Fixes an issue where custom traffic lights wouldn't properly respect an application's locale setting if it differed from the system setting and had a different directionality. This was happening because macOS native elements set their origin and axis based upon the system locale RTL setting, and so even when we took RTL into account in `WindowButtonsProxy` it would still be incorrect. To fix this, we set Apple app-level defaults to force RTL or LTR if it differs from the system locale. This PR also adds support for `--force-ui-direction` similar to CL:956297
Tested with https://gist.github.com/8dc6c09539222ee3ad86146123982011, using an English system locale setting.
</details> …
=> fix: RTL `WindowButtonsProxy` buttons

patches/chromium/short-circuit_permissions_checks_in_mediastreamdevicescontroller.patch, shell/browser/web_contents_permission_helper.cc, spec/api-session-spec.ts
Closes https://github.com/electron/electron/issues/36629.
Refs https://github.com/electron/electron/pull/34895.
Fixes an issue where the `setPermissionRequestHandler` callback would be invoked twice when using `navigator.getUserMedia(...)`. This was happening because we didn't fully short-circuit all of the permission checks in `MediaStreamDevicesController` When a user called `getUserMedia`, Electron first does its own permissions check through `RequestMediaAccessPermission`, which resulted in the first callback being invoked. Then, when `MediaStreamDevicesController::RequestPermissions` was called, it would fall down to [this line](https://source.chromium.org/chromium/chromium/src/+/main:components/webrtc/media_stream_devices_controller.cc;l=161-167?q=%22t%20is%20OK%20to%20ignore%20%60re …
=> fix: `getUserMedia` duplicate permissions call

patches/v8/.patches, patches/v8/cherry-pick-28b9c1c04e78.patch
Merged: [arm] Do not emit the constant pool before a branch
After computing the branch offset but before emitting the actual branch,
we should not emit a constant pool. Otherwise the previously computed
offset would be off.
Instead of handling this indirectly via the Assembler::branch_offset
method, do this directly in the Assembler::b method (and friends), so it
is not missed on other call sites.
R=nicohartmann@chromium.org
(cherry picked from commit 9be597d194e108ba718610b9a611fe19a0fbfde5)
Bug: chromium:1399424
Change-Id: Ie30ba70508b4fb8913f79e049a33108608915704
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/4118864 …
=> chore: cherry-pick 28b9c1c04e78 from v8

.markdownlint.json, docs/api/command-line-switches.md, docs/api/debugger.md, docs/api/menu-item.md, docs/faq.md, docs/glossary.md, docs/tutorial/code-signing.md, docs/tutorial/performance.md, docs/tutorial/process-model.md, docs/tutorial/sandbox.md, docs/tutorial/tutorial-1-prerequisites.md, docs/tutorial/tutorial-2-first-app.md, docs/tutorial/tutorial-3-preload.md, docs/tutorial/tutorial-4-adding-features.md, docs/tutorial/window-customization.md
Cleans up unused and duplicate reference link definitions, and switches on the `markdownlint` rule to check them. The change in `docs/api/menu-item.md` fixes a rogue backtick which was causing a false positive with the linting rule - shouldn't have any effect on rendering.
Notes: none
=> docs: cleanup reference links

patches/v8/.patches, patches/v8/cherry-pick-0f481c9ddf2a.patch
Merged: [wasm][turbofan] Load 32-bit values more efficiently
When loading a 32-bit value from the stack, just load 32 bit and
zero-extend them into the target register, instead of loading the full
64 bits.
As there are things to fix (see https://crbug.com/1356461), we only
enable this optimization for Wasm for now.
Also include the related fix https://crrev.com/c/4096985.
R=mslekova@chromium.org
(cherry picked from commit 2ee52447c878721c89a55a780eb689ecba6817d3)
(cherry picked from commit a38209949fcbf045231c316e2d790b8b70ccb7ef)
Bug: chromium:1395604
Change-Id: I54a2182ada6fadbfcf5565f0dc8d4f477ecff393
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/4110897
Reviewed-by: Maya Lekova <mslekova@chromium.org> …
=> chore: cherry-pick 0f481c9ddf2a from v8

patches/chromium/.patches, patches/chromium/cherry-pick-43637378b14e.patch
Align NetworkContext::SetNetworkConditions better with devtools emulateNetworkConditions
The former used values of 0 to disable particular throttles, while the
later documents -1, and looks to be pretty much a direct client, and the
only one. So make NetworkService handle everything <= 0 as a disable,
clamping at intake of config.
Bug: 1382033
(cherry picked from commit ce463c2c939818a12bbcec5e2c91c35f2a0a1f0e)
Change-Id: I2fd3f075d5071cb0cf647838782115b5c00405bf
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4035891
Reviewed-by: Ken Buchanan <kenrb@chromium.org>
Reviewed-by: Eric Orth <ericorth@chromium.org>
Commit-Queue: Maks Orlovich <morlovich@chromium.org>
Cr-Original-Commit-Position: refs/heads/main@{#1073566}
Reviewed-on: …
=> chore: cherry-pick 43637378b14e from chromium

script/lib/utils.js, script/release/notes/index.js, script/release/publish-to-npm.js, script/release/version-utils.js
The main migration has been complete for some time, and so there are no longer any branches which might release off of master. Address TODOs and simplify code accordingly. There also aren't any branches that should take the `1-x-y` format any longer, so simplify that as well.
Notes: none
=> build: remove older branch migration helpers

.github/workflows/update_appveyor_image.yml, appveyor.yml
This PR bumps AppVeyor's image to e-111.0.5518.0 (latest), and fixes an issue with the GH actions token that prevent the PR for the image bump from being auto-created.
Notes: none
=> build: bump appveyor to e-111.0.5518.0

shell/browser/native_window_mac.mm
Closes https://github.com/electron/electron/issues/33503.
Refs https://github.com/electron/electron/pull/25470.
Fixes an issue on macOS when trying to switch processes with `Cmd+Tab` after exiting Kiosk Mode. We need to ensure that presentation options are reset _after_ exiting fullscreen, otherwise the fullscreen action takes precedence and causes them to improperly be reset.
Tested with https://gist.github.com/40902920c8fb6c0e2ebcd8fdb936cbf6.
Notes: Fixes an issue on macOS when trying to switch processes with `Cmd+Tab` after exiting Kiosk Mode.
=> fix: Cmd+Tab not working when exiting kiosk mode

.github/workflows/scorecards.yml
Bumping to the same versions as used [in `ossf/scorecard-action`'s own `scorecards.yml`](https://github.com/ossf/scorecard-action/blob/d6a6d2fa4e7cf79661fdc9ffa7aa332fe18e8faf/.github/workflows/scorecards.yml) in order to clear deprecation warnings for the action runs.
Notes: none
=> ci: update pinned versions for security scorecard workflow

patches/v8/.patches, patches/v8/cherry-pick-c79148742421.patch
Merged: Reland "[Promise.any] Fix errors allocation"
Bug: chromium:1379054
(cherry picked from commit 8b35091b2d244c975975e1c78e4cd09cb479b5dc)
Change-Id: Iec8f8bb51f4434d6ae86887cf742f2883a9b7bef
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/4004804
Cr-Commit-Position: refs/branch-heads/10.8@{#34}
Cr-Branched-From: f1bc03fd6b4c201abd9f0fd9d51fb989150f97b9-refs/heads/10.8.168@{#1}
Cr-Branched-From: 237de893e1c0a0628a57d0f5797483d3add7f005-refs/heads/main@{#83672}
Ref electron/security#252
Notes: Security: backported fix for CVE-2022-4174.
=> chore: [20-x-y] cherry-pick c79148742421 from v8

docs/api/structures/display.md, shell/common/gin_converters/gfx_converter.cc, spec/api-screen-spec.ts
Fix #36826. Implemented in Chromium by:
- [3646632: Plumb through display labels and add initial mac (>=10.15) implementation.](https://chromium-review.googlesource.com/c/chromium/src/+/3646632)
- [3697197: Add EDID labels for displays on Windows platform.](https://chromium-review.googlesource.com/c/chromium/src/+/3697197)
Notes: Added `label` property to `Display` objects.
=> feat: add label property to Display objects

shell/browser/api/electron_api_web_contents.cc
Closes https://github.com/electron/electron/issues/36417.
Fixes an issue where webview background color would not correctly be set on reload. This was happening as a result of https://github.com/electron/electron/pull/33435, where I fixed an issue with _missing_ transparency but made it such that when `webPreferences` had no color stored the initial background color would be set to white. Instead, we need to explicitly set guest webContents background color to transparent when `webPreferences` has no color stored.
Tested with https://gist.github.com/PerfectPan/100900b7758293b8f72b23d0babdb1cc and confirmed not to regress https://github.com/electron/electron/issues/33374
Notes: Fixed an issue where `webView`s could have an incorrect initial background color following reloads.
=> fix: webview background color on reload

package.json, script/spec-runner.js, yarn.lock
Makes use of `@electron/fiddle-core` to enable running tests against a released version of Electron. This makes it so you can run the Electron tests with just a traditional `git clone` of the repo rather than needing to set up a full working build of Electron. Should significantly lower the barrier to running the tests on a system. (With any caveats about `release` builds vs `testing` builds).
Will allow a flow like this to work (assume this PR is already landed in this example):
```sh
$ git clone https://github.com/electron/electron.git
$ cd electron
$ git checkout v22.0.1
$ yarn install
$ yarn test --electronVersion 22.0.1
```
Notes: none
=> test: support running tests against Electron releases

shell/browser/ui/autofill_popup.cc
Closes https://github.com/electron/electron/issues/36906.
Refs https://github.com/electron/electron/pull/35628.
Fixes an issue where `<datalist>` elements were improperly positioned within the page. We had copied several helper functions out of `chrome/browser/ui/views/autofill/autofill_popup_view_utils.cc` and were using `CalculatePopupXAndWidthHorizontallyCentered` after having called `CalculatePopupBounds`. `CalculatePopupBounds` itself calls `CalculatePopupXAndWidthHorizontallyCentered`, so there's no need to do it twice.
Tested with https://gist.github.com/e50cb256d567ed25b7bbf12b9cbe5417.
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
Notes: Fixed an issue where `<datalist>` elements were improperly positioned within the page.
=> fix: `<datalist>` dropdown positioning

docs/api/app.md
Added "or WOW" to display the use of Windows as a possible scenario.
Changed the wording of that same sentence in `app.runningUnderARM64Translation` to make it appear clearer. Replaced "incorrectly" with "mistakenly" and moved this word to before the verb instead of the end of the sentence.
Notes: none
=> docs: Change factuality and word choice in app.runningUnderARM64Translation

spec/api-native-theme-spec.ts
Fixed a test which is supposed to trigger a change to `nativeTheme.themeSource`, but would only happen if the system was in light mode. If the system was in dark mode, the test would not trigger a change since it set `nativeTheme.themeSource` to "dark" initially. I've updated the test to first set `nativeTheme.themeSource` to "light" before then changing it to "dark" to ensure a change is triggered regardless of the system theme.
Notes: none
=> test: fix nativeTheme test when system in dark mode

.github/workflows/stale.yml
By default the jobs in a workflow run in parallel which leaves open the small possibility that both jobs will act on the same issue like what happened in https://github.com/electron/electron/issues/34930 - although that one was a result of the workflow resuming after not having run for a while so both criteria were met, which they wouldn't normally be under normal circumstances.
Still, let's rule out the possibility, in case we add more jobs to the workflow going forward. `if: ${{ always() }}` ensures the job runs even if the job it depends on fails.
Notes: none
=> ci: don't run stale workflow jobs in parallel

shell/renderer/electron_autofill_agent.cc, shell/renderer/electron_autofill_agent.h
Cleanup `AutofillAgent` shutdown sequence to better match [upstream](components/autofill/content/renderer/autofill_agent.h). Also stylistically modernize `ShowSuggestionsOptions` to better match upstream.
Notes: none
=> chore: cleanup autofill agent shutdown sequence

shell/app/electron_main_delegate_mac.mm, shell/browser/electron_browser_client.cc, shell/common/mac/main_application_bundle.mm
Refs https://bugs.chromium.org/p/chromium/issues/detail?id=1342679
Plugin helper executable has use cases outside the plugin architecture of chromium to allow loading third-party unsigned libraries. We also leverage this capability in the [UtilityProcess API](https://github.com/electron/electron/blob/main/docs/api/utility-process.md#utilityprocessforkmodulepath-args-options)
`enable_plugins` is already on track for deletion in [upstream](https://bugs.chromium.org/p/chromium/issues/detail?id=702990) so they have made this executable [not conditional](https://chromium-review.googlesource.com/c/chromium/src/+/3751458) on that flag, the PR aligns to do the same in Electron. You can also refer to the linked issue as to why the executable has not been renamed.
/cc @miniak FYI
Notes: Remove …
=> fix: make plugin helper executable unconditional

shell/app/electron_content_client.cc
Refs CL:3837314. Small cleanup and inlining of `ComputeBuiltinPlugins`.
Notes: none
=> chore: cleanup `ElectronContentClient::AddPlugins`

shell/browser/file_select_helper.cc
Refs CL:4117255. From the CL:
> The contract of the SelectFileDialog API specifies that
ListenerDestroyed() must be invoked whenever you no longer want the
listener to be called back by the dialog.
Also tweaks a few other small things to ensure ongoing parity with `chrome/browser/file_select_helper.h`.
Notes: none.
=> chore: call `ListenerDestroyed()` in `FileSelectHelper::RunFileChooserEnd()`

patches/node/fix_expose_the_built-in_electron_module_via_the_esm_loader.patch
Fixes #36970
Notes: ESM loads of CJS modules that have `null` exports no longer throw
=> fix: do not error on null exports in ESM loader

script/generate-config-gypi.py
Enable whole-program optimization by default in script that generates config.gypi needed for electron native modules.
Related work item: #36936 
Notes: Whole-program optimization is enabled by default in electron node headers config file.
=> feat: enable whole-program optimization native modules by default

shell/browser/electron_browser_client.cc, shell/browser/electron_browser_client.h
This was originally added in https://github.com/electron/electron/pull/18483#discussion_r290876282 since we were initializing crashpad clients in the child process after sandbox was setup but we since then refactored crashpad initialization and now we initialize it before [sandbox is setup](https://github.com/electron/electron/blob/ca3145a54716d864c2487f239f6ebd44989bb7ff/shell/app/electron_main_delegate.cc#L361-L369), making this rule not necessary.
Notes: none
=> chore: remove crashpad related sandbox policy

patches/node/fixup_for_wc_98-compat-extra-semi.patch, patches/node/support_v8_sandboxed_pointers.patch, script/node-disabled-tests.json
Refs https://github.com/nodejs/node/pull/42695/commits/74a59561b0327c3631cfab76b8888c8bb158aade
Fixes a memory leak in `v8.serialize()` resultant of gc not being able to run properly. I implemented a modified version of [this approach](https://github.com/nodejs/node/pull/42695#issuecomment-1097901256) to be compatible with sandboxed pointers.
Result of `parallel/test-v8-serialize-leak`:
Before this change:
* `before=85573632 after=4512022528` - **52.7x** increased memory usage
After this change
* `before=85524480 after=189775872` -  **2.2x** increased memory usage
Notes: Fixed a memory leak in `v8.serialize()` when running Node.js within Electron.
=> chore: fix memory leak in `v8.serialize()`

patches/chromium/.patches, patches/chromium/cherry-pick-57c54ae221d6.patch
Ensure clean destruction of network::WebTransport
Once the destruction of the object begins, we should not process any
callbacks, nor should we attempt to reset the streams on a connection
that is already being closed.
Bug: 1376354
Change-Id: Ib49e0ce0b177062cccd0e52368782e291cf8166c
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4117501
Reviewed-by: Eric Orth <ericorth@chromium.org>
Commit-Queue: Victor Vasiliev <vasilvv@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1085965}
Ref electron/security#269
Notes: Security: backported fix for CVE-2023-0471.
=> chore: cherry-pick 57c54ae221d6 from chromium

docs/api/web-contents.md, docs/api/webview-tag.md, lib/browser/web-view-events.ts, shell/browser/api/electron_api_web_contents.cc, shell/browser/api/electron_api_web_contents.h, shell/browser/ui/inspectable_web_contents.cc, shell/browser/ui/inspectable_web_contents_delegate.h
Closes https://github.com/electron/electron/issues/36715.
This PR adds a new event `devtools-open-url` corresponding to a link in DevTools being either clicked or selected for opening in a new tab via context menu. There is precedent for event emission corresponding to `DevToolsEmbedderMessageDispatcher::Delegate` methods - this was previously a no-op and so the primary change here is adding an implementation to surface the action to developers.
Alternatively, we could potentially have implemented the new window behavior ourselves, but this is (imo) a large security hole and as such I believe we should ibstead give developers more fine-grained control over handling and optionally opening new links there.
Tested by adding:
```js
mainWindow.loadURL('https://www.baidu.com/') …
```
=> feat: emit `devtools-open-url` event for DevTools link selection

shell/browser/api/electron_api_system_preferences_mac.mm
If you have an Apple laptop in clamshell mode (lid is closed) and you don't have an Apple Keyboard with TouchID, `LAPolicyDeviceOwnerAuthenticationWithBiometrics` policy cannot be evaluated, and `CanPromptTouchID` returns false even if you have an Apple Watch capable of unlocking the laptop. This new policy is mirroring macOS behavior.
Notes: `SystemPreferences::CanPromptTouchID` (macOS) now supports Apple Watch
=> feat: add support for unlocking with Apple Watch

shell/browser/native_window.cc, shell/browser/native_window_views.cc
Closes https://github.com/electron/electron/issues/37008.
Refs https://github.com/electron/electron/pull/36230.
The above refactor improved draggable regions by typing them most closely to WebContents, but introduced an issue whereby draggable regions could take precedence over resizing borders on Windows. This was happening as a result of `NativeWindow::NonClientHitTest`, which returned the first non-HTNOWHERE value it found. This meant that the window's border coordinates would not take appropriate precedence, and instead of `HTBOTTOM`, `HTLEFT`, etc being returned for the window edge coordinates, `HTCAPTION` would instead be returned and the window bordered rendered useless. We fix this by first checking `ResizingBorderHitTest` results in `NativeWindow::NonClientHitTest` and proceeding …
=> fix: resizing borders in nondraggable regions

.circleci/config/base.yml, appveyor-woa.yml, appveyor.yml
Due to recent changes in depot_tools/ninja we need to explictly include ninja from src/third_party/ninja in the path.
Additionally this adds logic to our appveyor builds to ensure that multiple builds don't run per commit.
Notes: none
=> ci: ensure correct ninja is used

patches/chromium/.patches, patches/chromium/cherry-pick-ca2b108a0f1f.patch
[Merge M110] Delete PeerConnectionHandler in PeerConnection finalizer
Also guard against removal of PC during PeerConnectionHandler
call that may cause garbage collection.
(cherry picked from commit 5066dd66309d884762e5fb9be04b59582893d09a)
Bug: chromium:1405256
Change-Id: I9adf7b219e2026e07ccc0868c1a85f3b35cd9d26
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4154578
Commit-Queue: Guido Urdaneta <guidou@chromium.org>
Cr-Original-Commit-Position: refs/heads/main@{#1091801}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4176372
Auto-Submit: Harald Alvestrand <hta@chromium.org>
Cr-Commit-Position: refs/branch-heads/5481@{#418} …
=> chore: cherry-pick ca2b108a0f1f from chromium

patches/chromium/printing.patch
Closes https://github.com/electron/electron/issues/37049.
Refs CL:3958034
Fixed a crash caused by an uninitialized pref. 
Notes: Fixed a printing crash caused by an uninitialized pref.
=> fix: crash on `window.print()`

shell/renderer/electron_renderer_client.cc, shell/renderer/web_worker_observer.cc, shell/renderer/web_worker_observer.h, spec/fixtures/crash-cases/worker-multiple-destroy/index.html, spec/fixtures/crash-cases/worker-multiple-destroy/index.js, spec/fixtures/crash-cases/worker-multiple-destroy/worklet.js
Closes https://github.com/electron/electron/issues/37038.
It can be the case that `WorkerScriptReadyForEvaluationOnWorkerThread` is called multiple times on the same RendererClient, leading to a situation where `WorkerScriptReadyForEvaluation` is called again on a previously-created `WebWorkerObserver`, but a new context. When the context is finally destroyed and the observer cleaned up, we then see a crash when closing handles in the event loop. We can fix this by ensuring that each new call to `WorkerScriptReadyForEvaluationOnWorkerThread` creates a new observer. To my understanding, it _should_ be the case that there can be multiple Workers/Worklets per renderer process, so we shouldn't destroy previous ones before creating new ones.
Notes: Fixed a potential crash in some types of …
=> fix: crash on `WebWorkerObserver` script execution

script/lint.js
Use this pattern
https://github.com/electron/electron/blob/fcc7a869f218059d0de22db1ea3d63c2e9c192ce/script/lint.js#L78-L80
Instead of duplicating the code
https://github.com/electron/electron/blob/fcc7a869f218059d0de22db1ea3d63c2e9c192ce/script/lint.js#L89-L93
Notes: none
=> refactor: simplify script/lint.js

.github/workflows/stale.yml
Updates `actions/stale` in `stale.yml` from v6.0.0 to v6.0.1. Should clear the deprecation warning about `set-output` on the workflow runs.
Notes: none
=> ci: update actions/stale to v6.0.1

script/node-spec-runner.js
Fixes an issue where smoke test validation incorrectly ignored `.mjs` files.
Before:
```
electron on git:check-mjs-too ❯ node script/node-spec-runner.js --validateDisabled
Found 1 missing disabled specs:
parallel/test-fetch
electron on git:check-mjs-too ❯
```
After:
```
electron on git:check-mjs-too ❯ node script/node-spec-runner.js --validateDisabled
electron on git:check-mjs-too ❯
```
Notes: none
=> chore: validate `.mjs` spec files in Node.js smoke tests

package.json, yarn.lock
None of the audit warnings have any impact on us realistically, but the number not being 0 was annoying me constantly on every `git push` 🙃 
Notes: none
=> build: bump deps to clean up yarn audit

.github/workflows/release_dependency_versions.yml
Closes https://github.com/electron/electron/issues/37028.
Fixes up the regexes for new Chromedriver and mksnapshot releases to correspond to major, minor, and patch releases only. Also removes the read-only permissioning.
Notes: none
=> build: fixup release_dependency_versions action

lib/worker/init.ts
When 'nodeIntegrationInWorker: true', worker_init is loaded in worker scopes.
That script assumed that `self` was always available, which isn't the case in
AudioWorkletGlobalScope.
Found while investigating https://github.com/electron/electron/issues/37038, but this does not address that issue.
Notes: Fixed audio worklet scripts failing to run when `nodeIntegrationInWorker: true`.
=> fix: nodeIntegrationInWorker fails to boot in AudioWorklets

docs/api/session.md
It was removed in https://github.com/electron/electron/commit/bd10b19b0cdc46cdbadb570af89305e64541b679#diff-f8e925ef3d92ba436cccb0dde7392b784e2f5ecdee8a0156f68c4017e733eb39
Notes: Remove `appcache` storage type from `session.clearStorageData` supported storages.
=> docs: remove invalid appcache value from storages in clearStorageData()

docs/development/debugging-with-symbol-server.md
The docs website is including the trailing period in the link in the rendered HTML. Use the angle brackets automatic link syntax in Markdown to make it explicit what the link is.
Notes: none
=> docs: use automatic link syntax for symbol server link

appveyor-woa.yml, appveyor.yml, script/release/uploaders/upload.py, script/strip-binaries.py, script/zip-symbols.py
To my knowledge we don't build it and it hasn't worked in years.
Notes: none
=> build: remove `mips64el` build config

docs/api/browser-window.md, docs/api/global-shortcut.md
Just some narrowing I noticed could be done in passing
=> docs: improve globalShortcut and hookWindowMessage types

script/release/uploaders/upload.py
Fixes issue caused by #37093 where we stopped uploading symbols
=> build: actually upload symbol zips

spec/api-app-spec.ts, spec/index.js, spec/package.json, spec/yarn.lock
This updates `mocha` as we needed to to fix some `audit` output.  As part of this I enabled the new-and-improved global "retries" API which automatically reruns failed tests N times to ensure it's not flaky.
=> build: update mocha for retries and audit fix

package.json, spec/api-crash-reporter-spec.ts, spec/package.json, spec/yarn.lock, yarn.lock
As in title, the `dbus-native` package is a bit behind on everything and we don't actually use the cli part so I just force resolved a newer minimist version
Notes: none
=> build: update spec dependencies to clean up yarn audit

shell/browser/mac/electron_application.mm
c.f. https://chromium-review.googlesource.com/c/chromium/src/+/2680102
Notes: Basic accessibility support is now enabled when macOS Voice Control is activated to allow for full voice control of Electron applications
=> fix: enable basic a11y when voice control is active

docs/api/web-contents.md, shell/browser/api/electron_api_web_contents.cc, shell/browser/api/electron_api_web_contents.h, spec/api-browser-view-spec.ts, spec/api-browser-window-spec.ts
Follow-up to #35710. This is already documented:
- [Removed: webContents.incrementCapturerCount(stayHidden, stayAwake)](https://github.com/electron/electron/blob/main/docs/breaking-changes.md#removed-webcontentsincrementcapturercountstayhidden-stayawake)
- [Removed: webContents.decrementCapturerCount(stayHidden, stayAwake)](https://github.com/electron/electron/blob/main/docs/breaking-changes.md#removed-webcontentsdecrementcapturercountstayhidden-stayawake)
Notes: The deprecated `incrementCapturerCount()` / `decrementCapturerCount()` methods have been removed.
=> chore: remove deprecated capturer count APIs

shell/browser/api/electron_api_browser_view.cc, shell/browser/api/electron_api_browser_view.h, shell/browser/api/electron_api_menu.cc, shell/browser/api/electron_api_menu.h, shell/browser/api/electron_api_notification.cc, shell/browser/api/electron_api_notification.h, shell/browser/api/electron_api_tray.cc, shell/browser/api/electron_api_tray.h, shell/browser/api/electron_api_web_contents.cc, shell/browser/api/electron_api_web_contents.h, shell/browser/api/electron_api_web_frame_main.cc, shell/browser/api/electron_api_web_frame_main.h, shell/common/gin_helper/constructible.h, spec/api-web-frame-main-spec.ts, spec/chromium-spec.ts
This makes it so that gin::Wrappable clases that mix in
gin_helper::Constructible have their class methods on the object's prototype,
instead of on the object itself.
Notes: none
=> refactor: move gin_helper::Constructible methods to prototype

.github/workflows/release_dependency_versions.yml
Turns out `\d` [isn't supported in POSIX regexes](https://en.wikipedia.org/wiki/Regular_expression#Character_classes) - could use `[:digit:]` but personally I just prefer `[0-9]` here.
Example of skipped dependencies for `v23.0.0`: https://github.com/electron/electron/actions/runs/4109277828/jobs/7090932840
Notes: none
=> build: fix version check in release_dependency_versions.yml

docs/development/creating-api.md, shell/common/node_bindings.cc, spec/internal-spec.ts
For example running `process._linkedBinding('electron_browser_app')` in the renderer process would crash the process before. Now we get an error, which is more appropriate.
```
node:internal/bootstrap/loaders:158 Uncaught Error: No such module was linked: electron_browser_app
at process._linkedBinding (node:internal/bootstrap/loaders:158:34)
at <anonymous>:1:9
```
Notes: none
=> fix: expose native bindings by process type

docs/api/push-notifications.md
The types were incorrect in the initial commit; they excluded the initial `event` argument.
Notes: none
=> fix: type for received-apns-notification event

patches/chromium/.patches, patches/chromium/cherry-pick-e545559df538.patch
Ensure clean destruction of network::WebTransport
Once the destruction of the object begins, we should not process any
callbacks, nor should we attempt to reset the streams on a connection
that is already being closed.
(cherry picked from commit 57c54ae221d60e9f9394d7ee69634d66c9cd26f3)
Bug: 1376354
Change-Id: Ib49e0ce0b177062cccd0e52368782e291cf8166c
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4117501
Reviewed-by: Eric Orth <ericorth@chromium.org>
Commit-Queue: Victor Vasiliev <vasilvv@chromium.org>
Cr-Original-Commit-Position: refs/heads/main@{#1085965}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4139783
Reviewed-by: Kenichi Ishibashi <bashi@chromium.org>
Cr-Commit-Position: refs/branch-heads/5359@{#1326} …
=> chore: cherry-pick e545559df538 from chromium

patches/chromium/.patches, patches/chromium/cherry-pick-d652130c4bc2.patch
Remove NUM_COMMAND_BUFFER_NAMESPACES from SyncToken.mojom
Mojo validates input for allowed values, NUM_COMMAND_BUFFER_NAMESPACES
is not valid value to send over ipc and is used only to know maximum
value in code.
Bug: 1406115
Change-Id: I8e5c3b6b2a9a9206fbeb377b27ceb1242a4f54e2
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4167409
Reviewed-by: danakj <danakj@chromium.org>
Commit-Queue: Vasiliy Telezhnikov <vasilyt@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1093100}
Ref: https://github.com/electron/security/issues/273
Notes: Security: backported fix for 1406115.
=> chore: cherry-pick d652130c4bc2 from chromium

docs/tutorial/tutorial-1-prerequisites.md
`electron/releases` has been deprecated, so point folks at `releases.json`.
Notes: none
=> docs: remove reference to electron/releases

patches/node/fix_crypto_tests_to_run_with_bssl.patch
Refs https://boringssl-review.googlesource.com/c/boringssl/+/52829.
These tests can be run successfully now.
Notes: none
=> test: Node.js hkdf tests work now

spec/chromium-spec.ts
With retries in mocha only the `beforeEach` is re-run, we were shutting down the localhost server in an `afterEach` but setting it up in a `before`.  This moves the logic to a `beforeEach` and avoids a race condition where the server isn't listening when the test runs.
=> test: ensure fullscreen test is retryable

lib/browser/api/web-contents.ts
This event is undocumented and unused since 77297f37a3df4e430e2627accdaa1c9235684a08. It was added at the dawn of time but was never documented.
Notes: none
=> chore: remove load-url event

appveyor-bake.yml, appveyor-woa.yml, appveyor.yml, script/prepare-appveyor.js
Updates the Appveyor image to a newly baked image with the latest Appveyor build agent.  This should hopefully resolve some of the hanging we have recently seen on Appveyor jobs.  Additionally, this restores console output during Appveyor runs (previously it would stop updating the Appveyor UI).
Notes: none
=> ci: update appveyor build agent

appveyor-bake.yml, appveyor-woa.yml, appveyor.yml, script/prepare-appveyor.js
Updates the Appveyor image to a newly baked image with the latest Appveyor build agent.  This should hopefully resolve some of the hanging we have recently seen on Appveyor jobs.  Additionally, this restores console output during Appveyor runs (previously it would stop updating the Appveyor UI).
This is a manual backport of #37211.
Notes: none
=> ci: update appveyor image (23-x-y)

appveyor-bake.yml, appveyor-woa.yml, appveyor.yml, script/prepare-appveyor.js
Updates the Appveyor image to a newly baked image with the latest Appveyor build agent.  This should hopefully resolve some of the hanging we have recently seen on Appveyor jobs.  Additionally, this restores console output during Appveyor runs (previously it would stop updating the Appveyor UI).
This is a manual backport of #37211.
Notes: none
=> ci: update appveyor image (22-x-y)

appveyor-bake.yml, appveyor-woa.yml, appveyor.yml, script/prepare-appveyor.js
Updates the Appveyor image to a newly baked image with the latest Appveyor build agent.  This should hopefully resolve some of the hanging we have recently seen on Appveyor jobs.  Additionally, this restores console output during Appveyor runs (previously it would stop updating the Appveyor UI).
This is a manual backport of #37211.
Notes: none
=> ci: update appveyor image (21-x-y)

docs/api/browser-window.md, docs/api/webview-tag.md, docs/development/chromium-development.md, shell/utility/electron_content_utility_client.cc, spec/api-dialog-spec.ts
https://cs.chromium.org/ was replaced by https://source.chromium.org/
Notes: none
=> chore: update https://cs.chromium.org/ links to https://source.chromium.org/

appveyor-bake.yml, appveyor.yml, script/prepare-appveyor.js, script/setup-win-for-dev.bat
Recent Node patches have introduced a bug where uploading artifacts will hit this Node bug: https://github.com/nodejs/node/issues/46221 
This PR bakes a new image that uses Node v18.12.1, to avoid this bug while we find a solution to the duplex error.
Notes: none
=> build: bake node v18.12.1 Appveyor image

docs/api/shell.md, shell/common/api/electron_api_shell.cc, shell/common/platform_util.h, shell/common/platform_util_win.cc
Allow passing the `SEE_MASK_FLAG_LOG_USAGE` flag to `ShellExecuteEx` on Windows.
Notes: Added `logUsage` to `shell.openExternal()` options, which allows passing the `SEE_MASK_FLAG_LOG_USAGE` flag to `ShellExecuteEx` on Windows.
=> feat: add logUsage to shell.openExternal() options

shell/app/node_main.cc
Take advantage of Node.js-provided helper function to spin uv loop found [here](https://github.com/nodejs/node/blob/eaca13ddc9092e831b9b45180c6e0ee1f3292e5e/src/api/embed_helpers.cc#L17-L60). Allows us to remove a chunk of code and maintain tighter parity with upstream.
Notes: none
=> refactor: simplify Node.js event loop with `SpinEventLoop`

docs/api/browser-window.md
`BrowserWindow.prototype.isFocusable()` returns a `boolean`, but it wasn't documented.
I think it would also be important to change the `d.ts` file, but I couldn't figure out how.
Notes: none
=> docs: add `win.isFocusable()` return type

docs/api/web-contents.md, lib/browser/api/web-contents.ts
Closes https://github.com/electron/electron/issues/37127. Adds missing standard page sizes.
Notes: Added several standard page size options to `webContents.print()`.
=> feat: include all standard paper sizes for webContents.print()

shell/browser/api/electron_api_browser_window.cc, shell/browser/api/electron_api_web_contents.cc
Closes https://github.com/electron/electron/issues/37162.
Refs https://github.com/electron/electron/pull/35509 & https://github.com/electron/electron/pull/36230
When `Destroy()` is called in `WebContents::CloseContents` instead of `BrowserWindow::OnCloseContents`, this leads to a crash when `beforeunload` is prevented in the renderer process instead and there is at least one BrowserView present. This is owing to the `WebContents` being nullptr in the BrowserView when it is called by `NativeWindow::NonClientHitTest` as a result of clicking the close button. This is fixed by moving the destroy call back to `OnCloseContents` so that BrowserViews are reset properly prior.
Tested with https://gist.github.com/YauheniBH-EF/190ea8ff42c09a15763705ed4647b02e
Notes: Fixed a crash when `BrowserView`s …
=> fix: `BrowserView` crash when 'beforeunload' prevented

script/release/release.js
Octokit's `repos.getLatestRelease` only works on non-draft and non-prerelease builds, so it was returning a 404 error when looking for the latest nightly, since the nightlies repo only contains prereleases. 
This PR modifies the call to only check on non-prerelease builds.
Notes: none
=> build: ignore makeLatest on pre-releases

appveyor-bake.yml, appveyor.yml, script/prepare-appveyor.js, script/setup-win-for-dev.bat
Recent Node patches have introduced a bug where uploading artifacts will hit this Node bug: https://github.com/nodejs/node/issues/46221
This PR bakes a new image that uses Node v18.12.1, to avoid this bug while we find a solution to the duplex error.
Notes: none
=> build: use node 18.12 in AppVeyor (23-x-y)

appveyor-bake.yml, appveyor.yml, script/prepare-appveyor.js, script/setup-win-for-dev.bat
Recent Node patches have introduced a bug where uploading artifacts will hit this Node bug: https://github.com/nodejs/node/issues/46221
This PR bakes a new image that uses Node v18.12.1, to avoid this bug while we find a solution to the duplex error.
Notes: none
=> build: use node18.12 appveyor image (24-x-y)

docs/api/browser-window.md, docs/api/menu-item.md, docs/api/system-preferences.md, docs/api/tray.md, docs/breaking-changes.md
Update wording to assume the minimum supported macOS version is now 10.13 (High Sierra)
https://github.com/electron/electron/blob/17ea7f42fcf71527aef6646fcbc74abbda40db42/BUILD.gn#L40
This happened in #34272, which includes https://chromium-review.googlesource.com/c/chromium/src/+/3646050
Follow-up to #35911
Also add missing entry to breaking changes as this affects Electron 20+
Notes: none
=> docs: only macOS 10.13+ is supported now

appveyor-bake.yml, appveyor.yml, script/prepare-appveyor.js, script/setup-win-for-dev.bat
Recent Node patches have introduced a bug where uploading artifacts will hit this Node bug: https://github.com/nodejs/node/issues/46221
This PR bakes a new image that uses Node v18.12.1, to avoid this bug while we find a solution to the duplex error.
Notes: none
=> build: use node 18.12 in AppVeyor (22-x-y)

spec/api-web-contents-spec.ts, spec/chromium-spec.ts, spec/fixtures/no-proprietary-codecs.js
The old events are deprecated and going to be removed.
Notes: none
=> test: use render-process-gone event in tests

script/release/uploaders/upload.py
Prevent a similar problem as occurred in Sudowoodo yesterday by ensuring warnings are stripped from stdout.
Notes: none
=> build: strip warnings from stdout in `get_release`

spec/api-browser-view-spec.ts, spec/api-browser-window-spec.ts, spec/api-ipc-renderer-spec.ts, spec/api-protocol-spec.ts, spec/api-service-workers-spec.ts, spec/api-web-contents-spec.ts, spec/api-web-request-spec.ts, spec/chromium-spec.ts, spec/fixtures/crash-cases/webcontents-create-leak-exit/index.js, spec/node-spec.ts, typings/internal-electron.d.ts
Improves type safety
Notes: none
=> test: use webContents.create() in type-safe way

spec/crash-spec.ts, spec/modules-spec.ts
Exceptions thrown from failing `expect`s in the "exit" even handler do not reject the enclosing
promise and do not fail the corresponding test. Let's call `expect`s inside
`runFixtureAndEnsureCleanExit` instead to make sure tests tests fail nicely
if something goes wrong.
Notes:  no-notes
=> test: fix "crash cases" tests not failing properly

spec/parse-features-string-spec.ts, spec/process-binding-spec.ts, typings/internal-electron.d.ts
Separate `parse-features-string` internal module tests from `process._linkedBinding` ones.
Notes: none
=> test: rename & split internal module tests

docs/api/browser-window.md, docs/breaking-changes.md, filenames.gni, lib/browser/api/base-window.ts, shell/browser/api/electron_api_base_window.cc, shell/browser/api/electron_api_base_window.h, shell/browser/native_window.h, shell/browser/native_window_mac.h, shell/browser/native_window_mac.mm, shell/common/gin_converters/optional_converter.h, spec/api-browser-window-spec.ts
Close https://github.com/electron/electron/issues/34969.
This PR adds `BrowserWindow.set/getWindowButtonPosition` APIs which mean to replace the `set/getTrafficLightPosition` that:
1. The new API returns `null` instead of `{ x: 0, y: 0 }` when there is no custom position;
2. The new API takes `null` instead of `{ x: 0, y: 0 }` to reset the position;
3. The new names match the naming style of `set/getWindowButtonVisibility` APIs.
Notes: Add BrowserWindow.set/getWindowButtonPosition APIs.
=> feat: add BrowserWindow.set/getWindowButtonPosition APIs

spec/api-browser-window-spec.ts, spec/api-session-spec.ts, spec/api-web-contents-spec.ts, spec/api-web-frame-main-spec.ts, spec/chromium-spec.ts, spec/get-files.ts, spec/modules-spec.ts, spec/node-spec.ts, spec/webview-spec.ts
Use `emittedOnce`, `delay` and custom `waitForEvent(s)` to DRY
Notes: none
=> test: use async helpers to simplify tests

spec/ts-smoke/electron/main.ts, spec/ts-smoke/electron/renderer.ts
Follow-up to #30720. The `desktopCapturer` module is now only available in the main process.
Notes: none
=> test: move desktopCapturer usage from renderer to main in ts-smoke

spec/asar-spec.ts
Just a small improvement for consistency and better diagnostics
```
not ok 108 asar package node api fs.promises.readdir supports withFileTypes
expected false to be true
AssertionError: expected false to be true
at Context.<anonymous> (electron/spec/lib/spec-helpers.ts:191:22)
```
turns into
```
not ok 108 asar package node api fs.promises.readdir supports withFileTypes
expected { Object (name) } to be an instance of Dirent
AssertionError: expected { Object (name) } to be an instance of Dirent
at Context.<anonymous> (electron/spec/lib/spec-helpers.ts:191:22)
```
Notes: none
=> test: use expect(dir).to.be.an.instanceof(fs.Dirent);

patches/webrtc/.patches, patches/webrtc/cherry-pick-e0efbd45ea74.patch
[Merge-110] [Stats] Handle the case of missing certificates.
Certificates being missing is a sign of a bug (e.g. webrtc:14844, to be
fixed separately) which is why we have a DCHECK. But this DCHECK does
not protect against accessing the invalid iterator if it is a release
build. This CL makes that safe.
(cherry picked from commit 124d7c3fe5bdc79a355c9df02d07f25331631a68)
Bug: chromium:1408392
Change-Id: I97a82786028e41c58ef8ef15002c3f959bbec7f1
Reviewed-on: https://webrtc-review.googlesource.com/c/src/+/291109
Reviewed-by: Mirko Bonadei <mbonadei@webrtc.org>
Commit-Queue: Henrik Boström <hbos@webrtc.org>
Cr-Original-Commit-Position: refs/heads/main@{#39159}
Reviewed-on: https://webrtc-review.googlesource.com/c/src/+/291380
Cr-Commit-Position: refs/branch-heads/5481@{#2} …
=> chore: cherry-pick e0efbd45ea74 from webrtc

docs/api/process.md
Tweaked a typo in `process.defaultApp`
Notes: none
=> docs: fixed a typo in `process.defaultApp` doc

script/lib/config.py, script/lib/native_tests.py, script/lib/util.py
Remove unused Python functions and variables in our `script` directory. Determined with the [vulture](https://pypi.org/project/vulture/) static analyzer.
Notes: none
=> build: remove unused python code

patches/chromium/mas_no_private_api.patch
Closes https://github.com/electron/electron/issues/37292.
Refs CL:4079319
Guards more usage of private APIs (see [here](https://opensource.apple.com/source/WTF/WTF-7607.3.9/wtf/spi/darwin/SandboxSPI.h.auto.html)) on Mac App Store builds causing rejections.
Notes: Fixed potential private API usage for MAS builds on macOS.
=> fix: guard more private API usage on MAS builds

docs/api/cookies.md, shell/browser/api/electron_api_cookies.cc, spec/api-net-spec.ts
The existing filter does not fully cover some scenarios, such as `httpOnly`. This `httpOnly` filter can avoid additional judgments at the js level.
Notes: Add `httpOnly` to the cookie filter.
=> feat: add `httpOnly` `cookies.get` filter

shell/browser/api/electron_api_web_contents.cc, shell/browser/native_window_mac.mm, spec/api-browser-window-spec.ts
Closes https://github.com/electron/electron/issues/37311.
Refs https://github.com/electron/electron/commit/438347d891c472c0a630ecf319dbb467338eb2de.
Corrects an issue with HTML fullscreen when `BrowserWindow` fullscreening is disabled. We needed to ensure that:
1) We do not change fullscreen transition state in `NativeWindowMac::SetFullScreen` if the window is not fullscreenable
2) We account for HTML fullscreen in `WebContents::IsFullscreen()`.
Notes: Corrects an issue with HTML fullscreen when `BrowserWindow` fullscreening is disabled.
=> fix: html fullscreen when window not fullscreenable

shell/browser/electron_browser_main_parts.cc, shell/common/node_bindings.cc, shell/common/node_bindings.h, shell/renderer/electron_renderer_client.cc, shell/services/node/node_service.cc
We should avoid `v8::Isolate::GetCurrent()` where possible, and we can instead  directly pass a Context in all cases here.
Notes: none
=> refactor: use associated `v8::Context` for event setup

.circleci/config/base.yml
#36354 combined both darwin and mas builds together but there is an "Electron build" step that doesn't denote what kind of build is being done.  This PR changes the "Electron build" step name to a more specific name like "Electron Darwin build" or "Electron MAS build".
Notes: none
=> ci: rename Electron build step to include type of build being built

docs/api/structures/web-request-filter.md, shell/browser/api/electron_api_web_request.cc, shell/browser/api/electron_api_web_request.h, spec/api-web-request-spec.ts
Fixes #10867
Notes: Added `types` to `webRequest` filter.
=> feat: add types to webRequest filter

shell/browser/browser.h, shell/browser/browser_linux.cc, shell/browser/browser_mac.mm, shell/browser/browser_win.cc, spec/api-app-spec.ts
This code causes a crash bc the `about_panel_options_` gets initialized as a `base::Value`, thus not a `Dict`, and the calls to `GetDict()` fail. This just changes that type to a `base::Value::Dict` and everything 🪄 magically ✨ works. Added a sanity test as a cherry on top. 
**EDIT**: ~~This PR now also unifies every platform by making `showAboutPanel` run asynchronously, where before it varied platform to platform. I think this would be the sensible default for the about panel (fire and forget), but if "run code after closing" is desired, either recommend users to pursue a different solution (e.g. use a BrowserWindow) or we can choose to implement the callback proper later.~~ This will be broken into a separate PR.
Notes: Setting the about panel's options no longer crashes.
=> fix: about panel crash

spec/disabled-tests.json, spec/index.js
As part of the test love initiative (see #proj-test-love-initiative in Slack), this PR adds a simple JSON list for disabling tests.
> "Why not just add `.skip` to tests?" you might ask.
There are two reasons why I'm adding this list and hook instead of advocating for adding `.skip` to disable tests:
1. We use a number of helpers like `ifit` and `ifdescribe`, among others, which makes it complicated to skip, say, only a specific platform but not the others.
2. In the future we want to build automation around disabling tests. Adding `.skip` to test source code is a very complex task, whereas adding a string to a JSON list is trivial.
While this list is an empty stub currently, I will be moving tests that are currently marked `.skip` in our test suite to use this list instead in a later PR. …
=> test: add disabled tests list

shell/browser/notifications/mac/cocoa_notification.mm
Closes https://github.com/electron/electron/issues/37376.
Fixes an issue where passing both `hasReply` and `actions` to a main process Notification on macOS resulted in the first action being obscured and unavailable. This was happening because we called `setHasActionButton` for the first available button, followed by `setHasReplyButton`. Per [documentation](https://developer.apple.com/documentation/foundation/nsusernotification/1413216-hasreplybutton?language=objc), if `hasReplyButton` and `hasActionButton` are both YES, the reply button is shown. This meant that the first action would be lost.
We fix this by setting the reply first, and if there are actions, setting them _all_ as additional actions.
</details> …
=> fix: `Notification` with reply obscuring first action on macOS

shell/browser/api/electron_api_browser_view.cc, shell/browser/api/electron_api_browser_window.cc, shell/browser/api/electron_api_web_contents.cc, spec/api-browser-view-spec.ts
Closes https://github.com/electron/electron/issues/37356.
Closes https://github.com/electron/electron/issues/37419.
Closes https://github.com/electron/electron/issues/37378.
Refs https://github.com/electron/electron/pull/37205.
Take 2. 
The combination of https://github.com/electron/electron/pull/35509 and https://github.com/electron/electron/pull/35603 meant that if a user called `webContents.destroy()` on a `BrowserView`'s `webContents`, the associated `DraggableRegionProvider` would not be removed from the `NativeWindow`, as the only codepath for doing so relied on the user removing the _entire_ `BrowserView` via `BrowserWindow.removeBrowserView`. The first approach I tried fixed a symptom, but then prevented the `destroyed` event from emitting if a `BrowserView` still existed.
This PR …
=> fix: handle closing `webContents` in `BrowserView`s

docs/api/session.md, shell/browser/electron_browser_context.cc
This adds a boolean option called `enableLocalEcho` to the callback handler for `setDisplayMediaRequestHandler()` which prevents input from being echoed in the local output stream (e.g., speaker). It can only be used if the `audio` property is set to a `WebFrameMain`. Closes https://github.com/electron/electron/issues/37293.
Notes: Added the `enableLocalEcho` flag to the session handler `ses.setDisplayMediaRequestHandler()` callback for allowing remote audio input to be echoed in the local output stream when `audio` is a `WebFrameMain`.
=> feat: add enableLocalEcho flag to setDisplayMediaRequestHandler() callback

shell/browser/ui/cocoa/electron_ns_window_delegate.mm
Closes https://github.com/electron/electron/issues/37305.
Fixes an issue where `minWidth`/`minHeight` and `maxWidth`/`maxHeight` would not be enforced if the user set an `aspectRatio` on macOS. This was happening because we were explicitly setting the  new width and height in `windowWillResize`, which overrides the handling macOS sets on the updated frame when `setContentMinSize` and `setContentMaxSize` were previously called on the `NSWindow`.
cc @carterbs 
Notes: Fixes an issue where `minWidth`/`minHeight` and `maxWidth`/`maxHeight` would not be enforced if the user set an `aspectRatio` on macOS.
=> fix: min/max width/height enforcement when `aspectRatio` is set

shell/browser/api/electron_api_web_contents.cc, spec/api-web-contents-spec.ts
Closes https://github.com/electron/electron/issues/37424.
Adds more descriptive error messages to `contents.takeHeapSnapshot` so that users better understand why it may have failed.
Notes: Improved error messages for `contents.takeHeapSnapshot`.
=> chore: improve `contents.takeHeapSnapshot` error messages

shell/browser/api/electron_api_web_contents.cc
The InvokeCallback _must_ be called before it's destroyed; this was the only
path I could see that could possibly result in the callback being destroyed
before being called. Hopefully this fixes DCHECKs we've been seeing
occasionally in CI.
Notes: none
=> fix: DCHECK in MessageSync in rare cases

shell/browser/ui/cocoa/electron_ns_window.mm
This makes draggable regions work on MAS builds again, after they broke in
https://github.com/electron/electron/pull/35603.
The [mas_disable_custom_window_frame.patch](https://github.com/electron/electron/blob/main/patches/chromium/mas_disable_custom_window_frame.patch) patch prevents the Chrome custom frame from being used on MAS, but the new draggable regions impl on macOS requires it, so we need to find another way of getting this behavior without tripping the MAS guards.
Fixes #37414.
Notes: Fixed draggable regions not working in Mac App Store builds.
=> fix: draggable regions on MAS

patches/chromium/.patches, patches/chromium/cherry-pick-aeec1ba5893d.patch
Fix UAF problem in AngleVulkanImageBacking
Right now, we use vulkan fence helper to release the backing.
It is right, if the last usage of the backing is by skia.
If the last usage is by gl, the fence helper(skia) isn't aware of
the submitted work from ANGLE, skia may call flush finish callback
to release the backing while the backing is still being referenced
by works in ANGLE. Fix the problem by calling glFinish() if the last
usage is GL.
Know issue: the finish callback of skia flush() is not always called
in order. So in edge cases, the UAF problem can still happen.
(cherry picked from commit d5143b14a00807b40eada4dfb0bce610ffc1477a)
Bug: 1309035
Change-Id: I3562043650dd2b27bde3a370bef45b1226cdd48c
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4232858 …
=> chore: cherry-pick aeec1ba5893d from chromium

shell/browser/electron_browser_main_parts.cc, shell/renderer/electron_renderer_client.cc, spec/fixtures/api/unhandled-rejection-handled.js, spec/fixtures/api/unhandled-rejection.js, spec/node-spec.ts
Closes https://github.com/electron/electron/issues/36829.
Switches from unhandled rejection style from `warn` to `warn-with-error-code`. The `warn` mode always triggers a warning, no matter if the `unhandledRejection` hook is set or not - this isn't really intuitive behavior. We added this initially in https://github.com/electron/electron/pull/29244, because Node.js themselves switched their unhandled rejection behavior to throw by default and we didn't want unhandled rejections to crash the main or renderer processes. `warn-with-error-code` now only warns if the error is not handled with the `unhandledRejection` hook - it also sets the process exit code to 1, but this doesn't affect Electron as it sets its own exit code.
Notes: Fixed an issue where unhandled rejections could cause …
=> fix: don't double-log unhandled rejections

patches/webrtc/.patches, patches/webrtc/cherry-pick-218b56e51638.patch
Fix Destruction inside WGC Callback
If we are notified of the destruction of the window before a
CaptureFrame call can fail, then we may end up attempting to destroy the
underlying WGC object inside it's own event handler. This can be
problematic, as the class itself may want to run other code. Instead,
we just unsubscribe and signal that any future CaptureFrame calls should
reject.
This also removes setting "is_capture_started_=false" in the item closed
handler, as all that served to do is cause the WgcCapturerWin code to
attempt to restart the capturer, and somewhat muddies up our metrics.
(cherry picked from commit 318cf28945d80a0ac6f09382e507c95e649cc4c1)
Bug: chromium:1413005
No-Try: True
Change-Id: Ibccb7a2e7ce531ba80b4b331b9bc2cda0ff75f4e
Reviewed-on: …
=> chore: cherry-pick 218b56e51638 from webrtc

patches/chromium/.patches, patches/chromium/m108-lts_further_simplify_webmediaplayermscompositor_lifetime.patch, patches/chromium/m108-lts_simplify_webmediaplayermscompositor_destruction.patch
[M108-LTS] Simplify WebMediaPlayerMSCompositor destruction.
The code was only sometimes calling StopUsingProvider() and posted
the submitter destruction unnecessarily.
Destruction now works the same as in VideoFrameCompositor, where the
class itself is responsible for calling StopUsingProvider() during
its own destruction.
(cherry picked from commit cbd238e85903b7d94910bd2c6362ff9abf9908cc)
Fixed: 1407701
Disallow-Recycled-Builds: test-failures
Change-Id: Ia649cb5532519468eea34e12745ed9c990580d82
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4195824
Auto-Submit: Dale Curtis <dalecurtis@chromium.org>
Commit-Queue: Tony Herre <toprice@chromium.org>
Cr-Original-Commit-Position: refs/heads/main@{#1098505}
Reviewed-on: …
=> chore: cherry-pick 999cc7185e93 and 0f0b3a54c53c from chromium

patches/chromium/.patches, patches/chromium/cherry-pick-06851790480e.patch
[search_engines] Exclude Policy and Play API engines from Sync merging
There's a security bug in which the call to ResetTemplateURLGUID can
cause a policy-created engine to be deleted. This means that after
the call, either the current `conflicting_turl` pointer, or future
iterations in the loop may point to an already-freed TemplateURL,
causing the use-after free bug.
This CL addresses that by forbidding Policy-created and Play API
engines from being merged into Synced engines.
Although Play API engines aren't directly affected, they seem to also
not be something that should be merged to Synced engines.
(cherry picked from commit 315632458eb795ef9d9dce3fd1062f9e6f2c2077)
Bug: 1414224
Change-Id: Ide43d71e9844e04a7ffe2e7ad2a522b6ca1535a3
Reviewed-on: …
=> chore: cherry-pick 06851790480e from chromium

patches/chromium/.patches, patches/chromium/cherry-pick-e79b89b47dac.patch
CHECK that YUV readback finished synchronously
DoReadbackYUVImagePixelsINTERNAL is implemented using skia asynchronous
readback and to make it synchronous we use sync cpu and gpu. In some
edge cases on linux we saw that doesn't happen if readback triggered
vulkan device lost.
To avoid use after free, CHECK that callback was actually called. In
case of device-lost gpu process will restart anyway, so while this is
not proper fix of the problem, it doesn't result in worse user visible
behaviour.
(cherry picked from commit 081df1e7d3712131bcaa575bda2e37ec7f6aa83d)
Bug: 1399742
Change-Id: Ie2172539bb907b9696ef62c70d398aca3967177c
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4143606
Reviewed-by: Peng Huang <penghuang@chromium.org>
Commit-Queue: Vasiliy Telezhnikov …
=> chore: cherry-pick e79b89b47dac from chromium

docs/api/web-contents.md, shell/browser/api/electron_api_web_contents.cc, spec/api-web-contents-spec.ts
Closes https://github.com/electron/electron/issues/37352.
Exposes and documents the `audio-state-changed` event on `webContents`. We previously emitted it, but it was a private and undocumented event. This documents and removes the `-` prefix.
Notes: Exposes the `audio-state-changed` event on `webContents`.
=> feat: expose `audio-state-changed` on `webContents`

docs/api/app.md
crashReporter and open-url handlers should be registered before ready.
Notes: none
=> docs: remove misleading info from will-finish-launching docs

patches/config.json, patches/webrtc/.patches, patches/webrtc/fix_fallback_to_x11_capturer_on_wayland.patch, shell/browser/api/electron_api_desktop_capturer.cc
Closes #37463 
Desktop Capturer behaves inconsistently on Wayland. We use PipeWire within WebRTC on Wayland to gather desktop window & screen capture sources. However, PipeWire does not always successfully start, and beginning with this CL, we no longer fall back to the X11 capturer, even if it is enabled: https://webrtc-review.googlesource.com/c/src/+/279163
Currently if neither PipeWire or X11 can be used, we return a nullptr in place of the capturer sources, crashing the application.
This PR does two things:
1. Reinstates the previous fallback behavior in WebRTC, so that if PipeWire fails on Wayland, we can still attempt to gather capture sources, rather than simply failing. I'll submit this as a patch for upstream consideration as well.
2. Ensures that a lower level capturer of some …
=> fix: fallback to X11 capturer if pipewire fails on Wayland

docs/api/web-contents.md
Closes https://github.com/electron/website/issues/381.
=> docs: remove outdated ipc example

DEPS
squirrel.mac repository does not contain a gclient DEPS file, so recursing into it is useless
Notes: none
=> refactor: DEPS: remove squirrel.mac from recursedeps

docs/api/app.md
Closes https://github.com/electron/electron/issues/37495.
Clarifies that `open-url` is not in fact preventable and has never been.
Notes: none.
=> docs: clarify `open-url` not preventable

shell/browser/ui/cocoa/electron_ns_window.mm, spec/api-browser-window-spec.ts
Fixes https://github.com/electron/electron/issues/37476
The QuickLook NSWindow's delegate is set to the same object as the delegate for the BrowserWindow's NSWindow [here](https://github.com/electron/electron/blob/f5385bcdec1951db34f8e55754265701530f5888/shell/browser/ui/cocoa/electron_ns_window.mm#L279). The delegate's [handler for windowDidChangeOcclusionState](https://github.com/electron/electron/blob/99f6ff430f57683ad0a240045c3cfbfbb8d67686/shell/browser/ui/cocoa/electron_ns_window_delegate.mm#L44) doesn't seem to expect handling events for the QuickLook window, and so when the QuickLook window becomes occluded, it assumes that the BrowserWindow has been occluded.
There's a similar issue for other NSWindowDelegate methods besides windowDidChangeOcclusionState. So resizing/moving the …
=> fix: don't set delegate for `QLPreviewPanel`

shell/browser/hid/hid_chooser_context.cc, shell/browser/ui/inspectable_web_contents.cc, shell/browser/usb/usb_chooser_context.cc, shell/browser/web_contents_preferences.cc, shell/common/gin_converters/hid_device_info_converter.h
These methods will probably get removed from Chromium at some point.
Notes: none
=> refactor: replace deprecated base::Value::Set<Type>Key usage

shell/browser/native_window_mac.mm
Closes https://github.com/electron/electron/issues/37487.
Fixes an issue with potential dock icon duplication on macOS by calling into our existing `app.dock.show` and `app.dock.hide` implementations, which are also subject to the duplication bugs but include workarounds to prevent them from happening.
Tested with https://gist.github.com/PsychoLlama/fcb2790372b6e4957beac9be7e543d3d to verify no duplicates occur.
Notes: Fixes an issue with potential dock icon duplication on macOS.
=> fix: invoke `app.dock.{hide|show}` instead of duplicating logic

docs/api/session.md, lib/browser/api/session.ts, shell/browser/api/electron_api_session.cc, shell/browser/api/electron_api_session.h, shell/browser/electron_browser_context.cc, shell/browser/electron_browser_context.h, spec/api-session-spec.ts, typings/internal-ambient.d.ts
Description of Change
Allow an absolute path to be passed to the session.fromPath() API.
This allows multiple browser windows to be created with absolute paths specified in the session.fromPath() parameters.
Checklist
Release Notes
notes: Allows an absolute path to be passed to the session.fromPath() API.
=> feat: Allow usage of an absolute path for partitions used in a session

.circleci/config/base.yml
- #37130 added logic to preserve `strip_binary.gni` on macOS but due to the fact that the `Free up space on MacOS` step runs in the background, on occasion the file gets deleted and a build step runs that needs it before the file is restored.
This change uses the `tmpify` function to move the directory `~/project/src/build/linux/` instead of deleting it directly which is a quicker operation than running `rm -rf ~/project/src/build/linux`.
Notes: none
=> ci: make sure that strip_binary.gni is properly preserved

docs/api/app.md, docs/api/auto-updater.md, docs/api/browser-window.md, docs/api/native-image.md, docs/api/system-preferences.md, docs/faq.md, docs/fiddles/menus/customize-menus/index.html, docs/tutorial/recent-documents.md, docs/tutorial/using-native-node-modules.md
MSDN was shut down and merged into https://learn.microsoft.com in 2020. I dug through all the links in our docs and followed the redirects.
In some cases, we got redirected to the home page. I think I was able to find all the matching docs based on searches in https://web.archive.org.
Note that there are a few stragglers in code comments but I think we should change those links in a separate PR so this PR can count as `docs-only`.
Notes: none
=> docs: change MSDN links to new Microsoft docs

patches/chromium/.patches, patches/chromium/cherry-pick-26bfa5807606.patch
[M108-LTS] In Typed CSSOM, reject adding to something that is not a list.
M108 merge issues:
third_party/blink/renderer/core/css/cssom/style_property_map.cc:
The check before the added IsValueList check isn't present in 108
(cherry picked from commit 7301cf1e40fdd97594ea491676b867cf4e577edc)
Fixed: 1417176
Change-Id: Idef1a81af46d334c181979778c28f19ce6369718
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4293477
Commit-Queue: Steinar H Gunderson <sesse@chromium.org>
Cr-Original-Commit-Position: refs/heads/main@{#1110281}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4306796
Commit-Queue: Zakhar Voit <voit@google.com>
Reviewed-by: Steinar H Gunderson <sesse@chromium.org>
Reviewed-by: …
=> chore: cherry-pick 26bfa5807606 from chromium

patches/v8/.patches, patches/v8/cherry-pick-546e00df97ac.patch
Merged: [ic] store slow stubs for objects with access checks in DefineNamedIC
The CheckIfCanDefine() used to check the attributes of the object
as well as reporting to access check failure callbacks can update
the lookup iterator, resulting in wrong store handlers being
installed. Restart the lookup iterator in this case to make
sure that slow handlers are installed.
Bug: chromium:1415249
(cherry picked from commit da2df213bc70437ef76f47e0ab6995fa45f8014a)
Change-Id: I92d60af7ea798d80b1115e63b7fce8e2e8026ed9
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/4290868
Cr-Commit-Position: refs/branch-heads/11.0@{#33} …
=> chore: cherry-pick 546e00df97ac from v8

patches/angle/.patches, patches/angle/cherry-pick-55e2b6daba9d.patch
[M108-LTS] Vulkan: Don't close render pass if rebind to same fbo
M108 merge issues:
src/libANGLE/renderer/vulkan/ContextVk.cpp:
- hasActiveRenderPass named hasStartedRenderPass in 108
- getLastRenderPassQueueSerial named getLastRenderPassSerial in 108
In the Vulkan backend, the render pass can occasionally (and
transiently) be in a state of "open but inactive".  This is when the
render pass is closed, but has the potential for future modifications
(for example to add a resolve attachment).  Under many circumstances, it
is expected that an open render pass cannot be in such a state.
This assumption can be broken in this scenario:
- Open render pass, draw, etc
- Change framebuffer binding
- Change framebuffer binding back to original
- Masked Clear
When ContextVk is synced before clear, it …
=> chore: cherry-pick 55e2b6daba9d from angle

patches/chromium/.patches, patches/chromium/cherry-pick-d202ad3c6aeb.patch
[M108-LTS] Prevent potential integer overflow in PersistentMemoryAllocator
https://crrev.com/c/4250177 added an extra check for potential
integer overflow in GetAllocSize but forgot to add the same
check in GetBlock.
This meant that it was possible to get a pointer to a block
but calling GetAllocSize on the same block would return zero.
This change makes the two functions consistent with each other
so calling GetBlock on invalid data will return nullptr.
BUG=1417317,1415328
(cherry picked from commit 81be8e8f2e13a9f1fe6d3150205a3c13af1db6e9)
Change-Id: I8eb3d91bae4528fc97517d202baf337536a4c81f
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4264177
Commit-Queue: Alexei Svitkine <asvitkine@chromium.org>
Cr-Original-Commit-Position: refs/heads/main@{#1107105} …
=> chore: cherry-pick d202ad3c6aeb from chromium

patches/v8/.patches, patches/v8/cherry-pick-f6ddbf42b1ea.patch
[M108-LTS][compiler] check if maps become deprecated during optimization
(cherry picked from commit f82d802a20aa62e42269f977302f26c5c3ed031b)
Bug: chromium:1417585
No-Try: true
Change-Id: Ie8eb76d2afb3ee4be66cf5d1c4bff8f745dc145b
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/4255648
Cr-Original-Commit-Position: refs/heads/main@{#85848}
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/4294983
Reviewed-by: Tobias Tebbi <tebbi@chromium.org>
Cr-Commit-Position: refs/branch-heads/10.8@{#50} …
=> chore: cherry-pick f6ddbf42b1ea from v8

patches/chromium/.patches, patches/chromium/cherry-pick-38de42d2bbc3.patch
[M108-LTS] Fix potential out of bounds write in base::SampleVectorBase
BUG=1417185
(cherry picked from commit 552939b035e724e022fedb90fd80cd008e441fcf)
Change-Id: I70719d0f9afb81dda373f88ab3a1c177397659ec
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4265437
Commit-Queue: Will Harris <wfh@chromium.org>
Cr-Original-Commit-Position: refs/heads/main@{#1106984}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4289351
Commit-Queue: Zakhar Voit <voit@google.com>
Owners-Override: Victor-Gabriel Savu <vsavu@google.com>
Cr-Commit-Position: refs/branch-heads/5359@{#1397}
Cr-Branched-From: 27d3765d341b09369006d030f83f582a29eb57ae-refs/heads/main@{#1058933}
Notes: Security: backported fix for …
=> chore: cherry-pick 38de42d2bbc3 from chromium

patches/chromium/.patches, patches/chromium/m108-lts_do_not_register_browser_watcher_activity_report_with.patch, patches/chromium/m108-lts_prevent_potential_integer_overflow_in.patch
[M108-LTS] Prevent potential integer overflow in PersistentMemoryAllocator
BUG=1415328
(cherry picked from commit 19de280a0c28065acf2a7e001af5c981698a461c)
Change-Id: I66dcae6a1aacc1310ddd715033b3704c932b9800
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4250177
Commit-Queue: Will Harris <wfh@chromium.org>
Commit-Queue: Alexei Svitkine <asvitkine@chromium.org>
Cr-Original-Commit-Position: refs/heads/main@{#1105177}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4279513
Commit-Queue: Zakhar Voit <voit@google.com>
Owners-Override: Victor-Gabriel Savu <vsavu@google.com>
Cr-Commit-Position: refs/branch-heads/5359@{#1400} …
=> chore: cherry-pick 86fc0e9bedaf and 8d52bc14b306 from chromium

appveyor-bake.yml, appveyor-woa.yml, appveyor.yml, script/prepare-appveyor.js
Updates the Appveyor image for 24-x-y to 112.0.5615.29
Notes: none
=> ci: update appveyor image to e-112.0.5615.29

appveyor-bake.yml, appveyor-woa.yml, appveyor.yml, script/prepare-appveyor.js
Updates the Appveyor image for 23-x-y to 110.0.5481.208
Notes: none
=> ci: update appveyor image to e-110.0.5481.208

docs/api/web-contents.md, docs/fiddles/features/web-bluetooth/index.html, docs/fiddles/features/web-bluetooth/main.js, docs/fiddles/features/web-bluetooth/preload.js, docs/fiddles/features/web-bluetooth/renderer.js, shell/browser/lib/bluetooth_chooser.cc, shell/browser/lib/bluetooth_chooser.h
There was an issue where bluetooth requests could not be cancelled when no devices are returned because `select-bluetooth-device` never fires in that case and the only way to cancel a bluetooth request is to call the callback from `select-bluetooth-device` with an empty string.  This PR fixes that issue by always firing `select-bluetooth-device` regardless of whether devices are available or not.
Additionally, this PR updates the bluetooth documentation to be more accurate and contain more explanation about how `select-bluetooth-device` works as well as to update the example fiddle to include logic to cancel a bluetooth request.
- Fixes #37090
- Fixes #37436
Notes: Fixed canceling of bluetooth requests when no devices are returned.
=> fix: allow cancelling of bluetooth requests

patches/config.json, patches/pdfium/.patches, patches/pdfium/cherry-pick-a0d16d18d072.patch
M110: Observe CPWL_* object destruction across CPDFSDK_Widget methods
This is a simple fix to stop the symptoms while we investigate
how to avoid mutations at these points in the first place.
-- fix some nearby braces and annoying blank lines while at it.
Bug: chromium:1419831
Change-Id: I20c38806b91c7c0c9016bb1b567a04ce319243d8
Reviewed-on: https://pdfium-review.googlesource.com/c/pdfium/+/104397
(cherry picked from commit 63e3719f1ec20ee6db804b2b2d4b00680db18d9c)
Reviewed-on: https://pdfium-review.googlesource.com/c/pdfium/+/104833
Auto-Submit: Tom Sepez <tsepez@chromium.org>
Notes: Security: backported fix for CVE-2023-1530.
=> chore: cherry-pick a0d16d18d072 from pdfium

patches/angle/.patches, patches/angle/cherry-pick-6da1a8953313.patch
M110: Vulkan: Don't close render pass if rebind to same fbo
In the Vulkan backend, the render pass can occasionally (and
transiently) be in a state of "open but inactive".  This is when the
render pass is closed, but has the potential for future modifications
(for example to add a resolve attachment).  Under many circumstances, it
is expected that an open render pass cannot be in such a state.
This assumption can be broken in this scenario:
- Open render pass, draw, etc
- Change framebuffer binding
- Change framebuffer binding back to original
- Masked Clear
When ContextVk is synced before clear, it sees that the framebuffer
binding is changed (though it hasn't really), and it closes the render
passes and sets the render pass dirty bit.  If a draw were to follow, a
new render pass would …
=> chore: cherry-pick 6da1a8953313 from angle

patches/angle/.patches, patches/angle/cherry-pick-ce029c91a662.patch
M110: D3D11: Add logic to disassociate EGL image storages.
The TextureStorage classes for External and EGLImages were missing the
logic to disassociate from images. This lead to the images continuing
to hold references to deleted storages.
Bug: chromium:1415330
Change-Id: I8303f6751d87a9b0a52993c7d4e9509b086b93f3
Reviewed-on: https://chromium-review.googlesource.com/c/angle/angle/+/4328347
Reviewed-by: Peng Huang <penghuang@chromium.org>
(cherry picked from commit a8720455fda43167465c3d2f9a13fca60c21f56e)
Reviewed-on: https://chromium-review.googlesource.com/c/angle/angle/+/4348335
Ref electron/security#305
Notes: Security: backported fix for CVE-2023-1531.
=> chore: cherry-pick ce029c91a662 from angle

patches/chromium/.patches, patches/chromium/cherry-pick-1235110fce18.patch
Disable glShaderBinary in the passthrough cmd decoder.
This matches the behaviour of the validating command decoder. The client
does not use this function and it's not exposed to WebGL.
(cherry picked from commit 4a81311a62d853a43e002f45c6867f73c0accdab)
Bug: 1422594
Change-Id: I87c670e4e80b0078fddb9f089b7ac7777a6debfa
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4324998
Cr-Original-Commit-Position: refs/heads/main@{#1115379}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4335184
Cr-Commit-Position: refs/branch-heads/5481@{#1357}
Cr-Branched-From: 130f3e4d850f4bc7387cfb8d08aa993d288a67a9-refs/heads/main@{#1084008}
Ref electron/security#300 …
=> chore: cherry-pick 1235110fce18 from chromium

docs/tutorial/sandbox.md
For disabling the sandbox, `sandbox` should be assigned to false, however the demo code is using incorrect value.
@electron/docs
Notes: None
=> docs: fixup incorrect value for disabling sandbox

patches/chromium/.patches, patches/chromium/cherry-pick-0407102d19b9.patch
[M108-LTS] Convert known it != end() DCHECK failures to CHECK
These have hit on DCHECK builds in the wild and precede erasing or
dereferencing an iterator that is UB.
This CL excludes DCHECK failures that precede non-DCHECK handling of the
it != end() failures. Those should probably be rewritten as CHECKs
but are less urgent and semi-orthogonal.
Known crashes (one per file) are:
crash/dc49e3cadab36d4c
crash/0ee3427d25937024
crash/b89303e84d123019
crash/cc35183b861a4992
(cherry picked from commit 1aec0b297900a7b59bd24314dff239f3c5697f45)
Bug: 1418734
Change-Id: I81ed7b45be33769e250c65c8bb7334a34be4380e
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4288168
Commit-Queue: Peter Boström <pbos@chromium.org>
Cr-Original-Commit-Position: refs/heads/main@{#1109350} …
=> chore: cherry-pick 0407102d19b9 and 183a57f4eabc from chromium

shell/browser/api/message_port.cc, spec/api-ipc-spec.ts
Closes https://github.com/electron/electron/issues/37565.
Fixes an issue where calling `port.postMessage` in `MessagePortMain` with some invalid parameters could cause a crash. When passing an (unsupported) `ArrayBuffer`, for example, this happened because we try to unwrap everything in the transferrables list and upstream's [`WrapperInfo`](https://source.chromium.org/chromium/chromium/src/+/main:gin/wrapper_info.cc;l=10-16;drc=0e9a0b6e9bb6ec59521977eec805f5d0bca833e0) logic doesn't take into account that an object might have the correct number of internal fields but not be a `WrappableBase`. I first tried to [upstream this](https://chromium-review.googlesource.com/c/chromium/src/+/4335426) but was told it's for now better handler on the embedder's side.
We can therefore address this by …
=> fix: crash in `MessagePortMain` with some `postMessage` params

patches/chromium/.patches, patches/chromium/cherry-pick-8731bd8a30f6.patch
[M110] Use optional SafeRef to save RenderFrameHost in NavigationRequest
This prevents use-after-free if NavigationRequests somehow still
points to an already-deleted RFH, which is currently possible (see bug).
Also converts usages of `render_frame_host_` to use the
GetRenderFrameHost() function to ensure that they are all called after
the final RenderFrameHost is picked for the navigation.
(cherry picked from commit 7b75ae34df6d15acf4e5a45f12c9dca4ce7f2586)
Bug: 1416916
Change-Id: I45569e7bb1f160158dc3139fc9e49d7d6bb56738
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4278923
Reviewed-by: Hiroki Nakagawa <nhiroki@chromium.org>
Commit-Queue: Rakina Zata Amni <rakina@chromium.org>
Reviewed-by: Alex Moshchuk <alexmos@chromium.org> …
=> chore: cherry-pick 8731bd8a30f6 from chromium

patches/v8/.patches, patches/v8/cherry-pick-aeceeb2187a6.patch
Merged [valueserializer] Fix map transition chain following w/ dictionary maps
Map::Update might return a dictionary map, and the calling code didn't
take it into account.
Bug: chromium:1412487
(cherry picked from commit b0db6637936a88807b5512a4de68145d0a9d6f02)
Change-Id: Ib5e55aa60719e4ac2f14d993a3fc3e908cd43d2e
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/4290145
Reviewed-by: Marja Hölttä <marja@chromium.org>
Reviewed-by: Lutz Vahl <vahl@chromium.org>
Commit-Queue: Lutz Vahl <vahl@chromium.org>
Cr-Commit-Position: refs/branch-heads/11.0@{#35}
Cr-Branched-From: 06097c6f0c5af54fd5d6965d37027efb72decd4f-refs/heads/11.0.226@{#1}
Cr-Branched-From: 6bf3344f5d9940de1ab253f1817dcb99c641c9d3-refs/heads/main@{#84857}
Ref electron/security#295
Notes: Security: backported fix …
=> chore: cherry-pick aeceeb2187a6 from v8

patches/chromium/.patches, patches/chromium/cherry-pick-bfd926be8178.patch
[M110] webcodecs: Fix VP9 p2 encoding of NV12 frames
(cherry picked from commit 503831d1bdfdbe20c096f04cefc2231efd9ca4c0)
Bug: 1412991
Change-Id: I2e596f65170c1fc98c122bfb0ecff4b241feee15
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4250421
Commit-Queue: Eugene Zemtsov <eugene@chromium.org>
Reviewed-by: Dale Curtis <dalecurtis@chromium.org>
Cr-Original-Commit-Position: refs/heads/main@{#1105528}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4288113
Cr-Commit-Position: refs/branch-heads/5481@{#1271}
Cr-Branched-From: 130f3e4d850f4bc7387cfb8d08aa993d288a67a9-refs/heads/main@{#1084008}
Notes: Security: backported fix for 1412991.
=> chore: cherry-pick bfd926be8178 from chromium

patches/chromium/.patches, patches/chromium/cherry-pick-56bd20b295b4.patch
[M110] Update Crashpad to 3e8727238bae3c069bd71cfb3b2bbaa98b55f05b
3e8727238bae win: Only process up to EXCEPTION_MAXIMUM_PARAMETERS in an
EXCEPTION_RECORD
(cherry picked from commit d05bea76b7ce72d66507ebbe00caf5e45afd587a)
Fixed: 1412658
Change-Id: I7461602d1a18d44ea1a11ac19f1487fbdb92acf6
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4285061
Commit-Queue: Robert Sesek <rsesek@chromium.org>
Commit-Queue: Alex Gough <ajgo@chromium.org>
Reviewed-by: Alex Gough <ajgo@chromium.org>
Auto-Submit: Robert Sesek <rsesek@chromium.org>
Cr-Original-Commit-Position: refs/heads/main@{#1108722}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4295200
Cr-Commit-Position: refs/branch-heads/5481@{#1298} …
=> chore: cherry-pick 56bd20b295b4 from chromium

shell/renderer/api/electron_api_context_bridge.cc
Closes https://github.com/electron/electron/issues/37504.
They were previously being sent over the bridge as plain objects, but without all their distinguishing properties. This corrects that and conforms to docs.
Notes: none.
=> chore: generator objects can't be sent over the context bridge

patches/chromium/.patches, patches/chromium/cherry-pick-b041159d06ad.patch
[M-110] hid: Handle empty input reports
It's possible for a HID device to define its report descriptor such that
one or more reports have no data fields within the report. When receiving these reports, the report buffer should contain only the
report ID byte and no other data.
Ensure that we do not read past the end of the buffer when handling
zero-length input reports.
(cherry picked from commit c9d77da78bc66c135520ac77873d67b89cdcaee6)
Bug: 1419718
Change-Id: I51d32c20f6b16f0d2b0172e0a165469b6b79748c
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4296562
Reviewed-by: Reilly Grant <reillyg@chromium.org>
Commit-Queue: Matt Reynolds <mattreynolds@chromium.org>
Cr-Original-Commit-Position: refs/heads/main@{#1112009}
Reviewed-on: …
=> chore: cherry-pick b041159d06ad from chromium

shell/browser/api/electron_api_web_contents.cc
Closes https://github.com/electron/electron/issues/37515
Refs https://github.com/electron/electron/pull/36230
The refactor lost this [check for frameless windows](https://github.com/electron/electron/pull/36230/files#diff-bfaa73008a8b883d15dd11323996e12e24ae556c8a03e8dd0ad43b8785cf099dL151) which meant that draggable regions started taking effect for framed windows as well as capturing clicks. This fixes that by only setting `draggable_region_` in `WebContents::UpdateDraggableRegions` if the window is frameless.
Notes: Fixed an issue where draggable regions incorrectly captured clicks in framed windows.
=> fix: draggable regions shouldn't capture clicks on frames windows

docs/tutorial/tutorial-2-first-app.md
The Building your First App guide states: "Your package.json file should look something like this after initializing your package and installing Electron." then `package.json` content is shown, but it is not up to date with how it looks now when creating the app by using the commands provided in the guide and the default values. This was corrected by adding:
```
"scripts": {
"test": "echo \"Error: no test specified\" && exit 1"
},
```
which is added by default while `npm init`. Also bumped the electron version. 
=> docs: updated package.json content and electron version in build first app guide

patches/chromium/.patches, patches/chromium/cherry-pick-86fc0e9bedaf.patch, patches/chromium/cherry-pick-d202ad3c6aeb.patch
[M108-LTS] Prevent potential integer overflow in PersistentMemoryAllocator
BUG=1415328
(cherry picked from commit 19de280a0c28065acf2a7e001af5c981698a461c)
Change-Id: I66dcae6a1aacc1310ddd715033b3704c932b9800
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4250177
Commit-Queue: Will Harris <wfh@chromium.org>
Commit-Queue: Alexei Svitkine <asvitkine@chromium.org>
Cr-Original-Commit-Position: refs/heads/main@{#1105177}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4279513
Commit-Queue: Zakhar Voit <voit@google.com>
Owners-Override: Victor-Gabriel Savu <vsavu@google.com>
Cr-Commit-Position: refs/branch-heads/5359@{#1400} …
=> chore: cherry-pick 86fc0e9bedaf from chromium

patches/chromium/.patches, patches/chromium/cherry-pick-b5c9e5efe5dd.patch
Merge M110: "Improve checks for VideoFrame layouts."
Adds a `VideoFrameLayout::IsValidForSize(size)` method which clients can
use to verify a VideoFrameLayout for their purpose. Updates a few call
sites to use the new verifier and adds tests.
(cherry picked from commit 17f73200c066158330542c19d521c517586533a2)
Fixed: 1421268
Change-Id: I51049ada6119eddb31cdd9b7edfe77ee65b1da7a
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4307674
Auto-Submit: Dale Curtis <dalecurtis@chromium.org>
Reviewed-by: Hirokazu Honda <hiroh@chromium.org>
Reviewed-by: Dominick Ng <dominickn@chromium.org>
Commit-Queue: Dominick Ng <dominickn@chromium.org>
Cr-Original-Commit-Position: refs/heads/main@{#1116233}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4342492 …
=> chore: cherry-pick b5c9e5efe5dd from chromium

docs/api/app.md, docs/api/structures/printer-info.md, docs/api/tray.md, docs/development/azure-vm-setup.md, docs/development/debugging-on-windows.md, docs/development/testing.md, docs/glossary.md, docs/tutorial/code-signing.md, docs/tutorial/tutorial-2-first-app.md, docs/tutorial/windows-arm.md, docs/tutorial/windows-taskbar.md
Similar to https://github.com/electron/electron/pull/37603. `docs.microsoft.com` redirects to `learn.microsoft.com`, so updating these links.
Leaving one link on `docs/tutorial/windows-store-guide.md` because it looks like it might be a different page rather than a simple redirect, and needs to be dug further into, so leaving the original link to not lose that context.
Notes: none
=> docs: update docs.microsoft.com links to learn.microsoft.com

patches/chromium/.patches, patches/chromium/cherry-pick-9aa4c45f21b1.patch
[M108-LTS] Shutdown RtpContributingSourceCache in Dispose().
The cache is an off-heap object, but it is owned by an on-heap object
(RTCPeerConnection). Dispoing the owning object poisons memory owned by
it, but the cache may have in-flight tasks (cache doing ClearCache in a
delayed microtask). This CL adds a Shutdown() method to ensure the
cache isn't doing anything in the next microtask after disposal.
No reliable way to repro this has been found but the change should be
safe so hoping we can land without tests.
(cherry picked from commit 4d450ecd6ec7776c7505dcf7d2f04157ff3ba0eb)
Bug: 1413628
Change-Id: I479aace9859f4c10cd75d4aa5a34808b4726299d
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4247023
Commit-Queue: Henrik Boström <hbos@chromium.org> …
=> chore: cherry-pick 9aa4c45f21b1 from chromium

.devcontainer/on-create-command.sh
Refs https://github.com/electron/build-tools/pull/421/
Prevents the following on every build in Codespaces:
```
builduser@9bbff9c296d0:/workspaces/gclient/src/electron$ e build
WARN We've made these temporary changes to your configuration:
* added missing property $schema
Run "e sanitize-config" to make these changes permanent.
WARN We've made these temporary changes to your configuration:
* added missing property $schema
Run "e sanitize-config" to make these changes permanent.
```
Also tweaks order of config to match build-tools default.
Notes: none
=> build: fix build-tools schema in config

shell/browser/ui/views/menu_bar.cc, shell/browser/ui/views/menu_bar.h
Fixes #34939.
More information is in a comment on that issue, but the long and short of it is the `Background` created by `views::CreateThemedSolidBackground` isn't immediately set, and will change to stay in sync with the color provider. So the code has been refactored to ensure `background_color_` is always up-to-date.
Notes: Fixed the active background color for top-level menu items on Windows
=> fix: set background color for menu bar on Windows

.markdownlint.json, CONTRIBUTING.md, docs/api/app.md, docs/api/browser-window.md, docs/api/menu-item.md, docs/api/menu.md, docs/api/native-image.md, docs/api/session.md, docs/api/tray.md, docs/api/web-contents.md, docs/api/webview-tag.md, docs/development/azure-vm-setup.md, docs/development/goma.md, docs/development/issues.md, docs/development/pull-requests.md, docs/tutorial/boilerplates-and-clis.md, docs/tutorial/electron-timelines.md, docs/tutorial/electron-versioning.md, docs/tutorial/macos-dock.md, docs/tutorial/offscreen-rendering.md, docs/tutorial/performance.md, docs/tutorial/recent-documents.md, docs/tutorial/security.md
Follow-up to #36540 which enables the rules enforcing consistent style for **strong** and _emphasis_. In our docs that means `**` and `_`, respectively, as those are the dominant styles.
Also updated the line endings for `.markdownlint.json` as it was CRLF for some reason.
Notes: none
=> chore: enforce consistent Markdown style for strong and emphasis

patches/node/fixup_for_wc_98-compat-extra-semi.patch, patches/node/support_v8_sandboxed_pointers.patch, script/node-disabled-tests.json
Backport of https://github.com/electron/electron/pull/37021
Notes: Fixed a memory leak in v8.serialize() when running Node.js within Electron.
=> chore: fix memory leak in v8.serialize()

build/args/all.gn
Node PR: https://github.com/nodejs/node/pull/47375
Do not merge before attached Node PR is merged. This PR updates our NMV to 116 for Electron 25.
Please merge this PR before branching 25-x-y
Notes: none
=> build: bump nmv to 116 (Electron 25)

spec/api-menu-spec.ts
Was fixed a while ago in #20114, so remove the workaround on these tests.
Notes: none
=> test: remove workaround for fixed Menu.closePopup issue

shell/common/node_bindings.cc, spec/chromium-spec.ts
When sandbox: false and contextIsolation: false, CSP wasn't being correctly
enforced.
Notes: Security: Fixed an issue with Content-Security-Policy not being correctly enforced when sandbox: false and contextIsolation: false. (CVE-2023-23623)
=> fix: apply csp correctly when contextIsolation: false

spec/api-app-spec.ts, spec/api-autoupdater-darwin-spec.ts, spec/api-browser-window-spec.ts, spec/api-media-handler-spec.ts, spec/api-menu-item-spec.ts, spec/api-menu-spec.ts, spec/api-process-spec.ts, spec/api-protocol-spec.ts, spec/api-screen-spec.ts, spec/api-session-spec.ts, spec/api-web-contents-spec.ts, spec/api-web-frame-main-spec.ts, spec/asar-spec.ts, spec/chromium-spec.ts, spec/disabled-tests.json, spec/extensions-spec.ts, spec/index.js, spec/version-bump-spec.ts, spec/visibility-state-spec.ts, spec/webview-spec.ts
This PR does a straightforward cleanup of almost all usages of `.skip()` in our code, either replacing with a proper helper function (`ifit`, `ifdescribe`) or the disabled test list if the test is intended to be disabled. There should be no semantic differences, just the mechanics of how tests are skipped.
Perhaps some of these are meant to represent something like "disable only on windows" but I'll leave that type of interpretation for a follow-up, more semantics-focused, PR. ⏩
Notes: none
=> test: migrate to helpers & disabled tests list

docs/api/app.md
Closes https://github.com/electron/electron/issues/37781.
Fixes an issue with the return type of `app.getPreferredSystemLanguages()` by reformatting the example documentation. The issue is rooted in https://github.com/electron/docs-parser/issues/84, which should also be handled eventually cc @MarshallOfSound 
Notes: none
=> docs: fix `app.getPreferredSystemLanguages()` return type

docs/api/session.md, docs/api/structures/resolved-endpoint.md, docs/api/structures/resolved-host.md, filenames.auto.gni, filenames.gni, shell/browser/api/electron_api_session.cc, shell/browser/api/electron_api_session.h, shell/browser/net/resolve_host_function.cc, shell/browser/net/resolve_host_function.h, shell/common/gin_converters/net_converter.cc, shell/common/gin_converters/net_converter.h, spec/api-session-spec.ts, spec/index.js
Backport of #37690.
Notes: Introduced `session.resolveHost` for resolving hostnames with Chromium's DNS resolver
=> feat: session.resolveHost

script/spec-runner.js
Expands on #36944 to support version strings which get the latest version on a major version. Also adds a log message to state which version is being used.
```sh
yarn test --electronVersion latest
yarn test --electronVersion latest@24
```
Notes: none
=> test: support 'latest'/'latest@X' Electron version strings

lib/browser/api/menu-item-roles.ts
Similar to #23681 - `role`: `about` doesn't work on Linux, even though docs make it look like it works.
See also #23847 #23851 https://github.com/mifi/lossless-cut/issues/1537
Notes: Added about panel for menu role `about` on Linux as well
=> fix: showAboutPanel also on linux

docs/breaking-changes.md
This PR corrects two APIs that were listed as deprecated in 24-x-y - they were actually deprecated in 25-x-y.
Notes: none
=> docs: update E24/E25 breaking changes

docs/breaking-changes.md
Updates breaking changes in 24-x-y to remove two APIs that were actually deprecated in 25-x-y.
Notes: none
=> docs: update 24-x-y breaking changes

shell/renderer/api/electron_api_context_bridge.cc, shell/renderer/api/electron_api_context_bridge.h, shell/renderer/api/electron_api_web_frame.cc, shell/renderer/renderer_client_base.cc, spec/api-context-bridge-spec.ts
Fixes an obscure crash that could occur when exceptions got thrown in certain ways
=> fix: exceptions in nested conversions live in the target world

patches/node/allow_embedder_to_control_codegenerationfromstringscallback.patch, patches/node/build_ensure_native_module_compilation_fails_if_not_using_a_new.patch, patches/node/src_allow_optional_isolation_termination_in_node.patch
In
https://github.com/electron/electron/blob/main/docs/tutorial/using-native-node-modules.md#using-npm, we recommend setting the `npm_config_disturl` variable but doing that does not work on node-gyp v8.4.0 because after
https://github.com/nodejs/node-gyp/pull/2497
landed, the dist URL was read only from `gyp.opts['dist-url']`. The fix for reading the value from `npm_config_disturl` by parsing `gyp.opts.disturl` was landed in
https://github.com/nodejs/node-gyp/pull/2547 and that change was released in node-gyp v9.0.0, so this change updates the error macro to recommend node-gyp v9.0.0 as the minimum required version.
Notes: Fix recommended `node-gyp` version in `node.h` error 
cc @zcbenz
=> fix: recommended `node-gyp` version in `node.h` error

patches/chromium/.patches, patches/chromium/cherry-pick-d6946b70b431.patch
[M112] Move the edit commands to an on stack variable
DevTools uses nested event loops and the usage of the class member can
be problematic for iteration because the nested loop can change the
variable's storage causing a UAF.
(cherry picked from commit d9b34f0f3a2d0dd73648eca3ef940fb66806227b)
Bug: 1420510
Change-Id: Ie08a71b60401fa4322cca0cc31062ba64672126a
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4355811
Reviewed-by: David Bokan <bokan@chromium.org>
Commit-Queue: Dave Tapuska <dtapuska@chromium.org>
Cr-Original-Commit-Position: refs/heads/main@{#1120123}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4369603
Cr-Commit-Position: refs/branch-heads/5615@{#809} …
=> chore: cherry-pick d6946b70b431 from chromium

lib/browser/api/power-monitor.ts, shell/browser/api/electron_api_power_monitor.cc, spec/api-power-monitor-spec.ts
This doesn't seem to be needed any more.
Notes: none
=> feat: remove on(ready) requirement from powerMonitor

.github/workflows/issue-commented.yml, .github/workflows/stale.yml
Currently the automation around https://github.com/electron/electron/labels/blocked%2Fneed-repro will remove the label on any activity on the issue, including labeling. This has caused several issues to have the label removed due to maintainers adding a label after the initial https://github.com/electron/electron/labels/blocked%2Fneed-repro label, even if it's just a couple of seconds later, since the stale bot compares timestamps.
Rework the automation a bit to tell `actions/stale` to not manage removing the label (it has no way to configure comments vs other activity) and have a separate workflow on issue comments to remove the label.
Also excludes maintainer comments from removing the label, so that the order of applying the label and making a comment does will not accidentally result …
=> ci: only remove blocked/need-repro on comment

docs/tutorial/tutorial-2-first-app.md
By using `app.on('ready').then(xxx)`, application will throw a TypeError
Changed `app.on('ready').then(() => {` to `app.on('ready', () => {`
Notes: none
=> docs: Fix the syntax error for code fragment

shell/browser/ui/cocoa/electron_ns_window.mm
Closes https://github.com/electron/electron/issues/37628.
Refs https://github.com/electron/electron/pull/35603
Fixes an issue where the 'swipe' event wasn't being emitted properly on macOS. This happened as a result of https://github.com/electron/electron/pull/35603, which removed our `OverrideNSWindowContentView` logic. This logic replaced `BridgedContentView` in `ElectronNSWindow` with our own logic, and enabled our implementation of `swipeWithEvent` to take precedence. After the removal of that code, the `swipeWithEvent` implementation in `BridgedContentView` would always be called regardless of our override. Fix this by forcing our implementation to be called instead.
Notes: Fixed an issue where the 'swipe' event wasn't being emitted properly on macOS.
=> fix: swipe event emission on macOS

shell/browser/web_contents_preferences.cc, spec/api-browser-window-spec.ts
This fix brought to you by `clang-tidy`, which detected the problem:
```
../../electron/shell/browser/web_contents_preferences.cc:430:71: warning: an integer is interpreted as a character code when assigning it to a string; if this is intended, cast the integer to the appropriate character type; if you want a string representation, use the appropriate conversion facility [bugprone-string-integer-assignment]
prefs->standard_font_family_map[blink::web_pref::kCommonScript] = font;
^
../../electron/shell/browser/web_contents_preferences.cc:433:68: warning: an integer is interpreted as a character code when assigning it to a string; if this is intended, cast the integer to the appropriate character type; if you want a string representation, use the appropriate conversion facility …
```
=> fix: defaultFontFamily in webPreferences

script/node-disabled-tests.json
The node test `parallel/test-heapsnapshot-near-heap-limit-by-api-in-worker` has been flaky for us recently:
* https://app.circleci.com/pipelines/github/electron/electron/67691/workflows/ed8d62f3-eb83-40be-99d2-5119e01f4ddb/jobs/1486657
* https://app.circleci.com/pipelines/github/electron/electron/68070/workflows/b01ed73b-5352-4a2e-b076-3fd3b97624e0/jobs/1492764/tests#failed-test-0
Notes: none
=> chore: disable flaky node test

patches/v8/.patches, patches/v8/cherry-pick-f4b66ae451c2.patch
Merged: [compiler] Prevent constant folding of TypeGuard
TypeGuard are used to prevent operations from floating before a
preceding check, and thus shouldn't be constant-folded.
Bug: chromium:1427388
(cherry picked from commit 867716437273c16dc6ef5bc85b9c18affa1fb242)
Change-Id: Ia334d079707f13974235f8c04ccb468ac16ff794
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/4386487
Commit-Queue: Darius Mercadier <dmercadier@chromium.org>
Cr-Commit-Position: refs/branch-heads/11.2@{#23}
Cr-Branched-From: 755511a138609ac5939449a8ac615c15603a4454-refs/heads/11.2.214@{#1}
Cr-Branched-From: e6b1ccefb0f0f1ff8d310578878130dc53d73749-refs/heads/main@{#86014}
Notes: Security: backported fix for 1427388.
=> chore: cherry-pick f4b66ae451c2 from v8

shell/common/platform_util_win.cc
Refs CL:2271074.
Replaces uses of `ComPtr::GetAddressOf()` with `ComPtr::operator&`. From the CL:
> Microsoft::WRL::ComPtr<T>::GetAddressOf() is banned due to the ease
of causing memory leaks. 
> Also replace CopyTo(foo.GetAddressOf()) with As(&foo) since CopyTo(&foo)
does not work if we are copying to different interfaces.
> Also replace QueryInterface(foo.GetAddressOf()) with
QueryInterface(IID_PPV_ARGS(&foo)).
Also brings in CL:3491805.
Notes: none
=> chore: replace uses of `ComPtr::GetAddressOf()` with `ComPtr::operator&`

docs/api/browser-window.md
Closes https://github.com/electron/electron/issues/37852.
Notes asynchrony of `win.setFullScreen(flag)`.
Notes: none
=> docs: add note to `win.setFullScreen(flag)`

shell/browser/extensions/api/resources_private/resources_private_api.cc
Usage of the "chrome/browser/pdf/pdf_extension_util.h" header
requires the `ENABLE_PDF` buildflag to be enabled.
Related to #37856.
Notes: none
=> build: fix building with no PDF support

patches/v8/.patches, patches/v8/cherry-pick-c605df24af3c.patch
[runtime] Make Error.captureStackTrace() a no-op for global object
(cherry picked from commit fa81078cca6964def7a3833704e0dba7b05065d8)
Bug: chromium:1432210
Change-Id: I8aa4c3f1d9ecbfffce503085c2879416ff916c69
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/4417690
Reviewed-by: Tobias Tebbi <tebbi@chromium.org>
Auto-Submit: Igor Sheludko <ishell@chromium.org>
Cr-Original-Commit-Position: refs/heads/main@{#87045}
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/4419050
Reviewed-by: Lutz Vahl <vahl@chromium.org>
Cr-Commit-Position: refs/branch-heads/11.2@{#31} …
=> chore: cherry-pick c605df24af3c from v8

patches/chromium/.patches, patches/chromium/cherry-pick-9585757f9fad.patch
Addresses #37053 
StatusIconLinuxDbus: Use default session bus name
The StatusNotifierItem spec requires status items register with the name
`org.kde.StatusNotifierItem-$PID-$ID`.  However this causes problems
in sandboxed environments such as flatpak because extra permissions
are required to register the bus name.  Additionally, the name
`org.kde.StatusNotifierItem-2-1` will be used every time when PID
namespaces are used for sandboxing.
To address this, just use the default bus name we were given on
initially connecting to the bus.  This violates the spec, but there's
actually no consequence for doing this.
R=sky
Fixed: 1408315
Change-Id: I1abc4100c2899206eaa1804a3ff47dce7ad4e565
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4179380
Auto-Submit: Thomas Anderson …
=> chore: cherry-pick 9585757f9fad from chromium

docs/api/power-monitor.md, lib/browser/api/power-monitor.ts, shell/browser/api/electron_api_power_monitor.cc, shell/browser/api/electron_api_power_monitor.h, spec/api-power-monitor-spec.ts
Expose some more base::PowerMonitor stuff. Specifically, thermal state and CPU
throttling.
See
https://source.chromium.org/chromium/chromium/src/+/refs/heads/main:base/power_monitor/power_observer.h;l=35;drc=991110a34dafb7233475cdfa91c3416d1e91b724
Notes: Added thermal management information to `powerMonitor`.
=> feat: add thermal states to powerMonitor

shell/app/electron_main_delegate.cc, shell/common/api/electron_bindings.cc, shell/common/gin_helper/callback.cc, shell/common/gin_helper/locker.cc, shell/common/gin_helper/locker.h, shell/common/gin_helper/microtasks_scope.cc, shell/common/gin_helper/promise.cc, shell/common/gin_helper/promise.h, shell/common/gin_helper/trackable_object.cc, shell/common/node_bindings.cc, shell/common/process_util.cc, shell/common/process_util.h, spec/api-utility-process-spec.ts, spec/fixtures/api/utility-process/eval.js
Regressed with https://github.com/electron/electron/pull/37756
New check introduced in the above PR will default to blink path for code generation in the utility process which is invalid.
Notes: Fix crash when executing eval in the utility process.
=> fix: crash in utilityProcess when generating code from strings

.devcontainer/on-create-command.sh
This PR adds one comma to fix [the errors that cropped up in Codespaces Prebuilds](https://github.com/electron/electron/actions/runs/4749172572/jobs/8436158247), due to some errant copy-pasta from #37765.
Notes: none
=> build: Fix Codespaces prebuilds with missing comma

shell/common/api/electron_api_shell.cc
When calling `shell.openExternal('https://example.com/');` it parses `activate` as `true` correctly.
However calling `shell.openExternal('https://example.com/', {});` would parse `activate` as `false`.
Related to:
https://github.com/electron/electron/blob/0240f6664e5c94d68cb9ad7fb1a9e7c8bbf281d3/shell/common/gin_helper/dictionary.h#L34-L50
Notes: Fixed broken defaults in `shell.openExternal()` options.
=> fix: defaults broken in shell.openExternal() options

patches/angle/.patches, patches/angle/cherry-pick-aed05b609629.patch
M112: Mark RGBX and BGRX formats as having 8 unused bits.
This makes sure that pixelBytes ends up being 4 and fixes potential
buffer size validation.
Fix EGL configs using pixelBytes to compute EGL_BUFFER_SIZE which
is not supposed to include unused bits. This is covered by
dEQP-EGL.functional.query_config.constraints.color_buffer_size
Bug: chromium:1404790
Change-Id: Ie0480cbdc6229c4bb3a6c6242337eaed5a3ae3b7
Reviewed-on: https://chromium-review.googlesource.com/c/angle/angle/+/4428752
Reviewed-by: Amirali Abdolrashidi <abdolrashidi@google.com>
Notes: Security: backported fix for 1404790.
=> chore: cherry-pick aed05b609629 from angle

patches/chromium/.patches, patches/chromium/cherry-pick-63686953dc22.patch
Add lock to AlternativeStateNameMap.
To prevent the class from accessing its localized_state_names_map_ and
localized_state_names_reverse_lookup_map_ members, a lock is added. It
locks all reads/write from the aforementioned members.
(cherry picked from commit dd848883aa0d7d88520846bbf6735eaae9f2b60e)
Bug: 1360571, 1414241, 1425951
Change-Id: Ic01b0cba3878748617863274deb04ec9e13645d4
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4352658
Reviewed-by: Christoph Schwering <schwering@google.com>
Commit-Queue: Florian Leimgruber <fleimgruber@google.com>
Cr-Original-Commit-Position: refs/heads/main@{#1119411}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4402262
Auto-Submit: Florian Leimgruber <fleimgruber@google.com> …
=> chore: cherry-pick 63686953dc22 from chromium

docs/api/session.md
WebUSB API (added with https://github.com/electron/electron/pull/36289) docs and Typescript typings are not correct. 
References:
- `usb-device-added`: https://github.com/electron/electron/blob/f12e12b341cbc202388d704449b2fcf6c1743ae0/shell/browser/usb/usb_chooser_controller.cc#L72
- `usb-device-removed`: https://github.com/electron/electron/blob/f12e12b341cbc202388d704449b2fcf6c1743ae0/shell/browser/usb/usb_chooser_controller.cc#L81
- `usb-device-revoked`: https://github.com/electron/electron/blob/f12e12b341cbc202388d704449b2fcf6c1743ae0/shell/browser/usb/usb_chooser_context.cc#L211
CC: @jkleinsc 
Notes: Fix 'usb-device-added', 'usb-device-removed', 'usb-device-revoked' typings
=> docs: fix 'usb-device-added', 'usb-device-removed', 'usb-device-revoked' typings

patches/config.json, patches/skia/.patches, patches/skia/enforce_size_limits_on_struct_and_array_declarations.patch, patches/skia/reland_enforce_program_stack_limits_on_function_parameters.patch
Reland "Enforce program stack limits on function parameters."
This reverts commit f5715362aac554ff3108b9e2a56b8ac8a6ef1acb.
> Revert "Enforce program stack limits on function parameters."
>
> This reverts commit fa089d61014b77048daddb89300a3ab7cdf601bf.
>
>
> Original change's description:
> > Enforce program stack limits on function parameters.
> >
> > Previously, a function's parameter list did not count against its
> > stack size limit.
> >
> > Bug: chromium:1432603
> > Change-Id: If49dce98f3155f3144a766c26b5a3a39401ce1b2
> > Reviewed-on: https://skia-review.googlesource.com/c/skia/+/670236
> > Auto-Submit: John Stiles <johnstiles@google.com>
> > Commit-Queue: John Stiles <johnstiles@google.com>
> > Reviewed-by: Kevin Lubick <kjlubick@google.com>
> > …
=> chore: cherry-pick 8421a9eebd8a and 4dc670a8c557 from skia

patches/chromium/.patches, patches/chromium/cherry-pick-1d491fff578b.patch, patches/chromium/cherry-pick-2b30a50d0e62.patch, patches/chromium/cherry-pick-ec53103cc72d.patch, patches/chromium/cherry-pick-f098ff0d1230.patch, patches/chromium/cherry-pick-f58218891f8c.patch
<details>
<summary>electron/security#336 - [1d491fff578b](https://chromium-review.googlesource.com/) from chromium</summary>
[Merge M112] Remove the second WeakPtrFactory from SpdyProxyClientSocket
It was introduced [1] to work around an old issue that wouldn't happen
any more since we store a write callback in the class. Instead of having
the second WeakPtrFactory and moving the callback, we can just keep it
until RunWriteCallback() is called.
This is a speculative fix for the linked bug.
[1] https://codereview.chromium.org/338583003/
(cherry picked from commit 01b25615896b911e21103dd381fafc1f85886d91)
Bug: 1428820
Change-Id: I0b5af2675b68188e208c2ecd42293251b2722b28
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4393905
Reviewed-by: Adam Rice <ricea@chromium.org> …
=> chore: cherry-pick 5 changes from Release-2-M112

patches/chromium/.patches, patches/chromium/check_callback_availability_in.patch, patches/chromium/merge_m112_check_spdyproxyclientsocket_is_alive_after_write.patch, patches/chromium/merge_m112_remove_the_second_weakptrfactory_from.patch
[Merge M112] Remove the second WeakPtrFactory from SpdyProxyClientSocket
It was introduced [1] to work around an old issue that wouldn't happen
any more since we store a write callback in the class. Instead of having
the second WeakPtrFactory and moving the callback, we can just keep it
until RunWriteCallback() is called.
This is a speculative fix for the linked bug.
[1] https://codereview.chromium.org/338583003/
(cherry picked from commit 01b25615896b911e21103dd381fafc1f85886d91)
Bug: 1428820
Change-Id: I0b5af2675b68188e208c2ecd42293251b2722b28
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4393905
Reviewed-by: Adam Rice <ricea@chromium.org>
Commit-Queue: Kenichi Ishibashi <bashi@chromium.org>
Cr-Original-Commit-Position: refs/heads/main@{#1125216}
Reviewed-on: …
=> chore: cherry-pick 1d491fff578b, f7b87bea19d7 and 549d92d7ef35 from chromium

patches/chromium/.patches, patches/chromium/cherry-pick-2b30a50d0e62.patch
[M112] Use ScriptState::Scope instead of setting HandleScope.
Since `GetEffectiveFunction` may call `Get` if the given v8 listener is
an object, we need to prepare `v8::Context::Scope` before calling it.
Blink already have a helper class to prepare the environment for the
script execution, which has already been used used in other
ServiceWorkerGlobalScope member functions.  It is `ScriptState::Scope`
This CL also use it instead.
(cherry picked from commit 299385e09d41d5ce3abd434879b5f9b0a8880cd7)
Bug: 1429197
Change-Id: Idbcfdfa9c06160a18b57155a9540f72eed4ec0b8
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4387655
Commit-Queue: Yoshisato Yanagisawa <yyanagisawa@chromium.org>
Commit-Queue: Kouhei Ueno <kouhei@chromium.org>
Reviewed-by: Leszek Swirski …
=> chore: cherry-pick 2b30a50d0e62 from chromium

docs/api/web-contents.md, spec/api-web-contents-spec.ts, spec/chromium-spec.ts
Some APIs may have undefined return values, but they are not reflected in d.ts.
Before:
After:
Notes: none
=> fix: webContents return type incorrect

docs/fiddles/features/notifications/renderer/renderer.js, docs/fiddles/features/offscreen-rendering/main.js, docs/fiddles/features/web-bluetooth/main.js, docs/fiddles/features/web-bluetooth/renderer.js, docs/fiddles/features/web-serial/main.js, docs/fiddles/features/web-usb/renderer.js, docs/fiddles/native-ui/external-links-file-manager/external-links/renderer.js, docs/fiddles/system/clipboard/copy/renderer.js, docs/fiddles/system/clipboard/paste/renderer.js, docs/fiddles/system/system-app-user-information/app-information/renderer.js, docs/fiddles/tutorial-preload/renderer.js, docs/fiddles/windows/manage-windows/frameless-window/main.js, docs/fiddles/windows/manage-windows/manage-window-state/main.js, docs/fiddles/windows/manage-windows/new-window/main.js, docs/fiddles/windows/manage-windows/window-events/main.js, package.json
Follow-up to #37689, which fixes the remaining linting errors and promotes `lint:docs-fiddles` up into `lint:docs`.
There's quite a few out-of-date fiddles under `docs/fiddles`, they could definitely use some fixing up, but for now always linting them should help stop new errors from creeping in.
Notes: none
=> chore: always lint JS in docs/fiddles

patches/chromium/.patches, patches/chromium/cherry-pick-f098ff0d1230.patch
[m112] Retain DevToolsAgentHost after ForceDetachAllSessions()
(cherry picked from commit 8c4aee2a90d08535cfb1bf0a59e00cae956b1762)
Bug: 1424337
Change-Id: Ie0ebe2a49ffbd2356b896c39446b93e09cd81f5a
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4378100
Reviewed-by: Dmitry Gozman <dgozman@chromium.org>
Commit-Queue: Andrey Kosyakov <caseq@chromium.org>
Cr-Original-Commit-Position: refs/heads/main@{#1123772}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4420271
Commit-Queue: Srinivas Sista <srinivassista@chromium.org>
Cr-Commit-Position: refs/branch-heads/5615@{#1244}
Cr-Branched-From: 9c6408ef696e83a9936b82bbead3d41c93c82ee4-refs/heads/main@{#1109224}
Ref electron/security#316
Notes: Security: backported fix for CVE-2023-2135.
=> chore: cherry-pick f098ff0d1230 from chromium

spec/api-browser-window-spec.ts
Refs https://github.com/electron/electron/issues/30140.
Re-enable multiple window fullscreen inheritance test. This was disabled because it was flaking at the point the second window was opened, which upon investigation is a small bug in AppKit which means that `windowDidEnterFullScreen` fires in a way that creates a race condition with a second window opening. With a short enough timeout, the second window doesn't correctly reflect the fullscreen status of the first one, and doesn't open in fullscreen. This is fixed consistently with a 1 second delay.
Notes: none
=> test: re-enable multi-window fullscreen test

.clang-tidy, shell/browser/api/electron_api_desktop_capturer.cc, shell/browser/api/electron_api_system_preferences.cc, shell/browser/api/electron_api_system_preferences_mac.mm, shell/browser/api/electron_api_utility_process.cc, shell/browser/api/gpu_info_enumerator.cc, shell/browser/bluetooth/electron_bluetooth_delegate.cc, shell/browser/electron_permission_manager.cc, shell/browser/file_select_helper.cc, shell/browser/font_defaults.cc, shell/browser/linux/unity_service.cc, shell/browser/net/asar/asar_url_loader.cc, shell/browser/ui/file_dialog_gtk.cc, shell/browser/ui/file_dialog_mac.mm, shell/browser/ui/webui/accessibility_ui.cc, shell/browser/usb/usb_chooser_context_factory.cc, shell/browser/usb/usb_chooser_controller.cc, shell/common/gin_helper/trackable_object.cc, shell/common/platform_util_linux.cc, shell/renderer/electron_autofill_agent.cc
Fixes the current warnings from `clang-tidy`, other than `modernize-use-nullptr` which I'm disabling for now as there's too much noise.  There's a couple false positives I had to silence with `// NOLINT`.
The goal is to add a `clang-tidy` CI job, but that will be done in a future PR.
For completeness, here is the `clang-tidy` output without the fixes:
<details><summary>Warnings</summary>
```
../../electron/shell/common/gin_helper/trackable_object.cc:24:3: warning: 'operator int' must be marked explicit to avoid unintentional implicit conversions [google-explicit-constructor]
operator int32_t() const { return id_; }
^
explicit 
../../electron/shell/browser/api/electron_api_desktop_capturer.cc:246:35: warning: unnecessary temporary object created while calling emplace_back …
```
=> chore: fix clang-tidy warnings

docs/tutorial/accessibility.md, shell/browser/mac/electron_application.mm
Closes https://github.com/electron/electron/issues/37465.
Fixes an issue where using Swift etc to enable various a11y features within Electron using the `AXManualAccessibility` attribute would appear to fail. This was happening because we were always calling `[super accessibilitySetValue:value forAttribute:attribute]` in our override, and the custom attribute would always fail when that superclass function was shown. After this fix, the attribute correctly reflects success, with no failure and the `accessibility-support-changed` event correctly emitted on `app`.
I also took the opportunity to update the documentation a little to reflect multiple approaches.
Tested using the Swift REPL and the following code:
```swift
import Cocoa
let name = CommandLine.arguments.count >= 2 ? …
```
=> fix: `AXManualAccessibility` showing failure

shell/browser/api/electron_api_web_contents.h, shell/browser/extensions/electron_extensions_api_client.cc
This PR surfaces context menu handling from extensions. This means that, among other thing, developers can now create context menus for PDF documents.
Notes: Surface the `context-menu` event from extensions.
=> feat: emit `context-menu` event from extensions

shell/browser/ui/cocoa/electron_inspectable_web_contents_view.mm
Backport of https://github.com/electron/electron/pull/38100
Notes: Fixed a potential crash when right-clicking on macOS windows with draggable regions.
=> fix: crash on missing `RenderWidgetHostView`

shell/browser/api/electron_api_web_contents.h
These methods implement `content::WebContentsDelegate`:
https://github.com/electron/electron/blob/a2d35e9cf53f324d8153cb56982074e1af5fb177/shell/browser/api/electron_api_web_contents.h#L693-L697
Notes: none
=> chore: add missing content::WebContentsDelegate section

docs/api/net.md, lib/browser/api/net.ts
See https://github.com/electron/electron/pull/37690
This adds `net.resolveHost` method that uses `defaultSession` to resolve hosts (similar to `net.fetch`).
cc @nornagon 
Notes: Add net.resolveHost that resolves hosts using defaultSession object
=> feat: net.resolveHost

lib/browser/api/web-contents.ts, shell/browser/web_contents_preferences.cc, spec/api-browser-window-spec.ts, spec/guest-window-manager-spec.ts, spec/lib/screen-helpers.ts
Fixes #37737.
Fixes #36538.
Falsy values for `transparent` were incorrectly setting the `webContents` background to be transparent. This was only noticeable in certain situations, since setting a background color for the page would override the transparency. It would affect child windows without any explicit setting of `transparent` due to the usage of an empty object for browser window options in those cases which led to the `transparent` key being set with a value of `undefined`, triggering the bug.
Notes: Fixed an issue where default background color for windows might be incorrect
=> fix: falsy transparent shouldn't affect webContents background

docs/tutorial/tutorial-3-preload.md
Fixes #38137 by moving the `icpMain.handle` call out of the `createWindow` function to `app.whenReady`.
=> docs: moves icpMain.handle call in tutorial part 3

shell/browser/api/electron_api_web_contents.cc, shell/browser/api/electron_api_web_contents.h
Refs https://chromium-review.googlesource.com/c/chromium/src/+/4255184
Implements `WebContentsDelegate::GetFullscreenState` and resolves an error now seen intermittently in the console: 
```
[77991:0502/100511.081484:ERROR:web_contents_delegate.cc(174)] Not implemented reached in virtual FullscreenState content::WebContentsDelegate::GetFullscreenState(const WebContents *) const
```
Notes: none
=> chore: implement `WebContentsDelegate::GetFullscreenState`

spec/api-web-contents-view-spec.ts, spec/extensions-spec.ts
Nothing is broken, but this way it is a bit more readable.
Also, in all other places that's how `closeWindow` is called now.
Notes: none
=> test: use `await` to call "closeWindow"

shell/browser/file_select_helper.cc, shell/browser/file_select_helper.h
Refs CL:4424786
From the CL:
> FileSelectHelper already observes RenderFrameDeleted and
RenderFrameHostChanged to clear its RenderFrameHost reference.  This
means that the RenderWidgetHost observer, which is also used to clear
the RFH reference, is redundant, since it shouldn't be possible to
destroy a RFH's RWH without triggering destruction of the RFH itself.
> This CL removes the RWH observation logic, since it is not only
redundant, but also incorrect for OOPIFs, since the RWH being observed
was retrieved from the frame's RenderViewHost, and that is not going
to be the right RWH for an OOPIF.
Notes: none
=> chore: stop using a `RenderWidgetHost` observer in `FileSelectHelper`

docs/api/net.md, lib/browser/api/net.ts
Backport of #37853.
Notes: Add net.resolveHost that resolves hosts using defaultSession object
=> feat: `net.resolveHost`

docs/api/session.md, docs/tutorial/devices.md
`USBDevice` was missing as a possible type for `device`.
Notes: none
=> docs: fix typing of session.setDevicePermissionHandler

.gitattributes
Ran into an issue with this today in an `.idl` file. Update our `.gitattributes` file to more closely match [Chromium's](https://source.chromium.org/chromium/chromium/src/+/main:.gitattributes)
Notes: none
=> build: force LF checkout of more files

spec/asar-spec.ts
See #38192:
> This test seems to flake only on ASan builds. The DCHECK below seems to obscure any information the `v8::internal::Isolate::StackOverflow()` method would normally expose.
>
> There's no information in the failed test output that points specifically to this test, however this is always the test that should be running when the crash occurs, so I'm identifying this test as the source of the flake.
Notes: none
=> test: disable flaky asar worker test on ASan build

docs/tutorial/notifications.md
This PR updates the link to Apple's Human Interface guidelines for notifications in macOS in Electron's notifications guide. The link has changed and the current link in the docs points to a page that no longer exists.
Notes: none
=> docs: update dead link to Apple Human Interface notification guidelines

.github/workflows/issue-commented.yml, .github/workflows/issue-labeled.yml
This should drop GHA usage of these workflows significantly since the jobs won't need to be started if the conditional is false. Also improves the UX since the workflow runs will show which were skipped without needing to click into each run.
Notes: none
=> ci: do conditional in blocked/need-repro workflows at job level

.circleci/config/base.yml, spec/crash-spec.ts, spec/index.js
We've been granted early access to the preview of [CircleCI's "re-run failed tests only" feature](https://circleci.com/docs/rerun-failed-tests-only/). This PR updates our test suite runner and CircleCI config to enable this feature to work.
Notes: none
=> test: enable CircleCI's "re-run failed tests only" feature

shell/browser/ui/webui/accessibility_ui.cc
Refs CL:4219030
Fixes the following error seen when loading `chrome://accessibility`, which prevented the Top Level Windows section from populating:
```
[59750:0504/101326.049599:ERROR:CONSOLE(27)] "Refused to create a TrustedTypePolicy named 'sanitize-inner-html' because it violates the following Content Security Policy directive: "trusted-types ".", source: chrome://resources/js/parse_html_subset.js (27)
[59750:0504/101326.049984:ERROR:CONSOLE(27)] "Uncaught TypeError: Failed to execute 'createPolicy' on 'TrustedTypePolicyFactory': Policy "sanitize-inner-html" disallowed.", source: chrome://resources/js/parse_html_subset.js (27)
```
Notes: Fixed an error seen in the Top Level Windows section of `chrome://accessibility`.
=> chore: fix TrustedTypes policy in `chrome://accessibility`

.github/workflows/branch-created.yml
Creates the new version labels when a branch matching `N-x-y` is created and grays out the unsupported labels.
This also labels any existing PRs which are still being backported to `(N-1)-x-y` to also target the new branch, which I believe should address https://github.com/electron/trop/issues/248.
Notes: none
=> ci: automate release label tasks

package.json
To better support running tests without doing a build. A build generates `electron.d.ts` via the `gn-typescript-definitions` script.  Running the `create-typescript-definitions` in `pretest` should ensure the TS definitions exist and are up-to-date when switching branches.
Notes: none
=> build: add pretest script to create TS definitions

patches/chromium/.patches, patches/chromium/wayland_ensure_dnd_buffer_size_is_a_multiple_of_scale.patch
Manual backporting of [4099423](https://chromium-review.googlesource.com/c/chromium/src/+/4099423) for fixing a drag-and-drop crash on [wlroots](https://gitlab.freedesktop.org/wlroots/wlroots/) based compositors (e.g.: sway, Hyprland, wayfire, etc).
This is currently causing crashes for vscode users on Wayland (https://github.com/microsoft/vscode/issues/179836 and possibly also https://github.com/microsoft/vscode/issues/181533).
Notes: Fixed drag-and-drop crash on Wayland.
=> chore: cherry-pick d42c3e5fb7c3 from chromium

shell/browser/mac/electron_application.mm
Follow-up to https://github.com/electron/electron/pull/38102. Ensure that Electron's custom `AXManualAccessibility` attribute works as expected in all relevant protocol methods.
Notes: Ensure that Electron's custom `AXManualAccessibility` attribute works as expected in all relevant protocol methods.
=> fix: handle `AXManualAccessibility` attribute cross-protocol

patches/chromium/printing.patch
Backport of https://github.com/electron/electron/pull/38165
Notes: Fixed a potential crash when calling `webContents.print` with invalid settings.
=> fix: printing crash when settings invalid

package.json, patches_npm/@octokit+request+6.2.3.patch, yarn.lock
[(See similar PR for 25-x-y)](https://github.com/electron/electron/pull/38237)
CircleCI recently updated the Mac 14 images, which changed the version of Node used for releases. Because of this, we're now running into a known Node issue on the Mac release upload job. Specifically, [an error within @octokit/request where POST calls don't include a duplex option in the request](https://github.com/octokit/rest.js/issues/267), and cause the request to fail.
[A fix has been merged upstream](https://github.com/octokit/request.js/pull/571), but a new version of octokit/request hasn't yet been released, so this PR uses patch-package to patch in the fix instead.
Notes: none
=> build: fix octokit resolution with patch-package

build/args/all.gn
[This commit was relanded](https://chromium-review.googlesource.com/c/v8/v8/+/4406038) in the last Chromium roll, which now causes builtins PGO to break the release builds. This PR disables the builtins PGO in Electron, as we don't ship the needed profiling information with mksnapshot anyway.
Note: Please don't merge until the publish-linux job passes.
Notes: none
=> build: disable v8 builtins pgo

docs/api/web-contents.md, shell/browser/api/electron_api_web_contents.cc
Follow-up to https://github.com/electron/electron/pull/38183.
Adds missing cursor types and corrects a previous error.
Notes: Added several new cursor values to the `cursor-changed` event.
=> feat: add missing 'cursor-changed' type values

build/generate_node_defines.py
This repository follows PEP 8.
In this case, the variable `outDir` should be replaced with `out_dir`.
PEP 8 Style Guide: https://peps.python.org/pep-0008/#descriptive-naming-styles
Google Python Style Guide (a superset of PEP 8): https://google.github.io/styleguide/pyguide.html#316-naming
Notes: none
=> fix: variable name should comply with naming convention

.circleci/config/base.yml, script/verify-chromedriver.py
We shouldn't need this anymore, if this is green we merge it 🥳 
=> build: drop python2 from CI

shell/browser/native_window_mac.mm, spec/api-browser-window-spec.ts
When an NSWindow is initially minimized on macOS, it's possible for `[window_ isZoomed]` to be true
when the window is minimized or fullscreened. This adds an explicit guard to fix that, thereby matching [Chromium behavior](https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/ui/views/apps/chrome_native_app_window_views_mac.mm;l=145-148?q=window%20%22isZoomed%5D%22%20%22minimized%22&sq=package:chromium).
See https://github.com/electron/electron/pull/38234#issuecomment-1546518668
Notes: Fixed an issue where `BrowserWindow.isMaximized()` could incorrectly return true for minimized or fullscreened windows on macOS.
=> fix: `isMaximized` after minimize/fullscreen on macOS

lib/browser/api/browser-window.ts, spec/api-browser-window-spec.ts
Closes https://github.com/electron/electron/issues/38170.
Enable access to `BrowserWindow.id` after the window has been destroyed.
Notes: Fixed an issue where accessing `BrowserWindow.id` threw an error after the window was destroyed.
=> fix: enable `BrowserWindow.id` access post-destruction

docs/api/browser-window.md, shell/browser/native_window_mac.mm, shell/browser/native_window_views.cc, spec/api-browser-window-spec.ts
Some debugging recently alerted me to the fact that `BrowserWindow.isVisible()` incorrectly differs cross-platform. On macOS, a window only returns `true` for `isVisible()` if the window is in the foreground and not minimized. However, on Windows, a window could be minimized and yet incorrectly show as visible. This corrects that schism.
Notes: Fixed an issue where `BrowserWindow.isVisible()` would incorrectly return `true` for minimized windows on Windows.
=> fix: unify `BrowserWindow.isVisible()` logic cross-platform

spec/api-protocol-spec.ts, spec/disabled-tests.json, spec/version-bump-spec.ts
Some of our disabled tests aren't actually broken and can simply be re-enabled.
Also, I removed a test that was old and basically just checked that giving a number where a string was expected would throw an error, where it has long since just been silently ignored instead. I find the behavior here to be negligible and am just opting to remove the test.
Notes: none
=> test: re-enable tests that aren't broken & remove old test

shell/browser/native_window_views.cc, spec/api-browser-window-spec.ts
Fixes an issue where calling `win.minimize()` directly after calling `win.maximize()`, and then calling `win.isMaximized()` incorrectly returns `true`.
This is happening because widget methods don't work as expected in several cases for transparent windows, and so we fall back to an approximation approach where we compare bounds. However, bounds when minimized match the screen area when minimized, so the resulting comparison can false positive to true. We should ensure it's not minimized before proceeding.
Notes: Fixed an issue where calling `win.minimize()` directly after calling `win.maximize()`, and then calling `win.isMaximized()` incorrectly returns `true`.
=> fix: `win.isMaximized()` for transparent windows on Windows

shell/browser/native_window_views.cc, spec/api-browser-window-spec.ts
Closes https://github.com/electron/electron/issues/38180.
Fixes an issue where `getNormalBounds()` returns incorrect bounds when a BrowserWindow is transparent and maximized. The underlying logic in widget doesn't account well for the transparent case - this is something we [already account for](https://github.com/electron/electron/blob/3ce35f224efa3a6e9bfc9b642816961b8691491b/shell/browser/native_window_views_win.cc#L190-L194) in [other areas](https://github.com/electron/electron/blob/eb0f47d377841d17f7880e42e23e7cd451d19fbe/shell/browser/native_window_views.cc#L617-L621). 
Notes: Fixed an issue where `getNormalBounds()` returns incorrect bounds for transparent maximized windows on Windows.
=> fix: `getNormalBounds()` for transparent windows on Windows

.circleci/config/base.yml
Switch to unified patch and also ensure `depot_tools` doesn't update during CI runs.
Notes: none
=> build: modify `gclient.py` with unified patch

docs/api/browser-window.md, shell/browser/api/electron_api_base_window.cc, shell/browser/api/electron_api_base_window.h, shell/browser/native_window.cc, shell/browser/native_window.h, shell/browser/native_window_views.cc, shell/browser/native_window_views.h, shell/common/options_switches.cc, shell/common/options_switches.h
Backport of #38163.
Notes: Add support for Mica and Acrylic background effects on Windows.
=> feat: support Mica/Acrylic on Windows

docs/api/webview-tag.md
Like the partition, changing the `disablewebsecurity` attribute on a `webview` doesn't work. There is no exception, but if changed after creation there is no actual change in the websecurity setting of the underlying webcontents.
Notes: none
=> docs: disablewebsecurity on webview-tag can not be changed for an active session

shell/browser/api/electron_api_web_contents.h
Fix the [dangling_raw_ptr](https://chromium.googlesource.com/chromium/src.git/+/main/docs/dangling_ptr.md) warning discussed in https://github.com/electron/electron/pull/38167. (There is at least one more I'm still tracking down, so this PR doesn't re-enable the leak checks in CI yet.)
This one was mostly harmless: `electron::api::WebContents` had two fields declared in this order:
```c++
raw_ptr<WebContentsZoomController> zoom_controller_ = nullptr;
std::unique_ptr<InspectableWebContents> inspectable_web_contents_;
```
The problem is that `inspectable_web_contents_` owns the object pointed to by `zoom_controller_`, so when `~WebContents()` is run and the fields are destroyed in reverse order, `inspectable_web_contents_` is destroyed first, causing `zoom_controller_` to be (temporarily) …
=> fix: `dangling_raw_ptr` warning in `electron_api_web_contents`

shell/browser/electron_browser_context.cc, spec/api-media-handler-spec.ts
Closes https://github.com/electron/electron/issues/38381.
Fixes an issue where `MediaStreamTrack.getCaptureHandle()` always returned `null`. This was happening because we were not properly setting `display_media_info` on each `blink::MediaStreamDevice` in our permission handling.
Verified with https://gist.github.com/t57ser/919ff9c9fe623b51fde41772bf4c9207
Notes: Fixed an issue where `MediaStreamTrack.getCaptureHandle()` always returned `null`.
=> fix: `MediaDevices` missing `DisplayMediaInformation`

lib/isolated_renderer/init.ts, lib/sandboxed_renderer/init.ts, typings/internal-ambient.d.ts
Declare the globals for each init separately. Also reuse `WebViewImplHooks` for  `isolatedApi` type
https://github.com/electron/electron/blob/e7b8bb4766da58fa693ec3e82c0af9b0a3406c9d/lib/renderer/web-view/web-view-impl.ts#L14-L18
Notes: none
=> refactor: cleanup global variable declarations

BUILD.gn, filenames.gni
"pdf_viewer_private_api.{cc,h}" should only be compiled when `enable_pdf_viewer=true`.
Related to #38127.
Notes: none
=> build: fix build with "enable_pdf_viewer=false"

BUILD.gn, build/webpack/webpack.config.base.js, buildflags/BUILD.gn, buildflags/buildflags.gni, chromium_src/BUILD.gn, filenames.gni, lib/browser/api/module-list.ts, shell/browser/api/electron_api_base_window.cc, shell/common/api/features.cc, shell/common/node_bindings.cc, spec/api-browser-window-spec.ts, spec/api-desktop-capturer-spec.ts, spec/api-media-handler-spec.ts, typings/internal-ambient.d.ts
Disabling `enable_desktop_capturer` only saves around 40 KB in the generated binaries.
Notes: The `enable_desktop_capturer` build flag has been removed.
=> build: remove enable_desktop_capturer flag

docs/api/app.md
Tweak code samples in `app.md` so that they're minimally runnable.
Notes: none
=> docs: ensure `app.md` examples are runnable

package.json, yarn.lock
Refs #38346.
Refs https://github.com/electron/github-app-auth/pull/9.
Lets us drop the resolution for `@octokit/request@6.2.4` and clears these warns:
```
warning Resolution field "@octokit/request@6.2.4" is incompatible with requested version "@octokit/request@^5.6.0"
warning Resolution field "@octokit/request@6.2.4" is incompatible with requested version "@octokit/request@^5.6.3"
warning Resolution field "@octokit/request@6.2.4" is incompatible with requested version "@octokit/request@^5.4.14"
warning Resolution field "@octokit/request@6.2.4" is incompatible with requested version "@octokit/request@^5.6.3"
warning Resolution field "@octokit/request@6.2.4" is incompatible with requested version "@octokit/request@^5.4.14"
warning Resolution field "@octokit/request@6.2.4" is incompatible …
```
=> build: upgrade @electron/github-app-auth to 2.0.0

shell/browser/ui/inspectable_web_contents.cc, shell/browser/ui/inspectable_web_contents.h
`InspectableWebContents::GetAll()` is unused and its implementation keeps a persistent `std::list<>` allocated in an anonymous namespace, so this PR removes it.
No particular stakeholders, but review welcomed from anyone
Notes: none
=> refactor: remove InspectableWebContents::GetAll()

shell/browser/ui/win/electron_desktop_window_tree_host_win.cc, shell/browser/ui/win/electron_desktop_window_tree_host_win.h
Closes https://github.com/electron/electron/issues/38385.
Refs CL:4435695.
Fixes an issue where Windows `FrameView`s always appeared inactive regardless of focus status. This was happening because Chromium added extra plumbing to set active state as a function of whether or not in `delegate_->ShouldPaintAsActive();` was `true` in `HWNDMessageHandler::PaintAsActiveChanged()`, and we'd overridden it to return false.
Confirmed not to regress https://github.com/electron/electron/issues/24647.
Notes: Fixes an issue where Windows `FrameView`s always appeared inactive regardless of focus status.
=> fix: Windows FrameView always appearing inactive

script/yarn.js
`process.mainModule` is long since deprecated - this should be `require.main`.
Notes: none
=> chore: `process.mainModule` -> `require.main`

DEPS
As in title - they should match version formatting of other deps.
Notes: none
=> build: make ReactiveObjC/Mantle deps format consistent

shell/browser/api/electron_api_base_window.cc, shell/browser/api/electron_api_global_shortcut.cc, shell/browser/api/electron_api_power_save_blocker.cc, shell/browser/api/electron_api_power_save_blocker.h, shell/browser/api/electron_api_web_contents.cc, shell/browser/api/electron_api_web_request.cc, shell/browser/api/message_port.cc, shell/browser/hid/hid_chooser_controller.cc, shell/browser/native_window.cc, shell/browser/native_window_views.cc, shell/browser/printing/print_view_manager_electron.cc, shell/browser/ui/message_box_win.cc, shell/common/api/electron_api_clipboard.cc, shell/common/api/electron_bindings.cc, shell/common/key_weak_map.h, shell/renderer/api/electron_api_context_bridge.cc, shell/renderer/api/electron_api_spell_check_client.cc, shell/renderer/electron_renderer_client.cc, shell/renderer/electron_sandboxed_renderer_client.cc
A minor readability refactor to prefer `base::Contains()` over `std::find(begin(), end(), foo) != end()`.
No behavioral changes & no stakeholders in particular, but all reviews are welcomed.
Notes: none
=> refactor: prefer base::Contains() over find() + end()

script/prepare-appveyor.js, script/release/prepare-release.js
It also solves two more eslint suppressions started by #38417
Notes: none
=> refactor: use literals instead of new RegExp() where possible

shell/browser/native_window.h, shell/browser/native_window_mac.h, shell/browser/native_window_mac.mm, shell/browser/ui/cocoa/electron_ns_window_delegate.mm, spec/api-browser-window-spec.ts
Closes https://github.com/electron/electron/issues/38459.
[`NativeWidgetNSWindowBridge::NotifyVisibilityChangeDown()`](https://source.chromium.org/chromium/chromium/src/+/main:components/remote_cocoa/app_shim/native_widget_ns_window_bridge.mm;l=1667) expects that the parent window's children have all been hidden before the window is hidden, or there is a DCHECK. This fixes that.
We previously solved something similar in https://github.com/electron/electron/issues/29821 - however, here, we can't just detach the windows. The children need to reappear when the window becomes visible again, so we instead need to add some mechanics to hide and restore windows appropriately. I took my cue upstream from [`components/remote_cocoa/app_shim/native_widget_ns_window_bridge.mm`](https://source.chromium …
=> fix: DCHECK minimizing parent window with non-modal child

shell/browser/api/electron_api_content_tracing.cc, spec/api-content-tracing-spec.ts
Reject with a more descriptive error when `contentTracing.stopRecording()` fails because no trace was in progress.
Notes: Improve error message when `contentTracing.stopRecording()` fails because no trace was in progress.
=> chore: make `contentTracing.stopRecording()` failure clearer

shell/browser/browser_process_impl.cc, shell/browser/browser_process_impl.h, shell/browser/electron_browser_main_parts.cc, spec/chromium-spec.ts
Closes https://github.com/electron/electron/issues/38484.
Fixes an issue where `navigator.connection` returned incorrect data. This was happening because we never set up the observer plumbing to set the correct values.
Notes: Fixed an issue where `navigator.connection` returned incorrect data.
=> fix: `navigator.connection` not working as intended

shell/common/electron_constants.cc, shell/common/electron_constants.h, shell/common/options_switches.cc, shell/common/options_switches.h
Cleanup PR that removes leftover `electron::switches` that are no longer used.
No particular stakeholders, but all reviews welcomed. :smile_cat: 
Notes: none
=> refactor: remove unused switches

docs/api/session.md, docs/fiddles/features/web-usb/main.js, docs/tutorial/devices.md, shell/browser/api/electron_api_session.cc, shell/browser/api/electron_api_session.h, shell/browser/electron_permission_manager.cc, shell/browser/electron_permission_manager.h, shell/browser/usb/electron_usb_delegate.cc, shell/common/gin_converters/usb_protected_classes_converter.h
Backport of #38263
Notes: Added setUSBProtectedClassesHandler to allow access to protected USB classes with WebUSB.
=> feat: add USB protected classes handler

appveyor-woa.yml, appveyor.yml
Refs https://help.appveyor.com/discussions/problems/28242-exit-appveyorbuild-command-doesnt-work-in-if-statement
Fixes doc-only script exit not actually exiting on Appveyor, as seen [here](https://ci.appveyor.com/project/electron-bot/electron-ia32-testing/builds/47196053/job/b740sas00gsr8j7n?fullLog=true#L32).
Notes: none
=> build: fix doc-only early exit on Appveyor

shell/browser/electron_browser_context.cc, shell/browser/mac/dict_util.mm, shell/browser/usb/usb_chooser_context.cc, shell/common/gin_converters/extension_converter.cc, shell/common/gin_converters/value_converter.cc, shell/common/gin_converters/value_converter.h
Avoid redundant / unnecessary calls to `base::Value::Clone()`, `base::Value::List::Clone()`, `base::Value::Dict::Clone()`:
Most of this is updating our code to use `base::ValueView` introduced [here](https://chromium-review.googlesource.com/c/chromium/src/+/3466767). tl;dr it's a read-only adapter for Value, Value::Dict, and Value::List.
- when we're converting dicts and lists to V8, use `base::ValueView` to pass originals by const ref instead of cloning. (This really just involves us marshalling the args correctly,  since upstream code `V8ValueConverter` [already uses `base::ValueView`](https://chromium-review.googlesource.com/c/chromium/src/+/3737382).)
- the previous change allows a couple of one-off improvements, e.g. avoid cloning when emitting `usb-device-revoked`
- since …
=> perf: avoid unnecessary base value clone

shell/browser/api/electron_api_view.cc, shell/browser/api/electron_api_view.h
Remove code in `electron::api::View` that was added in 2c8dc9e but is now unused. Short discussion today in `#ask-anything` from with @zcbenz confirming it should be safe to just remove the code.
CC: @zcbenz 
Notes: none
=> chore: remove unused electron::api::View code

shell/browser/native_window_views.cc, shell/browser/native_window_views.h
**What:** Before and after this PR, `NativeWindowViews` owns a `RootView` and `KeyboardEventHandler` that are created in the constructor and destroyed in the destructor. Previously they were implemented as `unique_ptr`s. This PR removes the `unique_ptr` wrapper and aggregates them directly.
**Why:** we pass a *lot* of pointers around and it's often difficult to tell who owns a pointer & what its lifecycle is. Using direct aggregation makes it explicit and clear that these two fields' lifecycles are identical to the NativeWindowViews that owns them.
If the team is OK with this change there are other places where similar changes are possible, so for this trial balloon PR I'm CC'ing people who have been active in shell/lbrowser/ui and shelll/browser/api recently: @codebytere @deepak1556 …
=> refactor: use direct aggregation in NativeWindowViews

docs/tutorial/sandbox.md
=> docs: clarify which electron modules are exposed in sandboxed renderers

shell/browser/ui/file_dialog_mac.mm
Refs [crbug.com/1357523](crbug.com/1357523)
Fixes an issue where files could in some circumstances be selection when `openFile` was not passed as a dialog property. Essentially, there's a bug in macOS where despite a request to disallow file selection, files/packages can be selected. If file selection was disallowed, we should drop any files selected.
Reproducible with the following:
<details><summary>Code Snippet</summary>
```js
const { app, BrowserWindow, dialog } = require('electron')
app.whenReady().then(() => {
const mainWindow = new BrowserWindow()
dialog.showOpenDialog(mainWindow, { properties: [] }).then(result => {
if (result.canceled) {
console.log('Dialog was canceled')
} else if (result.filePaths.length > 0) {
const file = result.filePaths[0] …
```
=> fix: file selection when disallowed on macOS

shell/browser/native_window_views.cc, shell/browser/native_window_views.h
Manual backport of #38559. See that PR for details.
Code is same as 38559; trop failed due to minor code shear.
Notes: none
=> refactor: in NativeWindowViews, aggregate fields directly

shell/browser/electron_autofill_driver.cc
Closes https://github.com/electron/electron/issues/38245.
Fixes an issue where `<datalist>` popup positioning did not account for the possibility of the `WebContents` belonging to a `BrowserView` and adjust accordingly.
</details>
</details>
Notes: Fixes an issue where `<datalist>` popups are positions incorrectly in `BrowserView`s.
=> fix: account for `BrowserView` bounds in setting autofill popup bounds

shell/browser/ui/inspectable_web_contents.cc, shell/browser/ui/inspectable_web_contents.h
A simplicity cleanup: `InspectableWebContents` aggregates a `DevToolsContentResizingStrategy` solely for checking whether the input arg of `SetInspectedPageBounds()` changes the resizing strategy so that we only call `view_->SetContentsResizingStrategy()` if it's changed. We don't need do this, since  [upstream already tests it for us](https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/ui/views/frame/contents_layout_manager.cc;l=20).
The upstream check has been present since 2013 so this is backport-safe. :smile_cat: 
This small change gives us a handful of small wins:
- Simplifies our code a little
- Avoids minor redundant operations
- Reduces the size of IWC by `sizeof(DevToolsContentResizingStrategy)`
- Removes `resizing_strategy.h` from the IWC header
Notes: none
=> refactor: remove redundant resizing strategy equality check

docs/api/structures/web-preferences.md, shell/browser/web_contents_preferences.cc
Added `math` option to `defaultFontFamily` in webPreferences to allow customization of the default math font along with other fonts.
Notes: Added support for customization of the default math font along with other fonts.
@zcbenz @deepak1556
=> feat: Allow customizing the default math font

shell/browser/api/electron_api_screen.cc, shell/browser/api/electron_api_screen.h
Sync the signatures of the `api::Screen`'s Display wrappers  to match the `ui::Display` methods that they wrap:
- make `GetAllDisplays()` const and return a const reference. Currently we're always returning a new vector.
- make `GetPrimaryDisplay()` const
- make `GetDisplayNearestPoint()` const
- make `GetDisplayMatching()` const
Notes: none
=> fix: sync api::Screen wrapper method sigs to upstream

lib/browser/api/protocol.ts, spec/api-protocol-spec.ts
Closes https://github.com/electron/electron/issues/38553.
Fixes invalid protocol response parameter validation `protocol.handle()`.
Notes: Fixes potential invalid protocol error handling.
=> fix: validate response in `protocol.handle()`

lib/browser/api/web-contents.ts
Fixes https://github.com/electron/electron/issues/38598.
Fixes an issue where passing `webContents.print(null)` would trigger the following error:
```console
Cannot read properties of null (reading 'pageSize').
```
This was happening because we weren't properly validating `options`.
Notes: Fixes an issue where passing `webContents.print(null)` could incorrectly trigger an error.
=> fix: bad error passing `webContents.print(null)`

yarn.lock
This PR bumps @octokit/request to 6.2.5, to fix a Node error during publishing
Notes: none
=> build: uuaw @octokit/request to 6.2.5

shell/browser/osr/osr_render_widget_host_view.cc, shell/browser/osr/osr_render_widget_host_view.h
Literally just removing unused fields.
Notes: none
=> refactor: remove unused OffScreenRenderWidgetHostView  fields

.circleci/config/base.yml, BUILD.gn, build/fake_v8_context_snapshot_generator.py
I'm not 100% sure that this is cost effective but raising the PR for review while I do the money math.  This loosely would make our `darwin arm64` build / test process twice as fast.
* Current P50 - 67 minutes
* New average runtime (across 3 runs) 27 minutes
It also greatly simplifies some of the hacks we have around "fake" snapshots 🙃  
Worth noting that I considered moving our x64 build to m1 hosts too but that (a) reintroduces some x-compilation complexity and (b) is almost certainly cost effective
=> build: use m1 hosts to build apple silicon binaries

script/release/release.js
[Sudowoodo expects to find an error logged on `stderr` when the script fails.](https://github.com/electron/sudowoodo/blob/57a758e7ec1d873bf7d359e13c2e7003cd78db4b/src/operations/validate.ts#L21)
Also adds a missing `process.exit(1)` for an error in `createReleaseShasums`.
Notes: none
=> build: improve error output in release.js

patches/v8/.patches, patches/v8/cherry-pick-0035a4a8dac2.patch, patches/v8/cherry-pick-73af1a19a901.patch
<details>
<summary>electron/security#362 - 73af1a19a901 from v8</summary>
Merged: [lookup] Robustify LookupIterator against own lookups
... on non-JSReceiver objects.
Bug: chromium:1447430
(cherry picked from commit 515f187ba067ee4a99fdf5198cca2c97abd342fd)
Change-Id: Ib9382d90ce19d6b55ee0b236dd299ded03ade04d
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/4575069
Cr-Commit-Position: refs/branch-heads/11.4@{#35}
Cr-Branched-From: 8a8a1e7086dacc426965d3875914efa66663c431-refs/heads/11.4.183@{#1}
Cr-Branched-From: 5483d8e816e0bbce865cbbc3fa0ab357e6330bab-refs/heads/main@{#87241}
</details>
<details>
<summary>electron/security#361 - 0035a4a8dac2 from v8</summary>
Merged: [ic] …
=> chore: cherry-pick 2 changes from Release-1-M114

docs/api/app.md
Docs for property `app.badgeCount` indicate that you need notifications permission in your app for the badge count to appear.
However, `app.setbadgeCount()` docs don't say this, even when you do need the same permission.
This PR adds the same note in `app.setbadgeCount()`.
Notes: none
=> docs: indicate `app.setBadgeCount()` needs notifications permission to work

shell/browser/electron_permission_manager.cc
Fix a few differences between our `PermissionManager` and [`ShellPermissionManager`](https://source.chromium.org/chromium/chromium/src/+/main:content/shell/browser/shell_permission_manager.cc;bpv=0;bpt=1) - namely missing FencedFrame checks and unnecessary else-after-returns.
Notes: none
=> chore: clean up `ElectronPermissionManager`

buildflags/BUILD.gn, buildflags/buildflags.gni, chromium_src/BUILD.gn, shell/browser/api/electron_api_web_contents.cc, shell/browser/electron_browser_client.cc, shell/browser/electron_browser_client.h, shell/browser/feature_list.cc, shell/common/api/features.cc, spec/api-web-contents-spec.ts, typings/internal-ambient.d.ts
The size difference is ~140 KiB (0.07%) on macOS, which is not very significant.
Nobody seems to be even using `enable_picture_in_picture = false` as it does not build currently:
```
../../electron/shell/browser/feature_list.cc:40:42: error: use of undeclared identifier 'mediablink'
disable_features += std::string(",") + mediablink::features::kDocumentPictureInPictureAPI.name;
^
1 error generated.
```
Notes: The `enable_picture_in_picture` build flag has been removed.
=> build: remove enable_picture_in_picture build flag

shell/browser/native_window_mac.h, shell/browser/native_window_mac.mm, spec/api-browser-window-spec.ts
Closes https://github.com/electron/electron/issues/38562.
Fixes an issue with potential UAF of child windows on close and reparent.
Notes: Fixes an issue with potential use-after-free of child windows on close and reparent.
=> fix: reparenting UAF crash on macOS

shell/browser/native_window_views.cc, shell/browser/native_window_views.h, spec/api-browser-window-spec.ts
Closes #35807.
As mentioned in https://github.com/electron/electron/issues/35807#issuecomment-1567678931, when exiting fullscreen, in addition to judging the `IsMenuBarAutoHide()` of the window, you should also judge the user-set visibility property of menu bar. As I known, when entering fullscreen, `IsMenuBarVisible()` will change and may not be consistent with the state set by `mainWindow.setMenuBarVisibility` .
Therefore, I added the `menu_bar_visible_before_fullscreen_`  to identify the visibility of the menu bar before entering fullscreen, and when exiting fullscreen to set the visibility of the menu bar, I also need to determine the value of this variable.
First time PR, not sure if this is the best way. Works for me though.
Notes: Fixes visibility of menu bar when exiting full …
=> fix: menu bar visibility when exiting full screen

script/lint.js
Our list of cpplint filters does not match upstream's and so our checks are not in line with the Google + Chromium style guides. This PR copies the cpplint filters from `depot_tools` into our own linter. (Maybe we should rewrite the linter in python so we can pick up depot-tools code directly instead of duplicating it?)
This showed up on my radar because I was hitting cpplint's do-not-pass-non-const-references warning while working on `raw_ref` and I saw that there is a lot of upstream code that passes non-const references :smile_cat:  Marking for backports in anticipation of backporting `raw_ref` code.
Notes: none
=> build: use upstream's presubmit cpplint filters.

shell/browser/api/electron_api_base_window.cc
Fix a dangling pointer reference to the `ElectronMenuModel` passed to `NativeWindow::SetMenu()`.
BaseWindow owns both the model and the native window. in `BaseWindow::SetMenu()`, it frees the old menu before calling the native window's `SetMenu()` method with the new one. This results in the native window temporarily holding a reference to the old menu that was just freed.
This PR reverses the order to prevent the dangling pointer.
Notes: none
=> fix: dangling pointer warning when updating menus

patches/chromium/allow_disabling_blink_scheduler_throttling_per_renderview.patch, patches/chromium/build_only_use_the_mas_build_config_in_the_required_components.patch, patches/chromium/feat_enable_offscreen_rendering_with_viz_compositor.patch
Do some modifications to chromium patches so it becomes possible to build other chromium targets like `views_examples` and `content_shell`, which is very helpful for determining whether a bug is caused by electron or chromium when debugging.
Notes: none
=> chore: modify patches so we can build other chromium targets

patches/angle/.patches, patches/angle/translator_limit_the_size_of_private_variables_in_webgl_shaders.patch, patches/angle/webgl_limit_total_size_of_private_data.patch, patches/chromium/.patches, patches/chromium/cherry-pick-48785f698b1c.patch, patches/chromium/m108-lts_return_after_readycommitnavigation_call_in_commiterrorpage.patch, patches/config.json, patches/dawn/.patches, patches/dawn/change_d3d12_descriptor_allocator_to_invalidate_submitted_descriptors.patch, patches/v8/.patches, patches/v8/m108-lts_api_fix_v8_object_setaccessorproperty.patch, patches/v8/merged_regexp_fix_clobbered_register_in_global_unicode_special.patch
<details>
<summary>electron/security#346 - 91fce3345668 from v8</summary>
[regexp] Handle empty ranges in unicode sets
If a unicode set operation contains only an empty range, we generated a
set expression without operands. However the expression should match
nothing, so add the special operand not matching anything instead.
Bug: chromium:1437346
Change-Id: I8dd58884aaf6915277c80effbda43ea715049146
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/4474547
Commit-Queue: Patrick Thier <pthier@chromium.org>
Reviewed-by: Jakob Linke <jgruber@chromium.org>
Cr-Commit-Position: refs/heads/main@{#87257}
</details>
<details>
<summary>electron/security#345 - 2c8a019f39d2 from v8</summary>
[regexp] Fix clobbered register in global Unicode special case
Bug: chromium:1439691
Change-Id: …
=> chore: cherry-pick 8 changes from Release-1-M113

.circleci/config/base.yml
- #38258 moved macOS arm builds to m1 hosts but unfortunately that broke release builds.  This PR should fix those release builds.
- 
Notes: none
=> build: ensure correct dsymutil is downloaded for macOS

.circleci/config/base.yml, BUILD.gn, buildflags/BUILD.gn, buildflags/buildflags.gni, filenames.gni, shell/app/electron_library_main.h, shell/app/electron_library_main.mm, shell/app/electron_main_linux.cc, shell/app/electron_main_mac.cc, shell/app/electron_main_win.cc, shell/common/api/features.cc, shell/common/crash_keys.cc, shell/common/electron_constants.cc, shell/common/electron_constants.h, spec/asar-spec.ts, spec/modules-spec.ts, spec/node-spec.ts, typings/internal-ambient.d.ts
We don't need the buildflag anymore now that we have https://github.com/electron/electron/blob/main/docs/tutorial/fuses.md#runasnode
Notes: The `enable_run_as_node` build flag has been removed in favor of the `runAsNode` fuse.
=> build: remove enable_run_as_node build flag

script/release/uploaders/upload-symbols.py
Need to bump the versions a bit to get a universal build of the sentry cli (it's an executable under the hood)
Notes: none
=> build: update sentry cli for m1 support

shell/browser/api/electron_api_session.cc, shell/browser/session_preferences.cc, shell/browser/session_preferences.h
Copy the [NativeWindowRelay::CreateForWebContents()](https://github.com/electron/electron/blob/69790f4b2a3d386230480c00ba9653febba2b78b/shell/browser/native_window.cc#L779) idiom to simplify SessionPreferences's constructor and lifecycle. Previously, one had to call `new SessionPreferences` and ignore the return value.
Notes: none
=> refactor: add SessionPreferences::CreateForBrowserContext()

docs/tutorial/window-customization.md, shell/browser/ui/views/win_caption_button_container.cc, shell/browser/ui/views/win_caption_button_container.h, shell/browser/ui/views/win_frame_view.cc
fixes https://github.com/electron/electron/issues/33567
WCO would not render properly when given colors containing non-opaque alpha values (e.g. `color: 'rgba(0,0,0,0)'`). The fix is to set the view's layer to not fill its bounds opaquely when the alpha value is not fully opaque.
fiddle gist: https://gist.github.com/samuelmaddock/666ab002510e259ef09fc33a2fd228a2
Notes: Added transparent color support for WCO on Windows
=> fix: WCO transparent background

patches/chromium/.patches, patches/chromium/cherry-pick-94af9d13a14b.patch
Check nullptr in ZWPTextInputWrapperV1::Activate()
After the CL https://crrev.com/c/4160118 a crash occurres on the
wl::get_version_of_object() call in ZWPTextInputWrapperV1::Activate()
when |ZWPTextInputWrapperV1::extended_obj_| is not set.
Added nullptr check to fix it.
Bug: b:251677220, 1431532
Change-Id: Ia5606f1c0d08f552f1091b2a9350655f4bdac939
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4423030
Reviewed-by: Hidehiko Abe <hidehiko@chromium.org>
Reviewed-by: Maksim Sisov <msisov@igalia.com>
Commit-Queue: Maksim Sisov <msisov@igalia.com>
Cr-Commit-Position: refs/heads/main@{#1137771}
Closes #38467
Notes: Backported fix for b:251677220, 1431532.
=> chore: cherry-pick 94af9d13a14b from chromium

lib/browser/api/web-contents.ts, spec/api-web-contents-spec.ts, typings/internal-electron.d.ts
Closes https://github.com/electron/electron/issues/38598.
Fixes an error with `webContents.print` parameter validation by adding missing options required to set printer printable area.
Notes: Fixed an error with `webContents.print` parameter validation by adding missing options required to set printer printable area.
=> fix: `webContents.print` parameter validation error

shell/browser/api/electron_api_web_contents.cc, shell/browser/api/electron_api_web_contents.h
Another easier-to-understand-lifecycles-and-ownership PR.
`api::WebContents` creates & owns a few objects that exist for its lifetime. This PR makes that lifetime scope more explicit: 
- `exclusive_access_manager_` was a `std::unique_ptr`,  is now aggregated directly
- `print_task_runner_` was a `scoped_refptr`, is now a `const scoped_refptr`
- `file_task_runner_` was a `scoped_refptr`, is now a `const scoped_refptr`
- `devtools_file_system_indexer_` was a `scoped_refptr`, is now a `const scoped_refptr` 
Notes: none
=> refactor: api web contents ownership

patches/chromium/printing.patch
Refs CL:3893234
Fixes an issue where `webContents.print()` stopped triggering its callback when the user cancelled the print dialog. This happened as a result of https://github.com/electron/electron/commit/5261e08d0c21b08a62a9f86340247aae0f4aeaf9 - the patch was modified to check for last status being cancelled, but this was done _after_ a check for `printer_query->last_status() != mojom::ResultCode::kSuccess`. This meant that code flow would never reach the cancellation check.
Notes: Fixed an issue where `webContents.print()` stopped triggering its callback when the user cancelled the print dialog.
=> fix: `webContents.print()` cancellation callback

shell/browser/api/electron_api_cookies.cc, shell/browser/api/electron_api_protocol.cc, shell/browser/api/electron_api_service_worker_context.cc, shell/browser/api/electron_api_web_contents.cc, shell/browser/web_contents_permission_helper.cc, shell/common/gin_converters/blink_converter.cc, shell/renderer/api/electron_api_web_frame.cc
In places where we're dealing with a set of strings that are known at build time, e.g. the names of cursor types, prefer `base::StringPiece` over `std::string`. The former involves no heap allocations and are constexpr. (In fact, most of these lookup helper functions are constexpr now in this PR).
Notes: none
=> perf: prefer base::StringPiece over std::string for build-time strings

docs/api/accelerator.md, shell/common/keyboard_util.cc
Closes https://github.com/electron/electron/issues/38676.
Clarifies supported acceleration per [`keyboard_util.cc`](https://github.com/electron/electron/blob/28ada6ea8bd2abeca8812e6d284c1f5f3974286b/shell/common/keyboard_util.cc#L142-L321)
Notes: none
=> docs: clarify supported accelerator punctuation

docs/api/web-contents.md
It got lost between #37085 and #34418
Notes: none
=> docs: add missing isSameDocument property to will-frame-navigate event details

shell/app/node_main.cc, shell/common/node_bindings.cc
We're currently building these on the heap with `std::set<std::string>` but this can be a very small compile-time container instead. (Discussion of `base::fixed_flat_map` and `base::fixed_flat_set` [here](https://chromium.googlesource.com/chromium/src/+/refs/heads/main/base/containers/README.md#base_fixed_flat_map-and-base_fixed_flat_set).)
Marking as 'refactor' rather than 'perf' since this isn't called often, but moving from heap to compile-time is good and using this container makes the code more readable.
CC: @dsanders11 who showed interest in string -> StringPiece conversion and @codebytere as the primary for the functions changed here, but code review welcome from anyone
Notes: none
=> refactor: use compile-time cli arg sets.

BUILD.gn, chromium_src/BUILD.gn
Follow up to https://github.com/electron/electron/pull/38465, this PR moves the chromium src files that need ARC support from Electron's top-level BUILD.gn into the chromium_src/BUILD.gn, for better separation of concerns.
Notes: none
=> build: move chrome_lib_arc to chromium_src/BUILD.gn

lib/asar/fs-wrapper.ts, spec/asar-spec.ts
Follow-up to #38567
Notes: Fixed asar integration for `node:child_process` imports.
=> fix: asar integration for require('node:child_process')

lib/browser/api/web-contents.ts
Closes https://github.com/electron/electron/issues/38751.
As in title.
Notes: Fixed `webContents.printToPDF`  `preferCSSPageSize` type error.
=> fix: `preferCSSPageSize` error type

patches/chromium/.patches, patches/chromium/base_do_not_use_va_args_twice_in_asprintf.patch, patches/v8/.patches, patches/v8/cherry-pick-2e76270cf65e.patch, patches/webrtc/.patches, patches/webrtc/m114_move_transceiver_iteration_loop_over_to_the_signaling_thread.patch
<details>
<summary>electron/security#364 - 2e76270cf65e from v8</summary>
Merged: Check for encoding when appending in string builder
Fixed: chromium:1450114
(cherry picked from commit a7e2bef27b72f187a7dcdf95714df686f56d9e0b)
Change-Id: I5838383b6b12d137e84c8a36863ef88000e85c76
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/4604652
Cr-Commit-Position: refs/branch-heads/11.4@{#41}
Cr-Branched-From: 8a8a1e7086dacc426965d3875914efa66663c431-refs/heads/11.4.183@{#1}
Cr-Branched-From: 5483d8e816e0bbce865cbbc3fa0ab357e6330bab-refs/heads/main@{#87241}
</details>
Notes:
* Security: backported fix for CVE-2023-3215.
* Security: backported fix for CVE-2023-3216.
* Security: backported fix for 1450536.
=> chore: cherry-pick 3 changes from Release-2-M114

patches/chromium/.patches, patches/chromium/base_do_not_use_va_args_twice_in_asprintf.patch, patches/config.json, patches/v8/.patches, patches/v8/cherry-pick-2e76270cf65e.patch, patches/webrtc/.patches, patches/webrtc/cherry-pick-218b56e51638.patch, patches/webrtc/cherry-pick-e0efbd45ea74.patch, patches/webrtc/m114_move_transceiver_iteration_loop_over_to_the_signaling_thread.patch
<details>
<summary>electron/security#364 - 2e76270cf65e from v8</summary>
Merged: Check for encoding when appending in string builder
Fixed: chromium:1450114
(cherry picked from commit a7e2bef27b72f187a7dcdf95714df686f56d9e0b)
Change-Id: I5838383b6b12d137e84c8a36863ef88000e85c76
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/4604652
Cr-Commit-Position: refs/branch-heads/11.4@{#41}
Cr-Branched-From: 8a8a1e7086dacc426965d3875914efa66663c431-refs/heads/11.4.183@{#1}
Cr-Branched-From: 5483d8e816e0bbce865cbbc3fa0ab357e6330bab-refs/heads/main@{#87241}
</details>
Notes:
* Security: backported fix for CVE-2023-3215.
* Security: backported fix for CVE-2023-3216.
* Security: backported fix for 1450536.
* Security: backported fix for …
=> chore: cherry-pick 5 changes from Release-2-M114, Release-1-M110 and Release-0-M110

shell/browser/api/electron_api_app.cc, shell/browser/api/electron_api_system_preferences_win.cc, shell/browser/api/electron_api_url_loader.cc
Manual backport of #38771. See that PR for details.
Manual intervention needed due to `#include` shear; no other changes to the patch.
Notes: none
=> refactor: constexpr lookup tables

patches/chromium/printing.patch
Closes https://github.com/electron/electron/issues/35996.
Fixes an issue where silent printing has no effect and settings are not applied.
Refs CL:3893234
Notes: Fixed an issue with `webContents.print({ silent: true })` not working correctly.
=> fix: `webContents.print({ silent: true })` not working correctly

shell/browser/ui/inspectable_web_contents_view.h, shell/browser/ui/views/inspectable_web_contents_view_views.cc, shell/browser/ui/views/inspectable_web_contents_view_views.h
Remove an unused function, `InspectableWebContentsView::GetWebView()`.
It's not used now, and I'm not 100% sure but it appears it's never been used?
Notes: none.
=> refactor: remove unused InspectableWebContentsView::GetWebView()

.circleci/config/base.yml
CircleCI has deprecated Xcode 13 except for the final release, 13.4.1, and are removing them on August 7, 2023. Since the `23-x-y` branch is being supported until Aug 2023, move to 13.4.1.
Notes: none
=> build: use Xcode 13.4.1

shell/browser/api/electron_api_app.cc, shell/browser/api/electron_api_url_loader.cc, shell/browser/api/electron_api_web_request.cc, shell/common/gin_converters/blink_converter.cc, shell/common/gin_converters/net_converter.cc, shell/common/gin_converters/std_converter.h
A followup to #38771. Use `base::fixed_flat_map` for `FromV8()` string-to-value conversions.
CC @miniak and @dsanders11 + all reviews welcomed.
Notes: none
=> refactor: use constexpr lookup tables in gin helper

shell/browser/electron_api_ipc_handler_impl.cc, shell/browser/electron_api_ipc_handler_impl.h, shell/browser/electron_permission_manager.cc, shell/browser/electron_web_contents_utility_handler_impl.cc, shell/browser/electron_web_contents_utility_handler_impl.h
We are already storing `content::GlobalRenderFrameHostId` in `UsbChooserController`, `SerialChooserController` and `HidChooserController`.
Notes: none
=> refactor: use content::GlobalRenderFrameHostId

.github/CODEOWNERS
Follow-up to #29405
Notes: none
=> chore: remove deleted guest-window-proxy.ts from CODEOWNERS

shell/browser/api/electron_api_browser_view.cc, shell/browser/api/electron_api_browser_view.h, spec/api-browser-view-spec.ts
Closes https://github.com/electron/electron/issues/37642.
Fixes an issue where calling `BrowserWindow.removeBrowserView()` with a destroyed `webContents` could caus a crash. This is a bit of an edge case, and happens specifically when calling `BrowserWindow.removeBrowserView()` in the `destroyed` event callback of the BrowserView's `webContents`. In this case, the callback is called and executed before `content::WebContentsObserver::WebContentsDestroyed()` is reached. We fix this by hooking into `OnCloseContents()`, which is called as a result of `view.webContents.close()` being called, and ensuring relevant cleanup is done both there and in `OnCloseContents()`, depending on how the `webContents` is being torn down.
<p>
```
Received signal 11 …
```
=> fix: crash calling `BrowserWindow.removeBrowserView()` with destroyed `webContents`

spec/api-app-spec.ts, spec/api-auto-updater-spec.ts, spec/api-browser-window-spec.ts, spec/api-native-theme-spec.ts, spec/api-session-spec.ts, spec/api-web-contents-spec.ts, spec/api-web-frame-main-spec.ts, spec/chromium-spec.ts, spec/extensions-spec.ts, spec/guest-window-manager-spec.ts, spec/webview-spec.ts
Improve type safety in tests
Notes: none
=> refactor: use types for once() return values in spec

docs/breaking-changes.md
macOS 10.13 (High Sierra) and macOS 10.14 (Mojave) are no longer supported by Chromium as of [this commit](https://chromium-review.googlesource.com/c/chromium/src/+/4629466) which will land in Electron in [this Chromium roll](https://github.com/electron/electron/pull/38891), so let's document that breaking change.
Copied from similar 10.11 / 10.12 notice in Electron 20 from #37286
CC @miniak, @electron/wg-releases 
Notes: none
=> docs: document e27 breaking change of dropping macOS 10.13, 10.14

.eslintrc.json, lib/browser/api/net-client-request.ts, lib/browser/devtools.ts
Fix errors reported by `node/no-deprecated-api` or suppress in-place
Notes: none
=> chore: re-enable node/no-deprecated-api linting

shell/renderer/electron_render_frame_observer.cc, spec/chromium-spec.ts
When handling node integration in child windows opened by `window.open`, the code assumed the child window's web frame must have a `opener`, which is not correct since the `opener` may be set to null.
Close https://github.com/electron/electron/issues/38844.
Notes: Fix `preload` script may not run in some child windows opened by `window.open`.
=> fix: child window may have opener removed

shell/browser/api/electron_api_tray.cc, shell/browser/api/electron_api_web_contents.cc, shell/browser/net/electron_url_loader_factory.cc, shell/browser/web_contents_preferences.cc, shell/common/gin_converters/content_converter.cc, shell/common/keyboard_util.cc, shell/common/keyboard_util.h
Backport of #38886.
CC @codebytere who approved 38886
No interesting changes compared to 38886; manual intervention needed due to `#ifdef` shear for the OSR build flag that was removed in main by #38703
Notes: none
=> refactor: more constexpr lookup tables

lib/browser/api/dialog.ts, lib/browser/api/menu-item-roles.ts, lib/browser/api/menu.ts, lib/browser/api/net-client-request.ts, lib/browser/api/protocol.ts, lib/renderer/security-warnings.ts, lib/sandboxed_renderer/init.ts, spec/api-net-spec.ts, spec/asar-spec.ts, spec/lib/spec-helpers.ts, tsconfig.json
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwn
> Note: Object.hasOwn() is intended as a replacement for [Object.prototype.hasOwnProperty()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwnProperty).
Notes: none
=> refactor: replace Object.prototype.hasOwnProperty() with Object.hasOwn()

patches/chromium/.patches, patches/chromium/cherry-pick-60b93798c991.patch, patches/chromium/cherry-pick-85beff6fd302.patch, patches/v8/.patches, patches/v8/merged_compiler_stackcheck_can_have_side_effects.patch, patches/v8/merged_runtime_set_instance_prototypes_directly_on_maps.patch, patches/webrtc/.patches, patches/webrtc/m114_sdp_reject_duplicate_ssrcs_in_ssrc-groups.patch
<details>
<summary>electron/security#367 - 85beff6fd302 from chromium</summary>
M114: Don't recursively destroy guests when clearing unattached guests
Don't recursively destroy guests when clearing unattached guests
When an embedder process is destroyed, we also destroy any unattached
guests associated with that process. This is currently done with a
single call to `owned_guests_.erase`. However, it's possible that two
unattached guests could have an opener relationship, which causes the
destruction of the opener guest to also destroy the other guest, during
the call to `erase`, which is unsafe.
We now separate the steps of erasing `owned_guests_` and destroying the
guests, to avoid this recursive guest destruction.
This also fixes the WaitForNumGuestsCreated test method to not
return …
=> chore: cherry-pick 4 changes from Release-3-M114

.github/workflows/branch-created.yml
Automates creating the new release project board when a new release branch is created.
1. Copies from the template project to a new project with the correct name (`N-x-y`)
2. Makes the new project board public
3. Links the project board with this repository
4. Moves draft items on the new project board to the "Stable Prep Items" column
* 🚧 This will be removed in the future once GitHub finishes implementing functionality such that draft items will retain their status field value when creating a new project board from the template
* ⚠️ Some items should actually be in "Beta Prep Items" but it's non-trivial to figure out which draft item should go to which column, so just accept this shortcoming until GitHub retains the status field values
6. Use `mustache` to do template interpolation on …
=> ci: automate release board creation

shell/browser/native_browser_view_mac.mm, spec/api-browser-view-spec.ts
Closes https://github.com/electron/electron/issues/35994.
Refs https://github.com/electron/electron/pull/34713.
This reverts 75f9573e53338e15af7c7ccd07a529332847ea2c. We can look towards a better solution in the future but for now I think it's better than behavior is consistent cross-platform.
Notes: Fixed an issue where setting bounds on `BrowserViews` can behave inconsistently across platforms.
=> revert: compensate for title bar height when setting bounds on `BrowserView`

shell/browser/api/electron_api_web_contents.cc, spec/fixtures/crash-cases/webview-remove-on-wc-close/index.html, spec/fixtures/crash-cases/webview-remove-on-wc-close/index.js, spec/fixtures/crash-cases/webview-remove-on-wc-close/webview.html
Closes https://github.com/electron/electron/issues/38941.
Fixes an issue where removing a webview in a close callback could cause crashes. This happened as a result of a change made in https://github.com/electron/electron/pull/35509, where `WebContents::CloseContents` was changed to call `Destroy` instead of it being called in `OnCloseContents` by a `BrowserWindow` or `BrowserView`. This made it the case that `Destroy()` would also now be called for webview webContents', which could lead to crashes since that was previously handled by the embedder frame.
Notes: Fixed an issue where removing a webview in a close callback could cause crashes.
=> fix: webview crash when removing in close event

patches/chromium/fix_crash_on_nativetheme_change_during_context_menu_close.patch
Closes https://github.com/electron/electron/issues/38991.
Refs https://github.com/electron/electron/pull/38840.
Fixes an issue with the application menu overlapping the menu item itself. Caused by a small conditional goof when fixing https://github.com/electron/electron/issues/38732.
Notes: Fixes an issue with the application menu overlapping menu items on Windows 11.
=> fix: menu border being created properly on Windows 11

shell/browser/notifications/mac/cocoa_notification.mm
Closes https://github.com/electron/electron/issues/38995.
Fixes an issue where notifications created on macOS which have no actions will erroneously have a `Show` button visible. As per [documentation](https://developer.apple.com/documentation/foundation/nsusernotification/1411564-hasactionbutton?language=objc), `[NSUserNotification hasActionButton]` is true by default, and so we need to explicitly set it to false when no actions exist.
Notes: Fixed an issue where notifications created on macOS which have no actions will erroneously have a `Show` button visible.
=> fix: Notification 'Show' button visible when no actions exist

appveyor-woa.yml, appveyor.yml
Windows builds were failing trying to run depot_tools update, eg https://ci.appveyor.com/project/electron-bot/electron-x64-release/build/1.0.2597/job/s0d7nqm8w5yxlfrm.  It appears that the error that stopped the build has resolved itself, but there still are goma errors present that this PR will resolve.
Notes: none
=> build: disable unneeded depot_tools update on Windows CI

docs/api/browser-window.md, docs/api/menu-item.md, shell/browser/api/electron_api_base_window.cc, shell/browser/api/electron_api_base_window.h, shell/browser/native_window.cc, shell/browser/native_window.h, shell/browser/native_window_mac.h, shell/browser/native_window_mac.mm, shell/browser/ui/cocoa/electron_menu_controller.mm, spec/api-browser-window-spec.ts, spec/ts-smoke/electron/main.ts
This PR implements feature requested in https://github.com/electron/electron/issues/31624. If MacOS native tabs enabled this API allows to show preview of all tabs.
Notes: browserWindow.showAllTabs api added
cc @dmnsgn @codebytere
=> feat: add `BrowserWindow.showAllTabs()` for macOS

shell/browser/api/electron_api_browser_view.cc, shell/browser/api/electron_api_browser_view.h, shell/browser/api/electron_api_menu.cc, shell/browser/api/electron_api_menu.h, shell/browser/api/electron_api_notification.cc, shell/browser/api/electron_api_notification.h, shell/browser/api/electron_api_protocol.cc, shell/browser/api/electron_api_protocol.h, shell/browser/api/electron_api_session.cc, shell/browser/api/electron_api_session.h, shell/browser/api/electron_api_tray.cc, shell/browser/api/electron_api_tray.h, shell/browser/api/electron_api_web_contents.cc, shell/browser/api/electron_api_web_contents.h, shell/browser/api/electron_api_web_frame_main.cc, shell/browser/api/electron_api_web_frame_main.h, shell/common/gin_helper/constructible.h, shell/common/gin_helper/event.h, spec/api-browser-view-spec.ts, spec/api-browser-window-spec.ts, spec/api-menu-spec.ts, spec/api-notification-spec.ts, spec/api-tray-spec.ts
(Mostly) Closes https://github.com/electron/electron/issues/39000.
Fixes an issue where classes that use `gin::Wrappable` and `gin_helper::Constructible` were either missing or had an incorrect prototype class name because the `v8::FunctionTemplate` never called `SetClassName`.
Example Before:
```js
const menu = new Menu()
console.log(menu) // EventEmitter { commandsMap: {}, groupsMap: {}, items: [] }
const bv = new BrowserView()
console.log(bv) // {}
const tray = new Tray(icon)
console.log(tray) // {}
```
Example After:
```js
const menu = new Menu()
console.log(menu) // Menu { commandsMap: {}, groupsMap: {}, items: [] }
const bv = new BrowserView()
console.log(bv) // BrowserView {}
const tray = new Tray(icon)
console.log(tray) // Tray {}
```
Notes: Fixed an issue where certain Electron …
=> fix: set prototype names on `gin::Constructible` classes

docs/tutorial/testing-on-headless-ci.md
Travis has a [specific page](https://docs.travis-ci.com/user/gui-and-headless-browsers/) in its docs dedicated to headless, with several different methods of using `xvfb`
- I consolidated a few links in https://github.com/facebook-atom/jest-electron-runner/issues/47#issuecomment-558848756, thought I'd add one of them to the official docs too
Replace Travis config with a link to its docs, similar to the Jenkins link
Feel free to modify the wording as desired!
- [n/a] `npm test` passes
- [n/a] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)
Notes: none
=> docs: add link to Travis CI headless page

shell/browser/ui/views/client_frame_view_linux.cc
Remove types from GTK CSS selectors similar to Chromium's changes in [CL 4289229](https://chromium-review.googlesource.com/c/chromium/src/+/4289229).
Fixes #38786
Notes: Fixed display of title bar buttons on Wayland.
=> fix: remove types from GTK CSS selectors

patches/chromium/desktop_media_list.patch, shell/browser/api/electron_api_desktop_capturer.cc, shell/browser/api/electron_api_desktop_capturer.h
Fixed a crash related to PipeWire capturer by adapting to Chromium's interface changes. Chromium expects a call to
`NativeDesktopMediaList::StartUpdating` with an implementation of `DesktopMediaListObserver` for delegated capturers like PipeWire. This interface allows listening to user permission events and listing sources only after the user has made a choice on the permission dialog.
The interface has been implemented by an inner class to allow listening to screen and window capture permissions concurrently using two instances of the class. A patch that was resetting the capturer on the first refresh has been changed to exclude PipeWire. PipeWire capturer object will follow the lifecycle of `NativeDesktopMediaList`, as is the case in Chromium.
Fixes #37463
Notes: Fixed a crash when …
=> fix: use StartUpdating method for PipeWire capturer

docs/api/browser-window.md, shell/browser/api/electron_api_base_window.cc, shell/browser/api/electron_api_base_window.h, spec/api-browser-view-spec.ts
This PR enhances `browserWindow.getBrowserViews()` to guarantee that browserViews are z-index sorted.
This is inspired by https://github.com/electron/electron/issues/29905 and will be useful for apps which support tabs.
- [+] PR description included and stakeholders cc'd
- [+] `npm test` passes
- [+] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)
- [+] relevant documentation, tutorials, templates and examples are changed or added
- [+] [PR release notes](https://github.com/electron/clerk/blob/main/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/main/README.md#examples).
notes: browserWindow.getBrowserView() started to …
=> feat: `browserWindow.getBrowserViews()` to return sorted by z-index array

lib/browser/api/protocol.ts, spec/api-protocol-spec.ts
Closes https://github.com/electron/electron/issues/39031.
Refs https://github.com/electron/electron/pull/36674
Fixes an issue where `protocol.handle()` never called its callback with the `'file'` scheme. This was happening because we were not noting `file:` as a buildin scheme, which meant that `Protocol.prototype.handle` was calling `registerProtocol` instead of `interceptProtocol` under the hood.
Notes: Fixed an issue where `protocol.handle()` never called its callback with the `'file'` scheme.
=> fix: `protocol.handle` not intercepting file protocol

shell/common/api/electron_api_native_image.cc
Small cleanup to avoid redundant map lookups in `NativeImage::GetHICON()`.
No particular stakeholders; any reviews welcomed.
Notes: none
=> perf: avoid redundant map lookup in NativeImage::GetHICON()

shell/browser/lib/bluetooth_chooser.cc
Another in a small set of PRs to avoid redundant map lookups, this time in BluetoothChooser::AddOrUpdateDevice().
No particular stakeholders; any review welcomed
Notes: none
=> perf: avoid redundant lookup in BluetoothChooser::AddOrUpdateDevice()

docs/api/safe-storage.md, shell/browser/api/electron_api_safe_storage.cc, shell/browser/browser_process_impl.cc, shell/browser/browser_process_impl.h, shell/browser/electron_browser_main_parts.cc, shell/browser/net/system_network_context_manager.cc, spec/api-safe-storage-spec.ts, spec/fixtures/api/safe-storage/decrypt-app/main.js, spec/fixtures/api/safe-storage/encrypt-app/main.js
It is currently not possible to determine why encryption is not available on Linux at runtime (i-e) which backend was attempted to be initialized. It is possible to get these information via `--vmodule="*/components/os_crypt/*=1"` but having the information at runtime would be helpful for applications to surface better error to users. The PR introduces two new API
1) `safeStorage.getSelectedStorageBackend()` to retrieve the preferred storage backend information
2) `safeStorage.setUsePlainTextEncryption(usePlainText)` to allow using the weaker plain text password for the encryption key, can be used as default when no storage backends are available on Linux.
Notes: Add `safeStorage.setUsePlainTextEncryption` and `safeStorage.getSelectedStorageBackend` api
=> feat: expose safestorage backend information on linux

docs/tutorial/message-ports.md
For a rookie, this little mistake took a long time to find out.
Notes: none.
=> docs: fix a capitalization problem in messagePort tutorial

patches/chromium/fix_harden_blink_scriptstate_maybefrom.patch, shell/common/node_bindings.cc, shell/common/node_bindings.h, shell/renderer/electron_renderer_client.cc, shell/renderer/web_worker_observer.cc, spec/chromium-spec.ts
Closes https://github.com/electron/electron/issues/37404.
Closes https://github.com/electron/electron/issues/36858.
Refs https://github.com/electron/electron/pull/35999
Fixes an issue where `window.open` can interfere with various aspects of Node.js functionality.
Node.js stores `IsolateData` internally on the `Environment` as a member, whereas Blink stores it using [`V8PerIsolateData`](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/platform/bindings/v8_per_isolate_data.h). This creates a situation where, in the renderer process, a previous `IsolateData` could be used for a new `v8::Context`, which then created a schism in the intended connection between the two. This would, for example, be a problem when using the vm module, because …
=> fix: `window.open` causing occasional Node.js crashes

spec/api-content-tracing-spec.ts, spec/api-crash-reporter-spec.ts, spec/api-session-spec.ts, spec/lib/spec-helpers.ts
Identified by https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-date-now.md
Using `Date.now();` is more readable than `+new Date();`
Notes: none
=> refactor: use `Date.now()` instead of `+new Date()`

.devcontainer/on-create-command.sh
It was trying to infer `$schema` as a variable since it was not properly escaped. Also add some extra logging.
<details><summary>Error Log</summary>
<p>
</p>
</details> 
<details><summary>Previously Generated Config</summary>
<p>
```
{
"goma": "cache-only",
"root": "/workspaces/gclient",
"remotes": {
"electron": {
"origin": "https://github.com/electron/electron.git"
}
},
"gen": {
"args": [
"import(\"//electron/build/args/testing.gn\")",
"import(\"/home/builduser/.electron_build_tools/third_party/goma.gn\")"
],
"out": "Testing"
},
"env": {
"CHROMIUM_BUILDTOOLS_PATH": "/workspaces/gclient/src/buildtools",
"GIT_CACHE_PATH": "/workspaces/gclient/.git-cache"
},
"": "file:///home/builduser/.electron_build_tools/evm-config.schema.json"
}
```
</p>
</details> 
Notes: none
=> build: fixup Codespaces build-tools setup

shell/browser/hid/hid_chooser_controller.cc, shell/browser/hid/hid_chooser_controller.h
A small perf cleanup in `HidChooserController`. Nothing major, but avoids some easily avoidable work while also making `AddDeviceInfo()` a little more readable.
- avoid a second map lookup in HidChooserController::AddDeviceInfo() when adding a new physical device.
- have PhysicalDeviceIdFromDeviceInfo() return a const& instead of creating a new string.
CC @jkleinsc as the primary on HidChooserController, but any reviews welcomed.
Notes: none
=> perf: small perf changes in HidChooserController

docs/api/system-preferences.md
The website isn't picking this up and badging it correctly because it only badges `_Deprecated_`.
Notes: none
=> docs: fix casing of _Deprecated_

appveyor-woa.yml, appveyor.yml
Fixes an issue where Appveyor will checkout `main` for test builds, which causes failures if the branch at hand has not been rebased to contain fixes necessary for new tests to pass. Below is a sample failure that occurred on the roll branch, because https://github.com/electron/electron/pull/38754 was merged, and the new test was checked out on the roll and run despite the branch build not containing the associated source changes.
<details><summary>Example</summary>
<p>
</p>
</details> 
Notes: none
=> build: fix Appveyor test workflow checkout

DEPS, patches/node/.patches, patches/node/build_add_gn_build_files.patch, patches/node/chore_allow_the_node_entrypoint_to_be_a_builtin_module.patch, patches/node/fix_crypto_tests_to_run_with_bssl.patch, patches/node/fix_wunreachable-code_warning_in_ares_init_rand_engine.patch, patches/node/pass_all_globals_through_require.patch, patches/node/refactor_allow_embedder_overriding_of_internal_fs_calls.patch
Updating Node.js to v18.16.1.
See [all changes in v18.16.0..v18.16.1](https://github.com/nodejs/node/compare/v18.16.0...v18.16.1)
This would be great to backport into electron 26, since that stream is still in beta and node released many security updates in this version (src: https://nodejs.org/en/blog/vulnerability/june-2023-security-releases)
Please consider including this in the 26 stream 🙏 
Cherry picked from main 327af3b03c
Backport of #38869
cc @ckerr @codebytere @jkleinsc 
Notes: Updated Node.js to v18.16.1 to address security fixes.
=> chore: bump node 18.16.1 (26-x-y)

docs/api/ipc-main.md, docs/api/ipc-renderer.md
These weren't using the actual event names, which is a bit confusing.
Notes: none
=> docs: remove redundant IPC event sections

lib/browser/api/menu.ts, script/release/prepare-release.js, script/release/release.js, spec/api-menu-spec.ts, spec/security-warnings-spec.ts
Identified by https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-includes.md
Using the modern `includes()` instead of `indexOf()` is more readable.
Notes: none
=> refactor: replace .indexOf() with .includes()

docs/api/window-open.md
Previously the [native documentation](https://developer.mozilla.org/en-US/docs/Web/API/Window/open#parameters) for window.open specified 'windowName' as the equivalent parameter to Electron's 'frameName'. This has since been updated to 'target'.
(Change noticed when addressing #39022)
Notes: None
=> docs: update window-open.md to include target

docs/api/session.md, spec/chromium-spec.ts, spec/fixtures/pages/button.html
Adds more descriptive and linked information for permission handlers as well as adds a missing `idle-detection` value alongside corresponding API tests.
Notes: none
=> docs: document `idleDetector` permissions

appveyor-woa.yml, appveyor.yml
Appveyor builds with failed compilation are sometimes getting the build job marked as successful (eg https://ci.appveyor.com/project/electron-bot/electron-ia32-testing/builds/47593406/job/umjyx8edik5uob56).  The test job does fail (eg https://ci.appveyor.com/project/electron-bot/electron-ia32-testing/builds/47593406/job/56veskcjys0in3b3), but it is confusing because it looks like the build succeeds.  This PR adds a check at the end of the build to fail if the artifacts are not present.
Additionally this PR adds a commented out block to our appveyor configs to download and extract pdb.zip to get full stack traces when crashes happen during testing.  By default this file isn't downloaded as it is rather large.
See https://ci.appveyor.com/project/electron-bot/electron-ia32-testing/builds/4762 …
=> ci: fail appveyor build if artifacts are missing

lib/browser/api/auto-updater/auto-updater-win.ts, lib/browser/api/touch-bar.ts, lib/browser/api/utility-process.ts, lib/browser/api/web-contents.ts, lib/browser/api/web-frame-main.ts, lib/browser/ipc-main-impl.ts, lib/renderer/web-view/guest-view-internal.ts, script/release/uploaders/upload-to-github.ts, spec/lib/video-helpers.js
Identified by https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-type-error.md
Notes: none
=> refactor: use `TypeError` instead of generic `Error` when appropriate

shell/browser/native_window.cc, shell/browser/native_window_mac.mm
Closes https://github.com/electron/electron/issues/39077. 
Fixes an issue where non-resizable windows incorrectly enabled the fullscreen/maximize button on initial window creation on macOS. Once the window was fullscreened and then un-fullscreened, the button was correctly disabled. This happened becuase `SetFullScreenable` should only be called on macOS at initial window creation when it's disabled. This change aligns defaults across platforms: a disabled  fullscreen/maximize button on app boot is the current behavior on Windows and Linux as well. A test cannot be added because despite the incorrectly enabled button, `window.isResizable` did correctly return `false`.
<details><summary>Default on Windows</summary>
<p>
</p>
</details>
<details><summary>macOS UI After This Change</summary> …
=> fix: `resizable: false` should disable fullscreen button at start

shell/browser/ui/cocoa/electron_ns_window_delegate.h, shell/browser/ui/cocoa/electron_ns_window_delegate.mm
Closes https://github.com/electron/electron/issues/39078.
This is rooted in a macOS bug where if a child window is minimized, and then both windows are restored via activation of the parent window, the child window is not properly deminiaturized. This causes traffic light bugs like the close and miniaturize buttons having no effect. We need to call deminiaturize on the child window to fix this. Unfortunately, this also hits ANOTHER bug where even after calling deminiaturize, `windowDidDeminiaturize` is not posted on the child window if it was restored as a side effect of parent restoration, so we need to manually reset `is_minimized_` here.
Tested with https://gist.github.com/pushkin-/c7f43c9692b085adca3a784a390eb89b.
Notes: Fixes an issue where macOS traffic lights could malfunction on …
=> fix: traffic lights not working when child windows are restored via parent window

patches/webrtc/.patches, patches/webrtc/fix_mark_pipewire_capturer_as_failed_after_session_is_closed.patch, shell/browser/api/electron_api_desktop_capturer.cc
Delete desktop capturer objects by resetting the DesktopMediaList objects that own them after the sources have been collected. Capturers that are not delegated are already being reset via a patch on NativeDesktopMediaList. That is not safe for delegated capturers as thumbnail generation depends on user events. Deleting the DesktopMediaList object is safe for all capturers and releases OS capture resources as soon as possible.
Also added patch to workaround https://bugs.chromium.org/p/chromium/issues/detail?id=1467060. 
Fixes #39112
Notes: Fixed `desktopCapturer` thumbnail generation after screen sharing is cancelled on Wayland.
=> fix: delete desktop capturers when they're not needed

shell/browser/native_window.h, shell/browser/native_window_mac.h, shell/browser/native_window_mac.mm, spec/api-browser-window-spec.ts
Closes https://github.com/electron/electron/issues/38939.
Refs https://github.com/electron/electron/commit/8f9f1cc2fe4b0121e94be002b1582eeeefd289e8.
Fixes an issue where re-parenting a child window whose first parent was destroyed caused a crash on macOS. This happened as a result of a previous fix addressing a UAF, which was incomplete. This more effectively ensures that when windows are closed, child windows are not left with dangling parents.
Working on this issue unearthed some other issues (namely that this behavior is not very consistent cross-platform) but i'd prefer to get this in for now as it restores previous behavior and addresses a hard crash.
Notes: Fixed a potential crash when re-parenting a BrowserWindow whose first parent has been destroyed.
=> fix: reparenting after `BrowserWindow.destroy()`

patches/node/.patches, patches/node/fix_do_not_resolve_electron_entrypoints.patch
This wastes io cycles and can result in strange behaviour if this path actually exists on disk
=> fix: do not resolve electron entrypoints on disk

patches/chromium/allow_disabling_blink_scheduler_throttling_per_renderview.patch, patches/chromium/extend_apply_webpreferences.patch, spec/api-browser-window-spec.ts, spec/disabled-tests.json, spec/fixtures/pages/visibilitychange.html
Closes https://github.com/electron/electron/issues/39165.
Refs CL:2082213
Fixes an issue where the pageVisibility API returned incorrect values in some situations when `backgroundThrottling` was disabled. This happened when page lifecycle state began being managed on the browser side - our existing patch no longer covered all paths that changed the page visibility state. This should address that by ensuring that the page visibility is always `visible` when `backgroundThrottling` is disabled, and that the `visibilitychange` event is no longer emitted.
Also allows us to re-enable the associated test.
Notes: Fixed an issue where the pageVisibility API returned incorrect values in some situations when `backgroundThrottling` was disabled.
=> fix: `pageVisibility` state when `backgroundThrottling` disabled

docs/development/creating-api.md, docs/tutorial/context-isolation.md, docs/tutorial/ipc.md, docs/tutorial/message-ports.md, package.json, yarn.lock
Tightens up a few remaining usages of blocks which were using `@ts-nocheck`, and starts type checking TypeScript blocks as well. Allows typing variables on the `Window` object, which would have caught #39130.
The remaining usages of `@ts-nocheck` are mostly code blocks using external modules where adding the types would add extra complexity for small gain. Good enough for now, support for external module type checking may be added to `@electron/lint-roller` in the future.
Notes: none
=> chore: update @electron/lint-roller and improve doc type checks

appveyor-woa.yml, appveyor.yml
Fixes an issue where doc-only PRs were failing on artifact validation because they by design produce no artifacts.
Notes: none
=> fix: skip artifact validation for doc-only PRs

patches/webrtc/.patches, patches/webrtc/pipewire_capturer_increase_buffer_size_to_avoid_buffer_overflow.patch
Cherry pick https://webrtc-review.googlesource.com/c/src/+/311541 from WebRTC to fix a crash during stream renegotiation.
Fixes #39131
cc @VerteDinde
Notes: Fixed a crash while screen sharing on Wayland with PipeWire.
=> chore: cherry-pick 8fcc6df from webrtc

shell/browser/ui/win/electron_desktop_window_tree_host_win.cc, shell/browser/ui/win/electron_desktop_window_tree_host_win.h, shell/browser/win/dark_mode.cc
The Windows 10 workaround we use to fix initial rendering of the title bar after changing the native theme stopped working after #38468 as a result of removing our hardcoded `ShouldPaintAsActive()` returning false. [Chromium's handling for the `WM_NCACTIVATE` message](https://source.chromium.org/chromium/chromium/src/+/main:ui/views/win/hwnd_message_handler.cc;l=2332-2381;drc=e6361d070be0adc585ebbff89fec76e2df4ad768) does a logical or between the requested `wParam` value and the result of `ShouldPaintAsActive()`, so before #38468 it was always doing `|| false` which meant the `wParam` value was always used. After the change in #38468 the workaround stopped working since it tries to toggle the title bar active state to force Windows to redraw it, but the logical or means you can't force it …
=> fix: initial dark mode title bar on Windows 10

shell/browser/electron_browser_client.cc, spec/extensions-spec.ts, spec/fixtures/extensions/mv3-service-worker/background.js, spec/fixtures/extensions/mv3-service-worker/main.js, spec/fixtures/extensions/mv3-service-worker/manifest.json
Closes https://github.com/electron/electron/issues/34178.
Fixes basic Chrome Extension Manifest V3 service worker functionality. Previously, the service worker would register but could not run any chrome APIs:
```
[61131:0731/100424.234951:ERROR:render_process_host_impl.cc(3967)] Request for unknown Channel-associated interface: extensions.mojom.ServiceWorkerHost
```
This fixes that and adds a simple regression test.
Notes: Fixed an issue where service workers could not run Chrome APIs in Chrome Extensions Manifest V3.
=> fix: Chrome Extensions service worker host registration

shell/browser/api/electron_api_tray.cc, shell/browser/ui/tray_icon.cc, shell/browser/ui/tray_icon.h, shell/browser/ui/tray_icon_cocoa.h, shell/browser/ui/tray_icon_cocoa.mm, shell/browser/ui/win/notify_icon.cc, shell/browser/ui/win/notify_icon.h
Speculative fix for a crash i've been seeing in CI a fair bit recently, but haven't been able to repro locally. It looks like the ElectronMenuModel is going away before this callback is called. We use `base::Unretained` here which isn't safe if we can't guarantee lifetime which I don't think we can here.
[Sample Failure](https://app.circleci.com/pipelines/github/electron/electron/72626/workflows/3b520c71-d6d4-410e-8e7e-d02decab2211/jobs/1570135)
<p>
```
Received signal 11 SEGV_MAPERR 000000000018
0   Electron Framework                  0x0000000129ff4632 base::debug::CollectStackTrace(void**, unsigned long) + 18
1   Electron Framework                  0x0000000129fe2393 base::debug::StackTrace::StackTrace() + 19
2   Electron Framework …
```
=> fix: potential crash calling `tray.popUpContextMenu()`

docs/api/ipc-main.md
Per the description, the value resolved by the promise is used, so it shouldn't be `Promise<void>`. From a practical standpoint this has little effect on typing since the union with `any` makes the whole thing `any`, but better to be accurate in the docs. Ideally we'd replace `any` with a type union of IPC serializable types, but we don't have an easy way to do that at the moment.
Notes: none
=> docs: fix return type for ipcMain handle functions

docs/api/power-save-blocker.md, spec/ts-smoke/electron/main.ts
Supersedes https://github.com/electron/electron/pull/39080 - which we determined to be employing ChatGPT.
Notes: none
=> docs: correct `powerSaveBlocker.stop(id)` return type

shell/browser/api/message_port.h
Fixes the following two crashes we have seen in our releases with utility process
<details>
<summary>Crash 1</summary>
```
Thread 0:
0   electron::JavascriptEnvironment::GetIsolate() [0x9a5f8c8] in javascript_environment.cc:380
x0 = 0x0000000000000000   x1 = 0x0000000000000000
x2 = 0x0000000000000000   x3 = 0x000000012a000000
x4 = 0x000000012a00b330   x5 = 0x0000000000000009
x6 = 0x0000000000000002   x7 = 0x0000000000000000
x8 = 0x0000000110747000   x9 = 0x23649dadec0d0055
x10 = 0x0000000000000000  x11 = 0x0000000000000000
x12 = 0x0000000000000735  x13 = 0x0000000000000073
x14 = 0x0000000000000808  x15 = 0x0000000000000808
x16 = 0x0000000185700e9c  x17 = 0x0000000185564d74
x18 = 0x0000000000000000  x19 = 0x0000000000000001
x20 = 0x000000012f71ea10  x21 = 0xaaaaaaaaaaaaaaaa
x22 = …
```
=> fix: destroy message port backend when JS env exits

docs/api/system-preferences.md
These were removed in #26849 but the documentation was never removed. There's also some dead code which wasn't removed, but I'll do a follow-up PR to remove that so this PR can be backported without also backporting the code changes. Doing a deep backport to clean up the types since currently the types think these methods exist, but they will fail at run time.
Notes: none
=> docs: clean up removed systemPreferences methods

shell/common/extensions/api/tabs.json, spec/extensions-spec.ts, spec/fixtures/extensions/chrome-api/main.js, spec/fixtures/extensions/tabs-api-async/background.js, spec/fixtures/extensions/tabs-api-async/main.js, spec/fixtures/extensions/tabs-api-async/manifest.json
Updates our implementation of `chrome.tabs` to support Promises with Manifest V3. Also adds a fuller test suite for `chrome.tabs` functionality. Note that this does not affect functionality with Manifest V2.
Notes: Notes: Fixes an issue where `chrome.tabs` did not work properly with Chrome Extensions Manifest V3
=> fix: update `chrome.tabs` for Manifest v3

docs/api/command-line-switches.md, shell/common/node_bindings.cc
Closes https://github.com/electron/electron/issues/39322.
This PR allows a few more cli flags to be set in the main process. We currently allow these to be set indirectly via the [`process` object](https://github.com/electron/electron/blob/67a6fbf2656c5aa18c59721b56b081c156e79fad/docs/api/process.md#L93-L110),  which causes Node.js itself to add them to cli flags. This aligns what's permitted so that users can set them in either place. Before this, Node.js would log the process warning in a way that ultimately created more confusion for users. They would be told to set the flag to see warnings, but if they did, it would be silently dropped and seem to have no effect.
<p>
```
electron-trace-warnings-issue on git:main ❯ npm start            11:40AM
> …
```
=> feat: allow more Node.js cli flags in main process

appveyor-woa.yml, appveyor.yml
Occasionally on build failures, the logic to detect if all artifacts have been uploaded to AppVeyor was hanging causing builds to run for 3 hours before timing out - eg https://ci.appveyor.com/project/electron-bot/electron-woa-testing/builds/47688239/job/02vd8tkwssqxt1ig.  
It turns out that trying to fail the build in the `on_finish` step was causing the hang.  This PR moves the logic to check the artifacts to the build step but leaves the actual uploading of artifacts in the `on_finish` step as we want to upload any artifacts we have even on build failure.
Notes: none
=> ci: fix hang when validating AppVeyor artifacts

shell/browser/ui/tray_icon_cocoa.mm
Closes https://github.com/electron/electron/issues/21062.
Fixes an accessibility issue where `VoiceOver` couldn't trigger the tray action when selected to emit the click event. This was happening because the `NSStatusBarButton` had no action or target, and since voiceover selection is not a `mouseEvent`, it wouldn't trigger `mouseDown` or `mouseUp`.
To correct this, we set a target and action for the button. We also need to create a synthetic event if we're triggering the click event via VoiceOver.
Tested with https://gist.github.com/oysteinmoseng/bec736b1c2ceec3fa6e5a77d46d3ac08 (and, of course, VoiceOver)
Notes: Fixes an accessibility issue where `VoiceOver` couldn't trigger the tray action when selected to emit the click event.
=> fix: macOS tray button selection with VoiceOver

shell/browser/extensions/api/tabs/tabs_api.cc, spec/extensions-spec.ts, spec/fixtures/extensions/tabs-api-async/background.js, spec/fixtures/extensions/tabs-api-async/main.js
Fixes an issue where `chrome.tabs.update` did not return a `tab` object that properly reflected potential properties that were changed, e.g. `muted`.
Notes: Fixed an issue where `chrome.tabs.update` did not return a `tab` object that properly reflected potential properties that were changed.
=> fix: `chrome.tabs.update` return value

shell/browser/api/electron_api_base_window.cc
Closes https://github.com/electron/electron/issues/39377.
This was happening because destroying the webContents in the BrowserView on removal by clicking triggered a `hitTest`, yet when our logic when to check against possible draggable regions, the browserView had not yet been removed from the set. This flips the order to ensure that there are no race conditions.
Cannot be tested (and was not caught in tests) because it specifically requires click or mouse interaction when `removeBrowserView` is called.
<p>
```
Received signal 11 SEGV_ACCERR 0000000005a0
0   Electron Framework                  0x000000011dc86950 base::debug::CollectStackTrace(void**, unsigned long) + 28
1   Electron Framework                  0x000000011dc77060 …
```
=> fix: `removeBrowserView` draggable region removal

shell/browser/ui/inspectable_web_contents_view_mac.mm
Refs https://github.com/microsoft/vscode/issues/167936
Repro: https://gist.github.com/deepak1556/dfeed162dcfb36f3e3b07409885f32f2#file-steps-md
<details>
<summary>Stacktrace</summary>
```
Received signal 11 SEGV_ACCERR 00000000010e
0   Electron Framework                  0x0000000119aca6b4 base::debug::CollectStackTrace(void**, unsigned long) + 28
1   Electron Framework                  0x0000000119aba854 base::debug::StackTrace::StackTrace() + 24
2   Electron Framework                  0x0000000119aca610 base::debug::(anonymous namespace)::StackDumpSignalHandler(int, __siginfo*, void*) + 1204
3   libsystem_platform.dylib            0x000000018abf9a24 _sigtramp + 56
4   Electron Framework                  0x00000001157a1678 -[ElectronInspectableWebContentsView …
```
=> fix: crash when closing active macOS native tab

.circleci/config/base.yml
This changes nothing about the build environment, only the underlying build infrastructure.  Linux jobs are still run inside the same docker containers but now those docker containers run inside an auto scaling kubernetes cluster.  The plan per #wg-infra is to merge this and monitor for any _perceived_ impact to build times and measure actual impact to CI infra costs.  At any point this change can be reverted if it is causing issues.
Notes: none
=> build: use aks backed runners for linux builds

shell/browser/extensions/api/runtime/electron_runtime_api_delegate.cc
Refs CL:3588696.
Also adds logs to indicate lack of support for certain functions.
Notes: none
=> chore: update `chrome.runtime.getPlatformInfo` impl

patches/node/fix_do_not_resolve_electron_entrypoints.patch
Follow up to #39247 to avoid another package.json lookup
=> fix: avoid package.json check on built-in modules

docs/api/extensions.md, shell/browser/api/electron_api_web_contents.cc, shell/browser/api/electron_api_web_contents.h, shell/browser/extensions/api/tabs/tabs_api.cc, shell/browser/extensions/api/tabs/tabs_api.h, shell/common/extensions/api/tabs.json, spec/extensions-spec.ts, spec/fixtures/extensions/tabs-api-async/background.js, spec/fixtures/extensions/tabs-api-async/main.js
Depends on https://github.com/electron/electron/pull/39317.
This PR adds support for [`chrome.tabs.query`](https://developer.chrome.com/docs/extensions/reference/tabs/#method-query). This API is fairly commonly used by various framework devtools extensions, including the React DevTools extension.
Notes: Added partial support for `chrome.tabs.query`.
=> feat: add support for `chrome.tabs.query`

lib/browser/api/web-contents.ts, spec/api-web-contents-spec.ts, spec/fixtures/pages/navigate_in_page_and_wait.html
After this fix [https://github.com/electron/electron/pull/36129](https://github.com/electron/electron/pull/36129) promise returned by `loadURL` function can be resolved before page finish loading. While page is loading it can trigger browser intendent in page navigation (e.g.: `window.history.replaceState` ). This PR fixes this problem.
Notes: Fix problem with promise resolved to early when browser intendent in-page navigation
=> fix: promise resolved to early when browser initiated in-page navigation

shell/common/extensions/api/_api_features.json, shell/common/extensions/api/resources_private.idl
Updates Electron's copy of `extensions/api/_api_features.json` to match [upstream](https://source.chromium.org/chromium/chromium/src/+/main:chrome/common/extensions/api/_api_features.json) where applicable. Also update `extensions/api/resources_private.idl` to add `[supportsPromises]` for Manifest V3.
Notes: none
=> chore: update `_api_features` manifest requirements

docs/api/cookies.md, docs/api/session.md, docs/api/web-contents.md, docs/api/webview-tag.md, docs/development/build-instructions-windows.md, docs/development/debugging-on-windows.md, docs/development/issues.md, docs/fiddles/menus/customize-menus/index.html, docs/fiddles/menus/shortcuts/index.html, docs/fiddles/native-ui/dialogs/error-dialog/index.html, docs/fiddles/native-ui/dialogs/information-dialog/index.html, docs/fiddles/native-ui/dialogs/open-file-or-directory/index.html, docs/fiddles/native-ui/dialogs/save-dialog/index.html, docs/fiddles/native-ui/drag-and-drop/index.html, docs/fiddles/native-ui/external-links-file-manager/index.html, docs/fiddles/native-ui/notifications/index.html, docs/fiddles/native-ui/tray/index.html, docs/fiddles/screen/fit-screen/main.js, docs/fiddles/system/protocol-handler/launch-app-from-URL-in-another-app/index.html, docs/fiddles/system/system-app-user-information/app-information/index.html, docs/fiddles/system/system-information/get-version-information/index.html, docs/fiddles/windows/manage-windows/frameless-window/index.html, docs/fiddles/windows/manage-windows/manage-window-state/index.html, docs/fiddles/windows/manage-windows/new-window/renderer.js, docs/fiddles/windows/manage-windows/window-events/index.html, docs/tutorial/automated-testing.md, docs/tutorial/electron-timelines.md, docs/tutorial/introduction.md, docs/tutorial/tutorial-6-publishing-updating.md, docs/tutorial/windows-store-guide.md
- Fix outdated links such as `docs.microsoft.com`
- Update the links to the canonical redirected forms
- Replace `http://` with `https://`
Notes: none
=> docs: update external links

shell/common/api/electron_api_clipboard.cc, spec/api-clipboard-spec.ts
Refs https://github.com/electron/electron/pull/39069.
Closes https://github.com/electron/electron/pull/39446.
Must explicitly specify kNestableTasksAllowed to make nested run loop work. 
Note that this is totally valid trick, there are a few examples can be found in Chromium:
https://source.chromium.org/chromium/chromium/src/+/refs/heads/main:components/printing/renderer/print_render_frame_helper.cc;l=2607;drc=b86abfa407f3f35d3e5904e76b9a8d3a741bdc8b
https://source.chromium.org/chromium/chromium/src/+/main:components/ui_devtools/agent_util.cc;l=38;drc=8ba1bad80dc22235693a0dd41fe55c0fd2dbdabd
/cc @codebytere @TomaszMa
Notes: Fix `clipboard.readImage()` getting blocked when there is no PNG image in the clipboard.
=> fix: use nested run loop in clipboard.readImage

docs/api/system-preferences.md, docs/breaking-changes.md, shell/browser/api/electron_api_system_preferences.cc, shell/browser/api/electron_api_system_preferences.h, shell/browser/api/electron_api_system_preferences_win.cc, spec/ts-smoke/electron/main.ts
~~Needs #39334 to land first.~~
These events were marked as deprecated in #26848 but were never removed.
Notes: The deprecated color scheme changed events in systemPreferences have been removed
=> chore: remove deprecated systemPreferences color scheme events

docs/api/system-preferences.md, docs/breaking-changes.md, lib/browser/api/system-preferences.ts, spec/api-native-theme-spec.ts, spec/api-system-preferences-spec.ts
These have been marked as deprecated in the docs for a long time, but were never called out in `docs/breaking-changes.md` or given warn on usage (except `alternate-selected-control-text`). Let's do a proper deprecation and remove them next version.
Notes: The `systemPreferences.getAppLevelAppearance` and `systemPreferences.setAppLevelAppearance` APIs have been deprecated, as well as the `alternate-selected-control-text` value for `systemPreferences.getColor`.
=> chore: document deprecated systemPreferences APIs

patches/node/chore_update_fixtures_errors_force_colors_snapshot.patch
Refs https://github.com/electron/electron/pull/39247
Refs https://github.com/electron/electron/pull/39154
#39154 wasn't rebase before merging so the snapshot update conflicts with #39247. This resolves that.
Notes: none.
=> test: resolve failing Node.js line number failure

.github/ISSUE_TEMPLATE/bug_report.yml, .github/workflows/issue-labeled.yml, .github/workflows/issue-unlabeled.yml
Automation for an issue triage board:
* Adds new bugs to the board via [the new `projects` field on the issue template](https://github.blog/changelog/2023-08-10-github-issues-projects-august-10th-update/#updates-to-issue-forms)
* Toggles the item blocked status when labels starting with `blocked/` are added or removed from the issue
Notes: none
=> ci: automation for issue triage board

.github/workflows/pull-request-labeled.yml
Adds automation for the deprecation project board in support of https://github.com/electron/cation/pull/144. At the moment that consists solely of setting the project board status of a PR to "✅ Reviewed" when it is labeled with https://github.com/electron/electron/labels/deprecation-review%2Fcomplete%20%E2%9C%85.
Notes: none
=> ci: automation for deprecation project board

.github/workflows/issue-labeled.yml
Improves the workflow in a few ways:
* Bumps the `actions-cool/issues-helper` version to clear deprecation warnings
* Uses the label link which renders nicely like this: https://github.com/electron/electron/labels/blocked%2Fneed-repro
* Checks if the bot has already commented so we can apply the label multiple times without spamming the comment
The one comment only was the main reason for this change. Since the logic for removing the label is dumb (any comment clears it), maintainers may want to re-apply the label when it is still applicable, but currently doing so will trigger the full comment again, which isn't a very nice experience.
Also allows for maintainers to suppress the bot comment in favor of their own by starting their comment with ``. If any comment (from the bot, or a …
=> ci: improve blocked/need-repro workflow

filenames.gni, shell/browser/extensions/api/tabs/tabs_api.cc, shell/browser/web_contents_zoom_controller.cc, shell/browser/web_contents_zoom_controller.h, shell/browser/web_contents_zoom_observer.h, shell/browser/web_view_guest_delegate.cc, shell/browser/web_view_guest_delegate.h
Refs https://codereview.chromium.org/301733006.
Refs https://github.com/electron/electron/pull/8537
This PR refactors and updates our ZoomController implementation to bring it into line with the current state of [`components/zoom/zoom_controller.cc`](https://source.chromium.org/chromium/chromium/src/+/main:components/zoom/zoom_controller.cc;l=176) upstream. This is being done as a precursor to supporting tab events in `chrome.tabs`, which expect data be sent to observers in struct form and contain both new and old zoom values.
Relevant Changes 
- Pulls `WebContentsZoomObserver` into a standalone file
- Zoom data is now sent to observers as a `ZoomEventChangeData` struct
- Triggers observers through a callback set on `ZoomHostMap`
Notes: none
=> refactor: update `WebContentsZoomController`
