electron/electron

- docs/api/command-line-switches.md
- shell/app/node_main.cc
- shell/common/node_bindings.cc
- shell/common/node_bindings.h
Closes https://github.com/electron/electron/issues/39288.
More clearly indicates that `--js-flags` is _only_ for V8 flags, as well as cleans up Node.js cli flag parsing.
Notes: none
> refactor: clean up Node.js cli arg parsing

- docs/api/app.md
Pretty self explanatory. Found a typo in the docs here: 
> if the the application being is being opened
> docs: fix typo in open-url API docs

- shell/browser/native_window_mac.mm
- spec/api-browser-window-spec.ts
Closes https://github.com/electron/electron/issues/39413.
Follow-up to https://github.com/electron/electron/pull/39034.
We should only reorder child windows when the windows are _not_ sheet windows.
Notes: Fixes a potential crash when calling `BrowserWindow.moveTop()` on modal child windows.
> fix: crash when calling `BrowserWindow.moveTop()` on modal children

- build/zip_libcxx.py
- #39375 was a bit too aggressive in addressing the CL [4666325: Move buildtools/third_party/lib*/trunk source paths to third_party/lib*/src.](https://chromium-review.googlesource.com/c/chromium/src/+/4666325).  This PR fixes our libcxx zip tool to grab the generated files from the proper directory.
Notes: none
> build: fixup libcxx zip

- build/args/all.gn
Bumps Electron's NMV to 118 - needed before forking the 27-x-y branch
Notes: none
> build: update NMV to 118

- docs/api/app.md
- docs/api/structures/render-process-gone-details.md
- docs/api/web-contents.md
- docs/api/webview-tag.md
- filenames.auto.gni
It should match the `webContents` events, which are used to implement the `webview` ones:
https://github.com/electron/electron/blob/9eeef5546927bc98d2bd8bc8089b998a58ed4e39/docs/api/web-contents.md?plain=1#L463-L496
Except for the `killed` argument, which is not being forwarded:
https://github.com/electron/electron/blob/9eeef5546927bc98d2bd8bc8089b998a58ed4e39/lib/browser/web-view-events.ts#L24-L25
Also adds `structures/render-process-gone-details.md` to eliminate duplicates
Notes: none
> docs: add missing webview `render-process-gone` event

- shell/browser/javascript_environment.cc
- shell/browser/javascript_environment.h
Fix a minor `raw_ptr` issue in JavascriptEnvironment:
```c++
class JavascriptEnvironment
{
...
raw_ptr<Isolate> isolate_;
IsolateHolder isolate_holder_;
...
};
```
The isolate that `isolate_` points to is owned by `isolate_holder_`, which disposes it in the isolate holder's destructor. Since classes destroy their fields in reverse order, `isolate_holder_` is destroyed first and so `isolate_` is a dangling pointer when it is destroyed.
CC @VerteDinde 
Notes: none
> fix: destruction order of js env fields

- docs/api/browser-window.md
Closes https://github.com/electron/electron/issues/39445.
Notes: none
> docs: note macOS bounds Tray offset

- docs/api/session.md
- docs/api/web-contents.md
- docs/api/webview-tag.md
- shell/browser/api/electron_api_web_contents.cc
- shell/browser/api/electron_api_web_contents.h
- spec/api-session-spec.ts
Refs https://github.com/electron/electron/pull/38785.
There's no reason that the API signatures for these methods shouldn't be identical, and it's arguably more confusing for users that they're not, given they both trigger `will-download` on `session`.
**NOTE**: The bulk of this change is test changes and additions - the code change is minimal and identical to what was changed in https://github.com/electron/electron/pull/38785.
Caught when cleaning up some tests. 
Notes: Added the ability to send HTTP headers with `webContents.downloadURL()`.
> feat: allow headers to be sent with `webContents.downloadURL()`

- shell/app/node_main.cc
- shell/browser/usb/electron_usb_delegate.cc
- shell/common/node_bindings.cc
https://chromium-review.googlesource.com/c/chromium/src/+/4660000 says that the sorted version is simpler at compile time because it can skip MakeFixedFlatSet()'s compile-time dynamic sorting.
Notes: none
> refactor: prefer Sorted variant of MakeFixedFlatSet()

- patches/node/fix_account_for_debugger_agent_race_condition.patch
- script/node-disabled-tests.json
Refs https://github.com/electron/electron/pull/39154
Enable debugger spec by correcting for race condition.
Notes: none
> test: enable `parallel/test-debugger-random-port-with-inspect-port`

- shell/browser/ui/views/client_frame_view_linux.cc
Adapt to the window frame size calculation changes in [CL 3970920](https://chromium-review.googlesource.com/c/chromium/src/+/3970920) by setting the inset sizes to 0 for tiled edges.
cc @jkleinsc 
Fixes #39470 
Notes: Fixed decorations for tiled windows on Wayland.
> fix: use tiled edges to calculate frame inset sizes in Linux

- patches/angle/.patches
- patches/angle/cherry-pick-5486190be556.patch
- patches/chromium/.patches
- patches/chromium/networkcontext_don_t_access_url_loader_factories_during_destruction.patch
- patches/config.json
- patches/skia/.patches
- patches/skia/enforce_an_upper_limit_of_715_million_path_verbs_in_skpath.patch
- patches/v8/.patches
- patches/v8/cherry-pick-8ff63d378f2c.patch
- patches/v8/cherry-pick-d671b099a57d.patch
<details>
<summary>electron/security#389 - 8ff63d378f2c from v8</summary>
Merged: [builtins] Clear FixedArray slot in Promise builtins
Fixed: chromium:1468943
(cherry picked from commit a84849ed718932b94dc877bb44a2d38eb8a0aef9)
Change-Id: Ia2b181c373c15bd1840e2a1572c0e930cddcd788
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/4753495
Auto-Submit: Shu-yu Guo <syg@chromium.org>
Cr-Commit-Position: refs/branch-heads/11.6@{#28}
Cr-Branched-From: 95cbef20e2aa556a1ea75431a48b36c4de6b9934-refs/heads/main@{#88340}
</details>
<details>
<summary>electron/security#393 - 5486190be556 from angle</summary> …
> chore: cherry-pick 5 changes from Release-0-M116

- shell/browser/native_window_views.cc
- shell/browser/native_window_views.h
- shell/browser/native_window_views_win.cc
When explorer restarted, it didn't regenerate the thumbnail toolbar button, so the button was removed.
Also, `BrowserWindow.setThumbarButtons` prevented adding buttons because `TaskbarHost.thumbar_buttons_added_` was `true`.
Restore thumbnail toolbar buttons when receiving "TaskbarCreated" message in `NativeWindowViews` class.
closes #39550
Notes: Fixed to regenerate thumbnail toolbar buttons when explorer is restarted.
> fix: explorer restart does not recreated thumbnail toolbar buttons

- shell/app/node_main.cc
- shell/browser/api/electron_api_app.cc
- shell/browser/api/electron_api_base_window.cc
- shell/browser/api/electron_api_browser_window.cc
- shell/browser/api/electron_api_desktop_capturer.cc
- shell/browser/api/electron_api_dialog.cc
- shell/browser/api/electron_api_in_app_purchase.cc
- shell/browser/api/electron_api_notification.cc
- shell/browser/api/electron_api_printing.cc
- shell/browser/api/electron_api_system_preferences.cc
- shell/browser/api/electron_api_url_loader.cc
- shell/browser/api/electron_api_web_contents.cc
- shell/browser/browser_mac.mm
- shell/browser/browser_win.cc
- shell/browser/lib/bluetooth_chooser.cc
- shell/browser/serial/serial_chooser_controller.cc
- shell/common/api/electron_api_asar.cc
- shell/common/api/electron_api_native_image.cc
- shell/common/api/electron_bindings.cc
- shell/common/gin_converters/blink_converter.cc
- shell/common/gin_converters/content_converter.cc
- shell/common/gin_converters/file_dialog_converter.cc
- shell/common/gin_converters/gfx_converter.cc
- shell/common/gin_converters/net_converter.cc
- shell/common/gin_converters/serial_port_info_converter.h
- shell/common/gin_helper/callback.cc
- shell/common/gin_helper/dictionary.h
- shell/renderer/electron_sandboxed_renderer_client.cc
- shell/renderer/renderer_client_base.cc
It allows using
```cpp
auto dict = gin_helper::Dictionary::CreateEmpty(isolate);
```
which is IMO more readable than
```cpp
gin_helper::Dictionary dict = gin::Dictionary::CreateEmpty(isolate);
```
Notes: none
> refactor: add gin_helper::Dictionary::CreateEmpty() helper

- shell/browser/electron_browser_main_parts.cc
- shell/browser/electron_browser_main_parts.h
Another order-of-destruction issue similar to https://github.com/electron/electron/pull/39521.
```c++
class ElectronBrowserMainParts
{
....
std::unique_ptr<JavascriptEnvironment> js_env_;
std::unique_ptr<NodeBindings> node_bindings_;
....
};
````
`js_env_` holds a pointer to the uv loop owned by `node_bindings_`, so when `node_bindings_` is destroyed before `js_env_` in the EBMP destructor, `js_env_` is holding onto a dangling pointer when its destructor is called.
CC @deepak1556, @codebytere who reviewed 39521 and @VerteDinde for raw_ptr fun.
Notes: none.
> fix: dangling raw_ptr in ElectronBrowserMainParts dtor

- docs/api/browser-window.md
- docs/breaking-changes.md
- lib/browser/api/base-window.ts
- spec/api-browser-window-spec.ts
Follow-up to #37094
Notes: The deprecated `getTrafficLightPosition()` / `setTrafficLightPosition()` APIs have been removed.
> chore: remove deprecated `getTrafficLightPosition()` / `setTrafficLightPosition()`

- lib/sandboxed_renderer/init.ts
- spec/chromium-spec.ts
- spec/fixtures/module/preload.js
Fixes #38161
Notes: A dummy `module.exports` is now passed to the sandboxed preload scripts to improve compatibility with CommonJS modules.
> feat: expose dummy module.exports to the sandboxed preload scripts

- shell/browser/api/electron_api_app.cc
- shell/browser/api/electron_api_in_app_purchase.cc
- shell/browser/api/electron_api_system_preferences.cc
- shell/common/api/electron_bindings.cc
- shell/common/gin_converters/gfx_converter.cc
> chore: remove obsolete "simple" object annotations for the remote module

- shell/browser/electron_browser_context.cc
- spec/api-media-handler-spec.ts
It seems `display_surface` in `display_media_info` wasn't correctly set when the display media source is a tab, which causes `getDisplayMedia` to return a `MediaStreamTrack` instead of  `BrowserCaptureMediaStreamTrack` for browser sources.
Looking at the uses of `DesktopMediaID::Parse` in Chromium, it looks like the id it's supposed to receive is the id of a `MediaStreamSource` instead of the id of `MediaStreamRequest`.
With this change, it'll be possible to use the new[ Region Capture API](https://www.w3.org/TR/mediacapture-region/) with tab/browser capturing.
Fixes https://github.com/electron/electron/issues/36331
*Before*
*After*
Notes: support Region Capture API with tab MediaStream
> fix: instantiate tab video tracks from BrowserCaptureMediaStreamTrack 

- patches/node/.patches
- patches/node/fix_assert_module_in_the_renderer_process.patch
Closes https://github.com/electron/electron/issues/39079.
When creating a Node.js Environment, embedders have the option to disable Node.js' default overriding of `Error.prepareStackTrace`. However, the `assert` module depends on a WeakMap that is populated with the error stacktraces in the overridden function.
This adds handling to fall back to the default implementation if `Error.prepareStackTrace` if the override has been disabled.
This will be upstreamed.
Notes: Fixes an issue where the Node.js `assert` module did not work in the renderer process.
> fix: assert module in the renderer process

- shell/browser/api/electron_api_base_window.cc
- shell/browser/api/electron_api_browser_view.h
- shell/browser/native_browser_view_mac.mm
- spec/api-browser-view-spec.ts
Closes https://github.com/electron/electron/issues/39257
Fixes an issue where `BrowserViews` that have their bounds set prior to being added to a `BrowserWindow` have unexpected incorrect offsets after being added. This was happening because `BrowserView` bounds are intended to be relative to the containing window, and were not updated relative to the window once they were added to one. We fix this by checking whether or not the `BrowserView` had its bounds previously set and ensure they're reset relative to the window on addition.
Notes: Fixed an issue where `BrowserViews` that had their bounds set prior to being added to a `BrowserWindow` could have unexpected incorrect offsets.
> fix: ensure `BrowserView` bounds are always relative to window

- build/args/all.gn
- shell/browser/electron_browser_main_parts.cc
- shell/browser/electron_browser_main_parts.h
- shell/browser/javascript_environment.cc
- shell/browser/javascript_environment.h
- shell/common/node_bindings.cc
- shell/common/node_bindings.h
- shell/renderer/electron_renderer_client.cc
- shell/renderer/electron_renderer_client.h
- shell/renderer/web_worker_observer.cc
- shell/renderer/web_worker_observer.h
- shell/services/node/node_service.cc
- shell/services/node/node_service.h
- `NodeBindings::CreateEnvironment()` now returns a `std::shared_ptr<node::Environment>` instead of a raw pointer. The new shared pointer has a custom deleter that knows how to cleanup both the `node::Environment` and its `node::IsolateData`.
- Remove duplicated cleanup code from `ElectronRenderClient`, `WebWorkerObserver`, and `NodeEnvironment`, which all had code similar to the new deleter.
- Removed now-unused class `NodeEnvironment`.
- side refactor: since only NodeBindings uses `kElectronContextEmbedderDataIndex`, make it a private field.
The initial motivation for this PR was to fix a dangling `raw_ptr` bug in `NodeEnvironment`; but when investigating the code, it looks like there's an opportunity to reduce coupling across the above classes and remove some code duplication. …
> refactor: node::Environment self-cleanup

- docs/tutorial/forge-overview.md
Supersedes #38685.
After discussion with @electron/docs, we wanted to give visibility to these tools without providing a whole other page and avoid duplicating "Boilerplates and CLIs".
I think we should revisit the structure of that page, though!
cc @mikehearn
Notes: none
> docs: mention alternative tooling

- docs/api/web-contents.md
- docs/api/webview-tag.md
- lib/browser/api/web-contents.ts
- spec/api-web-contents-spec.ts
- spec/package.json
- spec/yarn.lock
Refs https://bugs.chromium.org/p/chromium/issues/detail?id=1469961
Refs https://github.com/electron/electron/pull/39375.
`Page.printToPDF` now allows for experimentally generating tagged (accessible) PDFs. We needed to add the property to our implementation in the latest Chromium roll in order to fix compilation errors, but we should surface this new property to developers with a note about its experimental status.
Notes: Added a `generateTaggedPDF` option to `webContents.printToPDF` to allow generating  tagged (accessible) PDFs.
> feat: allow generating accessible pdf with `printToPDF`

- shell/browser/native_window_mac.mm
- spec/api-browser-window-spec.ts
Closes https://github.com/electron/electron/issues/39614
Closes https://github.com/electron/electron/issues/39630.
Fixes an issue where child windows opened when the parent window is _already fullscreen_ did not respect the child windows' fullscreenability and resizability settings.
Confirmed not to regress https://github.com/electron/electron/issues/39077.
Tested with https://gist.github.com/pushkin-/3b4bcdb219eee85789e95f6d94ec8a92
Notes: Fixed an issue where child windows opened when the parent window is _already fullscreen_ did not respect the child windows' fullscreenability and resizability settings.
> fix: ensure windows respect fullscreenability with different resizability values

- shell/browser/native_window_features.cc
Reasons to enable the feature by default:
* This feature flag only takes effect when the user opts into Wayland using one of the command line flags.
* When using a compositor that supports XDG Decoration protocol (KDE and Sway), then this flag has no effect.
* When using a compositor that doesn't support XDG Decoration protocol (GNOME and Weston), then this flag is necessary to have a functional window that can be moved and closed easily. This just adds more friction for users.
* The feature was introduced behind a flag about 18 months ago and there aren't any open issues specific to this feature.
cc-ing reviewers of the original PR @nornagon @zcbenz @ckerr 
> feat: enable WaylandWindowDecorations by default

- appveyor-woa.yml
- appveyor.yml
- script/start-goma.ps1
- [electron/build-tools/#510](https://github.com/electron/build-tools/pull/510) updated Goma to a newer version that requires python3, so the script to start Goma on AppVeyor has to be updated to use python3.
Notes: none
> ci: explicitly use python3 to start goma

- patches/angle/.patches
- patches/angle/cherry-pick-e4669a74888d.patch
- patches/chromium/.patches
- patches/chromium/cherry-pick-1939f7b78eda.patch
- patches/v8/.patches
- patches/v8/merged_squashed_multiple_commits.patch
<details>
<summary>electron/security#396 - 1939f7b78eda from chromium</summary>
[M114-LTS] Don't keep pointer to popped stack memory for :has()
The sibling_features pass into UpdateFeaturesFromCombinator may be
initialized to last_compound_in_adjacent_chain_features if null. The
outer while loop in
AddFeaturesToInvalidationSetsForLogicalCombinationInHas() could then
reference to the last_compound_in_adjacent_chain_features which is
popped from the stack on every outer iteration. That caused an ASAN
failure for reading stack memory that had been popped.
Instead make sure each inner iteration restarts with the same
sibling_features pointer, which seems to have been the intent here.
(cherry picked from commit 5e213507a2f0d6e3c96904a710407b01493670bd)
Bug: 1470477
Change-Id: …
> chore: cherry-pick 3 changes from Release-1-M116

- patches/angle/.patches
- patches/angle/cherry-pick-e4669a74888d.patch
- patches/chromium/.patches
- patches/chromium/cherry-pick-1939f7b78eda.patch
- patches/chromium/cherry-pick-37447eb52a74.patch
- patches/v8/.patches
- patches/v8/merged_squashed_multiple_commits.patch
<details>
<summary>electron/security#396 - 1939f7b78eda from chromium</summary>
[M114-LTS] Don't keep pointer to popped stack memory for :has()
The sibling_features pass into UpdateFeaturesFromCombinator may be
initialized to last_compound_in_adjacent_chain_features if null. The
outer while loop in
AddFeaturesToInvalidationSetsForLogicalCombinationInHas() could then
reference to the last_compound_in_adjacent_chain_features which is
popped from the stack on every outer iteration. That caused an ASAN
failure for reading stack memory that had been popped.
Instead make sure each inner iteration restarts with the same
sibling_features pointer, which seems to have been the intent here.
(cherry picked from commit 5e213507a2f0d6e3c96904a710407b01493670bd)
Bug: 1470477
Change-Id: …
> chore: cherry-pick 4 changes from Release-1-M116

- docs/api/ipc-renderer.md
- docs/api/structures/ipc-renderer-event.md
- docs/breaking-changes.md
- filenames.auto.gni
- lib/renderer/api/ipc-renderer.ts
- lib/renderer/common-init.ts
- shell/browser/api/electron_api_web_contents.cc
- shell/browser/api/electron_api_web_contents.h
- shell/browser/api/electron_api_web_frame_main.cc
- shell/browser/electron_api_ipc_handler_impl.cc
- shell/browser/electron_api_ipc_handler_impl.h
- shell/common/api/api.mojom
- shell/renderer/api/electron_api_ipc_renderer.cc
- shell/renderer/electron_api_service_impl.cc
- shell/renderer/electron_api_service_impl.h
- spec/api-ipc-renderer-spec.ts
- spec/fixtures/module/preload-ipc-ping-pong.js
- spec/ts-smoke/electron/renderer.ts
- typings/internal-ambient.d.ts
Follow-up to #39091
Notes: The deprecated `ipcRenderer.sendTo()` API has been removed.
> chore: remove deprecated `ipcRenderer.sendTo()`

- docs/api/extensions.md
- filenames.gni
- shell/browser/extensions/api/BUILD.gn
- shell/browser/extensions/api/scripting/scripting_api.cc
- shell/browser/extensions/api/scripting/scripting_api.h
- shell/browser/extensions/electron_extensions_browser_api_provider.cc
- shell/common/extensions/api/BUILD.gn
- shell/common/extensions/api/_api_features.json
- shell/common/extensions/api/_permission_features.json
- shell/common/extensions/api/scripting.idl
- shell/common/extensions/electron_extensions_api_provider.cc
- spec/extensions-spec.ts
- spec/fixtures/extensions/chrome-scripting/background.js
- spec/fixtures/extensions/chrome-scripting/main.js
- spec/fixtures/extensions/chrome-scripting/manifest.json
Closes https://github.com/electron/electron/issues/37876.
This PR adds support for [`chrome.scripting`](https://developer.chrome.com/docs/extensions/reference/scripting).
From reference docs: 
> `chrome.scripting` allows API to inject JavaScript and CSS into websites. This is similar to what you can do with [content scripts](https://developer.chrome.com/docs/extensions/mv3/content_scripts/). But by using the [chrome.scripting](https://developer.chrome.com/docs/extensions/reference/scripting/) namespace, extensions can make decisions at runtime. 
This represents an important step towards proper support of Manifest V3. Specifically -  `chrome.scripting` supersedes `chrome.tabs.executeScript`, which is gone in Manifest V3. It's commonly used in several DevTools extensions, including [React …
> feat: support `chrome.scripting` extension  APIs

- lib/browser/api/web-contents.ts
- spec/api-web-contents-spec.ts
- spec/fixtures/pages/navigate_in_page_and_wait.html
Reintroduce fix for loadURL promise resolved to early when browser initiated in-page navigation.
Fix was revered because test which was added in original PR was failing on linux. Now test is fixed. 
Original PR: https://github.com/electron/electron/pull/39260
Revert PR: https://github.com/electron/electron/pull/39481
Notes: Fix problem with promise resolved to early when browser initiated in-page navigation.
> fix: promise resolved to early when browser initiated in-page navigation v2

- README.md
Follow-up to #38917
https://github.com/electron/electron/blob/d42a94dddeb86d349c050c2ee59b135bd6c8245c/docs/breaking-changes.md?plain=1#L57-L62
Notes: none
> docs: fix the minimum supported macOS version to Catalina

- patches/chromium/.patches
- patches/chromium/cherry-pick-35c06406a658.patch
<details>
<summary>electron/security#399 - 35c06406a658 from chromium</summary>
Handle object destruction in MediaStreamDeviceObserver
MSDO executes some callbacks that can result in the destruction of
MSDO upon an external event such as removing a media device or the
user revoking permission.
This CL adds code to detect this condition and prevent further
processing that would result in UAF. It also removes some invalid
DCHECKs.
Drive-by: minor style fixes
(cherry picked from commit 7337133682ab0404b753c563dde2ae2b1dc13171)
Bug: 1472492, b/296997707
Change-Id: I76f019bb110e7d9cca276444bc23a7e43114d2cc
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4798398
Reviewed-by: Palak Agarwal <agpalak@chromium.org>
Commit-Queue: Guido Urdaneta <guidou@chromium.org> …
> chore: cherry-pick 1 changes from Release-2-M116

- .github/workflows/branch-created.yml
- .github/workflows/issue-commented.yml
- .github/workflows/issue-labeled.yml
- .github/workflows/issue-unlabeled.yml
- .github/workflows/pull-request-labeled.yml
- .github/workflows/stale.yml
The main motivation here is that actions taken by the default `github-actions` bot will not trigger other workflows. This caused some of the automation added in #39464 (which intended to change the status of an issue on the issue triage project when an issue is unlabeled) not to work since the label being removed was done by `github-actions` so the other workflow was not triggered.
For consistency I've changed all issue triage actions to be done by the same GitHub App, which will make it easier to do things like search or checking in other automation, and will let us provide a bit of a more polished UX instead of having it all coming from `github-actions`.
This PR also updates all token generation from using `npx @electron/github-app-auth` to using the new …
> ci: use new GitHub App for issue triage related actions

- README.md
- docs/api/app.md
- docs/api/browser-window.md
- docs/api/context-bridge.md
- docs/api/protocol.md
- docs/api/session.md
- docs/api/web-contents.md
- docs/tutorial/asar-archives.md
- docs/tutorial/automated-testing.md
- docs/tutorial/dark-mode.md
- docs/tutorial/devtools-extension.md
- docs/tutorial/ipc.md
- docs/tutorial/launch-app-from-url-in-another-app.md
- docs/tutorial/message-ports.md
- docs/tutorial/native-file-drag-drop.md
- docs/tutorial/offscreen-rendering.md
- docs/tutorial/performance.md
- docs/tutorial/quick-start.md
- docs/tutorial/recent-documents.md
- docs/tutorial/represented-file.md
- docs/tutorial/tutorial-3-preload.md
- docs/tutorial/window-customization.md
- docs/tutorial/windows-taskbar.md
Core Node.js modules (e.g. `os`, `fs`, `path`) can be [imported using the `node:` prefixed syntax as of Node.js 16.0/14.18](https://nodejs.org/dist/latest-v18.x/docs/api/modules.html#core-modules). Node's own documentation has moved to use this prefix syntax for clarity reasons (https://github.com/nodejs/node/pull/42752).
After discussing with @electron/docs, we believe we should migrate the syntax in our docs as well to follow suit.
> **Note**
> None of the examples in `breaking-changes.md` have been updated since users may be on older versions of Electron that do not support the `node:` syntax.
Notes: none
> docs: use `node:` imports for node core modules

- docs/api/session.md
This isn't being processed properly by `electron/docs-parser`, looks like it's due to multiple backticked types being union'd together, when we normally do it inside of the backticks. See the [Artifact Comparison check output](https://github.com/electron/electron/pull/39697/checks?check_run_id=16363303239) for difference.
Notes: none
> docs: fix return typing of ses.getExtension

- shell/browser/extensions/api/scripting/scripting_api.cc
- shell/browser/extensions/api/scripting/scripting_api.h
Refs:
- https://github.com/electron/electron/pull/39531
- https://github.com/electron/electron/pull/39395
Adapts to changes from:
- CL:4727292
- CL:4781259
- CL:4646844
- CL:4774717
- CL:4795146
Fixes broken scripting API compilation after most recent chrome roll.
Notes: none
> fix: broken `chrome.scripting` compilation

- spec/api-web-frame-spec.ts
> test: add missing tests to api-web-frame-spec.ts

- docs/api/web-contents.md
- docs/breaking-changes.md
- lib/browser/api/web-contents.ts
- shell/browser/api/electron_api_printing.cc
- spec/api-web-contents-spec.ts
- spec/ts-smoke/electron/main.ts
- typings/internal-electron.d.ts
Following up #39356 with the removal.
Notes: The deprecated `webContents.getPrinters()` API has been removed.
> chore: remove deprecated `webContents.getPrinters()`

- .circleci/config/base.yml
Refs https://chromium-review.googlesource.com/c/chromium/tools/depot_tools/+/4836379
Notes: none.
> build: fix `depot_tools` patch application

- lib/browser/api/dialog.ts
- lib/browser/init.ts
- spec/api-browser-window-spec.ts
- spec/api-debugger-spec.ts
- spec/api-protocol-spec.ts
- spec/api-session-spec.ts
- spec/api-web-request-spec.ts
- spec/asar-spec.ts
- spec/chromium-spec.ts
- spec/webview-spec.ts
Identified by https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-string-replace-all.md
Notes: none
> refactor: use `replaceAll()` instead of `replace()` when appropriate

- shell/browser/api/electron_api_web_contents.cc
- shell/browser/browser_mac.mm
- shell/browser/ui/inspectable_web_contents.cc
- shell/common/application_info.cc
- shell/common/application_info.h
https://github.com/electron/electron/pull/35209 defaulted to `detach` position when opening devtools without any predefined state to workaround a bug in chromium, this took away the docking feature of devtools on Windows. https://github.com/electron/electron/pull/35754 was later added to respect the `state` option when opening devtools, although it is a good enough solution it takes away the option to rely on preferred dock state persisted to user data dir when opening devtools without any arguments.
This PR attempts to respect the persisted preferred dock state when WCO is enabled on Windows and instead of detaching the devtools it will now `undock` depending the dock state corresponding to the position of window controls. This allows users to still have control over the dock position …
> fix: devtools allow restoring saved dock state on Windows

- shell/common/extensions/api/tabs.json
Fixes two errors in Chrome extensions that are thrown when extensions listen for `chrome.tabs`. Initially, these weren't added to our `tabs.json` file as we didn't initially intend to support them. However, the way that extension generation works, omitting them from the JSON file actually means that attempting to listen to them _at all_ will throw an error, which we don't want.  We don't need to implement them or make them work as intended in order to define them as valid events to listen to here. No documentation or tests are changed as support has not changed as a result of this PR.
Notes: Fixed an error where listening to certain `chrome.tabs` events would throw incorrectly.
> fix: prevent errors when extensions listen for `chrome.tabs` events

- shell/browser/native_window_mac.mm
Screenshots included for reference
| | Windowed | Fullscreen |
|-|-|-|
| **Before** | <img width="912" alt="image" src="https://github.com/electron/electron/assets/6634592/e1408faa-4196-4bbe-89d3-b98b4660c2b5"> | <img width="1728" alt="image" src="https://github.com/electron/electron/assets/6634592/a55ebc1c-099d-4a84-8808-0299a6eb9722"> |
| **After** | <img width="912" alt="image" src="https://github.com/electron/electron/assets/6634592/fd2ce9c2-9c4f-4799-9d62-5a069543a8d6"> | <img width="1728" alt="image" src="https://github.com/electron/electron/assets/6634592/a3a9e956-f5f7-44a2-8e44-5c4bafa2275d"> |
Note in fullscreen the titlebar only "peeks" over the content if you mouseover the top of the screen, it doesn't take up any frame dimensions
Notes: Fixed issue where titlebar would be …
> fix: make titlebar opaque while fullscreen

- shell/common/node_bindings.cc
- shell/common/node_bindings.h
- shell/common/node_bindings_linux.cc
- shell/common/node_bindings_mac.cc
- shell/common/node_bindings_win.cc
- shell/renderer/electron_renderer_client.cc
- shell/renderer/electron_renderer_client.h
Another `raw_ptr<>` bugifx PR similar to #39521, #39539
Main fix: declare `NodeBindings::worker_loop_` before `NodeBindings::uv_loop_`, since the latter is a `raw_ptr<>` that may point to the former. If `uv_loop_` is declared first, it can be a dangling `raw_ptr<>` in the destructor since classes destroy their fields in reverse order of declaration.
Secondary cleanups: reduce the scope and mutability of related fields & methods by making them `const` or `private` as applicable.
CC @codebytere @deepak1556 @VerteDinde who did review on previous PRs
Notes: none
> fix: raw_ptr destruction order in NodeBindings

- .github/workflows/issue-unlabeled.yml
The blocked label is removed after the issue is closed by the stale workflow, so don't change the triage status for closed issues.
Notes: none
> ci: ignore blocked label removed on closed issues

- patches/chromium/.patches
- patches/chromium/cherry-pick-26175b0903d8.patch
- patches/chromium/cherry-pick-74a2eb9c8cb2.patch
- patches/v8/.patches
- patches/v8/cherry-pick-038530c94a06.patch
<details>
<summary>electron/security#402 - 74a2eb9c8cb2 from chromium</summary>
Readd lock when ObserverListMap::erase()
We should lock when remove an item from the map.
This lock was accidentally removed in:
https://chromium-review.googlesource.com/c/chromium/src/+/4280021
(cherry picked from commit a41479ba6efb5e48b82edad972c7dded6f385b79)
Bug: 1469928
Change-Id: I2512e14d4ad9b246cadae947023dbccb5158da51
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4790983
Auto-Submit: Yoichi Osato <yoichio@chromium.org>
Reviewed-by: Yoichi Osato <yoichio@chromium.org>
Reviewed-by: Koji Ishii <kojii@chromium.org>
Commit-Queue: Koji Ishii <kojii@chromium.org>
Cr-Original-Commit-Position: refs/heads/main@{#1187668}
Reviewed-on: …
> chore: cherry-pick 3 changes from Release-3-M116

- shell/browser/native_window_mac.mm
- shell/browser/ui/cocoa/electron_ns_window.h
- shell/browser/ui/cocoa/electron_ns_window.mm
Closes https://github.com/electron/electron/issues/35403.
Patches a gap in https://github.com/electron/electron/pull/35421 - we also need to prevent fullscreen entrance via menu.
Notes: Fixed an issue where BrowserWindows could crash on macOS with `frame: false` and `roundedCorners: false` when going fullscreen.
> fix: fullscreen crashing with no roundedCorners and no frame

- patches/v8/.patches
- patches/v8/cherry-pick-038530c94a06.patch
<details>
<summary>electron/security#401 - 038530c94a06 from v8</summary>
Merged: [turbofan] Growing a non-JSArray packed elements kind makes it holey
Bug: chromium:1473247
(cherry picked from commit ae7dc61652805bc8e2b060d53b2b6da7cf846b6f)
Change-Id: I5268513bc91ca0cc18e3e2115244c0b090afa0da
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/4831892
Auto-Submit: Leszek Swirski <leszeks@chromium.org>
Owners-Override: Leszek Swirski <leszeks@chromium.org>
Commit-Queue: Darius Mercadier <dmercadier@chromium.org>
Reviewed-by: Darius Mercadier <dmercadier@chromium.org>
Commit-Queue: Leszek Swirski <leszeks@chromium.org>
Cr-Commit-Position: refs/branch-heads/11.6@{#34} …
> chore: cherry-pick 1 changes from Release-3-M116

- shell/common/gin_converters/blink_converter.cc
- spec/api-web-contents-spec.ts
- spec/fixtures/pages/key-events.html
Closes https://github.com/electron/electron/issues/39610.
Fixed an issue where accelerators representing DOM keys were not correctly converted in `webContents.sendInputEvent()`. This was happening because our internal conversion logic was correctly parsing strings their respective `ui::KeyboardCode` values, but then failing to check whether the DOM code represented a standalone valid character. This led to an issue where a call to, for example, `w.webContents.sendInputEvent({ keyCode: 'Plus', type: 'char' })` would get [truncated](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/public/common/input/web_keyboard_event.h;l=20) and then sent to the input as the char string and not the dom key character if one existed.
Notes: Fixed an issue where accelerators …
> fix: `keyCode`s being incorrectly converted in `webContents.sendInputEvent()`

- shell/renderer/electron_renderer_client.cc
- shell/services/node/node_service.cc
- shell/services/node/node_service.h
Fix an order-of-destruction issue in NodeService: `js_env_` depends on the uv_loop from `node_bindings_`, but `node_bindings_` was being destroyed before `js_env_`.
This was ameliorated by the fact that the uv_loop's destruction process is complex -- the memory is freed in a callback after `uv_close()` finishes; see UvHandle in node_bindings.h for details --  but the real fix is to just get NodeService's fields' order correct.
Notes: none
> fix: NodeService order-of-destruction issue

- package.json
- yarn.lock
In support of #39722, brings support for using `@nolint` to skip linting of specific code blocks.
Notes: none
> build: update @electron/lint-roller to 1.9.0

- shell/browser/javascript_environment.h
- shell/common/gin_helper/event_emitter_caller.cc
- shell/common/gin_helper/locker.cc
- shell/common/gin_helper/locker.h
- shell/common/node_bindings.cc
Cleaning out some unused code. I did this while working on another `raw_ptr<>` fix; but since these changes aren't really related, I'm putting them in a standalone PR.
- remove unused field `gin_helper::Locker::g_is_renderer_process`
- remove unused field `gin_helper::Locker::g_is_browser_process`
- remove unused declaration `gin_helper::Locker::new()`
- remove unused declaration `gin_helper::Locker::delete()`
And `const`ify a couple of fields:
- declare `electron::JavascriptEnvironment::locker_` as `const`
- declare `gin_helper::Locker::locker_` as `const`
No particular stakeholders, but all reviews/feedback are welcome!
Notes: none
> refactor: remove unused fields, methods in gin_helper::Locker

- shell/browser/javascript_environment.h
- shell/common/gin_helper/event_emitter_caller.cc
- shell/common/gin_helper/locker.cc
- shell/common/gin_helper/locker.h
- shell/common/node_bindings.cc
Manually backport https://github.com/electron/electron/pull/39803 to 27-x-y.
No interesting changes relative to 39803; just had some minor code shear that tripped trop.
Notes: none
> refactor: remove unused Locker fields

- .github/workflows/issue-commented.yml
- .github/workflows/issue-labeled.yml
Follow-up to #39635. Does not remove blocked label if the comment is from a bot, and fixes the account name for the only one comment logic.
Notes: none
> ci: ignore actions taken by triage bot

- patches/webrtc/.patches
- patches/webrtc/fix_check_pipewire_init_before_creating_generic_capturer.patch
Check if PipeWire can be initialized before creating generic capturer. This harmonizes the conditions with the ones used in Linux implementations of `DesktopCapturer::CreateRawScreenCapturer` and `DesktopCapturer::CreateRawWindowCapturer`. This allows `desktopCapturer.getSources()` to fallback to X11 capture when PipeWire library is not available.
cc @VerteDinde 
Notes: none
> fix: check PipeWire init before creating generic capturer

- patches/node/chore_update_fixtures_errors_force_colors_snapshot.patch
- patches/node/test_formally_mark_some_tests_as_flaky.patch
The node test `parallel/test-debugger-random-port-with-inspect-port` has been flaky of late, so this PR marks it as such.
Additionally, the node test `parallel/test-node-output-errors` has started failing due to a line number change, so this PR also updates the patch for that test to fix the issue.
Notes: none
> test: fixup node flakes

- patches/chromium/fix_crash_loading_non-standard_schemes_in_iframes.patch
Refactors to avoid interfering with origin security policies of known schemes and reuses the same security check api for non standard schemes as well.
> refactor: fix_crash_loading_non-standard_schemes_in_iframes.patch

- docs/api/structures/browser-window-options.md
- shell/browser/native_window_mac.mm
- shell/common/options_switches.cc
- shell/common/options_switches.h
This option is already ignored and has no effect since #27489.
Notes: none
> chore: remove no-op `fullscreenWindowTitle` option

- patches/v8/.patches
- patches/v8/cherry-pick-cf1d4d3c0b6e.patch
<details>
<summary>electron/security#404 - cf1d4d3c0b6e from v8</summary>
Merged: [interpreter] Fix TDZ elision in do-while tests
(cherry picked from commit 1626e229a8965f975db6e9da0e7ab85f8c74333f)
Change-Id: Ifb7461b6cfd62a10936470a760cb505cc5e1c60f
Fixed: chromium:1477588
Bug: v8:13723
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/4862981
Auto-Submit: Shu-yu Guo <syg@chromium.org>
Cr-Commit-Position: refs/branch-heads/11.6@{#38}
Cr-Branched-From: 95cbef20e2aa556a1ea75431a48b36c4de6b9934-refs/heads/main@{#88340}
</details>
Notes:
* Security: backported fix for 1477588.
> chore: cherry-pick 1 changes from Release-0-M117

- docs/api/system-preferences.md
- shell/browser/api/electron_api_system_preferences.cc
- shell/browser/api/electron_api_system_preferences.h
- shell/browser/api/electron_api_system_preferences_mac.mm
- spec/ts-smoke/electron/main.ts
Exposes an [api](https://developer.apple.com/documentation/appkit/nsworkspace/1533006-accessibilitydisplayshouldreduce) that reads the System Preferences to determine whether the app avoids using semitransparent backgrounds. If the property is  TRUE, don't use use semitransparent backgrounds in the UI.
This setting can be changed by choosing System Preferences > Accessibility > Display and selecting "Reduce transparency".
Notes: Exposed an API to allow apps to determine whether to avoid using semitransparent backgrounds.
> feat: expose app accessibility transparency settings api

- docs/tutorial/message-ports.md
fix example multiplying object * number. It should multiply number * number.
Notes: none
> docs: tiny update on example message-ports.md

- patches/node/tls_ensure_tls_sockets_are_closed_if_the_underlying_wrap_closes.patch
- both #39928 and
- #39915 landed, causing a patch issue.  This PR fixes that patch.
Notes: none
> build: update patch

- patches/node/chore_update_fixtures_errors_force_colors_snapshot.patch
- #39889 was merged with a failing node test - this PR fixes that failing test.
Notes: none
> test: fixup parallel/test-node-output-error test

- docs/breaking-changes.md
It has been deprecated since #29168
Notes: The `app.runningUnderRosettaTranslation` property has been deprecated.
> chore: add deprecated `app.runningUnderRosettaTranslation` to breaking-changes.md

- docs/tutorial/quick-start.md
Added 2 points for the deploiement chapter with Electron Forge.
These 2 points are required, else the rpmbuild will fail.
- install rpm (it was not mentionned in the doc)
- add a non-blank description to the package.json file of your project
Notes: none
> docs: Quick Start | Electron Forge chapter requirements updated

- BUILD.gn
- buildflags/buildflags.gni
- script/get-git-version.py
- script/lib/get-version.js
- script/print-version.py
For Linux/BSD packagers and some vendor builders, they are building electron from source code tarball instead of checking out the git repository, in which case reading electron version from git tag in gn configuration will not work.
This PR adds a `override_electron_version` variable to allow skipping the step of reading git tag.
Notes: none
> build: allow overriding electron version

- shell/browser/native_window.cc
- shell/browser/native_window_mac.h
- shell/browser/native_window_mac.mm
Closes https://github.com/electron/electron/issues/39786.
On macOS the size constraints must be directly applied to NSWindow by calling `setMin/MaxSize` methods, https://github.com/electron/electron/pull/38974 did a modification to `SetSizeConstraints` which accidentally cut off the call to NSWindow methods.
Unfortunately I am unable to write a test for size constraints code, because changing window size with code ignores the size constraints in Cocoa.
Notes: Fix window size constraints not working on macOS.
> fix: apply size constraints to NSWindow

- shell/browser/native_window_mac.mm
Closes https://github.com/electron/electron/issues/39960.
Fixes an issue where vibrant windows incorrectly have square corners when they're modals. This was initially changed in https://github.com/electron/electron/pull/24250 in response to the current design of macOS whereby modals were flush to the top of their parent window, which is no longer the case. There also isn't really a concept of framelessness on parented modals, so that condition only applies to non-modal windows.
<p>
</p>
</details>
<p>
</p>
</details> 
Notes: Fixes an issue where vibrant windows incorrectly have square corners when they're modals on macOS.
> fix: rounded corners on vibrant macOS modals

- shell/browser/extensions/api/resources_private/resources_private_api.cc
Fix build with `enable_pdf_viewer = false`. Without this fix, the following linker error occurs:
<details><summary>Linker Error</summary>
<p>
```
ld64.lld: error: undefined symbol: pdf_extension_util::AddAdditionalData(bool, bool, base::Value::Dict*)
>>> referenced by resources_private_api.cc:54 (../../electron/shell/browser/extensions/api/resources_private/resources_private_api.cc:54)
>>>               obj/electron/electron_lib/resources_private_api.o:(symbol extensions::ResourcesPrivateGetStringsFunction::Run()+0x84)
ld64.lld: error: undefined symbol: pdf_extension_util::AddStrings(pdf_extension_util::PdfViewerContext, base::Value::Dict*)
>>> referenced by resources_private_api.cc:52 (../../electron/shell/browser/extensions/api/resources_private/resources_private_api.cc:52)
>>> …
```
> build: fix with `enable_pdf_viewer = false`

- shell/browser/ui/win/electron_desktop_window_tree_host_win.cc
- shell/browser/ui/win/electron_desktop_window_tree_host_win.h
The window contents of Electron windows are marked as transparent even though neither `transparent` nor `opacity` settings are set in the `BrowserWindow` options.
**Debugging DirectComposition redraws**
Chromium 118 has a new flag called `DCompDebugVisualization` that uses [EnableDrawRegions](https://learn.microsoft.com/en-us/windows/win32/api/dcomp/nf-dcomp-idcompositionvisualdebug-enableredrawregions) to display on the screen sections of a window that are redrawn by DirectComposition.
**The problem**
With `DCompDebugVisualization`, we can notice a difference in the frequency of redraws of `<video>` elements in Chromium compared to a regular non-transparent window in Electron.
While a video stream is rendered on screen, almost no redraws are displayed in Chromium. On Electron, a redraw …
> fix: set window contents as opaque to decrease DWM GPU usage

- docs/tutorial/process-model.md
- docs/tutorial/tutorial-2-first-app.md
These have been present in our code for a while. We also use them internally in our tests and have recently added them to our Fiddle examples.
Notes: none
> docs: document type-specific module aliases

- lib/browser/api/web-contents.ts
Closes https://github.com/electron/electron/issues/38837.
Fixes an issue where `webContents.print` could fail when `options` is a frozen object.
Notes: Fixed an issue where `webContents.print` could fail when `options` is a frozen object.
> fix: failure on immutable `webContents.print(options)`

- patches/config.json
- patches/libvpx/.patches
- patches/libvpx/cherry-pick-3fbd1dca6a4d.patch
VP8: disallow thread count changes
Currently allocations are done at encoder creation time. Going from
threaded to non-threaded would cause a crash.
Bug: chromium:1486441
Change-Id: Ie301c2a70847dff2f0daae408fbef1e4d42e73d4
Notes: Security: backported fix for CVE-2023-5217.
> chore: cherry-pick 3fbd1dca6a4d from libvpx

- shell/browser/ui/views/inspectable_web_contents_view_views.cc
When BrowserView bounds are set from js, those might not trigger layout immediately, sometimes propagating InvalidateLayout call to parent. View is marked as needing layout, expecting to receive it from parent on next layout call. The problem is that BrowserView's view is added as child of InspectableWebContentsViews which does not call setBounds (which would trigger layout) on all of it's children when doing it's layout, so it skips propagating Layout call to its children BrowserViews views, even though those were marked as needing layout.
Call base class View::Layout which will iterate over views' children and call Layout on those that were marked as needing them.
Unfortunately I failed to create a spec test that would repro this behavior. It seems user click on button (like in gist in …
> fix: propagate layout call to all children of `InspectableWebContentsViewViews`

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/workflows/issue-labeled.yml
- .github/workflows/issue-opened.yml
- .github/workflows/issue-unlabeled.yml
- .github/workflows/pull-request-labeled.yml
Switches to [`dsanders11/project-actions`](https://github.com/dsanders11/project-actions) as `github/update-project-action` is not being adequately maintained.
Adds a workflow to add issues to the issue triage board as GitHub has a bug which prevents filtering on the bug label currently, and it also lets set custom fields while we do so. Removes the projects field from the bug template, which was the initial attempt at working around the GitHub bug, but it turns out that doesn't work if the project is private.
Notes: none
> ci: update automation workflows

- .github/workflows/branch-created.yml
- .github/workflows/stable-prep-items.yml
A few different goodies here. The generic logic around creating the new release project board from our template has been pushed to [`dsanders11/project-actions`](https://github.com/dsanders11/project-actions/) where it's got full test coverage (including integration tests) and can be iterated on without needing to involve `e/e`.
The project visibility unfortunately cannot be set to public automatically due to a GitHub bug, so for now that's commented out and we'll manually make it public.
As part of this change, there's added support for setting field values on draft issues when the new release project board is created. This can be done by adding an HTML comment to the draft issue body which maps field names to field values, and is done after the normal mustache templating so the values …
> ci: update release project board workflows

- shell/browser/api/electron_api_app.cc
GetPathConstant calls base::internal::flat_tree<Key, GetKeyFromValue, KeyCompare, Container>::find(Key const&) const which is not constexpr. GCC 12 and earlier raise a compile error on this.
Notes: none
> chore: remove invalid constexpr qualification

- lib/utility/init.ts
- spec/api-utility-process-spec.ts
- spec/fixtures/api/utility-process/esm.mjs
- spec/fixtures/api/utility-process/exception.mjs
Closes #40031
I'm not aware of any synchronous module load guarantees / expectations with the utility process API so just swapping to using the ESM loader instead of the CJS loader should work fine.  (the esm loader falls back to CJS) 
Notes: The `UtilityProcess` API now supports ESM entrypoints
> fix: support esm entrypoint to utility process

- shell/browser/extensions/api/tabs/tabs_api.cc
- spec/extensions-spec.ts
- spec/fixtures/extensions/chrome-tabs/api-async/background.js
Refs:
- https://chromium-review.googlesource.com/c/chromium/src/+/4772028
- https://chromium-review.googlesource.com/c/chromium/src/+/4264656
- https://chromium-review.googlesource.com/c/chromium/src/+/4712150
Updates `chrome.tabs.update` url handling to match upstream Chromium. 
Notes: none.
> chore: update extensions url handling to match upstream

- docs/api/app.md
- docs/breaking-changes.md
- shell/browser/api/electron_api_app.cc
- shell/browser/api/electron_api_app.h
- shell/browser/api/electron_api_app_mac.mm
- spec/ts-smoke/electron/main.ts
Follow-up to #39897
Notes: Removed deprecated `app.runningUnderRosettaTranslation()`
> chore: remove deprecated `app.runningUnderRosettaTranslation()`

- docs/tutorial/snapcraft.md
Added instructions to bundle PipeWire library in snap packages. PipeWire is dynamically loaded by Chromium and Electron, so it has to be bundled in a snap package. However, Ubuntu does not include libpipewire in any base snap, which necessitates manually bundling the library in every package. I've also updated the base snap in the example to the newest version.
I've tested the instructions using a [barebones Electron application](https://github.com/aiddya/desktop-capture-preview). I've also tested the changes in the example `snapcraft.yaml`. In my testing, `snapcraft` requires the output files to be world readable and writable and the files created by `electron-packager` are not. This is regardless of the base snap version. Once the permission issues are fixed, the changes create a valid …
> docs: add PipeWire integration instructions for snaps

- docs/api/browser-window.md
- shell/browser/api/electron_api_base_window.cc
- shell/browser/api/electron_api_base_window.h
- shell/browser/native_window.cc
- shell/browser/native_window.h
- shell/browser/native_window_mac.h
- shell/browser/native_window_mac.mm
- spec/api-browser-window-spec.ts
Closes https://github.com/electron/electron/issues/18138.
Continues https://github.com/electron/electron/pull/18141 which was closed.
Add a `tabbingIdentifier` runtime property to `BrowserWindow`. This allows, for example, properly restoring an arrangement of multiple groups of tabs.
Notes: Added a `tabbingIdentifier` property to `BrowserWindow`.
> feat: add `tabbingIdentifier` property to `BrowserWindow`

- chromium_src/BUILD.gn
- shell/browser/electron_browser_client.cc
- shell/browser/hid/electron_hid_delegate.cc
- shell/browser/plugins/plugin_utils.cc
- shell/browser/usb/electron_usb_delegate.cc
- shell/renderer/printing/print_render_frame_helper_delegate.cc
- shell/renderer/renderer_client_base.cc
Closes https://github.com/electron/electron/issues/39987.
Fixes build when `enable_electron_extensions=false`. The new dependencies added to `chromium_src/BUILD.gn` are required for functionality in the `webRequest` module.
Notes: Fixes failing build when `enable_electron_extensions=false`.
> fix: failing build with `enable_electron_extensions=false`

- shell/browser/native_window_mac.h
- shell/browser/native_window_mac.mm
- shell/browser/ui/cocoa/electron_ns_window_delegate.mm
- spec/api-browser-window-spec.ts
Closes https://github.com/electron/electron/issues/39704.
Fixes an issue where calling `show()` on a child `BrowserWindow` would incorrectly show all other children attached to the same parent. This was happening because logic to handle de- and re-attachment of children to a parent window did not properly take into account whether the window was visible prior. I will likely follow this up with a bit more of a cleanup around parent-child attachment logic but this fixes the immediate issue [similarly to Chromium](https://source.chromium.org/chromium/chromium/src/+/main:components/remote_cocoa/app_shim/native_widget_ns_window_bridge.h;l=413;drc=7593550779a58b1caf30dcbf6adc73eb52b617a4;bpv=1;bpt=1)
Notes: Fixes an issue where calling `show()` on a child `BrowserWindow` would show all other …
> fix: all children showing when showing child window

- patches/chromium/.patches
- patches/chromium/cherry-pick-b11e7d07a6f4.patch
- patches/v8/.patches
- patches/v8/cherry-pick-b0ad701a609a.patch
<details>
<summary>electron/security#409 - b0ad701a609a from v8</summary>
Merged: [builtins] Clear FixedArray slot in Promise builtins
(cherry picked from commit f1884222ad56734e56d80f9707e0e8279af9049e)
Bug: chromium:1479104
Change-Id: Iddc16d8add4dc6bf6f55f537da44770bea6f4bc3
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/4862980
Auto-Submit: Shu-yu Guo <syg@chromium.org>
Cr-Commit-Position: refs/branch-heads/11.6@{#36}
Cr-Branched-From: 95cbef20e2aa556a1ea75431a48b36c4de6b9934-refs/heads/main@{#88340}
</details>
<details>
<summary>electron/security#408 - b11e7d07a6f4 from chromium</summary>
M117: …
> chore: cherry-pick 2 changes from Release-1-M117

- lib/browser/api/app.ts
- lib/browser/api/web-contents.ts
- lib/common/deprecate.ts
- shell/browser/api/electron_api_web_contents.cc
Regressed by https://github.com/electron/electron/pull/33557/files#diff-ee83fd1a162a48cfe0ee8849a859f6d6700ceb6aa2bdee23b875d8941620c7c6
**`renderer-process-crashed` event**
```js
app.on('renderer-process-crashed', (event, wc, killed) => {
console.log('app: renderer-process-crashed', wc.id, killed)
})
app.on('render-process-gone', (event, wc, details) => {
console.log('app: render-process-gone', wc.id, details)
})
mainWindow.webContents.on('crashed', (event, killed) => {
console.log('webContents: crashed', killed)
})
mainWindow.webContents.on('render-process-gone', (event, details) => {
console.log('webContents: render-process-gone', details)
})
```
before:
```
app: renderer-process-crashed 1 true
webContents: crashed true
app: renderer-process-crashed 1 { reason: 'killed', exitCode: 2 } …
```
> fix: crashed events deprecation

- shell/browser/ui/views/inspectable_web_contents_view_views.cc
Closes https://github.com/electron/electron/issues/39991.
Fixes an issue where if a user opened DevTools in detached mode, minimized the DevTools window, and then toggled DevTools off and on again, the window would no longer be visible to the user. This was happening because our existing logic saved the last known DevTools window bounds prior to closure, and then attempted to restore to those bounds if the DevTools window was re-opened. However, if the window was minimized prior to being toggled off, then the saved bounds would be wildly inaccurate as a result of our calling `GetWindowBoundsInScreen()`:
```console
InspectableWebContents::SaveDevToolsBounds(): -16000,-16000 157x25
```
This fixes that by using the normal bounds if the window is not currently on screen.
Tested with …
> fix: toggling DevTools while minimized on Windows

- patches/chromium/.patches
- patches/chromium/cherry-pick-309b604c4e88.patch
- patches/chromium/cherry-pick-b11e7d07a6f4.patch
- patches/v8/.patches
- patches/v8/cherry-pick-b0ad701a609a.patch
<details>
<summary>electron/security#409 - b0ad701a609a from v8</summary>
Merged: [builtins] Clear FixedArray slot in Promise builtins
(cherry picked from commit f1884222ad56734e56d80f9707e0e8279af9049e)
Bug: chromium:1479104
Change-Id: Iddc16d8add4dc6bf6f55f537da44770bea6f4bc3
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/4862980
Auto-Submit: Shu-yu Guo <syg@chromium.org>
Cr-Commit-Position: refs/branch-heads/11.6@{#36}
Cr-Branched-From: 95cbef20e2aa556a1ea75431a48b36c4de6b9934-refs/heads/main@{#88340}
</details>
<details>
<summary>electron/security#408 - b11e7d07a6f4 from chromium</summary>
M117: …
> chore: cherry-pick 3 changes from Release-1-M117

- shell/browser/api/electron_api_browser_window.cc
- shell/browser/native_window.cc
A follow-up to #39708 - this PR fixes applying transparency as a background color when vibrancy is also set. 
Closes https://github.com/electron/electron/issues/40039
Notes: Fixed an issue with applying vibrancy on non-transparent windows on MacOS.
> fix: fix vibrancy applying without transparency on MacOS

- filenames.auto.gni
- lib/browser/api/app.ts
- lib/browser/api/crash-reporter.ts
- lib/browser/api/web-contents.ts
- lib/common/api/deprecate.ts
- lib/common/api/module-list.ts
- lib/common/define-properties.ts
- lib/sandboxed_renderer/api/module-list.ts
- spec/api-app-spec.ts
- spec/api-web-contents-spec.ts
- spec/deprecate-spec.ts
- typings/internal-electron.d.ts
Revert #35311 as it prevents us from testing deprecation warnings as the tests contain a different copy of the deprecate module than Electron itself
Also add missing tests for deprecated event warnings to unblock #40089
Notes: none
> chore: restore deprecate as an internal module

- BUILD.gn
- shell/app/electron_main_mac.cc
This PR reverts https://github.com/electron/electron/pull/33832 for 2 reasons:
1. The `EarlyMallocZoneRegistration` call is currently a no-op since PartitionAlloc is disabled in Electron.
2. The prerequisite of calling `EarlyMallocZoneRegistration` is that the whole application is built as a library and the executable binary loads the app by `dlopen` and `dlsym` (https://bugs.chromium.org/p/chromium/issues/detail?id=1452229 has some background information on this). Electron is currently still linking the executable binaries to the `Electron Framework` which does not match the prerequisite and will crash when  PartitionAlloc is enabled.
This PR will unblock https://github.com/electron/electron/pull/33981.
Notes: none
> fix: remove EarlyMallocZoneRegistration call

- spec/api-web-contents-spec.ts
Regressed in #37280 and #37316. It needs to be reverted to the original version from #27730 to actually test for the potential crash.
Notes: none
> test: fix "crashed event does not crash main process when destroying WebContents in it"

- .circleci/config/base.yml
The call to diagnose_goma_log.py after builds was failing with the error:
```
File "/home/builduser/project/build-tools/third_party/goma/diagnose_goma_log.py", line 184
yield from f
^
SyntaxError: invalid syntax
```
eg see https://app.circleci.com/pipelines/github/electron/electron/75261/workflows/0ea342e8-4faa-43bc-a706-9f59312f2c10/jobs/1616734/parallel-runs/0/steps/0-127.
This PR explictly runs that utility with python3 which fixes the issue.
Notes: none
> ci: fixup diagnose_goma_log.py call

- docs/api/tray.md
- shell/browser/ui/win/notify_icon.cc
- shell/browser/ui/win/notify_icon.h
- shell/browser/ui/win/notify_icon_host.cc
- shell/browser/ui/win/notify_icon_host.h
Add 'mouse-enter' and 'mouse-leave' Tray events for Windows.
Notes: Added 'mouse-enter' and 'mouse-leave' Tray events for Windows.
> feat: Add 'mouse-enter' and 'mouse-leave' Tray events for Windows.

- shell/browser/api/electron_api_web_contents.cc
- spec/api-web-contents-spec.ts
Closes https://github.com/electron/electron/issues/19847.
Refs http://crbug.com/347742.
Handles an issue where calling `loadURL` during some `webContents` url loading events could crash.
There are a few possible ways to handle this, as outlined in https://github.com/electron/electron/issues/19847#issuecomment-1297789018 - I decided to take the path of simply failing to load if we're currently in a non-reentrant loadURL function.
This crash was happening because it's not safe to start a new navigation or otherwise discard the current one while the call that started it is still on the stack. When this happens, we can see use-after-frees, which Chrome preemptively handles with CHECKs.
Notes: Fixed an issue where calling `loadURL` during some `webContents` url loading events could crash.
> fix: crash when calling non-reentrant function in `loadURL`

- spec/api-browser-window-spec.ts
It used to be the case that `BrowserWindow "transparent" option should not display a visible background` flaked much more frequently before we added a 1000ms timeout. We have timeouts in similar test that still flake ([see here](https://app.circleci.com/pipelines/github/electron/electron/75310/workflows/83c548f4-6514-4afc-af24-b792cfab0017/jobs/1617798/tests)) - I think we should make these consistent as we've seen that 1000ms is more reliably enough time to prevent snapshot races.
Notes: none
> test: make capturePage color matching timeouts consistent

- docs/breaking-changes.md
Deprecated since #23096, #24410, #39494
Warnings fixed in #40090
Notes: The `renderer-process-crashed` event on `app` and `crashed` event on `WebContents` and `<webview>` have been deprecated.
> chore: formally deprecate `crashed` and `renderer-process-crashed` events

- shell/browser/api/electron_api_web_contents.cc
- spec/api-browser-window-spec.ts
Closes https://github.com/electron/electron/issues/31992.
Refactors a previous choice made to return an empty image for occluded windows when using `webContents.capturePage` on Windows and Linux. This was done to address an issue where `GetRenderWidgetHostView::CopyFromSurface` didn't call its callback in some occlusion cases. The original issue occurred because when a given page is hidden, the compositor called the provided callback immediately without posting it to the main thread - the worker thread then deadlocked as it tried to acquire the lock guarding the `Promise` returned by `webContents.capturePage` held by the main thread. This second approach instead creates a `OnceCallback` that will run `OnCapturePageDone` via the `UIThreadTaskRunner`.
This is done in …
> fix: `webContents.capturePage()` for hidden windows on Windows/Linux

- .circleci/config/base.yml
- BUILD.gn
- appveyor-woa.yml
- appveyor.yml
- script/native-test-targets.json
- script/spec-runner.js
As in title. They're not currently tested in CI and we don't maintain or add to them.
Notes: none
> build: remove native specs

- docs/breaking-changes.md
Follow-up to #40089. Deprecated by #24367.
Notes: The `gpu-process-crashed` event on `app` has been deprecated.
> chore: formally deprecate `gpu-process-crashed` event

- README.md
Updates our list of support Linux distro versions to match [Chrome's browser system requirements](https://support.google.com/chrome/a/answer/7100626).
Notes: none
> docs: update supported Linux versions

- docs/tutorial/context-isolation.md
`renderer.d.ts` doesn't compile when the declaration name has the same root name as the TS file.
https://github.com/Microsoft/TypeScript/issues/7624#issuecomment-202501572
https://stackoverflow.com/questions/59728371/typescript-d-ts-file-not-recognized
Notes: none
> docs: rename `renderer.d.ts` in documentation

- docs/api/app.md
- docs/api/web-contents.md
- docs/api/web-frame.md
- spec/ts-smoke/electron/main.ts
Another instance of #38339. `electron/docs-parser` doesn't like double quotes, or the word 'either'.  See the [Artifact Comparison check output](https://github.com/electron/electron/pull/40180/checks?check_run_id=17622455127) for difference.
Notes: none
> docs: fix some string union typings

- shell/browser/api/electron_api_web_contents.cc
Refactors navigation events to use a getter property for accessing the RFH. This is consistent with other RFH properties which allow us to defer instantiating WebFrameMain instances.
I noticed we were creating WebFrameMain instances for every frame so I added some debugging code to confirm
```diff
WebFrameMain::WebFrameMain(content::RenderFrameHost* rfh)
: frame_tree_node_id_(rfh->GetFrameTreeNodeId()), render_frame_(rfh) {
GetWebFrameMainMap().emplace(frame_tree_node_id_, this);
+  if (!rfh->IsInPrimaryMainFrame()) {
+    LOG(ERROR) << base::debug::StackTrace();
+  }
}
```
Notes: none
> refactor: use getter property for RFH

- shell/browser/native_window.cc
- shell/browser/native_window.h
- shell/browser/native_window_mac.h
- shell/browser/native_window_mac.mm
Closes https://github.com/electron/electron/issues/39885.
Fixes an issue where webContents elements in the traffic light area couldn't be interacted with if a BrowserWindow with `titleBarOverlay` enabled was fullscreen. This was happening
1) Because we didn't notify WebContents when a given `BrowserWindow` entered or exited fullscreen that it should update WCO
2) We didn't account for a scenario where bounds could be `{ 0, 0 }` intentionally while the overlay was active.
This addresses that by making the return value of `GetWindowControlsOverlayRect` optional to distinguish intent. See [here](https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/ui/views/frame/browser_view.cc;l=2247-2256;drc=f5bdc89c7395ed24f1b8d196a3bdd6232d5bf771;bpv=1;bpt=1) for similar handling …
> fix: incorrect wco bounds in macOS fullscreen

- docs/api/app.md
- shell/browser/api/electron_api_app.cc
- shell/browser/browser.h
- shell/browser/browser_mac.mm
- shell/common/platform_util.h
- shell/common/platform_util_mac.mm
- spec/api-app-spec.ts
Closes https://github.com/electron/electron/issues/37560.
Refs https://github.com/electron/electron/issues/37228
Refs https://github.com/electron/governance/pull/533
This PR updated `app.setLoginItemSettings(settings)` and `app.getLoginItemSettings(settings)` on macOS 13 to use a single streamlined underlying API on both Mac App Store and regular macOS builds. This will remove several configuration and settings options, including `openAsHidden` in `app.setLoginItemSettings` and `wasOpenedAtLogin` and `wasOpenedAsHidden` in `app.getLoginItemSettings`.
This simplifies the underlying logic in accordance to the APIs apple has outlined for usage and improve parity between MAS and non-MAS builds. This will also allow developers to register app service objects, launch daemons, and login item …
> feat: update `app.{set|get}LoginItemSettings(settings)`

- lib/asar/fs-wrapper.ts
- spec/asar-spec.ts
Fixes #40211
Caused by node internal code that looks like this:
```js
const tryStatSync =
(path) => fs.statSync(path, { throwIfNoEntry: false }) ?? new fs.Stats();
```
Notes:
* Fixed loading nested ESM dependencies in `node_modules`
* Correctly support the `throwIfNoEntry` option in `fs.statSync`/`fs.lstatSync` in asar files
> fix: support the throwIfNoEntry option to statSync and lstatSync in asar files

- docs/tutorial/automated-testing.md
We recently have released a new major version of our Electron plugin that makes testing Electron apps even easier. This PR updates the description on Testing Electron apps with WebdriverIO:
- have user run through the config wizard which sets up all necessary dependencies for testing Electron apps
- adds code example on how a config should look like
- adds example tests how to retrieve data from the Electron API
- adds links to further resources on webdriver.io
Notes: none
> docs: Update docs on testing Electron apps with WebdriverIO

- shell/browser/hid/electron_hid_delegate.cc
- shell/browser/hid/electron_hid_delegate.h
- shell/browser/hid/hid_chooser_context.h
- shell/browser/hid/hid_chooser_controller.h
Refs CL:3764713
`ElectronHidDelegate` should maintain separate `ScopedObservations` for each BrowserContext instead of using the same observations for its observers.
See Impetus Bug: [1349514](https://bugs.chromium.org/p/chromium/issues/detail?id=1349514)
Notes: none
> refactor: partition HidDelegate observers by browser context

- docs/api/notification.md
- shell/browser/api/electron_api_notification.cc
- shell/browser/notifications/notification.cc
- shell/browser/notifications/notification.h
- shell/browser/notifications/win/windows_toast_notification.cc
- shell/browser/notifications/win/windows_toast_notification.h
Closes https://github.com/electron/electron/issues/40133
Inspiration [taken from upstream](https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/notifications/notification_platform_bridge_win.cc;l=447?q=IToastNotificationHistory&sq=package:chromium)
This PR closes a longstanding issue whereby Windows Toast notifications could only be dismissed and prevented from living in the Action Center until removed by the user if `.close` is called on them while the Notification is visible to the user. On an API level, When `ToastNotifier.Hide` is called, the `ToastNotification` is removed from the screen if it is currently visible, and it is _not_ sent to the Action Center. A `ToastNotification` is considered dismissed per underlying callbacks if it leaves the screen, and so our …
> fix: Windows Toast notification dismissal from Action Center

- docs/api/app.md
- docs/api/web-contents.md
- docs/api/webview-tag.md
- docs/breaking-changes.md
- lib/browser/api/app.ts
- lib/browser/api/web-contents.ts
- lib/browser/web-view-events.ts
- spec/api-app-spec.ts
- spec/api-web-contents-spec.ts
- spec/ts-smoke/electron/main.ts
Follow-up to #40089
Notes: The deprecated `renderer-process-crashed` event on `app` and `crashed` event on `WebContents` and `<webview>` have been removed.
> chore: remove deprecated `crashed` and `renderer-process-crashed` events

- filenames.gni
- shell/browser/extensions/api/extension_action/extension_action_api.cc
- shell/browser/extensions/api/extension_action/extension_action_api.h
- shell/browser/extensions/electron_extensions_browser_api_provider.cc
- shell/common/extensions/api/BUILD.gn
- shell/common/extensions/api/action.json
Refs https://github.com/electron/electron/issues/36545.
Refs https://github.com/electron/electron/issues/40142.
Implement scaffolding for unsupported `chrome.action` API surface. From [documentation](https://developer.chrome.com/docs/extensions/reference/action/):
> You can use the chrome.action API to control the toolbar button for your extension in Chrome's UI. The action icons are displayed in the browser toolbar, to the right of the omnibox (on left-to-right devices). After installation, by default, these appear in the extensions menu (the puzzle piece). Users can choose to pin your extension icon to the toolbar.
Electron has no comparable concept for the toolbar button or popup, and will never support this API. However, as of now, many extensions use it, and it throws disruptive …
> chore: implement no-op `chrome.action` extension APIs

- shell/renderer/api/electron_api_context_bridge.cc
- shell/renderer/api/electron_api_context_bridge.h
- shell/renderer/api/electron_api_web_frame.cc
- shell/renderer/renderer_client_base.cc
- spec/webview-spec.ts
Closes https://github.com/electron/electron/issues/39891
Corrects an issue where functions called over the `contextBridge` were not being called with the expected receiver (`this`), leading to errors like the following:
```
"Uncaught (in promise) Error: Illegal invocation: Function must be called on an object of type NativeImage"
```
Notes: Functions called over the `contextBridge` are now called with the expected receiver (`this`)
> fix: correctly track receiver for methods called via ctx bridge

- patches/config.json
- patches/dawn/.patches
- patches/dawn/cherry-pick-f666cceb92c2.patch
[tint][utils] Add support for large allocations
From the BumpAllocator.
Bug: chromium:1491912
Change-Id: I632fea8de1451358aa24f8a8d05c07d7f6823d7d
Reviewed-on: https://dawn-review.googlesource.com/c/dawn/+/155840
Kokoro: Ben Clayton <bclayton@google.com>
Reviewed-by: Antonio Maiorano <amaiorano@google.com>
Notes: Security: backported fix for chromium:1491912.
> chore: cherry-pick f666cceb92c2 from dawn

- shell/browser/hid/electron_hid_delegate.cc
- shell/browser/hid/hid_chooser_context.cc
- shell/browser/hid/hid_chooser_context.h
- shell/browser/hid/hid_chooser_controller.cc
- shell/browser/hid/hid_chooser_controller.h
Refs CL:3309164
> This CL allows devices containing a top-level collection with a usage
from the FIDO usage page to appear in the WebHID device chooser if
the requesting origin is allowed to access FIDO.
Refs CL:3595839
> This CL makes sure users can see why a HID device does not show up in the browser picker to help debugging. See https://stackoverflow.com/a/71922823/422957 for context
Refs CL:3809913
> There is a smaller window between BrowserContext and HidService
destruction timing in service worker condition, which creates an UAF
issue as the stored BrowserContext pointer can still be accessed by the
HidService. This is fixed by using weak pointer of
ServiceWorkerContextCore to access BrowserContext when it is valid.
Notes: none
> chore: Show FIDO devices in the chooser if allowed

- docs/api/utility-process.md
- spec/api-utility-process-spec.ts
Backport of #40281
Notes: none
> test: add spec for `child-process-gone` event for utility process

- docs/api/crash-reporter.md
- lib/browser/api/auto-updater/auto-updater-win.ts
- lib/browser/api/crash-reporter.ts
- lib/browser/api/message-channel.ts
- lib/browser/api/power-monitor.ts
- lib/browser/api/share-menu.ts
- lib/browser/api/utility-process.ts
- lib/browser/ipc-main-impl.ts
- lib/browser/message-port-main.ts
- lib/utility/parent-port.ts
- spec/api-autoupdater-darwin-spec.ts
- typings/internal-electron.d.ts
We are already doing it in some places such as
https://github.com/electron/electron/blob/beb0cbc6d02815f5d4c6ed3dcdff931a5d8ba0cf/lib/browser/api/net-client-request.ts#L299
Let's do it consistently everywhere
Notes: none
> fix: make sure classes in lib correctly implement Electron interfaces

- shell/browser/ui/file_dialog_mac.mm
Closes https://github.com/electron/electron/issues/40284
Refs [this roll](https://github.com/electron/electron/commit/c5b9f766f373f4d403a8af2f75e28ca2d901cc32#diff-69dd8c727cf22d632f5ed17d9f4024ecdf95e8e11a8da32cc614a21460685cb9)
See [here](https://developer.apple.com/documentation/appkit/nscontrol/1428885-target?language=objc) - turns out `target` is weak so we need to retain it elsewhere.
Notes: Fixed an error changing file format in `dialog.showOpenDialog` on macOS.
> fix: prevent `PopUpButtonHandler` premature dealloc

- patches/node/build_add_gn_build_files.patch
Refs https://github.com/electron/electron/pull/35999/files#r1018305596.
Finally addresses an old TODO to use a separate build target for conflicting filenames instead of renaming files in the source tree.
Done in preparation for Node.js v20 upgrade, which I'll look to start soon as it entered Active LTS on [`2023-10-24`](https://github.com/nodejs/release#release-schedule)
Notes: none
> build: don't rename files in `electron_node/deps/base64`

- shell/browser/api/electron_api_web_contents.cc
- shell/browser/api/electron_api_web_contents_mac.mm
- spec/chromium-spec.ts
- spec/fixtures/pages/modal.html
- spec/webview-spec.ts
Closes https://github.com/electron/electron/issues/40342.
Fixes an issue where `navigator.keyboard.lock()` did not work per [latest expected behavior](https://developer.chrome.com/blog/better-full-screen-mode) - pressing <kbd>Esc</kbd> exited fullscreen immediately despite a keyboard lock being present to capture the key. We added this behavior historically when we didn't use the `ExclusiveAccessManager` - it now handles fullscreen capture and exit when necessary.
This can be tested with https://fullscreen-keyboard-lock.glitch.me - now, pressing and holding escape correctly triggers [`RequiresPressAndHoldEscToExit()`](https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/ui/exclusive_access/keyboard_lock_controller.cc;drc=2d0a33ccdfa8ac1a9bdf1d86d3b9138f99484bdf;bpv=1;bpt …
> fix: `navigator.keyboard.lock()` fullscreen exit handling

- package.json
- yarn.lock
Upgrades docs-parser and typescript-definitions to add new 'electron/utility' namespace added in:
- https://github.com/electron/docs-parser/pull/95
- https://github.com/electron/typescript-definitions/pull/246
- https://github.com/electron/typescript-definitions/pull/247
Also removes obsolete remote interface: https://github.com/electron/typescript-definitions/pull/249
> build: update @electron/docs-parser and @electron/typescript-definitions

- docs/tutorial/installation.md
- npm/install.js
Resolves https://github.com/electron/electron/issues/31431
Notes: Added support for configuring `use_remote_checksums` via `.npmrc`.
> feat: configure use remote checksums via rc

- build/args/all.gn
Data collected from the linked issue,
1) Issue is isolated to Linux x64 users
2) Issue does not happen with builds that had enable_pkeys = false
3) Affected users run with renderer sandbox disabled which disables zygote in our case
4) Some users have reported crash does not happen with Chromium 118
5) I am unable to repro the issue on Ubuntu 22.04 vm with 4k page size, seems isolated to specific setups.
Given pkeys feature is only enabled on Linux x64 and is primarily used to implement thread isolated allocator whose consumer is v8 CFI which is currently disabled on this branch, I am inclined to disable the feature as there are no negative side effects. Also, given the issue is claimed to be addressed in Electron 27 and higher, this is an isolated fix which should make Electron 26 stable …
> fix: crash when thread isolated pool is enabled in the renderer process

- docs/breaking-changes.md
- lib/renderer/api/ipc-renderer.ts
- lib/renderer/ipc-renderer-internal.ts
- spec/fixtures/apps/libuv-hang/preload.js
- spec/fixtures/apps/libuv-hang/renderer.js
It's a security footgun that IpcRenderer (unlike everything else) can go over the context bridge by accident.  Let's just make it so it can't
> refactor: ensure IpcRenderer is not bridgable

- build/dump_syms.py
- build/npm-run.py
- build/profile_toolchain.py
- build/zip.py
- build/zip_libcxx.py
- script/add-debug-link.py
- script/copy-debug-symbols.py
- script/generate-config-gypi.py
- script/lib/config.py
- script/lib/git.py
- script/lib/native_tests.py
- script/lib/util.py
- script/native-tests.py
- script/patches-mtime-cache.py
- script/release/uploaders/upload-index-json.py
- script/release/uploaders/upload.py
- script/run-clang-format.py
- script/strip-binaries.py
- script/verify-chromedriver.py
- script/verify-ffmpeg.py
- script/verify-mksnapshot.py
- script/zip-symbols.py
These Python scripts have all been moved to running with Python 3, so let's drop the old Python 2 compatibility code.
Notes: none
> chore: remove py2 compatibility code

- docs/fiddles/ipc/pattern-3/preload.js
- docs/fiddles/ipc/pattern-3/renderer.js
- docs/tutorial/ipc.md
> docs: avoid leaking the `IpcRendererEvent` in `contextBridge` examples

- docs/api/session.md
Add `bypassCustomProtocolHandlers` to the documentation for `ses.fetch`'s `init` parameter as it already the case with `net.fetch`.
Notes: none
> docs: add `bypassCustomProtocolHandlers` to `ses.fetch`

- patches/chromium/.patches
- patches/chromium/cherry-pick-80106e31c7ea.patch
<details>
<summary>electron/security#422 - 80106e31c7ea from chromium</summary>
[M-118] usb: Validate isochronous transfer packet lengths
USBDevice.isochronousTransferIn and
USBDevice.isochronousTransferOut take a parameter containing
a list of packet lengths. This CL adds validation that the
total packet length does not exceed the maximum buffer size.
For isochronousTransferOut, it also checks that the total
length of all packets in bytes is equal to the size of the
data buffer.
Passing invalid packet lengths causes the promise to be
rejected with a DataError.
(cherry picked from commit bb36f739e7e0a3722beeb2744744195c22fd6143)
Bug: 1492381, 1492384
Change-Id: Id9ae16c7e6f1c417e0fc4f21d53e9de11560b2b7
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4944690 …
> chore: cherry-pick 1 changes from Release-0-M119

- docs/api/session.md
- shell/browser/api/electron_api_web_contents.cc
- shell/browser/api/electron_api_web_contents.h
- shell/browser/web_contents_permission_helper.cc
- shell/browser/web_contents_permission_helper.h
- shell/common/gin_converters/content_converter.cc
Similar APIs are routed through our permissions helper, and it breaks from our permissions expectations to have this API not be controllable through `ses.setPermissionRequestHandler(handler)`.
This change brings it in line with other APIs like the [`Pointer Lock API`](https://developer.mozilla.org/en-US/docs/Web/API/Pointer_Lock_API).
Notes: Added `keyboardLock` to `ses.setPermissionRequestHandler(handler)`.
> feat: `keyboard.lock()` should use permissions helper

- shell/browser/native_window_mac.mm
- spec/api-browser-window-spec.ts
This PR fixes https://github.com/electron/electron/issues/39914. On macOS Sonoma, a BrowserWindow of the `panel` type could no longer be focused without also making the app the foregrounded app.
This was likely caused by us incorrectly calling `[[NSApplication sharedApplication] activateIgnoringOtherApps:NO];` in those scenarios. However, having done some sleuthing, we've tried to not call that method in recent years and saw different focus bugs. With that in mind, this PR does two things:
1. Adds a test for focusing an inactive panel window
2. Ensures that we do not call `activateIgnoringOtherApps` for panel windows on macOS 14.0 or newer.
We've also verified this approach internally at Notion. Anyone needing a fix for this urgently can [use this native …
> fix: Do not activate app when calling focus on inactive panel window

- patches/chromium/.patches
- patches/chromium/crash_gpu_process_and_clear_shader_cache_when_skia_reports.patch
- patches/chromium/gpu_use_load_program_shader_shm_count_on_drdc_thread.patch
Backports https://github.com/electron/electron/pull/40450
The patch is different from the backport PR mainly because the atomic count `use_shader_cache_shm_count` was introduced in Chromium 118 as part of https://chromium-review.googlesource.com/c/chromium/src/+/4762849. There are no behavior changes between the count and the flag as you can see in the CL. I tried to keep the backport minimal by replicating the change from https://chromium-review.googlesource.com/c/chromium/src/+/4988290 using the atomic flag instead.
Notes: Fix rendering on Linux due to broken shader cache compilation with driver updates
> fix: broken shader cache due to compilation error

- docs/api/session.md
Closes https://github.com/electron/electron/issues/40457.
Fixes types for `hid-device-{added|removed|revoked}`.
Notes: none
> docs: fix `hid-device-{added|removed|revoked}` event types

- build/fuses/fuses.json5
- docs/api/protocol.md
- docs/tutorial/fuses.md
- docs/tutorial/security.md
- shell/app/electron_content_client.cc
- shell/browser/electron_browser_client.cc
- shell/renderer/renderer_client_base.cc
A long standing gap between Electron and "The Web" has been are special treatment of `file://` URLs.  This was handy during the early days but nowadays we have a good stable custom `protocol` API that should supercede the usage of a "privileged" `file://` protocol.
This PR does a few things in one go:
* Documents that folks should prefer custom protocols instead of using the `file://` protocol
* Fixes the protocol docs to securely serve files within a folder
* Adds a fuse that allows folks to opt in to the web standard behavior for the `file://` protocol
Notes: Added new [Electron Fuse](https://www.electronjs.org/docs/latest/tutorial/fuses) that opts the `file://` protocol into more secure and restrictive behaviour that matches Chromium
> feat: add new fuse to treat file: identically to browsers

- patches/chromium/allow_disabling_blink_scheduler_throttling_per_renderview.patch
- patches/chromium/build_only_use_the_mas_build_config_in_the_required_components.patch
- patches/chromium/expose_setuseragent_on_networkcontext.patch
- patches/chromium/network_service_allow_remote_certificate_verification_logic.patch
Slightly modify the patches so the `content_unittests` target can be built, which is very helpful when upstreaming patches to Chromium.
Notes: none
> build: fix building content_unittests

- shell/browser/extensions/api/BUILD.gn
- shell/common/extensions/api/BUILD.gn
- shell/common/extensions/api/_api_features.json
- shell/common/extensions/api/_manifest_features.json
- shell/common/extensions/api/action.json
- shell/common/extensions/api/browser_action.json
- spec/extensions-spec.ts
- spec/fixtures/extensions/chrome-action-fail/background.js
- spec/fixtures/extensions/chrome-action-fail/main.js
- spec/fixtures/extensions/chrome-action-fail/manifest.json
- spec/fixtures/extensions/chrome-action-fail/popup.html
Closes https://github.com/electron/electron/issues/36545
Fixes an issue with correct uncompiled source registration:
```
[12932:1013/112709.120:ERROR:extensions_browser_client.cc(69)] Extension Error:
OTR:     false
Level:   2
Source:
Message: Error handling response: TypeError: Cannot read properties of undefined (reading 'setIcon')
at setExtensionIconAndPopup (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/background.js:1:1614)
at checkAndHandleRestrictedPageIfSo (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/background.js:1:2090)
at Array.forEach (<anonymous>)
at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/background.js:1:2146
ID:      fmkadmapgofadopljbjfkapdkoienihi
Type:    RuntimeError
Context:
Stack Trace:
{
Line:     0
Column:   1
URL: …
```
> fix: `chrome.action` API registration

- .github/workflows/branch-created.yml
Automates the closing of the previous release project board after creating the new one so that they don't build up.
Also sets the `link-to-repository` input when creating the new release project board, since I forgot that previously.
Notes: none
> ci: close previous release project board after creating new one

- patches/chromium/.patches
- patches/chromium/cherry-pick-3df423a5b8de.patch
<details>
<summary>electron/security#424 - 3df423a5b8de from chromium</summary>
Check context status before recreating platform destination
Changing the channel count in the RealtimeAudioDestinationHandler will
trigger the recreation of the platform destination. This in turn can
activate the audio rendering thread.
This CL adds a check to prevent this from happening after the handler
is garbage collected.
(cherry picked from commit 4997f2ba263ff7e1dbc7987dd3665459be14dffe)
Bug: 1497859
Test: Locally confirmed with ASAN
Change-Id: I5d2649f3fd3639779ae40b0ca4ef2fe305653421
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4995928
Commit-Queue: Hongchan Choi <hongchan@chromium.org>
Reviewed-by: Michael Wilson <mjwilson@chromium.org> …
> chore: cherry-pick 1 changes from Release-1-M119

- shell/browser/electron_navigation_throttle.cc
- spec/api-browser-window-spec.ts
Navigating to links within `chrome:` pages—such as chrome://gpu—don't emit the "will-navigate" event. This is caused by navigations in pages with Web UI (e.g. `chrome:` pages) to [always be set as browser-initiated requests.](https://source.chromium.org/chromium/chromium/src/+/main:content/browser/renderer_host/navigator.cc;l=883-892;drc=0c8ffbe78dc0ef2047849e45cefb3f621043e956)
To fix this, we're overriding the browser-initiated flag for certain page transitions with navigations on Web UI pages. Pressing links is a [link page transition](https://source.chromium.org/chromium/chromium/src/+/main:content/browser/renderer_host/navigator.cc;l=860;drc=0c8ffbe78dc0ef2047849e45cefb3f621043e956) while calling `loadURL` uses [a different page transition …
> fix: emit will-navigate for links in chrome: pages

- patches/chromium/.patches
- patches/chromium/scale_rects_properly_in_syncgetfirstrectforrange.patch
Closes https://github.com/electron/electron/issues/40520.
Refs CL:4894366
Refs CRBUG:1486615
Fixes an issue where text replacement UI on macOS would be off-center:
Notes: Fixes an issue where text replacement UI on macOS could be off-center in some circumstances.
> fix: scale rects properly in `SyncGetFirstRectForRange`

- patches/node/.patches
- patches/node/fix_avx_detection.patch
Supersedes #40446
Notes: Backported fix for AVX related crashes on certain linux machines
> fix: add patch for simdutf base64 crash

- patches/chromium/.patches
- patches/chromium/cherry-pick-9384cddc7705.patch
<details>
<summary>electron/security#427 - 9384cddc7705 from chromium</summary>
[Merge to M118] Make URLSearchParams persistent to avoid UaF
The URLSearchParams::Create() function returns an on-heap object, but it
can be garbage collected, so making it a persistent variable in
DidFetchDataLoadedString() mitigates the issue.
(cherry picked from commit 8b1bd7726a1394e2fe287f6a882822d8ee9d4e96)
Bug: 1497997
Change-Id: I4ae0f93fccc561cd8a088d3fa0bf2968bf298acf
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4996929
Reviewed-by: Adam Rice <ricea@chromium.org>
Commit-Queue: Nidhi Jaju <nidhijaju@chromium.org>
Cr-Original-Commit-Position: refs/heads/main@{#1218682}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5007484
Commit-Queue: Adam Rice …
> chore: cherry-pick 1 changes from Release-2-M119

- docs/api/structures/display.md
- shell/common/gin_converters/gfx_converter.cc
- spec/api-screen-spec.ts
This PR adds missing `display` properties [upstream](https://source.chromium.org/chromium/chromium/src/+/main:ui/display/display.h;l=210;drc=7fa0c25da15ae39bbd2fd720832ec4df4fee705a;bpv=1;bpt=1?q=display::Display&sq=package:chromium&type=cs) as well as corresponding tests. Also alphabetizes the properties in docs.
Notes: This PR adds several properties to the `display` object including `detected`, `maximumCursorSize`, and `nativeOrigin`.
> feat: add/update missing Display properties

- shell/common/platform_util_linux.cc
According to https://edeproject.org/spec/file-uri-spec.txt , strings passed to `org.freedesktop.FileManager1.ShowItems` are regarded as _escaped file paths_:
> The specification for file: URIs, RFC2396[1] and RFC1738[2] says that
file URIs are of the form:
`file://<hostname>/<path>`
>
> Where the hostname and path parts can contain a limited subset of
ASCII characters, representing their ASCII values, and any other bytes
escaped by using a % followed by a two digit hex value. As a special
case the hostname part can be "localhost" or empty meaning the machine
the URI is being interpreted on.
Hence, we should escape the file path passed in before sending it to dbus.
This will fix https://github.com/microsoft/vscode/issues/198045 .
Notes: Fixed file paths passed to `shell.showItemInFolder` …
> fix: ShowItemUsingFileManager should escape path in Linux

- docs/tutorial/ipc.md
Description of Change
A very minor grammar fix update to wording in the IPC tutorial.
Checklist
Release Notes
Notes: none
> docs: wording in IPC tutorial docs

- .github/workflows/pull-request-labeled.yml
Trigger a Slack workflow when a PR is labeled with https://github.com/electron/electron/labels/backport%2Frequested%20%F0%9F%97%B3 to better automate Releases WG processes.
TODO:
Notes: none
> ci: trigger Slack workflow on backport requested

- shell/browser/native_window_views.cc
- shell/browser/native_window_views.h
- shell/browser/ui/win/electron_desktop_native_widget_aura.cc
- shell/browser/ui/win/electron_desktop_native_widget_aura.h
- spec/api-browser-window-spec.ts
Currently when we toggle setResizable function on maximized window then this window will change bounds and will not be equal to screen bounds.
This is happening because when we toggle setResizable then also HWNDMessageHandler::SizeConstraintsChanged() is called, where WS_THICKFRAME window style is removed.
Solution for this issue is to add WS_THICKFRAME for maximized window even if window is not resizable.
Notes: Fix problem with bounds of maximized window when  toggle BrowserWindow.setResizable function.
> fix: maximized window bounds when toggle setResizable

- shell/common/node_bindings.cc
Refs https://github.com/nodejs/node/pull/41424
We need to keep our handling in [`ErrorMessageListener`](https://github.com/electron/electron/blob/cf5f0419f11516937e43e8259204339dffa22aa4/shell/common/node_bindings.cc#L269-L295) in sync with that in Node.js' [`createOnGlobalUncaughtException()`](https://github.com/nodejs/node/blob/c39b7c240e3b0d31076a81bcdb2a2561a4310df1/lib/internal/process/execution.js#L145-L193).
Fixing incidental to https://github.com/electron/electron/issues/40573, but that is unfortunately a separate issue.
Notes: Fix a potential issue with `async_hook` corruption in some error contexts.
> fix: do not call `after()` `async_hook` for `asyncId` 0

- patches/chromium/fix_restore_original_resize_performance_on_macos.patch
Was missing in the OG PR
Notes: none
> chore: add patch upstream plan for resize patch

- shell/browser/native_window_mac.mm
This PR builds on top of https://github.com/electron/electron/pull/40307, which switched out the now-deprecated `activateIgnoringOtherApps` for the new `activate`. Thanks to https://github.com/electron/electron/pull/40307#issuecomment-1801976591, we now know that the new API doesn't quite behave exactly like the old one - so we'll use `activate` where `activateIgnoringOtherApps` is broken on macOS Sonoma — and in all other cases, continue to use `activateIgnoringOtherApps`. 
Notes: Use `activateIgnoringOtherApps` for focusing non-panels on macOS
> fix: Use activateIgnoringOtherApps for non-panels

- script/lint.js
Backport of #40571
Notes: none
> chore: allow passing more roots to lint.js

- patches/chromium/.patches
- patches/chromium/cherry-pick-3f45b1af5e41.patch
- patches/chromium/cherry-pick-6cc0d9aa5b3f.patch
- patches/chromium/cherry-pick-e13061c50998.patch
- patches/config.json
- patches/openscreen/.patches
- patches/openscreen/cherry-pick-971d6055e7b7.patch
- patches/skia/.patches
- patches/skia/avoid_combining_extremely_large_meshes.patch
<details>
<summary>electron/security#432 - 971d6055e7b7 from openscreen</summary>
[Cast Streaming] fix heap use-after-free
This patch fixes a use after free, caused by using an iterator
after it has been invalidated by a call to std::map::erase().
Bug: 1491210
Change-Id: I0c546eb6474af82f052b89e819a4886a004270f0
Reviewed-on: https://chromium-review.googlesource.com/c/openscreen/+/4981212
Reviewed-by: Mark Foltz <mfoltz@chromium.org>
Commit-Queue: Jordan Bayles <jophba@chromium.org>
Reviewed-by: Muyao Xu <muyaoxu@google.com>
</details>
<details>
<summary>electron/security#430 - 3f45b1af5e41 from chromium</summary>
Check context status before creating new platform destination
RealtimeAudioDestinationHandler::SetSinkDescriptor creates new
destination platofrm without validating context …
> chore: cherry-pick 5 changes from Release-3-M119

- script/release/notes/notes.js
This fixes the "some PRs are missing from the notes" issue I mentioned to @mlaurencin earlier today. Apparently, edited comments on GitHub can be stored with `\r\n\r\n` between paragraphs instead of `\n\n`, which broke the `PERSIST_LEAD` check in the notes generator.  Happily, the fix is easy: remove `\n\n` from the test.
I've also added a warning if we ever reach a PR that doesn't have a note _and_ doesn't have a no-note, so any future issues like this one won't fail silently.
CC @mlaurencin @VerteDinde 
Notes: none
> build: fix release notes script bug that omitted edited release-clerk comments

- shell/browser/native_window_mac.mm
- spec/api-browser-window-spec.ts
PR https://github.com/electron/electron/pull/40062 introduced a `bool wants_to_be_visible_` flag to `NativeWindowMac`, but it wasn't set in `NativeWindowMac::ShowInactive()`, only in `NativeWindowMac::Show()`. This meant that the parent-child relationship wouldn't be established for any window that was opened while the app wasn't the active one (typically this can occur in apps with always-visible floating overlay windows).
CC @codebytere 
Notes: fixed child window opening in non-active macOS apps
> fix: add missing `set_wants_to_be_visible(true)` to `NativeWindowMac::ShowInactive()`

- patches/chromium/.patches
- patches/chromium/cherry-pick-3f45b1af5e41.patch
- patches/chromium/cherry-pick-e13061c50998.patch
- patches/config.json
- patches/libavif/.patches
- patches/libavif/do_not_store_potentially_invalid_pointers.patch
- patches/libavif/remove_potential_out_of_bound_access_to_alphaitemindices.patch
- patches/openscreen/.patches
- patches/openscreen/cherry-pick-971d6055e7b7.patch
- patches/skia/.patches
- patches/skia/avoid_combining_extremely_large_meshes.patch
<details>
<summary>electron/security#432 - 971d6055e7b7 from openscreen</summary>
[Cast Streaming] fix heap use-after-free
This patch fixes a use after free, caused by using an iterator
after it has been invalidated by a call to std::map::erase().
Bug: 1491210
Change-Id: I0c546eb6474af82f052b89e819a4886a004270f0
Reviewed-on: https://chromium-review.googlesource.com/c/openscreen/+/4981212
Reviewed-by: Mark Foltz <mfoltz@chromium.org>
Commit-Queue: Jordan Bayles <jophba@chromium.org>
Reviewed-by: Muyao Xu <muyaoxu@google.com>
</details>
<details>
<summary>electron/security#430 - 3f45b1af5e41 from chromium</summary>
Check context status before creating new platform destination
RealtimeAudioDestinationHandler::SetSinkDescriptor creates new
destination platofrm without validating context …
> chore: cherry-pick 6 changes from Release-3-M119

- patches/chromium/.patches
- patches/chromium/cherry-pick-3f45b1af5e41.patch
- patches/chromium/cherry-pick-e13061c50998.patch
- patches/skia/.patches
- patches/skia/avoid_combining_extremely_large_meshes.patch
<details>
<summary>electron/security#430 - 3f45b1af5e41 from chromium</summary>
Check context status before creating new platform destination
RealtimeAudioDestinationHandler::SetSinkDescriptor creates new
destination platofrm without validating context status. This can
reactivate the audio rendering thread when AudioContext is already in
closed state.
(cherry picked from commit 0f9bb9a1083865d4e51059e588f27f729ab32753)
Bug: 1500856
Change-Id: If1fd531324b56fcdc38d315fd84d4cec577a14bc
Test: Locally confirmed with ASAN
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5021160
Reviewed-by: Alvin Ji <alvinji@chromium.org>
Commit-Queue: Alvin Ji <alvinji@chromium.org>
Reviewed-by: Hongchan Choi <hongchan@chromium.org>
Cr-Original-Commit-Position: refs/heads/main@{#1223168} …
> chore: cherry-pick 3 changes from Release-3-M119

- patches/config.json
- patches/libavif/.patches
- patches/libavif/do_not_store_potentially_invalid_pointers.patch
- patches/libavif/remove_potential_out_of_bound_access_to_alphaitemindices.patch
<details>
<summary>electron/security#429 - b2d36b1c3bfc from libavif</summary>
Remove potential out of bound access to alphaItemIndices
It is possible to craft a file that has more alpha auxiliary items
than color items and trigger an out of bound access into
alphaItemIndices in the for loop.
Fix is to ensure that each color grid item has exactly one alpha
grid item. Also, ensure that there are exactly the same number of
color grids as informed in the grid config before trying to
find the alpha item.
Also, update a diagnostic error message to cover all cases (i.e.)
there can be more grids than necessary as well.
Bug: 1501766, 1501770
Reviewed-on: https://chromium.googlesource.com/external/github.com/AOMediaCodec/libavif.git/+/6d62963f74aa76dbe05ac8c84bed94dece9ddde5
[118] Manual Backport: …
> chore: [25-x-y] cherry-pick 2 changes from Release-3-M119

- shell/browser/ui/inspectable_web_contents.cc
- spec/api-web-contents-spec.ts
Fixes #40660
Re-using the previous DevToolsFrontendHost instance no longer works, so we need to clean it up when devtools is closed.
Also updates `IsInMainFrame` to `IsInPrimaryMainFrame` to match upstream changes: https://chromium-review.googlesource.com/c/chromium/src/+/2957195
Notes: Fixed an issue where devtools could not be re-opened.
> fix: clean up devtools frontend_host on webcontents destroy

- shell/browser/web_contents_zoom_controller.cc
- spec/fixtures/pages/webview-zoom-change-persist-host.html
- spec/node-spec.ts
- spec/webview-spec.ts
Closes https://github.com/electron/electron/issues/40354
Fixes an issue where webview zoom reset on navigation after #39428. This brings behavior back in line with previously expected behavior. The webview zoom level should persist per-session for the same host even if navigations occur, as was the initial intention in https://github.com/electron/electron/pull/8537.
Confirmed to fix https://github.com/ferdium/ferdium-app/issues/1419 with a local build.
Notes: Fixed an issue where zoom level settings did not persist per-session for webviews.
> fix: webview zoom level persistence on navigation

- docs/tutorial/tutorial-2-first-app.md
This PR updates our tutorial to include ESM support in Electron 28
Notes: none
> docs: add E28 support for ESM in tutorial.md

- package.json
- yarn.lock
Updating typescript-definitions to 8.15.2.
* electron/typescript-definitions/pull/253
Notes: none
> build: update typescript-definitions to 8.15.2

- filenames.gni
- shell/app/node_main.cc
- shell/common/mac/codesign_util.cc
- shell/common/mac/codesign_util.h
- spec/api-autoupdater-darwin-spec.ts
- spec/fixtures/api/fork-with-node-options.js
- spec/lib/codesign-helpers.ts
- spec/node-spec.ts
See the code comment for the purpose of this change:
// On macOS, it is forbidden to run sandboxed app with custom arguments
// from another app, i.e. args are discarded in following call:
//   exec("Sandboxed.app", ["--custom-args-will-be-discarded"])
// However it is possible to bypass the restriction by abusing the node mode
// of Electron apps:
//   exec("Electron.app", {env: {ELECTRON_RUN_AS_NODE: "1",
//                               NODE_OPTIONS: "--require 'bad.js'"}})
// To prevent Electron apps from being used to work around macOS security
// restrictions, when NODE_OPTIONS is passed it will be checked whether
// this process is invoked by its own app.
Note that this change is only needed on macOS, because on other platforms there is no restriction on invoking another app with …
> fix: prevent node mode to be used as script runner by other apps

- .github/workflows/branch-created.yml
Unfortunately GitHub does not have a good permission model around projects and repos currently, and this linking would require giving the project automation GitHub app read and write "Contents" permission on `e/e` which isn't a good idea for such a small functionality, so disable it for now.
Notes: none
> ci: roll back the link release project board to repo automation

- patches/chromium/.patches
- patches/chromium/cherry-pick-5fde415e06f9.patch
<details>
<summary>electron/security#433 - 5fde415e06f9 from chromium</summary>
[BreakoutBox] Use KeepAlive to prevent lifetime race with audio delivery
(cherry picked from commit 186dad16ae69183f02730fb26d84e1d53f9f1b04)
Bug: 1497984
Change-Id: Ic22729b2ef9690203bbb09555d32238959e93a0f
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5009864
Reviewed-by: Michael Lippautz <mlippautz@chromium.org>
Commit-Queue: Guido Urdaneta <guidou@chromium.org>
Cr-Original-Commit-Position: refs/heads/main@{#1221614}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5018212
Cr-Commit-Position: refs/branch-heads/6099@{#500} …
> chore: cherry-pick 1 changes from Release-0-M120

- docs/tutorial/debugging-main-process.md
Wrong default port when debugging. See https://www.electronjs.org/docs/latest/api/command-line-switches#--inspecthostport
Notes: Fixed documentation of the default `--inspect` port.
> fix: wrong default port in docs

- docs/fiddles/menus/customize-menus/main.js
Fixes the `toggleDevTools` call in custom menu fiddle. 
It has been wrongly mapped to the `BrowserWindow` object instead of the `webContents` object. 
Notes: Fixed toggleDevTools() code example in documentation.
> fix: incorrectly mapped toggleDevTools in custom menu fiddle

- lib/browser/api/web-contents.ts
- spec/api-web-contents-spec.ts
Fixes this issue: https://github.com/electron/electron/issues/40640
The promise from `WebContents.loadURL()` rejects as soon as it receives `did-fail-load`. However, `did-fail-load` will be followed by a `did-finish-load`, which means that if the client code immediately issues another `loadURL()` when the promise rejects, this `loadURL()` will be resolved by the _previous_ call's `did-finish-load`.
This PR changes the `did-fail-load` handler to only note the failure, and leave it to `did-finish-load` to actually resolve/reject the promise.
Notes: Fixed `WebContents.loadURL()` incorrectly failing if called immediately after a previous call to `loadURL()` failed.
> fix: don't reject `loadURL()` promise from  `did-fail-load` - use `did-finish-load` instead

- patches/devtools_frontend/.patches
- patches/devtools_frontend/fix_active_trace_index_when_updating_models.patch
Refs https://github.com/microsoft/vscode/issues/200668
Notes: fix save to file option not working in performance tab of devtools
> fix: save to file option not working in performance tab of devtools

- appveyor.yml
Accidentally left this in when I merged
https://github.com/electron/electron/pull/35658.
Notes: none
> ci: re-comment pdb.zip download in appveyor.yml

- docs/tutorial/tutorial-3-preload.md
corrected the import path for ipcMain
Changed import path from electron to electron/main. Since ipcMain can only be imported from electron/main.
Notes:  none
> docs: corrected the ipcMain import path

- shell/common/gin_converters/content_converter.cc
I found this while working on nearby upgrades code but this doesn't belong in a roll, so I made it a standalone PR.
This is a small cleanup refactor in the spirit of #38886 and #38818 that uses a single constexpr lookup table for converting `ui::MenuSourceType` both to & from v8.
This is just a general cleanup PR so no particular stakeholders + review welcome from anyone, but CC @codebytere, @dsanders11, and @miniak who all did reviews on the previous PRs.
Notes: none
> refactor: use a FixedFlatMap for v8 converting ui::MenuSourceType

- patches/chromium/.patches
- patches/chromium/cherry-pick-8d607d3921b8.patch
<details>
<summary>electron/security#443 - 8d607d3921b8 from chromium</summary>
WebRtcAudioSink: Stop on invalid configuration
(cherry picked from commit 340b7e300d380460a039a07b90f62d1febae9da5)
Bug: 1513170
Change-Id: Ia4ca55e9eafb81789b28b8b8c54e615ac28df633
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5136295
Reviewed-by: Harald Alvestrand <hta@chromium.org>
Commit-Queue: Gustaf Ullberg <gustaf@chromium.org>
Cr-Original-Commit-Position: refs/heads/main@{#1239233}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5136708
Owners-Override: Krishna Govind <govind@chromium.org>
Commit-Queue: Krishna Govind <govind@chromium.org>
Reviewed-by: Krishna Govind <govind@chromium.org>
Cr-Commit-Position: refs/branch-heads/6099@{#1566} …
> chore: cherry-pick 1 changes from Release-2-M120

- patches/chromium/fix_activate_background_material_on_windows.patch
- shell/browser/ui/win/electron_desktop_window_tree_host_win.cc
Fixes #39959.
- Fixes a bug where Mica background won't work without the `transparent: true` setting
- Fixes a bug where a title bar is displayed on frameless windows
[A patch was added](https://github.com/electron/electron/pull/39708/) to fix Mica backgrounds on frameless windows, but it caused a side-effect in which a title bar gets displayed on frameless transparent windows.
This happens because, after the patch, `WM_NCACTIVATE` would be dispatched to `DefWindowProc` for frameless transparent windows. While this is necessary to make Mica work on these windows, it would cause an incorrect title bar to also be displayed.
To fix this, we are setting -1 as the lParam of `DefWindowProc`, which seems to prevent the non-client area from being displayed on window activation/deactivation:
> …
> fix: titlebar incorrectly displayed on frameless windows

- patches/chromium/.patches
- patches/chromium/cherry-pick-021598ea43c1.patch
- patches/chromium/cherry-pick-4ca62c7a8b88.patch
- patches/chromium/cherry-pick-76340163a820.patch
- patches/chromium/cherry-pick-998e947b265f.patch
- patches/chromium/cherry-pick-f15cfb9371c4.patch
- patches/config.json
- patches/libavif/.patches
- patches/libavif/do_not_store_colorproperties_until_alpha_item_is_found.patch
- patches/v8/.patches
- patches/v8/cherry-pick-cbd09b2ca928.patch
<details>
<summary>electron/security#442 - 998e947b265f from chromium</summary>
[FedCM] Check API permission before showing accounts UI
The accounts fetch could be delayed for legitimate reasons. A user may be
able to disable FedCM API (e.g. via settings or dismissing another FedCM
UI on the same RP origin) before the browser receives the accounts
response.
This patch checks the API permission before showing the accounts UI.
(cherry picked from commit 98676a2f66c4b4b802316eef70f4aab77e631f85)
Change-Id: Idbbe88912941113ec3f54d7f222845cd774dc897
Bug: 1500921
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5064052
Commit-Queue: Yi Gu <yigu@chromium.org>
Reviewed-by: Christian Biesinger <cbiesinger@chromium.org>
Cr-Original-Commit-Position: refs/heads/main@{#1229912} …
> chore: cherry-pick 7 changes from Release-1-M120

- build/fuses/build.py
- shell/browser/protocol_registry.cc
- spec/fixtures/apps/remote-control/main.js
- spec/fuses-spec.ts
This adds new testing infrastructure for fuses, and uses it to add a test for
the grant_file_protocol_extra_privileges fuse. Also, fix a bug with the
implementation of that fuse.
Notes: Fixed the `GrantFileProtocolExtraPrivileges` not correctly preventing `fetch()` calls to `file://` URLs.
> fix: make grant_file_protocol_extra_privileges fuse also block CORS fetches

- patches/node/build_add_gn_build_files.patch
Refs https://github.com/nodejs/node/pull/47339.
ICU is no longer requires to parse hostnames in Node.js' ada dependency and can be removed from our BUILD.gn patches.
Notes: none.
> chore: drop ada ICU requirement for parsing hostnames

- filenames.gni
- shell/app/node_main.cc
- shell/common/mac/codesign_util.cc
- shell/common/mac/codesign_util.h
- shell/common/node_util.h
- shell/common/node_util_mac.mm
- spec/fixtures/api/fork-with-node-options.js
- spec/node-spec.ts
This is a followup to https://github.com/electron/electron/pull/40579. 
@deepak1556 found that it is possible to work around the protection of `NODE_OPTIONS` by using another env `NODE_REPL_EXTERNAL_MODULE`, we think it is better just removing all envs start with `NODE_` in case there are new creative ways invented to work around the protection.
Note that `NODE_REPL_EXTERNAL_MODULE` only works in repl mode so only the `ELECTRON_RUN_AS_NODE` processes are affected.
Notes: Unset all Node envs in node process when parent is a foreign process.
> fix: ignore all NODE_ envs from foreign parent in node process

- docs/tutorial/electron-timelines.md
Follow up to #40622 - we caught a change in Chromium's schedule fairly late in the game, and updated the timeline doc after apps may have set their own schedules depending on the previous EOL date.
While we should always make sure this table is accurate, this PR adds a disclaimer to the timeline to clarify that the last 3 stable versions are supported, and how dates are determined.
Notes: none
> chore: add disclaimer to release timeline

- shell/browser/api/electron_api_web_contents.cc
This regressed with #35658. Chrome defaults this to white:
https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/exported/web_view_impl.cc;l=3301;drc=926dafb2e32d6676e53fde59efaff1aa4ea1dd61,
but we want transparent for &lt;webview> and BrowserView.
I'll leave it as white for WebContentsView as that matches more closely with
Chromium's behavior.
Notes: Fixed &lt;webview&gt; and BrowserViews being white instead of transparent by default.
> fix: BrowserView and <webview> should be transparent by default

- docs/api/accelerator.md
Closes https://github.com/electron/electron/issues/38673.
Explicitly state that accelerators are case insensitive
Notes:  none
> docs: note accelerator case insensitivity

- shell/browser/api/electron_api_app.h
- shell/browser/api/electron_api_desktop_capturer.cc
- shell/browser/api/electron_api_menu_views.cc
- shell/browser/api/electron_api_menu_views.h
- shell/browser/api/electron_api_power_save_blocker.h
- shell/browser/api/electron_api_system_preferences_mac.mm
- shell/browser/electron_browser_client.h
- shell/browser/net/proxying_url_loader_factory.h
- shell/browser/notifications/linux/libnotify_notification.cc
- shell/browser/ui/electron_menu_model.h
- shell/browser/ui/gtk/menu_util.cc
- shell/browser/ui/inspectable_web_contents.cc
- shell/browser/ui/inspectable_web_contents.h
- shell/browser/ui/message_box_gtk.cc
- shell/browser/ui/message_box_mac.mm
- shell/browser/ui/message_box_win.cc
- shell/browser/ui/views/electron_views_delegate.h
- shell/browser/ui/views/electron_views_delegate_win.cc
- shell/browser/web_view_manager.h
- shell/common/api/electron_api_native_image.h
- shell/renderer/electron_renderer_client.h
- shell/renderer/web_worker_observer.cc
- shell/renderer/web_worker_observer.h
`base::flat_map` and `base::flat_set` are STL-like map & set containers that are implemented using `std::vector` instead of an red-black tree, so they have good memory locality and lower overhead, especially for containers with smaller sizes. The upstream [usage advice](https://chromium.googlesource.com/chromium/src/+/HEAD/base/containers/README.md#Map-and-set-selection-Usage-advice) recommends:
>  Most maps and sets in Chrome are small and contain objects that can be moved efficiently. In this case, consider `base::flat_map` and `base::flat_set`.
>
> You need to be aware of the maximum expected size of the container since individual inserts and deletes are O(n), giving O(n^2) construction time for the entire map. But because it avoids mallocs in most cases, inserts are better or …
> perf: use flat_set, flat_map for small, trivially-moved containers

- shell/browser/native_window_mac.h
- shell/browser/native_window_mac.mm
- spec/api-browser-window-spec.ts
This PR fixes this bug: https://github.com/electron/electron/issues/39833
An [earlier PR](https://github.com/electron/electron/pull/39620/files#diff-148ef9a1a6f049d9fef8c6272a4871d89315f8fc6cd80dc2d41a28b21b29184cR848) (cc @codebytere) incorrectly disabled `NSWindowZoomButton` if the window was non-fullscreenable. However, if a macOS window is non-fullscreenable, the green zoom button turns into a maximize button (with a plus sign instead of the full-screen arrows), so it is still useful and shouldn't be disabled.
Here I'm enabling the button if the window is *fullscreenable OR (resizable AND maximizable)*. I'm also ensuring that this invariant holds whenever any of these 3 flags change (i.e. fullscreenable, resizable, maximizable).
Notes: Fixed the enabled/disabled behavior of the …
> fix: macOS maximize button shouldn't be disabled just because the window is non-fullscreenable

- patches/chromium/build_add_electron_tracing_category.patch
Modify `build_add_electron_tracing_category.patch` so that it doesn't inject a `DXVA_Decoding` category. Looks like it was added by accident as part of the #38465 Chromium roll in 60ca38fb.
CC @electron/wg-upgrades 
Notes: none
> chore: do not inject DXVA_Decoding trace category

- docs/breaking-changes.md
Closes https://github.com/electron/electron/issues/40799.
Adds missing breaking vibrancy change forced in https://github.com/electron/electron/pull/38891
Notes: none
> docs: add missing vibrancy breaking change

- shell/browser/browser_win.cc
- shell/browser/relauncher_win.cc
In a recent Chromium roll (#40045) we make some changes that were caused by this following revision: [Remove Windows-specific wstring variants of StringPrintf() etc.](https://chromium-review.googlesource.com/c/chromium/src/+/4776412).
While the changes we made appear to be correct, we're observing some unicode conversion errors in practice, where the strings we modified are ending up with U+FFFE (the "replacement character") in them, indicating a string encoding conversion issue.
I'm still digging into the specifics of what exactly is going wrong and verifying that this PR is indeed correct, but this PR brings us in line with the changes Chromium made to address these situations: using `base::StrCat` (and a few `base::NumberToWString`). (See: multiple revisions attached to [Chromium bug …
> fix: wide string concatenation

- shell/browser/electron_browser_main_parts.cc
- shell/browser/lib/power_observer_linux.cc
Closes https://github.com/electron/electron/issues/40694.
Refs https://github.com/electron/electron/pull/37937.
This PR fixes a crash resultant in trying to listen to power-related events before the `ready` event is emitted on Linux. This was happening because the `PowerObserverLinux` ctor called `bluez::BluezDBusThreadManager::Get()`, which assumed that `bluez::BluezDBusThreadManager::Initialize()` had already been called and `CHECK`ed if it hadn't been. However, our existing logic did not call `bluez::BluezDBusThreadManager::Initialize()` until `ElectronBrowserMainParts::PostCreateMainMessageLoop()`, which meant that trying to use:
```js
powerMonitor.on('suspend', () => {
console.log('suspend')
});
powerMonitor.on('resume', () => {
console.log('resume')
});
```
before the `ready` event …
> fix: crash using `powerMonitor` before ready event

- .circleci/config/base.yml
Uses images generated by https://github.com/electron/build-images/pull/32 that run on arm64 hosts in our kubernetes infra to run our arm64/32 tests.  This dramatically speeds up our linux CI.
This PR also fixes the circleci test splitting command to, well, actually work.  So tests are more consistent in their duration as well now.
> build: use container runner for arm tests

- .circleci/config/base.yml
- spec/api-content-tracing-spec.ts
The code comment above indicates 50kb should be the limit, I ran some historical CI and it looks like we were around ~9.8 before and now we're barely over 10.  Instead of being on the edge let's just move the boundary to where it doesn't flake but still would fail when appropriate
Notes: none
> chore: fix content tracing flake

- shell/browser/javascript_environment.cc
- shell/browser/window_list.cc
- shell/browser/window_list.h
First in a pair of PRs to stop using the deprecated class `base::LazyInstance`. [Its header file instructs callers to use `base::NoDestructor` instead](https://chromium.googlesource.com/chromium/src/+/refs/heads/main/base/lazy_instance.h#5), so that's what this PR does.
Notes: none
> refactor: migrate deprecated LazyInstance code to NoDestructor

- shell/browser/mac/in_app_purchase.mm
- shell/browser/mac/in_app_purchase_product.mm
- spec/api-in-app-purchase-spec.ts
Closes https://github.com/electron/electron/issues/40851.
Refs https://github.com/electron/electron/pull/39304/commits/e6bbc74e485e3b76100aa6c46b59f6ead7ce4131.
When we migrated to ARC both the `InAppPurchase` and `InAppPurchaseProduct` objects became automatically managed. They were being created in static methods, and so went out of scope at the end of `in_app_purchase::PurchaseProduct` and `in_app_purchase::GetProducts` respectively where they were then immediately deallocated without their associated callbacks ever being called. These classes should be refactored more largely but for now maintaining a strong reference to themselves until they're no longer needed should address the immediate issue.
This was missed because our IAP tests were disabled - they seem to work again so i've …
> fix: InAppPurchase pre-emptive deallocation

- .circleci/config/base.yml
#40953 removed the git cache from the gclient sync step, which may be causing release builds to timeout. Rather than adding it back it, let's increase the gclient sync step output timeout limit to allow a new cache (minus git cache) to be built. Then we can compare the total build numbers and see what the differences are.
Notes: none
> ci: increase "gclient sync" output timeout

- .circleci/config/base.yml
Release builds began failing after the removal of the git cache in #40953, stalling out in the gclient sync step. Let's try re-adding it and see if it affects the sync time.
Notes: none
> ci: revert CI git cache removal

- patches/v8/.patches
- patches/v8/cherry-pick-389ea9be7d68.patch
[runtime] Drop fast last-property deletion
This interacts badly with other optimizations and isn't particularly
common.
Bug: chromium:1517354
Change-Id: I7adb51a8fc0ec47eaeb911ca2a4cbc517088e416
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/5185340
Commit-Queue: Leszek Swirski <leszeks@chromium.org>
Auto-Submit: Toon Verwaest <verwaest@chromium.org>
Commit-Queue: Toon Verwaest <verwaest@chromium.org>
Cr-Commit-Position: refs/heads/main@{#91782}
Notes: Security: backported fix for chromium:1517354.
> chore: cherry-pick 389ea9be7d68 from v8

- script/prepare-appveyor.js
- script/release/ci-release-build.js
- script/release/get-url-hash.js
`got` error response bodies are optional and not logged by default. When we trigger CI builds, we want to see them if they fail. This fixes that.
Locally, using a bad token:
```console
electron on git:main ❯ node script/release/ci-release-build.js main                         9:47PM
Triggering AppVeyor to run build job: electron-x64 on branch: main with release flag.
Triggering AppVeyor to run build job: electron-ia32 on branch: main with release flag.
Triggering AppVeyor to run build job: electron-woa on branch: main with release flag.
3 jobs were requested.
Could not call AppVeyor:  { statusCode: 401, body: { message: 'Authorization required' } }
Could not call AppVeyor:  { statusCode: 401, body: { message: 'Authorization required' } }
Could not call AppVeyor:  { statusCode: 401, body: …
```
> build: log got error response bodies

- patches/chromium/feat_add_support_for_overriding_the_base_spellchecker_download_url.patch
- shell/browser/electron_browser_client.cc
- shell/browser/extensions/api/extension_action/extension_action_api.cc
- shell/browser/extensions/electron_extension_host_delegate.cc
- shell/common/asar/asar_util.cc
- shell/common/extensions/electron_extensions_client.cc
Second of a pair of PRs to stop using the deprecated class `base::LazyInstance`.  Its documentation says to use `base::NoDestructor` instead, so that's what this PR does.
Any reviews welcomed. CC @codebytere and @miniak, who reviewed the previous #40927.
Notes: none
> refactor: use base::NoDestructor instead of base::LazyInstance

- shell/browser/serial/serial_chooser_context.cc
- shell/browser/ui/inspectable_web_contents.cc
`Base64Encode(StringPiece input, std::string* output)` was deprecated in https://chromium-review.googlesource.com/c/chromium/src/+/4886030. This PR updates our use of that function to use its replacment instead.
Notes: none
> refactor: fix deprecated base::Base64Encode() API calls

- .circleci/config/base.yml
- appveyor-woa.yml
- appveyor.yml
Ref https://github.com/electron/rbe-credential-helper/pull/7
Ref https://github.com/electron/build-tools/pull/542
Notes: none.
> ci: correctly export RBE_experimental_credentials_helper_args

- patches/chromium/fix_return_v8_value_from_localframe_requestexecutescript.patch
Helpful when upstreaming patches that requires [web tests](https://chromium.googlesource.com/chromium/src/+/HEAD/docs/testing/web_tests.md)
Notes: none
> chore: fix building blink_tests target

- patches/node/chore_expose_importmoduledynamically_and.patch
- patches/node/fix_missing_include_for_node_extern.patch
- shell/common/node_bindings.cc
- spec/esm-spec.ts
- spec/fixtures/esm/import-meta/index.html
- spec/fixtures/esm/import-meta/main.mjs
- spec/fixtures/esm/import-meta/package.json
- spec/fixtures/esm/import-meta/preload.mjs
Closes https://github.com/electron/electron/issues/40989.
Fixes an issue where `import.meta.url` did not work in the renderer process with `contextIsolation` disabled and DCHECKed in local builds. This was happening because we blend the Blink and Node.js handlers for `HostInitializeImportMetaObjectCallback`, and we previously fell back to Blink in the situation where `contextIsolation` was disabled in the renderer process. This adds a check for whether the module was created by Node.js specifically - if that's the case it now uses the Node.js handler. Otherwise, it continues to fall back to Blink's handler.
Tested with https://gist.github.com/f9cde94e621204933822255591f11011.
Notes: Fixes an issue where `import.meta.url` did not work in the renderer process with `contextIsolation` …
> fix: check for Node.js-created module when `contextIsolation` disabled

- patches/chromium/.patches
- patches/chromium/cherry-pick-c1cda70a433a.patch
- patches/v8/.patches
- patches/v8/cherry-pick-46cb67e3b296.patch
- patches/v8/cherry-pick-78dd4b31847a.patch
<details>
<summary>electron/security#451 - 46cb67e3b296 from v8</summary>
[codegen] Install BytecodeArray last in SharedFunctionInfo
Maglev assumes that when a SharedFunctionInfo has a BytecodeArray,
then it should also have FeedbackMetadata. However, this may not
hold with concurrent compilation when the SharedFunctionInfo is
re-compiled after being flushed. Here the BytecodeArray was installed
on the SFI before the FeedbackMetadata and a concurrent thread could
observe the BytecodeArray but not the FeedbackMetadata.
Drive-by: Reset the age field before setting the BytecodeArray as
well. This ensures that the concurrent marker will not observe the
old age for the new BytecodeArray.
Bug: chromium:1507412
Change-Id: I8855ed7ecc50c4a47d2c89043d62ac053858bc75
Reviewed-on: …
> chore: cherry-pick 3 changes from Release-5-M120

- shell/browser/extensions/electron_extension_loader.cc
- shell/browser/notifications/win/notification_presenter_win.cc
In the base::Time* classes, `ToInternalValue()` is deprecated / not to be used in new code.  This PR updates the two cases where Electron was using that API.
Xref: https://bugs.chromium.org/p/chromium/issues/detail?id=634507
Notes: none.
> refactor: remove deprecated ToInternalValue()

- shell/browser/native_window_mac.mm
Closes https://github.com/electron/electron/issues/41023.
[The previous maximize button fix](https://github.com/electron/electron/pull/40705/files) had a [bug](https://github.com/electron/electron/pull/40705#issuecomment-1888106669) where the green button was disabled if the window got maximized. I incorrectly assumed that `SetResizable()` and `IsResizable()` were symmetric, but alas they're not:
```
bool NativeWindowMac::IsResizable() const {
bool in_fs_transition =
fullscreen_transition_state() != FullScreenTransitionState::kNone;
bool has_rs_mask = HasStyleMask(NSWindowStyleMaskResizable);
return has_rs_mask && !IsFullscreen() && !in_fs_transition;
}
```
The fix is to replace `IsResizable()` with `HasStyleMask(NSWindowStyleMaskResizable)` in `UpdateZoomButton()`.
Notes: fix macOS bug …
> fix: use `HasStyleMask(NSWindowStyleMaskResizable)` instead of `IsResizable()` for enabling/disabling window maximize button

- shell/browser/native_window_mac.mm
Closes https://github.com/electron/electron/issues/40800.
Fixes an issue where non-modal windows with vibrancy could have incorrectly rounded corners on Sonoma. This happened as a result of the following logic:
```c+
bool should_round_modal =
!no_rounded_corner && (macos_version >= 11 ? true : !is_modal());
```
Which would incorrectly be `true` in this case.
Tested with https://gist.github.com/977c2ba87b683011bf1e093f6dd06d2f
Notes: Fixes an issue where non-modal windows with vibrancy could have incorrectly rounded corners on Sonoma.
> fix: modal rounding on nonmodal windows

- shell/browser/ui/message_box_mac.mm
- spec/api-dialog-spec.ts
Closes https://github.com/electron/electron/issues/40676.
Fixes a potential crash when calling `dialog.showMessageBoxSync`, setting a `defaultId`, and not passing a `buttons` array. This was happening because `objectAtIndex` was being called on an empty array which causes an `NSRangeException`.
Notes: Fixes a potential crash when calling `dialog.showMessageBoxSync`.
> fix: crash when `dialog.showMessageBoxSync` with missing buttons

- spec/lib/window-helpers.ts
- It appears that after #40871 was merged, Linux starting flaking in tests using the `closeWindow` helper.  I added a setTimeout so that we wait until the next tick to verify that windows have been closed and that appears to have resolved the issue.
Notes: none
> test: fixup assertNotWindows

- .github/workflows/stale.yml
Some issues, such as https://github.com/electron/electron/issues/39075, do not fall under any previous labels we have had to exempt an issue from stale automation. After adding this label, the labeler would also then have to follow up in a comment explaining why they are marking the issue as `stale-exempt`. (e.g. In this case, since no maintainers currently have access to a Citrix environment)
Notes: None
> ci: add stale-exempt label to exempt issues from automation

- docs/tutorial/automated-testing.md
This PR refreshes the Playwright automated-testing guide for 2024. Relevant comments are attached on the files tab.
cc @codebytere
Notes: none
> docs: update Playwright automated-testing guide

- shell/browser/api/electron_api_service_worker_context.cc
- shell/browser/api/electron_api_session.cc
- shell/browser/browser_mac.mm
- shell/browser/electron_browser_context.cc
- shell/browser/hid/hid_chooser_context.cc
- shell/browser/notifications/win/windows_toast_notification.cc
- shell/browser/ui/accelerator_util.cc
- shell/browser/ui/inspectable_web_contents.cc
- shell/browser/ui/webui/accessibility_ui.cc
- shell/browser/ui/win/notify_icon.cc
- shell/browser/usb/usb_chooser_context.cc
- shell/browser/web_contents_preferences.cc
- shell/common/api/electron_api_url_loader.cc
- shell/common/asar/archive.cc
- shell/common/crash_keys.cc
- shell/common/keyboard_util.cc
- shell/renderer/api/electron_api_context_bridge.cc
- shell/renderer/electron_render_frame_observer.cc
`std::to_string()` is [banned](https://chromium.googlesource.com/chromium/src/+/main/styleguide/c++/c++-features.md#std_sto_i_l_ul_ll_ull_f_d_ld_to_string_banned), so use `base::NumberToString()` instead.
Any reviewers welcome.
Notes: None
> refactor: remove banned std::to_string() calls

- lib/browser/api/auto-updater/squirrel-update-win.ts
For squirrel update in case of errors during the update the `exit` event listener may not be called resulting on `spawnedProcess` remains defined in memory preventing further updates checks to run with success.
Notes: none
> fix: on error, reset spawnedProcess

- shell/browser/osr/osr_render_widget_host_view.cc
- shell/browser/osr/osr_render_widget_host_view.h
`delegated_frame_host_` holds a pointer to `delegated_frame_host_client_`. Since `delegated_frame_host_client_` was being destroyed first, that pointer was dangling in the OSRWHV destructor.
Also, make these two unique_ptr fields `const` since they point to the same objects for the lifespan of the OSRWHV.
Notes: none
> fix: dangling raw_ptr in OSRWHV destructor

- patches/chromium/.patches
- patches/chromium/cherry-pick-cc07a95bc309.patch
- patches/chromium/safely_crash_on_dangling_profile.patch
<details>
<summary>electron/security#453 - cc07a95bc309 from chromium</summary>
Update rendering state of automatic pull nodes before graph rendering
In rare cases, the rendering fan out count of automatic pull node
does not match the main thread fan out count after recreating
a platform destination followed by disconnection.
This CL forces the update of the rendering state of automatic
pull nodes before graph rendering to make sure that fan out counts
are synchronized before executing the audio processing function call.
NOTE: This change makes 2 WPTs fail. The follow-up work is planned
to address them once this patch is merged.
(cherry picked from commit f4bffa09b46c21147431179e1e6dd2b27bc35fbc)
Bug: 1505080
Test: Locally confirmed that ASAN doesn't crash on all repro cases.
Change-Id: …
> chore: cherry-pick 2 changes from Release-0-M121

- appveyor-woa.yml
- appveyor.yml
- build/args/all.gn
28.0.0 windows builds shipped with two new dlls: `dxcompiler.dll` and `dxil.dll`.  Those DLLs were added for experimental usage of https://github.com/microsoft/DirectXShaderCompiler in Chromium's WebGPU support.  Since they are [experimental](https://bugs.chromium.org/p/chromium/issues/detail?id=1474897) for now, we can remove them.   
Additionally, this PR fixes our check for new files in zip files on Windows.  Now when a new addition to the zip file is detected the build will fail on Windows (like it already does on macOS and Linux).
Notes: Removed extraneous dlls from Windows zip files.
> build: remove unneeded dlls in Windows zip

- shell/browser/api/electron_api_auto_updater.cc
- shell/common/gin_helper/event_emitter_caller.cc
- shell/renderer/electron_api_service_impl.cc
- spec/api-browser-window-spec.ts
Closes https://github.com/electron/electron/issues/40573.
Fixes an issue where an async_hooks crash could occur on Windows only if the user is listening to the `restore` event after minimizing a maximized window and an error occurs in the `restore` callback. This was happening after https://github.com/electron/electron/commit/6b97beb4897b47c1bad698c45bc01fbdae162ceb, which created the first instance in our entire codebase where two `Emit` calls were called sequentially. As a result, given they were in the same callbackscope, when `node::RunTimers` ran and an error was occurring in the previous handler, async_hooks would blow up.
This fixes that error by putting the first `Emit` in its own `CallbackScope`.
Notes: Fixed a potential `async_hooks` crash when listening for the `restore` event …
> fix: potential `async_hooks` crash in `NotifyWindowRestore` on Windows

- patches/chromium/fix_on-screen-keyboard_hides_on_input_blur_in_webview.patch
This is a follow up to https://github.com/electron/electron/pull/35921 that, it fixes more corner cases that on-screen-keyboard does not hide for webviews.
This change has been applied in Teams for quite a while and should be reliable enough to introduce to Electron.
Notes: Fix on-screen-keyboard not hiding for webviews under some cases.
> fix: update osk patch to fix more corner cases

- patches/chromium/fix_on-screen-keyboard_hides_on_input_blur_in_webview.patch
The patch in #41131 became outdated after merge, which breaks CI build on main branch.
Notes: none
> chore: fix outdated osk patch on main branch

- shell/browser/api/electron_api_notification.cc
- shell/browser/api/electron_api_notification.h
- shell/browser/electron_browser_context.cc
- shell/browser/electron_browser_context.h
- shell/browser/extensions/api/tabs/tabs_api.cc
- shell/browser/native_window_views.cc
- shell/browser/net/network_context_service.cc
- shell/browser/osr/osr_render_widget_host_view.cc
- shell/browser/osr/osr_render_widget_host_view.h
- shell/browser/osr/osr_video_consumer.cc
- shell/browser/osr/osr_view_proxy.cc
- shell/browser/osr/osr_view_proxy.h
- shell/browser/osr/osr_web_contents_view.cc
- shell/browser/ui/views/root_view.cc
- shell/browser/ui/views/root_view.h
- shell/browser/web_contents_zoom_controller.cc
- shell/browser/web_contents_zoom_controller.h
Follow the [Chromium C++ style guide](https://chromium.googlesource.com/chromium/src/+/main/styleguide/c++/c++.md) advice on [inline functions](https://chromium.googlesource.com/chromium/src/+/main/styleguide/c++/c++.md#inline-functions):
> Simple accessors should generally be the only inline functions. These should be named using `snake_case()`. Virtual functions should never be declared this way.
This PR inlines some nonvirtual simple getters and uses `snake_case()` to denote that they are simple getters.
Notes: none
> refactor: inline simple getters

- shell/browser/api/electron_api_web_contents_view.cc
Closes https://github.com/electron/electron/issues/41142
Fixes an issue with potential crashes while closing or interacting with a WebContentsView after its associated WebContents has been cleaned up. We first need to ensure that `api_web_contents_` is not nullptr, as is done [several](https://github.com/electron/electron/blob/69a7f75a1a6c43908e4a5a81a841c926bc20a993/shell/browser/api/electron_api_web_contents_view.cc#L71) other [places](https://github.com/electron/electron/blob/69a7f75a1a6c43908e4a5a81a841c926bc20a993/shell/browser/api/electron_api_web_contents_view.cc#L63) in the same file.
Notes: Fixed a potential crash while closing or interacting with a WebContentsView after its associated WebContents has been cleaned up.
> fix: ensure `WebContents` before checking draggable region

- shell/browser/api/electron_api_web_contents.cc
Closes https://github.com/electron/electron/issues/41136.
Refs https://github.com/electron/electron/pull/40257.
Fixes an issue where the `printBackground` option in `webContents.printToPDF` did not work as expected. The name was changed from `shouldPrintBackgrounds` to `printBackground` at the JS layer and not in the corresponding location in C++. This fixes that.
Tested with https://gist.github.com/drivron/1e1be91efbbbbc61e4a528d0e362be9f
Notes: Fixed an issue where the `printBackground` option in `webContents.printToPDF` did not work as expected.
> fix: `shouldPrintBackgrounds` -> `printBackground` in `webContents.printToPDF`

- shell/browser/api/electron_api_web_request.cc
- shell/browser/api/gpu_info_enumerator.cc
Use  [`base::Value::EnsureList()`](https://chromium.googlesource.com/chromium/src/+/HEAD/base/values.h#391)  where appropriate to simplify our code. In particular, the new version of `GPUInfoEnumerator::EndGPUDevice()` is easier to read IMO.
Notes: none.
> refactor: simplify code by using base::Value::EnsureList()

- shell/browser/ui/inspectable_web_contents.cc
Two small cleanups I came across while reading iwc.cc on an unrelated topic:
- fix: In `DictionaryToRect()`, replace `base::Value::GetInt()` calls with `base::Value::FindInt()` to avoid potential `CHECK()` failures. (We were calling GetInt() without confirming that the Value was an int)
- refactor: In `IsPointInScreen()`, use [`gfx::Rect::Contains()`](https://chromium.googlesource.com/chromium/src/+/main/ui/gfx/geometry/rect.cc#147) instead of reinventing the wheel. 
Notes: none.
> fix: avoid potential `CHECK()` failure in `DictionaryToRect()`

- spec/api-browser-window-spec.ts
- spec/lib/screen-helpers.ts
- spec/package.json
- spec/yarn.lock
Added a test to move a window around using draggable regions. This is in response to a recent regression following a Chromium upgrade which was not caught.
[Nutjs](https://nutjs.dev/) is used to automate mouse dragging. This seems like a worthy dependency to try out since I know we've had issues with robotjs in the past.
Here's the test in action:
https://github.com/electron/electron/assets/1656324/b7200448-b96e-4ce8-91c9-9ba5f5393296
As an aside, I found that using Mac Stage Manager causes windows with position `x=0` to be offset from the left side of the screen (as seen in the video).
Notes: none
> test: draggable region allows moving window

- lib/browser/api/web-contents.ts
- spec/api-web-contents-spec.ts
Closes https://github.com/electron/electron/issues/41064.
Fixes an issue where `webContents.printToPDF` could fail when certain combinations of `margins` and `pageSize` values are passed. Previously, the call would fail with a somewhat misleading `Content area is empty.` error. This happened because `print_to_pdf::GetPrintPagesParams()` calls `printing::RenderParamsFromPrintSettings`, which validates that the requested margins are less than or equal to the physical page size. If they exceed the physical page size, Chromium clamps them down to 0, which leads to the content area being empty. To address this, I've chosen to validate `margins` against `pageSize` and throw a more descriptive error.
Notes: Fixes an issue where `webContents.printToPDF` could fail when certain combinations of …
> fix: validate `printToPDF` `margins` against `pageSize`

- shell/browser/usb/usb_chooser_controller.cc
Closes https://github.com/electron/electron/issues/39279.
Fixes an issue where `select-usb-device` did not respect the `filter` option in `navigator.usb.requestDevice()`. This is respected in Chromium using [this logic](https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/usb/usb_chooser_controller.cc;l=245-253) which was missing in our own. To fix this, remove filtered items from the vector prior to creating the `v8::Object` to emit in the event.
Notes: Fixed an issue where `select-usb-device` did not respect the `filter` option in `navigator.usb.requestDevice()`.
> fix: `select-usb-device` should respect `filters` option

- spec/package.json
[Linux ARM tests are failing](https://app.circleci.com/pipelines/github/electron/electron/78108/workflows/d2287dc3-20f7-4ad3-88dd-4a1bc2b34af0/jobs/1665959?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary) following the [addition of draggable region tests](https://github.com/electron/electron/pull/41127):
```
error @nut-tree/nut-js@3.1.2: The CPU architecture "arm" is incompatible with this module.
error Found incompatible module
```
This dependency isn't used on Linux so moving to optional dependencies _should_ fix the build.
Notes: none
> fix: move nut-js to optional spec deps

- spec/api-browser-window-spec.ts
One more try for fixing https://github.com/electron/electron/pull/41199 🤞 
```
electron/spec/api-browser-window-spec.ts(6610,108): error TS2307: Cannot find module '@nut-tree/nut-js' or its corresponding type declarations.
```
Addresses [failure in linux-arm-testing-tests](https://app.circleci.com/pipelines/github/electron/electron/78153/workflows/ccb3fa14-053f-4683-a1ac-0740c2dee134/jobs/1666690?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary) by ignoring `@nut-tree/nut-js` type imports on platforms which don't install the optional dependecy.
Notes: none
> fix: typescript error for optional dependency

- patches/chromium/.patches
- patches/chromium/cherry-pick-e7ffe20ebfac.patch
[A11y] Ensure old children of objects that become leaves are cleared
Fixed: 1520335
Change-Id: I9cd2fa6bfbb59d43318b7b378e4267c53e139f97
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5238389
Commit-Queue: Chris Harrelson <chrishtr@chromium.org>
Auto-Submit: Aaron Leventhal <aleventhal@chromium.org>
Reviewed-by: Chris Harrelson <chrishtr@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1252998}
Notes: none
> chore: cherry-pick e7ffe20ebfac from chromium

- patches/chromium/.patches
- patches/chromium/cherry-pick-1f8bec968902.patch
- patches/chromium/cherry-pick-4a98f9e304be.patch
- patches/chromium/cherry-pick-8755f76bec32.patch
- patches/chromium/cherry-pick-91a02d67a83d.patch
<details>
<summary>electron/security#460 - d4a197e4913f from chromium</summary>
Fix use-after-free in DrawTextInternal
DrawTextInternal was calling GetOrCreatePaintCanvas multiple times,
once at the start of the function, once inside of the
BaseRenderingContext2DAutoRestoreSkCanvas helper class and once in the
Draw call. GetOrCreatePaintCanvas destroys the canvas resource provider
if the GPU context is lost. If this happens on the second call to
GetOrCreatePaintCanvas, destroying the resource provider will
invalidate the cc::PaintCanvas returned by the first call to
GetOrCreatePaintCanvas.
The GPU process can technically crash at any point during the renderer
process execution (perhaps because of something another renderer
process did). We therefore have to assume that any call to …
> chore: cherry-pick 4 changes from Release-1-M121

- shell/browser/api/electron_api_debugger.cc
- shell/browser/extensions/api/scripting/scripting_api.cc
- shell/browser/mac/dict_util.mm
- shell/browser/ui/webui/accessibility_ui.cc
Another PR in the "remove deprecated API use" series.
`base/json/json_writer.h` documents `base::JSONWriter::WriteJson()` this way:
>   // Deprecated: use the standalone method `WriteJson()` instead.
So this PR does exactly that.
Notes: none
> refactor: replace use of deprecated `base::JSONWriter::WriteJson()`

- lib/browser/api/web-contents.ts
- spec/api-web-contents-spec.ts
Invalid URLs never start navigation so there will be no navigation finish and did-fail-load will be only event raised in such cases. Fulfill the loadURL promise in did-fail-load if navigation was not started.
This change fixes #41193.
- [] `npm test` passes
Notes: Properly reject webcontents.loadURL promise on invalid URL load.
> fix: make sure invalid URL loads promises are fulfilled.

- shell/browser/api/electron_api_app.cc
- shell/browser/certificate_manager_model.cc
- shell/browser/certificate_manager_model.h
Another PR in the "remove deprecated API use" series.
`BrowserContext::GetResourceContext()` was deprecated a month ago by https://chromium-review.googlesource.com/c/chromium/src/+/5139789 because "[ResourceContext] seems to be an empty class meant to be removed at some point."
We use it in one place; and indeed, that use does seem superfluous. This PR removes it.
All reviewers welcomed. CC @zcbenz because I have a question about one change, mentioned inline
Notes: none.
> refactor: remove deprecated BrowserContext::ResourceContext

- lib/node/init.ts
Backport of https://github.com/electron/electron/pull/41148
Notes: none
> refactor: type-safe imports in lib/node/init.ts

- docs/api/browser-window.md
- shell/browser/api/electron_api_base_window.cc
- shell/browser/api/electron_api_base_window.h
- shell/browser/native_window.h
- shell/browser/native_window_mac.h
- shell/browser/native_window_mac.mm
- shell/browser/native_window_views.cc
- shell/browser/native_window_views.h
- spec/api-browser-window-spec.ts
Closes https://github.com/electron/electron/issues/38955.
We've historically not been consistent in our implementations of `BrowserWindow.isVisible()` and similar methods how occlusion affects return values. I believe instead it might be more effective to add in a separate method for apps to check occlusion status.
This also removes the occlusion check from the macOS implementation of `BrowserWindow.isVisible()`, which was broken and not being properly accounted for.
Notes: Added a new method `BrowserWindow.isOccluded()` to allow apps to check occlusion status.
> feat: add `BrowserWindow.isOccluded()`

- shell/common/gin_helper/trackable_object.h
- shell/common/key_weak_map.h
Code cleanup in `KeyWeakMap`:
- Make the impl struct `KeyObject` private
- Remove unused method `KeyWeakMap::Has()`
- Destructor was virtual but didn't need to be
- Rename misnamed local variable in `KeyValueMap::Values()`: was `keys`, is now `values`
Notes: none
> refactor:  KeyWeakMap cleanup

- buildflags/BUILD.gn
- buildflags/buildflags.gni
- shell/common/node_bindings.cc
For linux packagers and vendor builds, it is very common to add an extra field to `process.versions` to attach more information about the build, like which party did the build and the build ID in CI.
It was usually done by patching Electron, this PR makes it possible with a gn arg only.
Notes: none
> build: add flag for setting vendor version

- docs/api/utility-process.md
- docs/tutorial/fuses.md
This PR properly documents (1) that utility processes do _not_ receive an `stdout/stderr` `pipe` by default and (2) that they are excellent alternatives to `process.fork` when the `RunAsNode` fuse is set to `false`.
> docs: Properly document runAsNode utility process option

- docs/api/base-window.md
- docs/api/browser-window.md
#35658 added `docs/api/base-window.md` based on an outdated version of `docs/api/browser-window.md`
For example `getTrafficLightPosition()` / `setTrafficLightPosition()` don't exist anymore since #39479
Notes: none
> docs: fix docs/api/base-window.md

- docs/tutorial/quick-start.md
We must define language in HTML for different reasons (accessibility++)
A very simple, yet important, change - only defined language for `<html>` to be `<html lang="en">`.
Notes: none
> fix: add language to html in quick-start.md

- docs/api/native-image.md
Closes https://github.com/electron/electron/issues/41189.
Marks EXIF data as being unsupported in `nativeImage`. The simple [codec functions in Chromium](https://source.chromium.org/chromium/chromium/src/+/main:ui/gfx/codec/jpeg_codec.cc) we utilize right now do not take them into account.
Notes: none
> docs: note EXIF data unsupported in `nativeImage`

- patches/config.json
- script/apply_all_patches.py
- script/export_all_patches.py
- script/git-export-patches
- script/lib/git.py
- script/lint.js
- script/patches-mtime-cache.py
In our 'export patches' scripts, support filtering which patches get exported.
Not ready for code review just yet but I'm happy to answer any questions / concerns anyone has.
The tldr is when building Electron, we want to make it simpler to import/export downstream patches that don't make sense being upstreamed into `electron/electron`.
In the same way that [Electron patches upstream code like Chromium and V8](https://github.com/electron/electron/tree/main/patches), Microsoft's internal build of Electron has its own "downstream" patches to change Chromium, V8, and even Electron :smile_cat: . Keeping those "downstream" changes up-to-date with each new Electron release is a similar procedure to how @wg-upgrades keeps its patches up-to-date with each new Node or Chromium bump, so we have the …
> build: export matching patches

- shell/browser/api/electron_api_app.cc
- shell/browser/api/electron_api_safe_storage.cc
- shell/browser/api/electron_api_web_contents.cc
- shell/browser/api/electron_api_web_contents.h
- shell/browser/api/electron_api_web_contents_mac.mm
- shell/browser/browser.cc
- shell/browser/browser.h
- shell/browser/browser_process_impl.cc
- shell/browser/browser_process_impl.h
- shell/browser/native_window.cc
- shell/browser/native_window.h
- shell/browser/native_window_mac.mm
- shell/browser/ui/autofill_popup.cc
- shell/browser/ui/autofill_popup.h
- shell/browser/ui/cocoa/electron_inspectable_web_contents_view.mm
- shell/browser/ui/cocoa/electron_menu_controller.mm
- shell/browser/ui/cocoa/electron_ns_window_delegate.mm
- shell/browser/ui/electron_menu_model.cc
- shell/browser/ui/electron_menu_model.h
- shell/browser/ui/inspectable_web_contents.cc
- shell/browser/ui/inspectable_web_contents.h
- shell/browser/ui/views/autofill_popup_view.cc
- shell/browser/ui/views/inspectable_web_contents_view_views.cc
This PR follows up on #41125 by inlining more simple getters in line with the Chromium C++ style guide.
All reviews welcomed. CC'ing @codebytere, @zcbenz since they also reviewed 41125.
Notes: none.
> refactor: inline simple getters, pt . 2

- patches/chromium/.patches
- patches/chromium/fix_getcursorscreenpoint_wrongly_returns_0_0.patch
Fixes #41143.
The bug was introduced in https://chromium-review.googlesource.com/c/chromium/src/+/5214873 which tests for `x11::Input::CrossingEvent` but calls `ui::EventSystemLocationFromXEvent()`, which uses the similarly-named-but-different-class `x11::CrossingEvent`. This mismatch causes `x11::Input::CrossingEvent`s to incorrectly record the cursor's location at `0, 0`.
https://chromium-review.googlesource.com/c/chromium/src/+/5225569  exposed the 5214873 bug to Electron via `X11ScreenOzone::GetCursorScreenPoint()`, which caches the return value of `X11ScreenOzone::GetCursorScreenPoint() ` to avoid a round trip to X.
This patch should be backported to e29 to fix the release blocker + upstreamed to Chromium.
All reviews welcome!
Notes: Fixed Electron 29.0.0-beta.3 regression that could …
> fix: `GetCursorScreenpoint()` sometimes wrongly returns `(0,0)`

- shell/browser/native_window_mac.mm
Closes https://github.com/electron/electron/issues/40798
Refs https://github.com/microsoft/vscode/issues/204563
Fixes a crash that started occurring sporadically with some types of macOS window close after `PartitionAlloc` was enabled upstream. It seems to be the case now that `performClose:` can cause `window_` to be null, thus causing the call to `IsVisible` to crash trying to access a deallocated instance. There's probably  more effective long-term fix here but we can fix this by moving the conditional determining whether we should call `NotifyWindowCloseButtonClicked()` for a closed sheet above `performClosure` to avoid this problem altogether.
Using the `Cmd+Tab -> Cmd+Q` repro provided in https://github.com/electron/electron/issues/40798 I tracked this back to …
> fix: crash on macOS non-programmatic close

- shell/services/node/node_service.h
Refs https://github.com/microsoft/vscode/issues/196823
Fixes an issue where crashes in `node::Environment` destruction may not get propagated to the `NodeService` exit handler as the handler is destroyed prior to the `Environment`. By moving this member variable to the top of the list, we guarantee that it's destroyed last and thus that the utility process won't send faulty exit events while the process is still active.
Notes: Fixed an issue where crashes in `node::Environment` destruction potentially wouldn't be propagated to the `NodeService` exit handler.
> fix: destroy `NodeService` message pipe last

- docs/api/browser-window.md
- shell/browser/api/electron_api_base_window.cc
- shell/browser/api/electron_api_base_window.h
- shell/browser/native_window.h
- shell/browser/native_window_mac.h
- shell/browser/native_window_mac.mm
- shell/browser/native_window_views.cc
- shell/browser/native_window_views.h
- spec/api-browser-window-spec.ts
Closes https://github.com/electron/electron/issues/41295
Revert https://github.com/electron/electron/pull/38982 - it looks like there were missed failures on WOA. I'm working to debug but in the meantime we can revert to clear up CI depending how much progress I make.
Notes: none
> revert: add `BrowserWindow.isOccluded()`

- script/lib/git.py
- script/lib/patches.py
No production changes, just updates to our `script/lib/*py` scripts to make them a little more flexible. This is a continuation of #41174.
- `script/lib/patches.py` was already injecting  a `Patch-Filename: ` line when importing patches. This PR adds a sibling line, `Patch-Dir: ` to say what folder the patch was sourced from.
- `import_patches()` and `export_patches()` now take an optional `ref` parameter. When not specified, the default value is `refs/patches/upstream-head` , which matches the behavior prior to this patch. But by passing in a custom ref,  callers can now "stack" patches from different sources: source can use its own ref so that its import and export calls can work from the same unique reference point.
Notes: none
> feat: allow custom refs for patch import & export

- script/lib/git.py
- script/lib/patches.py
Manual backport of https://github.com/electron/electron/pull/41306
Notes: none
> build: allow custom refs for patch import & export

- patches/squirrel.mac/refactor_use_non-deprecated_nskeyedarchiver_apis.patch
Follow-up to https://github.com/electron/electron/pull/40315
`unarchivedObjectOfClass:fromData:error:` sets `secureCoding` to true and we don't
archive data with `secureCoding` enabled - use our own unarchiver to work around that.
Notes: none
> fix: work around `unarchivedObjectOfClass` requiring `secureCoding`

- chromium_src/BUILD.gn
- patches/chromium/.patches
- patches/chromium/fix_add_support_for_skipping_first_no-op_refresh_in_thumb_cap.patch
- shell/browser/api/electron_api_desktop_capturer.cc
This aligns us with Chromiums flags / capabilities in regards to using SCK for everything. Currently on 14.4 Electron apps will pop warnings for usage of deprecated APIs.  With this change and a few "enable-features" toggles.
`--enable-features="ScreenCaptureKitMac,ScreenCaptureKitStreamPickerSonoma,ThumbnailCapturerMac:capture_mode/sc_screenshot_manager"`
As Chromium enables these by default Electron will inherit those changes, apps wishing to skip ahead can apply these flags early.
This is safe to land / backport as is as in the default state this change is a no-op, multiple flags need to be enabled before any new codepath is followed
Notes: Added support for `ThumbnailCapturerMac` and `ScreenCaptureKitStreamPickerSonoma` chromium feature flags to bypass deprecated API warning on macOS …
> fix: add capability to use ScreenCaptureKit for thumbnail generation

- shell/browser/native_window.cc
Closes https://github.com/electron/electron/issues/41002
This is a workaround to close issue when an underlying view with `-webkit-app-region: drag;` blocks UI interaction on other overlayed views.
We already do this for MacOS [here](https://github.com/electron/electron/blob/03a3deca181807c2b152264a11f92c70b7adc9ef/shell/browser/native_window_mac.mm#L1757)
Notes: CSS style `-webkit-app-region: drag;` has no effect in full screen mode.
> fix: Ignore `-webkit-app-region: drag;` when window is in full screen mode.

- .circleci/config/base.yml
- appveyor-woa.yml
- appveyor.yml
https://chromium-review.googlesource.com/c/chromium/tools/depot_tools/+/5272474 broke our older branches building on goma, so this PR will lock the depot_tools revision so that older branches can continue to use goma.
Notes: none
> build: peg to a specific depot_tools so that we can use goma on older branches

- shell/browser/native_window_mac.mm
Made redundant by https://github.com/electron/electron/pull/35603.
Notes: none
> chore: remove unused anonymous namespace methods

- lib/browser/api/protocol.ts
- spec/api-protocol-spec.ts
Fixes a few annoying bugs which prevented requests intercepted with `protocol.handle()` from being properly forwarded to `net.fetch()`:
Fixes #39658
Fixes #40754 
Fixes #40826
I considered submitting multiple pull requests, but the fixes would've generated conflicts with each other. In essence I've just streamlined the `pull()` implementation of `convertToRequestBody()` and added a test case for every fixed bug. I also added an explicit error condition in case an unknown/new chunk type gets pushed into the protocol handler. Otherwise it is _very_
unobvious and hard to figure out why your request has been mutilated.
If you like, I am willing to fix the chunk type definitions / remove the `any` casts. However, I'd need some guidance on whether I should introduce local `type`s or add them to …
> fix: properly stream `uploadData` in `protocol.handle()`

- docs/breaking-changes.md
Since https://github.com/electron/electron/pull/41060 reverted the WebContentsView changes for 29-x-y, the breaking changes doc should have it noted as changing in v30 and not v29.
Notes: None
> chore: update breaking-changes.md to reflect WebContentsView revert

- .circleci/config/base.yml
- appveyor-woa.yml
- appveyor.yml
Follow up to https://github.com/electron/build-tools/pull/559, which turned the RBE config's helperPath to a function call. This PR modifies the helperPath to a function which passes in an empty config. (Thanks to @codebytere for spotting this!)
Not needed in 28-26, as those branches still use GOMA.
Notes: none
> ci: fix helperPath calls in ci configs

- shell/renderer/electron_render_frame_observer.cc
- shell/renderer/electron_render_frame_observer.h
A couple of small perf improvements to `ElectronRenderFrameObserver::ShouldNotifyClient()`:
- `GetBlinkPreferences()` returns a `const&`, so we can use that reference instead of making a temporary copy
- Don't copy the URL object unless we need it
- Move `is_main_world()` and `is_isolated_world()` from the header into an anonymous namespace in the .cc file so they can be inlined and made constexpr
Notes: none.
> perf: omit unnecessary work from `ElectronRenderFrameObserver::ShouldNotifyClient()`

- shell/renderer/electron_render_frame_observer.cc
- spec/api-browser-window-spec.ts
Fixes #41212 
Fixes a bug introduced by [crrev.com/c/4814003](https://chromium-review.googlesource.com/c/chromium/src/+/4814003), where draggable regions on local frames (set using the app-region CSS property) are no longer automatically set and calculated unless an app uses a Window Controls Overlay or is Borderless. In the upstream CL, the change assumes that the local frame is a browser tab, and doesn't need draggable regions calculated; on Electron's side, we can't make that assumption.
This PR modifies the check to `SetSupportsAppRegion()` to also check for frames outside of the main frame.
Notes: Fixed an issue where the `-webkit-app-region: drag` property was not respected on some windows.
> fix: check for draggable regions outside of main frame

- build/args/all.gn
This PR bumps the NMV to 123 for Electron 30. Please do not merge until the corresponding Node PR is merged.
Node PR: https://github.com/nodejs/node/pull/51803
Notes: none
> build: bump NMV to 123 for Electron 30

- docs/breaking-changes.md
This PR updates the language in breaking-changes.md to reflect better phrasing suggested by @erickzhao in the Electron 29 release blog post.
Notes: none
> docs: update breaking changes language

- filenames.gni
- shell/browser/feature_list.cc
- shell/browser/feature_list.h
- shell/browser/feature_list_mac.mm
This fixes a nasty warning / permission dialog that pops up to end-users when consuming legacy APIs.  Chrome has flipped these flags via field trials as have other Electron apps. It should just be the default.
Notes: Ensure ScreenCaptureKit is used exclusively on macOS 14.4 and higher to avoid permission prompts
> fix: use ScreenCaptureKit exclusively on macOS 14.4 and higher

- patches/chromium/.patches
- patches/chromium/prevent_mojotrap_event_re-ordering.patch
* 654837047abe4d3a0f22d17a22396eb77bb8235a from chromium
Notes:
* Security: backported fix for CVE-2024-1670.
> chore: cherry-pick 1 change Release-0-M122

- patches/node/build_add_gn_build_files.patch
Prior to this, `generate_gn_filenames_json.py` replaced all files starting with `deps/v8` with references to the version of v8 we actually use in `src/v8`. However, this causes problems for the set of files in `deps/v8/tools` as they're not compiled and Node.js depends on them directly with hardcoded paths. Up to now, I've just been manually changing this back after running `generate_gn_filenames_json.py`: https://github.com/electron/electron/blob/3f4c55b70d478340eef25e4c09e957dbcb30ed85/patches/node/build_add_gn_build_files.patch#L1716-L1726
We should figure out a better long-term path for this but for now this prevents needing to undo the change during roll filename generation.
Notes: none
> build: don't modify `deps/v8/tools` paths

- docs/api/app.md
- docs/api/session.md
- docs/api/structures/proxy-config.md
- filenames.auto.gni
- shell/browser/api/electron_api_app.cc
- shell/browser/api/electron_api_app.h
- shell/browser/browser_process_impl.cc
- shell/browser/browser_process_impl.h
- shell/browser/electron_browser_context.cc
- shell/browser/net/resolve_proxy_helper.cc
- shell/browser/net/resolve_proxy_helper.h
- spec/api-app-spec.ts
- spec/lib/spec-helpers.ts
Follow-up to https://github.com/electron/electron/pull/40017
Currently there is no way to configure proxy for the net module in the utility process due to network context backend used. Another option would have been to change the network context backend by allowing to configure session property of the net api in the utility process but that is complex since we need to think about how custom protocol and webrequest handlers need to run across process.
Notes: Add proxy configuring support for requests made with net module from utility process
> feat: add support for configuring system network context proxies

- shell/browser/badging/badge_manager_factory.cc
- shell/browser/badging/badge_manager_factory.h
- shell/browser/extensions/electron_extension_system_factory.cc
- shell/browser/extensions/electron_extension_system_factory.h
- shell/browser/media/media_capture_devices_dispatcher.cc
- shell/browser/media/media_capture_devices_dispatcher.h
- shell/browser/net/network_context_service_factory.cc
- shell/browser/net/network_context_service_factory.h
- shell/browser/serial/serial_chooser_context_factory.cc
- shell/browser/serial/serial_chooser_context_factory.h
- shell/browser/usb/usb_chooser_context_factory.cc
- shell/browser/usb/usb_chooser_context_factory.h
Ref https://issues.chromium.org/issues/40611103.
Seen while starting to work on https://github.com/electron/electron/issues/28422 - incidental cleanup.
Notes: none
> refactor: prefer using `base::NoDestructor` to `base::{Singleton,LazyInstance}`

- script/lib/git.py
We are getting this error in our internal builds
```
Traceback (most recent call last):
File "/Volumes/Builds/work/electron-28/src/microsoft/scripts/import_patches.py", line 20, in <module>
import git  # pylint: disable=wrong-import-position
^^^^^^^^^^
File "/Volumes/Builds/work/electron-28/src/electron/script/lib/git.py", line 18, in <module>
from .patches import PATCH_FILENAME_PREFIX, is_patch_location_line
ImportError: attempted relative import with no known parent package
```
our script does this
```python
SCRIPTS_LIB_DIR = os.path.join(ELECTRON_DIR, 'script', 'lib')
sys.path.append(SCRIPTS_LIB_DIR)
import git
from patches import patch_from_dir
```
Notes: none
> chore: fix import from patches.py in script/lib/git.py

- docs/api/web-contents.md
- docs/api/webview-tag.md
- docs/breaking-changes.md
- shell/common/gin_converters/content_converter.cc
- spec/ts-smoke/electron/main.ts
Follow-up to #40316
Notes: The `inputFieldType` property in the `context-menu` params has been removed.
> chore: remove deprecated `inputFieldType`

- patches/chromium/chore_add_electron_deps_to_gitignores.patch
Fixes the following:
Notes: none
> chore: add engflow-reclient-configs to gitignore

- script/release/uploaders/upload-symbols.py
Improvement attempt to address recent failures like [this](https://ci.appveyor.com/project/electron-bot/electron-woa-release/build/1.0.2766/job/l44f5qklp1sm2230).
Notes: none
> build: print error and retry on symstore fail

- script/release/uploaders/upload-to-github.ts
- script/release/uploaders/upload.py
We continue to see timeout errors when uploading to GitHub for releases, eg https://app.circleci.com/pipelines/github/electron/electron/78872/workflows/7322ac80-17f0-494f-98b4-d4c093653b18/jobs/1679041.
This PR adds additional logging to the script that uploads to GitHub.  Additionally the python script that calls that script has been changed to stream the logging instead of waiting until the script is done.  Hopefully this will provide enough additional context to diagnose the timeout issue.
Notes: none
> ci: add logging to uploading to GitHub releases

- .circleci/config/base.yml
- spec/api-browser-view-spec.ts
- spec/api-browser-window-spec.ts
- spec/disabled-tests.json
- spec/guest-window-manager-spec.ts
- spec/lib/artifacts.ts
- spec/lib/screen-helpers.ts
- spec/webview-spec.ts
This PR bundles together a couple of changes, with the shared goal of increasing our CI test pass rate. The changes are:
* Disables the `BrowserWindow module` > `focus and visibility` > `BrowserWindow.focus()` > `it does not activate the app if focusing an inactive panel` test.
* This test has been very flaky in CI as of recent, pointing to potential OS behavior changes and/or race conditions.
* I have found some issues that indicate this functionality has been somewhat broken for the past few months. We should re-enable this test in the future when we fix the underlying issue.
* Among others, see #41273 
* Addition of a helper that lets us generate artifacts from tests
* A refactor of tests based on screen captures
* The core problem is that these tests are somewhat fragile and it is …
> test: disable flaky macOS panel test & refactor screen capture testing

- .github/workflows/update_appveyor_image.yml
Make the commit for the update AppVeyor image workflow using `dsanders11/github-app-commit-action`, which will result in verified commits since it uses the GitHub API. This change drops the usage of `peter-evans/create-pull-request` as it was not playing nicely with the other changes, and the `gh` CLI has all the functionality we need for creating the PR (with the exception of the `delete-branch` feature, but that should happen on PR merge anyway).
It uses a dedicated GitHub app we created for the purpose as `github-actions[bot]` has several limitations, like not triggering other workflows and not being able to create PRs with `gh` CLI.
Notes: none
> ci: verified commits for appveyor update PR

- lib/browser/api/web-contents.ts
- spec/api-web-contents-spec.ts
Closes https://github.com/electron/electron/issues/41464.
Fixes an issue where `webContents.print(options)` failed if `options` was not passed or `undefined` is passed. This fixes that issue.
Notes: Fixes an issue where `webContents.print(options)` failed if `options` was not passed or `undefined` is passed.
> fix: webContents.print options should be optional

- patches/node/.patches
- patches/node/module_rework_of_memory_management_in_vm_apis_with_the.patch
- spec/fixtures/module/dynamic-import.js
- spec/node-spec.ts
Refs https://github.com/nodejs/node/pull/48510.
Resolves https://github.com/microsoft/vscode/issues/206630
Fixes a crash in Node.js when dynamically importing inside of a Function. When running the scripts sequentially, the `Local<Script>` created at `src/node_contextify.cc` can outlive the `ContextifyScript` so `ImportModuleDynamically` may crash because the ContextifyScript is released and the access can be invalid.
<p>
```
Electron Framework
node::loader::ImportModuleDynamically(v8::Local<v8::Context>, v8::Local<v8::Data>, v8::Local<v8::Value>, v8::Local<v8::String>, v8::Local<v8::FixedArray>) module_wrap.cc
Electron Framework
v8::internal::Isolate::RunHostImportModuleDynamicallyCallback(v8::internal::MaybeHandle<v8::internal::Script>, …
```
> fix: `node::loader::ImportModuleDynamically` crash

- .github/CODEOWNERS
- .github/workflows/update_appveyor_image.yml
Follow-up to #41470, [which couldn't open a PR when run](https://github.com/electron/electron/actions/runs/8098946962/job/22133568640) due to the reviewer team not being found. Looks like this is because the bot would need perms to read the org teams. Rather than give the bot additional permissions, it seems more reasonable to simply mark those files as owned by the team in `CODEOWNERS`, which should accomplish the same thing.
Notes: none
> chore: set wg-releases as CODEOWNER for AppVeyor configs

- appveyor-woa.yml
- appveyor.yml
This PR updates appveyor.yml to the latest baked image, e-124.0.6323.0.
Notes: none
> build: update appveyor image to latest version

- patches/chromium/.patches
- patches/chromium/allowlist_devtools_for_file_access_permission.patch
Fixes https://github.com/electron/electron/issues/39818
Backports https://chromium-review.googlesource.com/c/chromium/src/+/5132146
Notes: fix saving traces from devtools performance panel
> fix: saving traces from devtools performance panel

- patches/node/chore_allow_the_node_entrypoint_to_be_a_builtin_module.patch
- patches/node/fix_lazyload_fs_in_esm_loaders_to_apply_asar_patches.patch
- patches/node/fix_revert_src_lb_reducing_c_calls_of_esm_legacy_main_resolve.patch
- patches/node/refactor_allow_embedder_overriding_of_internal_fs_calls.patch
Refs https://github.com/electron/electron/issues/41469
Doesn't fix the issue but corrects for some fs overrides that weren't being properly applied.
Notes: none
> chore: fix fs overrides for asar

- shell/browser/api/electron_api_power_monitor_mac.mm
Closes https://github.com/electron/electron/issues/41497.
Fixes an issue where `user-did-{resign|become}-active` were not emitted properly on macOS.
This was happening because per [docs](https://developer.apple.com/documentation/appkit/nsworkspacesessiondidresignactivenotification?language=objc) the notification object is the shared NSWorkspace instance - we need to add an observer to `[[NSWorkspace sharedWorkspace] notificationCenter]` and not `[NSDistributedNotificationCenter defaultCenter]`.
Notes: Fixed an issue where `user-did-{resign|become}-active` were not emitted properly on macOS.
> fix: `user-did-{resign|become}-active` events on macOS

- shell/browser/api/electron_api_data_pipe_holder.cc
- shell/browser/api/electron_api_data_pipe_holder.h
- shell/browser/api/electron_api_power_save_blocker.cc
- shell/browser/api/electron_api_power_save_blocker.h
- shell/browser/api/electron_api_web_request.h
- shell/browser/api/message_port.h
- shell/common/api/electron_api_url_loader.cc
- shell/common/gin_converters/net_converter.cc
- shell/common/gin_helper/event.cc
- shell/common/gin_helper/event.h
Refs https://github.com/microsoft/vscode/issues/192119#issuecomment-1842407599.
Adds missing `gin::Wrappable` `GetTypeName` overrides.
Notes: none
> chore: add missing `gin::Wrappable` `GetTypeName` overrides

- electron_paks.gni
- spec/chromium-spec.ts
Closes https://github.com/electron/electron/issues/41459.
Refs CL:4472030
Broke in https://github.com/electron/electron/pull/38033 as a result of the above CL. Updates our `pak` file to handle changes and allow `chrome://process-internals` to load again.
Notes: Fixed `chrome://process-internals` failing to load.
> fix: `chrome://process-internals` failing to load

- patches/v8/.patches
- patches/v8/merged_wasm_add_bounds_check_in_tier-up_of_wasm-to-js_wrapper.patch
* 5578c6dd3a12dd66a85d075c599a6816efe68904 from v8
Notes:
* Security: backported fix for CVE-2024-2173.
> chore: cherry-pick 1 change from Release-2-M122

- spec/crash-spec.ts
- spec/lib/screen-helpers.ts
- #41127 was merged without running Windows x64 tests: https://ci.appveyor.com/project/electron-bot/electron-x64-testing/builds/49069062/job/nys9sfsv7hgn7bw1.  It turns out that the test added in that PR does not work on Windows x64
- #41377 also was merged without running Windows x64 tests and the test added in that PR does not work on Windows x64.
Notes: none
> test: disable CapturableScreen tests on Windows x64

- docs/api/native-image.md
- docs/api/tray.md
I was reading through the documentation and was a bit confused at times, so I wanted to take a stab at modernizing/cleaning it up.
* Changes example from setting the Tray icon using Clipboard to just generating the NativeImage
* Adds a preamble describing the utility of NativeImage (let me know if I'm off-base).
* Adds additional links to Template Image and Data URL external docs.
* A few wording changes to disambiguate concepts.
Notes: none
> docs: `nativeImage` api cleanup

- spec/api-app-spec.ts
Closes https://github.com/electron/electron/issues/24224.
They seem to work now except in Asan builds - re-enable them everywhere else. Better to have them partially running on Linux than not at all.
Notes: none
> test: re-enable `app.getGPUInfo()` specs on Linux

- patches/chromium/.patches
- patches/chromium/cherry-pick-2607ddacd643.patch
Fix primary display race condition crash on Windows
In rare cases, it's possible for the OS to provide us a list of displays
that doesn't contain the primary display. This situation causes
undefined behavior (dereference past vector end) and a crash to occur in
|display::win::(anon)::DisplayInfosToScreenWinDisplays| on builds
without DCHECK enabled.
Bug: 40265302
Change-Id: I2154bedea84478a84147c380610c85d4ea3f703a
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5353255
Reviewed-by: David Bienvenu <davidbienvenu@chromium.org>
Reviewed-by: Robert Liao <robliao@chromium.org>
Commit-Queue: David Bienvenu <davidbienvenu@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1271793}
Notes: Backported fix for 40265302.
> chore: cherry-pick 2607ddacd643 from chromium

- patches/chromium/.patches
- patches/chromium/gpu_notify_when_dxdiag_request_fails.patch
- patches/chromium/remove_dxdiag_telemetry_code.patch
- shell/browser/api/gpuinfo_manager.cc
This PR cherry-picks an upstream change from Chromium: https://chromium-review.googlesource.com/c/chromium/src/+/5337304 This change was causing memory corruption issues and increasing crashes. This fix will land naturally in main and 30-x-y, but we'll cherry-pick it into the other stable release branches to resolve the memory corruption crashes.
Notes: Fixes a memory corruption crash on Windows by removing DXDiag telemetry code.
> fix: remove DXDiag telemetry code

- spec/api-browser-window-spec.ts
As in title. These are consistently failing on arm64 with a [window pollution issue](https://circleci-tasks-prod.s3.us-east-1.amazonaws.com/storage/artifacts/6f0d7dce-43d4-4fdd-997a-ade727476389/7391d75b-72ac-4154-89aa-3dae4773d37e/0/src/electron/spec/artifacts/color-mismatch-017b1914c837b325d6f652f6.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=ASIAQVFQINEODM3JFTG4%2F20240313%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240313T084642Z&X-Amz-Expires=60&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEFEaCXVzLWVhc3QtMSJHMEUCIHuUfWwNtCduQJjIE3B5agvxDSjS5HoghrTEVdyghU68AiEA4AJrSfX4Ku5i4XkKelSHthnx5hQJtY200u42%2BFT2Cg8qqwIIWhADGgwwNDU0NjY4MDY1NTYiDGIBKptOGxdWQ80QAyqIApkfQcq3Gq5jDDz%2BBWq7dYB%2B%2BtgFXXsRZVeF1%2FBkdHzSTtDp9THNlgf5rUExjX9DsNaXxLAz%2BlHmkO197neFM4Mq9tnGLLoYs4NirMgCbGYxBIKAe1U7dL6kNu …
> test: disable transparency tests on macOS arm64

- shell/browser/ui/views/win_caption_button.cc
- shell/browser/ui/views/win_icon_painter.cc
- shell/browser/ui/views/win_icon_painter.h
Refs CL:4428171
Refs https://issues.chromium.org/issues/40890030
Refs https://issues.chromium.org/issues/40265331
On Windows 11's Restore button, the top and right edges of the top
rounded square should be drawn with half-rounded linecaps, rather than
being flat at the ends.
Also, the stroke width applied to the caption buttons is too thin when
the current fractional scale is close to the next higher integer
scaling, E.g. 175% and 275%, but not 150% or 125%.
Notes: Improved appearance of caption buttons on Windows 11 when using Windows Control Overlay.
> fix: improve caption button appearance on Windows 11

- shell/browser/api/electron_api_web_frame_main.cc
Refs https://issues.chromium.org/issues/40169570
Refs https://github.com/electron/electron/pull/30076
Fixes a crash in `WebFrameMain::FromRenderFrameHost` that could occur when a given RenderFrameHost's FrameTreeNode is invalid. In https://github.com/electron/electron/pull/30076 we addressed cross-origin navigation disposing WebFrameMain instances by mapping FrameTreeNode ids to WebFrameMains. At the time, a RenderFrameHost's FrameTreeNode was constant for the lifetime of the RenderFrameHost - that's no longer the case. With prerendering and bfcache, a `RenderFrameHost` can travel from one `FrameTreeNode` to another one during prerender activation.
We should migrate our mapping logic away from 1:1 `FrameTreeNode` -> `RenderFrameHost` but this addresses it crashing in the short term. …
> fix: account for potentially swapped `FrameTreeNodeId` in `WebFrameMain`

- BUILD.gn
The dependency name in Chromium has changed and the build fails without an updated name.
Notes: Fix ASAN build on macOS
cc @nornagon
> fix: asan build on macos

- patches/chromium/.patches
- patches/chromium/update_crashpad_to_37afd37401253ebcebcf6e07ce15c8cfecb1a1cc.patch
* 2a7dc5af567b4434cc346e9e2aa5dcd01ef64148 from chromium
Notes:
* Security: backported fix for 325296797.
> chore: cherry-pick 1 change from Release-3-M122

- spec/lib/spec-helpers.ts
Allow skipping or running `itremote` specs in isolation.
Notes: none
> test: modify remote specs to allow skip or only

- shell/browser/feature_list_mac.mm
Ref https://github.com/electron/electron/pull/41397.
<details><summary>Details</summary>
<p>
```
[64768:0318/145439.936909:FATAL:feature_list.cc(873)] Check failed: trial. trial='StudyThumbnailCapturerMac' does not exist
0   Electron Framework                  0x000000011cb39cc0 base::debug::CollectStackTrace(void const**, unsigned long) + 28
1   Electron Framework                  0x000000011cb29a20 base::debug::StackTrace::StackTrace() + 24
2   Electron Framework                  0x000000011ca57b40 logging::LogMessage::Flush() + 132
3   Electron Framework                  0x000000011ca57a3c logging::LogMessage::~LogMessage() + 36
4   Electron Framework                  0x000000011ca4200c logging::(anonymous namespace)::DCheckLogMessage::~DCheckLogMessage() + 124
5   Electron Framework …
```
> build: work around ScreenCaptureKit bad feature flag parsing in Chromium

- shell/browser/serial/serial_chooser_controller.cc
The `serial-port-added` event shouldn't be emitted if the serial port being added doesn't pass filters that were set. This fixes that - upstream logic does [the same](https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/ui/serial/serial_chooser_controller.cc;l=219;bpv=1;bpt=1).
Notes: Fixes an issue where the `serial-port-added` event improperly respected filters set by `serial.requestPort()`
> fix: `serial-port-added` should respect filters

- patches/v8/.patches
- patches/v8/merged_parser_fix_home_object_proxy_to_work_off-thread.patch
* 615c099b587db35e68486b531144241df5ec8579 from v8
Notes:
* Security: backported fix for CVE-2024-2625.
> chore: cherry-pick 1 change from Release-0-M123

- .github/workflows/issue-labeled.yml
Help cut down on manual work by setting the status when https://github.com/electron/electron/labels/status%2Fconfirmed or https://github.com/electron/electron/labels/status%2Freviewed are set. Being conservative with what labels will set the triaged status to avoid accidentally being overzealous since it's ambiguous to determine triage status from labels.
Notes: none
> ci: set issue status to triaged on status/{confirmed,reviewed} label

- script/apply_all_patches.py
- script/dbus_mock.py
- script/export_all_patches.py
- script/generate-config-gypi.py
- script/generate-zip-manifest.py
- script/generate_node_version_header.py
- script/lib/config.py
- script/lib/git.py
- script/lib/native_tests.py
- script/lib/patches.py
- script/lib/util.py
- script/lint.js
- script/native-tests.py
- script/patches-mtime-cache.py
- script/release/uploaders/upload-index-json.py
- script/release/uploaders/upload-node-checksums.py
- script/release/uploaders/upload-node-headers.py
- script/release/uploaders/upload-symbols.py
- script/release/uploaders/upload.py
- script/run-clang-format.py
- script/tar.py
- script/verify-chromedriver.py
- script/verify-ffmpeg.py
- script/verify-mksnapshot.py
- script/zip_manifests/check-zip-manifest.py
upstream has added [pylint 2.17 to depot-tools](https://chromium-review.googlesource.com/c/chromium/tools/depot_tools/+/5062345), so let's start using it instead of pylint 2.7.
All reviews welcome. CC @electron/wg-infra 
Notes: none
> chore: bump pylint to 2.17

- .github/workflows/issue-opened.yml
Automation to parse the Markdown in new issues and adds the https://github.com/electron/electron/labels/has-repro-gist label if a Gist URL is found under the "Testcase Gist URL" header (otherwise it's a no-op).
Notes: none
> ci: automatically add the 'has-repro-gist' label

- lib/node/asar-fs-wrapper.ts
- spec/asar-spec.ts
Follow-up to https://github.com/electron/electron/pull/41582. Support `withFileTypes` with recursive readdir.
Notes: Added support for `withFileTypes` when calling `fs.{readdir|readdirSync}` with the `recursive` in Asar archives.
> fix: support `withFileTypes` in `fs.{readdir|readdirSync}`

- README.md
docs: nodejs trademark policy link broken, this pr updates to valid value
Notes: none
> docs: nodejs trademark policy link broken

- .circleci/config/base.yml
- spec/api-app-spec.ts
- spec/api-media-handler-spec.ts
- spec/api-web-contents-spec.ts
This PR moves our macOS arm64 testing to CircleCI.  This will allow that testing to run on forks,
Notes: none
> ci: use CircleCI hosted macOS arm64 runners for testing

- filenames.gni
- shell/browser/api/electron_api_app.cc
- shell/browser/api/electron_api_app.h
- shell/browser/browser.cc
- shell/browser/browser.h
- shell/browser/browser_linux.cc
- shell/browser/browser_mac.mm
- shell/browser/browser_win.cc
- shell/common/gin_converters/login_item_settings_converter.cc
- shell/common/gin_converters/login_item_settings_converter.h
- spec/api-app-spec.ts
Fixes an issue where errors thrown `app.setLoginItemSettings` would be silently swallowed and the object returned. To fix this, we return a `v8::Local<v8::Value>` and shift the conversion locale.
This was missed in our tests as our machines weren't running a high enough version of macOS.
Notes: Fixed an issue where `app.getLoginItemSettings` didn't correctly throw errors.
> fix: `app.setLoginItemSettings` error getting swallowed by gin conversion

- shell/common/platform_util_win.cc
Resolves #11617, e.g. before Windows Explorer wouldn't open when calling `shell.showItemInFolder(fullPath)` with a path that contains forward slashes. This PR makes the change of first normalizing the path that was passed in using `NormalizePathSeparators()`.
Notes: Fixed `shell.showItemInFolder` not opening Windows Explorer if the passed path contains forward slashes
> fix: normalize path before calling `showItemInFolder` and `openPath`

- shell/common/gin_helper/callback.h
- shell/common/gin_helper/constructor.h
- shell/common/gin_helper/function_template.cc
- shell/common/gin_helper/function_template.h
Refs https://chromium-review.googlesource.com/c/chromium/src/+/5104930
Refs https://github.com/microsoft/vscode/issues/192119
We should still make it a goal to use upstream `gin/function_template`, but that'll be perhaps a longer-term venture as there are several critical things we do differently than they do. This updates our forked `gin/function_template.{h|cc}` to apply those differences to the latest upstream version of those files. A key critical change is from the above CL:
> gin previously relied exclusively on garbage collection in order to trigger cleanup of function templates. This is unreliable as garbage collection is never guaranteed to run, especially for short-lived isolates.
Now, we add observers for isolate disposal in order to clean up function templates once an isolate …
> refactor: update `gin_helper/function_template`

- docs/api/app.md
- docs/api/auto-updater.md
- docs/api/base-window.md
- docs/api/browser-window.md
- docs/api/client-request.md
- docs/api/crash-reporter.md
- docs/api/ipc-main.md
- docs/api/protocol.md
- docs/api/push-notifications.md
- docs/api/session.md
- docs/api/structures/file-path-with-headers.md
- docs/api/structures/notification-response.md
- docs/api/structures/protocol-request.md
- docs/api/structures/protocol-response.md
- docs/api/structures/trace-config.md
- docs/api/system-preferences.md
- docs/api/web-contents.md
- docs/api/web-request.md
- docs/api/webview-tag.md
- docs/breaking-changes.md
As discussed in the last @electron/wg-ecosystem meeting, the website upgrade to MDX 3 requires us to add additional escape characters to our parametrized API types.
This is because `Record<string, string>` will not render on MDX 3, while it did on MDX 1 and still does on most other Markdown implementations.
Escaping `<` as `\<` and escaping `>` as `\>` provides a solution that's _good enough_ on all environments. For example, for `Record\<string, string\>`:
* On GFM (github.com), it renders as `Record<string, string>`.
* On MDX 1 (current site), it renders as `Record\<string, string>`.
* On MDX 3 (Docusaurus 3 upgrade), it renders as `Record<string, string>`.
See CI run for Archeologist showing no changes in the TS output.
Notes: none
> docs: backslash escape parametrized TypeScript types

- shell/common/extensions/api/_api_features.json
- spec/extensions-spec.ts
- spec/fixtures/extensions/chrome-scripting/background.js
- spec/fixtures/extensions/chrome-scripting/main.js
Adds a test and `_api_features.json` definition for `chrome.scripting.globalParams`. Also adds a missing `extension.lastError` definition and manifest cap.
Notes: none
> test: add test and `api_feature` definition for `chrome.scripting.globalParams`

- shell/browser/extensions/api/scripting/scripting_api.cc
Refs CL:5225796
Fixes a potential crash on extension unload when script validation finishes. An extension may be unloaded while file validation for content scripts that are being registered is taking place. Fix this by guarding against an unloaded extension in OnUserScriptFilesValidated by returning early.
Notes: Fixed a potential crash in `chrome.scripting` on extension unload.
> fix: crash on extension unload when script validation finishes

- spec/api-web-contents-spec.ts
**Problem:**
[Flaky tests in navigationHistory](https://app.circleci.com/pipelines/github/electron/electron/79647/workflows/a7837709-00e2-4043-a059-1b10ffb63941/jobs/1692441/tests) because the tests load real URLs, meaning they’d fail if e.g. the website hiccups or there’s an internet connection issue. 
**This PR:**
Notes: none
> test: fix flaky tests in `webContents.navigationHistory`

- spec/api-web-contents-spec.ts
This PR:
I'm super sorry, I realized I missed 1 more url while I was looking over the commit. I double checked all the urls are now replaced with a find throughout the file.
I will make sure my backported PRs are properly updated once this merges!
Notes: none
> test: remove hardcoded url

- shell/browser/notifications/linux/libnotify_notification.cc
- shell/browser/notifications/linux/libnotify_notification.h
Callers of `Notification::Dismiss()` assume that the notification instance is not deleted after the call, but this was not the case for `LibnotifyNotification`:
- `Destroy()` would get `this` deleted.
- `notify_notification_close()` in portal environment triggers `LibnotifyNotification::OnNotificationClosed()`, and finally calls `Destroy()`
This patch removes all `Destroy()` in `Dismiss()`, and adds a boolean to tell whether `notify_notification_close()` is running, to avoid crash under portal environment.
Fixes #40461.
Notes: Fixed crash in Notification::Close() under libnotify 0.8.x with portal environment.
> fix: don't do self-destroy in LibnotifyNotification::Dismiss()

- docs/api/session.md
- spec/chromium-spec.ts
Closes https://github.com/electron/electron/issues/41368.
Documents `top-level-storage-api` in `ses.setPermission{Check|Request}Handler` and adds some associated tests.
Notes: none
> test: add tests for Storage Access API

- lib/common/api/net-client-request.ts
- spec/api-net-session-spec.ts
There was an issue I encountered that I mistakenly used `undefined` as a header value when using `electron.net.request()`, then threw an error "Cannot read properties of undefined (reading ‘toString’)". It's a non-semantic error and unfriendly for debug. 
I've check the source code, then found out there do have a `empty` check but it's only checked the `null` and miss out `undefined`.
Please let me know if this correction is need, then I'll add ut for it.
Notes: fix(ClientRequest): recognize the 'undefined' header value
> fix: recognize 'undefined' header value in `ClientRequest`

- docs/api/client-request.md
- spec/api-net-spec.ts
As pointed out by @daihere1993, this option was supported but missing from the
types/docs.
Notes: Added missing documentation for `headers` option in ClientRequest.
> docs: add missing headers option to ClientRequest options

- BUILD.gn
- shell/browser/serial/electron_serial_delegate.cc
- shell/browser/serial/electron_serial_delegate.h
- shell/browser/serial/serial_chooser_controller.cc
- shell/browser/serial/serial_chooser_controller.h
Refs CL:4522192.
In https://github.com/electron/electron/pull/38465 we added a parameter to `ElectronSerialDelegate::RunChooser` to account for upstream changes but never actually implemented the feature the parameter was added to support. This PR adds support for Bluetooth ports being requested by service class ID, thereby bringing our WebSerial implementation into alignment with the current state of the web platform api. Now, users can do e.g:
```js
const port = await navigator.serial.requestPort({
filters: [{bluetoothServiceClassId: 0x1101}]
});
```
Notes: Added support for Bluetooth ports being requested by service class ID in `navigator.serial`.
> feat(serial): allow Bluetooth ports to be requested by service class ID

- spec/webview-spec.ts
Flaking on Linux and macOS x64 too now:
* https://app.circleci.com/pipelines/github/electron/electron/79689/workflows/07ff3787-8219-45b3-8027-13f5ffce97d3/jobs/1693178/tests
* https://app.circleci.com/pipelines/github/electron/electron/79689/workflows/0acb9086-8617-49b5-8f47-977904c4cc12/jobs/1693219/tests
Disable entirely to get CI back to green.
Notes: none
> test: disable flaky `<webview>.capturePage()` specs

- shell/browser/electron_browser_client.cc
- shell/browser/ui/devtools_manager_delegate.cc
- shell/browser/ui/devtools_manager_delegate.h
- spec/api-debugger-spec.ts
Closes https://github.com/electron/electron/issues/41703.
Addresses an issue where calling `Storage.{get|set|clear}Cookies` via the Chrome Devtools protocol would return the following error:
> Browser context management is not supported.
This happened as a result of [this logic](https://source.chromium.org/chromium/chromium/src/+/main:content/browser/devtools/protocol/storage_handler.cc;l=957;drc=05bb4ce2df79db9c7f4fd9ef1856f0c41bca440f;bpv=1;bpt=1) for Storage handling which relies on a browser context being available via `DevToolsManagerDelegate::GetDefaultBrowserContext()`. Chrome's subclasses of `DevToolsManagerDelegate` override this to return a valid `BrowserContext`, but ours did not until this PR and so it would always be nullptr.
We can address this by returning the default …
> fix: `Storage.{get|set|clear}Cookies` via CDP not working

- script/release/ci-release-build.js
In preparation for our migration to GitHub Actions, this PR modifies the release build script to accept and run GitHub Actions as an optional CI provider. Actions will not be run by default - it must be manually passed into the command line flag.
Notes: none
> build: add GH Actions to release-build script

- docs/api/navigation-history.md
- docs/api/web-contents.md
- filenames.auto.gni
- lib/browser/api/web-contents.ts
- shell/browser/api/electron_api_web_contents.cc
- shell/browser/api/electron_api_web_contents.h
- spec/api-web-contents-spec.ts
- spec/chromium-spec.ts
- typings/internal-electron.d.ts
Backport of #41577 
Notes: none
> feat: add `navigationHistory.getEntryAtIndex(int index)` method 

- .markdownlint.json
- docs/api/client-request.md
- docs/tutorial/tutorial-2-first-app.md
- package.json
- yarn.lock
Follow-up to #41575 which adds a linting rule to enforce escaped angle brackets (technically only the opening one, since that's all that's needed to avoid the MDX issues). Includes a case that was missed in the original PR.
Also enables the `no-inline-html` rule (with certain elements allowed) as some usages of angle brackets will be considered as inline HTML by `markdown-it`, so we need a combination of both rules to ensure we catch all cases. The "unknown" element type is allowed because `markdownlint` is being overzealous and parsing the info string in some code blocks where we have TS types. It was quicker to allow that type than to try to fix the underlying issue (which may already be fixed upstream, will need to check).
Notes: none
> build: add Markdown lint check for unescaped angle brackets

- docs/tutorial/electron-timelines.md
As pointed out in the Discord server, the Node.js version marked in our docs was wrong. this version number was corrected in https://github.com/electron/electron/commit/035681202675a2543b2ed47e28fbdf8c9feffbd6 but I can't really backport it fully.
Backport of #41339
Notes: none
> docs: update node.js version for Electron 29

- patches/v8/.patches
- patches/v8/merged_wasm_gc_scan_the_code_field_of_the_wasminternalfunction.patch
* a4ae81ae1209b06a843d5e5c5990464fecd37859 from v8
Notes:
* Security: backported fix for CVE-2024-3156.
> chore: cherry-pick 1 change from Release-2-M123

- shell/browser/osr/osr_render_widget_host_view.cc
GNU libstdc++ does not allow using std::unique_ptr on incomplete types, leading to a compile error.
Notes: none
> build: add missing header for `content::SyntheticGestureTarget`

- shell/browser/ui/views/win_caption_button_container.cc
Closes https://github.com/electron/electron/issues/41786.
Fixes a bug where a window with maximization disabled and WCO enabled would still show its maximization button. This diverged from [upstream behavior](https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/ui/views/frame/browser_caption_button_container_win.cc;l=212?q=%22windows%20cannot%20be%20taken%20out%20of%20fullscreen%20or%20tiled%20mode%22&sq=package:chromium&type=cs), which shows the button if it both can maximize and is not currently maximized. This also cleans up existing code to remove redundancies and better match upstream.
Notes: Fixes a bug where a window with maximization disabled and WCO enabled would still show its maximization button
> fix: WCO maximize button visibility when non-maximizable

- shell/browser/extensions/api/management/electron_management_api_delegate.cc
- shell/browser/extensions/api/management/electron_management_api_delegate.h
- shell/browser/extensions/api/pdf_viewer_private/pdf_viewer_private_api.cc
- shell/browser/extensions/api/pdf_viewer_private/pdf_viewer_private_api.h
- shell/browser/extensions/api/streams_private/streams_private_api.cc
- shell/common/extensions/api/pdf_viewer_private.idl
Refs https://issues.chromium.org/issues/40268279
Closes https://github.com/electron/electron/issues/41726.
Incorporates:
- https://chromium-review.googlesource.com/c/chromium/src/+/4666784
- https://chromium-review.googlesource.com/c/chromium/src/+/4691287
- https://chromium-review.googlesource.com/c/chromium/src/+/4876972
- https://chromium-review.googlesource.com/c/chromium/src/+/4682380
- https://chromium-review.googlesource.com/c/chromium/src/+/5227362
- https://chromium-review.googlesource.com/c/chromium/src/+/5335529
Refactors our PDF viewer implementation to work with upstream migration from GuestView to OOPIF.
Notes: none
> refactor: move PDF viewer to OOPIF

- shell/browser/mac/in_app_purchase.mm
fix typo (information has no plural) in the comment section of `in_app_purchase.mm`
notes: none
> fix: typos in comment section of `in_app_purchase.mm`

- BUILD.gn
- shell/browser/api/electron_api_web_contents.cc
- shell/browser/printing/printing_utils.cc
- shell/browser/printing/printing_utils.h
Closes https://github.com/electron/electron/issues/39179.
Closes https://github.com/electron/electron/issues/40714.
Fixes an issue on Windows where silent printing resulted in comically tiny renderer output unless the dpi was overridden on the user side. This is fixed by pulling the dpi before calling print and using the printer default unless it's been explicitly overridden by the user. This PR also pulls printing utility functions into a new folder for cleanliness and simplicity.
Tested with https://gist.github.com/053de2471f74277e60fb908aaa3685ff
[PDF Sample Before](https://github.com/electron/electron/files/14922174/before.pdf)
[PDF Sample After](https://github.com/electron/electron/files/14922178/after.pdf)
Notes: Fixes an issue on Windows where silent printing resulted in comically …
> fix: silent printing default dpi on Windows

- shell/browser/native_window_mac.h
- shell/browser/native_window_mac.mm
- spec/api-browser-window-spec.ts
- spec/disabled-tests.json
Resolves https://github.com/electron/electron/issues/41273.
This is a follow-up to https://github.com/electron/electron/pull/40307 and https://github.com/electron/electron/pull/40570 to make sure that panel windows can be both shown and focused without activating the app. The previous attempts had a few issues:
1. The `IsPanel()` function checked for `NSPanel`. But Electron "panel" windows are not true panels, they are `ElectronPanelWindow` which inherit from `NSWindow` without going through `NSPanel` at all. So this function never actually returned true. 
2. The logic to avoid activation relied on the flaky/situational/deprecated `activateIgnoringOtherApps:NO`. It is better to simply not make any call to activate the app at all when focusing a panel window.
3. Activation handling was …
> fix: do not activate app when showing a panel on Mac

- BUILD.gn
Refs https://chromium-review.googlesource.com/c/chromium/src/+/5208502
```
In file included from ../node_modules/node-addon-api/napi.h:5:
In file included from /mnt/vss/_work/1/s/.build/libcxx_headers/include/functional:515:
In file included from /mnt/vss/_work/1/s/.build/libcxx_headers/include/__algorithm/search.h:14:
In file included from /mnt/vss/_work/1/s/.build/libcxx_headers/include/__algorithm/iterator_operations.h:12:
In file included from /mnt/vss/_work/1/s/.build/libcxx_headers/include/__algorithm/iter_swap.h:14:
In file included from /mnt/vss/_work/1/s/.build/libcxx_headers/include/__utility/swap.h:16:
In file included from /mnt/vss/_work/1/s/.build/libcxx_headers/include/__type_traits/is_nothrow_move_constructible.h:15:
In file included from …
```
> fix: package <__assertion_handler> as part of libcxx headers

- docs/api/menu-item.md
- docs/api/menu.md
The documentation for the `Menu` and `MenuItem` classes describes the constructor options `before`, `after`, `beforeGroupContaining` and `afterGroupContaining` wrongly. It is said, that the placement would be relative to the `MenuItem` containing the specified **labels**. The placement however is relative to a `MenuItem` with the specified **id** as shown in the example in the `Menu` classes [documentation](https://www.electronjs.org/docs/latest/api/menu#examples-1). This PR changes the descriptions to reflect this.
Notes:  none
> docs: use "id" instead of "label" for positions

- docs/api/app.md
Closes https://github.com/electron/electron/issues/29315
Took a stab at this long-standing docs issue. Please clarify my wording if I'm misusing some of the terminology here.
cc @pushkin- @nornagon @electron/docs 
Notes: none
> docs: clarify before `ready` usage

- script/generate-config-gypi.py
'\w' already includes '_'. solves a SyntaxWarning on python 3.12.
Notes: none
> build: redundant regex character class in generate-config-gypi.py

- patches/chromium/feat_add_data_parameter_to_processsingleton.patch
- shell/browser/api/electron_api_app.cc
- shell/browser/api/electron_api_app.h
replace `std::vector<const uint8_t>` with `std::vector<uint8_t>`
breaks compilation with gcc/libstdc++.
this is in line with https://issues.chromium.org/issues/323708866
Notes: none
> fix: stop using std::vector<const uint8_t> in ProcessingSingleton

- shell/browser/api/electron_api_app.cc
- shell/browser/api/electron_api_desktop_capturer.cc
- shell/browser/electron_browser_main_parts.cc
- shell/browser/net/asar/asar_url_loader.cc
- shell/browser/notifications/win/windows_toast_notification.cc
- shell/common/api/electron_api_command_line.cc
- shell/common/api/electron_api_shell.cc
Minor perf cleanup for cases where we have a string or wstring `foo` and pass it to a method that takes a `std::string_view` with `foo.c_str()` instead of just `foo`. Passing the string is preferable since its length is already known and won't have to be recomputed from the `const char*`.
All reviews welcome; no specific individual stakeholders.
Notes: none.
> perf: remove unnecessary `.c_str()` calls

- patches/chromium/printing.patch
- shell/browser/api/electron_api_web_contents.cc
- shell/browser/api/electron_api_web_contents.h
This PR cleans up `printing.patch` a bit by removing some cruft as well as folding the `silent` setting into the primary `base::Dict` holding other settings.
Notes: none
> refactor: fold silent print into settings

- shell/common/api/electron_api_v8_util.cc
Remove some dead hashing code. Looks like it's been unused since e1e73fa?
Notes: none
> chore: remove unused hash function

- patches/devtools_frontend/.patches
- patches/devtools_frontend/fix_support_for_worklet_targets.patch
Refs https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/5367245.
Closes https://github.com/electron/electron/issues/41263
Fixes an issue where `console.log()` in AudioWorkletGlobalScope produced incorrect output.
Notes: Fixes an issue where `console.log()` in AudioWorkletGlobalScope produced incorrect output.
> fix: console.log() in AudioWorkletGlobalScope

- shell/common/api/electron_api_native_image_mac.mm
- shell/common/platform_util_mac.mm
- spec/api-native-image-spec.ts
- spec/api-shell-spec.ts
`nativeImage.createThumbnailFromPath` wasn't resolving when called in the
renderer. This started happening in #37701, I think Chromium stopped pumping
the Grand Central Dispatch queue in renderer processes. I haven't figured out
the exact change which caused the regression, but relying on Chromium's own
dispatch queues fixes the issue.
Fixes #41816.
Notes: Fixed nativeImage.createThumbnailFromPath and shell.openExternal not resolving when called in the renderer process.
> fix: `nativeImage.createThumbnailFromPath` and `shell.openExternal` in renderer

- shell/browser/linux/unity_service.cc
Electron uses libunity to implement [setProgressBar](https://www.electronjs.org/de/docs/latest/api/browser-window#winsetprogressbarprogress-options) and [setBadgeCount](https://www.electronjs.org/de/docs/latest/api/browser-window#winsetprogressbarprogress-options). The Unity Launcher API is currently supported by multiple Programs and Desktop. Electron cheeks for some reason which desktop environment the User is using.
This is completely pointless. libunity just emits a DBus signal. If a Desktop Environment don't support the API, it just don't listen to the signal, so there is no harm when emitting this signal.
On the other hand, this Signal is supported by various Software such as the [Dash to Dock](https://github.com/micheleg/dash-to-dock/blob/c569e2e3dd4b79f848d22d23375ecad1038b2d97/lau …
> fix: don't check for Desktop Environment in unity_service.cc

- shell/browser/electron_browser_context.cc
- shell/browser/electron_browser_context.h
- shell/browser/usb/usb_chooser_controller.cc
- shell/browser/web_contents_preferences.cc
- shell/browser/window_list.cc
- shell/common/api/electron_bindings.cc
- shell/common/gin_helper/cleaned_up_at_exit.cc
- shell/renderer/web_worker_observer.cc
use `std::erase()` and `std::erase_if()` to simplify code, such as replacing [erase -> remove idiom](https://en.wikipedia.org/wiki/Erase%E2%80%93remove_idiom) code, e.g.:
```diff
-  Instances().erase(std::remove(Instances().begin(), Instances().end(), this),
-                    Instances().end());
+  std::erase(Instances(), this);
```
Upstream tracking bug: https://issues.chromium.org/issues/40256229
Upstream guidelines: https://chromium.googlesource.com/chromium/src/+/main/styleguide/c++/c++-features.md#std_erase_if_for-containers-allowed
Notes: none
> refactor: use `std::erase()`

- .devcontainer/docker-compose.yml
Now required as n-api will not build with lower than 18.
Notes: none
> build: use latest devcontainer buildimage with codespaces

- shell/browser/osr/osr_render_widget_host_view.cc
- shell/browser/osr/osr_render_widget_host_view.h
Fixes: [#37399](https://github.com/electron/electron/issues/37399)
1. `OffScreenRenderWidgetHostView` inherit from `RenderFrameMetadataProvider::Observer` and implement the `OnLocalSurfaceIdChanged` method. 
2. `GPU Process crashed` will trigger `OnLocalSurfaceIdChanged` and we can call `ResizeRootLayer` if `surface_id` changed
Notes: electron doesn't paint on offscreen-render mode after gpu process crashed
> fix: offscreen rendering does not paint after gpu process crashed

- lib/browser/api/protocol.ts
- spec/api-protocol-spec.ts
- spec/index.js
This fixes an issue in protocol.handle() when consuming incoming data chunks
asynchronously.
Previously, a view on the incoming buffer was passed to the handler function,
meaning that subsequent incoming packets would overwrite the buffer and cause
unexpected changes in the data. Now a copy of the buffer is made before passing
to the handler function instead.
Fixes #41872.
Notes: Fixed data corruption when protocol.handle() processed incoming data asynchronously.
> fix: data corruption in `protocol.handle`

- .devcontainer/devcontainer.json
- .devcontainer/on-create-command.sh
Update Codespaces creation command logic to use RBE instead of Goma.
At the moment, you'll still need to monitor the creation process and watch for the output of `e d rbe login` so that you can login and use the service:
```
Please visit https://auth.notgoma.com/rbe/8d716b0723ad1ed73a6d6388e5cbb66e6dfeea2b2810f1765c52ec1354a57d80 to obtain RBE authentication...
Authentication Status: Authenticated
Since:     2024-02-23 16:21:04 +0100 CET
Expires:   2024-05-23 17:21:04 +0200 CEST
Cluster:   rbe.notgoma.com
Principal: github/codebytere
Access:    Cache & Execute
```
However, even if it times out the fallback is to use `--no-remote` so the codespace shouldn't fail.
Confirmed success:
```console
Outcome: success User: builduser WorkspaceFolder: /workspaces/gclient/src/electron
devcontainer …
```
> build: fixup codespaces on-create

- docs/api/dialog.md
per https://github.com/electron/electron/issues/41914 the docs incorrectly stated that `filePath` would be `undefined` for canceled dialogs, but they are empty strings, this PR corrects that
fixes https://github.com/electron/electron/issues/41914
Notes: none
> docs: correct the return value for canceled showSaveDialog

- docs/tutorial/tutorial-6-publishing-updating.md
Replaced "Window" with "Windows" to fix typo in Tutorial document.
Notes: none
> docs: Windows typo in Tutorial document

- shell/app/electron_main_delegate_mac.mm
- shell/browser/api/electron_api_session.cc
- shell/browser/browser_linux.cc
- shell/common/mac/main_application_bundle.mm
Very small C++20 migration PR. Replaces `base::EndsWith(foo, base::CompareCase::SENSITIVE)` with `foo.ends_with()`.
Xref: https://issues.chromium.org/issues/40256235 upstream migration ticket
Notes: none
> refactor: replace base::EndsWith() with std::ends_with()

- .github/workflows/macos-build.yml
Incorporate https://github.com/electron/build-tools-installer/pull/30 for more durable build-tools pinning.
Notes: none
> build: use env var for build-tools pinning

- shell/browser/api/electron_api_base_window.cc
- shell/browser/api/electron_api_base_window.h
- shell/browser/api/electron_api_browser_window.cc
- shell/browser/api/electron_api_browser_window.h
Closes https://github.com/electron/electron/issues/41938.
Moves `setTitleBarOverlay` to BaseWindow.
Notes: Fixed an issue where `setTitleBarOverlay` didn't work as expected when called on `BaseWindow`.
> fix: `setTitleBarOverlay` should be implemented on `BaseWindow`

- script/release/notes/notes.js
- spec/release-notes-spec.ts
This PR fixes an issue that would appear when there were multiple Chromium stack upgrades between versions. The notes script did not correctly handle the comparisons needed to determine which stack upgrade superceded which. An example of the previous issue can be seen here: https://github.com/electron/electron/releases/tag/v29.1.1 lists Chromium 122.0.6261.95, however according to https://github.com/electron/electron/blob/v29.1.1/DEPS it's 122.0.6261.111.
Notes: None
> chore: fix notes stack updates

- shell/browser/ui/cocoa/electron_menu_controller.h
- shell/browser/ui/cocoa/electron_menu_controller.mm
Closes https://github.com/electron/electron/issues/41973.
Fixes an issue where `recentDocuments` wasn't populating properly after the ARC migration in https://github.com/electron/electron/commit/bbdd037219f81f8c11f4cd92239f15d5365ee905. This happened because the recent documents member became a member variable instead of a static item as it was previously, meaning it was getting clobbered. This fixes that.
Tested with https://gist.github.com/efaca06ece39c8c47ed9b2dae6c3f42e
Notes: Fixed an issue where `recentDOcuments` wasn't populating properly on macOS.
> fix: recentDocuments on macOS not working

- shell/browser/api/electron_api_web_contents_view.cc
- spec/api-web-contents-view-spec.ts
Closes https://github.com/electron/electron/issues/41941.
Fixes an issue where `document.requestFullscreen` didn't work when calling it from a `webContents` inside `WebContentsView`. This was happening because we weren't setting the owner window to the associated NativeWindow after the `WebContentsView` was added to one, and therefore the fullscreen transition wasn't being triggered.
Notes: Fixed an issue where `document.requestFullscreen` didn't work when calling it from a `webContents` inside `WebContentsView`.
> fix: `requestFullscreen` from `WebContentsView`

- patches/DirectXShaderCompiler/.patches
- patches/DirectXShaderCompiler/cherry-pick-bc18aec94c82.patch
- patches/angle/.patches
- patches/angle/cherry-pick-ba3b4e239620.patch
<details>
<summary>electron/security#494 - bc18aec94c82 from DirectXShaderCompiler</summary>
Replace dynamic_cast with virtual call (#6515)
Make TextDiagnosticPrinter::setPrefix a virtual function in base class
DiagnosticConsumer. This allows us to avoid using dynamic_cast in
BackendConsumer::DxilDiagHandler, required for codebases that do not
enable RTTI. This is also the only place in the codebase that uses RTTI
(AFAICT).
Bug: chromium:333420620
Change-Id: Ida73077f24fdb4b705b5d868b04ac6cfecb30327
Reviewed-on: https://chromium-review.googlesource.com/c/external/github.com/microsoft/DirectXShaderCompiler/+/5464347
Reviewed-by: dan sinclair <dsinclair@chromium.org>
Reviewed-by: David Neto <dneto@google.com>
</details>
<details>
<summary>electron/security#493 - ba3b4e239620 from …
> chore: cherry-pick 2 changes from 1-M124

- shell/app/electron_content_client.cc
- shell/browser/electron_browser_client.cc
- shell/renderer/renderer_client_base.cc
Because of upstream changes like [5293155: Move kPdfMimeType to //components/pdf/common/constants.h](https://chromium-review.googlesource.com/c/chromium/src/+/5293155), gn check currently fails if  the arg`enable_pdf_viewer = false`.  This PR fixes that gn check failure.
Notes: none
> chore: fixup gn check when enable_pdf_viewer is false

- spec/api-browser-window-spec.ts
- spec/disabled-tests.json
- spec/package.json
- spec/yarn.lock
Fixes https://github.com/electron/electron/issues/42005.
This PR disables the tests that use nut.js and removes the dependency. This is a short-term fix to unblock CI -- we should re-enable these tests once we find a replacement (*edit:* or once we work something out with Simon. Looks like he reach out to the Electron team via Discord saying he's happy to keep supporting Electron. :smile_cat:)
https://nutjs.dev/blog/i-give-up
> All of my packages around nut.js will cease to exist publicly on npm. Ready-to-use packages will only be available through the private nut.js package registry, which requires an active subscription to be used.
Notes: None.
> chore: disable tests that require nut.js

- patches/DirectXShaderCompiler/.patches
- patches/DirectXShaderCompiler/cherry-pick-bd7aa9779873.patch
- patches/chromium/.patches
- patches/chromium/cherry-pick-98bcf9ef5cdd.patch
<details>
<summary>electron/security#504 - 98bcf9ef5cdd from chromium</summary>
[M124][document pip] Don't assume the enter event window is a LocalDOMWindow
This CL changes DocumentPictureInPictureEvent to store a DOMWindow
instead of a LocalDOMWindow to prevent crashes when the window it gets
is actually a RemoteDOMWindow.
(cherry picked from commit 2314741cdf2c4a6e11234dda7006ec0dd9005bbb)
Bug: 335003891
Change-Id: I86a0ec5a89b51a26d5dd89559f86e6e4d6c3e8fe
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5467978
Commit-Queue: Tommy Steimel <steimel@chromium.org>
Reviewed-by: Frank Liberato <liberato@chromium.org>
Cr-Original-Commit-Position: refs/heads/main@{#1290122}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5477908
Auto-Submit: Tommy …
> chore: cherry-pick 2 changes from 2-M124

- docs/development/coding-style.md
Fixes outdated docs lint command in `coding-style.md`.
Notes: Fixed incorrect docs linting command in docs.
> docs: fix lint command

- patches/chromium/.patches
- patches/chromium/cherry-pick-c1f25647c2fc.patch
Cherry-pick https://source.chromium.org/chromium/chromium/src/+/c1f25647c2fcbf5e5a2d574feb284bc7284b944d to fix a regression caused by #41329 where the thumbnails are not captured at the requested resolution. (The patch was made in Chromium 123, so it's already in v30 and just needs to be backported to v29.)
Fixes #41630.
Notes: Fixed blurry thumbnails from desktop capturer on macOS.
> fix: cherry-pick fix thumbnail size patch for macOS

- patches/node/.patches
- patches/node/stream_do_not_defer_construction_by_one_microtick.patch
Closes https://github.com/electron/electron/issues/42041
Backports https://github.com/nodejs/node/pull/52005 to fix an issue where `fs.createWriteStream` could write out of order.
Notes: Fixed an issue where `fs.createWriteStream` could write out of order.
> fix: do not defer construction by one microtick in stream

- docs/api/base-window.md
- docs/api/browser-window.md
- docs/api/net.md
- docs/api/session.md
- docs/development/debugging-with-symbol-server.md
- docs/tutorial/esm.md
- docs/tutorial/tutorial-1-prerequisites.md
- docs/tutorial/tutorial-2-first-app.md
Ran through the gamut of `npx docusaurus-mdx-checker` for the Docusaurus v3 upgrade and this should clear the remaining issues:
1. `{` and `}` both need to be escaped as MDX >=2 supports curly brace JS expressions (ref: https://mdxjs.com/docs/what-is-mdx/#expressions)
2. MDX >=2 does not support GitHub-flavoured Markdown [autolinks](https://github.github.com/gfm/#autolink) such as `<https://electronjs.org>` (ref: https://docusaurus.io/blog/preparing-your-site-for-docusaurus-v3#bad-usage-of-gfm-autolink)
3. Putting `<details><summary>Summary here</summary>` doesn't work anymore in MDX >=2 for some reason and we need to add a line break now (ref: https://github.com/orgs/mdx-js/discussions/2241)
Notes: none
> docs: update formatting for mdx3 compatibility

- patches/chromium/.patches
- patches/chromium/a11y_avoid_clearing_resetting_focus_on_an_already_focus_event.patch
CL https://chromium-review.googlesource.com/c/chromium/src/+/5356613
Refs https://github.com/microsoft/vscode/issues/210842#issue-2254720002
Notes: [a11y] avoid clearing/resetting focus on an already focused element
> chore: cherry-pick 22871e619f from chromium

- .github/dependabot.yml
Fixes software supply chain safety warnings like at the bottom right of
https://github.com/electron/electron/actions/runs/8619491231
* [Keeping your actions up to date with Dependabot](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot)
* [Configuration options for the dependabot.yml file - package-ecosystem](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#package-ecosystem)
Notes: none
> ci: keep GitHub Actions up to date with GitHub's Dependabot

- patches/chromium/.patches
- patches/chromium/cherry-pick-013961609785.patch
Detect overflow in JPEG image size calculations.
Bug: 330756841
Change-Id: Ib30493152e08fd2347f76de276c5805d6fef9a7d
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5402199
Commit-Queue: John Stiles <johnstiles@google.com>
Cr-Commit-Position: refs/heads/main@{#1279376}
Notes: Backported fix for 330756841.
> chore: cherry-pick 013961609785 from chromium

- patches/angle/.patches
- patches/angle/cherry-pick-c67f290ef0f0.patch
<details>
<summary>electron/security#506 - c67f290ef0f0 from angle</summary>
M124: GL: Sync unpack state for glCompressedTexSubImage3D
Unpack state is supposed to be ignored for compressed tex image calls
but some drivers use it anyways and read incorrect data.
Texture3DTestES3.PixelUnpackStateTexSubImage covers this case.
Bug: chromium:337766133
Change-Id: Ic11a056113b1850bd5b4d6840527164a12849a22
Reviewed-on: https://chromium-review.googlesource.com/c/angle/angle/+/5498735
Commit-Queue: Shahbaz Youssefi <syoussefi@chromium.org>
(cherry picked from commit 1bb1ee061fe0bce322fb93b447a72e72c993a1f2)
Reviewed-on: https://chromium-review.googlesource.com/c/angle/angle/+/5518811
Commit-Queue: Srinivas Sista <srinivassista@chromium.org> …
> chore: cherry-pick 1 changes from 3-M124

- patches/devtools-frontend/.patches
- patches/devtools-frontend/cherry-pick-8a3bfd4b7403.patch
Add support of the Worklet target
This is in preparation for the back-end to report regular renderer
based worklets (such as CSS / Animation / Audio) as worklets rather
than workers. A sepratate target type from workers is needed since
unlike workers, these lack support for multiple domains, including
Network and Target.
Bug: 1517088
Change-Id: Id2919baaeec90c9259ace33e7249b5eccec031b7
Reviewed-on: https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/5183275
Reviewed-by: Danil Somsikov <dsv@chromium.org>
Commit-Queue: Danil Somsikov <dsv@chromium.org>
Auto-Submit: Andrey Kosyakov <caseq@chromium.org>
Notes: Backported fix for 1517088.
> chore: cherry-pick 8a3bfd4b7403 from devtools-frontend

- patches/chromium/.patches
- patches/chromium/cherry-pick-b2cc7b7ac538.patch
Viz: Tolerate SinkGroup destruction during submit
Fixed: 339266700
Change-Id: I8c0ea8c540948016346b00db64fe33260d2446f0
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5523748
Reviewed-by: Kyle Charbonneau <kylechar@chromium.org>
Reviewed-by: Jonathan Ross <jonross@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1298119}
Notes: Backported fix for 339266700.
> chore: cherry-pick b2cc7b7ac538 from chromium

- shell/browser/native_window_views.cc
- spec/api-browser-window-spec.ts
Closes https://github.com/electron/electron/issues/41956.
Refs: https://chromium-review.googlesource.com/c/chromium/src/+/4916277
The above CL changed `window.center()` behavior on Windows/Linux (which use `Widget`) such that the window is now centered relative to the parent window and not the full screen as is the expected behavior and the behavior on macOS. Chromium perceived this a bug, but it's important we maintain our end-user behavior consistency here as it's been this way for the lifetime of the method.
Tested with https://gist.github.com/yangannyx/277e71dc348b289cde39e94b4b59d683
cc @yangannyx
Notes: Fixed an issue where calling `window.center()` on Windows and Linux incorrectly centered the window.
> fix: `BrowserWindow.center()` should center relative to screen

- shell/browser/api/electron_api_view.cc
- spec/api-view-spec.ts
Fixes the following CHECK in [`View::AddChildViewAtImpl`](https://source.chromium.org/chromium/chromium/src/+/main:ui/views/view.cc;l=3071;bpv=1;bpt=1?q=AddChildViewAt):
```
[23853:0507/174950.101294:FATAL:view.cc(3081)] Check failed: view != this (0x130006c2000 vs. 0x130006c2000)You cannot add a view as its own child
```
and adds a test. Incidental to investigation of https://github.com/electron/electron/issues/41974
Notes: Fixes a crash in `addChildView` if a view is added as its own child.
> fix: CHECK when adding view as its own child

- shell/browser/api/electron_api_protocol.cc
- shell/browser/protocol_registry.cc
- shell/browser/protocol_registry.h
- shell/browser/ui/inspectable_web_contents.cc
- shell/common/api/electron_api_url_loader.cc
Fix a performance wart in `ProtocolRegistry`. The current workflow is to call `ProtocolRegistry::handlers().at(scheme)` after a safeguard check to `ProtocolRegistry::IsRegistered(scheme)`.  This workflow requires a redundant lookup for `scheme` and is also a minor demeter violation.
This PR replaces the methods `ProtocolRegistry::IsRegistered(scheme)` and `ProtocolRegistry::handlers(scheme)` with a new `ProtocolRegistry::FindRegistered(scheme) const` that returns a const pointer to the handler, or `nullptr` if none is found.
Notes: none
> perf: avoid protocol registry redundant lookup

- patches/devtools-frontend/.patches
- patches/devtools-frontend/cherry-pick-19a4eebd05a7.patch
Fix support for worklet targets
Bug: 327027138
Change-Id: I051565c591645f0a4ccc297825d299c0764501ca
Reviewed-on: https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/5367245
Reviewed-by: Danil Somsikov <dsv@chromium.org>
Commit-Queue: Andrey Kosyakov <caseq@chromium.org>
Notes: Backported fix for 327027138.
> chore: cherry-pick 19a4eebd05a7 from devtools-frontend

- docs/api/view.md
- shell/browser/api/electron_api_view.cc
- shell/browser/api/electron_api_view.h
- spec/api-view-spec.ts
- spec/api-web-contents-view-spec.ts
Closes https://github.com/electron/electron/issues/42077.
Closes https://github.com/electron/electron/issues/41974.
Closes https://github.com/electron/electron/issues/42061.
When the same view is added multiple times, we should match Chromium's behavior in [`View::AddChildViewAtImpl`](https://source.chromium.org/chromium/chromium/src/+/main:ui/views/view.cc;l=3070;bpv=1;bpt=1?q=View::AddChildViewAtImpl&sq=package:chromium&type=cs) and re-order the view such that the view becomes the topmost view. Also adds tests.
Notes: Fixed a crash when the same `WebContentsView` is added via `addChildView` multiple times.
> fix: View reordering on re-addition to same parent

- patches/v8/.patches
- patches/v8/cherry-pick-f320600cd1f4.patch
[wasm-gc] Only normalize JSObject targets in SetOrCopyDataProperties
Bug: 339458194
Change-Id: I4d6eebdd921971fa28d7c474535d978900ba633f
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/5527397
Reviewed-by: Rezvan Mahdavi Hezaveh <rezvan@chromium.org>
Cr-Commit-Position: refs/heads/main@{#93811}
Notes: Backported fix for 339458194.
> chore: cherry-pick f320600cd1f4 from v8

- patches/node/build_add_gn_build_files.patch
- patches/node/build_only_create_cppgc_heap_on_non-32_bit_platforms.patch
We were missing the `original-fs/promises` entrypoint that is lazy loaded via `cp.js`
Notes: `originalFs.promises.cp` now works
> fix: ensure originalFs.promises.cp works

- lib/browser/api/browser-view.ts
- shell/common/gin_converters/gfx_converter.cc
- spec/api-browser-window-spec.ts
Closes https://github.com/electron/electron/issues/42003.
Fixes the following issue when setting autoResize on a `BrowserView`:
This was happening because `setBounds` accepts a `gfx::Rect` and we were trying to pass double values to the width and height when resizing.
Notes: Fixes an error when calling `setAutoResize` on a `BrowserView`.
> fix: BrowserView autoresizing conversion error

- .github/workflows/issue-opened.yml
If "Electron Version" can be parsed by `semver` to a valid version on a new bug issue, and `${major}-x-y` exists as a label, add that label automatically. The call to `github.rest.issues.getLabel` is necessary to check if the label already exists because `github.rest.issues.addLabels` will create a label if it doesn't exist, which we don't want.
Notes: none
> ci: auto label bug issues with version label

- docs/fiddles/features/dark-mode/index.html
- docs/tutorial/dark-mode.md
The dark mode example had an extra `</body>` at end of the `index.html` file. The extra tag has been removed from the fiddle code as well as the documentation.
Notes: None
> docs: fixing typo in dark mode fiddle and doc

- shell/browser/extensions/electron_extension_system.cc
- shell/common/asar/archive.cc
- shell/common/gin_converters/net_converter.cc
- shell/common/gin_converters/value_converter.cc
Use `base::Value::TakeDict()`, `TakeList()`, and `TakeString()` where appropriate.
1. The docs recommend changing our current `std::move(value.Get*())` to `std::move(value).Take*()` for better build-time checks.
2. In some cases, e.g. when we're pulling data out of  a temporary `base::Value::Dict`, we can avoid extra work by `Take*()`ing objects directly from the temporary dict instead of copying them.
Description from [values.h code comments](https://chromium.googlesource.com/chromium/src/+/main/base/values.h#282):
>   // Transfers ownership of the underlying value. Similarly to `Get...()`
// variants above, fails with a `CHECK()` on a type mismatch. After
// transferring the ownership `*this` is in a valid, but unspecified, state.
// Prefer over `std::move(value.Get...())` so clang-tidy …
> refactor: use base::Value::Take*()

- shell/common/asar/archive.cc
- spec/api-autoupdater-darwin-spec.ts
- spec/asar-integrity-spec.ts
- spec/fixtures/apps/hello/hello.js
- spec/lib/codesign-helpers.ts
- spec/lib/fs-helpers.ts
- spec/node-spec.ts
- spec/package.json
- spec/yarn.lock
Trying to add some tests for some core fuses behavior
> test: add tests for electron fuses

- patches/chromium/fix_partially_revert_invalidate_focusring.patch
- #42126 and #42088 were recently merged and appear to have caused a need to update the patch added in #42126 
Notes: none
> chore: update patches after #42126 was merged

- patches/v8/.patches
- patches/v8/cherry-pick-b3c01ac1e60a.patch
[compiler] Don't build AccessInfo for storing to module exports
Bug: 340221135
Change-Id: I5af35be6ebf6a69db1c4687107503575b23973c4
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/5534518
Cr-Commit-Position: refs/heads/main@{#93872}
Notes: Backported fix for 340221135.
> chore: cherry-pick b3c01ac1e60a from v8

- script/spec-runner.js
Electron 30 CI runs on an older version of node that packager doesn't like, this just bypasses the engine check as it does actually work
Notes: none
> build: ignore node version mismatch for electron 30 tests

- .markdownlint.json
Follow-up to #42078 to enable the no autolinks rule which was meant to be part of that PR, but I borked a local rebase and it got dropped.
Notes: none
> chore: enable no autolink markdownlint rule

- lib/browser/api/web-contents.ts
- spec/api-web-contents-spec.ts
Refs https://github.com/electron/electron/issues/41577.
By default, properties added `using Object.defineProperty()` are not writable, enumerable, or configurable, so we don't need to specify `writable: false`. We also _do_ want to change the default enumerable value to `true` such that it shows up when calling `Object.getOwnPropertyNames`.
Notes: Fixed an issue where `webContents.navigationHistory` was not an enumerable property
> fix: `webContents.navigationHistory` should be enumerable

- shell/browser/ui/electron_desktop_window_tree_host_linux.cc
The frame view of the widget is an `ClientFrameViewLinux` instance only when both `frame` and `client_frame` booleans are set to `true`. Otherwise it is an instance of a different class and thus casting to `ClientFrameViewLinux` is incorrect and leads to crashes.
Fix: #41839
cc @VerteDinde @ckerr 
Notes: Fix crash on window maximize on X11
> fix: fix cast in ElectronDesktopWindowTreeHostLinux

- shell/browser/native_window_mac.mm
Fixes an issue caused by the chain of #40307 and #41750
Fixes https://github.com/electron/electron/issues/42157
With the new "only run this on non-panels" logic we can restore the exact same old codepath.
Notes: `BrowserWindow.focus()` now correctly restore focus to inactive apps on macOS
> fix: restore non-panel focus behavior

- shell/browser/native_window_views.cc
Closes https://github.com/electron/electron/issues/42194.
Follow-up to https://github.com/electron/electron/issues/42048. 
Fixes an issue where the window could be incorrectly centered in some circumstances. This was happening because we should be explicitly setting the parent to `nullptr` in `gfx::CenterAndSizeWindow` and were passing the HWND instead.
Notes: Fixes an issue where the window could be incorrectly centered in some circumstances when calling `BrowserWindow.center()`
> fix: `win.center()` on Windows

- shell/browser/ui/views/root_view.cc
- shell/browser/ui/views/root_view.h
Make the ownership / nullability contract for `RootView` fields a little stricter:
- [Use `raw_ref<T>` instead of `raw_ptr<T>`](https://chromium.googlesource.com/chromium/src/+/main/styleguide/c++/c++.md#non_owning-pointers-in-class-fields) for class fields that can never be `nullptr`
- Aggregate the `ViewTracker` directly since RootView already owns it, and its lifecycle is identical to the RootView, and the RootView header was already including the ViewTracker header
All reviews welcomed. CC @nornagon as most recent committer and @miniak for general C++ tidying :smile_cat: 
Notes: none.
> refactor: use raw_ref in RootView

- .github/workflows/macos-build.yml
As in title - cancel in-progress runs on new commits. Ensure concurrency group names are unique across workflows to avoid canceling in-progress jobs or runs from other workflows. 
Notes: none
> build: cancel in-progress runs on new commits

- docs/api/environment-variables.md
The LOC links don't work on the website and are brittler than just linking to the heading anchor directly.
notes: none
> docs: fix broken anchors

- patches/DirectXShaderCompiler/.patches
- patches/DirectXShaderCompiler/cherry-pick-2a434fd0af6b.patch
- patches/chromium/.patches
- patches/chromium/cherry-pick-03609e39be8c.patch
- patches/v8/.patches
- patches/v8/cherry-pick-6503a987d966.patch
<details>
<summary>electron/security#512 - 6503a987d966 from v8</summary>
[objects] Deal with large strings in NoSideEffectsErrorToString
If name is too big, StringBuilder will fail to even add
"<a very large string>" suffix.
In this case, we truncate name first.
Bug: 329699609
Change-Id: I6e4440c07eae84371f44b54f88127e2c70af0db5
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/5378286
Commit-Queue: Victor Gomes <victorgomes@chromium.org>
Reviewed-by: Patrick Thier <pthier@chromium.org>
Auto-Submit: Victor Gomes <victorgomes@chromium.org>
Cr-Commit-Position: refs/heads/main@{#92932}
</details>
<details>
<summary>electron/security#510 - 2a434fd0af6b from DirectXShaderCompiler</summary>
Fix invalid IR from scalarrepl-param-hlsl in ReplaceConstantWithInst (#6556) …
> chore: cherry-pick 3 changes from 0-M125

- shell/browser/native_window_mac.mm
This aligns our API usage with Chromium and ensures that windows shown inactive that were initially hidden actually get painted to.
Notes: Fixed issue where windows made visible with `showInactive` were blank
> fix: ensure showInactive actually shows

- shell/browser/api/electron_api_desktop_capturer.h
- shell/browser/api/electron_api_global_shortcut.h
- shell/browser/api/electron_api_view.h
- shell/browser/api/frame_subscriber.h
- shell/browser/api/gpuinfo_manager.h
- shell/browser/api/save_page_handler.h
- shell/browser/browser.h
- shell/browser/cookie_change_notifier.h
- shell/browser/electron_autofill_driver_factory.h
- shell/browser/hid/hid_chooser_controller.h
- shell/browser/serial/serial_chooser_controller.h
- shell/browser/ui/autofill_popup.h
- shell/browser/usb/usb_chooser_controller.h
- shell/browser/web_contents_zoom_controller.h
- shell/browser/web_view_guest_delegate.h
- shell/renderer/electron_autofill_agent.h
- shell/renderer/electron_render_frame_observer.h
- shell/renderer/pepper_helper.h
We have a lot of classes that inherit from upstream observer classes to manage internal state, e.g. our `AutofillDriverFactory`  inherits from `content::WebContentsObserver` so that it can know when to close popups.
Since `WebContentsObserver` inherits `AutofillDriverFactory` publicly, we are accidentally exposing a _lot_ of public API (it's a 900+ LOC class!) to `WebContentsObserver`'s clients. We shouldn't do that; it might accidentally get used.
This PR uses private inheritance instead..
Notes: none.
> refactor: prefer to inherit observer classes privately

- patches/v8/.patches
- patches/v8/cherry-pick-3e037e195e50.patch
[parser] Using FunctionParsingScope for parsing class static blocks
Class static blocks contain statements, don't inherit the
ExpressionScope stack.
Bug: 341663589
Change-Id: Id52a60d77781201a706fcf2290d7d103f39bed83
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/5553030
Cr-Commit-Position: refs/heads/main@{#94014}
Notes: Backported fix for 341663589.
> chore: cherry-pick 3e037e195e50 from v8

- docs/api/structures/web-preferences.md
- docs/api/webview-tag.md
Updated documentation of `webview-tag.md` to correct the type generated by the docs parser.
Fixes #42248 
Notes: Fixed the type of `WebviewTag.webpreferences` back to `string`
> fix: fixed the type of `WebviewTag.webpreferences`

- patches/node/enable_crashpad_linux_node_processes.patch
The old version of this patch has code that can call `options.env.foo = bar` even if  `options.env` is null.  This PR moves the pre-existing upstream Node line `const env = options.env || process.env` to be declared earlier in the function so that we can use `env` safely here.
CC @deepak1556, @mlaurencin since this upstreams a minor cleanup from the Microsoft build's patchset
CC @VerteDinde -- Keeley, I can't tell if you wrote the patch but your name is in the `From:` header so you're a stakeholder :smile_cat: 
Notes: none
> fix: potential null dereference in normalizeSpawnArguments() patch

- CODE_OF_CONDUCT.md
- README.md
- docs/api/app.md
- docs/api/auto-updater.md
- docs/api/content-tracing.md
- docs/api/environment-variables.md
- docs/api/extensions.md
- docs/api/ipc-renderer.md
- docs/api/net.md
- docs/api/protocol.md
- docs/api/session.md
- docs/api/web-contents.md
- docs/api/web-frame-main.md
- docs/breaking-changes.md
- docs/development/coding-style.md
- docs/development/source-code-directory-structure.md
- docs/tutorial/application-debugging.md
- docs/tutorial/application-distribution.md
- docs/tutorial/asar-archives.md
- docs/tutorial/code-signing.md
- docs/tutorial/launch-app-from-url-in-another-app.md
- docs/tutorial/notifications.md
Due to a bug in Docusaurus 3 (https://github.com/facebook/docusaurus/issues/9048), having links on multiple lines will break relative linking in the website build process.
```markdown
[This link will not
work properly in Docusaurus 3](https://electronjs.org)
```
This PR changes some whitespace around to fix all instances of this case in the Electron docs. These instances were vetted with https://github.com/electron/lint-roller/commit/f68f4691a17876787749d120c0c4185675b9dcae (thanks @dsanders11!), which will be applied to this repository in a separate PR.
Notes: none
> docs: ensure all links are on a single line

- shell/browser/native_window_mac.mm
The new activate API on macOS is pretty bad, we should just keep using the old API. Similar to #42180. Restores non-panel behavior to pre-panel support.
Notes: BrowserWindow.show() now correctly restores focus to inactive apps on macOS
> fix: restore original BrowserWindow.show() behavior

- docs/tutorial/notifications.md
Fix notification-spec link to link to the waybak machine instead of to a broken page
Notes: Fix notification-spec link in the example docs. Fixes https://github.com/electron/electron/issues/42240
> docs: fix broken notification-spec markdown link

- build/args/all.gn
Bumps Electron's NMV to 125. 125 was reserved during the last release cycle here: https://github.com/nodejs/node/pull/52379 but a bump commit like this was not made before 31-x-y was cut. (See https://github.com/electron/electron/pull/39538 for a previous example of this process).
cc @miniak 
Notes: none
> build: update NMV to 125

- docs/api/web-contents-view.md
- shell/browser/api/electron_api_web_contents_view.cc
- spec/api-web-contents-view-spec.ts
Closes https://github.com/electron/electron/issues/42054.
This PR enables `WebContentsView` to accept existing `webContents` object in order to be able to properly handle popups. This issue is described here: #42054.
Notes: Extended `WebContentsView` to accept pre-existing `webContents` object.
> feat: Allow WebContentsView to accept webContents object.

- lib/browser/api/dialog.ts
Closes https://github.com/electron/electron/issues/42225.
Fixes an issue where dialogs did not work if they were parented to a BaseWindow and not a BrowserWindow. The converter is for BaseWindows, so there's no reason we can't use BaseWindows here internally. We should consider checking more thoroughly what actually requires a BrowserWindow now and updating it, but in the interest of keeping this semver/patch
I held off.
Notes: Fixed an issue where dialogs did not work if they were parented to a BaseWindow and not a BrowserWindow.
> fix: dialogs should work with BaseWindows internally

- .github/workflows/config/evm.mas.json
- .github/workflows/macos-build.yml
- .github/workflows/macos-publish.yml
- script/actions/move-artifacts.sh
- script/actions/restore-artifacts.sh
- script/lib/azput.js
- script/release/ci-release-build.js
- script/release/find-github-release.js
- script/release/prepare-release.js
- script/release/publish-to-npm.js
- script/release/release.js
- script/release/uploaders/upload-to-github.ts
- script/release/uploaders/upload.py
Follow up: https://github.com/electron/electron/pull/41812
Pairs with: https://github.com/electron/sudowoodo/pull/269
This PR continues Electron's migration to use GitHub Actions for release builds and CI runs with @codebytere. The intention of this PR is to set up a publish-macos job that will run alongside our regularly scheduled nightlies.
In the short-term, this job will dump uploads into a private test repo in the Electron workspace, as well as a private test bucket in Azure. In the long-term, once this job has proven to work reliably with Sudowoodo and not cause additional issues, we'll remove the CircleCI publish-macos job and replace it with the GitHub Actions jobs. Once the publish jobs prove reliable and stable, we can also transition our CI runs to using the build-mac GitHub …
> build: add GitHub Actions publishing pipeline for macOS 

- shell/browser/usb/electron_usb_delegate.cc
- shell/browser/usb/electron_usb_delegate.h
- spec/chromium-spec.ts
Closes https://github.com/electron/electron/issues/42340.
Fixes an issue where some calls to WebUSB methods could crash. This could happen when the current partition was in-memory, as by default Chromium (and the spec) [do not support this](https://source.chromium.org/chromium/chromium/src/+/main:components/keyed_service/content/browser_context_keyed_service_factory.cc;l=64;drc=ac83a5a2d3c04763d86ce16d92f3904cc9566d3a;bpv=1;bpt=1). This pulls in CL:4506353 to ensure cases with no chooser context are handled appropriately.
Notes: Fixes an issue where some calls to WebUSB methods could crash.
> fix: WebUSB should not crash when using in-memory partitions

- build/args/all.gn
This PR bumps the NMV to 128 for Electron 32. ~Please do not merge until the corresponding Node PR is merged.~ Node PR is merged.
Node PR: https://github.com/nodejs/node/pull/53203
Notes: none
> build: bump NMV to 128 for Electron 32

- shell/browser/native_window_mac.h
- shell/browser/native_window_mac.mm
Fixes https://github.com/electron/electron/issues/41979 in Electron 30.
In Electron 30 setting a BrowserWindow's vibrancy on macOS will often cause the entire contents of the screen to have the vibrancy effect, wiping all actual window contents. This traces back to https://github.com/electron/electron/pull/35658 which replaced BrowserViews with WebContentsViews that use Chromium's Views API. We can fix this by inserting the vibrant view into Chromium's Views hierarchy by wrapping the vibrant view in a NativeViewHost.
The vibrancy setting creates a native macOS NSVisualEffectView that is inserted as a direct child of the window's contentView [here](https://github.com/electron/electron/blob/85df2a86dda7b99af99310566601ee04b72e55c8/shell/browser/native_window_mac.mm#L1459-L1461). Prior to …
> fix: vibrant view is inserted into Views API hierarchy

- shell/renderer/api/electron_api_web_frame.cc
Cleanup PR that moves the `WebFrameRenderer` into an anonymous namespace. It doesn't need to be public since it's only used by `shell/renderer/api/electron_api_web_frame.cc`, and making it private shrinks the object file.
Before:
```sh
$ du --bytes out/Testing/obj/electron/electron_lib/electron_api_web_frame.o
958224	out/Testing/obj/electron/electron_lib/electron_api_web_frame.o
$ nm out/Testing/obj/electron/electron_lib/electron_api_web_frame.o | c++filt | rg WebFrameRenderer | wc --lines
294
```
After:
```sh
$ du --bytes out/Testing/obj/electron/electron_lib/electron_api_web_frame.o
870784	out/Testing/obj/electron/electron_lib/electron_api_web_frame.o
$ nm out/Testing/obj/electron/electron_lib/electron_api_web_frame.o | c++filt | rg WebFrameRenderer | wc --lines
179
````
All reviews …
> refactor: move WebFrameRenderer into an anonymous namespace

- .github/workflows/macos-build.yml
This PR increases the fetch-depth in checkout, and fetches tags as well as commit history.
~It also re-enables SSH debugging with tmate, so it's easier for us to SSH into the Actions runner while debugging.~ Removed this functionality in this PR
Notes: none
> build: increase fetch-deps

- shell/browser/api/electron_api_cookies.cc
- spec/api-net-session-spec.ts
- spec/api-session-spec.ts
Closes https://github.com/electron/electron/issues/42342.
Improves cookie error messages and adds some safeguards to ensure our messages are kept up to date.
Notes: Improved error messages when `ses.cookies.set` fails.
> refactor: improve cookie failure rejection messages

- shell/common/platform_util_mac.mm
Closes https://github.com/electron/electron/issues/42376.
Corrects check from `loginService` -> `loginItemService`.
Notes: Fixed an issue where `app.setLoginItemSettings` incorrectly checked against `loginItemService`
> fix: `loginService` -> `loginItemService`

- docs/api/app.md
- shell/browser/browser.h
- shell/browser/browser_mac.mm
- shell/browser/mac/electron_application_delegate.mm
Closes https://github.com/electron/electron/issues/42302.
Re-adds `wasOpenedAtLogin` functionality to check whether or not an app was launched as a login item on macOS. I'd previously thought this wasn't possible when I switched our API base over to SMAppService, but @nikwen brought my attention in the above linked issue to a supported way to determine the information.
Notes: Re-adds functionality to check whether or not an app was launched as a login service on macOS.
> fix: restore `wasOpenedAtLogin` functionality

- patches/chromium/feat_add_support_for_missing_dialog_features_to_shell_dialogs.patch
- shell/browser/ui/file_dialog_linux.cc
Closes https://github.com/electron/electron/issues/42303.
Fixes support for multiple folder/file selection in `//shell_dialogs` portal implementation as well as in the KDE implementation.
Notes: Fixed support for multiple folder/file selection in //shell_dialogs portal implementation.
> fix: multiple selection in `//shell_dialogs` Portal/KDE implementations

- .markdownlint-cli2.jsonc
- docs/api/structures/trace-config.md
- docs/tutorial/security.md
- docs/tutorial/using-native-node-modules.md
- package.json
- yarn.lock
Follow-up to #42235 which enforces no newlines in link text. The rule is more strict (which is why there's a few additional changes for a clean lint).
Not sure what's up with the seemingly unrelated `yarn.lock` change, I'm using Yarn 1.22.22.
Notes: none
> chore: update @electron/lint-roller to 2.2.0

- script/lib/util.py
- script/release/uploaders/upload.py
Small tweaks to the upload script to fix several defaults founds during the GHA migration
Notes: none
> build: fix upload script defaults

- shell/browser/api/electron_api_web_contents.cc
- shell/browser/browser_linux.cc
- shell/browser/electron_browser_main_parts_linux.cc
- shell/common/gin_converters/net_converter.cc
Similar to #42369.
This PR takes impl classes that were accidentally made public and puts them in an anonymous namespace. This improves the compiler's ability to optimize the code and make smaller object files.
File | Size (bytes) Before | Size (bytes) After | Diff |
----|---:|---:|---:|
`net_converter.o` | 559,904 | 545,192 | -14,712
`electron_api_web_contents.o` | 3,780,168 | 3,772,112 | -8,056
`browser_linux.o` | 138,496 | 137,416 | -1,080
`electron_browser_main_parts_linux.o` | 46,312 | 45,312  | -1,000
Saving about 25K bytes. Nothing earth-shattering, but free is free -- we get this just by moving a few braces to the right place  :smile_cat: 
All reviews welcomed. CC @samuelmaddock and @codebytere, who both reviewed 42369.
Notes: none.
> refactor: move impl classes into unnamed namespaces

- shell/browser/javascript_environment.cc
Closes https://github.com/electron/electron/issues/42394.
Fixes an issue where bad flags passed via `--js-flags` crashed Electron. This happened because invalid args passed to `SetFlagsFromString` will cause all further flags to be ignored, so when a user passed a bad flag the freeze flags argument would be ignored.
Notes: Fixed an issue where bad flags passed via `--js-flags` could cause a crash.
> fix: bad js-flags shouldn't crash the app

- docs/api/structures/cpu-usage.md
- shell/browser/api/electron_api_app.cc
- shell/common/api/electron_bindings.cc
- spec/api-app-spec.ts
- spec/api-process-spec.ts
This allows apps to measure their CPU usage over any given period without worrying about other calls affecting the output, as they would with `percentCPUUsage`.
Haven't run the tests because I couldn't get the build process to cooperate locally, but this worked fine and returned results in line with expectations on a CI build I ran.
Notes: Added `cumulativeCPUUsage` to AppMetrics and CPUUsage
> feat: add cumulativeCPUUsage to AppMetrics and CPUUsage

- DEPS
Add a boolean variable to allow sysroot installation hooks to be skipped.  By default they are not skipped, so this doesn't affect any workflows in `electron/electron`. These sysroot hooks are new in Electron 31, having landed in https://github.com/electron/electron/pull/41868/commits/2d43e1e787a17ab7a949d8a04a79b4675ba6b32f.
To be fair, this is to solve a pretty specific use case in Microsoft's downstream build: we have a prebuilt Electron executable and want to test it with the `spec/` directory of a specific commit we obtain with `gclient sync`. We also have sequence-specific steps in our own DEPS hooks. There are goofier workarounds we could do all-downstream if this PR is rejected, but this is the simplest fix and is relatively unobtrusive to `e/e`.
Notes: none.
> build: add an option to skip the install-sysroot hooks

- .github/workflows/macos-pipeline.yml
Adds the ffmpeg generation for the MAS publish job as well as Darwin.
Notes: none
> build: build ffmpeg on MAS publish

- lib/node/init.ts
- shell/renderer/electron_renderer_client.cc
Closes https://github.com/electron/electron/issues/42381.
Refs https://github.com/electron/electron/pull/41710
Fixes an issue where `fetch` dependent interfaces in Node.js were not defined when `nodeIntegration` was enabled in some circumstances. I handled this partially in https://github.com/electron/electron/pull/41710/commits/9e4ae9c040763ff84e356c2bffd3076d9d5ad7b2, but the problem extended slightly further and the same approach needed to be taken for `FormData`, `Request`, etc.
Notes: Fixed an issue where `fetch` dependent interfaces in Node.js were not defined when `nodeIntegration` was enabled in some circumstances.
> fix: missing `fetch`-dependent interfaces in Node.js

- shell/browser/hid/electron_hid_delegate.cc
- shell/browser/usb/electron_usb_delegate.cc
Refs https://github.com/electron/electron/issues/42340.
Follow-up to https://github.com/electron/electron/pull/42347.
We also need to ensure we're not calling `Observe` on the `base::ScopedObservation` when the BrowserContext is in-memory.
Notes: Fixed an issue where `navigator.usb.getDevices()` could crash in some circumstances
> fix: don't observe WebUSB for in-memory partitions

- docs/tutorial/security.md
Fixed faulty :::info admonitions resulting in nested info boxes in security.md:
Tested locally with electron/website
Notes: none
> docs: fix info admonitions in security.md

- docs/tutorial/mac-app-store-submission-guide.md
I was revisiting this document as part of https://github.com/electron/osx-sign/pull/320.
Notable changes:
* Focus the information on MAS distributions.
* Refactor `@electron/osx-sign` APIs to use JS API.
* Remove mention of `--no-gatekeeper-assess`, which doesn't exist anymore.
* Update links.
* Hide manual steps behind details/summary HTML elements.
* Add missing information detailed in https://github.com/electron/osx-sign/wiki/3.-App-Sandbox-and-Entitlements
Notes: none
> docs: clean up MAS submission guide

- .github/workflows/macos-build.yml
- .github/workflows/macos-pipeline.yml
- script/azure_cli_deb_install.sh
Modifies the way we're handling the GHA MacOS cache to use the Linux AKS NFS image for caching.
Notes: none
> build: use the linux aks for macos checkout/cache

- docs/tutorial/web-embeds.md
Replaces a reference to a deprecated API. Also adds an additional link to the new API.
CC: @electron/docs 
Notes: none
> docs(web-embeds): replace BrowserView ref with WebContentsView

- .github/workflows/linux-build.yml
- .github/workflows/linux-pipeline.yml
- .github/workflows/macos-pipeline.yml
A follow up to #42447, this PR modifies the Linux Build GHA job to use the AKS disk cache, rather than using blob storage upload and download.
Notes: none
> build: save/restore cache on Linux builds

- .github/workflows/linux-pipeline.yml
- .github/workflows/macos-pipeline.yml
Does what it says on the tin - moves Hunspell from Mac to Linux, only runs it one time.
Notes: none
> build: move hunspell generation to Linux

- docs/api/dock.md
The link seems to have changed. This is the up to date link.
Fix state link.
Notes: none
> docs: fix the Apple HIG link for Dock context menu

- .github/actions/build-electron/action.yml
The PR adds the needed x64 v8_toolchain to compile mksnapshot to the correct arch
Notes: none
> build: add `v8_toolchain` to darwin/x64

- script/release/uploaders/upload.py
Unblocked publish linux; moves us back to the deprecated datetime.datetime.utcnow() method. We can update this once we move the Linux AKS runners to Python 3.11 or higher.
Notes: none
> build: fix datetime module for Linux Publish

- .github/workflows/linux-publish.yml
- .github/workflows/macos-publish.yml
This PR passes in the `gclient-extra-args` to the checkout job as an input, and then adds it to the environment so it can be used for the checkout build.
Notes: none
> build: remove gclient-extra-args from publish jobs

- .github/workflows/pipeline-segment-node-nan-test.yml
- script/actions/restore-artifacts.sh
Use `BUILD_TYPE` from env instead of setting it in `restore-artifacts.sh`. Fixes issue with mas src artifacts being incorrectly  extracted.
https://github.com/electron/electron/actions/runs/9510478302/job/26216072597 shows error fixed
Notes: none
> build: use `BUILD_TYPE` from env

- .circleci/config/base.yml
- .github/actions/checkout/action.yml
- .github/workflows/config/gclient.diff
- .github/workflows/pipeline-segment-electron-build.yml
- .github/workflows/pipeline-segment-electron-test.yml
- .github/workflows/pipeline-segment-node-nan-test.yml
This PR reverts commit a0a8bd2222176cec3b4131100937ffda2cf4df7c, as it's still need it for publish.
Notes: none
> build: revert removal of CIPD patch from depot tools

- .github/workflows/linux-publish.yml
- .github/workflows/macos-publish.yml
- .github/workflows/pipeline-segment-electron-build.yml
Moves Mac Publish & Linux Publish to use the `production-release` environment for secrets.
Notes: none
> build: add production-release environment to publish jobs

- .github/workflows/build.yml
- .github/workflows/pipeline-segment-electron-test.yml
This is kinda a bug in GitHub Actions itself, but it mounts a not-arm version of node20 on arm runners because it mounts based on host not based on container. For now we can just be kind and give actions _our_ node 20 which we know works 😆 This gets the linux CI green across the board
Notes: none
> build: fix GHA arm tests

- script/lib/util.py
Fixes the following:
```
✖ python3 script/run-clang-format.py -r -c --fix:
run-clang-format.py: error: clang-format exited with code 127: 'shell/common/platform_util_mac.mm'
/bin/sh: /Users/codebytere/Developer/electron-gn/src/buildtools/mac/format/clang-format: No such file or directory
husky - pre-commit hook exited with code 1 (error)
```
Notes: none
> build: fix clang format location helper

- script/release/ci-release-build.js
The 32-x-y branch point happened during the GitHub Actions migration - some of the work merged into main was included, but there have been several changes made in main that have not yet been backported. This PR disables GitHub Actions in 32-x-y until we have a chance to backport the additional changes.
Notes: none
> build: disable GitHub Actions in 32-x-y

- .github/actions/checkout/action.yml
- .github/workflows/build.yml
- .github/workflows/pipeline-electron-build-and-test.yml
- .github/workflows/pipeline-electron-docs-only.yml
- .github/workflows/pipeline-electron-lint.yml
- .github/workflows/pipeline-segment-electron-build.yml
- .github/workflows/pipeline-segment-electron-gn-check.yml
- .github/workflows/pipeline-segment-electron-test.yml
- .github/workflows/pipeline-segment-node-nan-test.yml
- script/actions/move-artifacts.sh
- spec/api-app-spec.ts
- spec/api-protocol-spec.ts
- spec/chromium-spec.ts
- spec/lib/codesign-helpers.ts
The part that actually fixes this is `Add TCC permissions on macOS`. Other parts included in this PR are:
* Running x64 tests on an x64 vm (instead of arm64 under rosetta)
* Running tests on small arm64 vms instead of chonky bois
* Adding `--frozen-lockfile` everywhere
* Removing `src/electron` from test artifacts
* Sharding macOS tests across two runners
Notes: none
> build: fix macOS tests on GHA

- docs/api/command-line-switches.md
In support of https://github.com/electron/website/pull/575. A change in Docusaurus is now trying to validate this URL (arguably a bug), so use backticks around it to sidestep that behavior.
Notes: none
> docs: add backticks around example URL

- spec/api-content-tracing-spec.ts
The contentTracing tests have been timing out in WOA more frequently leading to significant flaky runs.  This PR updates the timeout on those tests to resolve that flakiness.
Notes: none
> test: use longer timeout on contentTracing tests on WOA

- shell/common/platform_util_mac.mm
Seeing some failures in SMApp service setting in macOS tests - improve error output by logging the error's text even if it's not a recognized service management error. Before it basically logged a redundancy:
```
"Unable to set login item: Failed to register the login item"
```
Notes: none
> chore: improve error message on failed SMApp register/unregister

- .github/workflows/auto-close-pull-request.yml
Some automation to close non-maintainer PRs that touch lockfiles, per [our contribution policy](https://github.com/electron/electron/blob/main/CONTRIBUTING.md#dependencies-upgrades-policy).
Carves out exclusions for bot PRs (to allow for Dependabot) and draft PRs (which our policy says we allow in certain circumstances).
Notes: none
> ci: auto close non-maintainer PRs that touch lockfiles

- .github/workflows/pipeline-segment-electron-build.yml
- .github/workflows/pipeline-segment-electron-gn-check.yml
Currently `linux-arm` is failing on publish with `ld.lld: error: output file too large: 5118387152 bytes`. @jkleinsc found this issue where we need to set a symbol level to 1 for 32 bit releases because of https://crbug.com/648948. This PR correctly sets the symbol level for release builds.
Notes: none
> build: add symbol_level=1 to GN_BUILDFLAG_ARGS on release

- shell/browser/api/message_port.cc
- shell/services/node/parent_port.cc
- spec/api-utility-process-spec.ts
- spec/fixtures/api/utility-process/non-cloneable.js
Closes https://github.com/electron/electron/issues/42373. 
We need to return early if `electron::SerializeV8Value`, as that means an exception has occurred and should be surfaced to the user.
Takes the same approach as similar apis:
- https://github.com/electron/electron/blob/7f3dc7d4ceab7c33656ccb204a9bb7eb06821559/shell/browser/api/electron_api_utility_process.cc#L298-L302
- https://github.com/electron/electron/blob/1bfd3e0631a00a4940d7ce89bebb515ad7e519ca/shell/browser/api/electron_api_web_frame_main.cc#L244-L248
Notes: Fixed an issue where MessagePorts could close unexpectedly with non-cloneable objects sent via `postMessage`.
> fix: MessagePort closing unexpectedly with non-cloneable objects

- .github/workflows/pipeline-segment-electron-test.yml
- spec/lib/codesign-helpers.ts
Re-enables self-certified codesigning on macOS an associated tests. It continues to fail mysteriously on arm64 - but we weren't running this on arm64 in Circle either so let's at least bring it back on x64.
Successful build: https://github.com/electron/electron/actions/runs/9572243925
Notes: none
> build: re-enable self-cert codesigning on x64 macOS

- .github/actions/build-electron/action.yml
- .github/workflows/build.yml
- .github/workflows/pipeline-electron-build-and-test-and-nan.yml
- .github/workflows/pipeline-electron-build-and-test.yml
- .github/workflows/pipeline-segment-electron-build.yml
- .github/workflows/pipeline-segment-electron-gn-check.yml
- .github/workflows/pipeline-segment-electron-test.yml
This PR adds the Linux Address Sanitized (ASan) build to GitHub Actions. It also adds a verify check for mksnapshot and chromedriver to all builds outside of the ASan build.
Notes: none
> build: Add ASan Linux build to Actions build/test

- lib/worker/init.ts
- shell/renderer/web_worker_observer.cc
- spec/chromium-spec.ts
- spec/fixtures/pages/worker-fetch.html
- spec/fixtures/workers/worker_node_fetch.js
- spec/node-spec.ts
Closes https://github.com/electron/electron/issues/42577.
Addresses missing fetch-dependent interfaces in Web Workers using the same approach as in the renderer when `nodeIntegrationInWorker` is enabled. Also adds tests.
Notes: Fixed an issue where `fetch`-dependent interfaces could be missing in Web Workers with `nodeIntegrationInWorker` enabled.
> fix: fetch-dependent interfaces in Web Workers

- patches/config.json
- patches/libaom/.patches
- patches/libaom/encode_api_test_add_repro_for_chromium_339877165.patch
- patches/libaom/update_codec_config_after_svc_scale_controls.patch
* d3cc351e0294 from libaom
* ad697557950c from libaom
Notes:
* Security: backported fix for CVE-2024-5493.
> chore: [30-x-y] cherry-pick 2 changes from 3-M125

- patches/DirectXShaderCompiler/.patches
- patches/DirectXShaderCompiler/cherry-pick-93c3cf1c787f.patch
- patches/v8/.patches
- patches/v8/cherry-pick-8b400f9b7d66.patch
- patches/v8/cherry-pick-ba6cab40612d.patch
<details>
<summary>electron/security#537 - 8b400f9b7d66 from v8</summary>
Merged: [wasm] Enforce maximum number of canonicalized types
Storing canonical indices in ValueTypes doesn't work well if the
canonical index is too large.
Fixed: 344608204
(cherry picked from commit 422cdc5eddcadb53b8eafb099722fb211a35739e)
Change-Id: Id281d6a38e8f2c64c42352f2d3dd3df54e289525
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/5625825
Auto-Submit: Jakob Kummerow <jkummerow@chromium.org>
Commit-Queue: Jakob Kummerow <jkummerow@chromium.org>
Reviewed-by: Matthias Liedtke <mliedtke@chromium.org>
Commit-Queue: Matthias Liedtke <mliedtke@chromium.org>
Cr-Commit-Position: refs/branch-heads/12.6@{#30}
Cr-Branched-From: 3c9fa12db3183a6f4ea53d2675adb66ea1194529-refs/heads/12.6.228@{#2} …
> chore: cherry-pick 3 changes from 1-M126

- docs/tutorial/asar-integrity.md
This PR fixes a small typo that causes a rendering issue on the ASAR integrity page:
Notes: none
> docs: fix typo in ASAR integrity docs

- script/lint.js
Sample error:
```js
electron on git:roller/chromium/main ❯ node ./script/lint.js --patches
TypeError: Cannot read properties of null (reading '2')
at /Users/codebytere/Developer/electron-gn/src/electron/script/lint.js:256:33
at Array.map (<anonymous>)
at Object.run (/Users/codebytere/Developer/electron-gn/src/electron/script/lint.js:253:53)
at main (/Users/codebytere/Developer/electron-gn/src/electron/script/lint.js:469:20)
```
Notes: none
> build: account for `subjectAndDescription` null in patch linting

- patches/chromium/.patches
- patches/chromium/x11_fix_crash_when_randr_getmonitors_fails.patch
Backports https://chromium-review.googlesource.com/c/chromium/src/+/5324886
Refs https://github.com/microsoft/vscode/issues/215924
Notes: fix startup crash on linux when obtaining display info with x11 backend
> chore: cherry-pick d18460a2 from chromium

- docs/api/safe-storage.md
Improved `safeStorage` security semantics documentation
Notes: none
> docs: clarify security semantics of safeStorage

- .github/actions/build-electron/action.yml
- .github/workflows/linux-publish.yml
- .github/workflows/pipeline-segment-electron-build.yml
This PR strips the Linux binaries on release, so they should stay around ~100 MB.
Before: https://github.com/electron/electron/actions/runs/9683327107
After: https://github.com/electron/electron/actions/runs/9687839988
Notes: none
> build: strip linux release binaries

- shell/browser/ui/file_dialog_linux.cc
Closes https://github.com/electron/electron/issues/42621.
Fixes an issue where control could fail to return properly after saving a dialog using showSaveDialogSync on Linux.
Tested with https://gist.github.com/mpolk/2cf36a722696695b6e0107a2250c8ccc
Notes: Fixed an issue where control could fail to return properly after saving a dialog using showOpenDialogSync on Linux.
> fix: param passed to `showSaveDialogSync` on Linux

- patches/chromium/feat_add_support_for_missing_dialog_features_to_shell_dialogs.patch
Refs https://github.com/microsoft/vscode/issues/213780.
Fixes an issue where the user-specified default path did not take the expected effect when using XDG Portal unless the user was using a save dialog.
This was happening because Chromium's XDG Portal dialog implementation only set the default path in a save dialog context. Fix this by taking it into account for all dialog types.
Notes: Fixes an issue where the user-specified default path did not work in some circumstances when using Linux dialogs.
> fix: `defaultPath` should apply on all dialog types in Linux Portal

- .github/actions/build-electron/action.yml
We have `target-arch` as an input, so we should be consistent about usage even if we also have `TARGET_ARCH` as an env var.
Notes: none
> build: use inputs for target_arch in build

- patches/DirectXShaderCompiler/.patches
- patches/DirectXShaderCompiler/cherry-pick-771e74ab497d.patch
- patches/DirectXShaderCompiler/cherry-pick-8f07d39227f6.patch
- patches/DirectXShaderCompiler/cherry-pick-b3c64851765c.patch
- patches/angle/.patches
- patches/angle/m126_vulkan_disable_vk_ext_shader_stencil_export_on_swiftshader.patch
- patches/v8/.patches
- patches/v8/merged_wasm_add_missing_type_canonicalization_for_exceptions_js.patch
* 5d4df51d1d7d from angle
* 771e74ab497d from DirectXShaderCompiler
* 8f07d39227f6 from DirectXShaderCompiler
* b3c64851765c from DirectXShaderCompiler
* d5217a718925 from v8
Notes:
* Security: backported fix for CVE-2024-6291.
* Security: backported fix for CVE-2024-6293.
* Security: backported fix for CVE-2024-6290.
* Security: backported fix for CVE-2024-6292.
* Security: backported fix for chromium:346197738.
> chore: cherry-pick 5 changes from 2-M126

- .circleci/config/jobs/lint.yml
- .github/workflows/pipeline-electron-lint.yml
- script/lib/util.py
- script/run-clang-format.py
- script/run-gn-format.py
Fixes the clang-format binary path, h/t to @codebytere and @dsanders11 for the help!
Notes: none
> build: fix clang format/lint

- .circleci/config/base.yml
On June 28, CircleCI is deprecating and removing the macos.x86.medium.gen2 executor. This PR removes the executor from CI, both build and release jobs.
Notes: none
> build: remove MacOS x64 from CircleCI

- lib/browser/api/browser-window.ts
- spec/api-browser-view-spec.ts
fixes: https://github.com/electron/electron/issues/42637
- As highlighted in the [issue](https://github.com/electron/electron/issues/42637), prior to v30, when setting a view to `setTopBrowserView`, the view would focus correctly, and that is because it's using the [macOS view ordering APIs](https://github.com/electron/electron/commit/15c60143241c7d0335f3bc8c722054ce6b8a9481#diff-f9d7ef71aadb519c42f18e9c0170137f634f267d72036ab62c3c9e4548c266e0L1404) to reorder the view to the top without reseting any state.
- With the new WebContentView changes in v30, we updated our implementation of `setTopBrowserView` to:
```
BrowserWindow.prototype.setTopBrowserView = function (browserView: BrowserView) {
if (browserView.ownerWindow !== this) { throw new Error('Given BrowserView is not attached to the …
```
> fix: setTopBrowserView focus issue with reordering

- docs/api/web-contents.md
This PR fixes the wording on the `isBeingCaptured` documentation
Notes: none
> docs: grammar fix in isBeingCaptured docs

- shell/browser/api/electron_api_web_request.cc
- shell/browser/api/electron_api_web_request.h
- spec/api-web-request-spec.ts
Closes https://github.com/electron/electron/issues/42149.
Fixes an issue where Chromium could crash on a dangling unretained pointer in one of several webRequest functions. This was happening as a result of the fact that we had outstanding blocking requests continue to reference state owned by `ProxyingWebsocket` and `ProxyingURLLoaderFactory` after the requests were destroyed.
This had been going on for a few years, and was likely leading to some ongoing memory issues. To fix this, we need to ensure that all state is cleaned up in `OnRequestWillBeDestroyed`. I chose to create a new BlockedRequest struct to do so, which approximates the approach that [upstream takes](https://source.chromium.org/chromium/chromium/src/+/main:extensions/browser/api/web_request/extension_web_request_event_rout …
> fix: use `BlockedRequest` struct to handle `webRequest` data

- docs/tutorial/tutorial-6-publishing-updating.md
- docs/tutorial/updates.md
ref https://github.com/electron-forge/electron-forge-docs/issues/183#issuecomment-2192571984
notes: none
> docs(autoUpdater): signing is only a pre-req on macOS

- shell/browser/api/electron_api_session.cc
- shell/browser/api/electron_api_session.h
session::browser_context_ can't be `nullptr` and the pointer never changes, so use a [`const raw_ref`](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md#non_owning-pointers-in-class-fields) instead of a `raw_ptr`.
Notes: none
> refactor: make session::browser_context_ a const raw_ref

- .circleci/config.yml
- .circleci/config/base.yml
Remove macOS arm64 build jobs and publish jobs on both macOS and Linux. We're publishing exclusively on GHA now and macOS jobs are stalling out consistently.
Notes: none
> build: remove all publish & build on macOS

- .circleci/config/base.yml
- .devcontainer/README.md
- .devcontainer/on-create-command.sh
- .github/actions/build-electron/action.yml
- appveyor-woa.yml
- appveyor.yml
- docs/development/goma.md
Remove outdated goma references and replace with Reclient where necessary.
Notes: none
> chore: clean up outdated goma references

- shell/browser/web_contents_permission_helper.cc
- spec/chromium-spec.ts
Closes https://github.com/electron/electron/issues/42713.
Fixes an issue where calling `navigator.mediaDevices.enumerateDevices` hid all devices if audio permission was denied but video permission granted, and if audio permissions were granted but video denied there was no effect. This was happening because we were always passing `blink::PermissionType::AUDIO_CAPTURE` to `CheckPermission` because we believed it was processed similarly for both, but it does matter which one we pass because that logic falls down to here:
https://github.com/electron/electron/blob/c3b4cd987c618ee72d32f996a8f3ae9e3e80c2bf/shell/browser/electron_permission_manager.cc#L314-L322
and so the user's preference won't filter back up correctly via `session.setPermissionCheckHandler`. This fixes that issue.
Notes: Fixes …
> fix: video and audio capture should be separate

- lib/browser/api/browser-view.ts
- lib/browser/api/browser-window.ts
- shell/browser/api/electron_api_view.cc
- spec/api-browser-view-spec.ts
Fixes https://github.com/electron/electron/issues/42564.
This PR reworks some BrowserView logic to account for the fact that it's possible for a BrowserView to be actively attached to a BrowserWindow, but for the BrowserView's webContents to be closed. Previously, we were handling BrowserView ownerWindow logic by routing through the webContents' ownerWindow, and this would break in the above scenario. To fix this, we need to do the following:
- Ensure that when a child BrowserView is removed, it's removed even if its webContents is closed. Otherwise, if we go to add another BrowserView to the same window, our logic will have the incorrect number of existing children and DCHECK.
- Ensure that when a BrowserView's webContents is closed/destroyed, its owner window removes the BrowserView's …
> fix: potentially closed webContents in BrowserView

- shell/browser/api/electron_api_session.cc
- shell/browser/api/electron_api_session.h
Fix a dangling `raw_ptr<Session>` in Session's UserDataLink class. This class is for mapping BrowserContext to Session to implement `Session::FromBrowserContext()`. This approach converts those `raw_ptr` to `base::WeakPtr` to avoid the dangling raw_ptr.
The dangling raw ptr error:
```
[561781:0705/121435.715912:ERROR:partition_alloc_support.cc(687)] Detected dangling raw_ptr with id=0x0000026400bd9fd8:
[DanglingSignature]	gin_helper::CleanedUpAtExit::DoCleanup() [../../electron/shell/common/gin_helper/cleaned_up_at_exit.cc:30:5]	No active task	electron::api::(anonymous namespace)::UserDataLink::~UserDataLink() [../../base/allocator/partition_allocator/src/partition_alloc/pointers/raw_ptr_backup_ref_impl.h:200:7]	No active task
The memory was freed at:
#0 0x5f8f01799502 …
```
> fix: dangling raw_ptr<Session> in UserDataLink

- shell/browser/electron_browser_context.cc
The extension system is freed by the DestroyBrowserContextServices() call in the ElectronBrowserContext destructor, so we need to zero out the pointer to avoid a dangling raw_ptr error.
The raw_ptr error that this fixes:
```
The memory was freed at:
#0 0x5bb186624502 base::debug::CollectStackTrace() [../../base/debug/stack_trace_posix.cc:1044:7]
#1 0x5bb18660c25c base::debug::StackTrace::StackTrace() [../../base/debug/stack_trace.cc:242:20]
#2 0x5bb18662aaba base::allocator::(anonymous namespace)::DanglingRawPtrDetected() [../../base/allocator/partition_alloc_support.cc:497:11]
#3 0x5bb1866d8fb2 allocator_shim::internal::PartitionFree() [../../base/allocator/partition_allocator/src/partition_alloc/in_slot_metadata.h:396:5]
#4 0x5bb1817f47c5 base::internal::flat_tree<>::erase() …
```
> fix: dangling raw_ptr ElectronBrowserContext::extension_system_

- shell/browser/electron_browser_context.cc
- shell/browser/electron_browser_context.h
Minor side-cleanup to `electron::ElectronBrowserContext` that I did while working on a couple of browser context bugfixes
- move DevicePermissionMap, PartionOrPath, out of public namespace into private class
- remove forward declaration of unused v8 classes
- prefer `unique_ptr<T>` operator bool over checking `.get()` for `nullptr`
Notes: none
> refactor: minor electron browser context cleanup

- shell/browser/extensions/electron_extensions_browser_client.cc
Small fix I found while researching something else.
`BroadcastEvent()` takes and consumes a `std::unique_ptr<Event>` argument.  `ElectronExtensionsBrowserClient::BroadcastEventToRenderers()` has a bug in that it passes the same unique ptr to as many event routers as it can find.
Notes: none.
> fix: multiple move() calls on the same unique_ptr

- patches/node/fix_handle_boringssl_and_openssl_incompatibilities.patch
Refs https://boringssl-review.googlesource.com/c/boringssl/+/54306
Refs https://boringssl-review.googlesource.com/c/boringssl/+/67207
Cleans up and removes unnecessary `OPENSSL_IS_BORINGSSL` checks.
Notes: none
> build: clean up BoringSSL patch

- chromium_src/BUILD.gn
- shell/browser/electron_browser_main_parts.cc
- shell/utility/electron_content_utility_client.cc
Backport of #42758.
Notes: Fixed an issue where opening multiple file pickers on Windows via the `input` tag could cause a crash.
> refactor: run Windows `SelectFileDialog` out of process

- .github/actions/restore-cache-azcopy/action.yml
Occasionally a GHA macOS build will timeout copying the source cache from Azure.  This PR tweaks AzCopy to hopefully be a little faster.  Additionally, I've bumped up the timeout to 30 minutes to give more time for times when AzCopy is slower (eg lots of PRs running at the same time). 
Notes: none
> chore: speed up azcopy on src cache

- shell/browser/electron_speech_recognition_manager_delegate.cc
- shell/browser/electron_speech_recognition_manager_delegate.h
All the listener functions are empty stubs (and have been since d4e3c39) so it doesn't seem like we need a listener?
SpeechRecognitionManagerDelegate [declares](https://chromium.googlesource.com/chromium/src/+/refs/heads/main/content/public/browser/speech_recognition_manager_delegate.h#35) this method:
> // Checks whether the delegate is interested (returning a non nullptr
> // ptr) or not (returning nullptr) in receiving a copy of all sessions
> // events. This is called on the IO thread.
> virtual SpeechRecognitionEventListener* GetEventListener() = 0;
This PR has ElectronSpeechRecognitionManagerDelegate stop subclassing from the Listener and changes GetEventListener() to return nullptr.
Notes: none
> refactor: do not subclass ElectronSpeechRecognitionManagerDelegate from SpeechRecognitionEventListener

- shell/browser/electron_browser_client.cc
Closes https://github.com/electron/electron/issues/42609
Refs https://chromium-review.googlesource.com/c/chromium/src/+/5324688
Refs https://chromium-review.googlesource.com/c/chromium/src/+/5368321
Fixes an issue where High Contrast Mode didn't apply to webContents on Windows. This happened as a result of the above CLs - Chromium moved forced color state logic to a Web Setting in Blink. To fix this, we need to also handle it as a web preference via `ElectronBrowserClient::OverrideWebkitPrefs`
Notes: Fixes an issue where High Contrast Mode didn't apply to webContents on Windows.
> fix: High Contrast mode not working on Windows

- shell/browser/api/electron_api_desktop_capturer.cc
- spec/api-screen-spec.ts
Closes https://github.com/electron/electron/issues/42747.
Fixes an issue where sources returned by the `desktopCapturer` API and by `screen.getAllDisplays()` no longer match on Windows. This happened initially as a result of https://chromium-review.googlesource.com/c/chromium/src/+/5362362, which removed the static helper we were previously using and required that the id be derived from `HMONITOREX`. The ids are specifically intended and expected to match, so this created a problem for developers needing this information to be kept consistent. To fix this, we need to do a bit more work unfortunately and get that `HMONITOREX` information ourselves in order to derive the correct id.
Confirmed to produce expected results via https://gist.github.com/bukharin/7e4c4d61c9569e57de2183076d2808f9 …
> fix: `desktopCapturer` and `screen` source ids should match screen ids

- .github/workflows/pipeline-segment-node-nan-test.yml
- script/nan-spec-runner.js
Fixes an issue seen after the release of node-gyp@10.2.0 owing to https://github.com/nodejs/node-gyp/commit/ea99fea83485dc5be04db01df9b2fdbe05319b8e. To fix this, use the same version of node-gyp when building nan tests as the one they directly depend on.
Notes: none
> ci: fix Nan test failure on Linux

- .github/ISSUE_TEMPLATE/bug_report.yml
It would be nice to allow bug reports to flag multiple platforms, rather than having to specify in "Additional information".
Notes: none
> chore: allow multiple OS selection on bug reports

- shell/browser/api/electron_api_desktop_capturer.cc
- spec/api-screen-spec.ts
Follow-up to #42781:
> Closes https://github.com/electron/electron/issues/42747.
>
> Fixes an issue where sources returned by the `desktopCapturer` API and by `screen.getAllDisplays()` no longer match on Windows. This happened initially as a result of https://chromium-review.googlesource.com/c/chromium/src/+/5362362, which removed the static helper we were previously using and required that the id be derived from `HMONITOREX`. The ids are specifically intended and expected to match, so this created a problem for developers needing this information to be kept consistent. To fix this, we need to do a bit more work unfortunately and get that `HMONITOREX` information ourselves in order to derive the correct id.
>
> Confirmed to produce expected results via …
> fix: `desktopCapturer` and `screen` display ids should match

- shell/browser/browser_process_impl.cc
- shell/browser/electron_browser_context.cc
- shell/browser/net/resolve_proxy_helper.cc
- shell/browser/net/resolve_proxy_helper.h
Refs https://github.com/microsoft/vscode/issues/217220
Regressed in https://github.com/electron/electron/commit/26131b23b81a661fb65d37437b9a1f63b4408fae
Avoid capturing `network::mojom::NetworkContext` in the `ResolveProxyHelper` which is a singleton per browser context or per app depending on the caller. Instead use the helpers which will reinitialize the context if the network service was restarted.
Notes: fix crash when resolving proxy with `session.resolveProxy` api
> fix: crash when resolving proxy due to network service restart

- .github/actions/build-electron/action.yml
- .github/workflows/linux-publish.yml
- .github/workflows/pipeline-segment-electron-build.yml
- script/node-disabled-tests.json
- spec/webview-spec.ts
This PR fixes two issues in Linux 29-x-y CI:
1. The patch to strip binaries on Linux publish was only partially cherry-picked in - while the strip binary logic itself was applied, the input variable which set it to "true" on publish was not passed down through enough of the composite actions. The first commit fixes this issue.
2. The 29-x-y branch is seeing a consistent failure on x64 runners for `<webview>.printToPDF() rejects on incorrectly typed parameters`. The second commit skips that test on Linux x64 only (this will affect the x64 and ASan build tests).
Notes: none
> build: fix Linux binary strip on publish, Linux x64 PrintInPDF test flake

- .gitattributes
- script/lint.js
- script/run-clang-format.py
`npm run lint` is not runnable on Windows currently. Made some minor changes to make it working properly.
Notes: fix: fixed the `npm run lint` not working on Windows.
> chore: fix `npm run lint` not working on Windows

- docs/api/download-item.md
- shell/browser/api/electron_api_download_item.cc
- shell/browser/api/electron_api_download_item.h
- spec/api-session-spec.ts
This adds the following methods to `DownloadItem`:
- `getCurrentBytesPerSecond()`
- `getPercentComplete()`
- `getEndTime()`
Referenced via:
https://source.chromium.org/chromium/chromium/src/+/main:components/download/internal/common/download_item_impl.cc;bpv=0;bpt=1
Notes: Added `DownloadItem.getCurrentBytesPerSecond()`, `DownloadItem.getPercentComplete()`, `DownloadItem.getEndTime()`.
> feat:  add `getPercentComplete` / `getCurrentBytesPerSecond` / `getEndTime` to DownloadItem

- script/lib/util.py
- script/run-clang-format.py
Similar to #42527, Chromium recently:
* [Moved `clang-format` to `buildtools`](https://chromium-review.googlesource.com/c/chromium/src/+/5506857)
* This seems to be on the most recent M126
* [Then, later changed the path of `clang-format`](https://chromium-review.googlesource.com/c/chromium/src/+/5581721), moving from `{platform}/format` to `{platform}-format` (`/` to `-`).
* This change has not landed on M126
I'm going to backport this change to `32-x-y` and `31-x-y`. This should cleanly backport to `32-x-y`, but since `31-x-y` only got the first change we will have to subtly adjust the `util.py` change to join `format` as a path segment instead of as part of the platform.
Notes: none
> build: fix clang format location helper (again)

- shell/browser/api/electron_api_web_contents.cc
- spec/api-browser-window-spec.ts
Closes https://github.com/electron/electron/issues/42704.
Fixes an issue where calling `BrowserWindow.setBackgroundColor` and passing any level of transparency would cause a crash via CHECK [here](https://source.chromium.org/chromium/chromium/src/+/main:content/browser/renderer_host/render_widget_host_view_base.cc;l=313;drc=6d0ae42edc5f1bca00bdbd076d469ee675d3306c;bpv=1;bpt=1). This used to be a DCHECK but was recently turned into a CHECK in order to tighten up various expected values in WebContents. As many of my previous PRs have noted, background color logic is pretty scattered in Chromium. However, some digging shows that we only need to call `RenderWidgetHostViewBase::SetBackgroundColor` to designate whether or not the color is fully opaque - if there's any level of transparency we …
> fix: `BrowserWindow.setBackgroundColor` should work with transparency

- chromium_src/BUILD.gn
- docs/api/view.md
- shell/browser/api/electron_api_view.cc
- shell/browser/api/electron_api_view.h
- shell/browser/api/electron_api_web_contents_view.cc
- shell/browser/api/electron_api_web_contents_view.h
- shell/browser/ui/inspectable_web_contents_view.cc
- shell/browser/ui/inspectable_web_contents_view.h
- spec/api-browser-view-spec.ts
- spec/api-browser-window-spec.ts
- spec/api-view-spec.ts
- spec/api-web-contents-view-spec.ts
- spec/guest-window-manager-spec.ts
- spec/lib/screen-helpers.ts
- spec/webview-spec.ts
resolves #42288
resolves #33426
Adds `View.setBorderRadius(radius)` which applies a rounded corner mask to the view. Note that there are two separate implementations depending on whether it's purely a Chromium view (View/ImageView/etc.) or a native view (WebView).
| Windows | Mac |
| --- | --- |
| ![image](https://github.com/electron/electron/assets/1656324/032d27a8-01fc-490c-bdab-c226520ccd12) | ![image](https://github.com/electron/electron/assets/1656324/532474c0-bb2b-485e-81c5-71eb29f06e27) |
Border radius demo: https://gist.github.com/samuelmaddock/4905763d665905c9134447ab9a9ac283
Animated demo: https://gist.github.com/samuelmaddock/99f0c66a584d4134139d3c9608df6652
I unfortunately don't have a Linux machine setup to test this. However, that platform relies on //ui/aura, same as …
> feat: customize border radius of Views

- shell/browser/osr/osr_web_contents_view.h
On the Mac platform, OffScreenWebContentsView uses Automatic Reference Counting (ARC) to handle the lifecycle of offScreenView_. However, this private member variable is not initialized and its value is undefined. In some cases, it is initialized to a garbage value, which may cause ARC to release the value incorrectly, resulting in a crash.
The crash stack is：
> Crashed Thread:        0  CrBrowserMain  Dispatch queue: com.apple.main-thread
> 
> Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
> Exception Codes:       KERN_INVALID_ADDRESS at 0x0000100220010020
> Exception Codes:       0x0000000000000001, 0x0000100220010020
> 
> VM Region Info: 0x100220010020 is not in any region.  Bytes after previous region: 16277389246497  Bytes before following region: 446139662304
>       REGION TYPE …
> fix: crash with creating OffScreenWebContentsView

- shell/browser/api/electron_api_view.cc
Fix another `raw_ptr` error.
This one is pretty small: the destructor for `electron::api::View` isn't cleared before the View is destroyed.
Clearing it fixes this backtrace:
```
Running: Main process specs
ok 1 app module BrowserWindow events should emit browser-window-created event when window is created
[1223495:0716/123446.652699:ERROR:partition_alloc_support.cc(687)] Detected dangling raw_ptr with id=0x00000bf402e2f7f8:
[DanglingSignature]	base::debug::CollectStackTrace() [../../base/debug/stack_trace_posix.cc:1044:7]	electron::NodeBindings::WakeupMainThread() [../../electron/shell/common/node_bindings.cc:911:26]	electron::api::View::~View() [../../base/allocator/partition_allocator/src/partition_alloc/pointers/raw_ptr_backup_ref_impl.h:200:7] …
```
> fix: dangling raw_ptr<views::View> in api::View

- shell/browser/electron_browser_main_parts.cc
- shell/browser/electron_browser_main_parts.h
Fix a dangling raw_ptr `NodeBindings::uv_env_` in the node bindings owned by `ElectronBrowserMainParts`.
This is set from the EBMS's `node_env_` field [here](https://github.com/electron/electron/blob/778d3098a0f0bfc00015d54263674318f4adf6b1/shell/browser/electron_browser_main_parts.cc#L261) but wasn't being cleared before `node_env_` is destroyed [here](https://github.com/electron/electron/blob/778d3098a0f0bfc00015d54263674318f4adf6b1/shell/browser/electron_browser_main_parts.cc#L607). This PR adds a `set_uv_env(nullptr)` call to clear it.
This PR fixes this dangling raw_ptr error:
```
[1331881:0716/225832.407199:ERROR:partition_alloc_support.cc(687)] Detected dangling raw_ptr with id=0x00001594001957f8:
[DanglingSignature]	node::FreeEnvironment() …
```
> fix: dangling raw_ptr NodeBindings::uv_env_

- shell/browser/api/electron_api_session.cc
- shell/browser/api/electron_api_session.h
Manual backport of #42786 to 30-x-y. See that PR for details.
Notes: none.
> fix: dangling raw_ptr<Session> in UserDataLink 

- shell/browser/electron_browser_client.cc
- shell/browser/electron_browser_client.h
Remove unused field `ElectronBrowserClient::browser_main_parts_`. The code that used it was removed a few months ago in 48d0b09ad932aabc91ef072c862f3489202e40fd (#37587).
Notes: none.
> chore: remove unused field `ElectronBrowserClient::browser_main_parts_`

- shell/browser/electron_download_manager_delegate.h
Remove the `CreateDownloadPathCallback` typedef because the code using it was removed in  e3c580e9
Notes: none.
> chore: remove unused typedef CreateDownloadPathCallback

- shell/browser/api/electron_api_web_contents.cc
- shell/browser/web_contents_preferences.cc
- shell/browser/web_contents_preferences.h
Minor cleanup of WebContentsPreferences:
- remove unused methods (callers removed in #40598)
- make const methods const
- update `WebContentsPreferences::GetPreloadPath()` to use `std::optional`
Notes: none.
> refactor: remove unused web contents preferences methods

- shell/common/gin_helper/wrappable.cc
- shell/common/gin_helper/wrappable_base.h
last caller removed in 6159066c (#22916)
Notes: none.
> chore: remove unused WrappableBase::AfterInit()

- shell/browser/api/electron_api_base_window.h
The last caller was removed in 67ba3040 (#37902)
Notes: none.
> chore: remove unused BaseWindow::GetWeakPtr()

- docs/api/session.md
- shell/browser/file_system_access/file_system_access_permission_context.cc
- shell/browser/file_system_access/file_system_access_permission_context.h
Closes https://github.com/electron/electron/issues/42459
More closely match upstream spec behavior when File System Access API attempts to open a file or directory in a blocked path. Now, a `file-system-access-restricted` event is emitted on `session` when a user attempts to access a restricted path:
```js
{
origin: 'https://www.buzzfeed.com/',
isDirectory: true,
path: '/Users/codebytere/Downloads'
}
```
Developers can then decide how to proceed.
Notes: Aligned failure pathway in File System Access API with upstream when attempting to open a file or directory in a blocked path.
> feat: emit an event when accessing restricted path in File System Access API

- docs/api/browser-window.md
Closes https://github.com/electron/electron/issues/35360.
Improves docs to make clearer conditions where `win.isFullScreen()` might return an unexpected value on macOS.
Notes: none
> docs: note macOS fullscreen events in fullscreen query

- docs/api/native-theme.md
- docs/api/system-preferences.md
- docs/breaking-changes.md
- filenames.auto.gni
- lib/browser/api/system-preferences.ts
- shell/browser/api/electron_api_native_theme.cc
- shell/browser/api/electron_api_native_theme.h
- spec/api-native-theme-spec.ts
Closes https://github.com/electron/electron/issues/27910.
Refs https://issues.chromium.org/issues/40260615.
Adds a new property `prefersReducedTransparency` to `nativeTheme`, which indicates whether the user has chosen to reduce OS-level transparency via system accessibility settings.
Notes: Added a new property `prefersReducedTransparency` to `nativeTheme`, which indicates whether the user has chosen to reduce OS-level transparency via system accessibility settings.
> feat: add transparency checking to `nativeTheme`

- shell/browser/api/electron_api_base_window.cc
- shell/browser/native_window.cc
- shell/browser/native_window_mac.mm
- shell/common/api/electron_api_shell.cc
- shell/common/gin_converters/blink_converter.cc
- shell/common/node_bindings.cc
- shell/common/node_bindings.h
- shell/renderer/electron_render_frame_observer.cc
- shell/renderer/electron_render_frame_observer.h
- shell/renderer/electron_renderer_client.cc
- shell/renderer/electron_renderer_client.h
- shell/renderer/electron_sandboxed_renderer_client.cc
- shell/renderer/electron_sandboxed_renderer_client.h
- shell/renderer/renderer_client_base.cc
- shell/renderer/renderer_client_base.h
We should be using `v8::Local` rather than `v8::Handle`. They mean the same thing and the latter is kept around "for historical reasons." It's disabled when `V8_IMMINENT_DEPRECATION_WARNING` is defined (i.e. `V8_DEPRECATE_SOON`).
It's been in this  "imminent deprecation" state for years so it's probably not breaking tomorrow, but that's no reason to keep using the outdated naming...
https://source.chromium.org/chromium/chromium/src/+/main:v8/include/v8-local-handle.h;l=603;drc=c0265133106c7647e90f9aaa4377d28190b1a6a9
Notes: none.
> chore: use v8::Local<>, not v8::Handle<>

- package.json
- yarn.lock
`@electron/docs-parser@1.2.1` is needed to support API history in the docs, and also picking up `@electron/typescript-definitions@8.15.7` to get a little fix for extraneous log output.
Notes: none
> build: update docs-parser and typescript-definitions packages

- lib/browser/api/browser-window.ts
- shell/browser/api/electron_api_browser_window.cc
- shell/browser/api/electron_api_browser_window.h
After #37902 landed, windows that are either minimized or hidden can cause an app to throw an unresponsive error when an app calls `event.preventDefault()` on the close event, despite the app itself not being unresponsive. This PR reverts commit 67ba30402bcbf6942fa0846927f2d088cf0a749d - we can reland this refactor after fixing the minimize/hidden issue.
Notes: Fixed an error where a minimized or hidden window would thrown an unresponsive error in the main process.
> fix: revert BrowserWindow unresponsive handling refactor

- shell/browser/notifications/notification.cc
- shell/browser/notifications/notification_presenter.cc
Closes https://github.com/electron/electron/issues/43055
Recently, it was discovered that a crash occurs when erasing a notification point object in the ```electron::NotificationPresenter::RemoveNotification```.
Here, it should be checked and additional protection should be added to avoid it.
Notes:  Fixes a potential crash when removing notifications on Windows
> chore: avoid crash while notification removal

- shell/browser/net/node_stream_loader.cc
- shell/browser/net/node_stream_loader.h
- spec/api-protocol-spec.ts
`.destroy()` is an important method in the lifecycle of a Node.js Readable stream. It is typically called to reclaim the resources (e.g., close file descriptor). The only situations where calling it manually isn't necessary are when the following events are emitted first:
- `end`: natural end of a stream
- `error`: stream terminated due to a failure
Prior to this commit the ended state was incorrectly tracked together with a pending internal error. It led to situations where the request could get aborted during a read and then get marked as ended (having pending error).
With this change we disentangle pending "error" and "destroyed" cases to always properly terminate an active Node.js Readable stream.
cc @MarshallOfSound @VerteDinde 
Notes: Fixed the resource leak when using Node.js …
> fix: always terminate active Node Streams

- lib/browser/guest-view-manager.ts
- lib/common/web-view-methods.ts
This PR fixes https://github.com/electron/electron/issues/42879
Testing:
Before changes, tests show deprecation warning:
After changes, deprecation warnings are gone:
Notes: none
> fix: redirect webview navigation methods

- shell/common/gin_helper/dictionary.h
- shell/common/gin_helper/persistent_dictionary.h
- In getters, hold the result of `GetHandle()` in a temp variable instead of computing it twice
- Prefer [v8::Maybe&lt;bool&gt;::FromMaybe(false)](https://source.chromium.org/chromium/_/chromium/v8/v8/+/47f420e89ec1b33dacc048d93e0317ab7fec43dd:include/v8-maybe.h;l=81) over  [IsJust()](https://source.chromium.org/chromium/_/chromium/v8/v8/+/47f420e89ec1b33dacc048d93e0317ab7fec43dd:include/v8-maybe.h;l=35) && [FromJust()](https://source.chromium.org/chromium/_/chromium/v8/v8/+/47f420e89ec1b33dacc048d93e0317ab7fec43dd:include/v8-maybe.h;l=63) because the inlined code is simpler and safer
- Extract duplicate code into new private helper functions `MakeKey()` and `MakeHiddenKey()`
Notes: none.
> perf: avoid duplicate calculations in gin_helper::Dictionary getters

- shell/browser/native_window_mac.mm
Closes https://github.com/electron/electron/issues/42962
Refs https://github.com/electron/electron/pull/42226
Refs https://github.com/electron/electron/pull/43033
Fixes `showInactive` window not showing - we don't need to use `orderFrontKeepWindowKeyState` after reverting #43033
Notes: Fixed an issue where calling `window.showInactive` on macOS did not actually show the window.
> fix: `showInactive` window not showing

- shell/common/api/electron_api_v8_util.cc
- typings/internal-ambient.d.ts
Remove unused & undocumented function `v8Util.deleteHiddenValue()`. It hasn't been used since Nov 2020 (c8d77cae4a, #26659).
Notes: none.
> chore: remove unused & undocumented function v8Util.deleteHiddenValue()

- .github/actions/build-electron/action.yml
- Fixes #43076
Correctly generated ffmpeg for macOS x64 can been seen here:
https://github.com/electron/electron/actions/runs/10163398663?pr=43093
in the [generated_artifacts_darwin_x64](https://github.com/electron/electron/actions/runs/10163398663/artifacts/1755804915)
Notes: Fixed ffmpeg release on x64 macOS
> build: fixup ffmpeg release on x64 macOS

- docs/tutorial/electron-timelines.md
Closes https://github.com/electron/electron/issues/43091
Update external documentation to reflect the new Node.js version release policy decided by the Release WG.
Notes: none
> docs: update Node.js stable release policy

- .github/ISSUE_TEMPLATE/bug_report.yml
Does what it says on the tin. The "report an issue" template has an outdated link to the supported versions page.
Notes: none.
> docs: fix broken link in bug report template

- shell/browser/native_window_mac.h
- shell/browser/native_window_mac.mm
- shell/browser/ui/cocoa/electron_ns_window_delegate.mm
On macOS, entering or exiting fullscreen mode can fail even after `windowWillEnterFullScreen` or `windowWillExitFullScreen` has run (see the documentation for [`windowDidFailToEnterFullScreen`](https://developer.apple.com/documentation/appkit/nswindowdelegate/1419591-windowdidfailtoenterfullscreen?language=objc) and [`windowDidFailToExitFullScreen`](https://developer.apple.com/documentation/appkit/nswindowdelegate/1419573-windowdidfailtoexitfullscreen?language=objc)). If this happens, it is necessary to properly restore the window's original state, but Electron currently does not do that. The most prominent bug caused by this is that if the window fails to enter fullscreen, `fullscreen_transition_state_` is "stuck" at `FullScreenTransitionState::kEntering`, and `app.quit()` does not work …
> fix: handle failing to enter fullscreen on macOS

- shell/browser/serial/serial_chooser_context.cc
Closes https://github.com/electron/electron/issues/43083
Refs https://chromium-review.googlesource.com/c/chromium/src/+/4609200
Fixes an issue where `navigator.serial.getPorts()` incorrectly returned an empty array in some cases. This happened as a result of https://github.com/electron/electron/commit/abf7a486050f7705dcea661364b64e058c6c7aae - when `navigator.serial.getPorts()` is called, each port is validated via `SerialChooserContext::HasPortPermission`. To maintain parity with upstream, I incorporated all relevant [checks from upstream](https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/serial/serial_chooser_context.cc;l=448-456?q=SerialChooserContext::HasPortPermission&sq=package:chromium&type=cs). However, around the same time,  upstream migrated some of its …
> fix: take bluetooth serial ports into account in `serial.getPorts()`

- shell/common/api/electron_api_environment.cc
- typings/internal-ambient.d.ts
Remove `env.unSetVar()`, which was added to internal bindings in Oct 2020 (b33f2260, #25623) but never used.
Notes: none.
> chore: remove unused internal env.unSetVar()

- docs/tutorial/tutorial-6-publishing-updating.md
Hello,
I found the electron-fiddle's "Build and Release pipeline" and  "Forge configuration" links are broken due to the change of filename. I replaced the broken links with the up-to-date working ones. Thanks for reviewing this PR!
Notes: none
> docs: fixed broken electron-fiddle links in the "Tutorial - Publishing and Updating" doc

- patches/chromium/.patches
- patches/chromium/cherry-pick-1b9040817119.patch
- patches/chromium/cherry-pick-38e4483e47f9.patch
- patches/chromium/cherry-pick-43b8b682d05c.patch
- patches/chromium/cherry-pick-99cafbf4b4b9.patch
- patches/chromium/cherry-pick-c5dd8839bfaf.patch
- patches/chromium/cherry-pick-d54105311590.patch
- patches/v8/.patches
- patches/v8/cherry-pick-70d2fe6b7c47.patch
- patches/v8/cherry-pick-901377bb2f3b.patch
- patches/v8/cherry-pick-bb28367eed73.patch
- patches/v8/cherry-pick-bc545b15a0ee.patch
- patches/v8/cherry-pick-cdbc1d9684a3.patch
<details>
<summary>electron/security#549 - d54105311590 from chromium</summary>
[SCK] Retain refptr to shared helper to prevent UAF.
Capture a reference to the shared helper in the onerror handler to
prevent a UAF that can occur when the browser drops the mojo
connection.
Bug: 346692546
Change-Id: Ifb264488a6fa8417c134a34d902605d2c141720b
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5634908
Reviewed-by: Avi Drissman <avi@chromium.org>
Commit-Queue: Mark Foltz <mfoltz@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1316145}
</details>
<details>
<summary>electron/security#553 - 43b8b682d05c from chromium</summary>
Prevent script injection on reload when racing with a navigation
DevTools passes the loaderId now when calling Page.reload, in order to
prevent …
> chore: cherry-pick 11 changes from 3-M126

- DEPS
- patches/chromium/adjust_accessibility_ui_for_electron.patch
- patches/chromium/build_do_not_depend_on_packed_resource_integrity.patch
- patches/chromium/build_make_libcxx_abi_unstable_false_for_electron.patch
- patches/chromium/chore_provide_iswebcontentscreationoverridden_with_full_params.patch
- patches/chromium/desktop_media_list.patch
- patches/chromium/disable_hidden.patch
- patches/chromium/feat_add_data_parameter_to_processsingleton.patch
- patches/chromium/feat_enable_offscreen_rendering_with_viz_compositor.patch
- patches/chromium/fix_add_support_for_skipping_first_2_no-op_refreshes_in_thumb_cap.patch
- patches/chromium/fix_crash_loading_non-standard_schemes_in_iframes.patch
- patches/chromium/fix_restore_original_resize_performance_on_macos.patch
- patches/chromium/fix_return_v8_value_from_localframe_requestexecutescript.patch
- patches/chromium/mas_avoid_private_macos_api_usage.patch.patch
- patches/chromium/notification_provenance.patch
- patches/chromium/pepper_plugin_support.patch
- patches/chromium/process_singleton.patch
- patches/chromium/refactor_expose_cursor_changes_to_the_webcontentsobserver.patch
- patches/chromium/refactor_expose_hostimportmoduledynamically_and.patch
- patches/chromium/resource_file_conflict.patch
- patches/chromium/support_mixed_sandbox_with_zygote.patch
- patches/devtools_frontend/chore_expose_ui_to_allow_electron_to_set_dock_side.patch
- patches/v8/fix_disable_scope_reuse_associated_dchecks.patch
Updating Chromium to 129.0.6632.0.
See [all changes in 129.0.6630.0..129.0.6632.0](https://chromium.googlesource.com/chromium/src/+log/129.0.6630.0..129.0.6632.0?n=10000&pretty=fuller)
Notes: Updated Chromium to 129.0.6632.0.
> chore: bump chromium to 129.0.6632.0

- shell/browser/electron_browser_context.cc
- shell/browser/file_system_access/file_system_access_permission_context.cc
- shell/browser/hid/hid_chooser_controller.cc
- shell/browser/serial/serial_chooser_controller.cc
- shell/browser/ui/file_dialog_linux.cc
- shell/browser/ui/inspectable_web_contents.cc
- shell/browser/usb/usb_chooser_controller.cc
- shell/renderer/electron_renderer_client.cc
`std::ranges` is explicitly allowed now, so this PR migrates our C++20 `base::ranges` calls to `std::ranges`.
Related links:
- https://chromium.googlesource.com/chromium/src/+/main/styleguide/c++/c++-features.md#range-algorithms-allowed
- https://chromium-review.googlesource.com/c/chromium/src/+/5668999
- https://groups.google.com/a/chromium.org/g/cxx/c/ZnIbkfJ0Glw
Notes: none.
> refactor: prefer std::ranges over base::ranges

- shell/app/electron_login_helper.mm
Refs https://github.com/electron/electron/pull/43087.
Migrates deprecated API in `electron_login_helper` to use non-deprecated API. Functionality should remain identical.
Notes: none
> refactor: migrate `electron_login_helper` to non-deprecated API

- shell/browser/native_window_mac.mm
As in title. `ElectronNSWindow` is a `NativeWidgetMacNSWindow`, and so we can remove some of our child window ordering code as it's copied from [upstream](https://source.chromium.org/chromium/chromium/src/+/main:components/remote_cocoa/app_shim/native_widget_mac_nswindow.mm;l=51;drc=105770df485ace262780d95126bb60b1a16ec340;bpv=1;bpt=1). We instead can use `orderWindowByShuffling` to accomplish the same goal.
Notes: none
> refactor: simplify window `moveAbove/moveTop` impl on macOS

- shell/browser/api/electron_api_auto_updater.cc
- shell/common/api/electron_bindings.cc
- shell/common/gin_helper/callback.h
- shell/common/gin_helper/event_emitter_caller.cc
- shell/common/gin_helper/function_template.h
- shell/common/gin_helper/microtasks_scope.h
- shell/common/gin_helper/promise.cc
- shell/common/gin_helper/promise.h
- shell/common/node_bindings.cc
- shell/common/v8_value_serializer.cc
- shell/renderer/api/electron_api_spell_check_client.cc
- shell/renderer/electron_sandboxed_renderer_client.cc
Closes #43085.
Require code that instantiates `gin_helper::MicrotasksScope`s to provide all four constructor arguments.
CC @deepak1556 who has the most context on this, but who also (I think?) is on holiday so reviews welcomed from anyone :smile_cat: 
Notes: none.
> fix: gin_helper::MicrotasksScope instantiation

- shell/browser/hid/hid_chooser_context.cc
HidChooserContext's `OnHidManagerConnectionError()` and `DeviceRemoved()` methods both build temporary `std::vector<url::Origin>` objects that are unused. This PR removes them.
The code seems to have been there since the initial commit (6aece4a8, Sep 2021) , so possibly this code was copied from somewhere else? (ETA: answered by @codebytere in comments)
Notes: none.
> perf: don't build unused vectors in HidChooserContext

- .github/workflows/build.yml
- .github/workflows/pipeline-electron-build-and-test-and-nan.yml
- .github/workflows/pipeline-electron-build-and-test.yml
Noticed while looking at GHA insights, we spend a _lot_ of minutes running `gn-check` and there is no need to run them on super-large instances 🤔 Honestly it would be nice to somehow run them on linux boxes but you can't easily run `gn gen` on linux hosts for macOS builds.
Notes: none
> build: use smaller instances for gn-check

- docs/breaking-changes.md
Added some missing deprecations to `breaking-changes.md`.
See commit descriptions for links to relevant PRs.
> [!NOTE]
> If https://github.com/electron/electron/commit/7453729be1b5a75c2b620d9225ea920ebfc89b16 is merged, then modify/revert [`997d1a4` (#42982)](https://github.com/electron/electron/pull/42982/commits/997d1a48af2ee0f7837b1debddd8d1176388327f)
@dsanders11 @erickzhao @VerteDinde 
Notes: none
> docs: add missing deprecations to `breaking-changes.md`

- patches/chromium/.patches
- patches/chromium/cherry-pick-d9f7652c867c.patch
<details>
<summary>electron/security#570 - d9f7652c867c from chromium</summary>
Don't allocate WebTransportCloseInfo on stack
blink::WebTransport::OnClosed() was allocating a WebTransportCloseInfo
object on the stack. Since it is a garbage-collected object, this is
wrong. Allocate it with MakeGarbageCollected<>() instead.
(cherry picked from commit 84c1481d8a8d5e7f51316b648d1bf71f2ae52122)
Fixed: 352872238
Change-Id: I83484021d5f3f6d49d3c222c8f2dc34219f2d240
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5725413
Commit-Queue: Nidhi Jaju <nidhijaju@chromium.org>
Reviewed-by: Nidhi Jaju <nidhijaju@chromium.org>
Auto-Submit: Adam Rice <ricea@chromium.org>
Cr-Original-Commit-Position: refs/heads/main@{#1331525}
Reviewed-on: …
> chore: cherry-pick 1 changes from 1-M127

- shell/browser/api/frame_subscriber.cc
- shell/browser/osr/osr_render_widget_host_view.cc
- shell/browser/osr/osr_web_contents_view.cc
- shell/browser/ui/autofill_popup.cc
We have a lot of places where we check for a nullptr view before using it in this way:
```c++
if (GetView())
GetView()->DoSomething();
```
The assembly code does exactly what you'd expect: two identical sequential calls to `GetView()`. To avoid the redundant calls, this PR stores the view in a narrowly-scoped temporary variable, e.g.:
```c++
if (auto* view = GetView())
view->DoSomething();
```
Notes: none
> perf: avoid redundant calls to GetView()

- .github/actions/checkout/action.yml
- .github/workflows/build.yml
Don't run patchup if we don't have patchup creds -  Also run it on Linux as it's a bit faster.
Notes: none
> build: fix patchup logic only running on one platform

- docs/api/app.md
If you use a regular PNG, the Windows about panel will look pretty awful. I tested a bunch of sizes and settled on 48x48. Real fix would obviously be to not resize without any kind of resizing algorithm, but this makes things easier without changing code.
> docs: Document ideal iconPath size

- shell/browser/api/electron_api_session.cc
- shell/browser/electron_browser_context.cc
As in title. Compilation was failing when 
```
enable_pdf_viewer=false
enable_electron_extensions=false
```
Notes: none
> build: fix build when `enable_pdf_viewer` and `enable_electron_extensions` disabled

- shell/browser/native_window_views_win.cc
Closes https://github.com/electron/electron/issues/37614
Closes https://github.com/electron/electron/issues/26726
Closes https://github.com/electron/electron/issues/24893
Fixes an issue where `system-context-menu` was not triggered as expected on Windows when using a frameless BrowserWindow. As noted by @ckerr in the above issue, Electron never sees the `WM_CONTEXTMENU` message because [`hwnd_message_handler.cc`](https://source.chromium.org/chromium/chromium/src/+/main:ui/views/win/hwnd_message_handler.cc?q=hwnd_message_handler.cc&sq=package:chromium&type=cs) uses its [own custom event handling](https://source.chromium.org/chromium/chromium/src/+/master:ui/views/win/hwnd_message_handler.cc;l=3038;drc=db9ae7941adc1d95c943accce9e0151d265fd640) for` WM_RBUTTONUP`. We can fix this by …
> fix: system-context-menu with frameless BrowserWindows

- shell/browser/api/electron_api_desktop_capturer.cc
- shell/browser/api/electron_api_desktop_capturer.h
Closes https://github.com/electron/electron/issues/42143.
Resolves an issue following https://github.com/electron/electron/pull/41403 where `desktopCapturer.getSources` never resolves unless the user grants permissions on macOS.
This handles the issue by pre-emptively checking whether the user has granted permissions and rejects the promise if no permissions have been granted. `TryPromptUserForScreenCapture` plumbs down to `CGRequestScreenCaptureAccess()`, which is a (poorly documented) function that prompts for access if the user has not yet been prompted and returns false immediately. It then will return true or false without prompting if the user has either granted access or been previously prompted and chosen not to grant access.
Notes: Resolved an issue where …
> fix: check screen capture permissions in `desktopCapturer`

- patches/chromium/build_run_reclient_cfg_generator_after_chrome.patch
Refs https://chromium-review.googlesource.com/c/chromium/src/+/5724912.
Upstream now supports static nacl configs, whereas https://github.com/EngFlow/reclient-configs doesn't, so we get git conflicts that can make it harder to sync. This fixes that.
Notes: none
> build: add nacl back to buildtools gitignore

- shell/browser/api/message_port.cc
Fix a wart from e929b2140d4a1b8bce621f8826639e38cb3f3c6d which used `auto` instead of `auto&` in a ranged loop, causing us to create & throw away `gin::Handle<MessagePort>`s as we loop. Not a major problem; but since we can avoid it, let's avoid it.
Notes: none.
> fix: accidental handle copying in a range loop

- docs/api/cookies.md
- shell/browser/api/electron_api_cookies.cc
- spec/api-session-spec.ts
- Chromium's `url::DomainIs()` does the same thing as our `MatchesDomain()` function, so let's not reinvent the wheel.  This PR removes our bespoke code and uses `url::DomainIs()` instead
- Add domain-matching tests
- Fix a small typo in the docs
Historical note: looks like we have a bespoke impl because `MatchesDomain()` landed in dbbc2f19f4, which precedes https://codereview.chromium.org/2287483002 by a year. So we were _preinventing_ the wheel :smile_cat: 
Notes: none.
> refactor: use url::DomainIs() to check cookie domains

- shell/browser/ui/electron_desktop_window_tree_host_linux.cc
- shell/browser/ui/electron_desktop_window_tree_host_linux.h
Minor cleanup to remove an unused method `ElectronDesktopWindowTreeHostLinux::UpdateClientDecorationHints()`. This is unused as of Aug 26 in #41868 dff980c9c20da444fb853b6983eb75d48714b486
Notes: none.
> chore: remove unused method ElectronDesktopWindowTreeHostLinux::UpdateClientDecorationHints()

- shell/browser/extensions/api/scripting/scripting_api.cc
- shell/browser/extensions/api/scripting/scripting_api.h
- shell/common/extensions/api/scripting.idl
Updates our `chrome.scripting` extension support to reflect changes from, among others:
* https://chromium-review.googlesource.com/c/chromium/src/+/4795146
* https://chromium-review.googlesource.com/c/chromium/src/+/4968611
* https://chromium-review.googlesource.com/c/chromium/src/+/4968680
Notes: none
> refactor: update chrome.scripting extensions api impls

- shell/browser/api/electron_api_notification.cc
- shell/browser/api/electron_api_notification.h
Remove a couple of unused fields from `electron::api::Notifications`. 
- Last use of `icon_path_` was removed on May 29, 2017 (c741b584)
- Last use of `has_icon_` was removed on May 30, 2017 (5048425e)
Notes: none
> chore: remove unused Notification fields icon_path_, has_icon_

- shell/browser/net/system_network_context_manager.cc
Set the default network context params' `enable_zstd` flag to `true` to enable zstd encoding. As per 43124, this is true for requests made in Chromium but was not true in Electron.
Closes #43124.
Notes: Enabled zstd compression in net http requests.
> feat: accept-encoding zstd

- docs/api/app.md
- docs/api/utility-process.md
- docs/breaking-changes.md
- filenames.gni
- shell/browser/api/electron_api_utility_process.cc
- shell/browser/api/electron_api_utility_process.h
- shell/browser/electron_browser_client.cc
- shell/browser/login_handler.cc
- shell/browser/login_handler.h
- shell/browser/net/url_loader_network_observer.cc
- shell/browser/net/url_loader_network_observer.h
- shell/common/api/electron_api_url_loader.cc
- shell/services/node/node_service.cc
- shell/services/node/node_service.h
- shell/services/node/public/mojom/node_service.mojom
- spec/api-utility-process-spec.ts
- spec/fixtures/api/utility-process/net.js
With net module support to utility process added via https://github.com/electron/electron/pull/40017, it is currently not straightforward to handle basic auth. Apps would need to have some sort of boilerplate code from utility process to allow the main process trigger an interactive UI for obtaining the credentials. However, we already have logic obtained from Chromium to support basic auth requests from renderers or service workers via the `app.on('login', ...)` event. It would be simpler if apps can opt-in to the same event for requests from utility process as well, this is now possible via a new property `respondToAuthRequestsFromMainProcess` on the `utilityProcess.fork` api.
Refs https://github.com/microsoft/vscode/issues/212949
Notes: Add support for responding to auth requests …
> feat: support app#login event for utility process net requests

- shell/browser/api/electron_api_web_contents.cc
- shell/browser/printing/printing_utils.cc
- shell/browser/printing/printing_utils.h
- spec/api-web-contents-spec.ts
Closes https://github.com/electron/electron/issues/30947.
Fixes an issue where calling `window.print()`, `webContents.print()` or `printToPDF` from an existing PDF document resulted in a blank page. This was happening because we were using the incorrect `RenderFrameHost` in that case - we need to ensure we're using the one corresponding to the PDF plugin.
Notes: Fixed an issue where calling `window.print()`, `webContents.print()` or `printToPDF` from an existing PDF document resulted in a blank page.
> fix: blank page when printing pdf

- patches/node/ci_ensure_node_tests_set_electron_run_as_node.patch
Upstreamed in https://github.com/nodejs/node/pull/54375.
Refactor our test modifications to an upstreamable version so that we can run them all and remove sections that aren't necessary anymore.
Notes: none
> test: fixup Node.js snapshot tests to run correctly

- .github/workflows/issue-opened.yml
Ref https://github.com/electron/electron/issues/43344
Fixes an issue where issues opened against prerelease versions would be incorrectly marked as unsupported/EOL
Notes: none
> build: fix valid versions in issue version parsing

- build/args/all.gn
In preparation for releasing Electron 32, we are reserving a new Node Module Version in advance for Electron 33.
Node.js PR: ✅ https://github.com/nodejs/node/pull/54383 (Merged)
Notes: none
> build: update NMV to 130 for Electron 33

- patches/chromium/printing.patch
Closes https://github.com/electron/electron/issues/36084.
Adjusts print status logic to ensure that the job is marked cancelled both on `UserInitCancelled` and `OnCancelling`. Previously, the default status was `kFailed` instead of `kUnknown`, which also contributed to the user incorrectly seeing failure status messages in some cancellation cases.
Notes: Fixed an issue where users would be incorrectly notified of print failure upon intentional cancellation.
> fix: printing occasionally showing failed when cancelled

- docs/api/navigation-history.md
- docs/api/structures/navigation-entry.md
- filenames.auto.gni
- lib/browser/api/web-contents.ts
- shell/browser/api/electron_api_web_contents.cc
- shell/browser/api/electron_api_web_contents.h
- spec/api-web-contents-spec.ts
- typings/internal-electron.d.ts
This PR builds on #41577 and adds 2 more functions to `webContents.navigationHistory`.
The motivation is to provide an API for developers of browser-type applications.
New API:
- `navigationHistory.removeEntryAtIndex(index)` - Removes the navigation entry at the given index.
- `navigationHistory.getAllEntries()` - Returns webContents complete history.
This enables browser-type applications to save (`getAllEntries`) browsing sessions.
Also partially resolves these feature requests: #33899 #41250
Notes: Extended `navigationHistory` API with 2 new functions for better history management.
> feat: extend navigationHistory API

- shell/browser/electron_browser_main_parts.cc
Last use removed in Mar 2018 by 4b39d17e
Notes: none
> chore: remove unused method Erase()

- shell/browser/ui/x/x_window_utils.cc
- shell/browser/ui/x/x_window_utils.h
last use removed in Aug 2022 by 53cd2315 #35179
Notes: none.
> refactor: remove unused SetWMSpecState

- shell/common/node_bindings.h
- shell/common/node_bindings_linux.cc
- shell/common/node_bindings_mac.cc
- shell/common/node_bindings_win.cc
Cleanup PR to make `NodeBindings::Create()` follow Chromium's  [object ownership calling conventions](https://chromium.googlesource.com/chromium/src/+/main/styleguide/c++/c++.md#object-ownership-and-calling-conventions): ownership of the new object is being handed off to the caller, so return it as a `std::unique_ptr<NodeBindings>`.
Notes: none.
> refactor: NodeBindings::Create() returns a unique_ptr

- shell/browser/javascript_environment.cc
Manual backport of #43356 to 33-x-y. See that PR for details.
Notes: none.
> chore: remove unused ConvertableToTraceFormatWrapper (33-x-y)

- shell/app/node_main.cc
- shell/browser/api/electron_api_crash_reporter.cc
- shell/browser/api/electron_api_desktop_capturer.cc
- shell/browser/electron_browser_client.cc
- shell/browser/extensions/api/tabs/tabs_api.cc
- shell/browser/serial/serial_chooser_context.cc
- shell/common/asar/asar_util.cc
- shell/common/extensions/electron_extensions_api_provider.cc
- shell/common/gin_helper/cleaned_up_at_exit.cc
- shell/common/logging.cc
We have about two dozen impl / helper functions that were accidentally visible in public namespaces. This PR makes them private.
No behavior changes; just making impl details private. Should be good as long as it builds.
- AllowFileAccess()
- BindBadgeServiceForServiceWorker()
- BindBeforeUnloadControl()
- BindMimeHandlerService()
- DetermineLoggingDestination()
- EncodeToken()
- GetArchiveCache()
- GetArchiveCacheLock()
- GetClientIdPath()
- GetDoomed()
- GetEDIDProperty()
- GetMonitors()
- GetParameters()
- GetPermissionAliases()
- GetPermissionInfos()
- HandleExternalProtocolInUI()
- HasExplicitLogFile()
- IsKillURL()
- MonitorAtomIdToDisplayId()
- OnOpenExternal()
- PortInfoToValue()
- PrepareURLForNavigation()
- ReadClientId()
- ResolvePossiblyRelativeURL()
- WriteClientId()
Notes: …
> refactor: move impl functions into private namespace

- docs/api/notification.md
Closes https://github.com/electron/electron/issues/43343.
Main process notification have never accepted URLs.
Notes: none
> docs: clarify icon value in Notification

- lib/browser/api/base-window.ts
- lib/browser/api/browser-window.ts
- lib/browser/api/touch-bar.ts
- shell/browser/api/electron_api_base_window.cc
- spec/api-touch-bar-spec.ts
- typings/internal-electron.d.ts
Closes https://github.com/electron/electron/issues/43344.
`SetTouchBar` was implemented internally on `BaseWindow` but not properly at the ts layer. Fix that.
Notes: Fixed an issue where `BaseWindow.setTouchBar` didn't work as expected.
> fix: touch bar functionality on BaseWindow

- docs/api/session.md
- docs/api/touch-bar-scrubber.md
- docs/api/web-utils.md
Fix typos only
Typos only.
I was unable to run tests, since [Build Tools has Xcode issues](https://github.com/electron/build-tools/issues/514#issuecomment-2298204226)
Notes: none
> fix: documentation spelling errors

- docs/api/menu-item.md
- lib/browser/api/menu-item-roles.ts
- lib/browser/api/menu-item.ts
- lib/browser/api/menu.ts
- spec/ts-smoke/electron/main.ts
Closes https://github.com/electron/electron/issues/43398.
Most `windowMethod` functions in MenuItem allow `BaseWindow`s with few exceptions. This PR shifts `instanceof BrowserWindow` checks to the `windowMethod`s that explicitly don't work with `BaseWindow` so that `BaseWindows` can at least be used with some of them.
Notes: Fixed `MenuItem.click` handler not setting `focusedWindow` parameter when focused window is a `BaseWindow`.
> fix: menu should allow focused `BaseWindow` where possible

- shell/browser/api/electron_api_session.cc
- shell/browser/extensions/api/scripting/scripting_api.cc
- shell/browser/native_window.h
- shell/browser/native_window_views.cc
- shell/browser/net/asar/asar_url_loader_factory.h
- shell/browser/net/proxying_url_loader_factory.h
- shell/browser/usb/electron_usb_delegate.h
- shell/browser/usb/usb_chooser_context.h
- shell/common/extensions/api/browser_action.json
- shell/common/gin_converters/callback_converter.h
- shell/common/gin_helper/callback.cc
- shell/common/gin_helper/callback.h
Fixes typos in the `shell/` folder
@ckerr [suggested](https://github.com/electron/electron/pull/43366#pullrequestreview-2248182635) I split what was originally a single PR with changes into 39 files into many.
Notes: none.
> chore: fix typos in 'shell/' folder.

- shell/browser/native_window_views.cc
Closes https://github.com/electron/electron/issues/43417.
Fixes an issue where moving a window and not resizing it would cause errant `resize` events to be emitted. This was happening because  `GetWindowBoundsInScreen` has a ~1 pixel margin of error. If we check existing bounds directly against the new bounds without accounting for that we'll have constant false positives when the window is moving but the user hasn't changed its size at all. There's not really a way to test this unfortunately as it occurs as a direct result of user interaction.
Output from logs during testing while I moved the window around:
<details><summary>Sample Logs</summary>
<p>
```
[27956:0822/153943.250:INFO:native_window_views.cc(1652)] OnWidgetBoundsChanged widget_size_=800x600 new_bounds.size()=800x601 …
```
> fix: ensure bounds stability in `OnWidgetBoundsChanged`

- docs/api/structures/base-window-options.md
- docs/api/structures/browser-window-options.md
Closes https://github.com/electron/electron/issues/43399.
Fixes an issue where `titleBarOverlay` was incorrectly defined on BrowserWindow and not BaseWindow.
Notes: Fixed an issue where `titleBarOverlay` was incorrectly defined on BrowserWindow and not BaseWindow.
> docs: `titleBarOverlay` is defined as a `BaseWindow` ctor option

- BUILD.gn
- shell/browser/api/electron_api_web_contents.cc
- shell/browser/api/electron_api_web_contents.h
- shell/browser/electron_pdf_document_helper_client.cc
- shell/browser/electron_pdf_document_helper_client.h
- spec/api-web-contents-spec.ts
This PR adds a new event to WebContents, `-pdf-ready-to-print` which fires when the PDF viewer is done loading content and is ready to print.  This event is intended for testing purposes only. 
- https://github.com/electron/electron/pull/43309 added a test that used a timeout to wait for the PDF viewer to finish loading.  This PR fixes that test to now wait for this new event instead of using the timeout.
Notes: none
> test: add -pdf-ready-to-print event to WebContents for testing

- shell/common/asar/asar_util.cc
- shell/common/asar/asar_util.h
Remove the function `asar::ClearArchive()`, whose last use was removed in Jun 2021 (b1d1ac65, #29293)
Notes: none.
> chore: remove unused method asar::ClearArchives()

- shell/browser/browser_linux.cc
- shell/browser/browser_win.cc
- shell/browser/electron_web_ui_controller_factory.cc
- shell/browser/net/electron_url_loader_factory.h
- shell/browser/net/proxying_url_loader_factory.cc
- shell/browser/protocol_registry.cc
- shell/browser/protocol_registry.h
- shell/browser/ui/inspectable_web_contents.cc
- shell/browser/web_contents_zoom_controller.cc
- shell/common/api/electron_api_url_loader.cc
Avoid building some unnecessary temp strings.
A new `std::string` is created every time we call `gurl.host()` or `gurl.scheme()`.
We can use `std::string_view`s instead by replacing those calls with `gurl.host_piece()` and `gurl.scheme_piece()`.
Notes: none.
> perf: prefer GURL string_view getters

- shell/browser/ui/views/win_frame_view.h
Remove a small piece of unused code: `WinFrameView::kInactiveTitlebarFeatureAlpha` was added in Aug 2021 (41646d11, #29600) but never used.
Notes: none.
> chore: remove unused WinFrameView::kInactiveTitlebarFeatureAlpha

- shell/app/electron_main_win.cc
- shell/browser/api/electron_api_global_shortcut.cc
- shell/browser/api/electron_api_session.cc
- shell/browser/hid/hid_chooser_controller.cc
- shell/browser/notifications/notification_presenter.cc
- shell/browser/serial/serial_chooser_controller.cc
- shell/browser/ui/views/client_frame_view_linux.cc
- shell/browser/ui/win/notify_icon_host.cc
- shell/browser/window_list.cc
- shell/common/crash_keys.cc
- shell/common/node_bindings.cc
`std::ranges` is [allowed now](https://chromium-review.googlesource.com/c/chromium/src/+/5668999), so let's use it. This PR migrates the lowest-hanging fruit, e.g. easy cases like this:
```diff
- std::sort(foo.begin(), foo.end());
+ std::ranges::sort(foo);
```
```diff
- std::reverse(foo.begin(), foo.end());
+ std::ranges::reverse(foo);
```
Previously: #43172
Notes: none
> refactor: prefer std::ranges over begin() and end()

- shell/common/key_weak_map.h
Simplify KeyWeakMap's implementation a little:
- Instead of having a MappedType of `std::pair<std::pair<A, B>, C>`, make a private struct that holds A, B, and C
- Use `base::ToVector()` to implement `KeyWeakMap::Values()`
- Use `std::map<>::extract()` to implement `KeyWeakMap::Remove()`
- Remove extra template syntax from `OnObjectGC()`
- Remove unused `#include <utility>`
Notes: none.
> refactor: simplify KeyWeakMap impl

- shell/browser/ui/inspectable_web_contents.cc
Enables fix from https://github.com/electron/electron/pull/39734 for linux when WCO is enabled.
Refs https://github.com/microsoft/vscode/issues/226633
Notes: fix devtools to allow restoring saved dock state on Linux when WCO is enabled
> fix: devtools dock state with WCO on linux

- appveyor-woa.yml
- appveyor.yml
- As discovered in https://github.com/electron/build-tools/issues/630 there are certain environment variables that should be set when using read only reclient.  GHA uses build-tools so the changes in https://github.com/electron/build-tools/pull/631 will address this; however for AppVeyor we need to manually set the applicable environment variables which is what this PR does.
Notes: none
> chore: speed up cache only reclient for fork PRs

- .github/workflows/pipeline-segment-electron-build.yml
- .github/workflows/pipeline-segment-electron-gn-check.yml
Something happened to the GitHub Actions `macos-14-xlarge` runners that caused these runners to only have 19GB of free space available on them:
```
Run df -h
Filesystem        Size    Used   Avail Capacity iused ifree %iused  Mounted on
/dev/disk3s1s1   295Gi   9.6Gi    19Gi    35%    404k  194M    0%   /
devfs            195Ki   195Ki     0Bi   100%     674     0  100%   /dev
/dev/disk3s6     295Gi    20Ki    19Gi     1%       0  194M    0%   /System/Volumes/VM
/dev/disk3s2     295Gi   4.9Gi    19Gi    22%     [15](https://github.com/electron/electron/actions/runs/10686391001/job/29621645893#step:2:16)3  194M    0%   /System/Volumes/Preboot
/dev/disk3s4     295Gi   288Ki    19Gi     1%      23  194M    0%   /System/Volumes/Update
/dev/disk1s2     500Mi    20Ki   495Mi     1%       0 …
```
> build: free up macos disk space as soon as possible

- shell/app/command_line_args.cc
- shell/app/command_line_args.h
- shell/app/electron_main_win.cc
Upstream is starting to use `-Wunsafe-buffer-usage` as part of a [larger C buffer hardening project at Google](https://bughunters.google.com/blog/6368559657254912/llvm-s-rfc-c-buffer-hardening-at-google). We should be doing this too.
This is part 1 in a small series to fix `-Wunsafe-buffer-usage` warnings in Electron. My intent is to fix all of them and then add the clang warning to our cflags.
We have 44 such warnings in `shell/`. This PR fixes the first three :smile_cat: 
```sh
46362:../../electron/shell/app/command_line_args.cc:18:20: warning: unsafe pointer arithmetic [-Wunsafe-buffer-usage]
46365:../../electron/shell/app/command_line_args.cc:18:20: note: pass -fsafe-buffer-usage-suggestions to receive code hardening suggestions …
```
> fix: -Wunsafe-buffer-usage warnings in IsUrlArg()

- shell/browser/web_contents_permission_helper.cc
We are seeing a bug where `navigator.getUserMedia` is falsely reporting incorrect (`denied`) permissions when attempting to retrieve screen sharing permissions despite screen share TTC permissions being `allowed`. This bug is triggered when `camera` permissions are denied.
This PR changes the if statements so we only do this check when trying to return `getUserMedia` results for camera and microphone.
Notes:  fixed bug where camera permissions affected screen sharing
> fix: systemMediaPermissionDenied should not check camera perms when the request is asking for screen share

- shell/app/electron_main_delegate.cc
- shell/browser/api/electron_api_app.cc
When an electron app is launched by another app ensure that the XDG_ACTIVATION_TOKEN env var is read and used for activation using xdg_activation_v1 protocol.
Set the activation token received from XDG_ACTIVATION_TOKEN env var so that it is used to activate the window both for the first instance of an electron app as well a subsequent instance that uses [app.requestSingleInstanceLock()](https://www.electronjs.org/docs/latest/api/app#apprequestsingleinstancelockadditionaldata) to pass the control to an existing instance.
For reference, see:
- https://wayland.app/protocols/xdg-activation-v1
- https://issues.chromium.org/issues/40747285
- https://chromium-review.googlesource.com/c/chromium/src/+/5280365
Fixes an issue that still remains for https://github.com/electron/electron/issues/30912. …
> fix: Use XDG_ACTIVATION_TOKEN in wayland when launched by other app

- shell/common/gin_converters/file_path_converter.h
Upstream marked v8::String::Value as `V8_DEPRECATE_SOON` last month, so let's stop using it.
The replacement code mostly does the same as v8::String::Value()''s implementation; but since our test only cares about the length and not the contents, we also get a nice little perf win of not needing to allocate a char array and not needing to call Local::String::Write().
- [Upstream V8_DEPRECATE_SOON change](https://chromium-review.googlesource.com/c/v8/v8/+/5667299)
- Upstream's [v8::String::Value() impl](https://chromium.googlesource.com/v8/v8/+/20226b740bfa1a1e46dff80363232dfd3da50de8/src/api/api.cc#10883)
- History on why we used it in #19792: [1](https://github.com/electron/electron/pull/19792/commits/80c1a9739d191d2e393e56e2b254fb72bf6859e9), …
> fix: don't use deprecate-soon class v8::String::Value

- appveyor-woa.yml
- appveyor.yml
This PR fixes symbol generation on Windows - currently, autoninja is failing on PowerShell commands with an error which is swallowed when running the command in cmd. This will unblock release builds.
Notes: none
> build: don't run symbol generation on PS

- shell/common/gin_helper/event_emitter_template.cc
Xref: https://chromium-review.googlesource.com/c/v8/v8/+/5600627
[api] Mark v8::Object::GetPrototype() for deprecation
Notes: none.
> chore: migrate to v8::Object::SetPrototypeV2()

- shell/renderer/api/context_bridge/object_cache.cc
- shell/renderer/api/context_bridge/object_cache.h
Followup to #27639
This cache is a `v8::Object`-to-`v8::Local<v8::Value>` lookup.
We're currently using `v8::Local<v8::Object>` as the key in a two-step process: first we hash the object as a `std::unordered_map` key. Second, we walk through a linked list of previously-cached `v8::Local<v8::Object>`s looking for one that  matches our key. Handles check for equality via `v8::HandleHelper::EqualHandles()`, so this is basically just testing pointers for equality (`a.ptr() == b.ptr()`).
This PR skips the middle steps and just uses a ~~`v8::Object*`~~ `v8::Local<v8::Object>` as the key
Notes: none.
> perf: use v8::Local<v8::Object> as the key in ObjectCache

- appveyor-woa.yml
- appveyor.yml
autoninja has been throwing an error in Windows builds:
```
ERROR:root:Expecting value: line 1 column 1 (char 0)
```
eg see https://ci.appveyor.com/project/electron-bot/electron-x64-release/builds/50534902/job/m4hntgux7tc9xdva#L59117
It turns out that https://chromium-review.googlesource.com/c/chromium/tools/depot_tools/+/5669094 caused this error and we can work around it by creating a file called `build_telemetry.cfg` in the depot_tools directory.
This change is not needed for GHA as the error doesn't surface there, probably due to the fact that builds there run through `e build` instead of calling autoninja directly.
Notes: none
> build: fix telemetry error when using autoninja

- docs/api/context-bridge.md
`ipcRenderer` when sent over `contextBridge` will be empty for security reasons. This is mentioned in the breaking changes but it should also be mentioned on the contextBridge page itself.
Notes: none
> docs: explain ipcRenderer behavior in context-bridge.md

- .github/actions/build-electron/action.yml
As in title.  Otherwise we'd be running e.g. `autoninja electron:electron_symbols -j 200 electron` which isn't quite right.
Notes: none
> build: use proper targets for building

- shell/common/api/electron_api_url_loader.cc
Part 2 in a [series](https://github.com/electron/electron/pull/43477) to fix `-Wunsafe-buffer-usage` warnings in electron `shell/`.
This PR fixes warnings in `electron_api_url_loader.cc` by using [v8::ArrayBufferView::CopyContents()](https://chromium.googlesource.com/v8/v8/+/287f5002404a3d08df6b42de1081f89ace1927ea/include/v8-array-buffer.h#386) instead of doing the pointer math ourselves. This fixes the warnings, results in simpler code, and may also avoid some additional overhead:
> Copy the contents of the ArrayBufferView's buffer to an
> embedder defined memory without additional overhead that
> calling ArrayBufferView::Buffer might incur.
```
../../electron/shell/common/api/electron_api_url_loader.cc:250:24: error: function introduces unsafe buffer …
```
> fix: -Wunsafe-buffer-usage warnings in url-loader

- patches/chromium/feat_add_support_for_missing_dialog_features_to_shell_dialogs.patch
Closes https://github.com/electron/electron/issues/43310.
The minimum version of `org.freedesktop.portal.FileChooser` containing support for setting a defaultPath via `current_folder` in https://github.com/flatpak/xdg-desktop-portal/commit/71165a52ea6ba164816131ea039ccea253fe103b is 4. Chromium [requires version 3](https://source.chromium.org/chromium/chromium/src/+/main:ui/shell_dialogs/select_file_dialog_linux_portal.cc;l=47?q=kXdgPortalRequiredVersion&sq=package:chromium&type=cs) in order to use the interface, otherwise they fall back to GTK. Our dialog API requires that `defaultPath` work both on open and save dialogs - we can ensure this by bumping the required minimum to 4 before falling back to GTK.
The interface version bump commit is …
> fix: ensure version of `xdg-dialog-portal` with `defaultPath` support

- shell/app/uv_task_runner.cc
- shell/app/uv_task_runner.h
- shell/common/node_bindings.h
Fixes our UvTaskRunner to release uv handles correctly. The [libuv docs say](https://docs.libuv.org/en/v1.x/handle.html#c.uv_close):
> [uv_close()] MUST be called on each handle before memory is released. Moreover, the memory can only be released in close_cb or after it has returned.
Previously, our UvTaskRunner destructor cleaned up any remaining handles by unreffing them and then immediately deleting them. This PR changes that to use the `UvHandle` wrapper class from `node_bindings.h`. since [that class exists to follow libuv's close-then-free lifecycle correctly](https://github.com/electron/electron/pull/25332).
This PR also adds some new work to `UvHandle` to allow it to be used as a map key (follow the [rule of five](https://en.cppreference.com/w/cpp/language/rule_of_three), add a …
> fix: delete UvTaskRunner's timers only after they're closed

- shell/browser/api/message_port.cc
Small fix to confirm that a `Local<Value>` is a `Local<Object>` before casting it as one.
Looks like doing the other way around can cause a crash when`Local.As()` calls `Local.Cast()` if `V8_ENABLE_CHECKS` is defined and the Value isn't an Object?
Notes: none.
> fix: confirm a `v8::Value` is a `v8::Object` before casting it

- shell/browser/api/electron_api_base_window.cc
- shell/browser/native_window.h
- shell/browser/native_window_mac.mm
- shell/browser/native_window_views.cc
Cleanup PR to make `NativeWindow::Create()` follow Chromium's  [object ownership calling conventions](https://chromium.googlesource.com/chromium/src/+/main/styleguide/c++/c++.md#object-ownership-and-calling-conventions): ownership of the new object is being handed off to the caller, so return it as a `std::unique_ptr<NativeWindow>`.
Related: #43361
Notes: none.
> refactor: `NativeWindow::Create()` returns a unique_ptr

- shell/common/asar/archive.cc
- shell/common/asar/asar_util.cc
- shell/common/asar/asar_util.h
- shell/common/asar/scoped_temporary_file.cc
Small refactor in asar that lays groundwork for a `-Wunsafe-buffer-usage` fix:
- Change ValidateIntegrityOrDie() to take a span<const uint8_t> arg. We'll need this to migrate asar's base::File API calls away from the ones tagged `UNSAFE_BUFFER_USAGE` because the safe counterparts use span<uint8_t> too. (examples: [1](https://chromium.googlesource.com/chromium/src/+/main/base/files/file.h#224), [2](https://chromium.googlesource.com/chromium/src/+/main/base/files/file.h#228))
- Simplify ValidateIntegrityOrDie()'s implementation by using crypto::SHA256Hash() instead of reinventing the wheel.
Notes: none.
> refactor: take a `uint8_t` span in `ValidateIntegrityOrDie()`

- shell/common/gin_helper/promise.cc
- shell/common/gin_helper/promise.h
Several Promise methods call `GetContext()` multiple times. From looking at the assembly in obj/electron/electron_lib/promise.o, these redundant calls are actually being made -- they aren't optmized out.
This PR keeps the return value in a local variable to avoid extra calls.
Notes: none.
> perf: avoid redundant Promise.GetContext calls

- lib/browser/api/browser-view.ts
Closes https://github.com/electron/electron/issues/43462
During BrowserView auto-resize, the new size is calculated using BrowserView#lastWindowSize, but lastWindowSize is never updated and remains the value from the initial window size. This results in BrowserView being resized incorrectly.
To fix this issue, we should update lastWindowSize to the current window size after it has been used.
Notes: Fixed BrowserView auto resize issue.
> fix: update `BrowserView#lastWindowSize` after window resize

- shell/common/gin_helper/microtasks_scope.cc
- shell/common/gin_helper/microtasks_scope.h
A small refactor to avoid an extra heap allocation/free when instantiating `gin_helper::MicrotasksScope` objects.
Notes: none.
> refactor: use std::optional in MicrotasksScope

- shell/common/gin_helper/event_emitter_caller.cc
- Fixes a minor bug in `gin_helper::internal::CallMethodWithArgs()` that created a `node::CallbackScope` with an out-of-scope resource handle. This comes from [this suggestion](https://github.com/electron/electron/pull/40576#discussion_r1400808904) to add a `HandleScope` before creating the `CallbackScope` in an early draft of #40576 when the `CallbackScope` had a shorter lifespan; but in the version that got merged, the callback scope outlives the handle scope.
- Small refinement to #42297: since we unconditionally return false if there's no Node environment, the CallbackScope doesn't need to be heap-allocated anymore.
- I also wrapped everything in an EscapeableHandleScope to ensure that we don't leak either the CallbackScope resource object or any side handles created by …
> fix: out-of-scope Local handle in node::CallbackScope

- shell/common/asar/archive.cc
- shell/common/asar/scoped_temporary_file.cc
Part 3 in a [series](https://github.com/electron/electron/pull/43477) to fix `-Wunsafe-buffer-usage` warnings in electron `shell/`.
This PR fixes warnings in `asar::Archive::Init()` and `ScopedTemporaryFile::InitFromFile()` by replacing `base::File` API calls marked `UNSAFE_BUFFER_USAGE` (examples: [1](https://chromium.googlesource.com/chromium/src/+/main/base/files/file.h#224), [2](https://chromium.googlesource.com/chromium/src/+/main/base/files/file.h#228)) with their safer counterparts. See also #43592, which was a prerequisite for this PR.
```
../../electron/shell/common/asar/archive.cc:210:11: error: function introduces unsafe buffer manipulation [-Werror,-Wunsafe-buffer-usage]
210 |     len = file_.ReadAtCurrentPos(buf.data(), buf.size());
| …
```
> fix: -Wunsafe-buffer-usage warnings in asar file IO

- shell/browser/api/electron_api_web_request.cc
- spec/api-web-request-spec.ts
Fixes #41939
Notes: Restored Chromium default `Content-Disposition` header parsing.
> fix: restore Chromium default `Content-Disposition` header parsing

- shell/common/v8_value_serializer.cc
Part 4 in a [series](https://github.com/electron/electron/pull/43477) to fix `-Wunsafe-buffer-usage` warnings in electron `shell/`.
This PR fixes a warning in `electron::V8Serializer::Serialize()`. It does this by using a correctly-sized `data_` field directly so that we don't need to make a call to `UNSAFE_BUFFER_USAGE base::make_span()`.
The warning fixed by this PR:
```
../../electron/shell/common/v8_value_serializer.cc:54:28: error: function introduces unsafe buffer manipulation [-Werror,-Wunsafe-buffer-usage]
54 |     out->encoded_message = base::make_span(buffer.first, buffer.second);
|                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../electron/shell/common/v8_value_serializer.cc:54:28: note: pass -fsafe-buffer-usage-suggestions to receive code hardening …
```
> fix: -Wunsafe-buffer-usage warning in V8Serializer::Serialize()

- shell/browser/electron_pdf_document_helper_client.cc
- shell/browser/electron_pdf_document_helper_client.h
Refs https://issues.chromium.org/issues/40469585
Ensure fillable PDF forms are able to be saved correctly with and without edits in all contexts.
Notes: Fixed a potential issue with fillable PDF forms saving correctly in some circumstances.
> fix: ensure `SetPluginCanSave` updated in PDFs

- shell/browser/ui/cocoa/delayed_native_view_host.mm
- spec/api-view-spec.ts
- spec/api-web-contents-view-spec.ts
Closes https://github.com/electron/electron/issues/43449.
It should be possible to call `win.contentView.addChildView(v1)` either before or after adding a `WebContentsView` as a child of a `View` `v1`. Prior to this PR, this functionality worked on Windows and Linux, but did not display and also caused a paint-related crash on macOS due to the call to `ViewHierarchyChanged` not being called correctly via `DelayedNativeViewHost`.
I believe at one point `NativeViewHost` had issues with children being attached, but in local testing I found no issues, and calling `ViewHierarchyChanged` in the superclass fixed the crash while still passing other tests.
Notes: Fixed an issue where `WebContentsView`s did not show correctly in some circumstances on macOS after being added as child views.
> fix: native `View` wrapper crash missing when adding child view

- shell/browser/ui/inspectable_web_contents.cc
- shell/browser/ui/inspectable_web_contents.h
Closes https://github.com/electron/electron/issues/36203.
Fixes an issue where clicking the eyedropper icon did nothing instead of opening an eyedropper for color selection as expected. To fix this, we needed to implement `OpenEyeDropper` in `InspectableWebContents`
<details><summary>After Fix</summary>
<p>
</p>
</details> 
Notes: Fixed an issue where clicking the eyedropper icon did nothing instead of opening an eyedropper for color selection as expected.
> fix: EyeDropper working in devtools

- shell/browser/badging/badge_manager_factory.cc
- shell/browser/badging/badge_manager_factory.h
- shell/browser/extensions/electron_extension_system_factory.cc
- shell/browser/extensions/electron_extension_system_factory.h
- shell/browser/file_system_access/file_system_access_permission_context_factory.cc
- shell/browser/file_system_access/file_system_access_permission_context_factory.h
- shell/browser/hid/hid_chooser_context_factory.cc
- shell/browser/hid/hid_chooser_context_factory.h
- shell/browser/net/network_context_service_factory.cc
- shell/browser/net/network_context_service_factory.h
- shell/browser/serial/serial_chooser_context_factory.cc
- shell/browser/serial/serial_chooser_context_factory.h
- shell/browser/usb/usb_chooser_context_factory.cc
- shell/browser/usb/usb_chooser_context_factory.h
Migrate `BrowserContextKeyedServiceFactory` subclasses to use non-deprecated API. 
Use-this-not-that:
```diff
- BrowserContextKeyedServiceFactory::BuildServiceInstanceFor()
+ BrowserContextKeyedServiceFactory::BuildServiceInstanceForBrowserContext()
```
The old call is deprecated because it uses raw unmanaged memory; the new call returns a `std::unique_ptr`. It's been deprecated for over a year and there are still a lot of upstream instances of the old code, so probably no urgent danger on this :calendar: 
Xref: https://chromium-review.googlesource.com/c/chromium/src/+/4082051
Notes: none.
> refactor: remove use of deprecated API BuildServiceInstanceFor()

- shell/browser/api/electron_api_debugger.cc
- shell/browser/api/electron_api_download_item.cc
- shell/browser/api/electron_api_net_log.cc
- shell/browser/api/electron_api_protocol.cc
- shell/browser/api/electron_api_service_worker_context.cc
- shell/browser/api/electron_api_session.cc
- shell/browser/api/electron_api_web_contents.cc
- shell/browser/hid/hid_chooser_controller.cc
- shell/browser/native_window_mac.mm
- shell/browser/usb/usb_chooser_context.cc
- shell/browser/usb/usb_chooser_controller.cc
- shell/common/crash_keys.cc
- shell/common/gin_converters/osr_converter.cc
- shell/common/node_bindings_mac.cc
- shell/common/node_util.cc
- shell/common/node_util.h
- shell/common/process_util.cc
- shell/common/process_util.h
- shell/common/skia_util.cc
Change the `EmitWarning()` helper functions:
```diff
+ EmitWarning(std::string_view msg, std::string_view type);
+ EmitWarning(v8::Isolate*, std::string_view msg, std::string_view type);
- EmitWarning(node::Environment*, std::string_view msg, std::string_view type);
```
All the old calls to `EmitWarning()` looked like this:
```c++
v8::Isolate* isolate = JavascriptEnvironment::GetIsolate();
node::Environment* env = node::Environment::GetCurrent(isolate);
EmitWarning(env, msg, type);
```
This refactor does two things:
1. It eliminates the get-isolate-from-JavascriptEnvironment-and-then-get-node-environment code repetition by moving it into `EmitWarning()`
2. It eliminates some incidental coupling with Node.js, e.g. there were several files that were only including Node headers in order to …
> refactor: add `EmitWarning(v8::Isolate*)` helper

- shell/browser/api/electron_api_system_preferences_win.cc
- shell/browser/api/electron_api_web_contents.cc
- shell/browser/api/electron_api_web_contents.h
- shell/browser/electron_crypto_module_delegate_nss.cc
- shell/browser/serial/serial_chooser_controller.cc
- shell/browser/ui/devtools_manager_delegate.cc
- shell/common/api/electron_api_clipboard.cc
- shell/common/api/electron_bindings.cc
- shell/common/gin_helper/promise.cc
- shell/common/gin_helper/promise.h
- shell/common/node_bindings.cc
Refactor some parts of `node_helper::Promise` to avoid code repetition:
- There were five methods with identical handle/microtask/context scopes setup before doing v8::Promise work. This PR extracts that setup into a new [`SettleScope`](https://github.com/electron/electron/blob/cd850238e8c0f2c4ff138c36bff01b6bf23b6e71/shell/common/gin_helper/promise.cc#L19) struct, borrowing the idea from [`SpellCheckScope`](https://github.com/electron/electron/blob/1c3a5ba5d17c18cbc1fc096d2a05fc24f2b2ddee/shell/renderer/api/electron_api_spell_check_client.h#L56).
- There were three methods with identical logic to decide whether to settle the promise immediately or to post it as a task. This PR extracts that logic into a new protected static method, `PromiseBase::GetTaskRunner()`. This has a happy …
> refactor: reduce code duplication in gin_helper::Promise

- shell/browser/ui/views/opaque_frame_view.cc
Closes https://github.com/electron/electron/issues/43714.
Fixes an issue where the resizing border was not being handled correctly on Linux WCO caption buttons. This is now taken into account as a part of the NonClientHitTest.
cc @bpasero 
Notes: Fixes an issue when dragging to resize when using Window Controls Overlay on Linux.
> fix: resizing border on Linux WCO caption buttons

- shell/common/gin_helper/event_emitter_caller.h
The two `Emit(isolate, obj, name, Args&&... args)` methods convert `args` into an array of `Local<Value>s`  to pass to Node/V8. But they don't use a HandleScope, so these temporary handles are leaked into the caller's scopes.
In most calls this is OK since either `args` is empty or since the caller creates a scope right before emission, but not everywhere. It's more reliable to handle this in the `Emit()` functions, so this PR adds `EscapableHandleScope`s to plug the leaks.
Notes: none.
> fix: in `Emit()`, don't leak converted Arg `Local<Values>` into caller's scope

- script/release/release.js
Ok, turns out this is a 302
Notes: none
> build: improve logging on http errors during release process (again, but more)

- .github/workflows/macos-publish.yml
- .github/workflows/pipeline-segment-electron-build.yml
In CI doing MAS after darwin is incredibly quick, for release builds it rebuilds basically everything (unclear why). This does the quick and dirty thing of splitting MAS and Darwin out into two jobs during publish to make them way quicker.
Notes: none
> build: split darwin/mas macOS publish jobs
