electron/electron

shell/common/gin_helper/event_emitter_caller.cc
shell/common/gin_helper/event_emitter_caller.h

A followup to #43729. We know the size of the args list at compile time, so we can use a statically-allocated array instead of a heap-allocated vector, e.g.
```diff
- std::vector<Local> items = { (args)... }
+ std::array<Local, sizeof...(args)> items = { (args)... }
```
Notes: none.

perf: hold `Emit()` arg arrays in a `std::array`

---

shell/common/gin_helper/callback.h

Same idea as https://github.com/electron/electron/pull/43750, but for `V8FunctionInvoker`'s args.
Since the number of args is known at compile time, we can avoid a little heap memory management by using a std::array instead of a std::vector, e.g.:
```diff
template<typename... Args>
void Foo(Args&&... args) {
...
-     std::vector<Local> local_args = { ConvertToV8(args)... };
+     std::array<Local, sizeof...(args)> local_args = { ConvertToV8(args)... };
...
}
```
Notes: none.

perf: hold `V8FunctionInvoker` args in a `std::array`

---

shell/browser/ui/inspectable_web_contents.cc
shell/browser/ui/inspectable_web_contents.h

Manually backport #43685 to 32-x-y. See that PR for details.
Notes: Fixed an issue where clicking the eyedropper icon did nothing instead of opening an eyedropper for color selection as expected.

fix: EyeDropper working in devtools (32-x-y)

---

.github/workflows/build.yml
patches/node/.patches
patches/node/build_compile_with_c_20_support.patch
script/spec-runner.js

Manually backport #43555 to 32-x-y. See that PR for details.
Notes: none

build: compile Node.js with C++20 support (32-x-y)

---

shell/browser/badging/badge_manager_factory.cc
shell/browser/badging/badge_manager_factory.h
shell/browser/extensions/electron_extension_system_factory.cc
shell/browser/extensions/electron_extension_system_factory.h
shell/browser/file_system_access/file_system_access_permission_context_factory.cc
shell/browser/file_system_access/file_system_access_permission_context_factory.h
shell/browser/hid/hid_chooser_context_factory.cc
shell/browser/hid/hid_chooser_context_factory.h
shell/browser/net/network_context_service_factory.cc
shell/browser/net/network_context_service_factory.h
shell/browser/serial/serial_chooser_context_factory.cc
shell/browser/serial/serial_chooser_context_factory.h
shell/browser/usb/usb_chooser_context_factory.cc
shell/browser/usb/usb_chooser_context_factory.h

Manual backport of https://github.com/electron/electron/pull/43690 to 32-x-y. See that PR for details.
Notes: none.

refactor: remove use of deprecated API `BuildServiceInstanceFor()` (32-x-y)

---

docs/tutorial/window-customization.md

Manually backport #43388 to 33-x-y. See that PR for details.
Notes: none.

docs: update window customization tutorial (33-x-y)

---

shell/browser/badging/badge_manager_factory.cc
shell/browser/badging/badge_manager_factory.h
shell/browser/extensions/electron_extension_system_factory.cc
shell/browser/extensions/electron_extension_system_factory.h
shell/browser/file_system_access/file_system_access_permission_context_factory.cc
shell/browser/file_system_access/file_system_access_permission_context_factory.h
shell/browser/hid/hid_chooser_context_factory.cc
shell/browser/hid/hid_chooser_context_factory.h
shell/browser/net/network_context_service_factory.cc
shell/browser/net/network_context_service_factory.h
shell/browser/serial/serial_chooser_context_factory.cc
shell/browser/serial/serial_chooser_context_factory.h
shell/browser/usb/usb_chooser_context_factory.cc
shell/browser/usb/usb_chooser_context_factory.h

Manually backport #43690 to 31-x-y. See that PR for details.
Notes: none.

refactor: remove use of deprecated API BuildServiceInstanceFor() (31-x-y)

---

shell/browser/ui/message_box_mac.mm

There are the error encountering stems from multiple methods named `highlight:` being found in different classes within the macOS AppKit framework. Since different classes (NSScroller, NSButton, NSTextView) have a method named `highlight:`, the compiler is unable to resolve which one should be used.
It happened on macOS 15 and Xcode 16.
To fix this, we need to make sure the compiler knows explicitly which class's method you intend to call.
```
../../electron/shell/browser/ui/message_box_mac.mm:87:7: error: multiple methods named 'highlight:' found with mismatched result, parameter type or attributes
87 |       [[ns_buttons objectAtIndex:settings.default_id] highlight:YES];
|       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ …
```

chore: fix compile issue about ambiguous error of multiple methods named 'highlight'.

---

shell/browser/electron_browser_client.cc
shell/browser/notifications/linux/notification_presenter_linux.cc
shell/browser/notifications/mac/notification_presenter_mac.mm
shell/browser/notifications/notification_presenter.h
shell/browser/notifications/win/notification_presenter_win.cc

Cleanup PR to make `NotificationPresenter::Create()` follow Chromium's  [object ownership calling conventions](https://chromium.googlesource.com/chromium/src/+/main/styleguide/c++/c++.md#object-ownership-and-calling-conventions): ownership of the new object is being handed off to the caller, so return it as a `std::unique_ptr<NotificationPresenter>`.
Related: #43361
Notes: none.

refactor: NotificationPresenter::Create() returns a std::unique_ptr<>

---

shell/common/api/electron_api_clipboard.cc

Part 5 in a [series](https://github.com/electron/electron/pull/43477) to fix `-Wunsafe-buffer-usage` warnings in electron `shell/`.
This PR fixes a warning in `electron::api::Clipboard::WriteBuffer()`. The warning happened while copying a `v8::ArrayBufferView` into a `mojo::BigBuffer`. Previously we did this by using an unsafe `base::span constructor` to feed to the big buffer. Like #43564, this PR uses [`v8::ArrayBufferView::CopyContents()`](https://chromium.googlesource.com/v8/v8/+/287f5002404a3d08df6b42de1081f89ace1927ea/include/v8-array-buffer.h#386) as an alternative to unsafe pointer math.
The warning fixed by this PR:
```
../../electron/shell/common/api/electron_api_clipboard.cc:115:29: error: function introduces unsafe buffer manipulation [-Werror,-Wunsafe-buffer-usage]
115 | …
```

fix: -Wunsafe-buffer-usage warnings in Clipboard::WriteBuffer()

---

docs/development/patches.md

Document a potential patching pitfall that surprised @mlaurencin, @jkleinsc, and me :dizzy: 
Notes: none.

docs: document Windows pitfall when updating patches

---

lib/browser/guest-window-manager.ts
spec/guest-window-manager-spec.ts

Closes https://github.com/electron/electron/issues/43740.
Passing `createWindow` to `webContents.setWindowOpenHandler` shouldn't call `webContents.loadURL` on the existing webContents - this brings the logic into parity with what happens when `createWindow` is not passed: https://github.com/electron/electron/blob/7a9cbcac9fead05f3523b1178147a57bf8726b02/lib/browser/guest-window-manager.ts#L85-L96
Notes: Fixed a potential issue accessing a child window document when overriding browserWindow creation via `setWindowOpenHandler`.

fix: `createWindow` shouldn't load URL for `webContents`

---

shell/browser/ui/inspectable_web_contents.cc

Part 6 in a [series](https://github.com/electron/electron/pull/43477) to fix `-Wunsafe-buffer-usage` warnings in electron `shell/`.
This PR fixes three warnings in `GetNextZoomLevel()`. The previous code is reasonable IMO but still kicks a clang warning because of its use of pointer math. :man_shrugging: This PR uses iterators and begin / end / find_if instead.
The warnings fixed by this PR:
```
../../electron/shell/browser/ui/inspectable_web_contents.cc:128:33: error: unsafe buffer access [-Werror,-Wunsafe-buffer-usage]
128 |     if (!blink::ZoomValuesEqual(kPresetZoomFactors[i], factor))
|                                 ^~~~~~~~~~~~~~~~~~
../../electron/shell/browser/ui/inspectable_web_contents.cc:128:33: note: pass -fsafe-buffer-usage-suggestions to receive code hardening suggestions …
```

fix: -Wunsafe-buffer-usage warnings in GetNextZoomLevel()

---

.github/dependabot.yml

This enables github actions and npm dependabot on all supported branches instead of just main, it always felt a bit weird that we had this enabled for main but not our release lines. Should reduce drift and remove the need to backport these if dependabot runs on everything.
Will need to keep this file up to date during the release process but doing that manually for now (once every two months) isn't the end of the world.
Notes: none

build: enable dependabot on supported branches

---

.github/dependabot.yml

Per the docs setting the PR limit to 0 keeps security updates but stops the "hey you wanna update this dep for no reason" PRs.
I left the "hey you wanna update this dep" PRs on for `main` with a limit of 2 per day because we should stay up to date with stuff, but like, it's not that important.
Notes: none

build: stop dependabot doing things

---

shell/browser/api/electron_api_web_contents.cc
shell/browser/api/electron_api_web_contents.h
shell/browser/bluetooth/electron_bluetooth_delegate.cc

Hide some of the printing implentation details in api::WebContents.
This is for two reasons:
1. Just standard good housekeeping of hiding implementation
2. `electron_api_web_contents.h` is included by a lot of Electron, and `print_view_manager_electron.h` pulls in a lot of other dependencies. Decoupling these two files removes a lot of unnecessary #includes.
Notes: none.

refactor: hide printing impl details in api::WebContents

---

shell/common/asar/archive.cc
shell/common/asar/archive.h

refactor: prefer member initializers in `asar::Archive`, `asar::Archive::FileInfo`, and `asar::IntegrityPayload`
Notes: none

refactor: prefer member initializers in asar structs

---

shell/browser/osr/osr_render_widget_host_view.h
shell/common/platform_util_win.cc

A small cleanup to remove use of the C-style function declaration idiom.
Notes: none

refactor: remove C-style void arg type for no-arg functions

---

shell/browser/serial/serial_chooser_controller.cc
shell/browser/serial/serial_chooser_controller.h

Add a `base::WeakPtr<WebContents>` field to `SerialChooserController` and stop subclassing from `WebContentsObserver`. This follows the Observer [docs](https://chromium.googlesource.com/chromium/src/+/HEAD/content/public/browser/web_contents_observer.h#96):
> don't create a `WebContentsObserver` just to be able to check
> for a null `WebContentsObserver::web_contents()`.
> Use a `base::WeakPtr<WebContents>` instead.
Notes: none.

refactor: add SerialChooserController::web_contents_

---

shell/browser/ui/cocoa/delayed_native_view_host.mm

Right now DelayedNativeViewHost attaches its underlying native view when it's being attached to a widget but it doesn't detach it when it's being detached. It may lead to use-after-free and crash.
We (in OpenFin) have different views hierarchy and lack of detaching a native views causes use-after-free during destruction of a window which contains some views. I was not able to get a repo on clean Electron but it seems wrong that we don't detach a native view and it may cause problems in different scenarios also on clean Electron.
Notes: Fixed potential use-after-free during view removal on macOS.

fix: detach native view when its removed from parent on macOS

---

shell/common/asar/asar_util.cc

Part 7 in a [series](https://github.com/electron/electron/pull/43477) to fix `-Wunsafe-buffer-usage` warnings in electron `shell/`. This fixes an asar `base::File` API call, similar to [an earlier](https://github.com/electron/electron/pull/43624) asar fix in the series.
The warning fixed by this PR:
```
../../electron/shell/common/asar/asar_util.cc:130:7: error: function introduces unsafe buffer manipulation [-Werror,-Wunsafe-buffer-usage]
130 |       src.Read(info.offset, const_cast<char*>(contents->data()),
|       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
131 |                contents->size())) {
|                ~~~~~~~~~~~~~~~~~
../../electron/shell/common/asar/asar_util.cc:130:7: note: pass -fsafe-buffer-usage-suggestions to receive code hardening suggestions
``` …

fix: -Wunsafe-buffer-usage warning in asar_util's ReadFileToString()

---

shell/browser/api/electron_api_web_contents.cc
spec/api-web-contents-spec.ts

Closes https://github.com/electron/electron/issues/43818.
Fixes an issue where calling `Focus` on a `WebView`'s `webContents` would trigger a fatal `NOTREACHED` error. Attaching a webContents as an inner contents via `AttachInnerWebContents` results in the contents' view being a `WebContentsViewChildFrame`, which has never implemented `Focus`.
This happened as a result of CL:5539619 - it never worked before, but now crashed instead of silently failing.
Notes: Fixed a crash when calling `focus` on a `WebView`'s `webContents`.

fix: crash when focusing `WebView` `webContents`

---

BUILD.gn
shell/browser/notifications/linux/libnotify_notification.cc
spec/api-notification-dbus-spec.ts

This PR ensures that the `sender-pid` hint is set for new notifications. It also updates the spec to confirm that DBus receives the hint and that it has the correct value.
This fixes a spec failure when running libnotify >= 0.7.12 (2022-05-05). Starting with that version, libnotify [started injecting `sender-pid` if not provided by the client](https://github.com/GNOME/libnotify/commit/1fba04bc032ad65bedf43e74c2d53121440613f4#diff-e8f7068b3a06ea7f520fc8773e06c46d3ad2f97ff78a7c16a6394030e587d115R824). So our tests received a slightly different DBus payload depending on the libnotify version, causing our deep-equals tests to fail.
By always providing and testing the `sender-pid` hint, both our behavior and our tests should be consistent across distros.
Sample test failure:
```
not ok 1 …
```

test: ensure `sender-pid` hint is set in Linux notifications

---

docs/breaking-changes.md
spec/api-browser-window-spec.ts
spec/extensions-spec.ts

- #43454 and #43769 disabled tests as part of the chromium rolls.  This PR re-enables/fixes those tests.
- Additionally when resolving the test for #43454, I found that there was a breaking change introduced in that PR via https://chromium-review.googlesource.com/c/chromium/src/+/5802682.  This PR adds a section to breaking-changes documenting this breaking change.
- Resolves #43730
Notes: none

test: re-enable tests that were disabled in chromium rolls

---

shell/browser/ui/gtk_util.cc

OK, now that #43938 has some tests in place for `GdkPixbufFromSkBitmap()`... This is part 8 in a [series](https://github.com/electron/electron/pull/43477) to fix `-Wunsafe-buffer-usage` warnings in electron `shell/`. This one fixes these `GdkPixbufFromSkBitmap()` warnings:
```
../../electron/shell/browser/ui/gtk_util.cc:87:31: error: unsafe buffer access [-Werror,-Wunsafe-buffer-usage]
87 |       uint32_t pixel = bitmap.getAddr32(0, y)[x];
|                        ~~~~~~~^~~~~~~~~~~~~~~
../../electron/shell/browser/ui/gtk_util.cc:87:31: note: pass -fsafe-buffer-usage-suggestions to receive code hardening suggestions
../../electron/shell/browser/ui/gtk_util.cc:92:9: error: unsafe buffer access [-Werror,-Wunsafe-buffer-usage]
92 |         divided[i + 0] = SkColorGetR(unmultiplied);
| …
```

fix: -Wunsafe-buffer-usage warnings in GdkPixbufFromSkBitmap()

---

shell/browser/ui/gtk_util.cc

When using `g_dgettext(domain, str)` calls to get GTK strings, build the domain string at compile time rather than runtime. Nothing world-changing, but a nice cleanup:
- faster
- one less instance of `base::NoDestructor`
- one less instance of `// nogncheck`
- removes the need for `gtk::GtkVersion()` and `base::NumberToString()`
Notes: none.

perf: build g_dgettext domain name at compile time

---

shell/app/electron_content_client.cc
shell/browser/api/electron_api_web_contents.cc
shell/browser/browser_linux.cc
shell/browser/electron_browser_client.cc
shell/browser/extensions/electron_extensions_api_client.cc
shell/browser/notifications/linux/libnotify_notification.cc
shell/browser/ui/file_dialog_linux.cc
shell/common/application_info_linux.cc
shell/common/platform_util_linux.cc

Remove a handful of `#include "foo" // nogncheck` calls that weren't actually being used. Inspired by https://github.com/electron/electron/pull/43960.
Notes: none.

chore: remove unused nogncheck includes

---

lib/browser/api/browser-view.ts

Closes https://github.com/electron/electron/issues/43927.
Fixed an issue where an exception could be thrown on BrowserView after its owner BrowserWindow was closed. We need to ensure the resize listener is removed on closed to fix this. It relies on a race condition so we really can't add a test for it.
Notes: Fixed an issue where an exception could be thrown on BrowserView after its owner BrowserWindow was closed.

fix: remove resize listener when BrowserWindow closed

---

appveyor-woa.yml
appveyor.yml

Windows testing (on x64 and ia32) on AppVeyor was throwing the following error during testing:
```ERROR:logging.cc(148)] Failed to init logging: Access is denied. (0x5)```
I investigated this error and it appears that it is simply a contention issue writing to an error log. (https://ci.appveyor.com/project/electron-bot/electron-ia32-testing/builds/50689680/job/hw1k8991ug0jkkve contains some additional debugging to try to track down this issue). In looking at the rest of our CI configurations, we do not write to an error log file but instead log errors to the console.  This PR moves our Windows testing on AppVeyor to write logging to the console to be consistent with the rest of CI.
Notes: none

ci: write test logging to console on Windows

---

shell/browser/electron_pdf_document_helper_client.cc
spec/api-web-contents-spec.ts

Manually backport #43943 to 33-x-y. See that PR for details.
Notes: none.

fix: ensure correct `WebContents` when checking `PDFReadyToPrint` (33-x-y)

---

BUILD.gn
filenames.gni
shell/browser/electron_browser_client.cc
shell/browser/printing/printing_utils.cc

Fix a FTBFS regression in 33-x-y and main that prevents Electron from building when plugins are disabled.
CC @mlaurencin 
Notes: Fixed a build failure when the `enable_plugins` build flag is false.

fix: FTBFS when building with `enable_plugins = false`

---

docs/api/utility-process.md
shell/browser/api/electron_api_utility_process.cc
shell/browser/api/electron_api_utility_process.h
shell/common/node_includes.h
shell/services/node/node_service.cc
shell/services/node/node_service.h
shell/services/node/public/mojom/node_service.mojom
spec/.gitignore
spec/api-utility-process-spec.ts
spec/fixtures/api/utility-process/external-ab-test.js
spec/fixtures/native-addon/external-ab/binding.cc
spec/fixtures/native-addon/external-ab/binding.gyp
spec/fixtures/native-addon/external-ab/lib/test-array-buffer.js
spec/fixtures/native-addon/external-ab/package.json
spec/package.json
spec/yarn.lock

Manually backport #43774 to 33-x-y. See that PR for details.
Notes: Add error event in utility process to support diagnostic reports on V8 fatal errors

feat: add error event for utility process (33-x-y)

---

shell/browser/extensions/electron_component_extension_resource_manager.cc
shell/browser/extensions/electron_component_extension_resource_manager.h

Part 10 in a [series](https://github.com/electron/electron/pull/43477) to fix `-Wunsafe-buffer-usage` warnings in `shell/`.
The change is very simple this time: replace the pointer-and-size-args idiom with a `base::span`:
```diff
- foo(const Item* items, size_t n_items)
+ foo(const base::span<const Item> items)
```
```
../../electron/shell/browser/extensions/electron_component_extension_resource_manager.cc:91:38: error: unsafe buffer access [-Werror,-Wunsafe-buffer-usage]
91 |         base::FilePath().AppendASCII(entries[i].path);
|                                      ^~~~~~~
../../electron/shell/browser/extensions/electron_component_extension_resource_manager.cc:91:38: note: pass -fsafe-buffer-usage-suggestions to receive code hardening suggestions …
```

fix: -Wunsafe-buffer-usage warnings in AddComponentResourceEntries()

---

shell/browser/font_defaults.cc

Manually backport #44014 to 32-x-y. See that PR for details.
Changes from `main` / `33-x-y`:
- Fix minor `#include` shear
- `base::RStringSplitOnce()` doesn't exist in Chromium 128, so use `std::string_view::rfind()` instead
Notes: none.

fix: -Wunsafe-buffer-usage in electron::SetFontDefaults() (32-x-y)

---

appveyor-woa.yml
appveyor.yml
script/setup-win-for-dev.bat

This PR updates our Appveyor build images from Node 20.9 to Node 20.17
Note for backports: these will need to be manually backported, but adding the labels to ensure the backports happen and is cleanly documented.
Notes: none

build: update appveyor to node 20.17

---

script/release/prepare-release.ts

Missed this in the tsification, we should probably call this via API instead of spawning a sub-proc?
Notes: none

build: use ts-node to spawn the version-bumper

---

shell/common/api/electron_api_native_image.cc
shell/common/api/electron_api_url_loader.cc

A small little cleanup. This PR replaces our two `v8::ArrayBuffer.GetBackingStore()->Data()` calls with `v8::ArrayBuffer.Data()`. The V8 docs say the latter is a "more efficient shortcut" of the former:
> More efficient shortcut for GetBackingStore()->Data(). The
> returned pointer is valid as long as the ArrayBuffer is alive.
Notes: none.

perf: use ArrayBuffer::Data() instead of GetBackingStore()->Data()

---

shell/browser/ui/webui/accessibility_ui.cc

Part 12 in a [series](https://github.com/electron/electron/pull/43477) to fix `-Wunsafe-buffer-usage` warnings in `shell/`.
Both part 11 and 12 today are pretty easy.  This one's similar to https://github.com/electron/electron/pull/44024: upstream declares the length of some kConstantArray, which means that array is Spannable. We can pass it directly to functions taking a span argument and don't need to use the unsafe version of `make_span()`.
For example,`gen/chrome/grit/accessibility_resources_map.h` has these declarations:
```c++
extern const webui::ResourcePath AccessibilityResources[3];
extern const size_t kAccessibilityResourcesSize;
```
So we can change our code:
```diff
- FunctionThatTakesASpanArg(std::make_span(kAccessibilityResources, kAccessibilityResourcesSize));
+ …
```

fix: -Wunsafe-buffer-usage warnings in ElectronAccessibilityUI ctor

---

shell/renderer/api/electron_api_web_frame.cc

Part 11 in a [series](https://github.com/electron/electron/pull/43477) to fix `-Wunsafe-buffer-usage` warnings in `shell/`.
This one is pretty easy: Use [`base::span_from_ref()`](https://chromium-review.googlesource.com/c/chromium/src/+/5181774) to create a single-element span:
```diff
Foo foo;
- auto foo_span = base::make_span(&foo, 1u);
+ auto foo_span = base::span_from_ref(foo);
```
Warning fixed by this PR:
```
../../electron/shell/renderer/api/electron_api_web_frame.cc:656:47: error: function introduces unsafe buffer manipulation [-Werror,-Wunsafe-buffer-usage]
656 |         blink::DOMWrapperWorld::kMainWorldId, base::make_span(&source, 1u),
|                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../electron/shell/renderer/api/electron_api_web_frame.cc:656:47: …
```

fix: -Wunsafe-buffer-usage warnings in WebFrameRenderer::ExecuteJavaScript()

---

script/release/uploaders/upload-to-github.ts

Looks like this was inconsistent across branches somehow, let's align syntax to make backports clean
Notes: none

build: ensure consistent usage of getRepo

---

script/release/bin/README.md
script/release/bin/cleanup-release.ts
script/release/bin/prepare-for-release.ts
script/release/bin/print-next-version.ts
script/release/bin/publish-to-github.ts
script/release/bin/publish-to-npm.ts
script/release/bin/run-release-builds.ts
script/release/bin/validate-before-publish.ts
script/release/get-asset.ts
script/release/notes/index.ts
script/release/notes/notes.ts
script/release/prepare-release.ts
script/release/release-artifact-cleanup.ts
script/release/release.ts
script/release/run-release-ci-jobs.ts
script/release/types.ts
script/release/uploaders/upload-to-github.ts

This will require Sudowoodo changes as well, but this layout of `bin` scripts separate from the actual implementations should make things a lot cleaner and easier to understand. I also added documentation for the scripts we currently have, along with a note that one of them should be nuked from existence.
I did remove some now unused arguments and simplified the `--stable` flag into just checking the `bumpType` we already had.
This also gets rid of the confusing `--dryRun` style code which realistically followed entirely different code paths, instances of this pattern have been replaced with two explicitly named `bin` entry points. E.g. see `print-next-version` instead of `prepare-release --dryRun`.
This should be backported to all branches simultaneously to avoid complicated logic in …

build: cleanup release scripts, separate cli entrypoints from logic

---

appveyor-bake.yml
appveyor-woa.yml
appveyor.yml
script/nan-spec-runner.js
script/spec-runner.js

This PR bumps our base images to Node 20.17
Notes: none

build: use node 20.17 on Windows

---

shell/renderer/api/electron_api_web_frame.cc

Manually backport https://github.com/electron/electron/pull/44053 to 32-x-y. See that PR for details.
Simple manual patching needed due to trivial `#include` shear.
Notes: none.

fix: -Wunsafe-buffer-usage warnings in WebFrameRenderer::ExecuteJavaScript() (32-x-y)

---

shell/browser/notifications/win/windows_toast_notification.cc

Replace a call of deprecated API `base::Hash()` with `base::FastHash()` instead.
From `base/hash/hash.h`:
```c++
// Deprecated: Computes a hash of a memory buffer, use FastHash() instead.
// If you need to persist a change on disk or between computers, use
// PersistentHash().
// TODO(crbug.com/40107835): Migrate client code to new hash function.
BASE_EXPORT uint32_t Hash(const std::string& str);
```
Notes: none.

fix: remove use of deprecated API base::Hash()

---

shell/common/api/electron_api_native_image.cc
shell/common/api/electron_api_url_loader.cc

Manually backport #44067 to 32-x-y. See that PR for details.
Simple manual patching needed due to context shear from the `base::StringPiece` -> `std::string_view` migration.
Notes: none.

perf: use ArrayBuffer::Data() instead of GetBackingStore()->Data() (32-x-y)

---

shell/browser/net/asar/asar_file_validator.cc
shell/browser/net/asar/asar_file_validator.h

Part 13 in a [series](https://github.com/electron/electron/pull/43477) to fix `-Wunsafe-buffer-usage` warnings in `shell/`. This one migrates a handful of deprecated / unsafe crypto API calls in `AsarFileValidator`.
Warning fixed by this PR:
```
2024-10-01T01:27:56.0161997Z ../../electron/shell/browser/net/asar/asar_file_validator.cc:63:34: error: unsafe pointer arithmetic [-Werror,-Wunsafe-buffer-usage]
2024-10-01T01:27:56.0162901Z    63 |     current_hash_->Update(buffer.data() + bytes_added, bytes_to_hash);
2024-10-01T01:27:56.0163362Z       |                           ~~~~~~~^~~~~~
2024-10-01T01:27:56.0164170Z ../../electron/shell/browser/net/asar/asar_file_validator.cc:63:34: note: See //docs/unsafe_buffers.md for help.
```
It also removes use of [these deprecated SecureHash …

fix: deprecated API and -Wunsafe-buffer-usage warnings in AsarFileValidator

---

patches/node/cli_remove_deprecated_v8_flag.patch

Fix some patch shear introduced into `main` yesterday by competing Chromium & Node rolls
Notes: none.

fix: context shear in cli_remove_deprecated_v8_flag.patch

---

appveyor-woa.yml
appveyor.yml

Fixes issue on release builds where it was trying to upload test results when there were no test results.
Notes: none

ci: only upload to datadog when running tests

---

docs/api/cookies.md
shell/browser/api/electron_api_cookies.cc
spec/api-session-spec.ts

When testing samesite/sameparty cookies, we found a subtle regression after switching to the DomainIs implementation where the cookies were no longer being set. This PR reverts that refactor before Electron 33 stable until we can identify why the DomainIs implementation changes this.
Reverts https://github.com/electron/electron/pull/43262
Notes: none

refactor: revert url::DomainIs() for cookie domains

---

shell/common/heap_snapshot.cc

Part 16 in a [series](https://github.com/electron/electron/pull/43477) to fix `-Wunsafe-buffer-usage` warnings in Electron `shell/`. This PR fixes a minor API mismatch between Chromium's [spanification](https://groups.google.com/a/chromium.org/g/chromium-dev/c/iEy69ygz-rs) and `v8::OutputStream::WriteAsciiChunk(char* data, int size)`. 
Fixed by this PR:
```
2024-10-04T05:37:05.4109190Z ../../electron/shell/common/heap_snapshot.cc:27:26: error: function introduces unsafe buffer manipulation [-Werror,-Wunsafe-buffer-usage]
2024-10-04T05:37:05.4110250Z    27 |     auto bytes_written = file_->WriteAtCurrentPos(data, size);
2024-10-04T05:37:05.4110860Z       |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2024-10-04T05:37:05.4111530Z …
```

fix: -Wunsafe-buffer-usage warning in WriteAsciiChunk()

---

shell/renderer/api/electron_api_spell_check_client.cc

Part 15 in a [series](https://github.com/electron/electron/pull/43477) to  fix `-Wunsafe-buffer-usage` warnings in Electron `shell/`. This one works around an unchecked-pointer-dereference warning generated inside icu's `U16_NEXT()` macro. It fixes it by replacing the `U16_NEXT()` call with a `base::ReadUnicodeCharacter()` instead -- which we should arguably be using anyway, since we should prefer base API over third-party API.
NB: `base::ReadUnicodeCharacter()` takes still uses pointer-and-length arguments that [spanification](https://groups.google.com/a/chromium.org/g/chromium-dev/c/iEy69ygz-rs) is trying to avoid, so :man_shrugging: we'll probably need a one-liner followup PR to this if/when upstream changes this to take a span arg.
``` …
```

fix: -Wunsafe-buffer-usage warning in HasWordCharacters()

---

shell/common/api/electron_api_native_image.cc
shell/common/api/electron_api_native_image.h
shell/common/api/electron_api_native_image_mac.mm
shell/common/node_util.cc
shell/common/node_util.h
shell/common/skia_util.cc
shell/common/skia_util.h

This PR makes our C++ image API span-friendly and provides `get_byte_span()` getters for Node.js buffers and for NSData objects. The latter fixes one of our remaining `-Wunsafe-buffer-usage` warnings, making this PR part 14 in the [unsafe buffer PR series](https://github.com/electron/electron/pull/43477).
APIs changed to take a `base::span` instead of `data, len` params:
- `electron::api::NativeImage::CreateFromJPEG()`
- `electron::api::NativeImage::CreateFromPNG()`
- `electron::util::AddImageSkiaRepFromBuffer()`
- `electron::util::AddImageSkiaRepFromJPEG()`
- `electron::util::AddImageSkiaRepFromPNG()`
```
2024-10-04T05:37:14.0643890Z ../../electron/shell/common/api/electron_api_native_image_mac.mm:131:11: error: function introduces unsafe buffer manipulation …
```

refactor: spanify image utils

---

.github/workflows/pipeline-segment-electron-test.yml
appveyor-woa.yml
appveyor.yml

Fork PRS can't call datadog test logging so disable for foks.
Notes: none

ci: don't call datadog test logging on forks

---

docs/api/utility-process.md

It's useful to mention in the docs that the `exit` event is emitted no matter if you listen to the `error` event or not.
CC @deepak1556
Notes: none

docs: clarify interplay between utility process events

---

shell/browser/electron_browser_main_parts_posix.cc

Part 17 in a [series](https://github.com/electron/electron/pull/43477) to fix `-Wunsafe-buffer-usage` warnings in Electron `shell/`.  This PR fixes warnings generated when `read()`ing and `write()`ing an `int` type during shutdown handling in `ElectronBrowserMainParts`.
```
../../electron/shell/browser/electron_browser_main_parts_posix.cc:56:15: error: unsafe pointer arithmetic [-Werror,-Wunsafe-buffer-u
sage]
56 |               reinterpret_cast<const char*>(&signal) + bytes_written,
|               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../base/posix/eintr_wrapper.h:31:29: note: expanded from macro 'HANDLE_EINTR'
31 |     eintr_wrapper_result = (x); \
|                             ^
../../electron/shell/browser/electron_browser_main_parts_posix.cc:56:15: …
```

fix: -Wunsafe-buffer-usage warnings when read()ing and write()ing integers

---

shell/browser/ui/inspectable_web_contents.cc

Manual backport of #44149 to 31-x-y. See that PR for details.
Notes: none

fix: -Wunsafe-buffer-usage warnings in GetNextZoomLevel() (#44149)

---

shell/browser/electron_browser_main_parts_posix.cc

Manual backport of #44185 to 31-x-y. See that PR for details.
Notes: none

fix: -Wunsafe-buffer-usage warnings when read()ing and write()ing integers (31-x-y)

---

script/split-tests.js
spec/index.js

I realized looking at the backports of #44037 that it did not actually run the visibility tests first.  The backports have been corrected before merging, but this fix is needed for main.
Notes: none

test: run visibility-state-spec.ts first

---

patches/v8/.patches
patches/v8/cherry-pick-81155a8f3b20.patch
patches/v8/cherry-pick-9542895cdd3d.patch

<details>
<summary>electron/security#585 - 9542895cdd3d from v8</summary>
[wasm][streaming] Properly check max module size
and allow d8-based tests for it.
Fixed: 368241697
Change-Id: Iddc9f7e669de7a1d79dccbc99bcc5fb43dad67a1
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/5886728
Reviewed-by: Clemens Backes <clemensb@chromium.org>
Reviewed-by: Matthias Liedtke <mliedtke@chromium.org>
Auto-Submit: Jakob Kummerow <jkummerow@chromium.org>
Commit-Queue: Jakob Kummerow <jkummerow@chromium.org>
Cr-Commit-Position: refs/heads/main@{#96272}
</details>
<details>
<summary>electron/security#586 - 81155a8f3b20 from v8</summary>
[turbofan] Consider WasmStruct in InferHasInPrototypeChain
Drive-by: add some CHECKs in not _clearly_ safe uses of AsJSObject
to turn possible vulnerablities …

chore: cherry-pick 2 changes from 3-M129

---

.devcontainer/docker-compose.yml

Fixes broken Codespaces resultant of docs-parser requiring Node.js > v20.11.0. Our Codespaces sha was outdated - this pulls in a newer one with compatible Node.js version.
Notes: none

build: update devcontainer sha

---

.github/workflows/branch-created.yml

Better to put the usage of `${{ ... }}` in an env variable so it's properly stringified if the `workflow_dispatch` input is improperly formed.
Notes: none

ci: use env variable in branch created workflow

---

docs/api/base-window.md

I noticed my `webContents` weren't getting destroyed when I closed my `BaseWindow`s. I thought this should be documented somewhere.
There's a chance I got something wrong. In that case, please let me know and I'll fix it. I mostly arrived at these results through experiments.
Notes: none

docs: add section on resource management to base-window.md

---

shell/browser/ui/win/taskbar_host.cc
shell/common/v8_util.cc

Part 19 in a [series](https://github.com/electron/electron/pull/43477) to fix `-Wunsafe-buffer-usage` warnings in `shell/`. This PR fixes warnings in an array loop in `TaskbarHost::SetThumbarButtons()` by adding `constexpr` and `std::array` so that the compiler has enough info to know that the array index is always valid.
Notes: none.

fix: -Wunsafe-buffer-usage warnings in TaskbarHost::SetThumbarButtons()

---

shell/browser/api/electron_api_utility_process.cc
shell/browser/api/electron_api_utility_process.h
spec/api-utility-process-spec.ts

Refs https://github.com/electron/electron/pull/42297
Closes https://github.com/electron/electron/issues/44012
Fixes an issue where the `exit` event could be emitted twice from the `utilityProcess`. `HandleTermination` is called from multiple callsites, and so we need to ensure we only process it for the first callsite.
Notes: Fixed an issue where the `exit` event could be emitted twice from the `utilityProcess`.

fix: ensure `utilityProcess` only emits one 'exit' event

---

shell/app/electron_library_main.mm
shell/app/electron_main_delegate.cc
shell/app/electron_main_delegate.h
spec/chromium-spec.ts

Fixes https://github.com/electron/electron/issues/44151
Notes: fix `trace-startup` not working on macOS

fix: trace-startup crashing child process on macOS

---

patches/chromium/fix_crash_when_saving_edited_pdf_files.patch

Refactors our existing PDF save approach to use the File System Access API and therefore match existing (deprecated) behavior in upstream. I've also upstreamed this at CL:5934369.
Notes: none

fix: use proper PDF save approach

---

patches/chromium/printing.patch

Closes https://github.com/electron/electron/issues/44096.
Fixes an issue where closing a window after printing on Linux triggered a crash. This happened as a result of `gtk::ClearAuraTransientParent()` assuming the `aura:Window` has a root window when in some cases it might not. I've upstreamed this at CL:5933946.
<details><summary>Details</summary>
<p>
```
Received signal 11 SEGV_MAPERR 000000000000
#0 0x649ce6dd0922
base::debug::CollectStackTrace() [../../base/debug/stack_trace_posix.cc:1044:7]
#1 0x649ce6db966a
base::debug::StackTrace::StackTrace() [../../base/debug/stack_trace.cc:245:20]
#2 0x649ce6dd0331
base::debug::(anonymous namespace)::StackDumpSignalHandler() [../../base/debug/stack_trace_posix.cc:463:3]
#3 0x7895a7e45320 (/usr/lib/x86_64-linux-gnu/libc.so.6+0x4531f)
#4 …
```

fix: Linux crash after `webContents.print()` with no parent window

---

.github/CODEOWNERS
.github/workflows/update_appveyor_image.yml

The workflow has been failing as the `ubuntu-latest` image comes with Node.js 18 and we weren't installing a specific version.
Also adds this workflow to CODEOWNERS for Releases WG since it wasn't covered before.
Notes: none

ci: use Node.js 20 in Bake AppVeyor Image workflow

---

docs/tutorial/devtools-extension.md

This update removes for the AngularJS Batarang extension from the list of Devtool Extension Support in the docs, as it has been deprecated and is no longer available in the [Chrome Web Store ](https://chrome.google.com/webstore/detail/angularjs-batarang/ighdmehidhipcmcojjgiloacoafjmpfk)and the extension is no longer [actively maintained](https://github.com/angular/batarang)
Notes: none

docs: removed AngularJS Batarang from the Devtool Extension Support

---

.github/actions/install-build-tools/action.yml
.github/workflows/pipeline-segment-electron-build.yml
.github/workflows/pipeline-segment-electron-gn-check.yml
appveyor-woa.yml
appveyor.yml

Followup to https://github.com/electron/build-tools/pull/658.  This will fix an issue using reclient's read only cache on fork PRs.
Additionally, it turns out for GHA we were installing build tools twice and logging into RBE twice, so I removed the additional calls.
Notes: none

chore: fixup reclient read only access on forks

---

shell/app/electron_library_main.mm
shell/app/electron_main_delegate.cc
shell/app/electron_main_delegate.h
spec/chromium-spec.ts

Backport of https://github.com/electron/electron/pull/44257
Notes: fix `trace-startup` not working on macOS

fix: trace-startup crashing child process on macOS (32-x-y)

---

patches/config.json
patches/skia/.patches
patches/skia/sksl_rp_prevent_overflow_when_computing_slot_allocation_size.patch
patches/v8/.patches
patches/v8/merged_maglev_fix_non-materialized_receiver_closure.patch

b5bb998be272be2f78d7c365002066bf9bd412cd from skia
ed8e1cf4b4a6d0f1c9acc990f22a562db9491703 from v8
Notes:
* Security: backported fix for CVE-2024-7966.
* Security: backported fix for CVE-2024-9370.

chore: backport 2 changes from 2-M127 to 0-M129

---

shell/common/language_util_linux.cc

Part 20 in a [series](https://github.com/electron/electron/pull/43477) to fix `-Wunsafe-buffer-usage` warnings in `shell/`.  
This PR silences a warning caused by a call to `g_get_language_names()`. It's unavoidable due to that function's API, so we silence the warning by wrapping the pointer math in an `UNSAFE_MACROS()` macro add a [`// SAFETY`](https://chromium.googlesource.com/chromium/src/+/main/docs/unsafe_buffers.md#suppressions) comment  explaining what's up.
Warning silenced by this PR:
```
../../electron/shell/common/language_util_linux.cc:25:24: error: unsafe pointer arithmetic [-Werror,-Wunsafe-buffer-usage]
25 |   for (; *languages; ++languages) {
|                        ^~~~~~~~~
../../electron/shell/common/language_util_linux.cc:25:24: note: See //docs/unsafe_buffers.md for …
```

fix: silence -Wunsafe-buffer-usage warning in GetPreferredLanguages()

---

patches/v8/.patches
patches/v8/merged_don_t_assume_all_turbofan_frames_are_javascript.patch
patches/v8/merged_wasm_do_not_inline_wrappers_with_ref_extern_parameter.patch

Changes from 0-M130
Notes:
* Security: backported fix for chromium:367734947.
* Security: backported fix for chromium:366635354.

chore: backport 2 changes from 0-M130

---

spec/api-browser-window-spec.ts
spec/api-protocol-spec.ts
spec/chromium-spec.ts

Addresses the following flaky tests:
* `protocol module handle is fast` (disabling on mac since it is flaky there)
* `iframe using HTML fullscreen API while window is OS-fullscreened can fullscreen from out-of-process iframes (macOS)` - found underlying issue causing flake and fixed it
* `BrowserWindow module window states (excluding Linux) fullscreen state handles HTML fullscreen transitions when fullscreenable is false` - found underlying issue causing flake and fixed it
Notes: none

test: fixup flaky tests

---

spec/api-browser-window-spec.ts
spec/crash-spec.ts

Fixes the following flaky tests seen on Linux:
* ` crash cases "after each" hook for "the "js-execute-iframe" case should not crash"`
* `BrowserWindow module navigation events ordering for initial navigation, event order is consistent`
Notes: none

test: deflake flaky tests on linux

---

shell/common/api/electron_api_asar.cc
shell/renderer/api/electron_api_web_frame.cc
shell/renderer/electron_renderer_client.cc
shell/renderer/electron_sandboxed_renderer_client.cc

`NewFromUtf8Literal()` passes in the literal's string length at compile time and avoids the need to call `.ToLocalChecked()`.
Notes: none.

perf: prefer NewFromUtf8Literal() over NewFromUtf8() for string literals

---

shell/browser/ui/electron_gdk_pixbuf.sigs

We made gdk_pixbuf a dynamic dependency since https://github.com/electron/electron/pull/34077 to help with downstream packaging due to conflicting names of the source package in various distros. The dependency regressed recently via https://github.com/electron/electron/pull/43956 which missed adding required symbols to the stubs.
A good regression test to catch future breakages would be to run https://source.chromium.org/chromium/chromium/src/+/main:third_party/dpkg-shlibdeps/dpkg-shlibdeps.pl and ensure the dependency doesn't show up. If this sounds good I can port a version of https://github.com/microsoft/vscode/blob/a14300ec9f7d04fbbaa9f896d46626110baa2b90/build/linux/debian/calculate-deps.ts#L21-L97 in a follow-up PR
New stub declarations are taken from …

fix: keep gdk_pixbuf a dynamic dependency

---

.github/workflows/pipeline-segment-electron-gn-check.yml
script/gen-libc++-filenames.js

At the moment the output of this file isn't particularly easy to read - it just dumps the full contents from both the old and new files to demonstrate that the file contents differ. What we want is to know what files were added and what files were removed as a result of e.g. a Chromium bump - this PR reworks the logic to show that more succinctly and directly.
<details><summary>Details</summary>
<p>
```diff
diff --git a/filenames.libcxx.gni b/filenames.libcxx.gni
index d680308876..9e88c13444 100644
--- a/filenames.libcxx.gni
+++ b/filenames.libcxx.gni
@@ -14,7 +14,7 @@ libcxx_headers = [
"//third_party/libc++/src/include/__algorithm/copy_n.h",
"//third_party/libc++/src/include/__algorithm/count.h",
"//third_party/libc++/src/include/__algorithm/count_if.h",
- …
```

build: improve `gen-libc++-filenames` output

---

BUILD.gn
filenames.gni
shell/app/electron_content_client.cc
shell/app/electron_main_linux.cc
shell/app/electron_main_mac.cc
shell/app/electron_main_win.cc
shell/browser/api/electron_api_base_window.cc
shell/browser/api/electron_api_base_window.h
shell/browser/native_window.cc
shell/browser/native_window.h
shell/browser/native_window_observer.h
shell/browser/native_window_views_win.cc
shell/common/electron_constants.cc
shell/common/electron_constants.h

tldr: declare shared string constants as `inline constexpr std::string_view` in a common header.
Background reading & Chromium dev discussion:
- https://abseil.io/tips/140 in general, and https://abseil.io/tips/140#constants-in-header-files in particular
- https://groups.google.com/a/chromium.org/g/chromium-dev/c/jROTxMo_m2Q/m/HgciN2KsAgAJ
- https://groups.google.com/a/chromium.org/g/chromium-dev/c/jROTxMo_m2Q/m/AlDnKq4JBAAJ
This satisfies the same argument for using `const char kFoo[]` and also helps the length of the string to be known at compile time in more places.
Notes: none.

refactor: prefer `inline constexpr string_view` for string constants

---

docs/api/power-monitor.md

A formatting error in the `powerMonitor` docs caused the `speed-limit-change` type definition to be incorrect. This broke for me when upgrading to Electron 33, as it seems the default listener type was changed from `Function` to `() => void`, so anyone using the `limit` parameter would get a type error.
This PR fixes the documentation formatting so that the types parse correctly.
Notes: Fixed an issue with the `powerMonitor` documentation that was affected typings for the `speed-limit-change` event listener.

docs: Fix `powerMonitor` docs for type generation of `speed-limit-change`

---

.github/actions/build-electron/action.yml
script/lib/config.py
script/lib/util.py
script/release/uploaders/upload.py
script/strip-binaries.py

Refs https://github.com/electron/electron/issues/44409
Fixup verbose mode logic - help diagnose a potential issue with Linux x64 stripping, which seemingly works fine locally.
<details><summary>Verbose Strip Output</summary>
<p>
```console
19:59:29 /workspaces/gclient/src/electron on fix-verbosity ❯ script/strip-binaries.py --target-cpu=x64 --verbose
Stripping binaries in /workspaces/gclient/src/out/Testing
Stripping chrome-sandbox
Stripping chrome_crashpad_handler
Binary size before stripping: 3.74 MB
strip --verbose --discard-all --strip-debug --preserve-dates /workspaces/gclient/src/out/Testing/chrome_crashpad_handler
copy from `/workspaces/gclient/src/out/Testing/chrome_crashpad_handler' [elf64-x86-64] to `/workspaces/gclient/src/out/Testing/stSnSITX' [elf64-x86-64]
Binary size after …
```

build: fix python util verbose mode logic

---

shell/browser/ui/win/taskbar_host.cc

Manually backport #44238 to 31-x-y. See that PR for details.
Notes: none.

fix: -Wunsafe-buffer-usage warnings in TaskbarHost::SetThumbarButtons() (31-x-y)

---

shell/common/platform_util_mac.mm
spec/api-shell-spec.ts

This PR fixes bug [identified in Slack](https://electronhq.slack.com/archives/CB6CG54DB/p1729185377925139) where Electron 33 doesn't focus the browser window when opening links when using shell.openExternal.
**Current behavior:**
- If the URL was successfully opened and the options.activate flag is set to true, the method calls [[NSApp activateIgnoringOtherApps:YES].](https://developer.apple.com/documentation/appkit/nsapplication/1428468-activateignoringotherapps) This call forces the Electron app to become the active application, bringing it to the foreground and giving it focus, regardless of whether another application is currently active.
**Updated behavior:**
- The URL is opened with [`openURL:configuration:completionHandler`](https://developer.apple.com/documentation/appkit/nsworkspa …

fix: update shell.openExternal to correctly focus on external window

---

build/args/all.gn
electron_unsafe_buffers_paths.txt

Part 23 in a [series](https://github.com/electron/electron/pull/43477) to fix `-Wunsafe-buffer-usage` warnings in `shell/`. 
Now that all the warnings are fixed :tada: , this PR enables the compiler warning in our builds to prevent any future regressions. It uses [similar upstream work in pdfium](https://pdfium-review.googlesource.com/c/pdfium/+/117850) as a template for using [the `clang_unsafe_buffers_path` build option](https://chromium-review.googlesource.com/c/chromium/src/+/5369835) to enable unsafe buffer usage warnings in Electron's C++ code.
Notes: Fixed all `-Wunsafe-buffer-usage` Clang warnings and enabled the compiler warning in new builds.

build: enable -Wunsafe-buffer-usage warnings

---

shell/browser/microtasks_runner.cc

I was profiling Electron on Ubuntu 24.04 a bit with hotspot, and this section shows up pretty high due to the cost of  `ObtainCurrentThreadStackStart()` when calling `Isolate::Scope::Enter()`.
It's not clear to me that this line is actually needed here in `DidProcessTask()`. The line predates the Node microtasks fixup, going back to 0c711f690e6a50840e7866af87ed1cc1949bac37.
So this is a PR to remove it and see what CI and the other maintainers think of the idea.
CC @deepak1556 and @codebytere who probably have the best context to give a 2nd opinion on whether this Isolate::Scope is actually needed.
Notes: Performance improvements when processing microtasks.

perf: remove isolate scope from DidProcessTask()

---

docs/api/base-window.md

Fixup to #44430.
44430 causes this regression in `electron-api.json`:
```diff
@@ -3491,7 +3491,7 @@
"description": "",
"required": true,
"collection": false,
-            "type": "View"
+            "type": "`View`"
}
],
"returns": null,
```
This PR reverts that part of 44430.
**NB:** Important to note that 44430 looks correct to me at first read. If it **is** correct and this regression is being caused by a parser bug that we have a quick fix for, then let's fast-track that instead and close this PR.
Notes: none.

docs: fix win.setContentView() arg type

---

spec/api-browser-view-spec.ts
spec/api-utility-process-spec.ts

fixes a few reoccurring flaky tests I noticed in #44411
- Utility process checks for unique process name in crash details. Concurrent crashes can overlap causing problems. https://ci.appveyor.com/project/electron-bot/electron-woa-testing/builds/50882274/job/f4pqgi79du1fq2om/tests
- BrowserView tests ensure no WebContents exist before and after each test. Concurrently running non-BrowserView tests might be throwing this off.
Notes: none

fix: flaky utility and BrowserView tests

---

patches/config.json
patches/dawn/.patches
patches/dawn/tint_validate_that_align_is_large_enough.patch

Notes: Security: backported fix for CVE-2024-10487.

chore: cherry-pick 1 change from 2-M130

---

patches/chromium/.patches
patches/chromium/cherry-pick-8c4edae5e34d.patch
patches/v8/.patches
patches/v8/cherry-pick-153d4e84e5d1.patch
patches/v8/cherry-pick-d9893f4856af.patch

<details>
<summary>electron/security#619 - 153d4e84e5d1 from v8</summary>
[13.0][wasm] Don't tier up wrapper if signature depends on other instance
The wasm-to-js wrapper tierup currently does not handle signatures with
indexed types correctly if the WebAssembly instance from which the
JavaScript function is called is different than the WebAssembly instance
that imported the JavaScript function initially. With this CL the
wrapper tierup gets disabled in that case until tierup gets fixed
eventually.
R=clemensb@chromium.org
Bug: 371565065
(cherry picked from commit 5fcbf3954eb9f7f8221f068b5324e5b6f04b5839)
Change-Id: I43d8eff2d4ce4e3ec775b7346938ea26109f7045
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/5937800
Commit-Queue: Andreas Haas <ahaas@chromium.org>
Reviewed-by: …

chore: cherry-pick 3 changes from 1-M130

---

.github/actions/checkout/action.yml
.github/actions/restore-cache-aks/action.yml
.github/actions/restore-cache-azcopy/action.yml
.github/workflows/clean-src-cache.yml

We occasionally run into issues when our source cache runs out of disk space.  This PR does a couple of things to help alleviate this issue:
1. Check for enough free disk space before attempting to create a new source cache.  If there isn't enough space, exit the checkout job early so that we don't create incomplete caches.
2. Logic has been added to detect empty source cache files if they somehow exist. If there is an empty source cache, the checkout job will act as if the cache doesn't exist and will attempt to create a new source cache.  Jobs that use the cache will now exit early if the source cache is empty.
3. Adds a cron job to cleanup the source cache every week on Sunday at midnight.
Notes: none

build: handle out of disk space on source cache

---

patches/config.json
patches/dawn/.patches
patches/dawn/tint_validate_that_align_is_large_enough.patch

Notes: Security: backported fix for CVE-2024-10487.

chore: backport 1 change from 2-M130

---

shell/common/gin_converters/std_converter.h

Use `v8::String::NewFromUtf8Literal()` instead of `v8::String::NewFromUtf8()` when the string literal size is known at compile time. This avoids a little bit of overhead of v8 having to call strlen() and ToLocalChecked().
Notes: none.

perf: use v8::String::NewFromUtf8Literal in ToV8() gin converter

---

shell/browser/api/electron_api_web_contents.cc
shell/common/gin_converters/std_converter.h

Remove the unused `ToV8(v8::Isolate* isolate, const char* val)` gin converter.
Notes: none.

refactor: remove unused C string ToV8() gin converter

---

docs/api/web-frame.md
docs/experimental.md

Let's fast-track this urgent fix.
Notes: none.

docs: fix apostrophe typo "Electrons" -> "Electron's"

---

patches/chromium/.patches
patches/chromium/cherry-pick-8c4edae5e34d.patch
patches/chromium/fix_software_compositing_infinite_loop.patch
patches/chromium/oom_add_commit_limit_available_to_oom_exception_arguments.patch
patches/chromium/printing.patch
patches/dawn/tint_validate_that_align_is_large_enough.patch
patches/v8/cherry-pick-153d4e84e5d1.patch
patches/v8/cherry-pick-d9893f4856af.patch

Backports https://chromium-review.googlesource.com/c/chromium/src/+/5856490 , change is available starting M130
Helps with confirming the limits against the system limits captured via stability report, refs https://github.com/microsoft/vscode/issues/232820#issuecomment-2451848581
Changes to other patch files were triggered by https://github.com/electron/electron/blob/2081f771e4181a5a7db8a59c85e6e966820b9017/package.json#L131-L133 which required a re-export.
Notes: Add process memory limit details to parition_alloc oom handler

chore: add process memory limit details in parition_alloc oom handler

---

shell/browser/electron_browser_client.cc

Replace our one use of `absl::optional` with `std::optional`, since the former is [banned](https://chromium-review.googlesource.com/c/chromium/src/+/5805666).
Side node: this is an argument to a class method, and we specify `absl::optional` in the .cc file but `std::optional` in the .h file. `ABSL_USES_STD_OPTIONAL`  must be getting defined somewhere; otherwise, this wouldn't be compiling in `main` as-is :slightly_smiling_face: 
Notes: none.

chore: remove use of banned absl::optional

---

shell/browser/api/electron_api_session.cc
shell/browser/extensions/api/management/electron_management_api_delegate.cc
shell/browser/extensions/api/scripting/scripting_api.cc
shell/browser/hid/hid_chooser_context.cc
shell/browser/hid/hid_chooser_controller.cc
shell/browser/net/electron_url_loader_factory.cc
shell/browser/net/proxying_url_loader_factory.cc
shell/browser/net/proxying_websocket.cc
shell/browser/serial/serial_chooser_controller.cc
shell/browser/ui/inspectable_web_contents.cc
shell/browser/ui/views/global_menu_bar_x11.cc
shell/common/application_info.cc
shell/common/color_util.cc
shell/common/gin_converters/serial_port_info_converter.h
shell/renderer/renderer_client_base.cc

`base::StringPrintf()` is slated for removal and is currently just a pass-through to `absl::StrFormat()`.
Xref: https://issues.chromium.org/issues/40241565
Xref: https://chromium-review.googlesource.com/c/chromium/src/+/4907781
Notes: none.

refactor: replace base::StringPrintf() calls with absl::StrFormat()

---

.github/workflows/build.yml

This PR adds a new status, **_GitHub Actions Completed_**, which verifies that all required GitHub Actions jobs have successfully run.  Once this PR is merged, we can require this status to make sure that PRs don't get merged with failing GitHub Actions jobs.
Notes: none

build: add new status to verify if all the required gha jobs have run

---

docs/api/app.md
docs/api/command-line-switches.md
docs/api/shell.md
docs/api/utility-process.md

Just a quick capitalization fix in the docs.
Notes: none.

docs: capitalize POSIX and Windows correctly

---

shell/browser/notifications/win/windows_toast_notification.cc

Use `base::NumberToString()` instead of `std::to_string()` since the latter is [banned](https://chromium.googlesource.com/chromium/src/+/main/styleguide/c++/c++-features.md#std_sto_i_l_ul_ll_ull_f_d_ld_to_string_banned).
Notes: none.

fix: remove use of banned std::to_string()

---

patches/node/.patches
patches/node/chore_disable_deprecation_ftbfs_in_simdjson_header.patch

Fixes new `-Wdeprecated-literal-operator` simdjson.h warning that breaks the build in `main` due to `-Werror`.
Xref: https://github.com/electron/electron/pull/44281
Xref: https://github.com/electron/electron/pull/44360
CC @jkleinsc 
Notes: none

fix: ftbfs when including simdjson in Node.js

---

script/create-api-json.mjs
script/lint.js
spec/fixtures/api/pdf-reader.mjs
spec/fixtures/esm/import-meta/main.mjs
spec/fixtures/esm/import-meta/preload.mjs

Adds `mjs` as a lintable JS extension and fixes the lint errors that arose as a result.
Notes: none

build: also lint mjs files

---

docs/api/browser-window.md
shell/browser/api/electron_api_base_window.cc
shell/browser/api/electron_api_base_window.h
shell/browser/native_window.cc
shell/browser/native_window.h
shell/browser/native_window_mac.h
shell/browser/native_window_mac.mm

This PR adds an optional animate Boolean parameter to BrowserWindow.setVibrancy method so when applying a vibrant backdrop for a window or removing it, it fades in/out accordingly.
`animate=false`:
https://user-images.githubusercontent.com/1059699/195198178-d6a56e17-d409-4d27-ab94-4d4fed99b732.mov
`animate=true`:
https://user-images.githubusercontent.com/1059699/195198197-de8f6ee5-3676-4581-8e5f-45adfdd8bbe2.mov
Notes: Add optional animation parameter to BrowserWindow.setVibrancy

feat: add optional animation parameter to BrowserWindow.setVibrancy

---

spec/api-global-shortcut-spec.ts

Refs https://github.com/electron/electron/pull/44341.
Test fuller matrix of accelerator combinations to prevent regressions like the above.
Notes: none

test: exercise fuller `globalShortcut` matrix

---

.github/workflows/issue-transferred.yml

If an issue is transferred to another repo, it stays on the issue triage board, so this updates our automation to remove it.
Notes: none

ci: remove from issue triage on issue transferred

---

patches/chromium/.patches
patches/chromium/cherry-pick-e699ac35ac6c.patch

<details>
<summary>electron/security#623 - e699ac35ac6c from chromium</summary>
[M-130] serial: Cancel mojo::SimpleWatcher when source/sink become garbage
SerialPortUnderlyingSink and SerialPortUnderlyingSource need
prefinalizers so that when they become garbage the mojo::SimpleWatcher
is disarmed so that it doesn't invoke its callback on a garbage object.
(cherry picked from commit 8ecbee8becf25733afa6dde28c3fde6a1ee2498e)
Bug: 375065084
Change-Id: Ifc847d61fa530532783d47d5749db45091fdeb96
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5957129
Reviewed-by: Alvin Ji <alvinji@chromium.org>
Auto-Submit: Reilly Grant <reillyg@chromium.org>
Commit-Queue: Alvin Ji <alvinji@chromium.org>
Cr-Original-Commit-Position: refs/heads/main@{#1373408}
Reviewed-on: …

chore: cherry-pick 1 changes from 3-M130

---

patches/chromium/.patches
patches/chromium/cherry-pick-923797bac925.patch

<details>
<summary>electron/security#624 - 923797bac925 from chromium</summary>
[M131] Make GetCacheIdentifier() respect GetSkipServiceWorker().
Since the current GetCacheIdentifier() ignores GetSkipServiceWorker(),
GetCacheIdentifier() returns ServiceWorkerId even if GetSkipServiceWorker()
is true if the ServiceWorker has a fetch handler.
To make the isolated world respected as an isolated world, the cache
identifier should not be shared with a page under a ServiceWorker control.
(cherry picked from commit 75f322ad1f64c0bc56fa77ab877b48d72cdb903c)
Bug: 372512079, 373263969
Change-Id: Idd2d8900f2f720e0a4dc9837e2eb56474c60b587
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5961018
Reviewed-by: Justin Lulejian <jlulejian@chromium.org>
Reviewed-by: Kouhei Ueno …

chore: cherry-pick 1 changes from 0-M131

---

build/generate_node_defines.py
script/generate-config-gypi.py
script/zip-symbols.py

Fixes these warnings:
```
[3469/51023] ACTION //electron:electron_generate_node_defines(//build/toolchain/linux:clang_x64)
/home/charles/src/devdiv/src/out/Testing/../../electron/build/generate_node_defines.py:5: SyntaxWarning: invalid escape sequence '\w'
DEFINE_EXTRACT_REGEX = re.compile('^ *# *define (\w*)', re.MULTILINE)
[4627/51023] ACTION //electron:generate_config_gypi(//build/toolchain/linux:clang_x64)
/home/charles/src/devdiv/src/out/Testing/../../electron/script/generate-config-gypi.py:43: SyntaxWarning: invalid escape sequence '\w'
m = re.match('(\w+) = (.+)', line)
```
Also fixes three other minor warnings that were nearby: a pair of unused imports and a [pep 8 E711 warning](https://peps.python.org/pep-0008/#programming-recommendations) to use `foo is None` instead of `foo == …

build: fix python warnings "SyntaxWarning: invalid escape sequence '\w'"

---

shell/browser/api/electron_api_view.cc
shell/browser/api/electron_api_view.h
spec/api-web-contents-view-spec.ts

Closes https://github.com/electron/electron/issues/44652.
Fixes an issue where webContentsViews were being improperly removed as a result of comparison via GetID instead of direct `views::View == views::View` comparison. `views::View` IDs are default 0 and need to be manually managed in order to use, so we were constantly comparing 0 = 0 and removing all the children.
Notes: Fixes an issue where `WebContentsView`s were being improperly removed.

fix: `WebContentsView` removal should compare directly

---

docs/api/command-line-switches.md
docs/api/dialog.md
patches/chromium/feat_add_support_for_missing_dialog_features_to_shell_dialogs.patch
shell/browser/ui/file_dialog_linux.cc

1) Revert the version bump to `3`, to help address https://github.com/electron/electron/issues/43819
2) Provide `xdg-portal-required-version` flag for application developers to control the portal usage (ex: requires support of `current_folder`)
3) If portal code path is used and a call to dialog api with `default_path` is performed then log a warning pointing to the above flag.
Notes: fix file chooser dialogs for flaptak applications

fix: revert required portal version for file chooser dialogs

---

docs/api/utility-process.md
shell/browser/api/electron_api_utility_process.cc
spec/api-utility-process-spec.ts

Refs https://github.com/electron/electron/pull/44243.
The fix for the above surfaced a new problem, which is that the `pid` of the `child` process was still defined when the `exit` event is emitted. This worked previously as a fluke of the duplicate events - the [handle](https://github.com/electron/electron/blob/122685194a5642b73367e823aadf3942b0290099/lib/browser/api/utility-process.ts#L99) was reset _after_ exit was emitted the first time and so would be undefined in the callback the second time. We need to ensure it's reset on process termination.
Notes: Fixed an issue where a `utilityProcess` pid would not be `undefined` after exit.

fix: `utilityProcess` pid should be `undefined` after exit

---

.github/workflows/pipeline-segment-electron-test.yml
patches/node/.patches
patches/node/src_provide_workaround_for_container-overflow.patch

Closes https://github.com/electron/electron/issues/44549.
Backports https://github.com/nodejs/node/pull/55591 to re-enable `container_overflow` ASAN checks.
Notes: none

build: re-enable `container_overflow` ASAN check

---

patches/chromium/feat_enable_passing_exit_code_on_service_process_crash.patch
patches/chromium/refactor_unfilter_unresponsive_events.patch
shell/browser/api/electron_api_utility_process.cc
spec/api-utility-process-spec.ts

With https://github.com/electron/electron/pull/42297 we rely on service process host observers for termination events and the exit code is obtained from `ServiceProcessInfo` struct which is uninitialized for `TerminatedNormally` leading to stale values in the exit event, refs https://github.com/microsoft/vscode/issues/225485
The change also removes the helper `HasObserver` from the patch since observers are meant to be added only once and if we are accidentally adding them multiple times then the callsite should be revisited. In our case, the UtilityProcess ctor is 1:1 with ServiceProcessHost so we are good. This also reduces the patch surface.
Notes: Return 0 exit code for normal termination of the utility process

fix: utility process exit code for graceful termination

---

.github/workflows/issue-opened.yml

Fixes an issue where issues opened against Electron would fail to auto-assign versions if more than one was provided. All relevant versions should be assigned to the issue if more than one is provided.
Before:
```js
// Using 34.0.0-alpha.6, 33.0.2, 32.2.2, 31.7.3
const major = semver.parse(electronVersion)?.major; // undefined, no versions
```
After:
```js
// Using 34.0.0-alpha.6, 33.0.2, 32.2.2, 31.7.3
const major = semver.parse(electronVersion)?.major; // 34, 33, 32, 31
```
Notes: none

chore: fix multi-version parsing in issue assignment

---

docs/api/ipc-main.md
docs/api/ipc-renderer.md
spec/api-ipc-main-spec.ts
spec/api-ipc-renderer-spec.ts

The documentation for the `on`/`off` and `addListener`/`removeListener` docs for `ipcMain` and `ipcRenderer` are somewhat inconsistent. Thanks to @Kilian for pointing this out.
1. `ipcMain` is missing documentation for the `off` and `addListener` functions. I've added them
2. `off` and `addListener` are documented as aliases for `removeListener` and `on` respectively. This is a little confusing, so I've made `on` and `off` the "primary" APIs and documented `addListener`/`removeListener` as aliases.
3. `ipcRenderer.removeAllListeners` didn't document that the `channel` param was optional, even though it should be. I've updated the docs to mark it as optional, and I've updated both the `ipcRenderer` and `ipcMain` docs to better describe what happens if you don't pass a `channel` value.
I …

docs: Make ipcRenderer and ipcMain listener API docs consistent

---

patches/chromium/feat_enable_passing_exit_code_on_service_process_crash.patch
patches/chromium/refactor_unfilter_unresponsive_events.patch
shell/browser/api/electron_api_utility_process.cc
spec/api-utility-process-spec.ts

This reverts commit 36e1a0bf001d72f725297f43827d255b08c2e9b7.
Refs https://github.com/electron/electron/pull/44698#issuecomment-2484428725
Notes: none

chore: Revert "fix: utility process exit code for graceful termination"

---

.github/workflows/issue-opened.yml

Follow-up to #44679 which inadvertently broke adding the comment about unsupported versions. The `core.setOutput` isn't a human visible output, but a step output to be used in the next step. Restoring it to the previous value.
https://github.com/electron/electron/blob/58dc990f7a725537b447c22862956ac6d711291d/.github/workflows/issue-opened.yml#L133
Notes: none

chore: fix unsupported major comment in issue automation

---

shell/browser/native_window_views.cc
spec/api-browser-window-spec.ts

Refs https://github.com/electron/electron/pull/43431
Closes https://github.com/electron/electron/issues/44521
This PR follows up a previous PR to prevent overactive emission of `resize` events when the Window is resized and not moved. However, that PR did not distinguish between `WidgetObserver::OnWidgetBoundsChanged` being called from
`Widget::OnNativeWidgetMove()` and `Widget::OnNativeWidgetSizeChanged`. This led to a new issue where single-pixel resizes done by the user no longer caused `resize` events to be emitted where they should have been.
To handle this more effectively, we should check _both_ whether the window is moving at the time `OnWidgetBoundsChanged` is called via `is_moving_` as well as whether it's within the single-pixel tolerance zone. `is_moving_` is set in …

fix: improve single-pixel resize handling on Windows

---

shell/common/api/electron_api_url_loader.cc
shell/common/api/electron_api_url_loader.h

Similar fix to https://github.com/electron/electron/pull/39335
For https://github.com/microsoft/vscode/issues/232564
Notes: fix crash in net api when utility process exits.

fix: destroy url loader wrapper when JS env exits

---

patches/chromium/feat_enable_passing_exit_code_on_service_process_crash.patch
patches/chromium/refactor_unfilter_unresponsive_events.patch
shell/browser/api/electron_api_utility_process.cc
shell/browser/api/electron_api_utility_process.h
spec/api-utility-process-spec.ts

Brings back https://github.com/electron/electron/pull/44698
2ed41bf1ccca1875948d99c387e13f2701bae4a2 addresses https://github.com/electron/electron/pull/44698#issuecomment-2484428725
Notes: Return 0 exit code for normal termination of the utility process

fix: utility process exit code for graceful termination (reland)

---

shell/browser/ui/autofill_popup.cc
shell/browser/ui/autofill_popup.h
shell/browser/ui/views/autofill_popup_view.cc
shell/browser/ui/views/autofill_popup_view.h

Clean up dependency conflict between AutofillPopup and AutofillPopupView:
- fix cyclical #include header dependency
- fix clang-tidy warning in AutofillPopup warning: use '= default' to define a trivial default constructor [modernize-use-equals-default]
- reduce #include scope in autofill_popup.h and autofill_popup_view.h
- move some numeric constants out of public namespace into private AutofillPopup, since it is their only consumer
Notes: none.

fix: cyclical #include dependency between autofill_popup.h and autofill_popup_view.h

---

shell/common/api/electron_api_native_image.cc
shell/common/api/electron_api_native_image.h

I'm experimenting with running Electron's shell code through clang-tidy and thought I'd pick up some low-hanging-fruit fixes while I experiment.
This PR fixes a handful of [narrowing conversions](https://clang.llvm.org/extra//clang-tidy/checks/cppcoreguidelines/narrowing-conversions.html) warnings:
```
../../electron/shell/common/api/electron_api_native_image.cc:155:26: warning: narrowing conversion from 'size_t' (aka 'unsigned long') to signed type 'int32_t' (aka 'int') is implementation-defined [bugprone-narrowing-conversions]
155 |       new_memory_usage = image_skia->bitmap()->computeByteSize();
../../electron/shell/common/api/electron_api_native_image.cc:508:36: warning: narrowing conversion from 'unsigned int' to signed type 'int' is implementation-defined …
```

fix: bugprone-narrowing-conversions warnings in NativeImage

---

shell/browser/electron_browser_client.cc

Manual backport of #44513 to 32-x-y. See that PR for details.
Notes: none.

chore: remove use of banned absl::optional (#44513)

---

shell/browser/ui/views/win_caption_button_container.cc
shell/browser/ui/views/win_caption_button_container.h

This PR adds missing tooltip captions to WCO buttons when WCO is enabled. This matches upstream behavior and expectations for the WCO api.
<details><summary>With Tooltips</summary>
<p>
</p>
</details> 
Notes: Fixed an issue where buttons shown under the Window Controls Overlay API were missing tooltips.

fix: tooltips in WCO caption buttons

---

shell/browser/native_window_mac.mm

Closes https://github.com/electron/electron/issues/44688
Fixes an issue where frameless windows emitted a deprecation warning due to `NSWindowStyleMaskTexturedBackground` being deprecated. It's been functionally a no-op for a while (see https://chromium-review.googlesource.com/c/chromium/src/+/4300751) but should only be emitted when a user explicitly passes `type: textured`.
Notes: Fixed an issue where a deprecation warning was being incorrectly emitted for frameless windows on macOS.

chore: fix textured window conditional on macOS

---

BUILD.gn
shell/browser/ui/electron_gdk.sigs
shell/browser/ui/electron_gtk.sigs
shell/common/platform_util_linux.cc

Simplify `platform_util::Beep()` by using [gdk_display_beep()](https://docs.gtk.org/gdk4/method.Display.beep.html) instead of rolling our own implementation.
Notes: none.

refactor: use gdk_display_beep() on Linux

---

docs/tutorial/code-signing.md

Updates the documentation to remove redundant phrasing.
Notes: None

docs: removes redundant phrasing in the code signing documentation

---

shell/browser/extensions/electron_extensions_browser_client.cc
shell/common/logging.cc

Fix two [performance-no-automatic-move](https://clang.llvm.org/extra/clang-tidy/checks/performance/no-automatic-move.html) warnings.
Fixed by this PR:
> ../../electron/shell/common/logging.cc:40:12: warning: constness of 'log_filename' prevents automatic move [performance-no-automatic-move]
>
> ../../electron/shell/browser/extensions/electron_extensions_browser_client.cc:187:10: warning: constness of 'request_relative_path' prevents automatic move [performance-no-automatic-move]
Notes: none

fix: `performance-no-automatic-move` clang-tidy warnings

---

shell/common/v8_util.cc

Fix a sneaky bug that breaks our serialization on big endian systems.
I don't know of anyone running Electron running on IBM System/360, 370, and 390, so this probably less a production issue and more a code correctness issue :smile_cat: 
We have a set of 1-byte tags that we serialize in a single byte, but the tags are instantiated as 4-byte integers because of an untyped enum declaration. So when we call `V8Serializer::WriteRawBytes(void*, size_t )` with `WriteRawBytes(&tag, 1)`  the result is architecture-dependent: it writes the tag's little-endian byte on little-endian machines and works fine, but writes the tag's big-endian byte (a `'\0'`) on big-endian machines.
Notes: none

fix: big endian bug in V8 serialization

---

shell/browser/native_window_mac.h
shell/browser/ui/cocoa/delayed_native_view_host.h
shell/browser/ui/cocoa/delayed_native_view_host.mm
shell/browser/ui/cocoa/electron_ns_window.mm
spec/api-web-contents-spec.ts
spec/fixtures/pages/draggable-page.html

Closes https://github.com/electron/electron/issues/44386.
Refs https://github.com/electron/electron/pull/41256
Fixes an issue where the webContents `context-menu` event was not emitted when using `-webkit-app-region: drag`. This was happening after the sibling view change above because `sendEvent` in `NativeWidgetMacNSWindow` no longer sent the right-click event to the correct NSView. We can fix this by intercepting the event in `sendEvent` on `ElectronNSWindow`, which inherits from `NativeWidgetMacNSWindow`. This solution avoids patching.
cc @bpasero
Notes: Fixed an issue where the webContents `context-menu` event was not emitted when using `-webkit-app-region: drag`.

fix: ensure `context-menu` emitted for draggable regions

---

patches/chromium/.patches
patches/chromium/support_bstr_pkey_appusermodel_id_in_windows_shortcuts.patch

Closes https://github.com/electron/electron/issues/44752.
It's possible for a shortcut link on Windows to be BSTR format; this resulted in a DCHECK previously but as of the `NOTREACHED` fatal migration now will crash a given app. Fix this by allowing for supporting `VT_BSTR` variants
for `PKEY_AppUserModel_ID`.
Upstreamed at CL:6039894
Notes: Fixed a crash that could occur when calling `shell.readShortcutLink` on Windows.

fix: crash calling `shell.readShortcutLink`

---

docs/api/base-window.md
docs/api/browser-window.md
docs/api/structures/window-session-end-event.md
docs/tutorial/multithreading.md
filenames.auto.gni
shell/browser/api/electron_api_base_window.cc
shell/browser/api/electron_api_base_window.h
shell/browser/native_window.cc
shell/browser/native_window.h
shell/browser/native_window_observer.h
shell/browser/native_window_views_win.cc
shell/common/gin_helper/event_emitter.h

Current Electron version allows to handle only `WM_ENDSESSION`, but not `WM_QUERYENDSESSION`. This cause a lot of problems while Electron app is packaged into own MSI and is a menubar/tray app. For example currently we cannot close app using Restart Manager which is used by default since Windows Installer 4.0. We have to use [util:CloseApplication](https://wixtoolset.org/docs/schema/util/closeapplication/) or call `taskkil`.
Quote from [Restart Manager guidelines for Applications](https://learn.microsoft.com/en-us/windows/win32/rstmgr/guidelines-for-applications):
> Applications running on Windows Vista and Windows Server 2008 should adhere to these guidelines to ensure that the Restart Manager can shut down and restart applications if necessary to install updates.
> GUI applications …

feat: add query-session-end and improve session-end events on Windows

---

CONTRIBUTING.md

This currently dumps the user to the blank issue, which isn't what we want. Seems like there's oddly a behavior difference depending on if there's a trailing slash after `/issues/new` (trailing slash takes you to the chooser), so let's link directly to the issue template chooser.
Notes: none

docs: update new GitHub issue link

---

spec/api-web-contents-view-spec.ts
spec/api-web-request-spec.ts
spec/visibility-state-spec.ts

- While working on #44136, I discovered that we were not properly cleaning up webcontents in the visibility spec.  32-x-y in particular [continues to have issues with the visibility specs failing](https://ci.appveyor.com/project/electron-bot/electron-x64-testing/builds/51039960/job/dfncljb41qcusi5k/tests). I believe this PR should clean those up.
Notes: none

test: fixup visibility tests

---

shell/browser/api/electron_api_app.cc
shell/browser/relauncher.cc
shell/browser/ui/views/global_menu_bar_registrar_x11.cc

Don't declare local variables that we don't use.
This `bugprone-unused-local-non-trivial-variable` off of our clang-tidy bingo card :smile_cat: 
Notes: none.

fix: remove unused local variables

---

shell/browser/api/electron_api_web_contents.cc

Remove another tiny piece of code. This time it's a redundant class constructor.
Notes: none.

refactor: remove unnecessary constructor code

---

docs/api/auto-updater.md

Simple wording fix in autoUpdater docs
Notes: none

docs: fix wording in auto-updater.md

---

shell/browser/api/electron_api_crash_reporter.cc
shell/common/api/electron_api_clipboard.cc

Manually backport #44743 to 33-x-y. See that PR for details.
The backport needed human intervention because of minor `#include` context shear 
Notes: none.

fix: clang-tidy `performance-inefficient-vector-operation` warnings (33-x-y)

---

shell/browser/electron_permission_manager.cc
shell/browser/osr/osr_render_widget_host_view.cc
shell/common/api/electron_api_url_loader.cc
shell/common/extensions/electron_extensions_client.cc
shell/common/gin_converters/osr_converter.cc
shell/common/gin_helper/callback.cc
shell/common/heap_snapshot.cc
shell/renderer/api/electron_api_spell_check_client.cc
shell/renderer/renderer_client_base.cc

Annotate functions as `[[nodiscard]]` as suggested by clang-tidy's `modernize-use-nodiscard` warning
Notes: none

fix: modernize-use-nodiscard clang-tidy warnings

---

shell/app/electron_main_delegate.cc
shell/browser/extensions/api/scripting/scripting_api.cc
shell/browser/extensions/api/tabs/tabs_api.cc
shell/browser/file_system_access/file_system_access_permission_context.cc
shell/browser/ui/devtools_ui_theme_data_source.cc
shell/browser/ui/inspectable_web_contents.cc
shell/browser/ui/webui/accessibility_ui.cc
shell/browser/usb/usb_chooser_context.cc
shell/browser/zoom_level_delegate.cc
shell/renderer/electron_api_service_impl.cc
shell/renderer/electron_sandboxed_renderer_client.cc

In places where we pass a `kConstantStr` variable to a method that takes a `std::string_view` argument, then we can declare that `kConstantStr` as a `constexpr std::string_view`.
This fixes a lot of clang-tidy `modernize-avoid-c-arrays` warnings and is conceptually cleaner since we're declaring the same type that we use.
Notes: none.

fix: modernize-avoid-c-arrays

---

shell/browser/api/electron_api_web_frame_main.cc
shell/browser/linux/unity_service.cc
shell/browser/ui/views/global_menu_bar_x11.cc
shell/common/asar/asar_util.cc

Prefer `using` over `typedef` as suggested by clang-tidy's `modernize-use-using` warnings
Notes: none.

fix: modernize-use-using clang-tidy warnings

---

shell/browser/api/electron_api_crash_reporter.cc
shell/common/api/electron_api_clipboard.cc

Manually backport #44743 to 32-x-y. See that PR for details.
No significant changes compared to 44743; trop just got confused by some `#include` shear in `electron_api_crash_reporter.cc`
Notes: none.

fix: clang-tidy `performance-inefficient-vector-operation` warnings (32-x-y backport)

---

shell/browser/api/electron_api_web_frame_main.cc
shell/browser/linux/unity_service.cc
shell/browser/ui/views/global_menu_bar_x11.cc
shell/common/asar/asar_util.cc

Manually backport #44806 to 32-x-y. See that PR for details.
Trop got confused by the `electron_api_web_frame_main.cc` diff due changes in that file from 30fbeec036f8481ba9eba9cb01af0236ed0d28ff
Notes: none.

fix: modernize-use-using clang-tidy warnings (32-x-y backport)

---

shell/app/electron_content_client.cc

Simplify our CLI schemes parsing a little bit by using [base::Extend()](https://chromium.googlesource.com/chromium/src/base/+/refs/heads/main/containers/extend.h).
Notes:  none.

refactor: use base::Extend in AddAdditionalSchemes()

---

shell/browser/api/electron_api_menu.cc
shell/browser/api/electron_api_utility_process.cc
shell/browser/api/electron_api_web_frame_main.cc
shell/browser/extensions/electron_extension_system.cc
shell/browser/printing/printing_utils.cc
shell/common/gin_converters/blink_converter.cc
shell/common/platform_util.cc
shell/common/skia_util.cc
shell/renderer/api/electron_api_context_bridge.cc

Move several impl functions, structs, and variables into an anonymous namespace so that they're only visible to that source file. This fixes some [misc-use-internal-linkage](https://clang.llvm.org/extra/clang-tidy/checks/misc/use-internal-linkage.html) warnings.
Notes: none.

fix: misc-use-internal-linkage warnings

---

shell/browser/electron_permission_manager.cc
shell/browser/osr/osr_render_widget_host_view.cc
shell/common/api/electron_api_url_loader.cc
shell/common/extensions/electron_extensions_client.cc
shell/common/gin_helper/callback.cc
shell/common/heap_snapshot.cc
shell/renderer/api/electron_api_spell_check_client.cc
shell/renderer/renderer_client_base.cc

Manually backport #44808 to 32-x-y. See that PR for details.
No code changes relative to 44808, it just needed a human backport because trop was confused by unrelated context shear in `osr_render_widget_host_view.cc`.
Notes: none.

fix: modernize-use-nodiscard clang-tidy warnings (32-x-y backport)

---

docs/api/session.md

Backport of https://github.com/electron/electron/pull/44547
The purpose of this backport is to make the change show up on [electronjs.org](https://www.electronjs.org/docs/latest/api/session), which is currently built from the `33-x-y` branch.
Notes: none.

docs: clarify that sessions use cache by default (33-x-y backport)

---

patches/dawn/.patches
patches/dawn/ir_fix_robustness_transform_on_textureload_of_sampled_and_depth.patch
patches/dawn/tint_validate_that_align_is_large_enough.patch

488f45da141d9e2b3fe6f86aa0e3bca05ad95b64 from dawn.
Notes:
* Security: backported fix for chromium:378541479.

chore: cherry-pick 1 change from 1-M131

---

shell/browser/relauncher.cc
shell/browser/relauncher.h
shell/browser/relauncher_win.cc

`kRelauncherTypeArg` and `kRelauncherArgSeparator` were only used in relauncher.cc, so there's no need to declare them in relauncher.h where other files can see them. Move them into an unnamed namespace in relauncher.cc.
Somewhat related to https://github.com/electron/electron/pull/44843
Notes: none.

refactor: reduce scope of relauncher's internal constants

---

docs/api/utility-process.md

Relevant code: https://github.com/electron/electron/blob/9f1e23c405847c2773231347b7604731741b0034/shell/browser/api/electron_api_utility_process.cc#L419
CC @deepak1556
Notes: none

docs: specify default value for `respondToAuthRequestsFromMainProcess`

---

docs/breaking-changes.md

Sample code written in the [Breaking Changes](https://www.electronjs.org/docs/latest/breaking-changes#planned-breaking-api-changes-320) does not work, which was added by @nornagon in [#42053](https://github.com/electron/electron/pull/42053)
Notes: none

docs: fix a syntax issue in document breaking changes

---

shell/browser/ui/message_box_gtk.cc

Remove the `id` argument from `TranslateToStock()`. It's been unused since fb537d91fce3f97ac3b902c36fcc4626eef0c959.
Also, fix a small number of warnings in that function: [readability-braces-around-statements](https://clang.llvm.org/extra/clang-tidy/checks/readability/braces-around-statements.html) and [readability-convert-member-functions-to-static](https://clang.llvm.org/extra/clang-tidy/checks/readability/convert-member-functions-to-static.html)
Notes: none.

fix: remove unused id argument from TranslateToStock()

---

shell/browser/osr/osr_render_widget_host_view.cc

Our `UiMouseEventFromWebMouseEvent()` function was added in 2017 by 218e28b136124bdad6abd7e763ba89b36910aaca and it's mostly been unchanged since then.
This PR makes two changes:
- Use the `gfx::PointF` constructor of `ui::MouseEvent` intead of the deprecated `gfx::Point` variant. This was added upstream in 2019 by https://chromium-review.googlesource.com/c/1444251.
- Use `WebInputEvent::GetTypeAsUiEventType()` instead of rolling our own. This was added upstream in 2020 by https://chromium-review.googlesource.com/c/chromium/src/+/2180291.
Notes: none.

fix: don't use deprecated ui::MouseEvent constructor

---

shell/browser/api/electron_api_cookies.cc
shell/browser/api/electron_api_cookies.h

Remove the unused isolate argument from the Cookies constructor.
It hasn't been needed since the ginify cookies refactor in Mar 2020, commit 22202255
Notes: none.

chore: remove unused isolate argument from Cookies constructor

---

shell/browser/api/electron_api_base_window.cc
shell/browser/api/electron_api_base_window.h

Looks like this argument was added in db79734b but never used, so let's remove it.
Notes: none

chore: remove unused arg from BaseWindow::GetBackgroundColor()

---

shell/browser/electron_browser_client.cc

This arg has never been used; introduced by 91071570
Notes: none

chore: remove unused registry arg from GetPrivilegeRequiredByUrl()

---

docs/api/web-frame-main.md
shell/browser/api/electron_api_web_frame_main.cc
shell/browser/api/electron_api_web_frame_main.h
spec/api-web-frame-main-spec.ts
spec/index.js

Adds `WebFrameMain.collectJavaScriptCallStack()` to allow accessing the JavaScript call stack of unresponsive renderers. This is available in Chromium as part of the [Crash Reporting API.](https://wicg.github.io/crash-reporting/)
With this API, a dialog shown when a renderer becomes unresponsive could have an option to copy the stack trace. This would help application developers figure out why their website might be stuck on long-running JavaScript.
I've marked the API as experimental given that the proposal is still a draft.
-----
Here's an example of the output from a [fiddle gist](https://gist.github.com/dfddc4c3e4459f097ca7f9bb35218d88):
```
Renderer unresponsive
at startInfiniteLoop (<anonymous>:5:5)
at HTMLHtmlElement.clickHandler (<anonymous>:11:5)
```
Notes: Added …

feat: WebFrameMain.collectJavaScriptCallStack()

---

.github/workflows/issue-opened.yml

Fixes parsing error surfaced in https://github.com/electron/electron/issues/44917 - `V33.2.1` parsed as `null` instead of `33.2.1`. Fix this by trying to coerce instead of just parse.
CLI check:
```sh
npx semver --parse 'V33.2.1' // null
npx semver --coerce 'V33.2.1' // 33.2.1
```
Notes: none

chore: make version parsing more tolerant

---

shell/browser/auto_updater.h
shell/browser/browser_observer.h
shell/browser/extended_web_contents_observer.h
shell/browser/extensions/api/extension_action/extension_action_api.h
shell/browser/extensions/api/tabs/tabs_api.h
shell/browser/native_window_observer.h
shell/browser/ui/electron_menu_model.h
shell/browser/ui/inspectable_web_contents_delegate.h
shell/browser/ui/inspectable_web_contents_view_delegate.h
shell/browser/ui/tray_icon_observer.h
shell/browser/ui/views/autofill_popup_view.h
shell/browser/window_list_observer.h
shell/common/color_util.h
shell/common/gin_helper/event_emitter.h

Last one before honoring the quiet period, I promise
Fix a handful of [modernize-use-equals-default](https://clang.llvm.org/extra/clang-tidy/checks/modernize/use-equals-default.html) warnings. If a class having a trivial ctor/dtor was blocked by this, using `= default` will allow the compiler to make that optimization.
Notes: none.

fix: modernize-use-equals-default warnings

---

docs/api/menu.md
shell/browser/ui/cocoa/delayed_native_view_host.h
shell/browser/ui/cocoa/electron_ns_window.mm
spec/api-web-contents-spec.ts

Closes https://github.com/electron/electron/issues/44898.
Closes https://github.com/electron/electron/issues/44896.
Closes https://github.com/electron/electron/issues/44943.
Fixes an possible crash when using draggable regions and BaseWindows to get the `context-menu` event. My previous fix did not take into account that the `WebContentsView` was only added as as a sibling view in a `BrowserWindow` context. On an implementation level `menu.popup([options])` already takes a BaseWindows, so also update documentation to reflect this.
Tested with https://gist.github.com/09dd58e289571d3956cc95ea92b7d73a
Notes: Fixed an possible crash when using draggable regions and BaseWindows to get the `context-menu` event.

fix: `context-menu` event with `BaseWindows`

---

shell/browser/extensions/electron_extension_system.cc

Fix a FTBFS when the PDF viewer is enabled.
This was introduced by #44843 but it's kind of a good thing? This function has always been unused when the PDF viewer is disabled; but thanks to 44843, the compiler now has enough information to warn us about it & error out.
Notes: Fixed build failure when the PDF viewer is disabled.

fix: build failure when PDF viewer is disabled

---

docs/api/dialog.md

The docs for [Security Scoped Bookmark](https://developer.apple.com/library/content/documentation/Security/Conceptual/AppSandboxDesignGuide/AppSandboxInDepth/AppSandboxInDepth.html#//apple_ref/doc/uid/TP40011183-CH3-SW16) states that `showOpenDialog`, `showOpenDialogSync`, `showSaveDialog`, and `showSaveDialogSync` all support returning this data, when it is only the async methods that do.
This PR updates that description to only list the supported methods and provides more information about the data, copied from the parameter/return descriptions above.
Fixes #44889 
Notes: None

docs: update security scoped bookmarks info

---

shell/browser/api/electron_api_web_contents.cc
shell/browser/api/electron_api_web_contents.h
shell/browser/ui/cocoa/electron_inspectable_web_contents_view.h
shell/browser/ui/cocoa/electron_inspectable_web_contents_view.mm
shell/browser/ui/cocoa/electron_ns_window.mm
spec/api-web-contents-spec.ts

closes https://github.com/electron/electron/issues/44976
When a mouse event is signaled on `ElectronNSWindow`, it was being dispatched twice. Once from `redispatchContextMenuEvent` and once from `[super sendEvent:event]`.
https://github.com/electron/electron/blob/3bd5f14cee3ba62a654a37af76b92110e886630f/shell/browser/ui/cocoa/electron_ns_window.mm#L219-L230
`redispatchContextMenuEvent` works by temporarily disabling draggable regions, then dispatching the mouse event again on the specific WebContents. However, when the click won't pass a non-client (draggable region) hit test, it will be dispatched twice.
Instead of redispatching events, this fix proposes to globally disable draggable regions, allow the event to be processed as normally, then re-enable draggable regions. This effectively …

fix: context-menu emitted twice

---

lib/renderer/init.ts

closes https://github.com/electron/electron/issues/31724
Update the vm module warning to strongly recommend avoiding its usage rather than a deprecation warning.
The alternative is to disallow the module's usage without some kind of `dangerouslyAllowVMModule` flag. I think a warning is fine though and involves less code for us to maintain and ship.
Notes: none

chore: update vm module warning

---

lib/browser/api/web-contents.ts
typings/internal-electron.d.ts

This PR:
Notes: Fixed issue with missing index arg for `webContents.canGoToOffset`

fix: add missing index arg in `navigationHistory.canGoToOffset`

---

shell/renderer/api/electron_api_spell_check_client.cc

As reported in #44336, commit 478defb15c036eb749617ad65633b4eecd02cc66 now causes electron to freezes when using a custom spell checker.
`ReadUnicodeCharacter` updates index to the last character read, and not after it. We need to manually increment it to move to the next character.
It also doesn't validate that the index is valid, so we need to check that index is within bounds.
Refs: #44336
Notes: Fix custom spell checker getting stuck in infinite loop using 100% CPU.

fix: custom spell-checker stuck in infinite loop

---

patches/chromium/.patches
patches/chromium/cherry-pick-1282289030ab.patch

Prune superfluous calls to SetCompositorPending
We only need to call SetCompositorPending with the pending cancel
reason if the animation is running on the compositor.
The stack trace on the bug report showed a significant time being
spent in HasProperty. The timing was also optimized in this CL to
prevent unnecessary duplicate calculations.
Bug: 382394791
Change-Id: I03ffa1b486b267e05f63328212d192dfca26eb53
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6076354
Reviewed-by: Robert Flack <flackr@chromium.org>
Commit-Queue: Kevin Ellis <kevers@chromium.org>
Reviewed-by: Claire Chambers <clchambers@microsoft.com>
Cr-Commit-Position: refs/heads/main@{#1395390}
Notes: Backported fix for 382394791.

chore: cherry-pick 1282289030ab from chromium

---

.github/actions/install-build-tools/action.yml

- Followup to #44136.  That PR updated build tools to the SHA for https://github.com/electron/build-tools/pull/685, but it should instead point to the SHA of the merged commit, which is what this PR does.
Notes: none

build: update build tools to correct sha

---

lib/renderer/window-setup.ts

The message should simply read "is not supported" or, alternatively, "is not, and will not, be supported", but not "is and will not be supported".
Notes: none

fix: better prompt not supported message in window-setup.ts

---

spec/api-shell-spec.ts
spec/chromium-spec.ts

- Followup to #44136.  In investigating test failures on the 32-x-y backport of #44136 in #45013, I discovered that Edge was taking up the whole screen as seen here: 
This is due to the shell.openExternal tests opening up Edge, so I added a cleanup step to that spec to close Edge if it is open.  After doing that, all of the disabled tests now work.
Notes: none

test: reenable disabled GHA windows tests

---

patches/chromium/.patches
patches/chromium/cherry-pick-3dc17c461b12.patch

When wayland text-input-v3 is in use, a yellow background is applied the composition text, which makes the composition text hard to distinguish from the background when the app is in dark mode and the text itself is white.
This upstream patch removes the yellow background and replaces it w/ a underline. 
Refs https://issues.chromium.org/issues/382906871 , https://issues.chromium.org/issues/376516538 ,  https://issues.chromium.org/issues/355238629 .
To reproduce this on electron 33/34, run it via `electron --ozone-platform=wayland --enable-wayland-ime --wayland-text-input-version=3 "https://google.com"` on a GNOME Wayland system with fcitx5 or ibus, then enable the IME and try to input some text into the search bar.
Notes: fix yellow background of composition text with wayland …

chore: cherry-pick 3dc17c46 from chromium

---

patches/v8/.patches
patches/v8/fix_compiler_failure_on_older_clang.patch

Backports https://chromium-review.googlesource.com/c/v8/v8/+/5957255
```
npm error /home/cloudtest/.cache/node-gyp/33.3.0/include/node/v8-internal.h:1433:28: error: need 'typename' before 'Iterator::iterator_concept' because 'Iterator' is a dependent scope
npm error    using iterator_concept = Iterator::iterator_concept;
npm error                             ^~~~~~~~
```
Notes: fix native module compilation with gcc<= 8 and clang<=15

fix: native module compilation with gcc<=8

---

.github/actions/build-electron/action.yml

We're seeing an intermittent issue where the `electron` binary for Linux arm64 isn't seeming to be stripped properly. I've noticed that in these cases there's output which shows that the `electron` binary is being relinked while building the `electron:electron_dist_zip` target, which is why the stripping that occurred earlier is reverted.
It's not clear why the relinking is occurring (seems that `libinstrumentation_probes` is a commonality), so enable the `-d explain` debugging mode so the next time it happens we have extra output explaining why the relinking is happening.
We see this in nightly releases, so not going to backport it since it's just for debugging purposes.
```
2024-12-11T19:32:20.7318370Z Running "autoninja -j 300 electron:electron_dist_zip" in …
```

ci: enable debugging mode when building electron_dist_zip

---

shell/renderer/renderer_client_base.cc
shell/renderer/renderer_client_base.h

A quick small cleanup as I'm dusting off my keyboard from the holiday break :)
Xref: https://chromium.googlesource.com/chromium/src/+/main/styleguide/c++/c++.md#object-ownership-and-calling-conventions
Notes: none

refactor: remove redundant CreateExtensionsClient()

---

shell/browser/notifications/mac/cocoa_notification.mm
shell/browser/notifications/mac/notification_center_delegate.mm
shell/browser/notifications/mac/notification_presenter_mac.mm
shell/browser/notifications/notification.cc
shell/browser/notifications/notification.h
shell/browser/notifications/win/notification_presenter_win.cc
shell/browser/notifications/win/windows_toast_notification.cc

A small refactor to cache whether or not the `ELECTRON_DEBUG_NOTIFICATIONS` environment variable is set, instead of re-querying it every time.
Notes: none

perf: cache whether or not ELECTRON_DEBUG_NOTIFICATIONS env var is set

---

patches/chromium/.patches
patches/chromium/cherry-pick-3a6ff45cc3f4.patch
patches/chromium/cherry-pick-a51e7ebb7663.patch
patches/v8/.patches
patches/v8/cherry-pick-aad648bd2af9.patch
patches/v8/cherry-pick-cb0d9e1d7b88.patch

<details>
<summary>electron/security#635 - aad648bd2af9 from v8</summary>
Merged: [maglev] Avoid retagging loop phi backedges too early
When we decide that a loop phi should remain tagged, we call
EnsurePhiInputsTagged to ensures that it only has tagged inputs, which
calls EnsurePhiTagged, which might cause retagging of any untagged
phi it has as input.
In order to avoid retagging multiple times the same Phi, we have a
SnaphotTable (`phi_taggings_`), which records existing tagging in the
predecessors, and in which EnsurePhiTagged looks to avoid creating
new retagging nodes. For loop phis, the backedge predecessor won't
have an entry yet in this SnapshotTable (since we only visit loops
once, this has to be the first time we visit the header and thus
we can't have already visited the …

chore: cherry-pick 4 changes from 4-M131

---

docs/breaking-changes.md

Updating the breaking changes doc in preparation for the release of Electron 34. We identified two changes as being in the wrong sections. In both cases the PR merged after the last release, but was opened before it. Thus, their changes to this doc for the "next" version were no longer current.
I added a "correction" note to the section that we sent out in 33 but actually lands in this upcoming 34 release.
Ref: https://github.com/electron/electron/pull/43402, https://github.com/electron/electron/pull/43617
Notes: Corrected the release version of the "menu bar will be hidden during fullscreen on Windows" breaking change.

docs: correct breaking changes versions

---

script/get-git-version.py

In the old version of get-version.js, it replaces the leading 'v', i.e. |output.stdout.toString().trim().replace(/^v/g, '')|. However, in the new version of get-git-version.py, it directly replaces all 'v'. Obviously, it does not conform to the original semantics. Although it will not affect the existing electron version calculation, it may affect other developers' customized git-tag-version, such as v0.0.0-dev.xxx, which will lose the 'v' of dev.

fix: only remove the 'v' prefix from the git tag name

---

build/args/all.gn

Node PR: https://github.com/nodejs/node/pull/56513
Do not merge before attached Node PR is merged. This PR updates our NMV to 133 for Electron 35
Please merge this PR before branching 35-x-y
Notes: none

build: bump NMV to 133

---

shell/browser/api/electron_api_session.cc

Fixes #44853.
The `clearData` API uses `kClearDataTypeAll` when the `dataTypes` option is not set. This default value currently includes the `avoidClosingConnections` option, which contradicts that option's default value of `false`. This PR updates the default value (`kClearDataTypeAll`) to respect `avoidClosingConnections`'s default value of `false`.
Notes: The `avoidClosingConnections` option for `session.clearData` now properly defaults to `false` when the `dataTypes` option is not set.

fix: `session.clearData` `avoidClosingConnections` default to false

---

patches/chromium/.patches
patches/chromium/cherry-pick-35f86d6a0a03.patch
patches/config.json
patches/skia/.patches
patches/skia/ganesh_avoid_overflow_when_combining_aahairlineops.patch
patches/v8/.patches
patches/v8/cherry-pick-3c2d220ad025.patch

* 3c2d220ad025 from v8
* 35f86d6a0a03 from chromium
* c17fe9bc158c from skia
Notes:
* Security: backported fix for CVE-2025-0434.
* Security: backported fix for CVE-2025-0436.
* Security: backported fix for CVE-2025-0437.

chore: cherry-pick 3 changes from 0-M132

---

shell/browser/file_system_access/file_system_access_permission_context.cc
shell/browser/file_system_access/file_system_access_permission_context.h

Closes https://github.com/electron/electron/issues/45051.
Closes https://github.com/electron/electron/issues/45225.
Refs https://chromium-review.googlesource.com/c/chromium/src/+/5807287
Fixes an issue where drag-dropping two directories would cause `getAsFileSystemHandle` to never resolve. This happened because the existing logic only expected one directory and so the callback would be overwritten in this use case, triggered by a feature flag change upstream. We store this callback in order to emit an event on session, which is why this happened in Electron and not upstream as well. Fix this by keeping a map of callbacks corresponding to their file paths.
Notes: Fixed an issue where drag-dropping two directories would cause `getAsFileSystemHandle` to never resolve.

fix: `getAsFileSystemHandle` failure when drag-dropping two directories

---

spec/api-browser-window-spec.ts

Attempt to fix this issue causing flakes during visual testing.
Notes: none

test: quit Finder

---

shell/utility/electron_content_utility_client.cc

Refs CL:6032774 via https://github.com/electron/electron/pull/44748
Fixes broken printing on macOS/Linux with the following error messages:
```
[69931:0116/114046.603990:ERROR:utility_thread_impl.cc(227)] Cannot run unknown service: printing.mojom.UnsandboxedPrintBackendHost
[69913:0116/114048.175058:ERROR:device_event_log_impl.cc(199)] [11:40:48.174] Printer: printer_query_oop.cc:140 Error after getting settings due to client registration failure; service or renderer likely has terminated
```
Fix this by registering the relevant services in `ElectronContentUtilityClient`.
Tested with https://gist.github.com/0f0e776b138452d6815ef4efc16aa0d1
Notes: Fixed broken OOP `window.print()` on macOS/Linux.

fix: broken OOP `window.print()` on macOS/Linux

---

shell/browser/file_system_access/file_system_access_permission_context.cc

Refs https://chromium-review.googlesource.com/c/chromium/src/+/5786874
Refs https://chromium-review.googlesource.com/c/chromium/src/+/5794141
Addresses two possible crashes in the File System Access API fixed upstream.
Notes: Addressed two possible crashes in the File System Access API.

fix: two possible FSA crashes

---

patches/chromium/printing.patch

Closes https://github.com/electron/electron/issues/45080.
Refs CL:5349263
Fixes an issue where print scaling could be too small during silent print. This happened as a result of the above CL, where Chromium (which has no silent print) changed a default to scale down if necessary but not up as was done previously in `kFitToPrintableArea`.
Notes: Fixed an issue where print scaling could be too small during silent print.

fix: page scaling in silent mode printing

---

script/run-clang-format.py

Remove duplicate message on clang-format failure exit.
<details><summary>Sample</summary>
<p>
```
electron on git:fix-fsa-crashes ❯ npm run lint                    10:37AM
> electron@0.0.0-development lint
> node ./script/lint.js && npm run lint:docs
--- a/shell/browser/file_system_access/file_system_access_permission_context.cc
+++ b/shell/browser/file_system_access/file_system_access_permission_context.cc
@@ -474,8 +474,8 @@
bool creating_new_grant = !existing_grant;
if (creating_new_grant) {
grant = base::MakeRefCounted<PermissionGrantImpl>(
-        weak_factory_.GetWeakPtr(), origin, path_info, handle_type, GrantType::kRead,
-        user_action);
+        weak_factory_.GetWeakPtr(), origin, path_info, handle_type,
+        GrantType::kRead, user_action);
existing_grant = …
```

build: fix clang-format duplicate message

---

shell/browser/electron_browser_client.cc

This PR brings some of our `blink::web_pref::WebPreferences` into alignment with upstream Chromium.
Notes: none

chore: align `clipboard blink::web_pref::WebPreferences` with upstream

---

.github/workflows/branch-created.yml
.github/workflows/issue-labeled.yml
.github/workflows/issue-opened.yml
.github/workflows/issue-transferred.yml
.github/workflows/issue-unlabeled.yml
.github/workflows/pull-request-labeled.yml
.github/workflows/stable-prep-items.yml

We have occasional workflow failures (usually when blocked labels are added to non-bug issues) when the issue is not on a project board - this can also happen with race conditions if a maintainer changes a label and then removes the issue from a project board before the workflow runs, for example.
I've updated `dsanders11/project-actions` to add an input to not fail the workflow in these cases, since it just creates noise for us.
Notes: none

ci: don't fail issue triage workflows if issue not found on project

---

patches/chromium/printing.patch

Ref CL:6032774
Fixes `webContents.print()` after switch to OOP printing on macOS and Linux. We need to make sure that `query_with_ui_client_id_.has_value()` is true, which isnt a scenario upstream hits since we use the update print settings pathway by default when we pass custom settings via `webContents.print()`.
Tested with https://gist.github.com/codebytere/0f0e776b138452d6815ef4efc16aa0d1
✅ A print job can be sent
✅ Two print jobs can be sent consecutively
✅ A print job can be cancelled and a successful print job sent afterwards
Notes: Fixed `webContents.print()` after switch to OOP printing on macOS and Linux.

fix: `webContents.print()` with OOP printing

---

shell/browser/extensions/api/scripting/scripting_api.cc

Simplify ParseUserScript() by removing some boilerplate code that hasn't been necessary since #43205.
Notes: none.

refactor: simplify `ParseUserScript()`

---

shell/browser/api/electron_api_content_tracing.cc

StopTracing() has compile-time string literals that need to get passed to a method that takes a `std::string_view` argument, so the extra `std::optional<std::string>` scaffolding is just extra work that we don't need to do
Notes: none

refactor: in `StopTracing()`,  use string literals instead of `optional<string>`

---

.github/workflows/branch-created.yml
.github/workflows/issue-labeled.yml
.github/workflows/issue-opened.yml
.github/workflows/issue-transferred.yml
.github/workflows/issue-unlabeled.yml
.github/workflows/pull-request-labeled.yml
.github/workflows/stable-prep-items.yml

Bumps `dsanders11/project-actions` again to pick up a fix for redacted items being on a project board. This happened with our issue triage board when an issue on this repo was transferred to a private repo, leaving a dangling redacted item on the board. The current version of `dsanders11/project-actions` doesn't handle redacted items properly so some of the issue workflows can choke when the GraphQL API returns one.
This PR fixes two main things:
* Work as expected even if there's a redacted item on the issue triage board
* Bonus fix for the issue transferred workflow, which needs to use the new URL when removing the item from the board - I've also restricted the workflow to only run if the issue was transferred to a public repo, to prevent it from leaking the new URL (and as such the …

ci: fix issue workflow failures

---

docs/tutorial/window-customization.md

After #43693 was merged, `window-customization.md` became sort of a section index doc. This PR augments it with a Docusaurus component so that we get nice little auto-generated index cards.
ref https://docusaurus.io/docs/sidebar/items#embedding-generated-index-in-doc-page
Notes: none

docs: add DocCardList component for index doc

---

shell/browser/extensions/api/tabs/tabs_api.cc

Refs CL:6042891
From the CL:
> tabs.update() can trigger navigations by providing a new URL. These may
be rejected for any number of reasons. We catch some of these (e.g.,
debug URLs), but do not (and likely will never) have all the same checks
in the extensions layer that we do throughout the navigation stack. This
causes issues, since we expect (and DCHECK) that a navigation
successfully starts, which is causing a crash in the case that it fails.
Notes: Fixed a potential crash in `chrome.tabs.update()`.

fix: potential crash in `chrome.tabs.update()`

---

shell/app/node_main.cc
shell/common/node_bindings.cc
shell/common/node_util.cc
shell/common/node_util.h

If `node::CreateEnvironment()` fails in NodeBindings, log some more helpful  information, e.g. the file and line number where the error occurred.
I've only aimed this at 35-x-y since strictly speaking this is `semver/minor`, but IMO would be safe for older branches too.
Notes: Added more helpful logging if Node.js fails to initialize.

chore: better logging if Node initialization fails

---

docs/tutorial/fuses.md
docs/tutorial/security.md

Closes #45228 by updating our security checklist with guidance to not directly expose Electron APIs to untrusted web content through preload.

docs: Add note about directly exposing Electron APIs in preload

---

docs/api/context-bridge.md
lib/renderer/api/context-bridge.ts
shell/renderer/api/electron_api_context_bridge.cc
shell/renderer/api/electron_api_context_bridge.h
shell/renderer/api/electron_api_web_frame.cc
shell/renderer/renderer_client_base.cc
spec/api-context-bridge-spec.ts
typings/internal-electron.d.ts

Split from https://github.com/electron/electron/pull/44411
Implements part of [RFC #8](https://github.com/electron/rfcs/blob/main/text/0008-preload-realm.md)
`contextBridge.executeInMainWorld` is added to accept `{ func: Function, args: any[] }`. This allows serializing a function and arguments over the context bridge to be executed in the main world.
Tests to guarantee return values go through the context bridge reuse the logic from our [webFrame.executeJavaScript world safe test.](https://github.com/electron/electron/blob/6e3a5daf62314d4de541d64a1098b0bb3a37168c/spec/api-web-frame-spec.ts#L13-L27) The internals of `executeInMainWorld` are shared with `exposeInMainWorld`.
- Extension IDL specifies `[serializableFunction]` for Function argument \ …

feat: contextBridge.executeInMainWorld

---

.github/workflows/windows-publish.yml

We don't need to use the sas-token for Windows checkout (it's Mac only). Remove the requirement
Notes: none

build: remove generate-sas-token

---

shell/browser/resources/mac/Info.plist

https://support.apple.com/en-us/102125
> Apps can be updated to work better with this area of your screen. If a developer updates their app for compatibility with your Mac, the "Scale to fit below built-in camera" setting no longer appears.
Notes: Added `NSPrefersDisplaySafeAreaCompatibilityMode` = `false` to Info.plist to remove "Scale to fit below built-in camera." from app options.

build: add `NSPrefersDisplaySafeAreaCompatibilityMode` = `false` to Info.plist

---

.github/actions/install-build-tools/action.yml

Fixes our Windows CI to use Python 3.11.9/ the Python311.exe
Notes: none

build: use Python311 exe

---

docs/api/ipc-renderer.md

Refs #45228
Add security warning directly to `ipcRenderer.on` documentation.
This is a follow-up to #45241. Some of the proposed changes didn't make it into the version that was merged.
CC @felixrieseberg
Notes: none

docs: reference security guide in `ipcRenderer.on` docs

---

.github/workflows/pipeline-electron-build-and-test-and-nan.yml
.github/workflows/pipeline-electron-build-and-test.yml
.github/workflows/pipeline-electron-lint.yml
.github/workflows/pipeline-segment-electron-build.yml
.github/workflows/pipeline-segment-electron-test.yml
.github/workflows/pipeline-segment-node-nan-test.yml

It appears that on occasion our concurrency settings don't properly work for main and release branches, eg:
https://github.com/electron/electron/actions/runs/12941897356/job/36101814325.
This PR changes our concurrency settings to use a different concurrency tag for all of our protected branches and also explicitly sets cancel-in-progress to true for non-protected branches.
Notes: none

build: fixup concurrent builds on protected branches

---

patches/chromium/feat_add_support_for_missing_dialog_features_to_shell_dialogs.patch

Closes https://github.com/electron/electron/issues/45250.
Fixes an issue where selection of multiple directories didn't work on Linux. This was due to the fact that upstream's implementation didn't account for more than one directory being chosen. We patched that in partially but not completely.
Notes: Fixed an issue where selection of multiple directories with the `dialog` module didn't work on Linux.

fix: multiple directory selection on Linux

---

.github/workflows/pull-request-labeled.yml

Looks like [this commit](https://github.com/slackapi/slack-github-action/commit/e9b3a6beef047e819b8fb417da538f97a93a2ec8) in the action changed some of the logic around to require that a `webhook-type` be passed explicitly as an input.
This will fix backport requests not being sent to the expected Slack channel.
See sample error: https://github.com/electron/electron/actions/runs/12941904035/job/36406556780
Notes: none

build: fix `slack-github-action` for backports

---

docs/api/view.md
shell/browser/api/electron_api_view.cc
shell/browser/api/electron_api_view.h
spec/api-view-spec.ts

resolves https://github.com/electron/electron/issues/44961
Adds method to get visibility state of Views.
Notes: Added `view.getVisible()`

feat: view.getVisible()

---

patches/chromium/feat_add_support_for_missing_dialog_features_to_shell_dialogs.patch

Closes https://github.com/electron/electron/issues/44390.
Fixed a bug where the default path didn't always correctly fill the Name field in KDialogs on Linux. Existing logic upstream ensured that the path command line argument was never empty, but if it's a relative path it wouldn't be correctly prefilled.
Fix this by ensuring that it's an absolute path created by appending the relative path to PWD if necessary.
<details><summary>Post-Fix</summary>
<p>
</p>
</details> 
Upstreamed in CL:6219304
Notes: Fixed a bug where the default path didn't always correctly fill the Name field in KDialogs on Linux.

fix: default path not working on KDE Linux

---

shell/browser/ui/views/win_caption_button_container.cc

Refs https://chromium-review.googlesource.com/c/chromium/src/+/6098828.
From CL:
> This CL addresses an issue in RTL languages where the window caption
buttons display incorrect tooltips. The issue was caused by using `bounds()` for hit testing, which does not account for RTL layouts. The fix replaces `bounds()` with `GetMirroredBounds()`, ensuring that hit testing works correctly in both LTR and RTL contexts.
Notes: Fixed an issue where RTL tooltips could be incorrect when using WCO on Windows.

fix: incorrect WCO tooltip in RTL

---

.github/workflows/pipeline-segment-electron-test.yml
script/lib/get-version.js

While the deleted comment is accurate, we use `python3` extensively throughout the rest of the build scripts, and more importantly `depot_tools` only ships with a `python3.bat` these days. The existing code causes building to fail on a fresh Windows machine if Python is not installed - otherwise the Python version bundled with `depot_tools` is used and works fine.
Required one minor tweak to the test pipeline segment for WOA to ensure `python3` can be found - I believe this is because `depot_tools` doesn't have an arm64 recipe for Python on Windows.
Notes: none

build: always use python3 in `script/lib/get-version.js`

---

docs/breaking-changes.md

Since Electron v33, C++20 has been required for building native modules. This was mentioned in the [blog post](https://www.electronjs.org/blog/electron-33-0#behavior-changed-native-modules-now-require-c20) but not in the breaking changes document. This PR changes that. The wording was copied from the blog post.
CC @VerteDinde
Notes: none

docs: mention C++20 requirement in breaking changes document

---

docs/breaking-changes.md

Refs #45396
Documents a breaking change in Electron 32.
Notes: none

docs: document deletion of `databases` directory

---

shell/browser/api/electron_api_cookies.cc

Upstream added a new cookie exclusion type `EXCLUDE_ALIASING` last December in https://chromium-review.googlesource.com/c/chromium/src/+/6071023 but until now we weren't handling it in `InclusionStatusToString()`.
This PR:
- Adds a human-readable string for `EXCLUDE_ALIASING`
- Adds a `static_assert()` to ensure that if more reasons are added in the future, the compiler will give us a heads-up
- Uses a `std::ostringstream` to make building the `reason` string a little more efficient
Notes: none.

fix: handle exclude aliasing in InclusionStatusToString()

---

patches/node/fix_revert_src_lb_reducing_c_calls_of_esm_legacy_main_resolve.patch
script/node-disabled-tests.json

Follow up to https://github.com/electron/electron/pull/45307 - re-enable temporarily disabled test due to permission model differences owing to a patch we reverted. Adjust our reverted patch to match upstream expectations.
Notes: none

fix: `legacyMainResolve` respecting permission model

---

shell/browser/native_window_views.cc
shell/browser/ui/views/win_caption_button_container.cc

Fixes an issue where Windows Control Overlay didn't work with some window configurations, specifically transparent windows on Windows. For example, the maximize button didn't work on transparent windows at all. This was happening because WCO buttons always called the related methods on `views::Widget`, but our more complex window configurations have extra handling in `NativeWindow`. This PR updates the WCO buttons to call the correct methods on `NativeWindow` instead of `views::Widget`.
This is a prerequisite to some other Mica-related fixes I'll have up soon, which are partially broken because they now incorporate transparency.
Notes: Fixed an issue where Windows Control Overlay didn't work with some window configurations.

fix: WCO not working with some window configurations

---

patches/chromium/.patches
patches/chromium/cherry-pick-dd8e2822e507.patch

Set is_web_secure_context when initializing Service Worker from disk
The value of is_web_secure_context is not serialized to disk when
storing the service worker registration (only a few select policies
are).
When instantiating the policy container for an already-registered
worker, it uses the default value (false) which is wrong.
Since Service Workers are guaranteed to ALWAYS be a web secure
context, this change explicitly sets it to true when restoring a
serialized policy.
See: https://w3c.github.io/webappsec-secure-contexts/#examples-service-workers
Bug: 387258077,383070811
Change-Id: I75efe895662ab4e6d68cacace6d05e004c5dfd33
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6236205
Reviewed-by: Hiroki Nakagawa <nhiroki@chromium.org>
Reviewed-by: Dave Tapuska …

chore: cherry-pick dd8e2822e507 from chromium

---

shell/browser/api/electron_api_auto_updater.cc
shell/common/api/electron_bindings.cc
shell/common/gin_helper/callback.h
shell/common/gin_helper/event_emitter_caller.cc
shell/common/gin_helper/function_template.h
shell/common/gin_helper/microtasks_scope.cc
shell/common/gin_helper/microtasks_scope.h
shell/common/gin_helper/promise.cc
shell/common/node_bindings.cc
shell/common/v8_util.cc
shell/renderer/api/electron_api_spell_check_client.cc
shell/renderer/electron_render_frame_observer.cc
shell/renderer/electron_sandboxed_renderer_client.cc
shell/renderer/web_worker_observer.cc

There is no need to pass both `v8::Isolate` and `v8::MicrotaskQueue` as we can get both from the `v8::Context`
Notes: none

refactor: only pass `v8::Context` to `gin_helper::MicrotasksScope` constructor

---

shell/browser/api/electron_api_web_frame_main.cc
shell/browser/api/electron_api_web_frame_main.h

Fixes #45142. This PR uses the solution suggested there by @alexi in that issue and also applies it to a couple of other potentially risky places.
Notes: Fixed crash when accessing WebFrameMain frames and name attributes on destroyed frames.

fix: RenderFrameHost nullptr dereference

---

docs/tutorial/online-offline-events.md

- Removed width and height params because output could not be seen.
Notes: none

docs: remove width and height params

---

.github/actions/checkout/action.yml

As seen in https://github.com/electron/electron/actions/runs/13157928831/job/36733003034#step:4, compressed src is now 32G, so we need to update the check for free disk space for source caches.
Notes: none

build: make sure there is at least 35GB free for source cache

---

shell/browser/api/electron_api_service_worker_main.cc
shell/browser/api/electron_api_web_frame_main.cc
shell/browser/extensions/api/management/electron_management_api_delegate.cc

Small code cleanup to follow upstream's suggestions on when to use `GURL::EmptyGURL()` and when to use `GURL::GURL()`:
```
// Returns a reference to a singleton empty GURL. This object is for
// callers who return references but don't have anything to return in
// some cases. If you just want an empty URL for normal use, prefer
// GURL().
```
So this PR uses `GURL()` when we want a new instance of an empty URL, and uses `GURL::EmptyGURL()` when we need a reference to an empty URL.
Notes: none.

refactor: follow upstream's suggestions on when to use EmptyGURL()

---

shell/browser/native_window_mac.mm
shell/browser/ui/cocoa/electron_ns_window.h
shell/browser/ui/cocoa/electron_ns_window.mm

fix: Update widget visibility in `NativeWindowMac::ShowInactive`
When using `views::WebView` on macOS `NativeWidgetMacNSWindowHost`
contains a layer and compositor responsible for drawing web contents.
To trigger drawing `NativeWidgetMacNSWindowHost::OnVisibilityChanged`
needs to be called and `[NSWindow orderFrontRegardless]` does not trigger
`[NSWindow orderWindow:relativeTo:]` which can change
`NativeWidgetMacNSWindowHost` visiblity with stack:
```
views::NativeWidgetMacNSWindowHost::OnVisibilityChanged(bool)
remote_cocoa::NativeWidgetNSWindowBridge::OnVisibilityChanged()
-[ViewsNSWindowDelegate onWindowOrderChanged:]
-[NativeWidgetMacNSWindow orderWindow:relativeTo:]
```
`views::Widget` has method for showing inactive window:
`views::Widget::ShowInactive` which triggers …

fix: Update widget visibility in `NativeWindowMac::ShowInactive`

---

shell/browser/native_window_views.cc
shell/browser/native_window_views.h
shell/browser/native_window_views_win.cc

Closes https://github.com/electron/electron/issues/41824
Depends on https://github.com/electron/electron/pull/45422.
Refs https://github.com/electron/electron/pull/39708.
This PR mitigates an issue where the window lost its `backgroundMaterial` effects on maximization - turning black and losing its rounded corners. This happened in part because we made changes in an earlier PR to set transparency for correct Mica/Acrylic visuals, but didn't take into account that we'd then need to treat it in the special ways we treat transparent windows on Windows beyond that. This PR addresses those issues by expanding transparent handling to include `backgroundMaterial` translucency.
This PR comes at cost of losing the smooth window animation, which is something I'm hopeful i can fix as a follow up. …

fix: window maximizing with Mica

---

patches/chromium/cherry-pick-dd8e2822e507.patch

Small quality of life PR, cleans up the patch shas for cherry-pick-dd8e2822e507.patch
Notes: none

chore: clean up web secure context patch

---

docs/api/in-app-purchase.md

The description of the `transactions-updated` event is not in the order expected by the docs parser, which generates type information. Reordering the description after the type information fixes the generated types.
Fixes #45140
Notes: none

docs: `transactions-updated` event type

---

.github/actions/build-electron/action.yml

Broken by the migration to GHA on Windows, this PR fixes the path for gen\v8\embedded.S used for mksnapshot
Notes: Fixed the path for a needed library used for mksnapshot

fix: fix mksnapshot gen/v8 path

---

spec/chromium-spec.ts
spec/lib/screen-helpers.ts

Fixes #45322.  Using a newly added spec helper `takeScreenshot`, I was able to determine that on the focus tests in Windows, the testing window was behind other windows which interfered with the focus tests.  This PR changes our focus tests to make sure the test window is always on top.
Notes: none

test: make sure test window is on top for focus tests

---

docs/api/system-preferences.md
docs/breaking-changes.md
lib/browser/api/system-preferences.ts
shell/browser/api/electron_api_system_preferences.cc
shell/browser/api/electron_api_system_preferences.h
shell/browser/api/electron_api_system_preferences_win.cc
spec/api-system-preferences-spec.ts
spec/ts-smoke/electron/main.ts

This function has been hardcoded to return `true` since Electron 23, which only supports Windows 10+, where DWM composition can no longer be disabled.
https://learn.microsoft.com/en-us/windows/win32/dwm/composition-ovw#disabling-dwm-composition-windows7-and-earlier
Notes: The `systemPreferences.isAeroGlassEnabled()` API has been deprecated and will be removed without replacement.

chore: deprecate `systemPreferences.isAeroGlassEnabled()`

---

shell/browser/api/electron_api_web_contents.cc
shell/browser/api/electron_api_web_contents.h
shell/browser/electron_web_contents_utility_handler_impl.cc
shell/browser/electron_web_contents_utility_handler_impl.h
shell/common/web_contents_utility.mojom
shell/renderer/api/electron_api_web_frame.cc
spec/api-web-frame-spec.ts

Calling the `getZoomLevel` method (and its related `getZoomFactor` method) of the `webFrame` Renderer module causes an IPC call to the browser process to get the zoom level. However, the renderer already must know the zoom level for rendering. We should use the local information in the renderer process instead of the expensive IPC call to the browser process.
Notes: Optimized `webFrame.getZoomLevel` and `webFrame.getZoomFactor` APIs.

fix: avoid IPC for renderer `webFrame.getZoom...` APIs

---

script/gen-libc++-filenames.js

While working on #45535 I noticed that touching the `DEPS` file on Windows causes `filenames.libcxx.gni` and `filenames.libcxxabi.gni` to be regenerated with what appears to be a different list of paths. When I debugged the issue, I found that there are two causes for this:
1. The list of files returned by `fs.readdirSync` is not consistent between Mac and Windows, so when the script traverses the include directories on Windows, it gets back a list of paths that is in a different order.
2. For headers in nested folders, the `path.relative(path.resolve(...))` call still ends up with a backslash in the relative path on Windows.
To address these Windows inconsistencies, this PR updates the `findAllHeaders` function to sort the list of files in a folder before iterating over them, and updates …

build: make gen-libc++-filenames.js produce the same results on Windows

---

docs/api/navigation-history.md
docs/api/structures/navigation-entry.md
docs/tutorial/navigation-history.md
lib/browser/api/web-contents.ts
shell/browser/api/electron_api_web_contents.cc
shell/browser/api/electron_api_web_contents.h
spec/api-web-contents-spec.ts
typings/internal-electron.d.ts

This PR exposes a `navigationHistory.restore(index, entries)` API that allows developers to restore navigation history on a new webContents. Then, it also adds Chromium's own `pageState` to `NavigationEntry`, which allows developers to restore scroll position, form entries, and everything else that's part of Blink's serialized page state. This empowers developers to _really_ rehydrate apps, including "Opening apps at the same scroll position" or "Undo close tab".
The changes are straightforward. The only "decision" I've made is around `pageState`: Chromium itself serializes it to a binary string hex format that doesn't survive JSON serialization/deserialization. To make this easier for devs, I've decided to encode that hex format as base64 on our side. 
Notes: Added …

feat: Restore webContents navigation history and page state

---

.github/workflows/pipeline-segment-electron-test.yml
spec/chromium-spec.ts

In researching #45435, I noticed that sometimes on macOS [the keyboard lock test fails ](https://github.com/electron/electron/actions/runs/13229401223/job/36925369357)so I added a screenshot before that test and saw the following unexpectedly quit dialog:
I'm not 100% sure that this is why the keyboard lock test fails, but either way we should disable this dialog on macOS so that it doesn't interfere with testing on macOS.
Notes: none

test: disable unexpectedly quit dialog on macOS

---

DEPS

The `checkout_google_benchmark ` var was added to `DEPS` in https://github.com/electron/electron/commit/bf6e4b1247f3a48e8926080b1852ec5d739f0888 as part of a Chromium roll 6 years ago. 
I was curious what he variable did, so I poked around in the Chromium codebase. I found that the variable stopped having any effect in https://chromium-review.googlesource.com/c/chromium/src/+/4322306 and was removed from Chromium entirely in https://chromium-review.googlesource.com/c/chromium/src/+/4339138
It seems that including it in the Electron `DEPS` now has no effect, so this PR removes it to avoid confusion.
After making this change, I decided to double check the other variables in `DEPS`, and found that two others are also no longer declared in Chromium, so presumably setting them in Electron's …

chore: remove var declarations from DEPS that no longer have any effect

---

docs/api/power-monitor.md

Manually backport #45518 to 34-x-y. See that PR for details.
Notes: none

docs: fix powerMonitor event types (34-x-y)

---

.github/workflows/pipeline-segment-node-nan-test.yml

Change CI so that node tests timeout after 30 minutes instead of 20 minutes.
I've been hitting this in the Chromium roll and thought it might be new to the roll, but I see it's also happening in other PRs too. [here](https://github.com/electron/electron/actions/runs/13305285935/job/37165067833)
CC @electron/wg-infra 
Notes: none.

chore: change node test timeout from 20m to 30m

---

spec/api-content-tracing-spec.ts

Disable flaky test.  Test failures seen [here](https://github.com/electron/electron/pull/45573#issuecomment-2657366546) and in the main Chromium roll.
CC @codebytere
Notes: none.

chore: disable flaky content tracing tests on Linux

---

shell/browser/api/electron_api_web_contents.cc
shell/browser/api/electron_api_web_contents.h

Refs https://chromium-review.googlesource.com/c/chromium/src/+/5909989.
Implements `IsWaitingForPointerLockPrompt` to fix potential issues with pointer lock permissions after focus loss and regain.
Notes: Fixed a potential issues permissions in the Pointer Lock API after focus loss and regain.

fix: pointer lock permission after focus loss and regain

---

shell/browser/osr/osr_render_widget_host_view.cc
shell/browser/osr/osr_render_widget_host_view.h

Closes https://github.com/electron/electron/issues/45486.
Refs CL:5909989.
Fixes a crash that occurred in OSR after the above CL, which called into a `RenderWidgetHostDelegate` function without checking whether or not the delegate had been previously detached. Also pull in some other dtor fixes from CEF - see [here](https://github.com/chromiumembedded/cef/blame/144e01e377249cd614378cb7084a3ed9b06803ca/libcef/browser/osr/render_widget_host_view_osr.cc)
Notes: Fixed a crash that could occur in OSR on window close.

fix: osr crash on window close

---

.github/workflows/pipeline-electron-lint.yml
.github/workflows/pipeline-segment-node-nan-test.yml

Followup to #45581.  The lint job and the node test jobs were not getting the environment variable needed to set the chromium cookie.
Notes: none

build: make sure chromium cookie is set everywhere

---

docs/api/command-line-switches.md
shell/browser/electron_browser_main_parts.cc
shell/browser/javascript_environment.cc
shell/browser/javascript_environment.h
shell/common/node_bindings.cc
shell/common/node_bindings.h
shell/renderer/electron_renderer_client.cc
shell/services/node/node_service.cc
spec/api-utility-process-spec.ts
spec/fixtures/api/utility-process/oom-grow.js

Backport of https://github.com/electron/electron/pull/45606
Notes: Fix `v8.setHeapSnapshotNearHeapLimit` api in main and utility process, along with support for `--diagnostic-dir` Node.js cli flag to specify the directory to save the heap snapshots.

fix: support for v8.setHeapSnapshotNearHeapLimit api

---

.github/workflows/clean-src-cache.yml

Attempt to address persistent source cache space issues:
See https://github.com/electron/electron/pull/45641
> The cross mount cache has 27G free space which is not enough - exiting
Notes: none

build: run source cache clean daily

---

lib/browser/api/session.ts
lib/browser/api/web-contents.ts
lib/browser/guest-view-manager.ts
lib/browser/ipc-dispatch.ts
shell/browser/api/electron_api_web_contents.cc
shell/browser/api/electron_api_web_contents.h
shell/browser/api/ipc_dispatcher.h
shell/browser/electron_api_ipc_handler_impl.cc
shell/browser/electron_api_ipc_handler_impl.h
shell/browser/electron_api_sw_ipc_handler_impl.cc
shell/browser/electron_api_sw_ipc_handler_impl.h

When an IPC is received from a service worker (https://github.com/electron/electron/pull/44411), an event object is created and then dispatched from the associated `Session`. These changes follow the same path for IPC from render frames.
- Internal IPC event listeners now scale with `# of Sessions` instead of `# of WebContents`
- Reduces size of `electron_api_web_contents.cc` and `web-contents.ts` by splitting up IPC code
- Unifies JS dispatch of frame and service worker IPC
- Assigns `event.sender` from native code
- Renames `ipc-message-host` event to `-ipc-message-host`
- This was undocumented so the `-` is added to indicate its internal usage
```mermaid
flowchart TD
IsolatedWorld[Isolated World / Frame] --> IPCSend;
IPCSend["ipcRenderer.send(channel,&nbsp;...)"] --> IPCRenderFrame; …
```

refactor: dispatch IPC messages from Session

---

shell/browser/native_window_mac.mm
spec/api-browser-window-spec.ts

Accessing `[QLPreviewPanel sharedPreviewPanel]` causes the panel to be initialized and reappear according to [QLPreviewPanel.h](https://github.com/phracker/MacOSX-SDKs/blob/041600eda65c6a668f66cb7d56b7d1da3e8bcc93/MacOSX10.6.sdk/System/Library/Frameworks/Quartz.framework/Versions/A/Frameworks/QuickLookUI.framework/Versions/A/Headers/QLPreviewPanel.h#L36-L39).
```
/*!
* @abstract Returns the QLPreviewPanel instance, creating it if it doesnÕt exist yet.
*/
+ (QLPreviewPanel *)sharedPreviewPanel;
```
Thus when calling `win.closeFilePreview` multiple times, it would recreate the closed window every other call.
To fix this, we can release the `preview_file_` data source and gate based on its existence before accessing `[QLPreviewPanel sharedPreviewPanel]`.
This resolves our flaky visual tests …

fix: win.closeFilePreview recreates panel when called twice

---

spec/chromium-spec.ts

This has [flaked out on a half-dozen PRs](https://github.com/search?q=repo%3Aelectron%2Felectron+%22should+lock+the+keyboard%22&type=pullrequests
) in the past few weeks. It should be disabled to stop blocking PRs -> investigated ->  fixed + re-enabled.
Tracking issue: #45680
Notes: none.

chore: disable 'should lock the keyboard' test on macOS

---

docs/api/system-preferences.md
docs/breaking-changes.md
lib/browser/api/system-preferences.ts
spec/api-system-preferences-spec.ts
spec/ts-smoke/electron/main.ts

Finish deprecation from #45434
Notes: The deprecated `systemPreferences.isAeroGlassEnabled()` API has been removed.

chore: remove deprecated `systemPreferences.isAeroGlassEnabled()`

---

shell/browser/electron_browser_client.cc

Fixes an issue with chrome extensions in which calling `new Worker('chrome-extension://...')` would fail with `ERR_UNKNOWN_URL_SCHEME`. Below is a net log snippet of the problem.
```
42: URL_REQUEST
chrome-extension://likgccmbimhjbgkjambclfkhldnlhbnn/js/dictionary/dictionary-database-worker-main.js
Start Time: 2025-02-18 19:52:14.572
t=298 [st=0] +CORS_REQUEST  [dt=0]
--> cors_preflight_policy = "consider_preflight"
--> headers = "Accept: */*\r\n\r\n"
--> is_revalidating = false
--> method = "GET"
--> url = "chrome-extension://likgccmbimhjbgkjambclfkhldnlhbnn/js/dictionary/dictionary-database-worker-main.js"
t=298 [st=0]    CHECK_CORS_PREFLIGHT_REQUIRED
--> preflight_required = false
t=298 [st=0]   +REQUEST_ALIVE  [dt=0]
--> priority = "IDLE"
--> traffic_annotation = 72087791
--> url = …
```

fix: extension web workers net request failing

---

shell/browser/api/electron_api_web_contents.cc
shell/browser/api/electron_api_web_frame_main.cc
shell/browser/api/electron_api_web_frame_main.h
shell/common/gin_converters/std_converter.h
spec/api-web-frame-main-spec.ts
typings/internal-electron.d.ts

Backport of https://github.com/electron/electron/pull/45609
Notes: Fixed WebFrameMain crash related to accessing speculative frames that have been destroyed.

fix: dangling speculative frames

---

shell/browser/electron_download_manager_delegate.cc
shell/browser/electron_download_manager_delegate.h

Refs http://crbug.com/593020.
Small refactor - `GetDownload` is deprecated.
Notes: none

refactor: track downloads by guid

---

shell/browser/extensions/api/extension_action/extension_action_api.cc

Fixes one of the errors when compiling electron with `is_debug = true`.
relates to https://github.com/electron/electron/issues/44962
Notes: none

fix: action.openPopup function missing

---

patches/chromium/fix_osr_stutter_in_both_cpu_and_gpu_capture_when_page_has_animation.patch

A fresh checkout of `33-x-y` was failing when applying patches:
```
Applying: Ignore parse errors for PKEY_AppUserModel_ToastActivatorCLSID
Applying: feat: add signals when embedder cleanup callbacks run for gin::wrappable
Applying: feat: separate content settings callback for sync and async clipboard
Applying: fix: osr stutter in both cpu and gpu capture when page has animation.
error: patch failed: media/capture/content/video_capture_oracle.cc:198
error: media/capture/content/video_capture_oracle.cc: patch does not apply
Patch failed at 0144 fix: osr stutter in both cpu and gpu capture when page has animation.
hint: Use 'git am --show-current-patch=diff' to see the failed patch
hint: When you have resolved this problem, run "git am --continue".
hint: If you prefer to skip this patch, …
```

chore: fix broken patches in 33-x-y

---

spec/fixtures/api/utility-process/log.js

This fixture has been calling process.exit() immediately after writing to stdout and stderr, which the [Node.js docs say](https://nodejs.org/api/process.html#processexitcode) is risky behavior:
> Calling process.exit() will force the process to exit as quickly as
> possible even if there are still asynchronous operations pending that
> have not yet completed fully, including I/O operations to
> process.stdout and process.stderr.
This fixture's been around for years without problems (AFAIK). The writes are very small (`'hello\n'` and `'world'`) so they finish quickly. But recently I've been testing on a _very_ slow CI machine. There, I see this spec flaking when it expects stderr to be `'world'` but it gets `''`. This PR changes the fixture to wait for stdout & stderr to flush before …

fix: possible timing issue in utility-process spec

---

patches/v8/.patches
patches/v8/merged_reland_lower_the_maximum_js_parameter_count.patch

<details>
<summary>electron/security#659 - 84a0e230dabc from v8</summary>
Reland "Lower the maximum JS parameter count"
This is a reland of commit 1827ed8345369ca50a55a10ab3e45bcc581c6339
Before the change, one of the nodes had more than 2^16 inputs
so optimization bailed out.
After the change, the function has fewer parameters and gets
optimized, and the register allocator struggles with that many
parameters and times out.
Just mark the test as slow for now.
> Lower the maximum JS parameter count
>
> To allow extra implicit arguments on the call node without overflowing
> the uint16_t input count, in particular in the wasm-to-js wrapper where
> we don't have a bailout mechanism.
>
> R=verwaest@chromium.org
>
> Fixed: 394350433
> Change-Id: …

chore: cherry-pick 1 changes from 2-M133

---

patches/chromium/fix_crash_loading_non-standard_schemes_in_iframes.patch
spec/api-subframe-spec.ts

Refs https://chromium-review.googlesource.com/c/chromium/src/+/5873739
Refs https://github.com/electron/electron/pull/44986
Closes https://github.com/electron/electron/issues/45653.
Closes https://github.com/electron/electron/issues/45610
Fixes an issue where the renderer process crashes when loading `about:blank` in subframes. This happened resultant of the above CLs - we shouldn't be attempting to return a null origin for non-standard `about:blank` schemes.
Also removes a conditional for this occurring on subframes only - it's possible for this to affect e.g. the pdf viewer as well which is a main frame cc @deepak1556 
Notes: Fixes an issue where the renderer process crashed when loading `about:blank` in subframes.

fix: crash loading `about:blank` in subframes

---

.github/actions/set-chromium-cookie/action.yml

relates to https://github.com/electron/electron/pull/45669
Need to skip setting this to fix build failures on Windows due to empty strings in the powershell command.
https://github.com/electron/electron/actions/runs/13386146994/job/37515175922?pr=45669
```
powershell -noprofile -nologo -command Write-Output "" >>"%USERPROFILE%\.gitcookies"
Write-Output : Cannot process command because of one or more missing mandatory parameters: InputObject.
At line:1 char:1
+ Write-Output
+ ~~~~~~~~~~~~
+ CategoryInfo          : InvalidArgument: (:) [Write-Output], ParameterBindingException
+ FullyQualifiedErrorId : MissingMandatoryParameter,Microsoft.PowerShell.Commands.WriteOutputCommand
```
Notes: none

build: skip chromium git cookie on forks

---

docs/api/structures/base-window-options.md
shell/browser/native_window_views.cc

Refs https://github.com/electron/electron/pull/45456.
Allows removing rounded corners for frameless windows on Windows. Improved `BrowserWindow` ctor option platform parity just a bit.
<details><summary> roundedCorners enabled </summary>
<p>
</p>
</details> 
<details><summary>roundedCorners disabled</summary>
<p>
</p>
</details> 
Notes: Added support for `roundedCorners` BrowserWindow constructor option on Windows.

feat: allow setting `roundedCorners` on Windows

---

shell/browser/serial/serial_chooser_controller.cc
shell/browser/serial/serial_chooser_controller.h

Refs CL:5737296
> Enhance Web Serial chooser with Bluetooth status hints when exclusively
wireless serial ports are expected. This enhancement mirrors Web Bluetooth chooser behavior.
This change ensures our serial implementation matches upstream.
Notes: none

refactor: bluetooth in serial chooser when exclusively wireless serial ports are expected

---

shell/browser/api/electron_api_debugger.cc
shell/browser/ui/inspectable_web_contents.cc

Small cleanup to use `base::as_string_view()` as a safer alternative to `reinterpret_cast` in a couple of places.
Xref: https://chromium-review.googlesource.com/c/chromium/src/+/5472408
Notes: none.

refactor: use base::as_string_view()

---

shell/browser/serial/serial_chooser_context.cc

Small cleanup to use `base::as_byte_span()` in `EncodeToken()` to match [the changes in upstream's serial_chooser_context.cc](https://chromium-review.googlesource.com/c/chromium/src/+/5247305).
Notes: none.

refactor: use base::as_byte_span() in EncodeToken().

---

shell/browser/web_contents_permission_helper.cc
spec/api-media-handler-spec.ts

Fixes https://github.com/electron/electron/issues/45713.
When a an id from `chromeMediaSourceId` can't be parsed via `content::DesktopMediaID::Parse`, a `null` `DesktopMediaID` is returned with `Type::NONE`. Calling `ToString` on a null `DesktopMediaID` results in a `NOTREACHED` crash. This also fails in upstream - so we should error on this as well.
<details><summary>Upstream</summary>
<p>
</p>
</details> 
<details><summary>After Fix</summary>
<p>
</p>
</details> 
Notes: Fixed a potential crash when calling legacy `getUserMedia` with an invalid  `chromeMediaSourceId`.

fix: crash on `getUserMedia` with invalid `chromeMediaSourceId`

---

shell/browser/api/electron_api_web_frame_main.cc

Use `base::FindPtrOrNull()` in `WebFrameMain::FromFrameTreeNodeId()` and in `WebFrameMain::FromFrameToken()`.
Notes: none.

refactor: use base's map utills in WebFrameMain

---

shell/browser/api/electron_api_base_window.cc
shell/browser/api/electron_api_global_shortcut.cc
shell/browser/api/electron_api_power_save_blocker.cc
shell/browser/api/electron_api_protocol.cc
shell/browser/api/electron_api_session.cc
shell/browser/api/electron_api_web_contents.cc
shell/browser/api/electron_api_web_frame_main.cc
shell/browser/api/electron_api_web_request.cc
shell/browser/api/message_port.cc
shell/browser/electron_autofill_driver_factory.cc
shell/browser/electron_browser_client.cc
shell/browser/extensions/api/scripting/scripting_api.cc
shell/browser/extensions/api/tabs/tabs_api.cc
shell/browser/extensions/electron_component_extension_resource_manager.cc
shell/browser/hid/electron_hid_delegate.cc
shell/browser/hid/hid_chooser_context.cc
shell/browser/plugins/plugin_utils.cc
shell/browser/serial/serial_chooser_context.cc
shell/browser/ui/cocoa/electron_touch_bar.mm
shell/browser/ui/message_box_gtk.cc
shell/browser/ui/message_box_mac.mm
shell/browser/ui/message_box_win.cc
shell/browser/usb/electron_usb_delegate.cc
shell/browser/usb/usb_chooser_context.cc
shell/common/api/electron_api_clipboard.cc
shell/renderer/api/electron_api_context_bridge.cc
shell/renderer/api/electron_api_spell_check_client.cc
shell/renderer/electron_renderer_client.cc
shell/renderer/electron_sandboxed_renderer_client.cc

Now that we're using C++20, replace `base::Contains()` with C++20's `std::map<>::contains()` and `std::set<>::contains()`.
Notes: none.

refactor: use C++20's contains() method

---

docs/api/navigation-history.md

In an API WG meeting this month, we were reviewing https://github.com/electron/electron/pull/45433 and had a bit of confusion regarding `offset` vs `index`.
This PR aims to explain the two concepts a bit more explicitly.
cc @alicelovescake @felixrieseberg 
Notes: none

docs: clarify navigationhistory offsets

---

docs/api/extensions-api.md
docs/api/extensions.md
docs/api/session.md
docs/breaking-changes.md
docs/tutorial/devtools-extension.md
filenames.auto.gni
filenames.gni
lib/browser/api/session.ts
shell/browser/api/electron_api_extensions.cc
shell/browser/api/electron_api_extensions.h
shell/browser/api/electron_api_session.cc
shell/browser/api/electron_api_session.h
spec/api-service-worker-main-spec.ts
spec/extensions-spec.ts

Moves all extension APIs from `Session` to `Session.extensions` similar to protocol/serviceWorkers/etc. I intend to add new APIs in the future and this seems like the best way to avoid further growing the `Session` API. It has the added benefit of requiring less `ENABLE_ELECTRON_EXTENSIONS` conditionals.
Notes: Moved `Session` extension APIs to `Session.extensions`.

refactor: move extension APIs to session.extensions

---

default_app/preload.ts

Added upstream documentation links for Node.js, Chromium, and V8 in the default_app of Electron.
Fixes #14728
This is my first open-source contribution, and I’m excited to get involved with Electron! I would appreciate any feedback on improvements or best practices.
Notes: Added upstream documentation links for Node.js, Chromium, and V8 in the default_app.

docs: added upstream doc links for node, chromium, and v8 in default_app

---

patches/chromium/fix_crash_loading_non-standard_schemes_in_iframes.patch
patches/chromium/ignore_parse_errors_for_pkey_appusermodel_toastactivatorclsid.patch
patches/node/build_remove_explicit_linker_call_to_libm_on_macos.patch
spec/api-subframe-spec.ts

Manually backport #45694 to 35-x-y. See that PR for details.
Notes: Fixes an issue where the renderer process crashed when loading about:blank in subframes.

fix: crash loading `about:blank` in subframes (35-x-y)

---

docs/tutorial/offscreen-rendering.md
shell/browser/osr/osr_render_widget_host_view.cc

Remove 240 FPS limit of OSR when using shared texture, because there's no performance limit.
Notes: Remove 240 FPS limit when use shared texture OSR.

feat: remove osr framerate limit when use shared texture

---

shell/common/api/electron_api_url_loader.cc
shell/common/gin_helper/event_emitter_caller.h

Partial fix for #29739
Upstream removed `base::AdaptCallbackForRepeating()` a long time ago. We still use it, so we have a Chromium patch to patch it back in. This PR fixes a couple of instances of this call, moving towards removing that patch.
Notes: none.

refactor: do not use `AdaptCallbackForRepeating()` in `electron_api_url_loader.cc`

---

shell/browser/api/electron_api_global_shortcut.cc
shell/browser/api/electron_api_global_shortcut.h

Just a small cleanup to remove an unused argument. It hasn't been used since f1a0d5e811 (#22755)
Notes: none.

refactor: remove unused `v8::Isolate*` arg from `GlobalShortcut` constructor

---

patches/chromium/revert_code_health_clean_up_stale_macwebcontentsocclusion.patch
shell/browser/feature_list.cc

Follow up to #45055 . In that PR, the ability to toggle MacWebContentsOcclusion was removed as part of [CL:6078344 ](https://chromium-review.googlesource.com/c/chromium/src/+/6078344); it is now enabled by default upstream, but disabled by default downstream, as it's causing three of our visibility tests to fail (one seemingly where the webContents hangs).
This PR re-enables the feature flag for apps which might like to use the feature, while we debug the needed tests to enable it by default and match upstream. It will still be disabled by the default until the issues are fixed.
Notes: Re-enables the MacWebContentsOcclusion feature flag for Mac, with plans to make it enabled by default in a future release

fix: re-enable MacWebContentsOcclusion feature flag

---

patches/v8/.patches
patches/v8/cherry-pick-8131c09bc129.patch

<details>
<summary>electron/security#652 - 8131c09bc129 from v8</summary>
Merged: [maglev] Fix Phi untagging bug with CheckNumber(HoleyFloat64)
So far, CheckNumber(untagged phi) was always removed, but for a
holey float64, CheckNumber should fail on the hole nan.
Bug: chromium:389330329
(cherry picked from commit cc4c963c72b8da0c7c927680ef856cebdd87d60c)
Change-Id: I4bc634789e2d8d7f364e36b69dceeeb2886c54b1
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/6198231
Reviewed-by: Olivier Flückiger <olivf@chromium.org>
Commit-Queue: Olivier Flückiger <olivf@chromium.org>
Auto-Submit: Darius Mercadier <dmercadier@chromium.org>
Cr-Commit-Position: refs/branch-heads/13.2@{#68}
Cr-Branched-From: 24068c59cedad9ee976ddc05431f5f497b1ebd71-refs/heads/13.2.152@{#1} …

chore: cherry-pick 1 changes from 2-M132

---

patches/v8/.patches
patches/v8/cherry-pick-9209292e7898.patch
patches/v8/cherry-pick-97e828af5cbc.patch
patches/v8/cherry-pick-ca504d096c39.patch

<details>
<summary>electron/security#647 - 9209292e7898 from v8</summary>
Merged: [turbofan] Fix CallWithSpread bug when array prototype has changed
Bug: chromium:385386138
(cherry picked from commit 1be46f0e2e71159a74d8614f9ac108d334797729)
Change-Id: I8b0c95c4072652e6b9ccab792b6685e0e0dcfbb9
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/6172284
Auto-Submit: Darius Mercadier <dmercadier@chromium.org>
Commit-Queue: Darius Mercadier <dmercadier@chromium.org>
Cr-Commit-Position: refs/branch-heads/13.2@{#58}
Cr-Branched-From: 24068c59cedad9ee976ddc05431f5f497b1ebd71-refs/heads/13.2.152@{#1}
Cr-Branched-From: 6054ba94db0969220be4f94dc1677fc4696bdc4f-refs/heads/main@{#97085}
</details>
<details> …

chore: cherry-pick 3 changes from 1-M132

---

shell/common/gin_helper/event_emitter.h

Some cleanup to `gin_helper::EventEmitter`:
- avoid redundant calls to `gin_helper::Wrappable<T>::GetWrapper()`
- remove unused method `EventEmitter<T>::isolate()`
- remove unused method `EventEmitter<T>::GetWrapper()`
- remove unused method `EventEmitter<T>::GetWrapper(v8::Isolate*)`
- remove unused typedef `EventEmitter::Base`
Notes: none

perf: avoid redundant method calls in EventEmitter

---

shell/common/gin_helper/wrappable.cc
shell/common/gin_helper/wrappable_base.h

Does what it says on the tin: removes an unused method, `gin_helper::WrappableBase::GetWrapper(v8::Isolate*)`
Notes: none.

refactor: remove unused gin_helper::WrappableBase::GetWrapper(v8::Isolate*)

---

shell/common/gin_helper/function_template.h

A small golfing cleanup in the variadic template code for `Invoker::IsOK()`. We can remove the `And()` helper functions and just use [a fold expression](https://en.cppreference.com/w/cpp/language/fold) instead.
Notes: none.

refactor: simplify Invoker::IsOK()

---

docs/api/dialog.md

Fix a typo in the `window` parameter for `showSaveDialogSync`:
Replace
`dialog.showSaveDialogSync([wndow, ]options)`
With
`dialog.showSaveDialogSync([window, ]options)`
Notes: none

docs: dialog.md - typo fix s/wndow/window/

---

shell/browser/ui/electron_desktop_window_tree_host_linux.cc
shell/browser/ui/electron_desktop_window_tree_host_linux.h
spec/api-web-contents-spec.ts

Closes https://github.com/electron/electron/issues/45301.
Takes a similar approach as https://github.com/electron/electron/pull/44978 - we intercept potential right clicks and disable draggable regions temporarily to allow the events to punch through. Draggable regions only respond to left-click dragging, but the system will still suppress right-clicks in a draggable region, so this effectively allows `contextmenu` events to be dispatched as expected. I'm also looking into addressing this on Windows, but we'll probably need to take a different approach.
Tested with https://gist.github.com/bpasero/b04271deaacf0e099b0a0fa2289e8d28
cc @bpasero @deepak1556
Notes: Fixed an issue where `contextmenu` events wouldn't be correctly dispatched in draggable regions on Linux.

fix: context-menu event emitted in draggable regions

---

docs/breaking-changes.md

> ### Removed:`isDefault` and `status` properties on `PrinterInfo`
> These properties have been removed from the PrinterInfo Object
> because they have been removed from upstream Chromium.
These properties [won't be removed until Electron 36](https://github.com/electron/electron/pull/45500/commits/5b65cc739859c8b377209b5949fb729a6f89892d), but `breaking-changes.md` in `main` lists them as being removed in 35. This PR corrects the error.
Thanks @mlaurencin for catching this!
Notes: none.

docs: fix PrinterInfo info in breaking-changes.md

---

docs/breaking-changes.md

docs: update breaking-changes.md for 35.0.0
CC @electron/wg-releases 
Notes: none.

docs: update breaking-changes.md for 35.0.0

---

spec/api-service-worker-main-spec.ts
spec/fixtures/api/preload-realm/preload-tests.js

closes https://github.com/electron/electron/issues/45188
Adds a test to ensure values passed between service worker contexts do not leak prototypes. This is a reimplementation of a [test from the contextBridge spec file.](https://github.com/electron/electron/blob/eac270bea7798b5f8b62504e1f1161f89f3a189d/spec/api-context-bridge-spec.ts#L879-L989)
I decided to add a new test rather than refactor the contextBridge tests for a few reasons:
1. `ServiceWorkerMain` has no `executeJavaScript` method yet. This prevents us from running arbitrary JS in the main world of service workers.
2. The service worker preload context is more limited than render frame isolated contexts. The `Blob` global doesn't exist which the contextBridge test depends on.
3. The complexity involved in porting …

test: service worker contextBridge leak

---

.gitattributes
patches/chromium/.patches
patches/chromium/reland_lzma_sdk_update_to_24_09.patch
patches/v8/.patches
patches/v8/cherry-pick-1c7ff4d5477f.patch
patches/v8/cherry-pick-8834c16acfcc.patch

<details>
<summary>electron/security#656 - 51cd241b7b13 from chromium</summary>
Reland "lzma_sdk: Update to 24.09."
This is a reland of commit 1d69891ae775c74724558585929c89438a6fda93
> lzma_sdk: Update to 24.09.
>
> Files originate from https://7-zip.org/a/lzma2409.7z
> SHA-256(./lzma2409.7z)=
> 79b39f10b7b69eea293caa90c3e7ea07faf8f01f8ae9db1bb1b90c092375e5f3
>
> Fixed: 383772517, 40849176
> Change-Id: I7ccefbcc0dc92f94ae43566fe9d8b962369ea8b8
> Low-Coverage-Reason: OTHER - It's not clear how to exercise some of these conditionally-compiled alternatives.
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6091038
> Reviewed-by: Greg Thompson <grt@chromium.org>
> Commit-Queue: Will Harris <wfh@chromium.org>
> Auto-Submit: Joshua Pawlicki …

chore: cherry-pick 3 changes from 0-M133

---

patches/node/.patches
patches/node/build_define_nominmax_in_common_gypi.patch

Closes https://github.com/electron/electron/issues/45826.
Refs https://github.com/nodejs/node/pull/52794.
Fixes an issue where native Node.js addons including `uv.h` before `node.h` don't compile as expected.
Notes: Fixed an issue where native Node.js addons including `uv.h` before `node.h` don't compile as expected.

build: define `NOMINMAX` in `common.gypi`

---

patches/chromium/fix_harden_blink_scriptstate_maybefrom.patch

Move Electron's extra embedders to the end of the enum so they do not interfere with Chromium embedder indices.
Also use `kEmbedderBlinkTag` directly in its index calculation without adding extra indices from other tags.
Notes: Fixed invalid memory access in pdf viewer which lead to random crashes.

fix: correct electron gin embedder indices

---

.github/workflows/issue-commented.yml

We have a CI task that removes the `blocked/need-repro` and `blocked/need-info` labels when a user comments on an issue.
That task is already disabled for members and owners.
This PR updates the task to not run for collaborators either.
(In particular, this will make my own life easier as a collaborator with triage permissions.)
Notes: none

ci: preserve `blocked/*` labels on collaborator comments

---

docs/api/web-contents.md
shell/browser/api/electron_api_web_contents.cc
shell/browser/api/electron_api_web_contents.h
spec/api-web-contents-spec.ts

Adds a binding for [WebContents::GetFocusedFrame](https://source.chromium.org/chromium/chromium/src/+/main:content/public/browser/web_contents.h;l=486-488;drc=1187e4e80bbad755ac5a2234409153dab988bb54).
There doesn't appear to be any event which indicates when the focused frame changes unfortunately. It's set in [WebContentsImpl::SetFocusedFrame](https://source.chromium.org/chromium/chromium/src/+/main:content/browser/web_contents/web_contents_impl.cc;l=9555-9637;drc=798b98d70313e6a55bcf9cc85bc7ca7d42ca6d23).
These changes also change the type of `WebContents.opener` to have `null` to reflect its accurate state.
Notes:
* Added `WebContents.focusedFrame` to get the focused frame.
* Fixed `WebContents.opener` to specify potential `null` type.

feat: WebContents.focusedFrame

---

shell/browser/api/electron_api_base_window.cc
shell/browser/api/electron_api_base_window.h
shell/browser/native_window.h
shell/browser/native_window_mac.h
shell/browser/native_window_mac.mm
shell/browser/native_window_views.cc
shell/browser/native_window_views.h
spec/api-browser-window-spec.ts

Fixes https://github.com/electron/electron/issues/45844.
Refs CL:5789117
This PR fixes an issue where `setContentProtection(true)` was reverted when a given window was hidden. This happened as a result of the above CL, which added logic to avoid setting content protection when a window was hidden. That wouldn't be an issue, except that we weren't using the upstream `Widget` functionality, and so when it went to ensure protection state after re-showing it, the status was incorrect. Fix this by leveraging upstream functionality. This PR additionally adds testing and a currently private getter function for content protection status so we can test and prevent regressions in the future. I'll look to expose that in a follow-up PR.
Notes: Fixed an issue where `setContentProtection(true)` was …

fix: `setContentProtection(true)` after hide on Windows

---

patches/v8/.patches
patches/v8/cherry-pick-1c7ff4d5477f.patch
patches/v8/cherry-pick-9209292e7898.patch
patches/v8/cherry-pick-97e828af5cbc.patch
patches/v8/merged_fix_out_of_bound_string_access.patch
patches/v8/merged_wasm_replace_dead_code_set_with_is_dying_bit.patch
patches/v8/wasm_fix_freeing_of_identical_shared_wrappers.patch

* 76d19c57e890f99612cb39001b2eac5ba64e8fa2 from v8
* 924c1a79f1398960f20b97ace5ab7ffbd9db2d06 from v8
* 815da99004a525241c437e0a19b6968e61e52fe5 from v8
Notes:
* Security: backported fix for CVE-2025-0995.
* Security: backported fix for CVE-2025-0998.

chore: cherry-pick 3 changes from 1-M133

---

.github/PULL_REQUEST_TEMPLATE.md
docs/development/api-history-migration-guide.md
docs/development/style-guide.md

This PR aims to give additional visibility to our documentation style guide by adding it to the PR template and moving it into `/development` to mark that it belongs with other contributor-focused docs.
Notes: none

chore: emphasize documentation style guide

---

shell/browser/font_defaults.cc
shell/browser/font_defaults.h

Starting with Electron 34 there was a bump in `WebContentsImpl::Loading` due to font family resolutions when updating the default preference values for the renderer. Context and screenshots in https://issues.chromium.org/issues/400473071#comment1
In the browser process, we set the default font preferences via `SetFontDefaults` that populates the values for a given script of a font family. Some of these values can be comma-separated font family names.
We also only allow overriding the default font family for the unknown script `Zyyy` via the webPreferences https://github.com/electron/electron/blob/main/docs/api/structures/web-preferences.md
When the renderer applies these defaults via https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/exported/web_view_ …

fix: resolve font list in default prefernce values

---

spec/api-process-spec.ts

Using the `invoke` function to execute the process module methods in the `api-process-spec.ts` file eliminates duplicate code and simplifies the codebase.
Notes: none

refactor: eliminate duplicate code in spec/api-process-spec.ts

---

spec/api-utility-process-spec.ts

In three tests that call `utilityProcess.fork()`, remove unnecessary calls to `await once(child, 'spawn');` that caused a race condition. Consider a test like this:
```js {.line-numbers}
100    it('is valid when child process launches with pipe stdio configuration', async () => {
101      const child = utilityProcess.fork(path.join(fixturesPath, 'log.js'), [], {
102        stdio: 'pipe'
103      });
104      await once(child, 'spawn');
105      expect(child.stdout).to.not.be.null();
106      let log = '';
107      child.stdout!.on('data', (chunk) => {
108        log += chunk.toString('utf8');
109      });
110      await once(child, 'exit');
111      expect(log).to.equal('hello\n');
112    });
```
Forking a child process (line 101) and then adding a `'data'` listener (line 107) is usually …

fix: race condition in utilityProcess tests

---

patches/chromium/.patches
patches/chromium/cherry-pick-521faebc8a7c.patch

Disable setting primtive restart for WebGL in the cmd decoder.
Until it's blocked in ANGLE for WebGL contexts, disable it in the
command decoder on the service side.
Bug: 401059730
Change-Id: Ia9c7d951cbd122454afec2f884968e0a709cee77
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6334632
Commit-Queue: Kenneth Russell <kbr@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1429307}
Notes: Backported fix for 401059730.

chore: cherry-pick 521faebc8a7c from chromium

---

patches/chromium/.patches
patches/chromium/cherry-pick-9dacf5694dfd.patch

Move WebGL primitive restart state setting to the GPU process.
ANGLE will validate and initialize this state and errors are generated
when the WebGL client also initializes it on startup.
Initialize it even in the passthrough command decoder temporarily so
that ANGLE can roll without breaking WebGL tests.
Bug: 401059730
Change-Id: I0bfee710673bbcea6f915ffc4fc9be20438a2654
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6330188
Auto-Submit: Geoff Lang <geofflang@chromium.org>
Commit-Queue: Kenneth Russell <kbr@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1429228}
Notes: Backported fix for 401059730.

chore: cherry-pick 9dacf5694dfd from chromium

---

shell/browser/electron_browser_main_parts.cc

Remove redundant `MediaCaptureDevicesDispatcher::GetInstance()` call.
This appears to be a copy-paste error introduced in 465dee2c335db1cf081d07e84b757a65b984d881
Notes: none.

fix: remove redundant `MediaCaptureDevicesDispatcher::GetInstance()` call

---

docs/tutorial/native-code-and-electron.md

This is my first PR in a series of tutorials on how to integrate native code with Electron. All the maintainers are intimately familiar with Electron's "just write native code" superpower, but very little of that is prominently documented on the homepage. To make this easy to review, I'll be making a series of PRs.
This first tutorial covers the "Hello World" of making a native Node.js addon. All other tutorials will build on top of it.
- Native Code and Electron `← You are here`
- Native Code and Electron: C++ (Windows)
- Native Code and Electron: C++ (Linux)
- Native Code and Electron: Objective-C (macOS)
- Native Code and Electron: Swift (macOS)
- Native Code and Electron: Rust

docs: Add 'Native Code and Electron'

---

patches/chromium/.patches
patches/chromium/revert_blink_fix_over_invalidation_with_view_transitions.patch

Closes https://github.com/electron/electron/issues/45206
This patch reverts the commit upstream that caused this backdrop filter issue reported above. It have been resolved as of Chromium 135.0.7019.0 and Electron v35.0.0 is not affected. Thus only 34-x-y is being patched.
https://chromium-review.googlesource.com/c/chromium/src/+/6262017
Notes: Backported fix for 391907157, 361370195

fix: cherry-pick 3a72ebf7ec6f0 from chromium

---

spec/fixtures/api/utility-process/dns-result-order.js
spec/fixtures/api/utility-process/esm.mjs

Followup to #45690. The same race condition described there also exists in the `esm.js` and `dns-result-order.js` fixtures. This PR ensures that stdout's buffers are flushed before calling `process.exit()`.
This race condition's worth fixing in `electron/electron`; but FWIW, I'm only seeing this test fail on a downstream build's CI boxes, not in `electron/electron`'s GitHub Actions.
Notes: none.

test: fix timing issue in `utilityProcess` test fixtures

---

script/sysroots.json

Refs https://github.com/electron/electron/issues/45884
Roll sysroots to pick up https://github.com/electron/debian-sysroot-image-creator/pull/41
Notes: Fixed an issue where Electron could fail to load on some older Linux distributions.

build: roll sysroots to pick up glibc fix

---

.github/workflows/branch-created.yml

This ensures we can re-run the workflow to create the release project board if we need to and not have it fail since the previous project board was closed in the initial run. Ran into this the other day when we had to re-run the workflow to fix the variable interpolation failure.
Notes: none

ci: don't fail branch created workflow if previous board not found

---

shell/browser/api/electron_api_utility_process.h
shell/browser/api/message_port.h
shell/services/node/parent_port.h

We have a handful of classes that use public inheritance from `mojo::MessageReceiver` but, but didn't intend for that class's API to be public (e.g. the `Accept() override` method is made private). This PR changes that inheritance to private.
Notes: none.

refactor: use private inheritance from `mojo::MessageReceiver`

---

patches/chromium/fix_harden_blink_scriptstate_maybefrom.patch

Manually backport #45389 to 33-x-y. See that PR for details.
Notes: Fixed invalid memory access in pdf viewer which lead to random crashes.

fix: correct electron gin embedder indices (33-x-y)

---

patches/chromium/.patches
patches/chromium/cherry-pick-0adceb6159fb.patch
patches/v8/.patches
patches/v8/cherry-pick-91343bb45c78.patch

<details>
<summary>electron/security#123 - 0adceb6159fb from chromium</summary>
Speculative fix for cancelling current xr animation frame
When cancelling an XrAnimationFrame we don't actually need to clear the
list of async tasks, and in fact attempting to clear the current async
task can cause errors. This list is only populated while callbacks are
being executed, and is cleared once those callbacks are finished
executing. Removing the callback id from
`current_callback_frame_requests`, which is populated for the same
life span as the async_tasks, is sufficient to ensure the cancelled
callback does not run.
Note: This is a speculative fix because even when
external/wpt/webxr/xrSession_cancelAnimationFrame.https.html
was modified to cancel the current frame, Issue 396481096 did not
repro; …

chore: cherry-pick 2 changes from 3-M133

---

patches/v8/.patches
patches/v8/cherry-pick-2b4812d502b2.patch

<details>
<summary>electron/security#665 - 2b4812d502b2 from v8</summary>
merged: [maglev] Add missing ClearAllocationBlock
Fixed: 398065918
(cherry picked from commit eb9b25970b0ad4a3f8ce23d8de3583c62e5d6b87)
Change-Id: I20f3979984c1df11509f1630cf4c4c4460d6a83a
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/6304712
Reviewed-by: Victor Gomes <victorgomes@chromium.org>
Auto-Submit: Olivier Flückiger <olivf@chromium.org>
Commit-Queue: Olivier Flückiger <olivf@chromium.org>
Commit-Queue: Victor Gomes <victorgomes@chromium.org>
Cr-Commit-Position: refs/branch-heads/13.4@{#29}
Cr-Branched-From: 0f87a54dade4353b6ece1d7591ca8c66f90c1c93-refs/heads/13.4.114@{#1}
Cr-Branched-From: 27af2e9363b2701abc5f3feb701b1dad7d1a9fe8-refs/heads/main@{#98459}
</details>
Notes:
* Security: …

chore: cherry-pick 1 changes from 1-M134

---

shell/renderer/web_worker_observer.cc

Fix an issue where Web Workers crashed on unhandled rejections. This happened by default because it's how Node.js behaves, but it something we already disabled in the main process and renderer processes because it's not how the web behaves. Align with Web Worker behavior in browsers and prevent utility processes from crashing on any unhandled rejections.
Notes: Fixed an issue where Web Workers crashed on unhandled rejections.

fix: don't crash Web Workers on unhandled rejections

---

patches/node/fix_allow_passing_fileexists_fn_to_legacymainresolve.patch
patches/node/src_stop_using_deprecated_fields_of_fastapicallbackoptions.patch

Closes https://github.com/electron/electron/issues/45896.
Small but critical error not caught as we don't test for this. Adding a test will be a bit complex and I'll follow this up with that but it's blocking enough that we should perhaps not pend on it.
Notes: Fixed an issue where packages could be mistakenly not found in asar.

fix: package import existence verification

---

script/sysroots.json

Pick up the following:
* https://github.com/electron/debian-sysroot-image-creator/pull/43
* https://github.com/electron/debian-sysroot-image-creator/pull/44
* https://github.com/electron/debian-sysroot-image-creator/pull/42
Notes: none

build: roll sysroots again

---

shell/common/gin_helper/constructor.h

- Instead of having separate functions for handling each number of arguments, just use a single function that uses a `std::tuple`.
- Avoid unnecessary copies by `move()`ing the extracted arguments when passing them to the callback being invoked.
Notes: none.

refactor: make a variadic `gin_helper::internal::InvokeFactory()`

---

shell/browser/native_window_views_win.cc
shell/browser/ui/win/electron_desktop_window_tree_host_win.cc
spec/api-web-contents-spec.ts

Refs https://github.com/electron/electron/issues/45301
Follow-up to https://github.com/electron/electron/pull/45813
Fixes an issue where `context-menu` event weren't emitted as expected on Windows in draggable regions.
cc @bpasero 
Notes: Fixed an issue where `context-menu` event weren't emitted as expected on Windows in draggable regions.

fix: emit `context-menu` event in Windows draggable regions

---

shell/browser/api/electron_api_web_contents.cc
spec/api-web-contents-spec.ts
spec/fixtures/pages/navigation-history-anchor-in-page.html

Closes #44144
Previously the call to update the title occurred after any forward/backward navigation. Now it only occurs if that navigation is not done in page.
Notes: Fixed title changes to not occur while navigating within a page

fix: prevent title change for within page navigation

---

docs/breaking-changes.md
shell/renderer/web_worker_observer.cc
shell/services/node/node_service.cc

Change default behavior of utility processes crashed on unhandled rejections. This happened by default because it's how Node.js behaves, but it something we already disabled in the main process and renderer processes because it's not how the web behaves. 
Notes: Fixed an issue where utility processes crashed on unhandled rejections.

fix: don't crash Utility Processes on unhandled rejections

---

shell/app/electron_content_client.cc
shell/app/electron_main_linux.cc
shell/app/electron_main_win.cc
shell/browser/api/electron_api_service_worker_main.cc
shell/browser/api/electron_api_service_worker_main.h
shell/browser/api/electron_api_web_contents.h
shell/browser/api/gpu_info_enumerator.h
shell/browser/electron_download_manager_delegate.cc
shell/browser/electron_web_contents_utility_handler_impl.h
shell/browser/extensions/api/extension_action/extension_action_api.cc
shell/browser/extensions/api/extension_action/extension_action_api.h
shell/browser/extensions/api/scripting/scripting_api.h
shell/browser/file_system_access/file_system_access_permission_context.h
shell/browser/javascript_environment.cc
shell/browser/native_window.h
shell/browser/net/asar/asar_file_validator.cc
shell/browser/net/system_network_context_manager.cc
shell/browser/osr/osr_render_widget_host_view.cc
shell/browser/relauncher.cc
shell/browser/ui/devtools_ui_bundle_data_source.cc
shell/browser/ui/devtools_ui_theme_data_source.cc
shell/browser/zoom_level_delegate.cc
shell/common/process_util.h
shell/renderer/api/electron_api_context_bridge.cc
shell/renderer/electron_api_service_impl.cc
shell/renderer/electron_render_frame_observer.cc
shell/renderer/electron_sandboxed_renderer_client.cc
shell/renderer/extensions/electron_extensions_renderer_client.cc
shell/renderer/extensions/electron_extensions_renderer_client.h

Simple cleanup PR to remove unused #includes: e.g. if a header doesn't use `std::set`, it shouldn't  `#include <set>`.
Notes: none

refactor: remove unused system header includes

---

docs/api/service-worker-main.md
shell/browser/api/electron_api_service_worker_main.cc
shell/browser/api/electron_api_service_worker_main.h
spec/api-service-worker-main-spec.ts

Adds `scriptURL` property to `ServiceWorkerMain`. This is equivalent to the [`scriptURL`](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorker/scriptURL) property available in renderers.
This was omitted initially as it wasn't available on a public interface. I've since landed a CL to move it to the public `ServiceWorkerVersionBaseInfo` struct.
https://chromium-review.googlesource.com/c/chromium/src/+/6243058
Notes: Added `scriptURL` property to `ServiceWorkerMain`.

feat: ServiceWorkerMain.scriptURL

---

shell/browser/electron_browser_context.cc
shell/browser/electron_browser_context.h

- Remove `ElectronBrowserContext::extension_system()`, whose last caller was removed on Jul 21, 2020 by 94e64af9edeb82b5192ff01f166a35771b1bfbab in PR #24575...
- ...which, in turn, lets us remove the `raw_ptr` field `ElectronBrowserContext::extension_system_` ...
- ...which, in turn,  fixes the thing that got me looking at this part of the code: a `raw_ptr` error in the `ElectronBrowserContext` destructor  :raised_hands: 
Notes: none.

fix: `ElectronBrowserContext` `raw_ptr` bug + remove dead code

---

shell/browser/electron_browser_context.cc

Small perf cleanup that I found while looking for something else: remove duplicate map lookups from `ElectronBrowserContet::From()` and `ElectronBrowserContext::FromPath()`
Notes: none.

perf: avoid redundant map lookup in ElectronBrowserContext::From()

---

patches/chromium/fix_take_snapped_status_into_account_when_showing_a_window.patch

Run `e patches all` to make CI happy: all the other PRs to `main` (and the CI for the latest commits in `main` as well) are failing with:
```
2025-03-15T15:04:32.9696539Z [SUCCESS] Cleaning up...
2025-03-15T15:04:32.9811960Z [main 1544d60477] chore: update patches
2025-03-15T15:04:32.9812419Z  1 file changed, 4 insertions(+), 4 deletions(-)
2025-03-15T15:04:33.9082305Z Failed to push to target branch
2025-03-15T15:04:33.9124000Z 
2025-03-15T15:04:33.9124383Z ======================================================================
2025-03-15T15:04:33.9124885Z There were changes to the patches when applying.
2025-03-15T15:04:33.9125317Z Check the CI artifacts for a patch you can apply to fix it.
2025-03-15T15:04:33.9125703Z ====================================================================== …
```

chore: e patches all

---

shell/browser/file_system_access/file_system_access_permission_context.cc

Remove the code in `shell/browser/file_system_access/file_system_access_permission_context.cc` that loads `IDS_FILE_SYSTEM_ACCESS_CHOOSER_OPEN_SAVE_FILE_TITLE` for the title string in `kSaveFilePickerOptions` dialogs. The upstream default of that string is "Warning: this site can see edits you make", which doesn't make sense for Electron?
Removing the string there returns to the pre-30.0.0 behavior, which on my Linux test machine, is the string "All Files".
Fixes #46052.
Notes: Fixed incorrect titlebar in file save dialogs.

fix: warning in file picker UI

---

shell/browser/api/electron_api_session.cc

Always use `GetDefaultStoragePartition()` instead of `GetStoragePartition(nullptr)`. Previously we used both.
- It improves code uniformity, since we use `GetDefaultStoragePartition()` everywhere else already
- It's more readable (don't need to go look up "what happens when I pass nullptr?")
- It's (very marginally) faster, since `GetStoragePartition()` has more steps
Added in https://github.com/electron/electron/pull/28907/commits/49b0a1bf4a6c032d1788aac56c1e5eaa0f61e3d3
Notes: none.

refactor: use `GetDefaultStoragePartition()` instead of `GetStoragePartition(nullptr)`

---

.github/actions/checkout/action.yml
.github/workflows/pipeline-segment-node-nan-test.yml

Followup to #45581.
This PR:
Notes: none

build: move set chromium cookie before build tools step

---

spec/api-app-spec.ts
spec/api-browser-window-spec.ts
spec/ts-smoke/electron/main.ts

Refs https://github.com/electron/electron/pull/46073.
Tests didn't run so we missed this - the smoke tests should've caught it and i'll check why they didn't.
Notes: none

test: fix `app.dock` for corrected type

---

.github/actions/checkout/action.yml
script/push-patch.js

Follow-up to https://github.com/electron/electron/pull/46047.
Ensure out-of-date patches fail on forks as well by tweaking the patch-up script to fail without credentials.
Notes: none

build: fail for out of date patches on forks

---

script/node-disabled-tests.json

Refs https://github.com/electron/electron/pull/45922.
Seems like there's a threading issue upstream, and this feature is still very fresh and a little underbaked upstream. Disable this test to address a recent frequent CI flake.
Notes: none

test: disable `parallel/test-worker-resource-limits`

---

shell/browser/api/electron_api_session.cc
shell/browser/electron_browser_context.cc
shell/browser/electron_browser_context.h
shell/browser/electron_browser_main_parts.cc
shell/browser/extensions/electron_extensions_browser_client.cc
shell/browser/net/electron_url_loader_factory.cc
shell/browser/ui/devtools_manager_delegate.cc

Manually backport #46065 to 34-x-y. See that PR for details.
Notes: none.

refactor: add `ElectronBrowserContext::GetDefaultBrowserContext()` (34-x-y)

---

docs/api/dock.md
docs/fiddles/features/macos-dock-menu/main.js
docs/tutorial/macos-dock.md

Refs https://github.com/electron/electron/pull/46073
Refs https://github.com/electron/electron/pull/46110
Adjusted code in the Electron docs to work nicely with the new types for `app.dock`.
Notes: none

docs: use optional chaining for `app.dock`

---

shell/browser/feature_list.cc

Closes https://github.com/electron/electron/issues/45931.
Fixes a crash seen on Linux starting in Electron 35 when calling `webContents.print()`. This was happening due to the `EnableOopPrintDrivers` feature being enabled on Linux, which was causing crashes when trying to show dialogs.
Notes: Fixed a crash seen on Linux when calling `webContents.print()`.

fix: `webContents.print()` crash on Linux

---

shell/app/electron_content_client.cc
shell/app/electron_main_linux.cc
shell/app/electron_main_win.cc
shell/browser/api/electron_api_web_contents.h
shell/browser/api/gpu_info_enumerator.h
shell/browser/electron_download_manager_delegate.cc
shell/browser/electron_web_contents_utility_handler_impl.h
shell/browser/extensions/api/extension_action/extension_action_api.cc
shell/browser/extensions/api/extension_action/extension_action_api.h
shell/browser/extensions/api/scripting/scripting_api.h
shell/browser/file_system_access/file_system_access_permission_context.h
shell/browser/javascript_environment.cc
shell/browser/native_window.h
shell/browser/net/asar/asar_file_validator.cc
shell/browser/net/system_network_context_manager.cc
shell/browser/osr/osr_render_widget_host_view.cc
shell/browser/relauncher.cc
shell/browser/ui/devtools_ui_bundle_data_source.cc
shell/browser/ui/devtools_ui_theme_data_source.cc
shell/browser/zoom_level_delegate.cc
shell/common/process_util.h
shell/renderer/api/electron_api_context_bridge.cc
shell/renderer/electron_api_service_impl.cc
shell/renderer/electron_render_frame_observer.cc
shell/renderer/electron_sandboxed_renderer_client.cc
shell/renderer/extensions/electron_extensions_renderer_client.cc
shell/renderer/extensions/electron_extensions_renderer_client.h

Manually backport #46015 to 34-x-y. See that PR for details.
Notes: none.

refactor: remove unused system header includes (34-x-y)

---

docs/api/push-notifications.md
shell/browser/api/electron_api_push_notifications_mac.mm
shell/browser/mac/electron_application_delegate.mm

Closes https://github.com/electron/electron/issues/46081.
Refactors `pushNotifications.registerForAPNSNotifications()` as well as fixes a token formatting issue where the token ASCII values were incorrectly uppercased (See references [1](https://nshipster.com/apns-device-tokens/), [2](https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CommunicatingwithAPNs.html), [3](https://www.kodeco.com/11395893-push-notifications-tutorial-getting-started?page=2#toc-anchor-007))
Notes: Fixed an issue with token formatting for tokens received after calling `pushNotifications.registerForAPNSNotifications()`.

fix: APNS token ids are lowercase ASCII

---

shell/browser/api/electron_api_web_frame_main.cc
shell/browser/api/electron_api_web_frame_main.h
shell/common/gin_converters/std_converter.h

Remove `ToV8(isolate, const char*)`.
This was previously removed in #44568 but it snuck back in :slightly_smiling_face: 
Using string literals or `std::string_view` are slightly more efficient since they can avoid `ToLocalChecked()` and `strlen()` calls.
Even though that won't be true _in this specific_ case since the one caller was passing it a `char*` returned by `content::RenderFrameHostImpl::LifecycleStateImplToString()`, it's still valuable to remove this converter to ensure that more code won't accidentally call it in the future.
Notes: none.

refactor: remove ToV8(isolate, const char*)

---

shell/browser/serial/serial_chooser_controller.cc
shell/common/gin_converters/serial_port_info_converter.h

Teeny little cleanup for how we convert unsigned ints to strings:
```diff
- foo = absl::StrFormat("%u", bar);
+ foo = base::NumberToString(bar);
```
The latter is slightly more efficient, slightly to read, slightly more futureproof if the type of `bar` ever changes.
Notes: none.

refactor: use base::NumberToString()

---

shell/browser/electron_browser_context.cc
shell/browser/electron_browser_context.h
shell/browser/electron_browser_main_parts.cc
shell/browser/extensions/electron_extensions_browser_client.cc

1. Add a read-only getter so client code can loop through browser contexts w/o knowing about ElectronBrowserContext's internals
2. Migrate client code to use the new getter
3. Make ElectronBrowserContext implementation details private
This is to tighten down controls on how `ElectronBrowserContext` is accessed and to reduce leaking implementation details. Callers should not have mutable access to the context map. Callers shouldn't even need to know the context map exists :slightly_smiling_face: 
Notes: none.

refactor: Add `ElectronBrowserContext::BrowserContexts()`

---

docs/breaking-changes.md
shell/browser/native_window_views.cc

We can remove some custom Linux logic here - upstream [sets this](https://source.chromium.org/chromium/chromium/src/+/main:ui/ozone/platform/x11/x11_window.cc;l=1179-1193;drc=e71cafaddfaa5850b906bf4c78b5289a2fa2d81a;bpv=1;bpt=1) on X11 and also has other logic for Wayland we should be leveraging.
Notes: none

refactor: use upstream `Widget::IsVisibleOnAllWorkspaces()`

---

BUILD.gn

Added ffmpeg.dll to the /DELAYLOAD linker configuration in BUILD.gn to reduce startup overhead and avoid unnecessary loading when ffmpeg-related functionality is not used.
E.g., the browser process was unnecessarily loading it:
Notes: Added `ffmpeg.dll` to delay load configuration.

feat: add ffmpeg.dll to delay load configuration

---

patches/node/refactor_attach_cppgc_heap_on_v8_isolate_creation.patch

Ref https://github.com/electron/electron/pull/45922
Ref https://github.com/v8/node/pull/209
Add missing `cpp_heap` to Node.js worker `CreateParams` in `src/node_worker.cc`.
Notes: none

fix: add missing `cpp_heap` to Node.js worker `CreateParams`

---

docs/api/web-utils.md
package.json
yarn.lock

Supersedes https://github.com/electron/electron/pull/46000.
Closes https://github.com/electron/electron/issues/45999
From original PR:
> Upgrade @electron/typescript-definitions to a version that includes https://github.com/electron/typescript-definitions/pull/281, removing the path extension to the File type.
Notes: none

fix: remove `File.path` from types

---

shell/browser/electron_browser_context.cc
shell/browser/electron_browser_context.h
shell/browser/electron_browser_main_parts.cc
shell/browser/extensions/electron_extensions_browser_client.cc

Manual backport of #46089. See that PR for details.
Notes: none.

refactor: Add `ElectronBrowserContext::BrowserContexts()` (35-x-y backport)

---

shell/browser/api/electron_api_view.cc
shell/browser/extensions/api/extension_action/extension_action_api.cc
shell/browser/extensions/api/extension_action/extension_action_api.h
shell/browser/net/web_request_api_interface.h

A followup to #44935 that did the same thing last year. This PR converts a few more destructors.
Relevant Chromium styleguide: [C++ Dos and Don'ts: Prefer to use `=default`](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++-dos-and-donts.md#prefer-to-use)
Notes: none.

refactor: use `= default` to define trivial destructors

---

shell/browser/electron_browser_context.cc
shell/browser/electron_browser_context.h

- remove unused method `ElectronBrowserContext::GetWeakPtr()`. Last use removed in Aug 2020 by bac2f46.
- remove unused field `ElectronBrowserContext::weak_factory_`.
- remove unused `#include`s from `electron_browser_context.h`.
Notes: none.

refactor: remove unused method `ElectronBrowserContext::GetWeakPtr()`

---

shell/browser/api/electron_api_service_worker_main.h

Remove unused field `ServiceWorkerMain::weak_factory_`. Added in a467d06, appears to have never been used. Maybe I'm misunderstanding? Or maybe it's a leftover from an earlier draft? 
Notes: none.

refactor: remove unused field `ServiceWorkerMain::weak_factory_`

---

docs/api/structures/input-event.md

These modifiers are documented as being camelCase, but they're actually lowercase as described in: https://github.com/electron/electron/blob/e4d660af86b95254b8b49de948923d4e1f4769f6/shell/common/gin_converters/blink_converter.cc#L153-L170
Did a quick check with the code below using Fiddle and they seem to be lowercase since Electron 22 (the oldest version I could use this event on), so I assume it's just a documentation issue:
```ts
mainWindow.webContents.on('input-event', (_, inputEvent) => {
console.log(inputEvent)
})
```
Notes: Fixed capitalization for `InputEvent.modifiers`

docs: fix capitalization for `InputEvent.modifiers`

---

shell/browser/api/electron_api_service_worker_main.cc
shell/browser/api/electron_api_web_frame_main.cc
shell/browser/electron_autofill_driver_factory.h
shell/browser/hid/electron_hid_delegate.h
shell/browser/serial/electron_serial_delegate.h
shell/browser/usb/electron_usb_delegate.h
shell/common/asar/archive.h
shell/common/key_weak_map.h
shell/renderer/api/context_bridge/object_cache.h

One step towards following the [upstream container recommendations](https://source.chromium.org/chromium/chromium/src/+/main:base/containers/README.md)
> If you just need a generic map or set container without any additional properties then prefer to use `absl::flat_hash_map` and `absl::flat_hash_set`. These are versatile containers that have good performance on both large and small sized data.
...
> Note that this advice never suggests the use of `std::unordered_map` and `std::unordered_set`. These containers provides similar features to the Abseil flat hash containers but with worse performance. They should only be used if absolutely required for compatibility with third-party code.
Further background reading in [this (old) chromium-dev …

perf: use `absl::flat_hash_map` instead of `std::unordered_map`

---

shell/browser/net/proxying_websocket.h

Remove unused method. Appears to have been added in c608d6d7 when copied from upstream, but we never used it.
Notes: none.

refactor: remove unused method ProxyingWebSocket::web_request_api()

---

shell/browser/extensions/api/management/electron_management_api_delegate.cc

Remove unused `weak_factory_` field. Appears to have been added in 3745b76da but never used
Notes: none.

refactor: remove unused `weak_factory_` in electron_management_api_delegate.cc

---

shell/browser/ui/electron_desktop_window_tree_host_linux.cc
shell/browser/ui/electron_desktop_window_tree_host_linux.h
shell/browser/ui/views/client_frame_view_linux.cc
shell/browser/ui/views/client_frame_view_linux.h

Closes https://github.com/electron/electron/issues/44543.
Closes https://github.com/electron/electron/issues/42894.
Closes https://github.com/electron/electron/issues/45834.
Refs CL:5180720
Fixes an issue where the resizing border didn't work as expected on Wayland windows. This happened as collateral damage in changes we made to account for CL:5180720.
<details><summary>After Change</summary>
<p>
</p>
</details> 
Notes:  Fixed an issue where the resizing border didn't work as expected on Wayland windows.

fix: Wayland resizing border

---

docs/api/base-window.md
docs/api/browser-window.md
shell/browser/api/electron_api_base_window.cc
shell/browser/api/electron_api_base_window.h
shell/browser/native_window.cc
shell/browser/native_window.h
shell/browser/native_window_views.cc
shell/browser/native_window_views.h

This PR adds the ability for a developer to tell whether a given window has been arranged via Snap on Windows. Snap is becoming more integral to Windows window management and understanding this as a window arrangement similar to maximized or minimized is important for developers showing information to users.
See [Windows Documentation](https://support.microsoft.com/en-us/windows/snap-your-windows-885a9b1e-a983-a3b1-16cd-c531795e6241) for more information.
Notes: Added `BrowserWindow.isSnapped()` to indicate whether a given window has been arranged via Snap.

feat: add `BrowserWindow.isSnapped()`

---

shell/browser/api/electron_api_desktop_capturer.cc

Fixes #45198.
https://chromium-review.googlesource.com/c/chromium/src/+/5783826 modified `DesktopMediaListBase::OnDelegatedSourceListDismissed` to read as follows:
```cc
void DesktopMediaListBase::OnDelegatedSourceListDismissed() {
DCHECK_CURRENTLY_ON(BrowserThread::UI);
DCHECK(IsSourceListDelegated());
if (observer_)
observer_->OnDelegatedSourceListDismissed();
Refresh(false);
}
```
The extra refresh means that it is no longer safe to call `DesktopCapturer::HandleFailure` (which deallocates the `DesktopMediaList`) synchronously from `OnDelegatedSourceListDismissed`. Notably, on Linux when using the PipeWire capturer, trying to share a source and then cancelling it from the xdg-desktop-portal's share prompt often causes an immediate crash. It's very easy to reproduce:
```javascript
const …
```

fix: handle OnDelegatedSourceListDismissed asynchronously

---

shell/browser/api/electron_api_app.cc
spec/fixtures/apps/node-options-utility-process/fail.js
spec/fixtures/apps/node-options-utility-process/main.js
spec/fixtures/apps/node-options-utility-process/noop.js
spec/fixtures/apps/node-options-utility-process/package.json
spec/node-spec.ts

Exe basenames for child process on macOS should be validated against the respective helper base names.
Notes: fix NODE_OPTIONS parsing for child processes on macOS

fix: NODE_OPTIONS parsing for child processes on macOS

---

shell/browser/api/electron_api_web_contents.cc
shell/browser/api/electron_api_web_contents.h
shell/browser/extensions/electron_extensions_api_client.cc
spec/api-web-contents-spec.ts
spec/fixtures/api/print-to-pdf-same-origin.html

Closes https://github.com/electron/electron/issues/36588.
Fixes an issue where `webContents.printToPDF()` didn't work as expected with cross-process subframes (e.g. iframes).
<p>
[electron-printtopdf-iframe.pdf](https://github.com/user-attachments/files/19427812/electron-printtopdf-iframe.pdf)
</p>
</details> 
<p>
[electron-printtopdf-iframe.pdf](https://github.com/user-attachments/files/19427799/electron-printtopdf-iframe.pdf)
</p>
</details> 
Tested with https://gist.github.com/4de3b99eb855215fc5b7812cbff09f5c.
Notes: Fixed an issue where `webContents.printToPDF()` didn't work as expected with cross-process subframes.

fix: `webContents.printToPDF()` with cross-process subframes

---

shell/browser/api/electron_api_web_contents.cc

`IsDevToolsFileSystemAdded()` wants to know if a `const base::Value::Dict&` provided by Chromium contains an item.  This PR does that by calling `dict.contains(item)`. Previously, it was done by creating single-use temporary `std::map` and then calling `map.contains(item)`.
`IsDevToolsFileSystemAdded()` is used by:
- `WebContents::DevToolsAddFileSystem()`
- `WebContents::DevToolsIndexPath()`
- `WebContents::DevToolsSearchInPath()`
Notes: none.

perf: avoid `std::map` temporaries in `IsDevToolsFileSystemAdded()`

---

shell/browser/api/electron_api_web_frame_main.cc

Another PR to remove another redundant map lookup. :slightly_smiling_face: 
This one was in the `WebFrameMain` constructor.
Notes: none

perf: avoid redundant map lookup in `WebFrameMain` constructor

---

shell/browser/api/electron_api_web_contents.cc
shell/browser/api/electron_api_web_contents.h
shell/browser/feature_list.cc

Fix 1d6cb34 FTBFS regression when building with printing disabled.
This breaks the Microsoft internal builds of Electron; so if possible, I'd like to get this landed before we kick off the weekly 33 and 34 releases.
CC @codebytere @electron/wg-releases 
Notes: Fixed build failure when building with printing disabled.

fix: build failure when printing is disabled

---

docs/api/command-line.md
docs/breaking-changes.md
shell/common/api/electron_api_command_line.cc
spec/api-app-spec.ts

Closes https://github.com/electron/electron/issues/45991.
Addresses an issue where poorly formed switched could cause a hard crash in Chromium since M134 by ensuring the switches are lowercased. Also improve the docs a little.
Notes: Fixed an issue where badly formatted switches could cause crashes in `app.commandLine` functions.

fix: hard crash on invalid command line switches

---

shell/browser/api/electron_api_web_contents.cc

Another remove-redundant-map-lookups PR. This one fixes a double-lookup in `WebContents::DevToolsIndexPath()`.
Notes: none.

perf: avoid redundant map lookup in `WebContents::DevToolsIndexPath()`

---

shell/browser/api/electron_api_web_contents.cc

Avoid a `std::map` temporary in `WebContents::DevToolsRequestFileSystems()`.
This builds on top of a similar refactor in #46230.
All reviews welcomed. CC @dsanders11 who reviewed 46230.
Notes: none.

perf: avoid `std::map` temporaries  in `WebContents::DevToolsRequestFileSystems()`

---

shell/renderer/api/electron_api_context_bridge.cc

Closes https://github.com/electron/electron/issues/44460.
Fixes a crash that occurs with the following stacktrace:
<p>
```
[3194:0325/102703.083107:FATAL:third_party/blink/renderer/platform/bindings/dom_data_store.h:247] Check failed: Current(isolate).can_use_inline_storage_.
0   Electron Framework                  0x0000000122e26704 base::debug::CollectStackTrace(base::span<void const*, 18446744073709551615ul, void const**>) + 28
1   Electron Framework                  0x0000000122e16ba4 base::debug::StackTrace::StackTrace(unsigned long) + 224
2   Electron Framework                  0x0000000122d3c128 logging::LogMessage::Flush() + 152
3   Electron Framework                  0x0000000122d3c010 logging::LogMessage::~LogMessage() + 36
4   Electron …
```

fix: crash when drag-dropping some files

---

patches/chromium/.patches
patches/chromium/cherry-pick-b8f80176b163.patch

<details>
<summary>electron/security#667 - b8f80176b163 from chromium</summary>
Avoid receiving or sending sentinel handle values
These values can be misinterpreted by OS functions, so
avoid sending or receiving them over IPCZ.
(cherry picked from commit 36dbbf38697dd1e23ef8944bb9e57f6e0b3d41ec)
Bug: 405143032
Change-Id: Ib578fb4727e78e2697c60c42005daa97e08695e9
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6380193
Reviewed-by: Will Harris <wfh@chromium.org>
Commit-Queue: Alex Gough <ajgo@chromium.org>
Cr-Original-Commit-Position: refs/heads/main@{#1436135}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6383569
Owners-Override: Srinivas Sista <srinivassista@chromium.org>
Commit-Queue: Srinivas …

chore: cherry-pick 1 changes from 3-M134

---

shell/browser/api/electron_api_web_frame_main.cc

Remove another redundant map lookup. This one was in `WebFrameMain::UpdateRenderFrameHost()`.
Fix is similar to #46238
Notes: none.

perf: avoid double map lookup in `WebFrameMain::UpdateRenderFrameHost()`

---

shell/browser/ui/views/electron_views_delegate_win.cc

Another "avoid redundant map loookups" PR. This one is kind of novel: it fixes code that did *four* identical lookups in `ViewsDelegate::GetAppbarAutohideEdges()` :slightly_smiling_face: 
Notes: none.

perf: avoid a triple-redundant map lookup in `ViewsDelegate::GetAppbarAutohideEdges()`

---

shell/browser/ui/cocoa/electron_menu_controller.mm

Electron allows their menu items to enabled or disabled based on a boolean flag for key `enabled` (details [here](https://www.electronjs.org/docs/latest/api/menu-item)). From the `context-menu` event, an engineer can check if a menu item _should_ be disabled or enabled by reading the [editFlags object](https://www.electronjs.org/docs/latest/api/web-contents#:~:text=can%20be%20looped.-,editFlags%20Object,-%2D%20These%20flags%20indicate), which determines if an action is available such as `canCopy` and `canPaste`. 
However, the `enabled` key is not being honored when set to `false`, as shown in Image 1. 
This PR addresses this issue, by setting NSMenu's `setAutoenablesItem` to `No`. By default, it was set to `Yes`; as a result, when a user event occurred, it would override the `No` value to …

fix: allow NSMenuItems to be disabled

---

shell/browser/api/electron_api_session.cc

I'm getting close to the end of these double-map-lookup PRs, but here are two fixes.
This one removes double lookups in `GetStorageMask()` and `GetDataTypeMask()`.
Notes: none.

perf: avoid redundant map lookups in `GetStorageMask()`

---

shell/browser/notifications/notification_presenter.cc

Yep another remove-a-redundant-map-lookup PR :smile_cat: This time it's in `NotificationPresenter::RemoveNotification()`
Notes: none.

perf: avoid a double-map lookup in `NotificationPresenter::RemoveNotification()`

---

shell/browser/electron_browser_client.cc

Don't call virtual method `RenderProcessHost::GetID()` three times in a row when one time will do.
Notes: none.

perf: avoid 3x call to `GetID()` in RegisterPendingSiteInstance()

---

shell/browser/hid/hid_chooser_context.cc

Remove a redundant map lookup in `HidChooserContext::DeviceRemoved()`.
Notes: none.

perf: avoid double map lookup in HidChooserContext::DeviceRemoved()

---

shell/browser/api/electron_api_app.cc
shell/browser/ui/cocoa/electron_bundle_mover.mm
shell/common/gin_converters/guid_converter.h

A small code-correctness refactor to use `v8::String::Empty()` when creating empty strings because it's faster and clearer than the alternatives e.g. `gin::ConvertToV8(isolate, "")`.
Notes: none.

refactor: use `v8::String::Empty()` when creating empty strings

---

shell/browser/api/message_port.cc
shell/renderer/api/electron_api_spell_check_client.cc

Replace our two uses of `std::unordered_set` with `absl::flat_hash_set` instead.
This is a followup to #46202 with the same goals as that PR: to better follow  the [upstream container recommendations](https://source.chromium.org/chromium/chromium/src/+/main:base/containers/README.md)
> Note that this advice never suggests the use of `std::unordered_map` and `std::unordered_set`. These containers provides similar features to the Abseil flat hash containers but with worse performance. They should only be used if absolutely required for compatibility with third-party code.
All reviews welcomed. CC @codebytere who reviewed 46202.
Notes: none.

perf: prefer `absl::flat_hash_set` over `std::unordered_set`

---

shell/renderer/web_worker_observer.cc

A couple of small cleanups to `WebWorkerObserver::WorkerScriptReadyForEvaluation()`:
- replace a runtime `std::vector<std::string>` local with compile-time `std::string_view`s
- remove `.c_str()` pessimizations when building v8 strings. When we give gin a `string_view` instead of a `char*`,  then it doesn't have to recalculate the string length.
I came across this change while looking for something else :slightly_smiling_face:. It's a small change but worthwhile to move these strings to compile-time.
Notes: none.

perf: improve temporaries in `WebWorkerObserver::WorkerScriptReadyForEvaluation()`

---

shell/browser/api/electron_api_extensions.h

Appears to have been added in e3f61b46 but never used.
Notes: none.

refactor: remove field `unused weak_factory_`

---

shell/browser/native_window_mac.mm

Transparent windows suffer critical visual issues, including flickering and ghost artifacts. This PR makes the `views::Widget` for macOS windows support transparency when the window is initialized as transparent.
Fixes #45932.
Notes: Fixed flickering and ghosting artifacts in transparent windows on macOS.

fix: flicker and ghosting in transparent windows on macOS

---

shell/browser/plugins/plugin_utils.cc

Refactor `GetMimeTypeToExtensionIdMap()` to avoid some unnecessary work:
- `GetMIMETypeAllowlist()` returns a `const&`, so keep a reference instead of cloning it
- Move the `ExtensionRegistry::Get(browser_context)` call outside of the loop
- Remove redundant map lookups
Notes: none.

perf: avoid unnecessary vector copy in `GetMimeTypeToExtensionIdMap()`

---

docs/api/base-window.md
docs/api/browser-window.md
shell/browser/ui/electron_desktop_window_tree_host_linux.cc

Closes https://github.com/electron/electron/issues/45799.
Refs CL:6231191
Adds support for `system-context-menu` to Linux, allowing developers to conditionally show the native context menu in non-client regions.
cc @bpasero 
Notes: Added support for `system-context-menu` on Linux.

feat: support `system-context-menu` on Linux

---

docs/api/utility-process.md
shell/browser/api/electron_api_utility_process.cc
spec/fixtures/crash-cases/utility-process-app-ready/index.js

Closes https://github.com/electron/electron/issues/41396
Supersedes https://github.com/electron/electron/pull/41450
Shorter-term address for a crash that occurs when `UtilityProcess.fork` is called before the app ready event.
Notes: Fixed an issue where calling `UtilityProcess.fork` prior to the app ready event would cause a crash.

fix: `UtilityProcess.fork` crash before app ready

---

docs/api/structures/protocol-response.md
docs/breaking-changes.md
shell/browser/net/electron_url_loader_factory.cc

BREAKING CHANGE
This feature was deprecated in f7ba0d3b (#46131). This PR removes it for Electron 37.
It's being removed because we should discourage single-use sessions. They allocate resources that stick around forever due to bac2f46.
Notes: Removed deprecated feature of creating a new random session by setting `ProtocolResponse.session`'s property to `null`.

feat!: remove support for ProtocolResponse.session null value

---

shell/browser/ui/views/autofill_popup_view.cc

Fix a memory leak in AutofillPopupView.
A `gfx::Canvas` was leaked each time `AutofillPopupView::OnPaint()` was called when the popup view had an `OffscreenViewProxy`.
Notes: Fixed memory leak in AutofillPopupView.

fix: leaked `gfx::Canvas` in `AutofillPopupView::OnPaint()`

---

shell/common/gin_helper/error_thrower.cc
shell/common/gin_helper/error_thrower.h

ErrorThrower's default constructor is commented this way:
```
// This constructor should be rarely if ever used, since
// v8::Isolate::GetCurrent() uses atomic loads and is thus a bit
// costly to invoke
```
Unfortunately, nearly every instance of ErrorThrower comes as an argument in gin_helper's JavaScript-to-C++ marshalling code where a [thrower is default-constructed](https://github.com/electron/electron/blob/09135443a04c2155198adc29515c1f9b247ff52e/shell/common/gin_helper/constructor.h#L33) and then [populated in gin_helper::GetNextArgument()](https://github.com/electron/electron/blob/09135443a04c2155198adc29515c1f9b247ff52e/shell/common/gin_helper/function_template.h#L152) with an assignment operator to a temporary `ErrorThrower` constructed with the `gin::Arguments`' isolate.
tldr: …

perf: have `ErrorThrower` lazily lookup the current isolate

---

shell/browser/usb/usb_chooser_context.cc

Avoid a redundant map lookup in `UsbChooserContext::OnDeviceRemoved()`.
All reviews welcomed. CC @codebytere who reviewed [this PR's sibling](https://github.com/electron/electron/pull/46343) :smile_cat: 
Notes: none.

perf: avoid redundant map lookup in UsbChooserContext::OnDeviceRemoved()

---

shell/browser/native_window_views.cc

The return value of `IsX11()` isn't ever going to change during an Electron session, and it's cheap to cache the return value in a `static const bool`, so let's do that instead of re-running the test every time the function is called.
Also, add a `[[nodiscard]]` annotation to indicate that callers should use the return value.
Notes: none.

perf: cache the return value of `IsX11()`

---

shell/browser/native_window.h
shell/browser/native_window_views.h
shell/browser/native_window_views_win.cc
shell/browser/osr/osr_render_widget_host_view.h
shell/browser/ui/views/global_menu_bar_registrar_x11.h
shell/browser/usb/usb_chooser_context.h
shell/renderer/electron_sandboxed_renderer_client.h

Part 3 of a small series to find places where we should migrate code to `absl::flat_hash_set` and `absl::flat_hash_map` to follow [upstream container recommendations](https://source.chromium.org/chromium/chromium/src/+/main:base/containers/README.md). Previously: #46202, #46348
This PR takes instances where we are using `std::set` but don't care about sorted order -- e.g. when we're holding a set of pointers -- and migrates them to `absl::flat_hash_set`.
All reviews welcomed. CC @codebytere and @clavin who reviewed 46202 and 46348.
Notes: none.

perf: prefer `absl::flat_hash_set` over `std::set` when sorted order is not needed

---

.github/workflows/pipeline-segment-electron-test.yml

Should fix our macOS tests which have been [failing](https://github.com/electron/electron/actions/runs/14226269149/job/39868911885?pr=46447).
The failures happened after https://github.com/actions/runner-images/pull/11877 [disabled graphics effects](https://github.com/actions/runner-images/commit/a2547b98201714dad9849c3600dae6554f410cea#diff-b068ae80fe8907d5eabab271f84c4abfff179adbc3a8c0d5d351b050cff3c1f2R20-R21).
The failures can be reproduced locally by setting the same `defaults`.  
The failures stop happening locally when undoing those `defaults` changes.
Notes: none

build: reenable graphics effects for macOS tests

---

patches/node/.patches
patches/node/zlib_fix_pointer_alignment.patch

Refs https://github.com/google/brotli/issues/1159
Refs https://github.com/nodejs/node/pull/57727
Fixes a possible issue with brotli and Node.js on some arm32 devices:
> On Arm 32bits the size_t is 4 bytes long, but the alignment is 8 for some NEON instructions. When Brotli is compiled with optimizations enabled newer GCC versions will use the NEON instructions and trigger a bus error killing node.
Notes: Fixes a possible crash using Node.js on some arm32 devices.

fix: zlib pointer alignment

---

shell/browser/native_window_views.cc

Fix a bug where `NativeWindowViews::GetRestoredState()` could return the wrong state for maximized windows on Linux.
Introduced by the af58931 Chromium 131.0.6744.0 roll, specifically [this change](https://github.com/electron/electron/commit/9840662#diff-f9d7ef71aadb519c42f18e9c0170137f634f267d72036ab62c3c9e4548c266e0L1787-L1788). Since this was part of the 131 roll, it needs to be backported to Electron 34 and higher.
Notes: Fixed a bug that could cause some maximized windows on Linux to report an incorrect window state.

fix: `NativeWindowViews::GetRestoredState()` can return wrong state when maximized

---

.github/workflows/pipeline-segment-electron-test.yml
shell/browser/ui/cocoa/electron_ns_window_delegate.mm

Another quirk of macOS I guess, but a non-animated resize isn't "live" so we handle the single resize event instead specifically when reduce motion is enabled.
This also reverts the graphics change in CI in order to "prove" this fixes it.
Closes #46455

fix: ensure maximize is emitted when reduce motion is enabled on macOS

---

shell/browser/api/gpuinfo_manager.cc
shell/browser/api/gpuinfo_manager.h
shell/browser/electron_browser_main_parts.cc

Fixes #46433
Notes: fix crash on application exit with pending `app.getGPUInfo` promise

fix: gin_helper::Promise in GPUInfoManager must be destroyed before destroying Node/V8

---

lib/node/asar-fs-wrapper.ts
patches/node/.patches
patches/node/fix_expose_readfilesync_override_for_modules.patch

New Node.js module resolution system reads `package.json` from imported modules by reading from the file natively in C++ without calling into `fs.readFileSync`. The ASAR FS wrapper code had copied files out into a temporary folder as a workaround, but it is inefficient and does not cover all module resolution mechanisms in Node.js.
In this change we expose `overrideReadFileSync` method on the `modules` binding in Node.js, and use this override to call into ASAR-supporting `fs.readFileSync`.
cc @codebytere @MarshallOfSound 
Notes: fix: don't copy 'package.json's out of ASAR file

fix: don't copy 'package.json's out of ASAR file

---

shell/browser/hid/hid_chooser_context.cc

Another "don't do the same thing twice in a row" PR.
This one removes a redundant map lookup in `HidChooserContext::DeviceChanged()`.
Notes: none.

perf: avoid redundant map lookup in `HidChooserContext::DeviceChanged()`

---

patches/chromium/.patches
patches/chromium/fix_false_activation_logic_for_context_menu.patch

Closes https://github.com/electron/electron/issues/46163
Refs https://github.com/electron/electron/pull/38903
Refs CL:6039992
Fixes a Linux-only issue where the context menu runs the action under the cursor when opened and should not.
Notes: Fixed a Linux-only issue where the context menu runs the action under the cursor when opened and should not.

fix: context menu runs action under cursor when opened

---

docs/tutorial/native-code-and-electron-cpp-win32.md

This is my second PR in a series of tutorials on how to integrate native code with Electron. All the maintainers are intimately familiar with Electron's "just write native code" superpower, but very little of that is prominently documented on the homepage. To make this easy to review, I'll be making a series of PRs.
This second tutorial covers building a Node.js addon with C++ targeting the Win32 API. It's a meaty one because I'm covering how to build native GUI using the Win32 Common Controls.
- Native Code and Electron ✅ 
- Native Code and Electron: C++ (Windows) `← You are here`
- Native Code and Electron: C++ (Linux)
- Native Code and Electron: Objective-C (macOS)
- Native Code and Electron: Swift (macOS)
- Native Code and Electron: Rust

docs: Add C++/Win32 tutorial

---

docs/api/command-line.md
docs/breaking-changes.md
shell/common/api/electron_api_command_line.cc

BREAKING CHANGE
Manually backport #46004 to 36-x-y. See that PR for details.
Notes: Fixed an issue where badly formatted switches could cause crashes in app.commandLine functions.

fix!: hard crash on invalid command line switches (36-x-y)

---

shell/services/node/node_service.cc
shell/services/node/parent_port.cc
shell/services/node/parent_port.h

Refs https://github.com/microsoft/vscode/issues/243957.
Refs https://github.com/electron/electron/pull/39335.
We previously added this change to `MessagePort` but did not do the same for `ParentPort`, and it seems it is subject to the same potential issue.
Notes: Fix a potential crash in `parentPort`.

fix: destroy parent port backend when JS env exits

---

shell/browser/api/electron_api_global_shortcut.cc

Manually backport #46229 to 33-x-y. See that PR for details.
Notes: none.

perf: avoid redundant map lookups in `GlobalShortcut::OnKeyPressed()` (33-x-y backport)

---

shell/renderer/web_worker_observer.cc

Manually backport #46347 to 33-x-y. See that PR for details.
Notes: none.

perf: improve temporaries in `WebWorkerObserver::WorkerScriptReadyForEvaluation()` (33-x-y)

---

shell/browser/api/electron_api_web_contents.cc

Small cleanup in `WebContents::RestoreHistory()`:
- Instantiate `navigation_entries` on the stack instead of the heap
- Call `navigation_entries.reserve()` to preallocate capacity for all the entries.
Notes: none.

refactor: instantiate `navigation_entries` local variable on the stack

---

shell/browser/api/electron_api_app.h

Remove this unused typedef. Its last use was removed in 2018 by 3f15f516
Notes: none.

refactor: remove unused `electron::api::App::FileIconCallback`

---

shell/browser/native_window_views.cc

Don't call `IsEnabled()` twice in a row. Yes, it's a cheap call. But it's also a virtual method that makes a syscall on Windows.
Why waste time make lot call when few call do trick?
guide](https://github.com/electron/electron/blob/main/docs/development/style-guide.md)
Notes: none.

perf: avoid redundant virtual method call in `NativeWindowViews::SetEnabledInternal()`

---

shell/browser/api/electron_api_web_contents.cc
shell/common/gin_converters/base_converter.h
shell/common/gin_converters/std_converter.h

Use `base::flat_set` in `WebContents::DidUpdateFaviconUrl()`. Add a `ToV8()` gin converter for `base::flat_set<T>` (and, more abstractly, for any `std::span<T>`).
The pre-existing spec  `<webview> tag events page-favicon-updated event emits when favicon urls are received`  tests this code.
Notes: none.

refactor: use `base::flat_set` in `WebContents::DidUpdateFaviconUrl()`

---

shell/common/asar/archive_win.cc

Several small performance improvements to `Archive::HeaderIntegrity()` on Windows:
- Don't make a temporary copy of the payload cache every time
- Keep the payload cache in an `absl::flat_hash_map` instead of a `std::map`
- Preallocate capacity when populating the payload cache
- Use `std::string_view` to avoid creating temporary strings to feed to the JSON parser
- Remove an unnecessary std::optional<> wrapper
Notes: Improved ASAR integrity checks on Windows.

perf: on Windows, make `Archive::HeaderIntegrity()` faster

---

docs/api/structures/base-window-options.md

Mark `titleBarOverlay.symbolColor` as supported on Linux, since this is supported via OpaqueFrameView added in 32e5012017c
Notes: none.

docs: note that `titleBarOverlay.symbolColor` is supported on Linux

---

shell/browser/native_window_mac.mm
shell/browser/native_window_views.cc
shell/browser/ui/inspectable_web_contents_view.cc
shell/browser/ui/views/autofill_popup_view.cc
shell/browser/ui/views/autofill_popup_view.h
shell/browser/ui/views/client_frame_view_linux.cc
shell/browser/ui/views/client_frame_view_linux.h
shell/browser/ui/views/menu_bar.cc
shell/browser/ui/views/opaque_frame_view.cc
shell/browser/ui/views/win_caption_button_container.h

Try to get a bit ahead of https://crbug.com/40485510, which is a long-standing issue but has seen a lot of recent commits.  
1. The _easy_ areas to fix the areas where we're just using raw pointers, but are using the default ownership method of letting the View parent own the child. In these cases, we can furtureproof our code by using  `AddChildView(std::unique_ptr<View>)` instead of `AddChildView(View*)`:
```diff
- child_ = new SomeView();
- child_->SetSomeProperty(false);
- view->AddChildView(child_);
+ auto child = std::make_unique<SomeView>();
+ child->SetSomeProperty(false);
+ view_ = AddChildView(std::move(child));
```
2. There are also _harder_ areas to update because we managing some child views' lifecycles ourselves & can't pass ownership to the parent view. I've flagged these …

refactor: migrate to `View::AddChildView(std::unique_ptr<ui::View*>)`

---

.github/ISSUE_TEMPLATE/bug_report.yml

Asking for repros is the biggest drain of time when triaging issues.
This PR changes the issue template to encourages developers to include repros without us having to ask.
Notes: none

build: emphasize the need for a testcase in our issue template

---

shell/browser/api/electron_api_web_contents.cc

Manually backport #46409. See that PR for details.
Notes: none.

perf: avoid redundant call to virtual methods `GetProcess()` and `GetID()` (34-x-y backport)

---

shell/browser/api/electron_api_global_shortcut.cc

Manual backport of #46229. See that PR for details.
Notes: none.

perf: avoid redundant map lookups in `GlobalShortcut` (34-x-y backport)

---

shell/browser/api/electron_api_view.cc
shell/browser/api/electron_api_view.h

Teeny cleanup PR 3 of 3: Make some `api::View` methods const or private:
- Make `OnBoundsChanged()` private
- Make `OnViewIsDeleting()` private
- Make `OnChildViewRemoved()` private
- Make `GetBounds()` const
- Make `ChildPair` private
Notes: none.

refactor: make `api::View` methods const, private

---

shell/renderer/web_worker_observer.cc

Manually backport #46347 to 34-x-y. See that PR for details.
Notes: none.

perf: improve temporaries in `WebWorkerObserver::WorkerScriptReadyForEvaluation()` (34-x-y backport)

---

shell/common/gin_helper/trackable_object.h

Small cleanup to the way `TrackableObjectBase` and `TrackableObject` generate unique IDs.
- Make `weak_map_id_` const and private
- Simplify `next_id_` declaration by using `static inline`
- Make `next_id_` private
Notes: none.

refactor: make `TrackableObjectBase::weak_map_id_` const

---

shell/browser/api/electron_api_base_window.cc
shell/browser/api/electron_api_base_window.h
shell/common/gin_converters/std_converter.h

A new change in 41d8f90d lets us convert spans to V8. This means we can avoid `std::vector` heap allocations when we're dealing with a fixed-size span (we can use `std::array`) or a span with a known maximum size (we can use `absl::inlined_vector`).
This PR applies this idea to some low-hanging fruit, `BaseWindow`'s size and point getters.
Notes: none.

refactor: simplify some `BaseWindow` JS getters

---

shell/browser/electron_web_ui_controller_factory.cc

I'm doing spring cleaning on some small cleanup branches that I've had hanging around on my computer for awhile --
Teeny cleanup 1 of 3: `const_cast` is not needed in `ElectronWebUIControllerFactory::GetWebUIType()`  because as of July 2019 in 50b9c70 it is no longer a const method.
Notes: none.

refactor: remove unnecessary `const_cast`

---

shell/common/gin_helper/callback.cc
shell/common/gin_helper/event_emitter_caller.cc

Teeny cleanup 2 of 3: Instead of `v8::Boolean::New(isolate, true-or-false)`, use `v8::True(isolate)` and `v8::False(isolate)`.  They are slightly easier to read and very slightly faster (since `New()` just calls `True()` or `False()`)
```diff
- v8::Boolean::New(isolate, true)
+ v8::True(isolate)
- v8::Boolean::New(isolate, false)
+ v8::False(isolate)
```
Notes: none.

refactor: use v8::True(isolate) and v8::False(isolate)

---

shell/browser/api/electron_api_browser_window.cc
spec/api-browser-window-spec.ts

Closes https://github.com/electron/electron/issues/45595.
Adds missing checks for `api_web_contents_` validity present in other methods in this file but missing here.
Notes: Fixed a possible BrowserWindow crash caused by closing a parent window with focus or blur events.

fix: crash on parent window close and focur/blur

---

lib/browser/init.ts
patches/node/chore_allow_the_node_entrypoint_to_be_a_builtin_module.patch
typings/internal-ambient.d.ts

Closes https://github.com/electron/electron/issues/46491.
Refs https://github.com/nodejs/node/pull/55679
Removes logic made redundant in https://github.com/nodejs/node/pull/55679/files.
Notes: Fixed an issue with `--inspect-brk`  failing in packaged apps.

fix: remove obsoleted `--inspect-brk` logic

---

shell/browser/native_window.cc
shell/browser/native_window.h

`NativeWindow::window_id()` always returned the same value, no matter which `NativeWindow` was being queried. This caused `ElectronAccessibilityUI` to behave unpredictably because `RequestNativeUITree()` could sometimes key in on the wrong native window. Introduced in 3f37ff8.
Notes: Fixed ElectronAccessibilityUI bug.

fix: `NativeWindow.window_id()` returns same value for all windows

---

docs/fiddles/ipc/pattern-1/main.js
docs/tutorial/ipc.md

Unify the IPC Pattern 1 implementation in documentation with the actual fiddle code by:
- Adding `handleSetTitle` and removing anonymous callback in `set-title` event in `main.js` file in pattern-1 fiddle to match ipc.md
- Adding missing event handler for `activate` in `ipc.md` to match `main.js` in pattern-1 fiddle
Notes: No notes

docs: unify documentation example and fiddle for IPC pattern-1

---

docs/api/native-theme.md
shell/browser/api/electron_api_native_theme.cc
shell/browser/api/electron_api_native_theme.h
spec/api-native-theme-spec.ts

Closes https://github.com/electron/electron/issues/46429.
Refs https://github.com/electron/electron/pull/19735.
This PR adds a new API `shouldUseDarkColorsForSystemIntegratedUI` to the `nativeTheme` module. This API returns a boolean indicating whether the system is using dark colors for system integrated UI elements. This is useful for applications that want to adapt their UI to match the system theme, especially for those that use system integrated UI elements like the shell theme or taskbar appearance.
Notes: Added `nativeTheme.shouldUseDarkColorsForSystemIntegratedUI` to distinguish system and app theme.

feat: expose `nativeTheme.shouldUseDarkColorsForSystemIntegratedUI`

---

script/lint.js

Unknown reason why this suddenly became a problem, but the lint script started popping false positives inside the `.git` directory so explicitly ignore it.
Notes: none

build: ignore files in .git when running markdownlint-cli2

---

lib/browser/api/web-contents.ts
shell/browser/api/electron_api_web_contents.cc
shell/common/gin_helper/dictionary.h

Closes https://github.com/electron/electron/issues/31151.
Fixes an issue where printing from the renderer process crashes the main process when no printers are installed in the system or there's not a default printer.
Notes: Fixed an issue where printing from the renderer process crashes the main process when no printers are installed in the system or there's not a default printer.

refactor: use default printing path when no user options

---

docs/api/menu.md
shell/browser/api/electron_api_menu_mac.mm

Closes https://github.com/electron/electron/issues/46505
Follow up to #45138
This PR re-adds and falls back to the old code path for context menus, should a user not explicitly pass in a frame option into the menus
Notes: Fixed an issue where context menu actions such as copy/paste did not correctly fire when a frame was not passed in

fix: fallback to old MacOS context menu behavior if no frame is present

---

lib/browser/api/browser-window.ts

Closes https://github.com/electron/electron/issues/46574.
If an app for some reason emits `close` themselves the `close` event won't have an `event` property necessarily. Ensure an error isn't thrown in that case.
Notes: Fixed an error when calling `window.emit('close')` after toggling fullscreen mode.

fix: handle potential missing close event property

---

docs/api/web-contents.md

Issue: #46573  
Original PR: #45667
Notes: none

docs: `webContents.opener` can be null

---

shell/browser/ui/electron_desktop_window_tree_host_linux.cc

Closes https://github.com/electron/electron/issues/46484.
Refs https://github.com/electron/electron/issues/46155.
Fixes an inverted conditional in the above PR that caused broken window borders in some circumstances on Wayland.
Notes: Fixed an inverted conditional in the above PR that caused broken window borders in some circumstances on Wayland.

fix: window border on Gnome Wayland

---

shell/browser/ui/file_dialog_mac.mm

Migrate from deprecated [`allowedFileTypes`](https://developer.apple.com/documentation/appkit/nssavepanel/allowedfiletypes?language=objc) to non-deprecated [`allowedContentTypes`](https://developer.apple.com/documentation/appkit/nssavepanel/allowedcontenttypes?language=objc) in preparation for upcoming macOS minimum level migration to macOS 12.
Notes: none

refactor: migrate to non-deprecated `allowedContentTypes` on macOS

---

patches/node/feat_add_oom_error_callback_in_node_isolatesettings.patch
patches/node/fix_assert_module_in_the_renderer_process.patch
spec/node-spec.ts

Backport of #46528.
Notes: Fixed an issue with the `assert` Node.js module in the renderer process.

fix: `assert.ok` in the renderer process

---

shell/browser/api/electron_api_utility_process.cc
shell/browser/api/message_port.cc
shell/common/gin_helper/wrappable.cc
shell/common/gin_helper/wrappable.h
spec/api-ipc-spec.ts

Refs https://github.com/microsoft/vscode/issues/192175
Second effort at this with feedback incorporated from https://github.com/electron/electron/pull/41504/files#r1516814893
Fixes a potential crash in `utilityProcess.postMessage` when calling with an invalid transferable. This happened when passing e.g. an (unsupported) ArrayBuffer, because we try to unwrap everything in the transferrables list and upstream's [WrapperInfo ](https://source.chromium.org/chromium/chromium/src/+/main:gin/wrapper_info.cc;l=10-16;drc=0e9a0b6e9bb6ec59521977eec805f5d0bca833e0) logic doesn't take into account that an object might have the correct number of internal fields but not be a `WrappableBase`.
This PR also removes a check in `message_port.cc` for at least one argument being passed. The type of message is …

fix: `postMessage` crash with invalid transferrable

---

shell/common/v8_util.cc

Fixes #46654
> The root cause is that webContents.send eventually calls [Serialize](https://github.com/electron/electron/blob/32fea719b393c2757c4737386564c910d49b529e/shell/common/v8_util.cc#L37-L40), which has a `gin_helper::MicrotasksScope` that was changed in https://github.com/electron/electron/pull/43209. That change was one of the few that were unclear what the desired behavior should be and changed.
Notes: Microtasks are no longer (incorrectly) run by serializing values, including when sending IPC.

fix: do not run microtasks in V8Serializer in browser process

---

shell/browser/hid/electron_hid_delegate.cc

Refactor `ElectronHidDelegate::GetContextObserver()` s.t. it doesn't perform the same map lookup 3x in a row.
Notes: none.

perf: avoid triple map lookup in `ElectronHidDelegate::GetContextObserver()`

---

shell/browser/api/electron_api_auto_updater.cc
shell/common/api/electron_bindings.cc
shell/common/v8_util.cc
shell/renderer/api/electron_api_spell_check_client.cc
shell/renderer/electron_sandboxed_renderer_client.cc

Each of the 3 commits in this PR targets a specific use or category of uses of `gin_helper::MicrotasksScope` for removal and includes in-depth discussion on why they are removed. In summary:
* 2 browser process no-ops are removed
* 3 uses in `shell/renderer/` are reduced to `v8::MicrotasksScope`
Beyond only looking at the parameters & path name, I also considered the surrounding context and history (via. git blame) of each case, with the goal to avoid removing a call that _should_ be there but was incorrectly configured.
This leaves all remaining uses of `gin_helper::MicrotasksScope` in `shell/common/`.
Refs: #46669
(Branch based off #46668, ignore the `fix: do not run microtasks in V8Serializer in browser process` commit.)
Notes: none

refactor: reduce & remove no-op MicrotasksScope calls

---

patches/chromium/.patches
patches/chromium/mac_fix_check_on_ime_reconversion_due_to_invalid_replacement_range.patch

Backports https://chromium-review.googlesource.com/c/chromium/src/+/6470915
Refs https://github.com/microsoft/vscode/issues/230303
Notes: fix crash on reconversion with google IME and editcontext on macOS

fix: crash on reconversion with google IME and editcontext on macOS

---

shell/browser/api/electron_api_base_window.h
shell/browser/api/electron_api_browser_window.cc

Just a little code cleanup: make private the fields in the C++ class `electron::api::BaseWindow`.
No functional changes.
Notes: none.

refactor: make `electron::api::BaseWindow` fields private

---

docs/tutorial/custom-window-styles.md

> Transparent windows will not work when DWM is disabled.
This no longer applies since Electron 23, which only supports Windows 10+, where DWM composition can no longer be disabled.
Follow-up to #45563
Notes: none

docs: cleanup docs/tutorial/custom-window-styles.md

---

lib/browser/api/menu-item-roles.ts
spec/api-menu-item-spec.ts

Closes #46676
Previously the "Minimize" menu button would still allow the user to minimize the window on Windows, even if the window was created with `minimizable: false`. Now the window will not be able to be minimized via that button.
A follow-up PR is necessary to disable the button such that it is grayed out as well on both macOS and Windows.
Notes: fix Minimize menu button to follow set window minimizability on Windows

fix: stop menu minimization if set false

---

.github/actions/checkout/action.yml

Wait for any potential debugging sessions to exit before exiting the action. Without this they'll be killed forcefully during debugging.
Notes: none

build: don't kill ssh sessions on checkout failure

---

shell/browser/ui/file_dialog_linux.cc

Fixed a problem where filter name and the extensions they filter won't match.
If someone sets an `All filter` with `*` at the start of the filters all upcoming filters will be shifted and thus labels won't fit to the extensions they actually filter.
Notes: Fixed case where file dialog filters would get mixed up, if a `*` filter was included

fix: file dialog filters not working correctly

---

patches/chromium/.patches
patches/chromium/cherry-pick-0333ecde9142.patch

usb: Use GlobalRenderFrameHostId in UsbChooserController
The UsbChooserController currently holds a raw pointer to the requesting
RenderFrameHost. This can lead to use-after-free issues if the
RenderFrameHost is destroyed before the chooser controller. This CL
replaces the raw pointer with a `GlobalRenderFrameHostId`. This ID can
be used to retrieve the RenderFrameHost when needed, and checks are
added to ensure the RenderFrameHost is still valid before accessing it.
Bug: 405292639
Change-Id: Ifedaf80f6700d57ea28691abfaf4d2ff9cdbb448
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6440254
Commit-Queue: Alvin Ji <alvinji@chromium.org>
Reviewed-by: Matt Reynolds <mattreynolds@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1444224}
Notes: Backported fix for …

chore: cherry-pick 0333ecde9142 from chromium

---

docs/api/native-image.md
docs/api/web-contents.md
docs/breaking-changes.md
shell/common/api/electron_api_native_image.cc
shell/common/api/electron_api_native_image.h
spec/api-browser-window-spec.ts
spec/api-native-image-spec.ts
spec/ts-smoke/electron/main.ts

Mark `NativeImage.getBitmap()` as deprecated and document it as an alias for `NativeImage.toBitmap()`.
The documentation says:
> The difference between `getBitmap()` and `toBitmap()` is that `getBitmap()` does not
copy the bitmap data, so you have to use the returned Buffer immediately in
current event loop tick; otherwise the data might be changed or destroyed.
...but this hasn't been true since June 2022  https://github.com/electron/electron/pull/34403/commits/f61be5720deb2f21e7d4102b0f71d90258f0b0a4#diff-87426541166a1d650dedb7f3804023ffeb1718899ab7a83814ad538061546d60 because the old behavior of `getBitmap()` wasn't sandbox-compatible. For nearly three years, both functions have returned a newly-allocated copy of the bitmap and are functionally equivalent. :smile_cat: 
So this PR:
1. …

refactor: remove redundant NativeImage::GetBitmap()

---

filenames.gni
shell/browser/api/electron_api_base_window.cc
shell/browser/api/electron_api_base_window_mac.mm
shell/browser/api/electron_api_web_contents.cc
shell/browser/api/electron_api_web_contents_mac.mm
shell/browser/native_window.h

Fixes #46732.
This fixes a recent regression on macOS that caused `getNativeWindowHandle()` to return the wrong pointer.
Tracking this down was a fun ride. Full description [here](https://github.com/electron/electron/issues/46732#issue-3012257426).
Notes: Fixed `getNativeWindowHandle()` crash that affected 36 betas on macOS.

fix: explicitly call GetNativeNSView() on macOS

---

shell/browser/api/electron_api_web_contents.cc
shell/browser/api/electron_api_web_contents.h
shell/browser/api/electron_api_web_contents_mac.mm

Remove some API that was added in by https://github.com/electron/electron/pull/10308. It was added explicitly as private API, not public or experimental. But it was never called, never added to the ts types, never documented, and never tested. It may have been created for [this 2020 experiment](https://github.com/zcbenz/electron_yue) which had two commits in 2020.
Notes: none.

chore: remove `WebContents.getNativeView()`

---

shell/browser/api/electron_api_base_window.cc

Closes https://github.com/electron/electron/issues/46752.
Adds missing `v8::HandleScope` to `BaseWindow::RemoveFromParentChildWindows`.
Notes: Fixes a potential crash when closing a window with child windows.

fix: missing `HandleScope` in `RemoveFromParentChildWindows`

---

shell/browser/api/electron_api_cookies.cc
spec/api-session-spec.ts

- Removed our bespoke domain tester and updated callers to use [net::CanonicalCookie::IsDomainMatch()](https://chromium.googlesource.com/chromium/src/+/main/net/cookies/cookie_base.h#81) instead.
- Added domain-matching tests to `spec/api-session-spec.ts`.
Our bespoke method [first landed](https://github.com/electron/electron/pull/1981) in June 2015; but `IsDomainMatch()` has been public API since 2012 and seems like a perfect match, so I'm not sure why we haven't been using it all along. My guess is that it was an oversight?  Hopefully I'm not missing something subtle here -- CC @VerteDinde in case this is another [DomainIs()](https://github.com/electron/electron/pull/44153) change :slightly_smiling_face:  
Notes: none.

refactor: use `net::CanonicalCookie::IsDomainMatch()`

---

docs/breaking-changes.md

A few commits look like they might have mislabeled which version they would be breaking in. The first two backports would cause the changes to break in 36 as opposed to 37. The last PR was not backported to 36-x-y and thus will not land in a version until 37-x-y is cut.
- https://github.com/electron/electron/pull/46446
- https://github.com/electron/electron/pull/46736
- https://github.com/electron/electron/pull/45921
Notes: none

docs: correct breaking-changes.md for 36.0.0 release

---

build/args/all.gn

In preparation for releasing Electron 36 and cutting the `37-x-y` branch, this PR bumps the NMV to 136 for Electron 37.
(Ignore branch name and commit title, brain had an off-by-one error)
Ref: https://github.com/nodejs/node/pull/57979
Notes: none

build: update NMV to 136 for Electron 37

---

shell/browser/lib/bluetooth_chooser.cc
shell/browser/lib/bluetooth_chooser.h

Closes https://github.com/electron/electron/issues/46707
Fixes a possible crash when using `navigator.bluetooth.requestDevice` and the `select-bluetooth-device` event. This happened in the case where Bluetooth was turned off and `navigator.bluetooth.requestDevice` was called and subsequently cancelled via the `select-bluetooth-device` event. Also a bit of related cleanup.
Notes: Fixed a possible crash when using `navigator.bluetooth.requestDevice` and the `select-bluetooth-device` event.

fix: bluetooth crash in `select-bluetooth-device` event

---

docs/breaking-changes.md

- Followup to #46762
- #45887 did not get backported to 36-x-y and it shouldn't be listed as a breaking change there.
Notes: none

docs: additional update of breaking changes for 36-x-y

---

docs/tutorial/native-code-and-electron-objc-macos.md

This is my third PR in a series of tutorials on how to integrate native code with Electron. All the maintainers are intimately familiar with Electron's "just write native code" superpower, but very little of that is prominently documented on the homepage. To make this easy to review, I'll be making a series of PRs.
This third tutorial covers building a Node.js addon with Objective-C/Objective-C++ targeting macOS. It's a meaty one because I'm covering how to build native GUI using AppKit.
- Native Code and Electron ✅ 
- Native Code and Electron: C++ (Windows) ✅ 
- Native Code and Electron: Objective-C (macOS) `← You are here`
- Native Code and Electron: Swift (macOS)
- Native Code and Electron: C++ (Linux)
- Native Code and Electron: Rust

docs: Add ObjC/macOS tutorial

---

shell/browser/electron_autofill_driver_factory.cc
shell/browser/file_system_access/file_system_access_permission_context.cc
shell/browser/hid/electron_hid_delegate.cc
shell/browser/hid/hid_chooser_context.cc
shell/browser/net/proxying_url_loader_factory.cc
shell/browser/notifications/mac/cocoa_notification.mm
shell/browser/serial/electron_serial_delegate.cc
shell/browser/serial/serial_chooser_context.cc
shell/browser/usb/electron_usb_delegate.cc
shell/browser/usb/usb_chooser_context.cc

Small cleanup in our use of maps: `try_emplace()` has more efficient move semantics and its name is clearer about what happens when the same key is already present in the map. All other things being equal, we should use it instead of `insert()`.
All human reviews welcomed! :smile_cat: I'm also requesting a review from Copilot just to see what will happen; I've never used that before.
Notes: none.

refactor: use `std::map::try_emplace()` over `std::map::insert()`

---

shell/browser/api/electron_api_browser_window.cc
shell/browser/api/electron_api_browser_window.h

Remove `electron::api::BrowserWindow`'s public method `GetWeakPtr()`.
It's only used internally, so we shouldn't be exposing it to other classes.
Notes: none.

refactor: remove public method `BrowserWindow::GetWeakPtr()`

---

docs/breaking-changes.md

As decided in #46538, a callout is added to the breaking changes doc for Electron 36 for the [upstream transition to GTK 4 when using GNOME](https://chromium-review.googlesource.com/c/chromium/src/+/6310469).
The specific error text and the workaround flag are mentioned so users can find this change easily.
Notes: none

docs: call out breaking change for GTK 4 default on GNOME

---

shell/common/gin_converters/usb_protected_classes_converter.h

- Add a gin converter that can convert `std::span<const T>` to V8. Its code is nearly identical to the `std::vector<T>` gin converter, but this lets us pass in non-vector spans, e.g. std::array or [absl::InlinedVector](https://github.com/abseil/abseil-cpp/blob/master/absl/container/inlined_vector.h).
- Add a simple example in the `USBProtectedClasses` gin converter: it now uses a stack-allocated `absl::InlinedVector<std::string_view>` instead of a `std::vector<std::string>`.
Notes: none

refactor: use `absl::InlinedVector` in `ToV8(ElectronPermissionManager)`

---

patches/chromium/fix_activate_background_material_on_windows.patch

Manual backport of #46657 to 36-x-y. See that PR for details.
Notes: Fixed an issue where the backgroundMaterial feature did not work in a frameless window on initial window creation.

fix: `backgroundMaterial` on initial activate (36-x-y)

---

shell/browser/native_window.cc
shell/browser/native_window.h
shell/browser/native_window_mac.h
shell/browser/native_window_mac.mm
shell/browser/native_window_views.cc
shell/browser/native_window_views.h

Unify some logic within NativeWindow - this is implemented upstream everywhere except Linux.
Notes: none

refactor: use upstream content protection logic on macOS

---

docs/api/base-window.md
docs/api/browser-window.md
docs/api/structures/base-window-options.md
spec/api-browser-window-spec.ts

Part 3 in a series to enable/fix tests that didn't run due to #46807. This step fixes the `autoHideMenuBar` tests:
- enable `autoHideMenuBar` tests on Linux, Windows
- mark the `BaseWindow.autoHideMenuBar` property as supported on Linux, Windows
Notes: Fixed documentation to mark `Window.autoHideMenuBar` as supported on Linux and Windows.

fix: enable `autoHideMenuBar` tests on Linux and Windows

---

spec/api-browser-window-spec.ts

Part 1 in a series to enable/fix tests that didn't run due to #46807. 
This step fixes three issues with the `visibleOnAllWorkspaces` tests:
- The tests were enabled on Windows, even though Windows doesn't support this feature
- The tests were skipped on Linux, even though Linux supports this feature
- Due to nested `it()` statements, the tests were not run on any platform (which is why they didn't fail on Windows :smile_cat:)
This PR fixes these by running the tests on Linux and macOS.
All reviews welcomed. CC @nikwen who reviewed the original PR.
Notes: none.

fix: run `visibleOnAllWorkspaces` tests on the right platforms

---

shell/browser/usb/electron_usb_delegate.cc

```
In file included from ../../base/allocator/partition_allocator/src/partition_alloc/pointers/raw_ptr_backup_ref_impl.h:13,
from ../../base/allocator/partition_allocator/src/partition_alloc/pointers/raw_ptr.h:50,
from ../../base/memory/raw_ptr.h:11,
from ../../base/memory/weak_ptr.h:82,
from ../../electron/shell/browser/usb/electron_usb_delegate.h:14,
from ../../electron/shell/browser/usb/electron_usb_delegate.cc:5:
../../base/allocator/partition_allocator/src/partition_alloc/partition_address_space.h:279:3: warning: multi-line comment [-Wcomment]
279 |   //       \
|   ^
../../base/allocator/partition_allocator/src/partition_alloc/partition_address_space.h:281:3: warning: multi-line comment [-Wcomment]
281 |   //         \
|   ^
In file included from /usr/include/c++/14/memory:78,
from …
```

fix: build error with enable_electron_extensions=false

---

docs/api/base-window.md
docs/api/browser-window.md
docs/api/structures/base-window-options.md
spec/api-app-spec.ts
spec/api-browser-window-spec.ts

Part 2 in a series to enable/fix tests that didn't run due to #46807. This step fixes some `mocha/no-nested-tests` errors that prevented several tests from being run.
All reviews welcomed. CC @nikwen who reviewed the original PR.
Notes: none.

fix: enable some tests that were accidentally disabled

---

shell/browser/native_window_views.cc
shell/browser/native_window_views.h

fix: #46468
I can't run the test on the company's device. It gives the error "Error: Failed to get git tag, script quit with 9009." I looked at the script file but couldn't understand what's happening...
Notes: Fixed the issue where maximizing and restoring the window does not respect the corner radius settings, and the corner radius is incorrect in fullscreen mode.

fix: fullscreen fillet / recovery is incorrect

---

spec/api-app-spec.ts
spec/api-browser-window-spec.ts

Part 4 in a series to enable/fix tests that didn't run due to #46807. This one fixes the `accessibilitySupportEnabled` tests:
- Fix nested-it bug in the spec that prevented the tests from running.
- Fix tests that failed because they assumed the default initial state.
- Test every getter after calling each setter.
Notes: none.

fix: fix and enable `accessibilitySupportEnabled` tests

---

shell/browser/native_window_views.cc
spec/api-browser-window-spec.ts

Fix the broken `visibleOnAllWorkspaces` property on Linux and enable the related tests.
#45887 is the right long-term fix and is what we're using in Electron 37; however, it can't be backported because it has an edge case that counts as a breaking change.
This PR isn't as clean or maintainable, but it does fix the same bug in a nonbreaking way. So it's not here to supersede 45887, just to patch the older maintenance branches.
All reviews welcomed. CC @codebytere who wrote 45887.
Notes: Fixed the `visibleOnAllWorkspaces` property on Linux.

fix: Linux `visibleOnAllWorkspaces` property

---

shell/browser/native_window.cc
shell/browser/native_window.h
shell/browser/native_window_mac.h
shell/browser/native_window_mac.mm
shell/browser/native_window_views.cc
shell/browser/native_window_views.h
spec/api-browser-window-spec.ts

Use Chromium's `WidgetDelegate`'s title property instead of  implementing it ourselves in our `NativeWindow` subclasses.
1. In `NativeWindow`, make `GetTitle()` and `SetTitle()` non-virtual and have them use `WidgetDelegate`.
2. In `NativeWindow`, add new protected virtual method `OnTitleChanged()` to notify subclasses of changes.
3. Update the `NativeWindowMac` and `NativeWindowViews` subclasses accordingly.
4. Expand testing by adding Linux to the list of platforms that `BrowserWindow.title` tests run on.
All reviews welcome. Also CC @codebytere since she reviewed related PR #46765.
Notes: none.

refactor: use WidgetDelegate's title property

---

shell/browser/api/electron_api_web_request.cc
shell/browser/native_window_mac.mm
shell/common/api/electron_api_native_image.cc
shell/common/node_util.cc
shell/common/node_util.h

Also switches `EmitWarning` to using Node's `ProcessEmitWarningGeneric`. Just a small quality of life improvement here.
Notes: none

refactor: add EmitDeprecationWarning helper

---

patches/v8/.patches
patches/v8/enable_--perf-prof_flag_on_macos.patch

Backport of #46757
Notes: Added support for `--js-flags=--perf-prof` on macOS

feat: add support for `--js-flags=--perf-prof` on macOS

---

patches/chromium/chore_grandfather_in_electron_views_and_delegates.patch
shell/browser/native_window_views.cc

Part 2 in a [series](https://github.com/electron/electron/pull/46857) to remove deprecated `views::` API from our C++ code.
This removes the `RegisterDeleteDelegateCallback()` call from `NativeWindowViews` and moves the on-delegate-deleted callback logic to `OnWidgetDestroying()` and `OnWidgetDestroyed()`.
Notes: none

refactor: don't call deprecated `WidgetDelegate` API in `NativeWindowViews`

---

BUILD.gn
docs/api/base-window.md
docs/api/browser-window.md
docs/api/screen.md
shell/browser/api/electron_api_screen.cc
shell/browser/api/electron_api_screen.h
shell/browser/linux/x11_util.cc
shell/browser/linux/x11_util.h
shell/browser/native_window_views.cc

Refs https://github.com/electron/electron/pull/45848.
Adds support for `screen.dipToScreenPoint(point)` and `screen.screenToDipPoint(point)` on Linux X11. There's currently no support for Wayland as the coordinate system is notably more difficult to reconcile with this.
Notes: Added support for `screen.dipToScreenPoint(point)` and `screen.screenToDipPoint(point)` on Linux X11.

feat: support dip <-> screen conversion on Linux X11

---

shell/browser/api/electron_api_web_contents.cc
shell/browser/browser.cc
shell/browser/hid/electron_hid_delegate.cc
shell/browser/hid/hid_chooser_context.cc
shell/browser/native_window.cc
shell/browser/serial/electron_serial_delegate.cc
shell/browser/serial/serial_chooser_context.cc
shell/browser/ui/electron_menu_model.cc
shell/browser/ui/tray_icon.cc
shell/browser/ui/views/menu_delegate.cc
shell/browser/usb/electron_usb_delegate.cc
shell/browser/usb/usb_chooser_context.cc
shell/browser/web_contents_zoom_controller.cc
shell/browser/window_list.cc

Update our code to use `base::ObserverList::Notify()`, a function [added last year](https://chromium-review.googlesource.com/c/chromium/src/+/5868181) to simplify observer notification.
Notes: none.

refactor: use `base::ObserverList::Notify()`

---

docs/api/native-image.md

It was [really easy](https://github.com/electron/electron/issues/46514#issuecomment-2780698294) to think about the `nativeImage.createFromPath()` as a synchronous replacement for `Electron.App#getFileIcon()` which is [wrong](https://github.com/electron/electron/issues/46514#issuecomment-2780698294)
Notes: none

docs: clarified usage of createFromPath()

---

shell/common/api/electron_api_testing.cc
shell/common/logging.cc
spec/fixtures/log-test.js
spec/logging-spec.ts

* regression was introduced in https://github.com/chromium/chromium/commit/9d2b795f72832aa7216d7c84bdbf5d2358346548
* it appears that Electron is involved in the processing of the command line for Chromium child processes but doesn't handle the new "handle" option value
* this fix duplicates the new logic in `logging_chrome.cc` introduced in the patch that caused the regression
* that file appears to be where Electron's `logging.cc` was originally copied from based on a bunch of similarities in the code of the two files
* verified this does not write log files to the CWD with the fix
Fixes https://github.com/electron/electron/issues/46836
Fixes https://github.com/electron/electron/issues/43508
Notes: fix log files written to the current working directory on Windows

fix: prevent log files being written to current directory on Windows

---

shell/browser/api/electron_api_web_contents_view.cc
shell/browser/native_window.cc
shell/browser/native_window.h
shell/browser/native_window_mac.mm
shell/browser/native_window_views.cc

Add a helper method `static NativeWindow* NativeWindow::FromWidget(const views::Widget*)` to simplify client code: instead of knowing about the native window property values and `kElectronNativeWindowKey`, it just calls a getter instead.
Notes: none.

refactor: add `NativeWindow::FromWidget()` helper

---

shell/browser/api/electron_api_web_contents.cc
shell/browser/native_window.h
shell/browser/native_window_mac.mm
shell/browser/ui/cocoa/electron_ns_window_delegate.mm

We only care whether the window is transitioning, not whether the transition is entering or exiting. So let's simplify NativeWindow by replacing the tri-state transition state with an `is_fullscreen_transitioning` bool.
Notes: none.

refactor: simplify `NativeWindow::FullScreenTransitionState`

---

shell/browser/native_window.cc
shell/browser/native_window.h

Small refactor to make some incidentally-public API either protected or private
- Remove `NativeWindow::background_material()`: it was only used in one place and that's in a const `NativeWindow` method, so remove the getter and just reference the field directly instead.
- Remove `NativeWindow::vibrancy()`: same as above.
- Make `NativeWindow::set_has_frame()` protected because it's only needed by subclasses.
- Make `NativeWindow::titlebar_overlay_height_` private. Clients should use the getter & setter.
- Have `NativeWindow` unfriend `api::BrowserView`; this hasn't been needed since 2022
Notes: none.

refactor: remove some `NativeWindow` public API

---

shell/browser/native_window.h

`NativeWindow`  has a handful of virtual methods that are never overridden. Let's devirtualize them to avoid the vtable overhead.
Notes: none.

refactor: devirtualize `NativeWindow` methods

---

shell/browser/api/electron_api_web_contents.cc
shell/browser/native_window.h
shell/browser/native_window_mac.mm
shell/browser/ui/cocoa/electron_ns_window_delegate.mm

Manually backport #46918 to 36-x-y. See that PR for details.
Notes: none.

refactor: simplify `NativeWindow::FullScreenTransitionState` (36-x-y)

---

filenames.gni
patches/chromium/feat_add_support_for_missing_dialog_features_to_shell_dialogs.patch
shell/browser/ui/file_dialog.h
shell/browser/ui/file_dialog_linux.cc
shell/browser/ui/file_dialog_linux_portal.cc

Backport of #46905
Notes: fix xdg portal version detection for file dialogs on linux

fix: xdg portal version detection for file dialogs on linux

---

shell/browser/native_window.cc
shell/browser/native_window.h

Manually backport #46919 to 37-x-y. See that PR for details.
Notes: none.

refactor: remove some `NativeWindow` public API (37-x-y)

---

shell/browser/ui/file_dialog_mac.mm

Closes https://github.com/electron/electron/issues/46883.
Refs https://github.com/electron/electron/issues/46623
Fixes an issue where filters wouldn't apply in the specific case only one was passed.
Notes: Fixed an issue where filters wouldn't apply in the specific case only one was passed.

fix: allowed dialog file types with one filter

---

shell/browser/ui/cocoa/electron_ns_window.mm

Closes https://github.com/electron/electron/issues/46916.
Refs https://github.com/electron/electron/pull/45238
Fixes a crash that occurred with the following stacktrace:
<details><summary>Stack Trace</summary>
<p>
```
Received signal 11 SEGV_ACCERR 0000000002c8
0   Electron Framework                  0x000000012211083c base::debug::CollectStackTrace(base::span<void const*, 18446744073709551615ul, void const**>) + 28
1   Electron Framework                  0x0000000122100cbc base::debug::StackTrace::StackTrace(unsigned long) + 224
2   Electron Framework                  0x0000000122110790 base::debug::(anonymous namespace)::StackDumpSignalHandler(int, __siginfo*, void*) + 940
3   libsystem_platform.dylib            0x000000018ca10624 _sigtramp + 56
4   Electron Framework …
```

fix: crash on macOS dialog after `window-all-closed`

---

shell/browser/api/electron_api_base_window.cc
shell/browser/api/electron_api_base_window.h
shell/browser/native_window.cc
shell/browser/native_window.h
shell/browser/native_window_observer.h
shell/common/gin_converters/gfx_converter.cc
shell/common/gin_converters/gfx_converter.h

Small cleanup to pass `gfx::ResizeEdge` by value. It's [an enum class](https://chromium.googlesource.com/chromium/src/+/main/ui/gfx/geometry/resize_utils.h#17), so it's simpler to pass it by value than by reference.
Notes: none.

refactor: pass `gfx::ResizeEdge` by value

---

shell/browser/api/electron_api_web_contents.cc

Closes https://github.com/electron/electron/issues/46921.
Ensures `mediaSize` defaults to A4 when no `mediaSize` is passed, fixing the following:
```
[83233:0505/195335.950737:ERROR:components/device_event_log/device_event_log_impl.cc:202] [19:53:35.950] Printer: print_view_manager_base.cc:384 Printer settings invalid for _127_0_0_1 (destination type kLocal): content size is empty; page size is empty; printable area is empty
```
Notes: Fixed an issue where `webContents.print` did not work as expected when `mediaSize` was not passed.

fix: printing when no `mediaSize` specified

---

shell/browser/native_window.cc
shell/browser/native_window.h
spec/api-browser-window-spec.ts

Use upstream's `WidgetDelegate::SetAccessibleTitle()` instead of implementing it ourselves. We were previously doing it ourselves because our code predated the [May 2020 addition](https://chromium-review.googlesource.com/c/chromium/src/+/2218688)  of `SetAccessibleTitle()`.
(Upstream implementation: [SetAccessibleTitle()](https://chromium.googlesource.com/chromium/src/+/a034dd2e96b502a09f8d6dbd26897858e9beea9a/ui/views/widget/widget_delegate.cc#406), [GetAccessibleWindowTitle()](https://chromium.googlesource.com/chromium/src/+/a034dd2e96b502a09f8d6dbd26897858e9beea9a/ui/views/widget/widget_delegate.cc#127))
Notes: none.

refactor: use `WidgetDelegate::SetAccessibleTitle()`

---

script/release/get-url-hash.ts

Conversation here: https://electronhq.slack.com/archives/CC80G2R6H/p1745119875976869?thread_ts=1745000386.480629&cid=CC80G2R6H. Following some modernizations to the electron/hasher repo, this PR moves us to use the new Azure function for the artifact hasher during releases.
The corresponding env variable has also been updated in Sudowoodo.
_NOTE:_ This is targeting all active release branches, but we should merge into main and ensure the new function works with nightly before actually merging the backports. Because we're using a new variable for the new function and haven't removed the variable for the old key/function, upload will still work for other release branches in the meantime.
Notes: none

build: move release script to new hasher function

---

spec/api-browser-window-spec.ts

Enable `hasShadow` BrowserWindow tests on Linux.
Since this feature is supported on Linux, we should run the tests there too.
Notes: none.

test: enable `hasShadow` tests on Linux

---

shell/browser/native_window_views.cc
shell/browser/native_window_views_win.cc

Prefer to use stable `views::Widget` API instead of using its `native_widget_private()` getter directly. There are a handful of places where `views::Widget` has simple wrapper functions around `native_widget_private()`.
Example:
`views::Widget::AreScreenshotsAllowed()` [is implemented as a simple wrapper](https://chromium.googlesource.com/chromium/src/+/main/ui/views/widget/widget.cc#2429) around `NativePrivateWidget`:
```c++
bool Widget::AreScreenshotsAllowed() {
return native_widget_ ? native_widget_->AreScreenshotsAllowed() : true;
}
```
So we don't have to call `native_widget_private()`:
```diff
-  widget()->native_widget_private()->AreScreenshotsAllowed()
+  widget()->AreScreenshotsAllowed()
```
Notes: none.

refactor: reduce use of `NativeWidgetPrivate`

---

script/release/get-url-hash.ts

Follow up to #46989, updates the value returned by `getUrlHash` to handle an object being returned, as opposed to only the hash string value
Notes: none

build: update hasher return value

---

shell/browser/api/electron_api_web_contents.cc
shell/browser/electron_browser_context.cc
shell/browser/electron_download_manager_delegate.cc
shell/browser/net/electron_url_loader_factory.cc
shell/browser/ui/cocoa/electron_touch_bar.mm
shell/common/api/electron_api_url_loader.cc
shell/common/gin_converters/blink_converter.cc
shell/common/gin_helper/persistent_dictionary.h

A #46939 followup to use helper function [`Dictionary::ValueOrDefault()`](https://github.com/electron/electron/blob/c16ea8d54edc58f9ccd1ab9875a1c49ccc81e8e2/shell/common/gin_helper/dictionary.h#L70) in a few more places.
These are all small cleanups to improve conciseness & readability. Here's an example:
```diff
-  int maxValue = 100;
-  int minValue = 0;
-  int value = 50;
-  settings.Get("minValue", &minValue);
-  settings.Get("maxValue", &maxValue);
-  settings.Get("value", &value);
-  item.slider.minValue = minValue;
-  item.slider.maxValue = maxValue;
-  item.slider.doubleValue = value;
+  item.slider.minValue = settings.ValueOrDefault("minValue", 0);
+  item.slider.maxValue = settings.ValueOrDefault("maxValue", 100);
+  item.slider.doubleValue = settings.ValueOrDefault("value", …
```

refactor: use `gin_helper::Dictionary::ValueOrDefault()`

---

docs/api/command-line-switches.md
shell/common/node_bindings.cc

Allow `--experimental-network-inspection` to be used in NODE_OPTIONS.
Includes https://github.com/nodejs/node/pull/56805
cc @deepak1556 
Notes: Added support for node option `--experimental-network-inspection`

feat: add support for `--experimental-network-inspection`

---

shell/browser/ui/win/electron_desktop_window_tree_host_win.cc
shell/browser/ui/win/electron_desktop_window_tree_host_win.h

Fixes https://github.com/electron/electron/issues/45990
We previously made a change in https://github.com/electron/electron/pull/45868 to fix content protection being lost on hide and re-show. However, this cause a breaking change where protected windows were made opaque black instead of being hidden as before. This overrides relevant methods in ElectronDesktopWindowTreeHostWin to restore the previous behavior. without regressing the original issue.
Notes: Restored previous window-hiding behavior of `win.setContentProtected()` on Windows.

fix: restore previous Windows screenshotting

---

docs/api/menu-item.md
docs/api/menu.md
shell/browser/ui/cocoa/electron_menu_controller.mm

Closes #34621 
Adds sublabel functionality for macOS >= 14.4.
Tests and docs updates to come
Notes: added sublabel functionality for menus on macOS >= 14.4
@deepak1556 @VerteDinde

feat: enable secondary label for macOS menu

---

shell/browser/native_window_views.cc
shell/browser/ui/win/electron_desktop_window_tree_host_win.cc
shell/browser/ui/win/electron_desktop_window_tree_host_win.h

Refs CL:6245732
Closes https://github.com/electron/electron/issues/46924
Closes https://github.com/electron/electron/issues/35362
Closes https://github.com/electron/electron/issues/45625
Fixes an issue where the window flickers with either a light or dark color before loading the desired background color if one is set. This happened mostly as a result of transparency-related handling.
Notes: Fixed an issue where the window flickers with either a light or dark color before loading the desired background color.

fix: white window flicker on window creation

---

shell/browser/ui/views/root_view.cc

Use the [`WebInputEvent::kKeyModifiers` mask](https://chromium.googlesource.com/chromium/src/+blame/c00c5a0ea70368a64d703c638e6b539afd869ed8/third_party/blink/public/common/input/web_input_event.h#159) to determine whether an event is using only the alt modifier.
We probably didn't use this in `IsAltModifier()` because that function was written two years before the KeyModifiers mask was added upstream in 98ec378a. :smile_cat: 
In the same way that we previously added code to handle `kCapsLockOn` and `kNumLockOn` (81283db2da6c95a316d9345ae20fc0c1ac88d69c), this change also fixes an unreported edge case of not honoring menuitem accelerators when the scroll lock is on.
Notes: none.

refactor: use kKeyModifiers in IsAltModifier()

---

spec/api-desktop-capturer-spec.ts

Don't nest `it` calls in desktopCapturer specs. The nested call is [treated as a no-op by Mocha](https://github.com/mochajs/mocha/issues/4525#issuecomment-1930880132).
Notes: none.

test: fix desktopCapturer mocha syntax

---

shell/browser/api/electron_api_base_window.cc
shell/browser/api/electron_api_base_window.h
shell/browser/native_window.h
shell/common/gin_helper/trackable_object.h

Does what it says on the tin: make `TrackableObject::weak_map_id()` and `BaseWindow::GetID()` inline and constexpr.
Notes: none.

refactor: make TrackableObject::weak_map_id() constexpr

---

shell/browser/native_window_views.cc
shell/browser/ui/views/global_menu_bar_x11.cc
shell/browser/ui/views/global_menu_bar_x11.h

Remove a little bit of unnecessary coupling between `NativeWindowViews` and `GlobalMenuBarX11`. The latter doesn't need to know about the former:
- Remove the unused field `GlobalMenuBarX11::window_`.
- The `NativeWindowViews*` passed into the `GlobalMenuBarX11` constructor is only used to get the `gfx::AcceleratedWidget`, so skip the middleman and pass in the accelerated widget instead.
- Remove `#include` and forward declarations of `NativeWindowViews`
Notes: none.

refactor: decouple NativeWindowViews and GlobalMenuBarX11

---

docs/api/screen.md

Adds some additional context on DIP vs screen points. Referenced https://learn.microsoft.com/en-us/windows/apps/develop/win2d/dpi-and-dips to write the content, but tried to make the wording platform-independent.
cc @codebytere since this came up in an API Working Group meeting a while back.
Notes: none

docs: add note on DIP and DPI

---

shell/browser/ui/gtk/menu_util.cc
shell/browser/ui/gtk/menu_util.h

GTK >= 3.90.0 removed support for menuitem icons. When Electron is built with GTK >= 3.90.0, our code builds these icons and then throws them away unused. Instead, let's just not build them.
Our `gtk_util::GdkPixbufFromSkBitmap()` utility uses BGRAToRGBA and is expensive to call.
Notes: none.

perf: don't create unused menuitem icons

---

shell/browser/api/electron_api_base_window.cc
shell/browser/native_window.cc
shell/browser/native_window.h

Part 3 in a short series of PRs to reduce public use of `NativeWindow::widget()` so that it can be made into a protected method. See [Part 1](https://github.com/electron/electron/pull/47126) for discussion of why I want to do that.
---
This PR is a simple [demeter](https://en.wikipedia.org/wiki/Law_of_Demeter#In_object-oriented_programming) refactor to decouple `api::BaseWindow::SetShape()` from knowledge of `views::Widget`. Instead, it just  lets `NativeWindow` handle it by calling the new method `NativeWindow::SetShape()`.
Notes: none.

refactor: add NativeWindow::SetShape()

---

shell/browser/native_window.cc
shell/browser/native_window_views.cc

A minor cleanup I came across while working on other NativeWindow changes:
`NativeWindow::GetWidget()` is a virtual method that just calls the non-virtual inlined getter `NativeWindow::widget()` anyway, so `NativeWidow`'s code should skip the middleman and call the latter directly.
Notes: none.

refactor: NativeWindows should prefer widget() over GetWidget() for internal use

---

.github/actions/install-build-tools/action.yml

Release builds have been seeing the error:
```
python3_bin_reldir.txt not found. need to initialize depot_tools by
running gclient, update_depot_tools or ensure_bootstrap.
``` 
(eg https://github.com/electron/electron/actions/runs/15114398562/job/42508751795#step:23:44284)
This PR ensures that python is setup for proper use from depot_tools which should eliminate this issue.
Notes: none

build: update_depot_tools on initial install

---

shell/browser/api/electron_api_web_contents.cc
shell/browser/native_window.h
shell/browser/native_window_views.cc
shell/browser/native_window_views.h

this was already present on macOS; use in NativeWindowViews too
Part 4 in a short series of PRs to reduce public use of `NativeWindow::widget()` so that it can be made into a protected method. See [Part 1](https://github.com/electron/electron/pull/47126) for discussion of why I want to do that.
---
This PR adds `NativeWindow::IsActive()` on all platforms, when previously it existed only on macOS builds. `WebContents::ReadyToCommitNavigation()` can use this method instead of calling `NativeWindow::widget()->IsActive()` on Windows and Linux.
Notes: none.

refactor: add NativeWindow::IsActive()

---

shell/browser/native_window.h

Follow the base/containers/README.md advice that "Chromium code should always use `base::circular_deque` or `base::queue` in preference to `std::deque` or `std::queue` due to memory usage and platform variation."
Notes: none.

refactor: make `NativeWindow::pending_transitions_` a `base::queue`

---

patches/chromium/.patches
patches/chromium/cherry-pick-295a4a1b14b8.patch
patches/chromium/cherry-pick-c3568ceda9d8.patch

<details>
<summary>electron/security#674 - 295a4a1b14b8 from chromium</summary>
Drop transitive trust from transports
Untrusted nodes could reflect a broker initiated transport back to
a broker. This ultimately allows for handle leaks if the reflected
transport was later used to deserialize another transport containing
handles in the broker.
This CL addresses this along several axes:
1. untrusted transports cannot return new links to brokers.
2. process trustiness on Windows is propagated when a transport is
deserialized from a transport.
Windows has a special additional level of trustiness associated with
mojo peers via the is_remote_process_untrusted attribute (the
MOJO_SEND_INVITATION_FLAG_UNTRUSTED_PROCESS in invitations). This
affects how handles are sent between processes. This was …

chore: cherry-pick 2 changes from 2-M136

---

patches/v8/.patches
patches/v8/cherry-pick-22ac8acf3508.patch

<details>
<summary>electron/security#672 - 22ac8acf3508 from v8</summary>
Make F.p.caller return null when called from Wasm
Returning the calling Wasm function isn't generally possible when
that function isn't exported; skipping that and returning something
else would be either surprising or plain incorrect.
Fixed: 403364367
Change-Id: I2406a0abe15a8d66da06302e946ce653aaff259d
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/6362435
Commit-Queue: Toon Verwaest <verwaest@chromium.org>
Auto-Submit: Jakob Kummerow <jkummerow@chromium.org>
Cr-Commit-Position: refs/heads/main@{#99296}
</details>
Notes:
* Security: backported fix for 403364367.

chore: cherry-pick 1 changes from 0-M136

---

spec/esm-spec.ts

Ran into this when running these tests under VS Code, `FORCE_COLOR` would be set which caused ANSI escape codes to be present in the output and fail the test.  Node.js provides a nice little util for exactly this situation.
Notes: none

test: strip color output in ESM spec

---

shell/browser/api/electron_api_power_monitor_mac.mm
shell/browser/api/electron_api_power_monitor_win.cc

Closes https://github.com/electron/electron/issues/44252.
'suspend'/'resume' handling was added initially to `electron_api_power_monitor_{win|mac}` prior to `base::PowerSuspendObserver` being added upstream - these events are now emitted via `OnSuspend` and `OnResume` and the extra handling causes them to be emitted twice. On Windows, for example, resuming after sleeping shows:
```
The system is resuming
The system is resuming
```
Notes: Fixed an issue where the 'suspend' and 'resume' events could be emitted in duplicate.

fix: remove extra 'suspend'/'resume' handling from `powerMonitor`

---

BUILD.gn
docs/api/base-window.md
docs/api/browser-window.md
docs/api/screen.md
shell/browser/api/electron_api_screen.cc
shell/browser/api/electron_api_screen.h
shell/browser/linux/x11_util.cc
shell/browser/linux/x11_util.h
shell/browser/native_window_views.cc

Backport of #46211
Notes: Added support for `screen.dipToScreenPoint(point)` and `screen.screenToDipPoint(point)` on Linux X11.

feat: support dip <-> screen conversion on Linux

---

shell/browser/net/resolve_proxy_helper.h
shell/common/crash_keys.cc

A companion PR to https://github.com/electron/electron/pull/47157 to follow [Chromium's usage advice](https://chromium.googlesource.com/chromium/src/+/main/base/containers/README.md#deque-usage-advice).
That PR migrated `std::queue` use; this one migrates `std::deque`:
> Chromium code should always use `base::circular_deque` or `base::queue` in preference to `std::deque` or `std::queue` due to memory usage and platform variation.
>
> The `base::circular_deque` implementation (and the `base::queue` which uses it) provide performance consistent across platforms that better matches most programmer‘s expectations on performance (it doesn’t waste as much space as libc++ and doesn't do as many heap allocations as MSVC). It also generates less code than std::queue: using it across the code base …

refactor: prefer `base::circular_deque` over `std::deque`

---

shell/browser/native_window.cc
shell/browser/native_window.h

Companion refactor to https://github.com/electron/electron/pull/47156 that makes more fields const. This PR:
- Makes `NativeWindow::enable_larger_than_screen_` const
- Makes `NativeWindow::transparent_` const
- Annotates `NativeWindow::enable_larger_than_screen()` as `[[nodiscard]]`
- Annotates `NativeWindow::transparent()` as `[[nodiscard]]`
- Uses in-class member initialization for `NativeWindow::widget_`
Notes: none.

refactor: make `NativeWindow::transparent_` const

---

shell/browser/api/electron_api_menu_views.cc
shell/browser/native_window_views.cc
shell/browser/ui/electron_desktop_window_tree_host_linux.cc
shell/browser/ui/electron_desktop_window_tree_host_linux.h
shell/browser/ui/win/electron_desktop_native_widget_aura.cc
shell/browser/ui/win/electron_desktop_native_widget_aura.h
shell/browser/ui/win/electron_desktop_window_tree_host_win.cc
shell/browser/ui/win/electron_desktop_window_tree_host_win.h

Part 5 in a short series of PRs to reduce public use of `NativeWindow::widget()` so that it can be made into a protected method. See [Part 1](https://github.com/electron/electron/pull/47126) for discussion of why I want to do that.
---
In this PR, we pass the `views::Widget*` into the constructor methods of our bespoke TreeHosts and NativeWidgets instead of calling `NativeWindow::widget()` in those methods.
Notes: none.

refactor: pass views::Widget* into constructors of our TreeHosts and NativeWidgets

---

.github/actions/install-build-tools/action.yml

- Followup to #47160.  Unfortunately that PR did not fix the issue as it turns out the issue is caused by depot_tools being preinstalled on the widows runner image.  This PR fixes the underlying issue by properly setting the path to the depot_tools installed as part of the build which will then resolve this error:
```
python3_bin_reldir.txt not found. need to initialize depot_tools by
running gclient, update_depot_tools or ensure_bootstrap.
```
Verified by building ffmpeg for a testing build here: https://github.com/electron/electron/actions/runs/15171656549/job/42663073571?pr=47194#step:23:43892
Once this PR makes it way through all supported branches, we can remove depot_tools from the windows runner image by reapplying https://github.com/electron/infra/pull/120
Notes: none

build: fix depot tool pathing on Windows

---

package.json
yarn.lock

The semver major bump is causing an ESM import error on release builds, reverting this to get releases back up and running and then fixing forward.
This reverts commit 517f5c15b957a43702bd0cc5009440d5a0a339d6.
Notes: none

build: revert bump @octokit/rest from 20.1.1 to 21.1.1 

---

shell/browser/native_window.cc
shell/browser/native_window_mac.mm
shell/browser/native_window_views.cc
shell/common/api/electron_api_native_image.cc
shell/common/gin_helper/dictionary.h

Manually backport #46939 to 35-x-y. See that PR for details.
Notes: none.

refactor: add `gin_helper::Dictionary::ValueOrDefault()` (35-x-y)

---

.github/actions/build-electron/action.yml
.github/problem-matchers/clang.json

Adds [a GitHub actions problem matcher](https://github.com/actions/toolkit/blob/main/docs/problem-matchers.md) to turn warnings/errors in the build output into warning/error annotations on the workflow runs so they're more discoverable.
See https://github.com/electron/electron/actions/runs/15127447507 for an example run with annotations on the summary page (scroll to the bottom, but links won't work since I removed the build error commit), or see the image below. Unfortunately there's no deduplication of annotations (long standing issue) so we get a lot of duplicate ones across our various build configurations. On each individual jobs the annotations are at the top of the page, collapsed by default.
~~Blocked by https://github.com/actions/runner/pull/3802 as the relative paths in our …

ci: add problem matcher for clang output

---

shell/browser/native_window.cc
shell/browser/native_window.h
shell/browser/native_window_mac.mm
shell/browser/native_window_views.cc

Continuing some low-hanging-fruit refactor work to constify some read-only fields in `NativeWindow`.
I'm constifying these fields to guarantee that the assumptions our code's already making are safe assumptions. For example, `NativeWindow::has_frame_` is used to decide which subclass of `views::NonClientFrameView` to instantiate in `NativeWindowViews::CreateNonClientFrameView()` and then later to safely downcast it in `NativeWindowViews::GetClientFrameViewLinux()`. So we definitely don't want `has_frame_` changing during runtime :boom: 
Notes: none.

refactor: make `NativeWindow::has_frame_` const

---

shell/browser/native_window_views.cc

In `NativeWindowViews::SetAlwaysOnTop()`, we want to check & see if the `level` string argument exists in a set of strings that is known at compile time. To hold those strings, use a constexpr `fixed_flat_set<std::string_view>` instead of a `std::vector<std::string>`.
Notes: none.

refactor: use `base::fixed_flat_set` in `NativeWindowViews::SetAlwaysOnTop()`

---

shell/browser/native_window.h

Manually backport #47157 to 35-x-y. See that PR for details.
Notes: none.

refactor: make `NativeWindow::pending_transitions_` a `base::queue` (35-x-y)

---

docs/api/menu-item.md
lib/browser/api/menu-item-roles.ts
lib/browser/api/menu-item.ts
lib/browser/api/menu.ts
shell/browser/api/electron_api_menu.cc
shell/browser/api/electron_api_menu.h
shell/browser/ui/cocoa/electron_menu_controller.mm
shell/browser/ui/electron_menu_model.cc
shell/browser/ui/electron_menu_model.h
typings/internal-ambient.d.ts
typings/internal-electron.d.ts

Closes #42960
This PR adds two new macOS specific menu item roles:
* [`palette`](https://developer.apple.com/documentation/appkit/nsmenu/presentationstyle-swift.enum/palette): A menu presentation style where items to display align horizontally.
* [`header`](https://developer.apple.com/documentation/appkit/nsmenuitem/sectionheaderwithtitle:): A menu item representing a section header for a logical grouping of menu commands.
``` js
const reactions = []
for (let i = 1; i <= 4; ++i) {
reactions.push({
label: '',
icon: nativeImage.createFromPath(path.resolve(__dirname, '..', `reaction-${i}@2x.png`)),
click: () => console.log('Clicked reaction!')
})
}
const paletteMenu = Menu.buildFromTemplate(reactions)
const contextMenu = Menu.buildFromTemplate([
{
label: 'Reactions',
role: 'header',
},
{ …
```

feat: add menu item role `palette` and `header`

---

patches/chromium/chore_modify_chromium_handling_of_mouse_events.patch
patches/chromium/fix_activate_background_material_on_windows.patch
patches/chromium/fix_take_snapped_status_into_account_when_showing_a_window.patch

Manually backport #46657 to 35-x-y. See that PR for details.
Notes: Fixed an issue where the `backgroundMaterial` feature did not work in a frameless window on initial window creation.

fix: `backgroundMaterial` on initial activate (35-x-y)

---

shell/browser/api/electron_api_web_contents.cc
shell/browser/ui/inspectable_web_contents.cc
shell/browser/ui/inspectable_web_contents.h

Debug https://github.com/electron/electron/issues/47187 by:
1. Adding [SEQUENCE_CHECKER](https://source.chromium.org/chromium/chromium/src/+/main:base/sequence_checker.h) for `InspectableWebContents` and `DCHECK_CALLED_ON_VALID_SEQUENCE` to `InspectableWebContents::LoadCompleted`
2. Adding `DCHECK(!owner_window_.WasInvalidated())` to ensure window of the webContents holding the devtools is valid
3. Adding `DCHECK_EQ(handle->owner_window(), nullptr)` to ensure the devtools does not have a owner window
Notes: none

chore: debug crash on DevTools SetOwnerWindow

---

docs/fiddles/.eslintrc.json

Adds an ESLint config that matches what we lint for in `@electron/lint-roller` for the `docs/fiddles` samples.
cc @dsanders11 
notes: none

chore: add .eslintrc.json for `docs/fiddles`

---

package.json
yarn.lock

`eslint-plugin-standard` is deprecated on npm and the deprecation notice says we can remove it with the version of `eslint-config-standard` we're using.
> standard 16.0.0 and eslint-config-standard 16.0.0 no longer require the eslint-plugin-standard package. You can remove it from your dependencies with 'npm rm eslint-plugin-standard'. More info here: https://github.com/standard/standard/issues/1316
Notes: none

build: remove unnecessary eslint-plugin-standard package

---

docs/api/base-window.md
docs/api/browser-window.md
shell/browser/api/electron_api_base_window.cc
spec/api-browser-window-spec.ts

Expose a function to allow developers to check current content protection status. 
Notes: Exposed `win.isContentProtected()` to allow developers to check window protection status.

feat: expose `win.isContentProtected()`

---

docs/api/client-request.md
lib/common/api/net-client-request.ts
shell/common/api/electron_api_url_loader.cc
spec/api-net-spec.ts
typings/internal-ambient.d.ts

Add the priority and priorityIncremental options to customize the Priority header of requests sent by net.request.
Currently all requests sent by net.request have a priority header with value `u=4, i`, this maybe unexpected. We want it fully customizable and match the Chrome exactly if possible.
Close #46680
Notes: Added the priority and priorityIncremental options to net.request()

feat: [net] add "priority" option to net.request

---

script/patches-stats.mjs

Fixing this as now that they're uploading I can see we need these to be logged as gauge metrics, otherwise showing a monthly view will add up the counts on any given day, which is not what we want. You can manually update the metric type on DataDog's dashboard so I've done that to fix it on that side for now, but we should upload new datapoints as the correct type.
Notes: none

ci: change patches stats DataDog metric type to gauge

---

docs/api/web-contents.md

Refs https://github.com/electron/electron/issues/47046
Refs https://github.com/electron/electron/issues/32178
Corrects docs stating incorrectly that 'select-bluetooth-device' isn't necessarily required to retrieve devices.
Notes: none

docs: correct 'select-bluetooth-device' requirement

---

shell/browser/api/electron_api_view.cc
spec/api-web-contents-view-spec.ts

Closes https://github.com/electron/electron/issues/47074
Notes: Fixed `addChildView()` crashes when adding a closed WebContentsView

fix: addChildView() crashes when adding a closed WebContentsView

---

patches/node/fix_do_not_resolve_electron_entrypoints.patch
patches/node/fix_expose_the_built-in_electron_module_via_the_esm_loader.patch
patches/node/fix_lazyload_fs_in_esm_loaders_to_apply_asar_patches.patch

Mirrors a modification in the ESM patch that avoids loading source for the `electron` module to the same (synchronous) code used for CJS interoperability. This code path can only be triggered in packaged applications.
---
It was an interesting journey figuring out the root cause for this one.
There exists two flows in the ESM loader: asynchronous (ESM) and synchronous (CJS). The second flow enables CJS modules to load ESM modules and vice versa. When a CJS module loads an ESM module, its `import`s are loaded synchronously for compatibility.
We [patch](https://github.com/electron/electron/blob/c2ab63f6d7091f9412362136d3ed66a563d33082/patches/node/fix_do_not_resolve_electron_entrypoints.patch#L11-L20) the ESM loader to avoid loading source code for the `electron` module (because there is …

fix: do not load source for `electron` module in ESM loader synchronous flow

---

patches/v8/.patches
patches/v8/cherry-pick-7bc0a67ebfbf.patch

<details>
<summary>electron/security#675 - 7bc0a67ebfbf from v8</summary>
[turbofan] Weaken alias analysis in store-store elimination
Bug: 420636529
Change-Id: I7c5a8f47960708cecbb27d811eedc7f754933deb
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/6594051
Reviewed-by: Shu-yu Guo <syg@chromium.org>
Auto-Submit: Leszek Swirski <leszeks@chromium.org>
Commit-Queue: Leszek Swirski <leszeks@chromium.org>
Cr-Commit-Position: refs/heads/main@{#100530}
</details>
Notes:
* Security: backported fix for CVE-2025-5419.

chore: cherry-pick 1 changes from 1-M137

---

docs/api/web-contents.md
shell/browser/api/electron_api_web_contents.cc
shell/browser/api/electron_api_web_contents.h
shell/common/gin_converters/blink_converter.cc
shell/common/gin_converters/blink_converter.h
spec/api-web-contents-spec.ts
spec/fixtures/pages/mouse-events.html

Closes https://github.com/electron/electron/issues/15646.
Refs CL:6266792
Adds `before-mouse-event` to allow intercepting and preventing mouse events in WebContents.
Notes: Added `before-mouse-event` to allow intercepting and preventing mouse events in WebContents.

feat: allow intercepting mouse events

---

patches/v8/.patches
patches/v8/cherry-pick-45eb42cd398e.patch

[turbofan] Convert Smi to Word64 using zero extension
... when a known type range contains only positive values.
Bug: 420637585
Change-Id: I8d9bb3f2fe2e5268e1659bb4ea7bbf97bfb52288
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/6594731
Cr-Commit-Position: refs/heads/main@{#100538}
Notes: Backported fix for 420637585.

chore: cherry-pick 45eb42cd398e from v8

---

docs/api/environment-variables.md

`#L13` doesn't work on the website and isn't tied to a particular heading so it's a moving target.
(https://github.com/electron/electron/blob/main/docs/development/testing.md)
Notes: none

docs: update link to `runAsNode` fuse

---

README.md

Refs https://github.com/electron/.permissions/pull/293
The repo was renamed to `minimal-repro` and is no longer intended to be used as a way to start new projects (see PR above).
Since we really want bugs in `electron/electron` to be reported with a Fiddle gist instead of a standalone repo (makes reproducing and bisecting sooo much easier and safer!), I removed the repo from the README completely instead of mentioning it as an issue reproduction starting point.
CC @yangannyx
Notes: none

docs: remove `electron-quick-start` from README

---

patches/chromium/printing.patch

Closes https://github.com/electron/electron/issues/47272.
Fixes an issue where printing PDFs with `webContents.print({ silent: true })` would fail. This happened after the switch to OOP owing to [this code](https://chromium.googlesource.com/chromium/src/+/70c3e84ee73484ee2ef383e8cc0e5b1f32b106e3/chrome/browser/printing/print_view_manager_base.cc#654) which tried to composite any modifiable jobs. Under non-silent circumstances, calls to get settings from the user correctly set any non-html jobs to non-modifiable, but this logic was bypassed in silent printing and so PDF jobs were mistakenly marked modifiable.
Notes: Fixed an issue where printing PDFs with `webContents.print({ silent: true })` would fail.

fix: silent printing of PDFs with `webContents.print`

---

shell/browser/api/electron_api_web_contents.cc

Refs https://github.com/electron/electron/issues/47272
Partially fixes an issue with printing a PDF via `webContents.print()` where the callback would not be called and the print dialog sometimes not show. This was happening because we were not correctly using the `PrintViewManager` created for the PDF View Plugin's `webContents`.
Notes: Partially fixes an issue with printing a PDF via `webContents.print()` where the callback would not be called.

fix: printing PDF via `webContents.print()`

---

.github/workflows/audit-branch-ci.yml

We've seen these pop up but we don't want them to trip this audit since they're transient errors. Also removes a couple of debugging lines that were inadvertently left in previously.
Notes: none

ci: ignore network-related error annotations in audit

---

shell/browser/api/electron_api_session.cc

Speculative fix for https://github.com/electron/electron/issues/46671 - ran into it again recently.
Notes: Fixed a potential crash using `session.clearData` in some circumstances.

fix: rework lifetime mgmt of `ClearDataTask`/`ClearDataOperation`

---

.github/workflows/audit-branch-ci.yml

Don't send the Slack message on the workflow itself failing (we've seen it happen due to 5XX errors from GitHub servers or general GHA issues), ignores failures of the workflow itself, fixes some syntax errors which slipped in, and updates the Slack message to only send when run on `main` so we can more easily test this on branches without spamming ourselves
Notes: none

ci: fix up branch CI audit workflow

---

docs/api/command-line-switches.md
shell/common/node_bindings.cc
spec/api-utility-process-spec.ts
spec/fixtures/api/utility-process/navigator.js

With Node.js v21 starting to support global navigator object, applications that load 3-rd party plugins need to provide a migration timeline for these plugins that relied on the presence of navigator object to detect web environments which would not be the case anymore.
https://github.com/nodejs/node/commit/309c71ae38e0f29fd3d563bfc2766f4aa94eb0ad
Notes: add support for `--no-experimental-global-navigator` flag

feat: add support for --no-experimental-global-navigator

---

shell/browser/api/electron_api_dialog.cc
shell/browser/api/electron_api_web_contents.cc
shell/browser/ui/file_dialog.h
shell/browser/ui/file_dialog_linux.cc
shell/browser/ui/file_dialog_mac.mm
shell/browser/ui/file_dialog_win.cc

A small side refactor to [prefer return values to output parameters](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#f20-for-out-output-values-prefer-return-values-to-output-parameters) in `ShowSaveDialogSync()`.
```diff
-  bool ShowSaveDialogSync(const DialogSettings& settings, base::FilePath* path);
+  std::optional<base::FilePath> ShowSaveDialogSync(const DialogSettings& settings);
```
Notes: none

refactor: have ShowSaveDialogSync() return a std::optional<base::FilePath>

---

docs/breaking-changes.md
shell/services/node/node_service.cc
spec/api-utility-process-spec.ts
spec/fixtures/api/utility-process/no-js-after-exit.js

Fixes https://github.com/electron/electron/issues/44174
Relies on the `node::DefaultProcessExitHandler` to ensure termination of the process after performing our own cleanup related to the utility process.
Notes: fix utilityProcess running user script after process.exit is called

fix: utilityProcess running user script after process.exit is called

---

.github/workflows/audit-branch-ci.yml

Follow-up to #47404 which was a little too zealous in quieting the Slack messages and now they're not sending at all. The `always()` condition is needed for the rest of the conditional to be evaluated when the audit fails.
Notes: none

ci: fix sending Slack message in CI audit workflow

---

shell/browser/api/electron_api_utility_process.cc

Closes https://github.com/electron/electron/issues/47515.
Previously we were opening a handle to `/dev/null` and never remapping it, so it would be leaked as we never explicitly closed it. This fixes that.
Upstream in this case just called [`_exit`](https://source.chromium.org/chromium/chromium/src/+/main:base/process/launch_posix.cc;l=612;bpv=0;bpt=1) which terminates the process and closes open file descriptors belonging to the process, which s why they didn't have this issue.
Notes: Fixed an issue where utility processes could leak file handles.

fix: ensure `/dev/null` fd is closed on failure

---

build/args/all.gn

Bumps the NMV to [139](https://github.com/nodejs/node/pull/58779) for Electron 38
Notes: none

build: update NMV to 139

---

shell/renderer/api/electron_api_context_bridge.cc

A small cleanup/correctness PR for ContextBridge, which accidentally put its private lookup keys in a public namespace. 
This PR moves them into a private namespace and changes their type to `constexpr std::string_view`.
Notes: none.

refactor: make context bridge's private keys hidden, constexpr string_views

---

shell/browser/browser_win.cc

`browser_win.cc` has a lot of redundant declarations of Windows registry keys. This PR makes symbolic constants for them and uses those instead. The symbolic constants are declared as constexpr [base::wcstring_view](https://chromium.googlesource.com/chromium/src/base/+/refs/heads/main/strings/cstring_view.h) to avoid the need for `std::wstring` temporaries.
Notes: none.

refactor: extract-constant static Windows registry keys in Browser code

---

shell/browser/extensions/api/tabs/tabs_api.cc

Upstream updated the function to use `base::MakeFixedFlatSet()`. This PR copy-pastes the upstream code verbatim.
Notes: none.

refactor: sync IsKillURL() with upstream impl in extension_tab_util.cc

---

shell/browser/ui/webui/accessibility_ui.cc

Copy upstream change from https://chromium-review.googlesource.com/c/chromium/src/+/6462552 to our copy of `
RecursiveDumpAXPlatformNodeAsString()` in `shell/browser/ui/webui/accessibility_ui.cc`.
Notes: none.

fix: Reland "[accessibility] Platform node lifetime cleanups"

---

shell/browser/native_window.cc
shell/browser/native_window_mac.mm
shell/browser/native_window_views.cc

Reduce the scope of temporaries when getting dictionary values in NativeWindows. This leaves fewer temporaries laying around.
Basically, it's this kind of change again & again:
```diff
-  std::string foo;
-  if (options.Get(options::kSomething, &foo)) {
-    DoSomething(foo);
-  }
+  if (std::string val; options.Get(options::kSomething, &val))
+    DoSomething(val);
```
Notes: none.

refactor: reduce scope of temporaries when getting dictionary values

---

docs/api/structures/usb-device.md
shell/browser/usb/usb_chooser_context.cc

Similar vein as https://github.com/electron/electron/pull/47391 - we should expose the full property set of [`USBDevice`] per spec.
Notes: Added support for `USBDevice.configurations`.

feat: support complete WebUSB device properties

---

script/release/bin/publish-to-npm.ts

This adds a helper file that makes it easier for tools like `node-abi` to determine the ABI version of an otherwise unknown package. `node-abi` is a pretty massive source of annoyance for folks, even for seasoned Electron App developers it's an annoying thing you need to keep ensuring you update. Package managers don't make it easy, so instead to mitigate this as much as possible I'm proposing we write this file to disk, and then in `node-abi` if we are resolving a version we **don't recognize** we try to find this file on disk for a matching electron version. If it matches, and it exists, we can serve it and app developers don't need to do any package manager shenanigans.
Notes: Added `abi_version` file to the npm package

build: write abi version to published npm package

---

shell/browser/api/electron_api_desktop_capturer.cc

Refs CL:5783826
Closes https://github.com/electron/electron/issues/47591
Fixes a crash when calling `desktopCapturer.getSources` with an empty thumbnail size.
`DesktopMediaListBase` now calls `Refresh(false)` after dispatching `DesktopMediaListObserver::OnDelegatedSourceListSelection`, so it's important not to call `DesktopCapturer::HandleSuccess` (which deallocates the `DesktopMediaList`) synchronously from `OnDelegatedSourceListSelection`.
Notes: Fixed a crash when calling `desktopCapturer.getSources` with an empty thumbnail size.

fix: crash on source capture with empty thumbnail size

---

shell/browser/api/electron_api_web_contents.cc
shell/common/platform_util_linux.cc

Small cleanup that I came across while working on something else.
In a handful of cases, we're instantiating a `std::string` when a cheaper `std::string_view` will do. This PR fixes that.
Notes: none.

refactor: avoid a few unnecessary strings

---

shell/browser/native_window_views.h
shell/browser/native_window_views_win.cc

Closes https://github.com/electron/electron/issues/47626.
Refs https://github.com/electron/electron/pull/47285#issuecomment-3012764206.
Fixes an issue where a window's accent color didn't reflect system settings without restart.
After this PR:
* System Accent Disabled and `accentColor: undefined` => ❌  Frame does NOT have accent color
* System Accent Disabled and `accentColor: true` => ✅ Frame has accent color
* System Accent Disabled and `accentColor: #rrggbb` => ✅  Frame has accent color
* System Accent Disabled and `accentColor: false` => ❌  Frame does NOT have accent color
* System Accent Enabled and `accentColor: undefined` => ✅ Frame has accent color
* System Accent Enabled and `accentColor: true` => ✅ Frame has accent color
* System Accent Enabled and `accentColor: #rrggbb` => ✅ …

fix: accent color should reflect system settings without restart

---

shell/browser/native_window_mac.h
shell/browser/native_window_mac.mm
shell/browser/ui/cocoa/electron_ns_window.mm
shell/browser/ui/cocoa/electron_ns_window_delegate.h
shell/browser/ui/cocoa/electron_ns_window_delegate.mm
spec/api-browser-window-spec.ts

Closes https://github.com/electron/electron/issues/47579.
Fixes an issue where child windows could crash if they were opened while the parent is fullscreened and have `roundedCorners` set to `false`. 
This was happening because Chromium uses a custom `NativeWidgetMacNSWindowBorderlessFrame` when the NSWindow has a `NSWindowStyleMaskBorderless` style mask, which is itself a subclass of `NSNextStepFrame`. `NSNextStepFrame` does not implement any of the public or private methods required for fullscreen, and so it would crash. We initially handled this by preventing windows from going fullscreen in that case, but a better solution is to temporarily remove the `NSWindowStyleMaskBorderless` style mask when going fullscreen and then restore it afterwards.
Notes: Fixed an issue where child …

fix: fullscreen for windows without rounded corners

---

shell/common/platform_util_linux.cc

Refs CL:6180523
From CL:
> Share Linux DBus session and system connections
> This cuts down on file descriptor usage and bus initialization time by
sharing DBus connections where possible. This is similar to how ChromeOS
has DBusThreadManager to use one D-Bus thread and Bus object for
everything.
Notes: none

refactor: use `dbus_thread_linux::GetSharedSessionBus()`

---

.github/actions/install-build-tools/action.yml
.github/workflows/pipeline-segment-electron-test.yml

This is causing some intermittent failures in CI - see https://github.com/electron/build-tools/pull/727 as well.
Notes: none

ci: set git `core.longpaths` to true

---

.github/workflows/pipeline-segment-electron-test.yml

See https://github.com/electron/electron/actions/runs/16201576369/job/45745877787?pr=47712:
Adjust TCC perms to allow this permission. See [tcc db ref](https://www.rainforestqa.com/blog/macos-tcc-db-deep-dive) for context.
Notes: none

ci: add `kTCCServiceAppleEvents` perm override to fix AppleScript errors

---

chromium_src/BUILD.gn

The configuration in chromium_src's BUILD.gn causes Visual Studio's Solution Explorer to display projects and code irrelevant to the current platform.
This occurs because source sets originally intended for Mac-only were incorrectly included.
Notes: Add platform-specific conditions to the source_set in chromium_src

build: add platform-specific conditions to the source_set in chromium_src

---

.github/actions/install-build-tools/action.yml

As in title.
See [diff](https://github.com/electron/build-tools/compare/274cba0474f0d1e4e6adbb66c1da48556cb0add5..e5e0b7a7470a398cb3fe92eceaf0f8837dcc4d1b).
Notes: none

ci: roll `BUILD_TOOLS_SHA` for macOS 15.5 SDK

---

spec/extensions-spec.ts

Fixes a race condition flake in extensions tests:
Many of them depend on parsing console logs, and sometimes the empty page load from the server could interfere with what it was supposed to be parsing.
Notes: none

test: fix extensions console flake

---

docs/api/corner-smoothing-css.md
docs/api/structures/web-preferences.md
patches/chromium/feat_corner_smoothing_css_rule_and_blink_painting.patch
shell/browser/web_contents_preferences.cc
shell/browser/web_contents_preferences.h
shell/common/options_switches.h
shell/renderer/electron_smooth_round_rect.cc
spec/api-corner-smoothing-spec.ts

Manual backport of #47759.
Notes: Fixed a crash when adding the `-electron-corner-smoothing` CSS rule to a stylesheet with no associated document.

fix: corner smoothing feature gate crash (37-x-y)

---

spec/api-web-frame-main-spec.ts
spec/chromium-spec.ts

This PR fixes failing/flaky RenderFrame lifespan tests.  Additionally, it disables some device tests that are hanging on macOS arm64 due to some change made in the GHA macOS runners.
Notes: none

test: cleanup RenderFrame lifespan tests

---

package.json
yarn.lock

These days the `webpack` packages comes with its own types, and `@types/webpack@^5.0.0` is just a passthrough for those types, so it can be safely removed.
Notes: none

build(dev-deps): drop unused @types/webpack dep

---

build/rules.gni
shell/browser/native_window_mac.mm

This can be cleaned up after CL:6593912
Other small changes include removing `[[NSColor blackColor] set]` since `fill` uses black by default for masks.
Notes: none

chore: clean up `NativeWindowMac::UpdateVibrancyRadii`

---

.devcontainer/on-create-command.sh

Update codespace config defaults to use `preserveSDK` by default as well as `"remoteBuild": "reclient",`
Notes: none

build: update codespace `on-create-command`

---

.github/actions/build-electron/action.yml

Closes https://github.com/electron/electron/issues/47766
Refs https://github.com/electron/electron/pull/45466
Fixes an issue where ffmpeg builds didn't get built correctly on Windows arm64 or ia32
```
src on git:7a73d3ec5a6e8 ❯ file ~/Downloads/x64ffmpeg.dll                    10:25AM
/Users/codebytere/Downloads/ffmpeg.dll: PE32+ executable (DLL) (console) x86-64, for MS Windows
src on git:7a73d3ec5a6e8 ❯ file ~/Downloads/arm64ffmpeg.dll                    10:25AM
/Users/codebytere/Downloads/ffmpeg.dll: PE32+ executable (DLL) (console) x86-64, for MS Windows
src on git:7a73d3ec5a6e8 ❯ file ~/Downloads/ia32ffmpeg.dll                    10:25AM
/Users/codebytere/Downloads/ffmpeg.dll: PE32+ executable (DLL) (console) x86-64, for MS Windows
```
It seems we didn't properly set `GN_EXTRA_ARGS` …

build: fix ffmpeg generation on Windows non-x64

---

shell/browser/api/electron_api_web_contents.cc
spec/api-session-spec.ts

Description of Change
This PR fixes an issue where the `Referer` HTTP header was not being correctly applied when using the `webContents.downloadURL()` API.
The previous implementation added all headers, including `Referer`, through the generic `add_request_header` method. However, `Referer` is a special header that cannot be set via the generic `add_request_header` method. Instead, the download system requires the referrer to be set specifically via `download_params->set_referrer()`.
This change adds logic to specifically detect the `Referer` header (case-insensitively) from the options and sets it using the correct method, ensuring it is properly handled during the download request. Other headers continue to be processed as before.
Before this PR:
- …

fix: `webContents.downloadURL()` did not support referer header

---

.github/actions/free-space-macos/action.yml
.github/workflows/pipeline-segment-electron-test.yml
spec/chromium-spec.ts

- This fixes the hang on device tests on macOS arm64 that was disabled in #47746.
- Additionally, this PR disables macOS's spotlight indexing which will free up some disk space and may help improve build performance.
Notes: none

ci: fixup mac runners

---

docs/development/creating-api.md
shell/common/gin_helper/promise.cc
shell/common/gin_helper/promise.h
shell/common/node_bindings.cc
shell/common/node_util.cc
shell/common/node_util.h
shell/renderer/electron_render_frame_observer.cc
shell/renderer/electron_renderer_client.cc
shell/renderer/electron_renderer_client.h
shell/renderer/electron_sandboxed_renderer_client.cc
shell/renderer/electron_sandboxed_renderer_client.h
shell/renderer/preload_realm_context.cc
shell/renderer/preload_realm_context.h
shell/renderer/renderer_client_base.cc
shell/renderer/renderer_client_base.h
shell/renderer/service_worker_data.cc
shell/renderer/service_worker_data.h

Part 3 in a short [series](https://github.com/electron/electron/pull/477600) to remove deprecated calls to `GetIsolate()`. Broken up into a few PRs to keep things reviewable.
This step cleans up most of the remaining calls not related to the context bridge.
Notes: none.

refactor: avoid deprecated v8::Context::GetIsolate() calls pt 3 context get isolate pt 3

---

shell/browser/ui/electron_desktop_window_tree_host_linux.cc
shell/browser/ui/electron_desktop_window_tree_host_linux.h

Closes https://github.com/electron/electron/issues/47842
Refs CL:6469606
Fixes an issue where windows used dark theme on Linux all the time without reacting to system theme changes.
We need to take an approach similar to that in [`BrowserDesktopWindowTreeHostLinux`](https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/ui/views/frame/browser_desktop_window_tree_host_linux.cc;l=106-115;drc=4eaa7ecc4adc54dc936063562327f3d0c599f403;bpv=1;bpt=0) and override the `prefers_dark_theme` property based on our own `ui::LinuxUiGetter`.
Notes: Fixed an issue where windows used dark theme on Linux all the time without reacting to system theme changes.

fix: dark mode on Linux default themeing

---

docs/api/app.md
shell/app/electron_main_delegate.cc
shell/browser/api/electron_api_app.cc
shell/common/asar/archive_win.cc
shell/common/node_bindings.cc
spec/api-app-spec.ts

Electron currently uses the `DIR_MODULE` constants `DIR_EXE` when querying the `PathService` to calculate resource paths, but the [Chromium source](https://source.chromium.org/chromium/chromium/src/+/febc3ace14c2c7863c308ea1f27b5dd891245bd6:base/base_paths.h;l=35-38) and https://issues.chromium.org/issues/40203062 both discourage using these constants to  locate assets, and instead recommend using `DIR_ASSETS`.
By default `DIR_ASSETS` is an [alias](https://source.chromium.org/chromium/chromium/src/+/febc3ace14c2c7863c308ea1f27b5dd891245bd6:base/base_paths.cc;l=74-75) for `DIR_MODULE`, but by updating Electron to use `DIR_ASSETS`, we align better with Chromium recommendations, and make it possible for apps with custom layouts to only need to override `DIR_ASSETS`.
In addition to changing …

feat: Use DIR_ASSETS path to locate resource bundles

---

patches/chromium/can_create_window.patch
patches/chromium/chore_partial_revert_of.patch
patches/chromium/chore_provide_iswebcontentscreationoverridden_with_full_params.patch
patches/chromium/fix_on-screen-keyboard_hides_on_input_blur_in_webview.patch
patches/chromium/refactor_expose_cursor_changes_to_the_webcontentsobserver.patch
patches/chromium/refactor_unfilter_unresponsive_events.patch
patches/chromium/web_contents.patch
patches/chromium/webview_fullscreen.patch
shell/browser/api/electron_api_web_contents.cc
shell/browser/api/electron_api_web_contents.h
spec/guest-window-manager-spec.ts

Closes https://github.com/electron/electron/issues/34095
Fixes an issue where windows opened with `window.open` would never be offscreen regardless of what the user overrode via `setWindowOpenHandler`. This adjusts an existing patch to allow overriding the `delegate_view` and `view` in `CreateParams` the same way we do for an offscreen window opened via the typical `BrowserWindow` constructor.
Notes: Fixed an issue where windows opened with `window.open` would never be offscreen.

fix: offscreen mode under `window.open` creation

---

shell/renderer/api/electron_api_context_bridge.cc

Fourth and final  PR in a [series](https://github.com/electron/electron/pull/47760) of PRs to reduce use of `v8::Context::GetIsolate()` since that method has been deprecated upstream.
This PR removes most of the instances used by the context bridge and its callers.
Notes: none.

refactor: avoid deprecated `v8::Context::GetIsolate()` pt 4

---

.github/actions/free-space-macos/action.yml
.github/workflows/pipeline-segment-electron-test.yml
spec/chromium-spec.ts

- This is a reapply of #47877 which was reverted in #47917.  This fixes the underlying issue which was a leading space in the string `/opt/hca/hosted-compute-agent`.
- This fixes the hang on device tests on macOS arm64 that was disabled in #47746.
- Additionally, this PR disables macOS's spotlight indexing which will free up some disk space and may help improve build performance.
37-x-y and 38-x-y already have this fix in place.  
Notes: none

ci: fixup mac runner hang

---

docs/api/tray.md
shell/browser/api/electron_api_tray.cc
shell/browser/api/electron_api_tray.h
shell/browser/ui/tray_icon.cc
shell/browser/ui/tray_icon.h
shell/browser/ui/tray_icon_cocoa.h
shell/browser/ui/tray_icon_cocoa.mm
shell/browser/ui/tray_icon_linux.cc
shell/browser/ui/tray_icon_win.cc
shell/browser/ui/win/notify_icon_host.cc
shell/browser/ui/win/notify_icon_host.h
shell/common/gin_converters/guid_converter.h
spec/api-tray-spec.ts

Closes https://github.com/electron/electron/issues/42154.
Fixes an issue where a tray icon on macOS would not maintain position across launches.
macOS allows setting an autosave name on an `NSStatusItem`, which enables the icon to maintain its position across launches. If a user creates and then closes a tray icon and then creates a new one with the same autosave name as the previously closed one, macOS will place it in the same position as the previous one with the same name.
We do this by adding a feature to customize the autosave name.
Notes: Added `tray.{get|set}AutosaveName` to enable macOS tray icons to maintain position across launches.

feat: allow macOS tray to maintain position

---

docs/api/structures/offscreen-shared-texture.md
docs/api/structures/shared-texture-handle.md
docs/breaking-changes.md
shell/browser/osr/osr_paint_event.h
shell/browser/osr/osr_video_consumer.cc
shell/common/gin_converters/osr_converter.cc
shell/common/gin_converters/osr_converter.h

Breaking change for 'paint' event when shared texture offscreen is enabled, moved shared texture handle data to a unified `handle` property. Add `colorSpace` info. Split from https://github.com/electron/electron/pull/46811
Note that this API was marked experimental, so a breaking change should be expected by developers. Previous API put everything in root object which is not ideal.
Notes:
* Added `colorSpace` to offscreen shared texture info of `webContents.on('paint')` event.
* Breaking Changed the signature of `OffscreenSharedTexture` to provide a unified `handle` that holds the native handle.

feat: `paint` event move texture data to `handle`, add `colorSpace`

---

build/webpack/webpack.config.base.js
lib/browser/init.ts
lib/node/asar-fs-wrapper.ts
lib/renderer/init.ts
lib/utility/init.ts
lib/worker/init.ts
package.json
tsconfig.json
typings/internal-ambient.d.ts
yarn.lock

This change was prompted by #47621 which is trying to bring in the latest `@types/webpack-env` and causing TS build errors due to conflicting types. [Webpack added `module.d.ts` in v5.62.0](https://github.com/webpack/webpack/releases/tag/v5.62.0), which serves the same purpose as `@types/webpack-env`, so this PR switches to it and drops `@types/webpack-env`.
This PR also adds a path mapping in `tsconfig.json` to map `@node/*` to `../third_party/electron_node` and types the requires of Node.js modules so that we get accurate types for them, which required tweaking our existing types a bit.
Notes: none

build: drop @types/webpack-env in favor of webpack/module types

---

build/webpack/webpack.config.base.js
patches/node/fix_allow_passing_fileexists_fn_to_legacymainresolve.patch
patches/node/fix_expose_the_built-in_electron_module_via_the_esm_loader.patch
patches/node/fix_lazyload_fs_in_esm_loaders_to_apply_asar_patches.patch
spec/api-utility-process-spec.ts
spec/esm-spec.ts
spec/fixtures/api/utility-process/electron-modules/import-common.mjs
spec/fixtures/api/utility-process/electron-modules/import-lol.mjs
spec/fixtures/api/utility-process/electron-modules/import-main.mjs
spec/fixtures/api/utility-process/electron-modules/import-renderer.mjs
spec/fixtures/api/utility-process/electron-modules/import-utility.mjs
spec/fixtures/api/utility-process/electron-modules/require-common.js
spec/fixtures/api/utility-process/electron-modules/require-lol.js
spec/fixtures/api/utility-process/electron-modules/require-main.js
spec/fixtures/api/utility-process/electron-modules/require-renderer.js
spec/fixtures/api/utility-process/electron-modules/require-utility.js
spec/fixtures/esm/electron-modules/import-common.mjs
spec/fixtures/esm/electron-modules/import-lol.mjs
spec/fixtures/esm/electron-modules/import-main.mjs
spec/fixtures/esm/electron-modules/import-renderer.mjs
spec/fixtures/esm/electron-modules/import-utility.mjs
spec/modules-spec.ts

Follow-up to #47968. I missed that there's a patch to handle the `electron/*` module imports in ESM mode, as I'd only tested CJS. Our test coverage was a bit sparse so I expanded it to cover both ESM and CJS code paths for the utility process and added additional ESM coverage for these imports across the board.
Notes: Fixed an issue where importing  from `electron/utility` in an ESM file threw an error at runtime

fix: importing from electron/utility in ESM

---

docs/api/environment-variables.md
docs/breaking-changes.md

Deprecates the **`ELECTRON_OZONE_PLATFORM_HINT` environment variable** in Electron 38. It is planned to be removed in Electron 39.
See #48001 for more information.
Notes: Deprecated the `ELECTRON_OZONE_PLATFORM_HINT` environment variable.

docs: deprecate `ELECTRON_OZONE_PLATFORM_HINT` env var

---

docs/development/multi-monitor-testing.md
docs/development/testing.md
spec/api-browser-window-spec.ts
spec/fixtures/native-addon/virtual-display/binding.gyp
spec/fixtures/native-addon/virtual-display/include/VirtualDisplayBridge.h
spec/fixtures/native-addon/virtual-display/lib/virtual-display.js
spec/fixtures/native-addon/virtual-display/package.json
spec/fixtures/native-addon/virtual-display/src/Dummy.swift
spec/fixtures/native-addon/virtual-display/src/VirtualDisplay.swift
spec/fixtures/native-addon/virtual-display/src/VirtualDisplayBridge.m
spec/fixtures/native-addon/virtual-display/src/addon.mm
spec/package.json
spec/yarn.lock

> [!NOTE]
> This PR is part of GSoC 2025 [[project](https://electronhq.notion.site/Electron-Google-Summer-of-Code-2025-Ideas-List-1851459d1bd1811894dad8b48a68596d#1851459d1bd18153b559ca297694dda2)] [[rfc](https://github.com/electron/rfcs/pull/16/files)]
This PR adds a new native addon fixture for testing virtual display functionality in Electron. The `virtual-display` addon provides programmatic virtual display creation capabilities on macOS for comprehensive display testing scenarios.
Example usage:
```js
const virtualDisplay = require('@electron-ci/virtual-display');
const displayId = virtualDisplay.create();
virtualDisplay.destroy(displayId);
```
Notes: none

test: support for multimonitor tests

---

.github/workflows/issue-commented.yml
.github/workflows/non-maintainer-dependency-change.yml

[GitHub will be removing the `author_association` field from event payloads](https://github.blog/changelog/2025-08-08-upcoming-changes-to-github-events-api-payloads/) in the near future, so we need to switch this logic to manually fetch the association. Unfortunate downside here is that these runs used to be able to be filtered out entirely for maintainers, but now a small job has to run to determine if the user is a maintainer if the other criteria is met.
Notes: none

ci: manually fetch author_association in workflow automations

---

shell/browser/api/electron_api_app.cc

Closes https://github.com/electron/electron/issues/48039.
Fixes an issue where `app.accessibilitySupportEnabled` didn't work as expected. This happened as a result of https://github.com/electron/electron/issues/46118.
Notes: Fixed an issue where `app.accessibilitySupportEnabled` didn't work as expected.

fix: `app.accessibilitySupportEnabled` 

---

package.json
yarn.lock

This reverts commit 13ed526ca7d4622ddf14d0f737a6da6d33d6a92b, which broke releases on Windows. Fix forward incoming, just want to get a nightly out today
Notes: none

build: revert bump @octokit/rest from 20.1.2 to 22.0.0 

---

shell/common/platform_util_linux.cc

Closes https://github.com/electron/electron/issues/47668.
Fixes an issue where `shell.openPath` was not non-blocking as expected.
Notes: Fixed an issue where `shell.openPath` was not non-blocking as expected.

fix: `shell.openPath` should be non-blocking

---

shell/app/electron_main_delegate.cc

A previous PR landed with the incorrect `CHECK` syntax, and is breaking the release build. This PR corrects the syntax.
Notes: none

build: correct CHECK syntax

---

shell/common/color_util.cc

Closes https://github.com/electron/electron/issues/48086
Closes https://github.com/electron/electron/issues
Refs https://github.com/electron/electron/pull/47741.
Fixes an issue where the accent color would be accidentally inverted when set to match the system color. This could be seen if you chose e.g. an orange, whose color opposite is blue; the window would have a blue border in that case. This happened because `DwmGetColorizationColor` returns a color formatted `0xAARRGGBB`,  and the parsing performed [here](https://github.com/electron/electron/blob/5c98e3609f4b62490fd44541f28f1086b604e4e9/shell/browser/native_window_views_win.cc#L585-L589) used `Get{R|G|B}Value` to parse the color into a `COLORREF`. From [documentation](https://learn.microsoft.com/en-us/windows/win32/api/dwmapi/nf-dwma …

fix: system accent color parsing hex order

---

BUILD.gn
shell/browser/notifications/win/windows_toast_notification.cc
shell/browser/notifications/win/windows_toast_notification.h

We can clean up our XML building logic by re-using the XmlWriter class available upstream.
Notes: none

refactor: use `XmlWriter` for Windows toasts

---

.github/workflows/build.yml

#48120 accidentally turned off the docs-only CI. This PR restores that check.
Notes: none

build: fixup docs only condition

---

docs/breaking-changes.md

- #47983 documented the breaking change  of the `ELECTRON_OZONE_PLATFORM_HINT` environment variable removal as it was removed because of https://chromium-review.googlesource.com/c/chromium/src/+/6819616
- #48075 includes https://chromium-review.googlesource.com/c/chromium/src/+/6824606 which is a chromium backport of https://chromium-review.googlesource.com/c/chromium/src/+/6819616, so the breaking change has moved from 39.0.0 to 38.0.0. 
Notes: none

docs: update 38.0 breaking changes

---

shell/services/node/node_service.cc
shell/services/node/node_service.h

Closes #48100.
Fixes an issue where `net.isOnline()` always returned `true` in utilityProcesses. This happened because utility processes never created a `net::NetworkChangeNotifier`, so `net.isOnline()` always saw a null [global](https://source.chromium.org/chromium/chromium/src/+/main:net/base/network_change_notifier.cc;drc=280cd6cc9ad696c74313035a0bbaab8f4f8c4bf4;bpv=1;bpt=1;l=52) and defaulted to “online”.
Fix this by adding a per‑utility‑process `NetworkChangeNotifier` during `NodeService::Initialize()]`, allowing `net.isOnline()`  to reflect real connectivity. 
Notes: Fixed an issue where `net.isOnline()` always returned `true` in utilityProcesses.

fix: `net.isOnline` always true in utility processes

---

lib/browser/api/web-contents.ts

The fromId defined in the file accepts a string arg, while the api docs are number, the native binding also wants a int32.
Notes: none

fix: webContent.fromId should be number instead of string

---

.github/actions/build-electron/action.yml
build/args/all.gn

- Followup to #47534.  We no longer need to disable siso by default.
This also fixes our release builds generation of ffmpeg.zip.
Notes: none

build: remove no longer needed arg for siso

---

docs/tutorial/electron-timelines.md

Adds release dates for Electron 39 to our release timeline docs. Also, updated the [Node.js version](https://github.com/electron/electron/blob/38-x-y/DEPS#L7) in the 38 row.
Notes: none

docs: add release timeline for Electron 39

---

.github/workflows/build.yml
.github/workflows/pipeline-segment-electron-test.yml

GitHub has free arm runners we should use to reduce our CI costs:
- https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/
- https://github.blog/changelog/2025-04-14-windows-arm64-hosted-runners-now-available-in-public-preview/
This PR moves our Linux arm64 and Windows on Arm testing to the free runners.  Linux armv7 (32 bit) will still run on our custom runners as there are some incompatiblities between ubuntu-24.04-arm and our ghcr.io/electron/test:arm32v7 image.
Notes: none

ci: use free GH arm runners

---

docs/api/menu-item.md
docs/api/service-worker-main.md

* `MenuItem` is an exported module and should have a `#` heading.
* `ServiceWorkerMain` is an unexported class and should not have a `#` heading.
cc @dsanders11
Notes: none

docs: fix some module headings

---

docs/api/process.md
shell/common/api/electron_bindings.cc

Backport of #47628 
Notes: Added `fileBacked` and `purgeable` fields to `process.getSystemMemoryInfo()` for macOS.

feat: add `fileBacked` and `purgeable` fields to `process.getSystemMemoryInfo()` for macOS

---

shell/browser/native_window_views_win.cc
shell/browser/ui/win/electron_desktop_window_tree_host_win.cc

Closes https://github.com/electron/electron/issues/48179.
Fixes an issue where dragging sometimes didn't work after the `contextmenu` event was emitted. This happened because `WM_RBUTTONUP` can be racy with the mousehandler, so the call to `electron::api::WebContents::SetDisableDraggableRegions(false)` didn't always happen as expected. Fix this by consolidating logic into `ElectronDesktopWindowTreeHostWin::HandleMouseEvent`.
Notes: Fixed an issue where dragging sometimes didn't work after the `contextmenu` event was emitted.

fix: ensure dragging works again after emitting contextmenu event

---

shell/browser/api/electron_api_service_worker_main.h

`ServiceWorkerMain` doesn't emit anything, so it doesn't need to inherit from `EventEmitterMixin`.
Notes: none.

refactor: avoid unused inheritance in ServiceWorkerMain

---

docs/api/session.md
shell/browser/electron_permission_manager.cc
shell/browser/electron_permission_manager.h
shell/browser/file_system_access/file_system_access_permission_context.cc
spec/chromium-spec.ts
spec/fixtures/file-system/persist.txt
spec/fixtures/file-system/test-perms.html

Closes https://github.com/electron/electron/issues/41957.
Addresses an issue where File System API non-active statuses weren't correctly persistent on previous grant. This exposes `fileSystem` permissions via `ses.setPermissionCheckHandler` to handle this case.
Notes: Allowed for persisting File System API grant status within a given session.

feat: add `fileSystem` to `ses.setPermissionCheckHandler`

---

shell/browser/api/electron_api_session.cc
shell/browser/api/electron_api_web_contents.cc

Refs https://github.com/electron/electron/pull/48308#discussion_r2348597086
These callsites already get an associated default handle scope when V8 invokes them, these should have been an `EscapableHandleScope` if at all we need to add one.
The crash can be repro when running our test suites under `is_debug=true` build. Thanks to report from openfin cc @marekharanczyk
Notes: fix crash when accessing `webContents.session` or `webContents.debugger`

fix: remove unneeded handlescope from JS callbacks

---

patches/v8/.patches
patches/v8/cherry-pick-ec6c18478382.patch

[compiler] Don't assume that upper 32-bit of Int32MulOvfCheck are 0
Because Arm64 doesn't have a flag-setting 32-bit multiplication,
which means that instead with use a 64-bit multiplication, and compare
result.X() and result.W() to check if an overflow happened. But this
leads to the upper 32-bit not being zeroed.
Fixed: 445380761
Change-Id: I31287faf37dc615695047021324e9d1d802cbec2
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/6954290
Auto-Submit: Darius Mercadier <dmercadier@chromium.org>
Commit-Queue: Leszek Swirski <leszeks@chromium.org>
Cr-Commit-Position: refs/heads/main@{#102530}
Notes: Backported fix for 445380761.

chore: cherry-pick ec6c18478382 from v8

---

.github/actions/build-electron/action.yml
.github/actions/install-build-tools/action.yml

- Followup to https://github.com/electron/electron/pull/48319. Unfortunately that change was not sufficient to fix running siso from fork PRS.  This PR updates build-tools to pull in https://github.com/electron/build-tools/pull/751, which will pass `-re_exec_enable=false` to autoninja when a user doesn't have execute rights on the RBE cluster. 
This change has been verified via https://github.com/electron/electron/actions/runs/17773115669/job/50514256655?pr=48331, which is a copy of of #48293 where there are build issues because fork PRs can't write to the RBE cluster.
Notes: none

build: update build tools to get siso for forks fix

---

shell/common/api/electron_api_clipboard.cc
shell/common/api/electron_api_clipboard.h

Small refactor to reduce our use of bespoke gin code.
This PR uses `gin::Arguments*` instead of `gin_helper::Arguments*` in `api::Clipboard`. Clipboard doesn't use any of the extra features in `gin_helper::Arguments`.
Notes: none

refactor: use gin::Arguments in api::Clipboard

---

shell/renderer/api/electron_api_web_frame.cc

Remove code that parses a never-used, never-documented, never-tested `executionType` argument in `web_frame.executeJavaScriptInIsolatedWorld()`. This wart goes all the way back to when the feature originally landed in 2017 in https://github.com/electron/electron/pull/11131 which added the feature.
As [documented](https://github.com/electron/electron/blob/main/docs/api/web-frame.md#webframeexecutejavascriptinisolatedworldworldid-scripts-usergesture-callback), the API is:
```
* `worldId` Integer
* `scripts` [WebSource[]](structures/web-source.md)
* `userGesture` Boolean (optional) - Default is `false`.
* `callback` Function (optional) - Called after script has been executed.
* `result` Any
```
But the implementation works this way:
```
* `worldId` Integer
* `scripts` …
```

chore: remove unused, undocumented, untested executionMode arg from `web_frame.executeJavaScriptInIsolatedWorld()`

---

.github/workflows/pipeline-segment-electron-test.yml
package.json
script/actions/screencapture-nag-remover.sh
script/spec-runner.js
spec/api-web-contents-spec.ts
spec/lib/screen-helpers.ts
spec/webview-spec.ts
yarn.lock

- This PR was inspired by a conversation with @reitowo. It adds logic to rerun failed tests individually.  This should help avoid having to do full reruns of test suites when flakes happen.
- Additionally, this PR fixes a CI issue where a macOS system dialog was appearing with the following text which  broke/interfered with some of our tests:
>"bash" is requesting to bypass the system private window picker and directly access your screen and audio.  
- This PR also fixes #48291.
Notes: none

test: rerun failed tests individually

---

docs/tutorial/asar-integrity.md

* Correct heading level
* While I'm at it, convert `:::` admonition syntax to the block-quote stuff that's better to read in the raw Markdown.
notes: none

docs: fix formatting in asar integrity

---

shell/app/electron_main_delegate.cc
shell/browser/electron_browser_main_parts.cc
shell/browser/electron_browser_main_parts.h

`base::FeatureList` needs to be initialized before any features are parsed so that appropriate field trials are setup. Today we call `InitializeFeatureList` from `Electron::PreBrowserMain` and `Electron::PostEarlyInitialization` however the feature list is initialized somewhere in between via `Electron::PreEarlyInitialization`. This results in the following crash when launching the application with a feature param `--enable-features="NetAdapterMaxBufSizeFeature:NetAdapterMaxBufSize/8192"`.
```
[56990:0929/130502.801852:FATAL:base/feature_list.cc:905] DCHECK failed: trial. trial='StudyNetAdapterMaxBufSizeFeature' does not exist
```
This PR addresses by moving the feature list initialization before any feature parsing happens. The instance leaked is on purpose aligning with upstream …

fix: initialze featurelist before parsing features

---

docs/api/window-open.md

Fixes https://github.com/electron/electron/issues/48271
The `preload` option was removed in https://github.com/electron/electron/pull/23226.
Notes: none

docs: update allowed `window.open` options

---

docs/api/clipboard.md
docs/api/crash-reporter.md
docs/api/ipc-renderer.md
docs/api/native-image.md
docs/api/web-frame.md
docs/api/web-utils.md

Refs https://github.com/electron/electron/issues/45666
As discussed [here](https://github.com/electron/electron/pull/45861#discussion_r2393055125). CC @MarshallOfSound.
We've had many confused users in the bug tracker who had context isolation enabled and struggled to call `webUtils.getPathForFile`. This makes it clear that when context isolation is enabled, renderer process modules need to be called from the preload script.
Notes: none

docs: recommend calling renderer process modules from preload script

---

shell/renderer/electron_ipc_native.cc

Avoid a little extra work in `InvokeIpcCallback()`:
1. Allocate the `node::CallbackScope` on the stack instead of the heap by using `std::optional` instead of `std::unique_ptr`.
2. Skip a redundant call to  `node::Environment::GetCurrent()` by passing `env` to the callback scope's constructor
CC @codebytere, @deepak1556 
Notes: none.

perf: avoid a little extra work in `InvokeIpcCallback()`

---

.github/actions/build-electron/action.yml
.github/actions/install-build-tools/action.yml
.github/workflows/pipeline-segment-electron-test.yml

- After the migration to siso via #47534, on occasion on Windows mksnapshot or chromedriver fails to build which then causes errors while testing, eg https://github.com/electron/electron/actions/runs/18198927807/job/51842938994?pr=48439.  
- It turns out there are several issues at hand here: 
1. Build failures are silently failing/not marking the build as failing.  This issue is addressed via https://github.com/electron/build-tools/pull/759
2. The build failure seems to be happening because we run 2 targets back to back which seems to cause file contention on siso builds on Windows sometimes.  In both cases instead of calling e build with the build target and then calling e build with the zip target, we can directly call `e build` with the zip target which should fix this contention …

build: fixup chromedriver and mksnapshot
