electron/electron

atom.gyp
atom/browser/api/atom_api_tray.cc
atom/browser/api/atom_api_tray.h
atom/browser/ui/tray_icon.cc
atom/browser/ui/tray_icon.h
atom/browser/ui/tray_icon_cocoa.h
atom/browser/ui/tray_icon_cocoa.mm
atom/browser/ui/tray_icon_gtk.cc
atom/browser/ui/tray_icon_gtk.h
atom/browser/ui/win/notify_icon.cc
atom/browser/ui/win/notify_icon.h
atom/common/native_mate_converters/image_converter.cc
atom/common/native_mate_converters/image_converter.h
atom/common/native_mate_converters/image_converter_mac.mm
docs/api/image.md

Add support for template image

---

atom/browser/api/atom_api_dialog.cc
atom/browser/api/lib/dialog.coffee
atom/browser/ui/message_box.h
atom/browser/ui/message_box_mac.mm
atom/browser/ui/message_box_views.cc
atom/common/native_mate_converters/image_converter.cc
atom/common/native_mate_converters/image_converter_mac.mm
docs/api/dialog.md

Add "icon" option for dialog.showMessageBox

---

atom/browser/api/lib/web-contents.coffee
atom/renderer/api/lib/ipc.coffee
atom/renderer/atom_render_view_observer.cc
atom/renderer/lib/init.coffee
spec/fixtures/module/preload-ipc.js
spec/webview-spec.coffee

Don't rely on global "process" object for message dispatching

---

docs/api/auto-updater.md
docs/api/browser-window.md
docs/development/build-instructions-mac.md
docs/tutorial/application-distribution.md
docs/tutorial/quick-start.md

Apple has renamed Mac OS X to OS X.

Change Mac OS X to OS X.

---

docs/tutorial/application-packaging.md

Minor tweak, should make the sentence a bit more fluent. Thanks!

docs: update wording in `application-packaging`

---

atom/browser/api/atom_api_menu.cc
atom/browser/api/atom_api_menu.h
atom/browser/api/lib/menu-item.coffee
atom/browser/api/lib/menu.coffee
docs/api/menu-item.md

Enable setting icon for MenuItem

---

README.md

I figured this would be helpful for people wanting to quickly get it installed

add npm installation instructions to README

---

atom/browser/default_app/main.js

Thanks for putting this project together; really enjoying hacking with
it so far!

Fix tense of error message

---

atom/browser/net/adapter_request_job.cc
spec/api-protocol-spec.coffee

read files from asar archives in custom protocol

---

README.md

Update README to replace node.js with io.js

---

.gitignore
atom/browser/api/lib/dialog.coffee

avoid overriding type value of showMessageBox

---

spec/chromium-spec.coffee
spec/package.json
spec/static/main.js

the test should pass with the changes to brightray :)

test for ignoreCertificateError

---

atom/browser/api/atom_api_web_contents.cc
atom/browser/api/atom_api_web_contents.h
spec/api-browser-window-spec.coffee

add DidFailProvisionalLoad method

---

atom/browser/auto_updater_mac.mm
script/update-external-binaries.py

Catches and reports exception thrown from Squirrel

---

atom/browser/api/atom_api_tray.cc

throw when trying to create tray before app is ready

---

atom/common/api/atom_api_clipboard.cc
atom/common/api/lib/clipboard.coffee
docs/api/clipboard.md
spec/api-clipboard-spec.coffee

Add clipboard.writeImage API

---

atom/browser/native_window.cc

npapi: warn users loading npapi plugins on unsupported platform

---

atom/browser/api/atom_api_window.cc
atom/browser/api/atom_api_window.h
atom/browser/native_window.cc
atom/browser/native_window.h
atom/browser/native_window_mac.h
atom/browser/native_window_mac.mm
atom/browser/native_window_views.cc
atom/browser/native_window_views.h
docs/api/browser-window.md

Fixes #1279. @zcbenz  please take a look.

Add workspace visible APIs

---

script/create-dist.py

Verify whether the file exists before including it in zip

---

docs/tutorial/quick-start.md

Simply a small grammar improvement.

add `to` in sentence for grammar

---

atom/browser/api/atom_api_window.cc
atom/browser/api/atom_api_window.h
atom/browser/native_window.cc
atom/browser/native_window.h
atom/browser/native_window_observer.h
docs/api/browser-window.md

Fixes #981 
Depends on https://github.com/atom/brightray/pull/96

browserWindow: adding devtools-focused event

---

atom/app/atom_main_args.cc

atomMain: initialise uv_setup_args

---

atom/browser/native_window_mac.mm

nativeWindowMac: check for web_contents before clipping

---

atom/common/api/atom_api_native_image.cc
atom/common/api/atom_api_native_image.h
atom/common/api/atom_api_native_image_mac.mm
docs/api/native-image.md

nativeImage: adding setTemplateImage method

---

atom/common/platform_util_mac.mm

shell: fix regression for moveItemToTrash on mac

---

atom/browser/api/atom_api_web_contents.cc

webContents: fix dereferencing null in getURL

---

atom/browser/mac/atom_application.mm
atom/browser/native_window_mac.mm

This PR adds extremely basic support for accessibility on OS X using VoiceOver by enabling chromium accessibility when VoiceOver is active.
Previously, any usage of VoiceOver was broken due to a patch to force Text-to-Speech to use Cmd+C to speak the selected text instead of the window title. For users using accessibility, this trapped them in the window with no child accessibility elements, giving an experience something like:
This patch is two-fold:
* VoiceOver is detected, and the chromium accessibility feature is enabled and disabled based on this status. A similar approach to that used in Chromium itself is used for this.
* The TTS hack is modified to leave the chromium accessibility tree and the close/minimise/maximise buttons (but not the window title) as children of the window, …

mac: Dynamically enable accessibility based on VoiceOver status

---

docs/api/power-monitor.md

- Added two undocumented events.
- Added note that must be used after ready event.
closes #1420

Updated documentation for power-monitor

---

docs/tutorial/quick-start.md

The 2nd paragraph in "The renderer process was a little difficult to read. The following line especially,
>so it would be possible to interactive with
I have taken to revising the entire paragraph to make it flow easier.

Documentation Fix: edits quick-start doc file section "The renderer process" segment

---

docs/tutorial/quick-start.md

Fix app name in document of quick start.

docs: Atom Shell => Electron in quick-start.md

---

docs/tutorial/quick-start.md

Changed 1 occurrence of node.js to io.js in quick-start.md

node.js --> io.js

---

atom/browser/api/atom_api_content_tracing.cc

Depends on https://github.com/zcbenz/native-mate/pull/1

nativemate: moved std::set converter

---

README.md

Add Electron logo to Readme

---

docs/tutorial/quick-start.md

Fixed some run-on sentances and changed structor of some.

Minor grammatical fixes

---

atom/common/lib/asar.coffee
spec/asar-spec.coffee

asar: make fs async methods create errors asynchronously

---

atom/browser/api/atom_api_web_contents.cc
atom/browser/api/atom_api_web_contents.h
atom/renderer/lib/web-view/web-view.coffee
docs/api/web-view-tag.md

webview: add inspectElement method

---

atom/browser/native_window.cc
atom/browser/native_window.h
atom/browser/native_window_mac.h
atom/browser/native_window_mac.mm
atom/browser/native_window_views.cc
atom/browser/native_window_views.h

window: supports HTML5 fullscreen api

---

README.md

Logo png -> svg

---

atom/browser/api/atom_api_web_contents.cc
atom/browser/api/atom_api_web_contents.h
atom/browser/lib/guest-view-manager.coffee
atom/renderer/lib/web-view/guest-view-internal.coffee
docs/api/browser-window.md
docs/api/web-view-tag.md
spec/api-browser-window-spec.coffee
spec/fixtures/pages/f.html

webContents: providing dom-ready event

---

atom/browser/api/atom_api_web_contents.cc
atom/browser/api/atom_api_web_contents.h
atom/browser/atom_javascript_dialog_manager.cc
spec/fixtures/pages/beforeunload-false.html
spec/webview-spec.coffee

Make beforeunload handler work in webview

---

atom/browser/api/atom_api_web_contents.cc
atom/browser/api/atom_api_web_contents.h
docs/api/browser-window.md

webContents: adding serviceworker helper utilities

---

atom/browser/api/atom_api_window.cc
atom/browser/api/atom_api_window.h
atom/browser/native_window.cc
atom/browser/native_window.h
atom/browser/native_window_mac.h
atom/browser/native_window_mac.mm
atom/browser/native_window_views.cc
atom/browser/native_window_views.h
docs/api/browser-window.md

window: adding setBounds and getBounds api

---

atom/browser/api/atom_api_tray.cc
atom/browser/api/atom_api_tray.h
atom/browser/ui/tray_icon.cc
atom/browser/ui/tray_icon.h
atom/browser/ui/tray_icon_cocoa.mm
atom/browser/ui/tray_icon_observer.h
atom/browser/ui/win/notify_icon.cc
docs/api/tray.md

Related #1500 
Linux doesnt seem to use onclick notifier, so havnt implement it there. But will this help fix the problem ?

tray: send tray icon position as payload onclick OSX and windows

---

script/create-dist.py
script/upload.py

Upload mksnapshot to releases

---

script/update-external-binaries.py

Download 64bit directx sdk when building for 64bit target

---

README.md

Update China mirrors url

---

atom/browser/api/atom_api_protocol.cc
atom/browser/api/lib/protocol.coffee
atom/browser/net/adapter_request_job.cc
docs/api/protocol.md
spec/api-protocol-spec.coffee

protocol: adding error job to log error with custom protocols

---

atom.gyp
script/create-dist.py
script/lib/config.py
script/update-external-binaries.py

This PR fixes weird problems caused by Chrome's own allocator shim.
Fixes #1650.
Fixes #1471.
Fixes #1463.
Fixes #1509.
Fixes #1489.

Link with DLL version of VC++ runtime

---

atom/app/atom_content_client.cc
docs/README.md
docs/tutorial/using-pepper-flash-plugin.md

Fix https://github.com/atom/electron/issues/1637

ppapi: fix PPAPI flash plugin description as chromium does

---

atom/app/atom_main_delegate.cc
atom/browser/atom_browser_client.cc
atom/browser/atom_browser_client.h
atom/browser/atom_quota_permission_context.cc
atom/browser/atom_quota_permission_context.h
filenames.gypi
spec/chromium-spec.coffee

browser: create quota permission context to allow quota request

---

atom/common/api/lib/original-fs.coffee
atom/common/lib/asar_init.coffee
filenames.gypi
spec/asar-spec.coffee
spec/fixtures/module/original-fs.js

Make "original-fs" available in forked scripts

---

atom/browser/api/atom_api_web_contents.cc
atom/browser/api/atom_api_web_contents.h
atom/browser/lib/guest-view-manager.coffee
atom/renderer/lib/web-view/guest-view-internal.coffee
docs/api/browser-window.md
docs/api/web-view-tag.md

Fixes #832 , thought it would be good to have event to detect plugin crashes too. Thoughts ?

webContents: adding events to detect gpu and plugin process crashes

---

docs/tutorial/using-pepper-flash-plugin.md

Add brackets around `plugins: true`

doc: fix typo in pepper flash document

---

atom/browser/api/atom_api_screen.cc

screen: initialise displays_ vector with primary display

---

atom/browser/api/atom_api_web_contents.cc
atom/browser/api/atom_api_web_contents.h
atom/browser/api/atom_api_window.cc
atom/browser/api/atom_api_window.h
atom/browser/lib/guest-view-manager.coffee
atom/browser/native_window.cc
atom/browser/native_window.h
atom/browser/native_window_observer.h
atom/renderer/lib/web-view/guest-view-internal.coffee
docs/api/browser-window.md
docs/api/web-view-tag.md

Fixes #1503 
Fixes #1721 
Fixes #1627

webContents: override fullscreen notification apis for webview

---

README.md

Good list of really cool applications using `electron`.

Add link to `awesome-electron`

---

docs/api/native-image.md

docs: Fix grammatical issues

---

atom/browser/api/atom_api_window.cc
atom/browser/api/atom_api_window.h
atom/browser/native_window.cc
atom/browser/native_window.h
atom/browser/native_window_mac.mm
atom/browser/native_window_observer.h
atom/browser/native_window_views.cc
atom/browser/native_window_views.h
docs/api/browser-window.md
spec/api-browser-window-spec.coffee

Fixes #1561 , need verification for windows.
Test:

window: adding resize and move events

---

atom/browser/atom_browser_context.cc
atom/renderer/atom_render_view_observer.cc

protocol: adding ftp scheme support

---

atom/browser/api/atom_api_web_contents.cc

fix accessing headers from resourcerequestdetails

---

atom/browser/atom_browser_client.cc

browserClient: dont restart render process for javascript scheme

---

atom/browser/native_window.cc
atom/common/options_switches.cc
atom/common/options_switches.h
atom/renderer/atom_renderer_client.cc
atom/renderer/atom_renderer_client.h
docs/api/browser-window.md

renderer: option to override page visiblity state

---

atom/browser/native_window.cc
atom/browser/native_window.h

For https://github.com/atom/electron/issues/1842#issuecomment-108611241
Depends on https://github.com/atom/brightray/pull/111

devtools: supporting workspace usage

---

docs/api/browser-window.md
docs/development/build-instructions-linux.md

I've updated the Linux build instructions to add a little more detail. I hope this is satisfactory. Thank you!

Linux build instructions issue 1809

---

docs/api/chrome-command-line-switches.md

Depends on https://github.com/atom/brightray/pull/113

doc: adding info about log-net-log flag

---

atom/browser/api/atom_api_web_contents.cc
atom/browser/lib/guest-view-manager.coffee
atom/renderer/lib/web-view/web-view-attributes.coffee
docs/api/browser-window.md

The PR #801 forgot to update the doc.
\cc @frankhale

:memo: Add missing `httpreferer` option doc.

---

atom/browser/api/atom_api_web_contents.cc
atom/browser/api/atom_api_web_contents.h
atom/browser/lib/guest-view-manager.coffee

Fix getting owner window in guest WebContents

---

docs/tutorial/using-selenium-and-webdriver.md

doc on how to test with your application

---

docs/api/menu.md

Update menu documentation

---

atom/common/crash_reporter/crash_reporter.cc
atom/renderer/lib/web-view/web-view.coffee

See https://github.com/atom/electron/issues/1910

Fixing an issue compiling on Windows and improving webview interopability with other JavaScript libraries

---

atom/browser/api/atom_api_power_monitor.cc
atom/browser/api/atom_api_protocol.cc
atom/browser/api/atom_api_protocol.h
atom/browser/api/atom_api_screen.cc
atom/browser/api/atom_api_tray.cc
atom/browser/api/atom_api_tray.h
atom/browser/api/atom_api_window.cc
atom/common/api/atom_api_id_weak_map.cc
atom/common/lib/asar.coffee
atom/renderer/api/atom_api_renderer_ipc.cc
common.gypi
script/update.py

v2.2.1 seems stable enough, and it will make requests for io.js update quiet for some time.
Close #1914.

Update to io.js v2.2.1

---

atom/browser/atom_browser_client.cc
atom/browser/atom_browser_client.h
atom/common/options_switches.cc
atom/common/options_switches.h
docs/api/chrome-command-line-switches.md

browser: support client certificate

---

atom/renderer/api/lib/remote.coffee

Fixes https://github.com/atom/electron/issues/1888

remote: handle circular reference in wrapArgs

---

docs/api/tray.md

Note that setPressedImage only has an effect on OS X

---

atom/browser/api/lib/browser-window.coffee
docs/api/app.md
spec/api-app-spec.coffee

app: adding focus/blur events

---

atom/common/api/atom_bindings.cc
docs/api/process.md

process: add hang method

---

atom/renderer/lib/override.coffee

override: set window.opener to null for webview

---

README-ko.md
docs/README-ko.md
docs/api/accelerator-ko.md
docs/api/menu-item-ko.md
docs/api/power-monitor-ko.md
docs/api/tray-ko.md
docs/api/web-view-tag-ko.md
docs/development/coding-style-ko.md
docs/tutorial/application-distribution-ko.md
docs/tutorial/application-packaging-ko.md
docs/tutorial/debugging-main-process-ko.md
docs/tutorial/desktop-environment-integration-ko.md
docs/tutorial/devtools-extension-ko.md
docs/tutorial/online-offline-events-ko.md
docs/tutorial/quick-start-ko.md
docs/tutorial/using-native-node-modules-ko.md
docs/tutorial/using-pepper-flash-plugin-ko.md
docs/tutorial/using-selenium-and-webdriver-ko.md

Not yet fully completed, but main tutorials and apis translation has been completed. (except one file)
I will be also translate the other files soon!

Translate docs to korean (Re PR)

---

atom/common/lib/asar.coffee
spec/asar-spec.coffee

Add tests for reading unpacked files using both fs.readFileSync and
internalModuleReadFile

Update internalModuleReadFile to support unpacked asar files

---

atom/browser/api/atom_api_session.cc

Fixes #2050 is this problem with node integration that `resolveproxy` call made earlier than initialising `url_request_context_getter` ?
Also based on suggestion [here](https://code.google.com/p/chromium/codesearch#chromium/src/net/url_request/url_request_context_getter.h&q=geturlrequestcontext&sq=package:chromium&l=30) moved `GetURLRequestContext` to network task runner.

session: using storageparttion to retrieve requestcontext

---

docs/api/auto-updater.md

electron-installer not atom-shell-installer

---

atom/browser/atom_browser_client.h

ninja compilation failed for me under OS X 10.11

Missing overrides

---

atom/browser/ui/accelerator_util.cc

Fix the wrong reverse `pageup` and `pagedown` keys.

---

atom.gyp
script/bootstrap.py
script/cibuild
script/dump-symbols.py
script/update.py
toolchain.gypi

This PR makes electron build in GitHub's Windows CI machine.

Build in Windows CI

---

.gitmodules
script/bootstrap.py
script/cibuild
script/clean.py
script/lib/github.py
script/lib/util.py
script/update.py
script/upload.py
spec/api-browser-window-spec.coffee

This PR creates Release distributions when there is a new tag pushed and uploads them to GitHub releases.

Create Release distributions in CI machine

---

.travis.yml
script/lib/config.py

Fix https://github.com/atom/electron/issues/1680.

Don't force using OpenSSL on linux

---

atom/browser/api/lib/browser-window.coffee

Fix a type error on window.moveTo API.

---

docs/api/native-image.md

Slight change to improve documentation of this method.

improve docs on toJpeg(quality)

---

atom/common/api/atom_api_clipboard.cc
docs/api/clipboard.md
spec/api-clipboard-spec.coffee

Fixes #2130 
scopedwriter is so limited, if there is a better approach i can take here do suggest.

clipboard: api to write multiple formats to same writer

---

docs/api/chrome-command-line-switches.md

Depends on https://github.com/atom/brightray/pull/123

doc: kProxyPacUrl support

---

atom/browser/api/trackable_object.h

It is OK under most cases, but if you happen to also use COM in your application, you will have heap corruptions.
Fixes #2188.

Avoiding creating static STL containers

---

atom/browser/api/atom_api_web_contents.cc
atom/browser/native_window.cc

webContents: set http useragent settings when overriding user agent

---

docs/api/global-shortcut.md

Improve the grammar, sentence structure and code formatting of global-shortcut.md.

Improve grammar and code formatting

---

atom/browser/api/atom_api_session.cc
atom/browser/api/atom_api_session.h
docs/api/browser-window.md

session: api to set proxy

---

atom/browser/api/atom_api_web_contents.cc
atom/browser/api/atom_api_web_contents.h
atom/renderer/lib/web-view/web-view.coffee
docs/api/browser-window.md
docs/api/web-view-tag.md

Implement getUserAgent API.

---

atom/browser/api/atom_api_protocol.cc
atom/browser/net/adapter_request_job.cc
atom/browser/net/adapter_request_job.h

Fixes #2292 
Fixes #2286 
Fixes #2261 
Fixes #2303

protocol: fix adapter request job for default handlers

---

docs/README-es.md
docs/tutorial/application-distribution-es.md
docs/tutorial/application-packaging-es.md
docs/tutorial/debugging-main-process-es.md
docs/tutorial/desktop-environment-integration-es.md
docs/tutorial/devtools-extension-es.md
docs/tutorial/online-offline-events-es.md
docs/tutorial/quick-start-es.md
docs/tutorial/using-native-node-modules-es.md
docs/tutorial/using-pepper-flash-plugin-es.md
docs/tutorial/using-selenium-and-webdriver-es.md

Basic Spanish docs

---

atom/browser/api/lib/web-contents.coffee
docs/api/browser-window.md

Related to https://github.com/atom/electron/pull/1835#issuecomment-124852907.

Add 'pageSize' option in printToPDF API.

---

docs/api/accelerator.md
docs/api/auto-updater.md
docs/api/chrome-command-line-switches.md
docs/api/clipboard.md
docs/api/crash-reporter.md

Improve the grammar, sentence structure, punctuation and formatting.

Update api docs

---

atom/browser/web_dialog_helper.cc

Fix a missing the specified mime type check in <input> accept attribute.

---

atom/browser/api/atom_api_web_contents.cc
atom/browser/api/atom_api_web_contents.h
atom/browser/common_web_contents_delegate.cc
atom/browser/common_web_contents_delegate.h
docs/api/browser-window.md

Refs #2322 
Depends on https://github.com/atom/brightray/pull/128

webContents: api to add/remove path from devtools workspace

---

atom/browser/ui/tray_icon_cocoa.mm

This PR fixes a couple of tray issues causing by #2232 .
* Fixes #2360. It's caused by forcing the icon with to 26px. Some more, the native NSStatusItem implmentation will draw 4px to the image as left and right padding margin, in StatusItemView, we need to simulate its behavior manually.
* Fixes Tempate image doesn't show correctly in dark mode.
* Fixes title color will not reversed in dark mode.

Use NSImageView to draw tray icon.

---

atom/browser/native_window.cc
docs/api/browser-window.md

Add allowing-insecure-content option

---

docs/tutorial/application-packaging.md

'protect' implies a lot more security than ASAR provides (none). I asked around #2374 to get some understanding of what ASAR does do for you.

more accuracy around why to use ASAR

---

atom/browser/ui/tray_icon_cocoa.mm

* The title should be white when highlighted under light menu bar.
* The image should not be scaled when it is larger then menu bar.
* Fix a few leaks due to redundant calls of `retain`.
* Do not change status item's length for every draw.
* Do not create status item until we have setup the image view.
* Remove redundant draws before we set image for the tray icon.
* Do not call private APIs to detect dark menu bar.
* The title is not pure black under light menu bar.
* Adjustments of title and icon's margins.

mac: Make the tray icon behave more like the official one

---

atom/browser/api/atom_api_web_contents.cc
atom/browser/api/atom_api_web_contents.h
atom/browser/api/lib/web-contents.coffee
atom/common/api/api_messages.h
atom/renderer/atom_render_view_observer.cc
atom/renderer/atom_render_view_observer.h
docs/api/browser-window.md
docs/api/web-view-tag.md
spec/fixtures/pages/fullscreen.html
spec/webview-spec.coffee

render: executejavascript with option to create usergesture context

---

atom/renderer/api/atom_api_web_frame.cc
atom/renderer/api/atom_api_web_frame.h
docs/api/web-frame.md

Refs https://github.com/atom/electron/issues/2223

webFrame: api to make scheme bypass CSP

---

atom/browser/lib/guest-window-manager.coffee
atom/renderer/lib/override.coffee
spec/chromium-spec.coffee
spec/fixtures/pages/window-opener.html
spec/webview-spec.coffee

Only set window.opener for windows opened by window.open

---

atom/browser/atom_browser_client.cc
atom/browser/native_window.cc
atom/common/crash_reporter/crash_reporter_win.cc
atom/common/crash_reporter/win/crash_service.cc
atom/common/crash_reporter/win/crash_service.h
atom/common/crash_reporter/win/crash_service_main.cc

Fix crash reporter process not exiting if there is another one running

---

atom/browser/api/atom_api_content_tracing.cc
atom/browser/api/lib/content-tracing.coffee
docs/api/content-tracing.md

tracing: fix api and docs

---

atom/browser/native_window_mac.mm
spec/api-browser-window-spec.coffee

mac: Disable resizing window when changing style mask

---

atom/common/api/atom_api_native_image.cc

Close https://github.com/atom/electron/issues/2353.

Fix memory leak when creating NativeImage

---

atom/browser/lib/guest-view-manager.coffee
atom/browser/web_view_guest_delegate.cc
atom/browser/web_view_guest_delegate.h
atom/renderer/lib/override.coffee
atom/renderer/lib/web-view/guest-view-internal.coffee
atom/renderer/lib/web-view/web-view-attributes.coffee
atom/renderer/lib/web-view/web-view.coffee
docs/api/web-view-tag.md
spec/chromium-spec.coffee

webcontents: minor patches

---

atom/browser/api/atom_api_cookies.cc
atom/browser/api/atom_api_cookies.h
atom/browser/api/atom_api_protocol.cc
atom/browser/api/atom_api_protocol.h
atom/browser/api/atom_api_session.cc
atom/browser/api/atom_api_session.h
atom/browser/net/adapter_request_job.cc
atom/browser/net/adapter_request_job.h
atom/browser/net/url_request_fetch_job.cc
atom/browser/net/url_request_fetch_job.h

Force request context to initialize beforing incepting protocol

---

atom/browser/ui/win/notify_icon.cc

Fix some issues introduced by the PR #2328:
* Fixes #2468
* Fixes #2427
\cc @paulcbetts

Correct generation of GUID on Windows.

---

atom/browser/api/lib/web-contents.coffee
docs/api/browser-window-ko.md
docs/api/browser-window.md

Fix a typing error in option checking: printBackgrounds => printBackground

---

atom/browser/lib/guest-view-manager.coffee

Make sure guest view is destroyed immediately when embeder is closed

---

atom/browser/ui/file_dialog_gtk.cc
atom/browser/ui/file_dialog_mac.mm

Make dialog works on "*" file extension.

---

docs/development/coding-style.md

When I first tried to add something to the C++ code, I was a bit overwhelmed by all the special types and abstractions.
The info added will hopefully make it a bit easier to start, by directing users to the right place.

Update coding-style with info about Chromium's types

---

docs/tutorial/using-selenium-and-webdriver.md

Just fixed some wording issues and updated the example to use the promise based syntax of WebdriverIO

minor wording fix, updated example

---

atom/browser/lib/init.coffee
docs/tutorial/quick-start.md

Support index.js module resolution at startup of Electron.

---

atom/browser/native_window_mac.h
atom/browser/native_window_mac.mm

mac: Do not set rounded corner by adding layer

---

atom/browser/ui/tray_icon_cocoa.mm

mac: make tray's behavior more official when getting clicked quickly multiple times.

---

atom/browser/resources/win/atom.manifest

win: Add compatibility information in manifest file

---

docs/api/remote.md

Remote is a great feature, it's a shame to put people off unnecessarily. I think the original warnings given are too extreme
The potential bugs that stem from not cleaning up event handlers (or any reference) are present in any Javascript code. We don't avoid using event-handlers in the DOM because we might forget to clean them up!
I've added an example of the behaviour of return values from synchronously called callbacks from renderer, and have changed the advice from 'you shouldn't do this' to 'be careful when you do this'.

[docs] improve advice on callbacks passed from renderer to main

---

atom/renderer/atom_renderer_client.cc

renderer: send referrer for all naviagtions

---

atom/common/api/atom_bindings.cc
docs/api/app.md
docs/api/process.md

process: api to set file descriptor soft limit

---

chromium_src/chrome/browser/printing/print_job.cc

Fix print spooler hangs when printing more than 3 pages on Windows.

---

atom/browser/api/atom_api_session.cc
atom/browser/api/atom_api_session.h
atom/browser/api/atom_api_web_contents.h
atom/browser/api/lib/app.coffee
atom/common/node_bindings.cc
docs/api/app.md
docs/api/session.md

app: add will-download event to defaultSession

---

docs/api/native-image.md
docs/api/power-monitor.md
docs/api/power-save-blocker.md
docs/api/process.md

Next batch of docs re: [styleguide](https://github.com/atom/electron/blob/master/docs/styleguide.md).

Standardize Docs: native-image, power-monitor, power-save-blocker, process

---

docs-translations/zh-CN/development/atom-shell-vs-node-webkit.md
docs-translations/zh-CN/development/coding-style.md

- development/coding-style
- development/atom-shell-vs-node-webkit

Add docs-translations for zh-CN

---

docs-translations/zh-TW/tutorial/online-offline-events.md

Add zh-tw translation of docs-translations/zh-TW/tutorial/online-offline-events.md

---

atom/browser/api/atom_api_web_contents.cc
atom/browser/api/atom_api_web_view_manager.cc
atom/browser/atom_browser_client.cc
atom/browser/atom_browser_main_parts.cc
atom/browser/atom_browser_main_parts.h
atom/browser/lib/guest-view-manager.coffee
atom/browser/web_view_constants.cc
atom/browser/web_view_constants.h
atom/browser/web_view_guest_delegate.cc
atom/browser/web_view_manager.cc
atom/browser/web_view_manager.h
docs/api/web-view-tag.md
filenames.gypi
spec/fixtures/pages/partition/one.html
spec/fixtures/pages/partition/two.html
spec/webview-spec.coffee

Depends on https://github.com/atom/brightray/pull/136
Fixes #1010

webview: partition attribute

---

docs-translations/zh-TW/README.md
docs-translations/zh-TW/api/ipc-main-process.md
docs-translations/zh-TW/api/shell.md

- Add api/shell.md docs zh-TW translations
- Add api/ipc-main-process docs zh-TW translations
- Fix typos in zh-TW README docs

Add api/ipc-main-process docs zh-TW translations

---

atom/renderer/atom_renderer_client.cc
atom/renderer/node_array_buffer_bridge.cc
atom/renderer/node_array_buffer_bridge.h
filenames.gypi
script/lib/config.py

Support creating externalized ArrayBuffer for node::Buffer

---

atom/app/atom_main_delegate.cc
spec/node-spec.coffee
spec/static/main.js

Fix exception when accessing process.stdout

---

docs-translations/zh-TW/api/power-monitor.md
docs-translations/zh-TW/api/power-save-blocker.md

- add doc translation for power-monitor.md
- add doc translation for power-save-blocker.md

Add doc translation in zh-TW

---

atom/browser/api/atom_api_window.cc
spec/chromium-spec.coffee
spec/fixtures/pages/window-opener-node.html

Fix backward compatibility with old BrowserWindow options

---

atom/browser/api/atom_api_cookies.h
atom/browser/api/atom_api_protocol.h
atom/browser/atom_browser_main_parts.cc
atom/browser/atom_browser_main_parts.h
atom/browser/net/js_asker.h

Fix session not getting persisted on exit

---

spec/api-browser-window-spec.coffee
spec/fixtures/api/blank.html
spec/fixtures/api/preload.html
spec/fixtures/module/send-later.js
spec/static/main.js

Fix "node-integration" not working in "web-preferences"

---

atom/browser/api/lib/browser-window.coffee
docs/api/app.md
spec/api-app-spec.coffee

Add browser-window-created event for app module

---

docs-translations/ko/api/frameless-window.md
docs-translations/ko/api/menu.md

* Update as upstream (ko docs)

Update as upstream

---

atom/browser/api/atom_api_app.cc
atom/browser/api/atom_api_app.h
atom/browser/api/lib/app.coffee
atom/browser/browser.cc
atom/browser/browser.h
atom/browser/browser_observer.h
atom/browser/mac/atom_application_delegate.mm
docs/api/app.md

Implement 'activate' event for app.

---

atom/browser/api/atom_api_window.cc
atom/browser/api/atom_api_window.h
atom/browser/native_window.cc
atom/browser/native_window.h
docs/api/browser-window.md

Add BrowserWindow.isDevToolsFocused and fix "devtools-focused" not working

---

atom/browser/net/url_request_buffer_job.cc
atom/browser/net/url_request_buffer_job.h
atom/browser/net/url_request_string_job.cc
atom/browser/net/url_request_string_job.h
spec/api-protocol-spec.coffee

protocol: respect provided mimetype in generated response headers

---

atom/browser/api/atom_api_window.cc

Release the resources of native window immediately when it is closed

---

atom.gyp
spec/fixtures/module/set-immediate.js
spec/node-spec.coffee

Fixes #2755, also contains [a patch](https://github.com/atom/node/commit/aa9c7a2316ba7762f1d04d091585695be3e6be22) that fixes #2799.

Update to node v4.1.0

---

atom/browser/api/atom_api_web_contents.cc
atom/browser/api/atom_api_web_contents.h
docs/api/web-contents.md

Add two methods to webContents to enable/disable device emulation.

Add device emulation

---

script/create-dist.py

Refs https://github.com/atom/libchromiumcontent/issues/137.

Add Chromium's licenses to the dist

---

atom/common/lib/asar.coffee

Noticed it in Atom's console.
Related https://github.com/atom/atom/issues/8834#issuecomment-141353594

Fix a typo

---

atom/browser/api/atom_api_web_contents.cc
docs/api/web-contents.md

Add http_response_code, method, referrer, response_headers to did-get-redirect-request event.

More infos on did-get-redirect-request event

---

atom/renderer/api/atom_api_web_frame.cc
atom/renderer/api/atom_api_web_frame.h
docs/api/web-frame.md

webframe: api to register scheme as privileged

---

atom/browser/api/atom_api_web_contents.cc
atom/browser/api/atom_api_web_contents.h
atom/browser/api/atom_api_window.cc
atom/browser/lib/guest-window-manager.coffee
atom/browser/web_contents_preferences.cc
atom/browser/web_contents_preferences.h
docs/api/window-open.md
spec/chromium-spec.coffee
spec/fixtures/pages/window-open-size.html

Inherit parent window's options in window.open

---

atom/browser/lib/guest-window-manager.coffee
atom/renderer/lib/web-view/guest-view-internal.coffee
docs/api/web-contents.md
docs/api/web-view-tag.md

Pass options in "new-window" event

---

atom/common/asar/archive.cc
atom/common/asar/archive.h
spec/api-browser-window-spec.coffee
spec/asar-spec.coffee

win: Fix leaking of fd when reading file in asar

---

script/lib/config.py
spec/modules-spec.coffee

Fix crash when using ffi

---

atom/browser/native_window.cc
spec/chromium-spec.coffee
spec/fixtures/pages/document-hidden.html

browser: notify webcontents hidden when window not shown

---

atom/browser/native_window.cc
atom/browser/native_window.h
atom/browser/native_window_mac.mm

Make draggable region work for window with hidden titlebar

---

atom/browser/api/atom_api_session.cc
atom/browser/api/atom_api_session.h
docs/api/session.md

Fixes #2874 
Depends on https://github.com/atom/brightray/pull/145

session: api to emulate network conditions

---

docs/api/web-contents.md

Add more detailed documentation about the format of frameBuffer (FrameSubscription API)

---

atom/browser/atom_browser_client.cc
atom/browser/atom_browser_client.h
atom/browser/atom_browser_resource_dispatcher_host_delegate.cc
atom/browser/atom_browser_resource_dispatcher_host_delegate.h
filenames.gypi

protocol: allowing default clients to handle external unhandled protocols

---

atom/browser/native_window.cc
atom/browser/native_window_mac.mm
atom/browser/native_window_views.cc
atom/renderer/lib/override.coffee

Fix the regression of outerHeight and outerWidth being set to 0 in hidden window

---

docs-translations/ko-KR/api/menu.md
docs-translations/ko-KR/api/screen.md
docs-translations/ko-KR/api/session.md
docs-translations/ko-KR/tutorial/quick-start.md

* Update as upstream
* Improve grammar
* Small changes

Update as upstream, improve grammar

---

README.md

supported operating system list

---

docs/tutorial/supported-platforms.md

I've tweaked a bit of grammar that was bugging me. Mostly so I could learn a bit about how GitHub works. Hope that's OK.

Minor grammar correction

---

atom/browser/atom_browser_main_parts.cc
atom/browser/atom_browser_main_parts.h
atom/browser/atom_browser_main_parts_posix.cc
atom/browser/browser.cc
atom/browser/browser.h
filenames.gypi

Quit gracefully when Ctrl-C is pressed

---

atom/browser/api/atom_api_web_contents.cc
atom/browser/api/atom_api_web_contents.h
atom/common/api/api_messages.h
atom/renderer/api/atom_api_web_frame.cc
atom/renderer/atom_renderer_client.cc

Fixes #940 
One possible way as discussed with @zcbenz

webcontents: notify guests of embedders' zoom level change

---

atom/browser/api/atom_api_web_contents.cc

webcontents: dont modify response header value

---

atom/browser/default_app/index.html
atom/browser/default_app/main.js

This pull request implement the idea described in #1877
It worked quite well together with the webdriverio module.
There are currently no tests included because I didn't found the right place.
Maybe someone can point me to the right location so I can attach the tests to the pull request.
cheers Jan

add a --app parameter to the default_app

---

atom/browser/api/atom_api_web_contents.cc

Fixes #3034 
Related https://github.com/atom/brightray/pull/154

browser: get accept-language header from system locale

---

atom/common/native_mate_converters/v8_value_converter.cc
atom/common/native_mate_converters/v8_value_converter.h

nativemate: handle binary types in v8 value conversion

---

docs-translations/zh-CN/api/ipc-main-process.md

add doc-translations/zh-CN/api/ipc-main-process

doc-translations-zh-CN

---

atom/browser/api/atom_api_session.cc
atom/browser/api/atom_api_web_contents.cc
atom/browser/api/atom_api_web_contents.h
atom/browser/api/save_page_handler.cc
atom/browser/api/save_page_handler.h
docs/api/web-contents.md
filenames.gypi
spec/api-browser-window-spec.coffee

Implement webContents.savePage API.

---

docs/api/frameless-window.md

:memo:
Replace webp with web in frameless-window.md .

[Tiny correction of misspelling]

---

atom/browser/atom_ssl_config_service.cc
atom/common/options_switches.cc
atom/common/options_switches.h
docs/api/chrome-command-line-switches.md

browser: flag to disable specified cipher suites

---

docs/api/app.md

Some little fixes from my side. :book: :dizzy:

Doc improvements

---

atom/app/atom_library_main.mm
atom/app/node_main.cc
atom/app/uv_task_runner.cc
atom/app/uv_task_runner.h
atom/browser/javascript_environment.cc

Turns out #2889 is caused by memory corruption when cleaning timer.
Fix #2889.

Fix memory corruption when cleaning timer

---

atom/browser/native_window_views.cc
atom/common/options_switches.cc
atom/common/options_switches.h
docs/api/browser-window.md

browser: option to set window background color

---

atom/browser/api/atom_api_session.cc
atom/browser/api/atom_api_session.h
docs/api/session.md

session: allow setproxy to use external pac script

---

atom/browser/api/atom_api_window.cc
atom/browser/api/atom_api_window.h
atom/browser/native_window.cc
atom/browser/native_window.h
atom/browser/native_window_mac.h
atom/browser/native_window_mac.mm
atom/browser/native_window_views.cc
atom/browser/native_window_views.h
docs/api/browser-window.md

Also adds a setBackgroundColor method.
Refs #861.

Make background-color work on Windows 

---

atom/browser/api/lib/auto-updater.coffee
atom/browser/api/lib/auto-updater/auto-updater-win.coffee
atom/browser/api/lib/auto-updater/squirrel-update-win.coffee
filenames.gypi

Most of this has just been extracted from https://github.com/atom/atom. The Api of the current Mac autoupdater is kept. Feedback would be greatly appreciated.

Windows Auto Updater

---

docs/tutorial/using-native-node-modules.md

Updated docs to better understand how to use electron-rebuild on Windows

Updated docs

---

docs-translations/es/tutorial/quick-start.md

Remove english words in description

---

docs-translations/es/development/coding-style.md

Add coding style spanish translation

---

docs-translations/es/README.md
docs-translations/es/development/source-code-directory-structure.md

Add source code directory structure spanish translation

---

script/lib/config.py

Update libchromiumcontent: fix private API call

---

docs/api/app.md

* Remove extra spaces in `app.md`

Remove extra spaces

---

docs/api/auto-updater.md

Fix minor grammatical mistakes, correct sentence structures, and improve readability.

Update auto-updater.md to improve readability

---

atom/browser/api/atom_api_app.cc
atom/browser/api/atom_api_protocol.cc
atom/browser/api/atom_api_web_contents.cc
atom/browser/api/atom_api_web_contents.h
atom/browser/api/lib/web-contents.coffee
atom/common/native_mate_converters/content_converter.cc
atom/common/native_mate_converters/content_converter.h
atom/common/native_mate_converters/net_converter.cc
atom/common/native_mate_converters/net_converter.h
filenames.gypi

Fixes #3255 
Depends on resolving https://github.com/zcbenz/native-mate/commit/b7387da0854b20d376fdae0d93a01f83d080668d#commitcomment-14109076
Also have only converted data required for handling pepper flash menu in the `contextmenuconverter`

browser: handle flash context menu request

---

atom/common/crash_reporter/crash_reporter_win.cc

On some machines this call will fail and CHECK will abort the application.
Fix #3276.
Fix #3191.

win: Guard against failure of RtlAddFunctionTable

---

atom/browser/api/lib/app.coffee
atom/browser/api/lib/atom-delegate.coffee
atom/browser/api/lib/browser-window.coffee
atom/browser/lib/chrome-extension.coffee
atom/common/api/atom_bindings.cc
atom/common/api/lib/deprecate.coffee
atom/renderer/api/lib/ipc.coffee
filenames.gypi

Show warnings for deprecated APIs

---

docs/tutorial/desktop-environment-integration.md

Nothing fancy - just a little markdown documenting the Notification API.

Document Notifications

---

docs/api/ipc-main.md

Standardize the webContents object names

---

atom/browser/api/atom_api_tray.cc
atom/browser/api/atom_api_tray.h
atom/browser/ui/tray_icon.cc
atom/browser/ui/tray_icon.h
atom/browser/ui/tray_icon_cocoa.mm
atom/browser/ui/tray_icon_observer.h
docs/api/tray.md

Add drag-entered and drag-exited events to Tray

---

docs/tutorial/using-selenium-and-webdriver.md

Inspired by https://github.com/atom/electron/issues/1877#issuecomment-145488955
Such documentation that would have been helpful to me as I was learning how to use WebdriverIO.

Suggest adding arguments when running webdriver

---

atom/browser/api/atom_api_app.cc
atom/browser/native_window.cc
atom/common/native_mate_converters/file_path_converter.h
docs/api/app.md
docs/api/content-tracing.md

Fixes #3394
Fixes #3380
Ref #3413

Minor patches

---

docs-translations/zh-CN/README.md
docs-translations/zh-CN/development/source-code-directory-structure.md
docs/development/atom-shell-vs-node-webkit.md

Hi I just did some work on zh-CN docs
Feel free to let me know whether something is not qualified for merge, thanks~

Fix a dead link and add a new Chinese document translation

---

docs-translations/es/tutorial/quick-start.md
docs-translations/jp/quick-start.md
docs-translations/pt-BR/tutorial/quick-start.md
docs-translations/zh-CN/tutorial/quick-start.md
docs-translations/zh-TW/tutorial/quick-start.md

[Doc update]: Use loadURL since loadUrl is deprecated

---

atom/browser/lib/rpc-server.coffee

Spent a while tracking down an exception `"Error processing argument -1"`, which turned out to be caused by a missing param on a function call. (`app.exit()` now takes an exit code.) 
This PR traps these sort of exceptions and adds the function name when possible, so it's much easier to identify which remote call is causing the error.

Improve exception messages from remote calls

---

atom/browser/net/url_request_fetch_job.cc

protocol: handle http responses with no content

---

atom/app/atom_main.cc
docs/README.md
docs/api/environment-variables.md

Close #3434.
Also add some docs on other environment variables.

Add ELECTRON_RUN_AS_NODE environment variable

---

docs-translations/pt-BR/api/app.md

Didn't find a decent translation to a few words, such as "badging", "parse", etc.

:memo: [ci skip] Add translation to app.md

---

atom/browser/api/atom_api_tray.cc
atom/browser/ui/tray_icon.cc
atom/browser/ui/tray_icon.h
atom/browser/ui/tray_icon_cocoa.h
atom/browser/ui/tray_icon_cocoa.mm
atom/browser/ui/win/notify_icon.cc
atom/browser/ui/win/notify_icon.h
atom/browser/ui/win/notify_icon_host.cc
docs/api/tray.md

Add `menu` parameter for Tray.popUpContextMenu

---

atom/browser/browser_win.cc
atom/browser/ui/file_dialog_win.cc
atom/common/crash_reporter/crash_reporter_win.cc
atom/common/crash_reporter/win/crash_service.cc
atom/common/crash_reporter/win/crash_service_main.cc
chromium_src/chrome/browser/speech/tts_win.cc
chromium_src/chrome/renderer/printing/print_web_view_helper_pdf_win.cc
chromium_src/net/test/embedded_test_server/stream_listen_socket.cc

Port Chrome47 on Windows

---

atom/browser/ui/file_dialog_gtk.cc
atom/browser/ui/views/menu_bar.cc
chromium_src/chrome/browser/speech/tts_linux.cc
chromium_src/chrome/browser/ui/views/frame/global_menu_bar_registrar_x11.cc
chromium_src/chrome/browser/ui/views/frame/global_menu_bar_registrar_x11.h

Port Chrome47 on Linux

---

docs-translations/pt-BR/development/build-instructions-linux.md

:memo: [ci skip] translation build instructions

---

atom/browser/mac/atom_application_delegate.mm

Thanks @jasongrlicky for finding out the fix.
Close #3038.

Don't add the "Enter Full Screen" menu item automatically

---

appveyor.yml

We have bought its paid plan, each test takes about 10min to run, not very fast but better than travis ci's mac machine.

Run tests on Appveyor

---

atom/browser/lib/guest-window-manager.coffee
atom/renderer/lib/override.coffee
spec/chromium-spec.coffee
spec/fixtures/pages/window-open-postMessage.html

Use source origin instead of target origin in event.
Closes #3691

Fix window.postMessage event.origin value

---

atom/browser/api/atom_api_cookies.cc
atom/browser/api/atom_api_cookies.h
atom/browser/api/atom_api_web_contents.cc
atom/browser/api/atom_api_web_request.cc
atom/browser/api/atom_api_web_request.h
atom/browser/api/lib/session.coffee
atom/browser/net/atom_network_delegate.cc
atom/browser/net/atom_network_delegate.h
atom/common/native_mate_converters/net_converter.cc
atom/common/native_mate_converters/net_converter.h
docs/api/session.md
spec/api-session-spec.coffee
spec/api-web-request-spec.coffee
spec/chromium-spec.coffee

* Reorganize the code with some C++ tricks.
* Improve the docs.
* Add more specs.

Cleanup the webRequest and cookies code

---

script/lib/config.py

Backport https://codereview.chromium.org/1406133003

---

atom/browser/native_window.cc

browser: dont lose coordinates in capturepage src rect

---

atom/browser/api/lib/exports/electron.coffee
atom/browser/lib/guest-window-manager.coffee
atom/browser/lib/rpc-server.coffee
atom/browser/web_contents_preferences.cc
atom/common/api/lib/exports/electron.coffee
atom/common/options_switches.cc
atom/common/options_switches.h
atom/renderer/api/lib/exports/electron.coffee
atom/renderer/api/lib/remote.coffee
atom/renderer/lib/init.coffee
atom/renderer/lib/override.coffee

It should make the window show faster.

Remove usages of synchronous messages on startup

---

atom/browser/browser_mac.mm

Implemented workaround in DockShow for TransformProcessType bugginess based on discussion at http://stackoverflow.com/questions/7596643/

DockShow workaround for issue #3739

---

spec/chromium-spec.coffee
spec/fixtures/pages/service-worker/index.html
spec/fixtures/pages/service-worker/service-worker.js

Just for sanity to address https://github.com/atom/electron/issues/2831#issuecomment-166129642

spec: serviceWorker registration with file scheme

---

atom/browser/api/atom_api_web_contents.cc
atom/browser/api/atom_api_web_contents.h
atom/browser/lib/guest-view-manager.coffee
atom/common/native_mate_converters/blink_converter.cc
atom/common/native_mate_converters/blink_converter.h
atom/common/native_mate_converters/content_converter.cc
atom/common/native_mate_converters/content_converter.h
atom/renderer/lib/web-view/guest-view-internal.coffee
atom/renderer/lib/web-view/web-view.coffee
docs/api/web-contents.md
docs/api/web-view-tag.md
spec/fixtures/pages/content.html
spec/webview-spec.coffee

webContents: adding findInPage api

---

docs/api/app.md

This looks a bit odd on the site: http://electron.atom.io/docs/v0.36.0/api/app/#app-setusertasks-tasks-windows

Formatting app.md

---

atom/browser/native_window_mac.h
atom/browser/native_window_mac.mm

This PR Fixes the visual artifacts of hidden-inset window when entering and leaving fullscreen mode.
Refs #3890.

Fix visual artifacts of hidden-inset window

---

atom/browser/api/atom_api_web_contents.cc
atom/browser/api/atom_api_web_contents.h
atom/browser/lib/guest-view-manager.coffee
atom/renderer/lib/web-view/guest-view-internal.coffee
docs/api/web-contents.md
docs/api/web-view-tag.md
spec/fixtures/pages/theme-color.html
spec/webview-spec.coffee

This adds an event to webviews for when meta tags with a theme-color are encountered.

Theme color

---

script/create-dist.py

Refs https://github.com/atom/brightray/pull/186.

No longer need to ship with libnotify.so

---

atom/browser/native_window_views.cc

linux: Fix pressing Alt not toggling window menu bar

---

atom/common/platform_util_mac.mm

Fix converting string to NSURL

---

atom/common/platform_util_win.cc

Fixes #3656 by adding a Windows version check and using a different set of operations flags for Windows Vista/7.

Adding check for Windows version and alternate flags for Windows Vista/7

---

atom/browser/net/atom_network_delegate.cc
spec/api-web-request-spec.coffee
spec/chromium-spec.coffee

onBeforeSendHeaders should reset the whole headers

---

atom/common/api/atom_api_v8_util.cc
atom/renderer/api/lib/remote.coffee

Fix memory leak in remote module

---

atom/browser/browser_mac.mm

osx: Implement clear recent documents

---

atom/browser/lib/rpc-server.coffee
atom/renderer/api/lib/remote.coffee
spec/api-ipc-spec.coffee
spec/fixtures/module/print_name.js

remote: support arguments of type Date

---

atom.gyp
atom/app/atom_content_client.cc
atom/app/atom_content_client.h

Fixes #3925 
Depends on
https://github.com/atom/brightray/pull/189
https://github.com/atom/libchromiumcontent/pull/169
Have tested only on linux, should work in other platforms too, just need verification on the shipping of locale.

browser: provide localized string from resourcebundle

---

atom/common/lib/asar.coffee
spec/asar-spec.coffee
spec/package.json
spec/webview-spec.coffee

Throw ENOTDIR when calling mkdir inside asar archive

---

docs/tutorial/debugging-main-process.md

Add info on how to debug from 0.30 onwards

---

atom/browser/net/url_request_fetch_job.cc

Fix crash when request failed

---

atom/browser/native_window_mac.mm

Fix hiding fullscreen button on EL Capitan

---

atom.gyp
atom/app/atom_main_delegate.cc
atom/app/atom_main_delegate.h
atom/browser/atom_browser_main_parts_mac.mm
tools/mac/copy-locales.py

Refs #3925, the #3958 only fixes Windows and Linux sides, this PR also fixes the locale on OS X.
Also fixes #3754.

Fix loading locale on OS X

---

script/lib/config.py

Refs https://github.com/atom/libchromiumcontent/issues/170.

Backport https://codereview.chromium.org/1500713003

---

docs/api/remote.md

Add documentation update to sppt #4024

Specify enumerable property accessibility

---

docs/api/menu.md

in line 201 at menu.md, 
should be ```var menu = Menu.buildFromTemplate(template);```

missing "var" in line 201 menu.md

---

atom/browser/api/atom_api_session.cc
atom/browser/api/atom_api_session.h
docs/api/session.md

session: api to flush DOMStorage data

---

docs/api/ipc-main.md
docs/api/ipc-renderer.md

Detail ipc.removeListener & ipc.removeAllListeners

---

atom/renderer/lib/web-view/web-view-attributes.js

webview: respect properties provided during webview creation

---

atom/browser/api/atom_api_session.cc
atom/browser/api/atom_api_session.h
docs/api/session.md

session: api to get current cache size

---

docs/api/ipc-main.md
docs/api/ipc-renderer.md

They were previously not written with the same style as other parts of
the doc. Also there was a couple grammar errors

Styled the removeListener & removeAllListeners

---

atom/browser/lib/guest-view-manager.js
atom/renderer/lib/web-view/web-view-attributes.js
atom/renderer/lib/web-view/web-view-constants.js
docs/api/web-view-tag.md

webview: add blinkfeatures attribute

---

atom/common/lib/asar.js
docs/api/environment-variables.md

Overview here: https://github.com/atom/atom/issues/10163

Add env var to export a hint file to optimize ASAR ordering

---

atom/browser/api/atom_api_window.cc
atom/browser/api/atom_api_window.h
atom/browser/native_window.cc
atom/browser/native_window.h
atom/browser/native_window_mac.h
atom/browser/native_window_mac.mm
atom/browser/native_window_views.cc
atom/browser/native_window_views.h
atom/browser/native_window_views_win.cc
atom/common/options_switches.cc
atom/common/options_switches.h
docs/api/browser-window.md
spec/api-browser-window-spec.js

Also change `win.setFullscreenable` to `win.setFullScreenable` to make names consistent with `win.setFullScreen`. 
Refs #4156.

Add tests for "-able" options and methods

---

atom/browser/api/atom_api_debugger.cc
atom/browser/api/atom_api_debugger.h
atom/browser/api/atom_api_web_contents.cc
atom/browser/api/atom_api_web_contents.h
atom/browser/api/lib/web-contents.js
atom/common/node_bindings.cc
docs/api/web-contents.md
filenames.gypi
spec/api-debugger-spec.js

For #4002 
@zcbenz is this api implementation fine or should debugger be made a separate module ?

browser: add webContents.debugger api

---

atom/browser/browser_mac.mm

Update name of paramter for consistency

---

atom/browser/api/atom_api_app.cc
atom/browser/api/lib/app.js
atom/browser/browser.h
atom/browser/browser_mac.mm
docs/api/app.md

It's related with #4084 and It's my first contribute that add a new feature so please let me know if something went wrong. I couldn't find any test for `app.dock` APIs. is it right?

Add app.dock.setIcon to change icon of dock

---

docs-translations/jp/api/chrome-command-line-switches.md
docs-translations/jp/api/frameless-window.md

Add Japanes translated docs.

---

docs-translations/jp/api/content-tracing.md
docs-translations/jp/api/protocol.md
docs-translations/jp/api/remote.md

:memo:Add Japanes translated docs.

---

spec/node-spec.js
spec/static/main.js

Fixes #3482.
```diff
diff --git a/src/node.js b/src/node.js
index 937200d..37aa371 100644
--- a/src/node.js
+++ b/src/node.js
@@ -649,6 +649,8 @@
// Probably an error on in uv_guess_handle()
throw new Error('Implement me. Unknown stream file type!');
}
+    // Ignore stream errors.
+    stream.on('error', function() {});
} catch (error) {
stream = createDevNull();
}
```

Ignore errors happened in Node's stdout/stdin stream

---

docs-translations/zh-TW/tutorial/supported-platforms.md

Add supported-platforms.md
Other pages are coming soon.

Add Traditional Chinese Translation Page

---

atom/common/api/lib/exports/electron.js
script/test.py
spec/api-app-spec.js

common: export hideInternalModules

---

atom/browser/net/atom_network_delegate.cc
atom/common/native_mate_converters/net_converter.cc
atom/common/native_mate_converters/net_converter.h
docs/api/session.md
spec/api-web-request-spec.js

session: provide uploadData with webrequest api when available

---

atom/browser/resources/mac/Info.plist
docs/tutorial/supported-platforms.md

OS X min version bump (10.8=>10.9)

---

docs-translations/pt-BR/tutorial/application-distribution.md

System Operation windows and not literal windows!

PT/BR Docs Translation: update the "janelas" to "windows"

---

atom/browser/browser_mac.mm

Fix type cast of sharedApplication

---

atom/renderer/lib/init.js
atom/renderer/lib/web-view/web-view.js

Fix 'user strict' typo

---

atom/browser/api/atom_api_session.cc
atom/browser/api/atom_api_session.h
docs/api/session.md

session: api to clear host resolver cache

---

atom/browser/api/atom_api_download_item.cc
atom/browser/api/atom_api_download_item.h
atom/browser/api/atom_api_session.cc
docs/api/session.md
spec/api-session-spec.js
spec/static/main.js

Fixes #4295 
`DownloadItem::Remove` will delete the instance.

fix crash when default download is canceled

---

atom/renderer/atom_renderer_client.cc
atom/renderer/atom_renderer_client.h
atom/renderer/lib/init.js

Emit exit event reliably in renderer process

---

docs-translations/es/tutorial/application-distribution.md
docs-translations/jp/tutorial/application-distribution.md
docs-translations/ko-KR/tutorial/application-distribution.md
docs-translations/pt-BR/tutorial/application-distribution.md
docs-translations/zh-CN/tutorial/application-distribution.md
docs-translations/zh-TW/tutorial/application-distribution.md
docs/tutorial/application-distribution.md

See #4357 for more details.
Closes #4357 
Refs https://github.com/atom/electron.atom.io/pull/141

Remove ResEdit link from docs

---

docs/api/app.md

Docs: app: small process.argv clarification

---

package.json

Adds a `bootstrap` and `build` script.
I was getting tired of typing `./script/build.py -c D` on the command line often.
/cc @jlord :eyes:

Add more npm scripts

---

docs/tutorial/using-selenium-and-webdriver.md

The relative path for Electron's binary is Contents/MacOS/Electron

Fix electron binary relative path

---

docs/api/clipboard.md

* Remove unnecessary line feeds on `clipboard.md`.

Remove unnecessary line feeds

---

atom/browser/ui/message_box_mac.mm

Use the icon when specified on the created `NSAlert`.
I tried to follow the same pattern as the [brightray notifications](https://github.com/atom/brightray/blob/2a5cd7178b641de91ca6eb0bca826fea588f923a/browser/mac/cocoa_notification.mm#L40-L45) but would love any feedback on any memory leak issues with this approach.
Closes #4073

Support configurable dialog icon on Mac

---

atom/browser/api/atom_api_web_contents.cc
spec/api-browser-window-spec.js

browser: emit did-fail-load for invalid url

---

docs/api/ipc-renderer.md
docs/api/web-contents.md

Docs - clarify ipc arguments

---

docs/faq/electron-faq.md
docs/tutorial/quick-start.md

This has been discussed in #403 and in #1095.

Document different techniques to share objects

---

docs/api/content-tracing.md

docs: fix a minor typo

---

docs/tutorial/desktop-environment-integration.md

Icon overlays is missing in desktop environment integration.

Docs: Add icon overlays in taskbar

---

README.md
docs-translations/fr-FR/README.md
docs-translations/fr-FR/faq/electron-faq.md
docs-translations/fr-FR/styleguide.md

Here is a starting point for the french translation.
I'll try to do the remaining files in the following weeks.

Docs: Start french translation

---

docs/api/app.md
docs/api/browser-window.md
docs/api/web-view-tag.md

Found & corrected with https://github.com/lukeapage/node-markdown-spellcheck

spelling fixes and americanisms

---

docs-translations/zh-CN/api/file-object.md

tanslate `docs/api/file-object.md` into Chinese

tanslate file-object.md

---

atom.gyp
script/lib/config.py

Refs:
https://github.com/atom/libchromiumcontent/pull/181
https://github.com/atom/libchromiumcontent/issues/174

Link with ffmpeg dynamically

---

script/lib/config.py

Refs https://github.com/atom/libchromiumcontent/pull/180.

Update libchromiumcontent, fix #3666

---

atom/browser/native_window_mac.mm

Usually cmd+~ should be handled by OS X completely, but sometimes it would just pass the event to us, when this happens, we should simulate the behavior of cmd+~.
Fix #4512.

mac: Simulate the behavior of cmd+~ when OS X didn't handle it

---

docs/api/app.md

Added link to documentation about `Menu` objects

Link to Menu documentation

---

script/create-dist.py
script/lib/config.py
script/upload.py

Refs https://github.com/atom/libchromiumcontent/issues/174.

Provide ffmpeg binaries without proprietary codecs

---

atom/renderer/api/lib/remote.js
spec/api-ipc-spec.js

remote: return webcontents instance from cache

---

package.json

to get the deps badge green again :)

a new version of asar is out 0.10.0

---

atom/browser/api/atom_api_web_contents.cc
atom/browser/lib/objects-registry.js
atom/browser/lib/rpc-server.js
atom/common/api/atom_api_v8_util.cc
atom/renderer/api/lib/remote.js

Removes a bunch of unused code.

Cleanup code of remote module

---

docs-translations/zh-CN/tutorial/debugging-main-process.md

update zh-CN doc debugging-main-process.md to be up-to-date with
English ver.

docs: update zh-CN doc debugging-main-process.md

---

docs-translations/jp/api/ipc-renderer.md

docs: update jp doc ipc-renderer.md

---

atom/browser/native_window_views.cc
atom/browser/ui/views/global_menu_bar_x11.cc
atom/browser/ui/views/global_menu_bar_x11.h

Notify the global menu bar when window is mapped

---

docs-translations/zh-CN/README.md
docs-translations/zh-CN/api/accelerator.md
docs-translations/zh-CN/api/app.md
docs-translations/zh-CN/api/auto-updater.md
docs-translations/zh-CN/faq/electron-faq.md

Based on commit 45739ce434ec3c3eb190d35d3948b702b54706cd
- README.md
- electron-faq.md
- accelerator.md
- app.md
- auto-updater.md

docs: update zh-CN docs translation [WIP]

---

atom/browser/api/atom_api_protocol.cc
atom/browser/api/atom_api_protocol.h
atom/browser/api/atom_api_session.cc
atom/browser/api/atom_api_session.h
atom/browser/api/lib/protocol.js
atom/common/node_bindings.cc
docs/api/session.md
spec/api-protocol-spec.js

It currently has two crashes:
* Crash on exit on Linux;
* Crash when actually using it for multi-session on other platforms.
/cc @deepak1556

Revert  #4551

---

atom/browser/api/atom_api_web_contents.cc
atom/browser/api/atom_api_web_contents.h
atom/common/native_mate_converters/content_converter.cc
atom/renderer/lib/web-view/web-view.js
docs/api/web-contents.md
docs/api/web-view-tag.md
spec/webview-spec.js

webview: api to get host browser window

---

script/lib/config.py

Use harfbuzz 1.06

---

atom/common/native_mate_converters/v8_value_converter.cc
atom/common/native_mate_converters/v8_value_converter.h
spec/api-ipc-spec.js

ipc: allow passing date instances

---

docs-translations/jp/api/menu.md
docs-translations/ko-KR/api/menu.md
docs/api/menu.md

`electron.app` is only available in the main process.

Fix Menu template API example

---

atom/browser/api/atom_api_web_contents.cc
atom/browser/api/atom_api_web_contents.h
spec/chromium-spec.js

Fixes #4613 
Regression from https://github.com/atom/electron/pull/4223 .

browser: allow enumeration of media device labels

---

docs-translations/jp/README.md

Many docs are translated into Japanese but didn't add to readme(index) so I add.

Update docs-translations/jp/README.md tranlation.

---

docs/tutorial/testing-on-headless-ci.md

* Adjust 80 chars per line
* Line feed after header

Docs: Cleanup docs

---

atom/browser/api/atom_api_app.cc

Fix passing certificate to select-client-certificate's callback

---

atom/browser/api/lib/menu-item.js

Protect platform specific API by adding predicate

Add platform predicate for menu item action

---

atom/browser/ui/accelerator_util.cc
atom/common/keyboard_util.cc
atom/common/keyboard_util.h
atom/common/native_mate_converters/blink_converter.cc
docs/api/accelerator.md
docs/api/web-contents.md

Remove duplicated keyboard code

---

atom/browser/native_window_mac.mm

An attempt to fix #4577 
Not sure if there is a better way but this worked for me and simplified the implementation and worked for both directions (forward and reversed).
/cc @zcbenz @joshaber @jlord

Use sendAction for cycling windows

---

atom/browser/api/atom_api_app.cc
atom/browser/api/atom_api_app.h
atom/browser/browser.cc
atom/browser/browser.h
atom/browser/browser_mac.mm
atom/browser/browser_observer.h
atom/browser/mac/atom_application_delegate.mm
docs/api/app.md

Add API to check OSX's Dark theme

---

spec/asar-spec.js

Adding specs for #4610 although they currently pass and after talking with @paulcbetts we are going to close that issue as things appear to be currently working. :green_apple:

Add specs for realpath of unpacked asar path

---

atom/browser/api/lib/menu.js
atom/browser/atom_browser_main_parts.h
atom/browser/ui/views/global_menu_bar_x11.h
atom/common/crash_reporter/win/crash_service.cc
chromium_src/chrome/browser/chrome_notification_types.h

This PR fixes some typos in comments.

Fix typos in comments.

---

atom/browser/api/atom_api_window.cc
atom/browser/api/atom_api_window.h
atom/browser/native_window.cc
atom/browser/native_window.h
atom/browser/native_window_mac.mm
atom/browser/native_window_observer.h
atom/browser/native_window_views.cc
docs/api/browser-window.md
lib/browser/api/browser-window.js
lib/renderer/api/ipc-renderer.js
lib/renderer/inspector.js
lib/renderer/override.js
spec/api-browser-window-spec.js

Cache browser visibility state & emit visibilitychange event on change

---

atom/browser/api/atom_api_window.cc
atom/browser/api/atom_api_window.h
docs/api/browser-window.md
spec/api-browser-window-spec.js

Attempt to fix #4724 based on @zcbenz's [comment](https://github.com/atom/electron/issues/4724#issuecomment-195143681) (admittedly without knowing much of anything about C++ :grimacing:)

Add blur method to window

---

script/create-dist.py

Since we are now using sysroot for building by default, there is no need to copy system libraries anymore, we can assume the sysroot images will solve the library linking problems for us.

Do not copy system libraries on Linux

---

docs-translations/ko-KR/api/browser-window.md

Docs: Update Korean docs as upstream

---

atom/browser/atom_browser_client.cc
atom/browser/atom_permission_manager.cc

browser: fix retrieving webcontents from associated process id

---

atom/browser/api/atom_api_web_contents.cc
docs/api/web-contents.md
docs/api/web-view-tag.md
spec/webview-spec.js

webcontents: provide position of match with found-in-page event

---

atom/browser/ui/file_dialog_gtk.cc

Add extension to filename automatically for GTK+ save dialog

---

atom/browser/atom_browser_context.cc
atom/browser/common_web_contents_delegate.cc
atom/browser/common_web_contents_delegate.h
chromium_src/chrome/common/pref_names.cc
chromium_src/chrome/common/pref_names.h

Fixes #4798 
Depends on https://github.com/atom/brightray/pull/204

devtools: update filesystem api

---

docs/api/crash-reporter.md

In case there are people wanting to implement a server themselves.

List breakpad server implementations in crashReporter docs

---

docs/tutorial/debugging-main-process.md

Docs: Correct link anchor

---

docs/development/build-instructions-osx.md
docs/development/build-system-overview.md
docs/faq/electron-faq.md

Just making my way through the documentation, cleaning up typos and stuff.
📚

[WIP] Docs cleanup

---

lib/browser/api/app.js
lib/browser/api/dialog.js
lib/browser/api/navigation-controller.js
lib/browser/api/web-contents.js
lib/browser/guest-view-manager.js
lib/browser/guest-window-manager.js
lib/browser/init.js
lib/common/api/callbacks-registry.js
lib/common/api/deprecate.js
lib/renderer/api/ipc-renderer.js
lib/renderer/api/ipc.js
lib/renderer/override.js
lib/renderer/web-view/guest-view-internal.js
lib/renderer/web-view/web-view.js

Migrate old CoffeeScript usage of `args...` to the new ES6 supported `...args`
Refs #4065

Use rest parameters

---

lib/renderer/override.js

Adds two more camel case options to the ints array.
This is a minor follow up to #4829 
Thanks @kfranqueiro for reviewing and noticing these were missing :+1:

Add minWidth and maxWidth to ints array

---

docs/api/menu.md

Some Menu methods are instance methods, also items is a property.

Fix Menu documentation

---

docs/api/app.md

I guess it was implemented in https://github.com/atom/electron/commit/5670ee7693dc4f3cb6bb95131752852693b71eec.

Document `app.setName()`

---

atom/common/api/object_life_monitor.cc
atom/common/api/object_life_monitor.h

@mitchhentges Can you try if this fixes #4733 for you? I can't reproduce the original issue so I'm not able to try it myself.

Run callback of setDestructor immediately when GC happens

---

docs/faq/electron-faq.md

Add "black background?" to FAQ

---

docs/api/power-monitor.md
docs/faq/electron-faq.md
docs/tutorial/desktop-environment-integration.md

* Adjust line length to `80`
* Change platform marker `*` to `_`
* Enhance a note section

Docs: Update docs styles

---

docs/api/app.md

docs: Add notes on app.getLocale

---

atom/browser/net/url_request_fetch_job.cc

Fixes #4928 
Behavior was changed here https://codereview.chromium.org/1467603002

protocol: return status of ReadRawData instead of relying on SetStatus

---

docs/api/dialog.md

Add "remote" note to dialog docs

---

docs/api/app.md
docs/api/auto-updater.md
docs/api/ipc-renderer.md
docs/api/tray.md
docs/development/setting-up-symbol-server.md
docs/tutorial/debugging-main-process.md
docs/tutorial/desktop-environment-integration.md
docs/tutorial/mac-app-store-submission-guide.md
docs/tutorial/using-widevine-cdm-plugin.md

* Normalize note markers
* Normalize whitespaces
* Adjust line length to `80`

Docs: Improve docs styles

---

atom/browser/api/atom_api_app.cc
atom/browser/api/atom_api_app.h
atom/browser/api/atom_api_web_contents.cc
atom/browser/api/atom_api_web_contents.h
atom/browser/atom_browser_client.cc
atom/browser/atom_browser_client.h
lib/browser/api/browser-window.js
lib/browser/guest-window-manager.js
lib/renderer/override.js
script/lib/config.py

Fixes #4760 
~~Depends on https://github.com/atom/libchromiumcontent/pull/187~~
Depends on https://github.com/atom/libchromiumcontent/pull/191

browser: fix disposition value for new-window event

---

docs/api/accelerator.md

<kbd>Option</kbd> is only on OS X.

use alt, not option

---

atom/browser/native_window.cc
atom/browser/native_window_mac.mm
script/lib/config.py

Remove the white flash when loading page on OS X

---

docs/api/auto-updater.md

Add link to Aluxian/squirrel-updates-server in the docs page for autoUpdater

Add squirrel-updates-server link in the docs

---

atom/browser/net/atom_network_delegate.cc
docs/api/session.md
spec/api-web-request-spec.js

session: webRequest.OnHeadersReceived should accept status line.

---

docs-translations/zh-CN/tutorial/application-distribution.md

Delete the extra text

---

atom/app/atom_main_delegate.cc
atom/utility/atom_content_utility_client.cc
atom/utility/atom_content_utility_client.h
chromium_src/chrome/utility/printing_handler_win.cc
chromium_src/chrome/utility/printing_handler_win.h
script/lib/config.py

Fix printing not working on Windows

---

atom/browser/native_window.cc

Fix wrong default transparent background for frameless window

---

atom/browser/api/atom_api_web_contents.cc
atom/browser/atom_security_state_model_client.cc
atom/browser/atom_security_state_model_client.h
atom/browser/common_web_contents_delegate.cc
atom/browser/common_web_contents_delegate.h
atom/common/atom_constants.cc
atom/common/atom_constants.h
filenames.gypi

Depends on
https://github.com/electron/libchromiumcontent/pull/196
https://github.com/electron/brightray/pull/208
Fixes #5022

provide security style for devtools security panel

---

docs/api/menu.md

Sample missing reference to webContents for toggleDevTools.

Sample missing reference to webContents for toggleDevTools

---

docs-translations/zh-CN/api/browser-window.md

'same-origin policy' means '同源策略' in Chinese

translation error in browser-window.md

---

docs-translations/zh-CN/tutorial/online-offline-events.md

change `ipc` to `ipcMain`/`ipcRenderer`

Update sample code in online-offline-events.md

---

docs-translations/es/tutorial/application-packaging.md

Correct misspellings

---

atom/browser/api/atom_api_web_contents.cc

Otherwise it is going to be some random value and bite us.
Close #5180.

Initialize the embedder_ member data

---

atom/browser/native_window.cc
atom/browser/native_window_mac.mm
atom/browser/net/atom_network_delegate.h
docs/api/dialog.md

Fix some coding style issues

---

docs/development/source-code-directory-structure.md

@kevinsawicki taught me and @jlord this One Weird Trick™

keeping submodules up to date

---

atom/browser/api/atom_api_web_contents.cc
docs/api/web-contents.md

Depends on https://github.com/electron/brightray/pull/215
Fixes https://github.com/electron/electron/issues/5094

devtools: allow opening in specified dock state

---

atom/browser/atom_resource_dispatcher_host_delegate.cc
atom/browser/web_contents_permission_helper.cc
atom/browser/web_contents_permission_helper.h
atom/common/native_mate_converters/content_converter.cc
docs/api/session.md
spec/webview-spec.js

Fixes https://github.com/electron/electron/issues/5200

session: allow providing permission to handle external protocols

---

chromium_src/chrome/browser/process_singleton_posix.cc

Make the length of SingletonSocket's path as short as we can

---

docs/api/process.md
lib/common/init.js

`windowsstore` -> `windowsStore`

Windows Store Camels

---

docs/api/app.md
docs/api/auto-updater.md
docs/api/browser-window.md
docs/api/crash-reporter.md
docs/api/desktop-capturer.md
docs/api/dialog.md
docs/api/frameless-window.md
docs/api/menu-item.md
docs/api/process.md
docs/api/screen.md
docs/api/session.md
docs/api/synopsis.md
docs/api/web-contents.md
docs/api/web-view-tag.md
docs/development/build-instructions-osx.md
docs/development/build-instructions-windows.md
docs/development/build-system-overview.md
docs/development/coding-style.md
docs/development/debug-instructions-windows.md
docs/development/source-code-directory-structure.md
docs/faq/electron-faq.md
docs/tutorial/debugging-main-process.md
docs/tutorial/desktop-environment-integration.md
docs/tutorial/mac-app-store-submission-guide.md
docs/tutorial/quick-start.md

* Line wrap to `80`
* Remove additional spaces
* Fix coding style issues
* Some improvements
* Fix typos
* Apply some fixes

docs: Improve documentations

---

README-ko.md
README.md
docs-translations/tr-TR/README.md
docs-translations/tr-TR/styleguide.md

Not yet fully completed. 
I will be also translate the other files soon!

Translate docs to Turkish

---

docs/api/content-tracing.md
docs/api/web-frame.md

Update module names in docs

---

docs/tutorial/quick-start.md

This pull request brings in some recent code changes from the https://github.com/electron/electron-quick-start repo.

update quick-start code to match quick-start repo

---

docs/tutorial/quick-start.md

describe electron-prebuilt and link to it

---

script/upload.py

Bring the Windows symbol server back to life.
Close #784.

Upload PDBs to Windows symbol server

---

CONTRIBUTING-ko.md

* Fix wrong link
* Fix wrong word (Imperative mood is not "필수적 분위기")
- References: [English-Korean Dictionary](http://endic.naver.com/enkrEntry.nhn?sLn=en&entryId=30e2c26a5cf34ef695d68a7fdf39e4b5), [Wikipedia](https://ko.wikipedia.org/wiki/%EB%AA%85%EB%A0%B9%EB%B2%95)

Fix small mistakes in Korean Doc

---

default_app/index.html

__Before:__
__After:__
__Before:__
__After:__

Make the drag box fill the remaining height of window in default app

---

CODE_OF_CONDUCT.md

Also, switch email address for reporting.

:memo: Update to v1.4 of the Code of Conduct

---

docs/api/browser-window.md

docs: Make it clear that size constraints only apply for users

---

docs/api/web-contents.md

Based on discussion in https://github.com/electron/electron/issues/4396.

Clarify how did-fail-load handles redirects

---

atom/browser/common_web_contents_delegate.cc
atom/browser/common_web_contents_delegate.h

Fixes #5230 
Depends on https://github.com/electron/brightray/pull/217

devtools: handle file system indexing requests

---

atom/browser/api/event.cc
spec/api-ipc-spec.js

ipcRenderer: fix crash with multiple listeners to sync message

---

docs/README.md
docs/faq/electron-faq.md
docs/tutorial/security.md

As discussed with @zeke, this PR adds basic information about Electron and Security, including expectation-setting around Chromium updates, guidelines around remote content, and an invitation to contribute to security features. Contains information by @zcbenz, @zeke, and @paulcbetts.

Add Security Tutorial

---

default_app/default_app.js
default_app/index.html
default_app/main.js

Updates the default application to the same conventions as found in the latest revisions of the documentation.

Update default_app to ES6 conventions

---

docs-translations/zh-CN/api/process.md

Docs:fix a minor typo

---

atom/app/atom_content_client.cc
atom/browser/api/atom_api_app.cc

Fix passing paths in command line

---

docs/api/session.md

docs: Match object notation style

---

docs/api/dialog.md

Document Dialog Buttons Behavior on Windows

---

docs/tutorial/security.md

Hey folks! Just read through the security doc and made a few small changes to make the first two paragraphs easier to read. Feel free to merge / close as you see fit. I also added a note about CSP to the security suggestions.

Add to security checklist

---

docs/api/accelerator.md

Document 'Tab' as a supported accelerator.

---

atom/browser/api/atom_api_menu_mac.mm

Fix context menu positioning on OS X

---

docs/faq/electron-faq.md

wrong link destination

---

lib/browser/api/global-shortcut.js

Minor change to conform with the ES6 destructuring in the latest version of the docs on master.

💄 Destructure globalShortcut module

---

docs-translations/jp/README.md
docs-translations/jp/tutorial/mac-app-store-submission-guide.md
docs-translations/jp/tutorial/security.md

Japanese version of MAS submission guide was old.

Update: Japanese version of MAS submission guide

---

docs/api/web-view-tag.md
lib/browser/guest-view-manager.js
lib/renderer/init.js
spec/fixtures/module/preload-webview.js
spec/webview-spec.js

Disable webview when nodeIntegration is off

---

atom/browser/api/atom_api_system_preferences.cc
atom/browser/api/atom_api_system_preferences.h
atom/browser/api/atom_api_system_preferences_mac.mm
atom/browser/mac/dict_util.mm
docs/api/system-preferences.md

Also rewrote the `DictionaryValueToNSDictionary` so it works when the dictionary includes an object that can not be converted to JSON. 
Fix #5543.

Pass userInfo in systemPreferences.subscribeNotification

---

docs/api/app.md
docs/api/auto-updater.md
docs/api/dialog.md
docs/api/synopsis.md
docs/tutorial/electron-versioning.md
docs/tutorial/mac-app-store-submission-guide.md
docs/tutorial/windows-store-guide.md

docs: Improve docs

---

docs-translations/ru-RU/tutorial/mac-app-store-submission-guide.md

Russian language for http://electron.atom.io/docs/tutorial/mac-app-store-submission-guide/

docs : Russian

---

docs/api/file-object.md

Minor follow on to #5576 for consistency

Capitalize Object in doc heading

---

script/lib/config.py

Seems silly to default to 32-bit on Windows (if I'm Incorrect, feel free to close this PR)

Default to amd64 on Windows

---

atom/common/crash_reporter/win/crash_service.cc
atom/common/crash_reporter/win/crash_service_main.cc
spec/api-crash-reporter-spec.js

Fix crash reporter not working on x64 Windows

---

docs/api/browser-window.md

Close #5651 
Ref: https://github.com/electron/electron/blob/6f3d0e17826313898ef12932282479cf7d5cb7c0/atom/browser/native_window.cc#L92

Mention that x and y have to be used together when creating new window

---

docs-translations/ko-KR/development/build-instructions-windows.md
docs-translations/zh-CN/development/build-instructions-windows.md
docs/development/build-instructions-windows.md

Update Windows Build Instructions

---

lib/browser/api/menu-item.js
lib/common/asar.js
lib/renderer/override.js
package.json

Updates Standard Code Style to 7 (latest major) and ensures that code is conform.
* camelCase is now enforced
* No assignments in return statements

Implement JavaScript Standard Style 7

---

atom/browser/api/atom_api_menu_mac.mm

So I completely forgot to account for multiple screens when I first implement this...
I think I'll show myself out 😓     
Closes #5722

Fix context menus only showing on primary monitor.

---

atom/browser/api/atom_api_window.cc
docs/api/native-image.md

Choose the correct icon size for Windows taskbar

---

docs-translations/jp/README.md
docs-translations/jp/api/file-object.md
docs-translations/jp/api/web-view-tag.md
docs/api/web-view-tag.md

newly translate web-view-tag.md into Japanese :jp:

Japanese: add web-view-tag.md

---

atom/browser/net/url_request_fetch_job.cc
atom/browser/net/url_request_fetch_job.h
spec/api-protocol-spec.js

protocol: store initial response data for when resource loader becomes ready

---

lib/browser/api/session.js
lib/browser/api/web-contents.js

Throw error when session module is used before app is ready

---

docs/api/auto-updater.md

Add link to GitbookIO/nuts in the docs page for autoUpdater

Add nuts link to the docs

---

docs-translations/zh-CN/api/browser-window.md

Correct wrong words

---

atom/browser/native_window_views.cc

Chromium's implementation is somehow not working as expected, the new implementation follows the behavior of wmctrl.
Close #5206.

Fix NativeWindow::Focus not moving focus to window

---

atom/browser/api/atom_api_app.cc
atom/browser/api/atom_api_app.h
docs/api/app.md

Add app.disableHardwareAcceleration() API

---

atom/browser/api/atom_api_web_contents.cc
atom/browser/api/atom_api_web_contents.h
docs/api/web-contents.md
docs/api/web-view-tag.md
lib/browser/guest-view-manager.js
lib/renderer/web-view/guest-view-internal.js

Add update-target-url event

---

atom/browser/native_window_mac.h
atom/browser/native_window_mac.mm

Fix title of frameless window showing as empty under fullscreen

---

docs-translations/zh-CN/tutorial/quick-start.md

Based on electron ver 1.1.3 update Quick Start Page[Simplified Chinese].

update Quick Start Page[zh-CN]

---

docs-translations/ko-KR/api/ipc-renderer.md
docs-translations/ko-KR/api/web-contents.md
docs-translations/ko-KR/tutorial/application-distribution.md
docs-translations/ko-KR/tutorial/quick-start.md

* miss typed part
* not intended markdown grammar

Update Korean documentation translation to a latest version

---

docs/api/tray.md

Move example to the correct place

---

docs-translations/ko-KR/tutorial/mac-app-store-submission-guide.md

:memo: Update Korean doc to a latest version.

---

docs/api/screen.md

remove extraneous 'not'

---

lib/renderer/override.js

Fix exception in alert for inavlid parameter

---

docs/tutorial/using-selenium-and-webdriver.md

Test should always exit (app.stop()) either on success or failure.

Improved test exit

---

docs/tutorial/using-pepper-flash-plugin.md

Improve the example so it can be copy-pasted without modification, also add a new entry in troubleshooting.

Improve the docs on loading flash plugin

---

docs/api/app.md
docs/api/web-contents.md
docs/api/web-frame.md
docs/tutorial/security.md
docs/tutorial/testing-on-headless-ci.md
docs/tutorial/windows-store-guide.md

Minor doc typo fixes

---

docs/api/menu.md

Closes https://github.com/electron/electron/issues/6085
cc @kevinsawicki

Make Menu.getApplicationMenu() public

---

docs/tutorial/devtools-extension.md

Fixes #6133
Because apparently typos bug people enough to raise an issue but not enough to fix it 😆

Fix typo in DevTools Extensions tutorial

---

atom/browser/api/atom_api_tray.cc
atom/browser/api/atom_api_tray.h
atom/browser/ui/tray_icon.cc
atom/browser/ui/tray_icon.h
atom/browser/ui/tray_icon_cocoa.h
atom/browser/ui/tray_icon_cocoa.mm
atom/browser/ui/win/notify_icon.cc
atom/browser/ui/win/notify_icon.h
docs/api/tray.md

Add tray.getBounds() API

---

atom/browser/ui/file_dialog_gtk.cc
atom/browser/ui/message_box_gtk.cc

linux: Disable parent window when showing modal dialogs

---

atom/browser/ui/views/menu_bar.cc
atom/browser/ui/views/menu_bar.h

Update menubar color when theme changes

---

atom/browser/api/atom_api_menu.cc
atom/browser/api/atom_api_menu.h
atom/browser/api/atom_api_tray.cc
atom/browser/api/atom_api_tray.h
atom/browser/api/event_emitter.cc
atom/browser/api/event_emitter.h
docs/api/menu-item.md
docs/api/session.md
lib/browser/api/menu-item.js
lib/browser/api/menu.js
spec/api-menu-spec.js

Add "event" parameter for "click" handler of MenuItem

---

atom/browser/native_window_mac.mm

mac: Fix maximize/unmaximize event emitted before window is maximized

---

spec/api-session-spec.js

Most recent test failures came from this, hope it can make the test more reliable.

Split the session.protocol test into multiple tests

---

atom/browser/native_window_mac.mm

mac: Avoid calling setTitleVisibility for OS X 10.9

---

atom/browser/atom_browser_main_parts.cc
atom/browser/javascript_environment.cc
atom/browser/javascript_environment.h
atom/common/api/event_emitter_caller.cc
atom/common/native_mate_converters/callback.h
atom/common/node_bindings.cc

Handle v8::MicrotasksScope in the main process

---

docs-translations/pt-BR/README.md

Broken link (404) to DesktopCapturer

broken link (404)

---

docs-translations/jp/api/native-image.md
docs-translations/ko-KR/api/native-image.md
docs-translations/zh-CN/api/native-image.md

Follow on to #5725, update renamed APIs in translated docs.

Update renamed nativeImage APIs in translated docs

---

lib/browser/chrome-extension.js

For [chrome-react-perf](https://github.com/crysislinux/chrome-react-perf/blob/master/chrome/manifest.prod.json#L25) support.

Support background.page in extension manifest

---

docs/api/app-locales.md
docs/api/app.md
docs/faq/app-locale.md

Document possible getLocale returns values.  

---

docs/api/web-contents.md
docs/development/setting-up-symbol-server.md
docs/tutorial/windows-store-guide.md

docs: Some dlls are not there anymore

---

docs/api/remote.md

:memo: web-contents.md#webcontentsexecutejavascriptcode-usergesture ->
web-contents.md#webcontentsexecutejavascriptcode-usergesture-callback

Fix a hash of a link href in the remote.md

---

docs/api/remote.md

Fix typos in the remote.md

---

atom/browser/relauncher_linux.cc

Redirect relaunch process's stdout to /dev/null

---

docs-translations/pt-BR/README.md

This PR fix some broken links in PT-BR documentation.

Fixed broken links in documentation PT-BR

---

atom/browser/native_window_views.cc
docs/api/browser-window.md

win: Add toolbar type for BrowserWindow

---

atom/browser/native_window_views.cc

Auto-hide menubar when in fullscreen

---

atom/browser/ui/file_dialog.h
atom/browser/ui/file_dialog_gtk.cc
atom/browser/ui/file_dialog_mac.mm
atom/browser/ui/file_dialog_win.cc
docs/api/dialog.md
lib/browser/api/dialog.js

Add showHiddenFiles property for dialog.showOpenDialog

---

atom/browser/atom_resource_dispatcher_host_delegate.cc
atom/common/api/atom_api_shell.cc
atom/common/platform_util.h
atom/common/platform_util_win.cc

win: Fix openExternal not working with non-ASCII characters

---

atom/browser/native_window_mac.mm

Fix transparent window having border on OS X 10.9

---

atom/browser/api/atom_api_session.cc
atom/browser/atom_browser_context.cc
atom/browser/atom_browser_context.h
atom/browser/net/atom_cert_verifier.cc
atom/browser/net/atom_cert_verifier.h

Create AtomCertVerifier on IO thread

---

docs/tutorial/quick-start.md

A followup to https://github.com/electron/electron/pull/6471
cc @a904guy

link to boilerplates

---

docs/api/process.md

Incremental progress toward ✨ pristine docs✨

Clean up API Docs

---

atom/browser/relauncher_mac.cc

The #6412 only fixes the issue on Linux, it seems that we have the same problem on macOS, so this PR ports the code to macOS.
Close #6519.

Apply #6412 on macOS

---

atom/common/native_mate_converters/net_converter.cc
docs/api/app.md
docs/api/web-contents.md

[brave#27](https://github.com/brave/electron/pull/27)

serial number in hex string

---

docs/api/web-contents.md

[ci skip]
This will not fix issue #6541 , it will ONLY update documentation error pointed out by author.

fix documentation error pointed out in issue #6541

---

atom/browser/api/atom_api_session.cc
docs/api/session.md
spec/api-session-spec.js

session: add proxyBypassRules option to setProxy api

---

docs/tutorial/application-packaging.md

fix wording in asar doc

---

spec/api-menu-spec.js

Just realized that the tests don't pass after my PR (#6600). This fixes that :)

Fix test for PR #6600

---

atom/browser/native_window.cc

Set page's font settings with system settings

---

docs/api/desktop-capturer.md

Missed one string in my previous PR :(

Normalize string quotes in desktopCapturer docs

---

docs/development/build-instructions-windows.md
script/bootstrap.py
script/update.py

It can be used to generate a Visual Studio project.
Close #5868.

Add --msvs parameter to bootstrap.py

---

docs/api/tray.md

As discussed on https://github.com/electron/electron/pull/6620
/cc @kevinsawicki

docs: Explain how to use highlightMode with BrowserWindow

---

docs-translations/jp/README.md
docs-translations/jp/tutorial/testing-on-headless-ci.md

I have translated testing-on-headless-ci.md into Japanese newly.
Thanks.

Japanese: add testing-on-headless-ci.md

---

atom/browser/native_window_views.h
atom/browser/native_window_views_win.cc

fix issue caused by submission #6596

fix maximize restore issue caused by restore window size change

---

docs-translations/jp/README.md
docs-translations/jp/api/system-preferences.md

I have translated system-preferences.md into Japanese newly.
Thanks.

Japanese: add system-preferences.md

---

docs-translations/jp/README.md
docs-translations/jp/development/coding-style.md

I have translated it into Japanese newly.
Thanks.

Japanese: add coding-style.md

---

docs-translations/jp/README.md
docs-translations/jp/development/atom-shell-vs-node-webkit.md

I have translated it into Japanese newly.
Thanks.

Japanese: add atom-shell-vs-node-webkit.md

---

docs-translations/jp/README.md
docs-translations/jp/development/build-instructions-osx.md

I have translated it into Japanese newly.
Thanks.

Add: japanese build-instructions-osx.md

---

atom/browser/atom_browser_main_parts.cc

Ref #6548 
This fixes the render process crash.

browser: register extension scheme as web safe scheme

---

atom/common/atom_version.h
script/cpplint.py

- Remove files that are lint free from the ignore list
- Remove deleted files from the ignore list
- Minor lint fixes

Remove files from cpplint ignore list

---

atom/browser/ui/cocoa/atom_menu_controller.mm
default_app/main.js
docs/api/menu-item.md
docs/api/menu.md
lib/browser/api/menu-item-roles.js

https://chromium.googlesource.com/chromium/src/+/lkcr/content/browser/renderer_host/render_widget_host_view_mac.mm#3150
https://chromium.googlesource.com/chromium/src/+/lkcr/content/browser/renderer_host/render_widget_host_view_mac.mm#3154

Add macOS specific speaking roles for MenuItem

---

.gitignore

Adds Visual Studio and Visual Studio Code configuration files (auto-generated) to .gitignore.

Gitignore Visual Studio Files

---

atom/browser/net/atom_network_delegate.cc

don't convert header names to nested values

---

atom/browser/api/atom_api_window.cc
atom/browser/native_window_views.cc
atom/browser/ui/win/taskbar_host.cc
atom/browser/ui/win/taskbar_host.h

Save the thumbar buttons when setting them to restore later

---

atom/browser/api/atom_api_protocol.cc
spec/api-protocol-spec.js

Fix spelling mistake from registred to registered

---

docs/api/browser-window.md
docs/api/menu-item.md
docs/api/power-save-blocker.md
docs/api/session.md
docs/api/system-preferences.md
docs/api/web-contents.md

Found a few issues while linting with @kevinsawicki

Fix some invalid docs

---

docs/api/shell.md
docs/api/tray.md
docs/api/web-contents.md
docs/api/window-open.md

More parameter fixes

---

docs/api/web-view-tag.md

Adds docs using the web content's docs for these methods as a template.
Refs #6958

Document <webview>.setZoomFactor/Level as public

---

docs/api/session.md

fix optional param spacing

---

atom/browser/api/atom_api_web_contents.cc

Reverts electron/electron#7003 per https://github.com/electron/electron/pull/7003#issuecomment-243112371.

Revert "exit tab fullscreen on destroy"

---

docs/api/web-contents.md

I googled a lot and found this way. I think I should add it to the document to save others' time.

Add guide for force new page in print / printToPDF

---

atom/browser/browser.cc
atom/browser/browser.h
docs/api/app.md

Default app exit code to 0

---

docs/api/web-contents.md

documents webContents.fromId

---

docs/tutorial/application-distribution.md
docs/tutorial/supported-platforms.md
docs/tutorial/using-native-node-modules.md

Architecture reference consistency and missing words.

Fix documentation typos

---

atom/browser/native_window_mac.mm
docs/api/browser-window.md

Follow up to: https://github.com/electron/electron/pull/6848

Add support for titleBarStyle: 'hidden-inset' on OS X 10.9

---

docs/README.md

A few minor updates to docs/README.md

Docs Readme

---

atom/browser/api/atom_api_window.cc
atom/browser/api/atom_api_window.h
atom/browser/native_window.cc
atom/browser/native_window.h
atom/browser/native_window_mac.h
atom/browser/native_window_mac.mm
atom/browser/native_window_observer.h
docs/api/browser-window.md

Emit scroll-touch-edge event instead of changing the behavior of scrollll-touch-begin/end

---

docs/development/build-instructions-linux.md
docs/development/build-instructions-osx.md
docs/development/build-instructions-windows.md

Mention cleaning your local build environment in all three platform docs.
Closes #7202

Mention build cleaning on all three platforms

---

docs-translations/it-IT/README.md
docs-translations/it-IT/faq.md
docs-translations/it-IT/styleguide.md

This is a starting point for the Italian translation. I will try to update it as soon as I can.
Suggestion and questions, if any, are heartily appreciated.

Docs: Start Italian translations

---

docs/tutorial/accessibility.md

Fixed a problem is found during that translate documents into Korean.

Fix broken links

---

atom/renderer/atom_renderer_client.cc
atom/renderer/content_settings_observer.cc
atom/renderer/content_settings_observer.h
docs/api/protocol.md
filenames.gypi
spec/chromium-spec.js
spec/fixtures/pages/storage/cookie.html
spec/fixtures/pages/storage/indexed_db.html
spec/fixtures/pages/storage/local_storage.html
spec/fixtures/pages/storage/session_storage.html
spec/fixtures/pages/storage/web_sql.html

protocol: disable storage for non standard custom schemes

---

lib/renderer/web-view/web-view.js

A possible fix for https://github.com/electron/electron/issues/7309

add type to webview style tag

---

docs/api/app.md
docs/tutorial/mac-app-store-submission-guide.md

document lack of MAS support for login item APIs

---

docs/api/app.md
docs/api/browser-window.md
docs/api/desktop-capturer.md
docs/api/dialog.md
docs/api/menu.md
docs/api/protocol.md
docs/api/screen.md
docs/api/session.md
docs/api/tray.md
docs/api/web-contents.md
docs/api/web-view-tag.md

Couple of return and argument types were either incorrect or inaccurate
/cc @zeke

Update docs to contain more specific return values

---

atom/browser/atom_browser_client.cc

browser: allow filesystem access for devtools scheme

---

atom/browser/native_window_views.cc

Reverts electron/electron#7416 as explained in https://github.com/electron/electron/pull/7416#issuecomment-251086025.

Revert "Fix for issues seen on frameless window (Windows) when at 200% resolution"

---

spec/api-browser-window-spec.js
spec/fixtures/pages/window-open.html

This update the 'new-window' event test test to check code changes introduced by #7291.

Update BrowserWindow's test to check additional features upon window.open() call

---

docs/api/app.md

Fix misspelling in docs/api/app.md

---

docs/README.md
docs/api/repl.md
docs/tutorial/repl.md

Credit to @hellonearthis for starting this issue https://github.com/electron/electron/pull/6979

add REPL documentation

---

README.md

Update devDependency Status URL

---

docs/tutorial/online-offline-events.md

Add further information to online-offline event documentation

---

atom/browser/native_window_views_win.cc

This PR extracts `IsScreenReaderActive` as proposed by @miniak.
- Fix for #7611 on windows with touch screen and NVDA
- Original issue #7208
- Tested on my Surface Pro 4 running Windows 10 and NVDA.

Fire a11y event on touch screens using screen readers

---

docs/development/releasing.md
package.json

This new document outlines the steps to cut a new release of Electron.
👁 👁  @zcbenz

Document release process

---

docs/development/releasing.md

Adds a push step after bumping the version.
/cc @zeke

Push after bumping version

---

docs/tutorial/security.md

Credits to @jainmukul for starting #7568

📝Remove ambiguous default value of nodeintegration Issue #6939

---

docs/api/app.md
docs/api/browser-window.md
docs/api/content-tracing.md
docs/api/desktop-capturer.md
docs/api/dialog.md
docs/api/menu-item.md
docs/api/protocol.md
docs/api/session.md
docs/api/structures/desktop-capturer-source.md
docs/api/structures/upload-data.md
docs/api/system-preferences.md
docs/api/web-contents.md
docs/api/web-view-tag.md

Function param types

---

docs/api/net.md
lib/browser/api/net.js

fixed a couple of typos

---

docs-translations/zh-TW/api/structures/cookie.md
docs-translations/zh-TW/api/structures/task.md

ZH_TW docs api/structures/cookie add

ZH_TW docs api/structures/cookie add

---

docs/tutorial/debugging-main-process.md

According to Issue #7756 I added the example usage.

Added example usage for the default port

---

docs/tutorial/quick-start.md

Port over `url.format` change from https://github.com/electron/electron-quick-start/pull/102
/cc @privatzee
Closes #7786

Format URL passed to BrowserWindow.loadURL

---

docs-translations/ko-KR/api/app.md
docs-translations/ko-KR/api/net.md
docs-translations/ko-KR/tutorial/debugging-main-process-node-inspector.md
docs-translations/ko-KR/tutorial/debugging-main-process-vscode.md
docs-translations/ko-KR/tutorial/debugging-main-process.md
docs-translations/ko-KR/tutorial/quick-start.md

And, the contents of two files to relating debugging are swapped with each other to correct.

Update the korean docs up to '379c347' commit.

---

package.json

Thanks for @kevinsawicki for this improvement: https://github.com/electron/electron-docs-linter/pull/68

use docs linter with lots of stuff npmignored

---

docs/api/net.md

Documentation: Formatting JavaScript sample code.

---

.gitignore

Consolidate the gitignore log files.

Consolidate log files

---

docs/api/process.md

Adds argv and platform documentation to process docs

Process docs

---

docs-translations/zh-CN/api/web-contents.md

To improve the translation of content

update simplified Chinese translation 

---

docs-translations/zh-CN/api/remote.md

fix some translation problems

---

docs-translations/zh-CN/api/tray.md

There is an error in the translation of the last sentence.It may make reader confuse.

Modify the error terms

---

docs/api/app.md
docs/api/auto-updater.md
docs/api/browser-window.md
docs/api/clipboard.md
docs/api/crash-reporter.md
docs/api/dialog.md
docs/api/download-item.md
docs/api/ipc-renderer.md
docs/api/menu-item.md
docs/api/menu.md
docs/api/remote.md
docs/api/structures/crash-report.md
docs/api/structures/file-filter.md
docs/api/structures/jump-list-category.md
docs/api/structures/jump-list-item.md
docs/api/tray.md
docs/api/web-contents.md
package.json

Update docs to correctly identify props and params that are optional

---

docs/api/browser-window.md

Move footer links to bottom

---

docs-translations/zh-CN/api/app.md

update `app.md` Chinese translation to latest version

update app.md Chinese translation to latest version

---

atom/browser/ui/accelerator_util.cc

disable accelerator when menu item is disabled

---

docs/api/tray.md

* wrap example in a app ready event
* fix TypeError on `contextMenu.items[2].checked`

[ci skip] Correct Linux limitation example

---

docs-translations/zh-TW/tutorial/about.md
docs-translations/zh-TW/tutorial/accessibility.md

Make zh_TW translation of tutorial/about.md and tutorial/accessibility.md

zh_TW translation of tutorial docs

---

docs-translations/zh-TW/tutorial/accessibility.md
docs-translations/zh-TW/tutorial/debugging-main-process-node-inspector.md
docs-translations/zh-TW/tutorial/debugging-main-process-vscode.md
docs-translations/zh-TW/tutorial/desktop-environment-integration.md

* tutorial/debugging-main-process-node-inspector.md
* tutorial/desktop-environment-integration.md
I forgot to add [ci skip] in my commit, so the former pull request didn't pass ci.

zh_TW translation of some tutorial document 

---

docs/api/app.md
docs/api/auto-updater.md

Clarify docs on a `before-quit` behavior edge case

---

atom/browser/api/atom_api_window.cc
atom/browser/api/atom_api_window.h
atom/browser/native_window.cc
atom/browser/native_window.h
atom/browser/native_window_mac.h
atom/browser/native_window_mac.mm
docs/api/browser-window.md
spec/api-browser-window-spec.js

Add 'win.closeFilePreview()'

---

docs/api/crash-reporter.md

Updating docs with clarifying information about the crash reporter in Mac as per the findings in #7474 #8045

Clarifying crash reporter behviour in Mac

---

lib/browser/api/dialog.js
spec/api-dialog-spec.js

This is extracted from #8120 and adds some basic dialog specs that test the error cases.

Add basic dialog specs

---

script/lib/config.py

Pulls in https://github.com/electron/libchromiumcontent/pull/248

Upgrade libcc for CT timebomb patch

---

atom/browser/api/atom_api_session.cc
spec/chromium-spec.js
spec/fixtures/pages/media-id-reset.html

Depends on https://github.com/electron/brightray/pull/262

session: reset media device id salt when cookies are cleared

---

docs-translations/fr-FR/tutorial/quick-start.md

Remove trailing spaces

---

docs-translations/zh-CN/README.md
docs-translations/zh-CN/faq/electron-faq.md

update some electron-faq.md code demo in Simplified Chinese docs.And fix a little words in README.md.

[DOC]update electron-faq.md in  Simplified Chinese docs

---

docs-translations/zh-CN/README.md
docs-translations/zh-CN/api/net.md
docs-translations/zh-CN/api/system-preferences.md

add systemPreferences API and net API docs translation whith  Simplified Chinese

[DOC] Add systemPreferences API Simplified Chinese translation

---

docs/api/screen.md

Fixes a broken link in screen documentation

[Docs] fix link in screen docs

---

docs/api/protocol.md

Add options to protocol.registerStandardSchemes docs

---

docs/api/session.md

It won't work if you use include the space that is currently in the docs.

Use localstorage in clearStorageData docs

---

docs/glossary.md

:memo: Fix a broken asar link.

---

README.md

The link of electron-jp is broken ;(

Fix electron-jp's link in README.md

---

docs/api/browser-window.md

:memo: Link to tutorial from option description.

Link to offscreen rendering tutorial

---

docs-translations/zh-CN/api/process.md

API process Translated into zh-CN

docs-translations API process Translated into zh-CN

---

docs-translations/zh-CN/project/README.md

fix some expression with more coherent way

fix some expression

---

docs-translations/zh-CN/README.md

add glossary page link to readme

add glossary page link to readme

---

docs-translations/zh-CN/tutorial/mac-app-store-submission-guide.md

mac-app-store-submission-guide to zh-CN

mac-app-store-submission-guide to zh-CN

---

docs-translations/zh-CN/tutorial/application-distribution.md
docs-translations/zh-CN/tutorial/using-native-node-modules.md

application-distribution to zh-CN

application-distribution to zh-CN

---

docs-translations/zh-TW/tutorial/repl.md

translate repl.md into zh-TW

---

atom/browser/net/atom_url_request.cc
spec/api-net-spec.js

net: disallow cookies from cookie store

---

docs-translations/zh-CN/tutorial/debugging-main-process-node-inspector.md
docs-translations/zh-CN/tutorial/debugging-main-process-vscode.md
docs-translations/zh-CN/tutorial/debugging-main-process.md
docs-translations/zh-CN/tutorial/devtools-extension.md

Debugging the Main Process to zh-CN

---

spec/api-browser-window-spec.js

Add spec for resizable frameless window

---

docs/api/crash-reporter.md

Rename autoSubmit to uploadToServer in example

---

docs-translations/zh-CN/tutorial/using-pepper-flash-plugin.md
docs-translations/zh-CN/tutorial/using-selenium-and-webdriver.md
docs-translations/zh-CN/tutorial/using-widevine-cdm-plugin.md

Using Selenium and WebDriver to zh-CN	
Using Pepper Flash Plugin to zh-CN		
Using Widevine CDM Plugin to zh-CN

translate to zh-CN

---

spec/webview-spec.js

This pull request comments out some specs that are timing out pretty regularly on Travis but still will run on Jenkins builds.

Disable flaky specs on Travis

---

common.gypi
script/update-clang.sh

Updates to the clang version used by Chrome 54
Refs #8406

Upgrade to clang 278861

---

docs/development/build-instructions-osx.md
docs/development/build-instructions-windows.md

Document toolchains used for building official Electron releases

---

atom/browser/api/atom_api_web_contents.cc
spec/api-browser-window-spec.js

Refs https://github.com/electron/electron/issues/8448

WebContents: emit did-fail-load event when url exceeds character limit

---

docs-translations/zh-CN/api/chrome-command-line-switches.md
docs-translations/zh-CN/api/file-object.md
docs-translations/zh-CN/api/synopsis.md
docs-translations/zh-CN/api/webview-tag.md
docs-translations/zh-CN/tutorial/desktop-environment-integration.md
docs-translations/zh-CN/tutorial/online-offline-events.md
docs-translations/zh-CN/tutorial/quick-start.md
docs-translations/zh-CN/tutorial/testing-on-headless-ci.md

Quick Start to zh-CN
Desktop Environment Integration to zh-CN
Online/Offline Event Detection to zh-CN

translate zh cn

---

atom/common/native_mate_converters/blink_converter.cc
docs/api/web-contents.md
spec/api-web-contents-spec.js

Fixes #8471 
added `code` property for 'before-input-event'

add 'code' property in 'before-input-event''s 'input' argument

---

docs/api/app.md

Fix broken Squirrel.Windows link

---

script/create-dist.py
script/lib/config.py

Refs https://github.com/electron/libchromiumcontent/pull/260.
Close https://github.com/electron/electron/issues/8608.

Update libchromiumcontent: Fix debug symbols not generated

---

atom/browser/ui/file_dialog.h
atom/browser/ui/file_dialog_mac.mm
docs/api/dialog.md
lib/browser/api/dialog.js

Fixes #8601
Thanks for the detailed issue report @maxbrunsfeld was wondering what was causing this in a different Electron app for a while 😆

Add resolvesAliases option to openDialog

---

docs-translations/zh-CN/api/auto-updater.md
docs-translations/zh-CN/api/browser-window.md
docs-translations/zh-CN/api/content-tracing.md
docs-translations/zh-CN/api/dialog.md
docs-translations/zh-CN/api/global-shortcut.md
docs-translations/zh-CN/api/ipc-main.md
docs-translations/zh-CN/api/menu-item.md
docs-translations/zh-CN/api/menu.md
docs-translations/zh-CN/api/power-monitor.md
docs-translations/zh-CN/api/power-save-blocker.md
docs-translations/zh-CN/api/protocol.md
docs-translations/zh-CN/api/session.md
docs-translations/zh-CN/api/system-preferences.md
docs-translations/zh-CN/api/tray.md
docs-translations/zh-CN/api/web-contents.md
docs-translations/zh-CN/api/window-open.md

Modules for the Main Process to zh-CN

Modules for the Main Process to zh-CN

---

docs-translations/zh-CN/README.md
docs-translations/zh-CN/development/clang-format.md
docs-translations/zh-CN/styleguide.md

add zh-CN translations file - clang-format.md
add zh-CN translations file - styleguide.md
update zh-CN translations file - README.md

add translations files for zh-CN

---

docs/api/web-contents.md

Add doc for startDrag() files option.
Closes #8755

update startDrag(item) doc

---

docs/api/dialog.md

As suggested in https://github.com/electron/electron/pull/8733#issuecomment-282432973

Clarify docs for dialog.showMessageBox cancelId

---

docs-translations/jp/api/webview-tag.md
docs-translations/ko-KR/api/browser-window.md
docs-translations/ko-KR/api/webview-tag.md
docs-translations/zh-CN/api/browser-window.md
docs-translations/zh-CN/api/webview-tag.md
docs/api/browser-window.md
docs/api/webview-tag.md

:memo: Update link to Blink features.

---

docs-translations/nl/glossary.md

I translated the glossary.md file to dutch. I hope I did everything right, I tried to follow all of the guidelines but this is my first time contributing to electron so let me know if I did something wrong.

Pull request, for dutch translation of glossary.md

---

atom/browser/ui/cocoa/atom_touch_bar.mm
docs/api/touch-bar-label.md
docs/api/touch-bar.md
lib/browser/api/touch-bar.js

Follow on to #8095, support setting the text color of a label.

Support setting TouchBarLabel text color

---

docs/api/touch-bar-button.md
docs/api/touch-bar-color-picker.md
docs/api/touch-bar-label.md
docs/api/touch-bar-popover.md
docs/api/touch-bar-slider.md

Just some type declarations for the instance properties and function syntax 👍 
/cc @zeke @kevinsawicki

Add more explicit types to docs for TouchBar

---

atom/browser/api/atom_api_download_item.cc
atom/browser/api/atom_api_download_item.h

only emit `download-item done` event once

---

atom/browser/api/atom_api_web_contents.cc
atom/browser/api/atom_api_web_contents.h
spec/api-browser-window-spec.js
spec/static/main.js

Fixes https://github.com/electron/electron/issues/8700

webContents: defer url load when there is a pending navigation entry

---

atom/browser/api/atom_api_web_contents.cc
docs/api/browser-window.md
docs/api/web-contents.md
docs/api/webview-tag.md
spec/api-browser-window-spec.js
spec/fixtures/api/loaded-from-dataurl.js

This is my first time contributing to electron. Please suggest changes as needed.
Closes #8735

Support base URL option to loadURL for data URLs

---

docs/api/web-contents.md
lib/browser/api/web-contents.js
spec/api-browser-window-spec.js
spec/static/main.js

Ensure userGesture is boolean when calling executeJavaScript

---

docs/api/browser-window.md
docs/api/touch-bar.md

Add a note about possible future breaking changes given the newness of touch bar and its APIs. ⌨️

Mark TouchBar API as experimental

---

docs/api/touch-bar-button.md
docs/api/touch-bar-group.md
docs/api/touch-bar-popover.md
docs/api/touch-bar.md

Add more links to touch bar docs

---

atom/browser/web_contents_zoom_controller.cc
atom/browser/web_contents_zoom_controller.h
spec/fixtures/pages/webview-origin-zoom-level.html
spec/webview-spec.js

Fixes https://github.com/electron/electron/issues/8857

browser: track origin zoom with HostZoomMap

---

atom/common/crash_reporter/crash_reporter_linux.cc
atom/common/crash_reporter/crash_reporter_linux.h
docs/api/crash-reporter.md

Pass `uploadToServer` parameter to linux crash reporter

---

atom/browser/ui/cocoa/atom_touch_bar.mm
atom/browser/ui/cocoa/touch_bar_forward_declarations.h
docs/api/structures/segmented-control-segment.md
docs/api/touch-bar-segmented-control.md
lib/browser/api/touch-bar.js
spec/api-touch-bar-spec.js

This adds the `NSSegmentedControl` as a possible touch bar item.
/cc @kevinsawicki

Touchbar segmented control

---

script/lib/config.py
spec/chromium-spec.js

Pulls in the following libchromiumcontent changes:
* https://github.com/electron/libchromiumcontent/pull/263
* https://github.com/electron/libchromiumcontent/pull/266
* https://github.com/electron/libchromiumcontent/pull/270
* https://github.com/electron/libchromiumcontent/pull/272
* https://github.com/electron/libchromiumcontent/pull/273
* https://github.com/electron/libchromiumcontent/pull/274
* https://github.com/electron/libchromiumcontent/pull/275
Pulls in the following brightray changes:
* https://github.com/electron/brightray/pull/281
Closes #8791

Upgrade libcc and brightray to latest

---

docs/README.md
docs/development/chromium-development.md

This PR adds a doc for learning about Chromium and tracking its development.
- [chromiumdev](https://chromiumdev-slack.herokuapp.com) on Slack
- [@ChromiumDev](https://twitter.com/ChromiumDev) on Twitter
- [@googlechrome](https://twitter.com/googlechrome) on Twitter
- [Blog](https://blog.chromium.org)
- [Code Search](https://cs.chromium.org/)
- [Source Code](https://cs.chromium.org/chromium/src/)
- [Development Calendar and Release Info](https://www.chromium.org/developers/calendar)
- [Discussion Groups](http://www.chromium.org/developers/discussion-groups)

document resources for tracking chromium development

---

docs/api/client-request.md
docs/api/touch-bar-scrubber.md
docs/api/touch-bar-segmented-control.md

Fixes a few issues with the docs (missing types and missing function params)
/cc @zeke

Generic doc fixes

---

docs/api/process.md
docs/api/web-frame.md

Add missing property types on the process docs

---

docs/api/web-contents.md

/cc @zeke 
Love finding these 🌵

Fix return syntax in docs

---

atom/browser/ui/views/submenu_button.cc

Fix '&'  not showing in MenuItem label

---

spec/api-session-spec.js
spec/webview-spec.js

This spec is often failing on AppVeyor, disable for now to prevent confusion and bisect later.
https://ci.appveyor.com/project/electron-bot/electron/build/90/job/0djb3t6r2mijgy3s

Disable flaky post navigation spec on AppVeyor

---

script/lib/config.py

Pulls in https://github.com/electron/libchromiumcontent/pull/267
/cc @brenca 
Fixes #8667

Upgrade libcc for webview dnd fix

---

docs/api/web-contents.md
docs/api/webview-tag.md

Add missing finalUpdate prop

---

atom/app/atom_content_client.cc
atom/browser/api/atom_api_app.cc
atom/browser/api/atom_api_auto_updater.cc
atom/browser/api/atom_api_dialog.cc
atom/browser/api/atom_api_session.cc
atom/browser/api/atom_api_web_contents.cc
atom/browser/auto_updater_mac.mm
atom/browser/browser.cc
atom/browser/browser.h
atom/browser/browser_linux.cc
atom/browser/browser_mac.mm
atom/browser/browser_win.cc
atom/browser/common_web_contents_delegate.cc
atom/browser/native_window_mac.mm
atom/browser/net/atom_cert_verifier.cc
atom/browser/net/atom_network_delegate.cc
atom/browser/node_debugger.cc
atom/browser/osr/osr_render_widget_host_view.cc
atom/browser/osr/osr_render_widget_host_view_mac.mm
atom/browser/ui/cocoa/atom_menu_controller.mm
atom/browser/ui/cocoa/atom_touch_bar.mm
atom/browser/ui/file_dialog_mac.mm
atom/browser/web_contents_permission_helper.cc
atom/browser/web_dialog_helper.cc
atom/browser/window_list.cc
atom/common/native_mate_converters/content_converter.cc
atom/common/platform_util_mac.mm
atom/renderer/atom_sandboxed_renderer_client.cc
atom/renderer/atom_sandboxed_renderer_client.h

**No functionality change**: This PR cleans up electron cpp codebase (fixes a few code-style violations and uses C++11 features).

Cleanup cpp codebase

---

spec/api-net-spec.js

Seeing some flaky net specs on CI, this pull request switches the `afterEach` to destroy all connections and wait until the server closes before starting the next test.

Wait until server closes in afterEach in net spec

---

README.md
docs-translations/tr-TR/README.md
docs-translations/tr-TR/project/README.md
docs-translations/tr-TR/tutorial/application-distribution.md
docs-translations/tr-TR/tutorial/supported-platforms.md

I added translation files for some important tutorials for beginners and will try to translate all tutorials in next time. Hope this helps.

add turkish translation files

---

docs/api/frameless-window.md

I figured this out with some help from @MarshallOfSound. I added a note to the documentation explaining the problem.
I’ve never contributed to electron or any documentation so feedback is appreciated 😄

Add information about dragging not working with Dev tools open

---

atom/browser/ui/cocoa/atom_touch_bar.mm
docs/api/touch-bar-button.md
lib/browser/api/touch-bar.js
spec/api-touch-bar-spec.js

This allows icons to appear to the left / right of the label instead of overlapping all the time 👍

Add iconPosition property to touch bar buttons

---

docs/faq.md

Fix the most horrible typo of all time

Fix a typo in faq.md

---

docs/tutorial/desktop-environment-integration.md

Updated documentation on desktop notifications on Windows 7

---

docs/api/menu-item.md

Fix typos in MenuItem docs

---

docs/api/touch-bar.md

Add a simple example of running the example code as it might not be obvious to people who've not used Electron. Hopefully it makes sense :-)

Show how to run the example in touch-bar.md

---

README.md
docs-translations/es/project/README.md
docs-translations/ko-KR/project/README.md
docs-translations/pt-BR/project/README.md
docs-translations/tr-TR/project/README.md
docs-translations/zh-CN/project/README.md
docs-translations/zh-TW/project/README.md

I will update all links to turkish community with auto invite link, this is better.

add auto-invite for turkish community(en-readme)

---

docs/api/ipc-main.md

:memo: minor docs copy edit - add two words

---

docs/tutorial/quick-start.md

It was previously inconsistent

Fix order of OSs

---

docs/api/browser-view.md
docs/api/structures/memory-info.md

Covers a few of the things mentioned in https://github.com/electron/electron-typescript-definitions/issues/39

Minor typescript fixes

---

docs/api/browser-view.md

Fix webcontents capital

---

docs/api/native-image.md

Fix createFromDataURL return type

---

script/lib/config.py

Pulls in the following:
- https://github.com/electron/libchromiumcontent/pull/291
- https://github.com/electron/libchromiumcontent/pull/293

Upgrade libchromiumcontent

---

docs/api/ipc-main.md

Docs: Remove optional parameter for removeAllListeners.

---

atom/browser/net/url_request_fetch_job.cc
atom/browser/net/url_request_fetch_job.h
brightray/browser/browser_context.cc
brightray/browser/browser_context.h
brightray/browser/url_request_context_getter.h

Reverting https://github.com/electron/electron/pull/9358 for now, will reopen #9342
/cc @deepak1556 
Closes #9587

Revert #9358

---

docs/api/cookies.md

Fix typings for cookies.get

---

lib/browser/chrome-extension.js

Use Buffer.from instead of deprecated new Buffer.

Use Buffer.from instead of deprecated new Buffer

---

docs/api/session.md

Make clearStorageData options object's property optional

---

docs/tutorial/planned-breaking-changes.md

Should use `hiddenInset` instead.

Add titleBarStyle: 'hidden-inset' to planned breaking changes

---

brightray/brightray.gypi
script/create-dist.py

This addresses #9443 
Depends on [libchromiumcontent#312](https://github.com/electron/libchromiumcontent/pull/312)

Use dynamic CRT in the release build

---

docs/api/web-contents.md
docs/api/webview-tag.md

Fixes electron/electron-typescript-definitions/issues/63

Fixes electron/electron-typescript-definitions/issues/63

---

docs/tutorial/application-distribution.md

That thing is deprecated for _sure_

Remove grunt-build-atom-shell

---

docs/tutorial/keyboard-shortcuts.md

A small bit of documentation from https://github.com/electron/electron/issues/7737#issuecomment-310920444
cc @poiru

recommend before-input-event in keyboard shortcuts tutorial

---

docs/api/crash-reporter.md

Props to @zombieleet for noticing it.

fix crash reporter typo

---

docs/api/ipc-renderer.md

Fixes https://github.com/electron/electron/issues/9775

document the return value of ipcRenderer.sendSync

---

atom/app/atom_main_delegate.cc
atom/browser/api/atom_api_app.cc
atom/browser/api/atom_api_app.h
atom/browser/web_contents_preferences.cc
atom/common/options_switches.cc
atom/common/options_switches.h
atom/renderer/atom_sandboxed_renderer_client.cc
docs/api/app.md
docs/api/sandbox-option.md
lib/sandboxed_renderer/init.js
spec/api-app-spec.js
spec/api-browser-window-spec.js
spec/fixtures/api/mixed-sandbox-app/electron-app-mixed-sandbox-preload.js
spec/fixtures/api/mixed-sandbox-app/main.js
spec/fixtures/api/mixed-sandbox-app/package.json

Enable sandbox on webview

---

spec/chromium-spec.js
spec/fixtures/module/preload-pdf-loaded.js

Pulls in https://github.com/electron/pdf-viewer/pull/3

Upgrade to electron/pdf-viewer@beb36874a6b

---

atom/browser/api/atom_api_web_contents.cc
atom/browser/api/atom_api_window.cc
atom/browser/ui/autofill_popup.cc
atom/browser/ui/views/autofill_popup_view.cc
atom/browser/ui/views/autofill_popup_view.h
electron.gyp
features.gypi
filenames.gypi
script/update.py
spec/api-browser-window-spec.js

It would be great to have an ability to turn certain features off for custom builds.
It could also help with upgrades to new Chromium versions.
**Issue to address**:
Disable the tests if the flag is turned off.

[WIP] Add enable_osr flag

---

docs-translations/fr-FR/tutorial/electron-versioning.md
docs-translations/fr-FR/tutorial/quick-start.md
docs-translations/fr-FR/tutorial/security.md
docs-translations/fr-FR/tutorial/supported-platforms.md

Hello there,
When I was reading the french documentation, I noticed some mistakes, so here is a PR proposes to fix it. I might have missed some, but I think it's still better ! 😄

Fix french language mistakes in documentation

---

docs/glossary.md

add OSR to glossary

---

docs/api/auto-updater.md

We should point people to electron-forge, it's the modern way to package Electron apps

Recommend electron-forge in auto-updater, fix some Windows stuffs

---

docs-translations/pt-BR/api/browser-window.md
docs-translations/pt-BR/api/synopsis.md
docs-translations/pt-BR/development/build-instructions-linux.md
docs-translations/pt-BR/development/coding-style.md
docs-translations/pt-BR/development/source-code-directory-structure.md
docs-translations/pt-BR/project/CODE_OF_CONDUCT.md
docs-translations/pt-BR/styleguide.md
docs-translations/pt-BR/tutorial/accessibility.md
docs-translations/pt-BR/tutorial/application-packaging.md
docs-translations/pt-BR/tutorial/desktop-environment-integration.md
docs-translations/pt-BR/tutorial/security.md
docs-translations/pt-BR/tutorial/supported-platforms.md
docs-translations/pt-BR/tutorial/using-native-node-modules.md
docs-translations/pt-BR/tutorial/using-pepper-flash-plugin.md

All the documents on `\docs-translations\pt-BR\*` verified
Wrong words | Correct words |
-|-|
extenção | extensão |
possiblidade | possibilidade |
criar uma nova | criar uma |
pra | para |
renderizaçãp | renderização |
incluíndo | incluindo |
rendezição | renderização |
nivel |  nível |
incluisiva | inclusiva |
politicos | políticos |
permamentemente | permanentemente |
comprir | cumprir |
for (EN) | para o  |
descompacatar | descompactar |
aplicacões | aplicações |
binarios | binários |
construidos | construídos |
Atencão | Atenção |
construidas | construídas  |
construido | construído |
distruibuicão | distruibuição |
construcão | construção |
blibliotecas | bibliotecas |
contruídas | contruídas |
Igonorando | Ignorando |
probema | problema |
locamente | localmente |
opçao | opção | …

[docs-translations] Correct words in PT-BR

---

docs/api/file-object.md

So If you do not care bubbling equally, I think it should change like this.

this code is not care a bubbling event

---

docs/tutorial/windows-store-guide.md

Another typo found by @Toinane while translating.

fix typo in windows store guide

---

docs-translations/jp/README.md
docs-translations/jp/tutorial/keyboard-shortcuts.md

translate tutorial/keyboard-shortcuts.md to Japanese 🇯🇵

translate keyboard shortcuts doc to japanese

---

atom/browser/api/atom_api_browser_view.cc
docs/api/browser-view.md
spec/api-browser-view-spec.js

#10039 add BrowserView.fromId

---

docs/api/browser-window.md

See https://github.com/electron/electron-typescript-definitions/issues/25

Allow TypeScript definitions work with strictNullChecks

---

package.json

Reverts electron/electron#10250
See #10265

Revert "remove no-op preinstall script"

---

atom/browser/native_window_mac.h
atom/browser/native_window_mac.mm

Fix compilation on mac

---

docs-translations/fr-FR/tutorial/quick-start.md

Also fix some grammar and typing mistakes.
[ci skip]

:memo: Fix markdown syntax

---

atom/browser/api/atom_api_web_contents.cc
atom/browser/api/atom_api_web_contents.h

It would allow for some interesting things, let's keep it a private API first.

Add WebContents.getNativeView() API

---

Dockerfile
atom/app/atom_main.cc
atom/browser/api/atom_api_web_contents.cc
atom/browser/ui/views/menu_delegate.cc
atom/browser/ui/views/menu_delegate.h
atom/common/api/event_emitter_caller.cc
atom/renderer/atom_sandboxed_renderer_client.cc
brightray/brightray.gypi
chromium_src/chrome/browser/media/native_desktop_media_list.cc
script/cibuild-linux
spec/api-app-spec.js
spec/api-browser-window-spec.js
spec/api-web-contents-spec.js

See https://github.com/electron/libchromiumcontent/pull/345

Re-enabled debug mode

---

docs/api/ipc-renderer.md

Mark channel as non-optional in ipcRenderer

---

docs/development/releasing.md

wrote this last week and forgot to make a PR of it.

add more releasing tips

---

docs/api/desktop-capturer.md

Based on MDN example:
https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia#Examples

📝 Fix desktopCapturer example

---

docs/api/crash-reporter.md
docs/api/web-request.md

Fixes https://github.com/electron/electron-typescript-definitions/issues/75
/cc @bpasero

Mark filters as optional inside webRequest

---

atom/browser/ui/cocoa/atom_menu_controller.mm
docs/api/menu-item.md

:apple: Add roles for macOS native tab menu items

---

atom/browser/api/atom_api_web_contents.cc
docs/api/web-contents.md
spec/api-web-contents-spec.js

fixes #10240
A followup PR from #10247

return null when theme color is transparent or not found

---

atom/browser/api/atom_api_window.cc
atom/browser/api/atom_api_window.h
atom/browser/native_window.cc
atom/browser/native_window.h
atom/browser/native_window_mac.h
atom/browser/native_window_mac.mm
docs/api/browser-window.md
spec/api-browser-window-spec.js

Adds methods to the Window object allowing control of macOS native tab functionality.

:apple: Add macOS native tab methods to window API

---

docs/api/touch-bar.md

Just fix the word "directory" in the Touch Bar API docs! :)

Fix word in documentation

---

atom/browser/api/atom_api_app.cc

It was using a branch that had been deleted.

Update libcc to latest

---

atom/browser/mac/atom_application_delegate.mm

I patch the fix from 
https://chromium.googlesource.com/chromium/src.git/+/9984518a9c261026b5d2c4b82c7fd7372a06f1c2
https://chromium.googlesource.com/chromium/src.git/+/1eb85221f8f0805a5172ea603dddc706fd4d90a4
And it works!
Fix the issue https://github.com/electron/electron/issues/7551

fix mac ime crack

---

docs/api/sandbox-option.md

docs: fix examples for sandbox

---

docs/api/touch-bar-button.md

It seems like this property can be optional.

Docs: set iconPosition as optional

---

docs-translations/ko-KR/api/browser-window.md
docs-translations/pt-BR/api/browser-window.md
docs-translations/zh-CN/api/browser-window.md

More details: https://github.com/electron/electron/commit/8d3e09747a778b54317c9446f9da6db2fa27c1bd

Remove non-existent option

---

docs/api/web-request.md

Update the `web-request.md` to follow up the changes https://github.com/electron/electron/commit/2048a1a638cbba8903052087dc50b3345d3e358c recently made. Some typos were revised as well.

docs: update web-request.md

---

docs/glossary.md

add clarification about main process

---

lib/browser/api/auto-updater/auto-updater-win.js
lib/browser/api/auto-updater/squirrel-update-win.js

This cherry-picks #10483 to fix #5057.
cc @zcbenz

Use Squirrel.Windows --checkForUpdate (1.7.x)

---

lib/browser/api/auto-updater/auto-updater-win.js
lib/browser/api/auto-updater/squirrel-update-win.js

This cherry-picks #10483 to fix #5057.
cc @zcbenz

Use Squirrel.Windows --checkForUpdate (1.6.x)

---

.circleci/config.yml
spec/package.json
spec/static/index.html

Fixes running release builds in CircleCI
Enables better reporting on tests in CircleCI

CircleCI updates

---

docs/development/releasing.md

Minor doc change to point to correct CI locations

Update CI information

---

.github/stale.yml
CONTRIBUTING.md

let's talk about what we'd like to implement around marking and closing stale issues!

add initial file for stale bot

---

.circleci/config.yml
spec/package.json
spec/static/index.html

Improve CircleCI test results for 1-7-x

CircleCI report testing results

---

spec/api-browser-window-spec.js

Newly added test was leaving window open causing tests to fail.
Fixes #10685

Fix failing tests on master

---

brightray/browser/win/win32_desktop_notifications/common.h
brightray/browser/win/win32_desktop_notifications/desktop_notification_controller.cc

Fixed font DPI scaling

---

docs/development/build-instructions-windows.md

The previous link pointed to VS 2017 download location.

:memo: Updated with link to VS 2015

---

docs-translations/zh-CN/tutorial/notifications.md

Add notifications.md file in Chinese

Add notifications.md file in Chinese

---

docs/tutorial/accessibility.md

`thrid-party` => `third-party`

Fixed typo

---

docs-translations/zh-CN/styleguide.md

Add a little translation for zh-CN

Add a little translation for zh-CN

---

docs-translations/tr-TR/project/README.md

[docs] [tr-TR] Update README.md

---

spec/api-clipboard-spec.js
spec/api-crash-reporter-spec.js
spec/api-debugger-spec.js
spec/api-deprecations-spec.js
spec/api-desktop-capturer-spec.js
spec/api-global-shortcut-spec.js
spec/api-process-spec.js
spec/api-screen-spec.js
spec/api-system-preferences-spec.js
spec/api-touch-bar-spec.js

Remove all relics of older nonstandard code in the smaller specs in the first few steps of the testing suite improvement process.
Upgraded:

[WIP] Upgrade specs

---

spec/api-protocol-spec.js

Upgrade earlier tests in protocol module to match ES6 style of later tests added in `api_protocol_spec.js`
/cc @zeke

Upgrade protocol spec

---

docs/api/browser-window.md
spec/api-browser-view-spec.js

The code is already there, it just wasn't documented or tested.
Fixes #10921

Document and test `getBrowserView`

---

spec/api-app-spec.js
spec/api-ipc-spec.js
spec/api-menu-spec.js
spec/api-net-spec.js
spec/api-protocol-spec.js
spec/api-session-spec.js
spec/api-web-contents-spec.js
spec/api-web-request-spec.js
spec/chromium-spec.js
spec/modules-spec.js
spec/node-spec.js
spec/webview-spec.js

More progress in updating old specs before beginning to add new tests.
Upgraded:

Finish upgrading specs to ES6

---

atom/browser/api/atom_api_notification.cc
atom/browser/api/atom_api_notification.h
docs/api/notification.md

Close the previous notification on multiple calls to show

---

spec/api-browser-window-spec.js
spec/api-shell-spec.js

Typed app, meant shell, whoops. 
Upgraded last two specs to ES6.

convert shell and browser spec to ES6

---

spec/api-browser-window-spec.js

Task to enable them:
https://github.com/electron/electron/issues/10988

Temporary disable "document.visibilityState/hidden" tests

---

spec/api-crash-reporter-spec.js

It appears the timeout issues was only apparent in my other branch; i removed it here and all tests are well and green again in that module :)
/cc @alexeykuzmin @ckerr

remove function invocation from crash test

---

docs/api/browser-window.md

I know, silly to make a PR for one character, but also silly to leave it in.

fix: One-character typo change

---

package.json

Needed for electron/electron-typescript-definitions#80

Upgrade electron-typescript-definitions to latest

---

atom/browser/ui/cocoa/touch_bar_forward_declarations.h

Forward declare the scrubber layout

---

README.md

Meetup Group doesn't exist.
https://www.meetup.com/electron-kr/

Deleted Korean Community

---

README.md

Korean Community was Pull Request #10997.
But There is a Korean Community in Slack!
So I Added it.

Add Korean Community
